### ISSUE TITLE
APP Crashes when adding a GroundOverlay GIF or PNG Transparent

### ISSUE THREAD

**Issue by lasdou** [mapsplugin/cordova-plugin-googlemaps#1000]
Hello,

i am trying to add a transparent groundOverlay over my map but it does not works. When i try with a jpeg image wich is not transparent it works.

Here is an example with a transparent image wich will produce a crash. Map is correctly loaded but when groundOverlay is instanciate, the app crash and close :-(

```
const US_CENTER = new plugin.google.maps.LatLng(37.674858,-89.927734);
var div = document.getElementById("map_canvas");
map = plugin.google.maps.Map.getMap(div, {
	  'backgroundColor': 'white',
	  'mapType': plugin.google.maps.MapTypeId.TERRAIN,
	  'controls': {
		'compass': true,
		'myLocationButton': true,
		'indoorPicker': true,
		'zoom': true
	  },
	  'gestures': {
		'scroll': true,
		'tilt': true,
		'rotate': true,
		'zoom': true
	  },
	  'camera': {
		'latLng': US_CENTER,
		'zoom': 4,
	  }
});
      // Wait until the map is ready status.
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
}, false);

function onMapReady() {

   var swBound = new plugin.google.maps.LatLng(21.6,-127.778721);
   var neBound = new plugin.google.maps.LatLng(50.495006,-66.475537); 
	
    var bounds = [swBound, neBound];
    map.addGroundOverlay({
	  'url': 'http://www.chasing-live.net/RainUS00.png',
	  'bounds': bounds,
	  'opacity': 1
	}, function(groundOverlay) {
	    alert('addGroundOverlay ok');
	});		
}
```

Thanks for your help

**Comment by wf9a5m75** [comment]
Use the opacity property instead of the transparent image.

**Comment by lasdou** [comment]
It 's not a solution. The result of your suggestion will be awful.

I need to use transparent images for my app. I don't understand why it is
not supported by the plugin.

A correct patch would be appreciate.

Thank you very much.
Le 15 juin 2016 04:44, "Masashi Katsumata" <notifications@github.com> a
écrit :

Use the opacity property instead of the transparent image.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1000#issuecomment-226073921>,
or mute the thread
<https://github.com/notifications/unsubscribe/AC_7jXz48Xk8BmvnCouXfEmg7ViKyS-5ks5qL2cdgaJpZM4I1z6_>
.

**Comment by wf9a5m75** [comment]
Sorry for long-time waiting.
The point is your image file is **too large**.

Even I tested with the v2-beta version, the image file is too large.
Reduce the image size (width, height, convert to GIF).

**Don't forget, the mobile phones don't have large memory like desktop PC**

**Comment by KimberleeDArmstrong** [comment]
I am having the same problem.  I was able to overlay this exact transparent png in my app using google javascript api but in the app with this plugin, it crashes the app.  I am trying to see if the server can generate a gif instead.
