### ISSUE TITLE
Problem with Duplicate entry (gradle)

### ISSUE THREAD

**Issue by lucasgalli** [mapsplugin/cordova-plugin-googlemaps#1002]
when i install the plugin for cordova and then cordova run android, show this error:

Error:Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/iid/zzb$zza$zza.class
![erro](https://cloud.githubusercontent.com/assets/11078696/16081472/f05ea44a-32e3-11e6-9414-841536dd3a06.PNG)

**Comment by wf9a5m75** [comment]
Please adjust by your hand if you conflict with other plugins.

**Comment by lucasgalli** [comment]
I uninstalled all plugins and i installed just the cordova-plugin-googlemaps to test, the same problem....

**Comment by wf9a5m75** [comment]
This plugin requires `com.google.android.gms:play-services-maps:+` definitely. 
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L46-L47

I don't know which library or plugin conflict with this plugin, but no other people has your error (at least I can not reproduce your issue).

Please create very simple project following this tutorial.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Mac
