### ISSUE TITLE
Close button doesn't work

### ISSUE THREAD

**Issue by brisa-pedronetto** [mapsplugin/cordova-plugin-googlemaps#1003]
Hello guys, have you had this issue? The close button on the grey bar on the bottom simply doesn't work, so I can't get back to my app after opening a map.

Thank you!

**Comment by wf9a5m75** [comment]
Um, is there any log in native side?

**Comment by brisa-pedronetto** [comment]
Unfortunately no :( Nothing in ADB or Xcode.
