### ISSUE TITLE
Screen blink on map ready

### ISSUE THREAD

**Issue by ecorona** [mapsplugin/cordova-plugin-googlemaps#1004]
The screen blinks on map ready, is there any way to avoid this?

Thanks

**Comment by wf9a5m75** [comment]
Please check you API key.

**Comment by ecorona** [comment]
The api key is not the issue, the map fully loads but just a few milisecs before the "map ready" event the screen flicks.

**Comment by wf9a5m75** [comment]
Please provide the screen record (video) and the native log. Without these information, I can not debug for you.

**Comment by ecorona** [comment]
I will, but you must know the map container div is hidden at the time the map ready event fires (a loading div is showing).

Will post the video and log later.

**Comment by wf9a5m75** [comment]
>the map container div is hidden at the time the map ready event fires (a loading div is showing).

Please provide enough information (such a hint, code example, or test repository...etc) from the first time to debug smoothly.
