### ISSUE TITLE
Show google map into gray scale Android and IOS

### ISSUE THREAD

**Issue by kamal250** [mapsplugin/cordova-plugin-googlemaps#1005]
I am using cordova google map plugins in my app. I have already a working map with use of this plugin.

I have also shown multiple markers with using this plugins.

Now the problem is i want to show the map into gray scale.

Here is the code.

```js
function onDeviceReady() {
    var mapDiv = document.getElementById("map_data");

    const
    GOOGLE = new plugin.google.maps.LatLng(51.1247804, 4.2123471);
    map = plugin.google.maps.Map.getMap(mapDiv, {
        'camera' : {
            'latLng' : GOOGLE,
            'zoom' : 12
        },
        'backgroundColor': 'white'
    });

    map.addEventListener(plugin.google.maps.event.MAP_READY, function() {

        map.addMarker({
            'position' : GOOGLE
        }, function(marker) {

            marker.showInfoWindow();

        });

    });
}
```

For markers.

```js
function addMarkers(data, callback) {

    var markers = [];
    function onMarkerAdded(marker) {
        markers.push(marker);
        if (markers.length === data.length) {
            callback(markers);
        }
    }
    data.forEach(function(markerOptions) {
        map.addMarker(markerOptions, onMarkerAdded);
    });
}
```

**_Now my problem is_** : I want to convert this map to gray scale using the same plugin. How can i integrate gray scale to this map ? I have searched a lot but not be able to find out any solutions.

Any help will be greatly appreciated

**Comment by wf9a5m75** [comment]
Um, I can not understand your question clearly.
What do you mean the `gray scale`?
Could you show me with any picture?

**Comment by kamal250** [comment]
Thanks for your reply. Yes i can show you with screen shot. Actually i want to set map's background to Gray Scale. Here i am attaching demo screen shot what exactly i want in my app. Actually i have already integrated google map with this plugin and shown multiple marker i just wanted to convert it to Gray Scale. i just want to know is it possible with this plugins or not ?

![image_v8](https://cloud.githubusercontent.com/assets/5698578/16329834/a27f4722-3a02-11e6-853c-de3c30ada5e6.png)

**Comment by celron** [comment]
As you may know, Google maps allows styling with html and javascript libraries, however they have not provide support in either Android or iOS libraries.  As this plugin relies on the underlying Google libraries, there is no way for it to support styling the map.

**Comment by Hirbod** [comment]
c
