### ISSUE TITLE
Has anyone been getting the following error while using the plugin with ionic-native

### ISSUE THREAD

**Issue by GuelorEmanuel** [mapsplugin/cordova-plugin-googlemaps#1008]
[console.error] Error: [$injector:unpr] Unknown provider: GoogleMapProvider <- GoogleMap <- RegularHomeController

**Comment by wf9a5m75** [comment]
I can not understand what is wrong.
I'm not familiar with ionic.

**Comment by mhfen** [comment]
@GuelorEmanuel 

The ionic-native library is a set of wrappers for already developed cordova plugins like this one, so any issue with an API into the ionic-native library is an issue for the Ionic team. You could post it in their Github Issues area.

**Comment by GuelorEmanuel** [comment]
@mhfen 
Thanks, the problem was with the way I was using ionic native. The problem is resolved now, thanks.
