### ISSUE TITLE
[iOS] Snippet is ignoring my \n on the infoWindow

### ISSUE THREAD

**Issue by yupswing** [mapsplugin/cordova-plugin-googlemaps#1009]
I think it is a simple bug, but in the "snippet" properties of a marker if I put \n it work on Android (goes to a new line) but NOT in iOS.

**Comment by roblav96** [comment]
I can confirm this issue.

**Comment by longzheng** [comment]
Can also confirm. I think the Google Maps iOS doesn't actually support newlines.

**Comment by wf9a5m75** [comment]
Please use the HtmlInfoWindow class of the v2.0.
The default infoWindow of this plugin is not deprecated yet, but HtmlInfoWindow has more flexibility.

**Comment by topless** [comment]
@wf9a5m75 it probably doesn't belong to the topic, I can always create a new one, but I am trying the htmlInfoWindow with the version 2 of the maps and it doesn't seem to render html, it just spits out plain text. If I can be help of any kind, please guide me :)

**Comment by wf9a5m75** [comment]
Please read the document.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/HtmlInfoWindow/newHtmlInfoWindow/README.md

**Comment by wf9a5m75** [comment]
@topless please make another issue if you still have a problem. I close this issue
