### ISSUE TITLE
Header bar clicks passing to map div

### ISSUE THREAD

**Issue by husmen73** [mapsplugin/cordova-plugin-googlemaps#1010]
I have header bar and map which has static height.

First image:
![1](https://cloud.githubusercontent.com/assets/222654/16257871/b40eb9f0-3863-11e6-9e7b-8493c5fa57ad.jpg)

Second image:
![2](https://cloud.githubusercontent.com/assets/222654/16257870/b3db81f2-3863-11e6-9c8e-b81388f4d1ba.jpg)

There is an setClickable() function but how can I use it when page scrolled to bottom if map div goes to under header bar.

I could not find to solve this problem.

**Comment by wf9a5m75** [comment]
Um, in current mechanism, this plugin does not support z-index property.
It means this plugin does not design for this case.

**Comment by husmen73** [comment]
Okay. This is a problem for me. Will you write some code about z-index for newer versions?

Also, you should merge clusters from this fork : https://github.com/identy/cordova-plugin-googlemaps

**Comment by wf9a5m75** [comment]
Sorry, but detecting z-index is difficult for this plugin.
And I don't merge any pull requests at this time.
The source code of this plugin will be changed drastically in next version.

**Comment by douglasjunior** [comment]
I have a similar problem, could you tell me if it's related?

If open a HTML Popup (dialog) over the map, the touch events is not captured by Popup, but by the map.

![captura de tela 2016-07-29 as 09 31 45](https://cloud.githubusercontent.com/assets/1512341/17248224/85012976-556f-11e6-8835-fdb74cfb95e0.png)

Same problem if the header bar is over the map.

![captura de tela 2016-07-29 as 09 32 01](https://cloud.githubusercontent.com/assets/1512341/17248329/311aca64-5570-11e6-9c7b-6566c9ea7a59.png)

It happens both Android and iOS. With JavaScript maps I had no problems.

_Ionic 1.7.16
Cordova 6.3.0
cordova-plugin-googlemaps 1.3.9_

**Comment by wf9a5m75** [comment]
```map.setClickable(true/false)```

**Comment by douglasjunior** [comment]
I was hiding the map with `ng-hide` (I believe it is the same effect).

The problem is the second question, where is the scroll.

How do I know if the map is behind the Header Bar and then disable the click?

**Comment by wf9a5m75** [comment]
As I said above, the plugin does not support the fixed header (because z-index does not support) currently.

The plugin considers the child elements, but other elements are not.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/googlemaps-cdv-plugin.js#L334-L361

**Comment by douglasjunior** [comment]
Got it. Thank you.

**Comment by wf9a5m75** [comment]
Sorry

**Comment by douglasjunior** [comment]
Guys, I found a solution that worked for me.

If the user schrolls the screen I lock the map: `map.setClickable(false)`

So, when the user touchs on map, I scroll the screen to top: `$ionicScrollDelegate.scrollTop()`

My View:
```html
<ion-view view-title="Coordinates" >
  <ion-content class="padding" on-scroll="onScroll()"  >
      ...
      <div id="map" on-touch="onMapTouch($event)" style="width: 100%;" ></div>
      ...
  </ion-content>
</ion-view>
```

My Ctrl:
```javascript
app.controller('CoordinatesCtrl', function($scope, $ionicScrollDelegate, $ionicGesture) {

  $scope.onScroll = function(){
    console.log("onScroll positon: " + $ionicScrollDelegate.getScrollPosition().top);
    if ($ionicScrollDelegate.getScrollPosition().top <= 35) {
      $scope.map.setClickable(true);
    } else {
      $scope.map.setClickable(false);
    }
  }

  $scope.onMapTouch = function(event){
    $ionicScrollDelegate.scrollTop();
  }

});
```

**Comment by yurik94** [comment]
@douglasjunior You're a life saver.
