### ISSUE TITLE
Support for languages other than English

### ISSUE THREAD

**Issue by skirsche** [mapsplugin/cordova-plugin-googlemaps#1012]
There are hard-coded strings that are shown to the user. One example is the message "This app needs access to your location. Please turn on Location Services in your device settings." in GoogleMaps.m. 

Is there currently a way to localize these strings? If not, is there a plan to fix it?

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/GoogleMaps.m#L590

![screenshot](https://cloud.githubusercontent.com/assets/10923/16271773/8f93cb28-389b-11e6-89b4-06b393a76f46.png)

**Comment by wf9a5m75** [comment]
Please send me a pull request.
