### ISSUE TITLE
marker.isInfoWindowShown just makes marker visible

### ISSUE THREAD

**Issue by MortezaT** [mapsplugin/cordova-plugin-googlemaps#1013]
There is a problem with this method on a marker with hidden info, that when you want to check if it's visible it'll shows the info and then returns true.

**Comment by wf9a5m75** [comment]
Please post with test code.

**Comment by MortezaT** [comment]
Actually after encountered the error I changed my code.
So for now I have this code:

`marker.isInfoWindowShow(shown => shown? marker.hideInfoWindow(): marker.showInfoWindow());`

I tried to toggle info window by clicking on marker but the result was if it's open then close and if closed , open it for a bit (this was because of isInfoWindowShown) and after a blink of eye it hides again ( the value of shown is always true so the function hides the info window).

**Comment by wf9a5m75** [comment]
Um, the infoWindow is toggled clicking on the marker is default action.
So I think you don't need this code.

**Comment by MortezaT** [comment]
Is there anyway to disable this default?

Do you have any gitter (or similar live chat channel) to answer questions?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#disable-auto-pan

**Comment by MortezaT** [comment]
@wf9a5m75 This is about auto pan, not show the title.

**Comment by wf9a5m75** [comment]
Ok, your snippet code is not enough to test.
Please provide whole example code, and provide a screen recode(video).

**Comment by wf9a5m75** [comment]
This is fixed in the v2-beta version.
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Marker/isInfoWindowShown.html

Try the new version please.
https://github.com/mapsplugin/v2.0-demo/
