### ISSUE TITLE
Google Maps API error: MissingKeyMapError

### ISSUE THREAD

**Issue by oorodong** [mapsplugin/cordova-plugin-googlemaps#1014]
Has anyone get this problem,,

Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

**Comment by AvBrocklehurst** [comment]
We're also getting that, I imagine it's to do with - http://googlegeodevelopers.blogspot.co.uk/2016/06/building-for-scale-updates-to-google.html

**Comment by AvBrocklehurst** [comment]
Ours was caused by having <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script> still in the head of our index.html file. To fix it you can either remove the script or change it to <script src="http://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&sensor=false"></script>

**Comment by wf9a5m75** [comment]
>We're also getting that, I imagine it's to do with - http://googlegeodevelopers.blogspot.co.uk/2016/06/building-for-scale-updates-to-google.html

This is not affect to this plugin. The article is written for the Google Maps JavaScript API v3, not for Google Maps Android API v2 and Google Maps SDK for iOS.

**Comment by wf9a5m75** [comment]
This plugin does not use Google Maps Javascript API v3.
If you use it with this plugin, you have to be charge of everything about it.
This issue is not related with this plugin.
