### ISSUE TITLE
Sidemenu Ionic 2

### ISSUE THREAD

**Issue by rigobcastro** [mapsplugin/cordova-plugin-googlemaps#1019]
Hi there,

The map is wonderful but this doesn't work with the SideMenu in ionic 2. 

Thanks for any solution!

Note: The solution for Ionic 1 is not useful for Ionic 2.

**Comment by ZiFFeL1992** [comment]
@rigobcastro did you use `map.setClickable(false|true)` when triggering the menu?

**Comment by rigobcastro** [comment]
@ZiFFeL1992 I don't. How I can get the map instance outside of map page?

Another problem, the map is not deleted when changing to other pages

Thanks!

**Comment by wf9a5m75** [comment]
You need to remove the map by yourself using `map.remove()`

**Comment by rigobcastro** [comment]
@wf9a5m75 Ok thanks, I need to know how I can get the map instance after of init

**Comment by wf9a5m75** [comment]
```js
var map = plugin.google.maps.Map.getMap(mapDiv);
```

The above code is only way to get the map instance.

**Comment by mhfen** [comment]
@rigobcastro Your issues can be solved by controlling all map functions from a provider (aka service) in your Ionic2 app.

`ionic generate provider map-service`

Make sure that provider is bootstrapped through the App component so it lives across the entire life of the application. Then any page or component can import the MapService and call its methods. You won't need to ever remove the app (the instance will just keep on living once created), you can just toggle the clickability of the map as you enter and exit the map view.

**Comment by GuiCarneiro** [comment]
You could also change which kind of map you're using.

I changed my to reveal and it worked ;D
