### ISSUE TITLE
Does the plugin support the  event change of bouding box ?

### ISSUE THREAD

**Issue by alessandrogurgel** [mapsplugin/cordova-plugin-googlemaps#1020]
My company is studing this plugin in order to create a mobile app to trach vehicles in a company fleet. 

In our web system, we load the vehicles according to their position and the bounding box of the map viewport. 

I reade the plugin docummentation and I found that It is not support drag events, but it is not clear if there is a way to bind every time a map has its bounding box changed. Thus, I would like if this plugin (and Googe native SDK) provides support for change viewport events on google map.

**Comment by wf9a5m75** [comment]
CAMERA_CHANGE event.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#listen-events

**Comment by alessandrogurgel** [comment]
Thank you.
