### ISSUE TITLE
marker.remove callback is not executing.

### ISSUE THREAD

**Issue by ecorona** [mapsplugin/cordova-plugin-googlemaps#1021]
marker.remove callback is not executing.

**Comment by wf9a5m75** [comment]
Please ``always`` post more information, such as Android or iOS, example code, and native logs.

**Comment by kozuch** [comment]
This is true - at least for v1.4.0 (v2.0 not tested) indeed the marker.remove callback seems not to be executed. The docs do not mention the callback but in googlemaps-cdv-plugin.js there is a callback argument used - I have no idea whether it is meant to actually be working... but seems like a standard cordova.exec callback, the question is whether the callback is being invoked in java actually - one should inspect plugin/google/maps/PluginMarker.java remove method to see the reality.

The docs for 2.0 do not mention marker.remove callback either.

**Comment by wf9a5m75** [comment]
No longer support for v1.x

**Comment by wf9a5m75** [comment]
And no callback for `marker.remove()` for v2.0
