### ISSUE TITLE
Autocomplete for places and addresses

### ISSUE THREAD

**Issue by GuelorEmanuel** [mapsplugin/cordova-plugin-googlemaps#1027]
Any chance of adding autocomplete for searched terms? As shown here https://developers.google.com/maps/documentation/javascript/places-autocomplete #

**Comment by masashiGMS** [comment]
No enough time at this time. Sorry.

**Comment by tjaartvdwalt** [comment]
@GuelorEmanuel, I think it should be possible to use the Javascript Places library directly to get autocompletion.

**Comment by braianj** [comment]
@tjaartvdwalt do you have any example?
I'm working with http://devfanatic.com/blog/blog/2015/11/03/google-places-autocomplete-with-ionic-framework/ but it's not working

**Comment by codegreenie** [comment]
This Plugin is very good but does not come with Auto-Complete. Can anyone recommend a cordova/phonegap autocomplete plugin. Thank you.
