### ISSUE TITLE
reverse geocoding using place_id?

### ISSUE THREAD

**Issue by tjaartvdwalt** [mapsplugin/cordova-plugin-googlemaps#1028]
Thanks for a great plugin.
Is it currently possible to use reverse geocoding using `place_id`?

**Comment by wf9a5m75** [comment]
Not available currently.

**Comment by tjaartvdwalt** [comment]
Ok thanks, 
In my case I was able to use the Javascript api to get the result, and then pass it back to the plugin.
If you want we can close this issue.
