### ISSUE TITLE
Not loading map

### ISSUE THREAD

**Issue by KproApps2** [mapsplugin/cordova-plugin-googlemaps#1032]
Seems to be not loading the map,

It is not loading the canvas nothing is appearing and no error?

**Comment by wf9a5m75** [comment]
More information, please.

**Comment by daCookieProject** [comment]
I m having the exact same issue, no errors, canvas doesnt load but google logo is shown on the bottom left of the screen. Running on android device 4.-

**Comment by wf9a5m75** [comment]
>but google logo is shown on the bottom left of the screen

The most of reasons are your api key is mismatch with your package name, or you forget to enable the Google Maps API Android v2 or the Google Maps SDK for iOS in the Google APIs Console.

**Comment by lentyaishe** [comment]
Same for me...
The canvas is always light grey, no map, has Google logo in the bottom left corner. No errors either.

Any clue or help will be much appreciated!

**Comment by glblabs** [comment]
Same problem.
I have already made more times:
SHA1 Finegerprint 
Generate API Key
Set Package Name

I can also handle events map (MAP_LONG_CLICK , MAP_CLICK, MAP_READY).
I'm going crazy.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map

**Comment by lentyaishe** [comment]
Hi,

Thanks a lot for your assistance...

Unfortunately "Blank map" troubleshooting page didn't help me much...
1. I do not use Android Studio. I'm using an Apache Cordova project in
Visual Studio.
2. Google Maps API Console now looks very different from your screenshots
and I can't find out how should I verify settings you mentioned at the
troubleshooting page in the new Google APIs UI.

It would be great if you could assist me with this.

Thanks a lot in advance,
Ilya

**Comment by lentyaishe** [comment]
Well, guys, I have a working solution.. :))

What you need is prepare your app for signing. [Here is the official Microsoft Visual Studio guide](http://taco.visualstudio.com/en-us/docs/tutorial-package-publish-readme/) for preparing your .apk for signing. The best way to check whether you completed the procedure correctly is compiling the release version of .apk and check whether in your < project_folder >\bin\Android\Release you get the android-release.apk.

Whenever this procedure will work correctly, the map will be displayed in the app..

So good luck for all!

**Comment by ovitrif** [comment]
I get the same issue on iPhones.

I see the markers on the map, the logo and the centering button, but the map is white-gray.

**Comment by wf9a5m75** [comment]
The map color is gray means your api key is incorrect.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map

**Comment by juanf9224** [comment]
I'm having the same issue too, its not loading, i have the api key right, sha1 fingerprint right, but the map just doesn't load, only this appears: 
![7961682608157261056-account_id 1](https://cloud.githubusercontent.com/assets/9439694/17816315/9d394bf2-6606-11e6-89e9-eb1287502cc0.png)
Apis are enabled, wich by the way were renamed to "Google Maps Android API" instead of "Google Maps Android API v2", you should update the docs.

PD: I'm using ionic 2.

**Comment by dahas** [comment]
Just an idea: But maybe it has to do with the "Content-Security-Policy" meta-tag? Do we have to add some domains here? 

I have the same problem,  but the more I try to fix it, the worse it gets. :-(

**Comment by b4tch** [comment]
I have just solved my "map not loading" issue - after trying I-don't-know-how-many-things, all it took was to add "background-color: #fff;" to #map_canvas in the CSS.  I have no idea why it worked, but it did!

**Comment by willgeiger** [comment]
Any other ideas on how to resolve this? I'm having the same problem (blank map, Google logo at bottom left) on Android. Chrome inspector shows no errors when I debug the map. I'm using the plugins below in my project. Could they be colliding?

https://github.com/mapsplugin/cordova-plugin-googlemaps
cordova-plugin-inappbrowser
cordova-plugin-device
cordova-plugin-statusbar
cordova-plugin-google-analytics
cordova-plugin-appavailability
cordova-plugin-x-socialsharing
cordova-plugin-calendar
cordova-plugin-splashscreen
cordova-plugin-whitelist
cordova-plugin-googleplayservices

**Comment by wf9a5m75** [comment]
>blank map, Google logo at bottom left

It means the plugin is correctly installed, but your API key is invalid.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map

**Comment by willgeiger** [comment]
Yes, wf9a5m75, that was it. I moved over to a new mac, and didn't realize I had to generate a new SHA-1 fingerprint. Thanks!

**Comment by wf9a5m75** [comment]
Sounds great:)

**Comment by YeisonVelez11** [comment]
@wf9a5m75  hi, The gray map happens to me. Only the google logo appears below. this is what I do:
I create the key:

http://prntscr.com/jnwecw

I do this command:

`cordova plugin add  cordova-plugin-googlemaps@2.3.2  --variable API_KEY_FOR_ANDROID="AIzaSyAn3En_YYR2AOFnHoRDWR-KYjifQ.."  --variable  API_KEY_FOR_IOS="AIzaSyASOO8LPnb54A6EyrYo8X9wuEPZv7.." --save
`
when compile the app for android, it works on my phone.
when compile the app for ios using the emulator... the screen is gray. What can I do? thanks!

**Comment by vijaystudio45** [comment]
@wf9a5m75 i have the same issue I troubleshoot with all the solutions but the same result and one thing more i don't find the Google map API for Android on the google console i think they have changed the library into Google Map Android SDK so please tell me how to resolve it?
