### ISSUE TITLE
Displaying map between overlayed content

### ISSUE THREAD

**Issue by nbdamian** [mapsplugin/cordova-plugin-googlemaps#1033]
I have 2 divs, one fixed at the top. As the user scrolls down, the bottom div overlays ontop of the top div.
The map is located in the middle on some content in bottom div.
Would it be possible to stop the map from displaying beneath the top div when the used scrolls?

Please see the attached screenshot for an example.

Also, each portion of the dom as a different background colour... Is it possible to adjust what is being set by the plugin?

![screenshot_20160721-081811](https://cloud.githubusercontent.com/assets/16768293/17001650/ff9528cc-4f1b-11e6-87e0-ce4e9475aae1.png)
![screenshot_20160721-081817](https://cloud.githubusercontent.com/assets/16768293/17001649/ff8f9808-4f1b-11e6-8e3c-bc39db33a83e.png)

**Comment by wf9a5m75** [comment]
The map is always located UNDER the browser.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#how-does-the-plugin-work

![68747470733a2f2f676f6f676c6564726976652e636f6d2f686f73742f304231454366715443634c45385230683654336449645746424f484d2f6d656368616e69736d2e706e67](https://cloud.githubusercontent.com/assets/167831/17003376/8f1289f6-4e84-11e6-9f97-e52a0259b62e.png)

**Comment by nbdamian** [comment]
So, I take that as it is impossible, and should just use the JavaScript API?

**Comment by wf9a5m75** [comment]
yes
