### ISSUE TITLE
Map works sometimes

### ISSUE THREAD

**Issue by chlamy** [mapsplugin/cordova-plugin-googlemaps#1034]
Hello,

I have an HTML page with api maps, and before change page I close it with function remove(). But when I return on the maps page, sometimes it works and sometimes I have white screen.

I have something like this :

```js
var map = null;
navigator.geolocation.getCurrentPosition(function(position){onSuccess(){
map = plugin.google.maps.Map.getMap(mapDiv,{
                'backgroundColor': 'white',
                'mapType': plugin.google.maps.MapTypeId.ROADMAP,
                'controls': {
                    'compass': false,
                    'myLocationButton': false,
                    'indoorPicker': false,
                    'zoom': false
                },
                'gestures': {
                    'scroll': true,
                    'tilt': true,
                    'rotate': true,
                    'zoom': false
                },
                'camera': {
                    'latLng': new plugin.google.maps.LatLng(position['lati'],position['longi']),
                    'zoom': 16
                }
            });
},onError);
```

**Comment by wf9a5m75** [comment]
Please provide a whole project that reproduce your issue on your repo.
I had no problem with this code.

**Comment by chlamy** [comment]
It works 3-4 first times, and if I stop few seconds before show map it works too. I think that it's a memory fail. 
All my code is in the before post.

**Comment by wf9a5m75** [comment]
In that case, the problem is in your app. There is no help I can do for you.
Please adjust your app by your self.

**Comment by wf9a5m75** [comment]
@chlamy I guess you probably don't need this information anymore, but I found similar case and fixed it.
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/d5213984e88ebccd4eb031420fcdb2f50e3a784c

So using the master branch, you probably don't face this issue anymore.
