### ISSUE TITLE
iOS: DOM Exception 25 while invoking getMap() with 2 arguments

### ISSUE THREAD

**Issue by arekKalbarczyk** [mapsplugin/cordova-plugin-googlemaps#1037]
Hi everyone!
So I got my map working pretty sweet when using only 1 param with DOM element. However, when I attempt to pass a second param, an object (taken from ur sample), then an error is thrown.

Using IONIC + ES6 here

```
ionic.Platform.ready(() => {
       const GORYOKAKU_JAPAN = new plugin.google.maps.LatLng(41.796875,140.757007);
       
       let div = document.getElementById("map_canvas");       
       vm.map = plugin.google.maps.Map.getMap(div, {
          'mapType': plugin.google.maps.MapTypeId.ROADMAP,
          'controls': {
            'compass': true,
            'myLocationButton': true,
            'indoorPicker': true,
            'zoom': true
          },
          'gestures': {
            'scroll': true,
            'tilt': true,
            'rotate': true,
            'zoom': true
          },
          'camera': {
            'latLng': GORYOKAKU_JAPAN,
            'tilt': 30,
            'zoom': 15,
            'bearing': 50
          }
        });

       vm.map.setClickable(vm.isMapClickAble);
    });
```

Error snippet:
```
Error: DataCloneError: DOM Exception 25
postMessage@[native code]
iOSExec@http://localhost:12344/cordova.js:979:58
getMap@http://localhost:12344/plugins/plugin.google.maps/www/googlemaps-cdv-plugin.js:359:17
(...)
```
Also, since am already opening a thread am gonna mention one more bug.
When I load map using only 1 param (DOM element), then it adds itself correctly, yet few bugs appear in the console:
`Error: undefined is not an object (evaluating 'O.searchInput.value')`
and
`undefined is not an object (evaluating 'callback.apply')` - this seems to be cause by addEventListener

Test device: iPhone 5c

**Comment by wf9a5m75** [comment]
Could you make a complete example project, and share it with your open repository?
I'm not familier with ionic.

And if you use this plugin with cordova-ios latest version, you have to use the master branch

**Comment by arekKalbarczyk** [comment]
Hey @wf9a5m75 
I have integrated your plugin into my project, it would be quite troublesome to separate this chunk of code. 
However, when I read through your docs, I've noticed something, namely when you create a `const` with location coordinates, using `new plugin.google.maps.LatLng` it actually constructs a whole object with various properties. 
This doesn't get recognized as a param for both markers and initial position of the camera. If you simply pass an object with only lat/lng.
small sample from me:
```
let map = plugin.google.maps.Map.getMap(mapDOMHandler, { 'camera': { 'latLng': { lat: 35.13, lng: 137.33 }}});
```
*`mapDOMHandler` is just a function callback that fetches my DOM element.

**Comment by wf9a5m75** [comment]
>getMap@http://localhost:12344/plugins/plugin.google.maps/www/googlemaps-cdv-plugin.js:359:17

Error occurred at line 358 (JS always report with next line).
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/googlemaps-cdv-plugin.js#L358

It says the getDivRect() expects a DOM element, not function.
