### ISSUE TITLE
[Android] Update <meta-data> name for key

### ISSUE THREAD

**Issue by douglasjunior** [mapsplugin/cordova-plugin-googlemaps#1038]
Today [Google Maps Android Guide](https://developers.google.com/maps/documentation/android-api/signup#add_the_api_key_to_your_application) recomends to use:

```xml
<meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR_KEY_HERE" />
```

Instead of:

```xml
<meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="YOUR_KEY_HERE" />
```

Basically change this line: [plugin.xml#L74](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/798fae18808940c4ede6de4182b37f3601f9c4d0/plugin.xml#L74)

Please, let me know if I can send a PullRequest.

**Comment by wf9a5m75** [comment]
Thank you for your information.
This one will apply to the next version (currently the multiple_maps branch)

**Comment by wf9a5m75** [comment]
I updated the plugin.xml files. Thanks for the information.
