### ISSUE TITLE
Google Maps offline areas are not involved

### ISSUE THREAD

**Issue by lentyaishe** [mapsplugin/cordova-plugin-googlemaps#1039]
Hi,

In my project I'm trying to find a cordova solution for offline maps and this plugin seems perfect since it uses the native Google Maps SDK. The problem is that this plugin does not involve Google Maps offline areas.

For instance:
1. I've downloaded an offline area via the Google Maps app using WiFi or mobile network.
2. Turned off the WiFi and mobile internet.
3. Opened my app that uses the cordova-plugin-googlemaps and tried to zoom in to the area that was downloaded by Google Maps app. I figured out that I can't. The data doesn't show.
4. Only when the WiFi or mobile internet is on and connected the area data is updated.

Could this be solved?

Regards

**Comment by wf9a5m75** [comment]
Google Maps Android API v2 or Google Maps SDK for iOS do not related with the Google Maps app.
So if you downloaded the offline area, it is not related with them.
