### ISSUE TITLE
Keep multiple infoWindows always visible

### ISSUE THREAD

**Issue by arekKalbarczyk** [mapsplugin/cordova-plugin-googlemaps#1041]
Hey,
I was thinking if its possible to keep multiple infoWindows visible at the same time and not let them disappear once you click somewhere else.

My case is that I would need to populate the marker with some dynamically loaded content  (it's not possible to do so with marker, as far as am concerned) and then style it accordingly.

Ultimately, I want to hide marker icons and just display their infoWindows.
Is it possible, by any chance?

##EDIT
Would it be possible to provide html as icon for a marker?
Greetings

**Comment by wf9a5m75** [comment]
Since Google Maps Android API v2 and Google Maps SDK for iOS do not provide the multiple infoWindows, this plugin can not do also.

And html is not available in infoWindow since the native map sdks do not support it.
