### ISSUE TITLE
Autopan problem on Android with Ionic.

### ISSUE THREAD

**Issue by noveltys** [mapsplugin/cordova-plugin-googlemaps#1042]
Hi,
i can't get autopan to work clicking a marker on Android 5 using cordova-plugin-googlemaps in Ionic. Works fine on iOS.

Here is my code and a short video. Any help greatly appreciated.

    `angular.module('ionicApp.GoogleMaps', ['ionic'])

    .config(function($stateProvider, $urlRouterProvider){

      $stateProvider
      .state('Map', {
        url: "/Map",
        templateUrl: "templates/Map.html",
        controller: "GoogleMapsCtrl"
      })
    })

    .controller('GoogleMapsCtrl', function($scope, $ionicPlatform, $ionicMap, locationService) {
    })

    .directive("ionMap", function ($ionicPlatform, $ionicMap) {
      return {
        restrict: 'AEC',
        link: function(scope, element, attrs) {
          $ionicPlatform.ready(function() {

            // Create a div object
            var div = document.createElement('div');
            div.style.width = attrs.width;
            div.style.height = attrs.height;

            // Add this div to the DOM
            element.append(div);

            // Turn the div into Google Maps object
            $ionicMap.init(div);
          });

        }
      }
    })

    .factory('$ionicMap', function($ionicPlatform, locationService) {
      var map = {}

      return {
        init: function(div) {
          $ionicPlatform.ready(function() {

            // Initialize the map view
            const NANTES = new plugin.google.maps.LatLng(47.216671,-1.55);
            map = plugin.google.maps.Map.getMap(div, {
            'mapType': plugin.google.maps.MapTypeId.ROADMAP,
            'controls': {
                'compass': true,
                'myLocationButton': true,
                'indoorPicker': true,
                'zoom': true
            },
            'gestures': {
                'scroll': true,
                'tilt': true,
                'rotate': true,
                'zoom': true
            },
            'camera': {
                'latLng': NANTES,
                'tilt': 60,
                'zoom': 12,
                'bearing': 50
            }
            });

            // Wait until the map is ready status.
            map.addEventListener(plugin.google.maps.event.MAP_READY, function() {
            //Load the markers
            loadMarkers();
            console.log('MAP_READY');
            },

            function(error){
            console.log("Could not get location");

            });

          function loadMarkers() {
            //Get all of the markers from Markers factory
            locationService.getLocations().then(function(markers) {

              for (var i = 0; i < markers.length; i++) {
                  var marker = markers[i];
                  var markerPos = new plugin.google.maps.LatLng(marker.lat, marker.lon);

                if (marker.events_count > 0) {

                      // Add the marker to the map
                      map.addMarker({
                      'position': markerPos,
                      'title': marker.name,
                      'snippet': marker.city,
                      'markerClick': function(marker) {
                        marker.showInfoWindow();
                      },
                      'infoClick': function(marker) {
                        alert(marker.get("title"));
                      }
                    });
                }
              }
                    alert("Markers ok");
            });
          }
          });
          return;
        },
        getMap: map
      }
    });
`
![07262016105035](https://cloud.githubusercontent.com/assets/12413791/17133423/4099383c-5326-11e6-846a-bab2853eef71.gif)

**Comment by wf9a5m75** [comment]
Um, I don't know the reason.
Try like this:

```js
marker.addMarker({
  disableAutoPan: false,
  ...
});
```

**Comment by noveltys** [comment]
hi @wf9a5m75,
I tried, but no luck. Maybe related to #488 ?
Thanks anyway.

**Comment by wf9a5m75** [comment]
I don't know.
Could you provide your whole project (not only code, because I'm not familiar with Angular) ?
Create a repository on Github (or others), and tell me it.

**Comment by noveltys** [comment]
Hi,
i just made a repo on Github. Send you an invite. Thank you for your time.

**Comment by wf9a5m75** [comment]
@noveltys Sorry for long-waiting.
I tested couple of times, but I was not confirmed.
By the way, the new version (v2-beta) is available.
Please try with the new version, and if still happens, let me know.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/v2.0-demo/
