### ISSUE TITLE
Html buttons over map view are not working.

### ISSUE THREAD

**Issue by Farhan7786** [mapsplugin/cordova-plugin-googlemaps#1045]
I am able to run full screen map in my ionic app without any issues. I have placed some html buttons on map view but they are not working. When i press any button it starts panning map instead of doing button action.

Any help would be highly appreciated.

-Thanks

**Comment by wf9a5m75** [comment]
Check your app with `map.setDebuggable(true);`.
Remember, the html button MUST BE a child element under the map div.

**Comment by ndrd** [comment]
@Farhan7786 
Same problem here! I just put a div instead a button, works fine for me!
`  <div id="map_canvas">
		<div  class = "button  ar-trigger  ion-ios-camera-outline" ng-click="showAR()"></div>
		<div  class = "button  location-trigger  ion-ios-location-outline" ng-click="getLocation()"></div>
	</div>`

**Comment by Farhan7786** [comment]
Thanks @ndrd. Everything is working fine now. :)

**Comment by douglasjunior** [comment]
I have a similar problem, could you tell me if it's related?

If open a HTML Popup (dialog) over the map, the touch events is not captured by Popup, but by the map.

![captura de tela 2016-07-29 as 09 31 45](https://cloud.githubusercontent.com/assets/1512341/17248224/85012976-556f-11e6-8835-fdb74cfb95e0.png)

Same problem if the header bar is over the map.

![captura de tela 2016-07-29 as 09 32 01](https://cloud.githubusercontent.com/assets/1512341/17248329/311aca64-5570-11e6-9c7b-6566c9ea7a59.png)

It happens both Android and iOS. With JavaScript maps I had no problems.

_Ionic 1.7.16
Cordova 6.3.0
cordova-plugin-googlemaps 1.3.9_
