### ISSUE TITLE
Update the Google Maps SDK for iOS

### ISSUE THREAD

**Issue by djuju08** [mapsplugin/cordova-plugin-googlemaps#1047]
Hi,

Currently, the version **2.0.25803.0** of the SDK is available (a message is displayed in the console) and i'm running the **1.13.0** (available with the bitbucket repo).

Is it possible to update it ?

Have a nice day,

Julien

**Comment by Hirbod** [comment]
I will update the binary - and finally, the filesize was reduced by 70%, as the Places API got splitted into it own package, which will make it possible to pin it back to Github, which also should increase download-speed.

**Comment by djuju08** [comment]
Awesome !
It will be a nice improvement

**Comment by ZiFFeL1992** [comment]
Any update on this @Hirbod ?

**Comment by Hirbod** [comment]
I am waiting for Masashi to be "done", after that, I will pin up the new version. I don't want to break things (should not happen, but could)

**Comment by cafrie** [comment]
Hi,
Our iOS app was recently rejected for using/referencing the following non-public APIs:
imageWithName
nextStartIndex

To my understanding this was fixed by Google in version 1.13.2 (See issue):
https://code.google.com/p/gmaps-api-issues/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Introduced%20Fixed%20Summary%20Stars%20ApiType%20Internal&groupby=&sort=&id=9704

Has anyone else faced this issue?
Do you have a fix for this or just to wait for the update and hope it goes away?
Thanks.

**Comment by clshack** [comment]
@cafrie  I have the same issue and I am using the dev branch

**Comment by cafrie** [comment]
Solved.
Take a look at the issues on Google Maps bug report:
https://code.google.com/p/gmaps-api-issues/issues/detail?id=9704
https://code.google.com/p/gmaps-api-issues/issues/detail?id=10393

**Comment by clshack** [comment]
@cafrie how did you solve ? 
Did you updated manually the maps framework inside the plugin ?

**Comment by cafrie** [comment]
I did. Probably didn't need to.
Packages have changed a bit, but nothing seems to be broken.
Try Google's suggested workaround first - you'll have to use it anyway as there's another false positive in the latest sdk.

**Comment by wf9a5m75** [comment]
Oh, I see. I will check the Maps SDK for the master branch from now.

**Comment by canadaka** [comment]
:( Our app which has been approved many times before was rejected today due to this, same as #1098

**Comment by wf9a5m75** [comment]
Ok, I updated the master branch code. Please re-install the maps plugin from the master branch.
The new code will install the maps iOS SDK v2.0.1.
The problem should be solved.

And I ported some code from the optimization branch into the master branch.
So, the performance of adding markers and geocoding are improved.
Please test the master branch.

**Comment by vosecek** [comment]
@wf9a5m75 Nice job, thanks a lot. Will be verified by Apple in two days :)

**Comment by vosecek** [comment]
App has been approved.

**Comment by canadaka** [comment]
Our app update was also approved using the updated SDK, thank you!
