### ISSUE TITLE
html inside the map blocking touch after resize

### ISSUE THREAD

**Issue by GuiCarneiro** [mapsplugin/cordova-plugin-googlemaps#1051]
I'm doing a resize in a card inside my map, after the resize it blocks any touch.

this is my scss:
![captura de tela 2016-07-30 as 13 06 20](https://cloud.githubusercontent.com/assets/5458742/17271600/85eaed12-5656-11e6-9e5b-97597d200c5e.png)

this is the html:
![captura de tela 2016-07-30 as 13 06 28](https://cloud.githubusercontent.com/assets/5458742/17271602/8f834f0e-5656-11e6-8372-a5e231076118.png)

Do you guys have any idea?

**Comment by wf9a5m75** [comment]
`map.setDebuggable(true)` and `map.refreshLayout()`
