### ISSUE TITLE
Errors while coping files of old main activity of cordova 2.1 to new cordova cli 6.2 main activity

### ISSUE THREAD

**Issue by ashras12** [mapsplugin/cordova-plugin-googlemaps#1052]
Hi..I am getting 14 errors in main activity after coping files of old main activity of cordova 2.1 to new cordova cli 6.2 main activity in android studio.I am new to android cordova.Please let me know how to resolve these errors.The below is my mainactivity file.

package com.gingerhotels.GingerApp16;

import android.os.Bundle;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Timer;
import java.util.TimerTask;
import org.apache.cordova.CordovaActivity;
import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.util.Log;
import android.view.Menu;
import android.content.Context;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.net.Uri;
import android.widget.Toast;

public class MainActivity extends CordovaActivity
{

    /* added by sneha */
    // url of txt file where latest version is maintained
    String url = "https://bookings.gingerhotels.com/SmartTouch/android"; //prod url
    //String url = "https://115.112.50.66:8280/SmartTouch/android"; //quality url
    //String url = "http://192.168.240.73:8080/SmartTouch/android";//local
    //String url = "http://01hw483470:8080/SmartTouch/android"; //ashra local system
    CharSequence network_fail = "This application requires that you are connected to the Internet.";
    CharSequence general_fail = "There was some problem. Please try after sometime.";
    int duration = Toast.LENGTH_LONG;
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        // Set by <content src="index.html" /> in config.xml
        super.onCreate(savedInstanceState);

        boolean isAvailable = false;
        boolean isWifiAvailable = false;

        // Check availability of network connection
        try {

            ConnectivityManager cm = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
            cm.getActiveNetworkInfo();
            if (cm == null)
                isAvailable = false;
            else

                isAvailable = cm.getActiveNetworkInfo().isConnected();

            NetworkInfo mWifi = cm
                    .getNetworkInfo(ConnectivityManager.TYPE_WIFI);

            if (mWifi.isConnected()) {
                isWifiAvailable = true;
            }

            if (isAvailable || isWifiAvailable) {

                // Internet-reliant code

                // added by sneha to check current and latest version and give
                // appropriate message

                int currentVersion = getSoftwareVersion();
                String latestVersion1 = "";
                try {
                    latestVersion1 = getNewVersion();

                    int latest = Integer.valueOf(latestVersion1);

                    if (currentVersion < latest) {

                        new AlertDialog.Builder(MainActivity.this)
                                .setIcon(R.drawable.ico)
                                .setTitle("Update Available")
                                .setCancelable(false)
                                .setMessage(
                                        "Visit Android Market to update application?")
                                .setPositiveButton("OK",
                                        new DialogInterface.OnClickListener() {
                                            public void onClick(
                                                    DialogInterface dialog,
                                                    int whichButton) {

                                                Intent intent = new Intent(
                                                        Intent.ACTION_VIEW,
                                                        Uri.parse("https://play.google.com/store/apps/details?id=com.reservation.gingerapp14"));
                                                startActivity(intent);
                                                finish();
                                            }
                                        })
								/*
								 * .setNegativeButton("No", new
								 * DialogInterface.OnClickListener() { public
								 * void onClick(DialogInterface dialog, int
								 * whichButton) { // User clicked Cancel. Exit
								 * app finish(); } })
								 */
                                .show();

                    }
                } catch (Exception e) {

                    Toast fail = Toast.makeText(this, general_fail, duration);
                    fail.show();

                    Timer t = new Timer();
                    t.schedule(new TimerTask() {

                        @Override
                        public void run() {

                            finish();
                            // If you want to call Activity then call from here
                            // for 5 seconds it automatically call and your
                            // image disappear....
                        }
                    }, 3000);

                    e.printStackTrace();
                }

                // compare current and latest version code

            } else {
                Toast fail = Toast.makeText(this, network_fail, duration);
                fail.show();

                Timer t = new Timer();
                t.schedule(new TimerTask() {

                    @Override
                    public void run() {

                        finish();
                        // If you want to call Activity then call from here for
                        // 5 seconds it automatically call and your image
                        // disappear....
                    }
                }, 3000);

            }
        } catch (Exception e) {
            Toast fail = Toast.makeText(this, network_fail, duration);
            fail.show();

            Timer t = new Timer();
            t.schedule(new TimerTask() {

                @Override
                public void run() {

                    finish();
                    // If you want to call Activity then call from here for 5
                    // seconds it automatically call and your image
                    // disappear....
                }
            }, 3000);
        }

        // clear html & js code from the webview cache
        super.clearCache();

        super.setIntegerProperty("loadUrlTimeoutValue", 150000);

        super.setIntegerProperty("splashscreen",R.drawable.spalsh);

        super.loadUrl("file:///android_asset/www/booking1.html", 30000);

    }

    // get version code from server hosted server file
    public String getNewVersion() {

        HttpClient client = new DefaultHttpClient();
        HttpGet request = new HttpGet(url);
        String latestVersion = "";
        try {

            HttpResponse response = client.execute(request);

            InputStream in = response.getEntity().getContent();
            BufferedReader reader = new BufferedReader(
                    new InputStreamReader(in));
            StringBuilder str = new StringBuilder();
            String line = null;
            while ((line = reader.readLine()) != null) {
                str.append(line);
            }
            in.close();
            latestVersion = str.toString();
        } catch (IOException e) {
            Toast fail = Toast.makeText(this, network_fail, duration);
            fail.show();

            Timer t = new Timer();
            t.schedule(new TimerTask() {

                @Override
                public void run() {

                    finish();
                    // If you want to call Activity then call from here for 5
                    // seconds it automatically call and your image
                    // disappear....
                }
            }, 3000);
        } catch (Exception e) {

            Toast fail = Toast.makeText(this, network_fail, duration);
            fail.show();

            Timer t = new Timer();
            t.schedule(new TimerTask() {

                @Override
                public void run() {

                    finish();
                    // If you want to call Activity then call from here for 5
                    // seconds it automatically call and your image
                    // disappear....
                }
            }, 3000);

            e.printStackTrace();
        }

        return latestVersion;
    }

    // get current apk version
    private int getSoftwareVersion() {
        try {

            PackageInfo packageInfo = getPackageManager().getPackageInfo(
                    getPackageName(), 0);
            // return packageInfo.versionName;//EDIT: versionCode would be
            // better
            return packageInfo.versionCode;

        } catch (PackageManager.NameNotFoundException e) {
            Log.e(TAG, "Package name not found", e);
            return 0;
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

    @Override
    public void onStart() {
        super.onStart();
        EasyTracker.getInstance(this).activityStart(this);

        // EasyTracker.getInstance(this).dispatch(this);
    }

    @Override
    public void onStop() {
        super.onStop();
        EasyTracker.getInstance(this).activityStop(this);
    }

}

These errors i am getting while building apk..

Information:Gradle tasks [:CordovaLib:assembleDebug, :assembleDebug]
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:CordovaLib:compileDebugSources UP-TO-DATE
:CordovaLib:assembleDebug UP-TO-DATE
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJavaWithJavac
C:\App16\platforms\android\src\com\gingerhotels\GingerApp16\MainActivity.java
Error:(102, 52) error: cannot find symbol variable ico
Error:(190, 14) error: cannot find symbol method clearCache()
Error:(192, 14) error: cannot find symbol method setIntegerProperty(String,int)
Error:(194, 59) error: cannot find symbol variable spalsh
Error:(196, 14) error: method loadUrl in class CordovaActivity cannot be applied to given types;
required: String
found: String,int
reason: actual and formal argument lists differ in length
Error:(203, 9) error: cannot find symbol class HttpClient
Error:(203, 33) error: cannot find symbol class DefaultHttpClient
Error:(204, 9) error: cannot find symbol class HttpGet
Error:(204, 31) error: cannot find symbol class HttpGet
Error:(208, 13) error: cannot find symbol class HttpResponse
Error:(279, 36) error: cannot find symbol variable menu
Error:(286, 9) error: cannot find symbol variable EasyTracker
Error:(294, 9) error: cannot find symbol variable EasyTracker
Note: C:\App16\platforms\android\src\com\gingerhotels\App16\MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Error:Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 28.411 secs
Information:14 errors
Information:0 warnings
Information:See complete output in console

**Comment by wf9a5m75** [comment]
This is not related with this plugin.
