### ISSUE TITLE
Ionic 2 black screen over the map on iOS

### ISSUE THREAD

**Issue by melkir** [mapsplugin/cordova-plugin-googlemaps#1054]
![ios bug](https://cloud.githubusercontent.com/assets/3305685/17313071/925c8a6c-5893-11e6-87c0-6a05727eb1c8.jpg)

I am trying to use this plugin with iOS and Ionic 2 and there's this strange black layout that I can't get ride of. I know that the map is present under this black layout (reducing body opacity) and I can interact with.

This bug is only appear on iOS, I have no problem on Android.

**Comment by renshuki** [comment]
Same here! Background transparency issue on iOS?

**Comment by ZiFFeL1992** [comment]
Here you can find the solution: https://github.com/driftyco/ionic/issues/7205

**Comment by melkir** [comment]
Thanks, you saved my week ! :D

**Comment by renshuki** [comment]
Thanks for the help!  (*^。^*)
I think this issue can be closed btw.

**Comment by ihadeed** [comment]
You're the real MVP @ZiFFeL1992
