### ISSUE TITLE
How to install into Cordova Angular 1 Project

### ISSUE THREAD

**Issue by SurviveDrive** [mapsplugin/cordova-plugin-googlemaps#1055]
Hi Where do I put this code please in angular project?

     var map;
        document.addEventListener("deviceready", function() {
            var div = document.getElementById("map_canvas");

            // Initialize the map view
            map = plugin.google.maps.Map.getMap(div);

            // Wait until the map is ready status.
            map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
        }, false);

        function onMapReady() {
            var button = document.getElementById("button");
            button.addEventListener("click", onBtnClicked, false);
        }

        function onBtnClicked() {
            map.showDialog();
        }

**Comment by SurviveDrive** [comment]
Not my full screen button works and shows a map but when i try use the map_canvas id does not work

**Comment by SurviveDrive** [comment]
var app = {

    initialize: function () {
        this.bindEvents();
    },

    bindEvents: function () {
        document.addEventListener('deviceready', this.onDeviceReady, false);

    },




    onDeviceReady: function () {



        var map;
        document.addEventListener("deviceready", function() {
            var div = document.getElementById("map_canvas");

            // Initialize the map view
            map = plugin.google.maps.Map.getMap(div);

            // Wait until the map is ready status.
            map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
        }, false);

        function onMapReady() {
            var button = document.getElementById("button");
            button.addEventListener("click", onBtnClicked, false);
        }

        function onBtnClicked() {
            map.showDialog();
        }




        // Get a reference to the plugin.
        var bgGeo = window.BackgroundGeolocation;

        /**
         * This callback will be executed every time a geolocation is recorded in the background.
         */
        var callbackFn = function(location, taskId) {
            var coords = location.coords;
            var lat    = coords.latitude;
            var lng    = coords.longitude;

            // Simulate doing some extra work with a bogus setTimeout.  This could perhaps be an Ajax request to your server.
            // The point here is that you must execute bgGeo.finish after all asynchronous operations within the callback are complete.
            setTimeout(function() {
                bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
            }, 1000);
        };

        var failureFn = function(error) {
            console.log('BackgroundGeoLocation error', error);
        }

        // BackgroundGeoLocation is highly configurable.
        bgGeo.configure(callbackFn, failureFn, {
            // Geolocation config
            desiredAccuracy: 0,
            stationaryRadius: 50,
            distanceFilter: 50,
            disableElasticity: false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
            locationUpdateInterval: 5000,
            minimumActivityRecognitionConfidence: 80,   // 0-100%.  Minimum activity-confidence for a state-change
            fastestLocationUpdateInterval: 5000,
            activityRecognitionInterval: 10000,
            stopDetectionDelay: 1,   // [iOS] delay x minutes before entering stop-detection mode
            stopTimeout: 2,  // Stop-detection timeout minutes (wait x minutes to turn off tracking)
            activityType: 'AutomotiveNavigation',

            // Application config
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)
            forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user)
            forceReloadOnGeofence: false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user)
            stopOnTerminate: false,              // <-- Don't stop tracking when user closes app.
            startOnBoot: true,                   // <-- [Android] Auto start background-service in headless mode when device is powered-up.

            // HTTP / SQLite config
            url: 'http://posttestserver.com/post.php?dir=cordova-background-geolocation',
            method: 'POST',
            batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
            maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
            headers: {
                "X-FOO": "bar"
            },
            params: {
                "auth_token": "maybe_your_server_authenticates_via_token_YES?"
            }
        });



        function successFunction()
        {
            console.info("It worked!");
        }

        function errorFunction(error)
        {
            console.error(error);
        }

        function trace(value)
        {
            console.log(value);
        }

// Is this plugin supported?
        AndroidFullScreen.isSupported();

// Is immersive mode supported?
        AndroidFullScreen.isImmersiveModeSupported(successFunction, errorFunction);

// The width of the screen in immersive mode
        AndroidFullScreen.immersiveWidth(trace, errorFunction);

// The height of the screen in immersive mode
        AndroidFullScreen.immersiveHeight(trace, errorFunction);

/*// Hide system UI until user interacts
         AndroidFullScreen.leanMode(successFunction, errorFunction);*/
        // Hide system UI and keep it hidden (Android 4.4+ only)
        AndroidFullScreen.immersiveMode(successFunction, errorFunction);

        app.receivedEvent('deviceready');
        try {
            pwa();
        } catch (e) {
            pwios();
        }





        ons.setDefaultDeviceBackButtonListener(function () {
            //window.history.back();

              history.go(-1);
            navigator.app.backHistory();
           /* if (navigator.notification.confirm("Are you sure to close the app?",
                    function (index) {
                        if (index == 1) { // OK button
                            navigator.app.exitApp(); // Close the app
                        }
                    }
                ));*/
        });

        // Open any external link with InAppBrowser Plugin
        $(document).on('click', 'a[href^=http], a[href^=https]', function (e) {

            e.preventDefault();
            var $this = $(this);
            var target = $this.data('inAppBrowser') || '_blank';

            window.open($this.attr('href'), target);

        });




    },
    // Update DOM on a Received Event
    receivedEvent: function (id) {

        console.log('Received Event: ' + id);
    },


   };



   app.initialize();





   background();

   function pwa () {
                  var pushNotification = cordova.require("pushwoosh-cordova-plugin.PushNotification");

                  //set push notifications handler
                  document.addEventListener('push-notification', function (event) {
                      var title = event.notification.title;
                      var userData = event.notification.userdata;

                      if (typeof(userData) != "undefined") {
                          console.warn('user data: ' + JSON.stringify(userData));
                      }

                      alert(title);
                  });

                  //initialize Pushwoosh with projectid: "GOOGLE_PROJECT_NUMBER", pw_appid : "PUSHWOOSH_APP_ID". This will trigger all pending push notifications on start.
                   pushNotification.onDeviceReady({projectid: "995232076719", pw_appid: "3D096-58B57"});

                  //register for pushes
                  pushNotification.registerDevice(
                      function (status) {
                          var pushToken = status;
                          console.warn('push token: ' + pushToken);
                      },
                      function (status) {
                          console.warn(JSON.stringify(['failed to register ', status]));
                      }
                  );
              };

              function background (){


              // Android customization
                  cordova.plugins.backgroundMode.setDefaults({ text:'Doing heavy tasks.'});
                  // Enable background mode
                  cordova.plugins.backgroundMode.enable();

                  // Called when background mode has been activated
                  cordova.plugins.backgroundMode.onactivate = function () {
                      setTimeout(function () {
                          // Modify the currently displayed notification
                          cordova.plugins.backgroundMode.configure({
                              text:'Running in background for more than 5s now.'
                          });
                      }, 5000);
                  }
              }

function pwios() {
    var pushNotification = cordova.require("pushwoosh-cordova-plugin.PushNotification");

    //set push notification callback before we initialize the plugin
    document.addEventListener('push-notification', function(event) {
        //get the notification payload
        var notification = event.notification;

        //display alert to the user for example
        alert(notification.aps.alert);

        //clear the app badge
        pushNotification.setApplicationIconBadgeNumber(0);
    });

    //initialize the plugin
    pushNotification.onDeviceReady({pw_appid:"3D096-58B57"});

    //register for pushes
    pushNotification.registerDevice(
        function(status) {
            var deviceToken = status['deviceToken'];
            console.warn('registerDevice: ' + deviceToken);
        },
        function(status) {
            console.warn('failed to register : ' + JSON.stringify(status));
            alert(JSON.stringify(['failed to register ', status]));
        }
    );

    //reset badges on app start
    pushNotification.setApplicationIconBadgeNumber(0);
}

**Comment by djuju08** [comment]
Have you added the css ?

If not : 
```
#map_canvas {
  width: 100%;
  height: 100%;
}

.scroll {
  height: 100%;
}
```
