### ISSUE TITLE
Cordova-iOS 4.X and WKWebView

### ISSUE THREAD

**Issue by jayenashar** [mapsplugin/cordova-plugin-googlemaps#1056]
i've got a new project where i can't compile the ios version (android works fine).

```
/Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/ios/finderful.com/Plugins/plugin.google.maps/GoogleMaps.m:176:59: error: no known instance method for selector 'initWithWebView:'
        Map *mapClass = [[NSClassFromString(@"Map")alloc] initWithWebView:self.webView];
                                                          ^~~~~~~~~~~~~~~
/Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/ios/finderful.com/Plugins/plugin.google.maps/GoogleMaps.m:245:68: error: no known instance method for selector 'initWithWebView:'
                pluginClass = [[NSClassFromString(className)alloc] initWithWebView:self.webView];
                                                                   ^~~~~~~~~~~~~~~
/Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/ios/finderful.com/Plugins/plugin.google.maps/GoogleMaps.m:321:19: error: no visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
    [self.webView stringByEvaluatingJavaScriptFromString:jsString];
     ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

looking at issue #907 i'm guessing an update is needed for cordova ios 4.2.0 .  i'm using 1.3.9 of this plugin and don't know how to get a different version (new to npm and cordova).  i also seem to have com.googlemaps.ios 1.13.0 in plugins/ but i don't know where it came from.

**Comment by djuju08** [comment]
Try using cordova ios 4.0 by typing:

```
ionic platform rm ios
ionic platform add ios@4.0
```

**Comment by jayenashar** [comment]
Thanks.  I'm using `cordova`, not `ionic`, but it seems to be the same.  I tried 4.1.1 and 4.0.1.  Here's the error with 4.0.1:

```
/Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/ios/finderful.com/Plugins/plugin.google.maps/GoogleMapsViewController.m:10:9: fatal error: 'Cordova/CDVJSON.h' file not found
#import <Cordova/CDVJSON.h>
        ^
```

it compiles successfully with warnings on cordova ios 3.9.2

**Comment by djuju08** [comment]
Yes it's the same, ionic cli uses cordova cli to run the commands.

Have you installed the plugin with the name "cordova-plugin-googlemaps" or the url of the repo "https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps" ?

If this is your case, run the following commands:

```
cordova plugin rm plugin.google.maps
cordova plugin com.googlemaps.ios
cordova plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
```

On cordova ios 4+, you need to use the master to make it working.

I had the same issue and this solved my problem, I hope it can help you

**Comment by jayenashar** [comment]
yes, i installed `cordova-plugin-googlemaps` which i thought was this repository.

i just tried `https://github.com/mapsplugin/cordova-plugin-googlemaps.git` with cordova ios 4.2.0 and the build succeeded thanks.

i also see this now in the README: https://github.com/mapsplugin/cordova-plugin-googlemaps#information  sorry i didn't see it before.

thanks for your help!
