### ISSUE TITLE
customize infowindow ?

### ISSUE THREAD

**Issue by wroquet** [mapsplugin/cordova-plugin-googlemaps#106]
Nice cordova plugin,
i used before that the google maps javascript API for my cordova projects, but this plugin i awesome !
i just wondering if it exists a way to customise a marker infowindow ? With the Javascript API, i used to do it with infobox.js : https://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/docs/examples.html , and add custom HTML and CSS to make a full custom infowindow.

thanks !

**Comment by quiuquio** [comment]
Hi, is this planned to be supported eventually?
I could also work on it, but would need some pointers on where the relevant code is situated.
Thanks!

**Comment by wf9a5m75** [comment]
If you want to customize the infoWindow, read here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L1684-L1870

**Comment by iChuaNz** [comment]
> If you want to customize the infoWindow, read here.
> https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L1684-L1870

hi im facing the issue trying to customize infowindow as well, but your link is current not found able
