### ISSUE TITLE
Maps is going to backward of ion-app

### ISSUE THREAD

**Issue by GuimaP** [mapsplugin/cordova-plugin-googlemaps#1060]
Hi guys, im trying to instance a new map in ion-page, but all the time that i instance a new map, he is going to backward of ion-app in Ionic 2, someone already had this issue?

**Comment by djuju08** [comment]
Try [this](https://github.com/driftyco/ionic/issues/7205) : https://github.com/driftyco/ionic/issues/7205

**Comment by GuimaP** [comment]
Thanks @djuju08 ,
