### ISSUE TITLE
Custom InfoWindow : Customize the border and let transparent background.

### ISSUE THREAD

**Issue by CardosoGit** [mapsplugin/cordova-plugin-googlemaps#1061]
Is it Possible?

**Comment by CardosoGit** [comment]
I got by reversing the implementations of the methods: getInfoWindow() and getInfoContents.
Now, I can customize the infoWindow  by using Base64 Encode and Canvas without  the default InfoWIndow.
![image](https://cloud.githubusercontent.com/assets/10578336/17460289/6869b16c-5c35-11e6-80e8-ae125dd45728.png)

**Comment by cadz7** [comment]
Hi @CardosoGit , could you please share the code implementation of how you achieved the custom infoWindow.
I wish to achieve something similar to the image above.
Thanks!

**Comment by anymos** [comment]
+1

**Comment by JeffreyJamesMMM** [comment]
I am also interested in this. I need a custom infowindow.

**Comment by caffic** [comment]
+1

**Comment by CardosoGit** [comment]
It's for android.

Open and modify the file GoogleMaps.java.
![image](https://cloud.githubusercontent.com/assets/10578336/17791070/c6cc9c40-656f-11e6-9153-5379d1830b91.png)

Take the implementation of getInfoWindow () method and put within the getInfoContents () method and vice versa.


Before:
![image](https://cloud.githubusercontent.com/assets/10578336/17791037/9bda32f4-656f-11e6-92f9-39f011e25b9a.png)

After:
![image](https://cloud.githubusercontent.com/assets/10578336/17791666/c575f582-6572-11e6-8f1f-a70d81483060.png)


Don't forget to remove platform and add again.

**Comment by CardosoGit** [comment]
Now just customize InfoWindow using Base64 Encode:
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#base64-encoded-icon

**Comment by slimlime** [comment]
is this method no longer usable? I only see `CordovaGoogleMaps.java` files under `plugins/` and `platforms/` and neither have the `getInfo` functions.
