### ISSUE TITLE
Error building iOS app on version cli-6.3.0 of phonegap build

### ISSUE THREAD

**Issue by RubenMartins** [mapsplugin/cordova-plugin-googlemaps#1062]
**This is the error**
> Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: plugin.google.maps

**And the log shows this** 

> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileC build/SmartInfo.build/Release-iphoneos/SmartInfo.build/Objects-normal/armv7/GoogleMapsViewController.o SmartInfo/Plugins/plugin.google.maps/GoogleMapsViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)

**Comment by wf9a5m75** [comment]
We currently use `cordova-plugin-googlemaps`.

**Comment by RubenMartins** [comment]
Tanks for the quick reply.

I also noticed that but the error log returns this in the begining

> Fetching plugin "cordova-plugin-googlemaps@1.3.9" via npm
> Installing "plugin.google.maps" at "1.3.9" for ios
> Fetching plugin "https://bitbucket.org/nightstomp/cordova-plugin-googlemaps-sdk.git" via git clone
> Repository "https://bitbucket.org/nightstomp/cordova-plugin-googlemaps-sdk.git" checked out to git ref "master" at "862d8a2".
> Installing "com.googlemaps.ios" at "1.13.0" for ios
> 
>         Google Maps SDK for iOS : v1.13.0
>         
> 
>              In order to run this plugin, you need to obtain Google Maps API key for iOS.
>              Visit https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Installation
> 
>              Check our release notes.
>              https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Release-Notes

Looks like the fetch the cordova-plugin-googlemaps  but then install the plugin.google.maps instead.

**Comment by wf9a5m75** [comment]
Please use `https://github.com/mapsplugin/cordova-plugin-googlemaps` instead of npm.

**Comment by statiklabs** [comment]
I had the same issue. Build works fine with master version in git.

**Comment by wf9a5m75** [comment]
>Cordova-iOS 4.X and WKWebView are supported from version 1.4+. There is currently no npm package of 1.4 (work in progress) but if you need this feature, you can grab our master, which is currently considered stable. (We're still fixing bugs, so you might wait until we push 1.4.0 to npm)

https://github.com/mapsplugin/cordova-plugin-googlemaps#information
