### ISSUE TITLE
Blank Page on IOS

### ISSUE THREAD

**Issue by GuiCarneiro** [mapsplugin/cordova-plugin-googlemaps#1063]
I have an app in Ionic 2 that uses Google Maps, and it is working fine on Android.

But it is blank on IOS. Nothing appears on my console, so I have no idea why =/

My Screen:
![captura de tela 2016-08-11 as 18 13 14](https://cloud.githubusercontent.com/assets/5458742/17608374/8422041a-6002-11e6-9e85-d2206bd3e3c8.png)

The plugin:
![captura de tela 2016-08-11 as 18 14 02](https://cloud.githubusercontent.com/assets/5458742/17608378/8ab3273c-6002-11e6-8a3f-2a3f892b50d3.png)

My maps provider:
![captura de tela 2016-08-11 as 18 15 33](https://cloud.githubusercontent.com/assets/5458742/17608383/8ebf05b2-6002-11e6-98d8-7cf08313e609.png)

**Comment by wf9a5m75** [comment]
Maybe this?

```css
ion-app._gmaps_cdv_ .nav-decor {
    background-color: rgba(0,0,0,0);
}
```

https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=ionic&type=Issues&utf8=%E2%9C%93

**Comment by nakulgulati** [comment]
@wf9a5m75 
> Maybe this?
> 
> ion-app._gmaps_cdv_ .nav-decor {
>     background-color: rgba(0,0,0,0);
> }
> https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=ionic&type=Issues&utf8=%E2%9C%93

Fixed the issue with Ionic 2 Beta 11.
Thanks.
