### ISSUE TITLE
Markers overlap native user position on iOS

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#1064]
Markers added via
```
AddMarker(
{
icon:{
url:"icon.png"
}}
);
```
overlaps user position on iOS (Android seems to work properly).

Markers show be always below user location.

Any suggestion, how to solve this?

App is built with Ionic 1.

![img_3542](https://cloud.githubusercontent.com/assets/3978659/17621846/95240800-6096-11e6-9fa4-a7305f537a4c.PNG)

**Comment by wf9a5m75** [comment]
That is the same as native SDK (Google Maps SDK for iOS).
It means it's correct feature of the Google Maps SDK for iOS.
