### ISSUE TITLE
Getting timeout error during build process when trying to get plugin (IOS only)

### ISSUE THREAD

**Issue by amiriltd** [mapsplugin/cordova-plugin-googlemaps#1066]
This has been happening since the change from https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps to https://github.com/mapsplugin/cordova-plugin-googlemaps 
![capture build error](https://cloud.githubusercontent.com/assets/6475095/17627028/b4091792-607d-11e6-96fd-20687a9d95a5.PNG)

Error - Plugin repo install has timed out on the following plugin, please try building again: https://github.com/mapsplugin/cordova-plugin-googlemaps

**Comment by wf9a5m75** [comment]
First of all, we don't use `https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps` anymore.
Currently `https://github.com/mapsplugin/cordova-plugin-googlemaps` only.

And the time out issue is Github problem or your build environment problem (or maybe network...etc), not this plugin's problem.
