### ISSUE TITLE
Cordova plugin GoogleMaps throws error in the CLI

### ISSUE THREAD

**Issue by HamzaLJ** [mapsplugin/cordova-plugin-googlemaps#1068]
The plugin throws several error after I adding it, it was installed with no errors; however, when I run an emulate command (Ionic2) I receive the below error:

P.S. Everything back to normal once I delete the plugin!

1 warning and 1 error generated.

** BUILD FAILED **

The following build commands failed:

	CompileC build/Flavy.build/Debug-iphonesimulator/Flavy.build/Objects-normal/i386/GroundOverlay.o Flavy/Plugins/plugin.google.maps/GroundOverlay.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Michael/Documents/new/flavy/platforms/ios/cordova/build-debug.xcconfig,-project,Flavy.xcodeproj,ARCHS=i386,-target,Flavy,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Michael/Documents/new/flavy/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Michael/Documents/new/flavy/platforms/ios/build/sharedpch

Caught exception:
 undefined

**Comment by wf9a5m75** [comment]
Try from the master branch.

```
$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
```

**Comment by davorpeic** [comment]
Had the same issue, I uninstalled all and installed as @wf9a5m75 said and now the build goes without error.

dp

**Comment by wf9a5m75** [comment]
Please report all error logs, not only one line.

**Comment by davorpeic** [comment]
@wf9a5m75 Sorry, updates my answer

**Comment by wf9a5m75** [comment]
Thanks
