### ISSUE TITLE
Map loads slow during navigation (Requires pre-loading maybe?)

### ISSUE THREAD

**Issue by Vardan92** [mapsplugin/cordova-plugin-googlemaps#1069]
Hello, I've spent a few days working with this plugin, and after a huge war with it, I managed to make it run smoothly (yay). Now the last issue I'm facing which I can't seem to shake is that the map itself loads slow when navigating and quite ugly, if I dare say (or maybe this is just how it is?).

Basically is there a way to speed up the loading, or to pre-load a section of the map or something so when I navigate around it is already loaded?
Thanks!
and @developer - Thank you for this awesome plugin!

**Comment by wf9a5m75** [comment]
This plugin is not related with the loading speed. The factors are (1) your network speed, (2) your device spped (cpu & memory), some thing like that.

**Comment by Vardan92** [comment]
Based on the diagnostics my cpu and memory are fine, same rate whether I add all my content or take it out. This is ok I guess, but is there a way at least to load/preload the sides of map so when I scroll it doesn't require as much loading? Thanks!

**Comment by wf9a5m75** [comment]
Try like this: ```js
var map = plugin.google.maps.Map.getMap([options]);

function showMap() {
  map.setDiv(mapDiv)
}
function hideMap() {
  map.setDiv(null);
}
```

**Comment by Vardan92** [comment]
The map is ok, I'm just trying to preload the contents of it to prevent loading while scrolling.
The map only loads whatever is displayed, I want to load whatever is displayed AND the parts which aren't on the sides, therefore when navigating around the map the map is already loaded!
Example: Pre-load 1 mile radius of map (instead of whatever you see)
Sorry if question is difficult, thanks!

**Comment by uzumakinaruto123** [comment]
Tested Demo apk on One plus 3  device with top most hardware specs on 400 Mbps connection. Map is slow to render , not a good sight to end user.
 But , its still great that we are able to use native maps on cordova apps. I still want to try and find a way to render maps efficiently.
