### ISSUE TITLE
GoogleMaps.H file not found when manual instalation

### ISSUE THREAD

**Issue by rezadaulay** [mapsplugin/cordova-plugin-googlemaps#1070]
Hello,

I have to manually install the plugin both Googlemap IOS SDK and follow the installation guide manual.but i found error GoogleMaps.H file not found.

PS : I installed it manually because I have always failed to automatic installation from terminal,when installing I always get the error : 

error: RPC failed; result=56, HTTP code = 200iB | 524.00 KiB/s
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by wf9a5m75** [comment]
```
error: RPC failed; result=56, HTTP code = 200iB | 524.00 KiB/s
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
It seems you tried to install the plugin from npm.
Try from the master branch.

```
$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
```

**Comment by rezadaulay** [comment]
@wf9a5m75 , thanks you it doesnt work , but when i change my network config i can install via npm, i think it's my network problem.
