### ISSUE TITLE
Problem with secure origin

### ISSUE THREAD

**Issue by DianeSoares** [mapsplugin/cordova-plugin-googlemaps#1071]
Hi, i have a problem with getCurrentPosition in Phonegap application, this method return "Only secure origin Allowed". How to solve it?

**Comment by celron** [comment]
getCurrentPosition() is not a plugin call, it is a browser call and you are dealing with a browser issue, you can see [here] (https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins).  The plugin call is [getMyLocation()] (https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.getMyLocation())

**Comment by DianeSoares** [comment]
Thanks 
But, i tried this and it's returned this error "Uncaught TypeError: map.getMyLocation is not a function"

**Comment by celron** [comment]
You've just basically cited two different issues, and they are related to getting your current location.  Only the latter is related to this plugin, and for solutions on the former you should look on stackexchange.

I use getMyLocation() in my app so I know that the call exists in iOS and Android, so your error message "Uncaught TypeError: map.getMyLocation is not a function" sounds like programmer error, unless you provide more information, like did the map correctly display, did MAP_READY event occur, what version of the plugin are you using and what platform are you on.
