### ISSUE TITLE
map in different view than index.html

### ISSUE THREAD

**Issue by menicPL** [mapsplugin/cordova-plugin-googlemaps#1072]
First of all, the basic example of index.html with map script is working ok on android.
But what I want is to have the map view available in modal popup window or on another screen/page/activity.
In modal js function where I load tpl Im setting up a map with standard code. Got successful debug code from onMapReady() function but there is no map. Instead there is a blank/transparent space. 
My logcat is:

> I/chromium: [INFO:CONSOLE(19371)] "loadMappppppppppppppppp", source: file:///android_asset/www/app.js (19371)
I/zzai: Making Creator dynamically
W/art: Suspending all threads took: 5.682ms
I/art: Background partial concurrent mark sweep GC freed 16240(1173KB) AllocSpace objects, 5(160KB) LOS objects, 39% free, 9MB/16MB, paused 6.831ms total 25.659ms
D/ChimeraCfgMgr: Reading stored module config
W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000007/n/armeabi-v7a
W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000007/n/armeabi
D/ChimeraFileApk: Primary ABI of requesting process is armeabi-v7a
D/ChimeraFileApk: Classloading successful. Optimized code found.
I/Google Maps Android API: Google Play services client version: 9452000
I/Google Maps Android API: Google Play services package version: 9452436
I/c: Token loaded from file. Expires in: 419263487 ms.
I/c: Scheduling next attempt in 418963 seconds.
I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
W/art: Suspending all threads took: 9.922ms
I/chromium: [INFO:CONSOLE(19355)] "onmap ready fun", source: file:///android_asset/www/app.js (19355)
W/Google Maps Android API: GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API: GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API: GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API: GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API: GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API: GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/DynamiteModule: Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:1
I/DynamiteModule: Selected remote version of com.google.android.gms.googlecertificates, version >= 1
W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000006/n/armeabi
D/ChimeraFileApk: Primary ABI of requesting process is armeabi-v7a
D/ChimeraFileApk: Classloading successful. Optimized code found.
D/GoogleCertificates: com.google.android.gms.googlecertificates module is loaded
D/GoogleCertificatesImpl: Fetched 163 Google release certificates
D/GoogleCertificatesImpl: Fetched 318 Google certificates
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op

Im using framework7 on cordova.

**Comment by Hirbod** [comment]
The map is placed under the webview, not under a DOM node. Please read the documentations carfully to understand, how this plugin works

**Comment by sidgujrathi** [comment]
Hi, I am also facing same issue, can you please tell the solution for it. i didnt understand what this means : "The map is placed under the webview, not under a DOM node"

**Comment by Hirbod** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#how-does-the-plugin-work

**Comment by sidgujrathi** [comment]
SO does that meant I can not have google map on views?

**Comment by Hirbod** [comment]
correct!
