### ISSUE TITLE
push a new npm package

### ISSUE THREAD

**Issue by AjawadMahmoud** [mapsplugin/cordova-plugin-googlemaps#1074]
The master branch is very stable yet not pushed to npm.
can you please push it to npm so we can use it with phonegap build. unfortunately, i'm unable to build the app with the service with the git version. it seems the service is buggy when it comes to git sources with params.

**Comment by wf9a5m75** [comment]
We are working on for the next version, but not ready yet. Please wait for it, or use another map plugin if you can't wait.
