### ISSUE TITLE
location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION

### ISSUE THREAD

**Issue by kelvinrolex** [mapsplugin/cordova-plugin-googlemaps#1078]
Please I followed Josh Morony's tutorial http://www.joshmorony.com/integrating-native-google-maps-into-an-ionic-2-application/, I have implemented every thing, but when i run on my device and view the console on Chrome browser I see an error message that is making the Map not to open on my device, the error message reads (location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION).  Please how do i fix this issue.
![map](https://cloud.githubusercontent.com/assets/10676937/17856843/4de80da4-6877-11e6-880a-c22ac4a62982.PNG)

**Comment by kelvinrolex** [comment]
Solved by installing the Master branch....

**Comment by LtotheWT** [comment]
hi @kelvinrolex How do you install the master branch ?
