### ISSUE TITLE
Trying to use PlacesService

### ISSUE THREAD

**Issue by s-khan-net** [mapsplugin/cordova-plugin-googlemaps#1079]
Hi, Thanks for this plugin
Looking at the geocode example 
` plugin.google.maps.Geocoder.geocode(request, function(results) {`
, I tried using google PlacesService  like
```
           var request = {
                    location: center,
                    radius: 8000,
                    type: ['store']
                };
            plugin.google.maps.PlacesService.radarSearch(request, function(results) {
                alert(results.length);
            });
```

Should I do something in the config file or am I missing something in code?
PS. I'm using PhoneGap Build

**Sorry, I had not seen the code, I guess PlacesService or AutoComplete are not implemented

Is there a possibility of getting this?**

**Comment by celron** [comment]
The only way you can get PlacesService to work would be to instantiate a map using google mapsjavascript libraries, not this plugin.  While Google recently released native API's for places, I don't believe that it is in the scope of this project to implement them.

**Comment by s-khan-net** [comment]
Yes thank you
But again is it possible to call the placeservice from JS and use the results on this map
If so, this will increase the JavaScript API quota, wouldn't it?

**Comment by celron** [comment]
It is possible to call placeService from js and use the results on the plugin map.  I believe the placeServices api has it's own quota separate from any map calls, but you are correct using a javascript map with the plugin map will increase the calls.

**Comment by s-khan-net** [comment]
Thank you
I hope this plugin gets an upgrade 
Thanks again

**Comment by braianj** [comment]
Could you make it? 'cause the service is attached to the map `var service = new google.maps.places.PlacesService(map);`

**Comment by wf9a5m75** [comment]
I decided to start fundraising for creating another plugin of Google Places API.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1888
