### ISSUE TITLE
External Service doesn't open map in google map 

### ISSUE THREAD

**Issue by aaabidunique** [mapsplugin/cordova-plugin-googlemaps#1082]
I have installed google map in mobile trying to launch external service using below syntax

plugin.google.maps.external.launchNavigation({
  "from": "Tokyo, Japan",
  "to": "Kyoto, Japan"
});

but it always opens apple map instead of google map.
FYI code is working fine in android, problem with ios only.

**Comment by Hirbod** [comment]
Should be possible to force Google Maps
https://developers.google.com/maps/documentation/ios-sdk/urlscheme

But I am not sure if that is "best case". You can't rely on that Google Maps App is installed, and I am not sure if checking app availability is still possible since iOS 9.

**Comment by aaabidunique** [comment]
Maybe you can do something like this
https://github.com/dpa99c/phonegap-launch-navigator

**Comment by wf9a5m75** [comment]
I think you are already resolve this issue using [phonegap-launch-navigator](https://github.com/dpa99c/phonegap-launch-navigator),
but the [commit](https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/c2a7a8c408f1c4b177b1531b80a9f5d21a9d09fc) should resolve your original issue.

However, I agree the [phonegap-launch-navigator](https://github.com/dpa99c/phonegap-launch-navigator) is better than the external service.
