### ISSUE TITLE
Map not displayed in android marshmallow

### ISSUE THREAD

**Issue by norvinjohn** [mapsplugin/cordova-plugin-googlemaps#1084]
Hello guys,

Did any of you encountered a problem wherein the map is not displayed in android marshmallow.

**Comment by wf9a5m75** [comment]
```
$> cordova plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
```

**Comment by ajayambre** [comment]
Even I am not able to see map on Android 6.0.1
Followed this tutorial http://www.joshmorony.com/ionic-2-how-to-use-google-maps-geolocation-video-tutorial/

**Comment by norvinjohn** [comment]
@wf9a5m75 tried to reinstall everything I even updated my sdk

@ajayambre I'am currently implementing it to an v1 of ionic

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=ionic&type=Issues&utf8=%E2%9C%93

This plugin (the master branch) works fine with Android 6.0.1.
The most problem is the ionic covers on the map in browser.
The map view (native view) is located **under the browser view**, 
so the background of the map div and their parent nodes must be **transparent**.

**Comment by wf9a5m75** [comment]
Regerding of @ajayambre 's comment, ** it's Google Maps JavaScript API, not this plugin**.

@ajayambre Are you still in stack of this issue? If so, please update with new information. Otherwise, we will close this issue.

**Comment by Khsed4** [comment]
@wf9a5m75 I'm having the same issue with ionic4. The app is working on android 5, 7, 8. but not 6.
Can you help me?
