### ISSUE TITLE
Disable map centering on marker click 

### ISSUE THREAD

**Issue by tlaverdure** [mapsplugin/cordova-plugin-googlemaps#1085]
Is there a way to disable the map from being centered when you click on a marker?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#disable-auto-pan

**Comment by tlaverdure** [comment]
Thank you, appreciate the help! I couldn't find that with the search bar. Must have been using the wrong set of keywords.
