### ISSUE TITLE
getZoom() undefined

### ISSUE THREAD

**Issue by yissok** [mapsplugin/cordova-plugin-googlemaps#1086]
Hi  :)
I followed a lot of answers here on git and they have been a huge help!
by any chance is there a way to get information about the zoom or the unit of measure? (_map.getZoom()_ does not create an error, it just returns _'undefined'_)
Any help at all is greatly appreciated
Thanks

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#get-the-camera-position

**Comment by yissok** [comment]
thank you so much 👍  :)
