### ISSUE TITLE
ReferenceError: Can't find variable: plugin

### ISSUE THREAD

**Issue by zjx** [mapsplugin/cordova-plugin-googlemaps#1087]
Hi guys,
I encountered a problem while trying this plugin in browser directly:

```
          // Invoking Map using Google Map SDK v2 by dubcanada
          var map = plugin.google.maps.Map.getMap(div,{
```

ReferenceError: Can't find variable: plugin

does this plugin support desktop browser as well as android hybrid app?

**Comment by RonaldPK** [comment]
Like all Cordova plugins, this plugin only runs in Cordova apps on devices, including simulators.

**Comment by NestorAcevedo** [comment]
Running Simulator with Apache Ripple the error is the same: _Uncaught ReferenceError: plugin is not defined_

**Comment by wf9a5m75** [comment]
Hi guys, please test this plugin **WITH VERY SIMPLE CODE** at the first.

The **VERY SIMPLE CODE** means, create a new project, do not install other plugins, do not use any JS frameworks, create simple code like the tutorial.
Remember, please don't install the plugin before platforms are added.

**Comment by NestorAcevedo** [comment]
Step by step to reproduce the error:
* Created new VS 2015 Project, selecting Apache Cordova Blank app
* Select iOS as platform
* build to add iOS on Apache Cordova
* Install the plugin as shown in https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Windows
* Compiled again 
* Run simulation on Apache Ripple via VS run

Get the same uncaught referenceerror

**Comment by NestorAcevedo** [comment]
Step by step to reproduce the error:
* Created new VS 2015 Project, selecting Apache Cordova Blank app
* Select iOS as platform
* build to add iOS on Apache Cordova
* Install the plugin as shown in https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Windows
* Compiled again 
* Run simulation on Apache Ripple via VS run

Get the same uncaught referenceerror

**Comment by wf9a5m75** [comment]
@NestorAcevedo 
Thank you for the log, but it seems the log does not contain the records of installing the `cordova-plugin-googlemaps` plugin.

**Comment by NestorAcevedo** [comment]
Hi @wf9a5m75 
Just I run a new project, same steps but  moving all javascript from index.html to index.js.

Now I am not getting anything about undefined plugin, now I am getting some like:

_missing exec:GoogleMaps.getMap
ripple.js:48 GoogleMaps
ripple.js:48 getMap
ripple.js:41 missing exec:GoogleMaps.isAvailable
ripple.js:48 GoogleMaps
ripple.js:48 isAvailable_

and some additional (I think incoming from Chrome or Ripple):
**_GoogleMaps.isAvailable

We seem to be missing some stuff :(

What is kinda cool though you can fill in the textarea to pass a json object to the callback you want to execute_**


[vs-log.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/457896/vs-log.txt)
[vs-log-gmaps.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/457895/vs-log-gmaps.txt)

**Comment by wf9a5m75** [comment]
Could you share the project?

**Comment by wf9a5m75** [comment]
> 1>  Fetching plugin "cordova-plugin-googlemaps" via npm
According of your vs-log-gmaps.txt, you install the plugin from npm.

Please install from the master branch.
https://github.com/mapsplugin/cordova-plugin-googlemaps#quick-install

**Comment by NestorAcevedo** [comment]
Hi @wf9a5m75 

As I said before, I followed the instrtuctions on https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Windows adding
`<vs:plugin name="plugin.google.maps">
    <param name="API_KEY_FOR_ANDROID" value="YOUR_API_KEY_IS_HERE" />
    <param name="API_KEY_FOR_IOS" value="YOUR_API_KEY_IS_HERE" />
</vs:plugin>`
to config.xml on Visual Studio

The sample project is on https://1drv.ms/f/s!Am9wQZJr33R1k2mauSr3Q1rJIozr

**Comment by wf9a5m75** [comment]
Thank you for sharing your project.

I checked your blank project, and you installed from the npm version, which does not Cordova-ios@4.0.
In order to use this plugin, use Cordova-ios@3.9 or install from the master branch.
https://github.com/mapsplugin/cordova-plugin-googlemaps#information

At the last, please share your project on github next time instead of One drive.
Zip file is un-useful for reviewing.

**Comment by NestorAcevedo** [comment]
OK altouhg I shared the full VS project and as basic app the filesize is up to 50MB.

I edited my previous post saying about how did I installed the plugin in my full project.

**Comment by wf9a5m75** [comment]
I'm not familiar with Visual Studio. Sorry.

**Comment by wf9a5m75** [comment]
How about like this?
```
<vs:plugin name="https://github.com/mapsplugin/cordova-plugin-googlemaps">
```

**Comment by NestorAcevedo** [comment]
All is right for now in my case, after removing and adding many times the plugin.

What I notice is regarded to Ripple service:
missing exec:GoogleMaps.isAvailable
ripple.js:48 GoogleMaps
ripple.js:48 isAvailable
ripple.js:41 missing exec:GoogleMaps.getMap
ripple.js:48 GoogleMaps
ripple.js:48 getMap

and that is causing the popup with the message
_GoogleMaps.isAvailable

We seem to be missing some stuff :(

What is kinda cool though you can fill in the textarea to pass a json object to the callback you want to execute_

I will test in XCode simulator and I will update some results here.

**Comment by wf9a5m75** [comment]
I thinks you(everyone in this thread) use the npm version.
However the official document is already changed.
So some properties are not available in the npm version, but the master branch version is available.

Please use the master branch version.

```
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID....
```

**Comment by NestorAcevedo** [comment]
@wf9a5m75 I already did and in my case, as I said before, the new issue is related to Apache Ripple Simulator.

**Comment by wf9a5m75** [comment]
I have never used the Apache Ripple, it means the Apache Ripple  is not supported.
Please solve your issue by yourself.

Another chance, you can try the v2-beta. Might be solved the issue.
https://github.com/mapsplugin/cordova-plugin-googlemaps#version-20-beta

**Comment by wf9a5m75** [comment]
Did you try like this?
```window["plugins"].google.maps.Map.getMap()```

**Comment by wf9a5m75** [comment]
**update**

The ionic framework kills this plugin package name for some reason.
In that case, you can use like this `window["plugins"].google.maps.Map.getMap`.

**Comment by rayarchiem** [comment]
I have been fighting this problem also.  I have started over from scratch multiple times and followed the guidance to install and use the cordova-plugin-googlemaps with my Monaca app.  I swear that I have followed the guidance exactly with the same error repeatedly occurring.  I have been using this for reference: https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/hello-world/README.md.  

I have installed the plugin and put my API keys into config.xml  

The code that throws the error:      var map = new plugin.google.maps.Map

The above code is inside a device ready event listener function. 

Here is the error: ReferenceError: Can't find variable: plugin

Can someone who has successfully used the cordova-plugin-googlemaps please provide some feedback or any advice.  I feel like this plugin doesn't work the way it's documented but I know that  is unlikely, so I must be doing something wrong.

**Comment by wf9a5m75** [comment]
`plugin.google.maps.Map.getMap()` after the `deviceready` event.
