### ISSUE TITLE
Use with cordova-plugin-ace

### ISSUE THREAD

**Issue by b4tch** [mapsplugin/cordova-plugin-googlemaps#1090]
I would like to use the cordova-plugin-ace plugin to add a TabBar to my app, but if I initialise the ace TabBar (which creates a new native page) before initialising the googlemaps plugin, the googlemaps plugin overwrites the ace page (and vice versa if initialised the other way around).  Is there any way to tell this plugin to initialise _inside_ the current native page rather that creating a new one?

**Comment by wf9a5m75** [comment]
We don't support compatibility with other plugins. That's too much work. Please adjust by yourself. Sorry.
