### ISSUE TITLE
Div over the map hard to click/fire function

### ISSUE THREAD

**Issue by Hurinj** [mapsplugin/cordova-plugin-googlemaps#1091]
I have one div with an img over the map which is on top.
When I click on one specific (like 10% of the div) space of the img, it fires the function I want.
But if i click on the 90% left of the img nothing it fired. 

Is there a way to correct this bug ?
If I set the map clickable to false, there is no problem but I'd like to keep the map clickable.

Thank you.

**Comment by wf9a5m75** [comment]
On the master branch, the the img tag must be **under** the map div.
```html
<div id="map_div">
  <img src='...'>
</div>
```

**Comment by Hurinj** [comment]
Yes I know, in fact it is a normal div with a font awesome icon.
I call a ng-click like above. It only calls the ng-click in a specific place of the div :/
Here is my code : 

```
<div class="row" style="width: 100%; margin-left: 0px;">\
                                        <div id="appeler" class="col-lg-6 col-sm-6 col-xs-6" ng-click="mapCtrl.createConversationDiv();">\
                                        <i class="fa fa-commenting-o fa-5x" style="color: #5bf6a3; margin-top: 15px;"></i>\
                                            <div class="ligne_verticale" ></div>\
                                        </div>\
                                        <div id="present" class="col-lg-6 col-sm-6 col-xs-6" ng-click="mapCtrl.checker()">\
                                            <i class="fa fa-check fa-5x" style="color: #5bf6a3; margin-top: 18px;"></i>\
                                        </div>\
                                    </div>
```

**Comment by wf9a5m75** [comment]
I'm sorry but I'm not familiar with Angular at all.
Could you show me the screen capture?

**Comment by Hurinj** [comment]
Yes this is the top div html with the icon commenting

<div class="row" style="width: 100%; margin-left: 0px;">
        <div id="appeler" class="col-lg-6" ng-click="mapCtrl.createConversationDiv();">
                  <i class="fa fa-commenting-o fa-5x" style="color: #5bf6a3; margin-top: 15px;"></i>
</div>

represented by : 
![img_5695](https://cloud.githubusercontent.com/assets/18547740/18294883/e7dabade-749c-11e6-9f5b-c8bf21659f92.jpg)

**Comment by wf9a5m75** [comment]
Um, I'm not clear yet.
It seems the map div is bigger than <body> tag?

And could you take a screen capture with `map.setDebuggable(true)`?
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#mapsetdebuggable

`map.setDebuggable( true )` tells you where the plugin recognizes the clickable region (red and green).

**Comment by Hurinj** [comment]
The map div is map_canvas, it contains the previous code.

It is really weird, with the debuggable true, the div has no color (green or red) ... !

```
<div ng-controller="MapController as mapCtrl" style="height:100%;width:100%;" id="map_canvas">
...
<div class="row" style="width: 100%; margin-left: 0px;">
        <div id="appeler" class="col-lg-6" ng-click="mapCtrl.createConversationDiv();">
        <i class="fa fa-commenting-o fa-5x" style="color: #5bf6a3; margin-top: 15px;"></i>
</div>
...
</div>
```

I put the div in white to see if it was red or green, but there is nothing.

![img_5697](https://cloud.githubusercontent.com/assets/18547740/18303045/62f14074-74db-11e6-9141-42c8ea67cab0.png)

**Comment by wf9a5m75** [comment]
Do you set `position: fixed` or something?

Or if you change the position of child elements, you have to execute `map.refreshLayout()`. Do you do that?

**Comment by Hurinj** [comment]
Yes it is fixed position because don't want the user be able to scroll .. 
What can I do ?

**Comment by wf9a5m75** [comment]
`position: fixed` is not supported for the current version (probably, I forgot the detail).
So you can not use it.

Instead of that, how about `display: none` and `display:block`?

**Comment by Hurinj** [comment]
Ok, thank you very much for your time !
It is working with `display: block`
:)

**Comment by wf9a5m75** [comment]
Sound great!
