### ISSUE TITLE
google map build error

### ISSUE THREAD

**Issue by talhamit** [mapsplugin/cordova-plugin-googlemaps#1092]
HI,
any one can help me about the below issue that i mention.

The following build commands failed:
```
	CompileC build/blank.build/Debug-iphonesimulator/blank.build/Objects-normal/i386/GoogleMaps.o blank/Plugins/plugin.google.maps/GoogleMaps.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/lucky/Documents/projects/blank/platforms/ios/cordova/build-debug.xcconfig,-project,blank.xcodeproj,ARCHS=i386,-target,blank,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/lucky/Documents/projects/blank/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/lucky/Documents/projects/blank/platforms/ios/build/sharedpch.
```

I have added the latest ios platform ios@4.0

**Comment by b4tch** [comment]
I had a very similar error when I added a different plugin (cordova-plugin-ace) and tried to build.  Turns out it was conflicting with another plugin and once I removed the (fortunately not required) conflicting plugin it resolved this issue.

**Comment by wf9a5m75** [comment]
Please use the master branch version.
https://github.com/mapsplugin/cordova-plugin-googlemaps#information
