### ISSUE TITLE
IOs build and IntelXDK

### ISSUE THREAD

**Issue by afxgroup** [mapsplugin/cordova-plugin-googlemaps#1093]
Hello,
i'm trying to build my project using intel XDK and while on iOS i have no error and all is build correctly, on iOS i receive this error:
```
In file included from .../cordova_project/platforms/ios/Glance On Surface/Plugins/plugin.google.maps/Circle.m:9:
In file included from .../cordova_project/platforms/ios/Glance On Surface/Plugins/plugin.google.maps/Circle.h:9:
.../cordova_project/platforms/ios/Glance On Surface/Plugins/plugin.google.maps/GoogleMaps.h:10:9: fatal error: 'GoogleMaps/GoogleMaps.h' file not found
#import <GoogleMaps/GoogleMaps.h>
```
The iOS SDK is installed correctly since it is a dependency:

![gmapsios](https://cloud.githubusercontent.com/assets/484672/18254448/2cae0f8a-739e-11e6-996c-16ce9bb1bff5.png)

What's wrong? i'm using cli 5.4.1

**Comment by wf9a5m75** [comment]
Please use the master branch version. It seems the master branch version works probably.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=GoogleMaps.h+file+not+found&type=Issues&utf8=%E2%9C%93

**Comment by afxgroup** [comment]
mmm.. i'm using the master branch version but the problem is always there. It seems that symbolic links in iOS SDK are not recognized correctly by builders

**Comment by afxgroup** [comment]
well, i've resolved my problem changing "Current" path slice to "A" directly. So for example GoogleMaps file become Versions/A/GoogleMaps (from Versions/Current/GoogleMaps). This fix the compilation problem

**Comment by wf9a5m75** [comment]
Good 👍 
While the Google Maps SDK for iOS includes symbolic links, however windows does not support them.
In that case, you need to copy the directory by your hand (like you did).
