### ISSUE TITLE
error on framewor7 cordova dont work all controls after load the map

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#1095]
im tryng to use cordova with framework7 and this plugin map but after loaded the map, i cant use any controls of framework7 , i dont know what is the bug because i dont have how debug, this bug i have been seen too on bootstrap, can some one help me?

**Comment by wf9a5m75** [comment]
We don't support compatibility with any JS frameworks.
Sorry, but it's too much work for us.
Please adjust/resolve your issue by yourself.
