### ISSUE TITLE
App reject / non-public api imageWithName/nextStartIndex

### ISSUE THREAD

**Issue by clshack** [mapsplugin/cordova-plugin-googlemaps#1098]
Hi,
our iOS app was recently rejected for using/referencing the following non-public APIs:

- imageWithName
- nextStartIndex

I sent the app few times and I sued the latest release of this plugin and also the dev branch but nothing changed.

To my understanding this was fixed by Google in version 1.13.2 (See issue):
https://code.google.com/p/gmaps-api-issues/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Introduced%20Fixed%20Summary%20Stars%20ApiType%20Internal&groupby=&sort=&id=9704

How I can fix it ? 

Thanks.

**Comment by wf9a5m75** [comment]
Merge into #1047
