### ISSUE TITLE
Crash while dismissing zoom picker

### ISSUE THREAD

**Issue by craig-at-rsg** [mapsplugin/cordova-plugin-googlemaps#1100]
I just received this error report - any idea if there's something I can do to fix it, or if the code in the project needs to be fixed.

```
Fatal Exception: java.lang.IllegalArgumentException
Receiver not registered: android.widget.ZoomButtonsController$1@c8a017e
 Raw Text
android.app.LoadedApk.forgetReceiverDispatcher (LoadedApk.java:878)
android.widget.ZoomButtonsController.setVisible (ZoomButtonsController.java:404)
org.chromium.android_webview.AwZoomControls.dismissZoomPicker (AwZoomControls.java:38)
org.chromium.content.browser.ContentViewCore.onDetachedFromWindow (ContentViewCore.java:1537)
org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDetachedFromWindow (AwContents.java:3166)
org.chromium.android_webview.AwContents.onDetachedFromWindow (AwContents.java:2398)
com.android.webview.chromium.WebViewChromium.onDetachedFromWindow (WebViewChromium.java:1847)
com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished (WebViewContentsClientAdapter.java:531)
org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage (AwContentsClientCallbackHelper.java:188)
android.os.Handler.dispatchMessage (Handler.java:102)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

**Comment by wf9a5m75** [comment]
ZoomButtonsController.java is not this plugin.
I think it's depends on your code when the map is removed, or something.
Until you provide more certain information, such as the code which reproduces the issue 100%, we can not help this.

**Comment by craig-at-rsg** [comment]
I don't think it has anything to do with my code - I'm not handling zooming at all. 

It looks like this is a bug with Android that maybe this plugin can workaround? Here are the details, along with steps to reproduce: http://stackoverflow.com/questions/5267639/how-to-safely-turn-webview-zooming-on-and-off-as-needed

**Comment by wf9a5m75** [comment]
Try this at once in your local.
http://stackoverflow.com/a/34176342/697856

I can not reproduce your issue, and it's not this plugin issue.

**Comment by craig-at-rsg** [comment]
Thanks, but I haven't written any WebView or map related Java code in my project - I'm only interacting with the maps through this plugin, so trying that solution isn't easy. 

I'm closing this issue - you don't think it applies to your plugin, and I don't think it applies to my code, so it must not exist ;).

**Comment by wf9a5m75** [comment]
Thank you for understanding. 
Without certain reproduce code, debugging is so hard.
It's really depends on your code, the plugins you use, WebView version, etc...
That's why I can not help you.
