### ISSUE TITLE
GetDataUrl without loading map on view

### ISSUE THREAD

**Issue by Waniusza** [mapsplugin/cordova-plugin-googlemaps#1101]
Hi,
Thanks for this plugin, it's helpful a much;

Unfortunately, I got one problem, hope you can help;

I know it's not recommended to save map as base64-coded image, but in my case I need load it later without internet connection.
So I tried to convert it with .toDataURL(), but it breaks app like on [issue #388](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/388).

I tested it on:
Samsung Galaxy Tab A 
Android v5.0.2
Cordova v6.2

My code looks like:

    var map = plugin.google.maps.Map.getMap(DOMelement);
    map.setOptions(mapOptions);
    map.setCenter(centerLatLng);
    map.addEventListener(plugin.google.maps.event.MAP_READY, function onMapInit(map) {
        map.addMarker({
            'position': {
                lat: lat,
                lng: lng
            },
            'title': 'msg'
        }, function (marker) {
            DOMelement.class = DOMelement.class === undefined ? " mapField " : DOMelement.class + " mapField ";
            map.toDataURL(function (dataUrl) {
                DOMelement.src = dataUrl;
            });
        });
    });

Probably it's out of memory problem, like you suggest on issue #388;

To avoid memory usage I want to load map 64base-coded image without loading it on the view.
Is it possible there? Or could it be done soon?

**Comment by wf9a5m75** [comment]
You MUST wait the MAP_READY event before execute any statements.

**Comment by Waniusza** [comment]
Right, thanks, it's important to remember.

But still, code below firstly load map on DOMelement, and only then try to convert map onto base64 image. 
Can I convert it without editing DOM structure and showing transparent native image?

    var map = plugin.google.maps.Map.getMap(DOMelement);
    map.addEventListener(plugin.google.maps.event.MAP_READY, function onMapInit(map) {
        map.setOptions(mapOptions);
        map.setCenter(centerLatLng);
        map.addMarker({
            'position': {
                lat: lat,
                lng: lng
            },
            'title': 'msg'
        }, function (marker) {
            console.log("TEST === marker ustanowiony ", marker);
            DOMelement.class = DOMelement.class === undefined ? " mapField " : DOMelement.class + " mapField ";
    // LINE BELOW BREAKS APP
    //            map.toDataURL(function (dataUrl) {                                   
    //                console.log("TEST === dataUrl ", dataUrl);
    //                img.src = dataUrl;
    //            });
        });
    });

**Comment by wf9a5m75** [comment]
// LINE BELOW BREAKS APP
//            map.toDataURL(function (dataUrl) {                                   
//                console.log("TEST === dataUrl ", dataUrl);
//                img.src = dataUrl;
//            });
Please provide the full error logs.

**Comment by Waniusza** [comment]
Hope this fragment would be helpful.
It's happens only when code below is not commented 

    map.toDataURL(function (
        console.log("TEST === dataUrl ", dataUrl);
        img.src = dataUrl;
    });

I/zzai    ( 4208): Making Creator dynamically
W/ResourcesManager( 4208): Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
W/ResourcesManager( 4208): Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
D/ChimeraCfgMgr( 4208): Reading stored module config
D/ChimeraFileApk( 4208): Primary ABI of requesting process is armeabi-v7a
I/art     ( 4208): DexFile_isDexOptNeeded failed to open oat file '/data/dalvik-cache/arm/data@data@com.google.android.gms@app_chimera@m@00000001@DynamiteModulesB_GmsCore_prodlmp_alldpi_release.apk@classes.dex' for file location '/data/data/com.google.android.gms/app_chimera/m/00000001/DynamiteModulesB_GmsCore_prodlmp_alldpi_release.apk': Failed to open oat filename for reading: No such file or directory
D/ChimeraFileApk( 4208): Classloading successful, but code may not be optimized. It will either run in fallback (interpreted mode) or the odex has been found and isDexOptNeeded is misreporting a failure.
I/Google Maps Android API( 4208): Google Play services client version: 9452000
I/Google Maps Android API( 4208): Google Play services package version: 9452230
I/c       ( 4208): Token loaded from file. Expires in: 273239518 ms.
I/c       ( 4208): Scheduling next attempt in 272939 seconds.

[ SOME MORE NOT IMPORTANT LOGS ]

I/System.out( 4208): (HTTPLog)-Static: isSBSettingEnabled false
I/qtaguid ( 4208): Tagging socket 159 with tag 3000110100000000{805310721,0} for uid -1, pid: 4208, getuid(): 10211
I/qtaguid ( 4208): Tagging socket 183 with tag 3000110100000000{805310721,0} for uid -1, pid: 4208, getuid(): 10211
D/GoogleMapsPlugin( 4208): (debug)action=exec args[0]=Map.setOptions
D/GoogleMapsPlugin( 4208): (debug)action=exec args[0]=Map.setCenter
I/qtaguid ( 4208): Untagging socket 159
D/GoogleMapsPlugin( 4208): (debug)action=exec args[0]=Marker.createMarker
W/System.err( 4208): java.lang.reflect.InvocationTargetException
W/System.err( 4208): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4208): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 4208): 	at plugin.google.maps.MyPlugin.execute(MyPlugin.java:49)
W/System.err( 4208): 	at plugin.google.maps.GoogleMaps$3.run(GoogleMaps.java:262)
W/System.err( 4208): 	at android.os.Handler.handleCallback(Handler.java:739)
W/System.err( 4208): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 4208): 	at android.os.Looper.loop(Looper.java:145)
W/System.err( 4208): 	at android.app.ActivityThread.main(ActivityThread.java:6117)
W/System.err( 4208): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4208): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 4208): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
W/System.err( 4208): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
W/System.err( 4208): Caused by: java.lang.NullPointerException: null camera target
W/System.err( 4208): 	at com.google.android.gms.common.internal.zzab.zzb(Unknown Source)
W/System.err( 4208): 	at com.google.android.gms.maps.model.CameraPosition.<init>(Unknown Source)
W/System.err( 4208): 	at com.google.android.gms.maps.model.CameraPosition.<init>(Unknown Source)
W/System.err( 4208): 	at com.google.android.gms.maps.model.CameraPosition$Builder.build(Unknown Source)
W/System.err( 4208): 	at plugin.google.maps.PluginMap.setOptions(PluginMap.java:115)
W/System.err( 4208): 	... 12 more
I/chromium( 4208): [INFO:CONSOLE(39)] "TEST === marker ustanowiony ", source:  (39)
D/GoogleMapsPlugin( 4208): (debug)action=exec args[0]=Map.toDataURL
E/AndroidRuntime( 4208): FATAL EXCEPTION: Thread-18770
E/AndroidRuntime( 4208): Process: com.test.AEMobile, PID: 4208
E/AndroidRuntime( 4208): java.lang.IllegalArgumentException: width and height must be > 0
E/AndroidRuntime( 4208): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
E/AndroidRuntime( 4208): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:918)
E/AndroidRuntime( 4208): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:885)
E/AndroidRuntime( 4208): 	at maps.ad.ag.b(Unknown Source)
E/AndroidRuntime( 4208): 	at maps.ad.u$4.run(Unknown Source)
E/AndroidRuntime( 4208): 	at java.lang.Thread.run(Thread.java:818)
V/ApplicationPolicy(  849): isApplicationStateBlocked userId 0 pkgname com.test.AEMobile
V/ApplicationPolicy(  849): isApplicationStateBlocked userId 0 pkgname com.test.AEMobile
V/ApplicationPolicy(  849): isApplicationStateBlocked userId 0 pkgname com.sec.android.app.launcher

D/InputDispatcher(  849): Focused application set to: xxxx

D/InputDispatcher(  849): Focus left window: 4208
W/ActivityManager(  849):   Force finishing activity com.test.AEMobile/.MainActivity

**Comment by wf9a5m75** [comment]
> E/AndroidRuntime( 4208): java.lang.IllegalArgumentException: width and height must be > 0
I guess the DOMelement is not under the <body>.

**Comment by Waniusza** [comment]
Hi,

I solved problem.

Your answers was very successfully,
Problem was I tried to put map into element:

    <div id="test">
    </div>

I missed     style="width: something; heigth: something".

Now I know it's so important :)

Not sure I missed something in documentation, but it will be great to focus that size styles should be defined BEFORE define map.

Thanks for your work!
