### ISSUE TITLE
Code does not execute inside MAP_CLOSE event iOS

### ISSUE THREAD

**Issue by blackeagle1111** [mapsplugin/cordova-plugin-googlemaps#1103]
I dont know if anyone experiences this problem, but it seems to me that my code inside the MAP_CLOSE event does not execute when a map is closed. It is working just fine on Android. Any suggestion on this issue?
```
map.on(plugin.google.maps.event.MAP_CLOSE, function () {
  console.log("Close");                                        
});
```

**Comment by wf9a5m75** [comment]
It seems it's related with https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/554

**Comment by blackeagle1111** [comment]
thank you
