### ISSUE TITLE
Adding icon to the marker causing app crash.

### ISSUE THREAD

**Issue by shahbazkhan054** [mapsplugin/cordova-plugin-googlemaps#1105]
I am trying to add custom icon image to marker but as I am passing parameter to addMarker options, the app is getting crashed.

` map.addMarker({
                'position': pos,
                'title': 1,
                'icon': {
                    'url': '../images/map-marker-red.png'
                },`

When I am commenting the icon, default markers are loading normally.
Please help.

**Comment by wf9a5m75** [comment]
Same as #1106
