### ISSUE TITLE
marker.setIcon is not working 

### ISSUE THREAD

**Issue by shahbazkhan054** [mapsplugin/cordova-plugin-googlemaps#1106]
I am using marker.setIcon as below and it's not working.
`marker.setIcon({ 'url': '../images/1.png' });`

**Comment by wf9a5m75** [comment]
>You can use one of the following protocol: https, file, cdvfile and the file absolute path. (Android also accepts file:///android_asset/)

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#simple-icon
