### ISSUE TITLE
Custom icons cause performance problems?

### ISSUE THREAD

**Issue by TheMassassian** [mapsplugin/cordova-plugin-googlemaps#111]
Hi there,

I'm running at the moment some performance tests for an application.
I have a json with quite a lot entries. Each entry is a marker on the map.
Without a custom icon the application runs well, but if i give each marker a custom icon the application runs very slow. I'm using a png file for the icon which is located in the www/img folder. Tested on ipad 3 (very slow) and Samsung Galaxy S4 (slow)

Greetings

<b>UPDATE: </b>
Now that I changed the size of the original image instead of setting the size in the icon properties the application runs better.

Is there a way to use .svg files for the icons ?

**Comment by Moulde** [comment]
I thought i just ran into the same performance issue, but it seems that running the app from phonegap run andoid cmd, will make the performance much better then running it directly from eclipse.
I just thought i would add this if anyone else runs into the same thing, and starts looking for performance issues that are not there.

**Comment by leandro-shifteight** [comment]
@wf9a5m75 is posible now to load svg icons?

**Comment by wf9a5m75** [comment]
Not possible now.
