### ISSUE TITLE
setPadding()

### ISSUE THREAD

**Issue by arielgelbard** [mapsplugin/cordova-plugin-googlemaps#1111]
is setPadding working for anyone? I don't see any adjustment to the map when I go map.setPadding( 0,0,200,0 );

**Comment by wf9a5m75** [comment]
https://developers.google.com/maps/documentation/android-api/map#map_padding

**Comment by arielgelbard** [comment]
@wf9a5m75 I understand, but does setPadding work for you? I call map.setPadding(0,0,200,0), and nothing changes, the google logo doesn't move either...

**Comment by wf9a5m75** [comment]
Are you talking about Android or iOS?

**Comment by arielgelbard** [comment]
both...but for iOS to start is good :)

**Comment by arielgelbard** [comment]
@wf9a5m75  both...but focusing on iOS, seems to have less things to do in native sdk

**Comment by wf9a5m75** [comment]
![screen shot 2016-09-23 at 12 35 33 pm](https://cloud.githubusercontent.com/assets/167831/18799020/4527ca98-818a-11e6-81c7-6c5f094e1ec4.png)

Perfectly work.

I think you don't wait the MAP_READY event.

**Comment by wf9a5m75** [comment]
```js
document.addEventListener("deviceready", function() {
  var div = document.getElementById("map_canvas");

  // Initialize the map view
  map = plugin.google.maps.Map.getMap(div);

  // Wait until the map is ready status.
  map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
}, false);

function onMapReady() {
  map.setPadding(0,0,200,0);
}
```

**Comment by arielgelbard** [comment]
confirmed! the issue lies in ionic-native it seems, thanks for all your help!
