### ISSUE TITLE
Ionic2 Modals not Clickable

### ISSUE THREAD

**Issue by mehrshadpezeshk** [mapsplugin/cordova-plugin-googlemaps#1112]
Hi, 

First, thank you for this amazing plugin.

I'm trying to use this plugin for our app and we have a big problem with putting HTML elements on top of the map. Our app works with modals and each time we push a Modal to the NavController the modal is not clickable.

We already tried data-tap-disabled="true", scroll="false" on ion-content. The main problem is that we cannot put all the modals inside the map Div.

Please help us !!!

**Comment by wf9a5m75** [comment]
The current version does not support the modal dialog.
You have to put HTML elements **UNDER** the map div.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#put-html-elements-on-the-map

**Comment by wf9a5m75** [comment]
Or you can disable the map during the modal dialog is displayed.
`map.setClickable(true / false)`

**Comment by mehrshadpezeshk** [comment]
ok perfect, I'll try
