### ISSUE TITLE
Plugin slows down my app on Android

### ISSUE THREAD

**Issue by seme1** [mapsplugin/cordova-plugin-googlemaps#1113]
Adding the plugin to my app made it run extremely slow on Android. It was running smoothly before the plugin was added. My test device is Galaxy Nexus (Android 4.3). The map works fine, it's just the performance that has degraded A LOT.

I'm using crosswalk 17. I'm also using the github version of the plugin (added with the following commad:

cordova plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="Replaced_With_My_API_Key"

Any help would be greatly appreciated. The animation, app loading, and everything has slowed down (without even initiating the map).

**Comment by wf9a5m75** [comment]
What version did you use?

**Comment by seme1** [comment]
1.3.9

**Comment by wf9a5m75** [comment]
I see. Why don't you use v1.3.9 instead of the master branch?

**Comment by seme1** [comment]
Thanks. I tried the stable master version of 1.3.9 and it works now smoothly 👍 
Thanks
