### ISSUE TITLE
Android ACCESS_FINE_LOCATION permissions

### ISSUE THREAD

**Issue by chadwhitaker** [mapsplugin/cordova-plugin-googlemaps#1116]
Received the following email from Google Play:

> Hello Google Play Developer,
> 
> We're writing to let you know that the apps listed at the end of this email may be affected by an upcoming platform change.
> 
> Action required: If your app requires GPS hardware to operate properly, you will need to explicitly add the "android.hardware.location.gps" uses-feature to your manifest.
> 
> What’s changing
> 
> We’re making a change on October 15th, 2016 that will affect apps targeting API version 21 (Android 5.0, Lollipop) or higher that use ACCESS_FINE_LOCATION but don't explicitly have the "android.hardware.location.gps" uses-feature. Going forward, these apps will be available to install on devices that don't have GPS hardware. In most cases this won't be an issue since Wi-Fi and Cell-ID based location provides high enough fidelity for the typical operation of these apps. However, any apps that require GPS hardware, such as GPS navigators, should explicitly add the "android.hardware.location.gps" uses-feature to their manifest.
> 
> If your app requires GPS to function properly and you do not include android.hardware.location.gps in your manifest declaration, your users may have a poor app experience.
> 
> Also, if you’re using the fused location provider and wish to receive the most accurate location samples from GPS (i.e. with PRIORITY_HIGH_ACCURACY), you must include the "android.hardware.location.gps" feature in your app’s manifest to ensure that Google Play only distributes your app to devices with GPS sensors.
> 
> You can read more about this change in the [Android Developers Help Center](https://developer.android.com/guide/topics/location/strategies.html#Permission).

Here is more information on the manifest update:
https://forums.adobe.com/thread/2211532

**Comment by wf9a5m75** [comment]
Thanks

**Comment by d-cordeiro-** [comment]
Any ETA on the next version release (which would include this Android permission commit)?

**Comment by wf9a5m75** [comment]
It's already fixed on the current master branch.
