### ISSUE TITLE
Map not rendered with $state.go(...,{params}) if the map has been already initialized

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#1118]
I have some route params:
```
$stateProvider.state('menu.Map',{
...
params:{
myParam:false
}
}
```

And button which open the same state with myParam:integer which calls function wich $state.go('menu.Map',{myParam:123});

**Usecase**
If the map view is opened from side menu (not matter if with ui-sref or $state.go('menu.Map') function), the map is rendered.

After the map is rendered for the first time via ui-sref or $state.go('menu.Map'), I click on button with myParam defined. My MapCtrl is reinitialized (even $IonicView.loaded event is fired) $scope.map is also empty (my map is stored also in $rootScope.map which is not empty). And the map view is completely blank.

**Usecase 2**
The same process is in opposite way: If I click on my button and map is initialized ($stateParams is sent), I can not open the map with different state params.

It seems that the cordova-plugin-googlemaps module works somehow with sent $stateParams and consider it for different view, **if different state params is sent**.

**Comment by wf9a5m75** [comment]
You have to execute `map.remove()`

**Comment by homeportcz** [comment]
I tried this method, executed before map initialized. Did not work.

**Comment by homeportcz** [comment]
Anywasy, removing map due to different stateParams - it is clear way?

**Comment by wf9a5m75** [comment]
The map ia not rendered in browser.
You need to remove the map before changing the different page.
(I don't know what JS framework you use)

Otherwise create map only one time, and change the visibility `map.setVisible(true / false)`

**Comment by homeportcz** [comment]
Hm, before changing page - that will be key to solution. Thanks.

**Comment by wf9a5m75** [comment]
@homeportcz Did you try?

**Comment by wf9a5m75** [comment]
Opps, my mistake.

**Comment by wf9a5m75** [comment]
I think the v2-beta version solves this problem.
Please retry with it.

For the v2-beta version, please read here.
https://github.com/mapsplugin/v2.0-demo/
