### ISSUE TITLE
when keyboard is displayed, text/button inputs below the map disappear [ios10, WKWebview]

### ISSUE THREAD

**Issue by seme1** [mapsplugin/cordova-plugin-googlemaps#1119]
I have two inputs below the map (one text and another is button). After initiating the map, the two inputs appear as expected. When scrolling the page, the two inputs are also normal. However, when clicking the text input below the map, the keyboard shows up and both text and button inputs disappear. When typing any letter on the keyboard, the two inputs appear again. 

I'm using the latest master version of this plugin on ios 10 with WKWebview. I tried to reproduce this with the normal view, however it works as expected. So, I guess this problem is related with only the WKWebview.

**Comment by wf9a5m75** [comment]
> So, I guess this problem is related with only the WKWebview.

I agree with you. Please adjust by yourself.
