### ISSUE TITLE
can't access to camera.target

### ISSUE THREAD

**Issue by wroquet** [mapsplugin/cordova-plugin-googlemaps#112]
```
map.on(plugin.google.maps.event.CAMERA_CHANGE, function(pos){

    var data = JSON.stringify(pos);
    console.log(pos);
    if(pos.zoom >= 7){

        var lat = pos.target.lat;

        var lng = pos.target.lng;

        console.log(lat); //undefined
        console.log(lng); //undefined

        getSitesVTTJSONByDistance(lat, lng)
    }else{
        // map.clear();
    }
});
```

I can't access to the lat lng position when CAMERA_CHANGE, any idea ? thanks in advance

**Comment by ibadrehman90** [comment]
I am still not able to use 

map.getCameraPosition(function(camera) {
  var buff = ["Current camera position:\n",
      "latitude:" + camera.target.lat,
      "longitude:" + camera.target.lng,
      "zoom:" + camera.zoom,
      "tilt:" + camera.tilt,
      "bearing:" + camera.bearing].join("\n");
  alert(buff);
});

I am using your latest version. Please help!
