### ISSUE TITLE
add multiple markers and clear all markers on map ?? how create them? i dont have idea

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#1121]
Hi there im working wit this pluggin but i dont know how create multiple markers on the same map and clear all markers before create them, i use interval time on javascript to load the markers  from my server, any have idea how create this multiple markers?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#create-multiple-markers

**Comment by dsemerida** [comment]
i have been checked but not working , my issue is that i want i set my marker with my location , the marker have to remove and add new with my new location, i gett it but i rewrite the firstmarker, my interval is on 1000 milisecunds

**Comment by wf9a5m75** [comment]
Unlike the Google Maps JavaScript API v3, you can not detach/reatach the marker to the map again.
Only you can do is `map.addMarker()`, and `marker.remove()`.

Or `marker.setVisible(true / false)`

**Comment by dsemerida** [comment]
in my case i wanna to create location automatic on the map change the position of marker while im moving, is for that i need remove all marker and add news or im not sure this is the better way

**Comment by wf9a5m75** [comment]
This plugin does not provide such a feature.
You need to implement by your self.

**Comment by dsemerida** [comment]
i have implement the multiple markers , the way for this is, 1- i set interval time for retrieve my last location, 2- iterate all positions or coords and create marker, but the problem is that the marker position not change never

**Comment by wf9a5m75** [comment]
Show me your code, please.

**Comment by wf9a5m75** [comment]
@dsemerida ping
