### ISSUE TITLE
Smooth map panning to follow user

### ISSUE THREAD

**Issue by caleb87** [mapsplugin/cordova-plugin-googlemaps#1123]
I'm trying to pan the map smoothly while following the user, but it tends to jump even with animateCamera. 

animateCamera appears to have a slight delay which causes it to stop for a moment making it appear to jump or lag. moveCamera of course would jump as the user location may have moved 20 feet. 

Any ideas on how to have the map smoothly follow the user?

**Comment by wf9a5m75** [comment]
This plugin only provides `animateCamera()` and `moveCamera()`. There is no other methods.

Please adjust your code by your self, such as duration.

```js
map.animateCamera({
  'target': GOOGLE,
  'tilt': 60,
  'zoom': 18,
  'bearing': 140,
  'duration': 5000 // = 5 sec.
}, function() {
  console.log("The animation is done");
});
```

**Comment by caleb87** [comment]
Thanks for the tip wf9. I have tried a many different durations, but I think animateCamera has a delay before it moves. Calling animateCamera every 500ms, with the animation duration at 500ms still causes a delay where the map moves, stops, then moves. Ideally it would never stop.

If it were possible to abort the animation, I could possibly time it so that it's always in animation.  The plugin does not appear to support this though.

**Comment by wf9a5m75** [comment]
Please provide screen record(video).

**Comment by caleb87** [comment]
Finally got around to getting the video made. Here's a clip: https://vimeo.com/185061223

The clip was using animateCamera. I have tried different timings, and the all ultimately have done the same. The faster the timing, the better it looks. Also the clip wasn't actually driving, it's simulated 5 ft intervals on the road. 

My goal is to pan the map without it appearing to stop. 

A separate problem on Android only is that if the animateCamera duration is within 50ms of how often the interval calls animateCamera, it won't load tiles when panning. So for Android only, I have to have animateCamera duration at 450ms and setInterval(myMoveCameraFunction, 500ms). iOS loads tiles fine even the interval/duration at the same.

**Comment by wf9a5m75** [comment]
The plugin is not designed for tracking your position.
It means there is no way to move the camera smoothly and continuously.
(And I don't have plan to implement it)
