### ISSUE TITLE
Error: more than one library with package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by d-cordeiro-** [mapsplugin/cordova-plugin-googlemaps#1126]
Hello,

I'm using this plugin with ionic and when I try to build the Android app, I get the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'

My cordova version is 6.3.1 and my ionic version is 1.5.5
Any ideia why is this happening? why did it start to fail after I updated this plugin.

Thanks,
Cordeiro

**Comment by wf9a5m75** [comment]
I think you probably installed this plugin incorrect way.
Could you tell me what outputs the below command?

```
$> cordova plugin list
```

**Comment by d-cordeiro-** [comment]
Here is the list it returned:

`android.support.v4 21.0.1 "Android Support v4"
com.google.playservices 23.0.0 "Google Play Services for Android"
com.googlemaps.ios 2.0.1 "Google Maps SDK for iOS"
com.ionic.keyboard 1.0.4 "Keyboard"
com.teamnemitoff.phonedialer 0.3.0 "PhoneDialer"
cordova-plugin-googlemaps 1.3.9 "phonegap-googlemaps-plugin"
de.appplant.cordova.plugin.email-composer 0.8.2 "EmailComposer"
nl.x-services.plugins.toast 2.0.4 "Toast"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.inappbrowser 0.6.0 "InAppBrowser"
com.teamnemitoff.phonedialer 0.3.0 "PhoneDialer"
`

**Comment by wf9a5m75** [comment]
Remove `com.google.playservices` plugin, because this plugin install it automatically.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L48
