### ISSUE TITLE
ios build giving error 

### ISSUE THREAD

**Issue by shahbazkhan054** [mapsplugin/cordova-plugin-googlemaps#1127]
I am getting error while building ios.

```
  /Users/xxxx/.taco_home/remote-builds/taco-remote/builds/4144/cordovaApp/platforms/ios/xxxx/Plugins/plugin.google.maps/GoogleMaps.h:10:9: fatal error: 'GoogleMaps/GoogleMaps.h' file not found
1>  #import <GoogleMaps/GoogleMaps.h>
1>          ^
1>  1 error generated.
```

I am using visual studio tools for apache cordova remote build to build it.

**Comment by wf9a5m75** [comment]
```
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps
```

**Comment by shahbazkhan054** [comment]
I have added the plugin. It's working well on android but failing with above error on ios.

**Comment by wf9a5m75** [comment]
Other people who use Phonegap Build are no problem. It means the problem is in your project probably.

At least, too less Information. 
Please past ALL log of the phonegap build

**Comment by wf9a5m75** [comment]
Any update?

**Comment by Zoso221** [comment]
i am having the same issue, please help me.  i've been struggling on this for days.

i am also using tools for apache cordova and visual studio

**Comment by wf9a5m75** [comment]
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps

**Comment by shahbazkhan054** [comment]
I read there are some symbol problems with visual studio tools for apache cordova. Can you helo in that?

**Comment by wf9a5m75** [comment]
Sorry, I'm not Windows user

**Comment by shahbazkhan054** [comment]
Can you please check this link? 

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/719

**Comment by wf9a5m75** [comment]
PhoneGap build does not support the hook script. That's why this plugin does not provide using cocoapod.

**Comment by wf9a5m75** [comment]
It seems this is going to be help for Windows user.
https://taco.visualstudio.com/en-us/docs/tips-and-workarounds-ios-ios-plugin-symlink-fix-readme/

**Comment by wf9a5m75** [comment]
@shahbazkhan054 Can I see the result of this command : `$> cordova plugin list`?

I think you install the plugin from npm.

**Comment by wf9a5m75** [comment]
Or use the cordova-googlemaps-plugin v2-beta.

```
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
```

**Comment by Zoso221** [comment]
this is the answer:

https://taco.visualstudio.com/en-us/docs/tips-and-workarounds-ios-ios-plugin-symlink-fix-readme/

read this, it fixed my problem.  you may have to clean your solution and remove/readd the maps plugin.

**Comment by shahbazkhan054** [comment]
working for me. thanks.
