### ISSUE TITLE
$NSLocationWhenInUseUsageDescription

### ISSUE THREAD

**Issue by b4tch** [mapsplugin/cordova-plugin-googlemaps#1129]
When the app starts for the first time on iOS, I get the prompt to allow the app to use my location.  However, the description under this prompt reads "$NSLocationWhenInUseUsageDescription".  I saw there was a fix added recently so I downloaded the latest zip and installed it locally but the issue remains.  Do I have to do anything else?

**Comment by ZiFFeL1992** [comment]
Hey!

Check this: https://github.com/dpa99c/cordova-custom-config#ios-config-blocks

**Comment by b4tch** [comment]
Hey @ZiFFeL1992!  Many thanks - I actually already have that plugin installed but wasn't using it for this purpose.  I assumed there was a way to do it through the Google Maps plugin but if not, this is a decent alternative 👍

**Comment by wf9a5m75** [comment]
Since the custom config plugin does not work on Phonegap Build and intel xdk, we can not use it
