### ISSUE TITLE
Getting Blank Map

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/cordova-plugin-googlemaps#1130]
Thank you so much for this plugin.  I have been using the js api for years, but have decided to make the switch to this plugin to support offline maps using downloaded local tiles.

I was hoping you could tell me what I am doing wrong.  I am running the master of the plugin.  Xcode 8.0, iOS 10.0.2, and cordova 6.3.1.

I have the background color option set to blue and I am getting a blue div.  Running map.showDialog() in the javascript console does produce the map with proper zoom and center.

Below is my initialization code...
```js
var options = plugin.google.maps.Map.getMap({
		  'backgroundColor': 'blue',
		  'mapType': plugin.google.maps.MapTypeId.HYBRID,
		  'controls': {
			'compass': true,
			'myLocationButton': false,
			'indoorPicker': true,
			'zoom': true
		  },
		  'gestures': {
			'scroll': true,
			'tilt': true,
			'rotate': true,
			'zoom': true
		  },
		  'camera': {
			'latLng': new plugin.google.maps.LatLng(params.googleLat, params.googleLon),
			'tilt': 30,
			'zoom': parseInt(params.googleZoom),
			'bearing': 50
		  }
		});
		googleMap = plugin.google.maps.Map.getMap(document.getElementById("map_canvas"), options);
		googleMap.on(plugin.google.maps.event.MAP_READY, refreshGoogleMap);
```
When I run that code these are my Xcode logs:
```
2016-10-04 09:45:23.931861 AssessDamage[560:560920] FUNCTION = login()
2016-10-04 09:45:52.108033 AssessDamage[560:560920] $(window)  =====   0: 768X1024
2016-10-04 09:45:52.108257 AssessDamage[560:560920] avail  ======= 0: 768X1024
2016-10-04 09:45:52.108382 AssessDamage[560:560920] creating google map with zoom:8
```
When I run googleMap.showDialog()  after that this is my log:
```
2016-10-04 09:47:18.968298 AssessDamage[560:560920] THREAD WARNING: ['GoogleMaps'] took '30.750000' ms. Plugin should use a background thread.
```
Let me know if there is anything else you need.

**Comment by wf9a5m75** [comment]
First of all, you need to use the master branch version for iOS10.

```
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps --variable ...
```

The `backgroundColor` property is for specifying the background color when you want to use the embed map mode.
The backgroundColor option does not work for `map.showDialog()`

And if you can see the `Google Logo` but no map, double check your API key.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map

**Comment by KimberleeDArmstrong** [comment]
Thank you for the quick response...

-I think I am using the master branch..

cordova-plugin-googlemaps 1.3.9 "phonegap-googlemaps-plugin"

-showDialog() is working no blue background the map is correct.

-getMap with backgroundColor:blue shows a blue div no Google logo, no zoom controls, just all blue.

**Comment by wf9a5m75** [comment]
Did you install from npm or github branch?

**Comment by KimberleeDArmstrong** [comment]
github I believe..

cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps

**Comment by wf9a5m75** [comment]
I see. In that case, please check the background color of your HTML elements (&lt;html&gt;, &lt;body&gt;, &lt;div&gt; and the parent elements of the map div) are transparent using the chrome dev tool or safari dev tool.

**Comment by wf9a5m75** [comment]
Debugging iOS PhoneGap Apps with Safari's Web Inspector
http://phonegap-tips.com/articles/debugging-ios-phonegap-apps-with-safaris-web-inspector.html

Remote Debugging Android Devices
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3

**Comment by KimberleeDArmstrong** [comment]
![screen shot 2016-10-04 at 11 59 24 am](https://cloud.githubusercontent.com/assets/9216004/19083976/277ba8a4-8a2a-11e6-96ae-d88772ffcb60.png)
![screen shot 2016-10-04 at 11 58 35 am](https://cloud.githubusercontent.com/assets/9216004/19083975/27784dda-8a2a-11e6-90c6-b678b2f55d6c.png)


Body, map_page div, map_content div, and map_canvas div all show the grey checker board and rgba (0, 0, 0, 0)

**Comment by wf9a5m75** [comment]
Thank you for inspecting.
Um, I see... Please try the below code in the `MAP_READY` callback.

```js
document.body.style.backgroundColor = "rgba(0,0,0,0)";
document.body.style.display='none';
document.body.offsetHeight;
document.body.style.display='';
```

**Comment by wf9a5m75** [comment]
As far as I tested on iOS10, the UIWebKit does not redraw the background sometimes.
The plugin does that automatically, but if it does not work, you need to redraw the background mandatory.

http://stackoverflow.com/a/21947628/697856

**Comment by KimberleeDArmstrong** [comment]
I added the code to the MAP_READY callback function.  The map div is blank no google logo.  Let me know if there is anything else I can provide you.

**Comment by wf9a5m75** [comment]
I see. Could you try with very simple code?

Create a new project, then install the plugin from github.
Then write the below code into the index.html.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript">
    var map;
    document.addEventListener("deviceready", function() {
      var div = document.getElementById("map_canvas");

      // Initialize the map view
      map = plugin.google.maps.Map.getMap(div);

      // Wait until the map is ready status.
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
    }, false);

    function onMapReady() {
      var button = document.getElementById("button");
      button.addEventListener("click", onBtnClicked, false);
    }

    function onBtnClicked() {
      map.showDialog();
    }
    </script>
  </head>
  <body>
    <h3>PhoneGap-GoogleMaps-Plugin</h3>
    <div style="width:100%;height:400px" id="map_canvas"></div>
    <button id="button">Full Screen</button>
  </body>
</html>
```

**Comment by KimberleeDArmstrong** [comment]
Will do.  In the meantime I put breakpoints in GoogleMaps.m  One the first line of each function pageDidLoad, getMap, setDiv, and resizeMap.  The only breakpoint it stopped at was the pageDidLoad function.  Not sure if that helps.

**Comment by wf9a5m75** [comment]
I see. In that case, please confirm JS errors using safari debugger.

Open safari debug tool, then inspect the simulator/your device, then reload the HTML file using the debugger.

**Comment by KimberleeDArmstrong** [comment]
Simple project works.  Looking for js errors in existing project.

**Comment by KimberleeDArmstrong** [comment]
There was a js error I just had introduced trying to simple my project down so I could better test.  I fixed the js error.  Now the getMap function gets called twice.  The second time shouldLoad = NO after running through this.

BOOL shouldLoad = YES;

    if ([_delegate respondsToSelector:@selector(webView:shouldStartLoadWithRequest:navigationType:)]) {
        shouldLoad = [_delegate webView:webView shouldStartLoadWithRequest:request navigationType:navigationType];
    }

**Comment by KimberleeDArmstrong** [comment]
Do I have to have the WKWebView plugin installed for the master branch of this plugin to work?

**Comment by wf9a5m75** [comment]
no

**Comment by wf9a5m75** [comment]
The plugin js code does not call getMap() twice internally. Please double check your js code.

**Comment by KimberleeDArmstrong** [comment]
ok will do. Thanks

**Comment by KimberleeDArmstrong** [comment]
I copy and pasted the following into the safari javascript console.  And getMap breakpoint was still hit twice...
        var options = plugin.google.maps.Map.getMap({
		  //'backgroundColor': 'blue',
		  'mapType': plugin.google.maps.MapTypeId.HYBRID,
		  'controls': {
			'compass': true,
			'myLocationButton': false,
			'indoorPicker': true,
			'zoom': true
		  },
		  'gestures': {
			'scroll': true,
			'tilt': true,
			'rotate': true,
			'zoom': true
		  },
		  'camera': {
			'latLng': new plugin.google.maps.LatLng(params.googleLat, params.googleLon),
			'tilt': 30,
			'zoom': parseInt(params.googleZoom),
			'bearing': 50
		  }
		});
		googleMap = plugin.google.maps.Map.getMap(document.getElementById("map_canvas"), options);
		googleMap.on(plugin.google.maps.event.MAP_READY, refreshGoogleMap);

--------------------------------------------------------------------------------------
The first time it hits the if (self.mapCtrl) and goes into that if and hits the return.

The second time it goes into the else of that if (self.mapCtrl) .

Not sure if that helps.

**Comment by KimberleeDArmstrong** [comment]
oh crap I have a typo random plugin.google... got pasted in.  Sorry fixing it.

**Comment by KimberleeDArmstrong** [comment]
Ok we are good.  Can't believe I didn't see that!  Thanks for your help and your patience.

**Comment by msio777** [comment]
in ionic 2: 

```
ionViewDidEnter(){
this.map = new GoogleMap('map', options);
}
```
and after initializing the map, it should be removed `click-block-enabled`
```
const elem = document.getElementsByClassName('click-block-enabled')[0];
                    elem.parentNode.removeChild(elem);
```
