### ISSUE TITLE
Disabling 'Never' Option in LocationSettings Request in Android 

### ISSUE THREAD

**Issue by ronakkaria** [mapsplugin/cordova-plugin-googlemaps#1132]
the `map.getMyLocation()` method, automatically prompts dialog box for user to turn on location, if it is currently not enabled.

By default on Android, the prompt has 3 options, `Yes,` `No` and `Never`

Clicking on `Never` has the effect that the next time the user opens the app, he will not be prompted to turn on location. This can be detrimental to flow of apps. The user could easily make a mistake by clicking on `Never` the first time, and he wouldn't get a prompt again.

In Android native code you have the option of removing this `Never` option very easily. So it would be nice to have access to that feature via the javascript api. It would fit in very well in the `options` argument to the `map.getMyLocation()` method

**Comment by wf9a5m75** [comment]
Screen capture, please.

**Comment by ronakkaria** [comment]
![with never](https://cloud.githubusercontent.com/assets/6488852/19119571/d49b68f8-8b3d-11e6-8099-d73587d9dc51.png)

**Comment by ronakkaria** [comment]
Removing the never option via the Android Native Code is pretty simple.

In the java source code of this plugin in `GoogleMaps.java` inside method `_checkLocationSettings`
We add the `setAlwaysShow(true)` setting to the `LocationSettingsRequest.Builder` object:

`LocationSettingsRequest.Builder builder = new LocationSettingsRequest.Builder().setAlwaysShow(true);`

The result looks like this:

![without never](https://cloud.githubusercontent.com/assets/6488852/19119747/6441c9c0-8b3e-11e6-8e3f-abe103168049.png)

**Comment by wf9a5m75** [comment]
Thank you.
