### ISSUE TITLE
Plugin breaks full screen video playback on XWalk

### ISSUE THREAD

**Issue by eg271** [mapsplugin/cordova-plugin-googlemaps#1133]
On XWalk, cordova-plugin-crosswalk-webview 2.1.0 w/ latest Cordova, playing a HTML5 video works ok inline.  Then, when you hit the fullscreen button, only a white screen is shown (if this plugin is installed but no map has been instantiated) or the map appears.  The audio continues playing though and the playback controls appear at the bottom of the screen.

I'm using the recommended `<preference name="xwalkZOrderOnTop" value="true" />` which may be related.

**Comment by wf9a5m75** [comment]
I have never used XWalk.
Could you provide demo apk, demo project files, and screen record (video), please?

**Comment by eg271** [comment]
https://github.com/eg271/Video-Cordova-GMaps-Demo

**Comment by wf9a5m75** [comment]
Comment out line 196 : `root.setBackgroundColor(Color.WHITE);`

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L196

**Comment by eg271** [comment]
The video now displays.  However, if you create a map and then:

1. Call setVisible(false)   [to hide the map overlap so that the video is shown]
2. Watch the video in fullscreen
3. Call setVisible(true)

you get a black screen

**Comment by wf9a5m75** [comment]
In that case, you need to choose: use this plugin or not.

**Comment by wf9a5m75** [comment]
@eg271 Do you still continue for this?

**Comment by eg271** [comment]
The video only needed to be shown on the first page so I was able to create and destroy a map in the other parts of the app.  It still requires the above change (line 196) though.
