### ISSUE TITLE
is there route enviroment map on this pluggin?

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#1134]
i wanna know if there exist route enviroment on this pluggin ? like this https://www.mapsview.net/directions

**Comment by wf9a5m75** [comment]
Version1.3.9 provides https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/External-Service

Version 2.0-beta does not provide it.

**Comment by wf9a5m75** [comment]
Alternatively this plugin is better.
https://github.com/dpa99c/phonegap-launch-navigator
