### ISSUE TITLE
multiple-maps branch does not work on Ionic 2.0 rc0

### ISSUE THREAD

**Issue by adrinavarro** [mapsplugin/cordova-plugin-googlemaps#1135]
We've created a test app with Ionic 2.0 rc0 and the new branch does not work in that app.

Here's the source for said app: https://github.com/ZiFFeL1992/maps-v2
An example video: https://sendvid.com/23m9ynbu

What happens is that interactions (touch events) are not recognized. This does not happen in the test APK provided, just on Ionic 2.0 rc0.

**Comment by wf9a5m75** [comment]
ok,  I will check it.
By the way, please report issue of the v2-beta to here https://github.com/mapsplugin/v2.0-demo/issues

As I describe at the readme.md, I would like to separate the issue list between v1 and v2.
