### ISSUE TITLE
GoogleMapsLatLng coordinates issue

### ISSUE THREAD

**Issue by felzend** [mapsplugin/cordova-plugin-googlemaps#1136]
Commands related to map such as MoveCamera and AddMarker will not work with **GoogleMapsLatLng** object, but with

`let location = new GoogleMapsLatLng(lat, lng)['_objectInstance']`

Someone told me this and I'm reporting

**Comment by wf9a5m75** [comment]
This plugin does not provide GoogleMapsLatLng object

**Comment by felzend** [comment]
Yes, that's from ionic-native...

**Comment by wf9a5m75** [comment]
Probably yes.
