### ISSUE TITLE
Putting a GroundOverlay image in the center of a Polygon

### ISSUE THREAD

**Issue by paulparton** [mapsplugin/cordova-plugin-googlemaps#1138]
Hi,

I am using polygons to draw paddock shapes on a map, and I want to add a text label with the paddocks name. 

In the past we have done this in a native Android app by calculating the area of the polygon and using that to generate an image containing the label text, then we create a GroundOverlay with the image and set the GroundOverlay center to the center of the polygon.

using cordova-plugins-googlemaps I can't find a way to calculate the area of a polygon,  and it seems I can only create a GroundOverlay with bounds (not center).

Is there any plan to support positioning a GroundOverlay with center instead of bounds?

Is there any way currently for me to:
1. calculate the area of a polygon
2. align a groundOverlay image to the center of a polygon?

Thanks!

**Comment by wf9a5m75** [comment]
> 1.calculate the area of a polygon
`polygon.getPoints()`

>2 . align a groundOverlay image to the center of a polygon?
Do your best.

**Comment by paulparton** [comment]
Hey, 

1. I already have that, it's what I use to draw the polygons. The question is how can I calculate the area / dimensions from that. (In the native / JS API's we did it with google.maps.geometry.spherical.computeArea etc)

2. like i said, I don't know how to go about this when I can only position it with bounds. I have tried using the bounds that i used to draw the polygons in the first place, but that aligns the GroundOverlay in the top left.

**Comment by wf9a5m75** [comment]
Both features are not provided from this plugin. That's why I wrote "do your best".

It means you need to implement the features in JS or native code by yourself.

Otherwise using this plugin with the Google Maps js api v3.

**Comment by paulparton** [comment]
Thank you, "Both features are not provided from this plugin." and " using this plugin with the Google Maps JS api v3." are informative comments. 

Thank you for clarifying "do your best".

I will look into using the V3 Maps API. Have you had any experiences using it alongside cordova-plugin-googlemaps to use the geometry library? 

Are there any plans to implement the ability to position a GroundOverlay with center instead of bounds?

**Comment by wf9a5m75** [comment]
I just comes up the idea.

Basically, the plugin accepts `Array of LatLng` as bounds in all classes.
This code should be work.

```js
map.addPolygon({
  ....  // options
}, function(polygon) {
  var points = polygon.getPoints();

  map.addGroundOverlay({
     bounds: points,
     image: ...
  }, function(groundOverlay) {
     // to do something..
  });
});
```

Otherwise, you can do like this also.

```js
map.addPolygon({
  ....  // options
}, function(polygon) {
  var points = polygon.getPoints();
  var latLngBounds = new plugin.google.maps.LatLngBounds(points);
  var southWest =  latLngBounds.southwest;
  var northEast =  latLngBounds.northeast;

  var northWest = {"lat": northEast.lat, "lng": southWest.lng};  // top-left
  var southEast = {"lat": southWest.lat, "lng": northEast.lng};   // bottom-right

  map.addGroundOverlay({
     bounds:[northWest, southEast],
     image: ...
  }, function(groundOverlay) {
     // to do something..
  });
});
```

**Comment by paulparton** [comment]
Hey mate,

Thanks for giving it some thought.

The first solution (passing in the bounds used to create the polygon) is what I have tried already, and the image seems to position itself in the top left. I tried your second solution, but it does the same thing.

I don't think i am going to be able to make this work without the ability to center a groundOverlay on a latlng. 

As a work around I am currently working on using markers instead of GroundOverlay and making the marker smaller as you zoom out / hiding it once you zoom out far enough.

Is there any interest in adding the ability to create a GroundOverlay by position instead of bounds?

**Comment by wf9a5m75** [comment]
Google Maps SDK for iOS requires the bounds property.
The iOS SDK does not provide the `center` and `width` properties to specify the bounds.
That's why this plugin does not  provide the feature.

https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_ground_overlay.html#a88e95c2568ccfbbc6b694dfd7351e981

**Comment by wf9a5m75** [comment]
I talk about iOS. This plugin provide the feature only both os are supported.
If you want to use it, folk the repository, and Implement by your self.
That's why this plugin is open source.

**Comment by paulparton** [comment]
Hi, 

I understand, but on the iOS docs you sent isn't the feature there? I thought it was groundOverlayWithPosition?

**Comment by wf9a5m75** [comment]
`groundOverlayWithPosition: icon: zoomLevel` needs to specify zoomLevel.

**Comment by wf9a5m75** [comment]
If you implement the feature, that's easy. Just sending a pull request.
This is open-source. Contributions are welcome.

**Comment by paulparton** [comment]
Cool. Just to clarify though, the feature in question IS in iOS but it is different in that you need to create a different groundOveraly for every zoom level right?
