### ISSUE TITLE
ios map not show

### ISSUE THREAD

**Issue by alextapia007** [mapsplugin/cordova-plugin-googlemaps#1139]
im try the exmple.. android works fine... but ios dont show the map, when click the button... show the marker,etc... but not the map

**Comment by wf9a5m75** [comment]
Please post your issue more detail information.
How can I help you without information.... :(

**Comment by alextapia007** [comment]
![img_0007](https://cloud.githubusercontent.com/assets/15269078/19321275/0186512a-907a-11e6-9f7a-04ec20503877.jpg)
i hope the image help.

**Comment by alextapia007** [comment]
![img_0008](https://cloud.githubusercontent.com/assets/15269078/19321376/6e598b8c-907a-11e6-9323-86c019c61e27.jpg)
when i click the button

**Comment by alextapia007** [comment]
thanks for help wf9a5m75.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map

**Comment by alextapia007** [comment]
i'll try, thaks again.

**Comment by alextapia007** [comment]
ios work!! thanks, ios sdk switch was my problem...
