### ISSUE TITLE
Plugin not defined & on console i get "root directory var: "

### ISSUE THREAD

**Issue by pareta2** [mapsplugin/cordova-plugin-googlemaps#1141]
Hello Developers,

I am new to cordova plugin and using in a hybrid application cloud based platform appery.io
I have imported this plugin into the project with google map android key
and i used the code in the way it is described on the page but when i check in console i get 

plugin not defined and on console i get this  "root directory var: " 
please help me guys i love this plugin and I am stuck since so many days..

**Comment by pareta2** [comment]
Help me asap i can make donations who will help me on this successfully....

**Comment by wf9a5m75** [comment]
I don't support cloud base platform except the PhoneGap Build and the Monaca.

Please ask to the appery.io community.
