### ISSUE TITLE
MyLoatcion icon with white square

### ISSUE THREAD

**Issue by ckhsu3926** [mapsplugin/cordova-plugin-googlemaps#1145]
Hey guys.
I have enable myLocation after getMap function,
but no metter how I tried there are always a white square above my location icon.
And I search a lot of snapshots of this plugin and they didn't look like mine.

Is anybody have idea how to solve it ?

![2016-10-20 19 56 43](https://cloud.githubusercontent.com/assets/9319680/19558927/9ab0962c-96ff-11e6-8c4e-64b7bb8657fa.png)

**Comment by caleb87** [comment]
Looks like your image is a jpg/gif/png16. You need a png32 icon so the transparency is maintained.

**Comment by pixel2** [comment]
I have the same issue, but only when running my app in the ios simulator. When running on an actual device there is no white square and the location icon works as expected.

**Comment by wf9a5m75** [comment]
This is not the plugin issue. The problem is Google's one.
Please report to here.
https://code.google.com/p/gmaps-api-issues/
