### ISSUE TITLE
can not download sample apk file

### ISSUE THREAD

**Issue by zq8024** [mapsplugin/cordova-plugin-googlemaps#1146]
hi, can not download sammle apk file, url :
https://googledrive.com/host/0B1ECfqTCcLE8TXlUQUJXMmJpNGs/phonegap-googlemaps-plugin-v1.2.5.apk

can you send a new one?

thanks

**Comment by wf9a5m75** [comment]
Sorry. You can download the apk from here.
https://dl.dropboxusercontent.com/u/1456061/cordova-google-maps/apks/phonegap-googlemaps-plugin-v1.2.5.apk
