### ISSUE TITLE
setMylocation in android is not working, however in ios working perfectly. and marker in android not change when im trying to use custom marker

### ISSUE THREAD

**Issue by FarhanJohari** [mapsplugin/cordova-plugin-googlemaps#1147]
hi there.. button for setMylocation not appearing on map and the current location marker also not appear. i dont have ideas how to do the custom marker while in ios it works

**Comment by FarhanJohari** [comment]
for marker i manage to do it in ionic.. i missed www/ for url but still in setMyLocatiion i have the issues

**Comment by wf9a5m75** [comment]
Do you use the master branch version?

**Comment by alextapia007** [comment]
i trying to hide location button... some way to do that?

**Comment by alextapia007** [comment]
but keeping location icon

**Comment by wf9a5m75** [comment]
Available options:

```js
var map = plugin.google.maps.Map.getMap({
  'backgroundColor': 'white',
  'mapType': plugin.google.maps.MapTypeId.HYBRID,
  'controls': {
    'compass': true,
    'myLocationButton': true,
    'indoorPicker': true,
    'zoom': true
  },
  'gestures': {
    'scroll': true,
    'tilt': true,
    'rotate': true,
    'zoom': true
  },
  'camera': {
    'latLng': GORYOKAKU_JAPAN,
    'tilt': 30,
    'zoom': 15,
    'bearing': 50
  }
});
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.getMap()#create-a-map-with-initialize-options

**Comment by alextapia007** [comment]
thanks a lot.
