### ISSUE TITLE
Cordova Google map not Visible on android Device (Visible on emulator with latest android 7.0)

### ISSUE THREAD

**Issue by uditguru** [mapsplugin/cordova-plugin-googlemaps#1148]
I am having this issue with maps ,the map is not visible on android emulator 4.x..x, 5.x and 6 versions but is visible on 7, however it is not visible on actual devices (All the versions). Please help, I can see no error in the logs.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps#version-20-beta

**Comment by uditguru** [comment]
I don't understand what you are trying to say

**Comment by uditguru** [comment]
`$> cordova plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"`


is this how i should add beta plugin?

**Comment by wf9a5m75** [comment]
The master branch is old. The version2 works on Androind N.
You should use the beta version.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta

Please read the **How to install the v2 beta?** page.

**Comment by uditguru** [comment]
the plugin i am using right now works on latest version and not on older versions. Does v2 work on older version of android like 5.1 and above?

**Comment by wf9a5m75** [comment]
I don't support the master version anymore. It's too old for me.
Some methods and some event names are changed, but others are almost the same.
You can stick on the current version, but you can not support for older version.

**Comment by uditguru** [comment]
i am using the current stable only but can't see map on android device, its working on emulator.

**Comment by uditguru** [comment]
Other issue is that in android (on emulator), it sometimes show current location marker ,but does not show all the time.

**Comment by uditguru** [comment]
@wf9a5m75 hey I'm using ionic 2 so cannot use v2, please help

**Comment by wf9a5m75** [comment]
Sorry, but I'm not familiar with ionic.
But at least the latest version works on the ionic2.

**Comment by uditguru** [comment]
I am Using current master branch and it works fine on ios with map and everything but i am only getting white screen on android devices. Please help with a fix

**Comment by wf9a5m75** [comment]
Other people does not have your issue. I think problem is in your project.
And I already said the master branch will be deprecated soon.
Please use the v2-beta version.

**Comment by arielgelbard** [comment]
I upgraded to RC1 and maps is still working for me @uditguru

**Comment by uditguru** [comment]
I don't know what was wrong but it is working now
