### ISSUE TITLE
Example for ionic v2

### ISSUE THREAD

**Issue by inceptiveDipak** [mapsplugin/cordova-plugin-googlemaps#1149]
This is not issue, I want example in Ionic v2, i am new in ionic v2. Please Help me.
 Thank you.

**Comment by wf9a5m75** [comment]
Please ask at the ionic2 folum.

**Comment by uditguru** [comment]
@inceptiveDipak hi you can refer to this blog post www.joshmorony.com/integrating-native-google-maps-into-an-ionic-2-application/
