### ISSUE TITLE
map not destroyed , map always is on app no matter on other page diferent when was created

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#1151]
im developing a proyect when i have a page welcome.html when i load the map , and i have 2 pages more, page1.html and page2.html for example, but , i have a problem when i call the page1.html and see that the map is on the page1 too , the problem is that on the page1 i dont have any instance of map, i thing the problem is on my logic , but i dont know, the issue is the same in all enviroment if i have a index, html with login and after call the welcome with map, or calll other page from welcome

**Comment by wf9a5m75** [comment]
The current version does not support multiple pages.
You have to execute `map.remove()` before changing the page.

The version 2.0-beta supports multiple pages.
I recommend you use the new version.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta

**Comment by dsemerida** [comment]
ok , so how i cant update or install the  last version ?

**Comment by wf9a5m75** [comment]
Read  the `How to install the v2 beta?` page.

**Comment by dsemerida** [comment]
thanks man!
