### ISSUE TITLE
Permission error on android 6.*

### ISSUE THREAD

**Issue by gchokeen** [mapsplugin/cordova-plugin-googlemaps#1156]
Hi,

I am not able to get the current location. 

My environment 

- Ionic 2
- Android 6.0 
- using master branch of this plugin
 

I was getting below error with stable version of this plugin so I switched to master branch but  now getting exception while building app.

`
googlemaps-cdv-plugin.js:117 my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION`

**Exception**

```
platforms/android/gradlew: Command failed with exit code 1 Error output:
/var/www/html/RSA/platforms/android/src/plugin/google/maps/PluginMarker.java:167: error: cannot find symbol
              if(e instanceof FileNotFoundException) {}
                              ^
  symbol: class FileNotFoundException
Note: /var/www/html/RSA/platforms/android/src/plugin/google/maps/GoogleMaps.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by wf9a5m75** [comment]
The current version will be deprecated soon.
Please use the v2-beta version.
https://github.com/mapsplugin/cordova-plugin-googlemaps#version-20-beta

**Comment by gchokeen** [comment]
I tried installing the latest one by below command but it's simply hanging 

```
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="my key"
Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps" via git clone

```

I waited for long time nothing happend . Is this github issue or I miss anything !

**Comment by wf9a5m75** [comment]
>Is this github issue or I miss anything !

I think your environment problem, such as network or pc.

**Comment by gchokeen** [comment]
All other plugins are installing fine, even this plugins 'mater' branch. Totally strange !!!

`
ionic plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="mykey"`

**Comment by gchokeen** [comment]
After waiting long time, I got this exception. 

Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps" via git clone
Repository "https://github.com/mapsplugin/cordova-plugin-googlemaps" checked out to git ref "multiple_maps".
Installing "cordova-plugin-googlemaps" for android
ANDROID_HOME=/home/gowri/Android/Sdk
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Subproject Path: CordovaLib
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Incremental java compilation is an incubating feature.
:clean
:CordovaLib:clean

BUILD SUCCESSFUL

```
Total time: 20.181 secs
Failed to install 'cordova-plugin-googlemaps':Error: There was a conflict trying to modify attributes with <edit-config> in plugin cordova-plugin-googlemaps. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before cordova-plugin-googlemaps can be added. You may use --force to add the plugin and overwrite the conflicting attributes.
    at PlatformMunger.add_plugin_changes (/var/www/html/RSA/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:169:19)
    at /var/www/html/RSA/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:126:25
    at _fulfilled (/var/www/html/RSA/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/var/www/html/RSA/platforms/android/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/var/www/html/RSA/platforms/android/cordova/node_modules/q/q.js:796:13)
    at /var/www/html/RSA/platforms/android/cordova/node_modules/q/q.js:857:14
    at runSingle (/var/www/html/RSA/platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/var/www/html/RSA/platforms/android/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```
> Error: There was a conflict trying to modify attributes with <edit-config> in plugin cordova-plugin-googlemaps. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before cordova-plugin-googlemaps can be added. You may use --force to add the plugin and overwrite the conflicting attributes.

**Comment by wf9a5m75** [comment]
It seems another plugin might set another value to `<application android:largeHeap="(value)" />`
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/plugin.xml#L178-L180

You can install the plugin with `--force` option or modify your application by yourself.

**Comment by gchokeen** [comment]
I installed this branch and builded success, but still not tested the current location functionality Yet. I will test and let you know.

But one off topic question. My requirement is to display all near by hotels, polices stations, etc in ionic hybrid application. Do you have documentation to do the places API integration with this plugin. Can't find anything

**Comment by wf9a5m75** [comment]
This plugin does not provide the places API

**Comment by gchokeen** [comment]
I still not able to get the GPS location.

When I opened the map page.It was asking **permission to access the device location**.  Once I select Allow. it's not enabling the GPS of device?

> PositionError
> code
> 2
> message
> "application does not have sufficient geolocation permissions.

**Comment by gchokeen** [comment]
Since this is plugin not supporting places api, there is no point of discussing issue and using this plugin. So I will close this ticket. But you have done great work, I  appreciated you help!

**Comment by narayana1240** [comment]
from the version 6.0 on words we need to get/write permissions from user in runtime auto matic access is disabled please look at that pont
