### ISSUE TITLE
GoogleMaps/GoogleMaps.h file not found

### ISSUE THREAD

**Issue by kelvinrolex** [mapsplugin/cordova-plugin-googlemaps#1157]
Please I am trying to build my app with xcode but am getting this error GoogleMaps/GoogleMaps.h file not found, I am using xcode 8.0 and am using the Master branch of cordova-plugin-googlemaps. Please help me with a solution.
![error from xcode](https://cloud.githubusercontent.com/assets/10676937/19734041/fbcccb04-9b9d-11e6-85ee-7333390e14f2.PNG)

**Comment by wf9a5m75** [comment]
The current version will be deprecated soon.
Please use the v2-beta version.
https://github.com/mapsplugin/cordova-plugin-googlemaps#version-20-beta

**Comment by kelvinrolex** [comment]
@wf9a5m75 I have installed the current v2-beta and it's crashing the app when I open the map section of the app. This happen on android while the issue for ios not building bcos of GoogleMaps/GoogleMaps.h file not found is still there but I think I have found the solution to that in one of the closed issues, I will try that later. The real issue here now is why is the v2-beta crashing my app? Please I need solution.

**Comment by wf9a5m75** [comment]
The v2 does not use `GoogleMaps/GoogleMaps.h` anymore.

**Comment by kelvinrolex** [comment]
Ok but why is it crashing the app?

**Comment by kelvinrolex** [comment]
Or does the v2-beta has its own implementation if it's having pls can you give me a link to the documentation.

**Comment by wf9a5m75** [comment]
I can not say anything without log.

Please read this carefully. 
![screen shot 2016-10-26 at 11 19 11 pm](https://cloud.githubusercontent.com/assets/167831/19756622/d73c866e-9bd2-11e6-858e-1f7655582e66.png)


And you should install the demo app before asking.

![screen shot 2016-10-26 at 11 21 17 pm](https://cloud.githubusercontent.com/assets/167831/19756636/ee53e75c-9bd2-11e6-82e9-7b5a0ad2b3fb.png)

**Comment by kelvinrolex** [comment]
ok.
