### ISSUE TITLE
Screen have quick flash when call map.remove() or map.getMap()

### ISSUE THREAD

**Issue by hungca** [mapsplugin/cordova-plugin-googlemaps#1161]
When to go to the map page or go the other page from the map page (I call function map.remove()), on the app, there is a quick white flash, white screen displayed and hidden then ~0.5s, then the app works normally. Same as the both map.remove() and map.getMap() function is not work smoothly.
Please help me resolve it

```
$scope.initNativeMap = function () {
        var div = document.getElementById("map_canvas");
        // Initialize the map view
        map = plugin.google.maps.Map.getMap(div, {
            'backgroundColor': '#ffc20e',

            'controls': {
                'compass': true,
                //'myLocationButton': true,
                // 'indoorPicker': true,
                'zoom': true // Only for Android
            }
        });
        map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
    };

    function onMapReady() {
        console.log("map ready >> find current location");
        mixpanel.track("Map: initiliazed");
        $scope.getLocation();
    };
```

```
$scope.gotoOtherPage = function (pageName) {
        if (map != null) {
            map.remove();
        }
       $state.go(pageName);
    }
```

**Comment by wf9a5m75** [comment]
Since the plugIn changes the background-color of the map div and the parent elements as transparent, this might happen.
No solution.

**Comment by hungca** [comment]
you mean that we can't make it operate smoothly when initialization or remove map. the production app can't have a quick flash screen and do not operate smoothly. 
it really integrating an issue into my app
is the issue resolved in the v2 ?

**Comment by wf9a5m75** [comment]
Please try before asking.

**Comment by wf9a5m75** [comment]
@hungca Did you solve this?

**Comment by hungca** [comment]
@wf9a5m75 
The map.remove() function is really not working perfectly, It doesn't remove all the inline style and the "\_gmaps_cdv\_" class in parent element of the map page. 
So, I need to rollback style manually after leave out the map page.
Thanks for your best efforts. but I hope map.remove() function will rollback all the change of the map.getMap() function in the version 2.


````
$rootScope.$on('$stateChangeSuccess',
        function (event, toState, toParams, fromState, fromParams) {
            if (fromState.name == "app.map") {
                try {
                    console.log('map page: goto other page => remove map');
                    $('body').css({ background: "#ffc20e" });
                    //$('#heroView').css({ background: "#ffc20e" }); // main ui-view
                    map.remove();
                } catch (e) { }
            }
        })`
```

**Comment by wf9a5m75** [comment]
Please send a pull request
