### ISSUE TITLE
position ui Controls in map

### ISSUE THREAD

**Issue by orochies** [mapsplugin/cordova-plugin-googlemaps#1163]
Hello, first thank you for the great work done.

They could tell me, how I can change the position of the user interface controls? I mean the compass, zoom...

**Comment by masashiGMS** [comment]
No option is available.

**Comment by orochies** [comment]
Okay, thanks for the quick response.

**Comment by rroque6428** [comment]
Yeah, allowing controlling the position of the controls would be nice. I face this problem today.

**Comment by kpwa** [comment]
same here. could you please add this option
