### ISSUE TITLE
GoogleMaps.java:555: error: cannot find symbol mapView.getMapAsync(new OnMapReadyCallback() {

### ISSUE THREAD

**Issue by janrg** [mapsplugin/cordova-plugin-googlemaps#1165]
Hi,
I've been trying to use the plugin with phonegap on Android, been fiddling around with it for several hours now and still getting nowhere. I've tried following the instructions on
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Phonegap-Usage
(though the directory in the linked zip file is called cordova-* instead of phonegap-* as it says in the instructions), when I call phonegap run android the build fails with the error message

GoogleMaps.java:555: error: cannot find symbol
    mapView.getMapAsync(new OnMapReadyCallback() {
           ^
symbol:   method getMapAsync(<anonymous OnMapReadyCallback>)
location: variable mapView of type MapView

I've tried installing version 2.0, if I do it with the provided command, the map simply doesn't appear (it seems that the line that fails to execute is map = plugin.google.maps.Map.getMap(div);) and I couldn't get a manual install as detailed in the phonegap-usage page to work as there doesn't seem to be a plugin.xml file in https://github.com/mapsplugin/v2.0-demo

I don't know what else to try at this point, apologies if I'm being stupid, this is my first attempt at using phonegap...

**Comment by wf9a5m75** [comment]
Does your phone have the Google play services?

**Comment by janrg** [comment]
Yes, version 9.8.77. I also since tried building and installing the demo app from https://github.com/mapsplugin/v2.0-demo and that does work but I still can't figure out how to get the map to work in phonegap.

**Comment by wf9a5m75** [comment]
>GoogleMaps.java:555: error: cannot find symbol
mapView.getMapAsync(new OnMapReadyCallback() {
^
symbol: method getMapAsync()
location: variable mapView of type MapView


This error means your app does not have the Google play services library.
The maps plugin typically install it automatically ( because there is a definition in the plugin.xml), but in your case, no.

You need to install the google play services library by yourself

**Comment by janrg** [comment]
Thank you! It seems like there was some mess with plugins so I removed and reinstalled the plugin as well as all platforms a few times and finally got it to work!
Strangely though, it only works if I build the app in phonegap and sideload it onto my phone, not if I load it via the phonegap app. Do you know what might be causing this?

**Comment by wf9a5m75** [comment]
I don't know. I'm not familiar with phonegap.

**Comment by janrg** [comment]
Fair enough. It makes testing more awkward but at least it works now which is obviously the most important thing :-) Thanks again, and thank you also for writing this plugin!

**Comment by mumshadrifat** [comment]
I have the same problem but tried to reinstall plugins.
