### ISSUE TITLE
Property 'get' does not exist on type 'GoogleMapsMarker'

### ISSUE THREAD

**Issue by santu-git** [mapsplugin/cordova-plugin-googlemaps#1168]
According following document I am trying to store my custom data
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#add-your-data-and-hold-them

But I am getting following error 
Property 'get' does not exist on type 'GoogleMapsMarker'
I am using typescript in ionic2

**Comment by wf9a5m75** [comment]
The Ionic2 wrapper is out of support. Ask them.
