### ISSUE TITLE
Which is the current v2 branch?

### ISSUE THREAD

**Issue by pke** [mapsplugin/cordova-plugin-googlemaps#1169]
I've read in https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F that so much has been rewritten in v2. Yet the v2.0 branch is 268 commits behind master with last commit over a year old. Later I found this doc https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta which mentions `multiple_maps` as the current v2 branch.
How about removing the `v2.0` branch to reduce confusion?

**Comment by wf9a5m75** [comment]
I see. I forgot the v2.0 branch. I will remove it later.

**Comment by wf9a5m75** [comment]
Done
