### ISSUE TITLE
Register one listener for all marker clicks

### ISSUE THREAD

**Issue by pke** [mapsplugin/cordova-plugin-googlemaps#1170]
The docs are not very clear about that. Can I register a marker click handler at map level instead of attaching it to each single marker?

`map.addEventListener(MARKER_CLICK, listener)`
instead of 
`marker.addEventListener(MARKER_CLICK, listener)`

This would also require to send the marker itself and not only its position to the listener.

**Comment by wf9a5m75** [comment]
>map.addEventListener(MARKER_CLICK, listener)

No.

> Get the marker instance.

Use `this` in the listener.
For example,

````js
marker1.on(MARKER_CLICK, callback);
marker2.on(MARKER_CLICK, callback);

function callback() {
  var marker = this;
  ...
}
```
(This is normal way of the OOP in Javascript)
