### ISSUE TITLE
V2-Beta: Map not shown until clicked

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [mapsplugin/cordova-plugin-googlemaps#1173]
I'm writing an ionic app and I noticed that a map that isn't created directly after DOMContentLoaded is not visible until I touch it for the first time:

I have a page with content:

`<ion-content></ion-content>`

If I show the map like this, everything works fine:

```
document.addEventListener('DOMContentLoaded', function() {
    var el = document.querySelector('ion-content');
    plugin.google.maps.Map.getMap(el)
}, false);
```

however, if I add a timeout, the map is not shown initially, but after I click on the area where it should be, it is instantly shown:
```
document.addEventListener('DOMContentLoaded', function() {
  window.setTimeout(() => {
    var el = document.querySelector('ion-content');
    plugin.google.maps.Map.getMap(el)
  }, 1000);
}, false);
```

I am using the latest git version of v2 beta

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#change-4-save-battery-life

![screen shot 2016-11-04 at 4 26 04 pm](https://cloud.githubusercontent.com/assets/167831/20025421/691b9dac-a2ab-11e6-8c80-15e34f59dca0.png)

**Comment by hermitdemschoenenleben** [comment]
This works, thank you! I'm sorry for not having read this, I just read the migration hints from v1 to v2.
