### ISSUE TITLE
animateCamera always zooms in - #MultipleMaps on Android

### ISSUE THREAD

**Issue by samedii** [mapsplugin/cordova-plugin-googlemaps#1174]
console.log('zoom: ' + worldMap.getCameraZoom()); //"zoom: 15"
    
    worldMap.animateCamera({
        target: latLng,
        zoom: 15 //this can be removed, does not matter what it is set to
    }, () => {
        console.log('zoom: ' + worldMap.getCameraZoom()); //"zoom: 21"
    });

If animateCamera is replaced by moveCamera it also doesn't work since they use the same logic. However, setCameraTarget(latLng) works.

I started stepping through the code but this is one of the more complicated parts. Do you see anything obvious that might cause this? If not, I'll try looking through it when I have time

**Comment by wf9a5m75** [comment]
Please send a pull request.
And please use [this issue list](https://github.com/mapsplugin/v2.0-demo/issues) instead of here.
![screen shot 2016-11-06 at 7 26 21 pm](https://cloud.githubusercontent.com/assets/167831/20045537/eb5a3c18-a456-11e6-8014-2fcc24dd6c74.png)

**Comment by samedii** [comment]
Okay, moving it
