### ISSUE TITLE
[v2-beta] error when re-installing

### ISSUE THREAD

**Issue by xloading** [mapsplugin/cordova-plugin-googlemaps#1175]
Hi Masashi!

I've started experimenting with v2-beta and got my iOS app more or less working with new version but then I needed to remove the plugin temporarily to experiment with Android.

However when trying to install it again I started getting the following error:
```
xloading$ cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="xxx" --variable API_KEY_FOR_IOS="xxx" --force
Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps" via git clone
Repository "https://github.com/mapsplugin/cordova-plugin-googlemaps" checked out to git ref "multiple_maps".
Installing "cordova-plugin-googlemaps" for android
Failed to install 'cordova-plugin-googlemaps':TypeError: Cannot read property 'length' of undefined
    at /Users/xloading/ionic/xxx/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:381:23
    at Array.forEach (native)
    at is_conflicting (/Users/xloading/ionic/xxx/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:355:17)
    at PlatformMunger.add_plugin_changes (/Users/xloading/ionic/xxx/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:150:33)
    at /Users/xloading/ionic/xxx/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:126:25
    at _fulfilled (/Users/xloading/ionic/xxx/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/xloading/ionic/xxx/platforms/android/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/xloading/ionic/xxx/platforms/android/cordova/node_modules/q/q.js:796:13)
    at /Users/xloading/ionic/Guidelance/platforms/android/cordova/node_modules/q/q.js:857:14
    at runSingle (/Users/xloading/ionic/xxx/platforms/android/cordova/node_modules/q/q.js:137:13)
Error: Cannot read property 'length' of undefined

Pls note that without "--force" I got some exceptions when installing the plugin initially.
```
Could you make any suggestion why this error happens during the re-install?

Thanks in advance!

**Comment by wf9a5m75** [comment]
Thank you for using the v2-beta.
Regarding of the v2-beta issue, please use https://github.com/mapsplugin/v2.0-demo/issues

And I checked your error log, but I have no idea.
But I also faces similar errors sometimes. I think you (or cordova) removed some important file.
In that case, I removes the plugin by my hand.

Remove the `platforms/android/src/plugin.google.maps/`, `platforms/ios/(project)/plugins/plugin.google.maps/`, and `plugins/plugin.google.maps/`.
And remove the plugin definition from `plugins/fetch.json`, `plugins/android.json` and `plugins/ios.json`.
The point is remove the plugin files and definitions from all files of your project.
This works sometimes.

Even though you can not get luck, you need to create a new project.

**Comment by xloading** [comment]
Hi @wf9a5m75,
Thank you very much for the hints, after cleaning up as per your advice and series of magic actions, reinstalls etc. it installed without issues.
I will create further issues related to v2-beta in demo repo.
Thanks!
