### ISSUE TITLE
App is crashing due to memory leaks

### ISSUE THREAD

**Issue by mrameezraja** [mapsplugin/cordova-plugin-googlemaps#1176]
App was working fine before adding maps plugin. Xcode instruments is showing leaks only coming from plugin. As seen in attached images. Is there anything i can do to fix these?

Any help would be highly appreciated.

![screen shot 2016-11-07 at 10 13 18 pm](https://cloud.githubusercontent.com/assets/8121938/20068148/8af490b4-a4cc-11e6-89c8-3ba1d92499bd.png)
![screen shot 2016-11-07 at 10 29 50 pm](https://cloud.githubusercontent.com/assets/8121938/20068147/8af2219e-a4cc-11e6-81e5-8a2c715c90f8.png)

**Comment by wf9a5m75** [comment]
If you use the master branch (v1.3.9), I strongly recommend to use the version2-beta (the multiple-maps branch)

**Comment by mrameezraja** [comment]
Should i use 
https://github.com/mapsplugin/cordova-plugin-googlemaps 
or this
https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/multiple_maps

**Comment by wf9a5m75** [comment]
The master branch (https://github.com/mapsplugin/cordova-plugin-googlemaps ) is version 1.3.9, which is too old for me (based on 3 years ago).

The multiple_maps branch (https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/multiple_maps) is version 2.0-beta, which is I rewrite everything with new my new skills (this year). This version consider lots of thing, including performance, and memory management.
The reason of the beta is the documentation is not ready yet.

Read the pages:
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta

And try the demo apk which has lots of documents and demos.
https://github.com/mapsplugin/v2.0-demo

Regarding of the issue for the v2.o-beta, please post to https://github.com/mapsplugin/v2.0-demo/issues

**Comment by mrameezraja** [comment]
Sounds cool. Thanks @wf9a5m75 for such a nice work. :)
