### ISSUE TITLE
Execution failed for task ':processDebugGoogleServices'.

### ISSUE THREAD

**Issue by Shakti-Sharma** [mapsplugin/cordova-plugin-googlemaps#1178]
Error: platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.

FCMPlugin and Geolocation cordova plugin is also used.

Kindly Help
Thanks in Advance

**Comment by wf9a5m75** [comment]
updating the version of the Google Play Services library  to 9.2.0 (at least) in your pc.

**Comment by Shakti-Sharma** [comment]
Yes, i have checked it in the android skd manager, following is the snapshot.

Here in the snapshot google play service version is already upto the 33.

Please let me know if i am missing some thing here or doing some thing wrong here.
![screen shot 2016-11-08 at 9 56 02 pm](https://cloud.githubusercontent.com/assets/4133139/20107656/50fb5346-a5ff-11e6-97f7-530a61220e78.png)



Extra:
I also need to build for ios version.

**Comment by wf9a5m75** [comment]
The Google Play Services should be 37...

**Comment by wf9a5m75** [comment]
@Shakti-Sharma Did you solve this?

**Comment by Shakti-Sharma** [comment]
No, i already updated google play service to 37


Only temporary solution i found is to change the gradle file to specific version.


from
compile "com.google.android.gms:play-services-location:+"

to
compile "com.google.android.gms:play-services-location:9.2.0"


But it will over ride when i generate code from terminal.

Please help how to overide gradle file so that it will not cause any issue!!!

**Comment by Shakti-Sharma** [comment]
i dont have any clue about the ios !!! :(

**Comment by wf9a5m75** [comment]
I think you are missing something

**Comment by Shakti-Sharma** [comment]
i am generating android build using terminal, how do i suppose to change the gradle file.

**Comment by wf9a5m75** [comment]
I updated the plugin.xml.
Please reinstall the plugin from the master branch.


Please reinstall the plugin from the master branch.
```
$> cordova plugin rm cordova-plugin-googlemaps
$> cordova plugin rm cordova-plugin-googlemaps-sdk

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps --variable ...
```

**Comment by wf9a5m75** [comment]
@Shakti-Sharma ping

**Comment by wf9a5m75** [comment]
Since this issue is not updated in past 6 days, I close this issue at once.
If you have any information, please reopen again.
