### ISSUE TITLE
Failing to load tiles on scroll

### ISSUE THREAD

**Issue by loama** [mapsplugin/cordova-plugin-googlemaps#1181]
Hi, I have a very basic implementation of the plugin in my app, it loads nicely but if I scroll too much it stops loading the new tiles.

Just like this:

![screenshot_20161110-220136](https://cloud.githubusercontent.com/assets/5743857/20204024/b08dbc3e-a791-11e6-83f9-05626730d5b1.png)

**Comment by wf9a5m75** [comment]
That's google maps problem. Not plugin

**Comment by loama** [comment]
I changed the center of the map and it still only loads the tiles near to my position.
Do you have any idea on how to fix this?

**Comment by wf9a5m75** [comment]
I think your api key is wrong. Check the logcat

**Comment by loama** [comment]
thanks, that was a stupid error from my part.
