### ISSUE TITLE
addMarker callback not executed

### ISSUE THREAD

**Issue by janrg** [mapsplugin/cordova-plugin-googlemaps#1182]
I'm using ionic 2 and executing on Android M (device, not emulator)
I need to add a marker to a map and retain a reference so I can rotate it later. If I add it via e.g.

```
this.mapping.map.addMarker({'position': coords, 'icon': icon, 'rotation': 90}, (marker) => {
  alert("TEST");
});
```

The marker is placed but the callback is never executed. I've put some debugging output into googlemaps-cdv-plugin.js and everything looks like it's working fine, I've verified via alerts that typeof callback === "function" returns true  and that both self and marker in callback.call are objects.

**Comment by wf9a5m75** [comment]
Please show me the logcat output.

**Comment by janrg** [comment]
Attached
<
[logcat.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/587175/logcat.txt)

**Comment by wf9a5m75** [comment]
```
[ 11-12 11:38:08.525 19893:19893 I/chromium ]
[INFO:CONSOLE(6)] "Error: Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
    at s (file:///android_asset/www/build/polyfills.js:3:8546)
    at file:///android_asset/www/build/polyfills.js:3:8918
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14029)
    at Object.onInvokeTask (file:///android_asset/www/build/main.js:7:10830)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13965)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11389)
    at i (file:///android_asset/www/build/polyfills.js:3:8006)", source: file:///android_asset/www/build/main.js (6)
```

**Comment by janrg** [comment]
Yes I noticed that, but I don't understand what would be causing this.

**Comment by wf9a5m75** [comment]
Check your main.js line 6

**Comment by janrg** [comment]
Ionic automatically compiles the js code, so main.js doesn't have any useful function names and the lines are ~32k characters long.

**Comment by janrg** [comment]
I did just realize though, that even though the map is loaded (and adding markers to it works), the MAP_READY event is never fired.

**Comment by wf9a5m75** [comment]
Do you wait the deviceready event?

**Comment by janrg** [comment]
I use ionic's platform.ready() which I believe wraps deviceready.

**Comment by wf9a5m75** [comment]
Could you share your project with me? (all files)
Put your code on github (or similar service), then invite me please.

**Comment by janrg** [comment]
I had originally set this up with an older version of node which uses extremely deep paths so my windows machine was acting up a bit with it. So I briefly created a minimal working (or rather not working :-)) example:
https://drive.google.com/file/d/0B0vMcooeFY-fT3F6NEEwWDMtTG8/

**Comment by wf9a5m75** [comment]
Git repository please....

**Comment by janrg** [comment]
Apologies, you should have a repo invite now.

**Comment by wf9a5m75** [comment]
I see. You use the ionic wrapper.
Actually I have not created it.

Without wrapper, you can do like this
https://github.com/ZiFFeL1992/maps-v2/blob/master/src/pages/home/home.ts

**Comment by wf9a5m75** [comment]
Sorry, but I'm not familiar with ionic. How to build your project?

**Comment by janrg** [comment]
From the root of the repo, the following steps should build and run

```
npm install
npm install -g ionic
cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID ...
cordova plugin add cordova-plugin-geolocation
ionic run android
```

**Comment by wf9a5m75** [comment]
Ok, I built your project.

And I figured out the solution.
Just change your code like this.

```js
ionViewDidEnter() {
  this.platform.ready().then(() => {
  this.mapping.initMap('map');
  this.mapping.map.on(GoogleMapsEvent.MAP_READY).subscribe(() => {
    alert("MAP_READY");
    ...
  });
});
```

**Comment by janrg** [comment]
Thank you. The map callback is fired now, but the marker callback still isn't.

**Comment by wf9a5m75** [comment]
It seems the ionic wrapper kills the plugin feature for some reason.


The original code style (the below code) works as I expect.

```js
ionViewDidEnter() {
  this.platform.ready().then(() => {

    var div = document.getElementById("map");
    var map = window["plugin"].google.maps.Map.getMap(div, {
      'backgroundColor': 'white',
      'controls': {
        'compass': false,
        'myLocationButton': false,
        'indoorPicker': false,
        'zoom': false
      },
      'gestures': {
        'scroll': true,
        'tilt': false,
        'rotate': false,
        'zoom': true
      },
      'camera': {
        'latLng': {lat: 53.0, lng: 0.0},
        'tilt': 30,
        'zoom': 15,
        'bearing': 50
      }
    });

    map.on(window["plugin"].google.maps.event.MAP_READY, function() {
      map.addMarker({
        position: {lat: 53.0, lng: 0.0}
      }, function(marker) {
        alert("marker is added on the map");
      });
    });

  });
}
```

--------

By the way, if you have just started with this plugin, I **strongly** recommend you use the maps plugin v2-beta.

The current version is written 3 years ago, and the v2-beta is written this year.
The v2-beta improves performance, lots of issues are fixed, and multiple maps are supported.

Installation is easy.

```
$ cordova plugin rm cordova-plugin-googlemaps
$ cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemap
s#multiple_maps --variable API_KEY_FOR_ANDROID="(API Key)" --variable API_KEY_FOR_IOS="
(API Key)"
```

Unfortunately, you can not use the ionic wrapper with the v2.
See the document, https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta

And try the demo apk
https://dl.dropboxusercontent.com/u/1456061/cordova-google-maps/v2/cordova-googlemaps-v2-demo_02.apk

**Comment by janrg** [comment]
Brilliant thank you! I'm using v2 now without the wrapper and it works. Thank you so much for your help.
I think I've found a very minor bug in the marker btw. Lines 238 to 245 in Marker.js read
```
Marker.prototype.setRotation = function(rotation) {
    if (!rotation) {
        console.log('missing value for rotation');
        return false;
    }
    this.set('rotation', rotation);
    return this;
};
```
The issue is that 0 and 0.0 are both falsy, so setRotation(0) will not work. Perhaps something like

`if (!rotation && typeof rotation !== 'number')`

or even just the second condition would be better.

**Comment by wf9a5m75** [comment]
@janrg Thanks for inspecting. I fixed the problem position.
