### ISSUE TITLE
Disable 3D buildings

### ISSUE THREAD

**Issue by gigiojr** [mapsplugin/cordova-plugin-googlemaps#1183]
I found a Android [documentation](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#setBuildingsEnabled%28boolean%29) about disable 3D buildings on Google Maps API using the method `setBuildingsEnabled(false)`, but I don't found nothing in plugin documentation and I need that this works for Android, IOs and Windows Phone.

Is there some solution to help me?

**Comment by wf9a5m75** [comment]
This plugin does not work on Windows phone (no plan to implement).
It seems I forgot to implement the  setBuildingsEnabled(false) method.

**Comment by wf9a5m75** [comment]
I will implement this for both v1.4 and v2.0 in couple of days.

**Comment by wf9a5m75** [comment]
Ok, you can disable the building like this:

```js
var map = plugin.google.maps.Map.getMap(div, {
   'preferences': {
     'building': false
   }
});
```

Please reinstall the plugin from the master branch.
```
$> cordova plugin rm cordova-plugin-googlemaps
$> cordova plugin rm cordova-plugin-googlemaps-sdk

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps --variable ...
```

**Comment by moriczgergo** [comment]
For some reason the aren't disabled, even when I'm using {preferences: {building: false}}.

**Comment by adamduren** [comment]
@moriczgergo Can you share your project or a code sample to reproduce the issue?

**Comment by adamduren** [comment]
Also what platform(s) and version of the plugin?

**Comment by alexp25** [comment]
It seems that using {preferences: {building: false}} does not work. Maybe the setBuildingsEnabled method should be implemented.
