### ISSUE TITLE
"Touch to return call" bar breaks map's height

### ISSUE THREAD

**Issue by Mencls** [mapsplugin/cordova-plugin-googlemaps#1184]
I just noticed that when you take a call or use the Google Maps app, the top bar breaks the height of the map on my app, by something close to 20 pixels. It really looks like the behaviour you described in your "important notice" section.

A simple CSS fix with JQuery as you mentionned could work but I need to trigger this fix when the top bar shows up, and cancel it when it disappears.

Do you have an idea how I could resolve this issue?

**Comment by wf9a5m75** [comment]
Please use the maps plugin v2
