### ISSUE TITLE
Google maps and directions icons from marker click

### ISSUE THREAD

**Issue by craig-at-rsg** [mapsplugin/cordova-plugin-googlemaps#1186]
When my markers are clicked, a couple new buttons slide into view, for Google Driving Directions and Google Maps. I don't want the user to exit my application at this point - it's confusing and irrelevant to what they're doing. How can I prevent these new buttons from showing? 

You can see these buttons next to the +/- zoom control here:

![screen](https://cloud.githubusercontent.com/assets/6004181/20311099/7c0977bc-ab1c-11e6-8e93-347d617e436a.png)

**Comment by craig-at-rsg** [comment]
Did some more research - looks like this is what I need: #983

**Comment by wf9a5m75** [comment]
As I described #983, it was implemented in to the v2-beta version

**Comment by craig-at-rsg** [comment]
Is there any chance of getting this into the main plugin? We're close to a release and we're trying to decide whether we should fork our own version for this.

**Comment by wf9a5m75** [comment]
As I describe the above. That's all.

**Comment by craig-at-rsg** [comment]
Thanks, forked.
