### ISSUE TITLE
Set pointer events or preventDefault on html inside map div

### ISSUE THREAD

**Issue by loama** [mapsplugin/cordova-plugin-googlemaps#1187]
I need to put some draggable elements inside my view but I need to **trigger** pointer-events:none or jquery preventDefault on some of them so that instead of dragging the elements the touch event goes directly to the map which does not seem to work at all.

The only documentation I´ve found is about the inverse issue, setting click events to none for the map.

**Comment by wf9a5m75** [comment]
The plugin does not control html click at all

**Comment by loama** [comment]
Do you know which event I can send to the map div to simulate the touch?

**Comment by wf9a5m75** [comment]
I'm very confusing.
The plugin does not block the JS touch events at all.

Could you explain more details, such as providing example code, or screen record (video) etc...

**Comment by loama** [comment]
I have the map covering the entire screen and I am putting an overlay with touch gestures (a slider).

I want to make one slide invisible (transparent) and set pointer-events:none so that if the user wants to move the map, they will be able to.
It works fine with a JS map but when I change the map to a native map (using this plugin) the pointer events do not pass to the map.

**Comment by loama** [comment]
This is the code. ( I simplified it to just the basic functionality)

A slider with a transparent page and pointer-events:none
A fullscreen native map behind it, so that only in a slider page with pointer events none you are able to move the map.

![captura de pantalla 2016-11-16 a la s 19 44 39](https://cloud.githubusercontent.com/assets/5743857/20373071/388444b2-ac35-11e6-9fb4-66ca9da58a23.png)

I also uploaded a video to youtube with the example working with JS map.

https://www.youtube.com/watch?v=kpImyrMZsU0

**Comment by loama** [comment]
Also, with the plugin it only seems to break when I put a touch event. If I put a simple div with pointer events none it does go to the map.

**Comment by wf9a5m75** [comment]
Ah, I see. you are completely misunderstand how to use this plugin.
You use this plugin version 1.3.9 (npm or master).
The version 1.x supports **ONLY under the map div**.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#put-html-elements-on-the-map

It means the page divs **MUST BE UNDER the map div** like this:
```html
<div id="map_canvas">
  <div id="prueba" style="pointer-events: none">
    <ul>
     ....
    </ul>
  </div>
</div>
```

**Comment by loama** [comment]
I have tried it inside and outside the map div and it just does the same.

Simple div works.
Implement touch actions and it breaks.

**Comment by wf9a5m75** [comment]
There is another possible solution.
The plugin version 2-beta should recognize the html region automatically without putting your HTMLs under the map div.
But some people faces unexpected error, so currently it's beta.

If you want to try it, check out these documents.
https://github.com/mapsplugin/cordova-plugin-googlemaps#version-20-beta
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta

**Comment by wf9a5m75** [comment]
> Implement touch actions and it breaks. 

Without providing example project, I don't (can't) inspect the issue.

**Comment by loama** [comment]
If you could take a look at my project I would be really thankful.

https://www.dropbox.com/s/m4rw4a7upza1fng/mapsslider.zip?dl=0

It currently has the fullscreen native map and a top slider, which second page has pointer events none, so it should move the map.

One thing I´ve seen is that the slider also won´t work at all if I don´t set it a z-index above 1.

**Comment by wf9a5m75** [comment]
I checked your code.
As I described the above, you **MUST** put your HTML elements under the `map div`.

```html
<body>
  <div id="map_canvas">
    <!--<button id="button" onclick="drawRoute(19.411872, -99.180580, 0)">Full Screen</button>
    <button id="button" onclick="watchCompass()">Full Screen</button>
    <div id="compass">545542</div>-->
    <div id="prueba">
      <ul>
        <li class="first dragend-page" style="pointer-events: auto"></li>
        <li class="middle dragend-page"></li>
        <li class="last dragend-page" style="pointer-events: auto"></li>
      </ul>
    </div>
  </div>

</body>
```

And it seems the `dragend.min.js` inserts a `<div>` under the`<div id="prueba">` automatically.
The inserted `<div>` blocks all touches.

**Comment by wf9a5m75** [comment]
![screen shot 2016-11-21 at 10 33 06 pm](https://cloud.githubusercontent.com/assets/167831/20513490/0497e85c-b03b-11e6-9585-3289180e6fb6.png)

**Comment by wf9a5m75** [comment]
@loama ping
