### ISSUE TITLE
Map Drag Listener Implementation For Android

### ISSUE THREAD

**Issue by yasiramidtech** [mapsplugin/cordova-plugin-googlemaps#1191]
Hello, I am using your plugin for my android app, i want to know that how can i implement map callback functions like drag etc. if i am using only android?

**Comment by Fayozjon** [comment]
`	map.addEventListener(plugin.google.maps.event.MAP_READY, function(){
	map.addEventListener(plugin.google.maps.event.MAP_LOADED, function() { 
								//EXAMPLE
							}); 
   `

**Comment by yasiramidtech** [comment]
ACTION_DOWN and ACTION_UP event not working , can you share any example ??

**Comment by wf9a5m75** [comment]
What is that?

**Comment by yasiramidtech** [comment]
This is touchstart and touchend event on map

**Comment by wf9a5m75** [comment]
This plugin supports only these events.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#listen-events

**Comment by yasiramidtech** [comment]
CAMERA_CHANGE event not working , i'm using  CAMERA_CHANGE event inside the MAP_READY evetn.Actually i want to get latlng on CAMERA_CHANGE.
Thanks

**Comment by wf9a5m75** [comment]
Could you show me your code?

**Comment by yasiramidtech** [comment]
$ionicPlatform.ready(function () {
        var div = document.getElementById("map_canvas");
        var map = plugin.google.maps.Map.getMap(div);
        var lat, long;
        var onSuccess = function (location) {
            lat = location.latLng.lat;
            long = location.latLng.lng;
            console.log(lat + " - - " + long);
            url = "http://maps.googleapis.com/maps/api/geocode/json?latlng=" + lat + "," + long + "&sensor=true"
                    console.log(url);
                    $.get(url).success(function (data) {
                        console.log(data.results[0].formatted_address);
                        addresss = data.results[0].formatted_address;
                        $rootScope.pick123 = addresss;
                    }).
            error(function (error) {
                console.log(error);
            });
            map.setMyLocationEnabled(true);
            var msg = ["Current your location:\n",
            "latitude:" + location.latLng.lat,
            "longitude:" + location.latLng.lng,
            "speed:" + location.speed,
            "time:" + location.time,
            "bearing:" + location.bearing].join("\n");

            map.animateCamera({
                'target': location.latLng,
                'tilt': 20,
                'zoom': 16,
                'bearing': 25,
                'duration': 3000 // 10 seconds
            } //,
            //map.on(plugin.google.maps.event.MAP_CLICK, function (latLng)
            //{
            //    alert("Map was clicked.\n" +
            //          latLng.toUrlValue());
            //})
            );
        };
        var onError = function (msg) {
            alert("error: " + msg);
        };
        map.getMyLocation(onSuccess, onError);
        

        map.addEventListener(plugin.google.maps.event.MAP_READY, function () {

            map.addEventListener(plugin.google.maps.event.CAMERA_CHANGE, function (position) {
                map.getCameraPosition(function (camera) {
                    var buff = ["Current camera position:\n",
                    "latitude:" + camera.target.lat,
                    "longitude:" + camera.target.lng,
                    "zoom:" + camera.zoom,
                    "tilt:" + camera.tilt,
                    "bearing:" + camera.bearing].join("\n");
                    alert(buff);
                });
            });

        });


    });

**Comment by yasiramidtech** [comment]
how to get latlng on CAMERA_MOVE_END event?

**Comment by wf9a5m75** [comment]
You don't understand the basic of this plugin at all.....

```js
$ionicPlatform.ready(function () {
  var div = document.getElementById("map_canvas");
  var map = plugin.google.maps.Map.getMap(div);

  // You MUST wait the MAP_READY event first!!!!!
  map.addEventListener(plugin.google.maps.event.MAP_READY, function () {

    var lat, long;
    var onSuccess = function (location) {
        ...
    };
    var onError = function (msg) {
        alert("error: " + msg);
    };
    map.getMyLocation(onSuccess, onError);

    map.addEventListener(plugin.google.maps.event.CAMERA_CHANGE, function (position) {
        map.getCameraPosition(function (camera) {
            var buff = ["Current camera position:\n",
            "latitude:" + camera.target.lat,
            "longitude:" + camera.target.lng,
            "zoom:" + camera.zoom,
            "tilt:" + camera.tilt,
            "bearing:" + camera.bearing].join("\n");
            alert(buff);
        });
    });
    
  });
});
```

**Comment by wf9a5m75** [comment]
@yasiramidtech ping

**Comment by yasiramidtech** [comment]
I got it worked like this:

$ionicPlatform.ready(function () {

var div = document.getElementById("map_canvas");
var  map = plugin.google.maps.Map.getMap(div);

var onSuccess = function (location) {
            
            map.animateCamera({
                'target': location.latLng,
                'tilt': 20,
                'zoom': 16,
                'bearing': 25,
                'duration': 3000 // 10 seconds
            } ,
            map.on(plugin.google.maps.event.CAMERA_MOVE_END, function (location)
            {
                
                console.log(location.target.lat);
                console.log(location.target.lng);
                currentLat = location.target.lat;
                currentLon = location.target.lng;
                GetLat = location.target.lat;
                GetLong = location.target.lng;
                
            })
            );
        };
        var onError = function (msg) {
            alert("error: " + msg);
        };

})

**Comment by wf9a5m75** [comment]
Good.
