### ISSUE TITLE
getCameraPosition() does not work

### ISSUE THREAD

**Issue by ibadrehman90** [mapsplugin/cordova-plugin-googlemaps#1192]
I am trying to get some work done on getCameraPosition() function. Even the demo code snippet provided does not work:

map.getCameraPosition(function(camera) {
  var buff = ["Current camera position:\n",
      "latitude:" + camera.target.lat,
      "longitude:" + camera.target.lng,
      "zoom:" + camera.zoom,
      "tilt:" + camera.tilt,
      "bearing:" + camera.bearing].join("\n");
  alert(buff);
});

**Comment by wf9a5m75** [comment]
I guess you don't wait the MAP_READY event.

**Comment by Fayozjon** [comment]
`$rootScope.map.addEventListener(plugin.google.maps.event.MAP_READY, function(){
						 
							$rootScope.map.addEventListener(plugin.google.maps.event.MAP_LOADED, function() { 
								loadMarkers();
							}); 
							
							$rootScope.map.addEventListener(plugin.google.maps.event.CAMERA_CHANGE, function(position) {
								loadMarkers();
							});
						 
						});`

**Comment by Fayozjon** [comment]
Wrap your listeners into MAP_READY event

**Comment by ibadrehman90** [comment]
Thank you guys. I will give it a try and update.

**Comment by wf9a5m75** [comment]
@ibadrehman90 ping

**Comment by ibadrehman90** [comment]
I got it worked like this:

 map.on(plugin.google.maps.event.CAMERA_MOVE_END, function (location)
            {
                console.log(location.target.lat);
                console.log(location.target.lng);
 }),

Similarly on start event

 map.on(plugin.google.maps.event.CAMERA_MOVE_START, function (location)
            {
                console.log("working"); 
               console.log(location.target);
             
            })

**Comment by wf9a5m75** [comment]
good
