### ISSUE TITLE
Catch a user-triggered drag event on both IOS and Android

### ISSUE THREAD

**Issue by overlox** [mapsplugin/cordova-plugin-googlemaps#1195]
Hi, I'm trying to implement a "reload pins on drag" system, but the only event I can use for both IOS and android is CAMERA_CHANGE, which is triggered at the end of the move, and makes any non-user camera changes reloading twice.

Any solution to fix this ? I saw I could use MAP_WILL_MOVE for IOS which works fine.
Any way to get any event on android ? 

I saw that the beta ~~alpha~~ implements CAMERA_MOVE_START  ~~MAP_CHANGE_START~~ but it's too unstable to use right now.
Thanks ! 

```
      map.on(plugin.google.maps.event.CAMERA_CHANGE, function(){
        if (camera_active === false)
          // needs to reload data, should be triggered by user input 
         // triggers AFTER camera_active is set back to false
      });

    var updateMap = function(results){ // camera moves triggered by non-user input
        camera_active = true;
        map.moveCamera({
          'target' : 
        }, function(){
          camera_active = false;
        });
      }

```

**Comment by wf9a5m75** [comment]
Use the `CAMERA_MOVE_START` event of the plugin v2-beta.

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#version-2x-events

**Comment by overlox** [comment]
@wf9a5m75 I've already tried using the branch mutliple-maps but it was very unstable (crashes on pin changes and crashes at map load), and the CAMERA_MOVE_START did not trigger properly even.

**Comment by wf9a5m75** [comment]
Do you use the code for v2?
I mean if you move to v2, you have to rewrite your code with v2 style (except very simple code).

If you use the ionic wrapper (or something), it does not work at all.

**Comment by wf9a5m75** [comment]
Try the demo apk file.
https://github.com/mapsplugin/v2.0-demo#demo-apk

**Comment by overlox** [comment]
I tried it a while ago and I see you updated the doc so I'll give it another try!
Amazing work BTW

**Comment by wf9a5m75** [comment]
@overlox ping

**Comment by overlox** [comment]
@wf9a5m75 

CAMERA_MOVE_START works fine on Android and IOS

I tried it again today branch #1171  
And there are a few problems I noticed : 

`map.setMyLocationEnabled(true);`
> crash on android
> not displayed on IOS

```
          map.addMarker({
              ..
              // icon: {url: 'img.png'}
            },
```
> not displayed on IOS
> works on android

**+ a few random crashes on IOS at startup and while using**

If you need stack traces or any other thing let me know.

**Comment by wf9a5m75** [comment]
I don't play with quiz. Please provide more valuable information, such as native error log and your actual code.

**Comment by overlox** [comment]
How do I get the native logs ?

**Comment by overlox** [comment]
@wf9a5m75 I updated the comment above with all I could get. I keep an xcode open to catch any log if the app crashes.
Thanks,

**Comment by overlox** [comment]
A crash on "map.clear()" 

2016-11-24 11:53:06.883 Gault&Millau Restaurant[18865:3513718] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112e2734b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000011286621e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112d373b3 -[__NSPlaceholderArray initWithObjects:count:] + 275
	3   CoreFoundation                      0x0000000112d3e5c4 +[NSArray arrayWithObjects:count:] + 52
	4   CoreFoundation                      0x0000000112d3e35c -[NSDictionary allKeys] + 204
	5   Gault&Millau Restaurant             0x000000010ef2628f -[PluginMap clear:] + 559
	6   Gault&Millau Restaurant             0x000000010ef850c6 -[CDVCommandQueue execute:] + 870
	7   Gault&Millau Restaurant             0x000000010ef84921 -[CDVCommandQueue executePending] + 833
	8   Gault&Millau Restaurant             0x000000010ef7b12a __40-[CDVCommandDelegateImpl evalJsHelper2:]_block_invoke + 314
	9   Gault&Millau Restaurant             0x000000010ef8785c -[CDVUIWebViewEngine evaluateJavaScript:completionHandler:] + 156
	10  Gault&Millau Restaurant             0x000000010ef7afa4 -[CDVCommandDelegateImpl evalJsHelper2:] + 212
	11  Foundation                          0x00000001123966be __NSThreadPerformPerform + 326
	12  CoreFoundation                      0x0000000112dcc311 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	13  CoreFoundation                      0x0000000112db159c __CFRunLoopDoSources0 + 556
	14  CoreFoundation                      0x0000000112db0a86 __CFRunLoopRun + 918
	15  CoreFoundation                      0x0000000112db0494 CFRunLoopRunSpecific + 420
	16  GraphicsServices                    0x0000000116959a6f GSEventRunModal + 161
	17  UIKit                               0x00000001109db964 UIApplicationMain + 159
	18  Gault&Millau Restaurant             0x000000010eef7251 main + 65
	19  libdyld.dylib                       0x000000011459168d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by overlox** [comment]
pong @wf9a5m75

**Comment by wf9a5m75** [comment]
I could not reproduce your issue. Please provide your example code that reproduce the issue 100%.
I think the issue is depends on your code.

**Comment by overlox** [comment]
Ok thanks I'll give you a snippet ASAP.
Any idea for map.setMyLocationEnabled(true); ?

**Comment by wf9a5m75** [comment]
```js
var map = plugin.google.maps.Map.getMap(div, {
  'controls': {
    'myLocationButton': true
  }
});
```

**Comment by wf9a5m75** [comment]
@overlox ping

**Comment by overlox** [comment]
@wf9a5m75 I managed to get it working with timeouts which I did not needed before.
I still have a big issue with setClickable acting wierdly on IOS. Sometimes the map freezes and impossible to enable it with setClickable(true). Any thoughts on this ? I'll give you my code if needed

**Comment by overlox** [comment]
Hi, due to my company restrictions I can't share the whole code with you (sadly).
I found a new bug though, if location is disabled by the user and my locationbutton set to true, onMapInit is not triggered.
I also can't fix the issue with getting custom pins to work with IOS, must be a path problem but i tried everything.

```
 map = plugin.google.maps.Map.getMap(div,{
        'camera': {
          'latLng': new plugin.google.maps.LatLng(0, 0),
          'zoom': 4.
        },
        'controls': { 'myLocationButton': true }
      });
      map.addEventListener(plugin.google.maps.event.MAP_READY, function onMapInit() {
         // not triggered if user disabled location
      });
```

```
  _.each(results, function(r){
        map.addMarker({
            position: new plugin.google.maps.LatLng(r._geoloc.lat, r._geoloc.lng),
            identifier: r.id,
            title: r.name,
             icon: {url: 'img.png'}
          });
```

**Comment by wf9a5m75** [comment]
```js
 map = plugin.google.maps.Map.getMap(div,{
        'camera': {
          'latLng': new plugin.google.maps.LatLng(0, 0),
          'zoom': 4.
        }
      });
      map.addEventListener(plugin.google.maps.event.MAP_READY, function onMapInit() {
         map.setOptions({
           'controls': { 'myLocationButton': true }
         });

        _.each(results, function(r){
          map.addMarker({
             position: new plugin.google.maps.LatLng(r._geoloc.lat, r._geoloc.lng),
             identifier: r.id,
             title: r.name,
              icon: {url: 'www/img.png'}
          });
      });
```

**Comment by overlox** [comment]
I use v2 and have to because of CAMERA_MOVE_START

**Comment by wf9a5m75** [comment]
Even v2, the same code should work.

**Comment by overlox** [comment]
Thanks it worked for the location button.
Also I don't know if I should open another issue but when the map is within a scrolling view, it doesnt update in real time with the scrolling. 
Any solution to that ? 
the map is setClickable(false)

**Comment by wf9a5m75** [comment]
The plugin must delay the position because the map view is not a html element.
There is no way to resolve it.
