### ISSUE TITLE
setPosition() does not work

### ISSUE THREAD

**Issue by ibadrehman90** [mapsplugin/cordova-plugin-googlemaps#1197]
I am trying to change the marker's position on click event but every time it gives me an error like:

controllers.js:76 Uncaught TypeError: Cannot read property 'setPosition' of undefined(…)

My code:

```js
PickUpPosition = new plugin.google.maps.LatLng(24.8290593, 67.0221618);
            var marker =  map.addMarker({
                position: PickUpPosition,
                title: "Your PickUp",
                snippet: "This app is awesome!",
                icon: 'img/drop off-01.png'
            })
             var mylatLng = new plugin.google.maps.LatLng(24.843286, 67.053242);
             marker.setPosition(mylatLng);
```

P.S it also gives me the error as Error in Success callbackId: CordovaGoogleMaps1953897352 : TypeError: Cannot read property 'setPosition' of undefined

**Comment by wf9a5m75** [comment]
Please read the wiki pages before asking.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker

You **MUST** use callback.

```js
PickUpPosition = new plugin.google.maps.LatLng(24.8290593, 67.0221618);

map.addMarker({
    position: PickUpPosition,
    title: "Your PickUp",
    snippet: "This app is awesome!",
    icon: 'img/drop off-01.png'
}, function(marker) {
    var mylatLng = new plugin.google.maps.LatLng(24.843286, 67.053242);
    marker.setPosition(mylatLng);
});
```

**Comment by ibadrehman90** [comment]
Thank you! I will give it a try.

**Comment by ibadrehman90** [comment]
It seems to be working. Could you also tell me how this can be achieved on MAP_CLICK event?

**Comment by ibadrehman90** [comment]
Any help will be appreciated.

Thank You

**Comment by wf9a5m75** [comment]
>I literally can not do anything with this function outside. Main aim is to put it inside a separate function and call that function inside setTimeout();

Could you show me what you do want?

**Comment by ibadrehman90** [comment]
I am only trying to update the marker's position on a given time interval. 

`map.addMarker({
            position: PickUpPosition,
            title: "Your PickUp",
            snippet: "This app is awesome!",
            icon: 'img/drop off-01.png'
        }, 
        );
             
            setInterval(function ()
        {                       //code starts for moving marker
            abc();
        },5500);

        function abc(marker) {
            
            var mylatLng = new plugin.google.maps.LatLng(24.901730, 67.040126);
            marker.setPosition(mylatLng);
        }`

**Comment by wf9a5m75** [comment]
```
map.addMarker({
  position: PickUpPosition,
  title: "Your PickUp",
  snippet: "This app is awesome!",
  icon: 'img/drop off-01.png'
}, function(marker) {

  setInterval(function() {
      abc(marker);
   }, 5500);
});

function abc(marker) {
    marker.setPosition({ lat: 24.901730, lng: 67.040126});
}
```

**Comment by ibadrehman90** [comment]
Thank you for your quick response! I am gonna try this now.

**Comment by ibadrehman90** [comment]
Its working fine now. Thanks again!
Could you also guide me on how to slow down marker animation?
Cheers!

**Comment by wf9a5m75** [comment]
```js
map.animateCamera({
  'target': GOOGLE,
  'tilt': 60,
  'zoom': 18,
  'bearing': 140,
  'duration': 10000 // 10 seconds
});
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#move-the-camera-within-a-specified-duration-time

**Comment by ibadrehman90** [comment]
Appreciate it! I meant to say marker's transition from point A to B. Such as while seeing a car moving smoothly on the map. I was using a JS library for this but that is not compatible with this cordova maps.
