### ISSUE TITLE
Does not build on IOS

### ISSUE THREAD

**Issue by Ross-Rawlins** [mapsplugin/cordova-plugin-googlemaps#1199]
It works beautifully on android but when I try build on IOS it fails. it says its something to do with the main activity code of the plugin.

**Comment by wf9a5m75** [comment]
Please provide mor valuable information, such as native log or share your project files(using github or bitbucket).

**Comment by TheSegfault** [comment]
Hi,

Cordova 6.0.0 iOS set to 8.0 ionic1 
Master branch of your plugin

Everytime i got a wall of error 
<img width="247" alt="screen shot 2016-11-29 at 10 36 59" src="https://cloud.githubusercontent.com/assets/5268918/20704509/cf39eb84-b61f-11e6-96f4-fd8c2cf9676d.png">

**Comment by wf9a5m75** [comment]
It seems you fails install the plugin.
<img width="247" alt="cf39eb84-b61f-11e6-96f4-fd8c2cf9676d" src="https://cloud.githubusercontent.com/assets/167831/20707055/e045b520-b5de-11e6-8f68-3ce6919a5e73.png">

**Comment by Ross-Rawlins** [comment]
I resolved this by uninstalling and re installing platforms and plugin.
