### ISSUE TITLE
Map does not react after app was in background

### ISSUE THREAD

**Issue by pke** [mapsplugin/cordova-plugin-googlemaps#1201]
Bringing back the app to the foreground does not allow any more movements or touches on it.
Is there anything we need to do manually that the plugin should handle automatically?

**Comment by wf9a5m75** [comment]
The plugin v1 does not design for the case.
You should take care by yourself at this time please.

**Comment by pke** [comment]
how to take care of that?
It's working on Android though.

**Comment by wf9a5m75** [comment]
I don't know. Invest please.

**Comment by pke** [comment]
hmmm. I wonder, has this plugin ever been used in a serious production app? Do you know anything about that?

**Comment by wf9a5m75** [comment]
I don't know. You can choose use this plugin or others.

**Comment by wf9a5m75** [comment]
Since there is no enough information provided and he just testing, I close this issue.
