### ISSUE TITLE
camera center over polygon

### ISSUE THREAD

**Issue by alextapia007** [mapsplugin/cordova-plugin-googlemaps#1202]
is not an issue properly... really its a question.
Are some way to detect when camera center are over polygon?

**Comment by alextapia007** [comment]
or simulate a tap... in the center of the camera?

**Comment by wf9a5m75** [comment]
**v1 code**

```
polygon.on(plugin.google.maps.event.OVERLAY_CLICK, function(overlay) {

});
```

**v2 code**

```
polygon.on(plugin.google.maps.event.POLYGON_CLICK, function(clickLatLng) {
  
});
```

**Comment by alextapia007** [comment]
i already try it... but only work whit phisycall tap...

**Comment by wf9a5m75** [comment]
Did you try `polygon.trigger(plugin.google.maps.event.OVERLAY_CLICK)`?

**Comment by wf9a5m75** [comment]
The plugin does not provide to detect the feature that the point is contained in a polygon.

However you can port the code from Java to JS.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/ecdccaf5ad5e2b52a34fe15a83ac92f0a6efab01/src/android/plugin/google/maps/GoogleMaps.java#L1599-L1630

**Comment by alextapia007** [comment]
i will try polygon.trigger(plugin.google.maps.event.OVERLAY_CLICK)... i hope tell you latter a good news

**Comment by wf9a5m75** [comment]
@alextapia007 ping
