### ISSUE TITLE
Blank map on iOS

### ISSUE THREAD

**Issue by flipjack** [mapsplugin/cordova-plugin-googlemaps#1204]
i have this blank map on iOS 

![2035dcee-b27b-11e6-9f71-dcf26a61aa09](https://cloud.githubusercontent.com/assets/4236722/20736093/fd4e8364-b669-11e6-8848-e64313455d2b.png)

im change api keys in config.xml before prepare

![screen shot 2016-11-29 at 19 27 45](https://cloud.githubusercontent.com/assets/4236722/20736109/1ba00644-b66a-11e6-9ea0-2f7e910cc401.png)

i have this api's enable 

![screen shot 2016-11-29 at 19 36 46](https://cloud.githubusercontent.com/assets/4236722/20736302/450ddcc6-b66b-11e6-9ff8-c539e53b8f11.png)

**Comment by wf9a5m75** [comment]
You have to enable **Google Maps SDK for iOS** and **Google Maps Android API**.

**NOT Google Maps JavaScript API**

**Comment by flipjack** [comment]
All api's in the image are enable

![screen shot 2016-11-29 at 20 07 10](https://cloud.githubusercontent.com/assets/4236722/20736990/a2d67a4e-b66f-11e6-92e8-4bf975b21e3d.png)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map

or try to recreate your key. Sometime work

**Comment by dominikstrasser** [comment]
i'm also seeing a blank page...
the debugger says `_nw_connection_get_connected_socket_block_invoke 10 Connection has no connected handler `
anyone has an answer for this problem?

**Comment by wf9a5m75** [comment]
@dominikstrasser Please share your whole error logs.

**Comment by dominikstrasser** [comment]
I´m sorry it was my fault...
i figured out this error had something to do with firebase and not this plugin... :/
my problem not seeing the map was related to the current version of ionic 2.
for now i switched to the google maps js api but i´m looking forward to version 2 of this project :-)
keep up the good work 👍

**Comment by sunny061** [comment]
+1

I did go through the blank map troubleshooting guide and also made sure I have enabled the Google Maps iOS SDK but the map is still blank for me on iOS. There are no errors for me to share here. Just a blank map. Is there any way I can debug this issue further? I am using this plugin in an ionic 1 project.

**Comment by sunny061** [comment]
I finally managed to solve why mine is blank. So I will just leave a comment here in case someone else hits this problem, it turns out height is needed to make the map display on iOS (Android has no issues). The examples given in the wiki do have a fixed height however I don't see it mentioned anywhere that it is necessary for it to work on iOS.

Also, height: 100% will not work. You have to use height:100vh if you want it to take the full height.
