### ISSUE TITLE
<v2-beta> Hint for Ionic 2 users

### ISSUE THREAD

**Issue by schobbent** [mapsplugin/cordova-plugin-googlemaps#1205]
If like me you use Ionic2 and the v2, you need to know that the consts of GoogleMapsEvent from "ionic-native" are no more compatible (for some)

I had the problem with 
```
    //GoogleMapsEvent.MAP_LONG_CLICK in the stable version
    this.map.on(plugin.google.maps.event.MAP_LONG_CLICK).then( () => { ... } )
```

SO you need to use "plugin.google.maps.event", and if you have the error "cannot find name plugin", you need to declare a fake interface at the top. Like that

```
interface plugin {
    google:any;
};

declare var plugin;
```

Keep in mind that the V2 is still in BETA.

@wf9a5m75, is the GoogeMapsEvent from Ionic-native in relation with your plugin or it's more a general thing ? 

Just to give you more infos

```
GoogleMapsEvents.MAP_LONG_CLICK = "map_long_click"
plugin.google.maps.event.MAP_LONG_CLICK = "long_click"
```

**Comment by schobbent** [comment]
And " GoogleMap.isAvailable()" doesn't work too

**Comment by wf9a5m75** [comment]
The ionic wrapper is not compatible with the v2beta.
I don't touch about the ionic wrapper.

**Comment by schobbent** [comment]
@wf9a5m75 Do you know who maintain the ionic wrapper ? So I can advert them for the future release of the v2 ? ^^

**Comment by wf9a5m75** [comment]
Check out here
https://forum.ionicframework.com/t/google-maps-cordova-plugin-googlemaps-will-be-changed/68191/1

**Comment by AsimNet** [comment]
your hint is priceless .

thanks.
