### ISSUE TITLE
IOS not compiling.

### ISSUE THREAD

**Issue by Ross-Rawlins** [mapsplugin/cordova-plugin-googlemaps#1206]
GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform

When I try to add the plugin to my platform I get this error. How do I go about adding it.

**Comment by wf9a5m75** [comment]
Please provide whole error logs.

**Comment by Ross-Rawlins** [comment]
I had to uninstall the plugin remove my platform re add my platform and re install again and it finally worked.

**Comment by wf9a5m75** [comment]
👍
