### ISSUE TITLE
Extend changing bounds with CAMERACHANGE event ajax listiner

### ISSUE THREAD

**Issue by Fayozjon** [mapsplugin/cordova-plugin-googlemaps#1207]
Hello everyone! 
Please give me tips how to make app automatically zoom out on map when all markers after loaded fully.
My listing. But with this solution i got event loop = UNLIMITED LOADING MARKERS AND CHANGING BOUNDS.

By the way im using 1st version because 2 nd not  usable with crosswalk.

My listing:

`

    function loadMarkers(){ 
		$rootScope.is_loading_now = true;  
		
		map = $rootScope.map;
		map.getCameraPosition(function(camera) {
			
			$rootScope.centerz = {
									lat: camera.target.lat,
									lng: camera.target.lng
								};
								 		
			  $rootScope.camerazoom = camera.zoom;  
		 });
		 
		 
		 
		  map.getVisibleRegion(function(boundsx){  
				$rootScope.boundz = {
					northeast: {
						lat: boundsx.northeast.lat,
						lng: boundsx.northeast.lng
					},
					southwest: {
						lat: boundsx.southwest.lat,
						lng: boundsx.southwest.lng
					}
				}; 
				
				 
			});
		  
      
      
		var hints = ['Аптеки партнеры','Не участвуют в поиске','Сеть аптек'];
		var boundingRadius = getBoundingRadius($rootScope.centerz, $rootScope.boundz.northeast);
        
		var params = {
            "centre": $rootScope.centerz,
            "bounds": $rootScope.boundz,
            "zoom": $rootScope.camerazoom,
            "boundingRadius": 3 
        }; 
        
		var markers = Markers.getMarkers(params).then(function(markers){
        
		var records = markers.data.results;
		// list of all promises
		var promises = [];
		var new_bounds = [];
			angular.forEach(records, function (record, i) { 
			
			 var deferred = $q.defer();
			  
			   
					var markerPos = new plugin.google.maps.LatLng(record.GEO.LAT,record.GEO.LNG); 
					
					/***
					 	var _icon = { 
								url:'www/img/online_new.png'  
						}; 
					***/
					 
						var _icon ="red";
					
					if (record.FORMA !== undefined){
                        infoWindowContent = "<p>Аптека:<b>" + record.orgNAME + "</b><br>Адрес: " + record.STREET + "<br>Часы работы: " + record.MODE + "<br>Ориентир " + record.LANDMARK + "</p>";
                    }else{
                        infoWindowContent = "<p>Адрес: " + record.STREET + "<br>Часы работы: " + record.MODE +"<br>Тип:"+hints[record.ORGTYPE-1]+"<br>Ориентир " + record.LANDMARK + "</p>";
                    } 
					
                    var markerx = $rootScope.map.addMarker({ 
                        'icon':_icon,
                        'position': markerPos, 
						'id':record.ID, 
						'disableAutoPan': true,
						'iwin':infoWindowContent,
						'title': record.NAME.toUpperCase(),  
						'markerClick': function(marker){  
									$rootScope._marker_title = marker.get('title');
									$rootScope._marker_content = marker.get('iwin');
									$rootScope._marker_phone = record.PHONES[0];
									$rootScope.IS_OPEN = record.IS_OPEN;
									$rootScope.openModal(); 
						}
					},function(marker){
						marker.setIcon(_icon);
					});
					 
					new_bounds.push(markerPos); 
                    markerCache.push(markerx); 
					deferred.resolve(record);
        
					promises.push(deferred.promise);
 
			}); 
			 
			$q.all(promises).then( 
				function(){
					   //////HERE IM RUNNING CAMERA CHANGE BOUNDS BY new_bounds variable AND GETTING LOOP
				   $rootScope.is_loading_now = false;
				}, 
				function(response) {
				}
			); 
        });
		 

    }
`

I have such events 
`	$rootScope.map.addEventListener(plugin.google.maps.event.CAMERA_CHANGE, function(position){
								loadMarkers();
							});`

**Comment by Fayozjon** [comment]
please give some tips im stuck here. @wf9a5m75

**Comment by wf9a5m75** [comment]
Could you make a more simple code?

**Comment by Fayozjon** [comment]
I can say that its loads markers from API backend, after fully loaded its have to zoom out map to the markers bound. But i hang an event at CAMERA_CHANGE for loading markers for user interactions with map. I have only this event because its first VERSION of map plugin.
Can you give example how to implement it better?

**Comment by Fayozjon** [comment]
`const GORYOKAKU_POINTS = [
  new plugin.google.maps.LatLng(41.79883, 140.75675),
  new plugin.google.maps.LatLng(41.799240000000005, 140.75875000000002),
  new plugin.google.maps.LatLng(41.797650000000004, 140.75905),
  new plugin.google.maps.LatLng(41.79637, 140.76018000000002),
  new plugin.google.maps.LatLng(41.79567, 140.75845),
  new plugin.google.maps.LatLng(41.794470000000004, 140.75714000000002),
  new plugin.google.maps.LatLng(41.795010000000005, 140.75611),
  new plugin.google.maps.LatLng(41.79477000000001, 140.75484),
  new plugin.google.maps.LatLng(41.79576, 140.75475),
  new plugin.google.maps.LatLng(41.796150000000004, 140.75364000000002),
  new plugin.google.maps.LatLng(41.79744, 140.75454000000002),
  new plugin.google.maps.LatLng(41.79909000000001, 140.75465),
  new plugin.google.maps.LatLng(41.79883, 140.75673)
];

var latLngBounds = new plugin.google.maps.LatLngBounds(GORYOKAKU_POINTS);
map.animateCamera({
  'target' : latLngBounds
});

EACH LOADING HERE CHANGE BOUNDS TARGET OF CAMERA


map.addEventListener(function(){
GORYOKAKU_POINTS.push(new google.maps.plugin.LatLng(random,random))});
`

This an example

**Comment by wf9a5m75** [comment]
Adding multiple markers on the map, then changing the camera, should be like this:

```js
const GORYOKAKU_POINTS = [
  new plugin.google.maps.LatLng(41.79883, 140.75675),
  new plugin.google.maps.LatLng(41.799240000000005, 140.75875000000002),
  new plugin.google.maps.LatLng(41.797650000000004, 140.75905),
  new plugin.google.maps.LatLng(41.79637, 140.76018000000002),
  new plugin.google.maps.LatLng(41.79567, 140.75845),
  new plugin.google.maps.LatLng(41.794470000000004, 140.75714000000002),
  new plugin.google.maps.LatLng(41.795010000000005, 140.75611),
  new plugin.google.maps.LatLng(41.79477000000001, 140.75484),
  new plugin.google.maps.LatLng(41.79576, 140.75475),
  new plugin.google.maps.LatLng(41.796150000000004, 140.75364000000002),
  new plugin.google.maps.LatLng(41.79744, 140.75454000000002),
  new plugin.google.maps.LatLng(41.79909000000001, 140.75465),
  new plugin.google.maps.LatLng(41.79883, 140.75673)
];
addMarkers(GORYOKAKU_POINTS, function(markers) {
  map.animateCamera({
    target : GORYOKAKU_POINTS
  });
});

function addMarkers(points, callback) {
  var markers = [];
  function onMarkerAdded(marker) {
    markers.push(marker);
    if (markers.length === data.length) {
      callback(markers);
    }
  }
  points.forEach(function(position) {
    map.addMarker({
      position: position
    }, onMarkerAdded);
  });
}
```

**Comment by wf9a5m75** [comment]
If you want to expand the bounds automatically, should be like this:
(This is not plugin issue anymore though)

```js
var cameraMoving = false;

var positions = [
  new plugin.google.maps.LatLng(41.79883, 140.75675),
  new plugin.google.maps.LatLng(41.799240000000005, 140.75875000000002),
  ...
];

map.on(plugin.google.maps.event.CAMERA_CHANGE, onCameraChanged);

cameraMoving = true;
map.animateCamera({
  'target' : positions
}, function() {
  cameraMoving = false;
});

function onCameraChanged() {
  if (cameraMoving) {
    return;
  }
  
  positions.push(new google.maps.plugin.LatLng(random,random));

  cameraMoving = true;
  map.animateCamera({
    'target' : positions
  }, function() {
    cameraMoving = false;
  });
}
```

**Comment by Fayozjon** [comment]
Exactly this!!! Thank you! Saved me a week =)
