### ISSUE TITLE
marker to blink every render when location is update

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#1209]
im using this pluggin with cordova and i have engine that get the last current location with interval  pluggin gps(cordova) , every engine running i set the new marker on the map, but my problem is when i render the map because the marker blink in every update location  my code is

`
function loadmarkernow(coord){
 
      for(var i=0; i < markersop.length;i++){
        var mark=markersop[i];
        mark.remove();
      }
      
      map.addMarker({
                      'position': coord,
                      'icon':{
                        url: 'www/img/chofer.png',
                        size: { width: 16, height: 22 }
                      }
                    }, function(marker) {
                        markersop.push(marker);
                      // Display the infoWindow
                      //marker.showInfoWindow();

                    });

    

}
`
so, i wanna know what im doing bad?

**Comment by wf9a5m75** [comment]
You should not repeat adding/removing for that case.
You should update the position of the markers.
(This is general programming topic...)

```js
addMarkers(markersop, function(markers) {
  
  setInterval(function() {

    getLocations(function() {  // <-- the way you obtain the locations
      markers.forEach(function(marker) {
        marker.setPosition({
          position: {lat: ... , lng: ...} // new position
        });
      });
    });

  }, 5000);

});

function addMarkers(positions, callback) {
  var markers = [];
  function onMarkerAdded(marker) {
    markers.push(marker);
    if (markers.length === positions.length) {
      callback(markers);
    }
  }
  positions.forEach(function(position) {
    map.addMarker({
      position: position
    }, onMarkerAdded);
  });
}
```

**Comment by dsemerida** [comment]
Thanks friend! im goin to test , if will work ill close the issue, while is open
