### ISSUE TITLE
<Android> <v2-beta> Conflict with cordova-plugin-mauron85-background-geolocation

### ISSUE THREAD

**Issue by schobbent** [mapsplugin/cordova-plugin-googlemaps#1211]
Hello @wf9a5m75 , 

I had a conflict with this cordova plugin : https://github.com/mauron85/cordova-plugin-background-geolocation

The problem is the version of the play-service for those frameworks

_com.google.android.gms:play-services-location_ and _com.google.android.gms:play-services-maps_ 

_**mauron85-background-geolocation** plugin.xml_ : 

```
     ...
     <!-- android -->
     <platform name="android">
         .....
        <framework src="android/logtofile.gradle" custom="true" type="gradleReference"/>
        <framework src="com.google.android.gms:play-services-location:+" />
        <framework src="com.android.support:support-v4:+" />
        ....
```

_**cordova-plugin-googlemaps** plugin.xml_ : 

```
    ...
    <!-- android -->
    <platform name="android">
        ...
        <framework src="com.google.android.gms:play-services-maps:9.8.0" />
        <framework src="com.google.android.gms:play-services-location:9.8.0" />
       ...
```

When you use "**cordova build --stacktrace --debug**", you can see that **mauron85** use the v**ersion 10.01** and **cordova-plugin-googlemaps** use the **version 9.80**.

And here is the error : 

```
_project_\platforms\android\src\plugin\google\maps\PluginUtil.java:135: error: 
cannot access AbstractSafeParcelable
 
Builder builder = LatLngBounds.builder();
                                  ^
  class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
```

I think that there is a **difference** beetween **10.01 and 9.80** about **LatLngBounds.builder**, and cordova don't know which version use.

So I found the solution : ask to cordova-plugin-googlemap to use the 10.01

_Line 48 and 49 of **plugin.xml** :_ 
```
        <framework src="com.google.android.gms:play-services-maps:+" />
        <framework src="com.google.android.gms:play-services-location:+" />
```

And, now they both use 10.01, TADAAA "**BUILD SUCCESS**"

**but I don't know if it's bulletproof, what is your process to test the beta code?**

**Comment by wf9a5m75** [comment]
I don't support the compatibility with other plugins.
The app developers need to adjust these conflict by themselves.

The reason of pinning the library version is aim to work this plugin certainly.
More details, read here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1200#issuecomment-264662572

**Comment by schobbent** [comment]
@wf9a5m75 Thank you for your enlightement ! I'll pin the library version as you suggest 👍
