### ISSUE TITLE
blank map when i change machine laptop

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#1213]
im testing the map pluggin when i change from machine to other laptop the map is blank , i have create keystore and configurated the api from google console, but i dont know whats happening

**Comment by wf9a5m75** [comment]
This plugin only run on Android device and iOS device.

This plugin does not run on browser.

**Comment by dsemerida** [comment]
i know man, im talking about when i testing the pluggin on other laptop with diferent profile the keys api not work more

**Comment by wf9a5m75** [comment]
Ah, I see. I think the fingerprint of the environment is different.

Easiest solution is that specify `none` for api key restriction at the Google APIs console.
![screen shot 2016-12-06 at 11 25 48 am](https://cloud.githubusercontent.com/assets/167831/20940203/c6eafa9a-bba6-11e6-8e92-6bd629dde3ac.png)

**Comment by dsemerida** [comment]
ok, ill will try and set my resut to us

**Comment by dsemerida** [comment]
i have proib but i get work, thanks so much man!
