### ISSUE TITLE
my app crash stoped when i use together phonegap-pluggin-push 

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#1216]
im testing google map plugin cordova but i have a issue  when i install the plugin https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md on my project when i set cordova run android my app crash before load i dont know what is cause

**Comment by wf9a5m75** [comment]
Please inspect by yourself at once before asking.
Search the error log on google or stackoverflow.

**Comment by Fayozjon** [comment]
Exactly same issue here. I guess its because of Firebase Cloud Messaging plugin

**Comment by Fayozjon** [comment]
Ping @wf9a5m75  @dsemerida
