### ISSUE TITLE
Windows Phone compatibility

### ISSUE THREAD

**Issue by vvenegasv** [mapsplugin/cordova-plugin-googlemaps#1217]
Hi, great job. It's really a great plugin.

I was wondering if there is a plan to the near future to add windows phone compatibility or a way to add "manual" compatibility.

So far as i know, there is no SDK or API to Windows Phone, so, i think that if i want to add windows support, i will need to put the Javascript API.

So, there is a way to use this plugin for android and ios, but if there is another OS, use the javascript API? Anyone has worked on this? Any idea or experience?

Thanks a lot. 
Have a nice day 

PS: Sorry for my bad english
PS: It's not an issue. Sorry if this post shouldn't be here

**Comment by celron** [comment]
In my app, I actually use the plugin with javascript and have logic to differentiate between the two when necessary.  The majority of the business logic (your logic in this case) is the same.  

Off the top of my head, the major differences are the latLng coordinates (using google.maps.LatLng vs plugin.google.maps.LatLng()), the map object, the way to change position (using the camera with the plugin or using map.fitBounds/map.setCenter with javascript) and the way the markers are handled, but it is not difficult, just tedious.

**Comment by wf9a5m75** [comment]
@vvenegasv I have no plan to develop this plugin for Windows Phone.

**Comment by vvenegasv** [comment]
Ok, thanks for your comments :)
