### ISSUE TITLE
Failed to install 'com.googlemaps.ios':CordovaError: Uh oh!

### ISSUE THREAD

**Issue by PhillipZada** [mapsplugin/cordova-plugin-googlemaps#1219]
Hi,

Getting this issue when attempting to install the plugin. 

Failed to install 'com.googlemaps.ios':CordovaError: Uh oh!
Cannot find resource file "...\plugins\com.googlemaps.ios\Maps\Frameworks\GoogleMaps.framework\Versions\A\Resources\Go
ogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform

tried using the cmd
```
$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
```

**Comment by wf9a5m75** [comment]
What OS do you use? I guess you don't use MacOS X.

You can install from here.
https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk

**Comment by PhillipZada** [comment]
Sorry if this sounds dumb. Im new to cordova and using it as part or ionic2. 

Im using Windows 10. Do I need to add the plugin on a Mac? If so is there a way to add on the "andriod" plugin in browser development purposes?

**Comment by wf9a5m75** [comment]
Develop an app on MacOS X, there is no trouble for installation of `com.googlemaps.ios` plugin.
Typically Windows user.
So I just want to confirm what OS do you use.

Some people develop their app on Windows for iOS.
But I'm not Windows user, please you resolve the issue yourself.

And this plugin does not run on browser.
Only this plugin run in Android app or iOS app.

**Comment by fx69005** [comment]
hello, i have the same problem ,  I develop on windows  and i have this error. But when i try to install https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk
Cordova write same error : 
"...\plugins\com.googlemaps.ios\Maps\Frameworks\GoogleMaps.framework\Versions\A\Resources\Go
ogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform.

Best regards

**Comment by PhillipZada** [comment]
The only way i got it working was to "downgrade" the cordova ios version to 3.9.0 which allows the install to complete but unfortunately it skips the ios install as version 4.0.0 is the min version. 

@wf9a5m75 I tried doing the install on a Mac OSX running sierra and latest version of xcode with no luck, still saying the file is missing.

**Comment by fx69005** [comment]
hi @wf9a5m75,
 Can u have  pull request for install with cordova ios version upper 4.x.x ?

Best regards

**Comment by PhillipZada** [comment]
I managed to get my hands on a mac with xcode installed, copied the project over and it installs correctly.
I did have to delete the **com.googlemaps.ios** folder in the plugins directory though.

@wf9a5m75 can you suggest if there is a way to make it "skip" the ios install when not on a Mac?

Thanks again

**Comment by bigbossmaher** [comment]
the solution is here
https://software.intel.com/en-us/forums/intel-xdk/topic/705862
