### ISSUE TITLE
Onsen UI ver 2 Fix

### ISSUE THREAD

**Issue by xemox** [mapsplugin/cordova-plugin-googlemaps#1220]
If someone using onsenui framework and map is blank but no error in js and logcat. Actually your plugin is working. It just layered with white background.

You can add custom modifier to your page, for example with "transparent" name.
<ons-page modifier="transparent">

and add modifier css class in your css file like below
.page--transparent__background {
    background-color:rgba(0,0,0,0);
}

**Comment by mejiagarcia** [comment]
OMG  thank you.

**Comment by saravanans-arch** [comment]
Similar issue for me! It's working in main page only... but it's **not working after a pushPage**...
Note: I'm using ons sliding, I think it's working in mainMenu only... if i pushed a page then it will be blank

**Comment by joelchucn** [comment]
Is there any solution to the pushPage issue with google maps? I am having the same problem at the moment.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#how-does-this-plugin-work-android-ios
