### ISSUE TITLE
can't install the plugin on intel XDK

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1222]
i get this error messge when i try to install the plugin on intel XDK
![issue cordovapng](https://cloud.githubusercontent.com/assets/15154710/21204931/fd0e6e2c-c259-11e6-95f5-de9352a8cc11.PNG)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/714

**Comment by bigbossmaher** [comment]
i can't work with intel XDK , so i tried to use visuel studio . it is not working also .. in attachement you will find my visuel studio project , i just added the plugin in the config and i have changed the index
cn you please fix it.
![capture11](https://cloud.githubusercontent.com/assets/15154710/21245036/aaef7f2e-c320-11e6-97eb-523b62f1015d.PNG)

this is my index.html
`<!DOCTYPE html>
<html>
    <head>
    
        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">
        
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title>parking2</title>
        <script type="text/javascript">
    var map;
    document.addEventListener("deviceready", function() {
      var div = document.getElementById("map_canvas");

      // Initialize the map view
      map = plugin.google.maps.Map.getMap(div);

      // Wait until the map is ready status.
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
    }, false);

    function onMapReady() {
      var button = document.getElementById("button");
      button.addEventListener("click", onBtnClicked, false);
    }

    function onBtnClicked() {
      map.showDialog();
    }
        </script>
    </head>
    <body>
        <h3>PhoneGap-GoogleMaps-Plugin</h3>
        <div style="width:100%;height:400px" id="map_canvas"></div>
        <button id="button">Full Screen</button>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="scripts/platformOverrides.js"></script>
        <script type="text/javascript" src="scripts/appBundle.js"></script>
    </body>
</html>`


this is a screen shot from config

![capture12](https://cloud.githubusercontent.com/assets/15154710/21245092/f4f98eca-c320-11e6-995f-a3f2736704b2.PNG)

**Comment by wf9a5m75** [comment]
I have never used the intel XDK. Please resolve the issue by yourself.

**Comment by bigbossmaher** [comment]
this is visual studio

**Comment by wf9a5m75** [comment]
I have never used visual studio also.

**Comment by wf9a5m75** [comment]
And you can find past questions.
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=visual+studio&type=Issues&utf8=%E2%9C%93

**Comment by bigbossmaher** [comment]
what is the method that you use to develop hybrid apps ? ionic ?

**Comment by bigbossmaher** [comment]
i got the same error with Cordova command line , i ran this command
cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"



![capture5](https://cloud.githubusercontent.com/assets/15154710/21280562/0519b5c0-c3e7-11e6-9444-884cb3893e9d.PNG)

**Comment by wf9a5m75** [comment]
Installing problem is depends on your environment. Not this plugin issue.
Please resolve it by yourself.

This article might be helpful for your case.
https://taco.visualstudio.com/en-us/docs/tips-and-workarounds-ios-ios-plugin-symlink-fix-readme/

**Comment by bigbossmaher** [comment]
thank you very much
last question
i have succesfelly installed the plugin
when i run the app by Ripple i get unhandled exec call 
and the map not shown
how to solve it

**Comment by wf9a5m75** [comment]
This plugin does not run on Apache Ripple.
Please use your actual device.
