### ISSUE TITLE
OnsenUI2.0 Support -Help?

### ISSUE THREAD

**Issue by Melody521** [mapsplugin/cordova-plugin-googlemaps#1223]
hi here
I know there has been great discussion on how to get this plugin to work on onsenUI, but I have searched and read everything - but I can't find a solution. Everytime I try to init the Maps - I get nothing (I assume that it's hidden behind in some place).

And also I used the test branch of this plugin and I get no errors in the console log when the page is loaded.

Is there a solution for onsenUI2.0 users that we all reference? I know mabey you are so tired or hearing this, but just wanted to get an answer: this is my source and i attach my app's screen-shot.

----------------------index.html-------------------------------------------
    <script src="js/app.js"></script>
    <script src="js/googleMaps.js"></script>
     <script>
        ons.bootstrap();

        /*ons.ready(function () {
            document.addEventListener ('init', function (event) {
                //initMap();
            });
        });*/

        document.addEventListener("init", function(event) {
            if (event.target.id == "map-page") {
                mapDiv = document.getElementById("map_canvas");
                console.log("page init");
            }
        }, false);
    </script>
 <ons-template id="map.html">
    <ons-page id="map-page" ng-controller="mapCtrl" modifier="map">
        <ons-toolbar>
            <div class="center">Map</div>
        </ons-toolbar>
        <div style="width:100%;height:400px" id="map_canvas"></div>
    </ons-page>
</ons-template>
----------------------index.html---------------------------------------------------

----------------------googlemap.js------------------------------------------------

var app = angular.module('googleMaps', []);
app.controller('mapCtrl', ['$scope', function ($scope) {
    var map;
    var mapDiv;

    function initMap() {

        mapDiv = document.getElementById("map_canvas");
        map = plugin.google.maps.Map.getMap(mapDiv);
        map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);

        /*document.addEventListener("deviceready", function () {

         console.log("Map");
         //var div = document.getElementById("map_canvas");

         // Initialize the map view
         map = plugin.google.maps.Map.getMap(mapDiv);

         // Wait until the map is ready status.
         map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);*/
    }

    function onMapReady(map) {
        //map.showDialog(map);
        alert("map");
    }
}]);

![googlemap](https://cloud.githubusercontent.com/assets/24578591/21209456/b67f2524-c2b7-11e6-84e9-e4c3d07cad14.PNG)
------
Thank you in advance

**Comment by xemox** [comment]
Your map actually its working if there is no error. Your alert is popup right?
Add modifier to your page like 
<ons-page id="googlemap-page" **modifier="transparent"**>
</ons-page>

then add following css into your css file
.page--transparent__background {
background-color:rgba(0,0,0,0);
}

also dont forget to add height & width for your css too
#map_canvas {
    width:100%;
    height:400px;
}

**Comment by Melody521** [comment]
hello @xemox 
Thank you for your quick response.
i will try it.

**Comment by Melody521** [comment]
@xemox
it works for me .thank you again
