### ISSUE TITLE
Just updated to 1.4.0: Failed to load Info.plist from bundle 

### ISSUE THREAD

**Issue by davidmesa** [mapsplugin/cordova-plugin-googlemaps#1224]
I was using v1.4.0 beta from the current master. Today I did an update to the stable version of v1.4.0 but now when I'm trying to run the project from xcode I get:

Failed to load Info.plist from bundle at path /Users/.../Frameworks/GoogleMaps.framework 

Anyone have any idea what could be happening?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/How-to-upgrade-the-plugin%3F#ios-method-1

**Comment by davidmesa** [comment]
Thanks!! Didn't realized there was a guide to update.
