### ISSUE TITLE
Map freeze after keyboard open and close in ionic2

### ISSUE THREAD

**Issue by santu-git** [mapsplugin/cordova-plugin-googlemaps#1226]
I am using cordova-plugin-googlemaps along with goggle map autocomplete(Javascrip SDK).
After I click on search box keyboard appear then I close keyboard with out any search, then tap drag  move no event is happing on map. But if I search something and map pan to that location then no issue.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=keyboard&type=Issues&utf8=%E2%9C%93
