### ISSUE TITLE
Map center is not working

### ISSUE THREAD

**Issue by yasiramidtech** [mapsplugin/cordova-plugin-googlemaps#1227]
I'm using this code for the change center of map.

```
 var evtName = plugin.google.maps.event.MAP_CLICK;
            map.on(evtName, function (latLng) {
                var GOOGLE = new plugin.google.maps.LatLng(24.863610837474504, 67.03837305307388);
                map.setCenter(GOOGLE);
            });
```

But i'm getting this error 
```
Uncaught TypeError: map.setCenter is not a function
    at Map.<anonymous> (controllers.js:1268)
    at HTMLDocument.listener (BaseClass.js:55)
    at Map.BaseClass.self.trigger (BaseClass.js:43)
    at Map._onMapEvent (Map.js:861)
    at Map.nativeCallback (googlemaps-cdv-plugin.js:267)
    at Object.fireDocumentEvent (cordova.js:235)
    at <anonymous>:1:9
```

**Comment by wf9a5m75** [comment]
Do you really use cordova Android/iOS?
This plugin does not support browser.

**Comment by yasiramidtech** [comment]
I'm using this on both android/ios platform , but still is not working. I got the above mentioned error when i debug the application.

**Comment by yasiramidtech** [comment]
This is whole code.

$ionicPlatform.ready(function () {
        var div = document.getElementById("map_canvas");
        map = plugin.google.maps.Map.getMap(div);
        var lat, long;
        var onSuccess = function (location) {
            lat = location.latLng.lat;
            long = location.latLng.lng;
            map.setTrafficEnabled(true);
            console.log(lat + " - - " + long);
            map.setMyLocationEnabled(true);
            var msg = ["Current your location:\n",
            "latitude:" + location.latLng.lat,
            "longitude:" + location.latLng.lng,
            "speed:" + location.speed,
            "time:" + location.time,
            "bearing:" + location.bearing].join("\n");

            map.animateCamera({
                'target': location.latLng,
                'tilt': 20,
                'zoom': 16,
                'bearing': 25,
                'duration': 2000 // 10 seconds
            },
            function() {
                $('.centerDiv').show();
                $('.centerDiv').animate({ 'width': '110px', 'border-color': 'gold' }, 1500);
            },
           
            var evtName = plugin.google.maps.event.MAP_CLICK;
            map.on(evtName, function (latLng) {
                var GOOGLE = new plugin.google.maps.LatLng(24.863610837474504, 67.03837305307388);
           	map.setCenter(GOOGLE);
            });
            
        };
        var onError = function (msg) {
            alert("error: " + msg);
        };

        map.getMyLocation(onSuccess, onError);
        
        

    });

**Comment by xemox** [comment]
@yasiramidtech Your code should not run, because its would be syntax error your function should be closed. Try below.

```
        googleMap.animateCamera({
            'target': location.latLng,
            'tilt': 20,
            'zoom': 16,
            'bearing': 25,
            'duration': 2000 // 10 seconds
        },
        function() {
            $('.centerDiv').show();
            $('.centerDiv').animate({ 'width': '110px', 'border-color': 'gold' }, 1500);
        });
       
        var evtName = plugin.google.maps.event.MAP_CLICK;
        map.on(evtName, function (latLng) {
            var GOOGLE = new plugin.google.maps.LatLng(24.863610837474504, 67.03837305307388);
            map.setCenter(GOOGLE);
        });
        
    };
    var onError = function (msg) {
        alert("error: " + msg);
    };

    map.getMyLocation(onSuccess, onError);
```

**Comment by yasiramidtech** [comment]
did you test above code? map.setCenter() working?

**Comment by xemox** [comment]
Any error on console? I've copy paste and fix partial of your code and running it. Any area on map where I click, it will go to "karachi" as expected.

**Comment by yasiramidtech** [comment]
could you share your code ?

**Comment by xemox** [comment]
Here is sample from quick demo, I change the name a little bit.  just call googleSample function and when map showing up click in any area. Goodluck

```
    function googleSample() {
        var mapCanvas = document.getElementById("googlemap-canvas");
        googleMap = plugin.google.maps.Map.getMap(mapCanvas);
        googleMap.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
    }

    function onMapReady () {
        googleMap.setMyLocationEnabled(false);
        googleMap.setCompassEnabled(false);
        googleMap.animateCamera({
            target: { lat: 37.422359, lng: -122.084344 },
            zoom: 17,
            duration: 5000
        }, function () {
            googleMap.addMarker({
                position: { lat: 37.422359, lng: -122.084344 },
                title: "Welecome to \n" +
                       "Cordova GoogleMaps plugin for iOS and Android",
                snippet: "This plugin is awesome!",
                animation: plugin.google.maps.Animation.BOUNCE
            }, function (marker) {
                marker.showInfoWindow();
                marker.on(plugin.google.maps.event.INFO_CLICK, function () {
                    console.log('Hello World');

                });
            });

            var evtName = plugin.google.maps.event.MAP_CLICK;
            googleMap.on(evtName, function (latLng) {
                var GOOGLE = new plugin.google.maps.LatLng(24.863610837474504, 67.03837305307388);
                googleMap.setCenter(GOOGLE);
            });

        });

    };
```

**Comment by yasiramidtech** [comment]
above code work on version 2.0.0-beta ?
 becuase i'm still getting same error on above code

**Comment by xemox** [comment]
The above code is for v1.
There is no setCenter method in v2. The method has renamed to setCameraTarget in v2.

read this before using v2. You previously wrote for v1.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Migrate-from-v1-to-v2

**Comment by yasiramidtech** [comment]
@xemox  map.setCameraTarget() working.
Thank you

**Comment by ArjunNagraj** [comment]
I have copy pasted the below code thought the callback of animateCamera is invoked i do not see any thing happening including zoom level. 
Any experts who could help me debug this?

 map.animateCamera({
    target: {lat: 37.422359, lng: -122.084344},
    zoom: 17,
    tilt: 60,
    bearing: 140,
    duration: 5000
  }, function() {

    // Add a maker
    map.addMarker({
      position: {lat: 37.422359, lng: -122.084344},
      title: "Welecome to \n" +
             "Cordova GoogleMaps plugin for iOS and Android",
      snippet: "This plugin is awesome!",
      animation: plugin.google.maps.Animation.BOUNCE
    }, function(marker) {

      // Show the info window
      marker.showInfoWindow();

      // Catch the click event
      marker.on(plugin.google.maps.event.INFO_CLICK, function() {

        // To do something...
        alert("Hello world!");

      });
    });
  });
