### ISSUE TITLE
Child buttons from floating action button not working

### ISSUE THREAD

**Issue by cande1gut** [mapsplugin/cordova-plugin-googlemaps#1229]
I have a problem with my buttons on a floating action button menu from framework7, I checked the position of the menu and there should not be any problem since everything is set as absolute, so I can see everything on top of the map but the problem is when I try to click a button, the only button I can click is the principal (The bigger one) the one that opens another div, but I can't click any of the links inside that other div (The smaller ones), I tried to set setDebuggable(true), but I can't see the red or green colors, and at the same time I put the refreshLayout(), but seems like this is not working as well, since I am resizing my map canvas.

This behavior seems to look like in this issue: #1091

![screenshot_2016-12-17-20-50-24](https://cloud.githubusercontent.com/assets/5407915/21291158/daa2f3ba-c49a-11e6-902d-fb2019c15726.png)

**Comment by xemox** [comment]
Its like you put your div button outside the map canvas.

Put that div button inside of map canvas

**Comment by cande1gut** [comment]
I actually put all inside the map div:

`<div id="map_canvas">`
 `<div class="speed-dial">`
                  `<a href="#" class="floating-button">`
                    `<i class="icon icon-plus"></i>`
                    `<i class="icon icon-close"></i>`
                 ` </a>`
                  `<div class="speed-dial-buttons">`
                   ` <a href="#">`
                     ` <i class="icon icon-close"></i>`
                   ` </a>`
                   ` <a href="#">`
                     ` <i class="icon icon-close"></i>`
                   ` </a>`
                   ` <a href="#">`
                      `<i class="icon icon-close"></i>`
                    `</a>`
                 ` </div>`
                `</div>`
           `   </div>`

**Comment by xemox** [comment]
Oh I see, Your "speed-dial button" group is inside "speed-dial" content. 
Well, its currently only support one level down div from map_canvas. That is why your big button is working but its child not working.

**Comment by cande1gut** [comment]
Hhhmm interesting, that's what I was thinking, well thank you.
