### ISSUE TITLE
calculate distance

### ISSUE THREAD

**Issue by Myhaylyak** [mapsplugin/cordova-plugin-googlemaps#1230]
How can I calculate the distance between two points using this plugin?

**Comment by xemox** [comment]
Through this plugin? I dont think so. 

But you can get its Lat Lng and convert into distance with formula (google it) for straight line only.

Alternatively you can also use [distance matrix](https://developers.google.com/maps/documentation/distance-matrix/intro) to get distance results based on street length.

**Comment by Myhaylyak** [comment]
@xemox, I am developing meteor.js application. I tried to use distance matrix, but I came across an CORS error, I could not decide, so looking for other ways.

**Comment by xemox** [comment]
You can add access origin in config and install whitelist plugin.

**Comment by Myhaylyak** [comment]
@xemox, Access origin in config.xml? I tried, but it did not help. But have not tried this plugin, that you advised me.

**Comment by caleb87** [comment]
```
function spatial_distance(lat1, lon1, lat2, lon2, u) {
    //console.log('spatial distance'+lat1+'**'+lon2+'**'+lat2+'**'+lon2);
    var radlat1 = Math.PI * lat1 / 180;
    var radlat2 = Math.PI * lat2 / 180;
    var radlon1 = Math.PI * lon1 / 180;
    var radlon2 = Math.PI * lon2 / 180;
    var theta = lon1 - lon2;
    var radtheta = Math.PI * theta / 180;
    var dist = Math.sin(radlat1) * Math.sin(radlat2) + Math.cos(radlat1) * Math.cos(radlat2) * Math.cos(radtheta);
    dist = Math.acos(dist);
    dist = dist * 180 / Math.PI;
    dist = dist * 60 * 1.1515;
    if (u == "K") dist = dist * 1.609344;
    if (u == "N") dist = dist * 0.8684;
    //console.log(dist);
    if (isNaN(dist)) dist = 0;
    return dist
}
```

**Comment by wf9a5m75** [comment]
The plugin v2 supports the spherical features by default.
https://github.com/mapsplugin/v2.0-demo/tree/master/www/spherical
