### ISSUE TITLE
initialise map

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1232]
is that code is correct 

```
const GORYOKAKU_JAPAN = new plugin.google.maps.LatLng(41.796875,140.757007);

var map = plugin.google.maps.Map.getMap(div,{
  'backgroundColor': 'white',
  'mapType': plugin.google.maps.MapTypeId.HYBRID,
  'controls': {
    'compass': true,
    'myLocationButton': true,
    'indoorPicker': true,
    'zoom': true
  },
  'gestures': {
    'scroll': true,
    'tilt': true,
    'rotate': true,
    'zoom': true
  },
  'camera': {
    'latLng': GORYOKAKU_JAPAN,
    'tilt': 30,
    'zoom': 15,
    'bearing': 50
  }
});
```

**Comment by wf9a5m75** [comment]
Yes, correct code.
Make sure your `div` is real DOM element.

**Comment by bigbossmaher** [comment]
could you please tell me how to change default marker icon in this code

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#simple-icon

**Comment by bigbossmaher** [comment]
why this is not working
addMarkers(ParkingData, function(markers) {
  markers[markers.length - 1].hideInfoWindow();
  markers[markers.length - 1].marker.setIcon({
      'url': 'icons/parking.png'
    });
});

**Comment by wf9a5m75** [comment]
Please do your best before asking. Read the code, think the code, and find what you need.

```
function addMarkers(data, callback) {
  var markers = [];
  function onMarkerAdded(marker) {
    markers.push(marker);
    if (markers.length === data.length) {
      callback(markers);
    }
  }
  data.forEach(function(markerOptions) {
    map.addMarker(markerOptions, onMarkerAdded);
  });
}
```

**Comment by bigbossmaher** [comment]
i already tries this 
`addMarkers(ParkingData, function(markers) {
  markers[markers.length - 1].hideInfoWindow();
  markers[markers.length - 1].setIcon({
      'url': 'icons/parking.png'
    });
});`

and this 
`  ParkingData.forEach(function(markerOptions) {
    map.addMarker({
  'icon': {
      'url': 'icons/parking.png'
   }
}, onMarkerAdded);
  });`


not working :(

**Comment by wf9a5m75** [comment]
Why don't you like this?

```js
var ParkingData = [
    {
        position: {lat: ..., lng : ...},
        icon: 'icons/parking.png',
        title: "...."
    },
    ....
];

addMarkers(ParkingData, function(markers) {
   
});
```

**Comment by bigbossmaher** [comment]
Awesommmmmmmmmmmmmmmmmme

**Comment by bigbossmaher** [comment]
the icons  are not changing even i do like what you said

![sans titre](https://cloud.githubusercontent.com/assets/15154710/21368475/0774de8e-c703-11e6-8323-c945a66ffb7d.png)

**Comment by wf9a5m75** [comment]
Ah,

```
'icon': {
    'url': 'images/google_tokyo_icon.png'
}
```

**Comment by wf9a5m75** [comment]
Otherwise, your image path is wrong.
You have to put the image on `www/icons/parking.png`, if your app displays `www/index.html`

**Comment by bigbossmaher** [comment]
it works by adding www
thanks
