### ISSUE TITLE
create multiple markers

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1234]
var ParkingData = [['sr', 34.735278, 10.763944, 4], ['ss', 34.735000, 10.764833, 5], ['Beach', -34.028249, 151.157507, 3], ['j', 34.736972, 10.763972, 2],
   ['G', 34.734457, 10.766483, 1]];

i want the markers of this this array
i want that the info windows is shown only when i clic on the marker . 
in the documentation it not clear

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#create-multiple-markers
