### ISSUE TITLE
Center Change 

### ISSUE THREAD

**Issue by yasiramidtech** [mapsplugin/cordova-plugin-googlemaps#1237]
I'm using this code to change center , but i want to control center change speed its changing center to fast how to control it?
```
var GOOGLE = new plugin.google.maps.LatLng(new_lat, new_lon);
map.setCameraTarget(GOOGLE);
```

**Comment by bigbossmaher** [comment]
`  map.animateCamera({
    target: {lat: 37.422359, lng: -122.084344},
    zoom: 17,
    tilt: 60,
    bearing: 140,
    duration: 5000
  }, function() {

    // Add a maker
    map.addMarker({
      position: {lat: 37.422359, lng: -122.084344},
      title: "Welecome to \n" +
             "Cordova GoogleMaps plugin for iOS and Android",
      snippet: "This plugin is awesome!",
      animation: plugin.google.maps.Animation.BOUNCE
    }, function(marker) {

      // Show the info window
      marker.showInfoWindow();

      // Catch the click event
      marker.on(plugin.google.maps.event.INFO_CLICK, function() {

        // To do something...
        alert("Hello world!");

      });
    });
  });`

change the duration

**Comment by yasiramidtech** [comment]
change duration working only when map loading , duration is not effecting center change speed

**Comment by wf9a5m75** [comment]
This plugin does not provide `setCameraTarget` method. Do you really use this plugin?

**Comment by wf9a5m75** [comment]
@yasiramidtech If you use the map plugin v2, you should describe like "I'm using the plugin v2 beta".
This helps other people to understand your problem.

`map.setCameraTarget` does not provide to specify camera animation `duration`.
But you can use `map.animateCamera()`

```js
map.animateCamera({
  position: {lat: new_lat, lng: new_lon}
});
```

**Comment by yasiramidtech** [comment]
@wf9a5m75 Sorry next time i will describe the version of plugin.Now i'm getting error
position is not defined

**Comment by yasiramidtech** [comment]
It works for me.
map.animateCamera({
                    'target': GOOGLE,
                    'duration': 2000
                });
