### ISSUE TITLE
mousemove event?

### ISSUE THREAD

**Issue by caereservices** [mapsplugin/cordova-plugin-googlemaps#1238]
Hi, I need to intercept mousedown, mousemove and mouseup event on the map ... how can I do for do this?? Thanks (I use cordova and made app for Android and iOS)

**Comment by wf9a5m75** [comment]
The plugin version 1 supports only these events:
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#version-1x-events

The plugin version 2 supports these events:
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#version-2x-events
