### ISSUE TITLE
map not shown on height 100%

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1239]
the map can not be shown 

`<div style="width:100%;height:100%" id="map_canvas"></div>`

**Comment by yasiramidtech** [comment]
change height:100% to 100vh

**Comment by DreamYahia** [comment]
maker sure that the content not scrolled and try to add display block
do you use ionic ? if yes add scroll="false" to your ion-content

**Comment by bigbossmaher** [comment]
i'm using framework 7
the 100vh has solved my issue
thank you
