### ISSUE TITLE
Smoothly marker movement

### ISSUE THREAD

**Issue by yasiramidtech** [mapsplugin/cordova-plugin-googlemaps#1240]
Is there any way to move marker smoothly one Latlong to another  Latlong ?

**Comment by wf9a5m75** [comment]
no

**Comment by yasiramidtech** [comment]
Ok Thanks

**Comment by yasiramidtech** [comment]
Can i control map.setCenter(LatLng) speed?

**Comment by ibadrehman90** [comment]
Can we expect such functionality in future? As this is the only thing which is missing in your plugin; rest is as great as native.

**Comment by Anopetia** [comment]
Will be awesome. +1
