### ISSUE TITLE
can't modify marker options

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1241]
i have an array that contains parking data ( title / longitude/ latitude)
var ParkingData = [
              {'title': 'mark1', 'position': new plugin.google.maps.LatLng(xx, xx)},
              {'title': 'mark2', 'position': new plugin.google.maps.LatLng(xx, xx)}
            ];
i want to place all the markers 
i know that i should use this 
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#create-multiple-markers

but i want to customize the default marker like : icon / animation / styles

how can i do it

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#simple-icon

**Comment by bigbossmaher** [comment]
yes i know , but where i should the modifications in this code
where i should put the marker options 

`addMarkers(data, function(markers) {
  markers[markers.length - 1].showInfoWindow();
});

function addMarkers(data, callback) {
  var markers = [];
  function onMarkerAdded(marker) {
    markers.push(marker);
    if (markers.length === data.length) {
      callback(markers);
    }
  }
  data.forEach(function(markerOptions) {
    map.addMarker(markerOptions, onMarkerAdded);
  });
}`

**Comment by wf9a5m75** [comment]
Please study Javascript.

`Array.forEach()`
https://msdn.microsoft.com/en-us/library/ff679980(v=vs.94).aspx

**Comment by bigbossmaher** [comment]
please just make a little effort and just tell me where i should put the mark options

**Comment by wf9a5m75** [comment]
```
data.forEach(function(markerOptions) {
    map.addMarker(markerOptions, onMarkerAdded);
  });
```

The above code is nearly the same meaning as the below

```js
for (var i = 0; i < data.length; i++) {
  var markerOptions = data[i];
  map.addMarker(markerOptions, onMarkerAdded);
}
```

**Comment by bigbossmaher** [comment]
i oppened this like an issue because i tried this
`var ParkingData = [
  {'title': 'Beb Diwan, Borj Ennar', 'position': new plugin.google.maps.LatLng(34.735278, 10.763944),'icon': 'www/icons/parking.png'},
  {'title': 'devant le cour d appel', 'position': new plugin.google.maps.LatLng(34.735000, 10.764833),'icon': 'www/icons/parking.png'},
];

addMarkers(ParkingData, function(markers) {
  markers[markers.length - 1].hideInfoWindow();
});

function addMarkers(ParkingData, callback) {
  var markers = [];
  function onMarkerAdded(marker) {
    markers.push(marker);
    if (markers.length === ParkingData.length) {
      callback(markers);
    }
  }
  ParkingData.forEach(function(markerOptions) {
    map.addMarker({
 'styles' : {
    'text-align': 'center',
    'font-style': 'italic',
    'font-weight': 'bold',
    'color': 'red'
  }
}, onMarkerAdded);
  });
}`




but all markers ae dissapered

**Comment by wf9a5m75** [comment]
Because you don't pass the `position` and the `title` properties to `map.addMarker()` from the `markerOptions` variable.

```js
map.addMarker({
 'styles' : {
    'text-align': 'center',
    'font-style': 'italic',
    'font-weight': 'bold',
    'color': 'red'
  }
}
```

**Comment by bigbossmaher** [comment]
i think you have miss understood me

i have markers in ParkingData variable .
when they are placed on map i want to style them
is there any method other then placing styles in ParkingData variable

**Comment by wf9a5m75** [comment]
You don't understand the code at all.

```
ParkingData.forEach(function(markerOptions) {
   // The variable markerOptions = {'title': 'Beb Diwan, Borj Ennar', 'position': new plugin.google.maps.LatLng(34.735278, 10.763944),'icon': 'www/icons/parking.png'}
 
  // YOU HAVE TO the markerOptions to pass the map.addMarker() method like this.
  markerOptions.styles = {
    'text-align': 'center',
    'font-style': 'italic',
    'font-weight': 'bold',
    'color': 'red'
  };
    map.addMarker(markerOptions, onMarkerAdded);

```

If you still can't understand what is your mistake, I don't recommend you use this plugin.
Please use the Google Maps JavaScript v3. There are tons of example on the Internet.

**Comment by bigbossmaher** [comment]
i start using the Google Maps JavaScript v3 . but i can't make the rotation gesture on  Google Maps JavaScript v3

**Comment by wf9a5m75** [comment]
Google Maps Javascript v3 is not in this plugin scope.
Please ask at StackOverflow.

**Comment by bigbossmaher** [comment]
what do you mean by this
Google Maps Javascript v3 is not in this plugin scope.

**Comment by wf9a5m75** [comment]
This plugin does not use Google Maps JavaScript API v3 at all.
This plugin use only Android Google Maps API v2 anf Google Maps SDK for iOS.
So questions for Google Maps JavaScript v3 is not suite for this repository.
Please ask at StackOverflow.

I think it's too difficult to use this plugin.
I gave lots of hit (and even I gave answer), but you didn't understand.

**Comment by bigbossmaher** [comment]
sorry , i'm dreamer , maybe in one time you was like me . a newbie
we should help each other.

**Comment by bigbossmaher** [comment]
sorry a question : is there any way to change the blue point of myLocationButton

**Comment by wf9a5m75** [comment]
No
