### ISSUE TITLE
WF: === Starting WebFilter logging for process - only happened on iOS (working on Android)

### ISSUE THREAD

**Issue by calvingferrando18** [mapsplugin/cordova-plugin-googlemaps#1242]
Tested on iOS version: 10.2 (14C92)

Ionic Framework: 2.0.0-rc.2
Ionic Native: 2.2.3
Ionic App Scripts: 0.0.43

I can't render my map because of this(log below). Can someone tell me how to fix it?

WF: === Starting WebFilter logging for process Rink Rater
2016-12-23 15:41:12.395338 Rink Rater[553:81373] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2016-12-23 15:41:12.396871 Rink Rater[553:81373] WF: _WebFilterIsActive returning: NO

**Comment by masashiGMS** [comment]
The log is not related with map at all.

**Comment by mrpradipkumar46** [comment]
if anyone got the solution please help me out.. I am getting same issue

**Comment by Hansachauhan** [comment]
1 am getting same issue . please help me out

**Comment by aaka3207** [comment]
has anyone figured this out yet??

**Comment by wf9a5m75** [comment]
It seems this logs are came from Admob. At least not this plugin.
https://stackoverflow.com/questions/42195761/how-to-fix-xcode-bug-web-filter-is-active
