### ISSUE TITLE
is it possible to set :  getUiSettings().setMapToolbarEnabled(true);

### ISSUE THREAD

**Issue by yogeshwar607** [mapsplugin/cordova-plugin-googlemaps#1244]
I want GET DIRECTION button on my InfoWindow().
On clicking GET DIRECTION  , i want to open maps app to navigate. Is it possible using this plugin ?

**Comment by wf9a5m75** [comment]
In the plugin v2, you can.
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/setOptions.html#L51

**Comment by yogeshwar607** [comment]
If possible , can you please tell me how to use in ionic2 ?
After installing plugin , will i need to import from 'ionic-native' or from some where else ?

**Comment by yogeshwar607** [comment]
Thanks,
works like a charm on ionic2 RC.4
If you require any help regarding ionic2 integration, i am always ready to help.
