### ISSUE TITLE
Geocode not working

### ISSUE THREAD

**Issue by DreamYahia** [mapsplugin/cordova-plugin-googlemaps#1246]
hello

the plugin stop to get geocode from today i do not know why?
it was working yesterday no new on code
plugin.google.maps.Geocoder.geocode
the return array is empty
any one have the same issue ?

**Comment by wf9a5m75** [comment]
It sounds like your app is blocked by Google (android) or Apple (iOS) for some reason.

**Comment by bigbossmaher** [comment]
just i have a question , is it possible to get suggestion when typing with geocoder ?

**Comment by wf9a5m75** [comment]
This plugin does not support it yet.
