### ISSUE TITLE
Ionic-native Google Maps - Multiple markers detect infowindow click

### ISSUE THREAD

**Issue by TelmoFerreira** [mapsplugin/cordova-plugin-googlemaps#1248]
hi,
i am using the ionic-native Google Maps. I'm trying to detect click on the title canvas, does anyone know how to do this ?

thanks
![sem nome](https://cloud.githubusercontent.com/assets/3159113/21521695/43e4b160-ccf7-11e6-9cf5-a74ac57a6014.png)

`	loadMap(){
		

		var latitude 	= Global.userCoords['latitude'];
		var longitude 	= Global.userCoords['longitude'];
	
		
		
		let map = new GoogleMap('map');
		var markers = [];
		map.one(GoogleMapsEvent.MAP_READY).then(() => {
			let myPosition = new GoogleMapsLatLng(latitude, longitude);
			map.moveCamera({ target: myPosition, zoom: 16 }); 
			this.storage.get('list').then((list) => {
				if( list != undefined && list.length > 1 ){
					//let objecto =  JSON.parse(list); 
					var x;
					var obj = JSON.parse(list); 
					var canvas = [];
					for (x in obj) {
						var pd = obj[x]['ponderador'];
						var pm = obj[x]['preco_medio'];
						
						
						canvas[x] = document.createElement('canvas');
						canvas[x].width = 180;
						canvas[x].height = 50;
						var context = canvas[x].getContext('2d');

						var img = new Image();
						img.src = obj[x]['imagem_defeito'];
						context.drawImage(img, 0, 0,50,50); 
						context.font = 'bolder 10pt arial';
						context.fillStyle = 'black';
						context.fillText( obj[x]['nome'] , 60, 15);
						
						context.font = '8pt arial';
						context.fillStyle = 'black';
						context.fillText( obj[x]['morada']+' '+obj[x]['concelho'] , 60, 30);

						context.font = '8pt arial';
						context.fillStyle = 'black';
						context.fillText( obj[x]['tipos_cozinha'] , 60, 45);

						markers[x] = map.addMarker({
							position: new GoogleMapsLatLng(obj[x]['latitude'], obj[x]['longitude']),  
							title: canvas[x].toDataURL(),
							icon: "http://somelink",
						});
						
						
						canvas[x].addEventListener('click', function() {
							alert('teste');
						}, false);
						 
					}
					obj = undefined;
				} 
				list = undefined;
			}).catch((e) => {
				console.log(e);
			});
		});

    }`

**Comment by wf9a5m75** [comment]
I don't know about the ionic-native GoogleMaps (someone created, not me),
but the default feature should work like this

```js
map.addMarker({
  position: new GoogleMapsLatLng(obj[x]['latitude'], obj[x]['longitude']),  
  title: canvas[x].toDataURL(),
  icon: "http://somelink",
}, function(marker) {
  
  marker.on(plugin.google.maps.event.INFO_CLICK, function() {
    //marker is clicked.
  });
});
```

**Comment by TelmoFerreira** [comment]
Thank you for your help. I've tried it this way but I always get the following error:

Supplied parameters do not match any signature of call target.

**Comment by wf9a5m75** [comment]
This plugin does not fire such as error.
