### ISSUE TITLE
map.setVisible(false) set map background color

### ISSUE THREAD

**Issue by grundmanise** [mapsplugin/cordova-plugin-googlemaps#1250]
Hi,
Thanks for such a great plugin!

When I hide a map (using map.setVisible(false) method) the map hides but a grey background shows instead, how can I change that color?

**Comment by wf9a5m75** [comment]
May be
```js
var map = plugin.google.maps.Map.getMap(div, {
   backgroundColor: "red"
});
```

**Comment by grundmanise** [comment]
The background color of the map is semi transparent black or grey... setting `backgroundColor` does not change the background color of the map.

**Comment by wf9a5m75** [comment]
Or `map.setDiv(null)` instead of `map.setVisible(false)`

**Comment by grundmanise** [comment]
thanks, that works. Only I think it is less performant that `setVisible`...

**Comment by grundmanise** [comment]
_GoogleMapsViewController.m_
```
- (void)viewDidLoad
{
    [super viewDidLoad];
    self.view.backgroundColor = [[NSArray arrayWithObjects:[NSNumber numberWithInt:128],
                                                            [NSNumber numberWithInt:128],
                                                            [NSNumber numberWithInt:128],
                                                            [NSNumber numberWithInt:128], nil] parsePluginColor];
```

Problem was here. After changing all `numberWithInt:128` to `numberWithInt:0` - map has a white bg.

**Comment by wf9a5m75** [comment]
No more maintained v1.
