### ISSUE TITLE
Disable Point of interest

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [mapsplugin/cordova-plugin-googlemaps#1251]
Greetings, 

I dont know if this is where I get to submit feature request but I did not find any other ways to do so, This is the situation: https://developers.google.com/maps/documentation/android-api/hiding-features I am trying to  remove the Original Google Points Of interest on the map but no luck following these giving instructions: https://developers.google.com/maps/documentation/android-api/hiding-features I get  C:\apps\kvappcust\platforms\android\src\plugin\google\maps\PluginMap.java:247: error: package R does not exist

                            this, R.raw.style_json

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1180#issuecomment-261125046

**Comment by THEDOWNCOUNTRY** [comment]
Thank you much that solved my problem.
