### ISSUE TITLE
Performance seems to be slower in Android version

### ISSUE THREAD

**Issue by Hurinj** [mapsplugin/cordova-plugin-googlemaps#1252]
Hello,

I develop my app in both version, iOS and Android. On my iPhone, the map is really reactive, no lag ... but on Android it is not really smooth. First, I though it was because I have a cheap Android but I tried the native Google Map App and it seems to be faster and has less lag.

How can I improve the performance of the map on Android ?

Thank you :)

**Comment by wf9a5m75** [comment]
Try the v2-beta
https://github.com/mapsplugin/cordova-plugin-googlemaps#version-20-beta

Or create your app in native language (Java for Android)
