### ISSUE TITLE
Is the v2 version working with angular ?

### ISSUE THREAD

**Issue by Hurinj** [mapsplugin/cordova-plugin-googlemaps#1253]
I just tried the v2 version and I have a white screen, I checked the function which are differents but I don't use them.

I have no error of google in xcode just that : 

`HelloCordova[9250:2713100] THREAD WARNING: ['CordovaGoogleMaps'] took '11.795166' ms. Plugin should use a background thread.`

and when I inspect with safari no error of what google maps is doing wrong

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map

**Comment by wf9a5m75** [comment]
Please try the plugin with a clean project **BEFORE** using with your project.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Mac

**Comment by Hurinj** [comment]
Ok none of the trouble shooting is involved. I reach to have the map one time, maybe it 's a problem of timer ?
Can I inspect an other way to find the error ?

**Comment by Hurinj** [comment]
So It does work if I add the **plugin cross-walk** but doesn't without it.

Moreover, when I have cross-walk and the version 2 of google maps I have an issue with map.fromPointToLatLng : 
point[0] and point[1] are undefined.

```
map.fromPointToLatLng([a, b], function (point) {
                                console.log('mousedown lat' + point[0] + ' lng:' + point[1]);
                                sendEmojiListe(point[0], point[1], c);
                            });
```

**Comment by wf9a5m75** [comment]
The plugin v2 does not work with cross work at this time.
