### ISSUE TITLE
statusbar tap event not detected when using googlemaps plugin V1 & V2

### ISSUE THREAD

**Issue by dyew** [mapsplugin/cordova-plugin-googlemaps#1258]
How to detect 'statusTap' event for statusbar plugin in iOS when using googlemaps plugin? 

I tried with both version 1 and 2 of googlemaps plugin but the 'statusTap' event isn't triggered for both. This problem starts from app startup regardless if a map is initialized as long as the googlemaps plugin is installed.

**Comment by wf9a5m75** [comment]
Please share your project (or make an example project) using github or bitbucket.

**Comment by Hirbod** [comment]
I can confirm this. This plugin will reorganize plugin views to prevent some bugs, and prob. hide or make the statusbar non-responsive to taps.

**Comment by dyew** [comment]
Just create a simple ionic cordova iOS build with a scrollable page and cordova-plugin-statusbar. Tapping the status bar would automatically scroll the page to top or you can listen to statusbar tap events by including:

`window.addEventListener('statusTap', function() {  alert("status bar is tapped")  });`

However, once you add cordova-plugin-googlemaps, be it V1 or V2, the status bar tap event stops. This happens without the need to create a map. I've tried StatusBar.hide(), then StatusBar.show() after some timeOut but it doesnt help. The statusbar tap event is lost once cordova-plugin-googlemaps is installed.

Is this bug fixable?

**Comment by Hirbod** [comment]
Please read my last answer. We are aware of this problem. This plugin will reorganize all plugin view hierarchies (to make it compatible with InAppBrowser and the StatusBar) but does take care of the invisible StatusBar view, which keeps track of the StatusTap.

Prob. fixable, but @wf9a5m75 has to take care.

https://github.com/apache/cordova-plugin-statusbar/blob/master/src/ios/CDVStatusBar.m#L140-L148

Prob. getting lost here:
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/GoogleMaps.m#L44-L53

**Comment by dyew** [comment]
hi there, are there any updates on this issue?

**Comment by wf9a5m75** [comment]
@dyew 
Sorry for late.
I fixed some bugs in last two weeks, including touch problem.
If you still use this plugin, please reinstall the latest code, and try again.

**Comment by wf9a5m75** [comment]
If you have any question about this one, please make another issue. Thanks.
