### ISSUE TITLE
Version 2 -- map.fromPointToLatLng undefined and marker are not added after getMyLocation

### ISSUE THREAD

**Issue by Hurinj** [mapsplugin/cordova-plugin-googlemaps#1260]
On iOS, version 2 of google maps I have an issue with map.fromPointToLatLng :
point[0] and point[1] are undefined.

map.fromPointToLatLng([a, b], function (point) {
                                console.log('mousedown lat' + point[0] + ' lng:' + point[1]);
                                sendEmojiListe(point[0], point[1], c);
                            });

Moreover, after getting my coordinate of my location I can't put a marker anymore (the code worked in the last version)

                function tauper() {
                    if (!$scope.isTauper) {
                        $scope.isTauper = true;
                        map.getMyLocation(function (result) {
                            $scope.position = result.latLng;
                            map.animateCamera({
                                'target': result.latLng,
                                'tilt': 30,
                                'zoom': 17,
                                'bearing': 0,
                                'duration': 2000
                            });

                            map.addMarker({
                                'position': result.latLng,
                                'icon': {
                                    'url': 'www/img/taupe-0.png',
                                    'size': {
                                        width: 51,
                                        height: 64
                                    }
                                },
                                animation: plugin.google.maps.Animation.BOUNCE,
                                zIndex: 100
                            }, function (marker) {
                                $scope.markerTauper = marker;
                            });
                        }, false);
                    }
                }

```
```

**Comment by wf9a5m75** [comment]
See here:
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/fromPointToLatLng.html#L41-L50

**Comment by Hurinj** [comment]
perfect ! and do you know why I can't put a marker when I use the function getMyLocation ?

**Comment by wf9a5m75** [comment]
Maybe this code is better.

```
map.getMyLocation(function (result) {

  $scope.position = result.latLng;
  
  map.addMarker({
      'position': result.latLng,
      'icon': {
          'url': './img/taupe-0.png',
          'size': {
              width: 51,
              height: 64
          }
      },
      animation: plugin.google.maps.Animation.BOUNCE,
      zIndex: 100
  }, function (marker) {
      $scope.markerTauper = marker;
  });
  
  map.animateCamera({
      'target': result.latLng,
      'tilt': 30,
      'zoom': 17,
      'bearing': 0,
      'duration': 2000
  });

}, false);
```

For the plugin v2, you don't need to `www/` for icon path.

-------

You can donate some amount from here
https://github.com/mapsplugin/v2.0-demo#buy-me-a-beer
