### ISSUE TITLE
Some bug with templates cache or something [see screenshot inside]

### ISSUE THREAD

**Issue by Fayozjon** [mapsplugin/cordova-plugin-googlemaps#1261]
Hello everyone! 
Happy new year!
I need some help. After initialization of application first run map opens fine, but when i run intro screen and returning back i see this screen
![photo_2017-01-13_22-47-33](https://cloud.githubusercontent.com/assets/9584679/21939658/9f20faf0-d9e2-11e6-917a-6f63fafe0c16.jpg)
Please help to solve problem. 
@wf9a5m75 

Thank you!

**Comment by wf9a5m75** [comment]
Could you explain more details what the problem is?
Taking a video, providing apk file, share your project files on github or bitbucket are appreciated.

**Comment by wf9a5m75** [comment]
At least, the plugin does not manage your template at all.
I think it's your bug.

**Comment by Fayozjon** [comment]
Link for video of issue:
https://myapteka.uz/uploads/issue.mp4  
For making same issue please 1 - Launch app, if it asks first run enter phone number and name ENTER ANY RANDOM name and phone (example +998996666655) its ok.
Than go to last INFO sign of side-menu item. After hit right button it launches SLIDES after go to side-menu and hit MAP (second item).
and apk available by this link 
https://myapteka.uz/uploads/android-debug.apk
Thank you again for help and for your time. I really appreciate it

**Comment by Fayozjon** [comment]
`<ion-view title="{{(searchModel)?searchModel:'Карта аптек'}}" cache-view="false">  
	<ion-nav-buttons side="right">
		<ion-spinner icon="lines" ng-show="is_loading_now" class="myspinner"></ion-spinner> 
    </ion-nav-buttons> 
	<ion-content data-tap-disabled="true" class="map-container bg-lightgrey has-header" scroll="false">  	

   
		<map on-create="mapCreated(map)" coords="currentLocation"> 
				<div class="poup_help" ng-show="!first_search && $root.map" ng-click="zoomOut();first_search = 1;">
					Нажмите чтобы увидеть больше результатов
				</div> 
				<a class="btn-floating btn-large c0 zoom_out_btn" ng-show="$root.map" ng-class="{'markme': !first_search}" ng-click="zoomOut();first_search = 1;"><i class="icons ion-minus"></i></a>
			
				<a class="btn-floating btn-large c0 zoom_in_btn" ng-show="$root.map" ng-click="zoomIn()"><i class="icons ion-plus"></i></a>
			
				<a class="btn-floating btn-large c0 findme"  ng-show="$root.map" ng-click="findMe()"><i class="icons ion-navigate"></i></a> 
		</map> 	
	</ion-content>  
</ion-view>`

My map page

**Comment by Fayozjon** [comment]
@wf9a5m75 emplemented issue ?

**Comment by Fayozjon** [comment]
Ive found example solution. For now im just disabled TRANSITIONS on some pages.
