### ISSUE TITLE
remove a specific marker

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1266]
i have a lot of markers on map , how can i delete only one ,
is there ID for every marker ? how can i do it ?

**Comment by wf9a5m75** [comment]
marker.remove()

**Comment by bigbossmaher** [comment]
if i have 50 markers and i want to delete only one marker

**Comment by AsimNet** [comment]
you have to store markers object somewhere (like an array), and use that reference to delete the marker from the map

like : 
```
MarkersArray[] : [Marker1, Marker2, Marker3];
```
 delete marker 50:
```
MarkersArray.deleteAtIndex(50)
```
that's the idea!.

**Comment by bigbossmaher** [comment]
if i have this variable
var markers1 = [];
and 
i have created a marker
map.addMarker({
        'position': new plugin.google.maps.LatLng(36.851205,11.226290),
        'title': "TEST",
        'icon' : 'www/icons/car.png',
    }, function(marker) {
        marker.showInfoWindow();
    });

how can i insert it in the array so ican delete it later.
thanks

**Comment by wf9a5m75** [comment]
```js
addMarkers(data, function(markers) {
  markers[markers.length - 1].showInfoWindow();
});

function addMarkers(data, callback) {
  var markers = [];
  function onMarkerAdded(marker) {
    markers.push(marker);
    if (markers.length === data.length) {
      callback(markers);
    }
  }
  data.forEach(function(markerOptions) {
    map.addMarker(markerOptions, onMarkerAdded);
  });
}
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#create-multiple-markers

**Comment by bigbossmaher** [comment]
i'm not so advanced in javascript
just give me a solution for this not for a lot of data
if i have this variable
var markers1 = [];
and
i have created a marker
map.addMarker({
'position': new plugin.google.maps.LatLng(36.851205,11.226290),
'title': "TEST",
'icon' : 'www/icons/car.png',
}, function(marker) {
marker.showInfoWindow();
});

how can i insert it in the array so ican remove it later.
thanks

**Comment by bigbossmaher** [comment]
no answer ?

**Comment by cyrilbras** [comment]
You can just simply push it into array at the callback (like below), 
And after for remove it, you can make that like upper comment : markers1.deleteAtIndex(indexofmarker)

`var markers1 = [];

map.addMarker({
'position': new plugin.google.maps.LatLng(36.851205,11.226290),
'title': "TEST",
'icon' : 'www/icons/car.png',
}, function(marker) {
markers1.push(marker); //ADD THIS
marker.showInfoWindow();
});`
