### ISSUE TITLE
Always the HTML elements on the map are not working

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1268]
in my app , the clicks on the side panels are transfered to the map.
i tried the the v2 bta version , i tried also
#map_canvas{
    z-index:-1;
}
and
.panel{
      z-index:19000;
}
but no solution. it is really a big issue
this is my full intel XDK project
just open intel xdk and open this project
https://github.com/bigbossmaher/parking

![capture](https://cloud.githubusercontent.com/assets/15154710/22039129/54570b44-dcfe-11e6-8311-07b3fb50376b.PNG)

**Comment by wf9a5m75** [comment]
Try to move your map div after <body> tag.
```html
<body>
<div style="  width: 100%;height:93% ;margin: 0;padding: 0;left: 0;top: 0;" id="map_canvas"></div>
```

**Comment by bigbossmaher** [comment]
yes it works , is there any whay to solve the issue without moving the div ? because i must respect the framework7 structure

**Comment by bigbossmaher** [comment]
any help please ?

**Comment by herrberk** [comment]
I set `map.setClickable(true); ` when my panel is open in my app. Give it a try

**Comment by bigbossmaher** [comment]
yes it seems a temporary solution , but when adding more features in the app this solution is very tiresome
