### ISSUE TITLE
Android 7.0 permissions

### ISSUE THREAD

**Issue by cwoolum** [mapsplugin/cordova-plugin-googlemaps#1270]
Similar to #892, when the app launches for the first time and the map shows, it does not request permissions. I am using version 1.3.9 of the plugin. I am specifically testing in a Galaxy S7 Edge with Nougat. 

I'm looking through logcat and see no errors. After specifically setting location permissions in app settings of the system UI, the map then works.

**Comment by Hirbod** [comment]
Sorry, it's not avaiable on version 1.3.9, only in the current Github 1.4.0 master. You need to grab this master (which also has a lot of speed improvements loading remote markers)

**Comment by Hirbod** [comment]
Oh, @wf9a5m75 updated the npm to 1.4.0, so reinstalling the plugin should fix your problem. Be aware that Cordova Android 5+ and Cordova iOS 4+ is needed for that!
