### ISSUE TITLE
I'm using Ionic Native could I use v2 of the plugin?

### ISSUE THREAD

**Issue by 0x1ad2** [mapsplugin/cordova-plugin-googlemaps#1271]
Hi @wf9a5m75, I'm using Ionic Native could I use v2 of the plugin? And if so how do I switch from v1 to v2?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta

**Comment by 0x1ad2** [comment]
Thanks, just heard we are bound to the 1.x version because of stability.
Is there any way I could subscribe to the CAMERA_START of STOP events?

I already read this whole page but can't find a solution in there: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/844#issuecomment-200467799

**Comment by wf9a5m75** [comment]
You can see demo codes for the plugin v2 at https://github.com/mapsplugin/v2.0-demo

The v2 supports `CAMERA_MOVE_START`, `CAMERA_MOVE ` and `CAMERA_MOVE_END` events
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/CAMERA_EVENTS.html

code would be like this

```js
map.on(plugin.google.maps.event.CAMERA_MOVE_START, function() {
});
map.on(plugin.google.maps.event.CAMERA_MOVE, function() {
});
map.on(plugin.google.maps.event.CAMERA_MOVE_END, function() {
});
```

-----------

If you choose the v1, code would be like this

```js
map.on(plugin.google.maps.event.CAMERA_START, function() {
});
map.on(plugin.google.maps.event.CAMERA_END, function() {
});
```

**Comment by 0x1ad2** [comment]
If I look up the source code, I downloaded the dependencies using NPM. I don't see the `CAMERA_START` or `CAMERA_STOP` events unfortunately.

These are all the events that are available (running version 1.4.0):

```
/**
 * @private
 * You can listen to these events where appropriate
 */
exports.GoogleMapsEvent = {
    MAP_CLICK: 'click',
    MAP_LONG_CLICK: 'long_click',
    MY_LOCATION_CHANGE: 'my_location_change',
    MY_LOCATION_BUTTON_CLICK: 'my_location_button_click',
    INDOOR_BUILDING_FOCUSED: 'indoor_building_focused',
    INDOOR_LEVEL_ACTIVATED: 'indoor_level_activated',
    CAMERA_CHANGE: 'camera_change',
    CAMERA_IDLE: 'camera_idle',
    MAP_READY: 'map_ready',
    MAP_LOADED: 'map_loaded',
    MAP_WILL_MOVE: 'will_move',
    MAP_CLOSE: 'map_close',
    MARKER_CLICK: 'click',
    OVERLAY_CLICK: 'overlay_click',
    INFO_CLICK: 'info_click',
    MARKER_DRAG: 'drag',
    MARKER_DRAG_START: 'drag_start',
    MARKER_DRAG_END: 'drag_end'
};
```

**Comment by wf9a5m75** [comment]
The ionic wrapper is written by somebody. Not mine.

**Comment by 0x1ad2** [comment]
@wf9a5m75 I'm aware of that, it's only a Type wrapper for being able to use the plugin in TypeScript. You also provide those exports: https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/0c6cae90e500fdb65d5ed880a5fdc3ca7d83e80f/www/googlemaps-cdv-plugin.js#L2631
