### ISSUE TITLE
Marker

### ISSUE THREAD

**Issue by ran-j** [mapsplugin/cordova-plugin-googlemaps#1272]
How can remove a marker with coordinates.

To put a marker I use

```js
function criarmarquer(l,t){
	
	var latLong2 = new google.maps.LatLng(l, t);
	
	var marker2 = new google.maps.Marker({
			position: latLong2
		});
		
	marker2.setMap(map);
}
``` 

how can I remove the marker ?

**Comment by wf9a5m75** [comment]
It looks like your code is Google Maps JavaScript API v3.
It's not this plugin code.

**Comment by bigbossmaher** [comment]
i think you should put it an array then you can remove it.
if you find solution please share it.
thanks
