### ISSUE TITLE
Style, display all info window. 

### ISSUE THREAD

**Issue by pvsong** [mapsplugin/cordova-plugin-googlemaps#1273]
Hi, 
How can I display all info window and style background and title 
When click on one it will change styles like this. 

![screen shot 2017-01-21 at 3 21 54 am](https://cloud.githubusercontent.com/assets/9800579/22164318/454953ae-df89-11e6-8eaf-b446c1b59c9e.png)

Thanks!

**Comment by wf9a5m75** [comment]
The plugin does not provide the feature.

**Comment by wf9a5m75** [comment]
I think you can do with marker.
Because you can set base64 encoded image to the icon property.
It means you can generate marker image programmatically.

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#base64-encoded-icon
