### ISSUE TITLE
google autocomplete dropdown menu issue

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1274]
i use the gogole places api in my app.
the dropdown suggestions menu needs two clicks to be fired.
i tried making map clickble false , it is works with one clic
so the problem is related to your plugin
![capture](https://cloud.githubusercontent.com/assets/15154710/22174061/2a126822-dfd5-11e6-8021-53f5e54a26b5.PNG)

**Comment by wf9a5m75** [comment]
`map.setClickable(false)`
