### ISSUE TITLE
2.0.0-beta with Crosswalk is not working

### ISSUE THREAD

**Issue by lpikora** [mapsplugin/cordova-plugin-googlemaps#1275]
Hi,

when i try use maps plugin v2 in beta alongside Crosswalk 2.2.0, map is blank. Maps plugin v1.4.0 works fine with Crosswalk.

Reproducing error:

`git clone https://github.com/mapsplugin/v2.0-demo.git`
`setup android map key`
`cordova plugin add cordova-plugin-crosswalk-webview`
`add <preference name="xwalkZOrderOnTop" value="true" /> to config.xml`
`run on device`

**Comment by wf9a5m75** [comment]
Yes, the v2 does not work with crosswalk. That's known issue
