### ISSUE TITLE
multiple markers on click action

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1277]
i created i multiple markers using the function in the wiki.
i see that the default action to click on a marker is show infowindows
i want to change it to 
alert of title of the marker clicked

**Comment by wf9a5m75** [comment]
```js
map.addMarker({
  "myTitlte": "HelloWorld"
  "position": {lat:..., lng:...}
}, function(marker) {

    marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
        alert(marker.get("myTitle"));
    });
});
```

**Comment by bigbossmaher** [comment]
look here i tried this but not working
![capture](https://cloud.githubusercontent.com/assets/15154710/22317617/49b4d842-e375-11e6-8537-444d3fb44e77.PNG)


i still get the normal infowindow 

![capture1](https://cloud.githubusercontent.com/assets/15154710/22317621/571437ee-e375-11e6-998e-ce7d36be9f0c.PNG)

**Comment by wf9a5m75** [comment]
Don't use the title property

**Comment by bigbossmaher** [comment]
a tried alert("hello"); only and it is not show when i clik on the marker

**Comment by wf9a5m75** [comment]
Don't use the title property
![screen shot 2017-01-25 at 11 15 20 pm](https://cloud.githubusercontent.com/assets/167831/22322949/2fe063da-e354-11e6-9e05-0169dddfff70.png)

**Comment by bigbossmaher** [comment]
thanks a lot for your answer
i changed as you told me the proprety title to mtitle in the Json File
i try to alert it , but nothing shown ( the infowindow is dissapear ( good ))
![capture](https://cloud.githubusercontent.com/assets/15154710/22327151/0e5a1bcc-e3b6-11e6-9ccc-30865cddbe69.PNG)

**Comment by bigbossmaher** [comment]
how we can solve this ?

**Comment by bigbossmaher** [comment]
for 2 days , i have not recieve any solution

**Comment by wf9a5m75** [comment]
Are you a beginner of JavaScript? If so, I don't recommend you use this plugin.
The Google Maps plugin v3 is easy than this plugin.

If not, you should more effort to resolve your issue by your self.

At least your code obviously wrong at this part.
```js

map.addMarker(markerOptions, onMarkerAdded, function(marker) {
  marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
    alert("hello"):
  });
});
```

**Comment by bigbossmaher** [comment]
i used your  pkugin because javascript api have not some gesture like rotation by two fingers.
i tried for 5 days before i make a post on you wiki page
please help me to solve this issue

**Comment by wf9a5m75** [comment]
Hint: map.addMarker() function does not take the third arguments.

**Comment by bigbossmaher** [comment]
please i can't loose mre time . i choosed to work with your plugin so please be kind and help me . i will be very thinkful , it will not take more 2 min for you

**Comment by wf9a5m75** [comment]
The `map.addMarker()` method takes only two arguments, no the third arguments.
```js
map.addMarker(options, callback);
```

In your code, you take three arguments, but this is incorrect.
```js
map.addMarker(markerOptions, onMarkerAdded, function(marker) {
  marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
    alert("hello"):
  });
});
```

You should do like this:
```js
function addMarkers(ParkingData, calback) {
    var markes = [];
  
    function onMarkerAdded(marker) {
        marker.on(plugin.google.maps.event.MARKER_CLICK, function(marker) {
            alert("hello");
            alert(marker.get("myTitle"));
        });
        markers.push(marker);
        if (markers.length === ParkingData.length) {
            callback(markers);
        }

    }
    ParkingData.forEach(function(markerOptions) {
        map.addMarker(markerOptions, onMarkerAdded);
    });

}
```

**Comment by bigbossmaher** [comment]
thank you for your answer , it is very helpful 
but i'm getting the alert of "hello" only
the mtitle is not alerted

![capture2](https://cloud.githubusercontent.com/assets/15154710/22386522/c7cfda8e-e4d7-11e6-884f-ad88ce69cc0a.PNG)
![capture1](https://cloud.githubusercontent.com/assets/15154710/22386523/c7d24710-e4d7-11e6-8c17-cceed344dc8c.PNG)
![capture](https://cloud.githubusercontent.com/assets/15154710/22386524/c7d5e71c-e4d7-11e6-9cc3-746b567987b1.PNG)

**Comment by wf9a5m75** [comment]
Did you check JS error (width the chrome dev tools for Android)?

**Comment by bigbossmaher** [comment]
![capture](https://cloud.githubusercontent.com/assets/15154710/22387750/777eaa78-e4dd-11e6-82c6-78c7c54d2bfa.PNG)
this is what i get

**Comment by wf9a5m75** [comment]
Thanks, I'm inspecting it.

**Comment by bigbossmaher** [comment]
do you to have all my cordova project on github ?

**Comment by wf9a5m75** [comment]
It seems one of the 119 locations are incorrect (or have some problem), then a marker is not created for some reason.

`The line 830 of Map.js` means `Map.js line 829`.
JS error tells the error line number always +1.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/711d23c098bac8da22dba50bb318096abfc2b3fc/www/Map.js#L829

At the line line Map.js line 829, the code expects the result includes the `hashCode` property.
![screen shot 2017-01-27 at 1 46 13 pm](https://cloud.githubusercontent.com/assets/167831/22388754/0344a540-e497-11e6-8c53-6ec08b19592c.png)


The `hashCode` property is passed at here (PluginMarker.java / line 174):
![screen shot 2017-01-27 at 1 46 45 pm](https://cloud.githubusercontent.com/assets/167831/22388763/130b92d6-e497-11e6-9b2d-01eb86259e2e.png)

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/711d23c098bac8da22dba50bb318096abfc2b3fc/src/android/plugin/google/maps/PluginMarker.java#L174

I mean the code could not reach to the line 174 of PluginMarker.java.

I think there is an error message in native log.
Please find the logcat log, and tell me back.

And double check your data also.

Thanks.

**Comment by bigbossmaher** [comment]
ok i will check and back to you shortly

**Comment by bigbossmaher** [comment]
this the logcat of installation and exucution of the app 
[logcat.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/736399/logcat.txt)

**Comment by wf9a5m75** [comment]
Tons of 
```
I/chromium(15748): [INFO:CONSOLE(312)] "Error in Success callbackId: map_0_506614772230506496560 : ReferenceError: markers is not defined", source: file:///android_asset/www/cordova.js (312)
```

**Comment by bigbossmaher** [comment]
what that means ? :(

**Comment by wf9a5m75** [comment]
Variable `markers` is undefined in your code.

**Comment by bigbossmaher** [comment]
dear friend i tried to make some optimization 
this is the logcat
( the the mtitle property is not working )
this is the new logcat ( no ReferenceErro )
[logcat-new.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/736429/logcat-new.txt)

**Comment by wf9a5m75** [comment]
Ah, I understand what the wrong point is.

The below error means, at here `marker.get("myTitle")`, the marker variable does not have get() method.

```
"Uncaught TypeError: Object [object Object] has no method 'get'", source: file:///android_asset/www/index.html (57)
```

This causes because you use the v2 plugin.
In v2, you need to write your code like this:

```js
function onMarkerAdded(marker) {
   marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
      alert("hello");
      alert(marker.get("myTitle"));
   });
   markers.push(marker);
   if (markers.length === ParkingData.length) {
      callback(markers);
   }
}
```

Because the MARKER_CLICK event does not pass the marker instance as the first argument.

If you want to write the event lister in separate place, you can write like this:

```js
function onMarkerClick() {
  var marker = this;
  alert("hello");
  alert(marker.get("myTitle"));
}

function onMarkerAdded(marker) {
   marker.on(plugin.google.maps.event.MARKER_CLICK, onMarkerClick);
   markers.push(marker);
   if (markers.length === ParkingData.length) {
      callback(markers);
   }
}
```

**Comment by bigbossmaher** [comment]
every thing is working very good , but i still get this error message .. should i ignore it ?
![capture](https://cloud.githubusercontent.com/assets/15154710/22398023/09598c6e-e57f-11e6-9646-7ebde7df7da6.PNG)

**Comment by wf9a5m75** [comment]
Try to find which data causes the error, please. Create a marker one by one.

**Comment by Assilfira** [comment]
When I click a marker, I got this in my console log:

02-07 15:30:41.209 28366-28366/? I/chromium: [INFO:CONSOLE(63727)] "Uncaught TypeError: ele.hasAttribute is not a function", source: file:///android_asset/www/build/main.js (63727)

Any idea what might be?

Thanks

**Comment by wf9a5m75** [comment]
@bigbossmaher Map.js 830 is completely different with the latest code.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b2a99f4e78a532a72358ebf37adfc3b70b2307eb/www/Map.js#L830

I think you use old code

**Comment by wf9a5m75** [comment]
@Alex-Sessler This plugin does not use the `hasAttribute` method. Maybe in your code

**Comment by bigbossmaher** [comment]
i rechecked now 
the Map.js in parkingg\plugins\cordova-plugin-googlemaps\www in the same that you provid in the link
