### ISSUE TITLE
Not working on iOnic v2 

### ISSUE THREAD

**Issue by sarment0** [mapsplugin/cordova-plugin-googlemaps#1278]
I'm following this documentation https://ionicframework.com/docs/v2/native/google-maps/

It gives a runtime error:

```
Runtime Error
Uncaught (in promise): [object Object]
Stack
Error: Uncaught (in promise): [object Object]
    at s (http://localhost:8100/build/polyfills.js:3:4211)
    at s (http://localhost:8100/build/polyfills.js:3:4034)
    at http://localhost:8100/build/polyfills.js:3:4574
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:35830:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7083)
    at i (http://localhost:8100/build/polyfills.js:3:3671)
Ionic Framework: 2.0.0
Ionic Native: 2.4.1
Ionic App Scripts: 1.0.0
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.2.2
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
```

**If i run at iPhone it loads the app and it shows message in console that the map was loaded successfully, but it open a blank page, no map is showed.**

**Comment by wf9a5m75** [comment]
Someone created the ionic wrapper, but nobody maintenance it.

**Comment by Assilfira** [comment]
I don't know if it is the right way, but I used:

declare var plugin: any;

and then:

var map = plugin.google.maps.Map.getMap(mapElement);

and so on.. and it worked. (Ionic V2 + Angular 2)

**Comment by fripas** [comment]
Works: https://ionicframework.com/docs/v2/native/google-maps/

**Comment by battika** [comment]
Look [here](https://www.joshmorony.com/integrating-native-google-maps-into-an-ionic-2-application/)
