### ISSUE TITLE
On marker clic issue

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1279]
i created i multiple markers using the function in the wiki.
i see that the default action to click on a marker is show infowindows
i want to change it to
alert of title of the marker clicked

i changed the proprty title to mtitle
nothing work ever alert(hello"); is not working

this is my code 
![1ae6fd04-e3d1-11e6-8c03-a9aa853a60a9](https://cloud.githubusercontent.com/assets/15154710/22368305/1e403d20-e486-11e6-991f-46609887aac7.PNG)

**Comment by wf9a5m75** [comment]
Merge into  https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1277
