### ISSUE TITLE
Close v2-beta custom InfoWindow.

### ISSUE THREAD

**Issue by Yapsapp** [mapsplugin/cordova-plugin-googlemaps#1282]
Hi, first of all thanks for such a great plugin. The only problem is that map.clear() method does not clear opened custom InfoWindow. Maybe someone can advise me workaround to this issue. I've tried to push markers infowindows to an array and later  trigger infoWindow's close method but it didn't work

this.clearMap = function(){
   map.clear();
   for (var i = 0; i < infoWindows.length; i++) {
        infoWindows[i].close();
   }
   infoWindows = [];
}

**Comment by wf9a5m75** [comment]
I updated the code. Please try again.

**Comment by Yapsapp** [comment]
Thanks now all works as expected
