### ISSUE TITLE
Popover in Toolbar

### ISSUE THREAD

**Issue by Assilfira** [mapsplugin/cordova-plugin-googlemaps#1283]
I have a button in my toolbar, that when clicked, shows a Popover element (over the map). But when I click in any option of that Popover, that doesn't do anything...only Map Events work...

Any sugestion?

**Comment by battika** [comment]
Move the popover inside the map <div> if possible so that the map can detect and won't catch the click events. If not possible you can temporary disable click on the map by calling map.setClickable(false);

**Comment by Assilfira** [comment]
@battika 
Your first approach seems to do the trick. Is not 100%, but I think will do.

Thank you!

**Comment by battika** [comment]
Glad it helped. You can also use the v2 version of the plugin. It should detect any HTML element on the page. At least allegedly it should, I never tried and until v2 lacks Crosswalk support I will not do.
