### ISSUE TITLE
Any chance to add native support to Google Places API?

### ISSUE THREAD

**Issue by tuliobraga** [mapsplugin/cordova-plugin-googlemaps#1284]
I have seen here some discussion about the Places not being a part of this plugin and the suggested use of Javascript API. However, I am testing the Javascript API in my app (Ionic2) and it's kind unstable. If I'm not connected to the internet, the app suddenly stop. I know this plugin has nothing to do with Ionic, but is there any chance to add the native support to Places API? I believe it'll benefit many other developers. Thanks in advance!

**Comment by wf9a5m75** [comment]
Currently no plan.

**Comment by wf9a5m75** [comment]
I decided to start fundraising for creating another plugin of Google Places API.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1888
