### ISSUE TITLE
Plugin V 1.4.0

### ISSUE THREAD

**Issue by Assilfira** [mapsplugin/cordova-plugin-googlemaps#1285]
Version 1.4.0 of this plugin is working just fine for all my needs.

@wf9a5m75 you said,
"The version 1.x will be shutdown in 2017. The date is not decided yet, but we release the v1.4.0 is the last version of v1.x"

Does that means that this version will stop working for some reason, or it will just not be updated anymore? Can I still publish my App with 1.4.0 version?

Best regards.

**Comment by wf9a5m75** [comment]
>Does that means that this version will stop working for some reason, or it will just not be updated anymore?

The announce means the v1.4.0 won't update anymore. But you can still use it.
(But we won't support it, such as bug fixes)

> Can I still publish my App with 1.4.0 version?

Yes

**Comment by Assilfira** [comment]
@wf9a5m75 Thanks :)
