### ISSUE TITLE
Screen is Either Black or There's JavaScript Error with Ionic 2

### ISSUE THREAD

**Issue by mikeborozdin** [mapsplugin/cordova-plugin-googlemaps#1286]
Hi,

I'm using the code from the [Ionic 2 example](https://ionicframework.com/docs/v2/native/google-maps/).

I'm running it on a device (iOS) with live-reload and see the following behaviour:

1. When the app is loaded, I can see a black screen instead of the map
2. When I reload the map. It shows a map for a split of a second and then I see a JavaScript error:

```
[18:12:19]  console.warn: Native: tried accessing the GoogleMap plugin but it's not installed. 
[18:12:19]  console.warn: Install the GoogleMap plugin: 'ionic plugin add plugin.google.maps.Map' 
[18:12:19]  console.error: EXCEPTION: Uncaught (in promise): TypeError: undefined is not an object (evaluating 
            'pluginObj._objectInstance') callInstance@http://192.168.0.2:8100/build/main.js:395:21 
            http://192.168.0.2:8100/build/main.js:433:29 http://192.168.0.2:8100/build/main.js:319:19 
            t@http://192.168.0.2:8100/build/polyfills.js:3:11330 
```

**Comment by wf9a5m75** [comment]
Please ask at the ionic forum.
The ionic wrapper is created by someone, and nobody is maintained it.

**Comment by obermoserkitz** [comment]
This means, that cordova is not available.
Since you run this in the browser, it is an obvious error, because Browsers do not support cordova plugins.

Try to run this on an Emulator or real device!
