### ISSUE TITLE
addKmlOverlay callback

### ISSUE THREAD

**Issue by philipgriffin** [mapsplugin/cordova-plugin-googlemaps#1287]
Hi,

I'm using IONIC2 with android and this plugin, which is great, to show an overlay from a KML file.

I can get the overlay to show up and touching markers will show me their information but the callback function never seems to execute.

Here's the code I'm using

```
this.map.addKmlOverlay({'url': "myURL"},

                    function(kmlOverlay) {  
                    console.log("overlay");
                    
                    kmlOverlay.on(GoogleMapsEvent.OVERLAY_CLICK, function(overlay, latLng) {
                      
                      if (overlay.type == "Polygon") {
                        overlay.setFillColor("green");
                        console.log('polygon');
                      }
                      
                      if (overlay.type == "Polyline") {
                        overlay.setColor("green");
                       console.log('polyline');
                      }
                      
                      if (overlay.type == "Marker") {
                        overlay.showInfoWindow();
                          console.log('marker');
                      }
                      
                    });
                  });
```

None of my log statements ever execute. 

I have seen previous issues about this but I couldn't find a working solution.

**Comment by wf9a5m75** [comment]
I met this situation before.
The callback works but `console.log` does not work for some reason.

**Comment by philipgriffin** [comment]
Thanks for the reply. I still don't have any evidence that the callback is executed as no code inside the callback ever seems to be executed.

**Comment by wf9a5m75** [comment]
Did you try `alert("callback");` instead of `console.log`?

**Comment by philipgriffin** [comment]
I have attempted to alert within the callback with no success.

My ultimate goal for this is two things.

I want to have access to the Markers in the KML file so that I can make the info windows on the map always be displayed. So that every marker is showing its info window.

My second goal is to get the coordinates from the kmlOverlay.

This is why I'm trying to get the callback to work. Unless there is another way to achieve this.

**Comment by wf9a5m75** [comment]
Unfortunately, this plugin can display infoWindow only at once.

Secondly, I designed the KML layer is similar with the [kmlLayer](https://developers.google.com/maps/documentation/javascript/3.exp/reference#KmlLayer) of the Google Maps API v3.
You can get the marker coordinates only when you click on the marker.

Please find another way.

**Comment by philipgriffin** [comment]
Thanks very much.

**Comment by rgfactory** [comment]
Hi,

on android, the addKmlOverlay callback return only the Polyline items, but not the Marker items.
**On iOS it works like a charm, the callback contain polylines and markers.**

This is my config :

cordova android 5.1.1
cordova ios 4.1.1
ionic 1.3.1 (=> angular 1.5.3)
plugin name="cordova-plugin-googlemaps" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps"

and this is my code : 
```
class MapCtrl {

    /**
     * @ngInject
     */
    constructor() {

        this.mapDiv = document.getElementById("map_canvas"); // Define a div tag with id="map_canvas"
        this.map = plugin.google.maps.Map.getMap(this.mapDiv); // Initialize the map plugin

        this.onMapInit = function(map) {
            map.clear(); //Removes all markers, polylines, polygons, overlays, etc
            map.off(); //Removes event listeners

            map.addKmlOverlay({
                'url': "http://myrally.io/kml/test.kml",
                'animation': false
            }, function(kmlOverlay) {

                _.each(kmlOverlay.getOverlays(),
                    function(value) {
                        console.log(value);
                    }
                );
            });
        };

        // You have to wait the MAP_READY event.
        this.map.on(plugin.google.maps.event.MAP_READY, this.onMapInit);
    }
}
```

I am stucked...Do you have any idea ?

I hope you have enough informations to help.

Thanks in advance.
