### ISSUE TITLE
Is it possible to route?

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1288]
Hello, I have a javascript library that I can trace a route, which the response I can make directionsDisplay.setPanel (panel_id). Is it possible to do that with this plugin?

**Comment by wf9a5m75** [comment]
no

**Comment by wuilmerj24** [comment]
If you draw a polyline you could get the streets that transect the polyline?

**Comment by wf9a5m75** [comment]
This plugin provides only basic functions.
Drawing polyline is just drawing a polyline.
There is no way to detect which is street or POI...etc (because Google does not provide such a function).

If you want to draw a route, you need to specify all points.

**Comment by wuilmerj24** [comment]
If I have 2 coordinates I would only draw a straight polyline between the points not a route as such? If I google the map can I pass the coordinates?

**Comment by wf9a5m75** [comment]
The plugin can draw only a straight polyline if you pass 2 coordinates.

If you want to draw a route, you need to get the coordinate array using the Google Directions API, parse the result, then pass the coordinates to the plugin.
