### ISSUE TITLE
two clicks to work

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1291]
when this popup apear , the buttons are not working from the first click
so i should click one time and click another time to get response
![capture](https://cloud.githubusercontent.com/assets/15154710/22679467/c6c2b566-ed02-11e6-9618-23a925ab7ec1.PNG)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#change-4-save-battery-life

**Comment by rupalpatel0008** [comment]
You should try with events.
for eg, I use side menu in my app. So I use these code for setting side menu clickable.
* When you open the popup, publish an event like:
  this.events.publish('popup:opened', '');
* In your map file handle above event like:
  this.events.subscribe('popup:opened', () => {
    this.map.setClickable(false);
  });
* When you close the popup, publish an event like:
  this.events.publish('popup:closed', '');
* In your map file handle above event like:
  this.events.subscribe('popup:closed', () => {
    this.map.setClickable(true);
  });

**Comment by bigbossmaher** [comment]
thank you

**Comment by wf9a5m75** [comment]
@bigbossmaher When you pop up the dialog, try to execute `cordova.fireDocumentEvent('plugin_touch', {});`.

The plugin recalculates all HTML element positions.
