### ISSUE TITLE
V2 - Available

### ISSUE THREAD

**Issue by Assilfira** [mapsplugin/cordova-plugin-googlemaps#1292]
The isAvailable() method, does't work in V2 of the plugin

**Comment by wf9a5m75** [comment]
Why do you need?

**Comment by wf9a5m75** [comment]
Basically the plugin do it automatically.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/googlemaps-cdv-plugin.js#L348-L350

**Comment by Assilfira** [comment]
Yes, basically was to show some kind of alert, but you already said that. Thanks.
