### ISSUE TITLE
for iOS alone

### ISSUE THREAD

**Issue by nguyenkhanh87** [mapsplugin/cordova-plugin-googlemaps#1293]
I can not install this plugin because my MAC don't have android source.
So if I have no plan for Android development, and I don't install it, how can I install this plugin into my iOS-only app?

**Comment by wf9a5m75** [comment]
Just specify the google maps api key for ios

**Comment by nguyenkhanh87** [comment]
Thanks wf9a5m75 but still got error. Here is my error detail
Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 128 Error output:
Cloning into '/var/folders/83/xx8zl7ys59d3wl7fvgjyx23r0000gn/T/git/1486573050493'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by wf9a5m75** [comment]
I don't know your environment, but it's your problem, such as your git command version is old.

**Comment by nguyenkhanh87** [comment]
Seems not correct.
I've update all to lastest version. Error still there.
git version 2.10.1
cordova 6.5.0
Xcode 8
iOS SDK 10
Apache Ant 1.10.1
java version "1.8.0_121"

**Comment by wf9a5m75** [comment]
Otherwise clone the repository to local, then install from local.

**Comment by nguyenkhanh87** [comment]
I got error when download zip files (sdk and this plugin) and try to install it locally.
I am so desperate now, tried MAC, tried windows, I could not think about anything else, pls help me. 
```
Error: Uh oh!
Cannot find resource file "D:\Applications\xampp\htdocs\homerepublic\plugins\com.googlemaps.ios\Maps\Frameworks\GoogleMaps.framework\Versions\A\Resources\GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform
```

**Comment by wf9a5m75** [comment]
Why do you use `xampp`?
This plugin works only on native Android app and iOS app, does not run on browser.

**Comment by nguyenkhanh87** [comment]
yeah, I know, I use cordova & anguarjs, I want to test the app in browser first so I put it in xampp since I have it already, I am aware that this plugin will not work in browser, I only can see it in android/ios app. But I couldn't even install it successfully, that's my problem.
