### ISSUE TITLE
Pressing marker slides a navigation and a google maps button on to the map

### ISSUE THREAD

**Issue by JeffreyJamesMMM** [mapsplugin/cordova-plugin-googlemaps#1295]
I had to re-add my plugin today and now I'm getting new behavior and I hope that there is some map or marker option to disable it. It happens when a marker is pressed. It hides if I press anywhere else on the map.  It might be undocumented because I'm not seeing it anywhere. 

![image](https://cloud.githubusercontent.com/assets/942571/22748430/0e885c84-edf8-11e6-9783-bfe9a265b77d.png)

**Comment by wf9a5m75** [comment]
If you use the plugin v2, there is the `mapToolbar` option to disable it. No option for the plugin v1.
https://github.com/mapsplugin/v2.0-demo/blob/15be5b34f87b465f6b4420c7eb18d49d370dcee5/www/Map/setOptions.html#L51

**Comment by wf9a5m75** [comment]
The tool bar comes from the native api.

**Comment by JeffreyJamesMMM** [comment]
Thank you so much for your assistance.

**Comment by wf9a5m75** [comment]
:)
