### ISSUE TITLE
Map on multiple pages, not possible to remove marker

### ISSUE THREAD

**Issue by twinsit** [mapsplugin/cordova-plugin-googlemaps#1297]
Hi,

I created an app where I have on multiple screens a map (a logbook of bike-rides). If I open a second logbookitem, the old items are still displayed and I can't find a way to remove them. 

Is there a way to start every time with a new / blank map (without markers and polylines)?

I create every time a new object:

```
this.map = new GoogleMap('map', {
          'backgroundColor': 'white'
// Other settings removed to have a shorter post
        });
        let env = this;
		GoogleMap.isAvailable().then(() => {
		this.map.on(GoogleMapsEvent.MAP_READY).subscribe(() => {
		        var points = [];
		        var newpoint = null;
		        var latLngBounds = new GoogleMapsLatLngBounds(points);
		        for(let position of this.event.points) {
			      newpoint = new GoogleMapsLatLng(position.lat,position.lng);
				  points.push(newpoint);
				  latLngBounds.extend(newpoint);
				}
				
				if (env.marker) 
					env.marker.remove(); // This is what I tried to remove marker, but doesn't work
		        let markerOptions: GoogleMapsMarkerOptions = {
				  position: points[0]
				};
				this.map.setCenter(latLngBounds.getCenter());
				this.map.addMarker(markerOptions)
					.then((marker: GoogleMapsMarker) => {
						env.marker = marker;
				});
				
				
				
				this.map.addPolyline({
			        points: points,
			        'color' : '#AA00FF',
			        'width': 4
			      });		        
		        
			});
        });
		});
             }

```

Thanks a lot!

**Comment by wf9a5m75** [comment]
```js
map.clear()
```

Or

```js
map.addMarker(function(marker) {
  map.on("remove", function () {
    marker.remove();
  });
});

map.trigger("remove");
```

**Comment by twinsit** [comment]
Thanks. I tried, but the first one doesn't make any difference, and for the second one I receive an error that trigger isn't a function, 
> Property 'trigger' does not exist on type 'GoogleMap'. 

and
 
>Supplied parameters do not match any signature of call target.

**Comment by wf9a5m75** [comment]
The ionic wrapper is created by someone (not mine), and not maintenance well.
It seems the wrapper holds the native instance as the _objectInstance property.
https://github.com/driftyco/ionic-native/blob/master/src/plugins/googlemap.ts#L128

So the code likes

```js
map. _objectInstance.trigger("remove");
```

**Comment by twinsit** [comment]
The remove doesn't give an error anymore:

Now the code is

`       this.map._objectInstance.addMarker(markerOptions,function(marker) {
				  this.map._objectInstance.on("remove", function () {
				    marker.remove();
				  });
				});
				this.map._objectInstance.trigger("remove");
`

> TypeError: undefined is not an object (evaluating 'this.map._objectInstance'), http://192.168.1.12:8100/build/polyfills.js, Line: 3

Otherwise I have to do redo the whole implementation :(

**Comment by wf9a5m75** [comment]
The ionic wrapper is written by someone (not mine).
You need to choose use the wrapper or without the wrapper.

**Comment by twinsit** [comment]
I understand. But in fact I can work without the wrapper and just use the source / tutorial you provide here?

**Comment by wf9a5m75** [comment]
Or implement the trigger() method into the wrapper, send a pull request to the ionic-native repository.

**Comment by twinsit** [comment]
I solved this by creating a dynamic map ID. So every map has a dynamic I'd, and now it seems to be fixed.
