### ISSUE TITLE
InfoClick function read only the last id 

### ISSUE THREAD

**Issue by neoone75** [mapsplugin/cordova-plugin-googlemaps#1299]
Hi everybody, I'm using this wonderful plugin in a ionic v.1 project and  everything goes perfect except for one thing. When I read my marker from a table inside the db I start to put them on the map and I set an InfoClick function that should open the detail of the marker ( **openDetails(idMarker)** ) where idMarker should change foreach marker (**var idMarker = resultSet.rows.item(x).id** ). Unfortunately idMarker mantain always the last value of the for loop!

So if I parse 100 records, idMarker is set to the value of the last record parsed. Do you have an idea to correct this thing?

Thank you very much!

This is my simple code:

```
var callJsonP = function() {



    map.clear();


    var db = null;
    db = window.sqlitePlugin.openDatabase({
      name: 'dspot.db',
      location: 'default'
    });

    db.transaction(function(tx) {

          var query = "SELECT id, title, snipTesto, categoryId, lat, lon, owner, fresh FROM Marker";

          tx.executeSql(query, null, function(tx, resultSet) {


                console.log('logs: ' + resultSet.item);

                for (var x = 0; x < resultSet.rows.length; x++) {

                  var coord = new plugin.google.maps.LatLng(resultSet.rows.item(x).lat, resultSet.rows.item(x).lon);

                  //console.log('titolo:'+resultSet.rows.item(x).snipTesto );
                  var idMarker = resultSet.rows.item(x).id;


                  map.addMarker({
                    'position': coord,
                    'icon': 'img/' + resultSet.rows.item(x).categoryId + '-icon' + resultSet.rows.item(x).owner + resultSet.rows.item(x).fresh + '.png',
                    'draggable': false,
                    'title': resultSet.rows.item(x).snipTesto,
                    'infoWindowAnchor': [20, 5],
                    'snippet': 'Coordinate: ' + resultSet.rows.item(x).lat + ', ' + resultSet.rows.item(x).lon + ' id: ' + idMarker,
                    'markerClick': function(marker) {

                    },
                    'infoClick': function(marker) {
                      openDetails(idMarker);

                    },
                    'styles': {
                      'text-align': 'left',
                      'font-weight': 'bold',
                      'color': '#333'
                    }
                  })


                }
```

**Comment by battika** [comment]
Hello, did you check the infowindow example on the wiki page?

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker

**Comment by neoone75** [comment]
Do you mean the section "Create multiple markers"??

**Comment by battika** [comment]
Yes, exactly. By the way I start implementing the same function in Ionic 2 now so I will share my experience with you soon.

**Comment by neoone75** [comment]
My problem is only the function **openDetails(idMarker)** where idMarker is always the last id of my "for" loop... 
In another project I had a similar problem and I solve by using data.response.forEach(function(response) instead of "for"


`   data.response.forEach(function(response) {
                          
                          
                          var coord = new plugin.google.maps.LatLng(response.lat, response.lon);
                          
                        
                          if(response.newMarker==1){
                          //spot in attesa di validazione
                          
                          map.addMarker({
                                        'position': coord,
                                        'icon': 'img/new-icon.png',
                                        'draggable': false,
                                        'title': "New Spot",
                                        'infoWindowAnchor': [20,5],
                                        'snippet': "In attesa di validazione",
                                        'markerClick': function(marker) {
                                        //do something
                                        },
                                        'infoClick': function(marker) {
                                        
                                        if(window.localStorage.getItem("TIPOUTENTE")=== null || window.localStorage.getItem("TIPOUTENTE")=="USER")
                                        {marker.hideInfoWindow();}
                                        else{
                                        openDetails(response.id);
                                        }
                                        
                                        
                                        },
                                        'styles': {
                                        'text-align': 'center',
                                        'font-weight': 'bold',
                                        'color': '#333'
                                        }
                                        });
                          
                          
                          }`

**Comment by wf9a5m75** [comment]
Try like this:

```js
data.response.forEach(addMarkers);

function addMarkers(response) {
  map.addMarker({
   'position': {lat : response.lat, lng : response.lon},
   'icon': 'img/new-icon.png',
   'draggable': false,
   'title': "New Spot",
   'infoWindowAnchor': [20, 5],
   'snippet': "In attesa di validazione",
   'markerClick': onMarkerClicked,
   'infoClick': onInfoClicked,
   'styles': {
     'text-align': 'center',
     'font-weight': 'bold',
     'color': '#333'
    }
}

function onMarkerClicked(marker) {
  // do something...
}

function onInfoClicked(marker) {
    if (window.localStorage.getItem("TIPOUTENTE") === null || window.localStorage.getItem("TIPOUTENTE") == "USER") {
        marker.hideInfoWindow();
    } else {
        openDetails(response.id);
   }
}
```

**Comment by neoone75** [comment]
Unfortunately it doesn't work...

**Comment by neoone75** [comment]
This is my code:

`
       for(var x = 0; x < resultSet.rows.length; x++) {

         var coord = new plugin.google.maps.LatLng(resultSet.rows.item(x).lat, resultSet.rows.item(x).lon);

                   

                map.addMarker({
                                        'position': coord,
                                        'icon': 'img/'+resultSet.rows.item(x).categoryId+'-icon'+resultSet.rows.item(x).owner+resultSet.rows.item(x).fresh+'.png',
                                        'draggable': false,
                                         'title': resultSet.rows.item(x).snipTesto,
                                        'infoWindowAnchor': [20,5],
                                        'snippet': 'Coordinate: '+resultSet.rows.item(x).lat+', ' + resultSet.rows.item(x).lon,
                                        'markerClick': onMarkerClicked,
                                        'infoClick':onInfoClicked,
                                        'styles': {
                                        'text-align': 'left',
                                        'font-weight': 'bold',
                                        'color': '#333'
                                        }
                                    })

                

                function onMarkerClicked(marker) {
                  // do something...
                    }   


                function onInfoClicked(marker) {
                                                    
                                                   console.log('id: '+resultSet.rows.item(x).id)
  
                                                }




       }`

**Comment by wf9a5m75** [comment]
```js
function yourMainCode() {
  ....
  resultSet.rows.forEach(addMarker);
  ....
}

function addMarker(item) {

  map.addMarker({
    'position': {
      lat : item.lat,
      lng : item.lon
    },
    'icon': 'img/' + item.categoryId + '-icon' + item.owner + item.fresh + '.png',
    'draggable': false,
    'title': item.snipTesto,
    'infoWindowAnchor': [20, 5],
    'snippet': 'Coordinate: ' + item.lat + ', ' + item.lon,
    'markerClick': onMarkerClicked,
    'infoClick': onInfoClicked,
    'styles': {
      'text-align': 'left',
      'font-weight': 'bold',
      'color': '#333'
    },
    'item' : item
  });
}

function onMarkerClicked(marker) {
  // do something...
}

function onInfoClicked(marker) {
  alert('id: ' + marker.get("item").id);
}
```

**Comment by neoone75** [comment]
Thanks @wf9a5m75, I change the code like your suggest and I solve my javascript scope problem...

This is what I've changed:

` for(var x = 0; x < resultSet.rows.length; x++) {
                
                        
                        addMarker(resultSet.rows.item(x));

                }

            function addMarker(item) {

                                          map.addMarker({
                                            'position': {
                                              lat : item.lat,
                                              lng : item.lon
                                            },
                                            'icon': 'img/' + item.categoryId + '-icon' + item.owner + item.fresh + '.png',
                                            'draggable': false,
                                            'title': item.snipTesto,
                                            'infoWindowAnchor': [20, 5],
                                            'snippet': 'Coordinate: ' + item.lat + ', ' + item.lon,
                                            'markerClick': onMarkerClicked,
                                            'infoClick': onInfoClicked,
                                            'styles': {
                                              'text-align': 'left',
                                              'font-weight': 'bold',
                                              'color': '#333'
                                            },
                                            'item' : item
                                          });
                                        }


            function onMarkerClicked(marker) {
            // do something...
                                            }

            function onInfoClicked(marker) {
              alert('id: ' + marker.get("item").id);
            }
`
