### ISSUE TITLE
Plugin not working -- MapStyleOptions

### ISSUE THREAD

**Issue by LeoGuanco** [mapsplugin/cordova-plugin-googlemaps#1302]
Hello, i have installed the google-maps plugin and my problem is that when installing the FCM plugin gives me this error:

>**Execution failed for task ':processDebugGoogleServices'.
Please fix the version conflict either by updating the version of the google-s
ervices plugin (information about the latest version is available at https://bin
tray.com/android/android-tools/com.google.gms.google-services/) or updating the
version of com.google.android.gms to 9.0.0.**

I changed the google-play-services version to 9.0.0 in project.properties but now it gives me this error:

>**import com.google.android.gms.maps.model.MapStyleOptions;
                                        ^
  symbol:   class MapStyleOptions
  location: package com.google.android.gms.maps.model**

Anyone have the solution?

**Comment by wf9a5m75** [comment]
Must be 10.0.0 or over.

**Comment by LeoGuanco** [comment]
Switch to:

>**cordova.system.library.4=com.google.android.gms:play-services-maps:10.0.0
cordova.system.library.5=com.google.android.gms:play-services-location:10.0.0**

But now the first mistake I had:

>*** What went wrong:
Execution failed for task ':processDebugGoogleServices'.
Please fix the version conflict either by updating the version of the google-s
ervices plugin (information about the latest version is available at https://bin
tray.com/android/android-tools/com.google.gms.google-services/) or updating the
version of com.google.android.gms to 9.0.0.**

**Comment by wf9a5m75** [comment]
It seems the FCM plugin is too old.
You need to choose this plugin or the FCM plugin.

**Comment by LeoGuanco** [comment]
I see, it was probably that. Do you know of any plugin for push notifications?
