### ISSUE TITLE
Prevent map icons for navigating when marker is clicked

### ISSUE THREAD

**Issue by pke** [mapsplugin/cordova-plugin-googlemaps#1303]
Is there a way to prevent the map from showing the navigation icons in the bottom right corner when a marker is clicked?

**Comment by Assilfira** [comment]
Only in the v2 of the plugin.

**Comment by pke** [comment]
Pity. v2 does not work well with Crosswalk :(

**Comment by battika** [comment]
I hear you, that's the reason why I cannot switch to v2 and I don't have the necessary skill to fix the Crosswalk issue.

However there is a solution to this issue I found yesterday.

Here is a pull request that adds the feature you are after:
https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/1300

You can replace the provided GoogleMaps.java file in your Cordova folder and recompile it. It adds the mapToolbar option, if you set it to false, toolbar will not be displayed.

Note: if you are using Ionic 2 (which I am), you need to run ionic platform remove android / ionic platform add android commands to force recompilation.
