### ISSUE TITLE
reverse geolocation - geocoder

### ISSUE THREAD

**Issue by thpoiani** [mapsplugin/cordova-plugin-googlemaps#1305]
Hello guys,
I'm trying to do reverse geolocation but Im getting: "Geocoder service is not available."
Could anyone help me?﻿

**Comment by wf9a5m75** [comment]
I describe how to debug if you face any errors.
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?utf8=%E2%9C%93&q=Geocoder+service+is+not+available.

It seems the error message comes from MyGeocoder.java file.
![screen shot 2017-02-15 at 12 00 33 pm](https://cloud.githubusercontent.com/assets/167831/22993037/632c49a2-f376-11e6-912a-bd029cce217d.png)

Then you give me a hit "reverse geocoding". Check the code in the MyGeocoder.java.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/eee3cc817cc9771192d21019a05f5c5202c8f27a/src/android/plugin/google/maps/MyGeocoder.java#L104

![screen shot 2017-02-15 at 12 02 14 pm](https://cloud.githubusercontent.com/assets/167831/22993096/9dc39e8a-f376-11e6-8351-e5b51f26cccb.png)

I see. The error message "Geocoder service is not available." causes if the geocoder. getFromLocation throws an error.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/eee3cc817cc9771192d21019a05f5c5202c8f27a/src/android/plugin/google/maps/MyGeocoder.java#L104

Let's check the getFromLocation() of Android document.
https://developer.android.com/reference/android/location/Geocoder.html#getFromLocation(double, double, int)

I see. The getFromLocation() method throws an error when the input value is invalid or network error.
![screen shot 2017-02-15 at 12 04 51 pm](https://cloud.githubusercontent.com/assets/167831/22993188/f9d630ac-f376-11e6-8a3a-6ef799f387b7.png)

**Comment by thpoiani** [comment]
I tried on my Kindle, maybe that's the problem. On my Android Lenovo, it works ok!

**Comment by wf9a5m75** [comment]
Kindle does not contains the Google Play Services (I don't know the latest version). That's why.
