### ISSUE TITLE
Unable to make Rectangle Geofence in this plugin

### ISSUE THREAD

**Issue by inplamba** [mapsplugin/cordova-plugin-googlemaps#1306]
Hi @wf9a5m75 ,
I am unable to make rectangle geofence in this plugin .
I successfully make the Polygon and circle but didn't find any documentation for Rectangle case .
Please hep me out

**Comment by Assilfira** [comment]
Try using Polygon - https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Polygon

**Comment by inplamba** [comment]
Thanks @Assilfira for replying but this documentation is for Polygon shape geofence ,I already implemented it But i stuck in case of Rectangle didn't find anything for RECTANGLE shape geofence .

**Comment by wf9a5m75** [comment]
This plugin does not provide the geofence function

**Comment by inplamba** [comment]
Hi @wf9a5m75 thanks for replying , I need to draw just a shape just like i made polygon  using map.addPolygon() and show a circle on a map using map.addCircle() method ,so same as that is there is any method to show RECTANGLE on map using this plugin.

**Comment by inplamba** [comment]
Thanks for This, But how to check LatLngBounds.contains() in case of circle as it works for polygon but how to check in case of circle.

**Comment by wf9a5m75** [comment]
No method is provided.
