### ISSUE TITLE
map v2 on ios

### ISSUE THREAD

**Issue by luciman** [mapsplugin/cordova-plugin-googlemaps#1308]
Hi
I installed the v2 plugin 
On android it works well but on iOS, after I remove the map I can't click on any div from the screen area where the map was.

All the time the click event is returned by  ``googlemaps-cdv-plugin.js`` line 93
I'm using cordova with reactjs and on ``componentWillUnmount`` I use ``this._map.removemap()``
After I replaced `this._map.removemap()`` with ``this._map= null`` it worked well

Sorry for my English.

Thanks a lot.

**Comment by wf9a5m75** [comment]
I see. I will check this later. Thanks.

**Comment by thyde1** [comment]
I believe that I may have fixed this issue in PR #1269. It fixes an issue around maps which have been removed on iOS being handed touch events.

**Comment by luciman** [comment]
Indeed the problem is fixed in your PR!
Thanks a lot!

**Comment by thyde1** [comment]
@wf9a5m75 Can my PR #1269 be merged, seeing as it resolves the problem?
