### ISSUE TITLE
Not more 2 maps

### ISSUE THREAD

**Issue by sepiropht** [mapsplugin/cordova-plugin-googlemaps#1309]
I created a simple app with 4 tabs. Each tabs has one map. 
When i change tabs i canno't see the 4 map , i see only 2 or 1 and the others tabs are all empty.
I followed your guideline https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F.
it work well only if have not more 2 maps
Do you think that is really possible to have more than 2 maps in app ?
Link to my test. apk https://github.com/sepiropht/test-multiMap/tree/master/platforms/android/build/outputs/apk

**Comment by wf9a5m75** [comment]
You need to create maps when a new tab is open.

**Comment by sepiropht** [comment]
You mean call map.remove() when I leave a tab. ?

**Comment by wf9a5m75** [comment]
Creating map is only possible through `plugin.google.maps.Map.getMap()`.

You need to create maps in the tab when the tab page is opened.
