### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by starostin** [mapsplugin/cordova-plugin-googlemaps#131]
I am using this plugin in my application. In iOS everything works fine, but in Android, when I install app and open view with map, my app crashes. Than, when I launch app again, everything works. It happens just after first install .There are logs

07-09 19:01:15.676: W/dalvikvm(20469): VFY: unable to resolve static field 1062 (common_google_play_services_unknown_issue) in Lcom/google/android/gms/R$string;
07-09 19:01:15.676: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0007
07-09 19:01:15.676: W/dalvikvm(20469): VFY: unable to resolve static field 1052 (common_google_play_services_install_text_tablet) in Lcom/google/android/gms/R$string;
07-09 19:01:15.676: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0018
07-09 19:01:15.676: W/dalvikvm(20469): VFY: unable to resolve static field 1051 (common_google_play_services_install_text_phone) in Lcom/google/android/gms/R$string;
07-09 19:01:15.676: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x001f
07-09 19:01:15.676: W/dalvikvm(20469): VFY: unable to resolve static field 1047 (common_google_play_services_enable_text) in Lcom/google/android/gms/R$string;
07-09 19:01:15.676: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0026
07-09 19:01:15.676: W/dalvikvm(20469): VFY: unable to resolve static field 1067 (common_google_play_services_update_text) in Lcom/google/android/gms/R$string;
07-09 19:01:15.676: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x002d
07-09 19:01:15.676: W/dalvikvm(20469): VFY: unable to resolve static field 1064 (common_google_play_services_unsupported_text) in Lcom/google/android/gms/R$string;
07-09 19:01:15.686: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0034
07-09 19:01:15.686: W/dalvikvm(20469): VFY: unable to resolve static field 1057 (common_google_play_services_network_error_text) in Lcom/google/android/gms/R$string;
07-09 19:01:15.686: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x003b
07-09 19:01:15.686: W/dalvikvm(20469): VFY: unable to resolve static field 1054 (common_google_play_services_invalid_account_text) in Lcom/google/android/gms/R$string;
07-09 19:01:15.686: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0042
07-09 19:01:15.686: W/dalvikvm(20469): VFY: unable to resolve static field 1063 (common_google_play_services_unsupported_date_text) in Lcom/google/android/gms/R$string;
07-09 19:01:15.686: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0049
07-09 19:01:15.686: W/dalvikvm(20469): VFY: unable to resolve static field 1050 (common_google_play_services_install_button) in Lcom/google/android/gms/R$string;
07-09 19:01:15.686: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x000f
07-09 19:01:15.686: W/dalvikvm(20469): VFY: unable to resolve static field 1046 (common_google_play_services_enable_button) in Lcom/google/android/gms/R$string;
07-09 19:01:15.686: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0016
07-09 19:01:15.696: W/dalvikvm(20469): VFY: unable to resolve static field 1066 (common_google_play_services_update_button) in Lcom/google/android/gms/R$string;
07-09 19:01:15.696: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x001d
07-09 19:01:15.696: W/dalvikvm(20469): VFY: unable to resolve static field 1062 (common_google_play_services_unknown_issue) in Lcom/google/android/gms/R$string;
07-09 19:01:15.696: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0007
07-09 19:01:15.696: W/dalvikvm(20469): VFY: unable to resolve static field 1059 (common_google_play_services_notification_needs_installation_title) in Lcom/google/android/gms/R$string;
07-09 19:01:15.696: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x000e
07-09 19:01:15.696: W/dalvikvm(20469): VFY: unable to resolve static field 1060 (common_google_play_services_notification_needs_update_title) in Lcom/google/android/gms/R$string;
07-09 19:01:15.696: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0015
07-09 19:01:15.696: W/dalvikvm(20469): VFY: unable to resolve static field 1056 (common_google_play_services_needs_enabling_title) in Lcom/google/android/gms/R$string;
07-09 19:01:15.696: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x001c
07-09 19:01:15.706: W/dalvikvm(20469): VFY: unable to resolve static field 1064 (common_google_play_services_unsupported_text) in Lcom/google/android/gms/R$string;
07-09 19:01:15.706: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0023
07-09 19:01:15.706: W/dalvikvm(20469): VFY: unable to resolve static field 1057 (common_google_play_services_network_error_text) in Lcom/google/android/gms/R$string;
07-09 19:01:15.706: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x002a
07-09 19:01:15.706: W/dalvikvm(20469): VFY: unable to resolve static field 1054 (common_google_play_services_invalid_account_text) in Lcom/google/android/gms/R$string;
07-09 19:01:15.706: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0031
07-09 19:01:15.706: W/dalvikvm(20469): VFY: unable to resolve static field 1063 (common_google_play_services_unsupported_date_text) in Lcom/google/android/gms/R$string;
07-09 19:01:15.706: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0038
07-09 19:01:15.706: W/dalvikvm(20469): VFY: unable to resolve static field 1053 (common_google_play_services_install_title) in Lcom/google/android/gms/R$string;
07-09 19:01:15.706: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x004b
07-09 19:01:15.716: W/dalvikvm(20469): VFY: unable to resolve static field 1048 (common_google_play_services_enable_title) in Lcom/google/android/gms/R$string;
07-09 19:01:15.716: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0056
07-09 19:01:15.716: W/dalvikvm(20469): VFY: unable to resolve static field 1068 (common_google_play_services_update_title) in Lcom/google/android/gms/R$string;
07-09 19:01:15.716: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0061
07-09 19:01:15.716: W/dalvikvm(20469): VFY: unable to resolve static field 1065 (common_google_play_services_unsupported_title) in Lcom/google/android/gms/R$string;
07-09 19:01:15.716: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0073
07-09 19:01:15.716: W/dalvikvm(20469): VFY: unable to resolve static field 1058 (common_google_play_services_network_error_title) in Lcom/google/android/gms/R$string;
07-09 19:01:15.716: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0085
07-09 19:01:15.716: W/dalvikvm(20469): VFY: unable to resolve static field 1055 (common_google_play_services_invalid_account_title) in Lcom/google/android/gms/R$string;
07-09 19:01:15.716: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x00af
07-09 19:01:15.716: W/dalvikvm(20469): VFY: unable to resolve static field 1065 (common_google_play_services_unsupported_title) in Lcom/google/android/gms/R$string;
07-09 19:01:15.726: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x00ce
07-09 19:01:15.746: D/dalvikvm(20469): GC_FOR_ALLOC freed 884K, 30% free 7946K/11256K, paused 17ms, total 17ms
07-09 19:01:15.746: W/dalvikvm(20469): VFY: unable to resolve static field 1062 (common_google_play_services_unknown_issue) in Lcom/google/android/gms/R$string;
07-09 19:01:15.746: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x000c
07-09 19:01:15.746: W/dalvikvm(20469): VFY: unable to resolve static field 1061 (common_google_play_services_notification_ticker) in Lcom/google/android/gms/R$string;
07-09 19:01:15.746: D/dalvikvm(20469): VFY: replacing opcode 0x60 at 0x0005
07-09 19:01:15.746: I/dalvikvm(20469): DexOpt: unable to optimize static field ref 0x0419 at 0x25 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.showErrorNotification
07-09 19:01:15.746: E/GooglePlayServicesUtil(20469): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
07-09 19:01:15.756: E/GooglePlayServicesUtil(20469): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
07-09 19:01:15.756: I/u(20469): Making Creator dynamically
07-09 19:01:15.776: I/Google Maps Android API(20469): Google Play services client version: 4452000
07-09 19:01:15.776: I/dalvikvm(20469): Could not find method guj.a, referenced from method gqi.a
07-09 19:01:15.776: W/dalvikvm(20469): VFY: unable to resolve static method 24936: Lguj;.a (Landroid/content/Context;)Lgri;
07-09 19:01:15.776: D/dalvikvm(20469): VFY: replacing opcode 0x71 at 0x0003
07-09 19:01:15.776: E/dalvikvm(20469): Could not find class 'gpr', referenced from method gps.a
07-09 19:01:15.776: W/dalvikvm(20469): VFY: unable to resolve new-instance 4090 (Lgpr;) in Lgps;
07-09 19:01:15.776: D/dalvikvm(20469): VFY: replacing opcode 0x22 at 0x0000
07-09 19:01:15.776: E/dalvikvm(20469): Could not find class 'gpr', referenced from method gps.a
07-09 19:01:15.776: W/dalvikvm(20469): VFY: unable to resolve new-instance 4090 (Lgpr;) in Lgps;
07-09 19:01:15.776: D/dalvikvm(20469): VFY: replacing opcode 0x22 at 0x0000
07-09 19:01:15.776: E/dalvikvm(20469): Could not find class 'gpr', referenced from method gps.a
07-09 19:01:15.776: W/dalvikvm(20469): VFY: unable to resolve new-instance 4090 (Lgpr;) in Lgps;
07-09 19:01:15.776: D/dalvikvm(20469): VFY: replacing opcode 0x22 at 0x0000
07-09 19:01:15.776: D/dalvikvm(20469): DexOpt: unable to opt direct call 0x5ea3 at 0x0a in Lgps;.a
07-09 19:01:15.776: D/dalvikvm(20469): DexOpt: unable to opt direct call 0x5ea3 at 0x0c in Lgps;.a
07-09 19:01:15.776: D/dalvikvm(20469): DexOpt: unable to opt direct call 0x5ea3 at 0x0a in Lgps;.a
07-09 19:01:15.786: W/dalvikvm(20469): VFY: unable to resolve static field 1074 (MapAttrs) in Lcom/google/android/gms/R$styleable;
07-09 19:01:15.786: D/dalvikvm(20469): VFY: replacing opcode 0x62 at 0x000e
07-09 19:01:15.786: W/dalvikvm(20469): VFY: unable to resolve static field 20873 (t) in Lyp;
07-09 19:01:15.786: D/dalvikvm(20469): VFY: replacing opcode 0x62 at 0x000e
07-09 19:01:15.796: I/Google Maps Android API(20469): Google Play services package version: 5084030
07-09 19:01:15.796: W/dalvikvm(20469): VFY: unable to resolve static field 20873 (t) in Lyp;
07-09 19:01:15.796: D/dalvikvm(20469): VFY: replacing opcode 0x62 at 0x000d
07-09 19:01:15.956: D/dalvikvm(20469): GC_FOR_ALLOC freed 353K, 28% free 8104K/11256K, paused 18ms, total 18ms
07-09 19:01:16.016: I/dalvikvm(20469): Failed resolving Lcom/google/android/gms/location/internal/ParcelableGeofence; interface 4023 'Lgln;'
07-09 19:01:16.016: W/dalvikvm(20469): Link of class 'Lcom/google/android/gms/location/internal/ParcelableGeofence;' failed
07-09 19:01:16.016: E/dalvikvm(20469): Could not find class 'com.google.android.gms.location.internal.ParcelableGeofence', referenced from method glt.a
07-09 19:01:16.016: W/dalvikvm(20469): VFY: unable to resolve check-cast 2086 (Lcom/google/android/gms/location/internal/ParcelableGeofence;) in Lglt;
07-09 19:01:16.016: D/dalvikvm(20469): VFY: replacing opcode 0x1f at 0x0019
07-09 19:01:16.036: D/dalvikvm(20469): GC_FOR_ALLOC freed 330K, 27% free 8284K/11256K, paused 17ms, total 18ms
07-09 19:01:16.136: D/dalvikvm(20469): GC_FOR_ALLOC freed 372K, 26% free 8419K/11256K, paused 17ms, total 18ms
07-09 19:01:16.226: D/SoftKeyboardDetect(20469): Ignore this event
07-09 19:01:16.286: D/dalvikvm(20469): GC_FOR_ALLOC freed 372K, 26% free 8438K/11256K, paused 17ms, total 17ms
07-09 19:01:16.316: D/dalvikvm(20469): GC_FOR_ALLOC freed 476K, 26% free 8441K/11256K, paused 17ms, total 17ms
07-09 19:01:16.346: D/dalvikvm(20469): GC_FOR_ALLOC freed 456K, 25% free 8442K/11256K, paused 17ms, total 17ms
07-09 19:01:16.816: A/libc(20469): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 21145 (DataRequestDisp)

**Comment by deliriousrhino** [comment]
I am experiencing this same issue with  filetransfer @starostin I tried to set trustAllHosts to true but the maps still crash. Is there anything else you needed to do to fix the error?

**Comment by deliriousrhino** [comment]
@wf9a5m75 could this have something to do with your plugin.http.request dependency? Do we need that?
