### ISSUE TITLE
Reverse geo coding is not working 

### ISSUE THREAD

**Issue by Sunil2197** [mapsplugin/cordova-plugin-googlemaps#1310]
here code snippite
```js
addressLatLng  = {
   position:  {
            lat: 19.075984
          lng: 72.877656
}
}
```

```js
plugin.google.maps.Geocoder.geocode(that.addressLatLng, function (results) {
                debugger;
                if (results.length) {
                    that.$rootScope.address = '';
                    var address_1 = '';
                    var result = results[0];
                    angular.forEach(result.extra.lines, function (value) {
                        address_1 += value + '\n ';
                    });
                    var latLong = {
                        position: results[0].position
                    };
                    that.map.clear();
                    that.$rootScope.$broadcast('userAddress', latLong);
                    that.$rootScope.address = address_1;
                    that.$rootScope.$apply();
                    pageNavigator.popPage();
                }
                else {
                    alert("Not found");
                }
            });
```

**Comment by wf9a5m75** [comment]
What native error log did you get?

**Comment by Sunil2197** [comment]
`02-18 11:00:09.949 3035-3035/? D/PhoneStatusBar: updateNotification pkg=com.miui.securitycenter;id=2131296939
02-18 11:00:09.963 3035-3035/? D/SizeAdaptiveLayout: com.android.internal.widget.SizeAdaptiveLayout{87d2726 V.E...... ......ID 0,0-920,189 #7f0b0114 app:id/adaptive}child view android.widget.LinearLayout{9ae78b9 V.E...... ......ID 0,0-920,188 #1020371 android:id/status_bar_latest_event_content} measured out of bounds at 188px clamped to 189px
02-18 11:00:09.965 3877-10383/? W/System.err: java.net.UnknownHostException: Unable to resolve host "www.google.com": No address associated with hostname
02-18 11:00:09.965 3877-10383/? W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
02-18 11:00:09.965 3877-10383/? W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
02-18 11:00:09.965 3877-10383/? W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:358)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
02-18 11:00:09.966 3877-10383/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
02-18 11:00:09.966 3877-10383/? W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
02-18 11:00:09.966 3877-10383/? W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
02-18 11:00:09.966 3877-10383/? W/System.err:     at asgv.a(:com.google.android.gms:84)
02-18 11:00:09.966 3877-10383/? W/System.err:     at aukr.run(:com.google.android.gms:287)
02-18 11:00:09.966 3877-10383/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-18 11:00:09.966 3877-10383/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-18 11:00:09.966 3877-10383/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
02-18 11:00:09.966 3877-10383/? W/System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
02-18 11:00:09.966 3877-10383/? W/System.err:     at libcore.io.Posix.android_getaddrinfo(Native Method)
02-18 11:00:09.966 3877-10383/? W/System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
02-18 11:00:09.966 3877-10383/? W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
02-18 11:00:09.966 3877-10383/? W/System.err: 	... 20 more
02-18 11:00:10.667 3310-3310/? D/zhoumingliang: isINtest==false
02-18 11:00:10.677 1437-1437/? D/zhoumingliang: forLEDtest==false`

**Comment by Sunil2197** [comment]
02-18 11:00:09.949 3035-3035/? D/PhoneStatusBar: updateNotification pkg=com.miui.securitycenter;id=2131296939
02-18 11:00:09.963 3035-3035/? D/SizeAdaptiveLayout: com.android.internal.widget.SizeAdaptiveLayout{87d2726 V.E...... ......ID 0,0-920,189 #7f0b0114 app:id/adaptive}child view android.widget.LinearLayout{9ae78b9 V.E...... ......ID 0,0-920,188 #1020371 android:id/status_bar_latest_event_content} measured out of bounds at 188px clamped to 189px
02-18 11:00:09.965 3877-10383/? W/System.err: java.net.UnknownHostException: Unable to resolve host "www.google.com": No address associated with hostname
02-18 11:00:09.965 3877-10383/? W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
02-18 11:00:09.965 3877-10383/? W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
02-18 11:00:09.965 3877-10383/? W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:358)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
02-18 11:00:09.965 3877-10383/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
02-18 11:00:09.966 3877-10383/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
02-18 11:00:09.966 3877-10383/? W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
02-18 11:00:09.966 3877-10383/? W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
02-18 11:00:09.966 3877-10383/? W/System.err:     at asgv.a(:com.google.android.gms:84)
02-18 11:00:09.966 3877-10383/? W/System.err:     at aukr.run(:com.google.android.gms:287)
02-18 11:00:09.966 3877-10383/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-18 11:00:09.966 3877-10383/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-18 11:00:09.966 3877-10383/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
02-18 11:00:09.966 3877-10383/? W/System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
02-18 11:00:09.966 3877-10383/? W/System.err:     at libcore.io.Posix.android_getaddrinfo(Native Method)
02-18 11:00:09.966 3877-10383/? W/System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
02-18 11:00:09.966 3877-10383/? W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
02-18 11:00:09.966 3877-10383/? W/System.err: 	... 20 more
02-18 11:00:10.667 3310-3310/? D/zhoumingliang: isINtest==false
02-18 11:00:10.677 1437-1437/? D/zhoumingliang: forLEDtest==false

**Comment by Sunil2197** [comment]
Please close issue now its working
