### ISSUE TITLE
V2 not compatible with crosswalk

### ISSUE THREAD

**Issue by gbelmm** [mapsplugin/cordova-plugin-googlemaps#1311]
When will it be compatible?

**Comment by wf9a5m75** [comment]
If you create a patch and send it, I will test it, then merge it.

**Comment by olaferlandsen** [comment]
Hi @gbelmm I'm trying with crosswalk, but v2 don't work. So, you need remove crosswalk to work.

**Comment by gbelmm** [comment]
Ok but crosswall with ionic 1 is necessary

**Comment by PapyElGringo** [comment]
What is the issue with Crosswalk on the V2?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/crosswalk/README.md
