### ISSUE TITLE
marker icon is scaled by device density but its not documented properly

### ISSUE THREAD

**Issue by badpenguin** [mapsplugin/cordova-plugin-googlemaps#1312]
Wich is the minimum marker icon size? I've problem with 45x45 base64 icon created from the code below. It looks a little zoomed and very bad onto the app. With or without the "size" attribute does not change a thing.

```
marker.setIcon({
	url: this.MarkerService.doCreateIcon(item.punteggio, true)
	,size: this.MarkerService.mapMarkerSize
});

public mapMarkerSize = {
	width: 45,
	height: 45,
};

public doCreateIcon(val: number, active: boolean = false): string {
	this.canvasContext.clearRect(0, 0, this.mapMarkerSize.width, this.mapMarkerSize.height);
	this.canvasContext.drawImage(
		active ? this.backgroundIconActiveImage : this.backgroundIconImage,
		0, 0, this.mapMarkerSize.width, this.mapMarkerSize.height,
		0, 0, this.mapMarkerSize.width, this.mapMarkerSize.height,
	);
	this.canvasContext.fillText(val.toFixed(1), 14, 22, this.mapMarkerSize.width - 10);
	return this.canvasIcon.toDataURL();
}
```

**Comment by wf9a5m75** [comment]
If you specify the size property, the plugin makes image as the specify size.
Without the size property, the plugin makes image as the original size.

**Comment by badpenguin** [comment]
So, it seems there is some problem with the PNG. The images are not the size i specified also the transparency seems ignored. Should i use GIFs?

**Comment by wf9a5m75** [comment]
Decide by yourself please

**Comment by badpenguin** [comment]
uh? i'm asking if it is a know problem with PNG or not!

**Comment by wf9a5m75** [comment]
I don't know. If you feel this plugin has a problem with png, then use gif.

**Comment by badpenguin** [comment]
Definitively something strange.

I set the icon using:
```
icon: {
url: iconBase64,
size: { width:28, height: 45 }
}
```

instead the plugin render the marker of size 44x65 
it seems like scaled by the 150%

**Comment by wf9a5m75** [comment]
Please read the code before claiming. Source code is full open.

**Comment by badpenguin** [comment]
@wf9a5m75 Sorry, i really don't understand what you mean. I just followed the documentation and the instructions of this repository about custom markers :-(

**Comment by wf9a5m75** [comment]
If you are an engineer, you should try to resolve any problem by yourself at first, especially source code is full open, even you are not familiar with Java.
Reading code improve your skill, and understanding this plugin helps your programming.

This plugin is not product level, no full support.
It means you should try to resolve your issue by yourself.
You just says "something strange", but did you try to read the plugin code? 

---------

Keyword "**base64**" appears only here.
![screen shot 2017-03-15 at 10 00 45 am](https://cloud.githubusercontent.com/assets/167831/23961015/d6269ae2-0966-11e7-9fc3-6a82ea60b03d.png)

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/PluginMarker.java#L721

Then, keyword "**size**" appears around here.
![screen shot 2017-03-15 at 10 06 16 am](https://cloud.githubusercontent.com/assets/167831/23961097/19009b38-0967-11e7-8235-9d3ddaa4004d.png)

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/PluginMarker.java#L756-L771

It seems plugin does not ignore the property at least.

**Comment by badpenguin** [comment]
@wf9a5m75 the problem seems like that the icon size is multiplied by the device density - this thing is not documented properly IMHO. 
Basically to achieve the best results the documentation should be modified to explain that the icon must best x2 or more of the desired size otherwise its horribly upscaled by the plugin. 
This is my understanding of my problem so far.
 I've fixed by using a 256x256 icon and using a 45x45 size.
Good to know the plugin is not for production level, next time i'll try to use a different one but this is the one that ionic2-native suggests to use.
Said that, don't get me wrong, i thank you for the time you've dedicated to answering me.  
ありがとうございます
