### ISSUE TITLE
Error: Uh oh! Cannot find resource file ... GoogleMaps.bundle" for plugin com.google.maps.ios in iOS platform

### ISSUE THREAD

**Issue by andydemeulemeester** [mapsplugin/cordova-plugin-googlemaps#1313]
Since my upgrade to this versions:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.2 Build version 8C38

If get this error:
Error: Uh oh!
Cannot find resource file "/Volumes/Users/user/Documents/.../plugins/com.googlemaps.ios/Maps/Frameworks/GoogleMaps.framework/Versions/A/Resources/GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=Uh+oh%21+&type=Issues&utf8=%E2%9C%93

**Comment by andydemeulemeester** [comment]
Thanks

The problem was that I run the first remove, but not the second:
$> cordova plugin rm cordova-plugin-googlemaps
$> cordova plugin rm com.googlemaps.ios
