### ISSUE TITLE
Map touch event

### ISSUE THREAD

**Issue by yasiramidtech** [mapsplugin/cordova-plugin-googlemaps#1315]
Is there any way to create map touch event?like CAMERA_MOVE_START.I'm using map version 2.0 beta

**Comment by wf9a5m75** [comment]
Please use the plugIn v2

**Comment by yasiramidtech** [comment]
I'm using plugin v2 could you tell me the event of map touch how to implement?

**Comment by wf9a5m75** [comment]
What is your the map_touch event? I think click event is enough.

**Comment by yasiramidtech** [comment]
Thanks for click event suggestion.I come to back on map view from other view the map not shows sometimes only shows white screen when i tap to view the map shows.How to resolve it?

**Comment by wf9a5m75** [comment]
Trigger this code when you open the map page.
`cordova.fireDocumentEvent('plugin_touch', {});`

**Comment by wf9a5m75** [comment]
Read here
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#change-4-save-battery-life

**Comment by yasiramidtech** [comment]
It is working.
Thank you.

**Comment by yasiramidtech** [comment]
Could you tell me is there any limit to creating map?because i'm using map in 3 views map is working nice in 2 views but in 3rd view map is going to up.You can see view below image.
![screenshot_2017-02-28-10-34-38](https://cloud.githubusercontent.com/assets/23521283/23393155/983b0f9e-fda2-11e6-9beb-70a156957c71.png)
![screenshot_2017-02-28-10-35-19](https://cloud.githubusercontent.com/assets/23521283/23393156/983b0b66-fda2-11e6-9374-ae4c67894cad.png)

**Comment by yasiramidtech** [comment]
@wf9a5m75 ping

**Comment by wf9a5m75** [comment]
I think your HTML has problem. You need to create a map when open a page, then remove the map before moving to next page.

**Comment by yasiramidtech** [comment]
how to remove the map?

**Comment by wf9a5m75** [comment]
map.remove()
