### ISSUE TITLE
Google Map - Legal Notices

### ISSUE THREAD

**Issue by Assilfira** [mapsplugin/cordova-plugin-googlemaps#1316]
About the "Legal Notice", is it only necessary to call the method "getLicenseInfo()" and display its information, for instance, in a menu item, and the app is ready to go?

Btw, is there any way to check when the info was all fetched? So I can use a "loading" while waiting.

**Comment by wf9a5m75** [comment]
Since Google requires  to show the license attributes in your app, you must show the license. At least you need to provide the menu.
https://developers.google.com/maps/documentation/android-api/intro#attribution_requirements

> Btw, is there any way to check when the info was all fetched? So I can use a "loading" while waiting.

It's depends on your environment. Not programming problem.

**Comment by Assilfira** [comment]
Is it also normal, that the "getLicenceInfo()", besides "The Android Open Source Project", also shows other information like "Copyright (c) 2014 Chris Banes", or "Copyright 2006-2012, the V8 project authors", among others?

**Comment by wf9a5m75** [comment]
You need to display all strings that are obtained from `getLicenceInfo()` everything. That's all.

**Comment by Assilfira** [comment]
Ok. It is what I'm doing. Thanks
