### ISSUE TITLE
How to change the string when asking for permission of location

### ISSUE THREAD

**Issue by Hurinj** [mapsplugin/cordova-plugin-googlemaps#1317]
When I have to accept the location for the usage app, I have this string appearing too in the alert box : $NSLocationWhenInUseUsageDescription
I don't succeed to change it. 

I tried by changing the string in HelloCordova-Info.plist, but also in the plugin.xml of cordova-plugin-googlemap.

Thank you !

**Comment by wf9a5m75** [comment]
```
$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..." --variable NSLocationAlwaysUsageDescription="My app needs to access your location for example"
```

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a5af878a9d4a88c70f7a7d4212b5af9642c2b53a/plugin.xml#L199-L207

**Comment by Hurinj** [comment]
Doesn't seem to work well for me :/ 
I did : 
```
cordova plugin rm cordova-plugin-googlemaps
cordova plugin rm com.googlemaps.ios
cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..." --variable NSLocationAlwaysUsageDescription="My app needs to access your location for example"
```

And the string stays like that in the plugin.xml 
```

        <preference name="NSLocationWhenInUseUsageDescription" default="Show your location on the map" />
        <config-file target="*-Info.plist" parent="NSLocationWhenInUseUsageDescription">
            <string>$NSLocationWhenInUseUsageDescription</string>
        </config-file>

        <preference name="NSLocationAlwaysUsageDescription" default="Trace your location on the map" />
        <config-file target="*-Info.plist" parent="NSLocationAlwaysUsageDescription">
            <string>$NSLocationAlwaysUsageDescription</string>
        </config-file>
```

**Comment by wf9a5m75** [comment]
You need to specify both `NSLocationWhenInUseUsageDescription` and `NSLocationAlwaysUsageDescription`

**Comment by Hurinj** [comment]
Yes sorry this what i wrote exactly : 
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps --variable API_KEY_FOR_IOS="..." --variable API_KEY_FOR_ANDROID="..." --variable NSLocationAlwaysUsageDescription="La localisation est utilisée pour mieux vous repérer sur la carte et proposer plus de contenus pertinents" --variable NSLocationWhenInUsageDescription="La localisation est utilisée pour mieux vous repérer sur la carte et proposer plus de contenus pertinents"

**Comment by wf9a5m75** [comment]
Or just modify the plugin.xml directly.

```
$> git clone https://github.com/mapsplugin/cordova-plugin-googlemaps
$> vim cordova-plugin-googlemaps/plugin.xml  // open the plugin.xml, then edit the message
$> cordova plugin add (path to the folder)/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." ... etc
```

**Comment by Hurinj** [comment]
Ok thank you. 
So what I did is modifying the hellocordova-info.plist, but I have to do this each time after build because it is restarting the value to NSlocation...
I will try again with the --variable if I really need to rebuild all my project. 
:)
