### ISSUE TITLE
Ionic cordova not showing map

### ISSUE THREAD

**Issue by jcousin74** [mapsplugin/cordova-plugin-googlemaps#1319]
Hi, I have a problem but I don't know how to explain it.

I created an app which use a map with some points., It was working before but since few weeks the maps doesn't show. There is nothing, neither a blank map.

I've check this link https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map and everything seems right. 

There isn't any errors which is more dificult to find the problem

I hope you could help me.

Thanks

**Comment by wf9a5m75** [comment]
Please try to create a very simple project at first, then confirm the map is showing or not.

**Comment by jcousin74** [comment]
I tryed it as the one in your tutorial, but I get a blank map

2017-02-22 1:11 GMT-05:00 Masashi Katsumata <notifications@github.com>:

**Comment by wf9a5m75** [comment]
Then what native error did you get?

**Comment by jcousin74** [comment]
I don't have any error, this is my problem. It just doesn't show anything,
empty.

I put the SH1, and I can see that some marker are added (in the code) but
no map.

Perhaps if I show you the code yu could help me, it's an ionic app.

Let me know.

Thanks

2017-02-22 10:03 GMT-05:00 Masashi Katsumata <notifications@github.com>:

**Comment by malvadeza** [comment]
I'm having the same problem. The maps just show black on iOS. (works in Android)

I'm using ionic@2.2.1, cordova@6.5.0, ios-deploy@1.9.1, ios-sim@5.0.13
platform -> ios@4.3.1, android@6.0.0

It's funny because yesterday it was working perfectly and then I upgrade both ionic and cordova today morning and then it's not working. So it might be something with the version. But it's just a guess. Unfortunately I don't remember the previous versions

**Comment by wf9a5m75** [comment]
Please inspect the ionic versions by yourself.
First of all, the ionic wrapper is out of control from me.
And second, I have no knowledge about ionic framework.

**Comment by malvadeza** [comment]
@wf9a5m75  Thanks for the answer. 

I'm aware of that, just listed the ionic versions just to be safe and in case someone get here and have the answer for that.

I ran it now and I'm getting these messages now `ClientParametersRequest failed, 3 attempts remaining (0 vs 10). Error Domain=com.google.HTTPStatus Code=400 "(null)"`
I have checked the API Key in google console and everything is right, running on Android works (and I have feedback in the form of Traffic on the API) but in the XCode simulator all I see is a black screen. The user location seems to be avaible (I'm printing on console) but no rendering of the map and the error message mentioned.

**Comment by wf9a5m75** [comment]
`Google Maps SDK for iOS cannot connect or validate APIKey` means the Google Maps SDK for iOS can not to the Google server. It's not plugin's problem.

You can try:
1. recreate api key
2. recreate your project

**Comment by souber3746** [comment]
Hi @wf9a5m75 ,

I have created a simple cordova app to implement the cordova-plugin-googlemaps. I can built the App in Android. But the app doesn't render the Map. It only displays blank image with Google icon at lower left corner.

![screenshot_2017-03-15-19-24-26-346](https://cloud.githubusercontent.com/assets/8187909/23951756/2bc43cea-09b5-11e7-984f-5866d045b19a.jpeg)

Here the Environment details,
Cordova 6.5.0
Ionic 1.7.15
Installed platforms:
  android 6.1.2
  browser 4.1.0

Can you please help me to resolve this.

**Comment by wf9a5m75** [comment]
As imI said above, your api key is wrong, or something.

**Comment by ValentinKlinghammer** [comment]
Since this issue shows up on Google when looking for the issue; maybe this helps someone: 

It's also worth checking if you have enabled the  "Google Maps SDK for iOS" for your project in [Google Developers Console](https://console.developers.google.com/apis/api/maps_ios_backend/overview?project=).

**Comment by dimitri320** [comment]
I have the same problem. I think it's to do with CORS and WKWebview.... Just some ideas..

**Comment by joernlenoch** [comment]
I had the same problem which I could resolve by removing the crosswalk plugin.

Probably not the solution most were hoping for...

If you do not have it enabled, please
* make sure that you have proper styling for the element
* that the element does actually exist when you call the method (this would usually throw an error)

**Comment by ananharutyunyan** [comment]
I am using IONIC 2 and have the same problem, the google api key is correct and couldn't find the problem. Any Idea ?
Thanks

**Comment by victorhugorch** [comment]
Same problem. The google api key is correct.

**Comment by likedo** [comment]
**Ionic version:** 3.19.0
**Npm version:** 5.6.0
**Node version:** 9.3.0
**Cordova version:** 8.0.0

Hello.
Thanks for the plugin development ... it's great!

I wanted to report that I found problems with the iPhone emulator.
On the Android emulator, it seems to work great!

This is what i see:

**On Android Nexus 5X emulator:**

<img width="300" alt="nexus 5x" src="https://user-images.githubusercontent.com/8256514/34639626-bc63959e-f2e3-11e7-8e7b-9189e566e5fd.png">

**On iPhone 7 emulator:**

<img width="300" alt="iphone 7" src="https://user-images.githubusercontent.com/8256514/34639628-e54bbe82-f2e3-11e7-9b74-6a422a6f219b.png">

**My code**

```javascript
import { Component } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import {
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  GoogleMapOptions,
  CameraPosition,
  MarkerOptions,
  Marker
} from '@ionic-native/google-maps';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  map: GoogleMap;
  constructor(private googleMaps: GoogleMaps, private platform: Platform) {
    platform.ready().then(()=>{
      this.loadMap();
    });
  }

  loadMap() {
    let mapOptions: GoogleMapOptions = {
      camera: {
        target: {
          lat: 43.0741904,
          lng: -89.3809802
        },
        zoom: 18,
        tilt: 30
      }
    };
    
    this.map = this.googleMaps.create('map_canvas', mapOptions);
    
    // Wait the MAP_READY before using any methods.
    this.map.one(GoogleMapsEvent.MAP_READY)
    .then(() => {
      console.log('Map is ready!');
      // Now you can use all methods safely.
      this.map.addMarker({
        title: 'Ionic',
        icon: 'blue',
        animation: 'DROP',
        position: {
          lat: 43.0741904,
          lng: -89.3809802
        }
      })
      .then(marker => {
        marker.on(GoogleMapsEvent.MARKER_CLICK)
        .subscribe(() => {
          alert('clicked');
        });
      });
    });
  }
}
```
I do not write the log, because I have not found any errors.
In your opinion, what can I do? Tell me if you need more information!

best regards.

**Comment by wf9a5m75** [comment]
Blank map is your problem.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md
