### ISSUE TITLE
H

### ISSUE THREAD

**Issue by inplamba** [mapsplugin/cordova-plugin-googlemaps#1320]
Hi @wf9a5m75 How to Check if point is contained within a circle using this plugin .I used LatLngBounds.contains() forPolgon but its not working in case of circle Thanks in advance

**Comment by wf9a5m75** [comment]
No method is provided. But it's not difficult.
It's just easy math.
You can get the center position and the radius.
And you have a point.

Calculates the distance from A(center) to B(point you want to check). If smaller than radius, it's in the circle.

**Comment by inplamba** [comment]
Thanks for Quick reply ,But can you show me some working example to how to find distance in maps between my cuurrent point and center of circle.Thanks in advance

**Comment by wf9a5m75** [comment]
This is PHP version, but you can convert to JavaScript version easily.
http://stackoverflow.com/a/38457617/697856

**Comment by wf9a5m75** [comment]
Also somebody provides JavaScript version.
http://stackoverflow.com/a/18883819/697856

**Comment by inplamba** [comment]
Can i use computeDistanceBetween in this plugin?
