### ISSUE TITLE
How to properly use map.clear() ?

### ISSUE THREAD

**Issue by afgallo** [mapsplugin/cordova-plugin-googlemaps#1321]
Hi,

I use this great plugin in a Ionic 2 app. The code below sets up my map instance:

```
this.map = new GoogleMap(elementId, {
            backgroundColor: 'white',
            controls: {
                compass: true,
                zoom: true
            },
            gestures: {
                scroll: true,
                rotate: true,
                zoom: true
            },
            camera: {
                zoom: 10
            }
        });

        this.map.on(GoogleMapsEvent.MAP_READY).subscribe(() => {
            this.isMapReady = true;

            this.map.clear();

            this._addStopsToMap(stops);

            this._drawBusRouteOnMap(route.destinationSign, route.direction, busColour);
        });
```

You will have noticed a call to map.clear(). The goal with this call is to remove the previously drawn items such as markers and polylines. The issue is that the call to map.clear() has no effect whatsoever. Every time I load the map page I keep getting new markers and polylines on top of each other.

I am sure I'm doing something wrong because I also added a button on to this page and called map.clear() successfully. Is this a timing issue? When can I clear my map before adding new markers and stuff?

Cheers!

**Comment by wf9a5m75** [comment]
Ionic wrapper version(somebody created, but no maintains) is different from the original version.
`new GoogleMaps()` always returns different instance.

**Comment by afgallo** [comment]
@wf9a5m75 OK, but that doesn't still explain why my markers and polylines are still on the map. I would have expected if I got a new instance every time, my map would be 'clean' to start with. Would you care to elaborate a bit more please? Thanks.

**Comment by afgallo** [comment]
@wf9a5m75 never mind, I think I fixed the issue by replacing ```this.map.on``` to ```this.map.one```.  Thank you.
