### ISSUE TITLE
Javascript API vs Native SDKs

### ISSUE THREAD

**Issue by Yoloi** [mapsplugin/cordova-plugin-googlemaps#1322]
Hello!
I am currently developing an App with Ionic 2 and Cordova for Android and iOS.
It's a Geo-based app, I have tested what I want the app to do using the JavaScript API. 

I have encountered a few issues regarding the Js API (mentioned [here](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/How-different-are-the-JavaScript-APIs-(web)-and-the-mobile-SDKs-(native)))
- Slow loads 
- Limited to 25k free map loads per day 

Also the directions service API has an even lower limit of 2500 requests a day...
Can someone confirm if it's 2500 requests a day per API or 2500 requests a day per user?

I am using google.maps.DirectionsService(); to calculate a route but I have **NOT** activated the API for directions service and **it's working properly**. In the quota graph, 1 is added for every map load but not for direction service request (I think its included in Js API).

Due to the limit of the 25k map loads, I am more inclined to use the native SDKs, although I am concerned about the directions service...
Does the cordova-plugin-googlemaps support directions service?
Would I need to activate the directions service API to use it with the native SDKs?

Thanks in advance!

**Comment by wf9a5m75** [comment]
>Does the cordova-plugin-googlemaps support directions service?

Currently not supported

**Comment by Yoloi** [comment]
I don't really need directions per se.

When a user selects a level, that level has a certain distance. A polyline is drawn with a distance equal to the levels distance. A marker is placed at the end of this polyline.

The issue is drawing the polyline on roads / paths / routes a user can walk through. 

Can this be done using the cordova-plugin-googlemaps?

thanks in advance!

**Comment by wf9a5m75** [comment]
Since this plugin does not provide navigation feature, you need to get (or have) the navigation data.
If you have one, you can draw path on the map.
