### ISSUE TITLE
How to always show marker at the bottom of the map

### ISSUE THREAD

**Issue by inplamba** [mapsplugin/cordova-plugin-googlemaps#1323]
Hi @wf9a5m75 I want to always show the marker near to the bottom of the map just like in google map navigation ,as of now by using your plugin marker always shown in center of map ,can it be possible to show it below the center.Thanks in advance

**Comment by wf9a5m75** [comment]
Native APIs and this plugin do not have such a specific feature.
You need to calculate the bottom position always.
