### ISSUE TITLE
CSS not working and after using the map cant use other pages.

### ISSUE THREAD

**Issue by N00131835** [mapsplugin/cordova-plugin-googlemaps#1324]
Hi @wf9a5m75,
Thank you so much for this plugin.
I'm currently using this for my college project.
And I was wondering if you could help me figure out why the CSS is not working for the page where my map is?
![cssmapproblem](https://cloud.githubusercontent.com/assets/9143365/23274413/8cda9652-f9fa-11e6-8dc8-b1c48ff8230c.png)

It's supposed to have a bg color like this and other styles but it's not working..
![cssworking](https://cloud.githubusercontent.com/assets/9143365/23274275/014cb84a-f9fa-11e6-825a-8f6a0b140b84.jpg)

Also, when I'm on that Map page then I click the back button, everything else in my app doesnt work,
e.g. all of the buttons do not work anymore and I have to restart the app to use it again.

Hope you can help me.
Thank you in advance.

**Comment by wf9a5m75** [comment]
Read here at first please
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#how-does-the-plugin-work

**Comment by N00131835** [comment]
@wf9a5m75 Thanks for replying. I read it and change the bg colour. And it worked. Thanks.
But I have a 2nd issue..
It's when I'm on that Map page then I click the back button, everything else in my app doesnt work, e.g. all of the buttons do not work anymore and I have to restart the app to use it again.
Could you give me advice on how to solve this?
Thanks in advance.

**Comment by wf9a5m75** [comment]
Without checking your code, I can not advice anything.
Please try to start a very simple application (without UI, without other plugins) to learn this plugin.
This is the first way to understand this plugin.
