### ISSUE TITLE
Errors while installing this plugin

### ISSUE THREAD

**Issue by sharjeel619** [mapsplugin/cordova-plugin-googlemaps#1325]
Hi, I am having issues with this plugin. Whenever I install it, I get a lot of errors.  Otherwise my project builds fine. I followed every single instruction right in the following link:https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Windows
![errors](https://cloud.githubusercontent.com/assets/11159443/23273621/93ddb4c6-fa21-11e6-8772-72fb3e98878b.PNG)
 I am using Visual Studio 2015. And I would really appreciate if someone could help me.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=Visual+Studio+&type=Issues&utf8=%E2%9C%93

**Comment by wf9a5m75** [comment]
Also you use the google play services 9.8.0, but v10.0.0 or over is required.

**Comment by sharjeel619** [comment]
Thank you so much for replying. But I have already updated  everything in my android sdk. How do i install version 10 or above. Because there is no option where it would let me update any further.
![capture](https://cloud.githubusercontent.com/assets/11159443/23275241/966b2218-fa27-11e6-9f15-b8a13c883b5f.PNG)

**Comment by wf9a5m75** [comment]
Forget about the Google Play Services version, the plugin v1.4.0 works with v9.8.0 anyway.

You mentioned the Google Play Services v39, it does not matter.
It's a package version, not library version.
(If you want to learn it, google it)

----
Anyway, VS users face lots of trouble always.
Check out the past issues.

VS has a bug, but Microsoft does not want to fix it.
https://taco.visualstudio.com/en-us/docs/tips-and-workarounds-ios-ios-plugin-symlink-fix-readme/

**Comment by sharjeel619** [comment]
Even if i abandon VS and use the cli. It still gives me same error. Can you please point out what else might be wrong.
![zxc](https://cloud.githubusercontent.com/assets/11159443/23277504/dd97fc08-fa2f-11e6-800e-2c77aa430cab.PNG)

**Comment by wf9a5m75** [comment]
I guess another plugin specifies `<framework src="com.google.android.gms:+" />` or something. Find them and modify the version by your hand.

**Comment by sharjeel619** [comment]
Thanks but can you please be specific? What exactly would i have to modify?

**Comment by sharjeel619** [comment]
And also is there any alternative to using google maps on cordova?

**Comment by wf9a5m75** [comment]
>Thanks but can you please be specific? What exactly would i have to modify?

Find plugin.xml files in your app, check them please.

>And also is there any alternative to using google maps on cordova?

Please Google it.

**Comment by sharjeel619** [comment]
Thanks
