### ISSUE TITLE
V2 - No map until changing dimension of map div with inspector

### ISSUE THREAD

**Issue by Hurinj** [mapsplugin/cordova-plugin-googlemaps#1326]
Hi,

I changed the version to v2, I got no map displayed until I tried to change the width or height of the map and come back to the original height or width.
I had 100% for both, i changed 100% to 10% and then to 100% and the map displayed (I used inspector of safari).

I don't know what to do to change that, it is really strange ^^

**Comment by wf9a5m75** [comment]
Try this code:
 
```js
setTimeout(function() {
  map.refreshLayout();
}, 1000);
```

**Comment by Hurinj** [comment]
It doesn't work :(

**Comment by wf9a5m75** [comment]
This issue should fixed already (I so remember). If no, please report again.
