### ISSUE TITLE
plugin is not defined

### ISSUE THREAD

**Issue by GamalSebaee** [mapsplugin/cordova-plugin-googlemaps#1330]
i have install this plugin and when app run 
this error appear plugin is not defined
and this appear for get location
cannot ream method getMyLocation for undefined

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=plugin+is+not+defined&type=Issues&utf8=%E2%9C%93

**Comment by GamalSebaee** [comment]
thanks alot sir this is work
but i have new problem 
plugin work fine
but hidden div appear in map div 
and when i rotate mobile 
i show map under gui
Can you help me?

**Comment by wf9a5m75** [comment]
Don't use hidden div.

**Comment by GamalSebaee** [comment]
I can't add style to map div

**Comment by wf9a5m75** [comment]
This is already fixed on the master branch and the multiple_maps branch
