### ISSUE TITLE
map with more than one polygons  v2

### ISSUE THREAD

**Issue by luciman** [mapsplugin/cordova-plugin-googlemaps#1331]
If I have a map with two or more polygons, when I exit the app I recive "Unfortunately, apname has stopped"
on adb logcat I have:

```
02-27 15:33:13.859  1248  2076 D AudioFlinger: mixer(0xf4480000) throttle end: throttle time(2)
02-27 15:33:13.901  1209  1209 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
02-27 15:33:13.908 25078 25127 W PluginManager: THREAD WARNING: exec() call to CoreAndroid.exitApp blocked the main thread for 57ms. Plugin should use CordovaInterface.getThreadPool().
02-27 15:33:14.087  1209  1209 W SurfaceFlinger: couldn't log to binary event log: overflow.
02-27 15:33:14.161  1832  1873 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.activityPaused(android.os.IBinder) from ActivityManagerService.java:6439 waiters=0 for 248ms
02-27 15:33:14.163  1832  1876 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.activityPaused(android.os.IBinder) from ActivityManagerService.java:6439 waiters=1 for 246ms
02-27 15:33:14.170  1832  2632 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@cbab84d}
02-27 15:33:14.187 25078 25078 D AndroidRuntime: Shutting down VM
02-27 15:33:14.187 25078 25078 E AndroidRuntime: FATAL EXCEPTION: main
02-27 15:33:14.187 25078 25078 E AndroidRuntime: Process: com.xxx.xxx.xxx, PID: 25078
02-27 15:33:14.187 25078 25078 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.xxx.xxx.xxx/com.xxx.xxx.xxx.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.model.Polygon.remove()' on a null object reference
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.model.Polygon.remove()' on a null object reference
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at plugin.google.maps.PluginPolygon$2.run(PluginPolygon.java:149)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:5511)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at plugin.google.maps.PluginPolygon.onDestroy(PluginPolygon.java:139)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at org.apache.cordova.PluginManager.onDestroy(PluginManager.java:298)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at org.apache.cordova.CordovaWebViewImpl.handleDestroy(CordovaWebViewImpl.java:481)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at org.apache.cordova.CordovaActivity.onDestroy(CordovaActivity.java:305)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:6407)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	... 9 more
02-27 15:33:14.220  1832  2632 D WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@cbab84d}
02-27 15:33:14.236  1832  2111 I OpenGLRenderer: Initialized EGL, version 1.4
02-27 15:33:14.371  1832  2767 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
02-27 15:33:19.226  1832  2710 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@cbab84d}
02-27 15:33:19.238  1832  1857 D WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@cbab84d}
02-27 15:33:24.165  1832  1873 W ActivityManager: Activity destroy timeout for ActivityRecord{4cb36a8 u0 com.xxx.xxx.xxx/.MainActivity t543 f}
02-27 15:33:24.173  1209  1209 W SurfaceFlinger: couldn't log to binary event log: overflow.
```

**Comment by luciman** [comment]
``02-27 15:33:13.859  1248  2076 D AudioFlinger: mixer(0xf4480000) throttle end: throttle time(2)
02-27 15:33:13.901  1209  1209 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
02-27 15:33:13.908 25078 25127 W PluginManager: THREAD WARNING: exec() call to CoreAndroid.exitApp blocked the main thread for 57ms. Plugin should use CordovaInterface.getThreadPool().
02-27 15:33:14.087  1209  1209 W SurfaceFlinger: couldn't log to binary event log: overflow.
02-27 15:33:14.161  1832  1873 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.activityPaused(android.os.IBinder) from ActivityManagerService.java:6439 waiters=0 for 248ms
02-27 15:33:14.163  1832  1876 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.activityPaused(android.os.IBinder) from ActivityManagerService.java:6439 waiters=1 for 246ms
02-27 15:33:14.170  1832  2632 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@cbab84d}
02-27 15:33:14.187 25078 25078 D AndroidRuntime: Shutting down VM
02-27 15:33:14.187 25078 25078 E AndroidRuntime: FATAL EXCEPTION: main
02-27 15:33:14.187 25078 25078 E AndroidRuntime: Process: com.xxx.xxx.xxx, PID: 25078
02-27 15:33:14.187 25078 25078 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.xxx.xxx.xxx/com.xxx.xxx.xxx.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.model.Polygon.remove()' on a null object reference
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.model.Polygon.remove()' on a null object reference
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at plugin.google.maps.PluginPolygon$2.run(PluginPolygon.java:149)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:5511)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at plugin.google.maps.PluginPolygon.onDestroy(PluginPolygon.java:139)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at org.apache.cordova.PluginManager.onDestroy(PluginManager.java:298)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at org.apache.cordova.CordovaWebViewImpl.handleDestroy(CordovaWebViewImpl.java:481)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at org.apache.cordova.CordovaActivity.onDestroy(CordovaActivity.java:305)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:6407)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
02-27 15:33:14.187 25078 25078 E AndroidRuntime: 	... 9 more
02-27 15:33:14.220  1832  2632 D WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@cbab84d}
02-27 15:33:14.236  1832  2111 I OpenGLRenderer: Initialized EGL, version 1.4
02-27 15:33:14.371  1832  2767 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
02-27 15:33:19.226  1832  2710 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@cbab84d}
02-27 15:33:19.238  1832  1857 D WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@cbab84d}
02-27 15:33:24.165  1832  1873 W ActivityManager: Activity destroy timeout for ActivityRecord{4cb36a8 u0 com.xxx.xxx.xxx/.MainActivity t543 f}
02-27 15:33:24.173  1209  1209 W SurfaceFlinger: couldn't log to binary event log: overflow.
``
.
.
`` 02-27 15:33:14.187 25078 25078 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.schubertundfranzke.cityapp.predeal/com.xxx.xxx.xxx.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.model.Polygon.remove()' on a null object reference
``
I think this is most important part but I don't know how to solve it

**Comment by wf9a5m75** [comment]
Try to implement `map.remove()` before exiting your app

**Comment by luciman** [comment]
I have map.remove()
I also have map.clear() before map.remove() same thing... :-(

**Comment by wf9a5m75** [comment]
The error message says your app try to remove `null` polygon when you exits your app.
I think it's just timing problem of your code.
How about if you just call `map.remove` without exit your app?

**Comment by luciman** [comment]
I use react js and at componentwillunmount() I have map.remove(). Even if I load another component without polygons after the one with polygons, when I exitapp I recive the same error, also for polygons.

**Comment by wf9a5m75** [comment]
It doesn't matter what JS frame you use.
There is no other people that face to this issue, you need to resolve yourself.
Or if you put your **WHOLE FILES** including building files to your git repository, then I will check your code when I have a time.
