### ISSUE TITLE
markers not showing in ios

### ISSUE THREAD

**Issue by yasiramidtech** [mapsplugin/cordova-plugin-googlemaps#1333]
Custom png markers not showing in ios map.This code is working fine in android and marker shows.

map.addMarker({
                    position: { lat: GetLat, lng: GetLong },
                    icon: 'img/green-pin.png'
                });

**Comment by wf9a5m75** [comment]
I guess there is an error message in native (Xcode). Please provide it.

**Comment by shaneparsons** [comment]
I'm getting the same issue, but with android... the default marker is showing instead of my custom one.

**Comment by code-matt** [comment]
They are working fine for me on iOS.. I think you passing the wrong object for icon:

```
      'icon': {
        'url': 'img/green-pin.png'
      }}
```
