### ISSUE TITLE
NSLocationWhenInUseUsageDescription and NSLocationAlwaysUsageDescription not working in CLI and override to var placeholder in plist on_prepare

### ISSUE THREAD

**Issue by djett41** [mapsplugin/cordova-plugin-googlemaps#1334]
I believe your variable names are wrong, which is causing the actual variable placeholder $NSLocationAlwaysUsageDescription and $NSLocationWhenInUseUsageDescription to be the values of the plist settings..

For alot of us that dont commit platforms and plugins to version control (best practice), this is extremely annoying because everytime during the prepare phase, values are overwritten.

variables are typically uppercase just like your $API_KEY_FOR_IOS variable, so cordova is probably looking for $NSLocationAlwaysUsageDescription in caps rather than camel case..

I would recommend changing these to $LOCATION _WHEN_IN_USE_DESCRIPTION and $LOCATION _ALWAYS_USAGE_DESCRIPTION.

Also please test that these work before closing this issue for both CLI and config.xml and update the README.

Thanks!!!

**Comment by wf9a5m75** [comment]
Send me a pull request.

**Comment by djett41** [comment]
I wont be able to get to it until another day or so.  If you can make the quick change I would appreciate it, otherwise I'll wait until I can get to it thanks

**Comment by djett41** [comment]
@wf9a5m75 PR is up.  can this be released as 1.4.1?  This is a major issue for people who use the CLI for things like automated builds/releases, since the bug has to be manually overridden.

Thanks!

**Comment by djett41** [comment]
@wf9a5m75 any word on this?  should be a pretty quick test and update.  let me know if you have questions.

**Comment by banterstudios** [comment]
+1

**Comment by djett41** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/1336

**Comment by wf9a5m75** [comment]
#1336 is already merged to the multiple_maps branch. thanks.
