### ISSUE TITLE
Blank map on android

### ISSUE THREAD

**Issue by Vartex05** [mapsplugin/cordova-plugin-googlemaps#1335]
Hi, iam using this plugin with ionic 2 framework, but i cant solve with displaying map. It just shows blank map, just like in the troubleshooting tab, i checked all - api, correct api keys and so on, but it doesnt help at all. The weird thing is that in google developer console, i cant see any api request. Any advices? Iam not getting any errors.

**Comment by wf9a5m75** [comment]
Did you set your app background as transparent?
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#how-does-the-plugin-work

**Comment by Vartex05** [comment]
yea i did, i see the map controls, google logo, but map is blank...

**Comment by wf9a5m75** [comment]
How about any errors in native logs, logcat or xcode?

**Comment by Vartex05** [comment]
iam using chrome/ inspect console, how do i get to native logs?

**Comment by wf9a5m75** [comment]
This plugin works only on native devices, Android and iOS.
If you try to use this plugin on browser only, this plugin does not work.

**Comment by Vartex05** [comment]
well iam using samsung a5 for testing, but i can see it in chrome when i use Chrome://inspect. But no errors there

**Comment by wf9a5m75** [comment]
Although this plugin wraps the native APIs, but I strongly recommend learning how to create a simple app using Java/Objective-C(or swift), even hello world.

Since if you face something wrong, you can not even debug the log at this time.

Please try the HelloWorld of Android before using this plugin.
https://developer.android.com/training/basics/firstapp/index.html

**Comment by battika** [comment]
Follow this tutorial, it worked for me for Ionic 2

https://www.joshmorony.com/integrating-native-google-maps-into-an-ionic-2-application/

**Comment by Vartex05** [comment]
I followed the tutorial and it works... the problem must be it works only with debug keystore. When i use generated keystore, it displays blank map... how can i make it work with generated keystore?

**Comment by mrezzaaa** [comment]
Hi , this problem will solved when you build using `ionic cordova run android --prod --buildConfig=build.json`

here's an example with build.json

`{
    "android": {
        "debug": {
            "keystore": "android.keystore",
            "storePassword": "android",
            "alias": "android",
            "password" : "android",
            "keystoreType": ""
        },
        "release": {
            "keystore": "android.keystore",
            "storePassword": "android",
            "alias": "android",
            "password" : "android",
            "keystoreType": ""
        }
    }
}
`
