### ISSUE TITLE
Diferent map

### ISSUE THREAD

**Issue by jcousin74** [mapsplugin/cordova-plugin-googlemaps#1337]
Hi, I'd like to know if I can create diferente maps on diferente pages/screen. I've red that isn't multiple map, but if it's a map in page 1 and another one in page 2, is it posible ?
Thanks for helping
J

**Comment by wf9a5m75** [comment]
You need to create a map / destroy the map each time when you change your pages.

**Comment by jcousin74** [comment]
And how do you destroy the map ?!

**Comment by wf9a5m75** [comment]
`map.remove()`

**Comment by jcousin74** [comment]
I don´t know why, but I launch the map with
map.addEventListener(plugin.google.maps.event.MAP_READY, function ()

And it goes 3 or 4 time there, so I´ve got like 4 maps and got an error, do you have any idea why ?

**Comment by wf9a5m75** [comment]
`map.one()` insteadof `map.addEventListener()`
