### ISSUE TITLE
How to resize all markers when zoom changed?

### ISSUE THREAD

**Issue by DivineCake** [mapsplugin/cordova-plugin-googlemaps#1338]
I can't seem to find a better way to resize all markers other than clearing the map and placing them again, is there any more efficient way of achieving this? Thanks.

**Comment by wf9a5m75** [comment]
You can do it using event listeners.Please learn event handling before next asking.

**Comment by DivineCake** [comment]
I am actually able to detect change in zoom using listeners, what I'm asking is if there's any more efficient way of resizing the markers other than clearing the map and placing them again.

**Comment by wf9a5m75** [comment]
Marker also can have event listners for event.

**Comment by wf9a5m75** [comment]
You need to set new icon for all markers.

**Comment by DivineCake** [comment]
thanks, didn't know that this exists. Closing
