### ISSUE TITLE
[ionic2] Marker click not working

### ISSUE THREAD

**Issue by jlno** [mapsplugin/cordova-plugin-googlemaps#1340]
This listener not work:
```
this.map.addMarker(markerOptions).then((marker: GoogleMapsMarker) => {
  marker.addEventListener(GoogleMapsEvent.MARKER_CLICK).subscribe(() => alert());
});
```

**Comment by wf9a5m75** [comment]
Did you check the js console log and native lo

**Comment by jlno** [comment]
@wf9a5m75 yep, no error or warning.

**Comment by wf9a5m75** [comment]
So it's js problem. Unfortunately I'm not familiar with the ionic wrapper version. Please ask at the ionic forum.

**Comment by jlno** [comment]
https://github.com/driftyco/ionic/issues/10658
