### ISSUE TITLE
google map plugin isavailable  is undefined

### ISSUE THREAD

**Issue by minamorsali** [mapsplugin/cordova-plugin-googlemaps#1345]
hello I want to use google map plugin with cordova 6.5.0. I before use it in cordova 6.0.0 and it is ok. but now in cordova 6.5.0 plugin.google.maps.Map.isAvailable , isavailable variable is undefined...
why and how can I use it? please help me... thank you

**Comment by wf9a5m75** [comment]
I have no idea

**Comment by minamorsali** [comment]
no one has this issue?

**Comment by Assilfira** [comment]
If you are using V2, the plugin do that verification itself, so you don't have to do it yourself. If you are using V1, I don't know what can be the problem.

**Comment by thohng** [comment]
This one works with us:
https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/1398
