### ISSUE TITLE
HTML as a marker

### ISSUE THREAD

**Issue by loama** [mapsplugin/cordova-plugin-googlemaps#1348]
Is there any way to put HTML as my marker? I need to put a css animation and dynamic data inside it.

Thanks

**Comment by wf9a5m75** [comment]
no

**Comment by loama** [comment]
ok thanks

**Comment by loama** [comment]
I found a simple solution.
Using V2, you can use html inside infowindow so:

1) Put 1px transparent image as icon for your marker ( you can use http://www.1x1px.me/).

2) Change infowindow background-color and borders to transparent (in plugins/cordova-plugin-googlemaps/www/InfoWindow.js)

3) Add your html inside marker title, CSS animations and everything works.


Nice plugin!
