### ISSUE TITLE
Plugin don't set click on  dynamique html content in map canvas

### ISSUE THREAD

**Issue by sepiropht** [mapsplugin/cordova-plugin-googlemaps#1349]
I have elements in mapCanvas with dynamic dimensions ,when user click ont them. When the size of elements change all the new part added it not clickable. I cannot use map.setClickable() for this case, what  can i do ? 
Thanks

**Comment by wf9a5m75** [comment]
map.refreshLayout()

**Comment by sepiropht** [comment]
Thanks guy you are really great !
