### ISSUE TITLE
Set max zoom on the map

### ISSUE THREAD

**Issue by marijnroukens** [mapsplugin/cordova-plugin-googlemaps#1350]
Is it possible to set a max-zoom value on the map? And if so, how?

Thanks in advance!

**Comment by wf9a5m75** [comment]
If you use the plugin v2, you can do that.
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/setOptions.html#L68-L72

**Comment by marijnroukens** [comment]
Thanks for the tip! Appreciate it.
