### ISSUE TITLE
Uncaught TypeError: e.target.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by rgfactory** [mapsplugin/cordova-plugin-googlemaps#1352]
Hello folks,

I am loading a kml file on the map, everything works fine.
When I click on a marker, the info window is displayed, but I got the below error in the javascript console :

```
Uncaught TypeError: e.target.getBoundingClientRect is not a function
at HTMLDocument.<anonymous> (ionic.io.bundle.min.js:1)
at Pf (ionic.bundle.min.js:70)
at HTMLDocument.d (ionic.bundle.min.js:70)
at Marker.BaseClass.self.trigger (googlemaps-cdv-plugin.js:55)
at App._onMarkerEvent (googlemaps-cdv-plugin.js:176)
at <anonymous>:1:24
```

On iOS same problem... Please find below my code, it is quite simple :

```
class MapCtrl {
    /**
     * @ngInject
     */
    constructor() {
        this.mapDiv = document.getElementById("map_canvas");
        this.map = plugin.google.maps.Map.getMap(this.mapDiv);

        this.onMapInit = this.onMapInit.bind(this);
        this.displayStages = this.displayStages.bind(this);

        this.map.on(plugin.google.maps.event.MAP_READY, this.onMapInit);
    }

    onMapInit(map) {

        map.clear();
        map.off();

        this.displayStages(map);
    }

    displayStages(map) {

        map.addKmlOverlay({
            'url': "http://myrally.io/kml/test.kml",
            'animation': false
        }, function(kmlOverlay) {

            kmlOverlay.on(plugin.google.maps.event.OVERLAY_CLICK, function(overlay) {
            });
        });
    }
}
```

This is not blocking though, but I am afraid it could trigger side effects.

This is my config :
- cordova android 5.1.1
- cordova ios 4.1.1
- ionic 1.3.1 (=> angular 1.5.3)
- plugin name="cordova-plugin-googlemaps" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps"

Thanks in advance for your help on that.

**Comment by wf9a5m75** [comment]
Ionic is very strange framework for me.

Maybe this discussions are helpful for you.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/256

**Comment by NSahana** [comment]
Following is the exception in console after the overlay is shown (with the ConfirmDialog in the background)

EXCEPTION: Error in ./ConfirmDialog class ConfirmDialog - inline template:17:16 caused by: target.getBoundingClientRect is not a function
