### ISSUE TITLE
Android white flash on getMap and remove

### ISSUE THREAD

**Issue by banterstudios** [mapsplugin/cordova-plugin-googlemaps#1354]
Hi, So i'm running:

Cordova: 6.5.0
Android: 5.1.0
ios: 4.3.1
Cordova-google-maps: 1.4.0 (I've also tried with 1.3.9)
Android device : Galaxy S7 with Android 7.0

The problem is, whenever the map is initialised by getMap or removed with map.remove a white flash happens. This happens on both crosswalk and the native WebView android offers with Cordova. Any reason why this is happening or has anyone had any luck with fixing this issue?

I've attached a video of it happening and the source files are uploaded on github which can be seen from this link; https://github.com/banterstudios/androidmapbug

You can clone the repo, then cordova prepare and then cordova run android

[2017_03_12_21_46_30.mp4.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/836947/2017_03_12_21_46_30.mp4.zip)

**Comment by wf9a5m75** [comment]
Because the plugin must change the app background as `transparent`.

And I warn you that you **must** display the Google Logo because of the terms of service.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Terms-of-Services

**Comment by banterstudios** [comment]
But it only happens on android and not IOS. Also i forced the background colors to use !important so they couldnt be overriden but but still happens.

Thanks for the heads up on the logo, but this is a dummy project to demostrate the issue

**Comment by wf9a5m75** [comment]
Please understand how this plugin works before use this plugin.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#how-does-the-plugin-work

This plugin makes a map view **UNDER THE BROWSER VIEW**.
It means the map is not draw on the browser, such as video.

For the reason, the browser **MUST BE** transparent.
It doesn't matter iOS implementation.

If you need to specify background color, only available option is `map.setBackgroundColor()`
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.setBackgroundColor()

**Comment by banterstudios** [comment]
I understand how this plugin works.. With the exact same codebase for IOS and Android, only Android does the white flash when I call getMap and map.remove, I don't believe it has anything to do with making the html elements transparent when the map is initialised but more of an underlying bug with newer versions of Cordova / android.

**Comment by wf9a5m75** [comment]
Ah, I just remembered one thing.
This happens when your Android version is under ICE_CREAM_SANDWICH_MR1 (<= 4.0.4)
What is the version of your Android?

And I think this flashing is not occurred when you use the plugin v2.0.
Please also try the plugin v2.0.

**Comment by Textras** [comment]
Yes we still have this flash on latest Plugin V. 2.1.1. Working on it.
