### ISSUE TITLE
addKmlOverlay callback does not return everything on Android

### ISSUE THREAD

**Issue by rgfactory** [mapsplugin/cordova-plugin-googlemaps#1355]
Hi,

on android, the addKmlOverlay callback return only the Polyline items, but not the Marker items.
**On iOS it works like a charm, the callback contain polylines and markers.**

This is my config :

cordova android 5.1.1
cordova ios 4.1.1
ionic 1.3.1 (=> angular 1.5.3)
plugin name="cordova-plugin-googlemaps" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps"

and this is my code : 
```
class MapCtrl {

    /**
     * @ngInject
     */
    constructor() {

        this.mapDiv = document.getElementById("map_canvas"); // Define a div tag with id="map_canvas"
        this.map = plugin.google.maps.Map.getMap(this.mapDiv); // Initialize the map plugin

        this.onMapInit = function(map) {
            map.clear(); //Removes all markers, polylines, polygons, overlays, etc
            map.off(); //Removes event listeners

            map.addKmlOverlay({
                'url': "http://myrally.io/kml/test.kml",
                'animation': false
            }, function(kmlOverlay) {

                _.each(kmlOverlay.getOverlays(),
                    function(value) {
                        console.log(value);
                    }
                );
            });
        };

        // You have to wait the MAP_READY event.
        this.map.on(plugin.google.maps.event.MAP_READY, this.onMapInit);
    }
}
```

I am stucked...Do you have any idea ?

I hope you have enough informations to help.

Thanks in advance.

**Comment by rgfactory** [comment]
Another information : the Marker items are loaded on the map, but I don't have access their instance.

My goal is to change the icon of some markers (it works on iOS like I said !)

The weirdest part is if I display the callback parameter (kmlOverlay) in the javascript console, I can see the Marker items (but the array length does not "count" them) :

![console](https://cloud.githubusercontent.com/assets/25849017/23863365/e8e6d974-080f-11e7-9346-509203cf79bb.png)

Do you have any idea ?

Thanks a lot.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v1.2.1/example/DemoApp/www/pages/kmlOverlay.html#L219-L244

**Comment by wf9a5m75** [comment]
If you **just** change the marker icon, you can do like this (I haven't tested this, but should work):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.0">
    <Document>
        <Style id="My_Style">
            <IconStyle>
                <Icon>
                    <href>http://dagik.org/images/dagik_logo.png</href>
                </Icon>
            </IconStyle>
        </Style>
        <Placemark>
            <name> New point</name>
            <description>This is a new point to learn KML format.</description>
            <styleUrl> #My_Style</styleUrl>
            <Point>
                <coordinates>135.2,35.4,0</coordinates>
            </Point>
        </Placemark>
    </Document>
</kml>
```

**Comment by rgfactory** [comment]
Hello,

thank you for your answer.

This is exactly what I do to load the kml. The kml is loaded correctly. But

At the kml loading I want to change some **marker icons and set the anchor**, but it does not work because **I can't have access to Marker items in the kmlLayer parameter**. I tried with the example : 

```
loadKml(map, url) {

        map.addKmlOverlay({
            url: url,
            preserveViewport: false,
            animation: true
        }, function(kmlLayer) {
            
            console.table(kmlLayer);
            
            kmlLayer.on(plugin.google.maps.event.OVERLAY_CLICK, function(overlay, latLng) {
                switch (overlay.type) {
                    case "Marker":
                        overlay.setSnippet("Marker clicked!");
                        overlay.showInfoWindow();
                        break;
                    case "Polygon":
                        overlay.setFillColor("red");
                        break;
                    case "Polyline":
                        var width = overlay.getWidth();
                        overlay.setWidth(10);
                        setTimeout(function() {
                            overlay.setWidth(width);
                        }, 3000);
                        break;
                }

            });
        });
    }
```

**This line displays only the polyline Items**
`console.table(kmlLayer);`

**Comment by wf9a5m75** [comment]
addKmlOverlay is designed similar with kmlLayer of the Google Maps API v3.
Since that, there is no option to access each elements directly.
Instances are managed internally.

**Comment by rgfactory** [comment]
But it works on iOS, I have access to Polyline and Marker items. But on Android just Polyline items, that's the problem

**Comment by wf9a5m75** [comment]
Please read the code before asking, and try debugging by yourself. It's full open source.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/googlemaps-cdv-plugin.js

**Comment by rgfactory** [comment]
Ok I am gonna try...But I am wondering, maybe there is another solution.

Is it possible to change several properties of several markers at the same time ?

For example a click on a button will change several marker icons

**Comment by wf9a5m75** [comment]
You can do.

```js

addMarkers(data, function(markers) {
  markers.forEach(function(marker) {
    map.on("myCustomEvent", function() {
      onMyPropertyChanged(marker);
    });
  });
});

function onMyPropertyChanged(marker) {
  var myProperty = marker.get("myProperty");
  if (myProperty == "Yes") {
    marker.setIcon("new icon");
  }
}


button.addEventListener("click", function() {
  map.trigger("myCustomEvent");
});

```

Check out the addMarkers() function at here
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#create-multiple-markers

**Comment by wf9a5m75** [comment]
Also read this page.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/BaseClass

**Comment by rgfactory** [comment]
Ok thank you I will try it.

Another information about my issue. You said : 

> addKmlOverlay is designed similar with kmlLayer of the Google Maps API v3.
> Since that, there is no option to access each elements directly.
> Instances are managed internally.

But I used the [getOverlays()](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/KmlOverlay) function. It's supposed to return an Array.<Polyline | Polygon | Marker.

I insist because it's a strange behavior. I mean, the markers are loaded and displayed on the Map, but they are not in the array returned by the getOverlays() function, only on Android. I really don't understand that behavior...It should work, like on iOS.

This is my full function, with the getOverlays() function, that's quite easy :
```
loadKml(map) {

        map.addKmlOverlay({
            'url': "http://m[...]v1.kml",
            'animation': false
        }, function(kmlOverlay) {

            _.each(kmlOverlay.getOverlays(),
                function(value) {

                    if(value.type === "Marker") {

                        if(value.getTitle().includes("Départ")){
                            value.setIcon("images/departureMarker.png");
                            value.setIconAnchor(57, 57);
                        }
                        else if(value.getTitle().includes("Arrivée")){
                            value.setIcon("images/arrival.png");
                            value.setIconAnchor(57, 57);
                        }
                        else {
                            value.setIcon("images/zp_ok.png");
                        }
                    }
                }
            );

            kmlOverlay.on(plugin.google.maps.event.OVERLAY_CLICK, function(overlay) {

            });
        });
    }
```

What do you think ?

Thanks a lot.

**Comment by wf9a5m75** [comment]
I don't remember exactly, and I have no enough time to debug it.
That's why I said, "please read the code before asking".

**Comment by rgfactory** [comment]
About the other solution to change several properties of several markers at the same time : 

> You can do.
> 
> addMarkers(data, function(markers) {
>   markers.forEach(function(marker) {
>     map.on("myCustomEvent", function() {
>       onMyPropertyChanged(marker);
>     });
>   });
> });
> 
> function onMyPropertyChanged(marker) {
>   var myProperty = marker.get("myProperty");
>   if (myProperty == "Yes") {
>     marker.setIcon("new icon");
>   }
> }
> 
> 
> button.addEventListener("click", function() {
>   map.trigger("myCustomEvent");
> });
> Check out the addMarkers() function at here
> https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#create-multiple-markers

I can do that even if my markers are already added on the map ?
