### ISSUE TITLE
data url as icon for marker with SVG not working

### ISSUE THREAD

**Issue by christoph-puppe** [mapsplugin/cordova-plugin-googlemaps#1357]
Hi

I'm using SVG icons inside of my app and would like to use them for the map as well.

icon:  data:image/svg+xml;base64,PHN2ZyB4b....

-> no icon at all on the map

Loading png the same way works like a charm.

My Env: 

"ionic-native": "2.5.1",
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0

**Comment by wf9a5m75** [comment]
SVG is not supported.

**Comment by christoph-puppe** [comment]
sad to hear, thanks for the fast answer!

**Comment by Krishna25Vrinsoft** [comment]
Hello. svg is working or not for marker?

**Comment by wf9a5m75** [comment]
no

**Comment by nsuyog** [comment]
Same problem. but svg not working only for map
