### ISSUE TITLE
map.remove() does not work on iOS

### ISSUE THREAD

**Issue by petivagyok16** [mapsplugin/cordova-plugin-googlemaps#1358]
Hey. I just discovered that `this.map.remove()` does not work on iOS. At least for me.
I use the plugin in an ionic app and when i log out the user, i also want to `remove()` the map instance in ngOnDestroy. But if i login back the map is still there without its options and events. So a plain google map without any configuration and its not working.

**Comment by wf9a5m75** [comment]
I guess your code is something wrong.

**Comment by petivagyok16** [comment]
Well, it works fine on Android. But i will check it again.

**Comment by thyde1** [comment]
@petivagyok16 I have fixed a bug around iOS maps not being removed in PR #1269.
It may help solve your problem.

**Comment by petivagyok16** [comment]
Thanks.

**Comment by wf9a5m75** [comment]
Merged the pull request. Thanks.
