### ISSUE TITLE
Custom Styles?

### ISSUE THREAD

**Issue by shaneparsons** [mapsplugin/cordova-plugin-googlemaps#1359]
Is there a way to add custom styles like you can with the web version? 

If there isn't, consider this my request for the feature to be added.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1180#issuecomment-261125046

**Comment by shaneparsons** [comment]
Thanks. Not sure how I missed that.
