### ISSUE TITLE
GoogleMapsEvent.MY_LOCATION_CHANGE does not work

### ISSUE THREAD

**Issue by petivagyok16** [mapsplugin/cordova-plugin-googlemaps#1360]
I want to trigger the `MY_LOCATION_CHANGE` event (when the user moves, i guess?) but it does not work:

```
this.userMoves$ = this.map.addEventListener(GoogleMapsEvent.MY_LOCATION_CHANGE)
          .subscribe(changes => {
            console.log(`user moves: `, changes);
            this.map.getMyLocation({ enableHighAccuracy: true })
              .then( (myLocation: MyLocation) => {
                console.log(`user new location: `, myLocation.latLng);
                this.map.setCenter(myLocation.latLng);
              }).catch(error => {
                console.log(error);
              });
          });
```
it does not work with `this.map.on()` either.
They aren't give any data when im moving with my phone.
The purpose of this solution is that everytime the user moves i want to follow him with the camera.
am i doing something wrong, or ?

**Comment by wf9a5m75** [comment]
That event is gone long time ago.

**Comment by petivagyok16** [comment]
Wow. Its still there in the typescript documentation. Anyway, what would you recommend me to get a "user is constantly followed by the camera" behavior?

**Comment by wf9a5m75** [comment]
https://github.com/transistorsoft/cordova-background-geolocation-lt

**Comment by petivagyok16** [comment]
Thanks for your answer! Is there any free solution? I dont want to use the other functionalities only the mentioned one, and i think a whole paid plugin would be an overkill for 1 feature

**Comment by wf9a5m75** [comment]
cordova-background-geolocation-lt is free.

**Comment by petivagyok16** [comment]
Alright, thanks.
