### ISSUE TITLE
Feature Request: SVG marker icons

### ISSUE THREAD

**Issue by shaneparsons** [mapsplugin/cordova-plugin-googlemaps#1361]
The ability to use svg icons for the markers would be great.

I was able to do it in the javascript version of google maps, but it lacks a great deal of features that this plugin has.

**Comment by wf9a5m75** [comment]
Please send me a pull request :)

**Comment by shaneparsons** [comment]
I'd be glad to if I could get it working... Any advice on which files / code these changes would have to be made in?

**Comment by wf9a5m75** [comment]
The version 1.4.0 is cold. No more improve for the version.

The next version 2.0 is on the multiple_maps branch.
https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/multiple_maps

Similar case `base64:`, the code of Android is here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/android/plugin/google/maps/PluginMarker.java#L836-L839

Create a method into the PluginUtil class with proper name (such as `getBitmapFromSvgPath`), then write your code.

**Comment by shaneparsons** [comment]
I tried a few things, but couldn't get it to work in the end... My lack of experience with Java and Objective-C is likely a big part of that.

If anyone else stumbles upon this and would like to give it a shot, please do.

You can see the changes I made in [my fork](https://github.com/shaneparsons/cordova-plugin-googlemaps) if it helps.
