### ISSUE TITLE
Result of isGooglePlayServicesAvailable is not handled correctly

### ISSUE THREAD

**Issue by greg84** [mapsplugin/cordova-plugin-googlemaps#1364]
`isAvailable` calls `GooglePlayServicesUtil.isGooglePlayServicesAvailable`, which currently just generates an error message that assumes play services is not installed:

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/0c6cae90e500fdb65d5ed880a5fdc3ca7d83e80f/src/android/plugin/google/maps/GoogleMaps.java#L951

This is incorrect. The method being used has been deprecated and should be replaced with `GoogleApiAvailability.isGooglePlayServicesAvailable`, which returns any of the following values: SUCCESS, SERVICE_MISSING, SERVICE_UPDATING, SERVICE_VERSION_UPDATE_REQUIRED, SERVICE_DISABLED, SERVICE_INVALID

These return values can't all be treated as if play services is not installed. It may be disabled or need updating. If this method does not return SUCCESS, you need to call `getErrorDialog` so that Android will show a suitable dialog to the user based on the return value.

```
private boolean checkPlayServices() {
    GoogleApiAvailability googleAPI = GoogleApiAvailability.getInstance();
    int result = googleAPI.isGooglePlayServicesAvailable(this);
    if (result != ConnectionResult.SUCCESS) {
        if(googleAPI.isUserResolvableError(result)) {
            googleAPI.getErrorDialog(this, result, PLAY_SERVICES_RESOLUTION_REQUEST).show();
        }

        return false;
    }

    return true;
}
```
This code was copied from here: http://stackoverflow.com/questions/31016722/googleplayservicesutil-vs-googleapiavailability#31016761

**Comment by wf9a5m75** [comment]
The reason of the old code is that there were two versions , old Google play services and new Google play services, when the method were deprecated.

Anyway, the v1.4.0 is cold version. No more improved. Please send a pull request for the multiple_maps branch.
