### ISSUE TITLE
zIndex for android released 6/27/16; implementation possible?

### ISSUE THREAD

**Issue by caleb87** [mapsplugin/cordova-plugin-googlemaps#1366]
Any java developers know how hard adding support for Android zIndex is?

Appears it came out awhile ago: 
https://developers.google.com/maps/documentation/android-api/releases#june_27_2016
https://developers.google.com/android/reference/com/google/android/gms/maps/model/MarkerOptions#zIndex(float)

**Comment by wf9a5m75** [comment]
The plugin v2 has already implemented it
