### ISSUE TITLE
Cordova old setting JS, CSS NO PAGE REFRESH

### ISSUE THREAD

**Issue by tolgatasci** [mapsplugin/cordova-plugin-googlemaps#1369]
Hi,
my location maps.html

click marker redirect
harita.map.setClickable(false);
harita.map.clear();
 harita.map.off();
location.href = "home.html"

home click maps page
location.href="maps.html"

I'm redirecting, but the old settings are stopping. Page does not load completely. Map stays dull :(

**Comment by wf9a5m75** [comment]
You have to `map.remove()` before moving out from the map page.
