### ISSUE TITLE
Permission "READ_GSERVICES" still needed?

### ISSUE THREAD

**Issue by apptum** [mapsplugin/cordova-plugin-googlemaps#1371]
according to [this](http://stackoverflow.com/questions/24618806/is-read-gservices-permission-still-required-for-google-maps) this permission isn't needed with maps api v2.

**Comment by wf9a5m75** [comment]
Thanks. I will check it

**Comment by wf9a5m75** [comment]
Already removed the permission from the plugin.xml of the multiple_maps branch.
Thanks for sharing the information.
