### ISSUE TITLE
Plugin Geocoder not installed

### ISSUE THREAD

**Issue by williamdelvalle** [mapsplugin/cordova-plugin-googlemaps#1373]
I am trying to make use of the Geocoder plugin that comes with GoogleMaps but when I try to add a marker with the address obtained with the geocoder I get the error message saying that the Geocoder plugin is not installed, so the map loads fine but it shows me the marker With the title blank.

**Comment by alexgv99** [comment]
Same issue here... I've tried gitter (https://gitter.im/nightstomp/cordova-plugin-googlemaps) and G+ Community (https://plus.google.com/+AlexGouveaVasconcelos/posts/YgCrvcBWPiM), with no lucky yet.

**Comment by wf9a5m75** [comment]
It's the Geocoder plugin's problem

**Comment by alexgv99** [comment]
What does that mean, wf9a5m75?

**Comment by wf9a5m75** [comment]
I don't support the compatibility with other plugins.It's really depends on the plugins you installed. It's too much work.
