### ISSUE TITLE
Taking screen shot of map

### ISSUE THREAD

**Issue by santoshgupta901** [mapsplugin/cordova-plugin-googlemaps#1374]
Hi,
please tell me how could take snapshot of map which is loaded in the div element.
I try to take the image of div element it will show the blank image.

**Comment by banterstudios** [comment]
You will want to use the 'toDataURL()' function which will take a snapshot of the map and return the base64 string. Read more here

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.toDataURL()

**Comment by santoshgupta901** [comment]
Yes sir you are right thanks for your suggestion.

**Comment by sabanad** [comment]
But why isn't HtmlInfoWindow coming in the snapshot?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/HtmlInfoWindow/README.md#overview

**Comment by sabanad** [comment]
Isn't there any way HtmlInfoWindow can also be included in the snapshot?

**Comment by wf9a5m75** [comment]
No.
