### ISSUE TITLE
HTML Info Window Occasionally Shows Raw HTML behind Rendered HTML

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/cordova-plugin-googlemaps#1376]
I am using the HTML Info Windows in the #multiplemaps (v2) version of the plugin.  I can click on a marker one time and get the properly rendered Info Window.  Then later click the same marker and it displays the raw HTML behind it.   Any ideas what I could be doing to cause this?
![image](https://cloud.githubusercontent.com/assets/9216004/24517016/49f9b260-1542-11e7-8e60-26876df8b7fe.png)
![image](https://cloud.githubusercontent.com/assets/9216004/24517025/50d59892-1542-11e7-807a-8bb8536aad12.png)

**Comment by wf9a5m75** [comment]
How many times occur this issue? Is this rare case or almost every times?

**Comment by KimberleeDArmstrong** [comment]
It is a rare case.  Once it happens though, it happens every time until I reload the map.  Then it won't occur again for a while.

**Comment by KimberleeDArmstrong** [comment]
Any thoughts on how to fix this?  Our testers are hitting it on about 10% of their clicks and we can't release this project with it like this. :-(

**Comment by wf9a5m75** [comment]
I guess your HTML does contain something strange value in string.
![screen shot 2017-04-14 at 9 05 17 am](https://cloud.githubusercontent.com/assets/167831/25048473/80885268-20f1-11e7-95e8-897cac0945da.png)
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/InfoWindow.js#L76-L81

See the above code. If the browser detects as String, just inert it to innerHTML.
After that, that is browser's work. Not plugin's work.

**Comment by KimberleeDArmstrong** [comment]
I understand what you are saying.  Its just weird because the exact same title string sometimes works and sometimes doesn't.  
Unfortunately we are close to ditching this project and going back to the Google JS API due to stability issues :-(   I really don't want to do this.
I was going to present an option to management as a last chance option, but wanted to check with you first.  If I uploaded the entire app so that you can get to all the code, would you have any interest in looking for code issues in my app to help us make the it more stable? Let me know what you are thinking?  

Some issues we are seeing...
-HTML InfoWindow displaying non rendered HTML (issue above)
-InfoWindow gets stuck open and can not be closed.  Even map.clear() does not remove it.  Have to force quit.
-App Crashes when panning and zooming quickly.
-Image overlay get stuck on map and does not remove (I have a code hack in to workaround this issue so not a huge deal)
-PolyLines aren't being removed from map on remove call.

**Comment by wf9a5m75** [comment]
Ok. Please share your repository. And could you tell me how many days do you have?
As you may know, I have my real job. I can not commit full time on your project.

**Comment by KimberleeDArmstrong** [comment]
That is so nice of you. I completely understand. I can probably go 1-2 weeks? We can "buy you some beers" if you can get it stable. :-) 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by wf9a5m75** [comment]
Sounds great. Let's debug your project.

Please give me 'write' permission when you share your repository with me.
I don't affect your main code on the master branch. I will create another branch for debugging.

**Comment by wf9a5m75** [comment]
By the way, if you need to sign a NDA, send me it to my e-mail address.

**Comment by KimberleeDArmstrong** [comment]
I think we have an NDA on file from before. I shared the repo. We might have to look at getting you ssh access to our machine. Thanks! 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by wf9a5m75** [comment]
Thank you for the invitation. I will check out the repo after going back to my home.

**Comment by KimberleeDArmstrong** [comment]
I found something today that might help.  I can click on a marker when I get the raw html, I also get this console error.  I can click on the exact same marker right afterwards and it works perfectly with no console error.

**Comment by wf9a5m75** [comment]
Oh, I see. This might be great helpful. Thank you for the information.

**Comment by wf9a5m75** [comment]
Let me confirm one thing, is this occur only on iOS, or occur on both Android and iOS?

**Comment by wf9a5m75** [comment]
I noticed that the js error you pointed is not occurred every time when the html infowindow displays raw HTML strings. But at least the issue is occurred many times  than I thought. I will keep on work.

**Comment by KimberleeDArmstrong** [comment]
I am only on iOS currently

**Comment by wf9a5m75** [comment]
I have some update:

----

>HTML InfoWindow displaying non rendered HTML (issue above)

I figured out 50% of the reason of this issue.
But the issue is not reproduced after updating some code. Still inspecting.

----

> InfoWindow gets stuck open and can not be closed. Even map.clear() does not remove it. Have to force quit.

> App Crashes when panning and zooming quickly.

Both issues are caused by almost same reason.
I updated the plugin code. The commit https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/96dae7f5de778ea0b33f0acbb46debf6a1268f61 does not occur these problems (at least while I tested)

----

> Image overlay get stuck on map and does not remove (I have a code hack in to workaround this issue so not a huge deal)

I could not understand what the problem is.

----

> PolyLines aren't being removed from map on remove call.

The plugin code you installed was old. The problem was already fixed at https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/527d19389d4461bcd636724cbaf906b81a9705b5

**Comment by wf9a5m75** [comment]
I committed these updates on the update branch of your repo.
Please test it. (And please reinstall the latest code of the multiple_maps branch)

**Comment by KimberleeDArmstrong** [comment]
Great Thanks! Testing now. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by KimberleeDArmstrong** [comment]
I will explain better for the last issue. 

I have an image overly that shows the electric lines on the map. That layer is a global variable (gridOverlay). In my code on CAMERA_MOVE_END, I remove that layer and re-add it using gridOverlay.remove(). Sometime the layer is not removed from the map. If I look at the map object I can see the layer still there in the list of layers. I wrote a hack to get around it. 

I added this to CAMERA_MOVE_END event listener.... 

for (var key in googleMap.OVERLAYS) { 
if (key.indexOf('groundoverlay') != -1) { 
googleMap.OVERLAYS[key].remove(); 
} 
} 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by KimberleeDArmstrong** [comment]
Ok.  I feel like I am going crazy.  I removed and redownloaded the plugin...
![screen shot 2017-05-02 at 4 08 54 pm](https://cloud.githubusercontent.com/assets/9216004/25639881/35130f10-2f53-11e7-97c8-698d2959eeec.png)
I installed the bit bucket changes...
![screen shot 2017-05-02 at 4 20 41 pm](https://cloud.githubusercontent.com/assets/9216004/25639906/59cf5796-2f53-11e7-9d80-0ad20f6d5b71.png)
When I built my project it looked like the InfoWindow is gone.  I only see HTMLInfoWindow.  What did I do wrong?
![screen shot 2017-05-02 at 4 08 11 pm](https://cloud.githubusercontent.com/assets/9216004/25639991/8c20354e-2f53-11e7-8cba-5671f1b467e2.png)
![screen shot 2017-05-02 at 4 09 50 pm](https://cloud.githubusercontent.com/assets/9216004/25639998/92a3310a-2f53-11e7-98ef-5ee41320831c.png)


By the way, I can give you up to 4 more weeks to help debug the project and the company will donate handsomely if we can get it stable.

**Comment by wf9a5m75** [comment]
Ah, sorry. You tried the code before I announced.

Yes, the `InfoWindow` class has been renamed to `HtmlInfoWindow`.
And you also need to modify your code a little.

Before:

```js
  var infoWindow = new plugin.google.maps.InfoWindow();

  map.addMarker({
    position: {lat: 0, lng: 0},
    draggable: true,
    title: [
      'This is &lt;b&gt;Html&lt;/b&gt; InfoWindow',
      '&lt;br&gt;',
      '&lt;button onclick="javascript:alert(\'clicked!\');"&gt;click here&lt;/button&gt;',
    ].join(""),
    infoWindow: infoWindow
  });
```

After:

```js
  var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();

  var html = [
    'This is &lt;b&gt;Html&lt;/b&gt; InfoWindow',
    '&lt;br&gt;',
    '&lt;button onclick="javascript:alert(\'clicked!\');"&gt;click here&lt;/button&gt;',
  ].join("");
  htmlInfoWindow.setContent(html);

  map.addMarker({
    position: {lat: 0, lng: 0},
    draggable: true,
    infoWindow: htmlInfoWindow
  });
```

**Comment by KimberleeDArmstrong** [comment]
At least I am not going crazy ;-)

**Comment by wf9a5m75** [comment]
Sounds good :)

**Comment by KimberleeDArmstrong** [comment]
Should I still grab the commit code on bit bucket or does the plugin I installed yesterday evening have all that code in it?

**Comment by KimberleeDArmstrong** [comment]
I don't see the setContent function??

![screen shot 2017-05-03 at 9 57 58 am](https://cloud.githubusercontent.com/assets/9216004/25666902/7e47e702-2fe7-11e7-8aa3-479caec2d489.png)
![screen shot 2017-05-03 at 9 58 47 am](https://cloud.githubusercontent.com/assets/9216004/25666906/80832b30-2fe7-11e7-9a38-def615446ac7.png)

**Comment by wf9a5m75** [comment]
Should be there.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/814f019b3e1541d6312d7f38556bd58c8006dddf/www/HtmlInfoWindow.js#L182

**Comment by wf9a5m75** [comment]
Ah, I think you installed kind of old commit version.
Please reinstall the plugin.

**Comment by KimberleeDArmstrong** [comment]
I still use #multiplemaps? 


Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by KimberleeDArmstrong** [comment]
I still use #multiple_maps right?

**Comment by wf9a5m75** [comment]
The last commit of the multiple_maps is 
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/32f562955275e64f48a7a142f8bb36e6031d4b14

**Comment by KimberleeDArmstrong** [comment]
Sorry to be such a pain today.  Pointing directly to that commit allowed me to get the right code.  But now I am not seeing a showInfoWindow() function.  Did something change there?

**Comment by wf9a5m75** [comment]
>Did something change there?

No, I didn't. The changes only on HtmlInfoWindow.js

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Marker.js#L249-L252

**Comment by wf9a5m75** [comment]
I'm checking for iOS.

**Comment by wf9a5m75** [comment]
Sorry for painful day for you. I found the problem and fixed it.
Please reinstall the plugin. I confirmed the HtmlInfoWindow works on iOS.

**Comment by KimberleeDArmstrong** [comment]
No worries thank you for looking into it.  I have removed and installed the plugin several times.  Using just #multiple_maps and also using the latest commit tags afae77a...  I am still not seeing the ShowInfoWindow function though.  :-(   Can you think of something else I need to do?

**Comment by KimberleeDArmstrong** [comment]
It looks like the raw html behind the rendered infoWindow issue is fixed!  Yay!  I have been testing all day and haven't seen one problem.  I am having other new issue with my app.  Sometimes the marker isn't clickable for infoWindow, refresh same marker is clickable for infoWindow, refresh same marker doesn't appear, refresh same marker shows up and is clickable for infoWindow.  I am still having frequent app crashes also.  Do you want me to open another issue and close this one?

**Comment by wf9a5m75** [comment]
>Sometimes the marker isn't clickable for infoWindow, refresh same marker is clickable for infoWindow, refresh same marker doesn't appear, refresh same marker shows up and is clickable for infoWindow.

Is there any (JS or native) error logs at the time?

>I am still having frequent app crashes also. 

When? I tested your app 2 weeks ago, but I haven't faced the crash after the updating the plugin code.

> Do you want me to open another issue and close this one?

Yes, please.

**Comment by KimberleeDArmstrong** [comment]
I am not seeing any native nor JS errors and looking at the marker in the map object MARKERS element the markers that are working and aren't working are identical.
