### ISSUE TITLE
launchNavigation always opens Apple Maps

### ISSUE THREAD

**Issue by b4tch** [mapsplugin/cordova-plugin-googlemaps#1377]
Hi all, just a minor issue but when using the launchNavigation method, my iPhone always opens Apple Maps despite having Google Maps installed.  I have the latest version of the GoogleMaps plugin, and have installed the LaunchNavigator plugin.  My code is below, is there something I'm missing?  Thanks!

```
var destinationLatLng = new plugin.google.maps.LatLng( lat, lng );
map.getMyLocation(function(location) {
	plugin.google.maps.external.launchNavigation({
		from: location.latLng,
		to: destinationLatLng
        });
});
```

**Comment by Anopetia** [comment]
Same here.

**Comment by Anopetia** [comment]
Find a solution by using : https://github.com/dpa99c/phonegap-launch-navigator

This plugin is great and working fine.

**Comment by b4tch** [comment]
As I said, I have installed that plugin too - did you have to do anything in particular I may have missed to get it working? Thanks!

**Comment by b4tch** [comment]
A case of RTFM for me... thanks, Launch Navigator works great!
