### ISSUE TITLE
Trying to remove a polyline is failing...

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/cordova-plugin-googlemaps#1383]
<img width="1043" alt="screen shot 2017-04-03 at 2 47 53 pm" src="https://cloud.githubusercontent.com/assets/9216004/24629347/52fbcaf8-187e-11e7-92f0-b1b21bfe6021.png">
The polyline has 2 points but the call this.get('points').remove()  in Polyline.js is failing.  Any ideas?

**Comment by wf9a5m75** [comment]
It seems you execute the method as I designed. How do you execute the method? Please show me your code.

**Comment by KimberleeDArmstrong** [comment]
for (var key in googleMap.OVERLAYS) {
	if (googleMap.OVERLAYS[key].markerType == 'disconn') {
		googleMap.OVERLAYS[key].remove();
	}
}

**Comment by KimberleeDArmstrong** [comment]
This is the code that creates the polyline...
function getLines(type, tablename, threephase) {

	var whereClause = " AND phase != 'ABC'";
	if (threephase) {
		whereClause = " AND phase = 'ABC'";
	}
	var sql = "SELECT * from "+tablename+" p WHERE st_intersects(ST_Transform(ST_GEOMFROMTEXT('POLYGON(("+
	NorthEast.lng+" "+NorthEast.lat+", "+
	NorthEast.lng+" "+SouthWest.lat+", "+
	SouthWest.lng+" "+SouthWest.lat+", "+
	SouthWest.lng+" "+NorthEast.lat+", "+
	NorthEast.lng+" "+NorthEast.lat+"))',4326),"+params.Utility_Srid+"), GEOMETRY) = 1 "+whereClause+" AND "+
	"p.ROWID IN (SELECT ROWID FROM SpatialIndex WHERE f_table_name = '"+tablename+"' AND search_frame ="+
	"ST_Transform(ST_GEOMFROMTEXT('POLYGON(("+
	NorthEast.lng+" "+NorthEast.lat+", "+
	NorthEast.lng+" "+SouthWest.lat+", "+
	SouthWest.lng+" "+SouthWest.lat+", "+
	SouthWest.lng+" "+NorthEast.lat+", "+
	NorthEast.lng+" "+NorthEast.lat+"))',4326),"+params.Utility_Srid+"));";
	g_db.executeSql(sql, [],
	function(results) {		
		var myrows = [];
		for (var i = 0 ; i < results.rows.length ; i++){
			myrows[i] = results.rows.item(i);
		}
		$.each(myrows, function(i,m) {
			//disconn_markers[type]={data:results.rows.item(i)};
			var strokeWeight = 1;
			if (m.enettype == 'PL'){
				strokeWeight = 2;
			}
			if (m.enettype == 'PL' && m.phase == 'ABC'){
				strokeWeight = 3;
			}
			var content ='<button class="ui-btn ui-btn-a ui-btn-icon-right ui-icon-forbidden" onclick="javascript:reportDamage(i,\''+m.enettype+'\');">Report Damage</button>';
			var line = [];
			var json = JSON.parse(m.json_string);
			for (var j = 0 ; j < json.coordinates.length ; j++){
				line.push(new plugin.google.maps.LatLng(json.coordinates[j][1], json.coordinates[j][0]));
			}
			//var gdistance = plugin.google.maps.geometry.spherical.computeDistanceBetween ( start, stop )*3.28084+" ft.";	
			var infoWindow = new plugin.google.maps.InfoWindow();
			googleMap.addPolyline({
				points: line,
				color: "#00FF00",
				strokeOpacity: 0.6,
				width: strokeWeight,
				geodesic: true,
				clickable: true,
				zIndex: 97
			}, function(marker) {
				disconn_markers[m.enettype][index]={};
				marker.KAmarkerType = 'disconn';
				disconn_markers[m.enettype][index].marker=marker;
				disconn_markers[m.enettype][index].data = m;
				disconn_markers[m.enettype][index].marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
					mapMovedToPopInfoWindow = true;
					this.showInfoWindow();
				});
			});
		});
	},
	function(err) {
		$("#waiting").hide();
		alert("Failed to find equipment. "+JSON.stringify(err));
	});

	
}

**Comment by wf9a5m75** [comment]
Regarding of the variable `googleMap`, do you access internal property of the plugin? If no, it's not recommended.

**Comment by KimberleeDArmstrong** [comment]
I was doing this...
for (var key in disconn_markers) {
			//console.log(key+" has "+disconn_markers[key].length+" markers");
			for (var idx= 0 ; idx < disconn_markers[key].length ; idx++) {
				try {
					disconn_markers[key][idx].marker.hideInfoWindow();
					disconn_markers[key][idx].marker.remove();
				}catch(ex) {
					console.log(ex.message+" / "+key+" / "+idx);
				}
			}
			//console.log("Removed "+i+" markers for "+key);
		}
		disconn_markers = {'SUB':[],'FDR':[],'FUSE':[],'REC':[],'SEC':[],'CAP':[],'SW':[],'TRN':[],'STEP':[],'PL':[],'PL3':[],'SL':[],'MTR':[],'POLE':[]};

But I noticed it was not removing the markers from googleMaps.OVERLAYS.   However when I removed the markers using googleMaps.OVERLAYS object it was removing them.  When I added polylines I started getting this error.

I will change it back and see.

**Comment by wf9a5m75** [comment]
If you want to remove particular overlays (polyline, markers ..etc), using eventListener is better than for loop.

```js
function onMarkerDisconn() {
  var marker = this;
  marker.remove();
}

markerListData.forEach(function(markerParams) {
  map.addMarker(markerParams, function(marker) {
    map.on("disconn", onMarkerDisconn.bind(marker) );
  });
});


// Your timing
setTimeout(function() {
  map.trigger("disconn");
}, 10000);

```

**Comment by KimberleeDArmstrong** [comment]
Excellent.  Thank you.  I will try that.

**Comment by KimberleeDArmstrong** [comment]
I made the changes you recommended or at least attempted to.  I am back to getting the original error.

function mapMoved() {   // This is called on plugin.google.maps.event.CAMERA_MOVE_END
	if (mapMovedToPopInfoWindow) {
		mapMovedToPopInfoWindow = false;
		return;
	}
	if (hasSpatialDB) {
		//disconn_markers = {'SUB':[],'FDR':[],'FUSE':[],'REC':[],'SEC':[],'CAP':[],'SW':[],'TRN':[],'PL':[],'PL3':[],'SL':[],'MTR':[],'POLE':[]};
		googleMap.trigger("removeDisconnectedMarkers");
		disconn_markers = {'SUB':[],'FDR':[],'FUSE':[],'REC':[],'SEC':[],'CAP':[],'SW':[],'TRN':[],'STEP':[],'PL':[],'PL3':[],'SL':[],'MTR':[],'POLE':[]};
	}
	if (navigator.connection.type == Connection.NONE && hasSpatialDB) {
		//$("#mapheader h1").html(appname+' Map&nbsp;<span style="color:red;">(OFFLINE)</span>');
		clearTimeout(map_refresh_timer);
		disconnectedMapMoved();
	}else{
		if (localStorage.getItem('ckbx_PrimaryLines') !== 'false') {
			addPrimLineLayer();
		}
		if (localStorage.getItem('ckbx_Weather') !== 'false') {
			addWeatherLayer();
		}
	}
}
/*----------------------------------------------------------------------------*/
function getLines(type, tablename, threephase) {

	var whereClause = " AND phase != 'ABC'";
	if (threephase) {
		whereClause = " AND phase = 'ABC'";
	}
	var sql = "SELECT * from "+tablename+" p WHERE st_intersects(ST_Transform(ST_GEOMFROMTEXT('POLYGON(("+
	NorthEast.lng+" "+NorthEast.lat+", "+
	NorthEast.lng+" "+SouthWest.lat+", "+
	SouthWest.lng+" "+SouthWest.lat+", "+
	SouthWest.lng+" "+NorthEast.lat+", "+
	NorthEast.lng+" "+NorthEast.lat+"))',4326),"+params.Utility_Srid+"), GEOMETRY) = 1 "+whereClause+" AND "+
	"p.ROWID IN (SELECT ROWID FROM SpatialIndex WHERE f_table_name = '"+tablename+"' AND search_frame ="+
	"ST_Transform(ST_GEOMFROMTEXT('POLYGON(("+
	NorthEast.lng+" "+NorthEast.lat+", "+
	NorthEast.lng+" "+SouthWest.lat+", "+
	SouthWest.lng+" "+SouthWest.lat+", "+
	SouthWest.lng+" "+NorthEast.lat+", "+
	NorthEast.lng+" "+NorthEast.lat+"))',4326),"+params.Utility_Srid+"));";
	g_db.executeSql(sql, [],
	function(results) {		
		var myrows = [];
		for (var i = 0 ; i < results.rows.length ; i++){
			myrows[i] = results.rows.item(i);
		}
		$.each(myrows, function(i,m) {
			//disconn_markers[type]={data:results.rows.item(i)};
			var strokeWeight = 1;
			if (m.enettype == 'PL'){
				strokeWeight = 2;
			}
			if (m.enettype == 'PL' && m.phase == 'ABC'){
				strokeWeight = 3;
			}
			var content ='<button class="ui-btn ui-btn-a ui-btn-icon-right ui-icon-forbidden" onclick="javascript:reportDamage(i,\''+m.enettype+'\');">Report Damage</button>';
			var line = [];
			var json = JSON.parse(m.json_string);
			for (var j = 0 ; j < json.coordinates.length ; j++){
				line.push(new plugin.google.maps.LatLng(json.coordinates[j][1], json.coordinates[j][0]));
			}
			//var gdistance = plugin.google.maps.geometry.spherical.computeDistanceBetween ( start, stop )*3.28084+" ft.";	
			var infoWindow = new plugin.google.maps.InfoWindow();
			googleMap.addPolyline({
				points: line,
				color: "#00FF00",
				strokeOpacity: 0.6,
				width: strokeWeight,
				geodesic: true,
				clickable: true,
				zIndex: 97
			}, function(marker) {
				googleMap.on("removeDisconnectedMarkers", removeDisconnectedMarkers.bind(marker));
				disconn_markers[m.enettype][index]={};
				disconn_markers[m.enettype][index].marker=marker;
				disconn_markers[m.enettype][index].data = m;
				disconn_markers[m.enettype][index].marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
					mapMovedToPopInfoWindow = true;
					this.showInfoWindow();
				});
			});
		});
	},
	function(err) {
		$("#waiting").hide();
		alert("Failed to find equipment. "+JSON.stringify(err));
	});

	
}
/*----------------------------------------------------------------------------*/
function removeDisconnectedMarkers() {
	var marker = this;
	marker.remove();
}

**Comment by wf9a5m75** [comment]
I see. Could you show the result of this code?

```js
function removeDisconnectedMarkers() {
	var marker = this;
	console.log(marker);
        console.log(marker.get("points"));

}
```

**Comment by KimberleeDArmstrong** [comment]
<img width="1438" alt="screen shot 2017-04-03 at 5 09 29 pm" src="https://cloud.githubusercontent.com/assets/9216004/24633873/645ecaf4-1890-11e7-87b1-1c01f501e6a4.png">

**Comment by wf9a5m75** [comment]
Thanks. I see.

Please try to comment out this line. It should be fine.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Polyline.js#L168

**Comment by KimberleeDArmstrong** [comment]
I commented out that line.  The lines are not removed from the map.  After 3-4 pan or zooms the map freezes and the app crashes.. I see this in Xcode...
<img width="862" alt="screen shot 2017-04-04 at 8 47 27 am" src="https://cloud.githubusercontent.com/assets/9216004/24659897/a95f2a6c-1913-11e7-8b68-24f7c02a64fd.png">

**Comment by wf9a5m75** [comment]
Since I already fixed the issue that crash when you pan or zoom quickly, I close this issue.
