### ISSUE TITLE
Position of marker when clicked

### ISSUE THREAD

**Issue by b4tch** [mapsplugin/cordova-plugin-googlemaps#1384]
When a marker is clicked, it gets centered on the map.  Is there anyway to offset this position at all?

**Comment by wf9a5m75** [comment]
What is offset?

**Comment by b4tch** [comment]
So the marker is not positioned directly in the center of the screen, it is higher or lower than that (ideally specified by a number of pixels when initialised)

**Comment by wf9a5m75** [comment]
I couldn't understand what are you talking about. Could you draw a picture for me?

**Comment by KimberleeDArmstrong** [comment]
I would love this also. If I click the marker, I get this...
![cutoffinfowindow](https://cloud.githubusercontent.com/assets/9216004/24632478/df97aeb8-1889-11e7-9a04-840c97d7625f.PNG)

and have to scroll down to see full infoWindow.  I was going to make my info window wider to help with the issue.  But if we could specify an offset from center to pan to when clicked, it would be nice...
![notcutoffinfowindow](https://cloud.githubusercontent.com/assets/9216004/24632543/252b8a76-188a-11e7-965a-c9d17ef1549c.PNG)

**Comment by b4tch** [comment]
Perfect example, thanks Kimberlee, saved me a job!  Apologies for not explaining it better.

**Comment by wf9a5m75** [comment]
Ah, I see. 

You can do like this (I haven't tested this code, just idea) :

```js

map.addMarker({
  ...
  disableAutoPan: true,
  ...
}, function (marker) {

  marker.on(onMarkerClick);

});

function onMarkerClick(marker) {   //v1
   var marker = this;  // v2

   var x = mapDiv.offsetWidth() / 2;
   var y = mapDiv.offsetHeight() / 2;
   y += 100; // offset value what ever you want.

  marker.showInfoWindow();

  map.fromPointToLatLng([x, y], function(latLng) {
    map.animateCamera({
      position: latLng
    });
  });
}
```

**Comment by KimberleeDArmstrong** [comment]
Perfect!  Thanks.  I am happy.

**Comment by b4tch** [comment]
Appreciate your quick, helpful reply.  Unfortunately when I use animateCamera (or moveCamera) I experience a fatal crash, like in this thread: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1353 - Do you have any idea why this may be?

In case anyone else is attempting to use the above code, there are a couple of changes required - offsetWidth and offsetHeight are properties, not methods, and animateCamera takes a 'target', not a 'position'.  Here's the amended code, hopefully it will help someone that the animateCamera bug does not affect:

```
map.addMarker({
  ...
  disableAutoPan: true,
  ...
}, function (marker) {

  marker.on(onMarkerClick);

});

function onMarkerClick(marker) {   //v1
   var marker = this;  // v2

   var x = mapDiv.offsetWidth / 2;
   var y = mapDiv.offsetHeight / 2;
   y += 100; // offset value what ever you want.

  marker.showInfoWindow();

  map.fromPointToLatLng([x, y], function(latLng) {
    map.animateCamera({
      target: latLng
    });
  });
}
```

**Comment by b4tch** [comment]
Ok, I seem to have "fixed" the fatal error issue - the latLng returned by fromPoinToLatLng was in the format 51.923489238243,0.1343029230909 - apparently too many decimal places for animateCamera to handle.  By using toFixed(6) on each of the latLng elements, the map now moves... only to the wrong place!   The map just seems to move the y coord up by the same amount every time. Maybe you could tell me if I'm doing something silly?

```
var x = mapDiv.offsetWidth / 2;
var y = mapDiv.offsetHeight / 2; // half way
y -= mapDiv.offsetHeight / 4; // 25% down the page

map.fromPointToLatLng( [x, y], function(latLng) {
	var destinationLatLng = new plugin.google.maps.LatLng( latLng[0].toFixed(6), latLng[1].toFixed(6) );
	map.animateCamera({
		target: destinationLatLng,
		zoom: 10,
		duration: 1000
	});
});
```

**Comment by wf9a5m75** [comment]
Maybe 

```js
y -= mapDiv.offsetHeight / 4; // 25% down the page
```

to

```js
y += mapDiv.offsetHeight / 4; // 25% down the page
```

**Comment by b4tch** [comment]
I figured it out, thanks for your help again, and your excellent plugin.  Do you have a donation link?

**Comment by wf9a5m75** [comment]
@b4tch Congratulation 👍  

And thank you for offering donation. You can donate any amount from here. (Donate/Paypal button)
https://github.com/mapsplugin/v2.0-demo#buy-me-a-beer
