### ISSUE TITLE
Add style to map using Ionic 2 plugin

### ISSUE THREAD

**Issue by SoldierCorp** [mapsplugin/cordova-plugin-googlemaps#1390]
Hello,

Could you please help me how to set a style to my map declared with Ionic?

`let element: HTMLElement = document.getElementById('map');`
`let map: GoogleMap = this.googleMaps.create(element);`

I'm trying with this but is not working

`
map.setOptions({
        styles:[{...}]
`

Thanks!

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1180#issuecomment-261125046
