### ISSUE TITLE
Side menu options and buttons on the map do not work with Google Maps Native

### ISSUE THREAD

**Issue by MariaC15** [mapsplugin/cordova-plugin-googlemaps#1391]
Hi.!

I'm using Google Maps native Ionic. I can easily show the map in my application, I have a side menu (shown in the header of the screen) opens well, but the menu options do not work when you click, I also have other buttons on the map that do not work either.

Ionic plugins list
Cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin"
Ionic info
Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
Ios-deploy version: 1.9.0
Ios-sim version: 5.0.13
OS: OS X The Captain
Node Version: v6.9.1
Xcode version: Xcode 7.2 Build version 7C68

Will I be doing something wrong? Or forgetting something?
Please help.!
Thank you

**Comment by wf9a5m75** [comment]
If you use the plugin v1 (I think so), you need to execute `map.setClickable(false)` when the sidemenu is open.
Then when close the sidemenu, you need to execute `map.setClickable(true)`

**Comment by MariaC15** [comment]
I try to upgrade to V2 and still install V1.

I carry out the following steps

Ionic plugin rm plugin.google.maps

Ionic plugin rm com.googlemaps.ios

Ionic plugin add cordova-plugin-googlemaps --variable
API_KEY_FOR_ANDROID = "YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS = "YOUR_IOS_API_KEY_IS_HERE"

And no luck installing the V2, I have OS: OS X The Captain installed
Will I be doing something wrong? Or forgetting something?

**Comment by wf9a5m75** [comment]
```
Ionic plugin rm plugin.google.maps

Ionic plugin rm com.googlemaps.ios

cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/multiple_maps  --variable ...
```

**Comment by MariaC15** [comment]
Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/multiple_maps via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 128 Error output:
Cloning into '/tmp/git/1491423054861'...
remote: Not Found
fatal: repository 'https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/multiple_maps/' not found

**Comment by wf9a5m75** [comment]
oh #multiple_maps instead of /tree/multiple_maps

**Comment by MariaC15** [comment]
Still not working

cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="api_key" --variable API_KEY_FOR_IOS="api_key"
Password:
Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps" via git clone
Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps via git.
Either there is a connection problems, or plugin spec is incorrect:
Error: git: Command failed with exit code 128 Error output:
Cloning into '/tmp/git/1491426726801'...
error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by wf9a5m75** [comment]
It seems your git or cordova command has problem. It's not plugin problem.

**Comment by lampofdrog** [comment]
@MariaC15 hi , have u find any solution for this issue ??

**Comment by ItzGaurav** [comment]
hi,
I am getting the same issue, Let me know if anyone have solution for the same.
