### ISSUE TITLE
no match found

### ISSUE THREAD

**Issue by AsimNet** [mapsplugin/cordova-plugin-googlemaps#1395]
Hello

when I run this command to install V2 beta : 
```
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_
FOR_ANDROID="AIz" --variable API_KEY_FOR_IOS="AIz"
```

it gives me this output error: 
```
no matches found: https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
```

**Comment by wf9a5m75** [comment]
The issue of plugin installing is your problem depends on your environment.
Unfortunately I can not help you at all. Too less information.

**Comment by AsimNet** [comment]
still this is a visible problem.. i'm working on ionic3 now
`
ionic info:
`

```
cli packages: (/Users/user/project/node_modules)

    @ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.0
    ios-sim    : 5.0.13
    Node       : v8.2.1
    npm        : 5.3.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.0 Build version 8A218a
```

**Comment by AsimNet** [comment]
![screen shot 2017-08-26 at 11 56 54 pm](https://user-images.githubusercontent.com/3624441/29745053-4ed751aa-8aba-11e7-8d71-50cd0b89e617.png)

**Comment by wf9a5m75** [comment]
Remove the lines of cordova-plugin-googlemaps from config.xml, package.json and package-lock.json files.

Or you should create an empty project, then try it.

This is completely your environment problem.

**Comment by AsimNet** [comment]
thanks, that worked with me.
but now:
![screen shot 2017-08-27 at 12 25 06 am](https://user-images.githubusercontent.com/3624441/29745249-5db4165a-8abe-11e7-99c4-07a8ac67e910.png)

**Comment by wf9a5m75** [comment]
```
$> chmod +x platforms/android/gradlew
```

**Comment by AsimNet** [comment]
even aftre running the command above, the problem still there.

note:
i'm using firebase plugins
here's a peak of dependancies in build.gradle:
```
compile "com.google.firebase:firebase-core:+"
    compile "com.google.firebase:firebase-messaging:+"
    compile "com.google.firebase:firebase-crash:+"
    compile "com.google.firebase:firebase-config:+"
    compile "com.google.android.gms:play-services-maps:+"
    compile "com.google.android.gms:play-services-location:+"
```  

@wf9a5m75

**Comment by AsimNet** [comment]
I found that this problem caused by [fcm plugin](http://ionicframework.com/docs/native/fcm/)

thanks again
@wf9a5m75
