### ISSUE TITLE
Application rejected on Apple Store caused by Google Maps

### ISSUE THREAD

**Issue by anouvel** [mapsplugin/cordova-plugin-googlemaps#1397]
Hey everybody!

I previously have submitted my app to the Apple Store (a month ago) and it was approved, but I want to submit a new release and the app is rejected because of:

```
Your app's location feature is still not integrated with the built-in mapping functionality, which limits users to a third-party maps app.
```

My app is an ionic 2 one, with the following plugins for geolocation:

```
com.googlemaps.ios 2.1.1 "Google Maps SDK for iOS"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin"
```

The process of the app is pretty simple, one view for signin/signup, and when the user is registered, the application launch a google maps with a bottom navigation bar. I see some resources about google maps issues, but they said it is fix on the version 1.13..., but I'm using the 2.1.1 version, so I need help!

Thank you (for the plugin ;)) and for your support

Adrien

**Comment by wf9a5m75** [comment]
As far as I know, Google Maps SDK and this plugin do not use limited features of iOS.
Any comments more than "Your app's location feature is still not integrated with the built-in mapping functionality, which limits users to a third-party maps app."
It's too less information.

**Comment by anouvel** [comment]
Thank you for your reply,

Here is the full Apple comment, which does not give more information:

```
4. Design: Preamble
Design Preamble

Your app's location feature is still not integrated with the built-in mapping functionality, which limits users to a third-party maps app.

Please see the attached screenshot for details. (<- the attachment is just a screenshot of my app)

Next Steps

To resolve this issue, please revise your app to give users the option to launch the native Apple Maps app.
```

Thanks

**Comment by wf9a5m75** [comment]
> Please see the attached screenshot for details. (<- the attachment is just a screenshot of my app)

Please attach also this one.

**Comment by anouvel** [comment]
![attachment-8864705930819577681screenshot-0411-154047](https://cloud.githubusercontent.com/assets/8018172/24969307/a5e910a2-1fb0-11e7-8deb-05afeb2a9c04.png)

**Comment by msio777** [comment]
I have similar page with google maps and I'm planning to push it on app store soon, I'd like to hear more of this issue.
Thanks for any update @anouvel

**Comment by wf9a5m75** [comment]
http://stackoverflow.com/questions/36167212/my-application-was-rejected-due-to-google-maps

**Comment by wf9a5m75** [comment]
they say: "to give users the option to launch the native Apple Maps..."

**Comment by wf9a5m75** [comment]
> After making phone call, reviewer said that using only GMSMapView is the reason for rejection and MKMapView should be given as an option to show coordinates. I used only GMSMapView in my app and they rejected it just for that! There is no written rule for this rejection. It is totally ridiculous.

http://stackoverflow.com/a/41771669/697856

Wow, if it's true, it's really ridiculous.

**Comment by wf9a5m75** [comment]
I discussed with my expert friends. They suggested you should try to submit your application again, because the result of Apple validation is really depends on the person who inspected your app.

**Comment by anouvel** [comment]
Hi!

In fact that's what I did yesterday morning, "just to try", and they reply me a few hours ago, they rejected it at the beginning, I wrote them a message to explain what is my application, and why I can't / want to use the native Apple maps, and they just accept it, so it's okay for my release.

Thank you a lot @wf9a5m75, and @msio777 good luck!

**Comment by wf9a5m75** [comment]
Sounds great! 👍

**Comment by msio777** [comment]
thanks man @anouvel I appreciate your help 👍
