### ISSUE TITLE
Scaled Icon

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1399]
in the scaled icon code
i see this #iconPercent ?
what is refer to ?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#scaled-icon

**Comment by bigbossmaher** [comment]
what i should put in #iconPercent id ?

**Comment by wf9a5m75** [comment]
```js
marker.setIcon({
      'url': 'images/icon-yellow.png',
      'size': {
        width: 30,
        height: 30 // in pixels
      }
    });
```

**Comment by bigbossmaher** [comment]
is this code will make icons small , and they will be bigger when zoom in ?

**Comment by wf9a5m75** [comment]
Both work, but I recommend this feature uses for make smaller size.
