### ISSUE TITLE
V2 question

### ISSUE THREAD

**Issue by dukhanov** [mapsplugin/cordova-plugin-googlemaps#1401]
Hi,
V2 supports multiple maps, 
but what if I want to use just one instance of the map?

for example:
I have different views, but I want to use the same instance of the map on different views.
I case I leave the view, and all HTML of this view was removed, 
On the different view, I want to display the same map, 
I call:
```map.setDiv(someDiv)```
but nothing happens.

How to use one instance of the map on different views?

**Comment by dukhanov** [comment]
Moreover, if you call ```setDiv``` and the map is displayed the app crashes

**Comment by wf9a5m75** [comment]
This plugin does not support for your case.
The reason of crash is the target html element is null because you removed everything.

**Comment by dukhanov** [comment]
Is it possible to implement?
I can do it by myself, just show me the way :)

**Comment by wf9a5m75** [comment]
Fork this repository, then modify it by yourself please.

The v1 code is designed for controlling by developer everything. Actually the v1 code allows your case. But most of all Javascript developers feel kind of difficult.

The v2 code is designed for automatic detecting. So if the target html element is removed, the map is also removed.

It's depends on your skill level.

**Comment by dukhanov** [comment]
Do you support V1, in case I have some PR for V1, 
Will you manage to merge it into V1?

**Comment by wf9a5m75** [comment]
No. Your case is very rare case.

Most of all JavaScript developers want map is removed when the target html element is removed at the same time.
Only one exception (you) want to keep the map in the last three years.

**Comment by dukhanov** [comment]
No, I mean in common
If I have some new other feature for V1, will you manage to merge it into V1?

**Comment by wf9a5m75** [comment]
The v1 is cold version. No more improved.
Please develop new feature for v2.
