### ISSUE TITLE
Kml Overlay from string

### ISSUE THREAD

**Issue by philipgriffin** [mapsplugin/cordova-plugin-googlemaps#1402]
Hi,

I have a scenario where my kml file is a string.. for example..

`var myKMLString = "<?xml version='1.0' encoding='UTF-8'?><kml xmlns='http://www.opengis.net/kml/2.2'><Document></Document></kml>"`

and I am trying to use the `addKmlOverlay({'url': myKMLString});`

I understand that it does not accept a string but can you tell me how I might get this to work?

Possibly by converting the string to something else first?

Thanks!

**Comment by wf9a5m75** [comment]
There is no plan to support for this usage.

**Comment by philipgriffin** [comment]
I understand. 

But is there a way to convert my string to a file and get it to read the kml?

**Comment by wf9a5m75** [comment]
Maybe this?
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html

Then specify the file url as `file://`
