### ISSUE TITLE
Infowindows

### ISSUE THREAD

**Issue by ran-j** [mapsplugin/cordova-plugin-googlemaps#1403]
There is a way to create a custon infowindo like  [This](https://trello-attachments.s3.amazonaws.com/5814e91b79cc6f342ad96117/58a79aae41cc56545198a5d1/60b276c090c4bbf9d2988da4a17f9850/Balao_Voce_esta_aqui.png), or anything like this ?

**Comment by wf9a5m75** [comment]
In the plugin v2, you may create InfoWindow like this

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/InfoWindow.js

**Comment by ran-j** [comment]
Whats the difference between corrent version and the V2 ?

**Comment by wf9a5m75** [comment]
Read here.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

**Comment by ran-j** [comment]
which one I change the color ?

This one ? 

`contentFrame.style.backgroundColor = "white";`

**Comment by wf9a5m75** [comment]
I added `setBackgroundColor()` method for HtmlInfoWindow class (renamed from: InfoWindow class).
Check out here.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/HtmlInfoWindow/setBackgroundColor/README.md

**Comment by ran-j** [comment]
Thanks
