### ISSUE TITLE
Performance Issue when using iconView

### ISSUE THREAD

**Issue by glussian-luna** [mapsplugin/cordova-plugin-googlemaps#1404]
CPU Usage is very high ( > 70% ) as soon as iconView is used in conjonction with tracksViewChanges = true which seams to be the only way to do animation on a marker.

The simplest way to demonstrate the issue is to use the GoogleMapDemo/UIView Markers . CPU reaches 68% on iPhone 7 Plus to make this very simple effect ;-(...

**Comment by wf9a5m75** [comment]
Excuse me, but what are you talking about? What is iconView? GoogleMapDemo/UIView is not related with this plugin.
