### ISSUE TITLE
Map Camera moves after clicking a Marker

### ISSUE THREAD

**Issue by logicalThinker91** [mapsplugin/cordova-plugin-googlemaps#1405]
Hi,

First of all, thanks for the amazing project!

I am trying to make it so when an user clicks a Map Marker, the Maps Camera does not move to be centered over the clicked Marker. Is that possible?

Thank you,
Shane.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#disable-auto-pan

**Comment by logicalThinker91** [comment]
Thank you @wf9a5m75 !!!

Somehow I missed that when I went over the Documentation like 6 times! I am sorry I missed it!

Thanks again,
Shane.
