### ISSUE TITLE
iOS click issue - button over map

### ISSUE THREAD

**Issue by pooi-pooi** [mapsplugin/cordova-plugin-googlemaps#1406]
Hello guys,
I have a map with two "inputs" on it. I used a button as an input and on its click a modal is displayed.
This was an alternative to clicking issues on elements that are on the map `1.4.0`.

```html
<ion-view ng-controller="OriginController as vm" >
  <ion-content scroll="false">
    <div id="map-origin" class="map">
      <map-address></map-address>
    </div>
  </ion-content>
</ion-view>
```

```html
<div class="map-address">
  <form autocomplete="off">
      <div class="row">
        <div class="col col-90" style="position: relative;">
          <button class="button button-clear" ng-click="vm.openModal('origin')"><span ng-bind="geolocation.origin.value"></span></button>
        </div>
      </div>
      <div class="row">
        <div class="col col-90" style="position: relative;">
          <button class="button button-clear" ng-click="vm.openModal('destination')"><span ng-bind="geolocation.destination.value"></span></button>
        </div>
      </div>
  </form>
</div>
```

I can click these buttons most of the time.
But in just a few devices - **iOS** - , this doesn't work.

I'm not using `data-tap-disabled="true"` or `ng-touch`, just `ng-click` (ionic 1).

Do you have any idea what I can do to solve it?

**Comment by wf9a5m75** [comment]
Maybe you forgot to execute `map.refreshLayout()`?

**Comment by pooi-pooi** [comment]
I do `map.refreshLayout()` right on the `MAP_READY` event

```js
/* ... */
map.addEventListener(plugin.google.maps.event.MAP_READY, function() {
    $timeout(function() {
        map.clear();
        map.refreshLayout();
        init(); // here I define my modals
    });
});
```

```js
function init() {
   $ionicModal.fromTemplateUrl('templates/modalOrigin.html', {
      scope: $scope,
      animation: 'slide-in-up'
    }).then(function(modal) {
      $scope.modalOrigin = modal;
    });
}
```

**Comment by wf9a5m75** [comment]
```js
map.addEventListener(plugin.google.maps.event.MAP_READY, function() {
    $timeout(function() {
        map.clear();
        map.refreshLayout();
        init(); // here I define my modals
    });
});
```

This is no efficient at all.

`map.refreshLayout();` methods recalculate HTML element positions, so the method have to execute **after** HTML elements are inserted.

**Comment by pooi-pooi** [comment]
But would not this create a recurring problem?
I only had this problem on only two consumers.
Actually, I cannot even reproduce this problem in my emulators and devices.

**Comment by wf9a5m75** [comment]
>Actually, I cannot even reproduce this problem in my emulators and devices.

Please reproduce 100% this issue at your environment at first.

**Comment by pooi-pooi** [comment]
I will try to reproduce this and if I get the steps, I'll reopen this issue.
Thanks @wf9a5m75

**Comment by wf9a5m75** [comment]
Thank you for understanding.
