### ISSUE TITLE
Map (and app) crashing  on map drag or zoom change due to HTML infowindow

### ISSUE THREAD

**Issue by loama** [mapsplugin/cordova-plugin-googlemaps#1407]
Error iOS:

```
2017-04-18 13:46:41.736409-0500 Eiya[1791:534594] --->javascript:cordova.fireDocumentEvent('map_0_1203971324401', {evtName: 'syncPosition', callback: '_onSyncInfoWndPosition', args: [{x: 198.000000, y: 232.499985}]});
2017-04-18 13:46:41.953757-0500 Eiya[1791:534594] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x170642e20> was mutated while being enumerated.'
*** First throw call stack:
(0x190ce2fd8 0x18f744538 0x190ce2a28 0x1000a11a4 0x197102218 0x196e4b904 0x190bd1e24 0x190bd1d20 0x196e4b440 0x197102218 0x196e4b904 0x190bd1e24 0x190bd1d20 0x196e4b440 0x197102218 0x1970eaf44 0x196e16734 0x1970eae0c 0x1970eb150 0x197608618 0x19760b804 0x1976066c0 0x197606aec 0x190c91424 0x190c90d94 0x190c8e9a0 0x190bbed94 0x192628074 0x196e77130 0x10002fd88 0x18fbcd59c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
```

As far as I understand the device is trying to calculate the position of the infowindow but due to not being able to do it as fast as needed it crashes.

The problem does not seems to happen on Android.

**Comment by wf9a5m75** [comment]
>2017-04-18 13:46:41.953757-0500 Eiya[1791:534594] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x170642e20> was mutated while being enumerated.'

This error happens when you move the map during HTML elements are changed.

**Comment by loama** [comment]
yes, any idea on how to fix it?
It happens just by moving the map a little bit faster than normal.

**Comment by wf9a5m75** [comment]
@loama This is already fixed. Please reinstall the plugin, and test it.
