### ISSUE TITLE
Marker click triggers way after the click, and most of the time nothing happens

### ISSUE THREAD

**Issue by logicalThinker91** [mapsplugin/cordova-plugin-googlemaps#1408]
Hi,

This happen on the 2.0.0 beta.

The issue is when I click on any marker, sometimes the click triggers way after, but most of the time nothing happens.

Here is the code I have going on:

```
map.addMarker({
  position: {lat: lat, lng: lng},
  icon: imageData,
  zIndex: zIndex,
  disableAutoPan: true
}, function (markerRef) {
  markerRef.on(plugin.google.maps.event.MARKER_CLICK, function () {
    alert("clicked");
  });
  markerRef.addEventListener(plugin.google.maps.event.MARKER_CLICK, function () {
    alert("clicked");
  });
});
```

I know I have two ways of adding the click event, just showing each way I tried.

Am I doing something wrong?

Thanks,
Shane.

**Comment by wf9a5m75** [comment]
Please provide example apk file

**Comment by logicalThinker91** [comment]
I'll create an example and get back to you.

**Comment by logicalThinker91** [comment]
So I solved my original issue while creating the example APK. I had many markers next to each other, and the clickable markers had a lower zIndex then the non-clickable markers. I have no idea how I overlooked that when reviewing the issue. Sorry about that, I know your busy. Once I got all that figured out. I noticed that when you click a marker, the onClick event gets triggered, and if you click the same marker again without clicking anywhere else on the map, the onClick event will not trigger. Any suggestions on how to make a markers onClick event trigger every click, regardless of it was clicked last?

**Comment by wf9a5m75** [comment]
The plugin v2.0 supports the zIndex property for both Android and iOS.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/cf5c0b5e8d338e436bc434d00f55ac0bf581f310/src/android/plugin/google/maps/PluginMarker.java#L137-L139

And event listener is thin wrapper of native javascript event listener.
The plugin does not block anything.

**Comment by logicalThinker91** [comment]
My issue ended up being I had markers without click events next to markers with click events. This resulted in the markers with no click events being the ones sometimes clicked, which caused the markers with click events in the same location to not have its click event triggered. Thanks for your time. Keep up the good work!
