### ISSUE TITLE
Error GoogleMaps ionic-native

### ISSUE THREAD

**Issue by mserravalle92** [mapsplugin/cordova-plugin-googlemaps#1410]
I have an error when i try to instance GoogleMap. 
![image](https://cloud.githubusercontent.com/assets/12702310/25251953/940e5fee-25f1-11e7-9a30-90120e8b2877.png)

![image](https://cloud.githubusercontent.com/assets/12702310/25251967/acb65858-25f1-11e7-8e13-4a2c2e54406c.png)

if I remove the line "new GoogleMap()....." the app runs.

What is this problem??

I'm from Argentina. My English isn't so good. Sorry

**Comment by wf9a5m75** [comment]
Unfortunately I'm not familiar with ionic at all.

It seems the error says you did not install the `ionic-native`.
I guess you need to install this one.
https://www.npmjs.com/package/ionic-native

**Comment by fermedina** [comment]
@mserravalle92 are you install ionic-native/google-maps? If you see the oficial documentation you can see this command:

npm install --save @ionic-native/google-maps

**Comment by vosecek** [comment]
Use this import: import { GoogleMap, GoogleMapsEvent, MarkerOptions, Marker, LatLng } from '@ionic-native/google-maps';

**Comment by mserravalle92** [comment]
Thanks!. I solved the issue. The solution was like vosecek said.
The course that i was taking was Outdate. 

I repeat. I'm from Argentina. My English isn't so good. Sorry.
