### ISSUE TITLE
Non-clickable Marker

### ISSUE THREAD

**Issue by logicalThinker91** [mapsplugin/cordova-plugin-googlemaps#1413]
Is there any way to make a non-clickable Marker? Having an issue where if I have Markers close to each other, when I click on a Marker, it seems to rotate through the nearby Markers. So if I have 4 markers next to each other, and two of the markers have an onClick, and I click the spot that touches all 4 markers, 2 out of the 4 clicks will show the "marker clicked alert", and the other 2 will do nothing. Basically is there any way to stop this behavior? I know in the Google Maps Javascript V3 API, markers can have `clickable: false`, which solved this issue for me before I switched over to Google Maps Android V2 API.

**Comment by wf9a5m75** [comment]
```js
map.addMarker({
  clickable: false,
   ...
}, function(marker) {
  marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
    if (!marker.get("clickable")) {
      return;
    }
  });
});
```

**Comment by logicalThinker91** [comment]
Thanks for the quick awesome response! I forgot to mention I am working with the Version 2 Beta. Would the code example you just provided work on the Version 2 Beta?

**Comment by wf9a5m75** [comment]
The code should work.

**Comment by logicalThinker91** [comment]
I found a bug report on the Google Maps Android Version 2 API Issue Tracker about this issue. [Bug Report](https://issuetracker.google.com/issues/35823783) It was assigned to someone yesterday! Just have to wait for the fix now. Thanks for your help on this issue!
