### ISSUE TITLE
Help google maps v2 does not work on the side menu

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1414]
I installed the google maps v2. I have a menu which does not work when clicking on the icon, previously it worked.

**Comment by wf9a5m75** [comment]
Please make a simple  example that reproduce your issue 100%, then put it on a github repository with full code.

Don't share your full code of your app.

**Comment by wf9a5m75** [comment]
@wuilmerj24 I noticed some bugs of the plugin. Might be affected to your issue.
Please reinstall the plugin, and test it please.

**Comment by wf9a5m75** [comment]
ping
