### ISSUE TITLE
Failed to load Info.plist from bundle at path /Frameworks/GoogleMaps.framework

### ISSUE THREAD

**Issue by system65** [mapsplugin/cordova-plugin-googlemaps#1416]
when running the app on simulator :

Failed to load Info.plist from bundle at path /Users/OsamaAbdullah/Library/Developer/CoreSimulator/Devices/DF7791C1-2DB6-4B8B-8CED-8DE0B05BE3D6/data/Library/Caches/com.apple.mobile.installd.staging/temp.UfazAw/extracted/Payload/sakrobe.app/Frameworks/GoogleMaps.framework

any one help !

**Comment by wf9a5m75** [comment]
try to reinstall the sdk

https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk

**Comment by system65** [comment]
thanks, 

solved by :

`cordova platform remove ios`

and  

`cordova platform add ios`
