### ISSUE TITLE
How to use a function to animate marker to specified position?

### ISSUE THREAD

**Issue by AndreVicenteW** [mapsplugin/cordova-plugin-googlemaps#1417]
I found this pull https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/831 , but I didn't find a way to use it.

**Comment by wf9a5m75** [comment]
You can install the plugin from https://github.com/xming13/cordova-plugin-googlemaps

But the repository is too old.

**Comment by THEDOWNCOUNTRY** [comment]
I was taking a look at the code in the repository but I don't seem to find those files:

 <source-file src="src/android/plugin/google/maps/LatLngInterpolator.java" target-dir="src/plugin/google/maps" />
<source-file src="src/android/plugin/google/maps/MarkerAnimation.java" target-dir="src/plugin/google/maps" />

Included are they merge with other files?

**Comment by THEDOWNCOUNTRY** [comment]
+        <source-file src="src/android/plugin/google/maps/LatLngInterpolator.java" target-dir="src/plugin/google/maps" />
+        <source-file src="src/android/plugin/google/maps/MarkerAnimation.java" target-dir="src/plugin/google/maps" />

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/utilities/geometry/spherical/interpolate/README.md

**Comment by THEDOWNCOUNTRY** [comment]
Thank you very much.
