### ISSUE TITLE
Add map of city or even country to save bandwidth

### ISSUE THREAD

**Issue by tuliogalli** [mapsplugin/cordova-plugin-googlemaps#1427]
Good afternoon

Is there any way to "add the map" to the default installation of an entire city or even a country? To save as much as 3g or bandwidth usage by google maps?

thank you

**Comment by wf9a5m75** [comment]
no

**Comment by tuliogalli** [comment]
Thank you very much for your attention.

**Comment by tuliogalli** [comment]
Alias, would you have any other solution that would recommend me? I use ionic.

**Comment by wf9a5m75** [comment]
No I haven't.
