### ISSUE TITLE
Ionic 2.x, plugin beta, map does not work, frozen

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#1430]
With Ionic 2.x and current branch #multiple_maps the map does not work.

map.ts file
```
declare var plugin:any;
@ViewChild('mapdiv') mapdiv: ElementRef;

constructor(public navCtrl: NavController, private platform: Platform) {
		platform.ready().then(() => {
                    var map = plugin.google.maps.Map.getMap(this.mapdiv.nativeElement);
		});
	}
```

map.html file
```
<ion-content>
    <div #mapdiv id="mapdiv" style='height:100%'>
    </div>
</ion-content>
```

The map is created, but does not react on click, pinch, zoom etc. Even my location button does not react.

Does anyone have positive experience with current beta branch on iOS?

**Comment by wf9a5m75** [comment]
Maybe this one helps you?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1429#issuecomment-298769652

**Comment by robhoefakker** [comment]
This is caused by `.nav-decor`. The quick fix that works for me is adding the following css:

```css
ion-app._gmaps_cdv_ .nav-decor{
  background-color: transparent!important;
  display:none!important;
}
```

@wf9a5m75 I have some sample code for using the beta on a blank Ionic 3 project do you want me to add it somewhere in the documentation?

**Comment by wf9a5m75** [comment]
@robhoefakker Thanks for helping.

>I have some sample code for using the beta on a blank Ionic 2( latest version 3.1.1) project do you want me to add it somewhere in the documentation?

Yes, I appreciate for your help. Could you send me a pull request for this repository?

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0

**Comment by vosecek** [comment]
@robhoefakker thanks man. Updated documentation for Ionic users will save a lot of time for others :)

**Comment by robhoefakker** [comment]
@wf9a5m75 I've send a pull request :)

**Comment by wf9a5m75** [comment]
@robhoefakker Thanks for your help

**Comment by MMokhtari** [comment]
Hey guys I have the same issue and none of the solution I've found seems to work 
I'm using :
apache cordova@7.0.1
ionic@3.1.1
cordova android@6.2.3
any ideas  please ?

**Comment by vosecek** [comment]
@MMokhtari try to downgrade apache cordova to 6.x version, 7.x is pretty new version. And also upgrade ionic to 3.3.0.

**Comment by MMokhtari** [comment]
I have now apache cordova@6.5 installed and ionic@3.3.0 and no success 
what version they work for you @vosecek ?

**Comment by vosecek** [comment]
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
```
I do not use Ionic Wrapper, map is created via plugin.google.maps.Map.getMap();

map.scss
```
ion-app._gmaps_cdv_ .nav-decor {
    background-color: transparent!important;
    display: none!important;
}
```

and inside MAP_READY event:
```
setTimeout(() => {
    cordova.fireDocumentEvent('plugin_touch', {});
}, 500);
```

**Comment by robhoefakker** [comment]
Try to follow the tutorial with a blank app starter. https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md Let me know if it works with these steps.

**Comment by MMokhtari** [comment]
@vosecek  I tried your versions but with no success 
@robhoefakker tried a blank project but  the issue is still on The map is generated but you can't interact with it (tested in android 7 and 5 )
here is my env 
![info](https://cloud.githubusercontent.com/assets/9805952/26800455/0bdc3e46-4a42-11e7-99ee-5fc105234760.jpg)

**Comment by MMokhtari** [comment]
Hey guys its working now I had to remove the platform and plugin and reinstall them again
and with Cordova 7 and ionic 3.3.0
Thanks for your help
Cheers
