### ISSUE TITLE
Can't change page from marker click

### ISSUE THREAD

**Issue by laughinglion** [mapsplugin/cordova-plugin-googlemaps#1437]
My cordova app uses Angular for page routing, e.g. $location.path('/accounts'); to change route and load a new page.
When I add the above command inside the click handler for a marker the command does get fired but nothing happens, I don't even see an error message. I've tried passing $location to the marker as data but did not help either.  Guessing that scope is somehow involved but can't figure it out. Any suggestions?

**Comment by wf9a5m75** [comment]
You need to use the plugin v2.
