### ISSUE TITLE
Click marker doesn't work on iOS, custom marker icon doesn't show neither

### ISSUE THREAD

**Issue by ferminako** [mapsplugin/cordova-plugin-googlemaps#1438]
Hi,

On android it works, but I don't know why on ios that tap/click doesn't fire the function attached to the marker.
 ```
this.pits.forEach((item, index) => {
            let a = new GoogleMapsLatLng(item.latitud, item.longitud);
            let am: GoogleMapsMarkerOptions = {
                position: a,
                //icon:"www/assets/images/markers/map-marker-pit.png",
            };
            this.map.addMarker(am)
            .then((marker: GoogleMapsMarker) => {
                console.log('adding  pit marker');
                marker.addEventListener(GoogleMapsEvent.MARKER_CLICK)
            .subscribe(e => {
                console.log('you hit a pit marker');
               this.openPageContenido(item);
            });

            });

        });
        openPageContenido(pit:any){
          console.log('OPENPAGECONTENIDO');
          let cl= new ContenidoList(pit.id,pit.nombre,"");
          this.navCtrl.push( ContenidoPage, {"contenidoList": cl});
       }

```
So running "ionic run ios -lc" I can see for each marker -> adding pit marker
And the map shows all the markers, but If I tap one of them, there is no console log nor openPageContenido is fired.

Any idea?

Btw, I had to add:
```

.nav-decor{
     display:none!important;
   }
```
In order to be able to see he map, because otherwise a black screen is over the map.
And I don't know why, my custom markers are not displayed, I tried with different urls but no one worked. Meanwhile I leave them without my custom icon.

I'm using de v2 because in ios I couldn't install the v1 (https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1436)

**Comment by wf9a5m75** [comment]
If you use the plugin v2, you can NOT use the ionic wrapper.

**Comment by ferminako** [comment]
ok, so how do I should do it?

**Comment by ferminako** [comment]
Could you please show me an example of how should I do it?
I've seen https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md
But I can't do 

` var map = plugin.google.maps.Map.getMap(mapDiv, {...`
Because I don't know what is plugin due that I'm used to work with ionic wrapper.

Thanks

**Comment by wf9a5m75** [comment]
For v2, read here
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0

**Comment by wf9a5m75** [comment]
And there is a basic example for ionic user
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md#how-to-install-the-cordova-googlemaps-plugin-v2-beta-on-ionic-2

**Comment by wf9a5m75** [comment]
By the way, there was a bug in the iOS version of the plugin v2.
The bug is already fixed.
Please reinstall the plugin with `--nofetch` option.

Thanks

**Comment by ferminako** [comment]
Hi @wf9a5m75, I've reinstalled the plugin and tried the example code but I get this error when I try:
`this.map = new plugin.google.maps.Map.getMap(mapEle, {});`
`console.error: EXCEPTION: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'new 
            plugin.google') loadMap@http://192.168.1.196:8100/build/main.js:87449:30 
            cargarMarkers@http://192.168.1.196:8100/build/main.js:87401:21 
            getCurrentPosition@http://192.168.1.196:8100/build/main.js:87381:27 
            http://192.168.1.196:8100/build/main.js:87375:37 onInvoke@http://192.168.1.196:8100/build/main.js:39146:43 
            run@http://192.168.1.196:8100/build/polyfills.js:3:7025 http://192.168.1.196:8100/build/polyfills.js:3:4664 
            invokeTask@http://192.168.1.196:8100/build/polyfills.js:3:10289 
            onInvokeTask@http://192.168.1.196:8100/build/main.js:39137:47 
            invokeTask@http://192.168.1.196:8100/build/polyfills.js:3:10232 
            runTask@http://192.168.1.196:8100/build/polyfills.js:3:7647 
            i@http://192.168.1.196:8100/build/polyfills.js:3:3714 promiseReactionJob@[native code] 
[08:55:56]  console.error: ORIGINAL STACKTRACE: 
[08:55:56]  console.error: v@http://192.168.1.196:8100/build/polyfills.js:3:4869 
            s@http://192.168.1.196:8100/build/polyfills.js:3:4298 http://192.168.1.196:8100/build/polyfills.js:3:4691 
            invokeTask@http://192.168.1.196:8100/build/polyfills.js:3:10289 
            onInvokeTask@http://192.168.1.196:8100/build/main.js:39137:47 
            invokeTask@http://192.168.1.196:8100/build/polyfills.js:3:10232 
            runTask@http://192.168.1.196:8100/build/polyfills.js:3:7647 
            i@http://192.168.1.196:8100/build/polyfills.js:3:3714 promiseReactionJob@[native code] 
`
Any idea?

**Comment by ferminako** [comment]
It was my fault, I forgot declare a variable. It seems to work, I'm gonna try to add markers etc and confirm you that everything is ok.
Thanks

**Comment by ferminako** [comment]
OK the maps is working @wf9a5m75, but I don't know how can achieve what I achieved with ionic wrapper.

I need to be able to set a marker, when it is clicked show the info window and when info window is clicked fire a method.

I tried:
`this.map.addMarker({
                'position': {
                    lat: item.latitud,
                    lng: item.longitud
                },
                //'icon': "www/assets/images/markers/map-marker-localidad.png",
                'title':item.localidad,
                'snippet':'(More info...)',
            },function(marker) {
                marker.addEventListener(plugin.google.maps.event.INFO_CLICK)
                .subscribe(() => {
                    console.log('has tocado pit marker');
                    this.openPageLocalidad(item);
                });
            });`

Btw, custom icon doesn't work, is that url right?

Thanks.

**Comment by vosecek** [comment]
@ferminako url to icon works for me: "./assets/..." (Android and iOS).

**Comment by ferminako** [comment]
I I tried: 
`this.map.addMarker({
                'position': {
                    lat: item.latitud,
                    lng: item.longitud
                },
                //'icon': "www/assets/images/markers/map-marker-localidad.png",
                'title':item.localidad,
                'snippet':'(More info...)',
            },function(marker) {
                marker.on(plugin.google.maps.event.INFO_CLICK, this.openPageLocalidad(item));
            });`

I get this.openPageLocalidad is not a function. And of course is a function. So where could be the problem?

**Comment by vosecek** [comment]
@ferminako you are in different scope, use this way:
```
var self = this;
this.map.addMarker()....
```
For some reason Typesript construction does not work
`(marker)=>{marker.on()}.`

and inside the addMarker({}) use self.openPageLocalidad(item)

**Comment by ferminako** [comment]
Thanks @vosecek , I tried your icon route but doesn't work :(
And Now my code is: 
`var self = this;
            this.map.addMarker({
                'position': {
                    lat: item.latitud,
                    lng: item.longitud
                },
                //'icon': "./assets/images/markers/map-marker-localidad.png",
                'title':item.localidad,
                'snippet':'(More info...)',
            },function(marker) {
                marker.on(plugin.google.maps.event.INFO_CLICK, self.openPageLocalidad(item));
            });`
The problem is that the function oopenPageLocalidad is autodfired now :(

Any idea?

**Comment by vosecek** [comment]
@ferminako 
I did not try to use info window, but this construction should works:
```
var self = this;
		this.map.addMarker({
			'position': { lat: item.latitud, lng: item.longitud },
			'icon': {
				'url': "./assets/images/markers/map-marker-localidad.png"
			}
			'title': item.localidad,
			'snippet': '(More info...)'
		}, function(marker) {
			marker.on(plugin.google.maps.event.INFO_CLICK, function(){
				self.openPageLocalidad(item);	
			});
		});
```

Check especially the icon section :) url has to be specified by url property, no directly in icon. You can configure size for example. Check the marker doc.

**Comment by ferminako** [comment]
Thank you so much @vosecek , now the function is fired properly.
The problem with the icon marker persists. Any idea? Should I build or something in order to make this icons images available or something?
Cheers.

**Comment by vosecek** [comment]
Did you fix missing comma after icon property?
Maybe try to define dimensions.

Check console for errors (in XCode on Mac), error about missing file will be printed here.

**Comment by ferminako** [comment]
I tried to run emulator from xcode in order to see the log to check what is the problem witch marker icon image but the simulator is blank. and  I get this error:
2017-05-10 10:33:21.818 app[60703:3773070] Failed to load webpage with error: Could not connect to the server.
Any idea?

**Comment by ferminako** [comment]
Ok the problem was that didn't prepare code to xcode, solver using ionic prepare ios
THANKS!

**Comment by ferminako** [comment]
Btw @vosecek once I show the map and marker (icon works only if use emulator from xcode), once i tap the marker and then tap the infoview, it takes me to another page, and when I go back I don't know why this is not fired again:
`this.map.one(plugin.google.maps.event.MAP_READY, () => {
                this.map.clear();
                console.log("Map is ready.");
                this.setMarkers(zoom,centroBounds);
                this.map.moveCamera({
                    'zoom': zoom,
                    'target': centroBounds
                });
                this.loader.dismiss();
                console.log('e');
            });`

**Comment by wf9a5m75** [comment]
@ferminako Please use three-backslashes to show your code.
![screen shot 2017-05-10 at 12 28 29 pm](https://cloud.githubusercontent.com/assets/167831/25917246/42aea790-357c-11e7-9bb4-d973637f8611.png)

**Comment by wf9a5m75** [comment]
I'm not familiar with ionic framework, but this is my guess.
This plugin initializes only at once when a HTML file is loaded.
The Ionic uses only one html, and change the pages(tab or something) in the same html.

That's why the maps plugin does not fire the MAP_READY event when you come back to the map page.

**Comment by ferminako** [comment]
Sorry for the code format @wf9a5m75 
And I think you are right about ionic lifecycle...
Could you please tell me where can I find how to set map options to show map controls etc??? I've tried what I found but in my ios device and emulator I can't see the map zoom controls, etc...
Thanks.

**Comment by vosecek** [comment]
@ferminako There is no controls implemented, you can do it yourself by putting html elements on map and call setZoom() method.

**Comment by ferminako** [comment]
@vosecek  ok, thx for your support.
So I guess those controls will be available out of the box as well as ionic wrapper for  google maps plugin v2 in short/medium term, right @wf9a5m75 ?

**Comment by wf9a5m75** [comment]
@ferminako In that case, I guess the `map.setDiv()` works.

This is basic idea.

```js

controller.onPageIn = function() {
  map.setDiv(mapDiv);
};

controller.onPageout = function() {
  // before moving to another tab
  map.setDiv();
};

```

**Comment by wf9a5m75** [comment]
Ping

**Comment by wf9a5m75** [comment]
Since there is no update last 12 days, I close this at once. If you have any updates, you can reopen or just simply reply for here.

**Comment by stellasoft-charlie** [comment]
map.addMarker(markerOptions).then((marker: Marker) => {
            console.log(marker);
              marker.on(GoogleMapsEvent.INFO_CLICK).subscribe(() => {
                console.log('hello');
            })
          });

Bit late but.... This is probably what you're looking for, works for me.
