### ISSUE TITLE
does this plugin support places autocomplete like in Google Maps JavaScript API ?

### ISSUE THREAD

**Issue by MayankLogiciel** [mapsplugin/cordova-plugin-googlemaps#1440]
I want to build places autocomplete as shown in below example

https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

From plugin docs, i am unable to find any support for google places autocomplete.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

I know this can be easily implemented with Google Map Javascript Api, but i want to know, can i implement the same thing by using cordova-plugin-googlemaps?

**Comment by wf9a5m75** [comment]
no
