### ISSUE TITLE
Need plotted Route only in vertical direction 

### ISSUE THREAD

**Issue by kanishkamehta801** [mapsplugin/cordova-plugin-googlemaps#1445]
Hello,

I am using the plugin.google.maps and drawing the route in my js file, it draws the route correct but what I want it will always show the plotted route in vertical direction only not in horizontal & zig zag route. How can i do that ?
Should I need to rotate the map ?
If I rotate the map then if route is actually plotted in vertical direction then after rotating it will become horizontal ?
Please suggest

Thanks in advance!

**Comment by wf9a5m75** [comment]
Could you explain with any pictures? Such as screen captures.

**Comment by wf9a5m75** [comment]
Ping.

If no update, I will close this issue
