### ISSUE TITLE
self.get is not a function

### ISSUE THREAD

**Issue by Kirtashkill** [mapsplugin/cordova-plugin-googlemaps#1446]
I'm using Ionic2 to build an app with GoogleMaps fuctionality. I've used the example and it doesn't work and i get the error "main.js:1438 ERROR Error: Uncaught (in promise): TypeError: self.get is not a function(…)" when i call getMap. I'm runing the app in an emulator.

![image](https://cloud.githubusercontent.com/assets/5481164/25997355/fa5eaa48-371b-11e7-8d93-a02452c49575.png)

**Comment by wf9a5m75** [comment]
Do you use the plugin version 2?  If so, you can not use the ionic wrapper.

And this plugin does not run on browser.

And please provide more information, such as your code

**Comment by Kirtashkill** [comment]
I'm using the plugin version 2 and I'm runing the app in an emulator.
The code it's in your documentation:
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md

**Comment by wf9a5m75** [comment]
Then should work.
Please provide more information.

**Comment by vosecek** [comment]
@Kirtashkill show the full typescript code in your ts file.

**Comment by wf9a5m75** [comment]
@Kirtashkillping

**Comment by jayeshanandani** [comment]
Can reproduce this with simple code from docs of google maps cordova. No ionic plugins used.

**Comment by mayrarodriguez1709** [comment]
I have the same issue

**Comment by jayeshanandani** [comment]
I have followed code as shown over here:
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/For-ionic2-users

Same code copy paste. I am using latest version 2.0 beta. It fails on android/ios both.

**Comment by Kirtashkill** [comment]
I solved my issue with the plugin using this code:
````
<div id="divmap"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=API_KEY&libraries=places&callback=initMap" async defer></script>

````
in the view


and this one:
````
import {
    GoogleMap, GoogleMapsEvent, GoogleMapsLatLng, GoogleMapsMarker,
    GoogleMapsMarkerOptions
} from 'ionic-native';


 ionViewDidLoad(){
    	
        let location = new GoogleMapsLatLng(latitude, longitude);

    	let mapOptions = {
        		'controls': {
					'compass': true,
					'myLocationButton': true,
					'indoorPicker': true,
					'zoom': true
				},
				'gestures': {
					'scroll': true,
					'tilt': true,
					'rotate': true,
					'zoom': true
				},
				'camera': {
      				'latLng': location,
      				'tilt': 30,
      				'zoom': 16,
      				'bearing': 50
                }
      	};

    	this.map = new GoogleMap (document.getElementById('divmap'), mapOptions);

    	this.map.one(GoogleMapsEvent.MAP_READY).then(success => {

        	this.map.on(GoogleMapsEvent.CAMERA_CHANGE).subscribe(camera => {
        		console.log('map change');
        	});
        });	
    	
}
````
in the TS controller 

Only tested in Android.

**Comment by jayeshanandani** [comment]
@Kirtashkill are you using beta 2 version of this plugin or v1.4? As far as I know, ionic-native is not compatible with version 2 of this plugin.

**Comment by tennist** [comment]
I am getting this same error using version 1.4.  What was the solution to get it working?

**Comment by jayeshanandani** [comment]
@tennist : Are you using above with ionic 3? I would suggest to use multiple_maps branch of this plugin as it is quite stable and I have been using same for past 1 month without any issues so far. 1.4 would be deprecated soon enough.

**Comment by tennist** [comment]
i tried to install the multiple maps branch per the instructions, but it won't install.  It seems like it can't find the files to download

**Comment by tennist** [comment]
I finally got it to download after letting it sit for a long time.  It took forever to find the files for some reason.  Making adjustments for the new version now and will update as to whether or not I have the same issue.

**Comment by jayeshanandani** [comment]
@tenist: I did face the same issue, however, I upgraded npm to latest 5.x version and tried. In addition, do also make sure you uninstall the previous version by firing commands mentioned at https://github.com/mapsplugin/cordova-plugin-googlemaps#quick-install

**Comment by tennist** [comment]
I did uninstall the previous versions first and finally got my emulator updated so the correct version of google play services was available.  This new version is working great after changing my code a bit.  Just having a couple of issues, but I will start some new threads for them if I can't figure them out.  Thanks for all the help.
