### ISSUE TITLE
Module GoogleMapsBase not Found

### ISSUE THREAD

**Issue by tgb20** [mapsplugin/cordova-plugin-googlemaps#1447]
When building Cordova for iOS using this plugin I get this error 
` /Plugins/com.googlemaps.ios/GoogleMaps.framework/Headers/GMSCoordinateBounds+GoogleMaps.h:13:9: fatal error: module
      'GoogleMapsBase' not found`

Which causes the Build to fail. Has anyone else found this problem or know a solution? 

My config.xml has this:
`
<plugin name="cordova-plugin-googlemaps" spec="git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git">
<variable name="API_KEY_FOR_ANDROID" value="androidkey" />
<variable name="API_KEY_FOR_IOS" value="ioskey" />
<variable name="NSLOCATIONWHENINUSEUSAGEDESCRIPTION" value="Show your location on the map" />
<variable name="NSLOCATIONALWAYSUSAGEDESCRIPTION" value="Trace your location on the map" />
</plugin>
`
The values have my api keys in them.

**Comment by tgb20** [comment]
It works on Android. The issue is linked to the iOS build

**Comment by patrickboulay** [comment]
Same for me on the master branch and also on v2.0 branch.
Its very critics, I can not release a new version of my app. 
Any solution or work around?

**Comment by wf9a5m75** [comment]
Please show me the result of `cordova plugin list`

**Comment by patrickboulay** [comment]
com.googlemaps.ios 2.2.0 "Google Maps SDK for iOS"
cordova-admob-sdklibs 2.1.4 "Google Mobile Ads SDK for Cordova"
cordova-background-geolocation 2.7.0 "BackgroundGeolocation"
cordova-plugin-admob-simple 3.3.3 "Cordova-Phonegap AdMob Plugin"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 4.0.2 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-google-analytics 1.8.2 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova-plugin-yanap 0.8.9 "Yanap"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.6.1 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
es6-promise-plugin 4.1.0 "Promise"

**Comment by tgb20** [comment]
Here is mine:
com.googlemaps.ios 2.2.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by wf9a5m75** [comment]
Thank you for letting me know. I modified symbolic links for cordova.
Please reinstall the plugin.
You can do 

```
$> cordova plugin rm com.googlemaps.ios --force

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk --nofetch
```

**Comment by tgb20** [comment]
The app now builds successfully but the map is a black image.

**Comment by wf9a5m75** [comment]
I could display a map without no problem. 
The reason of blank map is different reason.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by tgb20** [comment]
It is not blank. Where the map should appear is solid black, no map functions work and it does not access for location permissions.

**Comment by tgb20** [comment]
I have tried both:
`ion-app._gmaps_cdv_ .nav-decor {
    background-color: rgba(0,0,0,0);
}`
and 
`ion-app._gmaps_cdv_ .nav-decor{
  background-color: transparent !important;
}`
and map map always looks like this
![simulator screen shot may 14 2017 10 36 20 am](https://cloud.githubusercontent.com/assets/5331697/26034861/4ed269ea-3891-11e7-9167-71798872c09d.png)

**Comment by wf9a5m75** [comment]
please share your whole project files on github (or other git repository services). Then I will check it.

**Comment by tgb20** [comment]
I have just added you as a collaborator on the project.

**Comment by patrickboulay** [comment]
Works perfect for me, thanks a lot!

**Comment by wf9a5m75** [comment]
@tgb20 I checked your code, but I don't know why the plugin does not work in your app.
I also noticed that your app blocks the script running of this plugin.

Unfortunately I'm not familiar with ionic.

I recommend you use the plugin v2 instead of v1.4.
Please check this document page, and try it.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/For-ionic2-users#how-to-install-the-cordova-googlemaps-plugin-v2-beta-on-ionic-2

**Comment by wf9a5m75** [comment]
@tgb20 ping

**Comment by wf9a5m75** [comment]
Since @tgb20 does not reply in one week, and the original issue (Module GoogleMapsBase not Found) was already solved, I close this issue at once.

If you have any update, you can still reply and open this issue.
