### ISSUE TITLE
Depedencies conflict when use phonegap-plugin-push at same time

### ISSUE THREAD

**Issue by tperrelli** [mapsplugin/cordova-plugin-googlemaps#1448]
Hello there. If i install phonegap-plugin-push i just can't run
`ionic build android` 

I got the following error message:

![captura de tela 2017-05-15 as 07 57 30](https://cloud.githubusercontent.com/assets/1470890/26054765/35de4a40-3944-11e7-9d6b-c7203882fc65.png)

![captura de tela 2017-05-15 as 07 56 45](https://cloud.githubusercontent.com/assets/1470890/26054739/14deacae-3944-11e7-8cbc-52f229980ee3.png)

On the other hand, if i unstall cordova--plugin-googlemaps or phonegap-plugin-psuh, i can build my app as well. So i went to phonegap-plugin-push github to see if there is some issue.

There, i've found this link: [click here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#more-than-one-library-with-package-name-comgoogleandroidgms)

They say: 
> "Those plugins should be using gradle to include the Google Play Services package but instead they include the play services jar directly or via a plugin dependency. So all of that is bad news. These plugins should be updated to use gradle. Please raise issues on those plugins as the change is not hard to make.

Is there any solution for this issue? :(

Thanks in advance

Cordova version: 6.5.0
phonegap-plugin-push version: 1.10.3
cordova-plugin-googlemaps version: 1.4.0
Android version: 6.1.2

**Comment by tperrelli** [comment]
Well, i noticed that there is 1.4.0 version release. I installed the version 1.3.9. It builds, but crashes when i open the Google Map view 👎

**Comment by wf9a5m75** [comment]
I don't support for old version. If you use the v1.3.9, you should take the risk by yourself.

And I checked the phonegap-plugin-push. Please try to install the maps plugin from github directly.

```
$> Cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps --variable ...
```
Might solve the issue.

**Comment by tperrelli** [comment]
It worked.

Well, i also noticed that when i installed directly from:
`cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps`

The Google Maps API dependencies in you plugin project properties file is being installed with version 10.+

com.google.android.gms:play-services-maps:10.+
com.google.android.gms:play-services-location:10.+

On the other hand, the traditional way:
`cordova plugin add cordova-plugin-googlemaps`

Uses the version 9.8.0 from Google Maps API:

com.google.android.gms:play-services-maps:9.8.0
com.google.android.gms:play-services-location:9.8.0

Would you update it?

Thanks for the answer.

**Comment by wf9a5m75** [comment]
The maps plugin 1.4 works on the play-serveices:9.8.0, but many people complains about that.
For the reason, I changed to specify the version `10.+`.

**Comment by tperrelli** [comment]
Yeah, i got it. I also saw those complains in other issues.

But what i mean is that when installing using command:
`cordova plugin add cordova-plugin-googlemaps`

It installs with version 9.8.0

running the command:
`cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps`

It stays with 10.+ version

Would you leave it as it is or will normalize to a unique version?

**Comment by wf9a5m75** [comment]
You can stay on the 10.+ version.
When you remove the `cordova-plugin-googlemaps`, gradle removes the Google Play Services v9.8 automatically.
You don't need to worry about it.

**Comment by tperrelli** [comment]
Ok. Thanks.
