### ISSUE TITLE
PhoneGap Cordova Map Plugin Marker drag issue

### ISSUE THREAD

**Issue by Sagarjai33** [mapsplugin/cordova-plugin-googlemaps#1453]
I am using the cordova map plugin. I have added the marker & added the MARKER_DRAG_END event. Event also get fired but I am not getting the new latlng of the marker.please Help how can we achieve this ?

i am using below code -
```js
map.addMarker({
  'position': GOOGLE,
  'draggable': true
}, function(marker) {
  marker.addEventListener(plugin.google.maps.event.MARKER_DRAG_END, function(marker) { 
     marker.getPosition(function(latLng) { 
        marker.setTitle(latLng.toUrlValue());
        marker.showInfoWindow(); 
      });
 });
});
```

But it is not working.Plz Help

**Comment by wf9a5m75** [comment]
Is there any error log in logcat or xcode log?

**Comment by wf9a5m75** [comment]
And just confirm. Do you use the plugin v1.4 or v2.0beta?

**Comment by Sagarjai33** [comment]
I am using V2.0 beta.if i put alert on drag event alert occur but it does not show current marker location.

**Comment by wf9a5m75** [comment]
If you use the plugin v2, your code is wrong.

Thw getPosition() method does not take a callback.


https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Marker/getPosition/README.md

**Comment by Sagarjai33** [comment]
Its work.Thank You So much Masashi Katsumata.You’re so helpful.
