### ISSUE TITLE
v2.0 Beta - Multiple maps sometimes does not render

### ISSUE THREAD

**Issue by rdelhommer** [mapsplugin/cordova-plugin-googlemaps#1454]
If you aren't taking issues on the beta branch, please disregard.

In my application, I have two tabs each with a separate map.  Sometimes when navigating between tabs, one map will not render.  If I switch to a different tab and back to the non-rendering tab though the map will render itself.

For example, I have tabs A, B, and C in an application.  Tabs A and B have maps.  If I start on tab A, the map on that tab (A) will render.  However, if I switch to tab B, the map on that tab (B) will **not** render.  If I then switch to tab C (no map) and then back to tab B, the map on tab B will render.

I am using the setVisible(true/false) workaround that is documented [here](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/whats-new-v2) in section "change 2: Multiple pages".  My code for setting the map visible state is shown below.

In Tab A controller
```
$scope.$on("$stateChangeSuccess", function (e, toState, toParams, fromState, fromParams) {
  if (fromState.name === 'tab.A') {
    return mapA.setVisible(false);
  }

  if (toState.name === 'tab.A') {
    return mapA.setVisible(true);
  }
});
```

In Tab B controller
```
$scope.$on("$stateChangeSuccess", function (e, toState, toParams, fromState, fromParams) {
  if (fromState.name === 'tab.B') {
    return mapB.setVisible(false);
  }

  if (toState.name === 'tab.B') {
    return mapB.setVisible(true);
  }
});
```

Before I added the code above, two maps would not render simultaneously at all.  With the above code, both maps render maybe 95% of the time, however, occasionally one will not render.

Am I missing something?  If I am doing things correctly, I'd be happy to provide more information and try to provide steps for consistently repeating the issue.

**Comment by wf9a5m75** [comment]
Since the ionic framework is slow, the plugin finishes the initialization before ionic finishing when you change the page tabs.
If you need to redraw the map mandatory, you need to execute `cordova.fireDocumentEvent('plugin_touch', {});` by yourself.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/whats-new-v2/README.md#change-4-save-battery-life

**Comment by rdelhommer** [comment]
I think I understand.  Is there an ionic event that can be used to ensure the plugin inits after the page does?  Right now, I'm initializing the maps inside of `$ionicPlatform.ready()` but upon further research that fires after the device is ready so it's probably not the best option for this.

Maybe `$ionicView.afterEnter()`?

**Comment by wf9a5m75** [comment]
I'm sorry but I'm not familiar with ionic at all.
I think `cordova.fireDocumentEvent('plugin_touch', {});` inside of `$ionicPlatform.ready()` or `map.on(plugin.google.maps.event.MAP_READY` solves your issue.

Basic idea 

```js
$ionicPlatform.ready(function() {
  cordova.fireDocumentEvent('plugin_touch', {}); // <-- maybe here 

  var map = plugin.google.maps.Map.getMap(div, { ... });
  map.on(plugin.google.maps.event.MAP_READY, function() {

     cordova.fireDocumentEvent('plugin_touch', {}); // <-- or maybe here 
     
  });
});

```

If the above idea does not work, please share your project on github or bitbucket.

By the way, please also check out this document.

**How to install the cordova-googlemaps-plugin v2-beta on Ionic 2**
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md#how-to-install-the-cordova-googlemaps-plugin-v2-beta-on-ionic-2

**Comment by rdelhommer** [comment]
No problem.  

Firing the event in the MAP_READY by itself unfortunately doesn't fix the issue.  However, wrapping the redraw event in a $timeout and seems to reduce the occurrence of the issue.  This is a pretty brittle "solution" though.
```
$ionicPlatform.ready(function() {
  var map = plugin.google.maps.Map.getMap(div, { ... });
  map.on(plugin.google.maps.event.MAP_READY, function() {

     $timeout(function() {
       cordova.fireDocumentEvent('plugin_touch', {});
     }, 200);
  });
});
```

**Comment by wf9a5m75** [comment]
Ok, thank you for sharing your solution ;)
