### ISSUE TITLE
全てのマーカーでタイトル情報を表示したい

### ISSUE THREAD

**Issue by come25136** [mapsplugin/cordova-plugin-googlemaps#1455]
現在[この](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md#create-multiple-markers)方法でマーカーを表示しているのですが、最後に実行されたshowInfoWindow()のみタイトル表示がされるのを全てのマーカーのタイトルが表示されるようにしたいのです。

そのような事は可能でしょうか？

**Comment by wf9a5m75** [comment]
残念ながらGoogle Maps APIそのものが1つしかinfoWindowを表示できないので、できません。

**Comment by come25136** [comment]
そうでしたか... 素早い返信ありがとうございます。
