### ISSUE TITLE
Can not fetch v2 multiple_maps branch

### ISSUE THREAD

**Issue by RealJaJaAdmin** [mapsplugin/cordova-plugin-googlemaps#1456]
Hi,

First, great plugin, we have been using 1.4.0 in our product. We would like to upgrade to 2.0, we followed the install instruction:

cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps \
     --variable API_KEY_FOR_ANDROID="<YOUR KEY>" \
     --variable API_KEY_FOR_IOS="<YOUR KEY>" \
     --nofetch

but the fetch is hanging, looks like the branch multiple_maps branch is not cloneable. Could you please clarify it?

Thanks!

**Comment by wf9a5m75** [comment]
The repository is totally open. If you can not clone the repository, it's your environment problem.

One possible solution is to use the git command, then local install.

```
$> git clone https://github.com/.....

Then switch to the multiple_maps branch


$> cordova add install (path to the repo)/ --variable API....
```

**Comment by RealJaJaAdmin** [comment]
thanks!
