### ISSUE TITLE
what is best way to delete the map .

### ISSUE THREAD

**Issue by Khalid-Nowaf** [mapsplugin/cordova-plugin-googlemaps#1457]
Hi there, I'm using the map for a while now. I used the map in ionic application, and every time the user leave the "Page" I try to delete, remove and clear the map. My approach something like
```javascript
map.clear();
map.empty(); // <-- no idea how this is helpful 
map.remove();
```
but the problem is the map events still working and never get cleared ! but I found a function in the "src" but not in the  [Docs](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v1.4.0/class/Map)
```javascript
map.off()
```
so now my final code is 
```javascript
map.clear();
map.empty(); // <-- no idea how this is helpful 
map.off();
map.remove();
```
do you think guys this will remove every related to the map ? and will help avoiding memory leaks in both sides "JS" and "Native";

**Comment by wf9a5m75** [comment]
If you use the maps plugin v2, just executes `map.remove()` is the best.

The map.remove() does `map.clear()` and `map.off()` internally

**Comment by wf9a5m75** [comment]
It looks you use the v1.4.

There is no method `map.empty()` (but I didn't know for the ionic wrapper case).

```js
map.clear();
map.off();
map.remove();
```

At lease the above steps are very fine to avoid memory leak.

**Comment by Khalid-Nowaf** [comment]
thanks @wf9a5m75 for answering my question .
