### ISSUE TITLE
addKmlOverlay() is not working in ionic 2

### ISSUE THREAD

**Issue by rupalpatel0008** [mapsplugin/cordova-plugin-googlemaps#1459]
Hi,
I am using this plugin to show a kml layer on google map. However, the method addKmlOverlay() is not working in my ionic 2 app.

This is my config info:
global packages:
    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.1.2

local packages:
    @ionic/app-scripts              : 1.1.3
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 2.3.0

System:
    Node       : v7.2.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

Plugin version:
2.0.0-beta2-20170517-2215

This is the function by which I am loading map and adding a kml layer on it. This function is called after platform is ready. The map is loaded using this plugin, but the kml layer is not added. I have also tried other kml urls.

```
loadMap() {
    console.log('Start loading MAP');
    let location = new GoogleMapsLatLng(41.876, -87.624);
    this.map = new GoogleMap('map', {
      'backgroundColor': 'white',
      'controls': {
        'compass': false,
        'indoorPicker': false,
        'zoom': true
      },
      'gestures': {
        'scroll': true,
        'tilt': false,
        'rotate': true,
        'zoom': true
      },
      'camera': {
        'latLng': location,
        'zoom': 5
      },
    });
    // listen to MAP_READY event
    this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
      console.log('map ready');
      let kmlOptions: GoogleMapsKmlOverlayOptions = {
        'url': "http://googlemaps.github.io/js-v2-samples/ggeoxml/cta.kml",
        'animation': false
      };
      this.map.addKmlOverlay(kmlOptions).then(kmlOverlay => {
        console.log(kmlOverlay);
      }).catch(error => {
        console.log(error);
      });
    });
  }
```

**Comment by wf9a5m75** [comment]
The addKmlOverlay() of the v2 is not ready to use yet.
