### ISSUE TITLE
Any way to debug map not showing on iOS?

### ISSUE THREAD

**Issue by mtflud** [mapsplugin/cordova-plugin-googlemaps#1460]
Hi! Thank you for your time developing this plugin. Just recently, I started integrating this on a Cordova application, using Vue and VueRouter. I installed V2 with the proper map keys with no problems. However, the map is not showing for me using the following code:

```html
<template>
    <div class="map gmap_div" id="map_canvas"></div>
</template>
<style>
    .map {
        width: 100vw;
        height: 100vh;
        display: block;
        z-index: 999999;
    }
</style>
<script>
    export default {
        methods: {
            /*
             * Initialize map and it's components
             */
            initialize() {
                let div = document.getElementById("map_canvas");
                let map = plugin.google.maps.Map.getMap(div);
                map.one(plugin.google.maps.event.MAP_READY, function() {
                    alert("LOADED")
                    // :: Read that this line could inform you if the map has been created, for me, it does not do anything
                    map.showDialog()
                })
            }
        },
        // :: When the component is mounted
        mounted() {
             // :: Vue fires this event from root instance when "deviceReady" event occurs
             bus.$on('appReady' => {
                 this.initialize()
             })
        }
    }
</script>
```
The "LOADED" alert gets fired, no evident errors, but I can't see the map. iOS emulator console just shows:

2017-05-22 16:41:54.085 MyApp[98075:1466235] Google Maps SDK for iOS version: 2.2.30010.0

Running the app on my iPhone and debugging with Safari Developer Console, I just see the div with nothing inside:

```html
<body class="_gmaps_cdv_" style="background-color: rgba(0, 0, 0, 0);" __plugindomid="pgm305567341438" _result="1">
    <div id="app" style="background-color: rgba(0, 0, 0, 0); z-index: -99;" class="_gmaps_cdv_" __plugindomid="pgm1264813173753" _result="1002">
        <div id="map_canvas" class="map gmap_div _gmaps_cdv_" __pluginmapid="map_0_126282158974" style="overflow: hidden; background-color: rgba(0, 0, 0, 0);" __plugindomid="pgm782337933078" _result="2003">
        </div>
    </div>

    <script type="text/javascript" src="cordova.js"></script>
    <!-- Main JS -->
    <script type="text/javascript" src="js/app.js"></script>
    <iframe src="gap://ready" style="display: none;"></iframe>
</body>
```

Can you help me see what am I doing wrong? Any way to further debug this?
Thank you very much!

**Comment by wf9a5m75** [comment]
`map.showDialog()` is not available in the v2 plugin.

**Comment by wf9a5m75** [comment]
And the safari debugger does not keep errors before you open it.

For that time, you need to reload your html using the safari debugger, then the safari debugger captures the errors.

Please try it. Maybe you will get some JS errors (I guess).

**Comment by mtflud** [comment]
@wf9a5m75 Thank you for your quick answer! Did as you told me and sure enough, an error is revealed

TypeError: map.showDialog is not a function. (In 'map.showDialog()', 'map.showDialog' is undefined)

Because as you said map.showDialog() is not available in V2. Removed that line, error goes away. No more errors and still no map :/ any other idea?
Thanks!

**Comment by wf9a5m75** [comment]
I see. Maybe like ionic, you need to fire the `plugin_touch` event.

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1454#issuecomment-302461067

```js
var map = plugin.google.maps.Map.getMap(div, { ... });
  map.on(plugin.google.maps.event.MAP_READY, function() {

     setTimeout(function() {
       cordova.fireDocumentEvent('plugin_touch', {});
     }, 200);
  });
```

**Comment by mtflud** [comment]
@wf9a5m75 Thanks again for your help. Tried adding what you told me, still no difference. Tried emulating on Android, same problem. Could this be an issue related on how Vue Router renders the view? I've read issues where the view overlays the map. Tried manually putting styles like z-index: -1 and background-color: rgba(0,0,0,0) to all the parent elements, but still no luck :(

**Comment by wf9a5m75** [comment]
Since I'm not familiar with the Vue framework at all, I can not detect what the wrong point is so far.
In order to inspect your case more deeply, please share your project file (all project files) using github or bitbacket (or other git repository services are acceptable).
(Don't send me a zip file)

**Comment by loama** [comment]
have you tried setting width and height of #map_canvas in px?

**Comment by wf9a5m75** [comment]
ping

**Comment by aboveo** [comment]
we had the same issue just keep the height 99.99vh it works

**Comment by wf9a5m75** [comment]
Since there is no update, I close this issue.

**Comment by dominiosaz** [comment]
> "@wf9a5m75 Thanks again for your help. Tried adding what you told me, still no difference. Tried emulating on Android, same problem. Could this be an issue related on how Vue Router renders the view? I've read issues where the view overlays the map. Tried manually putting styles like z-index: -1 and background-color: rgba(0,0,0,0) to all the parent elements, but still no luck :( "

This works for me, I'm using onsen for the UI so the problem was that the map was rendering behind the div that is used for display the background, and also behind the div that is used for display the content.

Thanks.
