### ISSUE TITLE
Mulltiple_Maps : White screen after switching tabs in ionic 

### ISSUE THREAD

**Issue by SAanish** [mapsplugin/cordova-plugin-googlemaps#1461]
Having an ios specific issue. When I switch on different tabs and come back to map screen than map disappeared. Even after debugging in safari I am getting Map div. I am getting this issue randomly not every time.

` <div id="map" style="height: 449px; overflow: hidden; background-color: rgba(0, 0, 0, 0);" __pluginmapid="map_0_885162164573" __plugindomid="pgm985073132027" class="_gmaps_cdv_" _result="68013"></div>`

**Comment by wf9a5m75** [comment]
Please search previous answers before asking.
  https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1454#issuecomment-302461067

https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=tab+ionic&type=Issues&utf8=✓

**Comment by SAanish** [comment]
Thanks for your reply. 

I already look into that but provided solution not fixing my problem.

**Comment by wf9a5m75** [comment]
In that case, please share your all project files using github or bitbacket.

**Comment by SAanish** [comment]
Hi wf9a5m75 ,

It's a personal project so I can't share anything from this. But if you can help us that would be great.

**Comment by wf9a5m75** [comment]
You can't share, I can't help you.

**Comment by SAanish** [comment]
It is necessary to reinitialize the map every time. Because we using caching in ionic.

**Comment by wf9a5m75** [comment]
Unless you share your code, I can not understand your code situation so far.
I'm not familiar with ionic at all.
And I'm so busy, so I don't have a time to play with quiz.

**Comment by wf9a5m75** [comment]
I'm not sure this is helpful or not, but check another person's solution.

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1429#issuecomment-298769652

**Comment by SAanish** [comment]
Thanks for your response on this. I will try to fix my issue with this solution.

**Comment by wf9a5m75** [comment]
ping

**Comment by SAanish** [comment]
I tried that solution but the issue is replicating on the random basis.

**Comment by wf9a5m75** [comment]
Please share your project files

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment]
@SAanish If you don't share your project files, I can not support you. (In that case, I close this issue)

**Comment by SAanish** [comment]
@wf9a5m75, I can't be shared my project files. you can close the issue.

**Comment by SKempin** [comment]
@SAanish Did you find a solution to this? I am experiencing a similar issue with Ionic 3 and tabs.

**Comment by SAanish** [comment]
@SKempin, Whenever I come back to the map screen, I am recalculating the height of the map div and assign the height to the map div.

**Comment by SKempin** [comment]
@SAanish And that has fixed the issue for you?

**Comment by SAanish** [comment]
Also fired and event which i got here.
[https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1454#issuecomment-302461067](url)

**Comment by SKempin** [comment]
@SAanish That link is broke unfortunately. Can you give me an example code snippet?

**Comment by SAanish** [comment]
@SKempin, Added the code. Use ionic **lifecycle** to execute the events.

**Comment by SKempin** [comment]
@SAanish I have solved this by using the fix as suggested on https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/256#issuecomment-309594480, however I have encountered a new issue with this - https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/256#issuecomment-309758583

**Comment by CesarAPPinheiro** [comment]
Hey guys, I've found the solution!
All you need to do is add:

  ionViewWillEnter() {
     cordova.fireDocumentEvent('plugin_touch', {});
  }

to you "map.ts" page...it simulates a click on the map when the page is about to became active...this is enough to get the map working at 100% width!

=)
