### ISSUE TITLE
Two roads for Ionic 2/maps v2 in readme.md. Which one to use?

### ISSUE THREAD

**Issue by tordnilsen** [mapsplugin/cordova-plugin-googlemaps#1463]
Hi.
In https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md
there is two links to how to use with Ionic 2.
* **For Ionic 2 users** https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md

and
* **How to use the plugin v2 with ionic2**  https://github.com/jalescardoso/ionic2-cordova-plugin-googlemaps-v2

As far as I can see there is rather big differences on the approach. 
Which one is recommended to use?

Thanks

**Comment by wf9a5m75** [comment]
Oh, I see..

I checked `How to use the plugin v2 with ionic2`, but the code is for v1.

The recommended way is 

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md
