### ISSUE TITLE
app crashes when adding circles

### ISSUE THREAD

**Issue by NikolaMandic** [mapsplugin/cordova-plugin-googlemaps#1464]
ionic app crashes once cashe is cleared it gives null pointer exception
any tips on how to handle it?

**Comment by NikolaMandic** [comment]
hm I better check this more sorry for spamming

**Comment by wf9a5m75** [comment]
How did you write your code?

**Comment by NikolaMandic** [comment]
hm actually I got it working with workaround
here is quick tutorial for ionic
don't clear cache no matter what
use ionic view events for when view loads or enters to rerender the map
I used beta2 with ionic

**Comment by wf9a5m75** [comment]
Hmm,  your broken English is very difficult for me.
I can not understand your English...

**Comment by NikolaMandic** [comment]
I can fake other languages too
we can try some other

**Comment by wf9a5m75** [comment]
I'm not native English speaker at least. Please give me some kind to understand your situation.
Could you simply answer for my questions?

- Could you show me you code that adds circles?

- Do you use the plugin v1, v2 or the ionic wrapper version?

- Could you show me the error log? or take a screen shot of Xcode?

**Comment by NikolaMandic** [comment]
sorry. 
1. I was wrong when attributing this to circle code
2. I was using plugin v2 and angular ionic that is not typescript but plain js
3. It happened on android I can't provide code but here is what was crashing 

there are two views one with map one without
map is rendered at first and it is ok
I did cache clear on certan parts of the app
with code similar to this
```

  $ionicHistory.clearCache().then(function(){
      $ionicHistory.clearHistory();
        $state.go("app.home");
    });

```

and if I did this and went back to map view it would crash the whole app
and give it as null pointer exception

so instead of trying to re render the map better to try to not clear cache in whole ionic app
and write code in different way if possible
to do that ionic provides events that you can use to update view
and that is specific to ionic

**Comment by wf9a5m75** [comment]
>and give it as null pointer exception

Please provide the error log.

**Comment by wf9a5m75** [comment]
ping
