### ISSUE TITLE
App crashes when adding multiple markers and after a infoWindow is open

### ISSUE THREAD

**Issue by marioshtika** [mapsplugin/cordova-plugin-googlemaps#1465]
Hello and thank you for this plugin. You have done a good job.

I am having a problem when adding multiple markers. 

All markers are shown (ok), when I click on a marker the infoWindow is shown (ok), when I click on another marker or anywhere in the map after a infoWindow is open it crashes.

I am using the v2 of the plugin with ionic v1.

Any ideas on why this is happening? 

Thank you in advance.

**Comment by wf9a5m75** [comment]
Could you show me your code?

**Comment by wf9a5m75** [comment]
Could you show me your code?

Without code, how can I test you guys case?

The execJS is used for passing plugin events to the JS side.
So without the test code that reproduce the issue 100% , I can not debug and fix the issue.

**Comment by erpxit** [comment]
var db;
var qrcode_ticket_img;
var nome_utente;
var cognome_utente;
var id_utente;
var t_uuid;
var i;
var parlamititolo;
var datamarker = [];
var watchGps = null;
var opzionigps = {
    enableHighAccuracy: true,
    timeout: 2500,
    maximumAge: 3000
};
var navigo_verso;

var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler

    onDeviceReady: function() {
        this.receivedEvent('deviceready');
    },

    // Update DOM on a Received Event
    receivedEvent: function(id) {

        ScreenResizeFunc();

        copyDatabaseFile('smartplanner.db').then(function() {
            db = sqlitePlugin.openDatabase('smartplanner.db', '1.0', '', 1);
            db.transaction(function(txn) {
                txn.executeSql('SELECT count(*) as answer from utente', [], function(tx, res) {
                    var righe = res.rows.item(0).answer;
                    if (righe > 0) {
                        $('#login').remove();
                        $('#initializeDiv').show();
                        txn.executeSql('SELECT * FROM utente', [], function(tx, res) {
                            id_utente = res.rows.item(0).id_utente;
                            nome_utente = res.rows.item(0).nome;
                            cognome_utente = res.rows.item(0).cognome;
                            t_uuid = res.rows.item(0).t_uuid;
                            qrcode_ticket_img = res.rows.item(0).qrcode_ticket_img;

                            $('#home').show();
                            $('#passDiv').html('<img src="' + qrcode_ticket_img + '" />');

                            Startmap();
                        });
                    } else {
                        $('#login').show();
                    }
                });
            });
        }).catch(function(err) {
            console.log(err);
        });




        function Startmap() {
            var div = document.getElementById("map");

            var map = plugin.google.maps.Map.getMap(div, {
                'mapType': plugin.google.maps.MapTypeId.ROADMAP,
                'controls': {
                    'compass': true,
                    'myLocationButton': true,
                    'indoorPicker': true,
                    'zoom': true
                },
                'gestures': {
                    'scroll': true,
                    'tilt': true,
                    'rotate': true,
                    'zoom': true
                },
                'camera': {
                    target: {
                        lat: 40.550689,
                        lng: 14.242800
                    },
                    zoom: 8
                },
                'styles': [{
                    featureType: "all",
                    stylers: [{
                        saturation: 20
                    }]
                }, {
                    featureType: "poi.business",
                    elementType: "labels",
                    stylers: [{
                        visibility: "off"
                    }]
                }],
                'preferences': {
                    'zoom': {
                        'minZoom': 8
                    }
                }
            });




            map.one(plugin.google.maps.event.MAP_READY, function() {
                $('#initializeDiv').hide();
                $('#apribottom').trigger("click");
                map.animateCamera({
                    target: {
                        lat: 40.550689,
                        lng: 14.242800
                    },
                    zoom: 14,
                    tilt: 60,
                    bearing: 0,
                    duration: 5000,
                    padding: 0
                }, function() {
                    parlami("it-IT", "Benvenuto a Capri, " + nome_utente);
                });



                db.transaction(function(txn) {
                    txn.executeSql('SELECT poi.*, tickets.id_anagrafica from poi LEFT JOIN tickets ON tickets.id_anagrafica = poi.id_o AND poi.category = "a" GROUP BY poi.id_o', [], function(txn, res) {
                        var icona_marker;
                        var placesHtml;


                        for (i = 0; i < res.rows.length; i++) {
                            icona_marker = res.rows.item(i).type_icon;
							
							placesHtml = '';
                            placesHtml = '<div class="row"><div class="col-xs-3"><img src="' + res.rows.item(i).type_icon_2 + '"></div><div class="col-xs-9">' + res.rows.item(i).title + '</div></div>';
                            if (res.rows.item(i).id_anagrafica > 0) {
                                icona_marker = res.rows.item(i).type_icon_2;
                                placesHtml = '<div class="row"><div class="col-xs-3"><img src="' + res.rows.item(i).type_icon_2 + '"></div><div class="col-xs-9">' + res.rows.item(i).title + '<br><i class="fa fa-qrcode fa-2x" aria-hidden="true"></i></div></div>';
                            }

                            datamarker.push({
                                'position': {
                                    'lng': res.rows.item(i).lng,
                                    'lat': res.rows.item(i).lat
                                },
                                'title': res.rows.item(i).title,
                                'icon': icona_marker,
                                'id_o': res.rows.item(i).id_o,
                                'id_tipo': res.rows.item(i).category
                            });




                            $('#places').append(placesHtml);

                            // end for
                        }


                        GenerateMarker(datamarker);

                    });
                });




                function GenerateMarker(data) {
                    var baseArrayClass = new plugin.google.maps.BaseArrayClass(data);
                    baseArrayClass.map(function(options, cb) {
                        map.addMarker(options, cb);
                    }, function(markers) {


                        for (i = 0; i < markers.length; i++) {
                            markers[i].id_o = data[i].id_o;
                            markers[i].id_tipo = data[i].id_tipo;
                            markers[i].nome_artplanner = data[i].title;
							markers[i].on(plugin.google.maps.event.MARKER_CLICK, onMarkerClick);
                        }
                       


                    });

                    // fine GenerateMarker
                }

                function onMarkerClick() {
                    var latlng = this.getPosition();
                    parlamititolo = this.nome_artplanner;
					
					
					var hmap = $(window).height();
					
					$('#header').slideUp("fast", function(){
					$('#map').css("top","0px");
					$('#map').height(hmap - 90);
                    $('#map_dialog').slideDown();
					});
                    
                    
					
					
					
					var map_dialog_html = '<div class="row"><div class="col-xs-12"><h5>'+parlamititolo+'</h5></div></div>' +
										  '<div class="row">' +
										  '<div class="col-xs-4"><a href="#" class="InfoButton btn-map-dialog"><i class="fa fa-info-circle" aria-hidden="true"></i></a></div>' + 
										  '<div class="col-xs-4"><a href="#" class="CalcRoute btn-map-dialog" data-id="' + this.id_o + '" data-tipo="' + this.id_tipo + '" data-lat="' + latlng.lat + '" data-lng="' + latlng.lng + '"><i class="fa fa-road" aria-hidden="true"></i></a><a href="#" class="StopWatchGPS btn-map-dialog"><i class="fa fa-stop" aria-hidden="true"></i></a></div>' + 
										  '<div class="col-xs-4"></div>' + 
										  '</div>';
					
					
                    $('#map_dialog').html(map_dialog_html);
					
					var check_navigo_verso = this.id_o + "-" + this.id_tipo;
					
					if(check_navigo_verso === navigo_verso){
						$('.CalcRoute').hide();
						$('.StopWatchGPS').show();
					}


                    $('.CalcRoute').on("touchend", function(event) {

                        event.preventDefault();
						navigo_verso = $(this).attr("data-id");
						navigo_verso = navigo_verso + "-" + $(this).attr("data-tipo");
						$('.CalcRoute').hide();
						$('.StopWatchGPS').show();
						
						if(watchGps !== null){
						StopWatchGps();
						}

                        var latDest = $(this).attr("data-lat");
                        var lngDest = $(this).attr("data-lng");
                        var pointsroute = [];
                        var pointsroute_final = [];
                        var myRoute;



                        map.getMyLocation(onSuccessLocation, onErrorLocation);

                        function onSuccessLocation(location) {
                            $.ajax({
                                url: "https://maps.googleapis.com/maps/api/directions/json?origin=" + location.latLng.lat + "," + location.latLng.lng + "&destination=" + latDest + "," + lngDest + "&mode=WALKING&region=it&language=it&units=metric&key=XXXXXXXXXXXXXXXXXXX",
                                cache: false,
                                dataType: 'json'
                            }).done(function(data) {

                                myRoute = data.routes[0].legs[0];



                                $.each(data.routes[0].legs[0].steps, function(key, value) {
                                    pointsroute.push(decodePolyline(data.routes[0].legs[0].steps[key].polyline.points));
                                });

                                $.each(pointsroute, function(key, value) {
                                    $.each(value, function(key2, value2) {
                                        pointsroute_final.push(value2);
                                    });
                                });




                                
                                map.clear();

                                map.addPolyline({
                                    'points': pointsroute_final,
                                    'color': '#0e9ef0',
                                    'width': 8,
                                    'geodesic': false
                                }, function() {
                                    GenerateMarker(datamarker);
                                });




                                var directions_panel_html = '<table class="table table-striped">';

                                console.log(myRoute);

                                for (i = 0; i < myRoute.steps.length; i++) {

                                    var sql_istruz = myRoute.steps[i].html_instructions;
                                    var sql_distanz = myRoute.steps[i].distance.text;

                                    var sql_icona_direzione = myRoute.steps[i].maneuver;



                                    directions_panel_html = directions_panel_html + '<tr><td><div class="dicor dir_' + sql_icona_direzione + '"</div></td><td>' + sql_istruz + '</td><td>' + sql_distanz + '</td></tr>';

                                }



                                parlami("it-IT", "Calcolo il percorso per " + parlamititolo + ". L'arrivo e' previsto fra " + myRoute.duration.text + ". " + removeHTMLTags(myRoute.steps[0].html_instructions) + "per " + myRoute.steps[0].distance.text);

                                directions_panel_html = directions_panel_html + '</table>';
                                $('#directions_panel').html(directions_panel_html);



                                StartWatchGps();




                                //fine chiamata ajax .done
                            });
                        }




                        // fine calroute
                    });
					$('.StopWatchGPS').on("touchend", function(event) {
                        event.preventDefault();
						$('.StopWatchGPS').hide();
						$('.CalcRoute').show();
						navigo_verso = '';
						if(watchGps !== null){
						StopWatchGps();
						}
                    });
					

                    // fine onMarkerClick 
                }

                function StartWatchGps() {
                    navigator.geolocation.getCurrentPosition(StartWatchGpsNow, onErrorLocation);
                }

                function StartWatchGpsNow(position) {
					window.plugins.insomnia.keepAwake();
					console.log("GPS Start Trace");

                    var compassdirGo = position.coords.heading;
                    if (compassdirGo === null) {
                        compassdirGo = 0;
                    }
                    map.animateCamera({
                        target: {
                            lat: position.coords.latitude.toFixed(6),
                            lng: position.coords.longitude.toFixed(6)
                        },
                        zoom: 19,
                        tilt: 60,
                        bearing: compassdirGo,
                        duration: 5000,
                        padding: 220
                    }, function() {
                        watchGps = navigator.geolocation.watchPosition(WatchGpsOk, onErrorLocation, opzionigps);
                    });

                }

                function StopWatchGps() {
                    navigator.geolocation.clearWatch(watchGps);
					window.plugins.insomnia.allowSleepAgain()
					watchGps = null;
					console.log("GPS Stop Trace");
                }

                function WatchGpsOk(position) {
                    console.log(position.coords.latitude + ' / ' + position.coords.longitude + ' Ac: ' + position.coords.accuracy);
                    var lat_now = position.coords.latitude;
                    var lng_now = position.coords.longitude;
                    var speed_ms = position.coords.speed;
                    var speed_km = (speed_ms * 3.6);
                    var accur = position.coords.accuracy;
                    var compassdir = position.coords.heading;
                    var gpstime = position.timestamp;
                    if (accur <= 100) {
                        if (compassdir === null) {
                            compassdir = 0;
                        }

                        map.moveCamera({
                            target: {
                                lat: lat_now.toFixed(6),
                                lng: lng_now.toFixed(6)
                            },
                            'bearing': compassdir

                        });

                    }

                }

                function onErrorLocation() {
                    console.log("Errore GPS");
                }

                //fne MAP Ready
            });



            //fne Startmap
        }




        $('.qrcodebtn').on("touchstart", function(event) {
            event.preventDefault();
            cordova.plugins.barcodeScanner.scan(
                function(result) {
                    if (result.cancelled === 0 && result.format === 'QR_CODE') {
                        logmein(result.text);
                    }
                },
                function(error) {
                    console.log("Scanning failed: " + error);
                }, {
                    preferFrontCamera: false,
                    showFlipCameraButton: true,
                    showTorchButton: true,
                    torchOn: true,
                    prompt: "Inquadra il Barcode",
                    resultDisplayDuration: 500,
                    formats: "QR_CODE",
                    orientation: "landscape",
                    disableAnimations: true,
                    disableSuccessBeep: false
                }
            );
        });


        $('#openPass').on("touchend", function(event) {
            event.preventDefault();

            setTimeout(function() {
                $('#bottomsheet').panel("close");
            }, 1000);
            $('#passDiv').show();
        });

        $('#openMap').on("touchend", function(event) {
            event.preventDefault();

            setTimeout(function() {
                $('#bottomsheet').panel("close");
            }, 1000);
            $('#passDiv').hide();
        });

        $('#passDiv').on('swipeup', function() {
            $('#apribottom').trigger("click");
        });
		
		$('.ui-panel-dismiss').on('swipedown', function() {
			$('#bottomsheet').panel("close");
		});
		
		$('#map_dialog').on('swipedown', function() {
			var hmap = $(window).height();
                    
					$('#map_dialog').slideToggle();
					$('#header').slideToggle("fast", function(){$('#map').css("top","64px");
					$('#map').height(hmap - 64);});
					
		});
		


        //window.addEventListener("orientationchange", ScreenResizeFunc, true);


        // funzioni
        function copyDatabaseFile(dbName) {
            var sourceFileName = cordova.file.applicationDirectory + 'www/' + dbName;
            var targetDirName = cordova.file.dataDirectory;
            return Promise.all([
                new Promise(function(resolve, reject) {
                    resolveLocalFileSystemURL(sourceFileName, resolve, reject);
                }),
                new Promise(function(resolve, reject) {
                    resolveLocalFileSystemURL(targetDirName, resolve, reject);
                })
            ]).then(function(files) {
                var sourceFile = files[0];
                var targetDir = files[1];
                return new Promise(function(resolve, reject) {
                    targetDir.getFile(dbName, {}, resolve, reject);
                }).then(function() {
                    console.log("file already copied");
                }).catch(function() {
                    console.log("file doesn't exist, copying it");
                    return new Promise(function(resolve, reject) {
                        sourceFile.copyTo(targetDir, dbName, resolve, reject);
                    }).then(function() {
                        console.log("database file copied");
                    });
                });
            });
        }

        function ScreenResizeFunc() {
            var hmap = $(window).height();
            $('#map').height(hmap - 64);
            $('#passDiv').height(hmap - 64);
            $('#initializeDiv').height(hmap);
        }

        function logmein(qrcode) {

            // org=26 = CaprismARTplanner
            $('#login').remove();
            $('#initializeDiv').show();
            var userx = $('#a').val();
            var pasx = $('#b').val();
            $.ajax({
                cache: false,
                type: "POST",
                data: "secret=XXXXXXXXXXXX&org=26&a=" + userx + "&b=" + pasx + "&c=" + qrcode,
                url: 'https://dw.coopculture.it/secure/applogin/logmein.cfm',
                success: function(data) {
                    var datax = JSON.parse(data);

                    qrcode_ticket_img = datax.dati[0].qrcodeimg;
                    nome_utente = datax.dati[0].nome;
                    cognome_utente = datax.dati[0].cognome;
                    id_utente = datax.dati[0].id_utente;
                    t_uuid = qrcode;
                    $('#passDiv').html('<img src="' + qrcode_ticket_img + '" />');


                    db.transaction(function(tx) {
                        var query;

                        // Insert Utente
                        query = "INSERT INTO utente (id_utente, nome, cognome, t_uuid, qrcode_ticket_img) VALUES (?,?,?,?,?)";
                        tx.executeSql(query, [id_utente, nome_utente, cognome_utente, qrcode, qrcode_ticket_img]);


                        // Insert Tickets
                        query = "INSERT INTO tickets (id, id_artplanner_ordine, id_anagrafica, id_protoddo, id_itinerario, id_evento, prezzo, iva, intero, ridotto, gratuito, usato, data_uso) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
                        for (i = 0; i < datax.dati[0].tickets.length; i++) {
                            tx.executeSql(query, [datax.dati[0].tickets[i].id, datax.dati[0].tickets[i].id_artplanner_ordine, datax.dati[0].tickets[i].id_anagrafica, datax.dati[0].tickets[i].id_protoddo, datax.dati[0].tickets[i].id_itinerario, datax.dati[0].tickets[i].id_evento, datax.dati[0].tickets[i].prezzo, datax.dati[0].tickets[i].iva, datax.dati[0].tickets[i].intero, datax.dati[0].tickets[i].ridotto, datax.dati[0].tickets[i].gratuito, datax.dati[0].tickets[i].usato, datax.dati[0].tickets[i].data_uso]);
                        }

                        // Insert Oggetti mappa
                        query = "INSERT INTO poi (id_o, category, title, location, lat, lng, type, type_icon, type_icon_2, img, price) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                        for (i = 0; i < datax.dati[0].poi.length; i++) {
                            tx.executeSql(query, [datax.dati[0].poi[i].id_o, datax.dati[0].poi[i].category, datax.dati[0].poi[i].title, datax.dati[0].poi[i].location, datax.dati[0].poi[i].lat, datax.dati[0].poi[i].lng, datax.dati[0].poi[i].type, datax.dati[0].poi[i].type_icon, datax.dati[0].poi[i].type_icon_2, datax.dati[0].poi[i].img, datax.dati[0].poi[i].price]);

                        }




                    }, function(error) {
                        console.log('transaction error: ' + error.message);
                    }, function() {
                        console.log('transaction ok');
                    });




                },
                complete: function() {
                    $('#initializeDiv').hide();
                    $('#home').show();
                    Startmap();

                },
                error: function(er) {
                    alert(er);
                }
            });
        }


        function parlami(lingua, testo) {
            TTS.speak({
                text: testo,
                locale: lingua,
                rate: 1.5
            }, function() {
                //alert('success');
            }, function(reason) {
                alert(reason);
            });
        }


        function removeHTMLTags(htmlString) {
            if (htmlString) {
                var mydiv = document.createElement("div");
                mydiv.innerHTML = htmlString;

                if (document.all) // IE Stuff
                {
                    return mydiv.innerText;

                } else // Mozilla does not work with innerText
                {
                    return mydiv.textContent;
                }
            }
        }


        function decodePolyline(encoded) {
            if (!encoded) {
                return [];
            }
            var poly = [];
            var index = 0,
                len = encoded.length;
            var lat = 0,
                lng = 0;

            while (index < len) {
                var b, shift = 0,
                    result = 0;

                do {
                    b = encoded.charCodeAt(index++) - 63;
                    result = result | ((b & 0x1f) << shift);
                    shift += 5;
                } while (b >= 0x20);

                var dlat = (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
                lat += dlat;

                shift = 0;
                result = 0;

                do {
                    b = encoded.charCodeAt(index++) - 63;
                    result = result | ((b & 0x1f) << shift);
                    shift += 5;
                } while (b >= 0x20);

                var dlng = (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
                lng += dlng;

                var p = {
                    lat: lat / 1e5,
                    lng: lng / 1e5,
                };
                poly.push(p);
            }
            return poly;
        }


        // fine funzioni		

        // end recived event device ready
    }

    // end app
};

app.initialize();

**Comment by erpxit** [comment]
the code is here... let us offer you a beer please! .. where is the link?

**Comment by marioshtika** [comment]
even with the example code it doesn't work

`
var div = document.getElementById("map_canvas");
var map = plugin.google.maps.Map.getMap(div);
map.one(plugin.google.maps.event.MAP_READY, function() {
  var data = [
    {
      position: {lng: -122.1180187, lat: 37.3960513},
      title: "Ardis G Egan Intermediate School"
    },
    {
      position: {lng: -122.1102408, lat: 37.3943847},
      title: "Portola School"
    }
  ];

  // Add markers
  var baseArrayClass = new plugin.google.maps.BaseArrayClass(data);

  baseArrayClass.map(function(options, cb) {
    // The variable "options" contains each element of the data.
    //
    // The variable "cb" is a callback function of interation.
    map.addMarker(option);

  }, function(markers) {

    // Set camera position that include all markers.
    var bounds = [];
    data.forEach(function(POI) {
      bounds.push(POI.position);
    });

    map.moveCamera({
      target: bounds
    }, function() {

    });

  });

});
`

**Comment by wf9a5m75** [comment]
Thank you for providing your code.
I fixed the problem. Please reinstall the plugin (the version is `2.0.0-beta2-20170525-1040`)

**Comment by KimberleeDArmstrong** [comment]
Yay! thanks!

**Comment by KimberleeDArmstrong** [comment]
I would like to buy you a beer also, but am having trouble finding the link. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by wf9a5m75** [comment]
Thank you for offering a beer :)

You can buy a beer for me from here.
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=cordova%2dgooglemaps%2dplugin&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted

----

The `buying a beer` button is in the this page always.
https://github.com/mapsplugin/v2.0-demo

![screen shot 2017-05-25 at 11 42 31 am](https://cloud.githubusercontent.com/assets/167831/26465212/48beabe8-413f-11e7-8b9f-d8119968a986.png)

**Comment by wf9a5m75** [comment]
@KimberleeDArmstrong 

There are couple of updates that are related with your code.

---

`map.getVisibleRegion()` returns the results without callback now:
(But you can still use the old style)

```js
// Before
map.getVisibleRegion(function(latLngBounds) {

});

// After
var latLngBounds = map.getVisibleRegion();
```

---

HtmlInfoWindow is able to use without the `infoWindow` property.
And `setContent()` method is also available.

```js
var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();

var html = "&lt;img src='./House-icon.png' width='64' height='64' &gt;" +
           "&lt;br&gt;" +
           "This is an example";
htmlInfoWindow.setContent(html);

map.addMarker({
  position: {lat: 0, lng: 0}
}, function(marker) {

  marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
    htmlInfoWindow.open(marker);
  });
  marker.trigger(plugin.google.maps.event.MARKER_CLICK);

});
```

---

addTileOverlay() is now become a very easy.
(In your code, you generates lots of ground overlay, but tile overlay is simple)

```js
map.addTileOverlay({

  getTile: function(x, y, zoom) {
    return "../images/map-for-free/" + zoom + "_" + x + "-" + y + ".gif"
  }
}, function(tileOverlay) {

});
```

---

I keep the backward compatibility, so your code should work without problem.
But you can change your code with new code style.

**Comment by marioshtika** [comment]
Thank you so much. It works perfectly.

**Comment by KimberleeDArmstrong** [comment]
Thank you! :-D 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144
