### ISSUE TITLE
Icons does not show in iOS

### ISSUE THREAD

**Issue by marioshtika** [mapsplugin/cordova-plugin-googlemaps#1466]
Hello,

I am using the v2 of the plugin and in android it works perfectly but in iOS it doesn't show the marker (because it doesn't find the path of the icon)

If I import the icon from an external url or as a base64 it works fine. It doesn't work when I want to load an image from my project folder.

I am using ionic v1

my code is:

```js
data.push({
    title: 'title', 
    snippet: 'description',
    styles: {
        maxWidth: "80%"
    },
    position: new plugin.google.maps.LatLng(latitude, longitude), 
    icon:  "./img/markers/blue.png"
});
```

My folder structure is: 
```
www
-- css
-- img
-- -- markers
-- -- -- blue.png
-- js
-- -- controllers
-- -- -- mapController.js
-- lib
-- templates
-- -- map.html
-- index.html
```
Any ideas on why this is happening?

Thank you in advance.

**Comment by vosecek** [comment]
Try this code:
'icon': {
	'url': 'relative path to image from index.html, check platforms/ios/www'
}

Sometimes it does not work for me too, next rebuild with ionic build ios fix it.

**Comment by marioshtika** [comment]
Unfortunately it didn't work.

**Comment by vosecek** [comment]
@marioshtika OK, strange issue, quit the app and load it again in the phone. After install from XCode the image is not loaded, every next start in the iPhone it works.

**Comment by wf9a5m75** [comment]
If your icon file is not on the specified file path, 
the error log message `(error)There is no file at ...` in the Xcode log.
Please check the error log.

And did you execute `$> cordova prepare` before execute your app on your phone?

**Comment by wf9a5m75** [comment]
And also, iOS (UIImage class) does not work with regular png file.

In that case, please try two possible solutions:

- Png optimization for iOS
https://tinypng.com/

- Use gif or jpeg image instead of png

**Comment by MichaelMassalas** [comment]
Hi, I have the same issue on android device.
Here is the log:
java.io.FileNotFoundException: ../assets/images/blueflagpin.png

I also tried with .gif and did run cordova prepare as u suggested, but nothing!

Any advice?

**Comment by marioshtika** [comment]
Still not working.

In Xcode log I see this error

(error)There is no file at '/Users/_________/Library/Developer/CoreSimulator/Devices/EDC06BD7-DC40-4977-8856-B14A013D0BFC/data/Containers/Bundle/Application/34C8BA60-7B00-49F8-A248-641D934F8879/myapp.app/www/index.html#/app/../../img/image-default.jpg'.

Any idea?

Thank you in advance.

**Comment by wf9a5m75** [comment]
As the error log says, there is no image file that you specified.

**Comment by marioshtika** [comment]
The image does exists, I checked it. It just does not recognise the path

**Comment by wf9a5m75** [comment]
ls -l Users/_________/Library/Developer/CoreSimulator/Devices/EDC06BD7-DC40-4977-8856-B14A013D0BFC/data/Containers/Bundle/Application/34C8BA60-7B00-49F8-A248-641D934F8879/myapp.app/www/index.html#/app/../../img/image-default.jpg

**Comment by wf9a5m75** [comment]
Until your project files are provided, there is no way to help your problem.

**Comment by qbix0r** [comment]
Hi, I have the same issue.

`<img src="assets/images/marker-red.png"/>` This works
`defaultMarkerIcon: any = {url: 'assets/images/marker-red.png', size: {width: 20, height: 32}};` This works on android, doesn't on ios.

It **IS** in the resoruces tab and the path is the same. It looks like the plugin can't find it somehow.

**Comment by marioshtika** [comment]
I think there is a problem in the path

Library/Developer/CoreSimulator/Devices/EDC06BD7-DC40-4977-8856-B14A013D0BFC/data/Containers/Bundle/Application/34C8BA60-7B00-49F8-A248-641D934F8879/myapp.app/www/**index.html#/app**/../../img/image-default.jpg

the **"index.html#/app/"** is a url path not a folder path.

I don't know if I helped you with this information.

Does it help to send you my project? How can I send it to you?

Thank you in advance.

**Comment by wf9a5m75** [comment]
BitBucket provide free private git repository.
So you can send your project files without discover your code to public.

If you don't know how to use git repository? Google it.

https://www.google.com/search?q=how+to+upload+code+bit+bucket&oq=how+to+upload+code+bit+bucket

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
If you don't share your project files, I can not help you guys. (In that case, I close this issue)

**Comment by wf9a5m75** [comment]
**One update**

I figured out a problem when you install the `cordova-plugin-wkwebview-engine` plugin and you specify relative path to icon.
Please reinstall the plugin. The latest plugin version is `cordova-plugin-googlemaps 2.0.0-beta2-20170615-1407`

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_...... --no-fetch

$> cordova plugin list
...
cordova-plugin-googlemaps 2.0.0-beta2-20170615-1407
...
```

**Comment by jaufgang** [comment]
I have been having a similar problem but the icon shows up on ios but not android.  

I was able to make it work on Android by using 
```
{url: this.platform.is("android") ? `file:///android_asset/www/${path}` : path}
```

but this shouldn't be necessary and it took a long time to figure this out.

**Comment by wf9a5m75** [comment]
@jaufgang As I commented above, please share your project files on github or bitbucket when you face a problem.

**Comment by jlcarvalho** [comment]
After update to 2.0.0-beta2-20170615-1407 version my icons do not work anymore. With or without wkwebview. I was using base64 icons as a workaround to the relative paths bug, but now this is not working either.

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbacket.

How and why?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment]
@jlcarvalho ping

**Comment by wf9a5m75** [comment]
Since there is no update, I close this issue.
