### ISSUE TITLE
The 2.0 version doesn't works with ionic v1 and crosswalk

### ISSUE THREAD

**Issue by RicardoBer** [mapsplugin/cordova-plugin-googlemaps#1467]
The 2.0 version doesn't works with ionic v1 and crosswalk. Download and prepare the 2.0 demo and maps are shown pretty good. But if you install crosswalk to demo (cordova plugin add cordova-plugin-crosswalk-webview) the maps go away and only shows white screen, any help?

It is not a webview background issue, I put <preference name="BackgroundColor" value="0x00000000"/> in config.xml and you can see the android launcher, icons..., but not the map

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/crosswalk/README.md

**Comment by RicardoBer** [comment]
Many thanks, It works.
