### ISSUE TITLE
Ionic sidemenu error 

### ISSUE THREAD

**Issue by GamalSebaee** [mapsplugin/cordova-plugin-googlemaps#1468]
Side menu Application has error in ionic .
I can't click at any element in side menu

**Comment by frystpingvin** [comment]
@GamalSebaee I had this issue as well recently. Using the v1.X of the plugin you have to use `setClickable()` passing true/false depending on if the menu is opened or not.

I solved it by following the answer [here](https://stackoverflow.com/questions/37215552/how-to-detect-side-menu-open-close-in-ionic-2).

**Comment by wf9a5m75** [comment]
@GamalSebaee Do you use the plugin v1 or v2?

**Comment by GamalSebaee** [comment]
2

**Comment by wf9a5m75** [comment]
Then how did you write your HTML?
Please make an example project and share it on github or bitbucket.

Without sample code, I can not help anything.

**Comment by wf9a5m75** [comment]
ping

**Comment by fripas** [comment]
@wf9a5m75 My code:

**sucursales.scss**
`
ion-app._gmaps_cdv_ .nav-decor {
    background-color: transparent!important;
    display: none!important;
}

page-sucursales {}
`

**sucursales.html**
`<ion-header>
    <ion-navbar color="dark" hideBackButton>
        <ion-icon class="btn-menu" name="menu" (click)="irInicio()"></ion-icon>
        <ion-title>SUCURSALES</ion-title>
    </ion-navbar>
</ion-header>


<ion-content>
    <div #map id="map" style="width:100%; height:100%;"></div>
</ion-content>`

**sucursales.ts**
`import { Component, ViewChild, ElementRef } from '@angular/core';
import { NavController, NavParams, Platform, LoadingController, AlertController, ToastController } from 'ionic-angular';
import { Geolocation } from 'ionic-native';

declare var plugin: any;
declare var cordova: any;

@Component({
  selector: 'page-sucursales',
  templateUrl: 'sucursales.html'
})
export class SucursalesPage {

  map: any;
  latLng: any;
  static marker: any;
  @ViewChild('map') theMap: ElementRef;

  constructor(public navCtrl: NavController, public navParams: NavParams, public platform: Platform, public alertCtrl: AlertController, public loadingCtrl: LoadingController, public toastCtrl: ToastController) {
    platform.ready().then(() => {
      this.loadMap();
    });
  }

  ionViewDidLoad() { }

  loadMap() {

    let mapEle = this.theMap.nativeElement;
    this.map = new plugin.google.maps.Map.getMap(mapEle, {});

    

    // listen to MAP_READY event
    this.map.one(plugin.google.maps.event.MAP_READY, () => {
      if(SucursalesPage.marker != null){
        SucursalesPage.marker.remove();
      }
      Geolocation.getCurrentPosition().then((resp) => {
        this.latLng = new plugin.google.maps.LatLng(resp.coords.latitude, resp.coords.longitude);
        let pos = {
          target: this.latLng,
          zoom: 18
        };
        this.map.moveCamera(pos, _ => {
          let markerOptions = {
            position: this.latLng,
            title: 'Información sin estilos sucursal',
            flat: true
          };
          this.map.addMarker(markerOptions, (markerVar) => {
            SucursalesPage.marker = markerVar;
            markerVar.showInfoWindow();
            this.map.addEventListener(plugin.google.maps.event.MAP_CLICK, (latLng) => {
              SucursalesPage.marker.setPosition(latLng);
              this.latLng = latLng;
            });
          });
        });
      }).catch((error) => {
        this.toastCtrl.create({
          message: 'No se pudo obtener la ubicación actual, se obtendrá una apróximada',
          duration: 3000
        }).present();
        this.map.getMyLocation((latLng) => {
          this.latLng = latLng;
          let pos = {
            target: this.latLng,
            zoom: 18
          };
          this.map.moveCamera(pos, _ => {
            let markerOptions = {
              position: this.latLng,
              title: 'Ubicación Actual',
              flat: true
            };
            this.map.addMarker(markerOptions, (markerVar) => {
              SucursalesPage.marker = markerVar;
              markerVar.showInfoWindow();
              this.map.addEventListener(plugin.google.maps.event.MAP_CLICK, (latLng) => {
                SucursalesPage.marker.setPosition(latLng);
                this.latLng = latLng;
              });
            });
          });
        });
      });
    });

  }

}
`

**Comment by wf9a5m75** [comment]
Could you share your project on github or bitbacket? I'm not familiar with ionic.

**Comment by wf9a5m75** [comment]
https://guides.github.com/introduction/getting-your-project-on-github/

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment]
@fripas If you does not provide your project files on github or bitbucket, I will close this issue.
