### ISSUE TITLE
google map empty

### ISSUE THREAD

**Issue by ammubasha** [mapsplugin/cordova-plugin-googlemaps#147]
Hi,
My map showing only Google logo and zoom icons(+/-) nothing else.what might be the reason

**Comment by montaserfzy** [comment]
The same issue 
Already I have added the SHA1 for android API key then remove google map plugin, add plugin with new api key 

-mac user 
-ionic framework 
-google map stable plugin 

try many times and still empty map 

any help please 

Thanks
