### ISSUE TITLE
Callback performances

### ISSUE THREAD

**Issue by sirhaplo** [mapsplugin/cordova-plugin-googlemaps#1470]
Hi guys,
I'm working on an app with a loots of markers. We can have 1500/2000 markers.
It's ok that the app will be slow in this case, but the problem is the loading time.

We tried a lot of things, we ended up discovering that the markers callback creates a lot of loading time.
When we add the markers, in 5/6 seconds the map is usable, but the UI outside the map is freezed.
We must wait 1/2 minutes waiting with process CPU at 25% and then all becomes usable.

After reading that : https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/835#issuecomment-277937646
We tried to comment out "callbackContext.success(result);" in PluginMarker and everything is much much better.
Obviously nothing work without callbacks, but maybe there is something wrong somewhere
It's seems that it queue up all callbacks and then return to works.
Using addMarker without callback, callback null or function() {} doesn't resolve.

**Comment by wf9a5m75** [comment]
Please don't use this plugin, and make your app with native languages (Java and Objective-c).
This is the best performance way.

**Comment by sirhaplo** [comment]
Dont take this personal, we love so much your work.
It's a bless for our app, and that problem happens in few cases.
I'm working on it now, and with some advices by you, maybe we can improve a bit and then merge our results.
But im new to cordova plugin, have you any idea of what could cause that ?

**Comment by wf9a5m75** [comment]
Use the plugin v2. At least the code is designed faster as much as possible.

And using crosswalk might be better especially on old android devices.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

**Comment by sirhaplo** [comment]
Sure, im using it, and i keep updating on your last updates. 
I didnt testsed Crosswalk for now.
I will try to create a test to simulate the problem

**Comment by wf9a5m75** [comment]
In order to add markers faster as much as possible, use the plugin v2, and store marker icon images in your app or load the same icon(url) as much as possible.

The plugin v2 has cache mechanism for loading icon. So if you use the same icon url, the second marker is added faster.

**Comment by wf9a5m75** [comment]
ping
