### ISSUE TITLE
Map Lagging issue

### ISSUE THREAD

**Issue by kanishkamehta801** [mapsplugin/cordova-plugin-googlemaps#1471]
Hello,

I have a map lagging issue with plugin.google.maps. I had an app with customer and driver. When driver moves, map always shows the current location but map is blurred, it is taking too much time to load, can you please suggest any solution for this as map is taking too much time to load and that is creating a problem.

Thanks in advance.

**Comment by wf9a5m75** [comment]
It means the Google Maps  API can not load the map from the Google's server.
The device must be offline or network troubles. Not related with this plugin.

**Comment by kanishka801mehta** [comment]
So is there any alternative solution to resolve map lagging issue because if the driver is moving with real time then map is taking too much time to load, map is blurred.

**Comment by wf9a5m75** [comment]
Create all tile images as image files (such as png or gif, etc), then store them in to your file (it's going to be large size app) , and load them as tile overlay.

Another solution is drag & drop on the road if the drive route is already fixed.
Then the Google Maps API generates internal cache.
(There is no way to create caches from outside the api).

----

The simplest solution is that the drive use good internet hotspot (such as potable hotspot, something).

**Comment by kanishka801mehta** [comment]
Thanks for your quick response.
