### ISSUE TITLE
How to use Map events in ionic 2??

### ISSUE THREAD

**Issue by yasiramidtech** [mapsplugin/cordova-plugin-googlemaps#1473]
I want to get my current location and use CAMERA_MOVE_START event. How is it possible??
I'm getting error when i use below code. I'm using map current version 1.4.0 and ionic2.

```js
loadMap() {

 // create a new map by passing HTMLElement
 let element: HTMLElement = document.getElementById('map');
 let map: GoogleMap = this.googleMaps.create(element);

// let ionic: LatLng = new LatLng(30.195825588923114,71.42629131674767);
 // listen to MAP_READY event
 map.one(GoogleMapsEvent.MAP_READY).then(
   () => {
     console.log('Map is ready!');
    // map.setMyLocationEnabled(true);
     
      var onSuccess = function (location)
        {
            map.setMyLocationEnabled(true);
            var msg = ["Current your location:\n",
            "latitude:" + location.latLng.lat,
            "longitude:" + location.latLng.lng,
            "speed:" + location.speed,
            "time:" + location.time,
            "bearing:" + location.bearing].join("\n");

            map.animateCamera({
                'target': location.latLng,// { lat: 30.195825588923114, lng: 71.42629131674767 },//location.latLng,
                'tilt': 20,
                'zoom': 16,
                'bearing': 25,
                'duration': 300 // 1/2 seconds
            })
            
             console.log(location.latLng);
            };

        var onError = function (msg)
        {
           // alert("error: " + msg);
        };
        map.getMyLocation(onSuccess, onError);  // i'm getting error on this line

       
        
   }
 );

map.one(GoogleMapsEvent.MAP_CLICK).then( () => 
{
              
      console.log("It is working")         
})

 map.on(GoogleMapsEvent.CAMERA_MOVE_START).then( () => // i'm getting error on this line
{
              
    console.log("It is working")
          
})

 }
```

**Comment by vosecek** [comment]
Do not use Ionic wrapper, use this plugin directly

```
import { Component, ViewChild, ElementRef, ApplicationRef } from '@angular/core';
declare var plugin: any;
@IonicPage()
@Component({
	selector: 'page-map',
	templateUrl: 'map.html', // contains id="mapdiv" id='mapdiv'
})
export class Map {
@ViewChild('mapdiv') mapdiv: ElementRef;
..
this.map = plugin.google.maps.Map.getMap(this.mapdiv.nativeElement, options);
this.map.one(plugin.google.maps.event.MAP_READY, () => {
console.log('initialized');
});
```

**Comment by wf9a5m75** [comment]
>  I'm using map current version 1.4.0 and ionic2.

It seems you use the plugin v1.4.0

Unfortunately, the CAMERA_MOVE_START is not provided for v1.4.0

The plugin v1.4.0 allows only (for map class):
- MAP_CLICK
- MAP_LONG_CLICK
- MY_LOCATION_BUTTON_CLICK
- CAMERA_CHANGE
- CAMERA_IDLE(iOS)
- MAP_READY
- MAP_LOADED(Android)
- MAP_WILL_MOVE(iOS)
- MAP_CLOSE

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Map/README.md#listen-events

**Comment by yasiramidtech** [comment]
Is this possible in next version CAMERA_MOVE_START & CAMERA_MOVE_END will be implement ??
It is very useful events of map.

**Comment by wf9a5m75** [comment]
The v1.x is disconnected.
Please use the v2.0.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md

**Comment by yasiramidtech** [comment]
I will try it.
Thank you

**Comment by battika** [comment]
https://github.com/ionic-team/ionic-native/pull/1424

Check this PR too

**Comment by wf9a5m75** [comment]
@battika great! You saved my time.

I noticed one thing, it seems some events recently added are missed in your PR.

Please check out the release note page.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.0-beta2/README.md

**Comment by battika** [comment]
It's not my PR but I will share your info on the patch request so that the originator will be able to fix it. Thank you for your great plugin!

**Comment by tracedaily** [comment]
Any idea how I can use the code from that PR?

**Comment by tracedaily** [comment]
@wf9a5m75 here's another PR for the Ionic Native wrapper:

https://github.com/ionic-team/ionic-native/pull/1166

**Comment by wf9a5m75** [comment]
PRs are incorrect.

**Comment by wf9a5m75** [comment]
And I don't touch the ionic wrapper at all.
