### ISSUE TITLE
Using htmlInfoWindow in version 2.

### ISSUE THREAD

**Issue by Mrjaid** [mapsplugin/cordova-plugin-googlemaps#1475]
Hello I have being battling with how to use the htmlInfoWindow , I actually uninstalled version and installed version 2, but I have not being able to get the htmlInfoWindow  to work, I copied the sample code from the Documentation below : 

```js
var div = document.getElementById("maplocation");
    var map = plugin.google.maps.Map.getMap(div);
    map.one(plugin.google.maps.event.MAP_READY, function () {
        var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();

        var html = [
            'This is &lt;b&gt;Html&lt;/b&gt; InfoWindow',
            '&lt;br&gt;',
            '&lt;button onclick="javascript:alert(\'clicked!\');"&gt;click here&lt;/button&gt;',
        ].join("");
        htmlInfoWindow.setContent(html);

        map.addMarker({
            position: {lat: 0, lng: 0},
            draggable: true
        }, function (marker) {

            marker.on(plugin.google.maps.event.MARKER_CLICK, function () {
                htmlInfoWindow.open(marker);
            });
            marker.trigger(plugin.google.maps.event.MARKER_CLICK);

        });
    });
```
but I keep getting the marker without the info window.

<img src="https://cloud.githubusercontent.com/assets/19732591/26650712/3780a518-4642-11e7-87be-161e248fb0c0.png" width="250">

please I need help ASAP, this is driving me crazy.
Many Thanks

**Comment by wf9a5m75** [comment]
Could you show me the output of `$> cordova plugin list`?

**Comment by Mrjaid** [comment]
com.googlemaps.ios 2.2.0-fixed "Google Maps SDK for iOS"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta2-20170510-1500 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-storage 2.0.3 "Cordova sqlite storage plugin"

**Comment by wf9a5m75** [comment]
Ah, the plugin you installed is too old. The v2.0 has been updating frequently.

The latest version of the maps plugin v2.0 is `2.0.0-beta2-20170531-1115`.

Here is mine.

```
$ cordova plugin list
com.googlemaps.ios 2.2.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.0.6 "Console"
cordova-plugin-googlemaps 2.0.0-beta2-20170531-1115 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```

**Comment by wf9a5m75** [comment]
Please reinstall the plugin. The problem should be gone.

**Comment by Mrjaid** [comment]
ok Many thanks, let me try that

**Comment by wf9a5m75** [comment]
The usage of HTMLInfoWindow was changed on May/22, but your plugin version is May/10. That's why.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.0-beta2/README.md#may222017

**Comment by Mrjaid** [comment]
please kindly give me the URL for version 2,

**Comment by wf9a5m75** [comment]
Do you mean you want to know how to install the plugin v2?

If so, follow the steps:

```
$> cordova plugin rm cordova-plugin-googlemaps

$> npm cache clean

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps \
     --variable API_KEY_FOR_ANDROID="<YOUR KEY>" \
     --variable API_KEY_FOR_IOS="<YOUR KEY>" \
     --nofetch
```

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/README.md

**Comment by Mrjaid** [comment]
Many thanks, your a soul saver.... I would try it and get back to you.. much regards

**Comment by Mrjaid** [comment]
followed the instruction and now all I get is a white screen, the map does not even load..

**Comment by wf9a5m75** [comment]
Is there JS errors or error messages?

**Comment by Mrjaid** [comment]
it was a js error, copied code from https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.0-beta2/README.md#may222017 without defining map variable

**Comment by wf9a5m75** [comment]
Ah, I see.

**Comment by Mrjaid** [comment]
but am still not able to see the htmlInfoWindow .. any sample code??

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/HtmlInfoWindow/newHtmlInfoWindow/README.md

**Comment by wf9a5m75** [comment]
Also 
https://github.com/mapsplugin/v2.0-demo/blob/master/www/HtmlInfoWindow/newHtmlInfoWindow.html

**Comment by Mrjaid** [comment]
used this : https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/HtmlInfoWindow/newHtmlInfoWindow/README.md
but was unable to get the HtmlInfoWindow to be displayed. only  the marker was displayed on the map

**Comment by wf9a5m75** [comment]
Please inspect your app more carefully.

If you doubt me this is plugin's bug, try the demo apk.
The demo apk works perfectly.

https://github.com/mapsplugin/v2.0-demo/blob/master/cordova-googlemaps-v2-demo_16.apk?raw=true

**Comment by Mrjaid** [comment]
I have inspected my code and discovered I used a canvas instead of a div, I made the change and the htmlinfowindow now displays, however it displays them as raw html codes

**Comment by wf9a5m75** [comment]
If you pass String (`typeof yourHTML == "string"`), the plugin displays HTML.
Otherwise, the plugin displays as object.

```js
  var html = [
    'This is &lt;b&gt;Html&lt;/b&gt; InfoWindow',
    '&lt;br&gt;',
    '&lt;button onclick="javascript:alert(\'clicked!\');"&gt;click here&lt;/button&gt;',
  ].join("");
  htmlInfoWindow.setContent(html);
```

Here is the logic:
```js
      var content = self.get("content");
      if (typeof content === "string") {
          contentBox.style.whiteSpace="nowrap";
          contentBox.innerHTML = content;
      } else {
          if (!content) {
            contentBox.innerText = "";
          } else if (content.nodeType === 1) {
            contentBox.appendChild(content);
          } else {
            contentBox.innerText = content;
          }
      }
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/d9e40dda01ed6bfed54edb81a6d01422b3211de4/www/HtmlInfoWindow.js#L74-L86

**Comment by wf9a5m75** [comment]
@Mrjaid ping

**Comment by Mrjaid** [comment]
So sorry for the delay.. have being so so busy... bug have being resolved.. all working fine now,..
many thanks

**Comment by wf9a5m75** [comment]
:+1
