### ISSUE TITLE
Ionic 3.0.1 - "Some input files use or override a deprecated API"

### ISSUE THREAD

**Issue by SKempin** [mapsplugin/cordova-plugin-googlemaps#1476]
When using plug 1.4 I am now reicivng this issue with Ionic 3.0.1:

```
Error: /Repository/location-app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Repository/location-app/platforms/android/src/plugin/google/maps/PluginUtil.java:135: error: cannot access AbstractSafeParcelable
    Builder builder = LatLngBounds.builder();
                                  ^
  class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.2 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by wf9a5m75** [comment]
Some plugins you use specifies older version of the Google Play Services.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/plugin.xml#L145-L146

The plugin v2 requires  v10.0 or higher, or the plugin v1 requires v9.8.0.

Please check your all plugins.

**Comment by SKempin** [comment]
I'm confused, which plugins?

I have updated to the latest with all those listed and am still getting the same error:

`platforms/android/src/plugin/google/maps/PluginUtil.java:135: error: cannot access AbstractSafeParcelable
    Builder builder = LatLngBounds.builder();`

`
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.2 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
`

**Comment by wf9a5m75** [comment]
Don't ask me about ionic. But the Google Play Services version is old. That's the reason.


https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1247
