### ISSUE TITLE
ver 2 Will be compatible with ionic 2

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1477]
when will you have version 2 ready?

**Comment by wf9a5m75** [comment]
In this summer.
https://github.com/mapsplugin/cordova-plugin-googlemaps#version-20-beta-roadmap

**Comment by wuilmerj24** [comment]
is compatible with ionic 2? 
Thank you

**Comment by wf9a5m75** [comment]
Some users already use the plugin v2 with ionic 2.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md

**Comment by wuilmerj24** [comment]
Thanks
