### ISSUE TITLE
App crash  with uncaught exception of type NSException

### ISSUE THREAD

**Issue by erpxit** [mapsplugin/cordova-plugin-googlemaps#1478]
I have a complex app using  your google map plugin.
I build both with 1.4 and with all 2 beta realase from 2.0.0.beta to latest 2.0.0-beta2-20170531-1320
the app always crash with:

```
2017-06-03 12:07:48.225441+0200 SaluberAMB[450:56108] -[NSNull doubleValue]: unrecognized selector sent to instance 0x1acb05ef8
2017-06-03 12:07:48.230284+0200 SaluberAMB[450:56108] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull doubleValue]: unrecognized selector sent to instance 0x1acb05ef8'
*** First throw call stack:
(0x1872c2fe0 0x185d24538 0x1872c9ef4 0x1872c6f54 0x1871c2d4c 0x10018b6d8 0x187d91814 0x187cd6770 0x187cc6b28 0x187d93bb0 0x100e55a10 0x100e5ab78 0x1872710c8 0x18726ece4 0x18719eda4 0x188c08074 0x18d452058 0x1000341dc 0x1861ad59c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

// more details from xcode //
libsystem_kernel.dylib`__pthread_kill:
    0x1862bd00c <+0>:  mov    x16, #0x148
    0x1862bd010 <+4>:  svc    #0x80
->  0x1862bd014 <+8>:  b.lo   0x1862bd02c               ; <+32>
    0x1862bd018 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1862bd01c <+16>: mov    x29, sp
    0x1862bd020 <+20>: bl     0x1862a086c               ; cerror_nocancel
    0x1862bd024 <+24>: mov    sp, x29
    0x1862bd028 <+28>: ldp    x29, x30, [sp], #0x10
    0x1862bd02c <+32>: ret    

libsystem_pthread.dylib`start_wqthread:
    0x186382ca8 <+0>: bl     0x186382cb8               ; _pthread_wqthread
    0x186382cac <+4>: nop    

it happen on ipad air 1 with iOS 10.3.2

on simulator it never happen and the app works great.

Build with:
Xcode :  8.3.2 (8E2002)
Cordova 7.0.1
Cordova ios@4.4.0

Cordova Plugin-List
{
    "cordova-plugin-whitelist": "1.3.2",
    "cordova-plugin-compat": "1.1.0",
    "cordova-plugin-file": "4.3.3",
    "cordova-media-with-compression": "2.1.1",
    "cordova-plugin-app-version": "0.1.9",
    "cordova-plugin-brightness": "0.1.5",
    "cordova-plugin-camera-preview": "0.9.0",
    "cordova-plugin-device": "1.1.6",
    "cordova-plugin-file-transfer": "1.6.3",
    "cordova-plugin-keyboard": "1.1.5",
    "cordova-plugin-tts": "0.2.3",
    "cordova-sqlite-storage": "2.0.4",
    "cordova-plugin-battery-status": "1.2.4",
    "cordova-plugin-device-name": "1.2.1",
    "cordova-plugin-geolocation": "2.4.3",
    "com.googlemaps.ios": "2.2.0-fixed",
    "cordova-plugin-googlemaps": "2.0.0-beta2-20170531-1320"
};

Do you have any idea on what's is going on, consider that if i dont use your plugin, the app never crash.

**Comment by wf9a5m75** [comment]
[NSNull doubleValue] means the plugin requires some value as double, but you pass null.

**Comment by wf9a5m75** [comment]
Please take a screen capture of the xcode when your app crash.
And thank you for sharing your code, but I appreciate if you share whole project files on github or bitbucket.

Important for debugging is that reproduce your issue.
Without your whole project files, I can not build your project, and I can not reproduce your issue.

Bitbucket provides private git repository as free.
https://www.youtube.com/watch?v=BtEvnE79jxY

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by erpxit** [comment]
Heelo, thanks for your kind answer…

you can download the full project here :

http://erpx.it/saluber-amb8.zip <http://erpx.it/saluber-amb8.zip>

the app will prompt you for userid and password , you can use this account

User = amb8
pass = 1234

for privacy reason i have to inform you that when u will get loggedin the app will start to trace your position…..  but i will delete all data from db, we are still in developing ….

anyhow i feel to offer you another beer…. thanks again for everythings…..!!!

i also attached on this email 3 screenshoot of the xcode screen when the app crash….

take care!!!!

carlo

**Comment by erpxit** [comment]
hello Masashi i shared my full code with you on bitbucket
user and pass to login with app on READ.ME

here attached log files.... and screenshot
![1](https://cloud.githubusercontent.com/assets/28953840/26760916/291e0e4a-4924-11e7-9652-8f17c503af8a.jpeg)

[xcode.log.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1050256/xcode.log.zip)


Beer !! beer ! beer for you!!!! thank you!

**Comment by erpxit** [comment]
I found the solution!!
i was passing Nan Value to moveCamera on bearing.
i think something change on cordova.geolocation.plugin before the upgrade the pass null vale and not Nan, fixing javascript to transform compassdir from Nan to 0 fix the crash!

thank u anyhow for your time !!!

regrds!!! anyhow more beer for you!!!!!

**Comment by wf9a5m75** [comment]
Sounds good.
By the way, in the above screenshot, I need to see no4 `moveCamera` instead of `0 __pthread_kill`.
Because it's plugin's code.
(But you already figured out the reason. So it's OK anyway this time)

------

You can buy beer for me from the [Donate|Paypal] button anytime :)
https://github.com/mapsplugin/v2.0-demo/blob/master/README.md#buy-me-a-beer
