### ISSUE TITLE
Map options beta 2 ionic 3

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1480]
Gesture, camera?

**Comment by wuilmerj24** [comment]
help me please @wf9a5m75

**Comment by wf9a5m75** [comment]
Please read documents.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

**Comment by wuilmerj24** [comment]
@wf9a5m75 My friend, I have a problem. Add the div for the map inside the <ion-content> and the element is placed above the map, but if I leave in the page only the div of the map and if it works.

**Comment by wf9a5m75** [comment]
Could you share your project files (all files are included) on github or bitbacket?


Why and How? Read here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wuilmerj24** [comment]
@wf9a5m75  https://github.com/wuilmerj24/prueba-maps-nativo

**Comment by wf9a5m75** [comment]
Thanks. I will check it later.
(I've been traveling in Japan. Please wait for a while)

**Comment by wuilmerj24** [comment]
@wf9a5m75 ok thanks.

**Comment by wf9a5m75** [comment]
I checked your project, and I noticed the nav-decor blocks this plugin.

CSS solution is here. Please try it.
https://github.com/ionic-team/ionic/issues/7205#issuecomment-299481840

**Comment by wuilmerj24** [comment]
@wf9a5m75 Friend does not work for me, I will update the repo

**Comment by wuilmerj24** [comment]
@wf9a5m75 https://github.com/wuilmerj24/prueba-maps-nativo

**Comment by wf9a5m75** [comment]
```css
.nav-decor{
   display: none !important;
}
```

**Comment by wf9a5m75** [comment]
Okay, I finally figured out what the problem is.
The ionic3 framework covers the map view with many elements.
I added some code to prevent this issue.
Please reinstall the plugin. I confirmed the issue was resolved (only checked iOS).
The latest version is `cordova-plugin-googlemaps 2.0.0-beta2-20170531-1320`.

**Comment by wuilmerj24** [comment]
@wf9a5m75 ok. I am going to try

**Comment by wuilmerj24** [comment]
@wf9a5m75 When trying to install the plugin t gives me this error Error: Can not find plugin.xml for plugin "package". Please try adding it again.

**Comment by wuilmerj24** [comment]
@wf9a5m75 How do I install that version?

**Comment by wuilmerj24** [comment]
@wf9a5m75 Friend I installed the plugins but I installed the versio: 2.0.0-beta2-20170606-1807 will be well? Now I need to place a search box on top of the map how can I do it? Since the map is superimposed over all the elements that are in the content

**Comment by wuilmerj24** [comment]
Hi. I've solved the search box above the map by adding z-index: 2! Important; To the input search class. How can I change the position of the button for my location?

**Comment by wf9a5m75** [comment]
No way is provided.

**Comment by wuilmerj24** [comment]
@wf9a5m75 it's not possible?

**Comment by wf9a5m75** [comment]
Ionic3 blocks the maps plugin touch mechanism.
Adding Z-index property is a good way to solve this issue.

**Comment by wf9a5m75** [comment]
The location button is provided by native API, not this plugin.
Since Google does not provide the way, no way.

**Comment by wuilmerj24** [comment]
Ok if it was driving me crazy 
OK thanks.

**Comment by wuilmerj24** [comment]
@wf9a5m75 Can you change the circumference of the icon of my location?

**Comment by wf9a5m75** [comment]
No. It is provided by Google. Not this plugin.
If you want to change the design etc, you need to implement your own way by yourself.

**Comment by wuilmerj24** [comment]
ok thanks
