### ISSUE TITLE
Ionic issues 2 and google maps v2

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1481]
The problem is that if I add the structure of the page I can not click on the map, but if I delete the whole structure of the page (ion-header, ion-content) if it works

**Comment by wuilmerj24** [comment]
help me please @wf9a5m75

**Comment by vosecek** [comment]
@wuilmerj24 provide your code

**Comment by wuilmerj24** [comment]
@vosecek https://github.com/wuilmerj24/prueba-maps-nativo

**Comment by wf9a5m75** [comment]
Since this talk is disconnected at 
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1480

I close this issue.

**Comment by wf9a5m75** [comment]
Since this talk is disconnected at 
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1480

I close this issue.
