### ISSUE TITLE
plugin.google.maps do not exist

### ISSUE THREAD

**Issue by patrickboulay** [mapsplugin/cordova-plugin-googlemaps#1482]
Hi,

I migrate from the master branch to the multiple_maps and I did some changes like the documentation said. When I try to call the plugin, it said that plugin.google.maps do not exist.Do I suppose to call the plugin in another way?

Im using cordova 7.0.1

**Comment by vosecek** [comment]
check this: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment]
@patrickboulay Please share your project files on github or bitbucket.

And one more thing, as you may know, this plugin does not work on browser. Only work on Android and iOS.

**Comment by wf9a5m75** [comment]
@patrickboulay If you don't share your project files, I can not help you because I can not confirm the issue.
Please share your project files.

How and why?
Read #1479

**Comment by patrickboulay** [comment]
Im in vacation, i let you know when im back!

Le 2017-06-22 5:04 AM, "Masashi Katsumata" <notifications@github.com> a
écrit :

**Comment by wf9a5m75** [comment]
Are you still in vacation?

**Comment by patrickboulay** [comment]
Yes! For still 2 Weeks! Sorry :)

Le 2017-07-06 8:25 PM, "Masashi Katsumata" <notifications@github.com> a
écrit :

**Comment by wf9a5m75** [comment]
Have a good vacation.

**Comment by wf9a5m75** [comment]
ping

**Comment by patrickboulay** [comment]
Hey!
Im back from vacation! Im currently on some emergencies on my application,
I let you know when im back on the map part.

Pat

**Comment by wf9a5m75** [comment]
ok

**Comment by wf9a5m75** [comment]
Can I close this issue?

**Comment by patrickboulay** [comment]
You can, I will write a new one if I have my problem again. Sorry about
that, I dont have time right now to investigate!

Btw, thats for the plugin!

On Thu, Jul 27, 2017 at 6:18 PM, Masashi Katsumata <notifications@github.com
