### ISSUE TITLE
Smooth marker animation

### ISSUE THREAD

**Issue by yasiramidtech** [mapsplugin/cordova-plugin-googlemaps#1484]
How to move marker with smooth animation from one latlng to another ??
I'm using map 2.0.0-beta

**Comment by wf9a5m75** [comment]
Check out here.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/utilities/geometry/spherical/interpolate/README.md

**Comment by UlisesCeca** [comment]
I'd like to repone this as that link is not available anymore and I can't find any way to smoothly animate the marker to make it look cooler as the user walks
