### ISSUE TITLE
App crash on map.remove() while markers are being created

### ISSUE THREAD

**Issue by qbix0r** [mapsplugin/cordova-plugin-googlemaps#1485]
Hi.

Is it possible to avoid the crash that accurs when you call map.remove() and markers are being created in the same time? 

Let me show what I'm doing in my app.

``` typescript
temp.forEach((v, k) => {
      this.createMarkerFromObject(v);
    });
```

``` typescript
  createMarkerFromObject(object: any) {
    this.map.addMarker({
      'position': {
        lat: object.location.coordinates[1],
        lng: object.location.coordinates[0]
      },
      icon: this.defaultMarkerIcon
    }, (marker) => {
      marker.setDisableAutoPan(true);
      console.log('marker created', marker);
      marker.on(plugin.google.maps.event.MARKER_CLICK, () => {
        this.navCtrl.push('DetailsPage', {objects: [object], index: 0});
      });
    });
  }
```

Creating a big amount of markers takes some time, and it's made in a native thread. What if I want to leave the map page and call map.remove() when markers are still being created? Is there some kind of map event I can use to safely call map.remove()?

That's the error I get when removing map

> java.lang.NullPointerException: Attempt to read from field 'plugin.google.maps.MyPluginLayout plugin.google.maps.CordovaGoogleMaps.mPluginLayout' on a null object reference
    at plugin.google.maps.MyPlugin$1.run(MyPlugin.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)

If you need, I can provide soon an example project.

Edit:
Also, I assume this is normal?

> Task android.os.AsyncTask$3@2affe92 rejected from java.util.concurrent.ThreadPoolExecutor@c406cc3[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 2]

**Comment by wf9a5m75** [comment]
Of course, you have to wait until the process is finished.

**Comment by KimberleeDArmstrong** [comment]
Does map.clear() take a callback function for when it is complete? I think this maybe whats causing my crashes. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by qbix0r** [comment]
The thing is, it's hard do check if all my markers were created if I keep getting the concurrency error. Is there any way to avoid it?

> Task android.os.AsyncTask$3@2affe92 rejected from java.util.concurrent.ThreadPoolExecutor@c406cc3[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 2]

So, even if I do a simple check on page leave (just an example)
if(toCreate == created)
  map.remove();

map.remove() won't execute, because not all markers were created.

**Comment by wf9a5m75** [comment]
Please read.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseArrayClass/constructor/README.md

**Comment by qbix0r** [comment]
Ok, I tried your apprach with BaseArrayClass, but the result is the same :( 
Am I doing something wrong?

``` typescript
    var positionList = new plugin.google.maps.BaseArrayClass(temp);
	
    console.log('position list get array', positionList.getArray());
    let that = this;

    positionList.map(function(object, cb) {
      that.mapObject.addMarker({
        'position': {lat: object.location.coordinates[1],
          lng: object.location.coordinates[0]},
        'icon': that.defaultMarkerIcon
      }, cb)
    }, function(markers) {

      console.log('created markers', markers);

    });
```

I'm still getting the concurrency error at random when creating a lot (150+) markers. Sometimes it is, sometimes not

console output of my code when no error
```
position list get array (195) [Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object…]

created markers (195) [Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker, Marker…]
```

console output of my code on error (as you can see the second console.log is not getting called)
```
position list get array (195) [Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object…]
BaseClass.js:130 Task android.os.AsyncTask$3@5b4c4cc rejected from java.util.concurrent.ThreadPoolExecutor@191dba3[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 2]
BaseClass.js:130 Task android.os.AsyncTask$3@3b62315 rejected from java.util.concurrent.ThreadPoolExecutor@191dba3[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 2]
{ REMOVED }
BaseClass.js:130 Task android.os.AsyncTask$3@afd26f3 rejected from java.util.concurrent.ThreadPoolExecutor@191dba3[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 2]
```

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbucket.

How and why? Read here please.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by qbix0r** [comment]
Ok, I'm preparing an example project right now.

While creating I found out when the concurrency error appears. It shows when you are creating ~150+ markers and use external url for the icon image. #1483
This generates error: 
`{url: 'https://cdn4.iconfinder.com/data/icons/ios7-active-tab/512/map_marker-512.png', size: {width: 28, height: 28}};`

This doesn't (but this icon works only on android, not ios; and that's why I was using external images):
`{url: 'assets/marker-red.png', size: {width: 28, height: 28}};`

I'll prepare this project anyway and link it here because I'm having other issues mentioned in issues here on github:

- Custom icon doesn't work on IOS #1466
- Some elements are not clickable on IOS (I think it's because of removing / adding them to DOM on the fly)
- Some crash scenarios

**Comment by wf9a5m75** [comment]
Where can I see your code?

**Comment by qbix0r** [comment]
Here is the project
https://github.com/qbix0r/cordova-plugin-googlemaps-issues

Problem with concurrency on android you can see on 'Map' page (there is external icon url used).

Problem with custom IOS icons you can see on 'Map IOS icons' page.
2017-06-13 12:43:43.335491+0200 MapIssues[2150:2553662] (error)There is no file at 'http:/localhost:8080/var/containers/Bundle/Application/A5B7DC2F-ADE8-4576-9873-54481AD202BB/MapIssues.app/www/assets/marker-red.png'.
That's the error I get, but if I use the same file somewhere within _img_ it works (path is the same, look at screenshot)
![obraz](https://user-images.githubusercontent.com/22236267/27079495-1efa20c8-5038-11e7-8dcc-8a6750a7e45c.png)

Let me know if you run into any problems running this project (it's ionic3).

Also, I'll update it when I manage to reproduce more bugs (can't click on some buttons in my main project).
Thanks for your help

**Comment by wf9a5m75** [comment]
Thank you for sharing your project.

I figured out a problem when you install the `cordova-plugin-wkwebview-engine` plugin and you specify relative path to icon.
Please reinstall the plugin. The latest plugin version is `cordova-plugin-googlemaps 2.0.0-beta2-20170615-1407`

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_...... --no-fetch

$> cordova plugin list
...
cordova-plugin-googlemaps 2.0.0-beta2-20170615-1407
...
```

I haven't checked Android case yet. Since I have been traveling, please wait for a while.

**Comment by wf9a5m75** [comment]
@qbix0r ping

**Comment by wf9a5m75** [comment]
Since there is no update and I already fixed the issue, I close this issue.
