### ISSUE TITLE
Cannot press button in ionic header bar when header bar overlaps the map div (v2.0 beta)

### ISSUE THREAD

**Issue by JeffreyJamesMMM** [mapsplugin/cordova-plugin-googlemaps#1487]
I have an ionic app where I have a map div that only takes up a portion of the screen and the content is scrollable. I have a header bar which has buttons and when the user scrolls the screen, placing the map div beneath the bar, the user press events propagate to the map instead of the button.

I tried setting a z-index on the button and also on the element wrapping the button to try to get it to work but it did not fix the problem.

I created a github repo with a demo of the issue,
[https://github.com/JeffreyJamesMMM/OverlapMap](url)

**Comment by wf9a5m75** [comment]
Do you use ionic2 or ionic3

**Comment by JeffreyJamesMMM** [comment]
I am using ionic 1

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbacket.

How and why?
#1479

**Comment by JeffreyJamesMMM** [comment]
The github link is in the original comment for the issue and here it is again: [https://github.com/JeffreyJamesMMM/OverlapMap](url)

**Comment by wf9a5m75** [comment]
The link is 304

**Comment by JeffreyJamesMMM** [comment]
I'm sorry, I incorrectly formatted the markdown. [https://github.com/JeffreyJamesMMM/OverlapMap](https://github.com/JeffreyJamesMMM/OverlapMap) should work!

**Comment by wf9a5m75** [comment]
Thank you. I check it later. ( I have been traveling currently. Please wait for a while. I check issues one by one)

**Comment by JeffreyJamesMMM** [comment]
Thank you, Masashi!

**Comment by wf9a5m75** [comment]
Thank you for waiting. I will check your project today.

**Comment by wf9a5m75** [comment]
Please uninstall the current plugin and reinstall the latest version.

**Comment by JeffreyJamesMMM** [comment]
Ok so I tried the latest version and I could press the button in the header when it overlaps the map BUT I can't press the map anymore.

**Comment by wf9a5m75** [comment]
I can touch both map and the button.
![1487](https://user-images.githubusercontent.com/167831/27490906-fe5d4984-57f4-11e7-9969-c7ddd476328f.gif)

**Comment by JeffreyJamesMMM** [comment]
Ok. I tested it with genymotion (android os v4.4.4) and it didn't work but when I tried it on a samsung s5 (android os v5.0) it worked.

I just tested it on another physical device (android os v4.4.2) and it does not work. So I think it's an android v4.* problem.

**Comment by wf9a5m75** [comment]
I see. I will check the code again after go back to my home.

**Comment by wf9a5m75** [comment]
I figured out the reason. I misunderstand [the zIndex of the stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

Please reinstall the plugin.

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ... --no-fetch

$> cordova plugin list
...
cordova-plugin-googlemaps 2.0.0-beta2-20170623-1615 "cordova-plugin-googlemaps"
...

**Comment by wf9a5m75** [comment]
Opps, sorry. I forgot to update the getZIndex() in Common.js yesterday.
Please reinstall the plugin

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ... --no-fetch

$> cordova plugin list
...
cordova-plugin-googlemaps 2.0.0-beta2-20170624-1408 "cordova-plugin-googlemaps"
...
```

This is the screen record of Android 4.4

![1487](https://user-images.githubusercontent.com/167831/27511978-1afbfdae-58e7-11e7-81f2-ad0cbf985400.gif)

**Comment by wf9a5m75** [comment]
iOS also worked with `cordova-plugin-googlemaps 2.0.0-beta2-20170624-1408`

![1487](https://user-images.githubusercontent.com/167831/27512038-14e30492-58e9-11e7-926e-1b460709fae1.gif)

**Comment by wf9a5m75** [comment]
ping

**Comment by JeffreyJamesMMM** [comment]
Hello Masashi, I haven't been able to go back and try it but I will try it again sometime today or tomorrow for certain.

**Comment by wf9a5m75** [comment]
Got it

**Comment by JeffreyJamesMMM** [comment]
That fixed it! It works in Android 4.x/Android 5.x/iOS 10.*. Thank you for helping with this bug.
