### ISSUE TITLE
Draw result polyline of a google maps v3a route

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1488]
I'm using DirectionsService to calculate the route. How I could draw the polyline of the route result.`var directionsService = new google.maps.DirectionsService();
  var directionsDisplay = new google.maps.DirectionsRenderer();
  directionsService.route({
    origin: new google.maps.LatLng(51.269776, 1.061326),
    destination: new google.maps.LatLng(51.30118, 0.926486),
    waypoints: [{
      stopover: false,
      location: new google.maps.LatLng(51.263439, 1.03489)
    }],
    travelMode: google.maps.TravelMode.DRIVING
  }, function(response, status) {
    if (status === google.maps.DirectionsStatus.OK) {
      // directionsDisplay.setDirections(response);
      
    } else {
      window.alert('Directions request failed due to ' + status);
    }
  });`

**Comment by wf9a5m75** [comment]
This plugin does not support the result of the direction.

**Comment by wuilmerj24** [comment]
I know that. The DirectionsServices I'm using javascript. But I solved it. What it required was to pass the coordinates of the route to the polyline so that I draw it in the street, not in a straight line. Thank you

**Comment by guillermogfer** [comment]
@wuilmerj24 could you share some code you used to solve this situation?

**Comment by wuilmerj24** [comment]
@guillermogfer hello uses google web services and a polilinea.setPoint(resultGoogle).
I can share the code later that I'm away from home

**Comment by guillermogfer** [comment]
Ok, thank you! you guided me in the right direction :)

**Comment by wuilmerj24** [comment]
@guillermogfer give me your email

**Comment by guillermogfer** [comment]
guillermogfer@gmail.com

**Comment by wuilmerj24** [comment]
@guillermogfer I already sent the mail

**Comment by Tinway** [comment]
Send it to me, too. tinway@mail.ru

**Comment by Tinway** [comment]
@wuilmerj24 Send me too. tinway@mail.ru

**Comment by wuilmerj24** [comment]
@guillermogfer ready

**Comment by wuilmerj24** [comment]
@guillermogfer did you receive my email?

**Comment by Tinway** [comment]
`var directionsService = new google.maps.DirectionsService();
var directionsDisplay = new google.maps.DirectionsRenderer();
directionsService.route({
origin: new google.maps.LatLng(53.1827345, 44.0108463),
destination: new google.maps.LatLng(53.2130357, 44.9675273),
travelMode: google.maps.TravelMode.DRIVING
}, function(response, status) {
if (status === google.maps.DirectionsStatus.OK) {
var gRoute = response.routes[0].overview_path;
var route = [];
for (var i = 0; i < gRoute.length; i++) {
route.push(new plugin.google.maps.LatLng(gRoute[i].lat(), gRoute[i].lng()));
}
map.addPolyline({
points: route,
'color' : '#000000',
'width': 5,
 'geodesic': true,
'clickable': true // default = false
}, function(polyline) {
var idx = 0;
polyline.on(plugin.google.maps.event.POLYLINE_CLICK, function(latLng) {
polyline.setStrokeWidth(20);
});
});`

**Comment by Tinway** [comment]
`var directionsService = new google.maps.DirectionsService();
var directionsDisplay = new google.maps.DirectionsRenderer();
directionsService.route({
	origin: new google.maps.LatLng(53.1827345, 44.0108463),
	destination: new google.maps.LatLng(53.2130357, 44.9675273),
	travelMode: google.maps.TravelMode.DRIVING
}, function(response, status) {
	if (status === google.maps.DirectionsStatus.OK) {
		var gRoute = response.routes[0].overview_path;
		var route = [];
		for (var i = 0; i < gRoute.length; i++) {
			route.push(new plugin.google.maps.LatLng(gRoute[i].lat(), gRoute[i].lng()));
		}
		map.addPolyline({
			points: route,
			'color' : '#000000',
			'width': 5,
			'geodesic': true,
			'clickable': true
		}, function(polyline) {
			var idx = 0;
			polyline.on(plugin.google.maps.event.POLYLINE_CLICK, function(latLng) {
				polyline.setStrokeWidth(20);
			});
		});
	} else {
		alert('Directions request failed due to ' + status);
	}
});`

**Comment by Tinway** [comment]
> var directionsService = new google.maps.DirectionsService();
var directionsDisplay = new google.maps.DirectionsRenderer();
directionsService.route({
	origin: new google.maps.LatLng(53.1827345, 44.0108463),
	destination: new google.maps.LatLng(53.2130357, 44.9675273),
	travelMode: google.maps.TravelMode.DRIVING
}, function(response, status) {
	if (status === google.maps.DirectionsStatus.OK) {
		var gRoute = response.routes[0].overview_path;
		var route = [];
		for (var i = 0; i < gRoute.length; i++) {
			route.push(new plugin.google.maps.LatLng(gRoute[i].lat(), gRoute[i].lng()));
		}
		map.addPolyline({
			points: route,
			'color' : '#000000',
			'width': 5,
			'geodesic': true,
			'clickable': true
		}, function(polyline) {
			var idx = 0;
			polyline.on(plugin.google.maps.event.POLYLINE_CLICK, function(latLng) {
				polyline.setStrokeWidth(20);
			});
		});
	} else {
		alert('Directions request failed due to ' + status);
	}
});

**Comment by Tinway** [comment]
_var directionsService = new google.maps.DirectionsService();
var directionsDisplay = new google.maps.DirectionsRenderer();
directionsService.route({
	origin: new google.maps.LatLng(53.1827345, 44.0108463),
	destination: new google.maps.LatLng(53.2130357, 44.9675273),
	travelMode: google.maps.TravelMode.DRIVING
}, function(response, status) {
	if (status === google.maps.DirectionsStatus.OK) {
		var gRoute = response.routes[0].overview_path;
		var route = [];
		for (var i = 0; i < gRoute.length; i++) {
			route.push(new plugin.google.maps.LatLng(gRoute[i].lat(), gRoute[i].lng()));
		}
		map.addPolyline({
			points: route,
			'color' : '#000000',
			'width': 5,
			'geodesic': true,
			'clickable': true
		}, function(polyline) {
			var idx = 0;
			polyline.on(plugin.google.maps.event.POLYLINE_CLICK, function(latLng) {
				polyline.setStrokeWidth(20);
			});
		});
	} else {
		alert('Directions request failed due to ' + status);
	}
});_

**Comment by wuilmerj24** [comment]
@guillermogfer I do not understand

**Comment by guillermogfer** [comment]
what?

**Comment by kpwa** [comment]
@wuilmerj24 can u please share code how uv achieved this?

**Comment by wuilmerj24** [comment]
@kpwa give me your email

**Comment by limkimsan** [comment]
@wuilmerj24 , can you please share me your code? Thanks in advance. My email is kimsanlim27@gmail.com

**Comment by marking11** [comment]
could you please share the code  hish0451@gmail.com

**Comment by iMestav** [comment]
Hi everyone,
 This code is working.

`directionsService.route({
                origin: new google.maps.LatLng(lat, lng),
                destination: new google.maps.LatLng(lat1, lng1),
                travelMode: google.maps.TravelMode.DRIVING
              }, function(response, status) {
                if (status == 'OK') {
                  var line = [];
                  response.routes[0].overview_path.forEach(function(element) {
                    line.push({"lat": element.lat(), "lng": element.lng()})
                  });
                  var polyline = vm.map.addPolyline({
                    'points': line,
                    'color' : "red",
                    'width': 10,
                    'geodesic': true,
                    'idx': 0
                  });
                }
              });`
