### ISSUE TITLE
Cannot access to the 'setPointAt' method. ionic 2 plugin v2

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1489]
me.mapa.addPolyline({
              points: me.puntos,
              'color' : '#000',
              'width': 4,
              'geodesic': true
            },function(polyline){
              let mvcArray;
              let ti=setInterval(()=>{
                if(me.direccion.length>0){
                  mvcArray = polyline.getPoints();
                  mvcArray.setAt(mvcArray, me.polilinea);
                  clearInterval(ti);
                }
              },10000)
            });
show console Cannot access to the 'setPointAt' method.

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbacket.

How and why?
#1479

**Comment by wuilmerj24** [comment]
Hello I could solve the problem The error was that the variable was not filled to update the polyline
