### ISSUE TITLE
Framework7 map is not clickable even map.setClickable(true) 

### ISSUE THREAD

**Issue by Symorp** [mapsplugin/cordova-plugin-googlemaps#1490]
Hello,
I use Framework7 with google maps,
everything works until i go from side panel to map from map to another page and one more, then by backbutton to map and now map stop working.
I am using remote debugging in chrome so i try: destroy, getMap, refresh layout, setClickable, everything but map is still not clickable.
But from direct link to map and 2 more pages and back button it works correctly.

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbacket.

How and why?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by Symorp** [comment]
I shared you on bitbucket a repository.
After build and run application.
Login with credentials : promo, pw: promo123
After login press side menu and select "mapa"
find cars in czech republic in prague, then pres button at the bottom "Zobrazit vozy" click on some car for show car detail. Then back button to car list then back button to map and map is not response.

**Comment by wf9a5m75** [comment]
Could you tell me the repository name?

**Comment by Symorp** [comment]
It is C4WMobile

**Comment by wf9a5m75** [comment]
I fixed the bug.
![1490](https://user-images.githubusercontent.com/167831/27503276-9883de8a-582f-11e7-84e8-fa69998010d5.gif)

Please reinstall the plugin. The fixed version is `2.0.0-beta2-20170623-1615`.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ... --no-fetch

$> cordova plugin list
...
cordova-plugin-googlemaps 2.0.0-beta2-20170623-1615 "cordova-plugin-googlemaps"
...
```

**Comment by Symorp** [comment]
Car4Way development team thanks to you man.

**Comment by wf9a5m75** [comment]
@Symorp I'm not sure you feel `the plugin still does not good click action or not`, but if so, it's true.
I fixed this problem today. Please reinstall the plugin `2.0.0-beta2-20170719-1400`.

I confirmed your app works correctly.
