### ISSUE TITLE
When navigating back to page with map, map flickers and blinks.

### ISSUE THREAD

**Issue by topless** [mapsplugin/cordova-plugin-googlemaps#1492]
I am using the branch `multiple_maps` and when I am navigating away from the page with the map and back to it, the map flickers kind of stretches and then gets in place. I have tried fixed widths and heights, with percent, I have removed all animations and stuff but it still does it. I have also tried to intercept and apply a css ease in transition to fade it in, in case I manage to hide it but it didn't work.

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbacket.

How and why?
#1479

**Comment by aman-daffodil** [comment]
The same issue is happening with my application too. Have you found any workaround?

**Comment by wf9a5m75** [comment]
Until any project files are provided, how can I help you guys?

**Comment by topless** [comment]
I have "fixed" the map blink when I am navigating back to it. I used the maps method `myMap.setVisible(false)` before I navigate away and `myMap.setVisible(true)` when I am about to navigate back.
