### ISSUE TITLE
 TypeError: node.className.indexOf is not a function. 

### ISSUE THREAD

**Issue by marijnroukens** [mapsplugin/cordova-plugin-googlemaps#1493]
After updating to the latest version I receive this error message. The app is still working but the map is not loading:

` TypeError: node.className.indexOf is not a function. (In 'node.className.indexOf("ion-page")', 'node.className.indexOf' is undefined), http://192.168.2.105:8100/plugins/cordova-plugin-googlemaps/www/Common.js, Line: 237`

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbacket.

How and why?
#1479

**Comment by tracedaily** [comment]
Same here. It breaks anytime the ionic loading element is used after the map loads. The spinner is svg element, and svg does not have indexOf

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbacket.

How and why?
#1479

**Comment by tracedaily** [comment]
https://bitbucket.org/tstaley/nativemapsexample

**Comment by tracedaily** [comment]
Click on the 'about' tab, and notice that the button works. Then click on the home tab, and click on the map to add a marker (which displays the loader). You can see the error in the console. Then if you click back on the about tab, the button doesn't work, and any additional taps on any other tab will continue to add more markers to the map, even though it isn't visible

**Comment by marijnroukens** [comment]
Temporary fix untill I find the time to upload the project files:

Replace function `getAllChildren` inside `plugins/cordova-plugin-googlemaps/www/Common.js` with:

```
function getAllChildren(root) {
    if (!root) {
      return [];
    }
    var ignoreTags = ["pre", "textarea", "p", "form", "input", "table", "caption"];

    var list;

    if (window.document.querySelectorAll) {
        // Android: v4.3 and over
        // iOS safari: v9.2 and over
        var childNodes = root.querySelectorAll("*");
        var allClickableElements = Array.prototype.slice.call(childNodes);
        list = allClickableElements.filter(function(node) {
            var tagName = node.tagName.toLowerCase();
            return node !== root && _shouldWatchByNative(node) && ignoreTags.indexOf(tagName) == -1;
        });
    } else {
        var node;
        var clickableElements = root.getElementsByTagName("*");
        for (var i = 0; i < clickableElements.length; i++) {
            node = clickableElements[i];
            if (_shouldWatchByNative(node) && ignoreTags.indexOf(tagName) == -1) {
                list.push(node);
            }
        }
    }

    return list;
}
```

I have not seen any unexpected behaviour so far.

**Comment by wuilmerj24** [comment]
I have the same problem. I have a page where I loaded the map and a search box and without modifying the plugin I solved the problem that the ionic elements 2 were above. Modifying the common.js does not work.

**Comment by blckshrk** [comment]
Has @tracedaily said, it comes from the `svg` element. I got the same problem. The solution proposed by @marijnroukens doesn't worked in my case. I've fixed the issue by simply add the `"svg"` to the `ignoreTags` array in `getAllChildren()` : 

```js
var ignoreTags = ["pre", "textarea", "p", "form", "input", "table", "caption", "canvas", "ion-content", "ion-app", "ion-nav", "svg"];
```

But I'm wondering if the implementation is really future proofed. It seems complicate to list every tag.

Gonna make a PR for this issue.

alex

**Comment by mayrarodriguez1709** [comment]
I have the same problem

**Comment by blckshrk** [comment]
This should be fixed on the current `multiple_maps` branch.

**Comment by wf9a5m75** [comment]
@tracedaily Thank you for waiting.
I built your project with the latest version `2.0.0-beta2-20170623-1318`, but no problem.
(Older versions might have problem)

![1493](https://user-images.githubusercontent.com/167831/27499168-747c12cc-5817-11e7-99b1-1afe839d1dce.gif)

And after come back to the home page from the about page, I got JS error which is not related with this plugin.
![screen shot 2017-06-23 at 1 22 55 pm](https://user-images.githubusercontent.com/167831/27499197-987c3f8a-5817-11e7-8d0d-8b75f34f5799.png)

**Comment by wf9a5m75** [comment]
@mayrarodriguez1709 

Please share your project files on github or bitbacket.
How and why?
#1479

**Comment by wf9a5m75** [comment]
@mayrarodriguez1709 Please share your project files on github or bitbucket.
If no update, I will close this issue.

**Comment by wf9a5m75** [comment]
Since there is no update for a while, I close this issue. If you face the same error, please make another issue.

**Comment by sam2x** [comment]
Hey, got the same error, happen when I come back to the view where the map is loaded. 

     Uncaught TypeError: node.className.indexOf is not a function
        at plugins/cordova-plugin-googlemaps/www/Common.js:237
        at Array.filter (<anonymous>)
        at Object.getAllChildren (plugins/cordova-plugin-googlemaps/www/Common.js:232)
        at putHtmlElements (plugins/cordova-plugin-googlemaps/www/googlemaps-cdv-plugin.js:98)

Seems to come from node.className :

        list = allClickableElements.filter(function(node) {
            var tagName = node.tagName.toLowerCase();
            return node !== root && _shouldWatchByNative(node) &&
              ignoreTags.indexOf(tagName) == -1 &&
              node.tagName.indexOf("nav-decor") === -1 &&
              node.className.indexOf("ion-page") === -1 &&
              node.className.indexOf("fixed-content") === -1;
        });

I dont use Ionic. 
Plugin version : Version 2.0.0-beta2-20170607-1043. 
I will update to the lastest dev to check if it happens again.

**Comment by sam2x** [comment]
Seems to work on last dev.
