### ISSUE TITLE
Lite Mode

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [mapsplugin/cordova-plugin-googlemaps#1494]
Is is possible to add lite mode? just like specify in this url: https://developers.google.com/maps/documentation/android-api/lite

**Comment by wf9a5m75** [comment]
No.

**Comment by THEDOWNCOUNTRY** [comment]
Why not?

**Comment by wf9a5m75** [comment]
Because Google does not provide the lite mode for iOS

**Comment by THEDOWNCOUNTRY** [comment]
Yes but it will be very useful to have it for android... could you provide any input on how to have this implimented?

**Comment by wf9a5m75** [comment]
Please learn how to folk git repository, then how to write Java code.

**Comment by THEDOWNCOUNTRY** [comment]
I know how to write java... But can you provide some head start?

**Comment by wf9a5m75** [comment]
I recommend you should learn how to develop the cordova plugin.
https://cordova.apache.org/docs/en/7.x/guide/hybrid/plugins/index.html

-------
If you are already know, please follow the steps.

First of all, please fork this repository.
https://help.github.com/articles/fork-a-repo/

Then clone it to your local, and you can modify the code.

**Comment by THEDOWNCOUNTRY** [comment]
Thank you very much I will look into it later.
