### ISSUE TITLE
v2.0 - Map.getMyLocation() does not invoke error callback if location permission denied

### ISSUE THREAD

**Issue by rdelhommer** [mapsplugin/cordova-plugin-googlemaps#1496]
I've taken out the body of my callbacks, but this is essentially what I have.  If user denies the app permission from using location, the error callback is not invoked.  I looked through the code and nothing looked obvious.  I've never done any cordova plugin development so I dont really know what to look for though. :D

```
map.getMyLocation({}, function (location) {
  console.log('Success!');
}, function () {
  console.log('Error!');
});
```

**Comment by wf9a5m75** [comment]
Do you use Android or iOS?

**Comment by rdelhommer** [comment]
Ah sorry... Android

**Comment by rdelhommer** [comment]
The plugin code is really clean by the way :+1:

**Comment by wf9a5m75** [comment]
I just executed the v2.0 demo app, but it worked.

[Document page](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/class/Map/getMyLocation)

[Full code](https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/getMyLocation.html)

Demo APK
https://github.com/mapsplugin/v2.0-demo#demo-apk

**Comment by rdelhommer** [comment]
Sorry false alarm.  I had included the "myLocationButton: true" option in the Map.getMap() function and I didn't realize that the permission was being checked in the Map.getMap() function.

Thanks for helping and sorry about the false alarm.  Closing the issue.
