### ISSUE TITLE
google map is not working

### ISSUE THREAD

**Issue by Krishna25Vrinsoft** [mapsplugin/cordova-plugin-googlemaps#1497]
In Android google play services provide new update yesterday as version 11.0.55 and in this version google map is not displaying in application.
Can you please provide me any solution for this

**Comment by neslob** [comment]
You provided very little info, so it is hard guess your error.
You should try to have all your google services to use the same version.

Excerpt from my `project.properties` file:
```
...
cordova.system.library.1=com.google.android.gms:play-services-maps:11+
cordova.system.library.2=com.google.android.gms:play-services-location:11+
cordova.system.library.4=com.google.android.gms:play-services-gcm:11+
...
```

**Comment by PogoMips** [comment]
Might be related to these issues:
https://stackoverflow.com/questions/44623970/mapview-oncreate-throws-nullpointerexception-on-lg-devices
https://github.com/airbnb/react-native-maps/issues/1358
https://github.com/airbnb/react-native-maps/issues/1314

**Comment by wf9a5m75** [comment]
The pull request #1506 is merged. Please reinstall the plugin.
