### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jayeshanandani** [mapsplugin/cordova-plugin-googlemaps#1498]
Hi,

Great work has been done on new version. I was just wondering around for some kind of roadmap if you can provide one with some release dates as there have been no updates on stable version 2 for quite some time.

Ionic PR's are also pending due to stable release making it little difficult to use the plugin.

If there are some contributions that can be helped with I would be glad to be part of that.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#version-20-beta-roadmap

No specific date means it's not stable. Currently on ionic3.

**Comment by jayeshanandani** [comment]
@wf9a5m75 Appreciate the response. Is there a way to contribute and make it a stable release? I did see that roadmap :)

**Comment by wf9a5m75** [comment]
Please test the multiple_maps branch with ionic3.

**Comment by jayeshanandani** [comment]
@wf9a5m75 I did and I am facing some issues with that.  Please see #1446

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbucket.

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment]
@jayeshanandani Please share your project files on github or bitbucket.
If no update, I will close this issue.

**Comment by jayeshanandani** [comment]
@wf9a5m75 : Apologies for the delayed reply. We can close this. I was using the wrong branch for version 2. It works with ionic 3 as described.
