### ISSUE TITLE
Last version of beta 2.0

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1499]
What is the last version until today?

**Comment by wf9a5m75** [comment]
You can find it in the plugin.XML file.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/plugin.xml

**Comment by wuilmerj24** [comment]
Already have date for the stable version?

**Comment by wf9a5m75** [comment]
Please check other issues.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/v2.0-demo#versioning

**Comment by wuilmerj24** [comment]
ok thanks.
