### ISSUE TITLE
'Google' Button / Logo Behaviour 

### ISSUE THREAD

**Issue by simonbrazell** [mapsplugin/cordova-plugin-googlemaps#1500]
Hello,

I'm using this plug-in for a crossplatform project using the Ionic framework. I've managed to get everything in my app working nicely, map with pin on the desired location showing in the app, etc. 

One thing I've noticed however is that when a user clicks the 'Google' button / logo in the bottom left of the map it opens the native maps app, which is great, but it seems to only open the map without a pin, making it require an additional step should the user want to start navigation. Is there any way to also include a pin on the external map when it is loaded?

Cheers.

**Comment by wf9a5m75** [comment]
It is the feature of the native API. it means it is provided by Google. Not this plugin.

**Comment by simonbrazell** [comment]
Hi Masashi,

Thanks for responding, and your efforts with the plugin.

Okay got it, but does the plugin not supply some parameters to the native
API, like coordinates for a pin location, e.g. geo:lat,long?

Cheers.

On 18 Jun. 2017 8:32 pm, "Masashi Katsumata" <notifications@github.com>
wrote:

It is the feature of the native API. it means it is provided by Google. Not
this plugin.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1500#issuecomment-309269138>,
or mute the thread

**Comment by wf9a5m75** [comment]
No.
