### ISSUE TITLE
Kml drawn lines clickable even set to visible false

### ISSUE THREAD

**Issue by sudhirbitsgoa** [mapsplugin/cordova-plugin-googlemaps#1508]
Hi,
```javascript
    this.map.addKmlOverlay({
      url: url,
      preserveViewport: false,
      animation: true
    }).then(layer => {
       layer.on(GoogleMapsEvent.OVERLAY_CLICK).subscribe(overlay => {
            overlays.forEach(ov => {
                ov.setVisible(false);
            });
       });
    });
```
Even i set setVisible false the layers are still clickable.

**Comment by wf9a5m75** [comment]
Could you share your project files on github or bitbucket?

How and why?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment]
ping

**Comment by sudhirbitsgoa** [comment]
I'll share the repo details. Can you provide gitlab id ?

**Comment by wf9a5m75** [comment]
wf9a5m75

**Comment by wf9a5m75** [comment]
ping

**Comment by sudhirbitsgoa** [comment]
done clone AdminUI branch
user: narsapur_admin@gmail.com
pass: admin

check maps view.
kml can be made visible/hide by dropdown
if kml is hidden then onclick on kml line is still working.

**Comment by wf9a5m75** [comment]
Your project is waterTasksMobile?

**Comment by wf9a5m75** [comment]
Let me confirm one thing: do you use the plugin v1.4 or v2.0?

**Comment by sudhirbitsgoa** [comment]
I'm using 1.4 as 2.0 does not have kml support yet.

**Comment by wf9a5m75** [comment]
Thank you for your replay. I'm sorry the KML layer is not ready for the v2. I have been working for the marker clustering recently.

**Comment by sudhirbitsgoa** [comment]
Ok. Thanks for the plugin.

**Comment by wf9a5m75** [comment]
The commit [e9735b6c](https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/e9735b6ce0fd0d2b2d575b078dd0a174c88fdd07) improves the click detection on polyline.

I guess you use your own version (https://github.com/sudhirbitsgoa/cordova-plugin-googlemaps) because you write `polyline.getTitle()` but the original version does not have the method.
So you need to merge the latest code to your repository.

Step 1: From your project repository, check out a new branch and test the changes.

```
$> git clone https://github.com/sudhirbitsgoa/cordova-plugin-googlemaps
$> cd cordova-plugin-googlemaps
$> git checkout -b v1.4.3 master
$> git pull https://github.com/mapsplugin/cordova-plugin-googlemaps.git master
```

Step 2: Merge the changes and update on GitHub.

```
$> git checkout master
$> git merge --no-ff v1.4.3
$> git push origin master
```

**Comment by wf9a5m75** [comment]
And I could not find out this code in your project files.

```js
    this.map.addKmlOverlay({
      url: url,
      preserveViewport: false,
      animation: true
    }).then(layer => {
       layer.on(GoogleMapsEvent.OVERLAY_CLICK).subscribe(overlay => {
            overlays.forEach(ov => {
                ov.setVisible(false);
            });
       });
    });
```

**Comment by wf9a5m75** [comment]
At least, this code works.

```js
  onClickLayers(overlay, latLng) {
    console.log(overlay);
    overlay.setVisible(false);
    let desc = '<div>none</div>';
    if (overlay.type == "Polygon") {
      // overlay.setFillColor("grey");
      try {
        desc = overlay.getTitle();
        this.presentModal(desc)
      } catch(e) {
      console.log(e);
        alert('undef');
      }
    }
    if (overlay.type == "Polyline") {
      // overlay.setColor("red");
      try {
        desc = overlay.getTitle();
        this.presentModal(desc)
      } catch(e) {
      console.log(e);
        alert('undef');
      }
    }
    ...
```

![1508](https://user-images.githubusercontent.com/167831/28041846-bc3d9b56-657f-11e7-88b6-52cb99628f46.gif)

The reason of `undef` message is the plugin does not have the `getTitle()` method.
(Which might be had in your own plugin version)

![screen shot 2017-07-10 at 2 55 34 pm](https://user-images.githubusercontent.com/167831/28041913-008c8eca-6580-11e7-900a-b3374b123ae2.png)

**Comment by sudhirbitsgoa** [comment]
@wf9a5m75 Thank you very much for the quick response. I'll check the update and close the bug.

**Comment by wf9a5m75** [comment]
Did you confirm?

**Comment by wf9a5m75** [comment]
Since there is no update, and I already fixed this issue, I close this issue. But you can still reply this issue.
