### ISSUE TITLE
Compatible with Google maps version web

### ISSUE THREAD

**Issue by goinnn** [mapsplugin/cordova-plugin-googlemaps#1510]
First congrats for this project!

I don't know if this is in the project scope, but I think this would be a very nice feature.

If you are using cordova-plugin-googlemaps on web, this only be a wrapper of Google maps version web. I think it is comfortable for develop and especially if you are using the same code for apps and web version.

What do you think about this functionality?

**Comment by wf9a5m75** [comment]
I have no plan to wrap the web version.
