### ISSUE TITLE
How to update the points of polyline?

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1512]
I'm using google maps v3 api api to calculate a route, and from that route I draw the polyline, which is working very well. I need to update the polyline and also it does well but I need to update the last point of the polyline that I do not know how I can do it

**Comment by wf9a5m75** [comment]
```js
map.addPolyline({
  points : [ ... ]
}, function(polyline) {
  var points = polyline.getPoints();
  var last = points.getLength() - 1;
  points.setAt(last, {lat: .., lng: ...});
});
```

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Polyline/getPoints/README.md

**Comment by wuilmerj24** [comment]
Thank you. I already implemented it and it works very well. Thankful for the help.

**Comment by ktre2017** [comment]
Hi wuilmerj24, 

Can you please share some sample code about how to calculate route using maps v3 and draw route using polyline on map?

Thank you

**Comment by wuilmerj24** [comment]
let directionsDisplay= new google.maps.DirectionsRenderer({suppressMarkers: true});
    let directionsService= new google.maps.DirectionsService();
let request = {
          origin:{lat:parseFloat(this.latitudCliente),lng:parseFloat(this.longitudCliente)},
          destination: {lat:parseFloat(data[0].latitud),lng:parseFloat(data[0].longitud)},
          waypoints: [{
            stopover: false,
            location: new google.maps.LatLng(this.latitudCliente,this.longitudCliente)
          }],
          travelMode: google.maps.TravelMode.DRIVING,
        };
directionsService.route(request, function(response, status) {
          if (status == google.maps.DirectionsStatus.OK) {
for (var i = 0; i < response.routes.length; i++) {
              for (var i2 = 0; i2 < response.routes[i].legs.length; i2++) {
                for (var i3 = 0; i3 < response.routes[i].legs[i2].steps.length; i3++) {
                   // add the start and end location by the legs of routes on the path to the polyline
                   //path.push(response.routes[i].legs[i2].steps[i3].start_location);
                   //path.push(response.routes[i].legs[i2].steps[i3].end_location);
                   //console.info(response.routes[i].legs[i2].steps[i3].start_location)
                   this.puntos.push({lat:response.routes[i].legs[i2].steps[i3].start_location.lat(),lng:response.routes[i].legs[i2].steps[i3].start_location.lng()})
                   this.puntos.push({lat:response.routes[i].legs[i2].steps[i3].end_location.lat(),lng:response.routes[i].legs[i2].steps[i3].end_location.lng()})
                }
              }
            }
            this.mapa.addPolyline({
              'points': this.puntos,
              'color' : '#3e6372',
              'width': 4,
              'geodesic': true
            },function(polilinea){
              this.actualizarPolilinea(polilinea);
            });

actualizarPolilinea(polilinea){
    console.log(polilinea)
    this.updateTrazarRuta=setInterval(()=>{
      this.providerCliente.http.post(this.providerCliente.url,datos,this.providerCliente.options).map(res => res.json()).subscribe(data => {
        let mvcArray;
        let newPos:any={lat:data[0].latitud,lng:data[0].longitud};
        mvcArray = polilinea.getPoints();
        let ultimo=mvcArray.getLength() - 1;
        mvcArray.setAt(ultimo,newPos);
        console.info("actualizando la polilinea")
        this.polilinea=polilinea;
      })
    },3000);
  }

**Comment by ktre2017** [comment]
Thank you so much. Appreciate your help.
