### ISSUE TITLE
v2 documentation: marker.setIconAnchor describes how to use setDraggable instead

### ISSUE THREAD

**Issue by R2D221** [mapsplugin/cordova-plugin-googlemaps#1514]
The documentation for v2 incorrectly shows the description for `setDraggable` in the `setIconAnchor` entry. The actual description for `setIconAnchor` appears to be missing.

**Comment by wf9a5m75** [comment]
Sorry for your inconvenience. Fixed it.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Marker/setIconAnchor/README.md
