### ISSUE TITLE
Cannot slide menu open.

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [mapsplugin/cordova-plugin-googlemaps#1516]
Am using v2 beta with ionic 2 I cannot slide the menu to open it... Instead it slide the map.

**Comment by wf9a5m75** [comment]
Please share your project files.
How and why?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
I guess you installed kind of old version. Please try to reinstall the plugin latest version.
The current latest version is `2.0.0-beta2-20170625-1805`.

Since there is no update for a while, I close this issue.
