### ISSUE TITLE
Ionic 2 - Multi Markers method not creating markers

### ISSUE THREAD

**Issue by SKempin** [mapsplugin/cordova-plugin-googlemaps#1519]
Please describe your question, problem or request as much as possible.

- What is your question, problem or request?
Using the [provided](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/class/Marker/addMarker#adding-multiple-markers) documented code does not render markers. The map loads but no markers are present.

- What version of this plugin do you use? ($> cordova plugin list)
Version 2

- Screen capture or video record?
(you can upload your files with drag & drop)
I have added a branch `multi-maps` to the shared demoapp bitbucket repo.

- Error log (if possible)
n/a

- provide your app code
See Bitbucket repo.

Please past your code or share your project files.
You don't want to share your code with public?
You can share with me on a private repository at the bitbucket as free.
Please read https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment]
Please(x3) read document pages before coding.

-----

As describe in the [For ionic2 users](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md#ionic-native) page, the ionic wrapper plugin is not compatible with the plugin version2.

>The Ionic Native module that's available for the cordova-googlemaps-plugin is not yet modified to be compatible with the new v2-beta

----
So you can not `import { GoogleMap, GoogleMapsEvent, MarkerOptions } from '@ionic-native/google-maps';`

**Comment by wf9a5m75** [comment]
You **can not any statements of [this page](https://ionicframework.com/docs/native/google-maps/)**

**Comment by wf9a5m75** [comment]
By the way, the question `What version of this plugin do you use? ($> cordova plugin list)` means `what version of the v2 including miner number.

I already know you use the v2, but I update the code frequently.
So I want to know the miner version.

```
$> cordova plugin list
cordova-plugin-googlemaps 2.0.0-beta2-20170625-1805
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by SKempin** [comment]
@wf9a5m75 Sorry I do not understand your answer? The code in the repo is the same code that was used on the mutli maps issue that you solved? This includes the `import` statement: `import { GoogleMap, GoogleMapsEvent, MarkerOptions } from '@ionic-native/google-maps';`

I have tried `cordova plugin list` but the plugin is not listed in the output:

```
 /c/app/demoapp2 (multi-maps)
$ cordova plugin list

You have been opted out of telemetry. To change this, run: cordova telemetry on.
cordova-plugin-actionsheet 2.2.2 "ActionSheet"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
plugin.google.maps 1.3.9 "phonegap-googlemaps-plugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.2 "Launch Navigator"
{}
```

**Comment by wf9a5m75** [comment]
This is your code.

```js
import {Component,ViewChild,ElementRef} from '@angular/core';
import {LocationsData} from '../../providers/locations-data';
import {Platform,NavController,NavParams} from 'ionic-angular';
import {GoogleMap,GoogleMapsEvent,MarkerOptions} from '@ionic-native/google-maps';
import {GoogleAnalytics} from '@ionic-native/google-analytics';
declare  var plugin: any;
declare var cordova: any;

@Component({
    selector: 'page-map',
    templateUrl: 'map.html'
})

export class MapPage {
    locationCardClicked: any;

    @ViewChild('map') theMap: ElementRef;
    map: any;
    markers: any;


    constructor(public locData: LocationsData, public navCtrl: NavController, public platform: Platform, public navParams: NavParams, private GoogleAnalytics: GoogleAnalytics) {
        // this.locationCardClicked = this.navParams.data;
    }

    loadMap() {
        var POINTS = [
            {position: { lat: 51.4481951, lng: -2.6095827}},
            {position: { lat: 51.45329, lng: -2.60101} }
        ];

        let mapEle = this.theMap.nativeElement;
        this.map = new plugin.google.maps.Map.getMap(mapEle, {});

        this.map.one(plugin.google.maps.event.MAP_READY, () => {

            // Add markers
            this.map.addMarkers(this.map, POINTS, function(markers: any) {
                // Uncaught TypeError: _this.map.addMarkers is not a function
                var bounds = [];
                for (var i = 0; i < markers.length; i++) {
                    bounds.push(markers[i].getPosition());
                }
                this.map.moveCamera({
                    target: bounds
                });
            });
        });

        function addMarkers(map: any, data: any, callback: any) {
            this.markers = [];

            function onMarkerAdded(marker: any) {
                this.markers.push(marker);

                // If you click on a marker, the marker's icon will be changed.
                marker.on(plugin.google.maps.event.MARKER_CLICK, onMarkerClick);
                marker.on(plugin.google.maps.event.INFO_CLICK, onMarkerClick);

                if (this.markers.length === data.length) {
                    callback(this.markers);
                }

            }

            data.forEach(function(markerOptions: any) {
                this.map.addMarker(markerOptions, onMarkerAdded);
            });

        }

        function onMarkerClick() {
            var marker = this;
            var iconData = marker.get("iconData");

            // Change the marker icon
            marker.setIcon(iconData);
        }
    }
    ionViewDidLoad() {
        setTimeout(() => {
            this.loadMap();
        }, 200);
    }

}
```

And in your code,

you can not use this:
```js
import {GoogleMap,GoogleMapsEvent,MarkerOptions} from '@ionic-native/google-maps';
```

the below code is 100% wrong:
```js
this.map = new plugin.google.maps.Map.getMap(mapEle, {});
```

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update for a while, I close this issue.

**Comment by SKempin** [comment]
Sorry I have been on vacation and have not had a chance to look at this, I will update you within the next week or so. Thanks.
