### ISSUE TITLE
Map is displayed before "MAP_READY" event is fired

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1520]
I am using ionic 3.5.0 and the version `2.0.0-beta2-20170625-1805` of this plugin.

I have an small UI issue when initializing the map, which only appears on iOS.
I used your doc to set up the plugin and I initialize the map options as below:

```
  let mapEle = this.theMap.nativeElement;
  this.map = plugin.google.maps.Map.getMap(mapEle, {
      'camera': {
        'target': {
          'lat': 48.866667,
          'lng': 2.333333
        },
        'zoom': 12
      },
  });

  this.map.on(plugin.google.maps.event.MAP_READY, () => {
      console.log('map is ready');
   });
```

I noticed that the map options are only considered after the "MAP_READY" event is fired.
So I can see the map with default options (no zoom nor camera target) for a sec.
Only after the "MAP_READY" event is fired, I can see the correct map options (zoomed at 12 and correctly targeted).

Do you know what can be causing that?

A solution could be to hide the map until the "MAP_READY" event is fired, but I have some issue to achieve that as the map is not "ready" yet.

![btdgno](https://user-images.githubusercontent.com/16256207/27729116-cb66a814-5d84-11e7-9873-eceae27e5e88.gif)

**Comment by wf9a5m75** [comment]
> I noticed that the map options are only considered after the "MAP_READY" event is fired.
So I can see the map with default options (no zoom nor camera target) for a sec.
Only after the "MAP_READY" event is fired, I can see the correct map options (zoomed at 12 and correctly targeted).

This is correct, not bug.

The `MAP_READY` event means `you can use the map safely`, not **the map is loaded**.

**Comment by antoine92190** [comment]
Ok I understand.
But the options I set initially in `getMap()` should be considered as soon as the map is loaded, right?
However, right now the options are effective only after the `MAP_READY` event is fired.

**Comment by wf9a5m75** [comment]
>But the options I set initially in getMap() should be considered as soon as the map is loaded, right?

No. The native Google Maps SDK does not provide the camera option actually.

Providing the camera option means the same as below code (only meaning, not exactly the same code).

```js
  let mapEle = this.theMap.nativeElement;
  this.map = plugin.google.maps.Map.getMap(mapEle);

  this.map.one(plugin.google.maps.event.MAP_LOADED, () => {

      map.moveCamera({
        'target': {
          'lat': 48.866667,
          'lng': 2.333333
        },
        'zoom': 12
      });
      map.trigger(plugin.google.maps.event.MAP_READY);
  });

  this.map.on(plugin.google.maps.event.MAP_READY, () => {
     
   });
```

**Comment by antoine92190** [comment]
Thanks, I understand better.
Do you have any advice on how to hide the map until those options are actually effective?

**Comment by wf9a5m75** [comment]
How about like this?
```js
  let mapEle = this.theMap.nativeElement;
  this.map = plugin.google.maps.Map.getMap(mapEle);

  this.map.on(plugin.google.maps.event.MAP_READY, () => {
    
      map.moveCamera({
        'target': {
          'lat': 48.866667,
          'lng': 2.333333
        },
        'zoom': 12
      }, () =>  {
          console.log("completed");
      });
 
  });
```

**Comment by wf9a5m75** [comment]
Or 
```js
  let mapEle = this.theMap.nativeElement;
  this.map = plugin.google.maps.Map.getMap(mapEle);

  this.map.on(plugin.google.maps.event.MAP_READY, () => {
    
      map.moveCamera({
        'target': {
          'lat': 48.866667,
          'lng': 2.333333
        },
        'zoom': 12
      });

     map.one(plugin.google.maps.event.CAMERA_MOVE_END, () => {
          console.log("completed");
     });
 
  });
```

**Comment by antoine92190** [comment]
I think I can work with that. Thanks a lot!
