### ISSUE TITLE
Cannot install v1.3.9 with Cordova 7.0.0

### ISSUE THREAD

**Issue by cwoolum** [mapsplugin/cordova-plugin-googlemaps#1521]
Getting to following error on my build server after upgrading to Cordova 7.0.0

```Failed to install 'plugin.google.maps': CordovaError: Failed to fetch plugin https://bitbucket.org/nightstomp/cordova-plugin-googlemaps-sdk.git via registry.```

I am trying to build an iOS app. Only ```cordova-plugin-googlemaps``` is included in my config.xml and I am pointing it at ```https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps#1.3.9```

**Comment by wf9a5m75** [comment]
Why do you want to use 1.3.9?

**Comment by cwoolum** [comment]
I was having issues with 1.4.x when I first tried it. I'll try again and report back

**Comment by wf9a5m75** [comment]
I recommend you use the v2.0-beta
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

**Comment by cwoolum** [comment]
2.0 was causing me bugs. When switching between pages of my app, the map
would not reliably render. On 1.3.9, I was able to remedy this by caching
the page but that's doesn't work with 2.0.

**Comment by wf9a5m75** [comment]
Could you share your project files on github or bitbucket?
I will check it.

How and why?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by cwoolum** [comment]
I cannot share the project but I will try to repro and publish. I'm using
Ionic 1. The map loads when the view first renders but if I leave the page
and come back, most of the time I'm just left with a blank map.

**Comment by wf9a5m75** [comment]
>I cannot share the project

Even with a private repository on bitbucket as free?

>  I'm just left with a blank map

Do you mean a blank map a white page or a gray map?

**Comment by wf9a5m75** [comment]
Since there is no update and no enough information is provided, I close this issue.
