### ISSUE TITLE
[v2] Avoid unnecessary Tile load in TileProvider

### ISSUE THREAD

**Issue by sam2x** [mapsplugin/cordova-plugin-googlemaps#1523]
#### What is your question, problem or request?

When loading a Tile Overlay, the appropriate function [getTile](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/android/plugin/google/maps/PluginTileProvider.java#L87 ) is loaded. This function check if URL is local/remote and fetch image appropriately.  

The problem is, when there are tiles we dont want to draw/generate (eg: empty data), i have to also return an empty PNG image. The things is, if we return empty data (empty body response, code 200, or 404), the lib is raising errors for every empty tiles (not crashing, but multiples errors appears in the logs files).  The problem is coming from the [http.getInputStream()](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/android/plugin/google/maps/PluginTileProvider.java#L87) which try to bitmap decode the  response decoded even if there are *no data* (thus raising error). 

Instead of returning empty small PNG (which consume bandwidth, and increase delays), is it possible to just check that http.getInputStream() isnt null/empty ?  

#### What version of this plugin do you use? ($> cordova plugin list) 

Last v2 branch.

**Comment by wf9a5m75** [comment]
I give you a hint.
How can you reach this line?
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/android/plugin/google/maps/PluginTileProvider.java#L108

**Comment by sam2x** [comment]
I know about this line, however at this step, client doesnt know if tile is empty or not. So it has to fetch the server which render "in live" the tile, and he is the only one to know if "no need overlay tile here" or "here the png".

**Comment by wf9a5m75** [comment]
> client doesnt know if tile is empty or not. 

Your app should check the area in advance.

**Comment by wf9a5m75** [comment]
How about add an option `ignoreHttpErrors` to map.addTileOverlay().

**Comment by sam2x** [comment]
There are two ways to solve this : 
- Server returns HTTP error status (40x/50x*, etc.) and thus 'IgnoreHttp(s)Error" can make sense 
- Server returns OK status (20x) , and handle empty [input stream](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/android/plugin/google/maps/PluginTileProvider.java#L164) (adding one line to 164, best easier way) :
   ``` if (!inputStream || inputStream.length == 0) return null;```

I can submit the PR on the next days (for Android), dont know what is the equivalent code for objective C.

**Comment by wf9a5m75** [comment]
In general, mobile apps should reduce HTTP requests as much as possible. Because even if the server response s empty response, HTTP requests spend battery life.
That's why I said "your app should check the area in advance" (This is common in mobile programming).

However certainly sometimes, you want to ignore the server side errors.
That's why I said adding the option.

But event though, you should not rely on the option. You should avoid HTTP requests as much as possible.
