### ISSUE TITLE
v2.0-demo shows brown blank map

### ISSUE THREAD

**Issue by yesman99** [mapsplugin/cordova-plugin-googlemaps#1524]
Hi there,

- What is your question, problem or request?
When I try to open any map in v2.0-demo, only show brown and blank map (At bottom left, there is "Google" logo though). 
Do you know why or can you guess why this is happening?
Thank you in advance.

- Screen capture or video record?
![img_6194](https://user-images.githubusercontent.com/6134076/27780970-d7f986e4-6006-11e7-9542-dafe1d02e199.PNG)

- provide your app code
v2.0 (I didn't change any codes)

**Comment by wf9a5m75** [comment]
The gray map means your API key is wrong.
 
Please check out this page.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by wf9a5m75** [comment]
解決しましたか？

**Comment by yesman99** [comment]
ご連絡が遅くなってしまい申し訳ありません。

Finally I could make it!
The reason is because I couldn't change config.xml.

`<plugin name="cordova-plugin-googlemaps" spec="1.4.0">
    <variable name="API_KEY_FOR_ANDROID" value="YOUR_ANDROID_API_KEY_IS_HERE" />
    <variable name="API_KEY_FOR_IOS" value="YOUR_IOS_API_KEY_IS_HERE" />
    <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="My custom when in use message" />
    <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="My custom always usage message" />
</plugin>`

Thank you author.

**Comment by wf9a5m75** [comment]
良かったです。私は日本人なので、日本語で質問していただいても構いませんよ。
