### ISSUE TITLE
Execution failed for task ':transformClassesWithDexForDebug'

### ISSUE THREAD

**Issue by ToBeM12** [mapsplugin/cordova-plugin-googlemaps#1525]
when i install the plugin

`ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"`

and try to build the app i get error:

```
        * What went wrong:
        Execution failed for task ':transformClassesWithDexForDebug'.
        > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException:
        java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define
        Lcom/google/android/gms/iid/zzc;
```

`

**Comment by wf9a5m75** [comment]
try to reinstall the android platform.

```
cordova platform rm android

cordova platform add android
```

**Comment by kamran377** [comment]
I'm facing the same issue

**Comment by wf9a5m75** [comment]
Could you share your project files on github or bitbucket?
How and why?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment]
Ah, I see. I might get the reason.
You guys probably use other plugin that use the google play services of old version.

**Comment by ToBeM12** [comment]
i solved this by the hard way 😢 .. i created new project and installed google maps first and then installed the whole plugins again after it and copied my src directory to it.

**Comment by wf9a5m75** [comment]
@ToBeM12 I guess the google play services library you installed (actually cordova installed automatically) was old version.

Google changes the version of the library from 10.x to 11.x.
I guess that is why.
