### ISSUE TITLE
setTilt inside GoogleMapsEvent.CAMERA_CHANGE freeze

### ISSUE THREAD

**Issue by frozenxis** [mapsplugin/cordova-plugin-googlemaps#1526]
Please describe your question, problem or request as much as possible.

- What is your question, problem or request?
I want to automatically set the tilt based on zoom level.
When i setTilt inside GoogleMapsEvent.CAMERA_CHANGE event i get freezes in map and i must repeat the zoom gesture about 20 times to get from zoom 18 to zoom 19 for example

- What version of this plugin do you use? ($> cordova plugin list)
com.googlemaps.ios 2.2.0-fixed "Google Maps SDK for iOS"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 1.4.1 "phonegap-googlemaps-plugin"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

- provide your app code
```
         this.map.on(GoogleMapsEvent.CAMERA_CHANGE).subscribe((cameraPosition) => {
          let tilt: number = 40;
          tilt += cameraPosition.zoom;
          this.map.setTilt(tilt);
        });
```

**Comment by wf9a5m75** [comment]
Your code causes forever looping

**Comment by wf9a5m75** [comment]
The setTilt() method changes camera position.
