### ISSUE TITLE
The call to calback is slow ionic 2

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1527]
Please describe your question, problem or request as much as possible.

- The call to calback is slow ionic 2

- What version of this plugin do you use? ($> cordova plugin list)
cordova-plugin-googlemaps 2.0.0-beta2-20170615-1407

- Screen capture or video record?
```js
this.mapa.addMarker({
        'position':{lat:data.latitud,lng:data.longitud},
        'animation':plugin.google.maps.Animation.BOUNCE,
        icon:{
          'url':this.imgMarkerProfesional,
          'size':{
            width:24,height:24
          }
        },
        title:data.idProfesional
      },function(marker){
        console.log("marcador creado")
        me.arrayMarcadoresProfesionales.push(marker);
        marker.addEventListener(plugin.google.maps.event.MARKER_CLICK, function() {
          marker.hideInfoWindow();
          console.log("Marker is clicked");
          console.log(marker.getTitle());
        });
      });
```

- Error log (if possible)

```
(here)
```

- provide your app code

Please past your code or share your project files.
You don't want to share your code with public?
You can share with me on a private repository at the bitbucket as free.
Please read https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment]
How slow? Could you provide a screen record(video)?
And also the plugin you installed is already old minor version. Please try to reinstall the latest version.

**Comment by wuilmerj24** [comment]
The calback is executed 2 seconds later. I already uploaded a video with a log

**Comment by wf9a5m75** [comment]
> I already uploaded a video with a log

Where?

![screenshot_20170704-182134](https://user-images.githubusercontent.com/167831/27845631-bbfc5cf2-60e5-11e7-93ca-f1768ecfd846.png)

**Comment by wuilmerj24** [comment]
Sorry, I'm uploading the video

**Comment by wuilmerj24** [comment]
What date does the new update have?

**Comment by wf9a5m75** [comment]
`2.0.0-beta2-20170625-1805`

You can check the latest version date in the plugin.xml

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/plugin.xml#L2

**Comment by wf9a5m75** [comment]
Are you still uploading your video?

**Comment by wf9a5m75** [comment]
Since there is no update, I close this issue.
