### ISSUE TITLE
[V2] [Question] Is the documentation up to date and complete?

### ISSUE THREAD

**Issue by ihadeed** [mapsplugin/cordova-plugin-googlemaps#1528]
I'm in the progress of updating Ionic Native's Google Maps wrapper to work with the second version of this plugin.

I noticed that some methods are there in the source code, but they are not documented in the docs repo. For example, the Circle class has a `getVisible` and `setVisible` methods, but they are not documented. There are other similar instances of this confusion, but I guess you get the point. 

Should I follow the source code, or the docs?

**Comment by wf9a5m75** [comment]
Oh, I see.
Maybe I forgot to add them to the documents.

Except KML layer, you can follow the source code.
I will check the documents tomorrow (I'm outside of town today)

**Comment by ihadeed** [comment]
Ok perfect, thanks for the clarification.

If I come up with a list of missing items, do you want me to post them here?

**Comment by wf9a5m75** [comment]
Yes, please. Thank you for your work.

**Comment by ihadeed** [comment]
# BaseArrayClass
It extends BaseClass but that's not mentioned in the docs. I think the only methods that matter are `on()` and `one()`.

# Circle
- getHashCode()
- getMap()
- getVisible()
- setVisible()

# Environment
- setDebuggable()
- isAvailable()

# Map
- [setCameraBearing](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/class/Map/setCameraBearing) docs are invalid, they are duplicate of setCameraZoom 
- getDiv

# Marker
- getTitle
- getSnippet
- getRotation

# Polygon
- getGeodesic
- setGeodesic
- setStrokeWidth
- getStrokeWidth

# Polyline
- getMap

# TileOverlay
- getTileSize

**Comment by wf9a5m75** [comment]
Thank you for the update.

The setDebuggable() method is actually only for me (it's not perfect for users). 
The isAvailable() method is run automatic at the initialize. It is not necessary to run by users.
So please don't implement these methods.
Sorry, I forgot to mention about that.

I will update the documents for other methods.

I appreciate for your great work.

**Comment by ihadeed** [comment]
Thanks for the feedback @wf9a5m75 

Also, thanks for the awesome plugin! Looks like lots of hours have been put into it.

**Comment by wf9a5m75** [comment]
@ihadeed I have a question. What is the `<div class="nav-decor">` is for?
This element blocks this plugin actually.
Is there any affect if I apply a style `display: none;` for it?

**Comment by ihadeed** [comment]
As far as I know, that is only used for some iOS transition animations. Not sure if they use it for anything else now, I'm not very up to date with the Framework's internals.

I would say it's fair to set it's display property to none, or make it's background transparent (while google maps are visible). It shouldn't affect the behaviour of the app.

**Comment by wf9a5m75** [comment]
I see. Thank you for telling that. I got relieved disabling the nav-decor class does not affect to the app behavior.

I updated the plugin code to disable the nav-decor class actually. It looks fine.

And I also added one method : map.getVisible()
It just returns the value of map.setVisible().

------

I have been working on the market clustering recently. The due date is at the end of July (Pacific time).

Since of this, I have been still diddling around with the internal code.
But I promise I don't change the methods significantly.
(Might be add some methods)

I will set the multiple_maps branch as the stable. The current plan date is August/1.
I will update at this thread, and the release notes.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.0-beta2/README.md

**Comment by ihadeed** [comment]
Ok thanks. Would it be safe if we release the Ionic Native update earlier? If you only plan to add methods, and not change anything major, then I think it should be fine.

**Comment by wf9a5m75** [comment]
You can release it early :)
I only plan to update `add` some methods.

**Comment by wf9a5m75** [comment]
@ihadeed I have a question. The ionic wrapper uses "ILatLng". Is this your intended or just typo?

**Comment by wf9a5m75** [comment]
@ihadeed 
I sent a pull request. But I'm not ionic user, so I could not how to install ionic native from local. Please test the pull request.
https://github.com/ionic-team/ionic-native/pull/1815

**Comment by ihadeed** [comment]
Thanks @wf9a5m75 .. I'll take a look when I get a chance.

**Comment by wf9a5m75** [comment]
Thanks
