### ISSUE TITLE
Is there a way to create an "Address search" with Auto Complete?

### ISSUE THREAD

**Issue by juanjoseadan** [mapsplugin/cordova-plugin-googlemaps#1531]
Hi everyone, I'm integrating this plugin to my Ionic application. By now all is working Ok, but I need to use the Address Search in real time, so the user can get suggestions by typing the street and city (as Google Maps web platform does).

I was trying to implement it with Geocoder with no success...

Also if I try to put an "ion-input" or "button" over the map I cant click it or type text because every time I tap the control It fires the map "click" event...

This is what I get when I run "cordova plugin list"

> com.googlemaps.ios 2.2.0-fixed "Google Maps SDK for iOS"
> cordova-plugin-camera 2.4.1 "Camera"
> cordova-plugin-compat 1.1.0 "Compat"
> cordova-plugin-console 1.0.5 "Console"
> cordova-plugin-device 1.1.4 "Device"
> cordova-plugin-dialogs 1.3.3 "Notification"
> cordova-plugin-facebook4 1.9.1 "Facebook Connect"
> cordova-plugin-geolocation 2.4.3 "Geolocation"
> cordova-plugin-googlemaps 1.4.1 "phonegap-googlemaps-plugin"
> cordova-plugin-network-information 1.3.3 "Network Information"
> cordova-plugin-splashscreen 4.0.3 "Splashscreen"
> cordova-plugin-statusbar 2.2.2 "StatusBar"
> cordova-plugin-whitelist 1.3.1 "Whitelist"
> cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
> ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by wf9a5m75** [comment]
This plugin does not provide the place auto-complete (as web) so far.
