### ISSUE TITLE
Request: Make getMyLocation a static function of Map class

### ISSUE THREAD

**Issue by rdelhommer** [mapsplugin/cordova-plugin-googlemaps#1533]
Is it possible to get the current location without having to instantiate a map?

If not, I think it would be a nice feature if the source supports it without too much work.

**Comment by wf9a5m75** [comment]
Please use the cordova-geolocation-plugin. 
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-geolocation/#cordova-plugin-geolocation

**Comment by rdelhommer** [comment]
True.  The hope was to not have to install two plugins

**Comment by wf9a5m75** [comment]
Since the development member is just one person, there is a limit to develop features.
If you create the feature, and send a pull request, I will happy to review it, and merge it if no problem.
I hope you contribute the plugin, not just requesting.

**Comment by rdelhommer** [comment]
Absolutely, I'd be happy to as long as you don't mind code-reviewing my noob code :D.  I've never done any cordova plugin development, but the code looked fairly straightforward when I looked through it the other day.

**Comment by battika** [comment]
Is there any progress with this one? At the moment cordova-plugin-geolocation is not compatible with this plugin.
