### ISSUE TITLE
v2: Running out of memory on IOS.   

### ISSUE THREAD

**Issue by stackexchanger7** [mapsplugin/cordova-plugin-googlemaps#1535]
Running out of memory on IOS with `max number of texture atlases, can not allocate more` while loading 1000 custom icons.    

In attempts to optimize memory utilization on iPhone 6 I came across this issue: 

My app dynamically creates base64 inline png for each icon. If I keep each icon at **2kB**, and **do not use icon "size" property** the plugin loads **1000 icons** OK. As soon as I specify icon size, even if it matches the actual png size (_no downscaling to account for pixel density - what I really need, it works great on Android, icons are crisp_), IOS throws `max number of texture atlases, can not allocate more` for each icon past 300 count and the app eventually crashes. 

_At 2kB icons are of unusable quality, just trying to find the icon size that the app/plugin can work with on iPhone 6. Android icons are 11kB [stable]._

I came accross issue @Hirbod [#337](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/337) where @wf9a5m75 kindly mentions:

> loading 90 icon images with resizing means your app makes another small 90 icon images

1. **Is there a way to dispose of the memory used by the original images?**
I destroy the png `var` on each `for` loop cycle, does the plugin keep the original unsized png's in mem somehow?    
2. Is there another strategy that could potentially help reduce icons memory footprint? 
_ie: What if instead of generating the images in memory and assigning them to map icons I would write the png files to local storage and then use the icon url somehow(???) referencing local storage location - would it still keep the original unsized images in mem?_

**My enviroment:** the latest cordova-plugin-googlemaps v2, iPhone 6 (1GB RAM). iPhone caps the app at 320MB and crashes. The same app runs great on 2GB Samsung S6 where I can afford 4x downscaling. The memory utilization on S6 maxes out at around 800MB.

**Comment by wf9a5m75** [comment]
Mobile device has small memory than PC.

**Comment by stackexchanger7** [comment]
**Thanks Masashi! I appreciate you taking your precious time to respond.** 

I am trying to understand why `size` property causes `max number of texture atlases` when the same marker set without `size` renders OK.

In `Marker.m` we declare `*image`, the decoded png is assigned to it. All we have so far is just `*image`:
```
UIImage *image;
...
image = [[UIImage alloc] initWithData:decodedData];
if (width && height) {
  image = [image resize:width height:height];
} 
```
If width and height are specified we call `PluginUtil.m`:
```
-(UIImage *)resize:(CGFloat)width height:(CGFloat)height {
  if (width > 0 && height > 0) {
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(width, height), NO, 0.0);
    [self drawInRect:CGRectMake(0, 0, width, height)];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return image;
  }
  return self;
}
```
which assigns the resized version back to `*image` variable in `Marker.m`:
`image = [image resize:width height:height];`

It looks clean to me. The memory should be released after resize. I am puzzled to why it would cause such an overhead. 

Are all markers trying to resize at the same time? Is there a way to execute this `sync` in **small groups** so the phone does not get overwhelmed? It will allow to increase map marker capacity. 
Load speed for small amount of markers (less than the group size) will not get affected.

**Comment by wf9a5m75** [comment]
If you find memory leak points, please send pull requests.
