### ISSUE TITLE
Always display black screen on the IOS device

### ISSUE THREAD

**Issue by Golotus** [mapsplugin/cordova-plugin-googlemaps#1539]
Why Always display black screen on the IOS device?
I only run the example code on project, but always display black screen.
I used VPN net. Open the Google Map by app is right.

**Comment by wf9a5m75** [comment]
If you use the ionic framework, please disable the `.nav-decor` class of CSS.

```html
<style type="text/css">
.nav-decor {
   background-color: rgba(0,0,0,0) !important;
   background: rgba(0,0,0,0) !important;
   display:none !important;
}
</style>
```

If the above does not work, please share your project files on github or bitbucket.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by Golotus** [comment]
@wf9a5m75 Thank you a lot!
I tried on your advice and the problem was solved, the map was able to display properly.

**Comment by DrMabuse23** [comment]
in which branch or version ?

**Comment by wf9a5m75** [comment]
The current multiple_maps inserts the above CSS automatically.

If you use the current master branch, you need to insert the above code by yourself.

I noticed the ionic blocks with the CSS class recently.

**Comment by wf9a5m75** [comment]
I insert the code for anti .nav-decor class of the ionic framework.
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/13a00e01aa3682de33402975bf1671f1103440f4

And I also updated the npm version.

@DrMabuse23 Please reinstall the plugin.

**Comment by DrMabuse23** [comment]
Ok last question i figured out why my map is not visible i have the following css : `body {
  background-color: color($colors, bluebg) !important;
}` if i uncomment this style the map is still visible

**Comment by wf9a5m75** [comment]
Please read the documents first.

 https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Environment/setBackgroundColor/README.md

**Comment by wf9a5m75** [comment]
Additional information. Even if you specified `body { background-color: color($colors, bluebg) !important; }`, this plugin disables it automatically.
Because the map view (native view) places under the browser view.

Important thing is map is not HTML element. So it is placed out side of the browser.
