### ISSUE TITLE
HTMLInfoWindow handling line-wrap

### ISSUE THREAD

**Issue by dasois** [mapsplugin/cordova-plugin-googlemaps#1540]
Branch: mutliple_maps

Currently very long lines in HTMLInfoWindow do not get wrapped, which they do in the original GoogleMaps Html InfoWindow.

The `calculate()` method sets `white-space: nowrap`, which means, that if you set `white-space: normal` in your infoWindow-div the height of the HTMLInfoWindow is not high enough, when it comes to a line-break.

There also is not an option to set maxWidth, which could replace setting `white-space: normal` in the infoWindow-div in most cases.

**Comment by wf9a5m75** [comment]
The plugin does not take care the contents of HTMLinfoWindow. You need to manage the contents by yourself.

**Comment by dasois** [comment]
The HTMLInfoWindow has the wrong size then, if your content wraps lines.

**Comment by wf9a5m75** [comment]
As I said, you need to manage your contents by yourself.

For example,

```js
var box = document.createElement("div");
box.style.width = "500px";
box.style.height = "300px";
box.innerHTML = "your HTML";

var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();
htmlInfoWindow.setContent(box);

```

**Comment by dasois** [comment]
![bildschirmfoto von 2017-07-12 15-10-17](https://user-images.githubusercontent.com/3832690/28119780-51de8958-6716-11e7-9037-316870b2e8ce.png)

I cannot set fixed width or height, because my content is dynamic.
It shall automatically adjust the size of the info-window.
Currently I'm doing:
```
infoDiv.style.width = "auto !important";
infoDiv.style.maxWidth = "400px";
                infoDiv.style.height = "auto !important";
                infoDiv.style.maxHeight = "200px";
```

**Comment by wf9a5m75** [comment]
As I said, you need to manage the contents of the HTMLinfoWindow, including size calculation.

You don't want break the line? Just set nowrap CSS.
