### ISSUE TITLE
Setting focus back to map

### ISSUE THREAD

**Issue by dasois** [mapsplugin/cordova-plugin-googlemaps#1542]
Branch: multiple_maps

When you come back from another Component (Angular 4.0) the map does not have focus. If you try to click e.g. a marker, nothing happens. It needs a second click, then everything is fine.

`setClickable` is set to true.
Tried to run `focus()` on the map-div, but it does not change `document.activeElement`. That is always the body-tag, but it also is the body-tag when you first load the map (then it works fine).

So how to give the maps focus back? I did not have this problem in v1 of this plugin

**Comment by wf9a5m75** [comment]
In that case, you need to execute this code before going back to the map page.

```js
cordova.fireDocumentEvent('plugin_touch', {});
```

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/whats-new-v2/README.md#change-4-save-battery-life

**Comment by dasois** [comment]
thank you very much

**Comment by wf9a5m75** [comment]
@dasois Let me confirm one thing.

When you go back to the map page from another page, did you tap the `back button` of the Android? (comment out `cordova.fireDocumentEvent('plugin_touch', {});` at once)

**Comment by dasois** [comment]
@wf9a5m75 Yes. When i comment out `cordova.fireDocumentEvent('plugin_touch', {});` the map has no focus after going back via the android hardware back-button. With that code it works fine.

This also needs to work on iOS though, where going back is implemented via a back-button in the gui. I suppose it's ok to just always do `cordova.fireDocumentEvent('plugin_touch', {});` then?

**Comment by wf9a5m75** [comment]
I just want to confirm this occurred when you go back to the map page **with tapping the Android back button or not**.

I noticed this yesterday, and I committed code to execute with the plugin_touch event automatically.

https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/33b363d79321e1eee5eb8e57900668289393a9f4

But you can do `cordova.fireDocumentEvent('plugin_touch', {});` by yourself. It's no problem.
