### ISSUE TITLE
direction on markers

### ISSUE THREAD

**Issue by 7aduta** [mapsplugin/cordova-plugin-googlemaps#1543]
i have an idea and i don't know have to achieve it 
i have a place A and place B
and i have a lot of markers in between 
how to draw a line on the map from A to B through all the markers

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=direction&type=Issues&utf8=✓

**Comment by 7aduta** [comment]
i looked it up and i found direction from A to B 
and i couldn't found a way to make the markers part of the direction

**Comment by wf9a5m75** [comment]
You need to get the result of the direction function of Google Maps JavaScriptAPI v3 or  Google Directions API, theb parse it by yourself, then mapping then by yourself.

This plugin does not provide the direction feature.
