### ISSUE TITLE
How to show "Your Location" bottun over map?

### ISSUE THREAD

**Issue by parsarian** [mapsplugin/cordova-plugin-googlemaps#1545]
Hi ,
Is there any way to show "your location" button in ionic projects?
![image](https://user-images.githubusercontent.com/25129775/28051176-cf237572-6617-11e7-9bf5-6de5ade6b313.png)

**Comment by wf9a5m75** [comment]
The screen capture is not this plugin.

Anyway, this plugin provides myLocation button. Please read documents before asking.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Map/setOptions/README.md

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/setOptions/README.md
