### ISSUE TITLE
How to get access to tracking information?

### ISSUE THREAD

**Issue by parsarian** [mapsplugin/cordova-plugin-googlemaps#1546]
How to get access to tracking Information?
I want to show  some information over map
-) direction from A to B( i got in this plugin is not supported)
-) pointer of device 
-) real time tracking
- )speed, and acceleration information.

could you please help me?

**Comment by wf9a5m75** [comment]
These features are not provided.

**Comment by parsarian** [comment]
Any idea how to get access them?

**Comment by wf9a5m75** [comment]
Please ask at StackOverflow.

**Comment by parsarian** [comment]
@wf9a5m75  Great Thanks.
