### ISSUE TITLE
cordova browser platform target

### ISSUE THREAD

**Issue by eskhool** [mapsplugin/cordova-plugin-googlemaps#1549]
Has any thought/effort gone into implementing the cordova browser target using the Google Maps Web API v3? 

1. Has there been any work/thoughts in this direction?
2. Are there other folk interested in developing/testing/supporting/needing this?
3. Any thoughts on which branch/code base and where to begin/gotchas to keep in mind/?

**Comment by wf9a5m75** [comment]
Why do you guys want to develop a browser version?????

The Google Maps JavaScript v3 is already existed, and it's very powerful than this plugin.

**Comment by eskhool** [comment]
The idea is to have a single code base in javascript which works for the App on iOS, Android (using Native Google Maps) and same code then work in a website using the Google Maps API v3 without having to make different javascript calls to it.

**Comment by wf9a5m75** [comment]
Since Google Maps Android API v2 and Google Maps SDK for iOS are designed for different concept from Google Maps JavaScript API v3, there are not compatible.
So I have **no plan** to develop the website version.
