### ISSUE TITLE
1.4.0: Create Map on app-start

### ISSUE THREAD

**Issue by JaneDawson** [mapsplugin/cordova-plugin-googlemaps#1550]
Thank you for this great Plugin! I'm using v1.4.0 of your plugin for an Ionic 3 App.

My map is not on the main pages of my app. So the user has to navigate to it. Whenever the user first opens the map (and the `googleMaps.create(element);` is called the first time) a white fullscreenpage flashes for about 0.5 seconds, which is not hurting anybody, but no good UX.
When the user then goes back and navigate to the page again everything is as it's supposed to be. It's really only when the map is opened for the first time after starting the app.

Hence my question: Is it possible to create the map earlier? Without any markers on it, just initialize the map. For example when the app is started initially? Then the user probably wouldn't even notice this...

By now, I create the app in the `ngAfterViewInit()` Lifecycle hook on the map page (which is - as said before - none of my main pages).

Thank you very much and best regards.

**Comment by wf9a5m75** [comment]
Since this plugin uses native Google Maps view, it takes a few seconds

**Comment by JaneDawson** [comment]
Yes, I believe that. But even if I wait on my starting page for 5 minutes and then navigate to the MapPage, I experience this issue.
This is why I'm asking if there is a way to initiate the creation of the map for example from my homePage. If it was created before the user navigates to the MapPage I guess there won't be this "white flashing transition"...

**Comment by wf9a5m75** [comment]
Did you try to create map without div?
Then you can set the map div with `map.setDiv()`.

(If the ionic wrapper is written correctly)

**Comment by JaneDawson** [comment]
According to the Ionic Documentation, there is a `setDiv(domNode)` for the ionic wrapper, as well.

But I'm not sure if I fully understand the approach you're suggesting. Creating the map on another page without a div? How can I do this? 
Currently on my MapPage I use: `this.map = this.googleMaps.create(element);` and pass the div (`element`) to the create function.

**Comment by wf9a5m75** [comment]
`this.map = this.googleMaps.create()`

**Comment by JaneDawson** [comment]
That gives me a TS Error: 
```
[ts] Expected 1-2 arguments, but got 0.
(method) GoogleMaps.create(element: string | HTMLElement, options?: any): GoogleMap
```

**Comment by wf9a5m75** [comment]
In that case, you need to give up.

**Comment by wf9a5m75** [comment]
Why don't you display some message such as `loading...`, then remove it after the `MAP_READY` event.

**Comment by JaneDawson** [comment]
Yes, you're right, I can do that. That at least hides the "flashing page" behind a loading component... Probably our best shot... Thanks.
If you come up with any other idea, please let me know...
