### ISSUE TITLE
Text On Marker

### ISSUE THREAD

**Issue by belgarad** [mapsplugin/cordova-plugin-googlemaps#1551]
Is there a way to create label right on marker itself?

**Comment by wf9a5m75** [comment]
No.

**Comment by wf9a5m75** [comment]
Correction my previous answer. It's possible using `base64 encoded icon`.

You can specify base64 encoded image to the `icon` and `title` properties (only support GIF, PNG, or JPEG, does not SVG).

Check out this page.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md#base64-encoded-icon

**Comment by belgarad** [comment]
thank you its working great...
