### ISSUE TITLE
HTMLInfoWindow is not clickable if map-page gets loaded via navCtrl.setRoot

### ISSUE THREAD

**Issue by dasois** [mapsplugin/cordova-plugin-googlemaps#1552]
Branch: multiple_maps (v2)

This is a Ionic 3 App Scenario:
If you load the map directly on the homescreen, everything works fine.
If you go into the map-page via menu (navCtrl.setRoot), map is loading, markers are displayed, you can click any marker, but the InfoWindow's click-handler does not get executed then. Instead I think the click is passed through to the map (because InfoWindow disappers and you can drag the map).

Chrome Dev-Tools can click the HTMLInfoWindow and the handler executes correctly.

**Comment by wf9a5m75** [comment]
I'm not familiar with ionic at all. But as I said couple of times (and as you may know), HTMLinfoWindow just adjusts the position of your contents.

**Comment by wf9a5m75** [comment]
Ah , I guess you use the click handler of ionic(angular)? If so, it's not possible. Because ionic does not manage the HTML elements that are created dynamically.

**Comment by dasois** [comment]
Hi, thanks for your reply! :)
As I said, the click handler works fine if you directly go to this page. It only does not work if you come via setRoot...
It is not an Angular click-event listener. Instead I set the click handler via:
```
infoDiv.addEventListener("click", () => {
                    console.debug("click-handler run");
                });
```

**Comment by wf9a5m75** [comment]
I'm sorry but I'm really not familiar with ionic. What is `setRoot`?

In order to understand how to handle click position this plugin, you need to learn about native side.
Are you familiar with Android/iOS development?
If so, I will tell you. But if not so much, please just share your project files on github or bitbucket.
I will check your project files.

How to and why?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by dasois** [comment]
Hi, thanks for your offer, it would be very kind, if you'd take a look at it:
https://github.com/fr4gstar/findlunch.git
branch: fix_map-infowindow-not-clickable

**Comment by wf9a5m75** [comment]
Thank you for sharing your project files.
The reason was the depth calculation of the HtmlInfoWindow contents was incorrect for some reason.
Please reinstall the plugin.

**Comment by wf9a5m75** [comment]
ping

**Comment by dasois** [comment]
solved it, thanks!
