### ISSUE TITLE
A map instance per page

### ISSUE THREAD

**Issue by carvemerson** [mapsplugin/cordova-plugin-googlemaps#1553]
Hello,

What is the best way to use this plugin in multiple pages? 
I want a different instance of the map per page. 
I'm using the [version 2 of this plugin.](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/README.md)

In the main page, to create a map instance, I'm using: 
mainMap = plugin.google.maps.Map.getMap(div).

In a diferente page I have a list. When I click in a element of this list, I want to open a new page with a different instance of the map.

Do I need creating a new map for each page the I will open?: 
newMap = plugin.google.maps.Map.getMap(div)

I do this and I realized that the memory consumption increases rapidly.
Is this correct?

Thank you in advance for your attention.

**Comment by wf9a5m75** [comment]
>Do I need creating a new map for each page the I will open?:
> newMap = plugin.google.maps.Map.getMap(div)

Yes, you do.

>I do this and I realized that the memory consumption increases rapidly.
> Is this correct?

Yes, it is correct.

If you don't use the previous map, you should remove the map. (`map.remove()`)

Or clean up the map, and reuse it (this is better way).

```js
map.clean(); // remove all overlays
map.setDiv(null); // detach the map at once

map.setDiv(div);  // attach the map to new div
```
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/setDiv/README.md

**Comment by carvemerson** [comment]
Ok, I will try this!!

Thanks!

**Comment by carvemerson** [comment]
Well, I created a service called `MapService`. In this service I keep a instance of the map. So, all pages will use this instance. 
When I enter in the page I set the map div and init (centralize, add marker, etc) It again:
```
ionViewDidEnter() {
        this.mapService.map.setDiv(mapElement);
        this.initMap(); // add markers, polylines, etc
}
```

When I leave the page, I clean  the map and  detach the map

```
 ionViewWillLeave() {
        this.mapService.map.clean();
        this.mapService.map.setDiv(null);
 }
```

When I navigate to the any other page (not necessarily with a map) and go back to page with a map, the page stay white until I touch that. 
Look this prints:

Main Page:
![screenshot from 2017-07-13 18-41-41](https://user-images.githubusercontent.com/6718864/28189160-341a8350-67fb-11e7-8906-d39c0e36d4cd.png)

Other page:
![screenshot from 2017-07-13 18-42-20](https://user-images.githubusercontent.com/6718864/28189190-5b15f476-67fb-11e7-96c8-089a6c5ba290.png)

Back to main page:
![screenshot from 2017-07-13 18-42-42](https://user-images.githubusercontent.com/6718864/28189200-67e1545c-67fb-11e7-9426-6903edf26dda.png)

After a touch:
![screenshot from 2017-07-13 18-41-41](https://user-images.githubusercontent.com/6718864/28189160-341a8350-67fb-11e7-8906-d39c0e36d4cd.png)

what am I doing wrong?

**Comment by wf9a5m75** [comment]
You need to execute `cordova.fireDocumentEvent('plugin_touch', {});` when enter to the map page or leave the previous page.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/whats-new-v2/README.md#change-4-save-battery-life

**Comment by carvemerson** [comment]
Thank you!
This solved my problem!
Congratulations for the plugin, this is very good !!
