### ISSUE TITLE
Cannot install google maps plugin 

### ISSUE THREAD

**Issue by lampofdrog** [mapsplugin/cordova-plugin-googlemaps#1554]
hello,

i execute the command to install the plugin and i got 

![screen shot 2017-07-14 at 11 24 40](https://user-images.githubusercontent.com/11801709/28208875-d8bb6884-6887-11e7-9328-fd0ca3bc13a9.png)

![screen shot 2017-07-14 at 12 51 00](https://user-images.githubusercontent.com/11801709/28211197-4b0d417c-6893-11e7-8f54-93e4a8599540.png)

Help plz

**Comment by lampofdrog** [comment]
![screen shot 2017-07-14 at 12 51 00](https://user-images.githubusercontent.com/11801709/28211177-316b3198-6893-11e7-8ecf-b42f2cfbfcc3.png)

**Comment by wf9a5m75** [comment]
Please update your git command, npm command to the latest version.

**Comment by carvemerson** [comment]
I have a similar problem.
When I execute this command:
`
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="mykey" --variable API_KEY_FOR_IOS="mykey"
`
I got this error:

```
Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
module.js:487
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (my/path/node_modules/@ionic/app-scripts/node_modules/node-sass/scripts/install.js:10:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm WARN @angular/platform-server@4.2.5 requires a peer of @angular/animations@4.2.5 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
This are my vesion
cordova -v 7.0.1
node -v 8.1.4
npm -v 5.0.3

**Comment by wf9a5m75** [comment]
This plugin does not use the `request` module at all.

**Comment by wf9a5m75** [comment]
Please try these commands:

```
$> npm -g uninstall cordova ionic
```

Then update your git command (for just in case)
https://git-scm.com/

After that,
```
$> npm -g install cordova ionic --no-fetch
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="mykey" --variable API_KEY_FOR_IOS="mykey" --no-fetch
```

**Comment by carvemerson** [comment]
I was create a new project and the plugin install normally.
But in my main project it is not working.
There is any incompatibility with some plugin?

**Comment by carvemerson** [comment]
Well, I remove the folder node_module, execute npm update and npm install. 
After that,  I could install the plugin again.

**Comment by wf9a5m75** [comment]
@lampofdrog ping

**Comment by lampofdrog** [comment]
@wf9a5m75  i will test this solution and i come back to confirm , thank you ;)

**Comment by wf9a5m75** [comment]
@lampofdrog ping

**Comment by wf9a5m75** [comment]
ping

I think you need to install the latest node.js and npm.

**Comment by wf9a5m75** [comment]
Try to install the latest npm version
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1578

or downgrade the cordova version
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1579

**Comment by wf9a5m75** [comment]
Since there is no response from @lampofdrog for a while, I close this issue at once.
But you can still response anytime.

**Comment by ZiFFeL1992** [comment]
With `--no-fetch` parameter on `cordova plugin add ...` should be enough, there are problems installing some plugins via `npm`.

**Comment by DanFast** [comment]
downgrade the cordova version to 6.5.0
 #17821
