### ISSUE TITLE
HTMLInfoWindows are overlaying each other on iOS when clicking directly on the next marker

### ISSUE THREAD

**Issue by dasois** [mapsplugin/cordova-plugin-googlemaps#1555]
Branch: multiple_maps (v2)

### Scenario
1. Have mulitple Markers with different HTMLInfoWindows on a Map nearby.
2. Click on the marker with the bigger InfoWindow, it opens
3. **Directly** click on the other marker, you will see the smaller InfoWindow being in front of the other, but the bigger one didn't dismiss.

### Underlying problem
The old marker is not closed properly on iOS, because of the following code
```js
self.on("active_marker_id_changed", function(prevId, newId) {
  if (prevId in self.MARKERS) {
    if (self.MARKERS[prevId].isInfoWindowShown()) {
      self.MARKERS[prevId].trigger.call(self.MARKERS[prevId], event.INFO_CLOSE);
    }
  }
  exec(null, null, self.id + "-marker", 'setActiveMarkerId', [newId]);
});
```
`isInfoWindowShown()` returns `false`, because in it
```js
Marker.prototype.isInfoWindowShown = function() {
    var map = this.getMap();
    return map && map.get('active_marker_id') === this.id;
};
```
the call `map.get('active_marker_id')` **returns newId and not prevId**.

**Comment by wf9a5m75** [comment]
Thank you for filing another issue. I appreciate if you send a pull request also. I'm so tired.

**Comment by dasois** [comment]
What do you think: Should we either:
- Investigate, why `active_marker_id` is the newId only on iOS or
- replace with `map.get('active_marker_id') !== undefined && map.get('active_marker_id') !== null`

**Comment by wf9a5m75** [comment]
Thank you.
Since HtmlInfoWindow is managed in JavaScript side mainly, I think this issue might be occurred on Android also (at least there is potential).

**Comment by dasois** [comment]
I understand your point and that's what I thought as well, but I'm developing mainly with android devices, which never showed this issue before...

**Comment by wf9a5m75** [comment]
I see.

**Comment by wf9a5m75** [comment]
Could you make a small test code?

**Comment by dasois** [comment]
it's my project again...

**Comment by wf9a5m75** [comment]
Here you are.
![1555_ios](https://user-images.githubusercontent.com/167831/28228356-043b6be8-6893-11e7-9f9d-f1b57c88fa7d.gif)

**Comment by wf9a5m75** [comment]
This is screen record on Android
![1555_android](https://user-images.githubusercontent.com/167831/28228392-2a86912e-6893-11e7-887d-d07fd62f6751.gif)

**Comment by wf9a5m75** [comment]
Please reinstall the plugin.

**Comment by dasois** [comment]
Very nice, thanks! :1st_place_medal:
