### ISSUE TITLE
node.classname Error - ionic 3 ion-spinner

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1558]
Plugin version: `2.0.0-beta2-20170714-1245`
Ionic version: `3.5.3`

When creating a new ionic project with the map plugin and adding an `ion-spinner` in the HTML,
I get the following error:
 `node.classname || "").split is not a function`

```
<ion-spinner name="dots"></ion-spinner>
<div #map id="map" style="width:100%; height:100%;"></div>
```

**Comment by antoine92190** [comment]
How can I revert to a previous version of the plugin to know which version created the error?
For exemple revert to `2.0.0-beta2-20170713-1545`

**Comment by antoine92190** [comment]
I just noticed that the issue also happens with the `ion-refresher` component.

```  <ion-refresher (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
```

**Comment by wf9a5m75** [comment]
ion-spinner? What is that? This plugin does not modify for it at all.

Please share your project files on github or bitbacket. No more zip file.

**Comment by antoine92190** [comment]
You can test with the following repo:
https://github.com/antoine92190/ionic-map

**Comment by wf9a5m75** [comment]
Thank you for sharing your project files.
I have been inspecting your project.

This is really strange.
The error occurs this line.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/5ba0f0bd3c4abefb9398a2b1c41e8b5699f9fdfb/www/Map.js#L123

```js
        args.push(options);

        div.style.overflow = "hidden";
        self.set("div", div);   // <------ The error occurs here

        if (div.offsetWidth < 100 || div.offsetHeight < 100) {
        ...
```

But you can see, the set() method is very simple.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/5ba0f0bd3c4abefb9398a2b1c41e8b5699f9fdfb/www/BaseClass.js#L16-L22

```js
  self.set = function(key, value, noNotify) {
    var prev = _vars[key];
    _vars[key] = value;
    if (!noNotify && prev !== value) {
      self.trigger(key + "_changed", prev, value);
    }
  };
```

So this plugin should not affect to outside of this plugin at all.

I think asking to the ionic team has a good answer for your issue.

**Comment by wf9a5m75** [comment]
Yeah, it seems this occurs must be in ionic.

Similar issue was found.
https://github.com/ionic-team/ionic-service-analytics/issues/34

Unfortunately, the things I can do are that's all.

**Comment by antoine92190** [comment]
Thanks for looking at it, I'll ask the ionic team then.

I'm not sure if the error appeared because of your recent updates or the ionic ones.
Do you know how I can revert to the `2.0.0-beta2-20170713-1545` version of your plugin so I can check?

Anyway, until it is fixed, I need to revert back to this version as my app is currently in prod.

**Comment by wf9a5m75** [comment]
You can revert any old version.

step1: Find the commit you want to use. The miner version number indicates date and time. This is helpful to find out the commit.

```
2.0.0-beta2-20170713-1545
                      YYYYMMDD-HHSS
```

https://github.com/mapsplugin/cordova-plugin-googlemaps/commits/multiple_maps

step2: uninstall the current version.

```
$> cordova plugin rm cordova-plugin-googlemaps
```

step3: install the version from commit ID
```
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#6a50bda087e3cada5ea0d8766affb687df21b51c --variable API_KEY_FOR_ANDROID="(YOUR KEY)" --variable API_KEY_FOR_IOS="(YOUR KEY)"
```

**Comment by antoine92190** [comment]
Thanks a lot!
I'll open an issue on ionic and let you know how it goes :wink:

**Comment by antoine92190** [comment]
Just so you know, I do not get the error when reverting to `2.0.0-beta2-20170713-1545`

**Comment by antoine92190** [comment]
Sure

**Comment by wf9a5m75** [comment]
I got the reason. This occurs by the elements of SVG.

**Comment by wf9a5m75** [comment]
I fixed the issue. Please reinstall the latest version`2.0.0-beta2-20170716-1535` or higher.

By the way, as you may know, don't hide the Google Logo. This is against the terms of Google Maps API.

![screen shot 2017-07-16 at 3 38 07 pm](https://user-images.githubusercontent.com/167831/28251933-d19e2bc0-6a3c-11e7-8422-9149d9320e6a.png)

**Comment by antoine92190** [comment]
Awesome, thanks again!!
Yes I know, the spinner pushes the map down but this repo is only for testing purposes.
I'll check your update and close if everything works.

**Comment by antoine92190** [comment]
:thumbsup:
