### ISSUE TITLE
Click event for HTML Info Window

### ISSUE THREAD

**Issue by felixliu226** [mapsplugin/cordova-plugin-googlemaps#1560]
Hello,

The version I'm using is 2.0.0-beta2-20170714-1245. I would like to ask that is there any possible way to add event listener to HtmlInfoWindow? and trigger a function when click the infoWindow?

I tried to use 
marker.on(plugin.google.maps.event.INFO_CLICK, function() {})
, but it only works for the infoWindow created by 
map.addMarker({title: "abc"});
but not works for the HtmlInfoWindow.

Could any one help to suggest about how to add the click event for HtmlInfoWindow? Thanks in advance.

**Comment by stalniy** [comment]
try 
```js
info.get('frame').addEventListener('click', function() {
  console.log('run your function here!')
})
```

**Comment by wf9a5m75** [comment]
That is not good way, because you access internal variable. I don't guarantee to keep the same variable name.

Correct way is

```js

var div = document.create Element("div");
div.innerHTML="your HTML";
div.addEventListner("click", function () {});

htmlInfoWindow.set content(div);
```

**Comment by wf9a5m75** [comment]
@felixliu226  ping

**Comment by felixliu226** [comment]
Sorry for the late reply. Thanks for your method, it works as expected.
