### ISSUE TITLE
HtmlInfoWindow is displayed in out side of the map view

### ISSUE THREAD

**Issue by tennist** [mapsplugin/cordova-plugin-googlemaps#1561]
I am having trouble with my HTML Info Windows.  For some reason, the default anchor position is extremely far from my marker icons.  This happens even if I use the default marker icon.  

I am using the latest v2 of this plugin.

![image](https://user-images.githubusercontent.com/23710022/28249928-d73ca012-6a13-11e7-83c3-1f20af3ae7f8.png)

I am using the code as provided in the documentation for creating info windows.  The only change I made to it is the HTML that is sent to it.

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbacket.

**Comment by tennist** [comment]
Here is the code for creating the map in my app.

`function ale_trail_find_brews_map_pageshow() {
    
	// Build the lat lng object from the user's position.
          myLatlng = new plugin.google.maps.LatLng(
          _ale_trail_user_latitude,
          _ale_trail_user_longitude
        );  
	
	
	// Set the map's options.
        var mapOptions = {
          'controls': {
			'compass': true,
			'myLocationButton': true,			
			'zoom': true
		  },
		  'gestures': {
			'scroll': true,
			'tilt': true,
			'rotate': true,
			'zoom': true
		  },
		  'camera': {
			'latLng': myLatlng,			
			'zoom': 13			
		  }
		  
        };			
        
        // Initialize the map
        _ale_trail_map = new plugin.google.maps.Map.getMap(
          document.getElementById("ale_trail_find_brews_map_map"),
          mapOptions
        );
        
		//Wait for the map to be ready then add markers to it
		_ale_trail_map.one(plugin.google.maps.event.MAP_READY, function() {
		
			//Add markers for brewery locations
			var range = 100; // Search within a 100 mile radius.
			var path1 = 'find-brews-app/' +
			_ale_trail_user_latitude + ',' + _ale_trail_user_longitude + '_' + range;
			
			views_datasource_get_view_result(path1, {
			  success: function(data) {
				if (data.nodes.length > 0) {
				  
				  $.each(data.nodes, function(index, object){
					  var node = object.node;
					  var nodeLatlng = new plugin.google.maps.LatLng(node.latitude, node.longitude);
					  
					  //Create Address Object
						var address = new Array();
						if (node.street && node.street != '') {
							address['thoroughfare'] = node.street;
						};
						if (node.additional && node.additional != '') {
							address['premise'] = node.additional;
						};
						if (node.city && node.city != '') {
							address['locality'] = node.city;
						};
						if (node.province && node.province != '') {
							address['administrative_area'] = node.province;
						};
						if (node.postal_code && node.postal_code != '') {
							address['postal_code'] = node.postal_code;
						};
						if (node.country && node.country != '') {
							address['country'] = node.country.toUpperCase();
						};
						
						//Create Formatted Address				    
						var formatted_address = theme_addressfield(address);
					  
					  //Create Google Maps Link
						var place = formatted_address.replace(/<br\s*\/?>/mg,"+");
						var place = place.replace(/\s/g,"+");			
						var map_link = 'https://www.google.com/maps/search/?api=1&query=' + node.title.replace(/\s/g,"+") + '+' + place;				
						
				
					  //Create the Address Div
						var address_div = '<div style="clear:both; overflow:auto;">'
						+ '<div style="float:left;">'
						+	'<b> Address: </b>'
						+  '</div>'
						+  '<div style="float:left; margin-left:5px;">'		  
						+	'<a href="' + map_link + '" target="_blank">' + formatted_address + '</a>'	
						+  '</div>'					
						+ '</div>';
						
					  //Create Phone Div
						if (node.phone && node.phone != '') {
							
							var phone_div = '<div style="clear:both; margin-top:10px;">';
						  
							//Strip phone number to digits only
							phone_digits = node.phone.replace(/\-/g,"");
							phone_digits = phone_digits.replace(/\./g,"");
							phone_digits = phone_digits.replace(/\(/g,"");
							phone_digits = phone_digits.replace(/\)/g,"");
							phone_digits = phone_digits.replace(/\+/g,"");
							phone_digits = phone_digits.replace(/\s/g,"");
							
							//Remove any country codes that exist
							if (phone_digits.length > 10) {
								extra = phone_digits.length - 10;
								phone_digits = phone_digits.substr(extra, 10);
							}
							
							//Create number to be displayed to user
							phone_display = phone_digits.substr(0, 3) + '-' + phone_digits.substr(3, 3) + '-' + phone_digits.substr(6, 4);

							//Convert any letters to numbers
							phone_numbers = phone_digits.replace(/new Array("A","B","C","a","b","c")/g,"2");
							phone_numbers = phone_numbers.replace(/new Array("D","E","F","d","e","f")/g,"3");
							phone_numbers = phone_numbers.replace(/new Array("G","H","I","g","h","i")/g,"4");
							phone_numbers = phone_numbers.replace(/new Array("J","K","L","j","k","l")/g,"5");
							phone_numbers = phone_numbers.replace(/new Array("M","N","O","m","n","o")/g,"6");
							phone_numbers = phone_numbers.replace(/new Array("P","Q","R","S","p","q","r","s")/g,"7");
							phone_numbers = phone_numbers.replace(/new Array("T","U","V","t","u","v")/g,"8");
							phone_numbers = phone_numbers.replace(/new Array("W","X","Y","Z","w","x","y","z")/g,"9");
							
							//Create phone link
							phone_div = phone_div + '<b>Phone: </b><a href="tel:' + phone_numbers + '">' + phone_display +'</a>';				
							phone_div = phone_div + '</div>';	
						}
						
						//Create Website Div
						if (node.website && node.website != '') {
							
							var website_div = '<div style="clear:both; margin-top:10px;">';	  
								
							//Output website link
							website_div = website_div + '<b>Website: </b><a href="' + node.website + '" target="_blank">' + node.website + '</a>';
							
							website_div = website_div + '</div>';	
						} else if (node.node_website.length > 0){
							var website_div = '<div style="clear:both; margin-top:10px;">';	  
								
							//Output website link
							website_div = website_div + '<b>Website: </b><a href="' + node.node_website + '" target="_blank">' + node.node_website + '</a>';
							
							website_div = website_div + '</div>';
						}
					  
					  //Combine all html
					  var contentString = '<div style="zoom: 0.75;">'+					
						'<h3>' + '<a onclick="javascript:drupalgap_goto(' + "'node/" + node.nid + "'" + ');">' + node.title + '</a></h3>'+
						address_div +
						phone_div +
						website_div +
						'<br><b>Distance:</b> ' + node.distance + '<br>' +
						'<br><b>Rating:</b> ' + ale_trail_fivestar_rating(node.rating) +
						'</div>';			  
					  
					  //Create info window for marker
					  var htmlinfowindow = new plugin.google.maps.HtmlInfoWindow();
					  htmlinfowindow.setContent('test');
					  
					  //Add marker to map
					  _ale_trail_map.addMarker({
						position: nodeLatlng,
						map: _ale_trail_map,					
						icon: 'app/modules/custom/ale_trail/blue-dot.png'
					  }, function(marker) {					
						marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
						  htmlinfowindow.open(marker);
						});
						marker.trigger(plugin.google.maps.event.MARKER_CLICK);					
					  }); 
					  
				  });
				  
				  // Add a marker for the user's current position.
					_ale_trail_map.addMarker({
						position: myLatlng,            
						icon: 'app/modules/custom/ale_trail/red-dot.png'
					});			  
				}
			  }
			});	
		});	
}`

**Comment by tennist** [comment]
Also I am getting a bunch of the following errors in my console.

 [INFO:CONSOLE(207)] "Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.", source: file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/HtmlInfoWindow.js (207)

[INFO:CONSOLE(68)] "Uncaught TypeError: Cannot read property 'getMap' of undefined", source: file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/HtmlInfoWindow.js (68)

**Comment by wf9a5m75** [comment]
I asked "Please share your project files on **github or bitbacket**".

**Comment by wf9a5m75** [comment]
How and why?
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/articles/before_post_your_issue/README.md#6-provide-your-code

**Comment by wf9a5m75** [comment]
If you don't want to share your project files, I can't help you. Because this error occurs in only your project. I can not reproduce your issue.

**Comment by tennist** [comment]
I understand, my project is very large for uploading and currently has a bunch of api access information coded throughout it that I am not allowed to share.  I am able to send segments of my code that do not contain this info however.  There are also portions of code from others that have strictly told me not to distribute.  This is the only function on which I refer to the plugin and had assumed there may be some error in it.

**Comment by wf9a5m75** [comment]
If I can not build your project files, I can not reproduce your issue. I offered "I can accept NDA".
Even no, please close this issue, and resolve your issue by yourself.
I'm really busy. No contribution, no help.

**Comment by tennist** [comment]
I understand and apologize for wasting any of your time.  I was hoping it might have been something simple in my code above that you could point out.  When I resolve the issue, I will let you know if it is something that requires changes in your code or if it is something I did wrong on my end.

**Comment by wf9a5m75** [comment]
Sorry. It is my best answer. But please let me know if you find something. Thank you for using this plugin.
I close this issue, but you can still reply for this issue later.

**Comment by tennist** [comment]
After more troubleshooting, I think there might be a big incompatibility between the plugin and my platform.  I am running Cordova and DrupalGap.  I tried just loading a basic map on my page without markers or any html info windows and found an even bigger issue.  The problem is once I navigate to another page of the app, the map container doesn't close completely.  The map goes away, but the containers stays.   This container is on top of all other pages, menus, etc. and doesn't allow me to click in any text boxes or on any links other than those that are outside of the container limits.

**Comment by wf9a5m75** [comment]
I have never tested this plugin with `DrupalGap`. There were no user so far.
If you create a simple test project (just a map with DrupalGap), then I will test it.

**Comment by tennist** [comment]
Drupalgap is not so easy to setup a quick example app as a fake website has to be setup as well.  I got it done though.  The link below has the files for the example app.  Once you build this app and run it, load the map link from the menu in the upper left corner.  Then click the home button to take you back to the home screen.  Then try to open taxonomy, users, users2, or content 2 in the menu button.  Those links do not work.  But the first two links do work.  These links are ones that would not be in the same area of the screen as the map was.

https://github.com/tennist/drupalgap-test-map

**Comment by wf9a5m75** [comment]
Thank you for preparing the test app.
I was terribly busy today. Now I'm cloning the repo.

**Comment by wf9a5m75** [comment]
I just built your repo, but I got this error. What should I do?

![capture](https://user-images.githubusercontent.com/167831/28299887-76a9ae98-6b30-11e7-9bec-fa5a6118f25e.png)

**Comment by tennist** [comment]
That's interesting, I set the site path and made sure everything was working before I commit the app.  Go into the file www/app/setting.js.  Line 18 should read
'''
Drupal.settings.site_path = 'http://dev-testmap.pantheonsite.io/';
'''

**Comment by tennist** [comment]
I found an old .gitignore file in the drupalgap project that was causing a significant amount of the app to not be pushed to git.  Please try downloading the project again.

**Comment by wf9a5m75** [comment]
Thank you for the update. I could build your repo.

By the way, this is incorrect.

```js
// Initialize the map
_ale_trail_map = new plugin.google.maps.Map.getMap(
  document.getElementById("ale_trail_find_brews_map_map"),
  mapOptions
);
```

Correctly, no need to `new`

```js
// Initialize the map
_ale_trail_map = plugin.google.maps.Map.getMap(
  document.getElementById("ale_trail_find_brews_map_map"),
  mapOptions
);
```

**Comment by wf9a5m75** [comment]
Ok, I fixed the bug. This was CSS problem.
Please reinstall the latest plugin (`2.0.0-beta2-20170718-1602` or higher)

```js
  //Wait for the map to be ready then add markers to it
  _ale_trail_map.one(plugin.google.maps.event.MAP_READY, function() {

    var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();
    //Create the Address Div
    var address_div = '<div style="clear:both; overflow:auto;">' +
      '<div style="float:left;">' +
      '<b> Address: </b>' +
      '</div>' +
      '<div style="float:left; margin-left:5px;">' +
      '<a href="http://maps.google.com" target="_blank">Open the Google Maps</a>' +
      '</div>' +
      '</div>';

    // Add a marker for the user's current position.
    _ale_trail_map.addMarker({
      position: myLatlng,
      icon: 'app/modules/custom/ale_trail/red-dot.png'
    }, function(marker) {
      marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
        htmlInfoWindow.setContent(address_div);
        htmlInfoWindow.open(marker);
      });
    });
  });
```

![capture](https://user-images.githubusercontent.com/167831/28343571-e3646544-6bd2-11e7-8bd8-a6660eba5f70.png)

**Comment by tennist** [comment]
Everything works perfect now.  Thanks for all your help on this.  I figured it had to be something as simple as CSS and that you'd know right where to go.   Thanks for putting together this awesome plugin.
