### ISSUE TITLE
Google Map not showing in prod release

### ISSUE THREAD

**Issue by ypkkhatri** [mapsplugin/cordova-plugin-googlemaps#1562]
Hi,

I developed cross platform app in Ionic 3, and added this plugin, Map showing perfect in debug build, but showing empty in prod release, please see the attached file.

Version:
cordova-plugin-googlemaps:  1.4.3

Please help me, my prod release is stuck now

Thanks 

![d8235098-3289-4fcc-8678-d3ea58dbc30a](https://user-images.githubusercontent.com/16644003/28250019-d74b30da-6a79-11e7-9461-0291ad21faf4.jpeg)

**Comment by antoine92190** [comment]
maybe this #1517 can help

**Comment by wf9a5m75** [comment]
Yes, your API key is wrong.

**Comment by wf9a5m75** [comment]
@ypkkhatri ping

**Comment by ypkkhatri** [comment]
Hi, sorry for delay will update here tomorrow, thanks

**Comment by ypkkhatri** [comment]
Hi,
_**It's perfectly fine now**_, I have used by mistaken SHA-1 fingerprint of android.keystore and app build release from my own keystore file so it was stuck.

Thank you
