### ISSUE TITLE
Base64 images for map marker icon not work on v2.0 (beta)

### ISSUE THREAD

**Issue by sawinru** [mapsplugin/cordova-plugin-googlemaps#1566]
I'm updating from 1.4.3 to 2 (beta) and now do not work base64 icon for marker, but on 1.4.3 version, base64 worked perfectly. Even `marker.setIcon` does not help.

cordova version 7.0.1
platform iOS
plugin list:
```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta2-20170705-1715 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.0 "InAppBrowser"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.0.11 "OneSignal Push Notifications"
```

```js
map.addMarker({
	position	: {lat: cart.order.latitude, lng: cart.order.longitude},
	icon		: {
		url		: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgA...uQmCC",
		size	: {
			width	: 22,
			height	: 22
		}
	}
});
```

**Comment by wf9a5m75** [comment]
```js
map.addMarker({
	position	: {lat: cart.order.latitude, lng: cart.order.longitude},
	icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgA...uQmCC"
});
```

**Comment by sawinru** [comment]
I tried it, unfortunately it did not help

**Comment by wf9a5m75** [comment]
Please show me all base64 encoded strings

**Comment by sawinru** [comment]
I took base64 from example - 

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Marker/setIcon/README.md

```data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAACVUlEQVRIS8WWjVXCMBRGwwTqBMIEuAG4ARuIE6gTKBOgEyAT4AbABjKBMIE/C+h3m6S2pWlJ8BzfOTkpad6770teEzom3bZy/VbrpYTopDjJZ6w2c77X6p9j46SCUXvuYDxHq04BZ2rPHXa3y/DRqlPAmdqZW+hrkMZEq44F52q3oGTdrjEpqmPBudoxKVBVKqsU1THgPbW+klNUt4GHCn6idqEGuMveerUeXFGtNTCvah9qaz+n2gMmKMGBnLrfjPFcMirZ7231XUF19RUJkIhPZqXnT8AM9Osy62v0VPihUqIfjWwx1RkJvbxIpjArhabfbEJ6zQYwysiiT3CW8kJ6Q4BgqMALEnqVNAqQZGSkM/R7nMOBLhZ/B/ZQeg9V/1EsrpLy5dIqP8aAXV6WlQIlZrWq/wzeBK0DM3Y0vA0aAh8FPwTaBC7B2W8+qUOMT4l9dYUUrJK2k4tCOHl7O7zK+Xx69nbWU/iebgKz1+9E+OYPToR1fqOe+SquujeBWdzlYGBPohhjW9b2lGbRa72bwLdyml5d2auvaPyeTOzIw4MxzCkal8h8no3cqT3WJd0ExuFmOjXmlhRIXbnfKZQ7hfJ4HDTM8wVIMi6xJ01y3mV8E5glGlDRGIEKS75DrAtFn/0DA3x/b0ddZbPgGt23JnBW0agpKPzUGCvhoT4iv1HG9Zodtc6HGBTYnoXAXc3UR5SbBwK1d8y+8RUAzxNwU2orOwQeyolF/lLT7mUqQ8BqCj4Bt+j1lR0Cs3Sopt8GFLYNF/2JU7K2k6stePL7fwP/AER2xy+mY1/QAAAAAElFTkSuQmCC```

**Comment by wf9a5m75** [comment]
Thanks. And what miner version of the v2 do you use?

**Comment by wf9a5m75** [comment]
```
$ cordova plugin list
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.0.0-beta2-20170716-2155 "cordova-plugin-googlemaps"
                                      ^^^^^^^^^^^^^
```

**Comment by sawinru** [comment]
cordova-plugin-googlemaps 2.0.0-beta2-20170705-1715 "cordova-plugin-googlemaps

**Comment by wf9a5m75** [comment]
Ok, please reinstall the plugin the latest version `2.0.0-beta2-20170716-2155` at least.
I fixed lots of things in a few days. I didn't touch the code around base64, but it is recommended.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.0-beta2/README.md

**Comment by sawinru** [comment]
I'm reinstalled plugin, but it do not help :(

**Comment by wf9a5m75** [comment]
Yes, as I said I didn't touch the code around base64. It means I didn't change the code around base 64 processing. No change about base64.
But other parts are changed. Reinstalling the latest version prevents to face new issues that are already fixed.

I have been testing base64 icon. Please wait. (I'm working on my real job)

**Comment by wf9a5m75** [comment]
I have no problem with the base64 encoded strings.

![screen shot 2017-07-17 at 9 53 55 am](https://user-images.githubusercontent.com/167831/28279609-e0163d7a-6ad5-11e7-9891-94304202107f.png)

```html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title>Hello World</title>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
    </head>
    <body>
        <div id="map"></div>
    </body>
</html>
```

```css
html, body, #map {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
}
```

```js
document.addEventListener('deviceready', function() {
  var map = plugin.google.maps.Map.getMap(document.getElementById("map"));

  map.on(plugin.google.maps.event.MAP_READY, function() {
    map.addMarker({
      position: {lat: 0, lng: 0},
      icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAACVUlEQVRIS8WWjVXCMBRGwwTqBMIEuAG4ARuIE6gTKBOgEyAT4AbABjKBMIE/C+h3m6S2pWlJ8BzfOTkpad6770teEzom3bZy/VbrpYTopDjJZ6w2c77X6p9j46SCUXvuYDxHq04BZ2rPHXa3y/DRqlPAmdqZW+hrkMZEq44F52q3oGTdrjEpqmPBudoxKVBVKqsU1THgPbW+klNUt4GHCn6idqEGuMveerUeXFGtNTCvah9qaz+n2gMmKMGBnLrfjPFcMirZ7231XUF19RUJkIhPZqXnT8AM9Osy62v0VPihUqIfjWwx1RkJvbxIpjArhabfbEJ6zQYwysiiT3CW8kJ6Q4BgqMALEnqVNAqQZGSkM/R7nMOBLhZ/B/ZQeg9V/1EsrpLy5dIqP8aAXV6WlQIlZrWq/wzeBK0DM3Y0vA0aAh8FPwTaBC7B2W8+qUOMT4l9dYUUrJK2k4tCOHl7O7zK+Xx69nbWU/iebgKz1+9E+OYPToR1fqOe+SquujeBWdzlYGBPohhjW9b2lGbRa72bwLdyml5d2auvaPyeTOzIw4MxzCkal8h8no3cqT3WJd0ExuFmOjXmlhRIXbnfKZQ7hfJ4HDTM8wVIMi6xJ01y3mV8E5glGlDRGIEKS75DrAtFn/0DA3x/b0ddZbPgGt23JnBW0agpKPzUGCvhoT4iv1HG9Zodtc6HGBTYnoXAXc3UR5SbBwK1d8y+8RUAzxNwU2orOwQeyolF/lLT7mUqQ8BqCj4Bt+j1lR0Cs3Sopt8GFLYNF/2JU7K2k6stePL7fwP/AER2xy+mY1/QAAAAAElFTkSuQmCC"
    });
  });

});

```

**Comment by wf9a5m75** [comment]
ping

**Comment by sawinru** [comment]
I crate other new project and crate map, base64 works. I will search a problem in other methods, may be other plugin confilcts with google-map

**Comment by wf9a5m75** [comment]
Ok. Thank you for updating.

**Comment by trin4ik** [comment]
maybe i found this bug. 
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/932bab00847c720fe4b57c5da0c06001cbf60e65
this commit for wkwebview crash base64 icon.

this code in PluginMarket.m:

`NSRange range = [iconPath rangeOfString:@"http"];
        if (range.location != 0) {

            range = [iconPath rangeOfString:@"://"];
            if (range.location == NSNotFound) {

                range = [iconPath rangeOfString:@"/"];
                if (range.location != 0) {
                  // Get the current URL, then calculate the relative path.
                  CDVViewController *cdvViewController = (CDVViewController*)self.viewController;

                  id webview = cdvViewController.webView;
                  NSString *clsName = [webview className];
                  NSURL *url;
                  if ([clsName isEqualToString:@"UIWebView"]) {
                    url = ((UIWebView *)cdvViewController.webView).request.URL;
                  } else {
                    url = [webview URL];
                  }
                  NSString *currentURL = url.absoluteString;
                  currentURL = [currentURL stringByDeletingLastPathComponent];

                  range = [currentURL rangeOfString:@"http"];
                  if (range.location != 0) {

                    currentURL = [currentURL stringByReplacingOccurrencesOfString:@"file:" withString:@""];
                    currentURL = [currentURL stringByReplacingOccurrencesOfString:@"//" withString:@"/"];
                    iconPath = [NSString stringWithFormat:@"file://%@/%@", currentURL, iconPath];
                  } else {
                    iconPath = [NSString stringWithFormat:@"%@/%@", currentURL, iconPath];
                  }
                } else {
                  iconPath = [NSString stringWithFormat:@"file://%@", iconPath];
                }
            }

        }`

added prefix `http/` to `data:image…`

**Comment by wf9a5m75** [comment]
@trin4ik Could you show me the example  data strings that the app crash?

**Comment by trin4ik** [comment]
app does`t crash, my english bad ) 
js code:
`addMarker({
									position	: {lat: item.latitude, lng: item.longitude},
									icon		: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAACVUlEQVRIS8WWjVXCMBRGwwTqBMIEuAG4ARuIE6gTKBOgEyAT4AbABjKBMIE/C+h3m6S2pWlJ8BzfOTkpad6770teEzom3bZy/VbrpYTopDjJZ6w2c77X6p9j46SCUXvuYDxHq04BZ2rPHXa3y/DRqlPAmdqZW+hrkMZEq44F52q3oGTdrjEpqmPBudoxKVBVKqsU1THgPbW+klNUt4GHCn6idqEGuMveerUeXFGtNTCvah9qaz+n2gMmKMGBnLrfjPFcMirZ7231XUF19RUJkIhPZqXnT8AM9Osy62v0VPihUqIfjWwx1RkJvbxIpjArhabfbEJ6zQYwysiiT3CW8kJ6Q4BgqMALEnqVNAqQZGSkM/R7nMOBLhZ/B/ZQeg9V/1EsrpLy5dIqP8aAXV6WlQIlZrWq/wzeBK0DM3Y0vA0aAh8FPwTaBC7B2W8+qUOMT4l9dYUUrJK2k4tCOHl7O7zK+Xx69nbWU/iebgKz1+9E+OYPToR1fqOe+SquujeBWdzlYGBPohhjW9b2lGbRa72bwLdyml5d2auvaPyeTOzIw4MxzCkal8h8no3cqT3WJd0ExuFmOjXmlhRIXbnfKZQ7hfJ4HDTM8wVIMi6xJ01y3mV8E5glGlDRGIEKS75DrAtFn/0DA3x/b0ddZbPgGt23JnBW0agpKPzUGCvhoT4iv1HG9Zodtc6HGBTYnoXAXc3UR5SbBwK1d8y+8RUAzxNwU2orOwQeyolF/lLT7mUqQ8BqCj4Bt+j1lR0Cs3Sopt8GFLYNF/2JU7K2k6stePL7fwP/AER2xy+mY1/QAAAAAElFTkSuQmCC"
}`

in xcode i log `iconPath` in PluginMarker.m before and after this code:

`NSLog(@"iconPath = %@", iconPath);

        NSRange range = [iconPath rangeOfString:@"http"];
        if (range.location != 0) {

            range = [iconPath rangeOfString:@"://"];
            if (range.location == NSNotFound) {

                range = [iconPath rangeOfString:@"/"];
                if (range.location != 0) {
                  // Get the current URL, then calculate the relative path.
                  CDVViewController *cdvViewController = (CDVViewController*)self.viewController;

                  id webview = cdvViewController.webView;
                  NSString *clsName = [webview className];
                  NSURL *url;
                  if ([clsName isEqualToString:@"UIWebView"]) {
                    url = ((UIWebView *)cdvViewController.webView).request.URL;
                  } else {
                    url = [webview URL];
                  }
                  NSString *currentURL = url.absoluteString;
                  currentURL = [currentURL stringByDeletingLastPathComponent];

                  range = [currentURL rangeOfString:@"http"];
                  if (range.location != 0) {

                    currentURL = [currentURL stringByReplacingOccurrencesOfString:@"file:" withString:@""];
                    currentURL = [currentURL stringByReplacingOccurrencesOfString:@"//" withString:@"/"];
                    iconPath = [NSString stringWithFormat:@"file://%@/%@", currentURL, iconPath];
                  } else {
                    iconPath = [NSString stringWithFormat:@"%@/%@", currentURL, iconPath];
                  }
                } else {
                  iconPath = [NSString stringWithFormat:@"file://%@", iconPath];
                }
            }

        }
        
        NSLog(@"iconPath = %@", iconPath);`

i have before:

`iconPath = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iA…`
and after:

`iconPath = http:/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iA…`

**Comment by wf9a5m75** [comment]
Thank you for sharing your code.

By the way, pleas use triple back slashes to paste your code.

![screen shot 2017-07-18 at 3 16 45 pm](https://user-images.githubusercontent.com/167831/28342283-519ac85c-6bcc-11e7-9168-46df7847cb05.png)

![screen shot 2017-07-18 at 3 16 53 pm](https://user-images.githubusercontent.com/167831/28342284-51b954b6-6bcc-11e7-9438-8d954cf9619d.png)

**Comment by trin4ik** [comment]
for now we use hack:
```addMarker({
  position	: {lat: item.latitude, lng: item.longitude},
  icon		: "file://data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAACVUlEQVRIS8WWjVXCMBRGwwTqBMIEuAG4ARuIE6gTKBOgEyAT4AbABjKBMIE/C+h3m6S2pWlJ8BzfOTkpad6770teEzom3bZy/VbrpYTopDjJZ6w2c77X6p9j46SCUXvuYDxHq04BZ2rPHXa3y/DRqlPAmdqZW+hrkMZEq44F52q3oGTdrjEpqmPBudoxKVBVKqsU1THgPbW+klNUt4GHCn6idqEGuMveerUeXFGtNTCvah9qaz+n2gMmKMGBnLrfjPFcMirZ7231XUF19RUJkIhPZqXnT8AM9Osy62v0VPihUqIfjWwx1RkJvbxIpjArhabfbEJ6zQYwysiiT3CW8kJ6Q4BgqMALEnqVNAqQZGSkM/R7nMOBLhZ/B/ZQeg9V/1EsrpLy5dIqP8aAXV6WlQIlZrWq/wzeBK0DM3Y0vA0aAh8FPwTaBC7B2W8+qUOMT4l9dYUUrJK2k4tCOHl7O7zK+Xx69nbWU/iebgKz1+9E+OYPToR1fqOe+SquujeBWdzlYGBPohhjW9b2lGbRa72bwLdyml5d2auvaPyeTOzIw4MxzCkal8h8no3cqT3WJd0ExuFmOjXmlhRIXbnfKZQ7hfJ4HDTM8wVIMi6xJ01y3mV8E5glGlDRGIEKS75DrAtFn/0DA3x/b0ddZbPgGt23JnBW0agpKPzUGCvhoT4iv1HG9Zodtc6HGBTYnoXAXc3UR5SbBwK1d8y+8RUAzxNwU2orOwQeyolF/lLT7mUqQ8BqCj4Bt+j1lR0Cs3Sopt8GFLYNF/2JU7K2k6stePL7fwP/AER2xy+mY1/QAAAAAElFTkSuQmCC"
}```

**Comment by wf9a5m75** [comment]
@trin4ik I already fixed this bug in the commit someone (I committed a lot...)
But I confirmed the star image is displayed correctly without hack.
Please use the latest version `2.0.0-beta2-20170720-1821` or higher.
