### ISSUE TITLE
Problem with marker.getposition() in ionic 2

### ISSUE THREAD

**Issue by veder2431** [mapsplugin/cordova-plugin-googlemaps#1567]
I am unable to get the coordinates of the marker once i move it around the map:
I am using:  
`"@ionic-native/geolocation": "^4.0.0",
"@ionic-native/google-maps": "^4.0.0",`

i am using the next fuction to initialize the marker:
```js
 position: string = "";
  const GOOGLE:LatLng =  new LatLng(21.1213285,-86.9193511);
  loadMap() {
        
    let element: HTMLElement = document.getElementById("map");

    this.map = this.googleMaps.create(element);

    this.map.one(GoogleMapsEvent.MAP_READY).then(
      () => {
        this.presentToast("Mapa listo");

        let markerOptions: MarkerOptions = {
          position: GOOGLE,
          title: 'My position',
          snippet: "Soprendente",
          draggable: true
        };
        this.map.addMarker(markerOptions).then((maker: Marker) => {
          maker.showInfoWindow();
          maker.addEventListener(GoogleMapsEvent.MARKER_DRAG_END).subscribe((some: any) => {

            maker.getPosition().then((lt) => {
              this.position = lt.lat.toString() + " " + lt.lng.toString();

            }).catch(err => {
              this.presentToast("Error: " + err.toString());
            });

          }, (err) => {
            this.presentToast("Error: " + err.toString());
          });
        }).catch((err) => {
          this.presentToast("Error: " + err.toString());
        });

        this.map.animateCamera({
          target: GOOGLE,
          zoom: 16,
          duration: 4000
        });
      }
    ).catch((err) => {
      this.presentToast("error: " + err);
    });
  }

```

In my promises I don't get any errors, but I don't get the new position of the marker either

**Comment by wf9a5m75** [comment]
I'm not familiar with ionic, but I think

```
maker.getPosition().then((lt) => {
              this.position = lt.lat.toString() + " " + lt.lng.toString();
```

is wrong.

```js
let lt = maker.getPosition();
this.position = lt.lat.toString() + " " + lt.lng.toString();
```

**Comment by veder2431** [comment]
Unfortunately it did not help, I get this error: Property 'lat' does not existe on type 'Promise<LatLng>'

**Comment by wf9a5m75** [comment]
Um. The ionic wrapper is wrong.
https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/google-maps/index.ts#L1462-L1463

This plugin returns the position value as synchronize.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/520cd25188ec62f87f3eae1df5a3a0731221ba58/www/Marker.js#L132-L138

**Comment by veder2431** [comment]
Thanks for your help! I'm gonna check this issue in the ionic native git

**Comment by wf9a5m75** [comment]
I sent a pull request.

https://github.com/ionic-team/ionic-native/pull/1815

**Comment by veder2431** [comment]
I have question, with the pull request everything should work fine right?

**Comment by wf9a5m75** [comment]
I think so, but I'm not familiar with ionic. I haven't tested it.  Please test it, and please let me know if there are any problems.

**Comment by veder2431** [comment]
The problem continue, I don't getPosition() of marker.

**Comment by wf9a5m75** [comment]
Yes, pull request is not accepted yet.
https://github.com/ionic-team/ionic-native/pull/1815

**Comment by wf9a5m75** [comment]
I have been still waiting the ionic team merge the pull request for some reason.

**Comment by wf9a5m75** [comment]
The pull request has been accepted. Please reinstall the plugin.

**Comment by veder2431** [comment]
thanks very much, it works correctly.

**Comment by wf9a5m75** [comment]
Sounds good
