### ISSUE TITLE
Show div dynamically using MARKER_CLICK method

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1568]
plugin version: `2.0.0-beta2-20170717-1045`

Is it supposed to be possible to show/hide a div using the `MARKER_CLICK` method?
When clicking on a marker, I want to display a div but it is not working.

You can see the code below.
You can also check the repo: https://github.com/antoine92190/ionic-map

```
this.map.addMarker(options, (marker) => {

    marker.on(plugin.google.maps.event.MARKER_CLICK, () => {
        this.buttonVisible = !this.buttonVisible;
    })

})
```

```
<div #map id="map">

    <button ion-button *ngIf="buttonVisible">
        I'm a button
    </button>

</div>
```

**Comment by antoine92190** [comment]
Maybe it is linked to fd465ff.

If I click on the marker, the button is not displayed.
But if I click on the marker, change tab and go back to "Home", the button is displayed without any additional interaction.

**Comment by wf9a5m75** [comment]
I'm not familiar with ionic mechanism, but I think the ionic evaluates `*ngIf="buttonVisible"`  only at once when ionicView is displayed.

**Comment by wf9a5m75** [comment]
If I do that (without ionic), I do like this:

```js
var button = document.getElementById("button");

map.on("buttonVisible_changed", function(prevValue, newValue) {
  button.style.display = newValue === true ? "block" : "none";
});
map.set("buttonVisible", false);

map.addMarker({
  ...
}, function(marker) {
   marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
      map.set("buttonVisible", !map.get("buttonVisible"));
   });
});

```

**Comment by antoine92190** [comment]
I just tested, it also works on ionic. Thanks!
Actually, I encountered this issue when trying to reproduce another issue from my main project.
I think both issues are linked, so I'll try and see if your system fixes my other issue.

**Comment by wf9a5m75** [comment]
OK

**Comment by antoine92190** [comment]
Your system works to display the button, but I cannot click on the button.
=> When touching and moving inside the button, the map moves.

**Comment by wf9a5m75** [comment]
```js
map.on("buttonVisible_changed", function(prevValue, newValue) {
  button.style.display = newValue === true ? "block" : "none";
  cordova.fireDocumentEvent('plugin_touch', {});
});
```

**Comment by antoine92190** [comment]
This `plugin_touch` thing solved all my issues :ok_hand:

**Comment by wf9a5m75** [comment]
Good
