### ISSUE TITLE
Clear method and add marker used in sync raises Java exception

### ISSUE THREAD

**Issue by jayeshanandani** [mapsplugin/cordova-plugin-googlemaps#1569]
Before asking your question, problem or request, please read this page
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/articles/before_post_your_issue/README.md

(Optional) If you are Japanese, you can make an issue written in Japanese. Otherwise, in English, please.

- What is your question, problem or request?
Thanks for the great plugin. Below is snippet from my code.

```
this.map.one(GoogleMapsEvent.MAP_READY).then((googleMap) => {
      this.setCenter().then(() => {
        this.map.setCameraZoom(15);

        this.map.on(GoogleMapsEvent.CAMERA_MOVE_END).subscribe((data) => {
          this.map.clear();
          this.currentLatLong = data.target;
          this.getDrivers();

        });
      });
    });
```

In above code, I regenerate markers each time camera target is moved by destroying old ones using .clear() method and then regenerating it via add marker method.

The issue is that .clear() method doesn't have any promise and I have to keep minimum delay of 5seconds that is what I observed between clean and add markers to avoid the following error:

`W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference`

- What version of this plugin do you use? Please including minor version ($> cordova plugin list)
cordova-plugin-googlemaps 2.0.0-beta2-20170625-1805 "cordova-plugin-googlemaps"

- Screen capture or video record?
(you can upload your files with drag & drop)
I can create demo if needed but above code snippet should give a clear idea.

- Code, Data or Error log (please format your code or data)

Code pasted above.

**Comment by jayeshanandani** [comment]
I did saw the comments on at #1485 but they were not useful as how can BaseArrayClass solve that issue.

**Comment by wf9a5m75** [comment]
>cordova-plugin-googlemaps 2.0.0-beta2-20170625-1805

Since you use the old version, please try to reinstall the latest version at first.

Even if the issue occurs again, please share your project files on github or bitbucket.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/articles/before_post_your_issue/README.md#6-provide-your-code

**Comment by jayeshanandani** [comment]
I have upgraded the plugin version. I am testing it and I will get back in 12 hours on if it worked else I will share code.

**Comment by wf9a5m75** [comment]
The original code `map.clear()` accepts the callback.
(Actually, iOS has been accept it for quite some time now, but I forgot to return the result in Android).

If you want to use the callback, please reinstall the plugin `2.0.0-beta2-20170719-2226` or higher.

**Comment by jayeshanandani** [comment]
Thanks for the update. I will test it now with android.

**Comment by jayeshanandani** [comment]
I think the above change should be part of ionic google map plugin also where you have raised pull request as it doesn't accept callback.

**Comment by jayeshanandani** [comment]
Yeah it's already been done there. Thanks a lot :)

**Comment by wf9a5m75** [comment]
:)
