### ISSUE TITLE
getMapでオプション「camera: target」指定時に、一瞬アフリカ大陸が表示される

### ISSUE THREAD

**Issue by yesman99** [mapsplugin/cordova-plugin-googlemaps#1570]
Katsumataさん、質問させてください。

- What is your question, problem or request?
getMapでオプション「camera: target」指定時に、一瞬アフリカ大陸が表示された後に、指定場所が表示されます。
これを最初からtargetで指定した場所を表示する方法はありますでしょうか？
もしくは初期表示位置（アフリカ大陸）の変更はできますでしょうか？

また合わせて質問失礼いたします。
controls: myLocationButtonで現在位置表示（青丸）と現在地へ移動ボタンの表示・非表示が可能ですが、現在位置表示（青丸）のみを表示にすることはできますでしょうか？

以上、よろしくお願いいたします。

- What version of this plugin do you use? Please including miner version ($> cordova plugin list)
v2.0.0
https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps

- Screen capture or video record?
![capture1](https://user-images.githubusercontent.com/6134076/28356832-625f1872-6ca4-11e7-8592-e6e5b8ebaf73.gif)

- Code, Data or Error log (please format your code or data)
```
      var map = plugin.google.maps.Map.getMap(div, {
        'camera' : {
          'target': {
            lat: 35.170915,
            lng: 136.881537,
          },
          'zoom': zoom,
        },
        'controls': {
          'myLocationButton': false
        },
     });
```

**Comment by wf9a5m75** [comment]
camera オプションで一瞬アフリカ大陸が表示されるのはバグではなく、ある意味、仕様に近いです。
単純に内部でmoveCameraを実行しているだけで、native apiそのものにはカメラの初期位置を指定する方法がないです。

あとで工夫してみます

プラグインでは現在位置とボタンは連動しているため、どちらかだけを非表示にすることはできません。

**Comment by wf9a5m75** [comment]
あと

>What version of this plugin do you use? Please including miner version ($> cordova plugin list)

の質問なのですが、v2.0はここ最近、１日数回アップデートしています。
小さなバグ修正とパフォーマンスの向上が目的なので、いま使用していただいている古いバージョンを使用していても影響はないです。
ただこちらとしては、どのマイナーバージョンを使っているのかというのが重要なので、次回に質問していただくときにはそれを教えていただけると助かります。

```
$ cordova plugin list
cordova-plugin-googlemaps 2.0.0-beta2-20170711-2345 "cordova-plugin-googlemaps"
                                      ^^^^^^^^^^^^^
```

**Comment by wf9a5m75** [comment]
アフリカ大陸が表示される件ですが、こんな感じでどうでしょう。カメラの調整が終わるまで非表示にしています。
"Loading..."とかは開発者側で作ってください。

![1570](https://user-images.githubusercontent.com/167831/28398045-23e11364-6cba-11e7-9020-e67ad2628576.gif)

**Comment by yesman99** [comment]
Katsumataさん、初期位置表示の件確認できました。
工夫いただいたと言うことでありがとうございました。感謝いたします。

現在地ボタンの非表示は不可、またマイナーバージョンの件についても承知致しました。

この件クローズとさせていただきます。
ありがとうございました。
