### ISSUE TITLE
Error using newLatLngBounds(LatLngBounds, int): View size is too small after padding is applied.

### ISSUE THREAD

**Issue by carvemerson** [mapsplugin/cordova-plugin-googlemaps#1572]
In some cases (not all) when I set use `map.moveCamera()` to a list of `LatLng`, I get this error: 
```
Error using newLatLngBounds(LatLngBounds, int): View size is too small after padding is applied.
```
and camera do not show all poits.
The code is similar to:

```
let path: LatLng[] = [];

path.push(new LatLng(x, y));
path.push(new LatLng(x, y));
path.push(new LatLng(x, y));
path.push(new LatLng(x, y));
path.push(new LatLng(x, y));
path.push(new LatLng(x, y));
path.push(new LatLng(x, y));

let cameraPosition: CameraPosition = {
      target: path
 }

map.moveCamera(cameraPosition);

```
where x and y can be any point.
How can I avoid this erro?

**Comment by wf9a5m75** [comment]
The map div is too small.

**Comment by carvemerson** [comment]
When I set a new div to the map, Do I need wait some event to use the map?

**Comment by wf9a5m75** [comment]
Could you show me the code?

**Comment by carvemerson** [comment]
Yes:

```
 ionViewWillEnter() {
    map.setDiv(this.mapElement.nativeElement);
    this.initMap();
  }

  ionViewWillLeave() {
    map.clear();
    map.setDiv(null);
  }

  public initMap() {

        ...

        let path: Array<LatLng> = new Array<LatLng>();

        for (let event of this.wrapperEvent.track) {
          path.push(new LatLng(event.latitude, event.longitude));
        }

        let cameraPosition: CameraPosition = {
          target: path
        }

        this.mapService.map.moveCamera(cameraPosition).then(() => {

          let polylineOptions: PolylineOptions = {
            points: path,
            color: lineColor,
            width: 4
          }

          this.mapService.map.addPolyline(polylineOptions);
          
          ...
      });
  }
```

**Comment by wf9a5m75** [comment]
Could you share your project files on github or bitbucket?

**Comment by carvemerson** [comment]
Sorry, the project is private, I can't share it....

**Comment by wf9a5m75** [comment]
Tentatively, insert `setTimeout()` for `this.initMap();`

```js
setTimeout(function() {
  this.initMap();
}, 1000);
```

----

> Sorry, the project is private, I can't share it....

You can use bitbucket. Bitbucket allows you to create private repository as free.

**Comment by carvemerson** [comment]
The

```
setTimeout(function() {
  this.initMap();
}, 1000);
```

works!!

But, if I need wait some time to manipulate that, the map.setDiv() should not be a promise?

**Comment by wf9a5m75** [comment]
I checked the android code, the code probably work with `200ms` (or `100ms`) .

>But, if I need wait some time to manipulate that, the map.setDiv() should not be a promise?

Um, it's too difficult for this method.

**Comment by carvemerson** [comment]
I understand.
I will use 200ms.

Thanks so much for the help.
