### ISSUE TITLE
Native: tried calling GoogleMaps.isAvailable, but the GoogleMaps plugin is not installed

### ISSUE THREAD

**Issue by saintsatplay2015** [mapsplugin/cordova-plugin-googlemaps#1574]
Am trying to use the cordova-plugin-googlemaps plugin via Ionic Native.

I have created iOS and Android Google Map keys via the Google console API and these are both enabled.

I have installed the plugin with the following command:

```ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="ANDROID_KEY_HERE" --variable API_KEY_FOR_IOS="IOS-KEY_HERE"```

And the associated Ionic Native package with the following:

```npm install --save @ionic-native/google-maps```

The application's **package.json** file has the following installed in the **dependencies** section:

```
"dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/geolocation": "^4.0.1",
        "@ionic-native/google-maps": "^4.0.1",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic/storage": "2.0.1",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-geolocation": "^2.4.3",
        "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
        "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.5.3",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    }
```

As you can see there are 2 cordova references to the GoogleMaps plugin and 1 Ionic Native reference.

In the **cordova** section of the **package.json** file the following configuration is present:

```
   "cordova": {
        "plugins": {
            "cordova-plugin-geolocation": {},
            "cordova-plugin-googlemaps": {
                "API_KEY_FOR_ANDROID": "ANDROID_KEY_HERE",
                "API_KEY_FOR_IOS": "API_KEY_HERE"
            },
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {}
        },
        "platforms": [
            "ios"
        ]
    }
```

When I run ionic cordova plugin ls I get the following output:

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta2-20170719-2226 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

The GoogleMaps plugin is clearly installed/configured and the Ionic's project root module is configured with the plugin import like so:

```
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';
import { Geolocation } from '@ionic-native/geolocation';
import { GoogleMaps } from '@ionic-native/google-maps';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';

@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    Geolocation,
    GoogleMaps,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}
```

In my src/pages/home/home.ts file the GoogleMaps node package is imported like so:

```
import { GoogleMaps,
         GoogleMap,
         GoogleMapsEvent,
         LatLng,
         CameraPosition,
         MarkerOptions,
         Marker } from '@ionic-native/google-maps';
```

In the class the GoogleMap plugin is initiated like so:

```
constructor(public navCtrl    : NavController,
               private toastCtrl : ToastController,
               private _PLAT     : Platform,
               private _GEO      : Geolocation,
               private _MAPS     : GoogleMaps) 
   {
      this._PLAT.ready()
      .then((data) =>
      {
         
         this._MAPS.isAvailable()
         .then((isAvailable: boolean)=>
         {
            if(!isAvailable)
            {
              console.log('GoogleMap plugin is NOT available');
            }
            else
            {
              console.log('GoogleMap plugin is available');
            }
         });
    });
}
```

However when I build this through the Ionic CLI and then run this via Xcode I get the following error log:

```
WARN: Native: tried calling GoogleMaps.isAvailable, but the GoogleMaps plugin is not installed.
WARN: Install the GoogleMaps plugin: 'ionic cordova plugin add cordova-plugin-googlemaps'
```

Has anyone got any idea what is going on here as, from what I can tell (the documentation is a little spotty though), my code should work without any issue (it did on previous versions of the plugin) yet, no matter what I do, the plugin just doesn't seem to work.

The application doesn't even seem to recognise the plugin as being installed despite that being the case!!!

Is this a bug in the beta version of the plugin?

Is any other developer out there experiencing the same issue? If so, please give me a heads up on what potential fixes exist as this one's driving me crazy!

**Comment by wf9a5m75** [comment]
There is no more `isAvailable()` method in the GoogleMaps class.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/README.md

And the v2.0 executes it internally. So you don't need to try to execute it. 

I sent a pull request, but still waiting....
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1574

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/450ca710b62c60811610af95141eee096c3faa2c/www/googlemaps-cdv-plugin.js#L471-L480

**Comment by saintsatplay2015** [comment]
Hmm, that's odd.

When I look at the **Ionic Native index.d.ts** file (which I am correct in thinking that is independent of this repository and the developers who maintain the project?) features the following:

```
export declare class GoogleMaps extends IonicNativePlugin {
   
    /**
     * Checks if a map object has been created and is available.
     *
     * @returns {Promise<boolean>}
     */
    isAvailable(): Promise<boolean>;
```

So is this obsolete based on what you've stated with the pull request?

Thanks for the speedy reply by the way!

**Comment by saintsatplay2015** [comment]
Would what you've stated explain the reason for the plugin not installed message though?

```
WARN: Native: tried calling GoogleMaps.isAvailable, but the GoogleMaps plugin is not installed.
WARN: Install the GoogleMaps plugin: 'ionic cordova plugin add cordova-plugin-googlemaps'
```

This is what's maddening to me as the plugin clearly is installed so I'd love to know what's going on with that message.

**Comment by wf9a5m75** [comment]
The current ionic wrapper plugin code is too old.

**Comment by wf9a5m75** [comment]
The ionic googlemaps plugin is a wrapper plugin of this plugin.
Unfortunately, I'm not familiar with ionic at all (recently getting better).

The wrapper plugin code is written based on the v1.4, but it's not perfect.
That's why I modified the wrapper plugin code, and sent a pull request.
But it is still waiting for accepting.

**Comment by wf9a5m75** [comment]
The pull request has been accepted.
So please reinstall the ionic plugin. The issue should be gone.

**Comment by saintsatplay2015** [comment]
@wf9a5m75 Thanks so much for your time and help on this matter. Trust me when I say that they are very much appreciated, particularly now that everything is working!

Thanks as well for all the work you've put into developing this great little plugin.

**Comment by wiggitamoo** [comment]
I am experiencing this problem after pulling the latest code with 

`npm install @ionic-native/google-maps --save`

and 

`ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"`

replacing the API keys accordingly. 

When trying to call GoogleMap.isAvailable() I see the following error: `Property 'isAvailable' does not exist on type 'typeof GoogleMap'`

Additionally, **GoogleMapsLatLng** cannot be found.

Below is my ionic info:
global packages:

    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-utils        : 1.5.0
    Cordova CLI             : 7.0.1 
    Ionic CLI               : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.0.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 5.0.0

**Comment by wf9a5m75** [comment]
There is no isAvailable() method for public. The method is executed in internal. You don't need to worry about that.

The official doc is old.

And there is no GoogleMapsLatLng class.


Please (x3) read documents before asking.
https://ionic-site-staging.herokuapp.com/docs/native/google-maps/

**Comment by wiggitamoo** [comment]
Thanks! FYI, the super starter app probably needs to be updated as it references both of those methods in the map.ts file.
