### ISSUE TITLE
Reverting to specific version of google cordova maps

### ISSUE THREAD

**Issue by jayeshanandani** [mapsplugin/cordova-plugin-googlemaps#1575]
Before asking your question, problem or request , please read this page
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/articles/before_post_your_issue/README.md

(Optional) If you are Japanese, you can make an issue written in Japanese. Otherwise, in English please.

- What is your question, problem or request?
How can we revert to earlier version 2 commit? I have noticed app is hanging and ionic is not working with latest plugin. I wanted to make sure that is the root cause hence wanted to revert back the version.

- What version of this plugin do you use? Please including miner version ($> cordova plugin list)
The one released 5-10 mins back :)

- Screen capture or video record?
(you can upload your files with drag & drop)

- Code, Data or Error log (please format your code or data)

```js
(here)
```

**Comment by jayeshanandani** [comment]
I am using multiple_branch of version 2 beta plugin.

**Comment by wf9a5m75** [comment]
Sorry, the wrong code was mixed in to the `2.0.0-beta2-20170720-1741`.
I fixed the pluginMarker.m so you can use it.

The ionic wrapper code will be released tonight. 
https://github.com/ionic-team/ionic-native/pull/1815#issuecomment-316874855

If you want to revert the plugin code, you can install from git commit id.

Find the version you want to use, from the commit history.
https://github.com/mapsplugin/cordova-plugin-googlemaps/commits/multiple_maps

Then install it.

For example, `2.0.0-beta2-20170720-1431` is 
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/16502e15159fa506d37c9c426a54f4bd977e9873

```
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#16502e15159fa506d37c9c426a54f4bd977e9873
```

**Comment by jayeshanandani** [comment]
There seems to be some issue with the latest plugin. I will try again with the ionic latest release but if I revert to somewhere version around 2.0.0-beta2-20170717-xxx it works.

If I switch to latest version app becomes unresponsive to clicks and ionic stops working

**Comment by wf9a5m75** [comment]
I fixed the click issue yesterday. The plugin should comply the DOM hierarchy completely.
So please double check the DOM hierarchy of your app.

If the hierarchy is correct, please share your project (full) files on github or bitbucket.
I will try to reproduce your issue, and fix it.
(As I said before, you can create a free private repository at BitBucket)

Even though if you can not share the files, please create a project that reproduce the issue 100%.

**Comment by jayeshanandani** [comment]
I can share the private repository with you. Please let me know on which I need to provide access.

**Comment by wf9a5m75** [comment]
Please create a private repo at BitBucket (https://bitbucket.org/).
Github is not free.

Then please invite me to the repository, and let me know the repository name.

**Comment by jayeshanandani** [comment]
I already have my repo at bitbucket. shall I send invite on username: wf9a5m75?

**Comment by wf9a5m75** [comment]
yep

**Comment by wf9a5m75** [comment]
Let me just confirm. Did you send me the invitation? Or will you send it tomorrow?

**Comment by jayeshanandani** [comment]
I am just confirming this on both versions again as you said about HTML part. Once done I will share the repo so you can cross check tomorrow. Apologies for not informing earlier.

**Comment by jayeshanandani** [comment]
I am closing this in favor of latest ionic google maps and latest Cordova google maps version 2 as things seems they are working fine.
