### ISSUE TITLE
 iOS build failing, throws error (v2 beta multiple maps)

### ISSUE THREAD

**Issue by skyserpent** [mapsplugin/cordova-plugin-googlemaps#1576]
Before asking your question, problem or request , please read this page
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/articles/before_post_your_issue/README.md

(Optional) If you are Japanese, you can make an issue written in Japanese. Otherwise, in English please.

- What is your question, problem or request?
[repo demonstrating bug](https://github.com/skyserpent/ionic-maps-bug
)

Created a blank Ionic project via CLI, added [Maps v2 beta plugin via docs guide]( http://ionicframework.com/docs/native/google-maps), tried to run on iOS, build fails.
Above is the link to the repo of my codebase. Simply run 

```sh
yarn install     ## or npm install
ionic cordova run ios --simulator
```

and you will notice the build failing. It mentions something about propertyId being an undefined variable. 

- What version of this plugin do you use? Please including miner version ($> cordova plugin list)
Latest

- Screen capture or video record?
(you can upload your files with drag & drop)
file: PluginMarker.m
<img width="876" alt="screen shot 2017-07-20 at 10 12 34 pm" src="https://user-images.githubusercontent.com/2764735/28449898-9a7f22e8-6d98-11e7-909d-3e0caf2baf55.png">

- Code, Data or Error log (please format your code or data)
https://github.com/skyserpent/ionic-maps-bug

```js
(here)
```

**Comment by wf9a5m75** [comment]
Oh, sorry. I fixed it. Please reinstall and try again.

**Comment by skyserpent** [comment]
Thanks going to try this again. Is there a test process like testing iOS and Android builds before releasing the package into the wild? Just curious. Appreciate your work.

**Comment by wf9a5m75** [comment]
Sorry, I will take care.
