### ISSUE TITLE
Error installing the plugin  in the `multiple-maps` branch

### ISSUE THREAD

**Issue by AmitMY** [mapsplugin/cordova-plugin-googlemaps#1579]
**What is your question, problem or request?**

Running:
```
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="SOMETHING" --variable API_KEY_FOR_IOS="SOMETHING" --save
```

Results in an error:

> Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Failed to get absolute path to installed module

**What version of this plugin do you use?**
I am not yet using the plugin.

`npm --v` = 5.3.0

This is different error than https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1578

**Comment by wf9a5m75** [comment]
cordova also uses npm command. it's the same as #1578

**Comment by wf9a5m75** [comment]
And probably your node.js version is old.

**Comment by AmitMY** [comment]
@wf9a5m75 Thanks for the replies.
I think it is different than that issue, as I get a similar, but not the same error.
`npm --v` = 5.3.0
`node -v` v8.1.2
![image](https://user-images.githubusercontent.com/5757359/28491935-12926f3c-6f02-11e7-9c27-9ce75333c000.png)

**Comment by wf9a5m75** [comment]
Um, I wonder.

Could you show me the all error messages?

**Comment by wf9a5m75** [comment]
And try to install with `--no-fetch` and `--verbose` options.

**Comment by AmitMY** [comment]
This is the entire message..
With `--no-fetch` and `--verbose`
![image](https://user-images.githubusercontent.com/5757359/28491979-e68b8d8c-6f02-11e7-96a0-b4671e58f9fa.png)

**Comment by wf9a5m75** [comment]
Um, what cordova version do you use?

**Comment by AmitMY** [comment]
`7.0.1`

**Comment by wf9a5m75** [comment]
ping github.com

**Comment by AmitMY** [comment]
> Pinging github.com [192.30.253.112] with 32 bytes of data:
> Reply from 192.30.253.112: bytes=32 time=144ms TTL=53
> Reply from 192.30.253.112: bytes=32 time=143ms TTL=53
> Reply from 192.30.253.112: bytes=32 time=143ms TTL=53
> Reply from 192.30.253.112: bytes=32 time=144ms TTL=53
> 
> Ping statistics for 192.30.253.112:
>     Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
> Approximate round trip times in milli-seconds:
>     Minimum = 143ms, Maximum = 144ms, Average = 143ms

**Comment by AmitMY** [comment]
From [stackoverflow](https://stackoverflow.com/questions/43856285/failed-to-get-absolute-path-to-installed-module):

> I had the same problem right now. I fixed it by downgrading cordova from v7.0.0 to v6.5.0
> 
> sudo npm i -g cordova@6.5.0
> 
> They changed the way how they fetch the plugins. https://cordova.apache.org/news/2017/05/04/cordova-7.html
>

**Comment by wf9a5m75** [comment]
Try it.

**Comment by AmitMY** [comment]
Works. so I guess it is a cordova 7+ error.
I'll leave it open just so people with 7+ will have a reference until there is a different way?

**Comment by AmitMY** [comment]
Also, thanks a lot for the responsiveness! Beer is on me!

**Comment by wf9a5m75** [comment]
> I'll leave it open just so people with 7+ will have a reference until there is a different way?

I don't prefer open issues which are already solved.
I will refer this issue if someone ask this error again.

>Also, thanks a lot for the responsiveness! Beer is on me!

Thanks

**Comment by FingersCrossed** [comment]
Our team was experiencing a similar issue yesterday.  Attempting to down date Cordova to 6.5 did not help, but after running "ionic cordova prepare", we were able to find that the config.xml did not contain API_KEY_FOR_IOS.  When the first dev attempted to install the plugin, this variable was omitted.  After adding the API_KEY_FOR_IOS to config.xml prepare succeeded.

Error we were seeing while attempting to add the plugin:
```
Error: Failed to fetch plugin git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git via git.
Either there is a connection problems, or plugin spec is incorrect:
        Error: C:\Git\cmd\git.exe: Command failed with exit code 128 Error output:
Cloning into 'C:\Users\usr\AppData\Local\Temp\git\1505168556288'...
fatal: Unable to find remote helper for 'git+https'
```

Correct looking config.xml:
```
<plugin name="cordova-plugin-googlemaps" spec="git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps">
    <variable name="API_KEY_FOR_ANDROID" value="{apikey}" />
    <variable name="API_KEY_FOR_IOS" value="{apikey}" />
</plugin>
```

**Comment by arafa75** [comment]
- same issue here with cordova 7.0.1.
- if i downgrade to cordova 6.5.0 i get same error as **FingersCrossed** :
Error: Failed to fetch plugin git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git via git.
Either there is a connection problems, or plugin spec is incorrect:
        Error: C:\Git\cmd\git.exe: Command failed with exit code 128 Error output:
Cloning into 'C:\Users\usr\AppData\Local\Temp\git\1505168556xxx'...
fatal: Unable to find remote helper for 'git+https'
- i re-updated my cordova to 7.0.1 and then i have these 4 situations : 
 1) command : ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps .........................     FAILED with error unable to fetch
 2) command cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps.........................      SUCCEDED (notice i omit ionic in command) but command ionic cordova build android result in error << cannot find symbol groundOverlay.setTag(nul)
 3) i took this repo clone (i forget from where) https://github.com/Motoralfa/cordova-plugin-googlemaps.git#multiple_maps and run  command <<ionic cordova plugin add https://github.com/Motoralfa/cordova-plugin-googlemaps.git#multiple_maps>>   FAILED as with **FingersCrossed**

command : ionic cordova plugin add https://github.com/Motoralfa/cordova-plugin-googlemaps.git#multiple_maps      SUCCEDED

command ionic build android   SUCCEDED

**Comment by rodikh** [comment]
@wf9a5m75 @AmitMY  The no-fetch flag is actually `--nofetch`.

I've had issues installing cordova plugins using full github urls since cordova updated to 7.0.0, where it apparently uses npm to install the plugins.

`--nofetch` forces cordova to revert to the old way of installing plugins.
