### ISSUE TITLE
iOS button is not clickable on map

### ISSUE THREAD

**Issue by mba858** [mapsplugin/cordova-plugin-googlemaps#1580]
I'm facing this issue in version 1.4.0, I just added HTML div in map element and then attached the click listener in map ready function, but it's not clicking even though that area isn't draggable for map. But from console I got element and then trigger the click event, it works then.
So I'm not sure why this problem is coming. Here's my code:

<div id="cardMap" #map class="mapsDivs" [class.loaded]="mapBgHide">
    <div id="toggle_map_cardlist_view_id" class="cardlist_toggle"><span></span>Card View
    </div>
</div>

        that.elementMap = new GoogleMap("cardMap", mapOptions);
        that.elementMap.one(GoogleMapsEvent.MAP_READY).then((res) => {
          that.elementMap.setClickable(false);
          if (that.elementMap.loaded) {
            that.elementMap.clear();
          };
          var element__ = document.getElementById('toggle_map_cardlist_view_id');
          element__.addEventListener("click", function () {
            that.events.publish("show_cards_list", {});
            if (!window['mapLoaded'])
              window['mapLoaded'].setClickable(false);
          });
        })

**Comment by wf9a5m75** [comment]
Please use the v2.0.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0

The v1.4 will be shutdown soon.

And the ionic native wrapper plugin works with the v2.0 currently.

**Comment by wf9a5m75** [comment]
https://ionic-site-staging.herokuapp.com/docs/native/google-maps/

**Comment by mba858** [comment]
Thanks for quick reply, I changed the version, but still button inside map is not clicking up. Further issue is I'm unable to add custom marker icons, only default red icon is coming up. Can you please guide me to right direction for both these issue.

**Comment by wf9a5m75** [comment]
I think you are something wrong.
Please share your project files on github or bitbacket.

**Comment by mba858** [comment]
Project is too big to upload, should I upload or place the html && ts file somewhere?

**Comment by wf9a5m75** [comment]
Please prepare the files that are able to build your app.
If I can not build your app, I can not help.
I don't need platforms, plugins, www, and node_modules directlies.
But must include the src, resources.
I know how to build regular ionic app.

**Comment by wf9a5m75** [comment]
ping

**Comment by mba858** [comment]
Sorry for late reply, you were right I was making mistake. It was issue of z-index.
Thanks for your quick response.

**Comment by mino922** [comment]
I am having a similar issue. I have form elements and other buttons on the map, but I am unable to click on them. What did you need to set your z-index too?

**Comment by mba858** [comment]
@mino922 please confirm if your form and buttons are inside the map element. And which version of this plugin you'r using 1.4 or 2+?

**Comment by mino922** [comment]
I am running 2+. Adding the elements inside of the map element made them clickable. However, it appears that if I click on the button or form element the first time it works, then if I return to that view and click on the button again it does not work. But if I click a third time it does work. Any idea what could be causing that?

**Comment by wf9a5m75** [comment]
Execute `cordova.fireDocumentEvent('plugin_touch', {});` when you return to the view.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/whats-new-v2/README.md#change-4-save-battery-life
