### ISSUE TITLE
Ionic: Google Maps and Admob free

### ISSUE THREAD

**Issue by jaylecorse** [mapsplugin/cordova-plugin-googlemaps#1581]
**I'm submitting a [ x] any problem or bug report

**plugin version:**  (check one with "x")
[x ] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-admob-sdk 0.7.0 "AdMob SDK"
cordova-plugin-admob-free 0.9.0 "Cordova AdMob Plugin"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.0.0-beta2-20170721-1617 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
ionic-plugin-keyboard 2.2.1 "Keyboard"

 

**Current behavior:**

Hello, your plugin is very fantastic, it's a great job, thank you very much.

I finalize my Ionic project, with plugin googlemaps,  and I want insert Ad banner in all the page.

Without the plugin Ad mob, the google map display very good.

But when I insert the Ad banner, the screen of the page where is the map, is black.

An example of code 

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 3.10.10 

**Expected behavior:**

Without Admob, the map display very well

**Steps to reproduce:**

1) create ionic project
2) install Google maps native:
https://ionicframework.com/docs/native/google-maps/
3) install Admob free: https://ionicframework.com/docs/native/admob-free/
4) ionic cordova run android   , on a LG device,  Android  version 5.0.1

Project bug example: 
https://github.com/jaylecorse/ionic-googlemap-admob.git

**Screen capture or video record:**

![screenshot_2017-07-23-13-54-56](https://user-images.githubusercontent.com/25280716/28499398-25f088f8-6fb5-11e7-8ec0-6c3348c0e74c.png)

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
Great preparation. I will check it later.

**Comment by wf9a5m75** [comment]
Thank you for preparing an example app. I built your project and inspected it, but I could not figure out what is wrong.
It seems the Admob plugin (or internal Google Ad system itself) inserts a view, and set the background.

I guess this might help you. Try it.
https://stackoverflow.com/a/20831589/697856

**Comment by wf9a5m75** [comment]
I noticed one thing you are code is wrong at here.

You must wait the `MAP_READY` event at the first time.

```ts
 map.one(GoogleMapsEvent.MAP_READY).then(
   () => {
     console.log('Map is ready!');
     // Now you can add elements to the map like the marker
   }
 );

 // create LatLng object
 let ionic: LatLng = new LatLng(43.0741904,-89.3809802);

 // create CameraPosition
 let position: CameraPosition = {
   target: ionic,
   zoom: 18,
   tilt: 30
 };

 // move the map's camera to position
 map.moveCamera(position);

 // create new marker
 let markerOptions: MarkerOptions = {
   position: ionic,
   title: 'Ma position'
 };

  
 map.addMarker(markerOptions)
   .then((marker: Marker) => {
      marker.showInfoWindow();
    });
 }
```

The code has to be like this:

```ts
 map.one(GoogleMapsEvent.MAP_READY).then(
   () => {
     console.log('Map is ready!');
     // Now you can add elements to the map like the marker


     // create LatLng object
     let ionic: LatLng = new LatLng(43.0741904,-89.3809802);

     // create CameraPosition
     let position: CameraPosition = {
       target: ionic,
       zoom: 18,
       tilt: 30
     };

     // move the map's camera to position
     map.moveCamera(position);

     // create new marker
     let markerOptions: MarkerOptions = {
       position: ionic,
       title: 'Ma position'
     };


     map.addMarker(markerOptions)
       .then((marker: Marker) => {
          marker.showInfoWindow();
        });


   }
 );
```

**Comment by wf9a5m75** [comment]
Okay, I finally figured out the problem. 
This is completely the AdMob plugin's problem.

The wrong point is here.

```java
ViewGroup wvParentView = (ViewGroup) getWebView().getParent();
if (parentView == null) {
    parentView = new LinearLayout(webView.getContext());
}
if (wvParentView != null && wvParentView != parentView) {
    wvParentView.removeView(getWebView());
    ((LinearLayout) parentView).setOrientation(LinearLayout.VERTICAL);
    parentView.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT, 0.0F));
    getWebView().setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT, 1.0F));
    parentView.addView(getWebView());
    cordova.getActivity().setContentView(parentView);   <----- here is problem
}
```
https://github.com/ratson/cordova-plugin-admob-free/blob/f8357d40aded044a2e477e8a165b6a3ac2617e78/src/android/banner/BannerExecutor.java#L213

The webview redraws the background when the setContentView() method executes.

In order to prevent redraw the background, get the parentView of webView, and re-instart a new view.

```java
ViewGroup rootView = (ViewGroup)(getWebView().getParent());
wvParentView.removeView(getWebView());
((LinearLayout) parentView).setOrientation(LinearLayout.VERTICAL);
parentView.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT, 0.0F));
getWebView().setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT, 1.0F));
parentView.addView(getWebView());
rootView.addView(parentView);
```

**Comment by wf9a5m75** [comment]
![device-2017-07-23-152818](https://user-images.githubusercontent.com/167831/28503439-ac4334d6-6fbb-11e7-881e-4eed6ea3c42f.png)

**Comment by wf9a5m75** [comment]
I sent a pull request to fix this issue. If it is accepted, you need to reinstall the admob plugin.
https://github.com/ratson/cordova-plugin-admob-free/pull/95


By the way, since I spent lots of hours for you, I appreciate you donate some amount for this project.
(I decided to ask this everyone from now)

**Comment by jaylecorse** [comment]
Wonderful Job: It's work very well : I modified the code in 

platforms/android/src/name/ratson/cordova/admob/banner/BannerExecutor.java

and in
/plugins/cordova-plugin-admob-free/src/android/banner/BannerExecutor.java

Is it good?  (I'm not a great developer but I like Ionic ;-) . )


Thanks you so much.
How do I donate some amount? 

Do you have a paypal account?

Have a nice day (I'm going to sleep)

**Comment by wf9a5m75** [comment]
>platforms/android/src/name/ratson/cordova/admob/banner/BannerExecutor.java
>
> and in
> /plugins/cordova-plugin-admob-free/src/android/banner/BannerExecutor.java
>
>Is it good? (I'm not a great developer but I like Ionic ;-) . )

Yes.

And thank you for supporting the plugin project. I really appreciate.
You can donate from here (Donate|Paypal button)
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc#buy-me-a-beer

By the way, I haven't checked iOS code. If you face the same problem, please let me know.

**Comment by wf9a5m75** [comment]
Thank you for your donation, and using this plugin :)

**Comment by fmendoza** [comment]
Thanks for the solution @wf9a5m75 

It works great.
