### ISSUE TITLE
Google Play Services Error

### ISSUE THREAD

**Issue by Revo86** [mapsplugin/cordova-plugin-googlemaps#1582]
I installed your plugin 1.43 in Visual Studio (Visual Studio tools for Apache Cordova) and I'm getting this error:
Could not find any matches for com.google.android.gms:play-services-maps:11.+ as no versions of com.google.android.gms:play-services-maps are available.

How could I fix this?

**Comment by wf9a5m75** [comment]
Please use the v2.0. The v.1.4.3 will be shutdown soon.

**Comment by Revo86** [comment]
okay, where can I download the zip file? I can only find the documentation

**Comment by Revo86** [comment]
Okay just did, buth the error is staying the same.

**Comment by wf9a5m75** [comment]
Could you show me the error log?

**Comment by Revo86** [comment]
1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.

1>MSBUILD : cordova-build error : * What went wrong:
1>MSBUILD : cordova-build error : A problem occurred configuring root project 'android'.
1>MSBUILD : cordova-build error : > Could not resolve all dependencies for configuration ':_debugCompile'.
1>MSBUILD : cordova-build error :  > Could not find any matches for com.google.android.gms:play-services-maps:+ as no versions of com.google.android.gms:play-services-maps are available.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-maps/maven-metadata.xml
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-maps/
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-maps/maven-metadata.xml
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-maps/
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/maven-metadata.xml
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified
1>MSBUILD : cordova-build error :  > Could not find any matches for com.google.android.gms:play-services-location:+ as no versions of com.google.android.gms:play-services-location are available.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/maven-metadata.xml
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-location/
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-location/maven-metadata.xml
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-location/
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified

**Comment by wf9a5m75** [comment]
Do you use the Android emulator with Google APIs?
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md#1-do-you-use-android-emulator

**Comment by Revo86** [comment]
I've connected an Android 4.x tablet via to my PC and in Visual Studio I've selected "Device". Can't get an Adroid Emulator running.

Weirdly enough, when I select "Emulate in Browser" no error is thrown. But how do I get in working on my "real" Android devices?

**Comment by wf9a5m75** [comment]
I guess you don't install the `Google Play services` and the `Google Repository` in your pc.
https://stackoverflow.com/a/34812919/697856

**Comment by wf9a5m75** [comment]
Unfortunately, I'm not Windows user.

Please find answers by Google.
https://www.google.com/search?q=google+play+services+install+from+command+line+window&rlz=1C5CHFA_enUS717US717&oq=google+play+services+install+from+command+line+window&aqs=chrome..69i57j69i64l3.11767j0j7&sourceid=chrome&ie=UTF-8#tbs=qdr:y&q=google+play+services+install+visual+studio

**Comment by Revo86** [comment]
no more errors, thank you! :)
