### ISSUE TITLE
Plugin disables usage of DateTime picker on iOS

### ISSUE THREAD

**Issue by missCorduroy** [mapsplugin/cordova-plugin-googlemaps#1584]
**I'm submitting a ...**  (check one with "x")
[ X] any problem or bug report

**plugin version:**  (check one with "x")
[ X] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-googlemaps 2.0.0-beta2-20170721-1617 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.3 "Cordova WKWebView Engine"
```

**Current behavior:**

Individually, both plugins seem to work fine. But when I use both on the same project, the date picker is not clickable. It will appear on the screen, but clicking on it does nothing.

Debugging through xCode shows that the event doesn't even get called, like there is some kind of layer above the date picker that disables clicking. No errors are shown both in xCode and JS console.

Any ideas on what might be causing this?

The date picker that I'm using is: 
https://github.com/VitaliiBlagodir/cordova-plugin-datepicker

![screen shot 2017-07-24 at 15 39 19](https://user-images.githubusercontent.com/11718119/28526016-7332e3a0-7086-11e7-9848-0d542314b049.png)

**Expected behavior:**
I would expect that these plugins can be used individually within a single project.

**Steps to reproduce:**
In order to reproduce this issue, I've copied the demo project and just added the DatePicker plugin.  
https://github.com/missCorduroy/maps-picker.git

**Related code, data or error log (please format your code or data):**
No errors.

**Comment by wf9a5m75** [comment]
Sorry, but I don't support the compatibilities with other plugins, because it's too much work always, ant the datepicker is not HTML element.

But if you donate some amount to the project, I will check it. Otherwise please find another solution.

**Comment by z1ad** [comment]
Ive found a fix for this issue - the problem is MyPluginLayer.m assumes that any non-map clicks are meant to the webview. But some plugins (like datepicker, listpicker, etc) add a subview on top of webview and they are ignored.

#1875
