### ISSUE TITLE
Direction Render javascript api not compatible with map object

### ISSUE THREAD

**Issue by jayeshanandani** [mapsplugin/cordova-plugin-googlemaps#1585]
**I'm submitting a ...**  (check one with "x")
[x ] question
[ ] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ x] **2.0.0-beta2** 

**Current behavior:**

I am using google Cordova plugin for most of the operation that I want to achieve. How ever there are few operations that are not present as part of this plugin. One of them is plotting a path for the driver between 2 lat lang. I am trying to use google.maps.DirectionsRenderer and the method setMap requires a map object which when given shows non-compatibility with map object given by this plugin and hence the path is not plotted.

**Expected behavior:**
The map object should be accepted and be compatible with Javascript API so it can be reused or is there a way to achieve this using this plugin along with Javascript API.

**Comment by wf9a5m75** [comment]
Currently, I can not accept your request.
I have no plan to use the Google Maps JavaScript API v3 so far.
But both are not affected each others. So you can use it.

----

You need to parse the result of DirectionServices, and pass the points to the plugin.

**Comment by jayeshanandani** [comment]
@wf9a5m75 : Thanks for the quick response. I appreciate the answer and I understand you are not looking to implement this feature which is absolutely alright as per priority. My only concern was that if DirectionRender service needs map instance to plot path, why can't we pass map instance that the plugin generates?

**Comment by wf9a5m75** [comment]
Because this plugin does not use the Google Maps JavaScript API v3.

This plugin generates map using Google Maps Android API v2(Java) and Google Maps SDK for iOS(Objective-C). The map view is not HTML element.

So I have a question.

Do you pass an instance of JavaScript to PHP directly?

```
function App() {
   ...
}
var myApp = new App();

$MYAPP = myApp;
echo $MYAPP.myMethod();
```

**Comment by jayeshanandani** [comment]
Thank you for your wise answer as always. It helped me understand things better :)
