### ISSUE TITLE
Marker click do not AutoPan on second click

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1589]
Plugin version: `2.0.0-beta2-20170725-1201`
Platform: iOS only

- I click a marker once
- I move around the map
- I click on this very same marker again (without clicking any other marker in between)
=> It does not auto pan

![ezgif-3-03eca0631d](https://user-images.githubusercontent.com/16256207/28608816-5b240516-71e2-11e7-82f1-444d9ebb76da.gif)

**Comment by wf9a5m75** [comment]
Um, storage. I will check this later.

**Comment by wf9a5m75** [comment]
Sorry, I have been working on the marker clustering feature (private test).
Since this is not critical issue, please wait for a while.

**Comment by antoine92190** [comment]
Sure, no problem.
I am more interested in seeing the clustering feature go public anyway :simple_smile:

**Comment by wf9a5m75** [comment]
I confirmed this is not a bug. This is default behavior of the Google Maps SDK for iOS.

**Comment by wf9a5m75** [comment]
This is not a bug, but I also prefer the same behavior as Android.
So I change the code to pan the map camera mandatory.

![1589](https://user-images.githubusercontent.com/167831/28694485-9fb2d3d6-72de-11e7-951e-cf649a534cc8.gif)

**Comment by antoine92190** [comment]
Yes, I also think the iOS behaviour is strange.
Thanks for the fix !
