### ISSUE TITLE
Is it possible to debug/trace the plugin / Request for improved error handling

### ISSUE THREAD

**Issue by ThorvaldAagaard** [mapsplugin/cordova-plugin-googlemaps#1591]
**I'm submitting a ...**  (check one with "x")
[X ] question
[X ] any problem or bug report
[ X] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ X] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-custom-config 3.1.4 "cordova-custom-config"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-backbutton 0.3.0 "Backbutton"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-firebase 0.1.22 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta2-20170725-1201 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ios-camera-permissions 1.1.1 "iOS Permissions"
cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"
cordova-plugin-media 3.0.1 "Media"
cordova-plugin-nativegeocoder 1.0.2 "NativeGeocoder"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova.plugins.diagnostic 3.6.5 "Diagnostic"
de.appplant.cordova.plugin.local-notifica
```

**Current behavior:**

Second page with Map never fires MAP_READY

**Expected behavior:**

As the MAP_READY isn't fired, I expect there might be some error in my project, so I would like to be able to follow/trace the plugin, som I could get a hint about what might cause the problem

**Steps to reproduce:**

I have updated the Ionic/Cordova platform and made sure all plugins are at latest version, and this might have been introduced when google maps was updated to 2.0.0-beta2-20170725-1201, as it was working in version 2.0.0-beta2-20170720-1431. But as I have updated a lot of tools at the same time it is by no means expected to be a bug in the plugin

But in stead of wasting your time it would be nice if there was some error messages indicating why the MAP-READY isn't fired

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```
I have seen the same behaviour if I was call the Map with a Position where Lon/Lat was undefined, it just never fired the MAP_READY but gave no information about the error in position

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

Sure, as soon as my App is in the App Store :-)

**Comment by wf9a5m75** [comment]
Could you show me the map.getMap()?

**Comment by ThorvaldAagaard** [comment]
Just an update to let you know that as expected the problem was in my own code, as I was calling creating the Map in the constructor of the page, and not as I now have found out in the method

ionViewDidEnter()

So I did call

let map: GoogleMap = this.googleMaps.create(element)

when element was null.

But still it would be nice with some validation errors

**Comment by wf9a5m75** [comment]
You need to wait `platform.ready()`. This is the only way to create a map safely.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ionic-native/README.md

**Comment by ThorvaldAagaard** [comment]
That is not enough on Ionic 3 it seems, as the view probably isn't populated at that time

Failing code

    platform.ready().then(() => { 
     if (platform.is('cordova')) { 
       console.log("Loading map"); 
       this.loadMap(); 
     } 

Working code as platform.ready() is fired before IonViewWillEnter 

    ionViewDidEnter() { 
     if (this.platform.is('cordova')) { 
       console.log("Loading map"); 
       this.loadMap(); 
     } 
  }

**Comment by wf9a5m75** [comment]
I'm not familiar with ionic at all, but the certain thing is the plugin has to wait the cordova itself is ready, that is `platform. ready()`

**Comment by ThorvaldAagaard** [comment]
You are probably right. I am not sure if there are som issues with Ionic and platform.ready(), as i should fire, when the webpage is loaded to

But for me it worked fine moving it to after the page was displayed (Here is the Ionic LifeCycle: http://ionicframework.com/docs/api/navigation/NavController/)

But back to my request for improved error handling and debugging, is that something you will look at?

**Comment by wf9a5m75** [comment]
If you can read the native code, you understand what you should do to debug the plugin.
There is a hidden option.

But if you are not familiar with native code (java or objective-c), I don't want to use it.
Because this plugin has two side: JS and native side, and both knowledge are necessary.
I only know really a few people who understand this plugin deeply.
(These people don't ask there issues to here. Sending a pull request directly)

For the reason, I ask to share your code on github or bitbucket (for everyone) typically.

**Comment by ThorvaldAagaard** [comment]
I think I understand most of the JS and Java but still strugling with objective-c. But the Ionic process to update a plugin is annoying. I did notice the debug option but didn't figure out how to enable it. But I will give it a try when I hit the next problem.

**Comment by wf9a5m75** [comment]
If you are familiar with Java, talk situation is different.
You may notice `mPluginLayout.isDebug` option.
Did you find where `mPluginLayout.isDebug = true/false`?
If you find it, you would get the answer how to enable the debug option from JS side easily.

**Comment by ThorvaldAagaard** [comment]
Still strugling with the maps (Sometime it works, and at other times it doesn't) I have done som searching, and found this:
https://stackoverflow.com/questions/43882805/ionic-2-document-getelementbyid-returns-null

So for Ionic the recommended way with 

    this.mapElement = document.getElementById('map');

should probably be changed to something like this

```javascript
    import { GoogleMaps, GoogleMap, GoogleMapsEvent, GoogleMapOptions, 
    CameraPosition, MarkerOptions, Marker } from '@ionic-native/google-maps';
    import { Component, ViewChild, ElementRef  } from "@angular/core/";
    import { Platform } from 'ionic-angular';
    @Component({
      selector: 'page-home',
      templateUrl: 'home.html'
     })
    export class HomePage {
      @ViewChild('map', { read: ElementRef }) mapElement: ElementRef;

    map: GoogleMap;
    constructor(private googleMaps: GoogleMaps, public platform: Platform) {
      // Wait the native plugin is ready.
      platform.ready().then(() => {
          this.loadMap();
       });
    }

    // Don't use the ngAfterViewInit(). The native plugin is not ready.
    //ngAfterViewInit() {
    // this.loadMap();
    //}

    loadMap() {
      let mapOptions: GoogleMapOptions = {
      camera: {
        target: {
          lat: 43.0741904,
          lng: -89.3809802
        },
        zoom: 18,
        tilt: 30
      }
    };

    this.map = this.googleMaps.create(this.mapElement.nativeElement, mapOptions);

    // Wait the MAP_READY before using any methods.
    this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => {
        console.log('Map is ready!');

        // Now you can use all methods safely.
        this.map.addMarker({
            title: 'Ionic',
            icon: 'blue',
            animation: 'DROP',
            position: {
              lat: 43.0741904,
              lng: -89.3809802
            }
          })
          .then(marker => {
            marker.on(GoogleMapsEvent.MARKER_CLICK)
              .subscribe(() => {
                alert('clicked');
              });
          });

      });
    }
  }
```
For the html it is important to use #map as identifier, but I can that's all ready done
```html
<ion-content padding>
  <div #map id="map" style="height:100%;"></div>
</ion-content>
```

Here is a link to a guide for creating an Ionic 2 or 3 using Google Maps
https://www.joshmorony.com/ionic-2-how-to-use-google-maps-geolocation-video-tutorial/

**Comment by wf9a5m75** [comment]
Is this a new project or `Gemeapp/Geme`? If new, could you share it with me?

**Comment by ThorvaldAagaard** [comment]
Its still the same project, and you still have access. The sample above is the sample form your documentation I have updated
