### ISSUE TITLE
[ionic] The map shows a white part

### ISSUE THREAD

**Issue by clandro89** [mapsplugin/cordova-plugin-googlemaps#1592]
Hi,
Plugin version: 2.0.0-beta2-20170726
Platform: Android
If I change the view and then return to map view, the map show a white part like the image, but the problem fixed if I touch the map
![screenshot_2017-07-26-18-27-09](https://user-images.githubusercontent.com/30482272/28648432-67814ade-7233-11e7-964e-465664c74f2e.png)

**Comment by wf9a5m75** [comment]
There is no `2.0.0-beta2-20170726` version yet.

Could you show me the output of `$> cordova plugin list`?

**Comment by wf9a5m75** [comment]
And I think the map div (`<div id="map">`) size are changed after the map is displayed.

Try:
```
ngAfterViewInit() {
   cordova.fireDocumentEvent('plugin_touch', {});
}
```

**Comment by clandro89** [comment]
Sorry, is 2.0.0-beta2-20170725-1201
Actually the top content is inside  of map div, so the map div size is the same, but the problem fixed whit `cordova.fireDocumentEvent('plugin_touch', {});`
Thanks a lot!

**Comment by jsdussanc** [comment]
it's still happening in 
Ionic  3.18
@ionic-native/google-maps": "^4.4.2"
cordova-plugin-googlemaps": "^2.1.1"


I changed the size with ngClass, but I had to change it manually to implement this solution
