### ISSUE TITLE
MAP_READY event not fired on IOS

### ISSUE THREAD

**Issue by ThorvaldAagaard** [mapsplugin/cordova-plugin-googlemaps#1594]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ X] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ X] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-custom-config 3.2.0 "cordova-custom-config"
cordova-plugin-add-swift-support 1.6.0 "AddSwiftSupport"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-backbutton 0.3.0 "Backbutton"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-firebase 0.1.22 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta2-20170725-1201 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ios-camera-permissions 1.1.1 "iOS Permissions"
cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"
cordova-plugin-media 3.0.1 "Media"
cordova-plugin-nativegeocoder 1.0.2 "NativeGeocoder"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova.plugins.diagnostic 3.6.5 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**

Using Ionic 3 I have built an app, that should show a map.
On Android all works fine (After using the right way to find the element on the page that contains  the map)
**Expected behavior:**

Map should load

**Steps to reproduce:**

Follow the instruction on https://www.joshmorony.com/ionic-2-how-to-use-google-maps-geolocation-video-tutorial/

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
In CordovaGoogleMaps.m in method getMap there is a statement

[mapCtrl.view setHidden:YES];

right at the beginning. Removing that seems to solve the problem.

Looking at the code it seems that the problem is that the internal event MAP_LOADED never is fired.

This could be a problem only in Ionic

```

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
In order to hide the camera moving when you set the cameraPosition with map.getMap(), it is necessary code.


And https://www.joshmorony.com/ionic-2-how-to-use-google-maps-geolocation-video-tutorial/ uses the Google Maps JavaScript API v3, not this plugin.
So I guess you use completely wrong code.

**Comment by ThorvaldAagaard** [comment]
I was just giving the link to make it simple to reproduce as it otherwise is difficult to set up the proper environment. You are still free to install Geme/Geme on you Mac to reproduce the error

**Comment by ThorvaldAagaard** [comment]
And sorry for trying to short cut the reproduction of this issue, but I have been working day and night to find a solution

**Comment by ThorvaldAagaard** [comment]
But could it be that 
    
    [mapCtrl.view setHidden:YES];

should only be executed if there are camera options with map.getMap(), that would explain my trouble as I have moved the camera options to after map is loaded

**Comment by wf9a5m75** [comment]
Did you follow the all code from the `getMap()`in CordovaGoogleMaps.m to the end (until the `MAP_READY`)?

**Comment by wf9a5m75** [comment]
I understand you are not familiar with Objective-C, but you are familiar with Java, so you can follow the code flow at least.

**Comment by wf9a5m75** [comment]
(I'm working on my real job currently. I haven't enough time to check the code deeply right now. I don't ill turn for you.)

**Comment by ThorvaldAagaard** [comment]
I tried to follow the code, but the debugger on Ios often switch to assembly code. I could find the code for MAP_LOADED (the internal event) and added a breakpoint there. 

It was never reached

The I changed the statement as mentioned above and now I got the event.

I had trouble following the flow from MyPluginLayer to mapViewDidFinishTileRendering in PluginMap, as it is pretty different in the objective-c version compare to java

**Comment by ThorvaldAagaard** [comment]
I added the camera option to getMap(), but that did not fix the problem.

Searching thru the code I can see only 2 places where

    mapCtrl.view setHidden:NO

is called, and that is for the action "MoveCamera".

But I have no clue about where to unhide the view for the getMap() function

**Comment by wf9a5m75** [comment]
iOS code follows these steps:

1. [(void)getMap:(CDVInvokedUrlCommand *)command](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a57eb9055930b15e8313e5c05750f474041792f5/src/ios/GoogleMaps/CordovaGoogleMaps.m#L154) in CordovaGoogleMaps.m

Executes `[mapCtrl.view setHidden:YES];`

2. [[pluginMap getMap:command];](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a57eb9055930b15e8313e5c05750f474041792f5/src/ios/GoogleMaps/CordovaGoogleMaps.m#L312)  -> [- (void)getMap:(CDVInvokedUrlCommand*)command](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a57eb9055930b15e8313e5c05750f474041792f5/src/ios/GoogleMaps/PluginMap.m#L118) in PluginMap.m

3. If you specified the map div, the `[command.arguments count]` is `3`.
So go to line 142.

4. If no camera option, simply go to `[self _setOptions:initOptions]` at [line 150](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a57eb9055930b15e8313e5c05750f474041792f5/src/ios/GoogleMaps/PluginMap.m#L150) 

5. Now we are here [- (void)_setOptions:](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a57eb9055930b15e8313e5c05750f474041792f5/src/ios/GoogleMaps/PluginMap.m#L733)

If you don't specify the `camera` option at the `map.getMap()`, simply return to the JS side.
[[self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a57eb9055930b15e8313e5c05750f474041792f5/src/ios/GoogleMaps/PluginMap.m#L914)

6. In the success callback, the code wait the `MAP_LOADED` event.
[self.one(event.MAP_LOADED, function() {}](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a57eb9055930b15e8313e5c05750f474041792f5/www/Map.js#L168-L171)


7. The tile load is slow (as far as I tested), so the [mapViewDidFinishTileRendering:(GMSMapView *)mapView](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a57eb9055930b15e8313e5c05750f474041792f5/src/ios/GoogleMaps/GoogleMapsViewController.m#L362) fires the `MAP_LOADED` event after the callback.


----

Possible problem point is the `MAP_LOADED` is done before the code flow leaches to the JS callback.

**Comment by ThorvaldAagaard** [comment]
Updated my previous comment. You are probably right it is a timing issue, that could also explain why it sometimes work.

But for now I will just add the camera option as that works, so you can continue on your real job.

**Comment by wf9a5m75** [comment]
ok

**Comment by wf9a5m75** [comment]
I found a bug that does not display the map in your case. I fixed it.
