### ISSUE TITLE
cant install plugin

### ISSUE THREAD

**Issue by chukwu** [mapsplugin/cordova-plugin-googlemaps#1595]
```
Error: Failed to fetch plugin git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**I'm submitting a ...**  (check one with "x")
[ ] question
[. ] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ ] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
Please search the past issues before asking.

https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=install&type=Issues&utf8=✓

**Comment by tryadelion** [comment]
@wf9a5m75  please provide a working answer instead, there are different issues referenced on that search query.

**Comment by chukwu** [comment]
**Try this.......It doesnt make sense but works**

**Delete ios platform**

$> cordova platform add ios  //install the platform first for just in case

// If you get the below error, just ignore. And try again.
Error: Failed to fetch platform cordova-ios@~4.4.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Failed to get absolute path to installed module

$> cordova platform add ios

// Add the SDK plugin at first with --nofetch option
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk --nofetch

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_IOS="(API key)"

**Comment by tryadelion** [comment]
i re-added the platform and it worked. it didn't 1 hour ago. _the hell is going on_  😕

**Comment by aparkertg** [comment]
Thanks @chukwu and @tryadelion this solved my problem, and I didn't have to downgrade Cordova to 6.5 as mentioned in other articles.

I deleted my iOS platform and then added it back. 

I then executed:
ionic cordova plugin add cordova-plugin-googlemaps \
  --variable API_KEY_FOR_ANDROID="(API Key" \
  --variable API_KEY_FOR_IOS="API Key"

Worked after that.

**Comment by leo4444** [comment]
I had the same problem ...
I already had a project on Android developed on Windows 10 and I was now working on Mac for iOS. When I wanted to add the platform (sudo ionic cordova platform add ios) I had this problem ... I tried many things but the problem was that I added "sudo" in the command line. Removing "sudo" gave me permission errors in the platforms / ios directory, so I gave it read / write permissions and ran the command again ...
This was what worked for me, I hope it serves the one who has this problem
