### ISSUE TITLE
can't remove tileOverlay on android

### ISSUE THREAD

**Issue by frank10gm** [mapsplugin/cordova-plugin-googlemaps#1597]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-brightness 0.1.5 "Brightness"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.0.0 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta2-20170727-1500 "cordova-plugin-googlemaps"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-media 3.0.1 "Media"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**

I just try removing the tileoverlay and it crashes

**Expected behavior:**

removing the tileoverlay

**Steps to reproduce:**

just add a tileoverlay on android and remove it

**Comment by wf9a5m75** [comment]
Please show me the crash log.

**Comment by frank10gm** [comment]
`07-29 19:19:33.666 I/chromium(27545): [INFO:CONSOLE(19)] "tile: {"_map":{"_objectInstance":{"MARKERS":{"marker_m0":{"event":{}},"marker_m1":{"event":{}},"marker_m2":{"event":{}},"marker_m4":{"event":{}},"marker_m3":{"event":{}},"marker_m7":{},"marker_m5":{},"marker_m8":{},"marker_m9":{},"marker_m6":{},"marker_m10":{},"marker_m11":{},"marker_m13":{},"marker_m16":{},"marker_m14":{},"marker_m12":{},"marker_m17":{},"marker_m15":{}},"KML_LAYERS":{},"OVERLAYS":{"circle_ci0":{"event":{}},"marker_m0":{"event":{}},"marker_m1":{"event":{}},"marker_m2":{"event":{}},"marker_m4":{"event":{}},"marker_m3":{"event":{}},"marker_m7":{},"marker_m5":{},"marker_m8":{},"marker_m9":{},"marker_m6":{},"marker_m10":{},"marker_m11":{},"marker_m13":{},"marker_m16":{},"marker_m14":{},"marker_m12":{},"marker_m17":{},"marker_m15":{},"tileoverlay_1012599483921":{}},"event":{}}},"_objectInstance":{}}", source: file:///android_asset/www/build/main.js (19)
07-29 19:19:33.671 D/AndroidRuntime(27545): Shutting down VM
07-29 19:19:33.672 E/AndroidRuntime(27545): FATAL EXCEPTION: main
07-29 19:19:33.672 E/AndroidRuntime(27545): Process: io.ionic.starter, PID: 27545
07-29 19:19:33.672 E/AndroidRuntime(27545): java.lang.NullPointerException
07-29 19:19:33.672 E/AndroidRuntime(27545):     at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java)
07-29 19:19:33.672 E/AndroidRuntime(27545):     at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java)
07-29 19:19:33.672 E/AndroidRuntime(27545):     at plugin.google.maps.PluginTileOverlay$2.run(PluginTileOverlay.java:162)
07-29 19:19:33.672 E/AndroidRuntime(27545):     at android.os.Handler.handleCallback(Handler.java)
07-29 19:19:33.672 E/AndroidRuntime(27545):     at android.os.Handler.dispatchMessage(Handler.java)
07-29 19:19:33.672 E/AndroidRuntime(27545):     at android.os.Looper.loop(Looper.java)
07-29 19:19:33.672 E/AndroidRuntime(27545):     at android.app.ActivityThread.main(ActivityThread.java)
07-29 19:19:33.672 E/AndroidRuntime(27545):     at java.lang.reflect.Method.invoke(Native Method)
07-29 19:19:33.672 E/AndroidRuntime(27545):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
07-29 19:19:33.672 E/AndroidRuntime(27545):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
07-29 19:19:33.677 W/ActivityManager( 1851):   Force finishing activity io.ionic.starter/.MainActivity`

**Comment by wf9a5m75** [comment]
Thank you. And could you show me the code around the TileOverlay.remove()?

I guess you do:

```js
tileoverlay.remove();
map.clear();
```

**Comment by frank10gm** [comment]
sure I do as you said!

`}).then((tileOverlay) => {
      tileOverlay.remove();
map.clear();
    });`

**Comment by wf9a5m75** [comment]
You don't need to `tileoverlay.remove()` before `map.clear()`.

`map.clear()` do that automatically.

**Comment by frank10gm** [comment]
Ok, I removed that line. But it is not related to the error because it still remains.

**Comment by wf9a5m75** [comment]
I see. Could you share your project files on github or bitbacket?
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/articles/before_post_your_issue/README.md#6-provide-your-code

**Comment by frank10gm** [comment]
Sorry I misspelled, I don't want to remove all map elements (such markers).
The purpose of the tile.remove() is just for changing tile (night and day mode of my personal tileset).
1. I remove day tile
2. Add the night tile to the map

**Comment by wf9a5m75** [comment]
I see. I noticed the demo apk I provide also crashes. I will check it later.

**Comment by frank10gm** [comment]
Thank you!

**Comment by wf9a5m75** [comment]
I fixed the bug. Please reinstall the latest version `2.0.0-beta2-20170729-1650`

**Comment by frank10gm** [comment]
Great! Thank you very much for your work.
