### ISSUE TITLE
Map asks for Geolocation twice

### ISSUE THREAD

**Issue by dasois** [mapsplugin/cordova-plugin-googlemaps#1598]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x ] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-googlemaps 2.0.0-beta2-20170729-1650 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-nativegeocoder 1.0.2 "NativeGeocoder"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"
phonegap-plugin-push 1.10.5 "PushPlugin"
{}
```

**Current behavior:**
After intalling and starting my app, the map, that get's immediately loaded at the startup after device is ready, asks for the location two times.

**Expected behavior:**
only ask once

**Steps to reproduce:**
1. install app
2. start app

files: https://github.com/fr4gstar/findlunch.git#code_review

**Screen capture or video record:**

![screencast_double-geolocation](https://user-images.githubusercontent.com/3832690/28753116-3f963012-752f-11e7-9c4f-9396d8e35f3f.gif)

**Related code, data or error log (please format your code or data):**

```
this.platform.ready().then(
            () => {
                this.loadMap();
            })
```

**Comment by wf9a5m75** [comment]
What branch?

**Comment by dasois** [comment]
code_review

Am 31. Juli 2017 00:30:55 MESZ schrieb Masashi Katsumata <notifications@github.com>:
>What branch?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1598#issuecomment-318934560

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by wf9a5m75** [comment]
In the `home.ts`, you do

```js
this.map.setMyLocationEnabled(true);   <--- The plugin asks the permission the first time
this.map.setAllGesturesEnabled(true);
this.map.setCompassEnabled(true);

this.map.getMyLocation(...)    <--- The plugin asks the permission the second time
```

Remember, the native methods execute asynchronously. 
Let's write your code with pseudo-code,

```
function setMyLocationEnabled() {
  if (!plugin.hasPermission("geolocation")) {
    askPermission(function() {
      setMyLocationEnabled();
    });
    return;
    ...
 }
}
setTimeout(function() {
  setMyLocationEnabled();
}, 0);

this.map.setAllGesturesEnabled(true);  // skip explaining
this.map.setCompassEnabled(true);   // skip explaining

function getMyLocation() {
  if (!plugin.hasPermission("geolocation")) {
    askPermission(function() {
      getMyLocation();
    });
    return;
    ...
 }
}

setTimeout(function() {
  getMyLocation()
}, 0);
```

As you can see, the plugin checks it has the permission before executing the actual code.

When you execute `setMyLocationEnable()`, then execute `getMyLocation()` soon, the plugin does not have the permission yet.
That's why the maps plugin asks the permission twice.

This is not bug.

------------

In order to avoid this, you should specify with the initialize options.


```js
this.map = plugin.google.maps.Map.getMap(element, {
  controls: {
    'myLocationButton': true,
    'compass': true
  },
  'gestures': {
    'scroll': true,
    'tilt': true,
    'rotate': true,
    'zoom': true
  }
});
```

**Comment by dasois** [comment]
Thank you for pointing that out. Using initialize options fixed it.

However would suggest introducing a "isAskingPermission()" in order to prevent this async issue, if possible.

**Comment by wf9a5m75** [comment]
Not possible. Because the native methods are executed as  async by cordova.

**Comment by dasois** [comment]
They don't have callbacks? 

Am 1. August 2017 15:51:32 MESZ schrieb Masashi Katsumata <notifications@github.com>:
>Not possible. Because the native methods are executed as  async by
>cordova.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1598#issuecomment-319375894

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by wf9a5m75** [comment]
`cordova.exec()` method itself works as async.

If you want to fall into so many callback, you can use v1.4 like this:

```js
var self = this;
self.map.setMyLocationEnabled(true, function() {
  self.map.setAllGesturesEnabled(true, function() {
    self.map.setCompassEnabled(true, function() {
      self.map.getMyLocation(function(result) {
         ...
      });
    });
  });
});
```

**Comment by wf9a5m75** [comment]
@dasois By the way, are you interested in to the MarkerClustering?
If yes, I invite you to the private repo if you help me to fix the ionic wrapper plugin.

**Comment by wf9a5m75** [comment]
@dasois Good new for you.

I bumped up the plugin version `2.0.0-beta3-20170802-1930`.
I implemented the safe command queue mechanism.

This mechanism allows you to write the below code, but the permission asks only one time.

```
this.map.setMyLocationEnabled(true);
this.map.getMyLocation(...);
```

**Comment by dasois** [comment]
@wf9a5m75 Ah that's nice, I implemented it as you suggested with the config options, though.

**Comment by wf9a5m75** [comment]
Please contact to me by e-mail.
