### ISSUE TITLE
Issue Installing the v2 (multiple-maps) variant

### ISSUE THREAD

**Issue by tryadelion** [mapsplugin/cordova-plugin-googlemaps#1599]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ X] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ X] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-firebase 0.1.22 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta2-20170725-1201 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

*Issue Description*

Currently Using ionic.

sh-3.2# ionic info

cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (/Users/admin/Documents/dev/ionic/incom/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/admin/Documents/dev/ionic/incom/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/Users/admin/Documents/dev/ionic/incom/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/Users/admin/Documents/dev/ionic/incom/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 26.0.2
    Node              : v6.9.2
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
    ios-deploy        : 1.9.0
    ios-sim           : 5.0.13
    npm               : 5.3.0

Additional info: also tried downgrading Cordova to 6.5.X and almost all the hacks present on the lateast 10-days installation issues ( --no-fetch, update npm, etc..).

Currently facing an issue when installing from *sudo* where the CLI finds itself unable to retrieve the plugin, giving a permission issue. I was trying to install the plugin for the Ios platform as removing it and readding it caused the plugin to not reinstall correctly. all the  other plugins worked fine.

command ran:

ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="APIKEYANDROID" --variable API_KEY_FOR_IOS="APIKEYIOS" --no-fetch

i wish not to remove it (nor remove npm_modules), as it would be very uncomfortable, all the other plugins are fine and the android platform finally worked.

*Issue output*

An error occurred while running cordova plugin add
        https://github.com/mapsplugin/cordova-plugin-googlemaps#multi... (exit code 1):

        Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps via
        registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 1 Error output:
        npm ERR! code 128
        npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b multiple_maps
        https://github.com/mapsplugin/cordova-plugin-googlemaps.git /var/root/.npm/_cacache/tmp/git-clone-47f8ce5f
        npm ERR! fatal: could not create leading directories of '/var/root/.npm/_cacache/tmp/git-clone-47f8ce5f':
        Permission denied
        npm ERR!

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /var/root/.npm/_logs/2017-07-31T11_05_19_407Z-debug.log

**Comment by wf9a5m75** [comment]
Installing problem is your problem. This is not plugin's problem.

Error reasons really depends on your situation, and your information is too less.

First of all, you should try with `--verbose` and `--no-fetch` option.

```
$> cordova plugin add https://..... --variable .... --verbose --no-fetch
```

**Comment by tryadelion** [comment]
it didn't work, sadly it seems it either itself  or there was a github issue, as running the same command after lunch (eaving the mac open) solved it. you should check there is no issue in your repository because this is too frequent and too wide user-speaking to be only _my mac's fault_.

**Comment by tryadelion** [comment]
--no-fetch makes no change at all at the build process under the specified versions above.

**Comment by wf9a5m75** [comment]
`--variable` option gives you the information of the error details.

`--no-fetch` option prevents the npm command use the intetnal cache.

As I wrote, information is too less, I needed the error details.

-----

Normally, there is no problem to install the plugin.
Mac users common mistakes are :
- permission error
- cordova version is old or too new
- open the project folder with Android Studio
- git command version is too old

Windows users are:
- Visual studio is not installed correctly

Most of users are no problem.

This plugin completely comply with the cordova plugin specification.
If you doubt me, you can check the code. If you find the problem, please send me a pull request.

**Comment by ThorvaldAagaard** [comment]
Just leave out ionic in the command
