### ISSUE TITLE
Two map instance in conflict

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#1603]
i have one map with more than one marker, and another with just one.
When i enter the first map and then i go to the second, the second has the markers of the first one. is there a way to remove the first instace of the map to prevent that to happen. I am using cordova google maps plugin with ionic native.

**Comment by wf9a5m75** [comment]
Could you share your project files (or create an empty example project), and share it on github or bitbucket?

As far as I know, the JS version does not conflict each others.
But ionic-native version has many bugs. I have been working on to fix it.

**Comment by francoro** [comment]
I found out that my problem is the event listeners from the first map, it keeps in the second. is there a way to remove all event listeners in ionic native. i think i see there is a map.off method but in the JS version maybe its something similar in the ionic native that could help me

**Comment by francoro** [comment]
I see that have this version off the plugin 
<plugin name="cordova-plugin-googlemaps" spec="^1.4.0">

Is there a new one with the map.off method ?

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbucket.

Ionic-native does not use the v1.4 currently.

**Comment by francoro** [comment]
Pass me your email and i invite you to the repo

**Comment by wf9a5m75** [comment]
wf9a5m75@gmail.com

**Comment by francoro** [comment]
i already invite you, i will send you an email with the instructions

**Comment by wf9a5m75** [comment]
The v1.4 does not support multiple maps.

This is the answer of all.

**Comment by francoro** [comment]
i am having this error while running command: 

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multi... (exit code 1):


        You have been opted out of telemetry. To change this, run: cordova telemetry on.
        Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Failed to get absolute path to installed module

**Comment by wf9a5m75** [comment]
Please show me the whole error log, and don't choose the error log by yourself.
Installing the problem is your environment problem, but it's really depends on the situation.

Please show me the output of this command.

(Don't add `ionic`)
```
$>  cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="myapikey" --variable API_KEY_FOR_IOS="myapikey" --verbose --no-fetch
```

**Comment by francoro** [comment]
i already installed i removed and added again and works. It is okay that in the package.json says 
"cordova-plugin-googlemaps": "^1.4.3"
 or i have to change it manually to v2 or something like that

and in the config.xml

<plugin name="cordova-plugin-googlemaps" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps">
        <variable name="API_KEY_FOR_ANDROID" value="myapikey" />
        <variable name="API_KEY_FOR_IOS" value="myapikey" />
    </plugin>

**Comment by wf9a5m75** [comment]
This is not good.
`"cordova-plugin-googlemaps": "^1.4.3"` 

Because the v2 is beta version, so I don't publish the code to npm yet.
You can not install the v2 through npm.
So you need to remove the line.

**Comment by wf9a5m75** [comment]
![screen shot 2017-08-02 at 10 29 07 am](https://user-images.githubusercontent.com/167831/28886191-6f86bc66-776d-11e7-9bca-60907d94e972.png)

And I'm still installing modules in order to build your app... :(

**Comment by wf9a5m75** [comment]
Uh ah, lots of problems...

```
$> ionic cordova platform add android
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
> cordova platform add android --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova platform add android --save
        (exit code 1):
        
        (truncated) ... oblem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 194 Error output:
        npm ERR! path
        /Users/masashi/Documents/workspace/test/mdp365-ionic3/node_modules/es6-promise-plugin/package.json
        npm ERR! code ELOOP
        npm ERR! errno -62
        npm ERR! syscall open
        npm ERR! ELOOP: too many symbolic links encountered, open
        '/Users/masashi/Documents/workspace/test/mdp365-ionic3/node_modules/es6-promise-plugin/package.json'
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!
        /Users/masashi/.npm/_logs/2017-08-02T17_28_31_029Z-debug.log
        Discovered plugin "cordova.plugins.diagnostic" in config.xml. Adding it
        to the project
        Failed to restore plugin "cordova.plugins.diagnostic" from config.xml.
        You might need to try adding it again. Error: Failed to fetch plugin
        cordova.plugins.diagnostic@^3.6.5 via registry.
        Probably this is either a connection problem, or plugin spec is
        incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 194 Error output:
        npm ERR! path
        /Users/masashi/Documents/workspace/test/mdp365-ionic3/node_modules/es6-promise-plugin/package.json
        npm ERR! code ELOOP
        npm ERR! errno -62
        npm ERR! syscall open
        npm ERR! ELOOP: too many symbolic links encountered, open
        '/Users/masashi/Documents/workspace/test/mdp365-ionic3/node_modules/es6-promise-plugin/package.json'
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!
        /Users/masashi/.npm/_logs/2017-08-02T17_28_45_435Z-debug.log
        Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to
        the project
        Failed to restore plugin "ionic-plugin-keyboard" from config.xml. You
        might need to try adding it again. Error: Failed to fetch plugin
        ionic-plugin-keyboard@^2.2.1 via registry.
        Probably this is either a connection problem, or plugin spec is
        incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 194 Error output:
        npm ERR! path
        /Users/masashi/Documents/workspace/test/mdp365-ionic3/node_modules/es6-promise-plugin/package.json
        npm ERR! code ELOOP
        npm ERR! errno -62
        npm ERR! syscall open
        npm ERR! ELOOP: too many symbolic links encountered, open
        '/Users/masashi/Documents/workspace/test/mdp365-ionic3/node_modules/es6-promise-plugin/package.json'
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!
        /Users/masashi/.npm/_logs/2017-08-02T17_28_59_706Z-debug.log
        Discovered plugin "mx.ferreyra.callnumber" in config.xml. Adding it to
        the project
        Failed to restore plugin "mx.ferreyra.callnumber" from config.xml. You
        might need to try adding it again. Error: Failed to fetch plugin
        mx.ferreyra.callnumber@~0.0.2 via registry.
        Probably this is either a connection problem, or plugin spec is
        incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 1 Error output:
        npm ERR! code E404
        npm ERR! 404 Not Found: mx.ferreyra.callnumber@~0.0.2
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!
        /Users/masashi/.npm/_logs/2017-08-02T17_29_10_774Z-debug.log
        Discovered plugin "onesignal-cordova-plugin" in config.xml. Adding it to
        the project
        Failed to restore plugin "onesignal-cordova-plugin" from config.xml. You
        might need to try adding it again. Error: Failed to fetch plugin
        onesignal-cordova-plugin@^2.1.2 via registry.
        Probably this is either a connection problem, or plugin spec is
        incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 194 Error output:
        npm ERR! path
        /Users/masashi/Documents/workspace/test/mdp365-ionic3/node_modules/es6-promise-plugin/package.json
        npm ERR! code ELOOP
        npm ERR! errno -62
        npm ERR! syscall open
        npm ERR! ELOOP: too many symbolic links encountered, open
        '/Users/masashi/Documents/workspace/test/mdp365-ionic3/node_modules/es6-promise-plugin/package.json'
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!
        /Users/masashi/.npm/_logs/2017-08-02T17_29_25_678Z-debug.log
        Discovered plugin "cordova-plugin-googlemaps" in config.xml. Adding it
        to the project
        Failed to restore plugin "cordova-plugin-googlemaps" from config.xml.
        You might need to try adding it again. Error: Failed to fetch plugin
        cordova-plugin-googlemaps@^1.4.0 via registry.
        Probably this is either a connection problem, or plugin spec is
        incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 194 Error output:
        npm ERR! path
        /Users/masashi/Documents/workspace/test/mdp365-ionic3/node_modules/es6-promise-plugin/package.json
        npm ERR! code ELOOP
        npm ERR! errno -62
        npm ERR! syscall open
        npm ERR! ELOOP: too many symbolic links encountered, open
        '/Users/masashi/Documents/workspace/test/mdp365-ionic3/node_modules/es6-promise-plugin/package.json'
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!
        /Users/masashi/.npm/_logs/2017-08-02T17_29_39_211Z-debug.log
        --save flag or autosave detected
        Saving android@~6.2.3 into config.xml file ...
        
$ >
```

**Comment by francoro** [comment]
:( i dont know what to say. i didnt have this errors when i installed.When it works if it works you have to git checkout nueva

**Comment by wf9a5m75** [comment]
I'm trying another way. Then I got this error.

```
$> mv node_modules node_modules_
$> rm -rf platforms package.json package-lock.json
$> cordova prepare
$> ionic cordova build android
$> npm install @ionic/app-scripts
$> npm install typescript
$> ionic cordova build android
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova).
Error: Cannot find module '@angular/tsc-wrapped/src/tsc'
```

**Comment by wf9a5m75** [comment]
It looks something is missing...

```
$> npm install @angular/tsc-wrapped
$> npm install @angular/compiler-cli

$> ionic cordova prepare
> cordova prepare
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova prepare (exit code 1):
        
        Discovered plugin "mx.ferreyra.callnumber" in config.xml. Adding it to the project
        Failed to restore plugin "mx.ferreyra.callnumber" from config.xml. You might need to try adding it again. Error:
        Failed to fetch plugin mx.ferreyra.callnumber@~0.0.2 via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 1 Error output:
        npm ERR! code E404
        npm ERR! 404 Not Found: mx.ferreyra.callnumber@~0.0.2
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/masashi/.npm/_logs/2017-08-02T17_54_03_958Z-debug.log
        
```

**Comment by francoro** [comment]
Delete that mx.ferreyra.callnumber plugin we don need it for this testing purpouse is just for phone calls. maybe is that

**Comment by wf9a5m75** [comment]
I'm tried. Your project files are so many packages are missing for some reason.

Could you double check the repo?
Or simply create another app that contains only map pages?

**Comment by francoro** [comment]
I will try to upload one repo with the maps only

**Comment by wf9a5m75** [comment]
Thank you. I appreciate for your help.

**Comment by wf9a5m75** [comment]
I tested three maps in one page. But all events are fired separately.
(I means I can not confirm the conflict between each maps)

```
var map = plugin.google.maps.Map.getMap(div1);
map.one(plugin.google.maps.event.MAP_READY, function() {
  console.log("--> map_canvas1 : ready.");
  map.on(plugin.google.maps.event.CAMERA_MOVE, function() {
    console.log("--->map1: camera_move");
  });
});
```

**Comment by francoro** [comment]
I am doing a repo with the new code. i have a problem in ionic native i use: map.getVisibleRegion().then((data) => {
})

To get the bounds. Now with the version 2 of the plugin says: map.getVisibleRegion(...).then is not a function. Do you know if there is a new way maybe his name was changed?

**Comment by wf9a5m75** [comment]
```js
var visibleRegion = map.getVisibleRegion();
```

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getVisibleRegion/README.md

**Comment by francoro** [comment]
Okay i wiil give it a try tomorrow. I finish the work office for today. I hope tomorrow i get finished the repo with the two maps. Thanks for your great help of today i appreciate a lot

**Comment by wf9a5m75** [comment]
Ok. Good night

**Comment by francoro** [comment]
I am having trouble installing the plugin v2 in my project but i installed in a empty project a works. This the comand and error log.

cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="myapikey" --variable API_KEY_FOR_IOS="miapikey"

Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

My connection is working fine.

This are my other plugins maybe is in conflict with one of these:

cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-request-location-accuracy 2.2.1 "Request Location Accuracy"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.6.5 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
onesignal-cordova-plugin 2.1.2 "OneSignal Push Notifications"

The weird is that i added to my package.json this line:
 "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",

and i made npm install and it installed correctly so maybe it is not neccesary run the above command?

**Comment by francoro** [comment]
i could install it i had to install first the v1.4 and the above the v2 weird but it works. Then i install npm install --save @ionic-native/google-maps and check that is in the v4 . Now the thing is that doenst recognize the events from the v2 for example CAMERA_MOVE. And i am sure that i have all installed. what can i do?

**Comment by francoro** [comment]
I remove the platform and added again it solves the issue
