### ISSUE TITLE
I can't install plugin in ios platform

### ISSUE THREAD

**Issue by astronmy** [mapsplugin/cordova-plugin-googlemaps#1604]
I have an ionic project running the GoogleMaps plugin on android, when I want to add the ios platform at the time of installing the plugin fails.

Then hit the detail of the terminal

ionic cordova platform add ios
> cordova platform add ios --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova platform add ios --save (exit code 1):
        
        Using cordova-fetch for cordova-ios@~4.4.0
        Adding ios project...
        Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: com.ionicframework.caminoseguro2915508
        Name: CaminoSeguro2
        iOS project created with cordova-ios@4.4.0
        Installing "cordova-plugin-camera" for ios
        Plugin dependency "cordova-plugin-compat@1.1.0" already fetched, using that version.
        Installing "cordova-plugin-compat" for ios
        Dependent plugin "cordova-plugin-compat" already installed on ios.
        Installing "cordova-plugin-console" for ios
        Installing "cordova-plugin-contacts" for ios
        Plugin dependency "cordova-plugin-compat@1.1.0" already fetched, using that version.
        Dependent plugin "cordova-plugin-compat" already installed on ios.
        Installing "cordova-plugin-device" for ios
        **Installing "cordova-plugin-googlemaps" for ios**
        **Failed to install 'cordova-plugin-googlemaps': Error**
        at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:205:33
        at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:864:24)
        at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:890:30
        at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:1142:31)
        at Promise.promise.promiseDispatch
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:808:41)
        at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:624:44
        at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:137:13)
        at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickCallback (internal/process/next_tick.js:180:9)
        Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 1 Error output:
        npm ERR! code 1
        npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master
        https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git
        /Users/rvinci/.npm/_cacache/tmp/git-clone-230fdc79
        npm ERR! /Users/rvinci/.npm/_cacache/tmp/git-clone-230fdc79/.git: Permission denied
        npm ERR!
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/rvinci/.npm/_logs/2017-08-01T19_08_44_145Z-debug.log

Try creating a new project and adding the plugin but the result is the same
I do not know what to do, I can not find the solution anywhere

**Comment by wf9a5m75** [comment]
`npm ERR! /Users/rvinci/.npm/_cacache/tmp/git-clone-230fdc79/.git: Permission denied`

This is the reason.

I guess with `sudo` resolve your issue.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update, I close this issue.
