### ISSUE TITLE
Heat Map / Marker-Cluster

### ISSUE THREAD

**Issue by ThorvaldAagaard** [mapsplugin/cordova-plugin-googlemaps#1605]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[ X] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ X] **2.0.0-beta2** 

**Expected behavior:**

Is it possible to get support for MarkerCluster as described in https://developers.google.com/maps/documentation/javascript/marker-clustering ?

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
Answer for heatmap, please read this thread.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1518

Answer for marker clustering, please read this thread.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1006
