### ISSUE TITLE
ons-dialogを表示・タップやスクロールをしても後ろのGoogleMapsが動いてしまう

### ISSUE THREAD

**Issue by yesman99** [mapsplugin/cordova-plugin-googlemaps#1606]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta2** 
2.0.0-beta2-20170731-1540

**cordova information:**  (run `$> cordova plugin list`) 
Monacaで開発のため、コマンドが利用できません。

**Current behavior:**

OnsenUIを使用時に、GoogleMapsの上にons-dialogを開いてタップやスクロールをしても、背面に表示しているGoogleMapsが反応してしまう。

**Expected behavior:**

ons-dialogを利用してもタップやスクロールにきちんと反応する。

**Steps to reproduce:**
名古屋の近辺にピンが複数落ちており、それをタップするとons-dialogが表示されます。
普通にons-dialog内をスクロール等操作できるときもあれば、後ろのGoogleMapsが動いてしまうこともあります。

アプリを起動後、数秒放置後にこの現象が発生しやすいように思います。

可能であればMonacaのプロジェクトに招待させていただければと思います。

**Screen capture or video record:**
![default](https://user-images.githubusercontent.com/6134076/28857634-e2d4a2f6-7785-11e7-8e8e-05db28925e7b.gif)

**Comment by wf9a5m75** [comment]
dialogを表示するときに、`cordova.fireDocumentEvent('plugin_touch', {});`を実行してくださ

**Comment by wf9a5m75** [comment]
>アプリを起動後、数秒放置後にこの現象が発生しやすいように思います。

はい、正しいと思います。
プラグインでは全てのHTMLの重なり順を考慮しますので、逆に言えば、全てのHTMLの重なり順をチェックしなければなりません。
もちろん省略可能なところはそれなりに省略していますが。

その重なり順を調べる処理は多少時間がかかりますし、CPUもそれなりに使用しますので、ずっと行っているとバッテリーの減りが半端ないです。
そこで指が画面に触れてから最初数秒が新しいHTMLの要素があるかないか、チェックをします。
指が離れてから3秒を経過すると1秒ごとにチェックをして、そこから7秒経過するとチェックすることを止めます。
（これでも長期間監視するようにした方です）
ただし初めて指が触れた領域が地図の場合は、この処理は行いません。

なので、Markerをクリックしたらダイアログを出すようにしているのであれば、ダイアログの領域を地図の領域として認識している確率が高いです。

そのような場合、開発者側で `cordova.fireDocumentEvent('plugin_touch', {});`を実行してください。

**Comment by yesman99** [comment]
早速のご連絡ありがとうございます。お陰様で解決することができました。
ご解説いただきありがとうございます。
またドキュメントの確認漏れ失礼いたしました。

微力ながら寄付させていただきました。
今後共よろしくお願いいたします。

**Comment by wf9a5m75** [comment]
ありがとうございます。大切に使わせていただきます。
