### ISSUE TITLE
Version 2.0 Beta need to add kml layer. Please help me

### ISSUE THREAD

**Issue by shrijan** [mapsplugin/cordova-plugin-googlemaps#1608]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[x] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
I know, sorry. Not ready yet.

**Comment by shrijan** [comment]
Hey if i put bounty on it what will be your target. I desperately need that feature. I am upgrading from v1.  Thanks

**Comment by Julieng50** [comment]
Hi !
Do you have a date or an advancement to give us on that feature ?
I really need that feature too, but I would like to know if I should waiting for it or not ?

Thanks :)

**Comment by wf9a5m75** [comment]
Nop

**Comment by shrijan** [comment]
Hi,

Just checking if this is available in version 2. Thanks

**Comment by wf9a5m75** [comment]
Not yet.

**Comment by shrijan** [comment]
Hi Masashi,

My project is heavily based on kml layer. So can please let me know way to install over version of plugin. 

Thanks

**Comment by wf9a5m75** [comment]
Could you search on the web at first?
https://stackoverflow.com/questions/21391431/can-i-install-a-previous-version-of-a-plugin-using-the-cordova-plugin-add-comman

**Comment by shrijan** [comment]
Thanks, i thought there might be different way to install.

**Comment by wf9a5m75** [comment]
@shrijan Thank you for waiting. I tentatively implemented `map.addKmlOverlay()` method for Android.
Only Android is available at this time.

In order to use this feature, please install the plugin from multiple_maps branch.
Please try it, and please give me feedbacks.
Thanks.

```js
map.addKmlOverlay({
  url: "./polygon.kml"
}, function(kmlOverlay) {

  map.moveCamera({
    target: kmlOverlay.viewport
  });

  var removeBtn = document.getElementById("removeBtn");
  removeBtn.addEventListener("click", function() {
    kmlOverlay.remove();
  }, {
    once: true
  });
});
```

**Comment by shrijan** [comment]
Do you have timeframe for ios. 80pc of our app user are ios. Thanks

**Comment by shrijan** [comment]
Also, I currently using plugin version 1.4.3. My app is heavily based on kml layer. 
I just upgraded to ios 11 and my app crash on opening page with kmllayer.

**Comment by wf9a5m75** [comment]
No more support v1.4.3

And no ETA is available

**Comment by shrijan** [comment]
Thanks Masashi, I upgraded the app to use v2 and replace kml with polyline. It works fine now.
This is great plugin. Thanks for your time and effort.

**Comment by wf9a5m75** [comment]
The implementation of the kml layer is still on progress.
The method behavior will be changed later, especially iOS.
But you can use the method at least.

**Comment by wf9a5m75** [comment]
update: This has been still working on hardly.

**Comment by wf9a5m75** [comment]
@samedii Finally the kmlLayer is ready to go for Android and iOS.

https://github.com/mapsplugin/v2.0-demo/blob/master/www/KmlOverlay/addKmlOverlay.html

At this time, `kmz` file is not supported. And even one kml file, not all kml tags are supported, such as `<screenoverlay>`.
I will update which tags are available later, but try the demo first.

**Comment by wf9a5m75** [comment]
`KmlOverlay` is finally the General Available.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.2.0/README.md#welcome-back-the-kmloverlay
