### ISSUE TITLE
Tile of Hybrid map is not loading in high zoom level (18)

### ISSUE THREAD

**Issue by fatalcaron** [mapsplugin/cordova-plugin-googlemaps#1610]
**I'm submitting a ...**
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:**
[ ] **1.4.x**
[x] **2.0.0-beta2** 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-googlemaps 2.0.0-beta2-20170731-1540 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.6.5 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
With basemap  MAP_TYPE_HYBRID the tiles of the basemap is not loading when I go to level zoom 18.  Everything seem OK with the road basemap.

![screenshot_20170803-114229](https://user-images.githubusercontent.com/12138642/28930561-5a34683e-7841-11e7-839d-26dd0b247ffa.png)

**Comment by wf9a5m75** [comment]
This plugin does not touch about that. That is a problem of Google Maps Android API v2.

**Comment by fatalcaron** [comment]
Just to clarify the situation, this problem only manifested itself when I upgraded to the version cordova-plugin-googlemaps 2.0.0-beta2. Do you know how I could fix the problem?

**Comment by wf9a5m75** [comment]
Sorry, I don't know.

**Comment by fatalcaron** [comment]
Totally my fault, I had enter bad Google API key for my APP... Thanks for your pluggin, I go to buy you a beer.

**Comment by wf9a5m75** [comment]
Great ;)

Thank you for using the cordova-googlemaps-plugin.
