### ISSUE TITLE
Marker.getPosition() not working

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#1611]
```
marker.addEventListener(GoogleMapsEvent.MARKER_CLICK).subscribe((markerClicked) => {                                  
   let latlng = markerClicked.getPosition().toUrlValue();
   map.setCameraTarget(latlng);
   let newZoom = zoom + 2;
   map.setCameraZoom(newZoom);
  })
```
I get markerClicked.getPosition is not a function. I tried without .toUrlValue() and still same error

**Comment by wf9a5m75** [comment]
@ionic-native/Google Maps plugin is not developed by me, actually by ionic-team.
However, the ionic-team does not check all features deeply.
So there are probably issues. I'm not sure this is a bug or your problem.

I have been working to fix the @ionic-native/Google Maps plugin recently.
I started creating a demo app to check all features works correctly.
But I'm not familiar with ionic.

If you help me on that project, I will help you additional something (give access to marker cluster, or develop DirectionServices).

If you don't want to help me, please wait for a while until I confirm your code.

**Comment by francoro** [comment]
I decide to no implement it in my application this feature.I wish i can help but i am really a beginner-intermediate in JS and i never work on a plugin and also i dont know java. Sorry :(

**Comment by wf9a5m75** [comment]
In that case, I recommend you to use this plugin **without** the ionic-wrapper plugin.

This plugin itself works fine. The problem is @ionic-native/google-maps plugin itself.

So if you write your app with pure JavaScript, your code works fine.

**Comment by francoro** [comment]
I'll keep that in mind. Thanks

**Comment by pavel-kurnosov** [comment]
Your code is wrong: GoogleMapsEvent.MARKER_CLICK event return location not object, that's why you getting markerClicked.getPosition is not a function.
To get what you want you need to have smthng like this: 
```
marker.addEventListener(GoogleMapsEvent.MARKER_CLICK).subscribe((location) => {                                  
   let latlng = marker.getPosition();
  })
```
 So, I think this isssue can be closed.

**Comment by wf9a5m75** [comment]
Actually, the original JS version provides the marker location as the callback argument.

```js
map.addMarker({
  ...
}, function(marker) {

   marker.addEventListener(plugin.google.maps.event.MARKER_CLICK, onMarkerClick);
});

function onMarkerClick(latLng) {
  // the first argument `latLng` is marker.getPosition() value.

  // if you want to manipulate on the marker,
  // you can get marker instance through `this`

  var marker = this;
  marker.setTitle("Hello world");
  marker.showInfoWindow();
}
```

I haven't checked this code works with the ionic wrapper version yet.

**Comment by quanganh206** [comment]
Hi @wf9a5m75,

I can working with you on Ionic2 project to make plugin working better. Please tell me where to begin and timeline so I can arrange my time to working on it.

Regards./.

**Comment by wf9a5m75** [comment]
You can use this plugin without the ionic wrapper plugin.
Many people do this.

The current ionic wrapper plugin has lots of bug. I recommend you use this plugin without the ionic wrapper plugin.

**Comment by quanganh206** [comment]
No @wf9a5m75 

I mean that 

I have been working to fix the Maps plugin recently.

> I started creating a demo app to check all features works correctly.
> But I'm not familiar with ionic.
> If you help me on that project...

I can working with you and contribute on that project. Ionic or without Ionic no problem.

**Comment by wf9a5m75** [comment]
Please contact to me by e-mail
