### ISSUE TITLE
Current location marker is invisible if myLocationButton is false

### ISSUE THREAD

**Issue by stalniy** [mapsplugin/cordova-plugin-googlemaps#1612]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[x] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-googlemaps 2.0.0-beta3-20170803-0000 "cordova-plugin-googlemaps"
cordova-plugin-safariviewcontroller 1.4.7 "SafariViewController"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
if `myLocationButton` is `false` then user is not able to detect own location via custom html button.

**Expected behavior:**
Provide additional option which enables tracking of current location but doesn't show button `controls.myLocation = true`

**Steps to reproduce:**
* create a map and specify `controls.myLocationButton = false`

I can work on PR if you are ok with option name

**Comment by wf9a5m75** [comment]
Long long long time ago, I decided this plugin provides the myLocation button assigned with the blue dot.

Because there were no way to show only the myLocation button in Android.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/266#issuecomment-63118586

**Comment by stalniy** [comment]
as I understood you didn't implement this feature because in android you can't enable location button with disabled location tracking, correct?

If so, then I don't think it's a valid use case. 

## Suggestion
1. Have 2 options: `myLocationButton`, `myLocation`
2. if `myLocationButton: true`, plugin shows button and ignores `myLocation` setting and set it to `true`
3. if `myLocationButton: false`, plugin doesn't show button and looks for `myLocation` option
4. if `myLocation: false` and `myLocationButton: false`, location tracking is disabled

and that's it. I already have a working android version

**Comment by wf9a5m75** [comment]
>if myLocationButton: true, plugin shows button and ignores myLocation setting and set it to true

This behavior leads lots of people confuse.

**Comment by stalniy** [comment]
frankly speaking I don't think that people will use native button at all :) because it's impossible to change its look and feel. So, I don't think that it will and it can be clearly written in docs

**Comment by stalniy** [comment]
I created this issue just because I don't want to be bothered by current user location marker functionality but want to have a custom location button which I can put where I want and style as I want. This is just a guess but I believe this will be the main use case for this

**Comment by wf9a5m75** [comment]
> it can be clearly written in docs

I believe most of users of this plugin do not read the document deeply.
(I feel everyday)
Little number of people read the documents deeply (like you).
And very small number of people read in native side code.

So I don't want to implement the feature that has possibility to lead confuse.
(Because asking basic questions are stressful for me)

----------

I understand your point. But I don't want to do that at this time.
I haven't checked the behavior of the Android myLocation button recently, but I think Google does not change it.
In that case, I need to implement a custom my location button instead of native my location button.

Technically, not so difficult. But I'm terrible busy recently.
Actually this plugin project affects my real job and private time.
So I don't want to add additional work at this time.

-----

Want to implement custom my location button is just your persistence.
Not critical problem (such as crash app).
So your feature request is low priority at this time.

----

By the way, you can hide the button covering another DOM element.
This plugin considers the z-index property of CSS (as you may know)

```html
<div id="map" style="position:relative;z-index:0">
<button style="position:absolute;z-index:10;right:50px;top:50px;">MyCustomButton</button>
</div>
```

**Comment by stalniy** [comment]
I can hide but:
* android and iOS have this button in different place and different size
* I want to place button in different place

So, not that simple. Also I don't think this is minor issue because for projects who care about brand identity and design this may be a problem.

Anyway I understand why you don't want to spend time on this right now, thus I will proceed with my fork. Let me know when you change your mind or implement it in different way

**Comment by wf9a5m75** [comment]
Thank you for understanding.
Yes, I know what your point is. But not this time unfortunately.
Sorry about that.

I close this thread at once, but you can reply to here anytime.

**Comment by OmerCora** [comment]
This method should be exposed I believe. There is no reason anyone would get confused over two simple different methods? 

(Also getting confused sounds a lot better than getting frustrated over a feature that would at most take 9.5 seconds to develop on a platform natively.)

**Comment by jsdussanc** [comment]
If it is very annoying, I will be hoping that you can hide the button but leave the point of my location

**Comment by wf9a5m75** [comment]
**update**
The v2.2.0 allows you to control the myLocationButton and the myLocation (blue dot) separately.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.2.0/README.md#the-mylocation-property-is-changed

**Comment by kapilSoni101** [comment]
@wf9a5m75:- sir i am using google maps 2.4.4 verion but in my case location button is not display in the map i don't understand why dont show sir.what the problem sir?
