### ISSUE TITLE
Plugin not working for iOS 10.3

### ISSUE THREAD

**Issue by lhsantos** [mapsplugin/cordova-plugin-googlemaps#1619]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X] any problem or bug report
[ ] feature request

I'm submitting this because I've spent the last 3 days trying to solve this, and no solution on google works for me. I'm absolutely sure my API key is OK, I generated a new key 3 times to test, before giving up, I also generated a key for Android and it works perfectly.

**plugin version:**  (check one with "x")
[X ] **1.4.x**
[X] **2.0.0-beta2** 

(I tested with both, neither works)

**cordova information:**  (run `$> cordova plugin list`) 

cordova 6.5.0 + ionic 3.7

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 1.4.3 "cordova-googlemaps-plugin"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
Blank screen.

**Expected behavior:**
Map loaded

**Steps to reproduce:**
Create a blank ionic app and use the tutorial code for Google Maps Plugin Ionic (https://ionicframework.com/docs/native/google-maps/):
run ionic start myapp blank
install plugin
build+run on ios

Home.ts
```
import {AfterViewInit, Component} from '@angular/core';
import {
  CameraPosition,
  GoogleMap,
  GoogleMaps,
  GoogleMapsEvent,
  LatLng,
  Marker,
  MarkerOptions
} from '@ionic-native/google-maps';


@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage implements AfterViewInit {

  constructor(private googleMaps: GoogleMaps) {
  }

  // Load map only after view is initialized
  ngAfterViewInit() {
    this.loadMap();
  }

  loadMap() {
    // make sure to create following structure in your view.html file
    // and add a height (for example 100%) to it, else the map won't be visible
    // <ion-content>
    //  <div #map id="map" style="height:100%;"></div>
    // </ion-content>

    // create a new map by passing HTMLElement
    let element: HTMLElement = document.getElementById('map');

    let map: GoogleMap = this.googleMaps.create(element);

    // listen to MAP_READY event
    // You must wait for this event to fire before adding something to the map or modifying it in anyway
    map.one(GoogleMapsEvent.MAP_READY).then(
      () => {
        console.log('Map is ready!');
        // create CameraPosition
        let position: CameraPosition = {
          target: new LatLng(43.0741904, -89.3809802),
          zoom: 18,
          tilt: 30
        };

        // move the map's camera to position
        map.moveCamera(position);

        // create new marker
        let markerOptions: MarkerOptions = {
          position: <LatLng>position.target,
          title: 'Ionic'
        };

        map.addMarker(markerOptions).then((marker: Marker) => {
          marker.showInfoWindow();
        });
        // Now you can add elements to the map like the marker
      }
    );
  }
}
```

Home.scss
```
page-home {
  #map {
    position: fixed;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
    z-index: 100;
  }
}
```

Home.html
```
<ion-content>
  <div #map id="map"></div>
</ion-content>
```

**Related code, data or error log (please format your code or data):**
The only hint I have is the error message on XCode log:
```
>> libMobileGestalt MobileGestaltSupport.m:153: pid 575 (MyApp) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
>> libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)
```

People have reported this on StackOverflow, but everything I found on Google still doesn't work. Apparently it's an issue introduced with the latest version of iOS:
https://stackoverflow.com/questions/43197726/mobilegestalt-no-access-to-inversedeviceid

**Comment by wf9a5m75** [comment]
May be this answer?

https://stackoverflow.com/a/43848098/697856

**Comment by lhsantos** [comment]
@wf9a5m75 I tried that one, but ionic doesn't use bower for anything, the command returns an error...

**Comment by wf9a5m75** [comment]
I see. By the way, why do you use the plugin v1.4.3?
The current ionic wrapper plugin supports **only** v2.0-beta.

**Comment by lhsantos** [comment]
@wf9a5m75 I tried with both, maybe at this setting I pasted the version is wrong, but the first test I made was with the lastest version of the wrapper, the plugin and the ionic native package. I will test again, today and send the results.

**Comment by wf9a5m75** [comment]
Well, the current ionic-wrapper plugin has lots of bugs. I recommend you write your code with only pure JS code.

**Comment by lhsantos** [comment]
OK, now it's working. I'm still not sure about the reason it wasn't on my other tests, but I think earlier my code was creating the map before the platform.ready() event. The documentation (and the example) on ionic's page doesn't do that, it uses AfterViewInit, while the documentation for the plugin here at github clearly states that problem, but I hadn't found that section until this morning. Thank you for the help and sorry for the trouble!
