### ISSUE TITLE
Question: Can I create custom overlay and use d3.js?

### ISSUE THREAD

**Issue by stripathix** [mapsplugin/cordova-plugin-googlemaps#1620]
I am asking a question.

Can a custom overlay be created and shapes can be drawn on that using d3.js. I have to draw different shapes like rectangles, arcs, circles etc on google map at different locations.

Something like this
<img width="583" alt="screen shot 2017-08-06 at 8 21 20 pm" src="https://user-images.githubusercontent.com/8480351/29004451-dc524c64-7ae4-11e7-8112-19eb504c7774.png">

I got this working with GoogleMap JS API but there is a big issue with JS google map api of crashes due to memory leaks.

**Comment by wf9a5m75** [comment]
If you don't use the map camera tilt or bearing, it's almost the same as the google maps JavaScript api v3.

This plugin recognizes the z-index. 
So you can overlay any HTML elements on the map.

But I haven't checked with d3.js
Please play with the map before using this plugin in your product app.

**Comment by stripathix** [comment]
@wf9a5m75  So I can append HTML objects over it :-).

Will those HTML elements rendered inside map? Like can I tell at what lat/lng those html elements will be positioned and will it also manage zoom +/-?
**For example:** If I draw some HTML over Point A, B, C, D and zoomIn to point B, then Point A, C and D will auto get out of the view area?

**Comment by wf9a5m75** [comment]
no.

The map view is not a HTML element. You can not display any html elements inside the map except HTMLInfoWindow.

**Comment by wf9a5m75** [comment]
You can draw rectangles, arcs, circles using this plugin methods by the way.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

**Comment by wf9a5m75** [comment]
This plugin works like this:
https://user-images.githubusercontent.com/167831/28292982-910af668-6b06-11e7-933e-42311a58e64e.png

In the above picture, the fixed header is an html element (div, `position: fixed; z-index:100` etc).
But the map view is not HTML element. It is placed **under the browser**.

So you can put any HTML elements (such as button), and cover on the map (such as dialog), but you  can not insert any HTML elements in the map.
