### ISSUE TITLE
When set icon with custom dataurl, map.clear() does not fire callback.

### ISSUE THREAD

**Issue by lpikora** [mapsplugin/cordova-plugin-googlemaps#1621]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**cordova information:**

```
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.0-beta3-20170805-2349 "cordova-plugin-googlemaps"
cordova-plugin-ios-camera-permissions 1.1.1 "iOS Permissions"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
Using custom data uri icon for markers cause not fire map.clear() methods callback.

**Expected behavior:**
map.clear() callback function should fire when using custom icons wit data uri

**Steps to reproduce:**
Add marker with custmo data uri icon.
use method map.clear()

**Related code, data or error log (please format your code or data):**

```
          position: { lat: poi.geometry.coordinates[1], lng: poi.geometry.coordinates[0] },
          icon: {
            url: '"data:image/png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==',
            size: {
              width: this._poiIconService.width,
              height: this._poiIconService.height
            }
          }
...
this.map.clear(() => {
        // not fired
      });
```

**Comment by wf9a5m75** [comment]
Android or iOS?

**Comment by wf9a5m75** [comment]
And please do not omit your code with `...`

**Comment by lpikora** [comment]
Android

**Comment by lpikora** [comment]
This commit works as I expect: 12266a6 But the latest one don't work.. I'll try figure out which commit broke it.

**Comment by wf9a5m75** [comment]
It seems you use the @ionic-native/google-maps plugin.

Since the wrapper plugin is written `clear(): Promise<any> { return; }`,
your code has to use `then`

```
this.map.clear().then(() => {

});
```
https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/google-maps/index.ts#L1258

**Comment by lpikora** [comment]
It was not related with Ionic Native plugin but side effect of https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1622 bug somehow in my app. It's ok after fix.
