### ISSUE TITLE
Custom dimensions of markers data uri icon should work.

### ISSUE THREAD

**Issue by lpikora** [mapsplugin/cordova-plugin-googlemaps#1622]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**cordova information:**

```
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.0-beta3-20170805-2349 "cordova-plugin-googlemaps"
cordova-plugin-ios-camera-permissions 1.1.1 "iOS Permissions"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

```

**Current behavior:**
Setting width and heigth of icon when adding marker not apply when using icon with data uri. Icon is rendered in original dimensions.

```
icon: {
            url: '"data:image/png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==',
            size: {
              width: 10,
              height: 10
            }
          }
```

**Expected behavior:**
Icon should render with custom dimensions.

**Steps to reproduce:**
set size object in icon config object when adding marker to map.

**Comment by wf9a5m75** [comment]
Android or iOS?

**Comment by lpikora** [comment]
Android

**Comment by lpikora** [comment]
This commit works as I expect: https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/12266a62dd4f9fabb9b2d270dcc715a02b8a40ed But the latest one don't work.. I'll try figure out which commit broke it.

**Comment by wf9a5m75** [comment]
Thank you for letting me know. I appreciate if you try commits one by one, then find out which commit causes your problem.

**Comment by wf9a5m75** [comment]
Okay, I found the problem code and fix it.

**Comment by lpikora** [comment]
It's fixed now, thank you.
