### ISSUE TITLE
LatLng.toUrlValue and LatLng.toString return different values in v2

### ISSUE THREAD

**Issue by halyburton** [mapsplugin/cordova-plugin-googlemaps#1625]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ X] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[X ] **2.0.0-beta3** 

**cordova information:**  (run `$> cordova plugin list`) 

```
only relates to this plugin
```

**Current behavior:**
Starting in v2, the LatLng.toUrlValue and LatLng.toString methods both return JSON object string.
```javascript
/**
 * @method
 * @return {String} latitude,lontitude
 */
self.toString = function() {
    return "{\"lat\": " + self.lat + ", \"lng\": " + self.lng + "}";
};

/**
 * @method
 * @param {Number}
 * @return {String} latitude,lontitude
 */
self.toUrlValue = function(precision) {
    precision = precision || 6;
    return "{\"lat\": " + self.lat.toFixed(precision) + ", \"lng\": " + self.lng.toFixed(precision) + "}";
};
```
**Expected behavior:**
Return a string like <v2. The LatLng.toUrlValue and LatLng.toString methods both return a comma separated string. 
```javascript
/**
 * @method
 * @return {String} latitude,lontitude
 */
self.toString = function() {
    return self.lat + "," + self.lng;
};

/**
 * @method
 * @param {Number}
 * @return {String} latitude,lontitude
 */
self.toUrlValue = function(precision) {
    precision = precision || 6;
    return self.lat.toFixed(precision) + "," + self.lng.toFixed(precision);
};
```
**Steps to reproduce:**
```javascript
var x = map.getVisibleRegion().northeast.toUrlValue();
```

I am not sure if this change was intended or not, but it should be at least documented when upgrading from v1 to v2. 

----

**Comment by wf9a5m75** [comment]
Sorry, but not acceptable. This is just your request.
There are already lots of users, and some users use current behavior.
Changing output format breaks their code.
That's why this is not acceptable.

**Comment by wf9a5m75** [comment]
You just do `latLng.lat + "," + latLng.lng` in your code.

**Comment by halyburton** [comment]
Thanks, I already worked around this in my code. However it should be noted as breaking change when migrating from v1, plus your method documentation should be updated to reflect the proper expected return value.

**Comment by wf9a5m75** [comment]
I work on a lot of things, so I don't remember all of things.

If you find any missing things for migrating from v1 to v2, please send me pull requests.
This is really appreciate for me and for everyone.
