### ISSUE TITLE
Marker custom styles ignored in iOS

### ISSUE THREAD

**Issue by halyburton** [mapsplugin/cordova-plugin-googlemaps#1626]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ X] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ X] **2.0.0-beta3** 

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.0.0-beta3-20170803-1233 "cordova-plugin-googlemaps"
```

**Current behavior:**
Custom styles for Marker windows are not getting applied in iOS. Issue related to any style added.

**Expected behavior:**
Custom styles get applied to the Marker window.

**Steps to reproduce:**
Add a custom styles to the marker, e.g. 'text-align': 'center'
```javascript
map.addMarker({
            'position': new plugin.google.maps.LatLng(43.230293, -87.984200),
            'disableAutoPan': true,
            'title': 'Test Marker',
            'styles': {
                'text-align': 'center'
            });
```

The problem is the property marker reference. The properties key for the dictionary is looking for the key:
```
"marker_property_6180629808" =     {
        disableAutoPan = 1;
        styles =         {
            "text-align" = center;
        };
    };
```
but the objects dictionary only has a key for
```
"marker_property_marker_6180629808" =     {
        disableAutoPan = 1;
        styles =         {
            "text-align" = center;
        };
    };
```

If I make these changes the issue is fixed. 

```objective-c
// GoogleMapsViewController.m

// replace references of
NSString *markerPropertyId = [NSString stringWithFormat:@"marker_property_%lu", (unsigned long)marker.hash];

// with 
NSString *markerPropertyId = [NSString stringWithFormat:@"marker_property_%@", marker.userData];
```
and 

```objective-c
// PluginMarker.h

// replace references of
NSString *propertyId = [NSString stringWithFormat:@"marker_property_%lu", (unsigned long)marker.hash];
// with
NSString *propertyId = [NSString stringWithFormat:@"marker_property_%@", marker.userData];
```

The key with double "marker" in the name seems wrong to me, but it could be needed for some of the references to clustering i see. I can submit a pull request for the above fixes if thats how you want it fixed.

**Comment by wf9a5m75** [comment]
Thank you for letting me know, and your inspection.
The plugin does not use the `marker.hash` anymore, but it seems there were still remained.
So I replaced all `marker.hash` with `marker.userData`.
