### ISSUE TITLE
Problem: getVisibleRegion() in GoogleMap class, wrong return

### ISSUE THREAD

**Issue by NicolasBehra** [mapsplugin/cordova-plugin-googlemaps#1631]
Hi, hope it won't disturb you,

**I'm submitting a problem or a bug report

**plugin version:**
**2.0.0-beta2** 

It's about the ``` getVisibleRegion() ``` method in the ``` GoogleMap ``` class, 

This method is written in the code as she should return a ```VisibleRegion``` object, 

```
/**
* Get the current visible region (southWest and northEast)
* @return {VisibleRegion}
*/
getVisibleRegion(): VisibleRegion;
```

but the current behaviour is that she finally return a ```LatLngBounds``` object.

Isn't there any problem here?

Thank you very much for your help.

**Comment by wf9a5m75** [comment]
In order to keep backward compatibility, 
code returns different way.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Map.js#L617


You should check the code before posting.

**Comment by NicolasBehra** [comment]
Thanks a lot to answer me,
Here is a sample code that doesn't work,
```
let map: GoogleMap = new GoogleMap(mapId, googleMapOptions);
let latLngBounds: LatLngBounds = map.getVisibleRegion();
```
but this code below work
```
let visibleRegion: VisibleRegion = map.getVisibleRegion();
```
and when i try to display it in console like below
```
let visibleRegion: any = map.getVisibleRegion();
console.log("visibleRegion", visibleRegion);
```
it returns me a LatLngBounds object

Hope you understand what I mean, and I looked carefully to the code,
Of course when i declare the variable as ```any``` it works, but I like to put the right Type...
Sorry to take your time

**Comment by wf9a5m75** [comment]
This code is strange.
```js
let map: GoogleMap = new GoogleMap(mapId, googleMapOptions);
let latLngBounds: LatLngBounds = map.getVisibleRegion();
```

You have to wait the MAP_READY event.
```js
let map: GoogleMap = new GoogleMap(mapId, googleMapOptions);
map.one(GoogleMapsEvent.MAP_READY).then(() => {
  let latLngBounds: LatLngBounds = map.getVisibleRegion();
});
```

And the ionic wrapper plugin returns the value as LatLngBounds.
The current ionic wrapper plugin has lots of problem (and not developed by me).

If you are **really** important the value, you should not use the ionic wrapper plugin at this time.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/8ad7d124b5629095e4562ecb2b248c777a4a4be6/v2.0.0/For-ionic2-users/README.md

**Comment by NicolasBehra** [comment]
Thanks
I didn't put the ready part to not complicate the code,
Sorry for disturbing and maybe I don't used the good beta version,
I don't annoy you anymore
Have a great day.

**Comment by wf9a5m75** [comment]
Thank you for using this plugin.

**Comment by mesutcakir** [comment]
Its Work but, use must Observable or Promise 
![image](https://user-images.githubusercontent.com/4125460/41469041-928b5992-70b4-11e8-8237-41ff4f612f10.png)
