### ISSUE TITLE
Change htmlinfowindow on marker based on user action on button

### ISSUE THREAD

**Issue by archito2** [mapsplugin/cordova-plugin-googlemaps#1634]
Hi all & @wf9a5m75 , 

I have a situation where im creating  no. of markers and each marker has its infowindow (containing button for user action). Now based  on user action i want to change the infowindow button value and count value i.e a label in infowindow. When im calling my createinfowindow function again based on click of that button by user it executes the function with updated values from my backend server but then when i again click on the marker on the map it opens the previous infowindow containing previous values. As the marker is bound to that at the start. 
Appreciate any advice/help to overcome this.

**Comment by wf9a5m75** [comment]
You have to do `infoWindow.setContent()` again.

**Comment by wf9a5m75** [comment]
The plugin does not take care of the contents at all.
I don't know how do you set the contents, such as HTML strings or DOM element, but you have to manage it by yourself.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/HtmlInfoWindow.js

**Comment by archito2** [comment]
i kind of tried that with using jQuery html property of that label but when i close and reopen that infowindow an earlier instance is loaded i.e having previous values due to on click bound to marker right?? I dont have the instance of the marker in which this button  was clicked to use the infowindow setcontent.
I am using a createwindow func to create window and its content is created as below
     var html = '<b>Creator</b> '+ value.Creator+
      <label id="lblid1">'+value.Required+'</label>'+
      '<br><b>Date</b> '+value.data+
      '<br><b>Time</b> '+value.time+
       <br><input id = "chatbtnid" value="True for eg" type="button" onclick="trueevent">

So when i click this true button it updates the db and based on response if success it should become false. So on next click of that marker the false button and its updated value should be loaded in the htmlinfowindow this is also executed in create window event but based on the values the true or false button part is loaded based on if else.

**Comment by wf9a5m75** [comment]
This is the very common mistakes for JS beginners.

I guess you write your code something like this:

```
data.forEach(function(markerOpts) {
   map.addMarker(markerOpts, function(marker) {
       marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
           var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();
           htmlInfoWindow.setContent("<button onclick='onButtonClick(" + markerOpts.myId + ")'>button</button>");
           htmlInfoWindow.open(marker);
       });
   });
});
function onButtonClick(myId) {
  
}
```

Write your code more smart:

```js
var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();

data.forEach(function(markerOpts) {
   map.addMarker(markerOpts, function(marker) {
       marker.on(plugin.google.maps.event.MARKER_CLICK, onMarkerClick);
   });
});

function onMarkerClick() {
  var marker = this;

  var myHtml = document.createElement("div");
  myHtml.innerHTML = "<button>button</button>";
  var button = myHtml.getElementsByTagName("button")[0];
  button.addEventListener("click", function() {
     
     dbUpdate({
        myId: marker.get("myId")
     }, function() {
        button.innerText = "clicked!");
        htmlInfoWindow.setContent(myHtml);
        htmlInfoWindow.open(marker);
     });

  });
  htmlInfoWindow.setContent(myHtml);
  htmlInfoWindow.open(marker);
}
```

**Comment by archito2** [comment]
And if i try to pass the marker instance when inside the callback function of addmarker by sending onclick=trueevent(marker) i am getting [object object] in the true event function. So not getting the instance of wother the infowindow or the marker.

**Comment by wf9a5m75** [comment]
```
onclick=trueevent(marker)
```

Did you consider why you get `[object object]` ?

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since this is not bug, I close this issue thread. But you can still reply to this thread.
If you reply with enough information, I reply to your comment.
