### ISSUE TITLE
Google Map shows black screen when click on sliding menu.

### ISSUE THREAD

**Issue by Sagarjai33** [mapsplugin/cordova-plugin-googlemaps#1635]
I am developing an app using cordova-plugin-googlemap. Map works fine but when i click on sliding menu map shows black screen. See below-

Before click -
![image](https://user-images.githubusercontent.com/28764911/29243070-3e842ce4-7fb4-11e7-8461-51ab40004ffb.png)

OnClick  -
![image](https://user-images.githubusercontent.com/28764911/29243082-85c1b748-7fb4-11e7-966d-977dcf588f5a.png)

After click on sliding menu -
![image](https://user-images.githubusercontent.com/28764911/29243061-0e65ccac-7fb4-11e7-8ac9-be31d6d7e36a.png)

Code is written below -
[index.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1219993/index.txt)

Please someone help to solve this issue.Thanks in advance for your help and cooperation.

@wf9a5m75

**Comment by wf9a5m75** [comment]
I guess some css blocks like that.

Check your(or framework) css

**Comment by wf9a5m75** [comment]
I recommend you don't modify CSSs around the map div.

**Comment by Sagarjai33** [comment]
Hi Masashi,

Problem is resolved now,the issue is due to sliding menu type. i just change it to type="push" its start working properly.

Thanks for you coordination.

**Comment by wf9a5m75** [comment]
Thank you for letting me know.
