### ISSUE TITLE
Google map freezes sometime directly after starting.

### ISSUE THREAD

**Issue by Sagarjai33** [mapsplugin/cordova-plugin-googlemaps#1636]
I am developing an app using cordova-plugin-googlemap. Map works fine but some time it freezes and not allow to drag marker,slide map and other event.

Code is written below -
[drag.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1220486/drag.txt)

Please someone help to solve this issue.Thanks in advance for your help and cooperation.

@wf9a5m75

**Comment by wf9a5m75** [comment]
Please share your project files on github.
Not just html, but also css, js framework, everything.

**Comment by Sagarjai33** [comment]
Hi ,
PFA.
Attached is the source code of the project. i used onsenui and monaca IDE to develop this project.

[map check.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1222908/map.check.zip)

**Comment by wf9a5m75** [comment]
git please ....

**Comment by wf9a5m75** [comment]
Let me confirm one thing. Do you really use the latest version?
I guess you download the maps plugin, and upload it to the monaca.
In this case, you use old version.

I recommend you install the plugin using URL, not uploading.

**Comment by Sagarjai33** [comment]
i used URL to install Plugin in monaca

URL is "https://github.com/mapsplugin/cordova-plugin-googlemaps.git"

**Comment by wf9a5m75** [comment]
Do you mean you use the v1.4? Since you don't specify the `#multiple_maps` branch.

**Comment by Sagarjai33** [comment]
yes i used V1.4

**Comment by wf9a5m75** [comment]
I see. The v1.4 will be shutdown soon. Please use the v2.0.

**Comment by Sagarjai33** [comment]
is this issue due to version ? 
if yes then please provide v2.0  link which i can use to import plugin in monaca.

**Comment by wf9a5m75** [comment]
In order to use the v2.0 in monaca, just specify `https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps`

**Comment by wf9a5m75** [comment]
I will shutdown the v1.4 at least in this month.

**Comment by Sagarjai33** [comment]
ok
 Thanks for you help.i will update the version and let you know the status about this issue.

**Comment by wf9a5m75** [comment]
![screen shot 2017-08-14 at 10 55 33 am](https://user-images.githubusercontent.com/167831/29284341-2191da6a-80df-11e7-8e18-3f451d9e4514.png)

----
**tips**

Download the master.zip from this repository.
https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk

Then upload it to the monaca. This saves the build time even if you use only Android.

**Comment by Sagarjai33** [comment]
Thank You so much.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update, I close this issue.

**Comment by gfavour** [comment]
Please am using ionic 4 and building android phone. The same thing happens to me on android phone but on browser it works perfectly.
This is my ionic info
`
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (C:\Users\Progmatech\AppData\Roaming\n
pm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-i
onic-webview 2.3.2, (and 11 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\android-sdk)
   NodeJS            : v10.14.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 7
`

This is my dependencies;

`"private": true,
  "dependencies": {
    "@angular/animations": "^7.2.4",
    "@angular/common": "~7.1.4",
    "@angular/core": "~7.1.4",
    "@angular/forms": "~7.1.4",
    "@angular/http": "~7.1.4",
    "@angular/platform-browser": "~7.1.4",
    "@angular/platform-browser-dynamic": "~7.1.4",
    "@angular/router": "~7.1.4",
    "@ionic-native/background-geolocation": "^5.0.0",
    "@ionic-native/call-number": "^5.0.0-beta.24",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/diagnostic": "^5.0.0",
    "@ionic-native/geolocation": "^5.0.0",
    "@ionic-native/google-maps": "^5.0.0-beta.26",
    "@ionic-native/http": "^5.0.0-beta.23",
    "@ionic-native/in-app-browser": "^5.0.0",
    "@ionic-native/native-audio": "^5.4.0",
    "@ionic-native/native-geocoder": "^5.0.0",
    "@ionic-native/network": "^5.0.0-beta.22",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-rc.0",
    "@ionic/storage": "^2.2.0",
    "call-number": "1.0.1",
    "cordova-android": "^7.1.4",
    "cordova-browser": "5.0.4",
    "cordova-custom-config": "^5.0.2",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-geolocation": "4.0.1",
    "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
    "cordova-plugin-inappbrowser": "3.0.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.3.2",
    "cordova-plugin-mauron85-background-geolocation": "3.0.0-alpha.50",
    "cordova-plugin-nativeaudio": "3.0.9",
    "cordova-plugin-nativegeocoder": "3.1.3",
    "cordova-plugin-paystack": "git+https://github.com/tolu360/cordova-plugin-paystack.git",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova.plugins.diagnostic": "4.0.10",
    "core-js": "^2.5.4",
    "mx.ferreyra.callnumber": "~0.0.2",
    "paystackcordovav2": "git+https://github.com/mrfoh/paystackcordovav2.git",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"
  },`
