### ISSUE TITLE
Wrong zoom after moveCamera when the map is hidden

### ISSUE THREAD

**Issue by xloading** [mapsplugin/cordova-plugin-googlemaps#1638]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ x] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.2.0-fixed "Google Maps SDK for iOS"
cordova-custom-config 3.1.4 "cordova-custom-config"
cordova-fabric-plugin 1.1.7 "cordova-fabric-plugin"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-globalization 1.0.5 "Globalization"
cordova-plugin-googlemaps 2.0.0-beta2-20170625-1805 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova.plugins.diagnostic 3.5.0 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
In my app I allow users to switch between different locations (i.e. cities) and when they do it the map is cleared of old markers, markers for the new location are set and the map is moved to the new location.
This is always initiated through autocomplete dialog (https://github.com/guylabs/ion-autocomplete), but two scenarios are possible: map can be present on the screen after the new location is selected or it can be hidden (with "ng-show") when the app is in "list mode" (vs. "map mode").
In any case this is the code invoked after setting all the markers:
```js
var latLngBounds = new plugin.google.maps.LatLngBounds($rootScope.latLng);

        if($rootScope.latLng.length > 0) {
          console.log('Before camera moved 1');
          console.log(latLngBounds);
          map.moveCamera({
            'target': latLngBounds
          }, function () {
            var cameraPosition = map.getCameraPosition();
            console.log(cameraPosition);
            console.log("zoom: " + map.getCameraZoom());
            if (zoomOut == 1) {
              map.setCameraZoom(Math.floor(cameraPosition.zoom - zoomOut));
            }
            console.log('Camera moved 1');
          });
        }
```
For some reason behavior of moveCamera for these two cases differs:
* when the map is shown then targeting to latLngBounds goes well and zoom is appropriate;
* when the map is hidden zoom is at much lower level (showing much larger piece of map), even though the objects in latLngBounds are exactly the same.

**Expected behavior:**

The zoom should be the same for both cases.

**Steps to reproduce:**
I have already shared the guidelanceapp repo on Bitbucket with you earlier ;)

**Screen capture or video record:**
https://youtu.be/pzH-Tfk1BxU

**Related code, data or error log (please format your code or data):**
Here is the console log example:
![wrong_map_zoom](https://user-images.githubusercontent.com/1406364/29267702-7a1ac0bc-80f2-11e7-968d-5103cd246e1f.png)
(the same LatLngBounds are highlighted with blue, different cameraPosition/zoom after moveCamera are highlighted with red)

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
Since you use very old version, you should try the latest version at least before posting here.

**Comment by wf9a5m75** [comment]
And the plugin is not designed for your case. Please change the zoon with visible map.

**Comment by xloading** [comment]
Hi @wf9a5m75 
Thanks a lot for the prompt answer, as I understood this case doesn't look to be fixed anywhere soon.

Regarding the version to be honest I'm somewhat afraid to update to the latest versions of plugin since this left me with bunch of issues earlier and I'm too close to production already being confident about the plugin's version I use.
Therefore I would prefer to wait for stable v2 version first and then update the plugin.

Thank once again!

**Comment by wf9a5m75** [comment]
Ok. Thank you for letting me know.

Yes, I apologize too many updates. `2.0.0-beta2-20170625-1805` is suitable for you is fine.
But I also fixed lots of problems.
I recommend you try the latest version **after** you release your app.
