### ISSUE TITLE
Polygon with hole

### ISSUE THREAD

**Issue by shrijan** [mapsplugin/cordova-plugin-googlemaps#1641]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[x ] **1.4.x**
[x ] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**Current behavior:**

**Expected behavior:**

How i can i achieve polygon hole with plugin v1 or v2. For example
[https://developers.google.com/maps/documentation/javascript/examples/polygon-hole](url)

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```

----
Thanks
If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
I appreciate if you search in the document before asking.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Polygon/setHoles/README.md

**Comment by shrijan** [comment]
Thanks

**Comment by shrijan** [comment]
Hi Masashi,

Sorry to trouble you again.

Is there anyway to find if lat/long is within a set of polygons.

I used javascript polygon.contains to check it before

Thanks
Shrijan

**Comment by shrijan** [comment]
Please ignore my email i found the way to do it Thanks
