### ISSUE TITLE
How to install google maps v2 Beta2 instead of Beta3

### ISSUE THREAD

**Issue by Macario** [mapsplugin/cordova-plugin-googlemaps#1643]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ ] **2.0.0-beta2** 
[x] **2.0.0-beta3** 

Hello, I would like to know, how can I install google maps v2 Beta2 instead of Beta3. 

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
Find the commit ID you want to use it, then specify the commit id.

```
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#(commit it)
```
