### ISSUE TITLE
Attempt to remove non-JNI local reference, dumping thread

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1644]
[ ] question
[X ] any problem or bug report
[ ] feature request

[ ] **1.4.x**
[ X] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
com.lampa.startapp 0.1.4 "startApp"
cordova-plugin-add-swift-support 1.6.2 "AddSwiftSupport"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-geofence 0.6.0 "geofence"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta2-20170705-1715 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
es6-promise-plugin 3.0.2 "Promise"
```

**Current behavior:**
i get 5 or 6 lines of
Attempt to remove non-JNI local reference, dumping thread
in the log of android

**Expected behavior:**

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
It's east. Please give u to use this plugin.
That message is not related with this plugin.
