### ISSUE TITLE
Support for fusion tables?

### ISSUE THREAD

**Issue by danielcrk** [mapsplugin/cordova-plugin-googlemaps#1647]
Hi! I hate to put this under Issues since it is just a feature request, but here goes;

Would it be possible to load native maps with prerendered data from fusion tables, just like the google maps javascript api can? I'm not sure if the native maps api supports this or not.

Thanks!

**Comment by wf9a5m75** [comment]
nop

**Comment by wf9a5m75** [comment]
>native maps api supports this or not.

Google does not support it in native.
