### ISSUE TITLE
Google Maps 2.0.0-beta2 + wheelselector-plugin/date-picker

### ISSUE THREAD

**Issue by LeVadim** [mapsplugin/cordova-plugin-googlemaps#1650]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com-sarriaroman-photoviewer 1.1.10 "PhotoViewer"
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-apprate 1.2 "AppRate"
cordova-plugin-camera 2.4.0 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.5 "Globalization"
cordova-plugin-google-analytics 1.7.9 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.0-beta3-20170816-1600 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ios-no-export-compliance 0.0.1 "iOS No Export Compliance"
cordova-plugin-nativeaudio 3.0.8 "Cordova Native Audio"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-touch-id 3.2.0 "Touch ID"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-vibration 2.1.4 "Vibration"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
cordova-plugin-x-socialsharing 5.1.6 "SocialSharing"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.1 "Cordova sqlite storage plugin"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.9.4 "PushPlugin"

```

**Current behavior:**
https://ionicframework.com/docs/native/wheelselector-plugin/
https://ionicframework.com/docs/native/date-picker/
These both 2 plugins does not work at all with new Google Maps version.
The feeling is that those 2 plugins are invisible - finger can't do any tap.

**Expected behavior:**
They should work as they worked in the 1.4 version. 

**Steps to reproduce:**
<!-- Reproduce steps are really important.
Install both plugins with 2.0 google maps version.

**Comment by wf9a5m75** [comment]
I don't support the compatibility with other plugins.

**Comment by LeVadim** [comment]
I thought you would know, probably there is some type of overlay?
Because this is very strange that they stopped working right after updating to Google Maps 2.0.
Would you be able to help here or you want me to close it?

**Comment by wf9a5m75** [comment]
Since inspecting other plugin needs to work a lot, I don't support the compatibility with other plugins.

If the `wheelselector-plugin/date-picker` is html element, I check it. But it uses native view.

Please asks to the `wheelselector-plugin/date-picker` repository.

**Comment by z1ad** [comment]
Hi guys, see pull request to fix this issue

https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/1875
