### ISSUE TITLE
Opening modal on marker click and the map view is occasionally still interactable

### ISSUE THREAD

**Issue by jjw123** [mapsplugin/cordova-plugin-googlemaps#1651]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-firebase 0.1.22 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta3-20170810-1904 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-themeablebrowser 0.2.17 "ThemeableBrowser"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.4 "Launch Navigator"
{}

**Current behavior:**

When clicking on a marker, i have a modal appear (through ionic).

Occasionally, the modal will not be interactable, but the map behind it will be until I click on a part of my app that is not the google maps area. This makes the modal interactable again.

**Expected behavior:**

Clicking on the marker and bringing the modal up should stop all interactions with the map view.

**Steps to reproduce:**
It's very inconsistent in terms of when it appears. 

**Screen capture or video record:**

I'm unable to get this right now, but will be able to tomorrow.

**Comment by wf9a5m75** [comment]
When you open the dialog, you need to execute `cordova.fireDocumentEvent('plugin_touch', {});`.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/whats-new-v2/README.md#change-4-save-battery-life

**Comment by jjw123** [comment]
Thanks a lot, this fixed my issue.

Much appreciated.

**Comment by CesarAPPinheiro** [comment]
Hey guys, I've found the solution!
All you need to do is add:

ionViewWillEnter() {
cordova.fireDocumentEvent('plugin_touch', {});
}

to you "map.ts" page...it simulates a click on the map when the page is about to became active...this is enough to get the map working at 100% width!

=)
