### ISSUE TITLE
I am getting cannot find symbol error

### ISSUE THREAD

**Issue by Krishna25Vrinsoft** [mapsplugin/cordova-plugin-googlemaps#1653]
Error:(1285, 5) error: cannot find symbol class AsyncLicenseInfo
Error:(1285, 40) error: cannot find symbol class AsyncLicenseInfo
In GoogleMaps.java file line no - 1285

I am frequently getting this error and can't run my project.

**Comment by wf9a5m75** [comment]
Duplicate: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1646
