### ISSUE TITLE
Please expose setMyLocationButtonEnabled() method

### ISSUE THREAD

**Issue by ryanhalley** [mapsplugin/cordova-plugin-googlemaps#1656]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[x] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

Currently, setMyLocationEnabled() enables map.setMyLocationEnabled(isEnabled) and map.getUiSettings().setMyLocationButtonEnabled(isEnabled); this means the underlying gps must be enabled, to gain the mylocation button (unless I am mistaken).
Please could you expose setMyLocationButtonEnabled(), so that I can leave setMyLocationEnabled(false). My end objective is to link the location button to a listener, to use my current gps service outside of the map process, so that libgps polling stays disabled.

**Comment by ryanhalley** [comment]
I see, thanks. I can but hope that you maybe find the time at some point to consider implementation; it would be very helpful, as almost all of the work seems to already be done.

**Comment by wf9a5m75** [comment]
**update**
The v2.2.0 allows you to control the myLocationButton and the myLocation (blue dot) separately.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.2.0/README.md#the-mylocation-property-is-changed

**Comment by ryanhalley** [comment]
Thanks for the update!
