### ISSUE TITLE
v2.0 Memory problem 

### ISSUE THREAD

**Issue by rgauthieropenmindt** [mapsplugin/cordova-plugin-googlemaps#1658]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
branch-cordova-sdk 2.6.8 "branch-cordova-sdk"
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-fabric-plugin 1.1.9 "cordova-fabric-plugin"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-app-conversion-tracker 0.0.2 "GoogleAppTracking"
cordova-plugin-googlemaps 2.0.0-beta3-20170820-2025 "cordova-plugin-googlemaps"
cordova-plugin-ios-camera-permissions 1.1.1 "iOS Permissions"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.5 "PushPlugin"
```

**Current behavior:**

I've added your plugin to show a map in my applicationand all the functionnality works fine. But i've discover that if I remove the map before leaving my page and recreate a new one when coming back, after a few times my application would crash.

My guess is that there are some listeners or variables aren't deleted because the loading of the map is slowly taking more time before crahsing. My map contains around 50 markers that have a click event on them. 

I've also tried to delete all listeners on my markers, remove all of them and deleting the map before leaving my page, but my memory doesn't seems to be cleared. Also, the app doesn't crash if there no marker on the map.

Last thing I can think of is that the app is build with ionic1, but i've never had this problem with your version 1.4.x with a similar approach with the maps. 

[app_log_crash.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1239596/app_log_crash.txt)

I'm currently trying to create a prototype, I'll will post below the link when it is done.

Thanks you, if you need other informations, I'll try to answer as soon as possible.

**Comment by wf9a5m75** [comment]
Thank you for sharing the native logs.

Regarding of your log, it seems there was some JS error.
```
08-21 13:04:14.671 22615 22615 I chromium: [INFO:CONSOLE(1)] "TypeError: Cannot read property 'addMarker' of undefined
08-21 13:04:14.671 22615 22615 I chromium:     at f.e.addNewMarker (file:///android_asset/www/js/app.js:28:2569)
08-21 13:04:14.671 22615 22615 I chromium:     at file:///android_asset/www/js/app.js:28:2392
08-21 13:04:14.671 22615 22615 I chromium:     at file:///android_asset/www/js/app.js:1:225854
08-21 13:04:14.671 22615 22615 I chromium:     at f.$eval (file:///android_asset/www/js/app.js:1:233171)
08-21 13:04:14.671 22615 22615 I chromium:     at f.$digest (file:///android_asset/www/js/app.js:1:231743)
08-21 13:04:14.671 22615 22615 I chromium:     at f.$apply (file:///android_asset/www/js/app.js:1:233465)
08-21 13:04:14.671 22615 22615 I chromium:     at o (file:///android_asset/www/js/app.js:1:209304)
08-21 13:04:14.671 22615 22615 I chromium:     at v (file:///android_asset/www/js/app.js:1:211438)
08-21 13:04:14.671 22615 22615 I chromium:     at XMLHttpRequest.b.onload (file:///android_asset/www/js/app.js:1:211984)", source: file:///android_asset/www/js/app.js (1)
```

Then the browser failed to parse JSON
```
08-21 13:04:18.896 24753 24839 W System.err: org.json.JSONException: End of input at character 0 of
08-21 13:04:18.917 24753 24839 W System.err:    at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
08-21 13:04:18.917 24753 24839 W System.err:    at org.json.JSONTokener.nextValue(JSONTokener.java:97)
08-21 13:04:18.917 24753 24839 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:156)
08-21 13:04:18.917 24753 24839 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:173)
08-21 13:04:18.917 24753 24839 W System.err:    at com.cmplay.webview.d.c.b(PreLoadImage.java:83)
08-21 13:04:18.917 24753 24839 W System.err:    at com.cmplay.webview.d.c$1.run(PreLoadImage.java:114)
08-21 13:04:18.917 24753 24839 W System.err:    at java.lang.Thread.run(Thread.java:818)
```

For me, it seems a `Facebook` plugin? has crashed.
```
08-21 13:04:19.326   775   786 I ActivityManager: Process com.facebook.katana:notification (pid 22559) has died
08-21 13:04:19.326   775   786 D ActivityManager: cleanUpApplicationRecord -- 22559
08-21 13:04:19.326   775   786 W ActivityManager: Scheduling restart of crashed service com.facebook.katana/com.facebook.rti.push.service.FbnsService in 87238ms
0
```

I'm not sure you are able to read Java or not, but this plugin removes the memory as much as possible.

**Comment by rgauthieropenmindt** [comment]
Sorry, I just know the basics of Java, just enough to understand what could happen in the code.

The first js error was that i've switched page before all the the markers were loaded. As for the facebook plugin, he is use on the login page only. I can navigate to see 100 pages  in my app without problem, but if I load 10 times the map page, it crash.

Same thing happen if I don't create markers on the map. I could navigate on the map page without problem as long as I want.

I've just tried to remove the click listener on the markers and the app is still crashing.

I just remember that I had modify this variable in the googlemaps-cdv-plugin.js: var MAX_EXECUTE_CNT = **100**;
Increasing the number has also increased the number of visit on my page before crashing.

**Comment by wf9a5m75** [comment]
You should not change the `MAX_EXECUTE_CNT`.

It causes app crash **of course! **

**Comment by wf9a5m75** [comment]
Since you modified the plugin JS code, it is out of support.

**Comment by rgauthieropenmindt** [comment]
It's just for testing purpose, the app is still crashing with the default property. I've just realised that it took more time to crash if I increase this property.

**Comment by wf9a5m75** [comment]
Ok. Please create a demo project (create from an empty project) then create only map page.
If you still the happens, please share it on github.

Then I will check it.

**Comment by rgauthieropenmindt** [comment]
While I was creating the demo, I've found the cause of the problem! The icon is the troublemaker. 
With the **default icon,** my apps **doesn't crash**. 
With an image from a relative path or an with an absolute url, the app will crash.

    map.addMarker({
        position: {lat: spot.lat, lng: spot.lng},
        icon: { url : 'https://app.hidden.place/maps/pin_medium.png' },
        disableAutoPan: true
      }, function(marker) {
         marker.addEventListener(plugin.google.maps.event.MARKER_CLICK, addMarkerCallback);
      });

I will send you a link to my demo tomorrow if you still need it, i'm nearly done with it.

**Comment by wf9a5m75** [comment]
If you load lots of marker with icon image, the app uses lots of memory of course.

**Comment by wf9a5m75** [comment]
Please prepare the demo project on github.

**Comment by rgauthieropenmindt** [comment]
Here's the link to the git repo: https://github.com/rgauthieropenmindt/map_crash_demo

I've test it few times with my device (Nexus 5) and every time it is crashing.

To reproduce the problem, there's two page in the app: pageA that contains a link to pageB and pageB that contains the native map. So you just need to navigate between the two pages.

On pageB I am creating a new map with spots (**51**), and when the page is leaving, the spots are deleted and the map is removed. But after coming back to pageB a dozen times to, the app will crash.

**Comment by wf9a5m75** [comment]
Ok. I will check it later.

By the way, you should not need to remove all markers by yourself.
In other words,  don't do that if you remove the map.

map.remove() takes care of everything internal.

**Comment by wf9a5m75** [comment]
By the way, how to build your project?

Just `$> ionic cordova run android`?

**Comment by rgauthieropenmindt** [comment]
you need to add the platform first: ```$> ionic cordova platform add android```

and then ```$> ionic cordova run android```

**Comment by wf9a5m75** [comment]
I just built your project, and run it.
I tested 32 times, but there is no crash at all.
https://www.youtube.com/watch?v=PS42xyeErjo&feature=youtu.be

**Comment by rgauthieropenmindt** [comment]
I just did it twice and both time the app crash. Without my image as the icon, i've succesfully load the page 50 times, but with my image I can't go further than 20.

Here my video: https://www.youtube.com/watch?v=E7nCiKz2Pbo

and the log
[logcat.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1243016/logcat.txt)

**Comment by wf9a5m75** [comment]
Um, unfortunately, I can not support for your case. Because I tested your project many times, but I can not face this crash.

I also checked the logcat.txt, but I can not figure out any information regarding to the maps plugin.

**Comment by rgauthieropenmindt** [comment]
Thanks for trying, I'll let you know if I'm able to find a solution to my bug.

**Comment by wf9a5m75** [comment]
I recommend you try it on another Android.

**Comment by rgauthieropenmindt** [comment]
I've tried with a samsumg S3 and it's crashing too.

**Comment by wf9a5m75** [comment]
I see. Please find the reason more details.
Unfortunately I can not reproduce your issue.

How about store the icon in local?

**Comment by rgauthieropenmindt** [comment]
Same result with an url or a local image

**Comment by wf9a5m75** [comment]
I found a bug in the code of `map.remove` ( = `map.clear()`).
Please reinstall the latest version.

And even your issue is not fixed. Please consider another way, such as Google Maps JavaScript API v3.

**Comment by rgauthieropenmindt** [comment]
Thank you, The issue seems to be fixed with your latest version.

**Comment by wf9a5m75** [comment]
Sounds good.
