### ISSUE TITLE
Marker click wrong name event

### ISSUE THREAD

**Issue by oscar-cocodin** [mapsplugin/cordova-plugin-googlemaps#1660]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x ] **2.0.0-beta2** 

The current MARKER_CLICK has a wrong value: 'marker_click', the correct name event is 'click'.
Actually if use the GoogleMapsEvent class the event not works

**Comment by wf9a5m75** [comment]
The ionic wrapper version is not developped by me.

**Comment by wf9a5m75** [comment]
The bug was fixed in the @ionic-native/core and @ionic-native/google-maps ver4.2.0

Please reinstall these two packages.

https://www.npmjs.com/package/@ionic-native/core
https://www.npmjs.com/package/@ionic-native/google-maps
