### ISSUE TITLE
HtmlInfoWindow constructor causes error

### ISSUE THREAD

**Issue by oscar-cocodin** [mapsplugin/cordova-plugin-googlemaps#1661]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x ] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 
 cordova-android-play-services-gradle-release 0.0.2 "cordova-android-play-services-gradle-release"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta3-20170820-2025 "cordova-plugin-googlemaps"
cordova-plugin-http 1.2.0 "SSL Pinning"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.9.4 "PushPlugin"
situm-cordova-plugin 1.0.0 "Situm Cordova plugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.2 "Launch Navigator"
```
insert the output from the command here
HtmlInfoWindow() is not a function
```

**Current behavior:**

Try to create a new HtmlInfoWindow object

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**
let infoWindow: HtmlInfoWindow = new HtmlInfoWindow()
```


----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
The ionic wrapper version is not developed by me.

**Comment by wf9a5m75** [comment]
The bug was fixed in the @ionic-native/core and @ionic-native/google-maps ver4.2.0

Please reinstall these two packages.

https://www.npmjs.com/package/@ionic-native/core
https://www.npmjs.com/package/@ionic-native/google-maps

**Comment by pitamash** [comment]
npm install @ionic-native/core @ionic-native/google-maps

ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
