### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined when I use map.clear().then(() => { /*do something*/ })

### ISSUE THREAD

**Issue by carvemerson** [mapsplugin/cordova-plugin-googlemaps#1662]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ ] **2.0.0-beta2** 
[x] **2.0.0-beta3** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-background-geolocation 2.8.1 "BackgroundGeolocation"
cordova-plugin-add-swift-support 1.7.0 "AddSwiftSupport"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.0.0 "CDVBackgroundFetch"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-buildinfo 1.1.0 "BuildInfo"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-firebase 0.1.23 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta3-20170820-2025 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-nativegeocoder 1.0.2 "NativeGeocoder"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
cordova.plugins.diagnostic 3.6.6 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**

When I use the `map.clear()` method, it should work as a promise (like the Ionic documentation https://ionicframework.com/docs/native/google-maps/#clear). 
But when I use `map.clear().then(() => { /*do something*/ })` I got this error:

`Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined` 

**Expected behavior:**

The `map.clear().then(() => { /*do something*/ })`  works. 

**Related code, data or error log (please format your code or data):**

```
null: ERROR
null: Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
message: "Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at file:///android_asset/www/build/main.js:6164:34
    at new t (file:///android_asset/www/build/polyfills.js:3:15044)
    at MapService.webpackJsonp.71.MapService.setDiv (file:///android_asset/www/build/main.js:6147:16)
    at file:///android_asset/www/build/main.js:5353:30
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9283)
    at Object.onInvoke (file:///android_asset/www/build/vendor.js:4508:37)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9223)
    at r.run (file:///android_asset/www/build/polyfills.js:3:4452)
    at file:///android_asset/www/build/polyfills.js:3:14076
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:9967)"
promise: t {__zone_symbol__state: 0, __zone_symbol__value: TypeError: Cannot read property 'then' of undefine…}
rejection: TypeError: Cannot read property 'then' of undefined
stack: "Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at file:///android_asset/www/build/main.js:6164:34
    at new t (file:///android_asset/www/build/polyfills.js:3:15044)
    at MapService.webpackJsonp.71.MapService.setDiv (file:///android_asset/www/build/main.js:6147:16)
    at file:///android_asset/www/build/main.js:5353:30
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9283)
    at Object.onInvoke (file:///android_asset/www/build/vendor.js:4508:37)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9223)
    at r.run (file:///android_asset/www/build/polyfills.js:3:4452)
    at file:///android_asset/www/build/polyfills.js:3:14076
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:9967)
    at c (file:///android_asset/www/build/polyfills.js:3:13535)
    at c (file:///android_asset/www/build/polyfills.js:3:13221)
    at file:///android_asset/www/build/polyfills.js:3:14067
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:9967)
    at Object.onInvokeTask (file:///android_asset/www/build/vendor.js:4499:37)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:9888)
    at r.runTask (file:///android_asset/www/build/polyfills.js:3:5143)
    at o (file:///android_asset/www/build/polyfills.js:3:2203)
    at <anonymous>"
task: t {_zone: r, runCount: 0, _zoneDelegates: null, …}
zone: r {_properties: Object, _parent: r, _name: "angular", …}
__proto__: Object {name: "Error", message: "", constructor: , …}

```

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
The current ionic wrapper version has many bugs. This is one of them.
(And the wrapper plugin is not developed by me).

**Comment by carvemerson** [comment]
Is there any alternative?
I have a lot of pages that use the map. When I enter in the page I execute:

```
this.map.clear();
this.map.setDiv(null);
this.map.setDiv(el);
```

Until the version beta2 (commit d437787cc118318d441e79f0d8b96895ac89a987), it was working. But when I update to the beta3, broken my app. 

If I don't use the `clear()` method, the change of map div is made very well. But the maps still with markers of the others screens.

I already tried using the map.remove(), and create a new one for each page, but the memory usage increase quickly, and the map.remove() does not free memory. 

How I proceed?

**Comment by wf9a5m75** [comment]
Could you make an example app (only include the code that reproduce your issue), then share it on github?
As far as I tested, the plugin does not remain memory when you remove the map.

And is that reproduce on Android or iOS?

**Comment by carvemerson** [comment]
I will make an example app later and share with you. 
I'm testing in Android, and de memory usage increase quickly when I remove and add a new map.

**Comment by carvemerson** [comment]
Well, I sove my problem.
I create my own clear() method. I save all references of markers, circles, polyline, etc, and instead of using map.clear() I used my function clear(), that call the remove() method of all references. 
My app is working now. 
But if I use map.clear(), something happens, and the map not work.

**Comment by wf9a5m75** [comment]
Please create a demo project and share it in order to check your issue `the map not work`.

**Comment by carvemerson** [comment]
I created one project, but in that project this error not appear. 
I don't why.

I have a service called MapService:

```cs
...
import { GoogleMaps, GoogleMap, GoogleMapsEvent, LatLng, CameraPosition, MarkerOptions, Marker, ...

declare var cordova;

@Injectable()
export class MapService {

  private map: GoogleMap;

...

  constructor(
    private http: Http,
    private platform: Platform,
    private googleMaps: GoogleMaps
  ) { }

  getMap() {
    return this.map;
  }

  setDiv(el: HTMLElement): Promise<any> {
    return new Promise<any>((resolve) => {

      if (!this.map) {
        this.map = this.googleMaps.create(el);

        this.map.one(GoogleMapsEvent.MAP_READY).then(
          () => {
            resolve(this.map);
          }
        );

      } else if (this.map.getDiv() != el) {
        
        this.map.setDiv(null);
        this.map.setDiv(el);
        this.map.clear();

        setTimeout(() => {
          resolve();
        }, 1000);

      } else { 

        this.map.clear();
        this.firePluginTouch();
        resolve();

      }
    });
  }

  firePluginTouch() {
    cordova.fireDocumentEvent('plugin_touch', {});
  }
}
```
And in the main-page and other pages the load the map i do:

```cs
ionViewWillEnter() {
    this.mapService.setDiv(this.mapElement.nativeElement).then(() => {
      this.loadMap();
    });
  }
```
The loadMap() add markers, polylines, etc. 

In version beta2 of the map, It worked.
But in version beta3, it's not working.

**Comment by wf9a5m75** [comment]
I'm not familiar with ionic. So I appreciate if you put the demo app on github, and share it.

I can build your app at least.

**Comment by wf9a5m75** [comment]
And you should not execute `cordova.fireDocumentEvent('plugin_touch', {});` without certain reason.
The `plugin_touch` uses the battery of your device.

You only need to do this is you display a dialog box after marker clicked, something like that.

**Comment by carvemerson** [comment]
I solved the white screen when I used `cordova.fireDocumentEvent('plugin_touch', {});` after the change of of div. If I don't use that, when i open a page with the map instance, the screen still white until i touch that.
For this reason i use the `cordova.fireDocumentEvent('plugin_touch', {});`.

Thanks for the tip.

**Comment by carvemerson** [comment]
I will try reproduce the error, when I get It, I share with you.

**Comment by wf9a5m75** [comment]
The reason of the plugin_touch event, I got it. Thanks.
