### ISSUE TITLE
Missing Command Error and Request for Directions Feature

### ISSUE THREAD

**Issue by binarybehemoth** [mapsplugin/cordova-plugin-googlemaps#1663]
I encountered an error. I could not run it in both my android phone and the browser. Nothing appeared. I tried versions 1.4.5 and 2.0 beta.
![cordova-googlemaps-plugin error](https://user-images.githubusercontent.com/15277380/29582207-69a73996-87ae-11e7-9bdc-41554097f60f.jpg)

My code is:
map = plugin.google.maps.Map.getMap(document.getElementById("map"));
where there is a div with the id 'map'.

I am using Cordova. I am not using Ionic.

Also, when can the Directions feature be ready? I need it. Perhaps the plugin can return 'map' as the google map object instead, so that we can manipulate it with Google Map JavaScript API.

**Comment by wf9a5m75** [comment]
Please share your project file on github. I guess you tried to use this plugin without rules.

----

>Perhaps the plugin can return 'map' as the google map object instead, so that we can manipulate it with Google Map JavaScript API.

This is completely misunderstand. This plugin **does not use** the Google Maps JavaScript API v3 at all.
This plugin uses only the Google Maps Android API v2 and the Google Maps SDK for iOS, these are native APIs, not JavaScript API.

They do not have direction features in their APIs, this plugin does not have it.

**Comment by binarybehemoth** [comment]
What rules do we need? My source file is quite a mess at the current state.

Are you saying Google Maps Android and Google Maps iOS do not support directions features? How does Uber show the directions then?

**Comment by wf9a5m75** [comment]
>Are you saying Google Maps Android and Google Maps iOS do not support directions features? How does Uber show the directions then?

They uses the Google Maps Directions API, I guess.

Why don't you confirm the official documents of Google by yourself?

-------

The rules are here
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0

You have to wait `MAP_READY` event at least **before using any methods**.

--------

Until you share something with me, I don't support you.

**Comment by binarybehemoth** [comment]
I did share a line of my code. Isn't that enough to generate the map?

**Comment by wf9a5m75** [comment]
No. I asked whole code of the map page.

**Comment by wf9a5m75** [comment]
You just share this line.
`map = plugin.google.maps.Map.getMap(document.getElementById("map"));`

Could you tell me how I can test for you?

**Comment by binarybehemoth** [comment]
I am trying Bings Map at the moment. Basically just now I just used that single line to try to display the map. Wouldn't that be enough?

**Comment by wf9a5m75** [comment]
This plugin does not support bing map.

**Comment by binarybehemoth** [comment]
I switched to Bing Maps only after I tried that line of code. Basically it was just a one liner. There is nothing else I could show you.

**Comment by wf9a5m75** [comment]
Then I can not help you. Please use the bing map.

**Comment by binarybehemoth** [comment]
ok. Good luck with your plugin.

**Comment by wf9a5m75** [comment]
Thank you.

**Comment by aboveo** [comment]
**We used google directions api**

- Draw direction with polyline from current location to destination
- Add destination marker
- Display Directions 

var distancetoDestination = '', durationtoDestination = ''
function requestDirections(myDestinationLocation) {
    var myCurrentLocation = {
        lat: getCurrentLatFromStorage(),
        lng: getCurrentLngFromStorage()
    };

    var url = "https://maps.googleapis.com/maps/api/directions/json?" +
        "origin=" + myCurrentLocation.lat + ',' + myCurrentLocation.lng + "" +
        "&destination=" + myDestinationLocation.lat + ',' + myDestinationLocation.lng + "" +
        "&key=" + googleMapsApiKey

    var wayPointsArray = []
    wayPointsArray.push(myCurrentLocation)

    $.getJSON(url,function (response) {
        var geoCodedPoints = response.routes[0].overview_polyline.points
        wayPointsArray = plugin.google.maps.geometry.encoding.decodePath(geoCodedPoints)

        drawDirections(wayPointsArray)
        addDestinationMarker(myDestinationLocation)

        $('#directionInstructions').html('')

        var start = response.routes[0].legs[0].start_address
        var end = response.routes[0].legs[0].end_address

        distancetoDestination = response.routes[0].legs[0].distance.text
        durationtoDestination = response.routes[0].legs[0].duration.text

        var directionsDisplay = new google.maps.DirectionsRenderer;
        var directionsService = new google.maps.DirectionsService;

        directionsDisplay.setPanel(document.getElementById('directionInstructions'));
        calculateAndDisplayRoute(directionsService, directionsDisplay, start, end);
    })
}

function calculateAndDisplayRoute(directionsService, directionsDisplay, start, end) {
    directionsService.route({
        origin: start,
        destination: end,
        travelMode: 'DRIVING'
    }, function (response, status) {
        if (status === 'OK') {
            directionsDisplay.setDirections(response);
        } else {
            window.alert('Directions request failed due to ' + status);
        }
    });
}

var markerRemove = ''
function addDestinationMarker(myDestinationLocation) {
    map.addMarker({
        'position': {
            lat: myDestinationLocation.lat,
            lng: myDestinationLocation.lng
        },
        draggable: false
    }, function (marker) {
        markerRemove = marker
        // Show the info window
        //marker.showInfoWindow();
    })
    map.setCameraZoom(17);
    map.setCameraTilt(60);
}

function drawDirections(wayPointsArray) {
    // Add a polyline
    map.addPolyline({
        'points': wayPointsArray,
        'color': '#005e91',
        'width': 5
    }, function (polyline) {
        var clearPath = document.getElementById('clearSearch')
        clearPath.addEventListener("click", function () {
            clearDirections(polyline)
        })
    })
}

function clearDirections(polyline) {
    markerRemove.remove();
    polyline.remove();

    map.moveCamera({
        target: {
            lat: getCurrentLatFromStorage(),
            lng: getCurrentLngFromStorage()
        },
        zoom: 15,
        tilt: 90
    })
}
