### ISSUE TITLE
Map become unresponsive

### ISSUE THREAD

**Issue by minhui27** [mapsplugin/cordova-plugin-googlemaps#1664]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
branch-cordova-sdk 2.6.0 "branch-cordova-sdk"
code-push 2.0.1-beta "CodePushAcquisition"
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-code-push 1.9.5-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.0-beta3-20170820-2025 "cordova-plugin-googlemaps"
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.1.2 "OneSignal Push Notifications"
```

**Current behavior:**
I found that if I using this plugin with the [ionic2-super-tabs](https://github.com/zyra/ionic2-super-tabs), the marker and map become unresponsive, else it was responsive. Similarly, with the ionic2-super-tabs, this bug was not found when I using the version 1.4.xx of this plugin.

Thanks.

**Comment by wf9a5m75** [comment]
I don't support the compatibility with other plugins.

**Comment by wf9a5m75** [comment]
I'm not ionic user.
Please create an example project, then put it (`src`, `resources` and other files) on to github.
Then share it please.

**Comment by wf9a5m75** [comment]
ping

**Comment by minhui27** [comment]
Here is my example project: [map unresponsive](https://github.com/minhui27/map-unresponsive). 
Thanks.

**Comment by wf9a5m75** [comment]
Thanks. I will check it later

**Comment by wf9a5m75** [comment]
Fixed!
![issue_1664](https://user-images.githubusercontent.com/167831/29738839-cfc8f37c-89e3-11e7-885f-93b1f01517b2.gif)

**Comment by minhui27** [comment]
Its working now. Thanks.

**Comment by franalt** [comment]
I'm having this issue, what was the problem?
