### ISSUE TITLE
mapToolbar won't disable

### ISSUE THREAD

**Issue by thezakman** [mapsplugin/cordova-plugin-googlemaps#1665]
**I'm submitting a ...**  (check one with "x")
[ X ] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[ X ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

>**Ionic info**

cli packages: (C:\Users\HP\Cheeper-1-0-3\node_modules)

@ionic/cli-utils  : 1.9.2
ionic (Ionic CLI) : 3.9.2
global packages:

Cordova CLI : 6.5.0
local packages:

@ionic/app-scripts : 2.1.3
Cordova Platforms  : android 6.2.3
Ionic Framework    : ionic-angular 3.6.0
System:

Node : v7.10.0
npm  : 4.6.1
OS   : Windows 7

>**cordova plugin list**

cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-buildinfo 1.1.0 "BuildInfo"
cordova-plugin-calendar 4.6.0 "Calendar"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta3-20170820-2025 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Current behavior:**

Maptoolbar is still showing even after setting in the controls the option **mapToolbar: false**

**Expected behavior:**

maptoolbar stop showing when boolean false is set. 

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

Here is the code section that I wrote:
[https://gist.github.com/thezakman/862a9e911857a1953d750bb000f23342](https://gist.github.com/thezakman/862a9e911857a1953d750bb000f23342)

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
The bug was fixed in the @ionic-native/core and @ionic-native/google-maps ver4.2.0

Please reinstall these two packages.

https://www.npmjs.com/package/@ionic-native/core
https://www.npmjs.com/package/@ionic-native/google-maps

**Comment by wf9a5m75** [comment]
Confirmed.

![1665](https://user-images.githubusercontent.com/167831/29800686-59ca97fe-8c20-11e7-881f-0ed73516e41a.gif)
