### ISSUE TITLE
move the marker based on new position in ionic v1

### ISSUE THREAD

**Issue by JYOTHISHPJ** [mapsplugin/cordova-plugin-googlemaps#1667]
i need to move the marker based on the gps position .I get the lat and long based on motion but i can't move the marker based on the lat and long.since duplication of marker is occur.
   map.addMarker({
           position: newPoint,
            'title': "TESLA",

           map: map

         },function(marker) {
      
             marker.showInfoWindow();
              
           });

anyone plz help...???

**Comment by wf9a5m75** [comment]
marker.setPosition()
