### ISSUE TITLE
GroundOverlay Issue

### ISSUE THREAD

**Issue by Tong2203** [mapsplugin/cordova-plugin-googlemaps#1668]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

------------------
Hi, I want to create a GroundOverlay by downloaded image which stored in cordova.file.dataDirectory. 
( path like: "file:///data/user/0/[package name]/files/data/image/overlay/map.png" )

It was OK in 2.0.0-beta2.

I had tried to set path like 
1."file:///android_asset/www/img/map.png"
2."www/img/map.png"
3."file:///data/user/0/[package name]/files/data/image/overlay/map.png" 

1&2 can be shown but 3.
And iOS version works perfectly. 

 Is this a bug?
Sorry for my poor English...

**Comment by wf9a5m75** [comment]
Please  share your project files on github or bitbuclet.

Or create a demo project, then share it.

**Comment by Tong2203** [comment]
Hi, I have created a demo project.
https://bitbucket.org/breezee_work/maptest
よろしくお願いします。

**Comment by wf9a5m75** [comment]
修正しました。最新版を再インストールしてください。

**Comment by Tong2203** [comment]
確認できました。
ありがとうございました。
