### ISSUE TITLE
Hello, it's just a question 

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1671]
**I'm submitting a ...**  (check one with "x")
[ X] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[X ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[X ] **Android**
[X ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.0.0-beta3-20170811-1937 "cordova-plugin-googlemaps"
```

 I'm developing an app similar to uber. My question is this: uber has an effect that is the mismatching of markers, does not skip the marker when doing setPosition, but scrolls. Could you do with this plguin?
In case it is not possible you could modify the plugin to add that movement? What class should you modify to add that effect?

**Comment by wf9a5m75** [comment]
I couldn't understand what the effect is.

**Comment by wuilmerj24** [comment]
@wf9a5m75 
este efecto http://terikon.github.io/marker-animate-unobtrusive/demo/unobtrusive/markermove-sliding.html
Or if it can be added native?

**Comment by wf9a5m75** [comment]
Even though, I couldn't understand what the point is.
But if you don't want to move the map when you click on a marker, just `disableAutoPath: true`.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md#disable-auto-pan

**Comment by wuilmerj24** [comment]
Open the link you want to send and click on the map, the marker does not jump, it only moves
Is it possible to add the plugin natively or by css?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/utilities/geometry/spherical/interpolate/README.md

**Comment by wuilmerj24** [comment]
@wf9a5m75 OK thanks.
  I try and comment
