### ISSUE TITLE
Please can we control/reduce the myLocationButton gps polling rate

### ISSUE THREAD

**Issue by ryanhalley** [mapsplugin/cordova-plugin-googlemaps#1673]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[x] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[x] **iOS**

**Current behavior:**

Enter the map, and watch system logs; libGps service aggressively polls once per second.

**Expected behavior:**
Polling behaviour can be controlled, as myLocationButton feature is a nice option to have, but may be used rarely depending on application - by being enabled, the feature drains battery. Please allow us to override the default 1s polling rate in milliseconds e.g 10000 - this will allow us to balance performance.

**Steps to reproduce:**
https://github.com/ryanhalley/googlemapsiconurl
Enter map page with myLocationButton option enabled.
On android, install and enable adb logging: adb lolcat | findstr /C:libgps

**Comment by wf9a5m75** [comment]
That is the native api function. not this plugin one.
