### ISSUE TITLE
Google maps not shows

### ISSUE THREAD

**Issue by rezkyrere** [mapsplugin/cordova-plugin-googlemaps#1674]
I am developing an app using cordova-plugin-googlemap. Map works fine but map not shows. 
See below-

https://user-images.githubusercontent.com/31013919/29717942-3d0131c4-89db-11e7-8326-66961ab4e888.png

Please someone help to solve this issue.Thanks in advance for your help and cooperation.

@wf9a5m75

**Comment by ryanhalley** [comment]
When you logged the ticket, you were asked for a ton of info; you need to provide everything that was asked, to get support (coming from someone who created a ticket without all the required info..).

**Comment by wf9a5m75** [comment]
Your API key is the problem.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by rezkyrere** [comment]
Thank you. This Works :+1:  @wf9a5m75
