### ISSUE TITLE
Predict the center of the map for animateCamera with bounds

### ISSUE THREAD

**Issue by heshamghandour** [mapsplugin/cordova-plugin-googlemaps#1675]
Hi!

Is it possible to predict the center of the map before the animation to certain bounds ends?
So basically if you animate the camera to fit certain bounds, I'd like to predict the coordinates of the camera center before the animation ends. 

Thanks!

**Comment by wf9a5m75** [comment]
No...

**Comment by heshamghandour** [comment]
I don't mean through a preset function btw. I obviously searched for that :D 
What I meant is more of a formula. There must be a way to calculate that, since the map does it internally

**Comment by wf9a5m75** [comment]
The ways for specifying the new target position are not only one.
And in order to adjust the tilt and/or the view angle after the camera moved, the plugin changes the camera again internally.

**Comment by wf9a5m75** [comment]
And you can know predict area because you specify the camera target.

```js
map.animateCamera({
   target: [ ... ]
})
```

is able to replace with

```js
var latLngBounds = new plugin.google.maps.LatLngBounds(target);
console.log(latLngBounds.southwest, latLngBounds.northeast);
```

**Comment by heshamghandour** [comment]
hmmm good point..
Maybe I'll just provide the problem I'd like to solve, in case you might have some insight.
I want to separate the "automatic" camera change done via code and the "manual" dragging done by the user.

Since it's impossible to detect touch events, the only way I can see is to have the next destination of the "automatic" change.. and if the camera stops somewhere else then it's a manual one.

Hope that made sense :D

**Comment by heshamghandour** [comment]
your code is quite useful! I'll try it with that!

**Comment by wf9a5m75** [comment]
And if you want to know where user stop the map, just monitor the `CAMERA_MOVE` event.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/CAMERA_EVENTS/README.md

**Comment by heshamghandour** [comment]
yes that part is clear. But predicting before the animation even starts is what I was asking and your suggestion of getting the southwest and northeast coordinates is very helpful! 
I guess the next best thing.
