### ISSUE TITLE
Change Position Control With Css

### ISSUE THREAD

**Issue by rezkyrere** [mapsplugin/cordova-plugin-googlemaps#1676]
How to change position my location button on map with css.

Please someone help to solve this issue. Thanks in advance for your help.

@wf9a5m75

**Comment by wf9a5m75** [comment]
The location button comes from the native api. Not this plugin. Only possible way is specifying the padding.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/setPadding/README.md

**Comment by rezkyrere** [comment]
ok. Thanks for this reply. I will try
