### ISSUE TITLE
Cluster image quality on iOS

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1679]
I noticed a difference of quality between the cluster image between Android and iOS.

- On Android, the image and the font inside it are of great quality.
- On iOS, both the image and the font are of questionable quality.

![android](https://user-images.githubusercontent.com/16256207/29752462-aedbbac4-8b5e-11e7-8554-bda5b01ff7b3.png)

![ios](https://user-images.githubusercontent.com/16256207/29752463-aee23692-8b5e-11e7-89f2-0634ad3a8022.png)

**Comment by wf9a5m75** [comment]
Looks like the same for me.

![screen shot 2017-08-27 at 5 14 57 pm](https://user-images.githubusercontent.com/167831/29755356-a4b2273a-8b4b-11e7-8547-3ca56f857b33.png)

![device-2017-08-27-171429](https://user-images.githubusercontent.com/167831/29755357-a7a8cf3e-8b4b-11e7-976a-86297a5d8f88.png)

**Comment by antoine92190** [comment]
I found out that the resizing of the cluster image is the source of the difference.
On Android, the resizing seems to improve the quality of the cluster image, however on iOS it does not.

I updated my repo: https://github.com/antoine92190/ionic-map

```
this.map.addMarkerCluster({
      markers: data,
      icons: [
        {
          min: 3,
          url: "./assets/cluster.png",
          anchor: { x: 16, y: 16 },
          label: {
            color: "white",
            bold: true,
            fontSize: 14
          },
          size: {
            width: 37,
            height: 37
          }
        }
      ]
    }
```

**Comment by wf9a5m75** [comment]
In the plugin,  I use `UIGraphicsBeginImageContextWithOptions` for resizing.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/ios/GoogleMaps/PluginUtil.m#L98

I have no other solution that improve the quality than this way.
If you have it, I will implement it.
Otherwise, there is no solution, so omitting the size option is the solution.

**Comment by wf9a5m75** [comment]
Until you find another way, I close this thread, because I have no option currently.

**Comment by antoine92190** [comment]
Ok, I will try to find something.

Just a question that could help me understand.
Is a cluster image considered the same as a normal marker image?

Because when I resize a normal marker, its quality is improved on both Android and iOS.
However, when I do the same with cluster images, its quality only improves on Android.

**Comment by wf9a5m75** [comment]
>However, when I do the same with cluster images, its quality only improves on Android.

Um, this might be helpful.

**Comment by wf9a5m75** [comment]
How about this?

Current code
![screen shot 2017-08-31 at 2 34 09 pm](https://user-images.githubusercontent.com/167831/29947771-422603ee-8e60-11e7-908d-68b9e3eab85e.png)

Test code
![screen shot 2017-08-31 at 3 22 36 pm](https://user-images.githubusercontent.com/167831/29947772-4239f23c-8e60-11e7-9510-491f5eae6435.png)

**Comment by antoine92190** [comment]
Perfect :thumbsup:
