### ISSUE TITLE
Crash App with Plugin Google Maps

### ISSUE THREAD

**Issue by Macario** [mapsplugin/cordova-plugin-googlemaps#1681]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ x] **Android**
[ ] **iOS**

**Current behavior:**
My App use in many pages the same instance of google maps. Sometimes I got an error and the app crash. My App is connected with the firebase and there show where the error happened. See the error from firebase below: 

Exception java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
android.view.ViewGroup.addViewInner (ViewGroup.java:4656)
android.view.ViewGroup.addView (ViewGroup.java:4492)
android.view.ViewGroup.addView (ViewGroup.java:4433)
android.view.ViewGroup.addView (ViewGroup.java:4406)
**plugin.google.maps.MyPluginLayout$3.run (MyPluginLayout.java:441)**
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:158)
android.app.ActivityThread.main (ActivityThread.java:7230)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

I set in bold, the related line of plugin. I've got the same error three times in the last week.

**Expected behavior:**

Plugin works fine without error.

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
I think you use this plugin with wrong way. 
Please share your project files on github or bitbucket.
(Or create a demo project, then share it on github)

**Comment by Macario** [comment]
I can't share my project, but why are you thinking that I'm using this plugin with wrong way? Other thing, after update plugin version to googlemaps 2.0.0-beta3-20170827-2151, I can't touch in the menu sidebar anymore. @wf9a5m75

**Comment by wf9a5m75** [comment]
As I said `(Or create a demo project, then share it on github)`.

If you don't create even demo project, I don't support you.

**Comment by wf9a5m75** [comment]
Important thing is that reproduce your issue on my side.
**I'm not interested in your app code at all.**

**Comment by Macario** [comment]
The last commit that plugin works fine with menu sidebar is fc4ddd618e40cd5f2c69d6ef306793250c1f6f03. After that, when open menu sidebar, it's not more possible click in one option of the menu sidebar.

**Comment by wf9a5m75** [comment]
As I said `Important thing is that reproduce your issue on my side.`.

If you repeat again, I close this thread.
