### ISSUE TITLE
Map.addPolygon(...) with holes causes iOS SIGABRT

### ISSUE THREAD

**Issue by Kraxxis** [mapsplugin/cordova-plugin-googlemaps#1682]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.1.1 "Google Maps SDK for iOS"
com.pylonproducts.wifiwizard 0.2.11 "WifiWizard"
cordova-fabric-plugin 1.0.9 "cordova-fabric-plugin"
cordova-plugin-chrome-apps-common 1.0.7 "Chrome Apps Common Utils"
cordova-plugin-chrome-apps-iossocketscommon 1.0.2 "Chrome Apps iOS Sockets Common"
cordova-plugin-chrome-apps-sockets-udp 1.3.0 "Chrome Apps Sockets UDP API"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-hash 0.4.1 "FileHash"
cordova-plugin-file-sharing 1.0.0 "File sharing"
cordova-plugin-googlemaps 2.0.0-beta3-20170823-2235 "cordova-plugin-googlemaps"
cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
cordova-plugin-powermanagement 1.0.5 "Cordova PowerManagement plugin"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.0.3 "Cordova WKWebView Engine"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
```

**Current behavior:**
Calling `Map.addPolygon(...)` with holes options causes the iOS app to SIGABRT. 

Note this error does not happen if the Polygon is created without holes, and then `Polygon.addHoles(...)` is executed later.

**Expected behavior:**
`Map.addPolygon(...)` should not cause a SIGABRT. 

**Additional Info**

First, I am upgrading an existing project which uses **1.4.x** to use the latest **2.0.0-beta3** branch.  This feature was working in the previous branch.

I took some time to investigate where i think the issue is.  This is what I have learned.  

The `SIGABRT` occurs at the following line:
[PluginPolygon.m](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/ios/GoogleMaps/PluginPolygon.m#L82)
The error occurs because `[latLng objectForKey:@"lat"]` does not have selectedor `ObjectForKey` because it is an `Array` and not an `Object`. Interrogating the options object in XCode reveals [the holes object](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/ios/GoogleMaps/PluginPolygon.m#L72) is malformed, and does not structurally look like my input.

Working backwards, I placed logging statements around [this javascript block](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Map.js#L847-L856).

Data before:
```
[ [ { lat: 0.100, lng: 0.100 }, { lat: 0.200, lng: 0.100 }, ... ] ]
```
Data After:
```
[ [ [ { lat: 0.100, lng: 0.100 } ], [ { lat: 0.200, lng: 0.100 } ], ... ] ]
```

Something is causing each individual point to be wrapped in an array. I suspect the call to [common.convertToPositionArray](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Common.js#L547) is the culprit because of the recent commit:

https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/fce0c545ba2d6439fddd18e37965f757d45050d8#diff-1d34c8b063d629edb17151167f851ecaL530

**Comment by wf9a5m75** [comment]
Please create a demo project, and share it on github.

**Comment by wf9a5m75** [comment]
ping

**Comment by Kraxxis** [comment]
Apologies; I have been very busy and have not had additional time to commit to this issue.

I'll try and create a project later this week.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Fixed.
![screen shot 2017-09-05 at 1 02 56 pm](https://user-images.githubusercontent.com/167831/30081063-9d2da5de-923a-11e7-999a-96030080f629.png)
