### ISSUE TITLE
getMyLocation crashes app when activate location permission is denied

### ISSUE THREAD

**Issue by Guchster** [mapsplugin/cordova-plugin-googlemaps#1683]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ x ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[ x ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ x ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.2.0 "Google Maps SDK for iOS"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.0.0-beta3-20170816-1440 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
...
```

**Current behavior:**

Problem:
The map is working fine, the problem comes when I use the getMyLocation() method and the user denies the activate location permission, in this cases the app crashes.
I am not using ionic-native.

First Permission = Use the Device Location
Second Permission = Activate the Device Location (is only asked when the location is turned off, i.e. gps is turned off)

@wf9a5m75 I already shared the project with you, the installed versión of the plugin is before you fixed the first permission bug, however the version after you fixed the problem with the first permission still has the same problem when the second permission is denied, so you will be able to reproduce it with this same project,

My Environment:
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed

**Expected behavior:**
The method should go to the onError function every time (when permission is denied) and not crash.

**Steps to reproduce:**
Install the plugin
Call the map.getMyLocation() method
Deny request for permissions when asked in app

**Related code, data or error log (please format your code or data):**

```
//I am sure that the mapCenter is a valid LatLng object

  map: any;

  private loadMap(mapCenter: LatLng) {
    this.platform.ready().then(() => {
      let element = document.getElementById('map');
      this.map = (<any>window).plugin.google.maps.Map.getMap(element, this.getMapConfigurations(mapCenter));
      this.map.on((<any>window).plugin.google.maps.event.MAP_READY, map => {
        console.log("Loaded map! (working fine)");
        var onSuccess = function (location) {
          console.log("I want to get here if success (working fine)");
        };
        var onError = function (msg) {
         // PROBLEM: can't get here when persmission denied //
          console.log("I want to get here if error (working sometimes)");
        };
        this.map.getMyLocation(onSuccess, onError);
      });
    }
  private getMapConfigurations(mapCenter: LatLng) {
    return {
      'controls': {
        'compass': true,
        'myLocationButton': true,
        'indoorPicker': true,
        'zoom': true
      },
      'gestures': {
        'scroll': true,
        'tilt': true,
        'rotate': true,
        'zoom': true
      },
      'camera': {
        'latLng': mapCenter,
        'tilt': 10,
        'zoom': 15,
        'bearing': 15
      }
    }
  }
```

----

**Comment by wf9a5m75** [comment]
I just built and run your app, but the app didn't crash.
![capture](https://user-images.githubusercontent.com/167831/29796206-c78c0776-8c04-11e7-8eca-11dbee2bd6ac.gif)

**Comment by Guchster** [comment]
Unfortunately this error is very random, and it happens one out of ten times, I'll come back to you when I have a better way to reprouce it, I'll close this issue for now.
Thanks for your help!
