### ISSUE TITLE
setCameraZoom crashes Xcode simulator

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1685]
When I call `this.map.setCameraZoom(15)` on the Xcode simulator, the app crashes.
The issue cannot be reproduced on iOS or Android devices.

Error thrown by Xcode:
`Terminating app due to uncaught exception 'GMSThreadException', reason: 'The API method must be called from the main thread`

Version: `2.0.0-beta3-20170828-2350`
https://github.com/antoine92190/ionic-map

**Comment by wf9a5m75** [comment]
ok

**Comment by wf9a5m75** [comment]
Fixed.
