### ISSUE TITLE
Moving maker to center of map when tap animation flickers on iOS

### ISSUE THREAD

**Issue by lpikora** [mapsplugin/cordova-plugin-googlemaps#1686]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.0-beta3-20170820-2025 "cordova-plugin-googlemaps"
cordova-plugin-ios-camera-permissions 1.1.1 "iOS Permissions"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
When tap on marker, animation of moving center of map to the marker flickers. First jumps to tapped marker, then back to previous position, then animate to tapped marker.

**Expected behavior:**
When tap marker, it should animate without any jumps.

**Steps to reproduce:**
Place markers on map and them tap to from one to one.

**Screen capture or video record:**
Slowdown video speed to 0.25x to view unwanted jump in animation.

https://www.youtube.com/watch?v=H7x0zyTCvOY&feature=youtu.be

**Comment by wf9a5m75** [comment]
The version 2.0.0-beta3-20170820-2025 is too old. please try the latest version at least.

Even if the issue is not solved, please share your project files on github, or create a demo project then share it on github.

**Comment by wf9a5m75** [comment]
I watched your video 10 times, but I couldn't understand your point.
But the plugin does not anythjng when you tap on a marker.
It is the behavior of the native api.

If you don't like it, please use the Google Maps JavaScript API v3.
