### ISSUE TITLE
Map incorrectly sizing when StatusBar.overlaysWebView == false

### ISSUE THREAD

**Issue by christopherwk210** [mapsplugin/cordova-plugin-googlemaps#1688]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 
(multiple maps branch)

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-firebase 0.1.23 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta3-20170828-2350 "cordova-plugin-googlemaps"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
```

**Current behavior:**
When `StatusBar.overlaysWebView(false);` is called, the map resizes itself incorrectly. It seemingly moves up 20px or so.

**Expected behavior:**
The map should resize as a normal element would, rather than moving up 20px or so.

**Steps to reproduce:**
[Repo that reproduces the issue.](https://bitbucket.org/christopherwk210/mapissue)

On a blank cordova project, adding a map and using the StatusBar cordova plugin to change the status bar overlay is all that it takes. Please run repo locally to see it in action.

**Screen capture or video record:**
<div align="center">
<img width=200 src="https://user-images.githubusercontent.com/13367277/29842681-6a2f6608-8cbe-11e7-932d-99637a0ae846.gif">
</div>

**Related code, data or error log (please format your code or data):**
No errors are thrown, and the only code that I use to actually trigger the behavior is
```
StatusBar.overlaysWebView(false);
```

**Comment by wf9a5m75** [comment]
Please create a demo project and share it on github.

**Comment by christopherwk210** [comment]
Does it have to be github? I've already created a demo project, I linked to it under "Steps to reproduce" and it is on bitbucket.

**Comment by wf9a5m75** [comment]
Ah, you already shared. Thank you. I will check it later.

**Comment by christopherwk210** [comment]
Awesome, thank you so much for your time!

**Comment by wf9a5m75** [comment]
Check here.

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/242

**Comment by christopherwk210** [comment]
Unfortunately that doesn't solve the issue. I've updated my demo repo with the solution proposed in issue #242, and the same error still happens.

**Comment by wf9a5m75** [comment]
It seems the status bar plugin changes the frame size.
https://github.com/apache/cordova-plugin-statusbar/blob/master/src/ios/CDVStatusBar.m#L476

**Comment by wf9a5m75** [comment]
I confirmed the maps plugin does not do anything at all.

**Comment by christopherwk210** [comment]
If it helps anyone else who comes across this in the future, I solved my issue by manually applying a 20px top padding to the page and kept the status bar overlapping the webview.
