### ISSUE TITLE
Google map not getting displayed on device back button

### ISSUE THREAD

**Issue by EvPut** [mapsplugin/cordova-plugin-googlemaps#1694]
**I'm submitting a ...**
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-googlemaps 2.0.0-beta3-20170820-2025 "cordova-plugin-googlemaps"
cordova-plugin-media 3.0.1 "Media"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.6.6 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**cli packages:**
@ionic/cli-utils  : 1.9.2
ionic (Ionic CLI) : 3.9.2

**global packages:**
Cordova CLI : 7.0.1

**local packages:**
@ionic/app-scripts : 2.1.3
Cordova Platforms  : android 6.2.3 ios 4.4.0
Ionic Framework    : ionic-angular 3.6.0

 I have created a tab on sidebar view to show google map. All is working fine if I navigate from ionic back button from header bar but if i redirect back using android device back button map will get disappear and it shows me a blank screen.
Please help me to solve this issue.
Thanks.
![](https://user-images.githubusercontent.com/31080162/29892530-8c08d934-8dd7-11e7-92c5-40140107507c.jpg)

The question was asked and here, but could not help: 
https://forum.ionicframework.com/t/google-map-not-getting-displayed-on-device-back-button/102407/2

**Comment by wf9a5m75** [comment]
Before asking, please try the latest version.
The `cordova-plugin-googlemaps 2.0.0-beta3-20170820-2025` is too old.

**Comment by wf9a5m75** [comment]
And I appreciate if you write your comment with correct syntax of Github markdown.

**Comment by EvPut** [comment]
In last version bug fixed. Thanks.
