### ISSUE TITLE
Google map is not visible but the canvas defined for it is visible with the google name at bottom-left of the canvas. Please view the screenshot attached.

### ISSUE THREAD

**Issue by tomNjerry** [mapsplugin/cordova-plugin-googlemaps#1695]
[

**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[ ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
What is your problem? Where is the screen shot?

**Comment by tomNjerry** [comment]
![screenshot_2017-08-31-12-27-58](https://user-images.githubusercontent.com/17373795/29941627-d0f10b28-8eb0-11e7-9c49-0593cb88ea04.png)

**Comment by wf9a5m75** [comment]
It's easy. Your key is wrong.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by tomNjerry** [comment]
already enabled the google android api
also generated debug key and given sha 1 key
what can be other possibility

**Comment by wf9a5m75** [comment]
Your keytool you use for generating is wrong (most of all cases is this one), or change the restriction is none.
![screen shot 2017-08-31 at 12 45 55 pm](https://user-images.githubusercontent.com/167831/29942369-7a92c160-8e4a-11e7-86d6-b1404296a30f.png)

**Comment by tomNjerry** [comment]
It worked ...
Thank you very much.

**Comment by tomNjerry** [comment]
how to make that key secure if kept 
https://user-images.githubusercontent.com/167831/29942369-7a92c160-8e4a-11e7-86d6-b1404296a30f.png

**Comment by wf9a5m75** [comment]
Search at Google. I'm not your teacher!
