### ISSUE TITLE
Maker cluster freezes application when zooming to cluster with many markers to resolution = 999

### ISSUE THREAD

**Issue by lpikora** [mapsplugin/cordova-plugin-googlemaps#1696]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-googlemaps 2.0.0-beta3-20170830-1907 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```

**Current behavior:**
When zooming to cluster with many pois in high zoom to resolution = 999 app regurarly crashes.

**Expected behavior:**
Should uncluster markes.

**Steps to reproduce:**
Put many makers in one area with small distances between them. Unzoom, then zoom to small cluster.

**Screen capture or video record:**

https://www.youtube.com/watch?v=yyBCq-OEZQg
(Click cluster zoom in, zoom out, click to cluster in zoom 18 -> app crashes)

Logcat:
https://pastebin.com/f3HAGQkt

traces.txt
https://ybin.me/p/195b7e1b43ac2a96#rhv2ojX9+XfGd2m2kWs0bdRruytW+JnMQynTFFtYRw8=

Using example: https://github.com/lpikora/cluster_test

**Comment by lpikora** [comment]
With further testing I found out that plugins marker cluster does not limit rendering markers just for current viewpoint (geo boundaries) when user zooms above value specified by `maxZoomLevel`.

In some cases i was able to zoom out back from higher zoom and see a lot of markers out of my previous view point. See: https://youtu.be/MJR2ZaLdsp8 (1400+ markers, maxZoomLevel=16)

It probably add all markers specified by options array - in my case 1400+ to the map and cause out of memory app crash.

Setting value of `maxZoomLevel` to highest value 18 did some improvement, but still when maps is zoomed to max it starts to lag sometime and then crash.

**Comment by wf9a5m75** [comment]
Yes, I know.

**Comment by wf9a5m75** [comment]
Please try the current latest version. Should be fine.

**Comment by wf9a5m75** [comment]
Please try the current version.

**Comment by wf9a5m75** [comment]
This is a demo on older device.
(Moto G, Android 4.4.4)

Although it is slow, but no crash.
![1696](https://user-images.githubusercontent.com/167831/29957659-80f48440-8ea3-11e7-9eb1-815545b9f377.gif)

**Comment by lpikora** [comment]
Now it works great. Tested on Nokia 5, Android 7.1.1. With 1400+ markers it performs fantastic, clustering + rendering in few milliseconds. Thank you.
