### ISSUE TITLE
Info window closed after click on marker and camera move when using marker clusterer on iOS

### ISSUE THREAD

**Issue by lpikora** [mapsplugin/cordova-plugin-googlemaps#1697]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-googlemaps 2.0.0-beta3-20170830-1907 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```

**Current behavior:**
After click on marker, infoWindow is opened. But after camera move clicked marker to center of map, clustererer redraw markers and infoWindow is closed.

**Expected behavior:**
Info windows should remain open.

**Steps to reproduce:**
Click on marker wint `title` property near edge of the screen. Some cluster icons have to be visible.

**Screen capture or video record:**

https://www.youtube.com/watch?v=eBT0OnF8zzo

**Related code, data or error log (please format your code or data):**

https://github.com/lpikora/cluster_test

**Comment by wf9a5m75** [comment]
Regards to this comment, `Some cluster icons have to be visible`

please learn the geocell grid algorithm.

**Comment by lpikora** [comment]
Ok, I would realy like to learn this algorith. But i just wanted describe when this issue (unwanted closing info window occurs) - when cluster icons (cluster markes) are displayed alognside with normal markers on a map. When there are only normal markers on a map (in high zoom), info window remains open.

**Comment by wf9a5m75** [comment]
Yes, I understand your point.

**Comment by wf9a5m75** [comment]
**Before**
![1697_before](https://user-images.githubusercontent.com/167831/29991063-3ea8bbb8-8f36-11e7-8f3b-a861064469a4.gif)

**After(current)**
![1697_after](https://user-images.githubusercontent.com/167831/29991062-3ea5197c-8f36-11e7-9470-ab84e44dff5d.gif)
