### ISSUE TITLE
Map blank if map-page gets loaded via navCtrl.setRoot

### ISSUE THREAD

**Issue by macklus** [mapsplugin/cordova-plugin-googlemaps#1698]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[X ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-googlemaps 2.0.0-beta3-20170830-1907 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
{}
```

**Current behavior:**
If i set map-page as home page, it works fine:
```js
rootPage: any = MapPage;
```

Problem appears when has another home page, and use nav.setRoot to open map page.
```js
constructor(public events: Events, public platform: Platform, public statusBar: StatusBar, public splashScreen: SplashScreen) {
        this.initializeApp();

        // used for an example of ngFor and navigation
        this.pages = [
            {title: 'Home', component: HomePage},
            {title: 'Map', component: MapPage},
            {title: 'Category', component: CategoryPage},
            {title: 'Us', component: UsPage},
            {title: 'List', component: ListPage},
        ];

        this.registerEvents();

    }

registerEvents() {
        // Events to move between pages
        //Home
        this.events.subscribe('openPage::Home', () => {
            this.openPage(this.pages[0]);
        });
        // Map
        this.events.subscribe('openPage::Map', () => {
            this.openPage(this.pages[1]);
        });
        //Category
        this.events.subscribe('openPage::Category', () => {
            this.openPage(this.pages[2]);
        });
        //Us
        this.events.subscribe('openPage::Us', () => {
            this.openPage(this.pages[3]);
        });
    }

    openPage(page) {
        // Reset the content nav to have just this page
        // we wouldn't want the back button to show in this scenario
        this.nav.setRoot(page.component);
    }
```
up are main component code, who uses setRoot to open page. I dont want to use nav.push because it is a main page, and not a children of

Also, i think is important note that GoogleMapsEvent.MAP_READY is fired always, even when page not load.

**Expected behavior:**
Map should appears when click on map page

**Steps to reproduce:**
Use nav.setRoot to move to map page

**Comment by wf9a5m75** [comment]
Please share your project files on github (or others)

**Comment by macklus** [comment]
Yo can get it on https://github.com/macklus/mapsplugin-error

**Comment by wf9a5m75** [comment]
Thank you. Check it later.

**Comment by wf9a5m75** [comment]
By the way, try
```
        platform.ready().then(() => {
            setTimeout(this.loadMap.bind(this), 1000);
        });
```

**Comment by wf9a5m75** [comment]
Hey, this is not plugin's problem. It is CSS problem ( = your mistake).

![screen shot 2017-08-31 at 4 01 31 pm](https://user-images.githubusercontent.com/167831/29948811-d71d9804-8e65-11e7-92ed-20a56b06d1d4.png)

**Comment by macklus** [comment]
Really, thanks ;-)

Let me check CSS and code before close. I update this ASAP

thanks in advance

**Comment by macklus** [comment]
Hi again:

I made a full app (based on sidemenu) to explain the problem i have:

You can find that on https://github.com/macklus/ionic-mapsplugin
Also, i deploy a new Google Api Keys to ensure it works fine.

You can reproduce the bug by do:

- Compile the app. You see the map works fine
- In app.component.ts line 16, change code
```
rootPage: any = MapPage;
```
by
```
rootPage: any = HomePage;
```
Run the app again. You see a default page with a button. When you push it, map page load but map not show.

If you go to line 43 on app.component.ts, you can change the way mappage is load, but also it not works.

I dont think is a design bug, so far MapPage load if it is defined as RootPage, but dont load if not.

thanks in advance.

**Comment by wf9a5m75** [comment]
What is the root page? I'm ionic user.

**Comment by wf9a5m75** [comment]
And why do you need to use the map in the app.component section?

I guess map div is null. Because the page is not displayed

This line is null I guess.
```
 this.mapElement = document.getElementById('map');
```

**Comment by macklus** [comment]
@wf9a5m75 i suppose you are using "ionic serve" as test platform ? beware that didnt work fine on ionic serve

Try to run app from _ionic cordova run android_, so you can see who problem works.
if you need detailed instructiones, let me know

Again, problem is "Map not show if map page is redirect from, but works if is main app page". Map works if i set map page as main page, so i dont think is a style or html mistake

thanks in advance

**Comment by wf9a5m75** [comment]
ionic serve is not supported.

**Comment by macklus** [comment]
@wf9a5m75 i just ask if you are using ionic serve.

Can you reproduce the bug using test repo i give you ? 
what steps are you using to test this bug ?

Thanks in advance

**Comment by wf9a5m75** [comment]
And did you understand what I said ` this.mapElement = document.getElementById('map');`?

In order to use the native plugins, you `must` wait the deviceready event using `platform.ready()`.

And **also the map div should not be null**.

At this code,
```
    constructor(private googleMaps: GoogleMaps, public platform: Platform) {

        // Wait the native plugin is ready.
        platform.ready().then(() => {
            console.log("platform ready");
            this.loadMap(); 
        });
    }

  loadMap() {
    this.map = this.googleMaps.create('map_canvas');   <--- 'map_canvas' is null

    this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
      console.log('map is ready');
    })
  }
```

**Comment by wf9a5m75** [comment]
You `have to wait both` **platform.ready()** and ** ionViewDidLoad**.

**Comment by wf9a5m75** [comment]
In actual case, this code is enough

```
  ionViewDidLoad() {
    setTimeout(this.loadMap.bind(this), 1000);
  }
```

**Comment by macklus** [comment]
Use ionViewDidLoad do the trick
really thanks !
