### ISSUE TITLE
hideInfoWindow() does not set infoWindowShown value to false on marker

### ISSUE THREAD

**Issue by Guchster** [mapsplugin/cordova-plugin-googlemaps#1699]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ x ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[ x ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ x ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.0.0-beta3-20170828-1830 "cordova-plugin-googlemaps"
```

**Current behavior:**
When the hideInfoWindow() method is called it does not set the infoWindowShown value to false, therefore if the isInfoWindowShown() method is called it will return true (if the showInfoWindow() method has been called at least once)

**Expected behavior:**
When the hideInfoWindow() method is called it should set the infoWindowShown value to false .

**Steps to reproduce:**
1. Add the maps plugin
2. Add a marker
2. Add a MARKER_CLICK event listener on the marker
3. Alternate between show and hide marker's infoWindow when marker clicked (see code below), through isInfoWindowShown() verification.
5. Click the marker several times, and at some point it will remain hidden

**Related code, data or error log (please format your code or data):**

```
this.map.addMarker(markerOptions, (marker) => {
      marker.on((<any>window).plugin.google.maps.event.MARKER_CLICK, () => {
        if (marker.isInfoWindowShown()) {
          marker.hideInfoWindow();
        } else {
          marker.showInfoWindow();
        }
      });
    });
```

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
Please create a demo project and share it. This saves my work time a lot.

**Comment by Guchster** [comment]
No problem!, @wf9a5m75 I shared you the repo

**Comment by wf9a5m75** [comment]
Thanks! I will check it tomorrow.

**Comment by wf9a5m75** [comment]
Sorry, I recognized this is a bug, but I haven't enough time to debug deeply today. I will check this tomorrow.

**Comment by Guchster** [comment]
Don't worry about it, is not an urgency

**Comment by wf9a5m75** [comment]
Actually this code is not good.

```
      marker.on((<any>window).plugin.google.maps.event.MARKER_CLICK, () => {
        if (marker.isInfoWindowShown()) {
          marker.hideInfoWindow();
        } else {
          marker.showInfoWindow();
        }
      });
```

Because the plugin (correctly the native API) does this automatically.

**Comment by Guchster** [comment]
You are right, I will remove that code, however you have to click the marker two times for the infoWindow to show, and only one for it to disappear, any idea on how to correct this behavior?

**Comment by wf9a5m75** [comment]
This is a bug of the Google Maps Android API v2.
https://stackoverflow.com/questions/14415548/second-tap-click-on-marker-doesnt-call-onmarkerclicklistener

As far as I tested, the Google Maps Android API v2 involves `onMapClick` instead of `onMarkerClick` for second and third times when you tap on the same marker.
![screen shot 2017-09-03 at 3 07 09 pm](https://user-images.githubusercontent.com/167831/30007017-11f71332-90ba-11e7-9cc8-29ecdc0505d8.png)

**Comment by Guchster** [comment]
That's just weird, But I can't see a workaround for it.
Thanks for the detailed explanation.
