### ISSUE TITLE
質問：getLicenseInfoについて

### ISSUE THREAD

**Issue by yuuki-ueno** [mapsplugin/cordova-plugin-googlemaps#1700]
I'm submitting a ... (check one with "x")
[*] question
[ ] any problem or bug report
[ ] feature request

plugin version: (check one with "x")
[ ] 1.4.x
[*] 2.0.0-beta3-20170831-1824

If you choose 'problem or bug report', please select OS: (check one with "x")
[*] Android
[ ] iOS

いつもお世話になっております。

質問させて下さい。

EnvironmentのgetLicenseInfoを呼び出したのですが、
「OK」という文字しか取得出来ません。

demoの「cordova-googlemaps-v2-demo_29.apk」をインストールして確認した際は
正常に表示されます。

2.0.0-beta3のバージョンとdemoのバージョンで、
何か違いがあったりするのでしょうか。

**Comment by wf9a5m75** [comment]
AndroidではGoogle Maps Android API v2でその機能が廃止されました。
つまりGoogle Maps Android APIの中で外部のライブラリはもう使わなくなった、ということです。

iOSでは引き続き、ライセンスの表示が必要ということでした。

(Googleに確認ずみ)

**Comment by yuuki-ueno** [comment]
ご回答ありがとうございます。
理解しました！

本件はクローズとさせて下さい。
