### ISSUE TITLE
After removing marker cluster by map.clear() newly added marker cluster not bind markers click callback fn on Android

### ISSUE THREAD

**Issue by lpikora** [mapsplugin/cordova-plugin-googlemaps#1701]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-googlemaps 2.0.0-beta3-20170831-1824 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```

**Current behavior:**
When marker cluster is removed from map calling `map.clear()`, all marker clusteres added to map after that not bind marker clicks callback function. 

**Expected behavior:**
When marker cluster is removed from map by `map.clear()`, newly added marker clusters should bind marker click callbacks.

**Steps to reproduce:**
Add marker cluster using `map.addMarkerCluster()` and put markers click event to it callback function:
```
markerCluster.on(plugin.google.maps.event.MARKER_CLICK, function (position, marker) {
  alert('marker click');
});
```
run `map.clear()`

Add add new marker cluster with the same code above.

Marker click event not firing callback function.

**Screen capture or video record:**
https://www.youtube.com/watch?v=4aCpI8tHtU8

**Related code, data or error log (please format your code or data):**

https://github.com/lpikora/cluster_test

**Comment by lpikora** [comment]
JS console outputs `-----> This is remained cluster icon : markercluster_69040575` 4 times after click on marker and click event is not fired. It happens only, when cluster is removed and then added to map again - with the same marker options array in `markes` property.

**Comment by wf9a5m75** [comment]
Fixed.
![1701_compressed](https://user-images.githubusercontent.com/167831/30043658-8996ff62-91ad-11e7-99cf-0f46942c223d.gif)

**Comment by lpikora** [comment]
thank you
