### ISSUE TITLE
MarkerCluster remove() method not work and break clustering on Android

### ISSUE THREAD

**Issue by lpikora** [mapsplugin/cordova-plugin-googlemaps#1702]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-googlemaps 2.0.0-beta3-20170831-1824 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```

**Current behavior:**
Calling markerCluster.remove() do not remove marker cluster from map. Marker clusterer also stop working after that.

**Expected behavior:**
Method remove() should remove marker cluster from map.

**Steps to reproduce:**
Call `markerCluster.remove() ` method on Android device.

**Screen capture or video record:**
https://www.youtube.com/watch?v=W6WgPvkWQHk&feature=youtu.be

Related code, data or error log (please format your code or data):
https://github.com/lpikora/cluster_test

**Comment by wf9a5m75** [comment]
Did you check there is any JS error?
I tested the same way before general available.
I guess there is some js error in your app.

**Comment by lpikora** [comment]
No JS error in Chrome Developer Tools console. I placed `debugger` in plugins MarkerCluster remove method definition `MarkerCluster.prototype.remove = function() {` and it reached it while executing.

**Comment by wf9a5m75** [comment]
ok. I will check it later

**Comment by wf9a5m75** [comment]
Fixed.
![1702](https://user-images.githubusercontent.com/167831/29988116-7280d648-8f20-11e7-8ab7-793c86c761b8.gif)
