### ISSUE TITLE
Problem when update form beta2 to beta3

### ISSUE THREAD

**Issue by carvemerson** [mapsplugin/cordova-plugin-googlemaps#1703]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.0.0-beta3-20170831-1824 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**

I create an Ionic project to show you some issues that appeared after I updated the googlemap plugin from beta2 to beta3. [Project Here](https://github.com/carvemerson/map).

 **First problem:**
When I open the navbar, I can't touch in the list of itens. 
Ok, I can disable and enable the map click with `map.setClickable()` when I open and close the menu, respectively. But in version beta2 it was not necessary.  Why in beta3 is necessary?

 **Second problem:**
I need to show the map in many pages. The project that I shared has a button in the top right of the header. Click than and a list is showed. When you click on a item of the list a new page with the map should appear, but it does not, it still white.  When I go back to the home, the map still white too.

In this project I have a provider `MapServiceProvider` where I will manipulate the instance of the map. 
When I will open any page with a map, I do  `mapServiceProvider.setDiv(el)`, where `el` is the HTML element, and the `setDiv()` method is:

```ts
setDiv(el: HTMLElement): Promise<any> {
    return new Promise<any>((resolve) => {

      if (!this.map) { 

        this.map = this.googleMaps.create(el);

        this.map.one(GoogleMapsEvent.MAP_READY).then(
          () => {
            resolve(this.map);
          }
        );

      } else if (this.map.getDiv() != el) { 
        this.map.setDiv(null);
        this.map.setDiv(el);
        this.map.clear();

        setTimeout(() => {
          resolve();
        }, 1000);

      } else { 
        this.map.clear();
        resolve();
      }
    });
  }
```
I'm using this method in the life cycle methods  `ionViewWillEnter()` or `ionViewDidLoad()`.
Something like this:
```ts
ionViewWillEnter() {
    this.mapServiceProvider.setDiv(this.mapElement.nativeElement).then(() => {
      //add markers, polyline, etc.
      this.mapServiceProvider.map.addMarker({
        position: new LatLng(0,0)
      });
    });
  }
```

The only one thing that appear in the debug console is: `Class not found`.

An alternative I found was to create a new map whenever I open a page, and delete it when I leave. but it is less expensive to use the set div. 

The funny thing is that it worked in beta2, but it does not work in beta3.

If you use the plugin util this commit e66cd25511a6adf3f8e9a7bb4e4bf7d9fe97164c the code works for the first problem, and partially for the second problem. It is beta3. 

Can you help me?

**Expected behavior:**

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
The reason of `The only one thing that appear in the debug console is: Class not found.` is the plugin is not loaded. You have to wait `platform.ready()`, or just wrap `setTimeout() { ... }, 1000);`

**Comment by wf9a5m75** [comment]
I just found another bug fix affect to other cases in couple minutes ago.
It seems this case also.

I fixed the code. Please reinstall the plugin, and try again.

**Comment by carvemerson** [comment]
Hi, I did what you sad, but the app does not work well. 
Look the modifications in the [project](https://github.com/carvemerson/map).
I think that the `map.setDiv()` is not working as should.

**Comment by wf9a5m75** [comment]
The platform.ready uses in the contractor usually.

You don't understand what is the platform.ready(), what is the problem your code.

Your code try to make a map when the native side is not ready or the map div is null.
This is really depends on the timing.
The platform.ready is faster sometimes, the view is ready sometimes.

That's why you need to wait both.

However most ionic users don't understand about this.

that's why your code becomes like this

```
ionViewDidLoad() {
    this.plt.ready().then(() => {
```
 As I describe this code works sometimes, but this code doesn't work sometimes. Because the platform.ready() is already done when the map view is ready.
After that the event is never fired.

For the people, setTimeout() is the most easiest solution.

https://github.com/wf9a5m75/ionic-googlemaps-demo/blob/master/src/pages/map/animate-camera/animate-camera.ts

**Comment by carvemerson** [comment]
I'm sorry, I forgot the height in the mapDetails. I will fix and test again.

**Comment by carvemerson** [comment]
OK, I updated the project. Now when I enter in the homePage the map appears normally, when I go to the mapDetails page the map appears (the error was the height of the mapDetail div), but when I come back to the homePage, the map still white. 

Now I'm using `setTimeout(this.loadMap.bind(this), 1000);` instead `this.plt.ready()`.

**Comment by wf9a5m75** [comment]
`class not found` means you tried to use the plugin before @ ionic-native/google-maps plugin is loaded.

**Comment by wf9a5m75** [comment]
Did you update your code?

**Comment by carvemerson** [comment]
Yes, did.

**Comment by wf9a5m75** [comment]
The maps plugin itself is only one times, but @ionic-native is loaded every pages.

**Comment by carvemerson** [comment]
I understand, but now, I'm doing this:

```ts
ionViewDidEnter() {
    this.plt.ready().then(() => {
      setTimeout(this.loadMap.bind(this), 1000);
    });
}
```
I'm waiting for `plt.ready()`, and using a `setTimeout()` inside them, and the map not load. 
The error still:

`"Class not found", source: file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/BaseClass.js (115)`

This error occurs only when I go to another page that use a map, and go back. 

So, the first `setDiv` work normally, but when I try to set it again, in any other page, the map still white. 
If you open the app, next open the list, click in any list item, a page with the map will open, then click in back button, and click in another list item. The map not work anymore.

**Comment by carvemerson** [comment]
Another interesting thing is, if I `remove()` and `create()` the map every load of any page, I do not need do this:

```ts
ionViewDidEnter() {
    this.plt.ready().then(() => {
      setTimeout(this.loadMap.bind(this), 1000);
    });
}
```

I only need do this:

```ts
ionViewDidEnter() {
 this.loadMap();
}
```
And the `setDiv` of the map-service.ts I change from

```ts
setDiv(el: HTMLElement): Promise<any> {
    return new Promise<any>((resolve) => {

      if (!this.map) {

      this.map = this.googleMaps.create(el);

      this.map.one(GoogleMapsEvent.MAP_READY).then(
        () => {
          resolve(this.map);
        }
      );

      } else if (this.map.getDiv() != el) {
        this.map.clear();
        this.map.setDiv(null);
        this.map.setDiv(el);
        resolve(this.map);

      } else {
        this.map.clear();
        resolve(this.map);
      }

    });
  }
```

to

```ts
 setDiv(el: HTMLElement): Promise<any> {
    return new Promise<any>((resolve) => {

      if (this.map) {
        this.map.remove();
      }

      this.map = this.googleMaps.create(el);

      this.map.one(GoogleMapsEvent.MAP_READY).then(
        () => {
          resolve(this.map);
        }
      );

    });
  }
```

and the app work normally, like I need. But the process of `remove()` and `create()` is much slower compared to `setDid()`.

What I do not understand is, why do I need to wait for `plt.ready()`, or `setTimeout()`, or both, in order to set the div, but if I create a new map it is not necessary?

**Comment by wf9a5m75** [comment]
setTimeout(this.loadMap.bind(this), 1000);

is enough

**Comment by wf9a5m75** [comment]
And didn't you understand what I describe?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1703#issuecomment-326814413

**Comment by carvemerson** [comment]
Yes, I understand, what you sad.

**Comment by carvemerson** [comment]
So, what am I doing wrong?
Why the `setDiv()` only in the first time?

**Comment by wf9a5m75** [comment]
I ill check that today

**Comment by carvemerson** [comment]
Thank you, I'll wait.

**Comment by wf9a5m75** [comment]
I found a reason. You need to `map.setDiv(null)` **before** the home page leave.

When the map div is removed, the map will be also removed automatically.
Thus, the map is already removed, when the code is executed.
```
this.map.clear();   <--- map is already removed. That's why `Class not found`.
this.map.setDiv(null);
this.map.setDiv(el);
```

**Comment by wf9a5m75** [comment]
Please reinstall the plugin, and you also need to write `map.setDiv(null)` in the `ionViewWillLeave()` 

```TypeScript
  ionViewWillLeave() {
    this.mapServiceProvider.map.setDiv(null);
  }
```

![1703_optimized](https://user-images.githubusercontent.com/167831/30039398-0377634a-9185-11e7-86bc-a19b42f45892.gif)

**Comment by carvemerson** [comment]
Thank you very much!!! 
All problems were fixed!!
