### ISSUE TITLE
'clear' is not defined in GoogleMaps plugin

### ISSUE THREAD

**Issue by minhui27** [mapsplugin/cordova-plugin-googlemaps#1705]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[x ] **1.4.5**
[ ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
branch-cordova-sdk 2.6.0 "branch-cordova-sdk"
code-push 2.0.1-beta "CodePushAcquisition"
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-code-push 1.9.5-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 1.4.5 "cordova-googlemaps-plugin"
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.1.2 "OneSignal Push Notifications"
```

**Current behavior:**
This bug only happen when I din't touch the app or device for few minutes. The behavior of my app is where it will keep searching for new items when the center of map has big changes. The marker of old items will be removed first, and then the marker of new items will be added into the map. Every time when the map is trying to remove the markers (I used the ```map.clear()``` method to remove all markers), the error ``` 'clear' is not defined in GoogleMaps plugin ``` will happen. As a result, the markers on the map was a lot (may up to 500++ markers) and the map become very lag.

**Expected behavior:**
All the markers can be removed and added repeatedly without any error.

**Comment by wf9a5m75** [comment]
Because you use the `cordova-plugin-googlemaps 1.4.5` with `@ ionic-native/google-maps` plugin. You need to use `cordova-plugin-googlemaps 2.0-beta3`

**Comment by minhui27** [comment]
I do try the ```cordova-plugin-googlemaps 2.0-beta3``` plugin too, but I found that the response of plugin 2.0-beta3 much slower than the plugin 1.4.5.

**Comment by wf9a5m75** [comment]
It's depends on your code.

**Comment by wf9a5m75** [comment]
And **without** the ionic wrapper plugin is faster
