### ISSUE TITLE
Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#1707]
Someone know what can be reasons for this error? it appears when i load markers and when i click on them but after a few seconds of working correctly.
Please help

**Comment by wf9a5m75** [comment]
It is depends on your code. Please share your project files on github or others.
(No zip file is acceptable)

**Comment by francoro** [comment]
i debugged my code with breakpoints and the error appear here when map.addMarker(markerOptions) is called after a few times

```
addCluster(map, locations, isCluster, zoom, isWatching?) {
        return new Promise((resolve) => {
            let __this = this;

            this.removeMarkers(map, isWatching);
            this.locations = [];
            this.locations = locations;
            this.platform.ready().then(() => {
              

                if (!isCluster) {
                
                    this.markers = [];
                    for (let i = 0; i < locations.length; i++) {
                        let latlng: LatLng = new LatLng(locations[i].lat, locations[i].lng);
                        let markerOptions;

                        markerOptions = {
                            position: latlng,
                            data: locations[i].id,
                            disableAutoPan: true,
                            icon: {
                                url: "assets/marker-imagen/marker.png",
                                size: {
                                    width: 15,
                                    height: 15
                                }
                            }
                        };



                    
                    
                        map.addMarker(markerOptions)
                            .then((marker) => {
                                marker.addEventListener(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {

                                    let propertyId = marker.get("data");
                                
                                    __this.service.broadcast({
                                        name: 'mapPreview',
                                        message: propertyId
                                    });
                                })
                            });
                        //this.markers.push(marker);

                    }

                    resolve(true);

**Comment by wf9a5m75** [comment]
Code is not enough to test at my side. Please commit your project files on github tomorrow, then I will check it.

**Comment by francoro** [comment]
Right now my boss says its not an option to give you the repo because he is in a hurry and well there is nothing i can do about it. But maybe with the code above you can give me reasons of why that error happen and maybe that can help me. I try to found that error message and it s not in the plugin, that is weird for me because where is taken it from then?.Like i said above the error appear in that line of code

`map.addMarker(markerOptions)`

but only after work correctly a number of times. So if you can give me the reasons of that error that would help me

**Comment by wf9a5m75** [comment]
As I said above, the code is not enough to detect the reason.
You need to create a demo project at least.
Otherwise, I will close this thread because no enough information.

**Comment by francoro** [comment]
I will try to update to the last version of the plugin. the last time i had a problem with my custom clusters made from canvas.But now i see in the docs that the native clusters are ready to use. Is this for ios too?
And for use it i have to install the multiple_maps branch: cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps

**Comment by francoro** [comment]
I update the version of the plugin to its lastest and now it works

**Comment by wf9a5m75** [comment]
The maker cluster works on both OS, Android ans iOS, if you use correctly
