### ISSUE TITLE
Monacaデバッガーにてデバッガーメニューボタンが押せなくなる

### ISSUE THREAD

**Issue by yesman99** [mapsplugin/cordova-plugin-googlemaps#1710]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3-20170905-1257**

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

お世話になっております。
最新バージョン（2.0.0-beta3-20170905-1257）にてMonacaカスタムデバッガーをビルドしたところ、
添付スクリーンショット右下の"Monacaデバッガーメニューボタン"をタップしても反応しなくなりました。
以前用意いただいた、こちらのサンプルプロジェクト↓でも同様の現象が確認できています。
[hello-googlemaps-for-monaca.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1279557/hello-googlemaps-for-monaca.zip)

お手数をおかけしますが、よろしくお願いいたします。

**Screen capture or video record:**
<img src="https://user-images.githubusercontent.com/6134076/30091745-36cda4da-92f6-11e7-9c29-dfc048d71eb3.PNG" width="300">

**Comment by wf9a5m75** [comment]
なんと!

**Comment by wf9a5m75** [comment]
このDebugボタンはHTML要素ではないですね。以前は押せましたか？
Androidでは押せていた記憶はありますが、iOSでは押した記憶が無いので定かではないです

**Comment by yesman99** [comment]
以前は押せました。
19日前の8/18 17:18にデバッガーアプリを最後にビルドしているのですが、それは正常に動いていました。

**Comment by wf9a5m75** [comment]
具体的なプラグインのバージョンまでは分からないですよね

**Comment by yesman99** [comment]
そうですね。。Monacaですといろいろとチェックしましたが確認できませんでした。
今Androidでも確認したところ、タップはできるのですが、何故か"重なり"が一番前では無くなっていました。
![2017-09-06 14 28 21](https://user-images.githubusercontent.com/6134076/30095781-ad353d9a-930f-11e7-8458-2a32d0f313cb.png)

**Comment by wf9a5m75** [comment]
うーん、予想ですが、Monacaのデバッガが変わった可能性が高いですね。

**Comment by wf9a5m75** [comment]
確認をさせていただきたいのですが、現在使用しているCordova CLIのバージョンは6.2.0ですか？それとも6.5.0ですか？

**Comment by wf9a5m75** [comment]
Cordova CLI 6.2.0モードでビルドすると、ちゃんとデバッグボタンがHTMLの上に表示されます。

```html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta http-equiv="Content-Security-Policy" content="default-src * data:; style-src * 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'">
    <script src="components/loader.js"></script>
    <link rel="stylesheet" href="components/loader.css">
    <link rel="stylesheet" href="css/style.css">
<script type="text/javascript">
var map;
document.addEventListener("deviceready", function() {
  var div = document.getElementById("map_canvas");

  // Initialize the map view
  map = plugin.google.maps.Map.getMap(div);

  // Wait until the map is ready status.
  map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
}, false);

function onMapReady() {
  alert("map is initialized!");
}

</script>
<style type="text/css">
    html,body,#map_canvas {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
    }
    #testBtn {
        position: absolute;
        right: 50px;
        bottom: 50px;
        width: 50px;
        height: 50px;
        border: 1px solid red;
        background-color: red;
    }
</style>
</head>
<body>
	<div id="map_canvas">
        <div id="testBtn"></div>   
	</div>
</body>
</html>
```
![capture](https://user-images.githubusercontent.com/167831/30096459-4e9600a8-928d-11e7-83f5-4f60993622c4.png)

**Comment by yesman99** [comment]
6.2.0と、6.5.0で確認しております。
2.0.0-beta3-20170905-1257より以前のバージョンを入手することは可能でしょうか？

**Comment by wf9a5m75** [comment]
ここから自分が使いたいgitコミットを探します。
https://github.com/mapsplugin/cordova-plugin-googlemaps/commits/multiple_maps

例えば19日前ならこのコミットになります。
https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/cb30d1901d512362a576d70e4f96d807d02e3269

MonacaでプラグインのURLを指定する際に
https://github.com/mapsplugin/cordova-plugin-googlemaps#cb30d1901d512362a576d70e4f96d807d02e3269 とコミットIDを指定すれば可能です

**Comment by wf9a5m75** [comment]
先程のコードをCordova CLI 6.5.0でビルドすると、デバッグボタンが表示されませんね。
![capture](https://user-images.githubusercontent.com/167831/30096645-7e1b1704-928e-11e7-885a-321171859a9a.png)

**Comment by wf9a5m75** [comment]
iOSはOSにiOS11をインストールしてあるので、Cordova CLI 6.2.0でテストできないですが、Cordova CLI 6.5.0でビルドすると確かにデバッグボタンは押せません。

**Comment by yesman99** [comment]
先程ご教授いただいた、19日前のコミットでビルドしたところ、iOSにてボタンがタップ出来ることが確認できました。
https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/cb30d1901d512362a576d70e4f96d807d02e3269

**Comment by wf9a5m75** [comment]
私の方だと、デバッグメニューは見えるのですが地図が表示されないですね。
すみませんが、どのコミットで押せなくなるか探していただけますか。
アメリカはもう23時なので、そろそろ寝る時間なのです

**Comment by wf9a5m75** [comment]
どのコミットで不具合が導入されたか特定ができれば、それを元に対応します。
かなり大変な作業になると思いますが、よろしくお願いします。

**Comment by yesman99** [comment]
夜遅くまで対応いただきありがとうございました。
こちらのコミットからボタンが押せなくなっていました。
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/f4d29fb2c1d92bbc12bb3db65f92187a6191d9be

**Comment by wf9a5m75** [comment]
ありがとうございます。あとで調べてみます

**Comment by wf9a5m75** [comment]
たしかに、一つ前のコミットである #b919aea3 では、ちゃんとデバッグメニューが押せますね

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/b919aea30203644079f000afe40ec66699f5044c はどう見てもAndroidのコードだったので、これではないだろうと、`4bd31d3`のグラフを調べると、

https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/923f6282596f8ec8ac632076ee6c3add9648808c のコミットからタップできないですね。その一つ前のhttps://github.com/mapsplugin/cordova-plugin-googlemaps/commit/da2df4f56b41a3ca0e87b6919a242e8564786e46 まではタップできます。

それをもとに、JSを試してみたのですが、どうも効果がないですね。
そもそもデバッグボタンは、HTMLではないので影響はないはず。
でも確かに押せないんですよね。なぜか。
かなり苦戦しています。

そしてMonacaの試用期間が今日で切れるので、アシアルさんに試用期間の延長をお願いしているところです。

**Comment by wf9a5m75** [comment]
現在、https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/da2df4f56b41a3ca0e87b6919a242e8564786e46 のコミットとmasterを比較して変更点があるファイルを一つずつgitにコミットして、どのファイルでタップできなくなるかテストしてみました。
どうやらCordovaGoogleMaps.m が原因のようです。

**Comment by wf9a5m75** [comment]
とりあえずiOSはタップできるようになりました。正直、なぜこのコードの修正で...って感じですが。
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/836a520682c8daa625eadc1cd2fdaf8521bd168f

![screen shot 2017-09-07 at 12 02 07 am](https://user-images.githubusercontent.com/167831/30150337-d4f524f8-935f-11e7-8e82-0acb98b37e21.png)

**Comment by wf9a5m75** [comment]
Androidは最初に「Permit drawing over other apps」を許可にしてあげたら、デバッグボタンがちゃんと押せますね。
![issue1710](https://user-images.githubusercontent.com/167831/30152643-9fcc3e48-9368-11e7-84a1-ed4971f35bc8.gif)

**Comment by wf9a5m75** [comment]
multiple_mapsブランチのコードでビルドしてください。
（そして私はもう寝ます  1:08am now）
