### ISSUE TITLE
MarkerCluster: Cannot get the information of marker on click

### ISSUE THREAD

**Issue by minhui27** [mapsplugin/cordova-plugin-googlemaps#1711]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.0.3 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
The information of marker cannot be retrieved when the marker is click.

Here is the link of example: [map-v2-testing](https://github.com/minhui27/map-v2-testing)

**Comment by wf9a5m75** [comment]
This line is wrong


      markerCluster.on(GoogleMapsEvent.MARKER_CLICK).subscribe((marker) => {
        

And you need to use @ ionic-native / core 4.1.2, not 3.12.1

**Comment by minhui27** [comment]
That line is correct. But it is solved when I update the @ionic-native/core & googlemaps to the latest version.
Thanks.

**Comment by wf9a5m75** [comment]
@minhui27 No. The MARKER_CLICK event of the marker cluster passes two values as array.

```
      markerCluster.on(GoogleMapsEvent.MARKER_CLICK).subscribe((params) => {
        let latLng: LatLng = params[0];
        let marker: Marker = params[1];

        marker.setAnimation(GoogleMapsAnimation.BOUNCE);
      });
```
https://github.com/wf9a5m75/ionic-googlemaps-demo/blob/master/src/pages/marker-cluster/add-marker-cluster/add-marker-cluster.ts#L77-L82

**Comment by minhui27** [comment]
Ya. I got it.
Thanks.

**Comment by minhui27** [comment]
Hi, @wf9a5m75 .
This error exists again when I update the plugin, `` @ionic/native/core & googlemaps`` to the latest version.
When the marker is clicked, the return value for the Marker (params[1]) was undefined.

![capture](https://user-images.githubusercontent.com/18694106/31041579-31b1e114-a5ca-11e7-8ecd-24a2dd8e9716.JPG)
