### ISSUE TITLE
Maps plugin intercept touch event of other plugins

### ISSUE THREAD

**Issue by jleuleu** [mapsplugin/cordova-plugin-googlemaps#1713]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** (2.0.0-beta3-20170905-1257)

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crashlytics 3.8.5 "CrashlyticsPlugin"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta3-20170905-1257 "cordova-plugin-googlemaps"
cordova-plugin-pixlive 1.3.2 "PixLive"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
On iOS, the map plugin intercepts the touch events of other plugins that are below the map plugin even if no map is displayed.

The view stack is the following (from back to foreground):
- Other plugin view (in my case a camera view (cordova-plugin-pixlive))
- Map plugin
- HTML app

I set the map background as transparent otherwise we don't see the camera view (`setBackgroundColor('rgba(0,0,0,0)')`). But I did not find a way to send touch events to the camera view which is below the map. The map plugin intercepts all the touch events.

**Expected behavior:**
If no map is displayed, the map plugin should not block the touch events targeted to other cordova plugins. If the map view is not present when there is no map to displayed, it would not block the touch events.

**Comment by wf9a5m75** [comment]
I don't support the compatibility with other plugins.
Because it needs to work so much time.

If you want to use it, please use the Google Maps JavaScript v3.

**Comment by wf9a5m75** [comment]
I saw the cordova-plugin-pixlive. It uses the same way as this plugin (more simple though).

Both plugins inspect the touch event. Thus, you need to choose one of them. This is the limit of hybrid application.
(If you write your application in native language, there is a solution. If you don't want to try it, choose one of them)
