### ISSUE TITLE
Color of MarkerCluster

### ISSUE THREAD

**Issue by minhui27** [mapsplugin/cordova-plugin-googlemaps#1714]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[x] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.0.3 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
Color of markerCluster cannot be changed. This caused the number is not very clear if the image is in dark color.

![screenshot](https://user-images.githubusercontent.com/18694106/30105418-17459750-932b-11e7-8075-5869b343c98e.jpg)

**Expected behavior:**
The color of markerCluster can be changed.

**Comment by wf9a5m75** [comment]
Yes, actually it's possible. The document page is not ready yet though (I'm so busy)

```js
map.addMarkerCluster({
      markers: data,
      icons: [
        {
          min: 3,
          url: "./assets/cluster.png",
          anchor: { x: 16, y: 16 },
          label: {
            color: "white",
            bold: true,
            fontSize: 14
          },
          size: {
            width: 37,
            height: 37
          }
        }
      ]
    }
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1679
