### ISSUE TITLE
iOS 11 map shifted down

### ISSUE THREAD

**Issue by craig-at-rsg** [mapsplugin/cordova-plugin-googlemaps#1716]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[x] **1.4.x**
[ ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

~/code/rPlace/aardvark-ios: cordova plugin list
com.googlemaps.ios 1.13.0 "Google Map iOS SDK for Cordova"
com.rsginc.exceptionthrower 1.0.0 "Exception Thrower"
com.rsginc.mobilesurvey 1.0.0 "Trip Recorder guts"
cordova-fabric-plugin 1.1.1 "cordova-fabric-plugin"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-preferences 0.99.3 "AppPreferences"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 4.0.4 "CDVBackgroundFetch"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-dbcopy 1.0.4 "sqlDB"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.2 "File Transfer"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-localization-strings 1.0.1 "Localization"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
plugin.google.maps 1.3.9 "phonegap-googlemaps-plugin"

**Current behavior:**

Map shifted down in iOS 11, possibly by the height of the status bar.

**Expected behavior:**

Map shows in its container instead of being shifted down.

**Steps to reproduce:**

?

I tried with and without the StatusBar plugin - still had the issue. 

**Screen capture or video record:**
![screen shot 2017-09-06 at 11 45 18 am](https://user-images.githubusercontent.com/6004181/30121229-20e3b904-92f9-11e7-83c1-78bd97c2b9d4.png)

**Related code, data or error log (please format your code or data):**

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1688

**Comment by wf9a5m75** [comment]
This is not plugin's bug. It is the status bar plugin's bug.
https://github.com/apache/cordova-plugin-statusbar/blob/master/src/ios/CDVStatusBar.m#L476

**Comment by craig-at-rsg** [comment]
Thank you for the quick response, but I see this with or without the StatusBar plugin installed, and it's only for iOS 11 - iOS 10 and various versions of Android work fine.

**Comment by wf9a5m75** [comment]
Then why do you share the image of Android?

**Comment by craig-at-rsg** [comment]
That's iOS.

**Comment by wf9a5m75** [comment]
The `plugin.google.maps 1.3.9` is deprecated. No more support.

**Comment by craig-at-rsg** [comment]
Ok, thank you, I'll upgrade.

**Comment by craig-at-rsg** [comment]
This was a problem with the plugin version 1.3.9 and iOS 11; it does not seem to be a problem with plugin version 1.4.5.

**Comment by wf9a5m75** [comment]
Thank you for letting me know.
By the way, v1.4.5 is also deprecated.
