### ISSUE TITLE
Maker event MARKER_DRAG_END is not working (with Ionic Native)

### ISSUE THREAD

**Issue by itanhduy** [mapsplugin/cordova-plugin-googlemaps#1720]
**I'm submitting a ...**
[ ] question
[X] any problem or bug report
[ ] feature request

**The plugin version:**
[ ] 1.4.x
[X] 2.0.0-beta3

**If you choose 'problem or bug report', please select OS:**
[X] Android
[ ] iOS

**cordova information:**
```
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-clipboard 1.0.0 "Clipboard"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 1.4.5 "cordova-googlemaps-plugin"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
```

**Current behavior:**
After adding map I've added maker then trying to catch the event MARKER_DRAG_END then test on device (**Samsung Galaxy J7 Prime**) but event is not trigger.

**Expected behavior:**
After adding map I've added maker then trying to catch the event MARKER_DRAG_END then test on device then hope event is trigger.

Steps to reproduce:
**Setup map, then call map.addMarker:**

```TypeScript
> 
    this.addMaker = function (mapCreated, coordinates, id, canDraggable = false, cb) {
      // Create maker with options
      let makerOptions : MarkerOptions = {
        position: new LatLng(coordinates.coords.latitude, coordinates.coords.longitude),
        icon: {
          url: id === self.optionService.default.self
            ? self.optionService.default.pinMe
            : self.optionService.default.pinOther,
          size: {
            width: 48,
            height: 48
          },
          optimized: false
        },
        draggable: canDraggable
      };
      mapCreated
        .addMarker(makerOptions)
        .then((maker : Marker) => {
          self
            .listMakers
            .push({id: id, maker: maker});
          if (canDraggable) {
            maker.setDraggable(true);
            // Trying to call this event. But it's not working console.info(result) didn't
            // run
            maker
              .addEventListener(GoogleMapsEvent.MARKER_DRAG_END)
              .subscribe((result : any) => {
                console.info(result);
              });
            // Trying to call this event. But it's not working console.info(result) didn't
            // run
            maker
              .on(GoogleMapsEvent.MARKER_DRAG_END)
              .subscribe((result : any) => {
                console.info(result);
              });
          }
        });
    }
```
Possible solution:
I've tried all the ways but nothing happens.

**Addtional Information**

```TypeScript
    // Setup map map: Element position: It's including lat and lng zoomSize: Number
    this.setupMap = function (map, position, zoomSize = 10) {
      let mapElement = document.getElementById(map);
      let mapOptions : GoogleMapOptions = {
        camera: {
          target: {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          },
          zoom: zoomSize,
          tilt: 30
        },
        controls: {
          mapToolbar: true,
          compass: true,
          indoorPicker: true
        }
      };

      let mapInstance : GoogleMap = this
        .googleMaps
        .create(mapElement, mapOptions);
      // Clear map before you want do something else
      mapInstance.clear();
      return mapInstance;
    }
```
Thanks in advance.

**Comment by wf9a5m75** [comment]
What version of the `@ionic-native/core` and `@ionic-native/google-maps` do you use?

**Comment by itanhduy** [comment]
Hi @wf9a5m75,

According to package.json here is the version of `@ionic-native/core` and `@ionic-native/google-maps`

`"@ionic-native/core": "^3.7.0"`
`"@ionic-native/google-maps": "^4.2.1"`

**Comment by wf9a5m75** [comment]
You need to use `@ionic-native/core` 4.2.0

**Comment by itanhduy** [comment]
Hi @wf9a5m75 ,

Thanks for response. I'll try. Will feedback soon.

Thank you.

**Comment by itanhduy** [comment]
Hi @wf9a5m75 ,

I've updated `@ionic-native/core` to version 4.2.0 but It's still not working.

May you advise?

Thanks ;)

**Comment by wf9a5m75** [comment]
Oh, sorry. I'm wrong. I mean `4.2.1`

**Comment by itanhduy** [comment]
@wf9a5m75 ,

Sorry. I forgot. I meant 4.2.1

**Comment by wf9a5m75** [comment]
Ok, please share your project files on github. I will check it.

**Comment by itanhduy** [comment]
I've updated to 4.2.1

![Ionic core version](https://image.ibb.co/kOYy6v/Screen_Shot_2017_09_09_at_14_27_48.png)

**Comment by wf9a5m75** [comment]
As I wrote above `please share your project files on github`

**Comment by itanhduy** [comment]
Hi @wf9a5m75 ,

Kindly check it here: [Add Maker](https://github.com/itanhduy/addmaker)

**Comment by itanhduy** [comment]
Hi @wf9a5m75 ,
I've just worked around this issue and now it's working.
I've updated cordova-plugin-googlemaps plugin to version 2.0.3-beta.

Thanks for your help ;)

**Comment by wf9a5m75** [comment]
Ah you used `cordova-plugin-googlemaps 1.4.5 "cordova-googlemaps-plugin"`.
I didn't notice that.
That's make sense.
