### ISSUE TITLE
Probable missing doc/feature request - myLocationButton callback

### ISSUE THREAD

**Issue by AmitMY** [mapsplugin/cordova-plugin-googlemaps#1722]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[x] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-add-swift-support 1.7.0 "AddSwiftSupport"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.0 "cordova-plugin-googlemaps"
cordova-plugin-nativegeocoder 1.0.2 "NativeGeocoder"
cordova-plugin-recentscontrol 1.1.0 "RecentsControl"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-deploy 0.6.7 "IonicDeploy"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please show me the package.json**
[Link to package](https://pastebin.com/EtEyWPAe)

**Current behavior:**
The "my location" button always goes back to my location.

**Expected behavior:**
To have a callback method of "where" to go to, for apps that do custom location (my use case: I let the user choose a location, so when they press this button, they should fly there and not to their real location)

**Comment by wf9a5m75** [comment]
The location button comes from the native api. Not this plugin.

And implementation of this  "To have a callback method of "where" to go to, for apps that do custom location (my use case: I let the user choose a location, so when they press this button, they should fly there and not to their real location)" is your task.

You can create a custom button with html and css.
Then open a dialog for example.
That's completely your task.

**Comment by AmitMY** [comment]
Fair enough, I'll make an overlay
