### ISSUE TITLE
Marker’s infoWindow is not opened when clicking on another marker and back on iOS using marker cluster.

### ISSUE THREAD

**Issue by lpikora** [mapsplugin/cordova-plugin-googlemaps#1723]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 
[x] 45c468099b4c472d832424e8c061f089aac1b544

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-googlemaps 2.0.6 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```

**Current behavior:**
When using marker cluster, clicking on marker opens info window. When you click on another marker its info window is opened and previous info window is closed. Clicking back on the first marker does not open info window.

Or

Clicking on one marker repatedly opens info window only for first click. Then info window is closed and cant be opened by another click.

**Expected behavior:**
Should open info window every time marker is clicked. 

**Screen capture or video record:**
https://photos.app.goo.gl/tdtYmCDqU8CON8q22

**Related code, data or error log (please format your code or data):**
https://github.com/lpikora/cluster_test

**Comment by wf9a5m75** [comment]
Okay, I will check this later.

**Comment by wf9a5m75** [comment]
Thank you for reporting the bug. I fixed it.
![1723_uncompress](https://user-images.githubusercontent.com/167831/30310740-d082a46e-9746-11e7-9573-442fd01c29f1.gif)

**Comment by lpikora** [comment]
Thank you for the fix.
