### ISSUE TITLE
MarkerCluster configuration

### ISSUE THREAD

**Issue by Luttik** [mapsplugin/cordova-plugin-googlemaps#1724]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[ x ] feature request

**The plugin version:**  (check one with "x")
[ x ] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

# MarkerCluster configuration.
Hé it's great that we can cluster markers on the map, but there are 2 things I would love to be able to configure. 

1.  How far it zooms on click. (In my opinion it usually zooms just slightly to far creating a situation where the icons of the markers in the cluster go over the border of the screen).
2. The greediness of clustering. In the sense that as is I'd like to have more clusters of less items. Having the option to configure this would be great.

**Comment by wf9a5m75** [comment]
1.

Do you mean you want to make a space between viewport and markers when you click on the cluster marker?

2.

Could you explain more details?

**Comment by Luttik** [comment]
1. Yes I want to maintain some space. (especially the case where you have jus 2 markers in a cluster and they both end up at the very border of the view feels odd.)
2. There are scenarios where only one clustericon is shown for a lot of markers that are actually quite far apart. Giving the illustion that the items are way more tightly grouped than they are. 

Currenly I use big icons to hide the effect a bit, but its still clear here where England has 1 cluster that when clicked contains markers in Ireland and England. (these screenshots are the approx the size of my phones screen)

![screenshot_20170908-170214](https://user-images.githubusercontent.com/6634187/30217960-03c2f7c0-94b8-11e7-8293-545fa19696d7.png)  ![screenshot_20170908-170221](https://user-images.githubusercontent.com/6634187/30217963-061f95d2-94b8-11e7-9a2e-969defb899ec.png)

**Comment by wf9a5m75** [comment]
The request 1 might be acceptable. But the request 2 is not acceptable.

The marker cluster is calculates based on the grid mechanism.
(Although there are another algorithms, I chose this algorithm because it is the best calculate performance).

![](https://cloud.githubusercontent.com/assets/167831/26082455/eeaccbba-3984-11e7-9529-7895f43507b3.gif)

England and Ireland are close. 
So if the map zoom level is small value, England and Ireland are in the same grid. That's why.

**Comment by Luttik** [comment]
Would it be possible to get square grids? I think that would improve the look and feel.

**Comment by wf9a5m75** [comment]
No.

**Comment by wf9a5m75** [comment]
If you implement the "square grids" code, and send it as a pull request, I will test and merge it.
Otherwise, no plan to implement another algorithm right now.

**Comment by wf9a5m75** [comment]
I tested couple of cases, but the best way to separate markers in England and Ireland, creating two marker clusters is the best and easiest solution.
