### ISSUE TITLE
Overlapping Marker Spiderfier

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#1725]
i have a suggestion of a good feature for your plugin. Look at this demo (click on the markers) https://jawj.github.io/OverlappingMarkerSpiderfier/demo-1.html

this is the repo https://github.com/jawj/OverlappingMarkerSpiderfier

In my case i have this problem of markers that overlapping each other it will be nice to have this feature i think its very useful.

**Comment by wf9a5m75** [comment]
If you donate $1,000 USD, I will create it.

**Comment by francoro** [comment]
It was just a suggestion if maybe you just run out of ideas to improve your plugin in some future.I though maybe i could be helpful

**Comment by wf9a5m75** [comment]
Idea is fun. But don't forget someone have to work to implement the feature.
The someone have to spend thier time to implement, and test it.

And for me, even if I don't implement it, I have to support the feature if it has some problems after merging the code.

That's why I always ask 1,000USD for the feature request.

Actually the amount is very cheap. I spent almost 4 months to implement the marker cluster.
I faced so much troubles than I expected.
So for me, 1,000USD is too cheap.

**Comment by francoro** [comment]
I understand maybe in some feature I will donate.You can close this.

**Comment by wf9a5m75** [comment]
Thank you for your understanding.

**Comment by MaxInMoon** [comment]
@wf9a5m75 could you create a mini-crowd funding box? If it doesn't reach the amount before a date, everybody take back is money, etc.
10 people would easily put 100$ each. 
@francoro What do you think?

**Comment by wf9a5m75** [comment]
@MaxInMoon Well, do you really consider this is really necessary feature?
Because mobile device has smaller space than PC.
And the maps plugin has already default marker cluster feature.

Even if you really really want to use this feature, please make a fundraising at https://www.bountysource.com/

**Comment by MaxInMoon** [comment]
@wf9a5m75 I have one exemple of use case where  the feature seems réacquiers, and it could happen oftenly I guess:

Users can create « dinners / lunch / breakfast » at a specific date time/address.
Other users want to see all food events around them on their map.
On a case like this you cannot see more than one market (food event) per address, even if the cooker user has many events in the day/week.

Am I wrong?

**Comment by wf9a5m75** [comment]
Do your best with provided features, or implement the feature and send it as PR.
I don't think `Marker Spiderfier` is the best answer for your case.
You should implement another ways, such as `open a dialog` or `open a next page`.
