### ISSUE TITLE
Failed to fetch plugin

### ISSUE THREAD

**Issue by khalilbenn** [mapsplugin/cordova-plugin-googlemaps#1729]
Getting an error using this command on ionic project and a new project
ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps   --variable API_KEY_FOR_ANDROID="xxxx"

Error : Failed to fetch plugin
https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps 
via registry

I also tried
cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="xxx"
on a new project, but same problem

**Comment by wf9a5m75** [comment]
use npm.
