### ISSUE TITLE
Detected bugs on this latest release

### ISSUE THREAD

**Issue by dherbe** [mapsplugin/cordova-plugin-googlemaps#1731]
Hey there and thanks for a great plugin.
It seems this latest version introduces some issues which weren't present on the last beta that was available.
I haven't changed any code I've just updated the plugin, and all issues weren't happening before.
Before I had a v2.0 beta installed which seems to be not available anymore.
Is it possible to access any of the previous beta?

[ ] question
[X ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[X] **2.0-beta3 (github)**  ( latest one download today from https://github.com/mapsplugin/cordova-plugin-googlemaps )
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[X ] **Android**
[ ] **iOS**

**Current behavior:**
1 - When I open my map view the map_canvas element it's white, and the map doesn't show. I've placed some alerts and all plugin objects are available, the flow of the app keeps running, but simply the map doesn't show. (I have all other html elements that operate the map inside the map_canvas element)
2 - Also happened when I tap a marker and then another one, the infoWindows keept flickering.

**Expected behavior:**
1- (Like previously with beta) every-time I open the app and the map view, the map should appear.
2 - When tap a marker and another one only the latest marker should appear

**Screen capture or video record:**
<img src="https://user-images.githubusercontent.com/308554/30342503-0c98810c-97f2-11e7-8ed9-01fc109c7ae1.png" width="250">

**Related code, data or error log (please format your code or data):**
Nothing changed on my end after updating the plugin.

Thanks in advance

**Comment by wf9a5m75** [comment]
Please share your project files on github or others. I will check it.

**Comment by dherbe** [comment]
I'll try to prepare the files so you can inspect better.
Meanwhile I've tried to comment all code except the map initialisation like this:

`            app.map.map = window.plugin.google.maps.Map.getMap(div, {
                'mapType': plugin.google.maps.MapTypeId.ROADMAP,
                'disableDefaultUI': true,
                'controls': {
                    'compass': false,
                    'myLocationButton': false,
                    'indoorPicker': false,
                    'zoom': false
                },
                'gestures': {
                    'scroll': true,
                    'tilt': false,
                    'rotate': true,
                    'zoom': true
                },
                'camera': {
                    'latLng': {"lat": myPos.latitude, "lng": myPos.longitude},
                    'tilt': 0,
                    'zoom': app.map.zoom,
                    'bearing': 50
                },
                //https://developers.google.com/maps/documentation/android-api/style-reference
                'styles': [
                    {
                        "featureType": "poi.attraction",
                        "elementType": "all",
                        "stylers": [
                            { "visibility": "off" }
                        ]
                    },{
                        "featureType": "poi.business",
                        "elementType": "all",
                        "stylers": [
                            { "visibility": "off" }
                        ]
                    },{
                        "featureType": "landscape.man_made",
                        "elementType": "all",
                        "stylers": [
                            { "visibility": "off" }
                        ]
                    }
                ]
            });
            app.map.map.addEventListener(plugin.google.maps.event.MAP_READY, function(){
                app.map.map.on(plugin.google.maps.event.CAMERA_CHANGE, function(position){
                    app.map.zoomChanged(parseInt(position.zoom));
                });
                app.map.map.on(plugin.google.maps.event.MAP_CLICK, function(latLng) {
                    app.map.followLocation = false;
                });
                app.map.map.on(plugin.google.maps.event.MAP_LONG_CLICK, function(latLng) {
                    app.map.followLocation= false;
                    app.map.suggest(latLng.lat, latLng.lng);
                });
            });`

And the same behaviour happens, the map normally is not visible.
It's really a strange behaviour because the map is shown some times (like 1 out 10 attempts)

Regarding the infoWindow issue here's a tiny clip that shows the behaviour happening with the latest update, when I tap the first marker the infoWindow appears as expected, but then if I start tapping more markers the video shows what happens.
[Uploading IMG_8743.zip…]()


Thanks

**Comment by dherbe** [comment]
I've also tried changing the background colour with:
plugin.google.maps.environment.setBackgroundColor("transparent");

Which seems to work because the map view (without showing any map) gets all black.

Also I've tried to execute this:
plugin.google.maps.environment.getLicenseInfo(function(text){ alert(text); });
And I get an alert with "OK"

![screenshot_2017-09-13-13-03-32](https://user-images.githubusercontent.com/308554/30376390-170239f2-9884-11e7-9630-f109e883c9d0.png)


Is this right?

Once again thanks.

**Comment by wf9a5m75** [comment]
> I've also tried changing the background colour with:
plugin.google.maps.environment.setBackgroundColor("transparent");
>Which seems to work because the map view (without showing any map) gets all black

This is not bug. Even if you don't install this plugin and set the background color as transparent for webview, you also get black color.

----

>plugin.google.maps.environment.getLicenseInfo(function(text){ alert(text); });
> And I get an alert with "OK"

Google changed the rule recently.
They removed the method from the Android API (I guess they reimplemented all code by themselves).
So in the Android, you don't need to display the license anymore.

But in the iOS, you still need to display the license.

**Comment by dherbe** [comment]
Thanks for the reminder about displaying the license on iOS.

I don't know what other files I could share with you besides my map view.
We're using Telerik Kendo Mobile with Cordova version 5.0.0
And before the update the map always showed up properly, with the same markup and the same code after yesterday's update, the map just shows up very very few times.

[map.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1299910/map.txt)
(renamed from .html to .txt in order to upload here)

**Comment by dherbe** [comment]
Other things I've tried and didn't change the behaviour:
- Different API keys for Android and IOS
- Changed to Cordova version 6.4.0
- Fixed an element which had two style attributes

**Comment by wf9a5m75** [comment]
**Please(x3) save my time. Sharing project files on github (or other services) is only acceptable way.**
I'm really busy person. Just share your code requires me to setup an application environment, and you use the JS framework, so I have to learn the framework.
I have no such a time (or if you pay $1,000 USD, I do that).

Sharing your project files on git repository saves my time a lot.
I can start to build your app, then test it. That is eligible for $1,000USD.

You just share an empty file, then what can I do?

I warned 3 times. Next time, I will close this thread mandatory (it means no more support)

**Comment by dherbe** [comment]
Just to let you know, This morning We've updated the project with last night update and the issue seems to be resolved.
Once again thanks and sorry to make use of your busy time.

**Comment by Textras** [comment]
@dherbe we experience this on occasion with V2. Has been very hard to fix. Do you recall what fixed it for you? Often we see a white flash on map transition, (also on occasion a very zoomed in marker), but then remedies and acts as expected. Other times it stays white. 

Interested if you'd share what your fix was? Thanks.

**Comment by dherbe** [comment]
After a lot of code reducing and debugging I've manage to keep update this plugin until version 2.1.0.
The intermittent problem might have due to the some options I was specifying on getMap.

So after quite a bit of struggle, what worked for me was just using the bare minimum on getMap function.
`app.map.map = window.plugin.google.maps.Map.getMap(div, {
                        'mapType': plugin.google.maps.MapTypeId.ROADMAP,
                        'controls': {
                            'compass': false,
                            'myLocationButton': false,
                            'indoorPicker': false,
                            'zoom': false,
                            'mapToolbar' : false,
                        },
                    });`

Further setting of options is done inside MAP_READY:

`app.map.map.one(plugin.google.maps.event.MAP_READY, function(){
	app.map.map.setOptions({
		'gestures': {
			'scroll': true,
			'tilt': false,
			'rotate': true,
			'zoom': true
		},
		'disableDefaultUI': true,
		'styles': app.map.getMapStyle()
	});
});`

Hope it helps
Cheers
