### ISSUE TITLE
HtmlInfowindow position with custom icon

### ISSUE THREAD

**Issue by javi124** [mapsplugin/cordova-plugin-googlemaps#1732]
it's possible to put it at top of icon, how  infowindow?
Thanks.
<img width="152" alt="captura de pantalla 2017-09-12 a las 23 07 30" src="https://user-images.githubusercontent.com/22007165/30348322-3c5b6b08-980f-11e7-99d5-cf346938ac16.png">

**Comment by wf9a5m75** [comment]
```js
map.addMarker({
  position: {...},
  icon: ...,
  infoWindowAnchor: [0, 0]
});
```

**Comment by javi124** [comment]
Thank you.
