### ISSUE TITLE
CAMERA_CHANGE

### ISSUE THREAD

**Issue by sherlockgomes** [mapsplugin/cordova-plugin-googlemaps#1733]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[x] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
Cordova 7.0.1
```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please show me the package.json**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
 @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.10.2
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    npm               : 3.10.10 



cordova-plugin-googlemaps 2.0.6



Guys, this cordova maps plugin version, not working the CAMERA_CHANGE event.
I need catch this event to create a dynamic maker.

**Comment by wf9a5m75** [comment]
Please share your project files (or create a demo project).
I guess you are wrong something.

**Comment by sherlockgomes** [comment]
The map implement, is a step by step and was working at 1.4.3 version. When I updated to 2.0.x, the change Camera event is  crashed. Basicaly, I need get the current Camera geo position, for create a marker after camera has change.

**Comment by wf9a5m75** [comment]
Please share your project files (or create a demo project).

**Comment by sherlockgomes** [comment]
map.on(GoogleMapsEvent.CAMERA_CHANGE).subscribe(data=>{   });

**Comment by wf9a5m75** [comment]
Nooooooooooo
The important thing is reproduce your issue on my side. Please share your project file on next time.
(Otherwise, I close the thread).

-------

In the v2.0, CAMERA_CHANGE event is no more available.
The event names are different.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/CAMERA_EVENTS/README.md

**Comment by sherlockgomes** [comment]
![captura de tela 2017-09-12 as 23 24 07](https://user-images.githubusercontent.com/6206306/30358276-841188ea-9811-11e7-8224-5a6ccfe15b6b.png)
![captura de tela 2017-09-12 as 23 24 01](https://user-images.githubusercontent.com/6206306/30358277-841512c6-9811-11e7-8c61-a39731598eb5.png)
![captura de tela 2017-09-12 as 23 23 50](https://user-images.githubusercontent.com/6206306/30358278-8416ecb8-9811-11e7-8132-7b1895d1773a.png)

The CAMERA_MOVE event, is not implemented by Npm Native Ionic package. =/

**Comment by wf9a5m75** [comment]
https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/google-maps/index.ts#L455

**Comment by wf9a5m75** [comment]
If you don't want to share your project files, even you refuse creating  a demo , I will close this thread.

**Comment by sherlockgomes** [comment]
@wf9a5m75, Tks for help me with this issue. After update the @nativeIonic, the event CAMERA_MOVE has available. Tks so much.
Only more one case.
Do you know if the event: map.getCameraPosition() is available yet?

**Comment by wf9a5m75** [comment]
```
      var cameraPosition = map.getCameraPosition();
```
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getCameraPosition/README.md
