### ISSUE TITLE
Multiple Maps Branch Merged, clarify in ReadMe

### ISSUE THREAD

**Issue by gloventRehan** [mapsplugin/cordova-plugin-googlemaps#1735]
For the people after me, I think it will be good if you write on the ReadMe page, that the MultipleMaps Branch was merged and that instead of using the direct github URL to install the plugin, to rather use the npm version again. 

This wasted a lot of  my time, not your fault, I should prob have read better. Was just so thrown into the dark as when I compiled the MultipleMaps Branch was merged and for some reason did not install at all. It also gave no warning or error. The first error I got was when trying to initialize the map, saying that the plugin is not installed. But no worries this was the problem. 

Then also state that from version 2.0.0 you need to have at least  "@ionic-native/core": "4.2.1", 
Which will mean a lot of people will have to update other dependencies as well, so just something to keep in mind to save the next brave souls attempting to use the latest maps some trouble shooting time. 

Great work with this repo by the way, keep it up.

**Comment by wf9a5m75** [comment]
If you have something improvements, please send a pull request.

By the way, this plugin is not only for the ionic. And `@ionic-native/google-maps` plugin is not my plugin. It is managed by `@ionic-native` team.
(But I send lots of bug fixes)

> Then also state that from version 2.0.0 you need to have at least "": "4.2.1",

I also requested this to the `@ionic-native` team many times, but not archived yet.

**Comment by gloventRehan** [comment]
Okay I will also try and do it. 

Thanks I am not  a regular github-er, will first see if I can contact them. Then make a pull request.
