### ISSUE TITLE
Interactive Map (Gestures not working)

### ISSUE THREAD

**Issue by kendall1997** [mapsplugin/cordova-plugin-googlemaps#1736]
**I'm submitting a ...**  (check one with "x")
[ X ] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[ X ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ ] **iOS**

Hi, I am starting developing an App that shows a Google Map instance with Ionic 3.0, I follow the demo code that is in the official documents 
https://ionicframework.com/docs/native/google-maps/
Everything goes well, however, I can't move the camera to another place or make zoom with my fingers or even tap the button that take me to my position, I know that this plugin uses a native SDK for Google Maps and what I actually see  is a transparent layer to the actual native content, but the question is, Can I interact to the map with fingers gestures or I must use the web SDK?

Thanks for your time.

**Comment by wf9a5m75** [comment]
Try this steps:

```
$> cordova plugin rm cordova-plugin-googlemaps
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="....." --variable API_KEY_FOR_IOS="....." --no-fetch
```

**Comment by kendall1997** [comment]
Thanks, it worked.
