### ISSUE TITLE
Typo in Map.js

### ISSUE THREAD

**Issue by hstalder** [mapsplugin/cordova-plugin-googlemaps#1737]
[ ] question
[x] any problem or bug report
[ ] feature request

The plugin version: (check one with "x")
[x] 2.0-beta3 (github)
[x] 2.0 (npm)

If you choose 'problem or bug report', please select OS: (check one with "x")
[x] Android
[x] iOS

There is probably a typo in www/Map.js line 1086 & 1106 (introduced in commit 8eebfe1 correcting #1723
if (eventName === event.INFO_CLOS) {

Expected behavior:

should be if (eventName === event.INFO_CLOSE) {

**Comment by wf9a5m75** [comment]
Oh...

**Comment by wf9a5m75** [comment]
Thank you for figured out!
