### ISSUE TITLE
Ionic 2 - Slow DOM manipulation (reopening)

### ISSUE THREAD

**Issue by walfridosp** [mapsplugin/cordova-plugin-googlemaps#1740]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ X] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[X ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**device information:**
Model Number: SM-C115
Android Version: 4.4.2

**ionic information:**

```
cli packages:
    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3
global packages:
    Cordova CLI : 7.0.1
local packages:
    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1
System:
    Node : v6.9.4
    npm  : 5.3.0
    OS   : Windows 10
```

**Current behavior:**
Hi guys, thanks for keeping the good work.
I reported this issue while this version was in development, and at that time you successfully fixed it, maybe you didn't include that fix in this version? 

This is what is happening: 
Only by adding the plugin (not even initializing the map) if I try to scroll over a list of 150 items, the performance is very slow.

**Expected behavior:**
Scroll performance shouldn't be affected

**Steps to reproduce:**

```
ionic start list sidemenu
ionic cordova platform add android
# open file list/src/pages/list/list.ts
# increase the loop to 150 iterations
ionic cordova run android --prod
```
After the app opens go to Menu->List, then try the scrolling performance (this is just to compare after installing the plugin)

To reproduce the issue, install the plugin:

```
cordova plugin add cordova-plugin-googlemaps \
    --variable API_KEY_FOR_ANDROID="..." \
    --variable API_KEY_FOR_IOS="..."
```

**Screen capture or video record:**

Without cordova-plugin-googlemaps:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11937646/30430411-332812e4-996c-11e7-9711-fc9d3839e2e7.gif)

With cordova-plugin-googlemaps:

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/11937646/30430480-6e761e68-996c-11e7-94b2-7f2df196ecab.gif)

Thanks,
Walfrido

**Comment by wf9a5m75** [comment]
Please share the project files  on github.

**Comment by wf9a5m75** [comment]
And you didn't give enough information at all. What version of this plugin do you use, using `@ionic-native/core and google-maps` or not, and their versions. How can I help you?

**Comment by walfridosp** [comment]
Thanks for your quick response, I'm using the latest version, cloned from github.

I didn't share the project because you can reproduce the issue just after installing any ionic project.

Here is package.json, let me know if you need more information:

{
    "name": "list",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic/storage": "2.0.1",
        "cordova-android": "^6.2.3",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-googlemaps": "file:cordova-plugin-googlemaps1",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.6.1",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.1.4",
        "typescript": "2.3.4"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-googlemaps": {
                "API_KEY_FOR_ANDROID": "XXX",
                "API_KEY_FOR_IOS": "XXX"
            }
        },
        "platforms": [
            "android"
        ]
    }
}

**Comment by wf9a5m75** [comment]
I'm really busy person. Even creating an ionic project, I don't want to do that. And I'm not ionic user.
 If you refuse preparing the demo project, I close this thread

**Comment by walfridosp** [comment]
I know you are a really busy person and even like that you always find time to fix any issue, that's why in my first comment I gave you the steps to reproduce the error, which will be faster than sharing the project with you, but  anyways, here is the project in [bitbucket](https://bitbucket.org/walfridosp/gmaps).

You fixed this issue on this version: https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/48256fd3c67b7ea36a7a8ecbeb5fedf010fb1a42

I tried it and it works fine, but not with the latest version.

Thanks

**Comment by wf9a5m75** [comment]
Thank you for sharing the project.

**Comment by wf9a5m75** [comment]
Try the multiple_maps branch version.
![issue_1740_after](https://user-images.githubusercontent.com/167831/30462412-48c7285c-997a-11e7-90bd-7ce6bc5bc98e.gif)

**Comment by walfridosp** [comment]
Hey man, thank you once again! it works perfect!

**Comment by wf9a5m75** [comment]
You are welcome. I appreciate if you donate [tip](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
