### ISSUE TITLE
Google Map does not load after 3 times of destroying and creating

### ISSUE THREAD

**Issue by svarughese91** [mapsplugin/cordova-plugin-googlemaps#1741]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[ x] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta3-20170823-2235 "cordova-plugin-googlemaps"
cordova-plugin-http 1.2.0 "SSL Pinning"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please show me the package.json**

```
{
    "name": "myApp",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/camera": "^4.2.1",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/device": "^4.2.1",
        "@ionic-native/facebook": "^4.2.1",
        "@ionic-native/file-transfer": "^4.2.1",
        "@ionic-native/geolocation": "^4.1.0",
        "@ionic-native/google-maps": "^4.2.1",
        "@ionic-native/http": "^4.1.0",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic-native/stripe": "^4.2.1",
        "@ionic/storage": "2.0.1",
        "card": "^2.4.0",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-camera": "^2.4.1",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-facebook4": "^1.9.1",
        "cordova-plugin-file": "^4.3.3",
        "cordova-plugin-file-transfer": "^1.6.3",
        "cordova-plugin-geolocation": "^2.4.3",
        "cordova-plugin-googlemaps": "^1.4.4",
        "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git",
        "cordova-plugin-http": "^1.2.0",
        "cordova-plugin-splashscreen": "~4.0.1",
        "cordova-plugin-statusbar": "2.2.2",
        "cordova-plugin-stripe": "^1.5.3",
        "cordova-plugin-whitelist": "1.3.1",
        "crypto-js": "^3.1.9-1",
        "io": "^0.1.10",
        "ionic-angular": "3.6.0",
        "ionic-plugin-keyboard": "~2.2.1",
        "ionic2-rating": "^1.2.2",
        "ionicons": "3.0.0",
        "moment": "^2.18.1",
        "rxjs": "5.4.0",
        "socket.io-client": "^2.0.3",
        "stripe": "^4.24.1",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
     .....
```

**Current behavior:**
I have a home page that the app first goes to and the map load fine then i navigate to a different page and then the map on the home page is destroyed.  Then I go back to the home page and the map is created again and it displays fine.  If I do this more than 3 time then the map does not create.  It seems like it gets stuck in this part of the code: 

```
        this.googleMap.addMarker({
          'position': {
            lat: this.lat,
            lng: this.long
          }
        })
```

**Expected behavior:**
Should allow me to create the map as many times as I want and load fine

**Steps to reproduce:**

**Screen capture or video record:**

No errors or anything show up it just seems like it gets stuck in a line as stated above.

```
insert any relevant code, data, or error log here
```

**Comment by wf9a5m75** [comment]
Please share the project files on github.

**Comment by svarughese91** [comment]
I uploaded the map parts [here:](https://gist.github.com/svarughese91/977a7bbee7fcb5cbac91ad3623a83cee)

Let me know if you need more parts of it. Thanks so much for the help!

**Comment by wf9a5m75** [comment]
I'm really busy person. I don't have enough time to setup for new project. And I'm not ionic user.
Please create a demo project. Then I will check it.
Otherwise, no help.

**Comment by svarughese91** [comment]
ok no problem sorry wasnt sure how much you wanted to see.  I shared the repo with you.  When you go from the home page to the settings page it will destroy the map then when you go back to the home page it will create the map again.  Try that a few time after the 5th time for me the map just stopped loading.  Thanks so much for your help i really appreciate it!

**Comment by wf9a5m75** [comment]
Thank you for sharing the project files. I will check it.

**Comment by wf9a5m75** [comment]
Okay, try the multiple_maps branch please.
I will describe what was wrong in your code and this plugin tomorrow.

**Comment by svarughese91** [comment]
Yes thank you that worked! Looking forward to hearing what was wrong.

**Comment by wf9a5m75** [comment]
The underlying factor is the calculation of the maps plugin is incorrect.
The hierarchy calculation of all DOM elements (z-index, etc) is really difficult.
Sorry about that.
Because of this, you execute `map.setClickable(true/false)` when you open/close the app menu.
You don't need to do that anymore.

---

But you execute this `map.setClickable(true/false)` even if you remove the map.

In order to execute methods safely, all methods are put in the command queue in the plugin at once.
The plugin limits maximumly 10 method executes at the same time (except couple of sync methods).
But you execute `map.setClickable(true/false)` for the removed map, the method is flagged as started, however the method is not executed in native.

That's why the command queue is stacked over, then a map is not created after 3 or 4 times.

----

And one more thing. **You have to wait all methods until the MAP_READY event.**

```
this.googleMap = this.googleMaps.create(this.mapElements, mapOptions);
this.isMapCreated = true;
this.googleMap.clear();  // <-- You can not execute this method until the MAP_READY event. And you don't need to execute this, because you create a new map.
this.setGoogleMapClick(false); // <-- You don't need to do that. And you have to wait the MAP_READY event.
this.googleMap.addMarker({ . // <--- You can't!
  'position': {
    lat: this.lat,
    lng: this.long
  }
}).then(marker => {
  console.log('Pre Add new marker')
  this.googleMapMarker = marker;
  console.log('ADDED new marker')
})
  .catch(err => {
    console.log('Google Add MArker had an error: ' + err);
  })
// Wait the MAP_READY before using any methods.
this.googleMap.one(GoogleMapsEvent.MAP_READY)
  .then(() => {

   });

```

**Comment by wf9a5m75** [comment]
I appreciate if you [donate some tip to the project](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted).

Thank you for your consideration.

**Comment by williamwilliamwilliam** [comment]
Thanks for your explanation of the command queue! I had a similar symptom on my project, and went through any place I could possibly be calling a Map object's methods after they were disposed. I found the problem line, and that cleared up my issue as well.
