### ISSUE TITLE
map.getMyLocation() doc

### ISSUE THREAD

**Issue by Madm0x** [mapsplugin/cordova-plugin-googlemaps#1742]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[x] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**Current behavior:**
map.getMylocation is returning other object, not the one in your documentation
(thats https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-geolocation/ ) 

**Expected behavior:**
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getMyLocation/README.md
(even here, you can see undefined in your gif :p ) 

**Screen capture or video record:**
![image](https://user-images.githubusercontent.com/24223170/30481306-c808fd7a-9a15-11e7-8978-790313c0dd16.png)

**Comment by wf9a5m75** [comment]
This plugin returns the raw values from the native api. The values are different depends on your android version, provider(GPS, or fuse), and device.

So the screen capture is true. Not bug.

**Comment by wf9a5m75** [comment]
And "cordova-plugin-geolocation" is not my plugin. It is not related with this plugin at all.
