### ISSUE TITLE
Blank page, map dosent load...

### ISSUE THREAD

**Issue by gonadn** [mapsplugin/cordova-plugin-googlemaps#1745]
Hi

Iam triyng to add cordova-plugin-googlemaps in a blank simple Cordova project created with VS2017.
Plugin is added without any error, and iam running Cordova -v 6.5.0 and the latest version of android SDK 25.x . 

When i run command "Cordova build" , projcts builds SUCCESSFULLY.
But when i deploy/run it on my device or emulator it just shows a blank page, and no errors or exception...
 API Key in Google console is created and thats what i used when i added the plugin:
`cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps \
    --variable API_KEY_FOR_ANDROID="..."

Now iam out of clue, what am i doing wrong here....
npm -v 3.10.10
Cordova -v 6.5.0

Plugins:
+-- cordova-plugin-compat@1.1.0
+-- cordova-plugin-console@1.0.7
+-- cordova-plugin-device@1.1.6
+-- cordova-plugin-geolocation@2.4.3
+-- cordova-plugin-googlemaps@2.0.8
+-- cordova-plugin-inappbrowser@1.7.1
`-- cordova-plugin-splashscreen@4.0.3

NO Angular or Ionic aded, just trieng to setup up plain sample "Quick Demo"...`

**Comment by wf9a5m75** [comment]
Please share the project files on github

**Comment by gonadn** [comment]
projected is shared on this [link](https://github.com/gonadn/PluginGMaps)

**Comment by wf9a5m75** [comment]
Your HTML is wrong.
![1745](https://user-images.githubusercontent.com/167831/30517105-131e4aec-9b09-11e7-96bf-0e078a5cb784.gif)

**Comment by wf9a5m75** [comment]
![dev_tool_compress](https://user-images.githubusercontent.com/167831/30517113-60468302-9b09-11e7-91a6-aa7df6245d83.gif)

**Comment by wf9a5m75** [comment]
I appreciate if you [donate some tip to the project](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted).

Thank you for your consideration.
