### ISSUE TITLE
InfoWindow setContent() Stopped Working

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/cordova-plugin-googlemaps#1748]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ X] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[X ] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
$ cordova plugin ls
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
com.transistorsoft.cordova.background-geolocation 1.5.1 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.2.2 "ActionSheet"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-googlemaps 2.0.9-beta-20170917-2321 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-spatialite-storage 1.0.0 "Cordova sqlite/spatialite storage plugin"
phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"
phonegap-plugin-contentsync 1.3.2 "content-sync"
phonegap-plugin-push 1.8.2 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.0.4 "Launch Navigator"
```
**Current behavior:**
I think the infoWindow setContent function stopped working

**Expected behavior:**
I would expect the infoWindow content to change based on the html string I passed in.

**Steps to reproduce:**
click on a camera icon, then click "View Next"

**Screen capture or video record:**
http://www.youtube.com/watch?v=zvPQ35QCHHc

**Comment by wf9a5m75** [comment]
Could you show me the part of code?

**Comment by KimberleeDArmstrong** [comment]
In Bitbucket -> LinemanApp ->www -> js -> common_map_funcs.js it is in the function swipeMedia() Line 595... 

Otherwise this is the loadMediaMarker code ... 

var mediaIdx = 0; var swipedMedia; function load_media_markers() { media = []; mediaSorter = {}; var data = []; for (var i = 0 ; i < masterMarkerList['media_markers'].rows.length ; i ++ ) { if (mediaSorter[masterMarkerList['media_markers'].rows[i].geodata] == undefined) { mediaSorter[masterMarkerList['media_markers'].rows[i].geodata] = data.length; data.push({ lat: masterMarkerList['media_markers'].rows[i].lat, lon: masterMarkerList['media_markers'].rows[i].lon, image_path: [masterMarkerList['media_markers'].rows[i].image_path], work_item_number: [masterMarkerList['media_markers'].rows[i].work_item_number], uploaded_by: [masterMarkerList['media_markers'].rows[i].uploaded_by], uploaded_on: [masterMarkerList['media_markers'].rows[i].uploaded_on], comments: [masterMarkerList['media_markers'].rows[i].comments] }); }else{ data[mediaSorter[masterMarkerList['media_markers'].rows[i].geodata]].image_path.push(masterMarkerList['media_markers'].rows[i].image_path); data[mediaSorter[masterMarkerList['media_markers'].rows[i].geodata]].work_item_number.push(masterMarkerList['media_markers'].rows[i].work_item_number); data[mediaSorter[masterMarkerList['media_markers'].rows[i].geodata]].uploaded_by.push(masterMarkerList['media_markers'].rows[i].uploaded_by); data[mediaSorter[masterMarkerList['media_markers'].rows[i].geodata]].uploaded_on.push(masterMarkerList['media_markers'].rows[i].uploaded_on); data[mediaSorter[masterMarkerList['media_markers'].rows[i].geodata]].comments.push(masterMarkerList['media_markers'].rows[i].comments); } } var infoWindow = new plugin.google.maps.HtmlInfoWindow(); var baseArray = new plugin.google.maps.BaseArrayClass(data); var idx = 0; baseArray.map(function(myData, cb) { myData.index = idx; idx++; var data = { icon: {url: 'images/cameraicon.png', anchor: [ 0.1, 0.1]}, position: { lat: myData.lat, lng: myData.lon }, draggable: true, disableAutoPan: true, zIndex: 30, visible: localStorage.getItem('ckbx_Media') === 'true', myData: myData }; googleMap.addMarker(data, cb); }, function(markers) { media = markers; markers.forEach(function(marker) { marker.on(plugin.google.maps.event.MARKER_CLICK, onMarkerClick); }); }); swipedMedia = function(markerIdx) { var thisData = media[markerIdx].get('myData'); var content = '<table style="width:325px;height:450px;"> <tr><td></td><td id="closeBtn" align="right"><img src="images/close.png"/></td></tr>'; content += '<tr><td colspan="2"><img style="max-width:300px;max-height:300px;" src="'+localStorage.getItem('ims_url')+''+thisData.image_path[mediaIdx]+'"/>'; content += '</td></tr>'; content += '<tr><td class="popup_heading"><b>Uploaded On: </b></td><td>' + thisData.uploaded_on[mediaIdx] + '</td></tr>' + '<tr><td class="popup_heading"><b>Uploaded By: </b></td><td>' + thisData.uploaded_by[mediaIdx] + '</td></tr>'; if (thisData.comments[mediaIdx] != null) { content+='<tr><td class="popup_heading"><b>Comment: </b></td><td>&nbsp;</td></tr>' + '<tr><td colspan="2">' + thisData.comments[mediaIdx] + '</td></tr>'; } content += '<tr><td align="left">'; if (mediaIdx > 0) { content+='<button class="ui-btn ui-btn-a ui-btn-icon-left ui-icon-arrow-l" onclick="javascript: mediaIdx= mediaIdx -1; swipedMedia('+thisData.index+');">View Previous</a>'; } content += '</td><td align="right">'; if (mediaIdx < thisData.uploaded_on.length-1){ content+='<button class="ui-btn ui-btn-a ui-btn-icon-right ui-icon-arrow-r" onclick="javascript: mediaIdx= mediaIdx + 1; swipedMedia('+thisData.index+');">View Next</a>'; } content += '<td></tr></table>'; infoWindow.setContent(content); setTimeout( function() { $("#closeBtn").on("click", function() { infoWindow.close(); }); },500); }; function onMarkerClick() { $("#closeBtn").trigger("click"); mediaIdx = 0; var marker = this; var myData = marker.get("myData"); var content = '<table style="width:325px;height:450px;"> <tr><td></td><td id="closeBtn" align="right"><img src="images/close.png"/></td></tr>'; content += '<tr><td colspan="2"><img style="max-width:300px;max-height:300px;" src="'+localStorage.getItem('ims_url')+''+myData.image_path[mediaIdx]+'"/>'; content += '</td></tr>'; content += '<tr><td class="popup_heading"><b>Uploaded On: </b></td><td>' + myData.uploaded_on[mediaIdx] + '</td></tr>' + '<tr><td class="popup_heading"><b>Uploaded By: </b></td><td>' + myData.uploaded_by[mediaIdx] + '</td></tr>'; if (myData.comments[mediaIdx] != null) { content+='<tr><td class="popup_heading"><b>Comment: </b></td><td>&nbsp;</td></tr>' + '<tr><td colspan="2">' + myData.comments[mediaIdx] + '</td></tr>'; } content += '<tr><td align="left">'; if (mediaIdx > 0) { content+='<button class="ui-btn ui-btn-a ui-btn-icon-left ui-icon-arrow-l" onclick="javascript: mediaIdx= mediaIdx -1; swipedMedia('+myData.index+');">View Previous</button>'; } content += '</td><td align="right">'; if (mediaIdx < myData.uploaded_on.length-1){ content+='<button class="ui-btn ui-btn-a ui-btn-icon-right ui-icon-arrow-r" onclick="javascript: mediaIdx= mediaIdx + 1; swipedMedia('+myData.index+');">View Next</button>'; } content += '<td></tr></table>'; infoWindow.setContent(content); infoWindow.open(marker); setTimeout( function() { $("#closeBtn").on("click", function() { infoWindow.close(); }); },500); } } 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by wf9a5m75** [comment]
Thank you, Kim. I confirmed this, and I'm working on this. I will update the code in couple of hours.

**Comment by wf9a5m75** [comment]
Fixed.
![1748](https://user-images.githubusercontent.com/167831/30572793-b17515e4-9ca4-11e7-9858-48b8d76f7288.gif)

**Comment by KimberleeDArmstrong** [comment]
I downloaded the latest plugin.  

cordova-plugin-googlemaps 2.0.9-beta-20170918-2233 "cordova-plugin-googlemaps"

Is that the right version?  It is still not working for me.

**Comment by wf9a5m75** [comment]
Somehow the previous fix does not work today.
I fixed again. Please reinstall the multiple_maps branch version (2.0.10-beta-20170919-1218).

**Comment by KimberleeDArmstrong** [comment]
Using cordova-plugin-googlemaps 2.0.10-beta-20170919-1218 "cordova-plugin-googlemaps"  and it doesn't look like its working.

**Comment by wf9a5m75** [comment]
Really?

**Comment by KimberleeDArmstrong** [comment]
Yes.  Sorry :-(

**Comment by KimberleeDArmstrong** [comment]
Not sure if this is why but on line 222 of HtmlInfoWindow.js marker.isInfoWindowShown() is returning false even though the infoWindow is showing.  

if (content !== prevContent && marker && marker.isInfoWindowShown()) {
     self.trigger("infoWindowAnchor_changed");
}

**Comment by wf9a5m75** [comment]
Yes, that is the problem line. I updated the code in the `2.0.10-beta-20170919-1218`, but it seems it does not work in your app. I'm inspecting now. Sorry for this inconvenience.

**Comment by wf9a5m75** [comment]
![1748_compress](https://user-images.githubusercontent.com/167831/30617728-4704738c-9d4c-11e7-8cd8-9e334741e393.gif)

**Comment by KimberleeDArmstrong** [comment]
No worries!  Thanks for your quick resolution!  :-D
