### ISSUE TITLE
Fund raise to fix the @ionic-native/google-maps plugin

### ISSUE THREAD

**Issue by wf9a5m75** [mapsplugin/cordova-plugin-googlemaps#1749]
## Overview

- Fundraise amount: $1,000 USD
- Fix the bugs of the `@ionic-native/google-maps` plugin 
- Create a demo of the `@ionic-native/google-maps` plugin for all methods.

------

## Description

As you may know, the ionic provides as [@ionic-native/google-maps](https://ionicframework.com/docs/native/google-maps/), but **the wrapper plugin is not written by me actually**.
Because of this, there are lots of bugs in the wrapper plugin.

I fixed lots of problems, but too many bugs.
In order to figure out the bugs, and fix them, I need to create the demo of all methods.
Some contributors and I tried to create that, but it takes so much time, and no profits.

The keypoint is `time is money`.
Working on the `@ionic-native/google-maps` spend my private time a lot.
Also the time of the contributors as well.

I discussed with the ionic team regarding the sponsor ship , but they refused my offer.
That's why I stop fixing the `@ionic-native/google-maps` plugin anymore.

However, I also understand many ionic users prefer the `@ionic-native/google-maps` plugin instead of the pure JS version. But nobody pay for our work.

Thus, I start the fund raising at here to fix the problems of the `@ionic-native/google-maps` plugin.

If the amount reach to $1,000 USD, we will restart the working to create the demo project.
https://github.com/wf9a5m75/ionic-googlemaps-demo

At the same time, I will restart to fix the `@ionic-native/google-maps` plugin.

Until the time, we stop our activities for a while.

------

## How to donate to this project?

Please donate from here.
<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Fix%20the%20%40ionic%2dnative%2fgoogle%2dmaps%20plugin&amount=100%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted"><img src="https://img.shields.io/badge/Donate%20$100USD-PayPal-green.svg"></a>

<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=fix%20the%20%40ionic%2dnative%2fgoogle%2dmaps%20plugin&amount=200%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted"><img src="https://img.shields.io/badge/Donate%20$100USD+support($100)-PayPal-green.svg"></a>

<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Fund%20raise%20to%20fix%20the%20%40ionic%2dnative%2fgoogle%2dmaps%20plugin&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted"><img src="https://img.shields.io/badge/Donate%20other%20amount-PayPal-green.svg"></a>
------

## Benefits

- I will let you know when I fix the new bugs of the `@ionic-native/google-maps` plugin
- I will support your project if you have a problem with the `@ionic-native/google-maps` plugin (I don't support for non-donated person, sorry)
- If you donate $200 USD, I support in private (by e-mail base. E-mail supporting is stressful for me, but if you donate the amount, I will support for that)

------

## The usage of the amount

I will share it with the contributors based on their work.

**Comment by thezakman** [comment]
Got to fix the badge icon/link

**Comment by wf9a5m75** [comment]
@thezakman Fix the icon and link!

**Comment by wf9a5m75** [comment]
Thank you for your donation, @Javi124

**Comment by heyjohnny** [comment]
So currently getting this error message when trying to install:

Error: Failed to fetch plugin 
        https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps 
        via registry.
        Probably this is either a connection problem, or plugin spec is 
        incorrect.
        Check your connection and plugin name/version/URL.
        Failed to get absolute path to installed module

...Is this because you are no longer providing the module? It worked fine yesterday and today it stopped....

**Comment by wf9a5m75** [comment]
@heyjohnny Why did you post your issue at here?
And did you find in the past issues? https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1435#issuecomment-299580754
That is npm problem, not this plugin.

**Comment by mlynch** [comment]
Hi @wf9a5m75, apologies for not following up in a timely manner on your email. We haven't refused to support the project, it's just not something we've done before so I hope you'll understand it's a process on our end figuring out how to do that.

However, we just donated to the cause which I hope helps in the short term. We very much appreciate your support and understand there's a large demand on your time from the community. 

I will follow up via email and we can continue the conversation there.

**Comment by wf9a5m75** [comment]
Hi @mlynch , thank you for understanding, and the donation!
Yes, let's discuss how we can effort for each others.

------

Since the total amount is reached to the end, I close this thread at once, and I support the closed issues.
And I will send the PR, which is I closed before, to the `@ionic-native` repository.
Also the contributors and I resume the demo project.
