### ISSUE TITLE
TileOverlay can not be shown

### ISSUE THREAD

**Issue by Tong2203** [mapsplugin/cordova-plugin-googlemaps#1750]
Hi,
I updated plugin to 2.0.9-beta-20170918-1858.
Then, tileOverlay can not be Shown.

You can reproduce the issue in `cordova-google-maps v2.0 example`.
<img src="https://user-images.githubusercontent.com/8978491/30575254-8a087eec-9d3a-11e7-8830-82b2a46bce70.png" width="250">

Please check it,  thanks a lot.

**Comment by wf9a5m75** [comment]
How did you write your code?

**Comment by wf9a5m75** [comment]
Oh...

**Comment by wf9a5m75** [comment]
![device-2017-09-18-223425](https://user-images.githubusercontent.com/167831/30577208-9f87a208-9cc1-11e7-81a6-7e637d515cf1.png)

Fixed. Please reinstall the plugin from the multiple_maps branch.

**Comment by Tong2203** [comment]
Thank you for the quick & awesome support !!

**Comment by wf9a5m75** [comment]
You are welcome. I appreciate if you donate [tip](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
