### ISSUE TITLE
MarkerCluster not working in last version 2.0.9

### ISSUE THREAD

**Issue by Flo-D** [mapsplugin/cordova-plugin-googlemaps#1751]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 
[x] **2.0.9 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.0.9 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please show me the package.json**

```
{
    "name": "ionic-hello-world",
    "version": "0.0.0",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "^4.2.1",
        "@ionic-native/google-maps": "^4.2.1",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic/storage": "2.0.1",
        "cordova-android": "^6.2.3",
        "cordova-plugin-console": "1.0.5",
        "cordova-plugin-device": "1.1.4",
        "cordova-plugin-googlemaps": "^2.0.9",
        "cordova-plugin-splashscreen": "~4.0.1",
        "cordova-plugin-statusbar": "2.2.2",
        "cordova-plugin-whitelist": "1.3.1",
        "ionic-angular": "3.6.0",
        "ionic-plugin-keyboard": "~2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.1.4",
        "typescript": "2.3.4"
    },
    "cordovaPlugins": [
        "cordova-plugin-whitelist",
        "cordova-plugin-console",
        "cordova-plugin-statusbar",
        "cordova-plugin-device",
        "cordova-plugin-splashscreen",
        "ionic-plugin-keyboard"
    ],
    "cordovaPlatforms": [],
    "description": "test-google-maps-cluster: An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-googlemaps": {
                "API_KEY_FOR_ANDROID": "x",
                "API_KEY_FOR_IOS": "x"
            }
        },
        "platforms": [
            "android"
        ]
    }
}
```

**Current behavior:**

As soon as I update the plugin, MarkerCluster is not working anymore. Nothing is displayed on the map.

I had the same code with this version and it was working : 

```
cordova-plugin-googlemaps 2.0.0-beta3-20170905-1257 "cordova-plugin-googlemaps"
```

**Expected behavior:**

MarkerCluster should be displayed on the map

**Steps to reproduce:**

Project : https://github.com/Flo-D/test-google-maps-cluster2

**Screen capture or video record:**

With cordova-plugin-googlemaps 2.0.0-beta3-20170905-1257 "cordova-plugin-googlemaps" : 

![screenshot_1505826692](https://user-images.githubusercontent.com/16482240/30593892-6b9ec184-9d4c-11e7-9c04-6b10c274da24.png)

With 2.0.9 : 

![screenshot_1505826622](https://user-images.githubusercontent.com/16482240/30593909-74aa39ca-9d4c-11e7-8b47-dc40fc7cb93c.png)

Thank you.

**Comment by wf9a5m75** [comment]
unfortunately, I decided I don't support @ionic-native/google-maps anymore after the discussion with the ionic-team.

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1749

**Comment by Flo-D** [comment]
Sure, I saw that you don't support anymore the ionic-native wrapper. If I thought it was a problem with the wrapper, I would have posted the issue in their repo.

But you still support your plugin right ? 

Because it seems only linked to the plugin, unless you've made a voluntary change to make it stop working with the wrapper, which I don't think..

**Comment by Flo-D** [comment]
Thank you for this fast fix ! This solved the issue
