### ISSUE TITLE
iOS: Scrolling lags within HTML element on map

### ISSUE THREAD

**Issue by eg271** [mapsplugin/cordova-plugin-googlemaps#1756]
iOS 10.3
v2 npm
Cordova 7.0.1
Testing on iPhone 5S
Question / Bug

Is it possible to temporarily disable the automatic check for html elements on the map when setClickable(false) is called?

Even after calling setClickable(false), there is a noticeable lag/jerkiness when scrolling inside an overlay element with a lengthy list - the XCode window shows a periodic:
`THREAD WARNING: ['CordovaGoogleMaps'] took '17.313965' ms. Plugin should use a background thread.`

which I presume is the result of the plugin still checking if there are elements on the map as the element is scrolled (despite it being unnecessary as mouse interaction shouldn't affect the map).

I'm able to prevent the lag by either:
- map.setDiv(null)
- display:none on the map div

But both involve hiding the map when all I want is to disable any interaction with the map.

**Comment by wf9a5m75** [comment]
Could you make an quick example?

**Comment by eg271** [comment]
https://bitbucket.org/Edgraham2/cordova-google-maps-test/src

After adding an app & API key combo in config.xml and installing the plugins as per usual, try running on a real device - I used an iPhone 5S.  If you've only got a newer device, might be necessary to increase the number of automatically generated div elements (currently set to 1000).

Once loaded, if you drag the list up and down quickly it's jerky and you get the thread warnings.   (Note that I'm referring to the actual smoothness of the movement not the flashing effect which you'd expect with a list this size as the browser tries to render the elements at the top/bottom.)   If you go to the console and type map.setClickable(false), you still get the same effect.

However, if you do map.setDiv(null), the list can be moved more smoothly.

Perhaps a quick fix/feature to disable html element checking if setClickable(false)?

**Comment by wf9a5m75** [comment]
Thank you for your preparing. I will check it later.

**Comment by wf9a5m75** [comment]
I checked your demo code.

This is not officially documented, but you can accelerate the touch feeling with `-webkit-overflow-scrolling: touch;`

**Comment by wf9a5m75** [comment]
```html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
  <meta name="format-detection" content="telephone=no">
  <meta name="msapplication-tap-highlight" content="no">
  <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
  <title>Hello World</title>
</head>

<style>
  html {
    height: 100%;

    /** this doesn't make sense **/
    /** -webkit-overflow-scrolling: touch; **/
  }

  body {
    font-size: 12px;
    height: 100%;
    margin: 0px;
    padding: 0px;
    width: 100%;
  }

  #map-canvas {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
  }

  #overlay {
    position: absolute;
    top: 150px;
    left: 30px;
    width: 250px;
    height: 400px;
    overflow-y: auto;
    overflow-x: hidden;
    background: blue;
    /** Specify -webkit-overflow-scrolling to the element that is container of scroll **/
    -webkit-overflow-scrolling: touch;
  }

  #overlay>div {
    height: 50px;
    background: linear-gradient(red, yellow);
    margin: 5px;
    box-shadow: rgba(136, 136, 136, 0.5) 0px 1px 2px 0px;
    width: 100%;
    color: white;
    text-align: center;
    font-size: 20px;
  }
</style>

<body>
  <div>
    <div id="map-canvas"></div>
  </div>
  <div id="overlay"></div>

  <script type="text/javascript" src="cordova.js"></script>
  <script>
    document.addEventListener('deviceready', onDeviceReady, false);

    function onDeviceReady() {
      map = plugin.google.maps.Map.getMap(document.getElementById('map-canvas'));

      for (var i = 0; i < 1000; i++) {
        var div = document.createElement('div');

        div.innerHTML = i;

        document.getElementById("overlay").appendChild(div);
      }
    }
  </script>

</body>
</html>

```

**Comment by eg271** [comment]
Tried moving the -webkit-overflow-scrolling: touch; to the scroll container but makes the performance worse if anything.  Applying it to the html element works perfectly in mobile Safari.

Also, tried the latest multiple maps branch with the above commit but still getting a thread warning and the above problem.

**Comment by wf9a5m75** [comment]
It seems you specify the css to wrong html element.

If the element with  `-webkit-overflow-scrolling` receives the touchstart, the touchmove, and the touchend events, the plugin omits the DOM calculation, and the plugin follows only the map div positions.

This aims to follow the map div positions on ionic smoothly.

Specifying to the HTML element does not work for this plugin, because the HTML element is not receive the touch events.

So even if you can't feel the performance up, your css is wrong.

**Comment by wf9a5m75** [comment]
This is the record of 1,000 elements.

![1756_1000](https://user-images.githubusercontent.com/167831/30731438-35b39c3e-9f22-11e7-9fd8-4cd06e906d6a.gif)

**Comment by wf9a5m75** [comment]
ping

**Comment by eg271** [comment]
The multiple maps branch (from a few days) crashes after some use.

![image](https://user-images.githubusercontent.com/1395967/30828235-e5a4e886-a234-11e7-9308-0f5162e702a4.png)

**Comment by wf9a5m75** [comment]
Please inspect more reason.
How can I reproduce the issue?
And **please DON'T paste the screen capture of the Xcode**. I can not see the details.

**Comment by wf9a5m75** [comment]
If you share **your actual code** with me, I help you.
If you don't do that, I can't help you, because I have no problem.

**Comment by eg271** [comment]
As for the scrolling, I've updated my demo app and moved the -webit-scrolling rule to the overlay.  

It's difficult to demo the situation where the scroll isn't so smooth - in my real app the HTML is more complex with CSS transforms, etc.  But, even with this demo, when scrolling, you do get Thread warnings which implies that the plugin is doing calculations to work out where elements are.

If you setDiv to null, these warnings don't display and so presumably the calls aren't made.  But if you call setClickable(true) they are still appearing.

Surely, if setClickable(true) is called, this automatic checking can be switched off even if it's difficult to prove it gives a performance gain for this demo?

**Comment by wf9a5m75** [comment]
Do you really use the latest version?
Please show me the result of `$> cordova plugin list`.

**Comment by eg271** [comment]
The test that led to the crash:

- Latest code from the same repo: https://bitbucket.org/Edgraham2/cordova-google-maps-test/src

- iPhone 5S

- cordova-plugin-googlemaps 2.1.0-beta-20170921-1843 "cordova-plugin-googlemaps"

It's happened several times on separate tests but unfortunately I can't reliably reproduce it - it happens after scrolling on the list and the map randomly, some times after just a few seconds.   The screenshot shows  "Collection was mutated whilst being enumerated".  If that's not helpful, is there a way to send an XCode memory dump or to trace the error more specifically?

**Comment by wf9a5m75** [comment]
I'm sorry, but I don't have iPhone5S, so I might not able to reproduce your issue.

**Comment by wf9a5m75** [comment]
Why do you have multiple `<HTML>` tags in one file?

```html
<!DOCTYPE html>

<html>
    <head>

        <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <title>Hello World</title>
    </head>
    
    <style>
        html{
            height: 100%;
            
        }
    
        body {
            font-size:12px;
            height:100%;
            margin:0px;
            padding:0px;
            width:100%;
        }
    
        #map-canvas{
            position: absolute;
            top:0;
            bottom:0;
            left:0;
            right:0;
        }
    
        #overlay{
            -webkit-overflow-scrolling: touch;
            position: absolute;
            top:150px;
            left:30px;
            width:250px;
            height:400px;
            overflow-y: auto;
            overflow-x: hidden;
            background:blue;
        }
    
        #overlay > div{
            height:50px;
            background:linear-gradient(red, yellow);
            margin:5px;
            box-shadow: rgba(136, 136, 136, 0.5) 0px 1px 2px 0px;
            width: 100%;
            color: white;
            text-align: center;
            font-size:20px;
        }
    
        #buttons{
            position:absolute;
            top:30px;
            width:100%;
            height:50px;
        }
    
        #buttons > button{
            width: 30%;
            height:100%;
            display:inline-block;
        }

    </style>
    
    <body>
        <div id="map-canvas"></div>
        <div id="buttons">
        <button onclick="toggleSetDiv()">Set Div</button>
        <button onclick="toggleClickable()">Set Clickable</button>
        <button onclick="reload()">Reload</button>
        </div>
        
        <div id="overlay"></div>
        
        <script type="text/javascript" src="cordova.js"></script>
        <script>
            document.addEventListener('deviceready', onDeviceReady, false);
            map_clickable = true
            
            function onDeviceReady() {
                map = plugin.google.maps.Map.getMap(document.getElementById('map-canvas'));
                
                for(var i=0; i<1000; i++){
                 var div = document.createElement('div');

                 div.innerHTML = i;
                 
                 document.getElementById("overlay").appendChild(div);
                 }
            }
        
            function toggleSetDiv(){
                if( map.getDiv()){
                    map.setDiv(null)
                } else {
                    map.setDiv(document.getElementById("map-canvas"))
                }
            }
        
            function toggleClickable(){
                map_clickable = !map_clickable
                console.log('set clickable', map_clickable)
                map.setClickable(map_clickable)
            }
        
            function reload(){
                location.reload()
            }
        
        
        </script>

    </body>
</html>
<!DOCTYPE html>

<html>
    <head>

        <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <title>Hello World</title>
    </head>
    
    <style>
        html{
            height: 100%;
            
        }
    
        body {
            font-size:12px;
            height:100%;
            margin:0px;
            padding:0px;
            width:100%;
        }
    
        #map-canvas{
            position: absolute;
            top:0;
            bottom:0;
            left:0;
            right:0;
        }
    
        #overlay{
            -webkit-overflow-scrolling: touch;
            position: absolute;
            top:150px;
            left:30px;
            width:250px;
            height:400px;
            overflow-y: auto;
            overflow-x: hidden;
            background:blue;
        }
    
        #overlay > div{
            height:50px;
            background:linear-gradient(red, yellow);
            margin:5px;
            box-shadow: rgba(136, 136, 136, 0.5) 0px 1px 2px 0px;
            width: 100%;
            color: white;
            text-align: center;
            font-size:20px;
        }
    
        #buttons{
            position:absolute;
            top:30px;
            width:100%;
            height:50px;
        }
    
        #buttons > button{
            width: 30%;
            height:100%;
            display:inline-block;
        }

    </style>
    
    <body>
        <div id="map-canvas"></div>
        <div id="buttons">
        <button onclick="toggleSetDiv()">Set Div</button>
        <button onclick="toggleClickable()">Set Clickable</button>
        <button onclick="reload()">Reload</button>
        </div>
        
        <div id="overlay"></div>
        
        <script type="text/javascript" src="cordova.js"></script>
        <script>
            document.addEventListener('deviceready', onDeviceReady, false);
            map_clickable = true
            
            function onDeviceReady() {
                map = plugin.google.maps.Map.getMap(document.getElementById('map-canvas'));
                
                for(var i=0; i<1000; i++){
                 var div = document.createElement('div');

                 div.innerHTML = i;
                 
                 document.getElementById("overlay").appendChild(div);
                 }
            }
        
            function toggleSetDiv(){
                if( map.getDiv()){
                    map.setDiv(null)
                } else {
                    map.setDiv(document.getElementById("map-canvas"))
                }
            }
        
            function toggleClickable(){
                map_clickable = !map_clickable
                console.log('set clickable', map_clickable)
                map.setClickable(map_clickable)
            }
        
            function reload(){
                location.reload()
            }
        
        
        </script>

    </body>
</html>
```

**Comment by eg271** [comment]
Sorry, copy and paste error - have now fixed so please try again

**Comment by eg271** [comment]
Also, this is on iOS 10.3.2

**Comment by wf9a5m75** [comment]
Thanks, but I don't have iOS 10 device anymore.

**Comment by wf9a5m75** [comment]
By the way, if you donate $100 USD to the project, I will buy a used iPhone5S at e-bay, then try to reproduce you issue.

**Comment by eg271** [comment]
I think it's more likely it's an iOS 10 problem as I can't reproduce the issue on the 5S iOS 11.0 simulator.

**Comment by wf9a5m75** [comment]
![1756](https://user-images.githubusercontent.com/167831/30833308-41355f6e-a203-11e7-8eaf-2e550b9286af.gif)

**Comment by eg271** [comment]
Ok, so leaving the crash aside for now, to summarise:

1. The demo isn't entirely smooth to scroll on some lesser devices (which is apparent on my iPhone 5S but not on your device) until setMap(null) is called
2. This becomes more noticeable the more complicated the HTML/CSS used
3. Thread warnings appear in this demo which seem to highlight a performance lag when checking for HTML elements
4. However, they don't appear at all when setMap(null) is called
5. Given that setClickable(false) shouldn't require any HTML checking as there is no possibility of scrolling the map, shouldn't this give the same performance increase as setMap(null)?  Just whilst keeping the map still visible.
6. If it does need to keep checking for other reasons, could another function be added which basically deactivates the plugin whilst keeping the map visible?


My alternative for now would be to use the master branch version and where the map should be visible behind a scrollable list, to output the map to a canvas using toDataUrl() and call setMap(null).

**Comment by wf9a5m75** [comment]
Unfortunately, I don't have iOS10 device anymore, and the developers (except you) asking me to use iOS11.
Since you don't share me the complete code, I can not reproduce your issue.

If you give me the complete demo html, I will help you further.
But if you don't create it, I have no more help.

**Comment by wf9a5m75** [comment]
ping

**Comment by eg271** [comment]
Have just upgraded my phone to iOS 11 but the issue is exactly the same.

The complete demo code is at  https://bitbucket.org/Edgraham2/cordova-google-maps-test/src
This is the code that causes the scroll lag and crashed under iOS 10.

If you scroll through the list, you get thread warnings and the scroll lags.  The only way to prevent this is to setMap(null) - whereas setClickable(false) should also prevent this, or another function might be needed.

Please try increasing the number of div elements from 1000 on line 91 of index.html if you can't recreate the thread warnings on your device.

**Comment by eg271** [comment]
It also seems to happen when momentum scrolling on the list whilst quickly moving the map immediately afterwards/simultaneously

**Comment by wf9a5m75** [comment]
I asked ` the complete code`. Not simple demo code.
You always reply " my real app the HTML is more complex with CSS transforms, etc", but the demo code is not the same as your app.
Please commit the **real the same code as your app**. Until the time, I don't check your issue.

**Comment by eg271** [comment]
**But the problem is evident in the demo code on an iPhone 5S, iOS 10 and 11.**  There are thread warnings that cause the scroll to lag slightly which disappear when setMap(null) is called.  It's difficult for me to share the 'real' code for various reasons but it doesn't seem sensible to diagnose the issue elsewhere when it has already been isolated for the simplest case (even if more complicated HTML/CSS exacerbates the problem).  Please try increasing the number of elements on line 91, if you can't observe the thread warnings.  

The plugin is making unnecessary HTML element calculations to check for the map div being moved or scrolled, _even when it is known in advance that this cannot happen_, as evidenced by the thread warnings.

The solution would seem to be to have a function to toggle the element checking manually whilst keeping the map visible.

Otherwise, I'll just use the toDataURL to canvas approach and setDiv(null).

**Comment by wf9a5m75** [comment]
I asked `Please commit the real the same code as your app. Until the time, I don't check your issue.`
It means it's ok demo code, but make it the same as real app.
**As I said, I am really not interested in your code at all.**

Unfortunately, until the issue is reproduced on my side, I don't work for this.

**Comment by chakke** [comment]
I have problem just like @eg271 . It happens not only iOS but android.
After sometime digging in the code. I saw the problem. 
Every time i touch in the screen, plugin will calculate the DOM change and put html elements (touchable area and z-index)  over js code and native code to detect which part of screen (webview or mapview) should recieve touch event. It happens realtime which caused scroll lag and performance is down. Instead of watching DOM change of all elements, we just focus on what should be care.
For example, if i have a div which scrollable, and it contain a lot of elements. The plugins will go through all of childrens which should not do. Checking touchable area of this div is good enough.
Here is what i do step by step to go over this problem :
1. Add class "map-ignore" (or whatever you want) to element which should be ignored when detect touch. Remember that the plugins inherracy detect change  so if parent is ignored, then all of children will be ignored.
2. Add "map-ignore" to ignoreClasses variable at line 229 in Common.js of plugin code.

@wf9a5m75 I think the function putHtmlElements in googlemaps-cdv-plugin.js is not good enough. it take too much time to calculate elements.

**Comment by dinh-anh** [comment]
I have problem just like @eg271 . It happens not only iOS but android.
After sometime digging in the code. I saw the problem.
Every time i touch in the screen, plugin will calculate the DOM change and put html elements (touchable area and z-index) over js code and native code to detect which part of screen (webview or mapview) should recieve touch event. It happens realtime which caused scroll lag and performance is down. Instead of watching DOM change of all elements, we just focus on what should be care.
For example, if i have a div which scrollable, and it contain a lot of elements. The plugins will go through all of childrens which should not do. Checking touchable area of this div is good enough.
Here is what i do step by step to go over this problem :

1 Add class "map-ignore" (or whatever you want) to element which should be ignored when detect touch. Remember that the plugins inherracy detect change so if parent is ignored, then all of children will be ignored.
2. Add "map-ignore" to ignoreClasses variable at line 229 in Common.js of plugin code.

@wf9a5m75 I think the function putHtmlElements in googlemaps-cdv-plugin.js is not good enough. it take too much time to calculate elements.

**Comment by wf9a5m75** [comment]
Without providing proper demo project files, I don't work for this anymore.
If you don't satisfy with this plugin, you can choose:
- improve the plugin code, and send a pull request wtih test code, or
- leave from this plugin.

This plugin displays native views under the browser view. So it is really difficult to behalf like HTML element perfectly.

So you need to understand about this point. Just argument is not acceptable.

**Comment by eg271** [comment]
Following on from @dinh-anh's comment, I have updated the demo code to an example which should reproduce the issue:

https://bitbucket.org/Edgraham2/cordova-google-maps-test/src

I have reduced the number of divs in the list to 100 but appended 100 child divs to each one.  This causes very slow response / a crash on my device.  If I press SetDiv though to hide the map, it scrolls smoothly (after a brief initial pause).

The thread warnings are now up to ~50ms in the error console.

**Comment by wf9a5m75** [comment]
So, is this **really the same HTML structure with your app?**
If so, I will check it. Otherwise, I don't do anything.
(I repeated so many times)

![screen shot 2017-10-02 at 9 33 35 am](https://user-images.githubusercontent.com/167831/31088253-ddd270b8-a754-11e7-9864-2051c25742c6.png)

**Comment by eg271** [comment]
Yes, my app has that structure.

**Comment by wf9a5m75** [comment]
But you said `It's difficult to demo the situation where the scroll isn't so smooth - in my real app the HTML is more complex with CSS transforms, etc. ` before with this structure.

**Comment by eg271** [comment]
I was trying to explain why the previous demo may have not showed the effect noticeably on a higher end device than the iPhone 5S.  But, I subsequently changed the app to remove the transforms and simplify the DOM tree and it made no difference.  However, having multiple child elements per list item does slow the scroll much more noticeably.

**Comment by wf9a5m75** [comment]
@eg271 Are you kidding me?
Your app displays lots of "<div>0</div>"?
![screen shot 2017-10-02 at 5 56 27 pm](https://user-images.githubusercontent.com/167831/31105742-1720cd9c-a79b-11e7-8a39-ba6a8010f854.png)

**Comment by wf9a5m75** [comment]
@eg271 Are you kidding me?
Your app displays lots of `<div>0</div>` in your real app?

I so many times requested you to create the same structure as your app.
But you kidding me. I'm so angry.

**Comment by wf9a5m75** [comment]
![screen shot 2017-10-02 at 5 56 27 pm](https://user-images.githubusercontent.com/167831/31105799-782981b0-a79b-11e7-92b5-f1a514730029.png)

**Comment by wf9a5m75** [comment]
As I said (many times), this plugin has to calculate the position, size and hierarchy(z-index).
Your app really displays 10,100 elements in your app?
If so, I strongly recommend you should not use this plugin, because it takes so much time and use spend CPU. Using other solution, such as Google Maps JavaScript API v3 , or MapBox are better, because they uses only HTML elements.

**Comment by eg271** [comment]
Sorry, I think there has been a misunderstanding.

You asked if my app had that **structure** - I am working on an app with a list of elements where each one  has many child elements.  That is exactly the same **structure**.   However, I increased the number of child elements **to ensure that you can observe the issue on your iPhone SE** because it is visible on my iPhone 5S with a lot less elements and in other situations as @dinh-anh has commented.  I was trying to be helpful  so that you could **reproduce** the issue as you requested.

As the demo example runs ok with the map switched off, the slow down is caused by the element checking and for the reasons you give - I appreciate this.

All I was asking, was whether it might be possible to add a simple toggle function / parameter passed to setClickable() to pause/resume the element checking for this kind of situation.  Because to keep the map displayed in the background **does not require the element checking if the map div doesn't move**.  Wouldn't this be a relatively simple feature to add for situations like this?

**Comment by wf9a5m75** [comment]
Even if you disable the map touch, the plugin has to recalculate when you set enable again.

And how about this case. You have two maps, one is disabled the touching, but the other one is not disabled.
In that case, the plugin has to calculate.

Please use other map solution. I spent for you so much time, and I agree this plugin is not perfect for you, because this plugin has to work a lot.

**Comment by wf9a5m75** [comment]
I think you don't use this plugin anymore, but I write for memo.
I implemented new mechanism of the DOM inspection, which is faster and less numbers.
As far as I tested, there is no problem. And you probably won't feel the time lag when you scroll the list.
In order to use this, you need to reinstall the plugin from the multiple_maps branch.

**Comment by wf9a5m75** [comment]
Another update.
https://photos.app.goo.gl/tBSjKNZqNESL3hei1

**Comment by wf9a5m75** [comment]
This is the video that runs your test project on **iPad2 (iOS 9.3.5)**
![1756](https://user-images.githubusercontent.com/167831/34471528-daeea648-ef00-11e7-89a2-88cfd350ae37.gif)

**Comment by eg271** [comment]
Thanks, I'll check it out.   
  
  
  

  
  

  
  
>
