### ISSUE TITLE
Can i use the plugin with angularjs or only works with ionic native(angular 4)?

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#1757]

**Comment by francoro** [comment]
And also it have for example if a want to show all the petshops or restaurants in the viewport?

**Comment by wf9a5m75** [comment]
I have no knowledge about angular.js.

**Comment by francoro** [comment]
Bit can i use it with vanilla js?and it has the places like i said above?

**Comment by wf9a5m75** [comment]
If the vanilla.js uses Apache Cordova, this plugin works.

**Comment by francoro** [comment]
Yes it is ionic 1. Anda what about the places? Is implemented?

**Comment by wf9a5m75** [comment]
What is the places?

**Comment by wf9a5m75** [comment]
If you intend the Google Places API, this plugin does not implement it.
If you pay me $1,000, I will implement it soon.

**Comment by francoro** [comment]
I just want to know If it is already.thanks you can close it
