### ISSUE TITLE
Drawing support

### ISSUE THREAD

**Issue by kotromeo** [mapsplugin/cordova-plugin-googlemaps#1758]
Plugin support drawing on map like here:
https://developers.google.com/maps/documentation/javascript/examples/drawing-tools?hl=en

**Comment by wf9a5m75** [comment]
No plan currently.
Please implement by yourself like this.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Polyline/getPoints/README.md

**Comment by kotromeo** [comment]
Thanks for link to documentation, but this is the other functionality.
i need the ability to let USER draw zone, directly on map.

**Comment by wf9a5m75** [comment]
This plugin does not have it.

**Comment by wf9a5m75** [comment]
`Time is money`. This is common sense of the world.
If you pay me $1,000 USD, I will implement this. Otherwise, I have no plan to implement this.
