### ISSUE TITLE
iOS 11 crash with Polyline (v1.4.5)

### ISSUE THREAD

**Issue by craig-at-rsg** [mapsplugin/cordova-plugin-googlemaps#1759]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 
[x] v.1.4.5

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
com.rsginc.exceptionthrower 1.0.0 "Exception Thrower"
com.rsginc.mobilesurvey 1.0.0 "Trip Recorder guts"
cordova-fabric-plugin 1.1.7 "cordova-fabric-plugin"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-preferences 0.99.3 "AppPreferences"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 4.0.4 "CDVBackgroundFetch"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-googlemaps 1.4.5 "cordova-googlemaps-plugin"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-localization-strings 1.0.1 "Localization"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
{}

**If you use `@ionic-native/google-maps`, please show me the package.json**

**Current behavior:**
Creating a Polyline crashes the app

**Expected behavior:**
Create a Polyline without crashing

**Steps to reproduce:**
Create  a Polyline under iOS 11

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**
(For creating 2 Polylines):

2017-09-21 10:05:07.771023-0400 rMove[274:14072] -[Polyline initWithWebViewEngine:]: unrecognized selector sent to instance 0x1c4137480
2017-09-21 10:05:07.771023-0400 rMove[274:14387] -[Polyline initWithWebViewEngine:]: unrecognized selector sent to instance 0x1c01372a0
2017-09-21 10:05:07.775361-0400 rMove[274:14072] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Polyline initWithWebViewEngine:]: unrecognized selector sent to instance 0x1c4137480'
*** First throw call stack:
(0x184157d38 0x18366c528 0x1841651f8 0x18415d6e4 0x1840430dc 0x100c596e4 0x100ba5490 0x10291949c 0x10291945c 0x10292556c 0x10292ab54 0x10292a880 0x183d83130 0x183d82c30)
2017-09-21 10:05:07.775361-0400 rMove[274:14387] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Polyline initWithWebViewEngine:]: unrecognized selector sent to instance 0x1c01372a0'
*** First throw call stack:
(0x184157d38 0x18366c528 0x1841651f8 0x18415d6e4 0x1840430dc 0x100c596e4 0x100ba5490 0x10291949c 0x10291945c 0x10292556c 0x10292ab54 0x10292a880 0x183d83130 0x183d82c30)
libc++abi.dylib: terminating with uncaught exception of type NSException
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by wf9a5m75** [comment]
Please share your project files on github (or other services).

**Comment by wf9a5m75** [comment]
And v1.4.5 is out of support.

**Comment by wf9a5m75** [comment]
Please use the v2.0.

**Comment by craig-at-rsg** [comment]
2.0 wasn't final while we were testing for a release - we're upgrading for our next release.

**Comment by wf9a5m75** [comment]
The code of v1.4.x is too old. It is not maintained anymore. Unfortunately, you can't receive any support in this case.

**Comment by wf9a5m75** [comment]
Since we talked via emails, I close this thread at once.
If you have further problems with the v2.0, please make another issue.

**Comment by craig-at-rsg** [comment]
Upgrading to 2.0 fixed this for us, and it wasn't that hard to do.

**Comment by wf9a5m75** [comment]
Sounds nice!

**Comment by steve-didomenico** [comment]
Just figured I'd leave this comment here for folks who are trying to use the old plugin. I found a fork here who appears to have fixed this crashing issue with iOS 11: https://github.com/luciman/phonegap-googlemaps-plugin . Specifically, this is the commit that seems to have solved this problem: https://github.com/luciman/phonegap-googlemaps-plugin/commit/1c5c9f00ef197cffe5d25d12a7e3c99e17e3dc64
