### ISSUE TITLE
Compability cordova  wkwebview engine

### ISSUE THREAD

**Issue by javi124** [mapsplugin/cordova-plugin-googlemaps#1760]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[x] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-admobpro 2.29.22 "AdMob Plugin Pro"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-extension 1.5.2 "Cordova Plugin Extension"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.7 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.6 "Cordova WKWebView Engine"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**If you use `@ionic-native/google-maps`, please show me the package.json**

**Current behavior:**
I had to install wkwebview, and now the app closed when the map init, they are not compatible?
Thanks.
**Expected behavior:**

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```

**Comment by wf9a5m75** [comment]
cordova-plugin-googlemaps 2.0.7 is old.
Please try the latest version at least.

**Comment by javi124** [comment]
The problem is not the load map, is when I update the content of the map (markers) I obtain this:
Terminating app due to uncaught exception 'GMSThreadException', reason: 'The API method must be called from the main thread'
Maybe my problem should not be posted here.
Thanks

**Comment by wf9a5m75** [comment]
> 'GMSThreadException', reason: 'The API method must be called from the main thread'

This error causes in the Google Maps SDK for iOS. (It's a bug of Google!!)

Did you read this page? It seems you forget to set the `BackgroundColor` and the `xwalkZOrderOnTop` properties.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/crosswalk/README.md

**Comment by javi124** [comment]
That did not solve the problem, if I remove the plugin map, the app works with wkwebview, and If remove wkwebview and add plugin map, the app work.
This is the log of Xcode 9:
[DEBUG] Did end background task
2017-09-22 06:49:49.141299+0200 My App[3966:157721] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
2017-09-22 06:49:49.198296+0200 My App[3966:157721] <Google:HTML> You are currently using version 7.22.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.
2017-09-22 06:49:49.260284+0200 My App[3966:157721] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
2017-09-22 06:49:49.334419+0200 My App[3966:157380] Map is ready!
2017-09-22 06:49:49.344484+0200 My App[3966:157678] Task <DF7DED34-09D6-40FB-851B-84631BCAAE35>.<1> finished with error - code: -1002
2017-09-22 06:49:49.345598+0200 My App[3966:157789] Task <7D54E753-A0A6-4540-8E45-CFB5FE3D1E8E>.<1> finished with error - code: -1002
2017-09-22 06:49:49.356285+0200 My App[3966:157380] Google Maps SDK for iOS version: 2.4.30121.0
2017-09-22 06:49:49.358904+0200 My App[3966:157677] [fail] url = (null)
2017-09-22 06:49:49.358913+0200 My App[3966:157691] [fail] url = (null)
2017-09-22 06:49:49.359947+0200 My App[3966:157721] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
2017-09-22 06:49:49.362576+0200 My App[3966:157691] *** Terminating app due to uncaught exception 'GMSThreadException', reason: 'The API method must be called from the main thread'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a7fb1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010a12ff41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a86fb95 +[NSException raise:format:] + 197
	3   My App                         0x000000010296f7d6 -[GMSOverlay setMap:] + 89
	4   My App                         0x000000010278085d __52-[PluginMarker setIcon_:iconProperty:callbackBlock:]_block_invoke_2.558 + 285
	5   My App                         0x0000000102783049 __53-[PluginMarker downloadImageWithURL:completionBlock:]_block_invoke_2 + 313
	6   CFNetwork                           0x00000001037fe208 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
	7   CFNetwork                           0x00000001037fda6d __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 147
	8   Foundation                          0x000000010523d9b7 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	9   Foundation                          0x000000010523d81a -[NSBlockOperation main] + 68
	10  Foundation                          0x000000010523bcd6 -[__NSOperationInternal _start:] + 778
	11  libdispatch.dylib                   0x000000010cff943c _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010cffeaf4 _dispatch_block_invoke_direct + 592
	13  libdispatch.dylib                   0x000000010cff943c _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010cffeaf4 _dispatch_block_invoke_direct + 592
	15  libdispatch.dylib                   0x000000010cffe884 dispatch_block_perform + 109
	16  Foundation                          0x0000000105237ce4 __NSOQSchedule_f + 342
	17  libdispatch.dylib                   0x000000010cff943c _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x000000010cfff856 _dispatch_continuation_pop + 967
	19  libdispatch.dylib                   0x000000010cffdc86 _dispatch_async_redirect_invoke + 780
	20  libdispatch.dylib                   0x000000010d0051f9 _dispatch_root_queue_drain + 772
	21  libdispatch.dylib                   0x000000010d004e97 _dispatch_worker_thread3 + 132
	22  libsystem_pthread.dylib             0x000000010d4bc5a2 _pthread_wqthread + 1299
	23  libsystem_pthread.dylib             0x000000010d4bc07d start_wqthread + 13

**Comment by wf9a5m75** [comment]
Please share the project files on github. Then I will check it. Otherwise, I can't help you

**Comment by javi124** [comment]
Is not a problem with google maps plugin, thank you.

**Comment by wf9a5m75** [comment]
Ok. Thank you for letting me know.

**Comment by javi124** [comment]
It is posible to call a custom marker another way to icon:
        {url: "assets/icon/favoricon.png"}?
with the wkwebview the app don't work, I think it's because of this...

WKWebView still has some issues when referencing local files, file://. We tried many solutions but went with a local server, as it was the only solution that worked for every case.

If you’re working with local files (text files, images, videos), you’ll need to make sure that the path of file does not have file:// in front of it.
