### ISSUE TITLE
Typing Error in QuickExample CameraPosition

### ISSUE THREAD

**Issue by GitToTheHub** [mapsplugin/cordova-plugin-googlemaps#1762]
<pre>
var options = {
  camera: { 
    position: {lat: ..., lng: ...},  << position musst be replaced with "target"
    zoom: 19
  }
};
var map = plugin.google.maps.Map.getMap(mapDiv, options)
</pre>

**Comment by wf9a5m75** [comment]
When you find typo, please send a PR.

**Comment by wf9a5m75** [comment]
Fixed.

**Comment by GitToTheHub** [comment]
Thanks.
