### ISSUE TITLE
Typing Error in Docu map.addMarker()

### ISSUE THREAD

**Issue by GitToTheHub** [mapsplugin/cordova-plugin-googlemaps#1763]
Typing Error in Section **Adding multiple markers**

Folowing Code-Sample has a typing error:

<pre>
    // Set a camera position that includes all markers.
    var bounds = [];
    data.forEach(function(POI) {
      bounds.push(POI.position);
    });
</pre>

<pre>
  bounds.push(POI.position);
</pre>

must be

<pre>
  bounds.push(POI.getPosition());
</pre>

Maybe the variable "POI" could be called "marker". Thats more accurate.

**Comment by wf9a5m75** [comment]
You are misunderstand. You can not add marker instance.
You can add marker options(json).

**Comment by GitToTheHub** [comment]
Oh sorry, i used the markers variable in your example to fill the bounds array, instead of the data variable. Sorry my bad.
