### ISSUE TITLE
SVG images don't work as Icon.

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [mapsplugin/cordova-plugin-googlemaps#1767]
SVG images don't work as marker on the map it show the generic google marker.

**Comment by HamzaLJ** [comment]
Unfortunately SVG is not supported.
I hope that the author add its supports as PNG markers shows up with a low quality over the map.

**Comment by isrmicha** [comment]
Please add SVG to icons, PNG lose alot of quality

**Comment by wf9a5m75** [comment]
Currently not supportted yet.

**Comment by wf9a5m75** [comment]
Basically, the native apis does not support svg at all.
So, even if the plugin supports it, just converting from svg to png, then pass it.
It is the same as passing png file.
