### ISSUE TITLE
How to move a map under a centered marker 

### ISSUE THREAD

**Issue by HamzaLJ** [mapsplugin/cordova-plugin-googlemaps#1769]
**I'm submitting a ...**  (check one with "x")
[ X ] question
[ ] any problem or bug report
[ ] feature request

How can I center a marker in the middle of the screen and move the map under it ?

**Comment by wf9a5m75** [comment]
```html
<div id="map">
  <img src="marker.png=" class="center_middle">
</div>  
```

**Comment by HamzaLJ** [comment]
But If I use it that way, I won't be able to customize the marker and even won't be able to write inside that marker (for example base64 icon, etc...)
