### ISSUE TITLE
Map is slow on Xcode simlator

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1774]
Map version `2.1.0-beta-20170925-1216`
Xcode version `9.0`
Simulator running on `iOS 11`

Repo: https://github.com/antoine92190/ionic-map

You should see that the map is very slow when moving it around.

**Comment by wf9a5m75** [comment]
Yes, Xcode 9 simulator is very slow.
Please ask to Google.

**Comment by antoine92190** [comment]
Right, I will wait for an Xcode fix then. Thanks

**Comment by wf9a5m75** [comment]
FYI: https://github.com/mapbox/mapbox-gl-native/issues/9959#issuecomment-331911512

![screen shot 2017-09-25 at 2 55 42 pm](https://user-images.githubusercontent.com/167831/30832865-a0f01112-a201-11e7-8ef2-028068a64d11.png)

https://twitter.com/xenadu02/status/911463433521860609

**Comment by antoine92190** [comment]
Yes I found this exact same post when I googled the issue :smile:

**Comment by hongchaozhang** [comment]
See one workaround from [Apple forum](https://forums.developer.apple.com/thread/83570). It works for me.
