### ISSUE TITLE
Pushing back to view 1 shows up a blank map page

### ISSUE THREAD

**Issue by HamzaLJ** [mapsplugin/cordova-plugin-googlemaps#1776]
**I'm submitting a ...**  (check one with "x")
[ X ] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ X ] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ X ] **iOS**

I have an ionic app where in `view 1` I have the map, when I push `view 1` to `view 2` then when I try to go from `view 2` to `view 1` I get a blank view !

I believe the reason is that the map has a unique `id` and when pushing from `view 2` to `view 1` maybe it create another map with the same it (or something like this....)

**Comment by wf9a5m75** [comment]
Please share your project files on github.
I'm really busy person. Please save my time as much as possible.

**Comment by HamzaLJ** [comment]
Here is it on BitBucket, you may reproduce the issue : https://Mzzika@bitbucket.org/Mzzika/testmap.git

**Comment by wf9a5m75** [comment]
Thank you. I appreciate.

**Comment by wf9a5m75** [comment]
Could you upload package.json file?
I need to install the package one by one.

**Comment by HamzaLJ** [comment]
Done

**Comment by wf9a5m75** [comment]
![screen shot 2017-09-25 at 4 31 12 pm](https://user-images.githubusercontent.com/167831/30835786-f5f78ed0-a20e-11e7-8767-d26940b8559d.png)

**Comment by HamzaLJ** [comment]
True, just discovered that, but that doesn't cause the issue.
I've already edited it and posted a commit, please update app.module.ts

**Comment by wf9a5m75** [comment]
I can only see these commits. Did you push it?
![screen shot 2017-09-25 at 4 43 54 pm](https://user-images.githubusercontent.com/167831/30836044-bf3a347c-a210-11e7-841f-a1b5df7b773c.png)

**Comment by HamzaLJ** [comment]
Yes, can yo please your `app.module.ts` ?

**Comment by HamzaLJ** [comment]
This is the correct one anyway : 

        import { BrowserModule } from '@angular/platform-browser';
        import { ErrorHandler, NgModule } from '@angular/core';
        import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
        import { SplashScreen } from '@ionic-native/splash-screen';
        import { StatusBar } from '@ionic-native/status-bar';
        import { MyApp } from './app.component';
        import { HomePage } from '../pages/home/home';
        import { AboutPage } from '../pages/about/about';
        import { GoogleMaps, Geocoder } from '@ionic-native/google-maps'

        @NgModule({
          declarations: [
            MyApp,
            HomePage
          ],
          imports: [
            BrowserModule,
            IonicModule.forRoot(MyApp)
          ],
          bootstrap: [IonicApp],
          entryComponents: [
            MyApp,
            HomePage,
            AboutPage
          ],
          providers: [
            StatusBar,
            SplashScreen,
            {provide: ErrorHandler, useClass: IonicErrorHandler},
            GoogleMaps,
            Geocoder
          ]
        })
        export class AppModule {}`

**Comment by wf9a5m75** [comment]
Yes, there is the same file (I just `git pull` and `run it`), but I still get the error.

Please prepare the perfect work project files.

**Comment by HamzaLJ** [comment]
That's weird, I don't get that error at all, I have the exact same project files

**Comment by wf9a5m75** [comment]
Sorry, I'm not ionic user.
Until you solve this error, I can not test your app.

**Comment by HamzaLJ** [comment]
Can you please try to re-create it again, I am using the same repo in my local machine and it runs with no issues

**Comment by wf9a5m75** [comment]
Okay, I got the reason. This error occurs when I reload your app from the web inspector.
However, your app runs fast, so without reloading, I can not see the console.log.

--------

In your code, 

```
  constructor(private googleMaps: GoogleMaps, public platform: Platform, public navCtrl:NavController,private reverseGeocode : Geocoder) {

    // Wait the native plugin is ready.
    platform.ready().then(() => {
          this.mapElement = document.getElementById('map');  <-- This might be null because view is not ready.
      this.loadMap();

         this.map.addEventListener(GoogleMapsEvent.CAMERA_MOVE_START).subscribe((position)=>{
          console.log('Lat ', position.target.lat, ' lng ', position.target.lng)
         })


    });

  }

```

**Comment by HamzaLJ** [comment]
Got it, but did you discover the issue ?

`this.mapElement = document.getElementById('map');` is placed inside `platform.ready().then()` to ensure that the DOM is fully loaded.

**Comment by wf9a5m75** [comment]
`platform.ready().then()` is not guaranteed to complete thr view, because it is the wrapper of the deviceready event of cordova.

`ionViewEntered` is the signal that DOM is ready completely.

**Comment by HamzaLJ** [comment]
I also tried to put `this.mapElement = document.getElementById('map');` inside `ionViewDidEnter` but it didn't work, you may try it in the repo you have

**Comment by wf9a5m75** [comment]
Unfortunately your app does not runbat all.
I can not see anything on your app, only white page.
And if I reload your app, I get the error.
So how can I debug your app?????

Until you fix the error when I reload your app, I don't work for this anymore. I'm so busy person. I can not waste my time further.

**Comment by HamzaLJ** [comment]
After several hours I found that the homePage has lazyLoading, I removed it and it worked fine !
Thanks for your time and for this great plugin !

**Comment by wf9a5m75** [comment]
You are welcome. [I appreciate if you buy me a beer](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
