### ISSUE TITLE
iOS/Android running out of memory

### ISSUE THREAD

**Issue by carlcronje** [mapsplugin/cordova-plugin-googlemaps#1777]
First of all, I love your plugin!

I have been using v1.4.0, and it worked perfectly for me, but it has stopped working on iOS 11, so I upgraded to v2.0.0, but now I run out of memory and my app gets really, really slow. as soon as I invoke the plugin.

I am just loading 1 map and reusing it, when I remove it from the screen I do the following:
    this.map.setDiv();
    this.map.clear();
    this.map.off(); 

I unfortunately still run out of memory on android and iOS.

Is there maybe something else I should do?

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by wf9a5m75** [comment]
```
this.map.setDiv();
this.map.clear();
this.map.off();
```

This is really bad performance in the v2.

You just need `this.map.clear()` or `this.map.remove()`

**Comment by carlcronje** [comment]
I have a singleton in which I have the following code.

    map: null,

    getMap: function (div, options, callback) {
        var me = this;
        if (me.map){
            me.map.setDiv(div);
            me.map.setOptions(options);
            callback(me.map);
        } else {
            me.map = plugin.google.maps.Map.getMap(div, options);
            me.map.addEventListener(plugin.google.maps.event.MAP_READY, callback);
        }
    },

    cleanMap: function () {
        if (this.map) {
            this.map.setDiv();
            this.map.clear();
            this.map.off();
        } 
    },
When I want map instance I call getMap() ;
When the page that the map is on gets removed it calls  cleanMap();

Am I using the map plugin wrong?

**Comment by wf9a5m75** [comment]
Please create a demo project, and share it on github.

**Comment by carlcronje** [comment]
Please just tell me if it's possible to use a single map in V2.0.0?
And if so how?

**Comment by wf9a5m75** [comment]
There is ton's of demo code.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md#classes

https://github.com/mapsplugin/v2.0-demo

**Comment by carlcronje** [comment]
Sorry I did not mean to close issue.

**Comment by carlcronje** [comment]
There is unfortunately no code on v2.0.0 on how to reuse a single map instance.

**Comment by wf9a5m75** [comment]
Check out this guys code.
https://github.com/carvemerson/map

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update for a while, I close this thread.
