### ISSUE TITLE
Is it possible to draw a route between two coordinates ?

### ISSUE THREAD

**Issue by HamzaLJ** [mapsplugin/cordova-plugin-googlemaps#1778]
**I'm submitting a ...**  (check one with "x")
[ X ] question
[ ] any problem or bug report
[ ] feature request

I have a starting and ending point.
Is it possible to draw a route using between the two points (coordinates) ?

**Comment by wf9a5m75** [comment]
Nop.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1663#issuecomment-328197013
