### ISSUE TITLE
Why I can't access to getMap() property ?

### ISSUE THREAD

**Issue by HamzaLJ** [mapsplugin/cordova-plugin-googlemaps#1779]
**I'm submitting a ...**  (check one with "x")
[X] question
[ ] any problem or bug report
[ ] feature request

I am trying to do the following : `this.map.getMap` however, the code editor throws an error saying `Property 'getMap' does not exist on type 'GoogleMap'` where map is an instance of `GoogleMap`

What's wrong with it ?

**Comment by wf9a5m75** [comment]
Without your code, how can I help you?

**Comment by HamzaLJ** [comment]
Here is it : 

      var mapDiv = document.getElementById("map_canvas");
       var map = this.map.getMap(mapDiv, { ///editor throws error here
         camera: {
          target: this.decodedPath
         }
    });

**Comment by wf9a5m75** [comment]
Can you show me the code overall?

**Comment by HamzaLJ** [comment]
I found that .getMap property does not belong to `Map` in ionic, instead I used `createElement` and it worked.
