### ISSUE TITLE
Hide red Area on marker cluster zoom

### ISSUE THREAD

**Issue by TimothyFehr** [mapsplugin/cordova-plugin-googlemaps#1783]
Hello,

**I'm submitting a ...**  (check one with "x")
[X] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[X] **2.0 (npm)** 

I am looking for a solution to hide the red area which shows the focus area when clicking on a cluster marker, shown in your demo (https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/MarkerCluster/README.md), and by the love of all that is good and holy i can not figure out where that area marking is coming from and how i can hide it.

Optionally question, can i change the area so it is about 20px bigger than currently calculated? (it sometimes cuts some of my custom marker icons in half (on the edge of the map)

Can you please help me out?

Thanks in advance.
Tim

**Comment by mihaicolceriu** [comment]
As you can see in the documentation:
```
And other optional parameters are:
boundsDraw: draw bounds when you tap on a clustered marker (default: true)
```
so to answer your question, you need to change boundsDraw parameter to false.

Regarding your second question, I am not sure exactly what you are referring to. Can you provide an example?

**Comment by wf9a5m75** [comment]
Thank you, @mihaicolceriu 

@TimothyFehr 
For the second question, there is no option at this time.

**Comment by TimothyFehr** [comment]
How could i miss that.

Sad to hear that my second question is not doable but it was kind of a nice to have anyway

Thanks a lot @mihaicolceriu & @wf9a5m75
