### ISSUE TITLE
iOS Map Clustering

### ISSUE THREAD

**Issue by mihaicolceriu** [mapsplugin/cordova-plugin-googlemaps#1785]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[x] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-call-number 1.0.1 "Cordova Call Number Plugin"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-googlemaps 2.0.10 "cordova-plugin-googlemaps"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
{}
```

**Current behavior:**
I use google maps to cluster different locations with custom icon. The map moves zooms in/out as expected. Each time I move the map, I update the location markers (clusters) with MAP_DRAG_END event. First I clear the map, and after that, I repopulate the array of markers for the cluster. Everything works just fine, but at some point my app crashes. This does not happen right away and seems to be random, but it mostly happens when I use rapid movements, zooms in/outs.

**Expected behavior:**
The map should move/zoom in/out and update markers/clusters without crashing. This works fine, but as I mentioned above, at random times it crashes. I am not sure if this happens on Android as well, since I can only test it on iOS.

**Steps to reproduce:**
Move/Zoom in/out on map quickly.

**Screen capture or video record:**
https://imgur.com/PmIV68z

**Related code, data or error log (please format your code or data):**
Here are some device crash logs:
1. https://pastebin.com/8JUTnfjn
2. https://pastebin.com/sm3zbG2a
3. https://pastebin.com/ajVk4V3t

Xcode console: when launching the app:
```
2017-09-28 14:40:16.116 Potdrive[9494:7506543] THREAD WARNING: ['Console'] took '407.906982' ms. Plugin should use a background thread.
```

When tested on simulator (crash log):
https://imgur.com/a/r9cB0

Optionally, sometimes when clicking on a cluster, the cluster doesn't do anything.

I think there is a memory leak or something goes wrong (sempaphores) when redrawing the markers, more precisely, when deleting the old markers from the map.

**Comment by wf9a5m75** [comment]
Please  share your project files on github.

**Comment by mihaicolceriu** [comment]
@wf9a5m75 https://github.com/mihaicolceriu/phonegap

**Comment by mihaicolceriu** [comment]
I did not have an inspiring name for that function, at the time.
When navigating through the app, I hide the map using map.setDiv(null).
The function shows the map when user returns to the map.

**Comment by wf9a5m75** [comment]
In that case, you just need to do `map.setDiv(div)`.

```
  function enableMap() {
      map.setDiv(div)
  }
```

**Comment by mihaicolceriu** [comment]
Good catch, thank you.
The enableMap function is only called when navigating through the app. When the app first loads, it loads the map first thing. As long as I only navigate the map, the function is not called. I changed it, and it works fine, but still the crash mentioned above occurs.

**Comment by wf9a5m75** [comment]
Yes, I will check it from now.

**Comment by mihaicolceriu** [comment]
@wf9a5m75 did you manage to reproduce the bug?

**Comment by wf9a5m75** [comment]
Yap. Could you try the multiple_maps branch version?

**Comment by mihaicolceriu** [comment]
Thank you, the app does not crash anymore. But there is something new: after navigating for about 1 minute on the map, at a certain point, the markers are not loaded anymore and the app suddenly freezes completely. Not sure what is causing this.

**Comment by wf9a5m75** [comment]
Could you describe more certain steps? I appreciate if you record the steps.

**Comment by mihaicolceriu** [comment]
@wf9a5m75 https://youtu.be/1GOzFtYlQQU . The problem occurs at around 0:21 mark. If I tap outside the map, the app freezes.

**Comment by kalitk0** [comment]
I had the same issue but with the fix it is working fine now. I have a question why is this red rectangle when a cluster is clicked ?

**Comment by mihaicolceriu** [comment]
@kalitk0 good to know. Does your app freeze as well as mine does, or is it isolated only for my app?
@wf9a5m75 do you have any news regarding the second problem that I mentioned?

**Comment by kalitk0** [comment]
@mihaicolceriu no i have not encountered such an issue for now

**Comment by mihaicolceriu** [comment]
Seems that this is not the case for other users as well. I guess that the problem may be related with how I show/hide the map. This happens very often on my app. What is the correct way to show/hide the map?
If the map was not initialised at all, I show the map using:
```
div = document.getElementById('map_canvas');
map = plugin.google.maps.Map.getMap(div);
map.setDiv(div);
map.one(plugin.google.maps.event.MAP_READY, function() {
      //Show my location on the map
      map.setMyLocationEnabled(true);
      map.setAllGesturesEnabled(true);
      //Fly map to my location
      fly_map_to_current_location();  
});
```

To hide the map, I use
```
map.setDiv(null)
```
and to show the map again, I use
```
div = document.getElementById('map_canvas');
map.setDiv(div)
```
Is this the correct way to do this?

**Comment by wf9a5m75** [comment]
```
map = plugin.google.maps.Map.getMap(div);
map.setDiv(div); // <-- you should not do that.
```

**Comment by wf9a5m75** [comment]
@mihaicolceriu I have been recognized for your issue. The issue occurs for some reason. I have been working for this.

**Comment by wf9a5m75** [comment]
One of the reason of this is you execute `map.clear()` when the map is dragged every time.
Then generate new marker cluster.
This is very bad performance, and may cause this trouble.

**Comment by mihaicolceriu** [comment]
@wf9a5m75 Yes, I figured that out. For the moment I removed the clusters and only addMarkers (maximum 50). I use an array to keep track of what markers to show based on map bounds (no more map.clear()). If the map moves, remove the markers which are no longer in the map bounds, keep those that are still in the map bounds, and add new markers (if any) for the new bounds.
```
map = plugin.google.maps.Map.getMap(div);
map.setDiv(div);
```
What should be the correct approach to show/hide map as many times as I wish, without it breaking? The map does not appear if I don't use "map.setDiv(div)".

**Comment by mihaicolceriu** [comment]
```
function clearMarkerList(latLngBounds) {
    $.each(markerList, function(index, value) {
      lat = value.marker.get('position').lat
      lng = value.marker.get('position').lng
      if (lng > latLngBounds.southwest.lng && lng < latLngBounds.northeast.lng && lat < latLngBounds.northeast.lat && lat > latLngBounds.southwest.lat) {
        return true
      } else {
        value.toDelete = true
      }
    })
    
    markerList = $.grep(markerList, function(el, i) {
      if (el.toDelete) {
        el.marker.remove()
        return false
      } else {
        return true
      }
    })
    markerCount = markerList.length
  }
  
  function updateMap() {
    //get map bounds
    latLngBounds = map.getVisibleRegion()
    clearMarkerList(latLngBounds)
    $.each(window.locations_data.features, function(ind, value) {
      if ($.inArray(value.properties.category, window.category) != -1) {
        if (value.geometry.coordinates[0] > latLngBounds.southwest.lng && value.geometry.coordinates[0] < latLngBounds.northeast.lng && value.geometry.coordinates[1] < latLngBounds.northeast.lat && value.geometry.coordinates[1] > latLngBounds.southwest.lat) {
          if (markerCount < MARKER_LIMIT) {
            toPush = true
            $.each(markerList, function(i, v) {
              if (ind == v.index) {
                toPush = false
                return false
              }
            })
            if (toPush) {
              markerCount += 1
              addMarkerToList(ind, value);  
            }
          } else {
            return false
          }
        }  
      }
    })
  }

  //add markers to map
  function addMarkerToList(index, location) {
    fullAddress = window.setFullAddress(location)
    iconData = getImage(location)
    map.addMarker({
      position: {
        lat: location.geometry.coordinates[1],
        lng: location.geometry.coordinates[0]
      },
      icon: iconData,
      title: location.properties.name,
      image: location.properties.image,
      phone: location.properties.phone,
      fullAddress: fullAddress,
      location: location
    }, function(marker) {
      markerList.push({index, marker, 'toDelete': false})
      // window.list_page_data.push(location)
      marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
        popup(location)
      });
    })
  }
```
Somehow, the markerList (list of visible markers on the map) still sometimes contains duplicates? Maybe I've done something wrong here?

**Comment by wf9a5m75** [comment]
Could you update the repository?

**Comment by wf9a5m75** [comment]
I might figure out the reason.
In your original code, you execute `map.clear()` twice (This is nonsense though).
Because of this, the plugin causes the dead lock of semaphore in the marker cluster class.

```js
$.when(map.clear()).done(function() {
      map.clear();
      ...
```

I updated the code to prevent the dead lock. As far as I tested, I haven't faced the error anymore.
But please try by yourself with the `multiple_maps` branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."  --verbose --no-fetch

```

**Comment by wf9a5m75** [comment]
ping

**Comment by mihaicolceriu** [comment]
@wf9a5m75 As I mentioned in my earlier post, I changed the code quite a bit and removed clusters. At this moment, I only call map.clear() twice in my code and it is NOT one after the other as mentioned above by you (which caused the deadlock). Everything works fine now, and the app does not crash. This can be marked as fixed. If I should experience any other bug or unpredicted behavior, I will open a new issue.
Thank you very much for your support.
