### ISSUE TITLE
I cant install the plugin 

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#1786]
Any idea why i cannot install the plugin i could in the past i dont know what is wrong now 

$ ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="mykey" --variable API_KEY_FOR_IOS="mykey" --save
× Running command - failed!
[ERROR] An error occurred while running cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multi... (exit code 1):

        Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! Windows_NT 6.1.7601
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\NATALIA\\Documents\\mdp365-ionic3\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps" "--save"
        npm ERR! node v6.10.3
        npm ERR! npm  v2.15.12
        npm ERR! code EPEERINVALID

        npm ERR! peerinvalid The package @angular/core@4.1.0 does not satisfy its siblings' peerDependencies requirements!
        npm ERR! peerinvalid Peer @angular/common@4.1.0 wants @angular/core@4.1.0
        npm ERR! peerinvalid Peer @angular/compiler@4.1.0 wants @angular/core@4.1.0
        npm ERR! peerinvalid Peer @angular/compiler-cli@4.1.0 wants @angular/core@4.1.0
        npm ERR! peerinvalid Peer @angular/forms@4.1.0 wants @angular/core@4.1.0
        npm ERR! peerinvalid Peer @angular/http@4.1.0 wants @angular/core@4.1.0
        npm ERR! peerinvalid Peer @angular/platform-browser@4.1.0 wants @angular/core@4.1.0
        npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@4.1.0 wants @angular/core@4.1.0
        npm ERR! peerinvalid Peer @ionic-native/call-number@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/diagnostic@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/facebook@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/geolocation@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/google-analytics@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/google-maps@4.3.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/location-accuracy@4.3.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/network@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/onesignal@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/screen-orientation@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/social-sharing@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/splash-screen@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/status-bar@3.7.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic-native/toast@3.14.0 wants @angular/core@*
        npm ERR! peerinvalid Peer @ionic/storage@2.0.1 wants @angular/core@*
        npm ERR! peerinvalid Peer angular2-moment@1.7.0 wants @angular/core@>=2.0.0 <6.0.0
        npm ERR! peerinvalid Peer ionic-angular@3.2.1 wants @angular/core@4.1.0
        npm ERR! peerinvalid Peer ionic-gallery-modal@0.1.1 wants @angular/core@^4.1.2

        npm ERR! Please include the following file with any support request:
        npm ERR!     C:\Users\NATALIA\Documents\mdp365-ionic3\node_modules\npm-debug.log

**Comment by wf9a5m75** [comment]
Try
```
$ ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="mykey" --variable API_KEY_FOR_IOS="mykey" --save
```

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps#if-you-cant-reinstall-the-plugin-try-like-this

**Comment by HamzaLJ** [comment]
It fails several times, just keep re-trying and use : 

```
ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="mykey" --variable API_KEY_FOR_IOS="mykey" --save
```

**Comment by francoro** [comment]
My problem was when i tried to install it with Git Bash. Works great in cmd of windows. You can close it

**Comment by minortom** [comment]
It works if you remove ionic and add the --nofetch and --save option

`cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="apikey" --variable API_KEY_FOR_IOS="apikey" --save --nofetch`

**Comment by KishanIos007** [comment]
I am using cmd but still have the same error.After search for a while i get this solution
```
1) npm cache clear
2) ionic cordova platfrom rm android
3) ionic cordova platfrom add android
4) ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID=api_key
```

**Comment by NarendraGumma** [comment]
@KishanIos007 
use this command 
ionic cordova platform remove android
