### ISSUE TITLE
setDiv(...) fails if map is initialised with "off-screen-div" 

### ISSUE THREAD

**Issue by fogfish** [mapsplugin/cordova-plugin-googlemaps#1788]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 
[x] **2.0 (GitHub/multiple_maps)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-googlemaps 2.1.0-beta-20170929-1050 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.3 "Cordova WKWebView Engine"
```

**Current behavior:**

setDiv(...) does nothing is map is initialised with "off-screen" element. See snippet below. It is expected that `map.setDiv(div)` would render the map on screen but it remains blank.

```
var div = document.getElementById("map_canvas_offscreen");
var offscreen = document.createElement('div');
offscreen.style.width = div.style.width;
offscreen.style.height = div.style.height;

var map = plugin.google.maps.Map.getMap(offscreen);
map.one(plugin.google.maps.event.MAP_READY, function() {

  var buttonA0 = div.getElementsByTagName('button')[0];
  buttonA0.addEventListener('click', function() {
    map.setDiv(div)
  });
  var buttonA1 = div.getElementsByTagName('button')[1];
  buttonA1.addEventListener('click', function() {
    map.setDiv()
  });

});
```

**Expected behavior:**

setDiv() should work.

**Steps to reproduce:**

I've integrated this demo to [your demo app](https://github.com/fogfish/v2.0-demo/blob/master/www/Map/setDiv.html)

**Comment by wf9a5m75** [comment]
Should not do that.

**Comment by fogfish** [comment]
Hmm, How init map in the background? It takes a while to create a map.

**Comment by wf9a5m75** [comment]
I haven't tested this case recently, but should work. 
```js
var map = plugin.google.maps.Map.getMap();
map.one(plugin.google.maps.event.MAP_READY, function() {

  var buttonA0 = div.getElementsByTagName('button')[0];
  buttonA0.addEventListener('click', function() {
    map.setDiv(div)
  });
  var buttonA1 = div.getElementsByTagName('button')[1];
  buttonA1.addEventListener('click', function() {
    map.setDiv()
  });

});
```

**Comment by fogfish** [comment]
Yes, you are right this is a way to make it (al least it works). I'll close this issue now.
