### ISSUE TITLE
Event for cluster zoom on marker click

### ISSUE THREAD

**Issue by TimothyFehr** [mapsplugin/cordova-plugin-googlemaps#1789]
**I'm submitting a ...**  (check one with "x")
[X] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[X] **2.0 (npm)** 

What event do you trigger when you finished your Cluster zoom? I try to recalculate the visible makers and the normal events like zoom_end and camera_move_end do not seam to be triggered.

thans in advance

**Comment by wf9a5m75** [comment]
CAMERA_MOVE_END only

**Comment by TimothyFehr** [comment]
Der wird bei mir leider nicht getriggert,

```
markerCluster.on(plugin.google.maps.event.CAMERA_MOVE_END, () => {
    vm.storeVisibleMarkers();
});
```

**Comment by wf9a5m75** [comment]
The CAMERA_MOVE_END event is fired from map only.
