### ISSUE TITLE
Angular - plugin is not defined

### ISSUE THREAD

**Issue by chrillewoodz** [mapsplugin/cordova-plugin-googlemaps#1790]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 

**cordova information:**  (run `$> cordova plugin list`) 
```
cordova-plugin-battery-status 1.1.2 "Battery"
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-contacts 2.0.1 "Contacts"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-device-motion 1.2.5 "Device Motion"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-media 2.2.0 "Media"
cordova-plugin-media-capture 1.2.0 "Capture"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-whitelist 1.2.2 "Whitelist"
```

I'm trying to get this to work in an Angular environment, but it keeps saying `plugin is not defined`. I've scraped the internet for solutions but I can't find anyone who has had this problem, what is `plugin` and how can I make my app realise what it is?

What I'm doing now is having a Cordova app inside an Angular CLI project. Then I run this command in one terminal tab:

```
ng b --output-path cordova/www/ --baseHref ./ --watch
```

What this does is build the angular project and output the files in the Cordova project's `www` folder which can then be previewed in my Phonegap Developer App on my Android by running this:

```
phonegap serve
```

I'm starting to become really depressed by this and I would greatly appreciate any hints or guidance in order to get this to work.

**Comment by wf9a5m75** [comment]
Please share the project files on github.

**Comment by wf9a5m75** [comment]
I noticed that you use `phonegap serve`.
However this plugin does not work on browser. Only works on Android and iOS devices.
So you can not use this plugin with `phonegap serve` command.

**Comment by chrillewoodz** [comment]
@wf9a5m75 OK, but if I am using the Developer App that should work, no? Or does that count as a browser?

**Comment by chrillewoodz** [comment]
Ok I just managed to get it to run on Android! SO HAPPY. Big thanks for that hint, like really. Massive thanks.

**Comment by bmonson** [comment]
I'm having the very same problem - neither the Phonegap Developer App or any build from Phonegap Build works when I include the plugin. How did you fix it, @chrillewoodz?
