### ISSUE TITLE
Marker object for a marker in a Cluster

### ISSUE THREAD

**Issue by gassaki** [mapsplugin/cordova-plugin-googlemaps#1791]
I'm submitting a ... (check one with "x")
[X] question
[ ] any problem or bug report
[ ] feature request

The plugin version: (check one with "x")
[ ] 2.0-beta3 (github)
[X] 2.0 (npm)

Is it possible to access the Marker object for a marker in a Cluster? I'd like to set custom data and change properties for markers in the Cluster, but couldn't get the object.

Thank you in advance!

**Comment by wf9a5m75** [comment]
You can pass any additional parameter to the markers option.

```js
map.addMarkerCluster({
  markers: [
    {position: {lat: ..., lng: ...}, title:"hoge", myData: "myValue"},
    ....
    N
  }

}, function (markerCluster) {
   markerCluster.on(plugin.google.maps.event.MARKER_CLICK, function (position, marker) {
     var myData = marker.get("myData");
   });
});
```

Please read the example code.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/MarkerCluster/addMarkerCluster/README.md

**Comment by gassaki** [comment]
Thank you @wf9a5m75 , but is it possible to access the markers later? Like, if I want to modify some property after the marker is already added.

**Comment by wf9a5m75** [comment]
Nop.

**Comment by wf9a5m75** [comment]
Only available way is `markerCluster.addMarker(s)` method.

**Comment by gassaki** [comment]
Maybe in the future, markerCluster.addMarker() could return Promise, like map.addMarker()?

**Comment by wf9a5m75** [comment]
Nop.
You should store only the position id, then store actual data in somewhere.
This is the **basic** of programming.

```js
   markerCluster.on(plugin.google.maps.event.MARKER_CLICK, function (position, marker) {
     var myId = marker.get("myId");
     getDataFromDB(myId, function(data) {
         ..
     });
   });
```

**Comment by gassaki** [comment]
Yes, but what if in that Starbucks example I want to show a different icon, or change the opacity, for open and closed places? I have to remove the entire cluster and create it again, right?

**Comment by wf9a5m75** [comment]
Dp you want to change the icon of all markers? In that case, you need to recreate the marker cluster.
If you want to change just the marker you opened, it's easy. You can do that like a regular marker.

The marker cluster passes the instance of the clicked marker as the second argument.

**Comment by gassaki** [comment]
Right, but I don't want to change all markers neither clicked ones. Let's say markers for open stores are green and red for closed. An user is running the app from 6:55pm to 7:10pm. Some stores were open at 6pm but closed at 7pm. I need to change the icon for the closed stores without the user clicking them.

**Comment by wf9a5m75** [comment]
Unfortunately not available for that case.
