### ISSUE TITLE
Android conflics

### ISSUE THREAD

**Issue by patrickboulay** [mapsplugin/cordova-plugin-googlemaps#1793]
Hi,

It seems that I have conflics with the new version of the plugin and other plugin. When I build my project, I get this error:

project_folder/platforms/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml
Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

Does anyone know how to fix this?

Thanks

**Comment by wf9a5m75** [comment]
I think this error is not related with this plugin.

**Comment by patrickboulay** [comment]
I dont have this error with the version 1.4.5, only the version 2...

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by wf9a5m75** [comment]
ping

**Comment by patrickboulay** [comment]
sorry, same problem with version 1.4.5, Its not a problem with this plugin.. sorry!
