### ISSUE TITLE
[Feature] MBtiles or base64 images support ?

### ISSUE THREAD

**Issue by thiphariel** [mapsplugin/cordova-plugin-googlemaps#1795]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[x] feature request

I saw that `getTile()` method **must** return a string, but how about supporting base64 images, like ones stored in an `.mbtiles`sqlite database ?
Returning a string of the url or the blob image itself is nearly the same thing I guess, can you confirm it ?

Do you think it can be added as an enhancement of this plugin ?

Cheers :)

**Comment by wf9a5m75** [comment]
Why do you need this? I am not interested in at all.

**Comment by thiphariel** [comment]
It could provide a much better way to handle offline tiles support. With the current method, you should pack a lot of images in the application itself, or download it from the internet. 
The MBtiles format, which is just nothing more like an SQLite database (it's much more than that but it's not the point here), it's quite smaller than the images. Just one file to embed in the application and all you have to do is a sql query to retrieve the base64 image for an x, y and zoom level.

It's not a big deal, you're still the owner so the choice is yours ! :)

Cheers

**Comment by wf9a5m75** [comment]
>Thus, the actual length of MIME-compliant Base64-encoded binary data is usually about 137% of the original data length

https://en.wikipedia.org/wiki/Base64

Regarding of wikipedia, the encoded data by base64 is bigger than original data size.

------

I think store the image data to files, then store the file path in to the SQL database. That's smart solution.

**Comment by thiphariel** [comment]
Hmm, weird. I did a test and my sqlite database (MBTiles) was around ~20% lighter (37Mb vs 45Mb)

Maybe it's an optimization of the mbtiles format. 

Why would you store in an SQL database if you already have the files ? I mean, my question was about the opposite way. 
But I understand your position, I guess I can read the MBtiles database at the app launch, store the images on the device, then use the `tileOverlay` with these images.

I close this, and feel free to re open if needed for more info.

Thanks
