### ISSUE TITLE
Race condition: TileOverlay.clearTileCache() is called on a null object reference

### ISSUE THREAD

**Issue by sam2x** [mapsplugin/cordova-plugin-googlemaps#1797]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 
[x] 2.1.0-beta-20170929-1050

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.1.0-beta-20170929-1050 "cordova-plugin-googlemaps"
```

**Current behavior:**

I have differents views on my app. The bug can be spotted by doing the following steps: 

1. Go to map view. 
2. Wait for the map loading. 
3. Leave the view. 
4. Repeat step 1 until the app crash (you may repeat it several times).

**Expected behavior:**

The app is not crashing when going back to the view.

**Steps to reproduce:**

Install last version, create 2 views (home page / map view). Switch between the pages until the app crash..

**Related code, data or error log (please format your code or data):**

```
10-05 12:09:41.996 21321-21321/com.xxx.xxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.xxx.xxx, PID: 21321
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.model.TileOverlay.clearTileCache()' on a null object reference
                                                                       at plugin.google.maps.PluginTileOverlay$2.run(PluginTileOverlay.java:175)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:7331)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

A race condition occurs sometimes, during the map destruction, the Tile handler destructor (remove) is called, however it is sometimes called even if Tile hasnt been (yet) created. The faulty code line 175 of maps/PluginTileOverlay.java : 

        tileOverlay.clearTileCache();

** How to solve ** 

Check if tileOverlay is not null before calling any method (like you did on line 94).

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by sam2x** [comment]
Dude, the stacktrace is self explanatory, I dont have time to provide a new sample project. Plus, I gave you the "one line code" solution.... If you read the stack-trace and the source, you will not need to spend time debugging.

**Comment by wf9a5m75** [comment]
Important thing is to figure out the reason of the error.
I haven't experienced the error never.
And I haven't received this error except you.
Further, the plugin does not execute the `clearTileCache` method automatically.
So I guess the reason is based in your code.

If you don't share the project, I will close this thread.
I'm so busy.

**Comment by sam2x** [comment]
It is called when I destroy map (as said in my issue). The issue is related to the way I destroy the map, in following order (during the view destruction) : 

1. map.clear();
2. map.off();
3. map.remove();

I think the problem is that map.clear() is the first to destroy the TilesOverlay, and Map.remove() tries to destroy it again... Its not 100% due to my code (To avoid this issue, i just removed the map.clear). I use it to be sure there is 0 memory leak. I think you should care about not trying to remove a null object that was destroyed wiht map.clear()...Or state it in the documentation. No need to thanks me.
Good luck.

**Comment by wf9a5m75** [comment]
Thank you. I agree your code was the reason, because the steps.

The most plugin users do the same thing, like you, but map.remove() executes map.clear() and map.off() internally.

And when you execute the map.clear(), the plguin executes the clearTileCache() method.
I think it is the timing.
Because you execute map.clear() and map.remove().

Until you explain your code steps, I couldn't figure out the reason. Then I can test to reproduce the issue.
