### ISSUE TITLE
PluginMap cannot find symbol

### ISSUE THREAD

**Issue by shivangcnc** [mapsplugin/cordova-plugin-googlemaps#1800]
**platforms/android/src/plugin/google/maps/PluginMap.java:52: error: cannot find symbol
import com.google.android.gms.maps.model.MapStyleOptions;
                                        ^
symbol:   class MapStyleOptions
location: package com.google.android.gms.maps.model**

It's showing this error while build project

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=cannot+find+symbol&type=Issues&utf8=%E2%9C%93

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1761
