### ISSUE TITLE
HTML Info Window overlaps marker

### ISSUE THREAD

**Issue by JaneDawson** [mapsplugin/cordova-plugin-googlemaps#1801]
I'm using the HTMLInfoWindow in combination with custom markers. Currently the HTMLInfoWindow overlaps the marker-icon. Looks like this:

![marker](https://user-images.githubusercontent.com/26357664/31339182-50c57e82-ad02-11e7-8d60-f196d7b180d8.png)

I don't want the infowindow to overlap the icon but start on top of the marker. Hence, I would like to move the HTMLInfoWindow further to the top. However, I don't get it done...

My code:

```
     let markerOptions: MarkerOptions = {
        position: location,
        zIndex: 10
      };
      [...]
      markerOptions.icon = { 
        'url': 'icon.png',
        'size': { width: 21, height: 34 }
      };
      [...]
      markerOptions.infoWindowAnchor= [11, -10]; // I tried with [11,0] as well. Same result
```
Any idea on how to achieve this? Thank you!

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/HtmlInfoWindow.js#L176

**Comment by JaneDawson** [comment]
I'm not sure what you want to tell me. If you want to say, I should use 'infoWindowAnchor': I already did. See the code I posted above.

**Comment by wf9a5m75** [comment]
> I should use 'infoWindowAnchor': I already did. See the code I posted above.

Yes, you should use the `infoWindowAnchor` property.
It does not work, please share your project files on github. I will check it.

Otherwise, you need to solve by yourself.

**Comment by wf9a5m75** [comment]
At least `markerOptions.infoWindowAnchor= [11, -10]` is wrong.
The values should be `[11,0]` (did you read the code? It's JavaScript, so you should be understood)

**Comment by JaneDawson** [comment]
Thank you for your response. Yes, I read the code. And I made some further research.
My icon size is: `{ width: 21, height: 34 }`

On `infoOffset.x` works fine. I got problems with the y-axis.
When I use `markerOptions.infoWindowAnchor= [11, 0]` the the info window starts too "low", as can be seen in the picture I posted. When I use `markerOptions.infoWindowAnchor= [11, 34]` the the info window starts lower than expected, as well. It then starts even a few pixels below the marker.

Hence, it seems like the calculations of `infoOffset` are correct, but they use another point from where to start the position of the marker and the infowindow.

Does that somehow help you and you have another idea of what else to try? Thank you!

**Comment by JaneDawson** [comment]
I was able to solve it, using `marker.setIconAnchor()`.
I had to use quite a strange combination, which in my case was `marker.setIconAnchor(21, 17);` and `markerOptions.infoWindowAnchor= [0, 0];` to receive the desired result.

Thanks for your support! The issue can be closed.

**Comment by JaneDawson** [comment]
Unfortunately, I was too quick in saying that solved it. The info window looks fine now, however, the marker it self is obviously moved, so it's not at the correct position anymore... 
So using marker.setIconAnchor() is no option...

Any other idea? Thank you!

**Comment by wf9a5m75** [comment]
Please share your project files on github. Without your project files, how can I test you?

You **MUST** give parameters to`marker.setIconAnchor() `

**Comment by JaneDawson** [comment]
I would love to share the project. However, unfortunately, I'm not allowed to...
Of course, I used parameters. As posted above, I used `marker.setIconAnchor(21, 17);` in combination with `markerOptions.infoWindowAnchor= [0, 0];`. Then the marker and infowindow looked well, however, the marker was pointing to a slightly wrong location.
I hope that you may still have some idea, even without having access to the code. .. Thank you!!

**Comment by wf9a5m75** [comment]
Sorry, I'm so busy. Without sharing the project files (even demo project), I don't work for this.

The `anchor` position means that the position at which to anchor an image in correspondence to the location of the marker on the map. By default, the anchor is located along the center point of the bottom of the image.

**Comment by JaneDawson** [comment]
Hi @wf9a5m75,
I put together a blank ionic starter project that demonstrates the issue: [](https://github.com/JaneDawson/maptest).
Thanks for looking into this!

**Comment by wf9a5m75** [comment]
Thank you for waiting.

In your code, your code is wrong (also the ionic-native/google-maps wrapper plugin is wrong).

You need to specify the anchor and the infoWindowAnchor in the icon property.

```js
      markerOptions.icon = {
        'url': 'www/assets/icon/marker2.png',
        'size': { width: 21, height: 34 },
        'infoWindowAnchor': [11, 0],
        'anchor': [21, 17]
      };
```

**Comment by JaneDawson** [comment]
Hi @wf9a5m75,
Did you have the chance to look into this?

**Comment by wf9a5m75** [comment]
Thank you for waiting. I'm really busy. I checked your project at once.
The reason is `HTMLInfoWindow does not consider the anchor property`.

I tried to fix that, but I'm so busy. Please wait or use the regular info window.

**Comment by JaneDawson** [comment]
Thank you for looking into this. I will wait some time and hope you'll get it fixed. Unfortunately, the HTML Info Window's functionality was the only reason for me to upgrade to v2 of the plugin, because the regular info window wasn't enough anymore...
Thanks for your effort! I appreciate that.

**Comment by wf9a5m75** [comment]
![screen shot 2017-10-18 at 7 29 39 pm](https://user-images.githubusercontent.com/167831/31751580-028a3f4c-b43b-11e7-8d6d-e8f92d12a1c3.png)

**Comment by wf9a5m75** [comment]
I fixed. Please reinstall the plugin from the multiple_maps branch (version `2.1.0-beta-20171018-1930`).


----

By the way, I appreciate if you support for this project.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
When you donate some amount to the project, please include your issue number in your name.

**Comment by JaneDawson** [comment]
Hi @wf9a5m75. Thanks for fixing this. The InfoWindow seems to be at the proper position now.

However, using the posted beta-version leads to bad behaviour on android. Whenever the Android Hardware Back button is clicked, the app is closed instead of removing the current page from the navigation stack. This is really bad... Hence, I had to remove the 2.1.0-beta and roll back to the stable version.

 When are you planning on publishing the fix in a stable release?

**Comment by wf9a5m75** [comment]
When you find a problem, please create a demo.

**Comment by JaneDawson** [comment]
I updated the repository (https://github.com/JaneDawson/maptest).

When pressing the back button, the app closes instead of going one step backwards in the navigation stack. Tested on One Plus X, Android 6.0.1

**Comment by wf9a5m75** [comment]
Thank you. I fixed it.
The reason of crash is you registered the backbutton event, but you didn't cancel the event, however you move back to another page.

I decided the plugin does not take care after the callback function.
The callback function must take care everything (the plugin does not take care).
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b1704af5e2003b6ed6e6d2251d02d74a8646bb5f/www/googlemaps-cdv-plugin.js#L543-L546

**Comment by JaneDawson** [comment]
Now it works like expected. Thank you!

However, in the current code there is some testing-leftover (a small red box in the upper left corner). I removed it manually on my side, however you should probably update your code:

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b1704af5e2003b6ed6e6d2251d02d74a8646bb5f/www/HtmlInfoWindow.js#L108-L113
