### ISSUE TITLE
Trigger redrawing after div resizing 

### ISSUE THREAD

**Issue by TimothyFehr** [mapsplugin/cordova-plugin-googlemaps#1802]
**I'm submitting a ...**  (check one with "x")
[X] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[X] **2.0 (npm)** 

Hello, 

Can you point me the direction on how I can trigger trigger a redrawing or other Google Map Events through your wrapper?

I am resizing the div in which the map is rendered. After that the map should theoretically adjust ist self to the new div size. But it does not do that.
Neither with: 
   vm.map.refreshLayout()
nor (the google v3 api way)
   window.plugin.google.maps.event.trigger(vm.map, 'resize');
   => trigger is not defined

The rendered map is still in the original size and my marker is outside of the view point.
after a few minutes when i remove the "focus" from the map by clicking elsewhere the map magically adjusts it self. (and fits the new div size as originally intended)

thanks in advance for your help.

**Comment by wf9a5m75** [comment]
`cordova.fireDocumentEvent('plugin_touch', {});`

**Comment by NicksonYap** [comment]
@wf9a5m75 
`cordova.fireDocumentEvent('plugin_touch', {});`

Couldn't figure how how run this function in Ionic 3
I used `this.events.publish('plugin_touch', {});` but didn't work

**Comment by UlisesCecaDT** [comment]
Hi, did you fix this somehow?

I'm using Ionic 3 and when I put a loader before the map is shown then it doesn't show
