### ISSUE TITLE
The request for google maps license info returns the string "OK" instead of the license info text

### ISSUE THREAD

**Issue by jlews** [mapsplugin/cordova-plugin-googlemaps#1807]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[x] **iOS**

**Current behavior:**
The request for google maps license info returns the string "OK" instead of the license info text.

**Expected behavior:**
The request for google maps license info should return the license info text.

**Steps to reproduce:**
Run the following JavaScript inside the application:
`plugin.google.maps.environment.getLicenseInfo(function(text){console.log(text);});`

**Screen capture or video record:**

![image](https://user-images.githubusercontent.com/15945708/31435057-2f832588-ae76-11e7-9bd4-fb7bc8f73e52.png)

**Related code, data or error log (please format your code or data):**
```
plugin.google.maps.environment.getLicenseInfo(
  function(text){
    console.log("Response text:", text);
  }
)
```

**Comment by wf9a5m75** [comment]
For Android is no longer required. For iOS is still required.

**Comment by jlews** [comment]
My apologies. I incorrectly reported this as broken in iOS, it is in fact working in iOS.
