### ISSUE TITLE
Marker Dragged End not Working

### ISSUE THREAD

**Issue by RanmalN** [mapsplugin/cordova-plugin-googlemaps#1811]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please show me the package.json**
"dependencies": {
        "angular/common": "4.1.3",
        "angular/compiler": "4.1.3",
        "angular/compiler-cli": "4.1.3",
        "angular/core": "4.1.3",
        "angular/forms": "4.1.3",
        "angular/http": "4.1.3",
        "angular/platform-browser": "4.1.3",
        "angular/platform-browser-dynamic": "4.1.3",
        "ionic-native/core": "3.12.1",
        "ionic-native/geolocation": "^4.2.1",
        "ionic-native/google-maps": "^4.3.0",
        "ionic-native/splash-screen": "3.12.1",
        "ionic-native/status-bar": "3.12.1",
        "ionic/storage": "2.0.1",
        "ngx-translate/core": "6.0.1",
        "ngx-translate/http-loader": "0.0.3",
        "chart.js": "^2.7.0",
        "cordova-android": "^6.3.0",
        "cordova-plugin-compat": "^1.2.0",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-geolocation": "^2.4.3",
        "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.6.1",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "tslint-config-airbnb": "^5.3.0",
        "zone.js": "0.8.12"
    }
**Current behavior:**
Nothing happen when marker is dragged

**Expected behavior:**
console.log('marker location changed'); when marked dragged is ended

**Related code, data or error log (please format your code or data):**

```
this.map.addMarker({
            title: 'Current Location',
            icon: 'red',
            animation: 'DROP',
            position: {
              lat: this.location.lat,
              lng: this.location.lng,
            },
            draggable: true,
          }).then((marker) => {
            marker.addEventListener(GoogleMapsEvent.MARKER_DRAG_END).subscribe(() => {
              console.log('marker location changed'');
            });
          });
```

**Comment by wf9a5m75** [comment]
You need to reinstall `@ionic-native/core`, `@ionic-native/google-maps` latest versions.
And also you need to reinstall the plugin from the multiple_maps branch.

**Comment by RanmalN** [comment]
I re-install the packages still doesn't work 

cordova plugin list

cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

package.json dependancies

"@angular/common": "4.1.3",
    "angular/compiler": "4.1.3",
    "angular/compiler-cli": "4.1.3",
    "angular/core": "4.1.3",
    "angular/forms": "4.1.3",
    "angular/http": "4.1.3",
    "angular/platform-browser": "4.1.3",
    "angular/platform-browser-dynamic": "4.1.3",
    "ionic-native/core": "^3.14.0",
    "ionic-native/geolocation": "^4.2.1",
    "ionic-native/google-maps": "^4.3.0",
    "ionic-native/splash-screen": "3.12.1",
    "ionic-native/status-bar": "3.12.1",
    "ionic/storage": "2.0.1",
    "ngx-translate/core": "6.0.1",
    "ngx-translate/http-loader": "0.0.3",
    "chart.js": "^2.7.0",
    "cordova-android": "6.3.0",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-geolocation": "^2.4.3",
    "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "ionic": "^3.13.0",
    "ionic-angular": "3.6.1",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "tslint-config-airbnb": "^5.3.0",
    "zone.js": "0.8.12"

**Comment by wf9a5m75** [comment]
You didn't install the latest version.

`ionic-native/core` has to be v4.3.1
`ionic-native/google-maps` also has to be v4.3.1
`cordova-plugin-googlemaps` has to be `2.1.0-beta-20171005-1430`

**Comment by RanmalN** [comment]
i installed ionic-native/core using npm install @ionic-native/core --save but still installing 3.14

**Comment by wf9a5m75** [comment]
`npm cache clean`

PLEASE (x30) do your best as much as possible. I'm not your teacher.
At least you should consider why I can not install v4.3.1.

**Comment by RanmalN** [comment]
i have updated 

ionic-native/core  to  v4.3.1
ionic-native/google-maps   to be v4.3.1
but couldn't get  Cordova-plugin-google maps to 2.1.0-beta-20171005-1430 

i have tried 

 cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps \
    --variable API_KEY_FOR_ANDROID="..." \
    --variable API_KEY_FOR_IOS="..."

and remove it then npm cache clean then re install it but didn't update

**Comment by wf9a5m75** [comment]
https://60devs.com/npm-install-specific-version.html

**Comment by RanmalN** [comment]
this works when i create a demo project and reun but when i run on the original project it doesnt work

Dependancies: 
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/compiler-cli": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@ionic-native/core": "^4.3.1",
    "@ionic-native/geolocation": "^4.3.1",
    "@ionic-native/google-maps": "^4.3.1",
    "@ionic-native/splash-screen": "^4.3.1",
    "@ionic-native/status-bar": "^4.3.1",
    "@ionic/storage": "2.0.1",
    "@ngx-translate/core": "6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "chart.js": "^2.7.0",
    "cordova-android": "6.3.0",
    "cordova-plugin-device": "^1.1.6",
    "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.3",
    "cordova-plugin-whitelist": "^1.3.2",
    "ionic": "^3.13.0",
    "ionic-angular": "3.7.1",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "rxjs": "5.4.3",
    "sw-toolbox": "3.6.0",
    "tslint-config-airbnb": "^5.3.0",
    "zone.js": "0.8.18"

cordova plugin list 

cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.1.0-beta-20171005-1430 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by wf9a5m75** [comment]
It is not my problem. It's your problem

**Comment by RanmalN** [comment]
bug is fixed when

this.map = this.googleMaps.create(this.mapElement, mapOptions);  is used to create a map

@wf9a5m75 thanks for helping out
