### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined 

### ISSUE THREAD

**Issue by RanmalN** [mapsplugin/cordova-plugin-googlemaps#1812]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `ionic-native/google-maps`, please show me the package.json**
"dependencies": {
        "angular/common": "4.1.3",
        "angular/compiler": "4.1.3",
        "angular/compiler-cli": "4.1.3",
        "angular/core": "4.1.3",
        "angular/forms": "4.1.3",
        "angular/http": "4.1.3",
        "angular/platform-browser": "4.1.3",
        "angular/platform-browser-dynamic": "4.1.3",
        "ionic-native/core": "3.12.1",
        "ionic-native/geolocation": "^4.2.1",
        "ionic-native/google-maps": "^4.3.0",
        "ionic-native/splash-screen": "3.12.1",
        "ionic-native/status-bar": "3.12.1",
        "ionic/storage": "2.0.1",
        "ngx-translate/core": "6.0.1",
        "ngx-translate/http-loader": "0.0.3",
        "chart.js": "^2.7.0",
        "cordova-android": "^6.3.0",
        "cordova-plugin-compat": "^1.2.0",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-geolocation": "^2.4.3",
        "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.6.1",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "tslint-config-airbnb": "^5.3.0",
        "zone.js": "0.8.12"
    },

**Current behavior:**
Gets an error but the marker is marked;

Uncaught TypeError: Cannot read property 'push' of undefined

**Related code, data or error log (please format your code or data):**

```
this.map.addMarker({
            title: 'Current Location',
            icon: 'red',
            animation: 'DROP',
            position: {
              lat: this.location.lat,
              lng: this.location.lng,
            },
            draggable: true,
          }).then((marker) => {
            marker.addEventListener(GoogleMapsEvent.INFO_CLICK).subscribe(() => {
              console.log('ffv');
            });
          });
```

**Comment by wf9a5m75** [comment]
Please share your project files on github. Otherwise, I can not help you because too less information

**Comment by Chibuzor06** [comment]
I am also experiencing this issue.
It occurs on adding marker to the map. Without the add marker code, the map load fine

<h4> The ts file </h4>
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, Platform } from 'ionic-angular';
import {
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  GoogleMapOptions,
  CameraPosition,
  MarkerOptions,
  Marker,
  LatLng
 } from '@ionic-native/google-maps';


@IonicPage()
@Component({
  selector: 'page-track-vehicle',
  templateUrl: 'track-vehicle.html',
})
export class TrackVehiclePage {
  map: GoogleMap;
  mapElement: HTMLElement;
  constructor(private googleMaps: GoogleMaps, public platform: Platform) {
    this.platform.ready().then( () => {
      // this.loadMap();
    });
   }


  ionViewDidLoad() {
    this.loadMap();
  }

  ionViewDidEnter() {
    // this.loadMap();
  }
  loadMap() {
    this.mapElement = document.getElementById('map');

    let mapOptions: GoogleMapOptions = {
      camera: {
        target: {
          lat: 43.0741904,
          lng: -89.3809802
        },
        zoom: 18,
        tilt: 30
      }
    };

    // this.map = this.googleMaps.create(this.mapElement, mapOptions);
    this.map = new GoogleMap(this.mapElement, mapOptions);

    // Wait the MAP_READY before using any methods.
    this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => {
        console.log('Map is ready!');

        // let coordinates: LatLng = new LatLng(33.6396965, -84.4304574);

        // let position = {
        //   target: coordinates,
        //   zoom: 17
        // };
        // this.map.animateCamera(position);

        // let markerOptions: MarkerOptions = {
        //   position: coordinates,
        //   title: 'Our first POI'
        // };

        // const marker = this.map.addMarker(markerOptions)
        //   .then((marker: Marker) => {
        //     marker.showInfoWindow();
        // });
        // console.log('marker ', marker);
        // console.log('map ', this.map);
        // Now you can use all methods safely.
        // this.map.addMarker({
        //     title: 'Ionic',
        //     icon: 'blue',
        //     animation: 'DROP',
        //     position: {
        //       lat: 43.0741904,
        //       lng: -89.3809802
        //     }
        //   })
        //   .then(marker => {
        //     marker.on(GoogleMapsEvent.MARKER_CLICK)
        //       .subscribe(() => {
        //         alert('clicked');
        //       });
        //   });

      });
  }

}
<h4> package.json </h4>
{
    "dependencies":  {
        "angular/common": "^4.4.3",
        "angular/compiler": "^4.4.3",
        "angular/compiler-cli": "^4.4.3",
        "angular/core": "^4.4.3",
        "angular/forms": "^4.4.3",
        "angular/http": "^4.4.3",
        "angular/platform-browser": "^4.4.3",
        "angular/platform-browser-dynamic": "^4.4.3",
        "ionic-native/core": "3.12.1",
        "ionic-native/file": "^4.2.1",
        "ionic-native/google-maps": "^4.3.1",
        "ionic-native/onesignal": "^4.3.0",
        "ionic-native/splash-screen": "3.12.1",
        "ionic-native/status-bar": "3.12.1",
        "ionic-native/vibration": "^4.3.1",
        "ionic/storage": "^2.0.1",
        "cordova-android": "^6.2.3",
        "cordova-plugin-compat": "^1.0.0",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-file": "^4.3.3",
        "cordova-plugin-googlemaps": "^2.0.11",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-vibration": "^2.1.5",
        "cordova-plugin-whitelist": "^1.3.1",
        "cordova-sqlite-storage": "^2.0.4",
        "ionic-angular": "^3.7.0",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "onesignal-cordova-plugin": "^2.2.1",
        "rxjs": "^5.4.3",
        "sw-toolbox": "3.6.0",
        "zone.js": "^0.8.17"
    },
    "devDependencies": {
        "@ionic/app-scripts": "^3.0.0",
        "@types/googlemaps": "^3.29.0",
        "typescript": "2.3.4"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-file": {},
            "cordova-sqlite-storage": {},
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "onesignal-cordova-plugin": {},
            "cordova-plugin-vibration": {},
            "cordova-plugin-googlemaps": {
                "API_KEY_FOR_ANDROID": "key removed for security",
                "API_KEY_FOR_IOS": ""
            }
        },
        "platforms": [
            "android"
        ]
    }
}

<b>scss file</b> 
ion-app._gmaps_cdv_ .nav-decor{
  background-color: transparent !important;
}

page-track-vehicle {
  #map {
    height: 100%;
  }
}

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by Chibuzor06** [comment]
Please can you specify what other files you need? I can't share the whole project on a public repository.
What I posted earlier is the only code that uses the maps plugin. Is it insufficient to diagnose the problem?

**Comment by wf9a5m75** [comment]
I'm so busy person, I have no enough time to reproduce your snippet code (such as copy & paste, install related plugins, etc).
And I'm not ionic user.

Please create a demo project, then share it on github.
I'm not interested in your code at all. I only need to reproduce your problem in my side.

**Comment by wf9a5m75** [comment]
@Chibuzor06 At least, you need to use `ionic-native/core` latest version.
`ionic-native/core` is too old.

**Comment by RanmalN** [comment]
Git Repo: https://github.com/RanmalN/Googlemapssample

updated the ionic-native/core but problem is still there

**Comment by wf9a5m75** [comment]
You didn't update the dependency module at all.

**Comment by RanmalN** [comment]
i have updated ionic-native/core to 4.3.1 but still gets the error

**Comment by wf9a5m75** [comment]
Are you kidding me? The home.ts in your repo is just this.
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  constructor(public navCtrl: NavController) {
  }
}
```

Even you didn't install the plugin.
```
{
  "name": "googleMapsDemo",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/compiler-cli": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@ionic-native/core": "4.3.0",
    "@ionic-native/splash-screen": "4.3.0",
    "@ionic-native/status-bar": "4.3.0",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.7.1",
    "ionicons": "3.0.0",
    "rxjs": "5.4.3",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.0.0",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project"
}
```

**Comment by RanmalN** [comment]
This works in the sample project but doesn't work on the main project.So sorry github wasnt updated with the project

**Comment by uiktiomasfeliz** [comment]
In my case the error shows when i use the old way to create map:
` this.map = new GoogleMap(this.mapElement, mapOptions);`

When i create the map using `this.map = this.googleMaps.create(this.mapElement, mapOptions);` , the error disapear but i can't see map, i verify api key's and all stufs...

**Comment by RanmalN** [comment]
The error got fixed when this.map = this.googleMaps.create(this.mapElement, mapOptions); is used insted of this.map = new GoogleMap(this.mapElement, mapOptions); 

Thanks @uiktiomasfeliz @wf9a5m75 for the help

**Comment by uiktiomasfeliz** [comment]
@RanmalN you don't see white screen on div map?

**Comment by RanmalN** [comment]
nope, the map got loaded.you may be having an error.use chrome inspect to find errors

**Comment by uiktiomasfeliz** [comment]
I already did, everything seems fine, the map is not seen, but the events i can run them, I think it is a problem related to styles.

**Comment by RanmalN** [comment]
styles :- 

#map {
    height: 100%;
  }
  
  ion-app._gmaps_cdv_ .nav-decor {
    background-color: transparent !important;
  }

**Comment by uiktiomasfeliz** [comment]
already have that lines, i was using ` "cordova-plugin-googlemaps": "^1.4.1"` and everything was going good, after update to 2.x, the map doesn't show anymore...

**Comment by ipleh** [comment]
Hi there,
problem you trying to solve does not have roots in cordova-plugin-googlemaps module, but in implementation of typescript types in ionic native d.ts file. Please, try change your `"ionic-native/google-maps": "^4.3.1",` in your package.json file in your project to `"ionic-native/google-maps": "4.2.0"`. 
Something went wrong in [https://github.com/ionic-team/ionic-native/blob/master/CHANGELOG.md#430-2017-09-27](url)
