### ISSUE TITLE
Ionic app crashes when adding KML layer containing link/href returning 404 http error

### ISSUE THREAD

**Issue by ryaa** [mapsplugin/cordova-plugin-googlemaps#1813]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
com.megster.cordova.FileChooser 0.0.0 "File Chooser"
cordova-android-support-gradle-release 1.1.2 "cordova-android-support-gradle-release"
cordova-google-api-version 0.0.1 "cordova-google-api-version"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crosswalk-webview 2.2.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-opener2 2.0.4 "File Opener2"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-media-capture 1.4.1 "Capture"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.1 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.3.3 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.4 "PushPlugin"

**If you use `@ionic-native/google-maps`, please show me the package.json**
{
    "name": "boss811.mobile",
    "author": "Alex Ryltsov",
    "homepage": "",
    "private": true,
    "version": "2.0.17",
    "scripts": {
        "dev": "bnr dev",
        "build": "bnr build",
        "build-dev": "bnr build-dev",
        "test": "bnr test",
        "test:watch": "bnr test-watch",
        "pree2e": "cd www && python -m SimpleHTTPServer 8100 >> ../python_serve.log 2>&1 &",
        "e2e": "protractor",
        "pree2e:interactive": "npm run pree2e",
        "e2e:interactive": "protractor --elementExplorer",
        "ionic:serve": "ionic-app-scripts serve",
        "ionic:build": "ionic-app-scripts build",
        "ios:dev": "bnr ios:dev",
        "ios:release": "bnr ios:release",
        "ios:release:ci": "bnr ios:release:ci",
        "android:dev": "bnr android:dev",
        "android:release": "bnr android:release",
        "commit": "git-cz",
        "docs": "typedoc --options typedoc.json --exclude '**/*+(e2e|spec|index).ts' ./src/",
        "release": "standard-version --no-verify",
        "push": "git push --follow-tags origin master",
        "lint": "tslint \"src/**/*.ts\" --exclude=src/**/*.d.ts",
        "scss-lint": "scss-lint",
        "outdated": "npm outdated --depth 0",
        "post-install": "webdriver-manager update"
    },
    "betterScripts": {
        "dev": {
            "command": "ionic serve",
            "env": {
                "NODE_ENV": "development",
                "PLATFORM": "web"
            }
        },
        "build": {
            "command": "ionic-app-scripts build --prod",
            "env": {
                "NODE_ENV": "production"
            }
        },
        "build-dev": {
            "command": "ionic-app-scripts build --dev",
            "env": {
                "NODE_ENV": "development"
            }
        },
        "test": {
            "command": "karma start",
            "env": {
                "NODE_ENV": "test"
            }
        },
        "test-watch": {
            "command": "karma start --auto-watch --no-single-run",
            "env": {
                "NODE_ENV": "test",
                "NO_COVERAGE": true
            }
        },
        "ios:dev": {
            "command": "ionic run ios --livereload",
            "env": {
                "NODE_ENV": "development",
                "PLATFORM": "ios"
            }
        },
        "ios:release": {
            "command": "ionic build ios --prod",
            "env": {
                "NODE_ENV": "production",
                "PLATFORM": "ios"
            }
        },
        "ios:release:ci": {
            "command": "npm run build",
            "env": {
                "NODE_ENV": "production",
                "PLATFORM": "ios"
            }
        },
        "android:dev": {
            "command": "ionic run android --livereload",
            "env": {
                "NODE_ENV": "development",
                "PLATFORM": "android"
            }
        },
        "android:release": {
            "command": "ionic build android --prod",
            "env": {
                "NODE_ENV": "production",
                "PLATFORM": "android"
            }
        }
    },
    "dependencies": {
        "@angular/common": "2.4.8",
        "@angular/compiler": "2.4.8",
        "@angular/compiler-cli": "2.4.8",
        "@angular/core": "2.4.8",
        "@angular/forms": "2.4.8",
        "@angular/http": "2.4.8",
        "@angular/platform-browser": "2.4.8",
        "@angular/platform-browser-dynamic": "2.4.8",
        "@angular/platform-server": "2.4.8",
        "@ionic-native/core": "^4.3.1",
        "@ionic-native/geolocation": "^3.12.1",
        "@ionic-native/google-maps": "^4.3.1",
        "@ionic-native/screen-orientation": "^3.5.0",
        "@ionic/cloud-angular": "^0.12.0",
        "@ionic/storage": "2.0.0",
        "android-versions": "^1.2.1",
        "angular2-moment": "^1.6.0",
        "cordova-android": "~6.0.0",
        "cordova-ios": "~4.3.1",
        "cordova-plugin-camera": "~2.3.1",
        "cordova-plugin-console": "1.0.5",
        "cordova-plugin-crosswalk-webview": "~2.2.0",
        "cordova-plugin-device": "1.1.4",
        "cordova-plugin-file": "~4.3.1",
        "cordova-plugin-file-opener2": "~2.0.3",
        "cordova-plugin-file-transfer": "~1.6.1",
        "cordova-plugin-filepath": "~1.0.2",
        "cordova-plugin-media-capture": "~1.4.1",
        "cordova-plugin-network-information": "~1.3.1",
        "cordova-plugin-screen-orientation": "~1.4.2",
        "cordova-plugin-splashscreen": "~4.0.1",
        "cordova-plugin-statusbar": "2.2.1",
        "cordova-plugin-whitelist": "1.3.1",
        "cordova-sqlite-storage": "~2.0.1",
        "cordova.plugins.diagnostic": "~3.3.3",
        "esri-leaflet": "2.0.8",
        "font-awesome": "^4.7.0",
        "intl": "^1.2.5",
        "ionic-angular": "2.2.0",
        "ionic-native": "2.9.0",
        "ionic-plugin-deeplinks": "^1.0.15",
        "ionic-plugin-keyboard": "~2.2.1",
        "ionicons": "3.0.0",
        "jquery": "^3.1.1",
        "jszip": "^3.1.3",
        "leaflet": "1.0.3",
        "leaflet-plugins": "3.0.0",
        "material-design-iconic-font": "^2.2.0",
        "mime": "^1.3.4",
        "moment": "^2.17.1",
        "moment-timezone": "^0.5.11",
        "ng2-translate": "^5.0.0",
        "phonegap-plugin-push": "^1.10.4",
        "rxjs": "5.0.1",
        "sw-toolbox": "3.4.0",
        "zone.js": "0.7.2"
    },
    "devDependencies": {
        "@ionic/app-scripts": "1.1.4",
        "@types/jasmine": "2.5.38",
        "@types/jasmine-jquery": "1.5.28",
        "@types/jquery": "^2.0.41",
        "@types/leaflet": "1.0.59",
        "@types/lodash": "ts2.0",
        "@types/mime": "0.0.29",
        "@types/moment-timezone": "^0.2.34",
        "@types/node": "^6.0.52",
        "angular2-template-loader": "^0.6.0",
        "awesome-typescript-loader": "^2.2.1",
        "better-npm-run": "0.0.13",
        "codelyzer": "2.0.0-beta.1",
        "commitizen": "^2.9.2",
        "css-loader": "^0.26.1",
        "cz-conventional-changelog": "^1.2.0",
        "html-webpack-externals-plugin": "^2.2.1",
        "html-webpack-plugin": "^2.28.0",
        "husky": "^0.13.1",
        "istanbul-instrumenter-loader": "1.2.0",
        "jasmine-core": "^2.5.2",
        "jasmine-spec-reporter": "^2.7.0",
        "json-loader": "^0.5.4",
        "karma": "^1.2.1",
        "karma-chrome-launcher": "^2.0.0",
        "karma-coverage": "^1.1.1",
        "karma-jasmine": "^1.1.0",
        "karma-jasmine-jquery": "^0.1.1",
        "karma-mocha-reporter": "^2.2.1",
        "karma-remap-coverage": "0.1.2",
        "karma-sourcemap-loader": "^0.3.7",
        "karma-webpack": "1.8.0",
        "lodash": "^4.17.4",
        "phantomjs-prebuilt": "^2.1.14",
        "protractor": "^4.0.14",
        "protractor-jasmine2-screenshot-reporter": "^0.3.2",
        "raw-loader": "0.5.1",
        "source-map-loader": "^0.1.5",
        "standard-version": "^4.0.0",
        "to-string-loader": "^1.1.4",
        "ts-helpers": "^1.1.1",
        "ts-node": "^1.7.2",
        "tslint": "4.0.2",
        "tslint-loader": "^3.3.0",
        "typedoc": "^0.5.1",
        "typescript": "2.0.9",
        "validate-commit-msg": "^2.8.0",
        "webpack": "2.1.0-beta.27",
        "xml2js": "^0.4.17"
    },
    "cordovaPlugins": [
        "cordova-plugin-console",
        "cordova-plugin-splashscreen",
        "cordova-plugin-whitelist",
        "ionic-plugin-keyboard",
        "cordova-plugin-device",
        "cordova-plugin-statusbar"
    ],
    "cordovaPlatforms": [
        "ios",
        {
            "platform": "ios",
            "version": "",
            "locator": "ios"
        }
    ],
    "config": {
        "ionic_bundler": "webpack",
        "ionic_source_map_type": "#inline-source-map",
        "ionic_generate_source_map": true,
        "commitizen": {
            "path": "./node_modules/cz-conventional-changelog"
        },
        "ionic_webpack": "./config/webpack.config.js",
        "ionic_copy": "./config/copy.config.js",
        "ionic_sass": "./config/sass.config.js"
    },
    "description": "BOSS811 is a cloud-based hosted solution offered by BOSS Solutions to provide an environment where utility provider management and locate field crews can stay on top of service requests coming from the state's 811 agency.",
    "cordova": {
        "plugins": {
            "phonegap-plugin-push": {
                "SENDER_ID": "XXXXXXX"
            },
            "com.megster.cordova.FileChooser": {},
            "cordova-plugin-camera": {
                "CAMERA_USAGE_DESCRIPTION": " ",
                "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
            },
            "cordova-plugin-console": {},
            "cordova-plugin-crosswalk-webview": {
                "XWALK_VERSION": "22+",
                "XWALK_LITEVERSION": "xwalk_core_library_canary:17+",
                "XWALK_COMMANDLINE": "--disable-pull-to-refresh-effect",
                "XWALK_MODE": "embedded",
                "XWALK_MULTIPLEAPK": "true"
            },
            "cordova-plugin-device": {},
            "cordova-plugin-file": {},
            "cordova-plugin-file-opener2": {},
            "cordova-plugin-file-transfer": {},
            "cordova-plugin-filepath": {},
            "cordova-plugin-media-capture": {
                "CAMERA_USAGE_DESCRIPTION": " ",
                "MICROPHONE_USAGE_DESCRIPTION": " ",
                "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
            },
            "cordova-plugin-network-information": {},
            "cordova-plugin-screen-orientation": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "cordova-sqlite-storage": {},
            "cordova.plugins.diagnostic": {},
            "ionic-plugin-keyboard": {},
            "ionic-plugin-deeplinks": {
                "URL_SCHEME": "boss811",
                "DEEPLINK_SCHEME": "https",
                "DEEPLINK_HOST": "boss811.com",
                "ANDROID_PATH_PREFIX": "/",
                "ANDROID_2_PATH_PREFIX": "/",
                "ANDROID_3_PATH_PREFIX": "/",
                "ANDROID_4_PATH_PREFIX": "/",
                "ANDROID_5_PATH_PREFIX": "/",
                "DEEPLINK_2_SCHEME": " ",
                "DEEPLINK_2_HOST": " ",
                "DEEPLINK_3_SCHEME": " ",
                "DEEPLINK_3_HOST": " ",
                "DEEPLINK_4_SCHEME": " ",
                "DEEPLINK_4_HOST": " ",
                "DEEPLINK_5_SCHEME": " ",
                "DEEPLINK_5_HOST": " "
            }
        },
        "platforms": [
            "android",
            "ios"
        ]
    }
}

**Current behavior:**

The app crashes when adding KML layer with invalid/incorrect href URL for Icon element. For example
```
						<Style id="sn_track10">
							<IconStyle>
								<scale>1.2</scale>
								<Icon>
									<href>http://maps.google.com/mapfiles/kml/shapes/track.png</href>
								</Icon>
								<hotSpot x="32" y="1" xunits="pixels" yunits="pixels"/>
							</IconStyle>
							<LabelStyle>
								<scale>0</scale>
							</LabelStyle>
							<BalloonStyle>
								<text><![CDATA[<b>$[name]</b><br />$[address]<br />$[description]<br/><br/>$[geDirections]]]></text>
							</BalloonStyle>
						</Style>
```

Note that http://maps.google.com/mapfiles/kml/shapes/track.png returns http 404

**Expected behavior:**

The app should not crash. It can report the problem with the URL to console or smth but not keep running

**Steps to reproduce:**

Add KML layer using the link to the KML file below

```
map.addKmlOverlay({
      url: 'https://dl.dropboxusercontent.com/s/ckul2o1ck0sdv3w/Jefferson%20Parish%201-16-2017.kml?dl=0',
      preserveViewport: false,
      animation: true
    }
```

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```
Below is the logcat output from the android device running the ionic application
 
                                                                    --------- beginning of crash
10-12 09:10:37.643 11627-11627/com.mobile.boss811 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.mobile.boss811, PID: 11627
                                                                    java.lang.IllegalStateException: no included points
                                                                        at com.google.android.gms.common.internal.zzbp.zza(Unknown Source)
                                                                        at com.google.android.gms.maps.model.LatLngBounds$Builder.build(Unknown Source)
                                                                        at plugin.google.maps.PluginPolyline$1.run(PluginPolyline.java:80)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-12 09:10:37.645 774-1511/? W/ActivityManager:   Force finishing activity com.mobile.boss811/.MainActivity
10-12 09:10:37.700 774-10184/? I/OpenGLRenderer: Initialized EGL, version 1.4
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err: java.lang.NumberFormatException: Invalid int: "2.5"
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at java.lang.Integer.invalidInt(Integer.java:138)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at java.lang.Integer.parse(Integer.java:410)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at java.lang.Integer.parseInt(Integer.java:367)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at java.lang.Integer.parseInt(Integer.java:334)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncKmlParser.parsePlaceMark(AsyncKmlParser.java:347)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncKmlParser.access$000(AsyncKmlParser.java:37)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncKmlParser$1.call(AsyncKmlParser.java:204)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncKmlParser$1.call(AsyncKmlParser.java:201)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-12 09:10:37.732 11627-12317/com.mobile.boss811 W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err: java.lang.NumberFormatException: Invalid int: "2.5"
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at java.lang.Integer.invalidInt(Integer.java:138)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at java.lang.Integer.parse(Integer.java:410)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at java.lang.Integer.parseInt(Integer.java:367)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at java.lang.Integer.parseInt(Integer.java:334)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncKmlParser.parsePlaceMark(AsyncKmlParser.java:347)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncKmlParser.access$000(AsyncKmlParser.java:37)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncKmlParser$1.call(AsyncKmlParser.java:204)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncKmlParser$1.call(AsyncKmlParser.java:201)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-12 09:10:37.735 11627-12317/com.mobile.boss811 W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-12 09:10:37.748 774-783/? I/art: Background partial concurrent mark sweep GC freed 9714(546KB) AllocSpace objects, 6(120KB) LOS objects, 33% free, 27MB/41MB, paused 5.989ms total 90.853ms
10-12 09:10:38.161 774-790/? W/ActivityManager: Activity pause timeout for ActivityRecord{1589b2c u0 com.mobile.boss811/.MainActivity t10 f}
10-12 09:10:38.494 774-790/? I/ActivityManager: Killing 3733:com.google.android.youtube/u0a81 (adj 15): empty #17
10-12 09:10:38.541 774-1234/? D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=9, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@e1bbbf1)
10-12 09:10:38.541 774-883/? D/ConnectivityService: releasing NetworkRequest NetworkRequest [ id=9, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
10-12 09:10:38.542 774-883/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=9, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
10-12 09:10:38.571 774-2960/? D/ActivityManager: cleanUpApplicationRecord -- 3733
10-12 09:10:38.762 1504-1709/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-12 09:10:38.913 11627-11670/com.mobile.boss811 W/System.err: java.io.FileNotFoundException: http://maps.google.com/mapfiles/kml/shapes/track.png
10-12 09:10:38.913 11627-11670/com.mobile.boss811 W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
10-12 09:10:38.913 11627-11670/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:303)
10-12 09:10:38.913 11627-11670/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:31)
10-12 09:10:38.913 11627-11670/com.mobile.boss811 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-12 09:10:38.913 11627-11670/com.mobile.boss811 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-12 09:10:38.913 11627-11670/com.mobile.boss811 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-12 09:10:38.913 11627-11670/com.mobile.boss811 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-12 09:10:38.913 11627-11670/com.mobile.boss811 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-12 09:10:38.913 11627-11670/com.mobile.boss811 W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-12 09:10:39.160 11627-11670/com.mobile.boss811 W/System.err: java.io.FileNotFoundException: http://maps.google.com/mapfiles/kml/shapes/track.png
10-12 09:10:39.161 11627-11670/com.mobile.boss811 W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
10-12 09:10:39.161 11627-11670/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:303)
10-12 09:10:39.161 11627-11670/com.mobile.boss811 W/System.err:     at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:31)
10-12 09:10:39.161 11627-11670/com.mobile.boss811 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-12 09:10:39.161 11627-11670/com.mobile.boss811 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-12 09:10:39.162 11627-11670/com.mobile.boss811 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-12 09:10:39.162 11627-11670/com.mobile.boss811 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-12 09:10:39.162 11627-11670/com.mobile.boss811 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-12 09:10:39.162 11627-11670/com.mobile.boss811 W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by wf9a5m75** [comment]
KML layer is not ready yet in v2.
