### ISSUE TITLE
@ionic-native/google-maps: Type 'any' is not a constructor function type

### ISSUE THREAD

**Issue by gonadn** [mapsplugin/cordova-plugin-googlemaps#1815]
Hi

Iam using the ionic version of google maps plugin, and iam getting an error when i RUN ionic Build, se pic:
![error](https://user-images.githubusercontent.com/3224441/31513865-ebc3c3aa-af8f-11e7-9d92-155e6b43d07d.PNG)

typescript: .../DrivStoffAppn/DrivStoffAppen2/node_modules/@ionic-native/google-maps/index.d.ts, line: 480 

ionic -v 3.13.0
cordova -v 6.5.0
Android target: android-26

How can i fix this?

**Comment by wf9a5m75** [comment]
Could you tell me what version of the `@ionic-native/core` and `@ionic-native/google-maps`?

**Comment by gonadn** [comment]
looks like problem was that @ionic-native/core was not installed in my solution. by npm install @ionic-native/core the error was gone, but now i have another issue when i build my project...
![error2](https://user-images.githubusercontent.com/3224441/31534169-1148f742-aff6-11e7-953c-d937bdc27b84.PNG)

**Comment by gonadn** [comment]
The issue is resolved by first installing `npm install @ionic-native/core` and for the second error i had to remove android platform and add android version 6.2.3...

**Comment by wf9a5m75** [comment]
If you still need my help, please share your project files on github. Otherwise, please close this thread.

**Comment by wf9a5m75** [comment]
There is no update for a while, I close this thread.
