### ISSUE TITLE
HtmlInfoWindow to follow marker on position change

### ISSUE THREAD

**Issue by stormwin** [mapsplugin/cordova-plugin-googlemaps#1816]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[x] **iOS**

**Current behavior:**
Is there any way for HtmlInfoWindow to follow marker when marker position change?
HtmlInfoWindow position is only updated when map is changed.

i am using latest stable version.

**Comment by wf9a5m75** [comment]
Please create a demo project in order to reproduce your issue.

**Comment by wf9a5m75** [comment]
It seems the plugin works fine (using the multiple_maps branch, and the [PR](https://github.com/ionic-team/ionic-native/pull/2035))

```TypeScript
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import {
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  HtmlInfoWindow,
  Marker,
  ILatLng
} from '@ionic-native/google-maps';

@IonicPage()
@Component({
  selector: 'page-new-html-info-window',
  templateUrl: 'new-html-info-window.html',
})
export class NewHtmlInfoWindowPage {
  map: GoogleMap;

  constructor(
    public navCtrl: NavController,
    public navParams: NavParams,
    private googleMaps: GoogleMaps) {
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad NewHtmlInfoWindowPage');
    this.loadMap();
  }

  loadMap() {
    this.map = this.googleMaps.create('map_canvas');
    this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
      let htmlInfoWindow = new HtmlInfoWindow();

      let html: string = [
        'This is <b>Html</b> InfoWindow',
        '<br>',
        '<button onclick="javascript:alert(\'clicked!\');">click here</button>',
      ].join("");
      htmlInfoWindow.setContent(html);

      this.map.addMarker({
        position: {lat: 0, lng: 0},
        draggable: true
      }).then((marker: Marker) => {

        marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
          htmlInfoWindow.open(marker);
        });
        marker.trigger(GoogleMapsEvent.MARKER_CLICK);

      });
    });
  }
}
```
![1816](https://user-images.githubusercontent.com/167831/31528025-e4811de0-af85-11e7-985a-df0f09200eb3.gif)

**Comment by stormwin** [comment]
Maybe i described my problem wrongly.

I do not touch or move the map.
Only clicked on marker once (to activate htmlinfowindow)
Marker is object that is in constant motion for example, and update the position every X seconds.
All i want is when marker change position, htmlinfowindow to track marker, 
(see gif below)

This is very basic pure cordova demo that reproduce my problem.
https://github.com/stormwin/maptest

![ezgif-5-fd8eed6a4e](https://user-images.githubusercontent.com/1946036/31570808-98163676-b088-11e7-832f-8518eea049f5.gif)

**Comment by wf9a5m75** [comment]
Ah, I see. HtmlInfoWindow does not follow for that case. You need to execute `htmlInfoWindow.open(marker)` again when the marker position is moved, or use the regular infoWindow

**Comment by stormwin** [comment]
Thanks, it work with ```htmlInfoWindow.open(marker)```
