### ISSUE TITLE
Ionic plugin: Property 'MAP_READY' does not exist on type '{ [eventName: string]: string; }'

### ISSUE THREAD

**Issue by gonadn** [mapsplugin/cordova-plugin-googlemaps#1817]
Error: Property 'MAP_READY' does not exist on type '{ [eventName: string]: string; }'

Getting this error when map is loaded:
![err2](https://user-images.githubusercontent.com/3224441/31539184-2946f7c4-b008-11e7-91f5-86db4e45e3b2.PNG)

line 51: `console.log(GoogleMapsEvent.MAP_READY);`

map is loaded fine, but this event is not firing up....

**Comment by wf9a5m75** [comment]
Please share your project files on github. Otherwise, I don't support this.

**Comment by gonadn** [comment]
Iam sharing my prosject thrue google drive [link](https://drive.google.com/file/d/0B8sGIuAXHtUKMDlUVlBrbHN1eVU/view?usp=sharing) 

Vs2017 and Git extention is not wrking as expected....Sorry...

I hope you can download the project...

**Comment by gonadn** [comment]
any clue why iam getting this error?

**Comment by wf9a5m75** [comment]
I have a question. What is the platform of this error?
Because this plugin works **only** on Android and iOS.

**Comment by wf9a5m75** [comment]
Um, I checked your repo, but I could not figure out the reason.

**Comment by gonadn** [comment]
strange, was you able to reproduce the error ?
Or did you build and see the same error result?

**Comment by wf9a5m75** [comment]
I tried to rebuild your project, and I achieved to build it without error.
What I did is

```
$> cordova platform rm android

$> cordova platform add android
```

That's it. I didn't change any code of yours.

So this is not plugin's problem.

**Comment by gonadn** [comment]
Oki, i did as you described above, but still iam getting same error mesage on "Map_READY and MAP_CLICK events. 

which cordova version are you running, and android version?

**Comment by wf9a5m75** [comment]
```
$ cordova -v
7.0.1
```

**Comment by wf9a5m75** [comment]
@gonadn The ionic team fixed the problem of the `@ionic-native/google-maps` wrapper plugin.
It was the problem of TypeScript for some reason.

Please reinstall the `@ionic-native/google-maps` v4.3.2.
The problem should be gone.

```
$> npm uninstall @ionic-native/google-maps

$> npm clear cache

$> npm install @ionic-native/google-maps@4.3.2
```
