### ISSUE TITLE
map.addEventListener(plugin.google.maps.event.MAP_READY, function(){}) doesn't work in the success callback of http request

### ISSUE THREAD

**Issue by kanalasumant** [mapsplugin/cordova-plugin-googlemaps#1818]
**Mine is an angular based cordova app where I initialize the map view and wait for it in a controller. It works fine, when I do this:**

```js
app.controller('eventDataCTRL', ['$scope', '$location', 'eventFactory', '$http', function($scope, $location, eventFactory, $http){
  $scope.eventFactory = eventFactory;
  var div = document.getElementById("map_canvas");
  // Initialize the map view
  map = plugin.google.maps.Map.getMap(div);
  // Wait until the map is ready status.
  map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady([42.3601, -71.0589]));
  $http({
    method: 'POST',
    url: "https://xyz.com/",
    headers: {
      'Content-Type': 'application/json'
    },
    data: JSON.stringify({uri:eventFactory.event_url[0]})
  }).then(function successCallback(response) {

    }, function errorCallback(response) {
  });
```

**But what I want is send coordinates which I get from this endpoint, or more specifically for any location (lat, long) I want. so this doesn't work:**

```js
app.controller('eventDataCTRL', ['$scope', '$location', 'eventFactory', '$http', function($scope, $location, eventFactory, $http){
  $scope.eventFactory = eventFactory;
  var div = document.getElementById("map_canvas");
  // Initialize the map view
  map = plugin.google.maps.Map.getMap(div);
  // Wait until the map is ready status.
 
  $http({
    method: 'POST',
    url: "https://xyz.com/",
    headers: {
      'Content-Type': 'application/json'
    },
    data: JSON.stringify({uri:eventFactory.event_url[0]})
  }).then(function successCallback(response) {
     map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady([42.3601, -71.0589]));
    }, function errorCallback(response) {
  });
```

**For the sake of privacy I replaced the http request url with a random url. 
Any help would be greatly appreciated.**

**Comment by wf9a5m75** [comment]
Unfortunately, without sharing your code with me, I can not help you at all.
Please share your project files on github.

**Comment by kanalasumant** [comment]
https://github.com/kanalasumant/test_events

Kindly look into the js/main.js and also read my comments above. Thank you!

**Comment by wf9a5m75** [comment]
Could you tell me how I can build your project?

**Comment by kanalasumant** [comment]
Hey thanks again for helping on this. this is a new repository where the full cordova repo is available at https://github.com/kanalasumant/erwerwer to be run using **cordova run**. I personally haven't setup an emulator and it's tough to set it up properly on my machine with the documentation in cordova not being clear, so I generate an apk and run it on my phone. If something goes wrong, I can send you my apk file to your email address. Thank you.

**Comment by wf9a5m75** [comment]
Thank you for waiting. I reviewed your code, and this code is strange.

```js
  map = plugin.google.maps.Map.getMap(div);
  // Wait until the map is ready status.
  $http({
    method: 'POST',
    url: "https://fair-events.herokuapp.com/api/parseLatAndLongWeather/",
    headers: {
      'Content-Type': 'application/json'
    },
    data: JSON.stringify({uri:eventFactory.event_url[0]})
  }).then(function successCallback(response) {
      document.getElementById('weather').style.visibility = "visible";
      $scope.url=response.data.info;
      $scope.lat_long=response.data.position;
      $scope.$apply();
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady([42.3601, -71.0589]));
    }, function errorCallback(response) {
  });
```


----

After the creating a map instance, the map fires `MAP_READY` event when it is ready.
You need to add the event listener **before** the event is fired.
But during the time, you do `$http(...)`. That's why you miss the event.

So you should do like this.


```js
  map = plugin.google.maps.Map.getMap(div);
  // Wait until the map is ready status.
  map.addEventListener(plugin.google.maps.event.MAP_READY, function() {

    $http({
      method: 'POST',
      url: "https://fair-events.herokuapp.com/api/parseLatAndLongWeather/",
      headers: {
        'Content-Type': 'application/json'
      },
      data: JSON.stringify({uri:eventFactory.event_url[0]})
    }).then(function successCallback(response) {
        document.getElementById('weather').style.visibility = "visible";
        $scope.url=response.data.info;
        $scope.lat_long=response.data.position;
        $scope.$apply();
        onMapReady([42.3601, -71.0589]);
      }, function errorCallback(response) {
    });
  });
```

![1818_complessed](https://user-images.githubusercontent.com/167831/31782817-0dfa92b6-b4b1-11e7-9595-ca9a3ea4fe5e.gif)

**Comment by kanalasumant** [comment]
Thank you so much, but this should resolve the issue as seen in the gif you put up, but weirdly isn't working on my phone when I updated the code the way you described as above. That is strange! If you dont' mind can you once more look at the main.js file in the repository I updated for the updated code. I did exactly as you said. Maybe the android OS version might differ the code written. Can you describe which android os you're running it on and if possible can you send the updated file if possible to my email id. this is my email: kanalas@sunyit.edu

**Comment by kanalasumant** [comment]
I'm very close to getting this issue fixed. I cannot appreciate the time you put into this.!

**Comment by wf9a5m75** [comment]
You should invite me to your project repository.

**Comment by kanalasumant** [comment]
Done. Thanks

**Comment by wf9a5m75** [comment]
Thank you.  I will puah the code later.

**Comment by wf9a5m75** [comment]
ping

**Comment by kanalasumant** [comment]
Sorry, must be apk caching issues. But I'll confirm it today evening, and we could close this issue. I cannot thank you enough for your help @wf9a5m75

**Comment by wf9a5m75** [comment]
Ok, sounds good. Thank you for using this plugin.

----

By the way, I appreciate if you support for this project. 
This is not mandatory asking.
I just always ask when I debug for other person project because I spend my private time.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
When you donate some amount to the project, please include your issue number in your name.

**Comment by kanalasumant** [comment]
I will certainly donate to this wonderful and simple to use plugin you created.

**Comment by wf9a5m75** [comment]
Thank you for your donation!
