### ISSUE TITLE
Can we add Ionic-footer component underneath the map view with the map scrolling option.

### ISSUE THREAD

**Issue by mba858** [mapsplugin/cordova-plugin-googlemaps#1819]
We've requirement to place map in scroll view. And we also need to place footer component at the bottom of screen. So when user scrolls the view and map comes underneath of the footer, the footer inner elements stop working due to map interaction.
So is there any option, if we can entertain some components outside of the map?
Screenshots of the scenarios are attached too.
Footer inner elements works in first 2 screenshots, but doesn't work in last screenshot.

<img src="https://user-images.githubusercontent.com/5446242/31583909-ee848b72-b1bc-11e7-8fb8-01923b7045e6.png" width="250">
<img src="https://user-images.githubusercontent.com/5446242/31583910-eecc81f2-b1bc-11e7-9d7a-7c7ba2cd362b.png" width="250">
<img src="https://user-images.githubusercontent.com/5446242/31583912-f9b1a6ce-b1bc-11e7-85ca-1674dafb19c2.png" width="250">

**Comment by wf9a5m75** [comment]
Add z-index(higher value than the map div)  to the footer.

**Comment by wf9a5m75** [comment]
ping

**Comment by mba858** [comment]
Sorry for late reply. I tried it, it's not working in 1.4.1 version. Will it work in latest version?

**Comment by wf9a5m75** [comment]
No more support for v1.x.
