### ISSUE TITLE
Map disappears when in a tab, and Android back button is tapped

### ISSUE THREAD

**Issue by ahvin2020** [mapsplugin/cordova-plugin-googlemaps#1820]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ x] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-android-play-services-gradle-release 0.0.2 "cordova-android-play-service
s-gradle-release"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.0-beta-20171005-1430 "cordova-plugin-googlemaps"
cordova-plugin-nativegeocoder 1.0.2 "NativeGeocoder"
cordova-plugin-network-information 1.3.0 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
cordova.plugins.diagnostic 3.6.5 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.0 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please show me the package.json**
```
"dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/camera": "^4.1.0",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/diagnostic": "^4.1.0",
    "@ionic-native/facebook": "^4.1.0",
    "@ionic-native/file-transfer": "^4.1.0",
    "@ionic-native/geolocation": "^4.1.0",
    "@ionic-native/keyboard": "^4.1.0",
    "@ionic-native/native-geocoder": "^4.1.0",
    "@ionic-native/push": "^4.1.0",
    "@ionic-native/social-sharing": "^4.2.0",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "^3.12.1",
    "@ionic/storage": "2.0.1",
    "cordova": "^7.0.1",
    "cordova-plugin-facebook4": "^1.9.1",
    "cordova-plugin-geolocation": "^2.4.3",
    "cordova-sqlite-storage": "^2.0.4",
    "cordova.plugins.diagnostic": "^3.6.5",
    "ionic-angular": "^3.6.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic2-rating": "^1.2.2",
    "ionicons": "3.0.0",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"
  }
```

**Current behavior:**
When map is in a page that belongs to a tab, tapping on the Android back button will make the map disappear. Also if that page pushes another view, when tapping the Android back button, the view is popped, but the map also disappears.

**Expected behavior:**
Map shouldn't disappear when tapping on Android back button

**Comment by wf9a5m75** [comment]
``cordova.fireDocumentEvent('plugin_touch', {});

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by uiktiomasfeliz** [comment]
i have same problem, the map is not showing, i think is related, [here ](https://github.com/uiktiomasfeliz/MyIonicProject)my example git

**Comment by ahvin2020** [comment]
Not sure is it because I tried this: before leaving the current tab or pushing another view onto map page, hide the map 
`this.map.setDiv();`

then when returning back to the page, show the map using:
`this.map.setDiv("mapDiv");`

The map then doesn't disappear

**Comment by wf9a5m75** [comment]
`this.map.setDiv("mapDiv");`

This code does not work of course.
You have to pass the DOM element, not string.

**Comment by ahvin2020** [comment]
Ah, my bad, was using the dom element:
this.map.setDiv(mapDiv);

**Comment by wf9a5m75** [comment]
@ahvin2020
Please share your project files on github if you still need my help. Otherwise, please close this thread.
