### ISSUE TITLE
addMarkerCluster is not a function

### ISSUE THREAD

**Issue by krishnareddy1526** [mapsplugin/cordova-plugin-googlemaps#1821]
i want to marker cluster in my map i am using ionic native 4.3.2 version and cordova plugin vesion is git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps

i am getting these errors 

reject: TypeError: _this._objectInstance.addMarkerCluster is not a function
cordova.js:312 Error in Success callbackId: GoogleMaps1340072753 : TypeError: Cannot read property 'push' of null
cordova.js:314 Uncaught TypeError: Cannot read property 'push' of null
    at App.<anonymous> (main.js:58344)
    at plugins/cordova-plugin-googlemaps/www/googlemaps-cdv-plugin.js:1096
    at Object.callbackFromNative (cordova.js:293)
    at <anonymous>:1:9

my code is 

 `this.map.addMarkerCluster({
      'boundsDraw': false,
      maxZoomLevel: 14,
      markers: this.dummyData(),
      icons: [
        {
          min:2,
          max:20000,
       path: this.car,
      scale: .7,
      strokeColor: 'white',
      strokeWeight: .10,
      fillOpacity: 1,
      fillColor: '#404040',
      offset: '5%',
      // rotation: parseInt(heading[i]),
        anchor: new google.maps.Point(10, 25)
        }
      ]
    }).then((markerCluster) => {
       console.log("markercluster");
      markerCluster.on(GoogleMapsEvent.MAP_READY).subscribe((params) => {
        let latLng: LatLng = params[0];
        let marker: Marker = params[1];

        console.log(params);
        console.log(latLng);
        console.log(marker);

        marker.setAnimation(GoogleMapsAnimation.BOUNCE);

        marker.one(GoogleMapsEvent.INFO_CLICK).then((param) => {
          console.log('info click');
          console.log(param);
        });
      });

    }).catch(e => console.log("reject: " + e));

dummyData(){
return [
      {
        "position": {
          "lat": 21.382314,
          "lng": -157.933097
        },
        "name": "Starbucks - HI - Aiea  03641",
        "address": "Aiea Shopping Center_99-115 Aiea Heights Drive #125_Aiea, Hawaii 96701",
        "phone": "808-484-1488"
      },
      {
        "position": {
          "lat": 21.3871,
          "lng": -157.9482
        },
        "name": "Starbucks - HI - Aiea  03642",
        "address": "Pearlridge Center_98-125 Kaonohi Street_Aiea, Hawaii 96701",
        "phone": "808-484-9548"
      },
      {
        "position": {
          "lat": 21.363402,
          "lng": -157.928275
        },
        "name": "Starbucks - HI - Aiea  03643",
        "address": "Stadium Marketplace_4561 Salt Lake Boulevard_Aiea, Hawaii 96818",
        "phone": "808-488-9313"
      },
      {
        "position": {
          "lat": 21.3884,
          "lng": -157.9431
        },
        "name": "Starbucks - HI - Aiea  03644",
        "address": "Pearlridge Mall_98-1005 Moanalua Road_Aiea, Hawaii 96701",
        "phone": "808-484-9355"
      },
      {
        "position": {
          "lat": 21.6507,
          "lng": -158.0652
        },
        "name": "Starbucks - HI - Haleiwa  03645",
        "address": "Pupukea_59-720 Kamehameha Highway_Haleiwa, Hawaii 96712",
        "phone": "808-638-0341"
      }
   ]
}`

these are my function please identify if there is mistake and give me suggestions for rsolving problem`

`
![screenshot 57](https://user-images.githubusercontent.com/21124990/31716664-860cc73c-b426-11e7-9a5a-d01d190d6574.png)

**Comment by wf9a5m75** [comment]
Please share your project filea on github. Please do not past your code on here.

I'm so busy person. Please (x30000000) save my time.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update for a while, I close this thread. But you can still reply to this thread if you have any updates.
