### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#1822]
Class not found

  | (anonymous) | @ | ion-dev.js?v=3.0.0:156
-- | -- | -- | --
  | errorHandler | @ | BaseClass.js:116
  | (anonymous) | @ | googlemaps-cdv-plugin.js:754
  | t.invokeTask | @ | polyfills.js:3
  | onInvokeTask | @ | core.es5.js:3881
  | t.invokeTask | @ | polyfills.js:3
  | r.runTask | @ | polyfills.js:3
  | e.invokeTask | @ | polyfills.js:3
  | i.isUsingGlobalCallback.invoke | @ | polyfills.js:3
  | n | @ | polyfills.js:2
  | setTimeout (async) |   |  
  | o | @ | polyfills.js:2
  | t.scheduleTask | @ | polyfills.js:3
  | onScheduleTask | @ | polyfills.js:3
  | t.scheduleTask | @ | polyfills.js:3
  | r.scheduleTask | @ | polyfills.js:3
  | r.scheduleMacroTask | @ | polyfills.js:3
  | (anonymous) | @ | polyfills.js:2
  | o.(anonymous function) | @ | polyfills.js:2
  | commandQueue.push.args | @ | googlemaps-cdv-plugin.js:753
  | callbackFromNative | @ | cordova.js:295
  | processMessage | @ | cordova.js:1119
  | processMessages | @ | cordova.js:1142
  | t.invoke | @ | polyfills.js:3
  | onInvoke | @ | core.es5.js:3890
  | t.invoke | @ | polyfills.js:3
  | r.run | @ | polyfills.js:3
  | (anonymous) | @ | polyfills.js:3
  | t.invokeTask | @ | polyfills.js:3
  | onInvokeTask | @ | core.es5.js:3881
  | t.invokeTask | @ | polyfills.js:3
  | r.runTask | @ | polyfills.js:3
  | o | @ | polyfills.js:3
  | Promise resolved (async) |   |  
  | r | @ | polyfills.js:3
  | t.scheduleTask | @ | polyfills.js:3
  | onScheduleTask | @ | polyfills.js:3
  | t.scheduleTask | @ | polyfills.js:3
  | r.scheduleTask | @ | polyfills.js:3
  | r.scheduleMicroTask | @ | polyfills.js:3
  | f | @ | polyfills.js:3
  | c | @ | polyfills.js:3
  | (anonymous) | @ | polyfills.js:3
  | Promise resolved (async) |   |  
  | (anonymous) | @ | polyfills.js:3
  | t | @ | polyfills.js:3
  | t.then | @ | polyfills.js:3
  | (anonymous) | @ | cordova.js:935
  | androidExec | @ | cordova.js:977
  | resetTimer | @ | googlemaps-cdv-plugin.js:478
  | fireDocumentEvent | @ | cordova.js:235
  | getMap | @ | googlemaps-cdv-plugin.js:622
  | GoogleMap | @ | index.js:1349
  | GoogleMaps.create | @ | index.js:370
  | (anonymous) | @ | profile.ts:44
  | t.invoke | @ | polyfills.js:3
  | onInvoke | @ | core.es5.js:3890
  | t.invoke | @ | polyfills.js:3
  | r.run | @ | polyfills.js:3
  | (anonymous) | @ | polyfills.js:3
  | t.invokeTask | @ | polyfills.js:3
  | onInvokeTask | @ | core.es5.js:3881
  | t.invokeTask | @ | polyfills.js:3
  | r.runTask | @ | polyfills.js:3
  | o | @ | polyfills.js:3
  | e.invokeTask | @ | polyfills.js:3
  | p | @ | polyfills.js:2
  | v | @ | polyfills.js:2
  | XMLHttpRequest.send (async) |   |  
  | s | @ | polyfills.js:3
  | t.scheduleTask | @ | polyfills.js:3
  | onScheduleTask | @ | polyfills.js:3
  | t.scheduleTask | @ | polyfills.js:3
  | r.scheduleTask | @ | polyfills.js:3
  | r.scheduleMacroTask | @ | polyfills.js:3
  | (anonymous) | @ | polyfills.js:3
  | o.(anonymous function) | @ | polyfills.js:2
  | (anonymous) | @ | http.es5.js:1275
  | Observable._trySubscribe | @ | Observable.js:171
  | Observable.subscribe | @ | Observable.js:159
  | MapOperator.call | @ | map.js:54
  | Observable.subscribe | @ | Observable.js:156
  | webpackJsonp.199.ProfilePage.ngOnInit | @ | profile.ts:32
  | checkAndUpdateDirectiveInline | @ | core.es5.js:10856
  | checkAndUpdateNodeInline | @ | core.es5.js:12357
  | checkAndUpdateNode | @ | core.es5.js:12296
  | debugCheckAndUpdateNode | @ | core.es5.js:13160
  | debugCheckDirectivesFn | @ | core.es5.js:13101
  | (anonymous) | @ | ProfilePage_Host.html:1
  | debugUpdateDirectives | @ | core.es5.js:13086
  | checkAndUpdateView | @ | core.es5.js:12263
  | callWithDebugContext | @ | core.es5.js:13486
  | debugCheckAndUpdateView | @ | core.es5.js:13026
  | ViewRef_.detectChanges | @ | core.es5.js:10189
  | NavControllerBase._viewAttachToDOM | @ | nav-controller-base.js:589
  | Tab._viewAttachToDOM | @ | tab.js:324
  | NavControllerBase._transition | @ | nav-controller-base.js:681
  | (anonymous) | @ | nav-controller-base.js:363
  | t.invoke | @ | polyfills.js:3
  | onInvoke | @ | core.es5.js:3890
  | t.invoke | @ | polyfills.js:3
  | r.run | @ | polyfills.js:3
  | (anonymous) | @ | polyfills.js:3
  | t.invokeTask | @ | polyfills.js:3
  | onInvokeTask | @ | core.es5.js:3881
  | t.invokeTask | @ | polyfills.js:3
  | r.runTask | @ | polyfills.js:3
  | o | @ | polyfills.js:3
  | e.invokeTask | @ | polyfills.js:3
  | p | @ | polyfills.js:2
  | v

this error appears in my log. I dont know what can be this is my code: 
`mport { Component, OnInit } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';

import { ClientsService } from '../../providers/clients.service';

import {
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  GoogleMapOptions,
  CameraPosition,
  MarkerOptions,
  Marker
 } from '@ionic-native/google-maps';

@Component({
  selector: 'page-profile',
  templateUrl: 'profile.html'
})
export class ProfilePage implements OnInit {
  client: any;
  map: GoogleMap;
  mapElement: HTMLElement;
  constructor(private googleMaps: GoogleMaps, public platform: Platform, public clientsService: ClientsService) {

    platform.ready().then(() => {
      this.loadMap1();
    });
  }

  ngOnInit() {
    this.clientsService.getProfile().subscribe((data: any) => {
      this.client = data;
      //this.loadMap1();
    })
  }

 loadMap1() {
    this.mapElement = document.getElementById('map');

    let mapOptions: GoogleMapOptions = {
      camera: {
        target: {
          lat: 43.0741904,
          lng: -89.3809802
        },
        zoom: 18,
        tilt: 30
      }
    };

    this.map = this.googleMaps.create(this.mapElement, mapOptions);

    // Wait the MAP_READY before using any methods.
    this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => {
        console.log('Map is ready!');

        // Now you can use all methods safely.
        this.map.addMarker({
            title: 'Ionic',
            icon: 'blue',
            animation: 'DROP',
            position: {
              lat: 43.0741904,
              lng: -89.3809802
            }
          })
          .then(marker => {
            marker.on(GoogleMapsEvent.MARKER_CLICK)
              .subscribe(() => {
                alert('clicked');
              });
          });

      });
  }

}
`

**Comment by wf9a5m75** [comment]
What is this? At least you should share your project files on github if you want to help me.

**Comment by francoro** [comment]
is a bitbucket repo. Pass me your email

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75

**Comment by francoro** [comment]
I already send you the invite. The file is in src/pages/profile/profile.ts and when you see it running is under the tab Perfil it should be at the bottom in this page , but it shows a blank space the error that i told you above it doesnt happen anymore so the error now is that it shows a blank space instead of the map

**Comment by francoro** [comment]
Android

**Comment by francoro** [comment]
this.map = this.googleMaps.create(this.mapElement, mapOptions);

Look my log of this code. It seems that the map is added but maybe its something of time that is not added when it should be:

this.map GoogleMap {_objectInstance: Map}_objectInstance: MapKML_LAYERS: {}MARKERS: {marker_202361513: Marker}OVERLAYS: {marker_202361513: Marker}errorHandler: ƒ ()Symbol(subscriptions): {map_click: Array(1), active_marker_id_changed: Array(1), remove: Array(1), map_ready: Array(0)}Symbol(vars): {visible: false, _overlays: BaseArrayClass, camera: {…}, camera_target: {…}, camera_zoom: 2, …}hashCode: 6332973197id: "map_0_943932710046"type: "Map"_isReady: true__proto__: Object__proto__: BaseClassaddCircle: ƒ ()addGroundOverlay: ƒ ()addMarker: ƒ ()addMarkerCluster: ƒ ()addPolygon: ƒ ()addPolyline: ƒ ()addTileOverlay: ƒ ()animateCamera: ƒ ()animateCameraZoomIn: ƒ ()animateCameraZoomOut: ƒ ()clear: ƒ ()constructor: ƒ GoogleMap(element, options)fromLatLngToPoint: ƒ ()fromPointToLatLng: ƒ ()getCameraBearing: ƒ ()getCameraPosition: ƒ ()getCameraTarget: ƒ ()getCameraTilt: ƒ ()getCameraZoom: ƒ ()getDiv: ƒ ()getFocusedBuilding: ƒ ()getMyLocation: ƒ ()getVisibleRegion: ƒ ()moveCamera: ƒ ()moveCameraZoomIn: ƒ ()moveCameraZoomOut: ƒ ()panBy: ƒ ()refreshLayout: ƒ ()remove: ƒ ()setAllGesturesEnabled: ƒ ()setCameraBearing: ƒ ()setCameraTarget: ƒ ()setCameraTilt: ƒ ()setCameraZoom: ƒ ()setClickable: ƒ ()setCompassEnabled: ƒ ()setDiv: ƒ ()setIndoorEnabled: ƒ ()setMapTypeId: ƒ ()setMyLocationEnabled: ƒ ()setOptions: ƒ ()setPadding: ƒ ()setTrafficEnabled: ƒ ()setVisible: ƒ ()toDataURL: ƒ ()__proto__: Object

**Comment by wf9a5m75** [comment]
When you past your log or code, please use the github markdown format.

**Comment by francoro** [comment]
Done

**Comment by wf9a5m75** [comment]
![screen shot 2017-10-18 at 10 51 10 am](https://user-images.githubusercontent.com/167831/31734077-66573596-b3f2-11e7-9204-762fbf2764b7.png)

![screen shot 2017-10-18 at 10 50 02 am](https://user-images.githubusercontent.com/167831/31734022-3ae920ae-b3f2-11e7-9457-8dce1a56c416.png)

**Comment by francoro** [comment]
why can be this happen? it has the same name in the view if you check it profile.html

**Comment by wf9a5m75** [comment]
`platform.ready()` does not mean the view is ready.
Please study the lifecycle of the ionic framework.

**Comment by francoro** [comment]
Oh i see now. i use and it works. Thanks!
 ```
ionViewDidLoad() {
    this.loadMap();
  }
```

**Comment by wf9a5m75** [comment]
If you want to use the `livereload`, inserting `setTimeout` is better like this. Because the platform.ready() delays sometime.

```js
  ionViewDidEnter(){
    setTimeout(this.loadMap.bind(this), 1000);
  }
```

----

By the way, I appreciate if you support for this project.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
When you donate some amount to the project, please include your issue number in your name.

**Comment by francoro** [comment]
Sure i will donate when i free at night.Thanks for all your help
