### ISSUE TITLE
Geocoder cannot converts address to position 

### ISSUE THREAD

**Issue by tuanvuf4** [mapsplugin/cordova-plugin-googlemaps#1826]
new Geocoder().geocode({
        position: {
          lat: 52.5072095,
          lng: 13.1452818
        }
      }).then(data => {
        console.log(data);
      });
i receive an empty array on then method. Plz tell me what is this wrong ?

**Comment by wf9a5m75** [comment]
Geocoder is out of control of this plugin. The result is depend on Google or Apple. The plugin just passes the parameters to the api, then pass back the results to the js.

So I can not help you anything.

**Comment by tuanvuf4** [comment]
I dont know why but i restart my phone and reinstall plugin, it work for me. Thank!
