### ISSUE TITLE
My index.html is all blank

### ISSUE THREAD

**Issue by Zygon** [mapsplugin/cordova-plugin-googlemaps#1827]
Hi, 

I'm facing a problem with the plugin, i have 2 pages (index.html and map_page.html) 

I only use the map on the map_page! The index.html is all blank when i say blank the Map Plugin add this lines to the code: 

html, body, ._gmaps_cdv_ {   background-image: url() !important;   background: rgba(0,0,0,0) url() !important;   background-color: rgba(0,0,0,0) !important;}._gmaps_cdv_ .nav-decor {   background-color: rgba(0,0,0,0) !important;   background: rgba(0,0,0,0) !important;   display:none !important;}

and: 
`<body style="background-color: rgba(0, 0, 0, 0);">`

when i remove the plugin all the page style back to normal. 

i've tried to apply a workarround like this one but I think that is not the real solution: 

        element = document.body;
        element.removeAttribute("style");

        var hs = document.getElementsByTagName('style');
        for (var i = 0, max = hs.length; i < max; i++) {
            hs[i].parentNode.removeChild(hs[i]);
        }

Thank for the Help.

**Comment by wf9a5m75** [comment]
This plugin places the native map view under the browser view. So the browser must be transparented.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#how-does-this-plugin-work

**Comment by Zygon** [comment]
Hi, 

Thank for the help (I already made this work)!

**Comment by renznamoc21** [comment]
@Zygon how did you fix this ?
