### ISSUE TITLE
Infowindow marker just show last element

### ISSUE THREAD

**Issue by danbeo95** [mapsplugin/cordova-plugin-googlemaps#1828]
I have this code to add multil marker
setMap(option: { map: GoogleMap, marker: Array<any> }) {
		let labels: any[] = ['A', 'B'];
		let marker = option.marker;
		let map = option.map;
		let index = 0;
		marker.forEach((option) => {
			option.title = "A";
			map.addMarker(option).then((marker) => {
				marker.showInfoWindow();
			});
		});
	}
i don't understant why just last element show infowindow.Other marker show when i click!
i used googlemap-native 4.2.1
please help me

**Comment by wf9a5m75** [comment]
The native APIs support only one infoWindow. Can not open multiple infoWindow at the same time.
