### ISSUE TITLE
Ionic map blank screen second time

### ISSUE THREAD

**Issue by thiagovargas** [mapsplugin/cordova-plugin-googlemaps#1829]
Hi, im getting this error on my app when i access the page where has a map on the second time.
See the gif to know my problem.
This error happens only in iOS, Android works fine.

![video](https://user-images.githubusercontent.com/9723698/31825353-bdb76078-b590-11e7-890c-1460a13d3b87.gif)

**Comment by wf9a5m75** [comment]
Please share your project files. I will check it. Otherwise, I can not help you.

**Comment by thiagovargas** [comment]
Here is the code of the page that show de map?

`import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, Platform } from 'ionic-angular';
import { Geolocation, GeolocationOptions, Geoposition, PositionError } from '@ionic-native/geolocation';
import {
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  GoogleMapOptions,
  Geocoder,
  GeocoderRequest,
  LatLng,
  HtmlInfoWindow
} from '@ionic-native/google-maps';
import { LocalizarLaboratorioProvider } from '../../providers/localizar-laboratorio/localizar-laboratorio';
import { Storage } from '@ionic/storage';
import { ConfigProvider } from '../../providers/config/config';

//declare var google;

@IonicPage()
@Component({
  selector: 'page-localizar-laboratorio',
  templateUrl: 'localizar-laboratorio.html',
})

export class LocalizarLaboratorioPage {
  options: GeolocationOptions;
  currentPos: Geoposition;
  mapElement: HTMLElement;
  map: GoogleMap;
  lista_laboratorio: any;
  lista_estado: [any];

  constructor(
    private config: ConfigProvider,
    private storage: Storage,
    private localizarlab: LocalizarLaboratorioProvider,
    private geocoder: Geocoder,
    public platform: Platform,
    private googleMaps: GoogleMaps,
    private geolocation: Geolocation,
    public navCtrl: NavController,
    public navParams: NavParams) {
  }

  ionViewDidEnter() {
    this.platform.ready().then(() => {
      if (this.map != undefined) {
        this.map.remove();
      }

      //this.GetUserPosition();

      setTimeout(() => {
        this.GetUserPosition();
      }, 100);
    });
  }

  GetUserPosition() {
    this.options = {
      enableHighAccuracy: true
    };
    this.geolocation.getCurrentPosition(this.options).then((pos: Geoposition) => {
      this.currentPos = pos;
      this.LoadMap(pos.coords.latitude, pos.coords.longitude);
      this.GetUF(pos.coords.latitude, pos.coords.longitude);
    }, (err: PositionError) => {
      console.log("error : " + err.message);
      ;
    })
  }

  GetUF(lat: any, long: any) {
    let request: GeocoderRequest = {
      position: new LatLng(lat, long),
    };
    return new Promise((resolve, reject) => {
      this.geocoder.geocode(request).then((results) => {

        if (results[0].adminArea != undefined) {
          let sigla = this.localizarlab.GetSiglaUF(results[0].adminArea);
          resolve(sigla);
        } else {
          resolve("");
        }
      });
    });
  }

  ShowInfo(lista: [any], lat: number, lng: number, html: string, htmlInfoWindow: any, marker: any) {
    var lab = lista.find(x => x.Latitude === lat.toString() && x.Longitude === lng.toString());

    if (lab != undefined) {
      //html = html.replace("{0}", lab.UrlLogomarca);
      html = html.replace("{1}", lab.Nome);
      html = html.replace("{2}", lab.Endereco);
      html = html.replace("{3}", lab.Telefone);
      html = html.replace("{4}", lab.Site);
      html = html.replace("{5}", lab.Atendimento);
      htmlInfoWindow.setContent(html);
      htmlInfoWindow.open(marker);
    }
  }

  AddMarker(lista: [any]) {
    var htmlInfoWindow = new HtmlInfoWindow();
    var html = [
      "<div style='width:300px; min-height:200px;'>",
      "<div style='text-align: center;'>",
      //"<img src='{0}' style='width:50%; display: inline-block;'/><br/>",
      "<h5>{1}</h5>",
      "</div>",
      "<div>",
      "<table style='width:100%'>",
      "<tr><td valign='top' style='text-align: right;'><strong>Endereço:</strong></td><td> {2}</td></tr>",
      "<tr><td style='text-align: right;'><strong>Telefone:</strong></td><td> {3}</td></tr>",
      "<tr><td style='text-align: right;'><strong>Site:</strong></td><td> {4}</td></tr>",
      "<tr><td style='text-align: right;'><strong>Horário:</strong></td><td> {5}</td></tr>",
      "</table>",
      "</div>",
      "</div>"
    ].join("");

    for (let item of lista) {
      this.map.addMarker({
        icon: 'red',
        animation: 'DROP',
        position: {
          lat: Number.parseFloat(item.Latitude),
          lng: Number.parseFloat(item.Longitude)
        }
      }).then(marker => {
        marker.on(GoogleMapsEvent.MARKER_CLICK)
          .subscribe((mkr: LatLng) => {
            this.ShowInfo(lista, item.Latitude, item.Longitude, html, htmlInfoWindow, marker);
          });
      });
    }
  }

  AddMarkerToMap(lat: number, lng: number) {
    this.GetUF(lat, lng).then((data: string) => {
      let uf = "";
      let auth: string;

      uf = data;

      if (this.lista_estado == undefined) {
        this.lista_estado = [''];
      }

      if (this.lista_estado.find(x => x === uf) == undefined) {
        this.storage.forEach((value, key, index) => {
          if (key == "auth") {
            auth = value;
          }
        }).then(data => {
          this.localizarlab.GetLaboratorios(uf, auth)
            .then((data: string) => {
              this.lista_estado.push(uf);
              this.AddMarker(JSON.parse(data).retorno.dados_lab)
            }).catch(err => {
              this.config.ShowMessage("Erro!", err.json());
            });
        });
      }
    });
  }

  LoadMap(lat: number, long: number) {
    this.mapElement = document.getElementById('map');

    let mapOptions: GoogleMapOptions = {
      camera: {
        target: {
          lat: lat,
          lng: long
        },
        zoom: 14
      }
    };

    this.map = this.googleMaps.create(this.mapElement, mapOptions);
    this.map.setMyLocationEnabled(true);
    this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => {
        this.map.on(GoogleMapsEvent.CAMERA_MOVE_END).subscribe((cameraPosition) => {
          if (cameraPosition[0] == undefined) {
            this.AddMarkerToMap(cameraPosition.target.lat, cameraPosition.target.lng);  
          }else{
            this.AddMarkerToMap(cameraPosition[0].target.lat, cameraPosition[0].target.lng);
          }
        });

        this.map.addMarker({
          title: 'Minha localização',
          icon: 'blue',
          animation: 'DROP',
          position: {
            lat: lat,
            lng: long
          }
        })
          .then(marker => {
            marker.on(GoogleMapsEvent.MARKER_CLICK)
              .subscribe(() => {

              });
          });

        this.AddMarkerToMap(lat, long);
      });
  }
}
`

**Comment by wf9a5m75** [comment]
Please share your project files on github. Do not paste your code here please.

**Comment by thiagovargas** [comment]
Sorry, please, see the code in https://github.com/thiagovargas/ionicmapissue1

**Comment by wf9a5m75** [comment]
In your package.json, at lease you need to use `4.2.1` instead of `3.12.1`
https://github.com/thiagovargas/ionicmapissue1/blob/c67b7238c865edd8a311f6e960ea24b00efcdf08/package.json#L23

**Comment by wf9a5m75** [comment]
And is there any reason to stay on `"cordova-plugin-googlemaps": "^2.0.8"`?
https://github.com/thiagovargas/ionicmapissue1/blob/c67b7238c865edd8a311f6e960ea24b00efcdf08/package.json#L41

At least `2.0.11` currently.

**Comment by thiagovargas** [comment]
About the "@ionic-native/core": "3.12.1", how can i update it?

the cordova-plugin-googlemaps i will update.

**Comment by wf9a5m75** [comment]
```
$> npm uninstall @ionic-native/core

$> npm install @ionic-native/core@4.3.2
```

**Comment by thiagovargas** [comment]
when install ionic-native core again, im getting this error message:

`-- UNMET PEER DEPENDENCY @ionic-native/core@4.3.2 invalid

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @ionic-native/splash-screen@3.12.1 requires a peer of @ionic-native/core@^3.6.0 but none was installed.
npm WARN @ionic-native/status-bar@3.12.1 requires a peer of @ionic-native/core@^3.6.0 but none was installed.
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm ERR! code 1

**Comment by wf9a5m75** [comment]
https://www.npmjs.com/package/@ionic-native/core

**Comment by thiagovargas** [comment]
i dont know why, but wont install 4.3.2, see:

`-- @ionic-native/core@3.14.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.

**Comment by wf9a5m75** [comment]
Could you use proper github markdown? And I'm not your teacher. Installing problem is your problem. Please search by Google at least.

**Comment by wf9a5m75** [comment]
I built your project, then how can I enter to the app?
![capture](https://user-images.githubusercontent.com/167831/31833974-29df69b8-b581-11e7-8b51-4121f1bf4c75.png)

**Comment by wf9a5m75** [comment]
https://stackoverflow.com/a/25394085/697856

**Comment by thiagovargas** [comment]
Android it work fine! On iOS im getting the error

**Comment by wf9a5m75** [comment]
You should give enough information before I work....

**Comment by wf9a5m75** [comment]
At the login view, what should I do? You should give enough information.

**Comment by wf9a5m75** [comment]
ping

**Comment by thiagovargas** [comment]
try 
sl
sl2017

**Comment by thiagovargas** [comment]
i did what you said. update the ionic native to 4.3.2 and the plugin to 2.0.11.
Im getting the same problem...

**Comment by wf9a5m75** [comment]
I didn't say "the latest version fixes the problem", but at least you should use the latest version because another bugs are fixed.

**Comment by thiagovargas** [comment]
ok, im only inform you that i update everthing and continue the problem... did you log in on the app?

**Comment by wf9a5m75** [comment]
Yes, finally. I can see two maps when I open the map page second times.
I'm checking your code.
![screen shot 2017-10-20 at 11 38 04 am](https://user-images.githubusercontent.com/167831/31836794-56594770-b58b-11e7-8805-278bc06112fe.png)

**Comment by wf9a5m75** [comment]
By the way, you can remove `geocoder` and `geolocation` plugins.
Because this plugin has both features.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getMyLocation/README.md

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Geocoder/reverse_geocoding/README.md

Reduce the number of plugins decreases your app file size.

**Comment by thiagovargas** [comment]
i've noted that if i tap on Localizar Laboratorio, then show the page map, ok. If you tap on the icon menu, it not work, you have to tap twice to close the menu and if you do that, the map you appear only on the right screen.
If you drag from right to left, the menu is closed and the map show fine!

**Comment by wf9a5m75** [comment]
And in your code, you should do like this.

```js
  ionViewDidEnter() {
    this.platform.ready().then(() => {
      this.GetUserPosition();
    });
  }

  ionViewDidLeave() {
    if (this.map) {
      this.map.remove();
    }
    this.map = null;
  }
```

**Comment by wf9a5m75** [comment]
Did you solve the issue? I solved your problem at my side.

**Comment by thiagovargas** [comment]
Hello, the problem was solved! I update all my package.json and works fine now! Thank you!

**Comment by wf9a5m75** [comment]
I appreciate if you support for this project.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
When you donate some amount to the project, please include your issue number in your name.
