### ISSUE TITLE
No map... 

### ISSUE THREAD

**Issue by ppetree** [mapsplugin/cordova-plugin-googlemaps#1830]
I included 2.0.0 via npm into my phonegap build project.

The project builds with no errors and running it in a simulator or on any live iOS devices there are no javascript errors, however, I get no map. 

I get as far as initializing the map (which works)
`map = plugin.google.maps.Map.getMap(div);`

If I use the <javascript> api method from google the maps work fine.

**Comment by wf9a5m75** [comment]
ping

**Comment by ppetree** [comment]
The files aren't stored on github... 
I emailed them to you instead.

**Comment by wf9a5m75** [comment]
>I emailed them to you instead.

No!!!!! Please use git repository, please don't send your code to me directly.

BitBucket is able to create a private repository as free.
https://bitbucket.org/product

If you are not familiar with BitBucket, here is tutorial.
https://confluence.atlassian.com/bitbucket/create-a-git-repository-759857290.html

Sending zip file (your project files) to my e-mail address increases my stress.

Using git repository has lots of benefits for you.
- you can back up your code easily,
- you can understand what changes one time and another time
- automatic synchronize with PhoneGap Build (you don't need to upload zip file every time)
- you can collaborate with other people easily
... etc.

Please use git repository.

**Comment by wf9a5m75** [comment]
Github Hello world
https://guides.github.com/activities/hello-world/

**Comment by ppetree** [comment]
You can close the ticket, I'll go back to using the old way.
