### ISSUE TITLE
GroundOverlay Remove is Throwing an Error With Latest Plugin Version and ios 11.0.3

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/cordova-plugin-googlemaps#1832]
<!--
=========================================================
Please support the plugin project
=========================================================
Masashi and Hirbod work for this plugin tons of times.
In order to provide this plugin as free in the future, please donate some small amount (such a $5 or $10 is fine).

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
When you donate some amount to the project, please include your issue number in your name.

=========================================================
Before ask your question, problems or feature request
=========================================================

## For the person who want to report your problem or the plugin bugs

Please search the past issues at first. You might get any hints.
If you can't solve your problem, please post your problems with enough information.

If you share your project files on Github(or others), your issue would be fixed soon.
If you can't share your project files (i.e. company project), please create a demo project, then share it.
No sharing any code, we probably can not help you anything.

## For the person who want to request new feature

This plugin is open source. You can use this plugin as free. However, in order to add one new feature, we need to work tons of times.
Please consider any donation. We typically start working if the donation reach to $1,000 USD. (You can fundraise at here)

=========================================================
Language support
=========================================================
English 

**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ x] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

Kimberlees-MacBook-Pro:dvMeterAudit kimberleearmstrong$ cordova plugin ls
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.8.5 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.2.2 "ActionSheet"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-googlemaps 2.1.0-beta-20171019-1713 "cordova-plugin-googlemaps"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-spatialite-storage 1.2.0 "Cordova sqlite/spatialite storage plugin"
phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"
phonegap-plugin-contentsync 1.3.5 "content-sync"
phonegap-plugin-push 1.8.4 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.1.1 "Launch Navigator"
Kimberlees-MacBook-Pro:dvMeterAudit kimberleearmstrong$ 

**If you use `@ionic-native/google-maps`, please show me the package.json**

**Current behavior:**
calling remove function on ground overlay throws error self.trigger is not a function on GroundOverlay.js line 150

**Expected behavior:**
the ground overlay would be removed

**Steps to reproduce:**
panning or zooming will try to remove the ground overlay and throw the error

**Screen capture or video record:**
![screen shot 2017-10-20 at 4 36 06 pm](https://user-images.githubusercontent.com/9216004/31843023-84e1c9d4-b5b6-11e7-88d5-137f469806e3.png)

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```

**Comment by wf9a5m75** [comment]
Please create a demo project.

**Comment by wf9a5m75** [comment]
Can not reproduce with the multiple_maps branch.

![1832_compless](https://user-images.githubusercontent.com/167831/31844564-61825f88-b5ae-11e7-874d-a57f0349f322.gif)

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Well, the `OVERLAYS` property is for internal use. I don't guarantee I keep the same mechanism in the feature.

**Comment by KimberleeDArmstrong** [comment]
I understand, but it is the only way I can work around the issue where sometimes the old groundlayers get left on them map. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by wf9a5m75** [comment]
In common, the developers should manage the instances by themselves.
However, only JS developers (not only you, but also many people) do not manage the instances for some reason.

I inserted protector code to prevent executing the `remove` method after the instance has been removed.
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/c427a49fe6254e15399b45a920e39c8aabdc2135

Please try from the multiple_maps branch.
You should not need to do hack anymore.
