### ISSUE TITLE
Latitude and Longitude are in JSOn format instead of numbers

### ISSUE THREAD

**Issue by cuisineje** [mapsplugin/cordova-plugin-googlemaps#1833]
var your_location = new plugin.google.maps.LatLng(position.coords.latitude , position.coords.longitude); 	        
 var destination_location = new plugin.google.maps.LatLng(merchant_latitude , merchant_longtitude); 	        
plugin.google.maps.external.launchNavigation({
                "from": your_location,
	         "to": destination_location
	      });	
when the google navigation launches the from and to addresses are as below:
{"lat":49.179416,"lng":-2.109288}
{"lat":49.1188618,"lng":-2.1112165}

Navigation is expecting just two numbers as co-ordinates. Am I doing something wrong or is something changed in the library meanwhile?
using 2.0.0

**Comment by wf9a5m75** [comment]
plugin.google.maps.external.launchNavigation will be removed in next release

**Comment by wf9a5m75** [comment]
I recommend the alternative plugin. Please read the description page before question.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/External-Service/README.md
