### ISSUE TITLE
Extra white space is being shown for some reason, after updating from v1.4 to v2.0.11

### ISSUE THREAD

**Issue by sharjeel619** [mapsplugin/cordova-plugin-googlemaps#1836]
For some reason all of my pages are showing extra white space below, which do not even have a map in them. I did not change any code whatsoever. The map is working absolutely fine. If there is anything I could do inside some java file which would change the background color of the whole app, that may be able to help me. Any help would be highly appreciated. 
<img src="https://user-images.githubusercontent.com/11159443/31914479-43eadfe6-b864-11e7-95c1-acd8dffb17c5.png" width="250">

**Comment by wf9a5m75** [comment]
The plugin displays the same position as the map div.
You need to manage the div position by yourself.

If you can't resolve the issue, please share your project files on github(or others, such as bitbucket).

**Comment by sharjeel619** [comment]
But why does this plugin shows white spaces on pages which do not have a map or a map div?

**Comment by wf9a5m75** [comment]
The plugin does not make any space.

**Comment by sharjeel619** [comment]
Ok, no problem. I'll just revert back to v.14
