### ISSUE TITLE
Add marker with custom id

### ISSUE THREAD

**Issue by weiztech** [mapsplugin/cordova-plugin-googlemaps#1837]
is that possible to `addMarker` with custom id or key  ?

**Comment by wf9a5m75** [comment]
The `id` is reserved by the plugin. But you can use another word (such as `_id`) is possible.

**Comment by wf9a5m75** [comment]
For example, you can do like this:

```js
map.addMarker({
  position: {...},
  _id: "myId"
}, function(marker) {
  console.log(marker.get("_id"));
});
```
