### ISSUE TITLE
how can i detect zoom change event on map ?

### ISSUE THREAD

**Issue by tuanvuf4** [mapsplugin/cordova-plugin-googlemaps#1841]

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/CAMERA_EVENTS/README.md

**Comment by tuanvuf4** [comment]
this may be cause camera change but zoom level doesn't change ?

**Comment by wf9a5m75** [comment]
`zoom` means `camera zoom`

**Comment by tuanvuf4** [comment]
Yes. like when you drag map, camera position is changed but camera zoom level still doesn't change. So when i zoom in, how can i  ?

**Comment by wf9a5m75** [comment]
Did you see the example code?
```js
function onCameraEvents(cameraPosition) {
  // Display the current camera position

  fields.lat.innerText = cameraPosition.target.lat;
  fields.lng.innerText = cameraPosition.target.lng;
  fields.zoom.innerText = cameraPosition.zoom;
  fields.tilt.innerText = cameraPosition.tilt;
  fields.bearing.innerText = cameraPosition.bearing;
}
```

This is the only detectable way.
