### ISSUE TITLE
map.setZoom and marker.setPosition is not working in new update but worked perfectely in earlier version

### ISSUE THREAD

**Issue by JYOTHISHPJ** [mapsplugin/cordova-plugin-googlemaps#1842]
map.setZoom(14);

                                       marker.setPosition({
                                                       lat: data.TRK_LAT,
                                                       lng: data.TRK_LON
                                                     });
                                                    map.setCenter({
                                                         lat: data.TRK_LAT,
                                                      lng: data.TRK_LON
                                                  });

  i used the code in earlier version it worked but after using new version of the plugin it is not working... Can you plz help....thanks in advance....

**Comment by wf9a5m75** [comment]
Please share (or create) your project files on github.
It is too less information.

**Comment by JYOTHISHPJ** [comment]
function mapLoadByName()
{
 var div = document.getElementById("map_canvas");
  var map = plugin.google.maps.Map.getMap(div);
  map.setMapTypeId(plugin.google.maps.event.MAP_READY);

map.clear();
    map.one(plugin.google.maps.event.MAP_READY, function() {
    map.addMarker({
       'position': {
         lat: 0,
         lng: 0
       },

       'title': document.getElementById('hfNameVeh').value
     }, function(marker) {
    map.setZoom(14);

       // Show the infoWindow.
    marker.showInfoWindow();


    TrackerUpdate();
     $scope.show($ionicLoading);
         function TrackerUpdate()
                   {
//alert("21");

                   var ChildId=document.getElementById('hfChildTrkId').value;
                  // alert(ChildId);

                          var LocationUpdateUrl = 'url of my webservice';
                                               var LocationUpdatTimeOut = 8000; /* 30 Seconds */
                                               var Trackid=document.getElementById('hfTrackIdFmSerach').value;
                                      $http.get(LocationUpdateUrl + "REVZ_MainSelectLATLON?CHI_ID=" + ChildId ,{
                                       timeout: LocationUpdatTimeOut
                                             })
                                            .success(function(data, status, headers, config){
                                             $ionicLoading.hide();

                                             marker.setPosition({
                                                       lat: data.TRK_LAT,
                                                       lng: data.TRK_LON
                                                     });
                                                    map.setCenter({
                                                         lat: data.TRK_LAT,
                                                      lng: data.TRK_LON
                                                  });
                                                   // map.setZoom(16);
                                           })
                                            .error(function(){
                                             $ionicLoading.hide();

                                              });
                          timer1 =  $timeout(TrackerUpdate, 4000);
                   };

       });

});
}
   });



this is my function which is used for calling map... everything is perfectly earlier....but 
map.setZoom(14);

and

 marker.setPosition are not working after new i updated the plugin.

**Comment by wf9a5m75** [comment]
First of all, your code is wrong couple of things.

You must wait the MAP_READY event before using any methods.

And this plugin does not have the name of the method `map.setZoom()`.
In v1.4, someone insert the code during I leave the project,
but in v2, it doesn't have it.
You should read the documents before question.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/setCameraZoom/README.md

**Comment by JYOTHISHPJ** [comment]
Sorry man...It's worked perfectly at first...I think is i missed something at new update....Anyway thanks for your time......
