### ISSUE TITLE
Cannot access to the 'fromPointToLatLng' method.

### ISSUE THREAD

**Issue by caereservices** [mapsplugin/cordova-plugin-googlemaps#1845]
BaseClass.js:116 Cannot access to the 'fromPointToLatLng' method.
errorHandler @ BaseClass.js:116
(anonymous) @ googlemaps-cdv-plugin.js:754
setTimeout (async)
commandQueue.push.args @ googlemaps-cdv-plugin.js:753
callbackFromNative @ cordova.js:296
(anonymous) @ VM304:1

This following code cause errors:

function touchStartEvt(e) {
   e.preventDefault();
   var x = e.pageX - this.offsetLeft;
   var y = e.pageY - this.offsetTop;
   map.fromPointToLatLng([x, y], function(LatLng) {
      map.addPolyline({
         'points': [new plugin.google.maps.LatLng(LatLng[0], LatLng[1])],
         'color' : '#c0392b',
         'width': 3
      }, function(polyline) {
         polyGlobal = polyline;
         div.addEventListener("touchmove", touchMoveEvt, true);
         div.addEventListener("touchend", touchEndEvt, true);
      });
   });
}

map is defined like a GLOBAL variable and other functions/methods working correctly

I work with this software version

cordova 7.1.0
android 6.3.0
ios 4.5.2
cordova-plugin-googlemaps  2.0.11

FYI: this problem occours on iOS platform also

**Comment by wf9a5m75** [comment]
Please share your project files on github

**Comment by wf9a5m75** [comment]
In your code, here is wrong.
```
map.addPolyline({
'points': [new plugin.google.maps.LatLng(LatLng[0], LatLng[1])],
```

You have to give at least two points.

**Comment by caereservices** [comment]
Before I upgrade to 2.0.11 ALL WORK CORRECTLY ... the problem is fromPointToLatLng ... look my first message please

**Comment by wf9a5m75** [comment]
It doesn't matter. You must specify two points at least.
Please share your project files on github if you want me to check your project.

**Comment by caereservices** [comment]
I can't share project .. is a commercial app ... the problem is in call of fromPointToLatLng ... I've tried to add another point on addPolyline but the error remain the same ...

**Comment by wf9a5m75** [comment]
You can't share your project files?, then I can't help you. Because there is no problem on my side. I'm so busy. I don't have enough time with hidden code.

**Comment by wf9a5m75** [comment]
At least, you can create a demo project that reproduce your issue. Or you can create private repository at BitBucket as free.

**Comment by caereservices** [comment]
Mah?? ... I'm surprised ... it's banal ... before (with 1.4.x) the code I posted working correctly ... now (with 2.0.11) NOT!! ... what hidden code?? what quiz??? ... the errors is autoesplicative ... I goggled it  ... but the problem is the call in BaseClass .. the code is yours not mine ... I simply signaled a problem ... the rest of plugin working correctly ...

**Comment by wf9a5m75** [comment]
` before (with 1.4.x) was worked`.

It it not related thing at all. v1.4 and v2.x are completely different code.
You need to provide project files if you want to help me.

The method works perfectly on my side. In that case, the problem might be in your code, or might be in plugin.
But I can detect it because you don't provide project files.

**Comment by caereservices** [comment]
Ok .. that answer have a sense ... can be another plugin that cause "interference" for example?

**Comment by wf9a5m75** [comment]
or timing, etc...

**Comment by caereservices** [comment]
function touchStartEvt(e) {
   e.preventDefault();
   var x = e.pageX - this.offsetLeft;
   var y = e.pageY - this.offsetTop;
   var div = document.getElementById("map_canvas");
   var lclMap = plugin.google.maps.Map.getMap(div);
   lclMap.fromPointToLatLng([x, y], function(LatLng) {
      lclMap.addPolyline({
         'points': [
            new plugin.google.maps.LatLng(LatLng[0], LatLng[1]),
            new plugin.google.maps.LatLng(LatLng[0], LatLng[1])
         ],
         'color' : '#c0392b',
         'width': 3
      }, function(polyline) {
         polyGlobal = polyline;
         div.addEventListener("touchmove", touchMoveEvt, true);
         div.addEventListener("touchend", touchEndEvt, true);
      });
   });
}
 
this code it's all you need ... on my app NOT WORK .. the error remain the same ...

**Comment by caereservices** [comment]
timing?? what?? I don't understand ... you mean setTimeout or Promise?? for example

**Comment by wf9a5m75** [comment]
No, timing of all in your app. Please create a demo project that reproduce your issue.
Then commit it to github. I'm really stressful just pasting snippet code.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
![android](https://user-images.githubusercontent.com/167831/32315059-d3856310-bf67-11e7-943f-8488b987da53.gif)
![ios](https://user-images.githubusercontent.com/167831/32315063-d9e468e6-bf67-11e7-96be-65089f2d3862.gif)
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/fromPointToLatLng.html


Is there any question?

**Comment by caereservices** [comment]
SOLVED ... you have deep modified code from 1.4.x and 2.x ... I have reviewed code in many points ... but .. one question ... because you don't see this?? 
'points': [new plugin.google.maps.LatLng(LatLng[0], LatLng[1])],
The error was here!!! ... 
Thanks
