### ISSUE TITLE
EXC_BAD_ACCESS in PluginCircle.m

### ISSUE THREAD

**Issue by eddragon** [mapsplugin/cordova-plugin-googlemaps#1846]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

branch-cordova-sdk 2.6.15 "branch-cordova-sdk"
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-firebase 0.1.24 "Google Firebase Plugin"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-deploy 0.6.7 "IonicDeploy"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"

**Current behavior:**
After the map is initialised a bunch of circles is added to it using:
this.earthMap.addCircle(circleOptions)

8/10 times everything works fine, but in the remaining cases the app crashes with an error displayed on the screenshot (see attachment).

**Expected behavior:**
No crash every time. :)

**Steps to reproduce:**
The issue is intermittent; it is unclear how exactly to reproduce it.
However, it seems to be caused by calling addCircle after the map is initialised, e.g.:

this.earthMap = this.googleMaps.create(mapNode, options);
this.earthMap.on(GoogleMapsEvent.MAP_READY).subscribe(
    () => {
        //addCircle called here
    }
);

**Screen capture or video record:**
![exc_bad_access](https://user-images.githubusercontent.com/26381489/32176909-cae373a2-bd80-11e7-8551-fd86858dca8b.png)

**Comment by wf9a5m75** [comment]
It seems your code has problem, probably the values you specified.
Please share your project files on github. I will check it.

**Comment by TheSquareDragon** [comment]
Sorry, can't share the project (trade secrets :)), but which values could possibly cause this?
There are only two arguments used on this line of code (position and radius); both of which remain static and work 80% of times without any issues.
You can see that I've supplied the radius of 15 and the redacted position is a correct decimal as well (e.g. 40.83669 and 14.23544) and these values don't change in my code.

**Comment by eddragon** [comment]
Sorry, can't share the project (trade secrets :)), but which values could possibly cause this?
There are only two arguments used on this line of code (position and radius); both of which remain static and work 80% of times without any issues.
You can see that I've supplied the radius of 15 and the redacted position is a correct decimal as well (e.g. 40.83669 and 14.23544) and these values don't change in my code.

**Comment by wf9a5m75** [comment]
You can't share your project files?, then I can't help you. Because there is no problem on my side. I'm so busy. Sorry, I don't have enough time playing quiz with hidden code.

**Comment by eddragon** [comment]
Your code is provided as an official google maps solution for the Ionic framework, used by thousands of developers online, and this is your response?
You may choose to deny the existence of this problem, but it doesn't mean that it will go away. There is an intermittent crash in creation of circles, regardless of whether you choose to believe in it.
If you decide to ignore my report and pretend that there is no issue with your project - that's your choice, I have no problem with that.
In any case, my report was a courtesy to you, not a privilege; I will be writing my own version of this plugin.
Thank you.
