### ISSUE TITLE
the stable version

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1851]
can you please give tell me what are the steps to install the stable version of this plugin.
because i always gets beta

**Comment by wf9a5m75** [comment]
```
$> cordova plugin add cordova-plugin-googlemaps
```

**Comment by wf9a5m75** [comment]
The beta is for the people who want to use the edge feature.

**Comment by bigbossmaher** [comment]
i getting a lot of D/map_0_1172801932000: (debug)action=loadPlugin containsKey=true
in the log , is it normal ?
