### ISSUE TITLE
Error while cleaning markers on ionic wrapper

### ISSUE THREAD

**Issue by jalescardoso** [mapsplugin/cordova-plugin-googlemaps#1852]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `this.map.clear();`) 

```
main.js:1122 TypeError: Cannot read property 'apply' of undefined
    at Marker.trigger (BaseClass.js:62)
    at Marker.remove (Marker.js:112)
    at clearObj (Map.js:268)
    at Map.clear (Map.js:277)
    at vendor.js:52912
    at new t (polyfills.js:3)
    at GoogleMap.clear (vendor.js:52911)
    at GoogleMap.value [as clear] (vendor.js:128009)
    at MapsPage.<anonymous> (main.js:1111)
    at step (main.js:1022)
```

**If you use `@ionic-native/google-maps`, please show me the package.json**

```
"@ionic-native/google-maps": "^4.3.2",
<plugin name="cordova-plugin-googlemaps" spec="^2.0.11">
```

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```

**Comment by Luttik** [comment]
I had a comparable issue when upgrading ionic from 4.2.1 to 4.3.3 `_this.get('_overlays')` on the GoogleMap object was null (This could stem from the same issue) maybe try to downgrade @ionic-native to 4.2.1

**Comment by fablrdigital** [comment]
I'm having this same issue. However, the latest version of Ionic appears to be 3.7.1, so not sure if @Luttik is referring to a different platform or if he is using a beta version?

Either way, the `_this.get('_overlays')` issue was fixed when I updated @ionic-native/google-maps to v5.5.1 and this issue highlighted by @jalescardoso appeared when I tried to clear my markers. I don't think that's a solution to the issue, unfortunately. but I'd love to hear one! :)

**Comment by Luttik** [comment]
@fablrdigital Yeah, sorry for not being clear. I was talking about ionic-native. More specifically @ionic-native/google-maps (but I believe they suggest to keep all ionic-native plugins at the same version).

**Comment by fablrdigital** [comment]
@Luttik That makes more sense and I should probably have put two and two together and figured it out. I guess downgrading would be the interim solution in this instance, then.

**Comment by wf9a5m75** [comment]
Please try to use #multiple_maps branch.

**Comment by wf9a5m75** [comment]
```
$> cordova plugin rm cordova-plugin-googlemaps

$> npm uninstall @ionic-native/core @ionic-native/google-maps

$> cordova plugin add  cordova-plugin-googlemaps@2.1.1 --variable API_KEY... --no-fetch

$> npm install @ionic-native/core@4.3.3 @ionic-native/google-maps@4.3.3

```

**Comment by jalescardoso** [comment]
Thanks @wf9a5m75 ! everything working here.
