### ISSUE TITLE
Disable autocenter on tap for markers

### ISSUE THREAD

**Issue by Jordan-Milner** [mapsplugin/cordova-plugin-googlemaps#1857]
**I'm submitting a ...**  (check one with "x")
[ x] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x") If you use old version, please try the latest version first
[x ] **2.1.0 (npm)**
[ ] **multiple_maps (github)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ x] **iOS**

I'm trying to disable autocenter for markers on tap, I don't see any options for this? 

Any advice?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md#disable-auto-pan
