### ISSUE TITLE
Creating Marker with opacity 0

### ISSUE THREAD

**Issue by TGMorais** [mapsplugin/cordova-plugin-googlemaps#1858]
Hello,

Thank you for work on this plugin, it really came in handy!
I ran into a very small issue, while trying to create a marker with opacity set to `0`.

**I'm submitting a ...**
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**
[x] 2.1.0 (github)
[] 2.0 (npm)

**If you choose 'problem or bug report', please select OS:**
[x] Android
[x] iOS

**Cordova plugin list**
```bash
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-googlemaps 2.1.0-beta-20171031-1849 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.0 "PushPlugin"
```

**Current behavior:**
Creating a new marker on the map with opacity set to `0` still adds it with opacity `1`

**Expected behavior:**
Marker opacity should be `0`

**Steps to reproduce**
```javascript
//...
const marker = {
   position: { lat: 51.458554, lng: -0.30211 },
   opacity: 0, //this is not working
};
map.addMarker(marker);
//...

```
---
When doing this, opacity is always `1` and I believe the reason why is because of this line:
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/921b961da04a21fc3407829d01c95c75a9563769/www/Common.js#L581

This will evaluate to `1` when `markerOptions.opacity` is `0`.
I worked around this by setting the opacity to something very low, like `0.001`.

I can submit a pull request, if you like.

Cheers!

**Comment by wf9a5m75** [comment]
I couldn't understand why do you need? `opacity:0` means user can not see the marker. So there is no necessary.

If you want to create a hidden marker, use `visible: false`.

**Comment by TGMorais** [comment]
@wf9a5m75 

Yeah, you're correct. Setting `visible: false` works. 
I used opacity because I'm porting code from the web and opacity can be animated there, that does not apply here.
Though, I still think it should work, as `0` is a valid value for `opacity`, even if it makes no sense.

Thank you.

**Comment by wf9a5m75** [comment]
Well, I think `opacity:0` does not make sense, but this code `parseFloat("" + markerOptions.opacity, 10) || ` is incorrect is make sense. I will fix it.
