### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by cuisineje** [mapsplugin/cordova-plugin-googlemaps#1860]
Hi there
I am getting this error when I create map and add markers to it.

Uncaught TypeError: Cannot read property 'apply' of undefined
    at Map.trigger (BaseClass.js:62)
    at Map.js:195

Here is my code snippet:
Am I doing anything wrong ?

```js
function displayRestaurantResultsOnMap(data) {
  //Get all the restaurants info and parse the lat and long
  var JERSEY = new plugin.google.maps.LatLng(49.217231, -2.140589); //Center of JERSEY
  $("#searchmap-text").html('Loading...');
  setTimeout(function() {
    var div = document.getElementById("searchmap_canvas_div");
    $('#searchmap_canvas_div').css('height', $(window).height() - $('#searchmap_canvas_div').offset().top);
    mapNew = plugin.google.maps.Map.getMap(div, {
      'camera': {
        'latLng': JERSEY,
        'zoom': 12
      }
    });
    mapNew.on(plugin.google.maps.event.MAP_READY, searchMapInit(data));
  }, 1000);

}

function searchMapInit(data) {
  mapNew.clear();
  mapNew.setVisible(true);
  mapNew.setCameraZoom(11);



  //	var mData =[];
  $.each(data, function(key, val) {
    if (val.latitude) {
      var point = new plugin.google.maps.LatLng(val.latitude, val.longitude);
      var entry = {
        'position': point,
        'title': val.restaurant_name,
        'icon': {
          'url': 'https://www.cuisine.je/assets/images/menu-icon.png'
        }
      };
      //mData.push(entry);
      dump("marker options" + entry);
      //Add marker
      dump(mapNew)
      mapNew.addMarker(entry, function(marker) {
        dump("Marker added " + marker);
        // Display the infoWindow
        marker.showInfoWindow();
        marker.setAnimation(plugin.google.maps.Animation.BOUNCE);

      });
    }
  });


  $("#searchmap-text").html('Loaded!!');
  addSearchMarkers(mData, function(markers) {
    markers[markers.length - 1].showInfoWindow();
    markers[markers.length - 1].setAnimation(plugin.google.maps.Animation.BOUNCE);
  });

}

function addSearchMarkers(data, callbac) {
  var markers = [];

  data.forEach(function(markerOptions) {
    dump(markerOptions);
    mapNew.addMarker(markerOptions, onMarkerAdd);
  });

  function onMarkerAdd(marker) {
    dump("Marker added " + marker);
    markers.push(marker);
    if (markers.length === data.length) {
      callbac(markers);
    }
  }
}
```

Thanks and cheers
Raj

**Comment by cuisineje** [comment]
Its throwing undefined variable at the Baseclass' trigger funciton
trigger: function(eventName) {
    if (!eventName) {
      return this;
    }

    if (!this[SUBSCRIPTIONS_FIELD][eventName]) {
      return this;
    }

    var listeners = this[SUBSCRIPTIONS_FIELD][eventName];
    var i = listeners.length;
    var args = Array.prototype.slice.call(arguments, 1);

    while (i--) {
      **listeners[i].apply(this, args);**
    }

    return this;
  },

**Comment by wf9a5m75** [comment]
```
mapNew.on(plugin.google.maps.event.MAP_READY, searchMapInit(data));
```
This is incorrect code.

Because you try to register the return value of `searchMapInit(data)` (and it's undefined).
That's why you get error.

If you want to pass initial data to `searchMapInit`, you need to do this

```
mapNew.on(plugin.google.maps.event.MAP_READY,function() {
  searchMapInit(data)
});
```

**Comment by cuisineje** [comment]
Thank you.. that error is gone but my map never displayed.. stays blank screen for me..

**Comment by wf9a5m75** [comment]
If you want to check your project by me, please share your project files on github or bitbucket.

**Comment by Sprechen** [comment]
Hi guys, I have the same problem. 
I use the map in two different pages in a Ionic 2 project. When I move from a page that uses the map plugin to another, I've got the following stack trace:

```
vendor.js:50225 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Marker.<anonymous> (vendor.js:50225)
    at Marker.callback (plugins/cordova-plugin-googlemaps/www/BaseClass.js:101)
    at Marker.trigger (plugins/cordova-plugin-googlemaps/www/BaseClass.js:62)
    at Marker.remove (plugins/cordova-plugin-googlemaps/www/Marker.js:112)
    at clearObj (plugins/cordova-plugin-googlemaps/www/Map.js:554)
    at Map.remove (plugins/cordova-plugin-googlemaps/www/Map.js:563)
    at plugins/cordova-plugin-googlemaps/www/googlemaps-cdv-plugin.js:401
    at Array.forEach (<anonymous>)
    at putHtmlElements (plugins/cordova-plugin-googlemaps/www/googlemaps-cdv-plugin.js:388)
    at HTMLDocument.resetTimer (plugins/cordova-plugin-googlemaps/www/googlemaps-cdv-plugin.js:485)
```

that is the same problem depicted by @cuisineje

**Comment by wf9a5m75** [comment]
If you want to check your project by me, please share your project files on github or bitbucket

**Comment by cuisineje** [comment]
I get a different error. I know Im doing something wrong.. can you have a quick look?
Uncaught TypeError: marker.getPosition is not a function
    at Marker.<anonymous> (app.js?ver=1.0:1658)
    at Marker.trigger (BaseClass.js:62)
    at Map._onMarkerEvent (Map.js:1460)
    at Map.nativeCallback (googlemaps-cdv-plugin.js:706)
    at Object.fireDocumentEvent (cordova.js:235)
    at <anonymous>:1:28


 map.addMarker({
					  'position': your_location ,
					  'title': marker_title,
					  'snippet': getTrans( "Press on marker 2 seconds to drag" ,'press_marker'),
					  'draggable': true
					}, function(marker) {

					   marker.showInfoWindow();
					   if(drag_marker_bounce==1){
					      marker.setAnimation(plugin.google.maps.Animation.BOUNCE);
					   }

					   drag_marker=marker;
					   drag_marker_bounce=2;

					   marker.on(plugin.google.maps.event.MARKER_DRAG_END, function(marker) {
							_**marker.getPosition(function(latLng) {**_
								 temp_result=explode(",", latLng.toUrlValue() );
								 /*alert(temp_result[0]);
								 alert(temp_result[1]);*/
								 drag_marker=marker;
								 callAjax("dragMarker","lat=" + temp_result[0] + "&lng="+ temp_result[1] );
							});
					   });

					});

**Comment by wf9a5m75** [comment]
@cuisineje If you want to check your project by me, please share your project files on github or bitbucket

**Comment by cuisineje** [comment]
I did before I posted

**Comment by wf9a5m75** [comment]
Ah, sorry. Misunderstood with other person. But your project is not Cordova project. I could not build it. Could you tell me how to build it?

**Comment by cuisineje** [comment]
it is cordova project

**Comment by cuisineje** [comment]
use phonegap

**Comment by wf9a5m75** [comment]
No. I tried the phonegap cli also, but it could not.

**Comment by wf9a5m75** [comment]
I think the main reason is you don't create a www folder

**Comment by cuisineje** [comment]
I just zip all files  and upload to phonegap.com for build

**Comment by wf9a5m75** [comment]
```
$ phonegap build
[phonegap] executing 'cordova build ' ...
Error: Current working directory is not a Cordova-based project.


```

**Comment by wf9a5m75** [comment]
In your code,

```
    marker.getPosition(function(latLng) { // <--
      ...
    });
```

is incorrect with the plugin v2.

```
var latLng = marker.getPosition();
```

is correct.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Marker/getPosition/README.md

**Comment by wf9a5m75** [comment]
ping

**Comment by cuisineje** [comment]
Hi thanks, now I got it correct.

**Comment by cuisineje** [comment]
marker.on(plugin.google.maps.event.MARKER_DRAG_END, onMarkerDragEnd);
					 
					   function onMarkerDragEnd() {
						// the first argument `latLng` is marker.getPosition() value.
						var marker = this;
						var temp_result=marker.getPosition() ;
						drag_marker = marker; //this and the next line is for my business code
						callAjax("dragMarker","lat=" + temp_result['lat'] + "&lng="+ temp_result['lng']);
					  }

**Comment by wf9a5m75** [comment]
Then, did you solve your problem?

**Comment by cuisineje** [comment]
yes sir.. thanks

**Comment by wf9a5m75** [comment]
Ok, I close this thread. Thank you for using this maps plugin.

---

By the way, I appreciate if you support for this project. 
This is not mandatory asking, but I appreciate if you donate some tip because I spend my private time.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by cuisineje** [comment]
will do
