### ISSUE TITLE
Is navigation mode possible?

### ISSUE THREAD

**Issue by ThalesMatoso** [mapsplugin/cordova-plugin-googlemaps#1861]
**I'm submitting a ...**  (check one with "x")
[X] question
[ ] any problem or bug report
[ ] feature request

Wow, what's up? I strolled through the issues and the closest I got to what I
 #1803 

When you put the videos, making the marker move to the next point, my situation I want to get as close as possible to a navigation in google maps for driver.

Videos --> https://www.youtube.com/watch?v=CXEBBYCulU0&feature=youtu.be
Videos --> https://www.youtube.com/watch?v=e1CGw-a0kFk&feature=youtu.be

Is it possible to do this with cordova-plugin-maps or at least the possibility of keeping the marker fixed and the map rotating around it according to the route?

**Comment by wf9a5m75** [comment]
This plugin does not have any navigation mode, even original Google Maps APIs do not have it.
You have to manage camera position, device location, and marker position by yourself.

**Comment by ThalesMatoso** [comment]
Is there any sample code for this?

**Comment by wf9a5m75** [comment]
nop.

**Comment by ThalesMatoso** [comment]
Ok, thanks, I'm scanning the internet and I'm going to try to get as close as possible and put the code here and most congratulations for the very practical plugin.
