### ISSUE TITLE
Error when leaving view using map.remove()

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1862]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x") If you use old version, please try the latest version first
[X] **2.1.0 (npm)**
[X] **multiple_maps (github)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[X] **iOS**

**cordova information:**

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-googlemaps 2.1.2-beta-20171102-2253 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
I call `this.map.remove()` when leaving a page with the map, then I go back to this page
=> I get the error `undefined is not an object (evaluating 'MAPS[mapId].getDiv') `.

It is related to this commit: https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/0af78b0bd2aadaeaeb1ba8fb99e51b7a60d76e4b

**Steps to reproduce:**
Use the repo below, the app will load on the Home Page.
Click on the About Page then go back to the Home Page, the error should appear.

https://github.com/antoine92190/ionic-map

**Comment by wf9a5m75** [comment]
Thanks, I will check it later

**Comment by wf9a5m75** [comment]
Fixed.

**Comment by antoine92190** [comment]
Thanks!
