### ISSUE TITLE
Ionic latest release map is not working with tabs and toolbar

### ISSUE THREAD

**Issue by pavel-kurnosov** [mapsplugin/cordova-plugin-googlemaps#1864]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x") If you use old version, please try the latest version first
[x] **2.1.1 (npm)**
[ ] **multiple_maps (github)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
when trying to move map - it is trigger ionic view scroll instead of map.

**Expected behavior:**
SHould move map instead of scroll view on top of it.

**Steps to reproduce:**
[Archive.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1445586/Archive.zip)

**Comment by wf9a5m75** [comment]
Thank you Paul. I will check it later.

Could you update the sample code to github instead of zip code?
You can remove the repository later when the issue thread is closed.

Because reproduce steps takes my time, and I'm busy. I do the debugging during my private time such as short break of work, or lunch time.
That's why I would like to save my time as much as possible.

Git repository can keep the status as you created everything.
I just clone the repository, (install the modules), and run it.
It saves my time a lot.

**Comment by pavel-kurnosov** [comment]
Hi, Yes, np. 
https://github.com/pavel-kurnosov/gmaps-ionic

**Comment by JeffreyJamesAttenti** [comment]
Having same issue with Ionic v1. Press events don't seem to be propagating to the map. I can't scroll and can't press markers.

**Comment by wf9a5m75** [comment]
Fixed. Please reinstall the plugin from multiple_maps branch.

**Comment by JeffreyJamesAttenti** [comment]
Would the same bug exist in Android? I am experiencing it in Android and I see that the fix is native code for iOS.

**Comment by wf9a5m75** [comment]
Really? I checked the code of Android, and the bug should not be related with Android.

**Comment by JeffreyJamesAttenti** [comment]
Yes I upgraded to latest plugin version today and tried it on Android first but haven't tried iOS. I can't scroll the map or press on markers. I even tried adding a console.log() to event handlers in javascript side and those don't fire.

**Comment by wf9a5m75** [comment]
@pavel-kurnosov 's project (build with https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/94c6665bed1369a4325a3c2ce86e5414e11aa114)

![1864](https://user-images.githubusercontent.com/167831/32459901-ece57e0e-c2e5-11e7-9475-2f444ddf0d64.gif)

**Comment by wf9a5m75** [comment]
@JeffreyJamesAttenti If you want to check your project, please share your project files on github (or other git repository services).

**Comment by JeffreyJamesAttenti** [comment]
Ok I'll try to debug my issue and open up a new issue if I find more information

**Comment by pavel-kurnosov** [comment]
Awesome ! Yes, it is fixed now. In this case Android worked in devices that we have.

**Comment by wf9a5m75** [comment]
Yeah. The problem was just casting inside the iOS native code.
In the past the plugin generates int values for depth calculation, and now it's double.
I forgot to update the iOS code.
