### ISSUE TITLE
Map doesn't receive gesture events when in Ionic modal view

### ISSUE THREAD

**Issue by JeffreyJamesAttenti** [mapsplugin/cordova-plugin-googlemaps#1869]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[X] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

![screencast-genymotion-2017-11-08_13 21 12 223 2](https://user-images.githubusercontent.com/942571/32567326-eec82dee-c488-11e7-9284-5e5e70648eeb.gif)

**Related code, data or error log (please format your code or data):**

[Repo with Issue Demo](https://github.com/JeffreyJamesAttenti/MapPluginIssues)

**Comment by wf9a5m75** [comment]
This plugin does not work on any dialog box. Because the map is placed under the browser.

**Comment by wf9a5m75** [comment]
![](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/raw/master/v1.4.0/class/Map/mechanism.png)

**Comment by JeffreyJamesAttenti** [comment]
Yes I understand but it was able to work before this version. I hide everything underneath the modal in order to make it work. It's hacky but works.

I added a branch to the demo repo where I'm using plugin v2.0.1 and it still works: [Branch using v2.0.1](https://github.com/JeffreyJamesAttenti/MapPluginIssues/tree/working_with_map_plugin_2.0.1). The latest plugin version, 2.1.1, does not work.

Here's an animated gif that illustrates it working:

![screencast-genymotion-2017-11-08_13 49 30 388](https://user-images.githubusercontent.com/942571/32568392-1b03ea1c-c48c-11e7-86ea-e4452587a96b.gif)

**Comment by wf9a5m75** [comment]
Ok, I will check it later.

**Comment by wf9a5m75** [comment]
I haven't tested your project, but try to set `z-index: 9999` to the map div.

**Comment by wf9a5m75** [comment]
And also the `multiple_maps` branch.

**Comment by JeffreyJamesAttenti** [comment]
Masashi, I set the z-index to 9999 and that allowed me to drag/scroll the map but pressing the marker would not open the html info window.

**Comment by wf9a5m75** [comment]
@JeffreyJamesAttenti Did you try the `multiple_maps` branch code?

I just installed the plugin from multiple_maps branch, and run your project on my Android.
But no problem at all.
![1869](https://user-images.githubusercontent.com/167831/32587544-d927fa7a-c4bd-11e7-87c3-7e8951e88f9e.gif)

**Comment by JeffreyJamesAttenti** [comment]
It works with multiple_maps but that sounds like a developmental feature branch. Would this fix make it into the stable version for next release?

Also, the html info still does not work with the multiple_maps branch. Should I open a new issue for that or do you want to do that fix against this issue?

**Comment by wf9a5m75** [comment]
>Also, the html info still does not work with the multiple_maps branch.

As far as your project, it seems fine.
And I haven't any problem with HtmlInfoWindow at all.

**Comment by JeffreyJamesAttenti** [comment]
Sorry, I meant to include a gif with the behavior. FYI, the android OS version is 4.4.4. That might make a difference.

In the video, you can see that it centers on the marker after pressing but the html info window doesn't display.

![screencast-genymotion-2017-11-09_10 11 12 442](https://user-images.githubusercontent.com/942571/32623865-85fc5434-c555-11e7-939f-ea638335d2e0.gif)

**Comment by wf9a5m75** [comment]
Thank you for letting me know. Fixed. Please reinstall the plugin from the multiple_maps branch.

(Screen recorded on Android 4.4.4)
![1869](https://user-images.githubusercontent.com/167831/32628846-05ce5f18-c54c-11e7-89a4-750f00778b85.gif)

**Comment by JeffreyJamesAttenti** [comment]
That fixed it! Thank you for all of your hard work, I appreciate it very much!

**Comment by wf9a5m75** [comment]
You are welcome. The fixed code will be released in the next npm update.

By the way, I appreciate if you support for this project. 
This is not mandatory asking, but I appreciate if you donate some tip because I spend my private time.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
