### ISSUE TITLE
index.js:483 GoogleMaps [deprecated] Please use GoogleMaps.create()... Please guide me to solve this issue.

### ISSUE THREAD

**Issue by VigneshSAN** [mapsplugin/cordova-plugin-googlemaps#1873]
index.js:483 GoogleMaps [deprecated] Please use GoogleMaps.create().

The above mentioned is my Error. Kindly help me to solve the issue.

**Comment by wf9a5m75** [comment]
As of `@ionic-native/google-maps` v4.4.0, the way of creating a map is changed.
Please read the release notes

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/ionic-googlemaps-4.4.0/README.md

**Comment by Felipe-Lima** [comment]
Changed like show on link https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/ionic-googlemaps-4.4.0/README.md

But still not working. Returning the same message "GoogleMaps [deprecated] Please use GoogleMaps.create()"

Help please!

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/ionic-googlemaps-demo/blob/master/src/pages/map/clear/clear.ts

**Comment by wf9a5m75** [comment]
At least you should share your project files on github if you ask to someone to help

**Comment by mah14** [comment]
just do  it:
change this code
this.googleMaps.create()  
to this
GoogleMaps.create()

**Comment by Felipe-Lima** [comment]
This is my Home.ts code

import { Component } from '@angular/core';
import { IonicPage } from 'ionic-angular';
import { Platform, NavController } from 'ionic-angular';

// Native Components
import { GoogleMaps, GoogleMap, GoogleMapsEvent, GoogleMapOptions, VisibleRegion, ILatLng, CameraPosition, MarkerOptions, Marker } from '@ionic-native/google-maps';

@IonicPage()
@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
})

export class HomePage {
  map: GoogleMap;

  constructor(public navCtrl: NavController, private platform: Platform, public toastCtrl: ToastController) { }
    /*platform.ready().then(() => {
      this.loadMap();
    });*/
    ionViewDidLoad() {
      this.loadMap();
     }

  loadMap() {
    
        let mapOptions: GoogleMapOptions = {
          camera: {
            target: {
              lat: 43.0741904,
              lng: -89.3809802
            },
            zoom: 18,
            tilt: 30
          }
        };
    
          this.map = GoogleMaps.create('map_canvas');

          this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
               console.log("Map is ready to use.");
    
            this.map.addMarker({
                title: 'Ionic',
                icon: 'blue',
                animation: 'DROP',
                position: {
                  lat: 43.0741904,
                  lng: -89.3809802
                }
              })
              .then(marker => {
                marker.on(GoogleMapsEvent.MARKER_CLICK)
                  .subscribe(() => {
                    alert('clicked');
                  });
              });
    
          });
      }
}

**Comment by Motoralfa** [comment]
i have the same issue but when i change
`this.googleMaps.create()` to `GoogleMaps.create()`
the method dont work... can somebody help me please :( 
![captura](https://user-images.githubusercontent.com/10781270/33444818-07767f78-d5da-11e7-803a-7768056501a3.PNG)

**Comment by Felipe-Lima** [comment]
Motoralfa, what worked for me was:

1 - Remove all google map plugins
2 - Reinstall all again
3 - Reboot the PC

Solve the error with "this.googleMaps.create()", but now I am facing a totally new problem, a blanck screen appears when I start the map, but no error occurr...

**Comment by leron8** [comment]
@Felipe-Lima that also happened to me, make sure you have your styles:

Home.ts:
`page-home{
	 
	    #map_canvas {
	        height: 100%;
	    }
}`

In your html:
```
<div id="map_canvas">
  </div>
```
