### ISSUE TITLE
Full screen button

### ISSUE THREAD

**Issue by dunice-boldirev** [mapsplugin/cordova-plugin-googlemaps#1877]
Hello! 
I read documentation and can not find way for add "full screen" control.
I need add "full screen" button like in a screenshot below. Does plugin supported this? If so, could you you help me and tell how I can do this? 

![2017-11-07 15 03 52](https://user-images.githubusercontent.com/11989481/32724916-2719ce10-c884-11e7-8324-4f1230f49a4c.png)

Thank you!

**Comment by wf9a5m75** [comment]
Not supported

**Comment by wf9a5m75** [comment]
This plugin displays the native map view from under the browser.
For the reason, the map can not be displayed as full screen, except you hide all html elements of outside of map divs.
