### ISSUE TITLE
 Rotation marker or navigation mode

### ISSUE THREAD

**Issue by renanmoraes** [mapsplugin/cordova-plugin-googlemaps#1878]
*I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**
```
cordova-background-geolocation-lt 2.8.5 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

```

**Current behavior:**

I need to do one of two things with my map.

1 - Place the map in navigation mode (GPS Style)

2 - Rotate the icon according to polyline direction

I would like to know if there is a way to do this with maps, and if this is a separate plugin or something of the maps themselves ..

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md#create-a-flat-marker

**Comment by renanmoraes** [comment]
It would not be quite what I need, the real case is this of the video, I need my marker to follow the polyline as the [https://www.youtube.com/watch?v=JIs4kLZ8qQI](rotate marker polilyne)

**Comment by wf9a5m75** [comment]
You need to create `flat marker` or `own icon`, then you need to rotate it by yourself.
At least the marker has `setRotation()` method.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Marker/setRotation/README.md

**Comment by renanmoraes** [comment]
Thanks for the moment solved my problem with the marker now I need to solve with the maps. I'll create another inssue

**Comment by wf9a5m75** [comment]
flat marker
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Marker/setFlat/README.md

calculate angle from A to B
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/utilities/geometry/spherical/computeHeading/README.md

**Comment by UlisesCecaDT** [comment]
Hi @renanmoraes , have you been able to rotate the map? how?
