### ISSUE TITLE
Map not clickable inside ion-slide

### ISSUE THREAD

**Issue by macklus** [mapsplugin/cordova-plugin-googlemaps#1882]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
cordova.plugins.diagnostic 3.7.1 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "4.3.2",
"@ionic-native/google-maps": "^4.3.3",
```

**Current behavior:**
When i put a map inside a ion-slide, it shows but i cant click on it, resize, etc

**Expected behavior:**
map should work as normal

**Related code, data or error log (please format your code or data):**

```
<ion-content padding>
    <ion-slides #addPointSlider>
        <ion-slide>
            <div id="infoText">
                <p><i class="fa fa-info" aria-hidden="true"></i> Localiza el punto en el mapa y pulsa "Siguiente"</p>    
            </div>
            <div id="mapDiv">
                <div id="mapAdd" style="width:100%; height:100%;"></div>
            </div>
        </ion-slide>

```

**Comment by wf9a5m75** [comment]
Did you try the `multiple_maps` branch version?

**Comment by wf9a5m75** [comment]
Even if you try the `multiple_maps` branch version, but it does not work, please create a demo project, and share it on github. I will check it.

**Comment by wf9a5m75** [comment]
ping

**Comment by macklus** [comment]
I create that demo project and update this. Thanks !

**Comment by wf9a5m75** [comment]
Thank you, but I can't see any link.

**Comment by wf9a5m75** [comment]
ping

**Comment by macklus** [comment]
Sorry, i dont explain fine.
What i want to say was:
"I update that ticket when i create the demo project". Im out know, so in about 8-9 hours i can do it

sorry about the delay

**Comment by macklus** [comment]
After some test, everything seems to work fine with development version.

Just for testing, i made a testing repository (https://github.com/macklus/ionic3-examples) with two branchs:

- google-maps-slider
- google-maps-develop-slider

You can use **ionic cordova prepare** to install everything (i install a test google console keys).

I close this ticket, thank you for everything!

**Comment by wf9a5m75** [comment]
Thank you for letting me know. I confirmed this issue has been resolved with your example.
