### ISSUE TITLE
plugin.google.maps.external.launchNavigation no External-Service class in v2

### ISSUE THREAD

**Issue by shrijan** [mapsplugin/cordova-plugin-googlemaps#1883]
**I'm submitting a ...**  (check one with "x")
[x ] question
[ ] any problem or bug report
[x ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-open-native-settings 1.4.1 "Native settings"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-badge 0.8.5 "Badge"
cordova-plugin-cache-clear 1.3.7 "Cordova Cache Clear"
cordova-plugin-calendar 4.6.0 "Calendar"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoapod-support 1.3.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-firebase 0.1.24 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-local-notifications 0.9.0-beta.0 "LocalNotification"
cordova-plugin-nativeclicksound 0.0.3 "Native Click Sound"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova.plugins.diagnostic 3.6.7 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

plugin.google.maps.external.launchNavigation doesn't work on google map version 2. I dont see the external service class. Is it gonna available soon?

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```

```

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/ReleaseNotes/v2.1.0#no-longer-external-service
