### ISSUE TITLE
Ionic frozen markers: clear() and addMarker() many times

### ISSUE THREAD

**Issue by codingandgo** [mapsplugin/cordova-plugin-googlemaps#1884]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
ionic-native/google-maps: "^4.4.0"

**Current behavior:**
Maps with 30 markers. 
this.map.clear() and then this.map.addMarker(opt) to update markers.
This works well.
But repeating this operation 10 times, markers remain frozen.

**Related code, data or error log (please format your code or data):**

```
 this.map.clear().then(() => {
    this.addMarkers(data); // this.map.addMarker(opt)
    });
    }}
```

**Comment by wf9a5m75** [comment]
Please share your project files on github. Otherwise, I can not give advices anything.

**Comment by wf9a5m75** [comment]
ping

**Comment by codingandgo** [comment]
This is the code:
```
...
this.map.clear().then(() => {
    for(i= 0; i< data.length; i++){
             let opt: opt= {
                  position: MarkerOptions,
                 ..}
       let marker = this.map.addMarker(opt)
                  .then((marker: Marker) => {...});
      }
    });
...
```
with ionic-native/google-maps 4.0.0 
I have this problem on Android Nougat, but in other versions of Android everything works.

Thank you

**Comment by wf9a5m75** [comment]
No... please share your project files (or create a demo project) on github.
Because I tested such a code so many times, and no problem.
And ionic is complicated than regular JS project. There are many factors.
Please share your project files (or create a demo project)  on github (or other services, such as bitbucket).

You hide `cordova-plugin-googlemaps` version, but I guess you use old version.
Because you use ` ionic-native/google-maps 4.0.0`. It's too old.
Please reinstall the latest plugins before asking.

**Comment by wf9a5m75** [comment]
No cooperation, no help. You cooperation, you get help.

**Comment by wf9a5m75** [comment]
By the way, in your code

```
let marker = this.map.addMarker(opt)
                  .then((marker: Marker) => {...});
```

This code is wrong. The `addMaker` method returns just a promise, not marker object.

**Comment by wf9a5m75** [comment]
ping

**Comment by codingandgo** [comment]
Fixed with addMarkerCluster.
Thanks for your help.
