### ISSUE TITLE
[Question] Quality loss of PNG 24 bits in Android

### ISSUE THREAD

**Issue by thiphariel** [mapsplugin/cordova-plugin-googlemaps#1886]
Hi.

Do you have any advice on this issue : 

I have a custom tileOverlay exported in PNG 24 bits and it looks great on iOS, but heavily pixelised on Android.

Look by yourself on these screenshots (sorry for the size difference) : 

- iOS
![img_0739](https://user-images.githubusercontent.com/3125705/32790027-8aa023a6-c95d-11e7-88ce-c1710f11a2ab.PNG)

- Android
![capture d ecran 2017-11-14 a 16 58 45](https://user-images.githubusercontent.com/3125705/32790040-9040adb2-c95d-11e7-9b3a-48a7485c2c42.png)

Look at the shadow on the middle, on iOS it's good, but on Android.. It's like the image has been convert to 8 bits or something.

Did you ever face to this problem ?

Thanks

**Comment by wf9a5m75** [comment]
I recommend you use 32bit png. This plugin just displays your image file.

**Comment by thiphariel** [comment]
Hum, but why is there a difference between the 2 systems ? If I open the same tile image on a browser or something, it look great. It's just pixelised on an Android phone

**Comment by wf9a5m75** [comment]
Please ask to Google.

**Comment by wf9a5m75** [comment]
https://stackoverflow.com/a/27583159/697856

**Comment by thiphariel** [comment]
I'll try that one

**Comment by thiphariel** [comment]
Hi.

I come back here with some news.

You told me that the plugin take the image and displays it on the screen right in, but look at this screenshot, on the left, the Android ionic map with the plugin and my custom tileOverlay, on the right, the exact same PNG file display on Chrome (Android) : 

![screenshot_1510927604](https://user-images.githubusercontent.com/3125705/32951331-cf516052-cba9-11e7-8d38-d6071878f238.png)

How can it be so different ? For info, it's a 512px tile, because the 256's one are heavily blurry.

And what exactly do this func ? 
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/PluginTileProvider.java#L393

Thanks

**Comment by wf9a5m75** [comment]
If you have a problem, you should share your project files on GitHub. Otherwise, please debug by yourself.

**Comment by thiphariel** [comment]
Don't be rude dude. I'm just asking you some questions.

And I can't share the project, the tiles are built for a client, so I can't share them.

If you don't want people asking you question, you should stop sharing your stuff on github.

Thanks anyway, I'll try by myself
