### ISSUE TITLE
Move map through marker

### ISSUE THREAD

**Issue by renanmoraes** [mapsplugin/cordova-plugin-googlemaps#1887]
**I'm submitting a ...** 
[x] question
[ ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:** 
[x] **Android**
[ ] **iOS**

**cordova information:**
```
cordova-background-geolocation-lt 2.8.5 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Expected behavior:**
I need to move the map like the video of the example, in git comrade has until the example however it is related to the native android and I am using ionic 3.

My doubts are, in your plugin can I make this effect? And the other is what could be the logic to do?

It is not clear in my mind the functioning, for example, when to turn, which event callback I need to hear.

**Screen capture or video record:**
[q](https://www.youtube.com/watch?v=uGjYqHSILxM)

**Comment by wf9a5m75** [comment]
If you want to create like video, you need to manage (1) the marker position and (2) camera position.

(1) `marker.setPosition()`

(2) `map.animateCamera()`

There is `no feature` such as `followCamera(marker)`, and I have no plan to create such a feature.

If you donate $1000USD,  I will consider that. But it's not so difficult. You should try that.
(Please try something before asking)
