### ISSUE TITLE
Fund raise: support Google Places API

### ISSUE THREAD

**Issue by wf9a5m75** [mapsplugin/cordova-plugin-googlemaps#1888]
One of high rated feature request is `supporting Google Places API`.

![screen shot 2017-11-14 at 11 54 21 am](https://user-images.githubusercontent.com/167831/32801669-9688ebd8-c932-11e7-9eaa-4893a7a933a4.png)

https://developers.google.com/places/

The places API allows you to get the place information, not just latitude/longitude, but also place name, phone number ... etc.

**Places Picker**
![](https://user-images.githubusercontent.com/167831/32801707-b285ff7e-c932-11e7-819e-1b26a4965cfb.png)

**Auto complete**
![](https://user-images.githubusercontent.com/167831/32801727-be2996b0-c932-11e7-942a-b5bcacf9b8e5.png)

**Place details**
![](https://user-images.githubusercontent.com/167831/32801743-c95f7f90-c932-11e7-9475-219e3fe9304f.png)

------------

I can implement the features for both Android and iOS, but it's kind of heavy task.
It means I need to work a lot in my private time.

If you want to implement this feature for this plugin, please donate to this project.
I will start development when the amount is reached to $2,000 USD.

Google Places API has many features. So I will **create another plugin** for this feature.
That's why $2,000USD for this time. (Generally $1,000USD for one feature implementation)

Since creating new features is stressful work, spending lots of my time, bug fixing...etc.
I appreciate for your understanding, and for your kindness.

------------

The benefits of donors are:
- access to the beta test features in advance
  (I will notify you when I am ready. )

- support your project in private
  (during the beta test, and only for the feature)

- feature request for the places api

------------

Fundraise amount: $2,000 USD

Minimum donation amount: $100 USD per person (with private support)

From $50 to $100USD, I will let you know the work progress, and access to the beta test in last minutes.
(* The word `in last minutes` means pre-release version. It is not released yet, but planing very soon)

Less $50 USD, I appreciate for your donation.

------------

## Paypal
(Please write a memo **for places api** when you donate some amount)

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=cordova%2dgooglemaps%2dplugin&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted)

## Bitcoin
(Please let me know when you donate some Bitcoin. I'm not familiar with Bitcoin actually, so I don't want to miss you)

3LyVAfANZwcitEEnFbsHup3mDJfuqp8QFb

**Comment by wf9a5m75** [comment]
If you have open question, please post here on this thread.

**Comment by wf9a5m75** [comment]
Thank you for your donation, Saud.

**Comment by battika** [comment]
@wf9a5m75 are you planning to create Ionic Native wrapper too?

**Comment by wf9a5m75** [comment]
@battika I will determine that after I create the JS version.
If I feel the JS version is too easy, I will create the native wrapper as well without no additional fundraise.
Otherwise, I might consider another fundraise.

**Comment by wf9a5m75** [comment]
I have been considering another option that `paid plugin` for this development instead of fundraise.
Since the most people are fine with the maps plugin, but some people want to use additional `places` feature.

Thus, pay additional cost for the people who want to use it. That's another fear style I think.
Of course, I will issue the token for whom pay during this fundraise. These people do not need additional payment.

**Comment by wf9a5m75** [comment]
It looks line nobody is interested in the places API except Saud.

**Comment by wf9a5m75** [comment]
Since the fundraise is not reached to the amount, I put back this fundraise at once. I refund the amount to donors.
