### ISSUE TITLE
[bug] BUG: Loading Map again crashes with message that map already exists.

### ISSUE THREAD

**Issue by ananmelkonyan** [mapsplugin/cordova-plugin-googlemaps#1890]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ x ] **Android**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.6.8 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.2.1 "OneSignal Push Notifications"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
 "@ionic-native/core": "^4.4.0",
 "@ionic-native/diagnostic": "^4.4.0",
 "@ionic-native/geolocation": "^4.4.0",
 "@ionic-native/google-maps": "^4.4.0",
```
**Current behavior:**

When loading map page from menu it crashes , with error message

```
console.error: GoogleMaps DIV[__pluginMapId='map_0_1171669735998'] has already map.
```

**Expected behavior:**

It should load map

**Screen capture or video record:**

![capture](https://user-images.githubusercontent.com/31433870/32825262-c878b7f6-c9fd-11e7-8dee-b55718e216e0.gif)

**Related code, data or error log (please format your code or data):**

*Menu Item load map code*

```
this.nav.setRoot(MainPage);
```

*Variables*
```
 map: GoogleMap;
 mapElement: HTMLElement;
 map_id = "map";
```

*Code for creating map*

```
 this.mapElement = document.getElementById(this.map_id);
      /*
      * @comment: Initial configuration for map pointing central brunch
      * */
      let mapOptions: GoogleMapOptions = {
        controls: {
          compass: false,
          myLocationButton: false,
          indoorPicker: false,
          mapToolbar: false
        },
        camera: {
          target: {
            lat: 40.1817318,
            lng: 44.5122556
          },
          zoom: 8
        },
        styles: [{
          stylers: [{
            saturation: -100
          }]
        }]
      };
      /*
      * @comment: Creating google map
      * */
      if (!this.map) {

        this.map = GoogleMaps.create(this.mapElement, mapOptions);
      }
```

**Suggest**

Create static method to destroy map object or resset

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub. I will check it tomorrow.

**Comment by ananmelkonyan** [comment]
I will create demo project and share with you thanks.

**Comment by ananmelkonyan** [comment]
Got failing loading in a new project the map

**Comment by wf9a5m75** [comment]
what do you mean?

**Comment by ananmelkonyan** [comment]
It is not loading map on new project in the latest ionic, i will try to do some research upon this bug, when project ready i will post it here

**Comment by wf9a5m75** [comment]
If you share the project, I will check it.

**Comment by ananmelkonyan** [comment]
@wf9a5m75 https://github.com/ananmelkonyan/test_map

**Comment by wf9a5m75** [comment]
https://docs.google.com/presentation/d/1zlkmoSY4AzDJc_P4IqWLnzct41IqHyzGkLeyhlAxMDE/edit#slide=id.g292c767148_0_0

**Comment by ananmelkonyan** [comment]
@wf9a5m75  Appreciate this thanks but the problem not in device ready, i posted gif that shows what happening,
When it opening map first time is ok, second time on page load it says `console.error: GoogleMaps DIV[__pluginMapId='map_0_1171669735998'] has already map.`

**Comment by wf9a5m75** [comment]
> console.error: GoogleMaps DIV[__pluginMapId='map_0_1171669735998'] has already map.

This means you tried to create a map to the same map div.
`GoogleMaps.create();` means create an instance.
So if you use Google Maps JavaScript API v3, do you create a map for the same div?

**Comment by ananmelkonyan** [comment]
Yes, because when you reload page it cant get old initiated map

**Comment by wf9a5m75** [comment]
I'm not sure how use this plugin in your project, but let's assumes `tab` template of ionic.

When you change the tab page from A to B, ionic **keep the DOM tree of page A**. The map div is not removed.

**Comment by ananmelkonyan** [comment]
so how can get initiated map and assign it to this.map

**Comment by wf9a5m75** [comment]
You need to create own provider. Or remove the map when you leave the page.

**Comment by ananmelkonyan** [comment]
and how to remove map?

**Comment by wf9a5m75** [comment]
`map.remove()` (Please read the document first)

**Comment by ananmelkonyan** [comment]
i used that not working actually

**Comment by ananmelkonyan** [comment]
throws me same error

**Comment by wf9a5m75** [comment]
If you want to help you by me, please share your **actual project files**. Otherwise, please debug by yourself.

**Comment by ananmelkonyan** [comment]
@wf9a5m75 just a moment please i need confirmation from PM

**Comment by wf9a5m75** [comment]
BTW, bitbucket.org or gitlub provides free private git repository.
I'm not interested in your project code at all.
So I don't leak your code.

**Comment by ananmelkonyan** [comment]
@watacoz3 I trust you its just company policy, can you give me your username at bitbucket please thanks.

**Comment by wf9a5m75** [comment]
wf9a5m75

**Comment by ananmelkonyan** [comment]
thanks

**Comment by wf9a5m75** [comment]
If you need to sign your company NDA, please send it to my e-mail address (see my profile page)

**Comment by ananmelkonyan** [comment]
Thanks very much for your help, i'l ping you when share to bitbucket.

**Comment by ananmelkonyan** [comment]
You are doing great work

**Comment by ananmelkonyan** [comment]
@watacoz3 Added to bitbucket and added your profile for editing

**Comment by ananmelkonyan** [comment]
Please see src/pages/main/main.ts

**Comment by wf9a5m75** [comment]
Did you invite me or someone elese?

**Comment by wf9a5m75** [comment]
Found your repo. I will check it later.

**Comment by wf9a5m75** [comment]
It seems you forgot to insert a double quotation after the API key for iOS.

(This url is not openable except your team and me, because of private repo)
https://bitbucket.org/francocoro4/inmokey-ionic/src/ef480d2d7ae0da2fc80670073f17975ff9ce7f6d/config.xml?at=master&fileviewer=file-view-default#config.xml-96

```xml
    <plugin name="cordova-plugin-googlemaps" spec="^2.0.11">
        <variable name="API_KEY_FOR_ANDROID" value="(your api key)" />
        <variable name="API_KEY_FOR_IOS" value="(your api key) --no-fetch" />
    </plugin>
```

**Comment by wf9a5m75** [comment]
Please tell me where I can find the test login ID/PW in your repo.

**Comment by wf9a5m75** [comment]
The app did not display the map when I built and run your project files first time.
I found the error message "You tried to use Google Maps plugin but not installed" or something like that (I forgot to write down the memo), even the plugin is installed.

Then I reinstall the plugin, and it worked.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="...." --variable API_KEY_FOR_IOS="...."

$> ionic cordova run android
```

<img src="https://user-images.githubusercontent.com/167831/32925335-42c8dfc4-caf6-11e7-8ba5-d98d3a84dc93.png">

**Comment by wf9a5m75** [comment]
Okay, I got the reason of `GoogleMaps DIV[__pluginMapId='map_0_1171669735998'] has already map.`.

Because you write your code like this:
```
this.mapElement = document.getElementById('map-main-page');
if (!this.map) {
  this.map = GoogleMaps.create(this.mapElement, mapOptions);
}
```

The ionic framework uses `fade-in` and `fade-out` when you change the pages, even accessing to the same page.
In your case, for changing language, the ionic regenerates new DOM tree.

So if there is the same div tag in pageA(Eng page) and pageB(Rus page), can you image what happens?

```
this.mapElement = document.getElementById('map-main-page');
```

This code returns the div of pageA, because it is still remained during the fading out.

That's why I recommend to use this way.

```
if (!this.map) {
  this.map = GoogleMaps.create('map-main-page', mapOptions);
}
```

Since `@ionic-native/google-maps@4.3.0`, the wrapper plugin waits the specified ID element is loaded. This prevents this problem.

![issue_1890](https://user-images.githubusercontent.com/167831/32926081-0e155b82-cafa-11e7-97eb-5aa52c400b04.gif)

**Comment by ananmelkonyan** [comment]
@wf9a5m75 Thanks you very much, you helped a lot thanks

**Comment by wf9a5m75** [comment]
You are welcome.

**Comment by ananmelkonyan** [comment]
@wf9a5m75 Can you please give me grade.build content because i get blank map with only google  logo

**Comment by wf9a5m75** [comment]
That's your problem
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by ananmelkonyan** [comment]
Nice thanks, very much.

**Comment by ananmelkonyan** [comment]
@wf9a5m75 Dear Masashi its not working for ios, can you please provide more info.

**Comment by ananmelkonyan** [comment]
@wf9a5m75 i added repo tht can help you. named ios_map

**Comment by wf9a5m75** [comment]
I just run your project files. What is the problem?
![screen shot 2017-11-20 at 10 32 55 pm](https://user-images.githubusercontent.com/167831/33058095-c8b6103a-ce42-11e7-828b-22eba4e367ac.png)

**Comment by ananmelkonyan** [comment]
@wf9a5m75 Its givving me blank map

**Comment by ananmelkonyan** [comment]
@wf9a5m75 can you please give me some info on which version did you run, i am running on latest xcode

**Comment by wf9a5m75** [comment]
No. I just built and run your project files.

**Comment by wf9a5m75** [comment]
`Blank map` means your api key is wrong.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by wf9a5m75** [comment]
I guess you forget to enable the Google Maps SDK for iOS, or you set the restriction for the api key.

**Comment by ananmelkonyan** [comment]
@wf9a5m75 i have fully looked at your documentation, let me make screen shoot

**Comment by ananmelkonyan** [comment]
<img width="1440" alt="screen shot 2017-11-21 at 10 45 57" src="https://user-images.githubusercontent.com/31433870/33058564-9f22c580-cea9-11e7-8e2c-da26c702a0c7.png">

**Comment by wf9a5m75** [comment]
Definitely your key is the problem.

**Comment by wf9a5m75** [comment]
Please show me the screen capture of project console of Google APIs

**Comment by wf9a5m75** [comment]
![screen shot 2017-11-20 at 10 53 46 pm](https://user-images.githubusercontent.com/167831/33058757-082949f0-ce46-11e7-8c52-528891517882.png)

**Comment by wf9a5m75** [comment]
Should be like this.
![screen shot 2017-11-20 at 10 56 52 pm](https://user-images.githubusercontent.com/167831/33058787-221e4928-ce46-11e7-953c-70dc72715279.png)

**Comment by ananmelkonyan** [comment]
@wf9a5m75 found the issue during plugin install the first key was always running even if i changed it to manually from config.xml, i removed plugin installed with new key and it worked, so in ios to change key i always need to remove and install it again

**Comment by wf9a5m75** [comment]
Well, you can modify the api keys by your hand if you are familiar with Cordova deeply, but it's kind of complex. Remove the plugin and install it again is the easiest way.

**Comment by ananmelkonyan** [comment]
@wf9a5m75 thanks for your support helped me alot.

**Comment by wf9a5m75** [comment]
You are welcome.

By the way, I appreciate if you support for this project. 
This is not mandatory asking, but I appreciate if you donate some amount to provide this plugin as free in the future.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by ananmelkonyan** [comment]
@wf9a5m75 Yes shure :)

**Comment by ananmelkonyan** [comment]
On iOS after Menu Open and close map gets half blank
![screen recording 2017-12-15 at 12 59](https://user-images.githubusercontent.com/31433870/34039053-aba507da-e1a7-11e7-8f78-e11a57721d15.gif)

**Comment by mnatsakanyan** [comment]
@wf9a5m75 any suggest?
