### ISSUE TITLE
No map shows at all

### ISSUE THREAD

**Issue by samlittler** [mapsplugin/cordova-plugin-googlemaps#1891]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-battery-status 1.2.5 "Battery"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.8 "Globalization"
cordova-plugin-googlemaps 2.0.0 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-media-capture 1.4.3 "Capture"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-vibration 2.1.6 "Vibration"


{}

```

**Current behavior:**
No map appears.

**Expected behavior:**
Small map shows on blank page.

**Related code, data or error log (please format your code or data):**

Code repo here:

[https://github.com/samlittler/googlemaps-app-demo](https://github.com/samlittler/googlemaps-app-demo)

I've reverted back to 2.0.0 just in case that was the problem but I can't seem to get it working on 2.1.1 either.

**Comment by samlittler** [comment]
I should also note, I'm running this using phonegap.

**Comment by wf9a5m75** [comment]
This plugin does not run on browser.
This read the title?

Cordova GoogleMaps plugin for iOS and Android

**Comment by samlittler** [comment]
Care to explain why this isn't a bug?

**Comment by wf9a5m75** [comment]
Oh sorry, it seems I forgot to explain the reason.

First of all, this plugin DOESN'T support browser platform.

Second, I guess you use `serve` command, but that is not supposed.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update, I close this thread. But you can reply anytime with new information.
