### ISSUE TITLE
Plugin Error when Running on iOS with HtmlInfoWindow

### ISSUE THREAD

**Issue by mrezzaaa** [mapsplugin/cordova-plugin-googlemaps#1892]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
insert the output from the command here
<img width="577" alt="screen shot 2017-11-15 at 19 07 28" src="https://user-images.githubusercontent.com/14961709/32835345-4a6a1fea-ca38-11e7-894f-bdcc9c23fb7e.png">

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
<img width="1022" alt="screen shot 2017-11-15 at 18 58 43" src="https://user-images.githubusercontent.com/14961709/32834977-0e4443c0-ca37-11e7-9ade-522959c3ef70.png">

**Current behavior:**

Hi, i am using plugin on Android and iOS . 
On android it's run perfectly . 
but not on iOS device(not emulator)

**Expected behavior:**

Running well on both platform.

**Screen capture or video record:**
![img_3250 copy](https://user-images.githubusercontent.com/14961709/32835244-f69b6a22-ca37-11e7-8a41-2542a8f45bf0.png)

**Related code, data or error log (please format your code or data):**
```
2017-11-15 18:47:31.314832+0700 Need n' Meet[10325:4021674] --->animateCamera
2017-11-15 18:47:32.953307+0700 Need n' Meet[10325:4021674] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]'
*** First throw call stack:
(0x18e3d2fe0 0x18ce34538 0x18e2b1200 0x1000c99e4 0x1019b5a50 0x1019b5a10 0x1019bab78 0x18e3810c8 0x18e37ece4 0x18e2aeda4 0x18fd19074 0x194569c9c 0x10000a90c 0x18d2bd59c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
```

<img width="1919" alt="screen shot 2017-11-15 at 18 56 14" src="https://user-images.githubusercontent.com/14961709/32834903-cb0da524-ca36-11e7-8bee-ed30f90cb899.png">

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub. I will check it.

**Comment by wf9a5m75** [comment]
```
 --->animateCamera
 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]'
```

Regarding of the Xcode log, you don't specify the camera target when you execute `map.animateCamera()`.

I guess that's the reason.

**Comment by wf9a5m75** [comment]
And I recommend you use `@ionic-native/core@4.4.0` and `@ionic-native/google-maps@4.4.0`.
Because I fixed some bugs of `@ionic-native/google-maps` plugin.

**Comment by mrezzaaa** [comment]
Updated to google maps native version 4.4.0
Problem is gone .Work smoothly on both device .

Thank you sir @wf9a5m75
