### ISSUE TITLE
Legal not showing up

### ISSUE THREAD

**Issue by dennismarksbury** [mapsplugin/cordova-plugin-googlemaps#1894]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[X ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

cordova-plugin-googlemaps 2.0.7-beta-20170911-2303 "cordova-plugin-googlemaps"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

N/A

**Current behavior:**

plugin.google.maps.environment.getLicenseInfo(showTheLicense);
        function showTheLicense(text) {
            alert('got license: ' + text);
        }

text = "OK"

**Expected behavior:**
I expect legal text other than "OK"

**Comment by wf9a5m75** [comment]
No longer required for Android. Google does not use any open source library currently.
That's why "OK".
But for iOS, Google still use some open source libraries (I guess).
