### ISSUE TITLE
IOS map.addMarker() fails with the message "icon property is null" 

### ISSUE THREAD

**Issue by hypersolution1** [mapsplugin/cordova-plugin-googlemaps#1895]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.8.5 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

In IOS, when I try to use map.addMarker() without the property "icon", it fails with the message "icon property is null", the property "icon" is not required in Android.

**Expected behavior:**

Expected either the same behavior on all platform, or the difference documented.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
    var map;
    var div = document.getElementById("map_canvas");

    // Initialize the map view
    map = plugin.google.maps.Map.getMap(div);

    // Wait until the map is ready status.
    map.on(plugin.google.maps.event.MAP_READY, onMapReady);

    function onMapReady() {
        map.setMyLocationEnabled(true);
        var marker;
        map.on(plugin.google.maps.event.MAP_LONG_CLICK, function(latLng) {
            if(marker) {
                marker.remove()
            }
            map.addMarker({
                position: latLng,
                title: latLng,
                animation: plugin.google.maps.Animation.DROP,
                //icon: "red", //leave commented to trigger the problem
            }, function (m) {
                marker = m //never reach here when "icon" not defined on IOS
            });
        });
    }
```

Thanks! Great plugin by the way.

**Comment by wf9a5m75** [comment]
Please try to reinstall the plugin from the `multiple_maps` branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID=".."  --variable API_KEY_FOR_IOS=".."
```

**Comment by hypersolution1** [comment]
Just saw your commit in that branch. I'm happy this was noticed.
"(iOS) bug fix : "icon property is null" if there is no icon property"
I don't mind to wait for that fix to be merged in the stable branch.
