### ISSUE TITLE
Make the webview transparent when the map initialises instead of on app startup

### ISSUE THREAD

**Issue by danielcrk** [mapsplugin/cordova-plugin-googlemaps#1896]
**I'm submitting a ...** 
[ ] question
[ ] any problem or bug report
[X] feature request

Hi!

This plugin makes the webview background transparent in order to show the maps underneath it, but the transparency is applied at app startup, which in my cases messes up some coool startup effects :)

Would it be possible to make the webview transparent when the map is initiated instead? If now technically messy, this would be a better approach, since the plugin wouldn't make any impact if not actually initialised.

With that said, this plugin is amazing. I've started converting my js-based map to this and I'm really surprised by the sheer amount of api support your have provided. Thanks so much for all your work on this!

**Comment by wf9a5m75** [comment]
This plugin changes the background when the map is created.
Did you read the code?
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/Map.js#L173

**Comment by danielcrk** [comment]
I'm not talking about the DOM, but the webview itself.

**Comment by wf9a5m75** [comment]
I see. But not acceptable.

**Comment by wf9a5m75** [comment]
The reason is ONLY one chance to change the background color of webview.
