### ISSUE TITLE
Issues while migrating from version 1.3.9 to version 2.1.1

### ISSUE THREAD

**Issue by tkram** [mapsplugin/cordova-plugin-googlemaps#1897]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ X] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
(Building with phonegap, pasting my plugin conf)
```
<plugin name="cordova-plugin-crosswalk-webview" spec="2.3.0" />
<plugin name="cordova-plugin-device" spec="1.1.1" />
<plugin name="cordova-plugin-dialogs" spec="1.2.0" />
<plugin name="cordova-plugin-file" spec="4.1.0" />
<plugin name="cordova-plugin-file-transfer" spec="1.5.0" />
<plugin name="cordova-plugin-geolocation" spec="2.1.0" />
<plugin name="cordova-plugin-googlemaps" spec="2.1.1" />
<plugin name="cordova-plugin-inappbrowser" spec="1.3.0" />
<plugin name="cordova-plugin-legacy-whitelist" spec="1.1.2" />
<plugin name="cordova-plugin-network-information" spec="1.2.0" />
<plugin name="cordova-plugin-splashscreen" spec="3.2.0" />
<plugin name="cordova-plugin-statusbar" spec="2.1.0" />
<plugin name="cordova-sqlite-storage" spec="1.2.0" />
<plugin name="phonegap-plugin-barcodescanner" spec="7.0.0" />
```

The map is the main thing in my app. This means im reusing the map and initializing the map only once.
Note: The app runs with jQuery Mobile.

**Current behavior:**
In migrating from version 1.3.9 to 2.1.1 i have the following issues:

- The map controls on iOS doesn't appear. (Zoom, Compass)
- If i switching to the map without drawing a line or a marker, i cant use gestures or camera movement. (iOS)
- animateCamera or moveCamera doesn't work properly while switching to the map. Should i wait for an event here? Maybe the MAP_LOADED ? (Android and iOS behavior..)

**Expected behavior:**
- Visible controls on the map.
- Gesture ready
- animateCamera, moveCamera ready

**Related code, data or error log (please format your code or data):**

Creating the map:
```javascript
        var map = plugin.google.maps.Map.getMap($('#map')[0], {
            'controls': {
                'compass': true,
                'zoom': true
            },
            'gestures': {
                'scroll': true,
                'tilt': true,
                'rotate': true,
                'zoom': true
            }
        });
        map.one(plugin.google.maps.event.MAP_READY, function () {
            console.log("Done Init map!");
            // Inform app controller
            onMapsApiLoadedComplete();
        });
```

I tested to set the options with setOptions, setDiv and got the same behaviour..

**Comment by wf9a5m75** [comment]
v1.3.9 and v2.x are completely different software.
I recommend you try to create an empty project for your first test.

If you share your project files on GitHub (or other git services), I will check it.

**Comment by wf9a5m75** [comment]
Please read documents before starting.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/migrate-from-v1/README.md
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md#classes

**Comment by tkram** [comment]
Yes i know that there are completely different and already read the documents. I fixed the things that changed (function names, events, ..) and can use the map in my app. But the same code that works on Android (Zoom Control. Compass) doesnt work on iOS. 
If i have some more time i will create a sample project for this behaviour.

**Comment by wf9a5m75** [comment]
Zoom control comes from the native api. But the iOS SDK does not support it.

And `compass` should work

```js
var map = plugin.google.maps.Map.getMap(div, {
  'controls': {
    'compass': true,
    'myLocationButton': true,
    'indoorPicker': true,
    'zoom': true // Only for Android
  },
```

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update, I close this thread. But you can reply anytime with new information.
