### ISSUE TITLE
Issue : Markers always show infowindow

### ISSUE THREAD

**Issue by tryadelion** [mapsplugin/cordova-plugin-googlemaps#1898]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X] **Android**
[X ] **iOS**

*

The default infowindow always shows when clicking a Marker, even when setting title and snippet to "", and clickable to false. i would like to not be able to click to SOME markers at all, they are there to showcase non-detailed data.

**Comment by tryadelion** [comment]
Tested code so far:

`var image = {
          url: "assets/img/ic.png",
          clickable: false,
          size: {
            width: 32,
            height: 32
          }
        }
        const markerOption: MarkerOptions = {
          title: "",
          icon: image,
          animation: 'DROP',
          zIndex: 99,
          position: {
            lat: success.coords.latitude,
            lng: success.coords.longitude
          },
          clickable: false
        }`

**Comment by tryadelion** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/5f94a098488fcadea828e14f8ad01d06728017a6?diff=unified

Browsing the commits, founds this could solve it by checking if both are Null to not show the infow indow, but there should really be a "do not show" feature, a boolean that triggers on that same function. "showInfoWindow" instead of clickable, maybe, to still let stuff happen on click, just not, native infowindow stuff.

**Comment by wf9a5m75** [comment]
Do not set title and snippet properties
