### ISSUE TITLE
HTMLInfowindow creation seems to "unlink" marker object reference from map marker

### ISSUE THREAD

**Issue by tryadelion** [mapsplugin/cordova-plugin-googlemaps#1900]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ X] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[X ] **Android**
[X ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
`"@ionic-native/core": "4.4.2",
    "@ionic-native/geolocation": "^4.4.2",
    "@ionic-native/google-maps": "4.4.2",`

For my app's behaviour, when clicking a marker i was saving the marker's reference to a global variable, to, when clicking the map, another marker, some buttons i have over the map, the infowindow would close and the marker would change it's icon.

This worked 100% fine with the default infoWindow.

After setting up a custom  HTML htmlInfoWindow,  the object i save as reference, when "de-selected", displays the correct icon name ( the changed one), after the change, but the map is not updating.

the png files:

ics.png -> selected icon
ic.png -> unselected icon

the code that adds the infowindow:
```
        let html: string = 
          '<div class="infowindowContent">'+
          '<h3>Farmacia ' + marker.get("debugId") + '</h3>'+
          '<br />'+
          '<p>Lorem ipsum<br />667733<br /> De dilluns a divendres</p>'+
          '<img class="colImg" src="assets/img/clusterer.png"/>'+
          '</div>';
        htmlInfoWindow.setContent(html);
        htmlInfoWindow.open(marker);
        this.lastMarker = marker;
```

the code that clears it:
```
clearLast(){
    if (this.lastMarker != undefined) {
      this.lastMarker.hideInfoWindow();
      var image = {
        url: "assets/img/ic.png",
        size: {
          width: 22,
          height: 32
        }
      }
      this.lastMarker.setIcon(image);
    }else{
      console.log("marker is undefined");
    }
  }
```

when printing this.lastmarker on next marker's  click,  it prints ic.png (unselected), but still displays as selected.

![device-2017-11-17-140729](https://user-images.githubusercontent.com/3778474/32948783-c1d43d5e-cba0-11e7-8fcb-ef47bc1ba639.png)

when i comment the htmlInfoWindow.open() lines, it works fine:

![device-2017-11-17-141018](https://user-images.githubusercontent.com/3778474/32948918-36988d70-cba1-11e7-9502-13fd713c8eb5.png)

I think it might have to do with the fact of adding a HTMLInfoView, maybe it's modifying the marker or something in behind the code. i have no clue.

**Comment by wf9a5m75** [comment]
You should not control show/hide the htmlInfoWindow() by yourself. The plugin does that automatically.
If you do, you get the problem.

The recommended way is to create only ONE htmlInfoWindow and recycling it.

**Comment by tryadelion** [comment]
show me an example please. is this the reason the marker breaks?

**Comment by wf9a5m75** [comment]
Please try like this:


```TypeScript

class MapPage {
   htmInfoWindow: HtmlInfoWindow =  new HtmlInfoWindow();

   locations: any[] = [
       {
          position: {lat: ..., lng: ...},
          myHtml: "<b>location1</b>"
       },
       {
          position: {lat: ..., lng: ...},
          myHtml: "<b>location2</b>"
       },
       ....
       {
          position: {lat: ..., lng: ...},
          myHtml: "<b>locationN</b>"
       },
   ];

   loadMap() {
     this.map = GoogleMaps.create(...);
     this.map.one(GoogleMapsEvent.MAP_READY).then(() => {

        let mvcArray:BaseArrayClass<any> = new BaseArrayClass<any>(locations);
        mvcArray.mapAsync((location: any, next: (marker:Marker)  =>void) => {
           this.map.addMarker(location).then(next);
        }).then((markers: Marker[]) => {
           markers.forEach((marker: Marker) => {
              marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(this.onMarkerClick);
           });
        });

    });
    onMarkerClick (params: any[]) {
      let marker:Marker = <Marker> params.pop();
      this.htmlInfoWindow.setConent(marker.get("myHtml"));
      this.htmlInfoWindow.open(marker);
    }
}
```

**Comment by tryadelion** [comment]
The responsiveness of this method is slower ( HTMLInfoWindows take a lot to show), still shows issues when changing selected marker, and most importantly, breaks after some clicks on markers:
`Uncaught TypeError: Cannot read property 'getMap' of undefined
    at HTMLInfoWindow.calculate (HtmlInfoWindow.js:157)
    at HTMLInfoWindow.trigger (BaseClass.js:62)
    at HTMLInfoWindow.set (BaseClass.js:34)
    at Marker.<anonymous> (BaseClass.js:44)
    at Marker.trigger (BaseClass.js:62)
    at Marker.set (BaseClass.js:34)
    at Marker.setIcon (Marker.js:229)
    at callInstance (vendor.js:85916)
    at Marker.<anonymous> (vendor.js:85992)
    at Marker.value [as setIcon] (vendor.js:146681)`

**Comment by wf9a5m75** [comment]
If you have some problems, you should share your project files. I will check it.
Otherwise, please debug by yourself.
At least, you **should** read JavaScript code, and all code is open source.

**Comment by tryadelion** [comment]
I am unable to share with you a  in-production project.
I have debugged my code and it works perfectly fine with **your library's** native InfoWindow
It's when i try to set up a HTML infowindow that the marker's reference on the map is lost, and the HTML infowindow stops working. 
I literally copied your code over mine just to make sure i wasn't doing anything wrong, but nay, it kept behaving incorrectly.

Steps to reproduce (again):

create a map.
create a marketCusterer.
add markers to the marketCluster ( either directly ( as a map of Markers ) or async ( one by one).
on  MARKER_CLICK, save to a global variable a reference to the clicked marker, and change the marker icon to anything else.

on MAP_CLICK (just to make a quick text), change the referenced marker's icon to the original icon.

IF using native infowindow ( title + snippet), the icon will change without issues.
IF using your HTMLInfowindow code ( html string, global infowindow reference recycled), the icon won't change and the last marker clicked reference will no longer apparently be linked the shown marker on the map, not changing the icon or behaving that it should. And clicking too many icons at once pretty fast, will break the HTMLInfoWindow code as shown above.

**Comment by wf9a5m75** [comment]
Sorry, I'm so busy. Until you create a demo project that reproduce your issue , or share your project files with private git repo, I don't help this.

**Comment by wf9a5m75** [comment]
Everyone who use this plugin in produce app, and want to help by me, they does either create a demo or share the project files on a private repo.
Some people still denies both, they search alternative library.

I'm not public service, something like that.
So you need to consider how save my time.

**Time is money**

This is common idiom in world wide.
If you want to receive my support by free, you should contribute to save my time.

**Comment by tryadelion** [comment]
I will try to create a blank project just with a map and some markers for you to see what's going on.

In the event where this fix gives you too much work (weird JS glitches, impossible to fix native stuff), could you help me on modifying your native OBJ-C code to replicate a custom infowindow adapter and layout file i have set up? it adds the option to setup up to two bottom buttons on a infowindow.
I'll post you the code and layout so you can reuse it and publish it if you want to when it's done, it's a very common feature in apps that use maps, a button that opens the details window and a button that opens the phone's goopge maps with a set up route.

i know how to do it in swift 3, but i have  0 clue on how obj-c works (i'm a late adopter of ios).

**Comment by tryadelion** [comment]
@wf9a5m75   here you have a sample project. 
https://mega.nz/#!cbxxABBI!HvIodyWl3AAMq_k1pT_ITp9s7go3y5eINkGgYX62wxc

commnet the next lines : 
```
this.htmInfoWindow.setContent(html);
this.htmInfoWindow.open(marker);
```
and set a title and snippet to see the different behaviours.

**Comment by wf9a5m75** [comment]
Thank you for your understanding. I don't need to include the nodejs folder and platform folders.

However, I appreciate you put your code to GitHub, instead of one zip file.
Because I can see what's updated when you change the code later, we can refer the code, I can update the code if you give me a permit, ... etc
Archive file is not able to do something like that.

Please use Github.

**Comment by tryadelion** [comment]
Ok, i will when i get home, (2-3hrs). in the meanwhile, you can check the behaviour. thanks.

**Comment by wf9a5m75** [comment]
Thanks, When I arrive to my work desk, I will check it.(I just waked up 10 minutes ago)

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
I don't need the `Welcome pdf`
![screen shot 2017-11-20 at 6 03 16 pm](https://user-images.githubusercontent.com/167831/33051090-247356a6-ce1d-11e7-98c1-872b9b2b45b1.png)

**Comment by tryadelion** [comment]
Sorry, it was my 3AM when you posted.

repo created
https://github.com/tryadelion/DemoMaps

**Comment by wf9a5m75** [comment]
Thank you for sharing the demo project, but what is the problem?
![1900](https://user-images.githubusercontent.com/167831/33060148-21a84ca4-ce4c-11e7-9a0d-c04f62634a46.gif)

**Comment by wf9a5m75** [comment]
I recommend you use the `multiple_map` branch if you have problems with `v2.1.1`

**Comment by tryadelion** [comment]
if you approach the map more, there's 3 markers. by the code, when a marker is clicked, it should change it's icon to a selected color. when clicking outside the marker, the marker should go back to the normal color ( grey ). currently with this version, when using native InfowView, the markers change colors correctly, but, when using the HTMLinfoview, they don't, the referenced marker ( lastMarker global )  doesn't change the icon.

**Comment by tryadelion** [comment]
the multiple_map branch way of implenting itself has not been quite ionic friendly in the past, giving me a lot of troubles installing it. Has the process changed in any way? installation didn't work _in any possible way_ for us and we had to switch to web JS maps for a recent project.
This one i'm using seems quite stable and hasn't given any installation, update or upgrade issue so far.

**Comment by tryadelion** [comment]
Also your marker seems to behave much nicely than mine, mine on map pan glitches over the screen  "teleporting" itself to multiple locations back and forth until it finds the marker.

**Comment by wf9a5m75** [comment]
The multiple_maps is development version. It means the edge version, sometimes good than master, sometimes bad than master.
It is depends on the timing (my development)
Currently good than master.
I fixed and improved many things, that's why I recommended.

**Comment by wf9a5m75** [comment]
I will check your repo again tomorrow.

**Comment by tryadelion** [comment]
ok! thanks.

**Comment by tryadelion** [comment]
ping

**Comment by wf9a5m75** [comment]
US is in holidays.

**Comment by tryadelion** [comment]
Ok, ok. had no idea. sorry!

**Comment by wf9a5m75** [comment]
Tentatively, I fixed the HtmlInfoWindow.js code on the airplain. Should be fine (I tested).
Please try the `multiple_maps` branch. (I'm going to bed from now)

**Comment by tryadelion** [comment]
@wf9a5m75  althought needs more testing, i can almost consider both HTMLinfowview flickering and marker "losing reference" when HTML infoview is enabled fixed! i would suggest PR-ing to the main repo so more people can have a fluentlier first hands on experience with the library.

**Comment by wf9a5m75** [comment]
Did you test the multiple_maps branch or no?

**Comment by tryadelion** [comment]
Yes, this is what i'm saying. althought i've found a quite breaking issue, even when adding your META tags, a button inside the HTMLInfoview is not getting any click call, the map  or the marker take the click event instead. i copied your example code from : https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/HtmlInfoWindow/newHtmlInfoWindow/README.md

**Comment by wf9a5m75** [comment]
Use the multiple_maps branch code. It's solved problem in the multiple_maps branch code.

**Comment by tryadelion** [comment]
Yes, im using that. the marker icon issue is solved, the htmlinfoview glitch is solved,  but i can't access any element on "click" inside the htmlinfoview, the MAP_CLICK takes over any action.

**Comment by wf9a5m75** [comment]
Did you try `cordova.fireDocumentEvent('plugin_touch', {});` when you open the HtmlInfoWindow?

**Comment by wf9a5m75** [comment]
And additionally, button of `ionic` does not work is not this pluing's fault.
That's ionic problem. You need to complie your html through the ionic dynamically

**Comment by wf9a5m75** [comment]
Even you use the normal button, and it doesn't work, please make another issue, and close the threads that are already solved.

PR is welcome with test project.

**Comment by tryadelion** [comment]
Normal button, or a div with a onclick="alert'HI')".or even a  DOM injected eventListener doesn't work.

the map canvas takes any incoming click call and puts it through the  GoogleMapsEvent.MAP_CLICK, i debugged it, this is what happens when i click anywhere on the infowindow.

![captura de pantalla 2017-11-23 a las 15 10 48](https://user-images.githubusercontent.com/3778474/33176778-8b646a2c-d060-11e7-90be-bd26c8c5bab4.png)


![captura de pantalla 2017-11-23 a las 15 08 42](https://user-images.githubusercontent.com/3778474/33176721-56df053c-d060-11e7-8ff5-ea24a680131e.png)

**Comment by tryadelion** [comment]
Will update the demo project
