### ISSUE TITLE
Error on "ionic cordova prepare"

### ISSUE THREAD

**Issue by macklus** [mapsplugin/cordova-plugin-googlemaps#1903]
I not really sure that this is really a problem, but i think it should report.

**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.1.2-beta-20171115-1911 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
cordova.plugins.diagnostic 3.7.2 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "4.4.0",
"@ionic-native/google-maps": "^4.4.0",
```
**Current behavior:**
I clone a working git repo of ionic app, who is using cordova-plugin-googlemaps, i run **ionic cordova prepare** to install all plugins and platforms, and command hangs with:

```
Discovered plugin "cordova-plugin-googlemaps" in config.xml. Adding it to the project

Failed to restore plugin "cordova-plugin-googlemaps" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

[ERROR] An error occurred while running cordova prepare (exit code 1).
```

But, if i remove all plugin info from package.json and config.xml, and install it again, everithing works fine

**Expected behavior:**
Commando ionic cordova prepare should run without problemas

**Comment by wf9a5m75** [comment]
That's not plugin's problem. Please ask to Apache cordova tea.m

**Comment by macklus** [comment]
thanks. I ask here because this problem only happens with your plugin
