### ISSUE TITLE
Can't see map anymore

### ISSUE THREAD

**Issue by sharjeel619** [mapsplugin/cordova-plugin-googlemaps#1904]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
<plugin name="cordova-plugin-geolocation" spec="~2.4.1" />
    <plugin name="cordova-plugin-console" spec="~1.0.5" />
    <plugin name="cordova-plugin-dialogs" spec="~1.3.1" />
    <plugin name="cordova-plugin-badge" spec="~0.8.1" />
    <plugin name="com.paypal.cordova.mobilesdk" spec="~3.5.0" />
    <plugin name="cordova-plugin-splashscreen" spec="~4.0.3" />
    <plugin name="cordova-plugin-network-information" spec="~1.3.1" />
    <plugin name="cordova-plugin-x-socialsharing" spec="~5.2.1" />
    <plugin name="cordova-plugin-googlemaps" spec="~1.4.5">
        <variable name="API_KEY_FOR_ANDROID" value="" />
    </plugin>
![screenshot_2017-11-20-02-07-01](https://user-images.githubusercontent.com/11159443/32995558-058ebec2-cd98-11e7-854e-c9e13b6dc6f9.png)

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

Hi, I just noticed that I can't see the map anymore. I did not change any code or anything. But all of sudden I can't see the map. I also used the updated version of this plugin and change my Google Maps API key and still I can't see the map. Any reason as to what I can do to fix it. I would really appreciate your help.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by sharjeel619** [comment]
Thank you for the reply. Unfortunately I have done everything like the documentation asks you to do. However I failed to mention one thing. That is the maps don't work after you upload them to google play. They work fine on a locally generated, signed and zipped apk.

**Comment by wf9a5m75** [comment]
The blank map is your problem.

The most common mistakes are 
- forget to enable the **Google Maps Android API v2 and Google Maps SDK for iOS**, not `Google Maps JavaScript API v3`
- you use the API key of Google Maps JavaScript API v3
- you set restrict for api key that is wrong specify.

The blank map is **your application package name and the api key is mismatched"**.

Try from the first.

**Comment by wf9a5m75** [comment]
ping

**Comment by sharjeel619** [comment]
Please close this issue. I have solved the issue. The issue was that instead of using SHA-1 generated from your local .keystore file. You had to use the one that google generates when you upload your app on the playstore.
![cats](https://user-images.githubusercontent.com/11159443/33149844-07263d2a-cff3-11e7-88a7-e99ab2415166.jpg)
