### ISSUE TITLE
markerCluster MARKER_CLICK event doesn't return the clicked marker

### ISSUE THREAD

**Issue by danielcrk** [mapsplugin/cordova-plugin-googlemaps#1905]
**I'm submitting a ...** 
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**
[ ] **Android**
[x] **iOS**

**cordova information:** 
```
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
```

**Current behavior:**
The markerCluster MARKER_CLICK event callback is supposed to include 2 parameters, position and the marker. Position works properly, but marker is always undefined.

**Expected behavior:**
A reference to the clicked marker should be returned.
Also, idealy (I think), this event should be triggered when a cluster is clicked as well, and then return an array of the markers in that cluster.

**Related code, data or error log:**
```
this.map.addMarkerCluster({
  boundsDraw: false,
  maxZoomLevel: 18,
  markers,
  icons: [
    {
      min: 2,
      url: 'assets/img/geomap/map-pin-zoom-transparent.png',
      anchor: { x: 24, y: 24 },
      label: {
        color: 'white',
        fontSize: 10,
        bold: true
      },
      size: {
        width: 72,
        height: 72
      }
    }
  ]
}, (markerCluster) => {
  markerCluster.on(plugin.google.maps.event.MARKER_CLICK, (position, marker) => {
    console.log(position); // This works well
    console.log(marker); // This is always undefined
  });
});
```

Edit: The version of the plugin is 2.1.1.

**Comment by danielcrk** [comment]
Also, just as a parentheses, is there a way to actually get an event when clicking a cluster?

In my case, the maxZoomLevel is set to max since the markers don't always have unique positions and I want the clustering to work when fully zoomed, but then I need to be able to actually get the click of the cluster when zoom level is 18, and somehow get all the markers in that cluster.

**Comment by wf9a5m75** [comment]
This is wrong.

```
markerCluster.on(plugin.google.maps.event.MARKER_CLICK, (position, marker) => {
    console.log(position); // This works well
    console.log(marker); // This is always undefined
  });
```

Correctly

```
markerCluster.on(plugin.google.maps.event.MARKER_CLICK, (params:any[]) => {
    console.log(params);
  });
```

**Comment by danielcrk** [comment]
It's the same problem, (position, marker) actually is (params[0], params[1]).

Even this just returns the location object, not the marker.
`
markerCluster.on(plugin.google.maps.event.MARKER_CLICK, (params:any[]) => {
  console.log(params);
});
`

**Comment by wf9a5m75** [comment]
What versions Do you use of `@ionic-native/google-map` and `@ionic-native/core`?

**Comment by danielcrk** [comment]
@wf9a5m75 None, it is a Ionic application but I use the js interface directly for this plugin.

**Comment by wf9a5m75** [comment]
Then you code should work.

Please share your project files on GitHub. I will check it.

**Comment by danielcrk** [comment]
I'll try to isolate the problem in a demo app. Just tried not clearing the map before adding the markers, but the issue remains.

**Comment by danielcrk** [comment]
@wf9a5m75 I've created a gist here. Mainly everything important is happening in the `ngAfterContentInit ()` and `plotMapMarkers ()` functions.

https://gist.github.com/danielcrk/dfc54df5520029c1b3118a588207da05

**Comment by wf9a5m75** [comment]
Could you create a demo project files to save my time?

**Comment by wf9a5m75** [comment]
In order to reproduce your issue easily

**Comment by danielcrk** [comment]
Will do!

**Comment by danielcrk** [comment]
@wf9a5m75 Ok, I've recreated the issue in a blank Ionic application, let me know if you need help getting it to run on a device or emulator.

It's basically following your example from the docs, and I'm assuming you'll see the issue there as well.

Let me know if you need any additional info. This is really a show stopper for me right now.

**Comment by danielcrk** [comment]
Also, do you have any idéa about my second question (see second post)? I realise it's not supported out of the box, but perhaps you have an idéa for a workaround? Thanks so much for your help!

**Comment by wf9a5m75** [comment]
Thank you for creating a demo project.

>  the markers don't always have unique positions 

What do you mean this?

In order to talk about the clustering, do you know the geocell  algorithm? If no, please study it first.

**Comment by wf9a5m75** [comment]
If you want to handle the click event of the cluster, you need to know about it.

**Comment by danielcrk** [comment]
I haven't heard the geocell algorithm, but I'm happy with the clustering itself, my issue is that sometimes for my data, even on the max zoom, markers need to be clustered. So this means the user clicks the cluster, but nothing will happen since the map is fully zoomed in. This is proper behaviour - but I'd just like to be able to react to this case, and present the user with the list of that data.

Does this explanation make sense?

**Comment by wf9a5m75** [comment]
The marker cluster is limited up to zoom level 18.
Because calculation of Geocell is kind of heavy task.
The Geocell algorithm is good for huge area, such as nation wide.

If you want to cluster very close positions, such as multiple locations in 10 meter, you should implement different algorithm by yourself.

**Comment by danielcrk** [comment]
I'm with you, but the current algorithm works just fine, only sometimes, I have a cluster of maybe 3-4 markers even when fully zoomed. This is an edge case, but I need to handle it somehow. So writing a new algorithm seems like overkill, since your works just fine for me, except for this small exception.

**Comment by wf9a5m75** [comment]
Main part of the algorithm is implemented in JS code.
Native side is just adding/removing markers mostly.

First, please learn the Geocell algorithm.
The description of this page is easy to understand.
https://www.npmjs.com/package/geomodel

Then read the code.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/MarkerCluster.js

**Comment by danielcrk** [comment]
I think we missunderstand eachother. I have data points that are on the EXACT same location, so it is impossible for them to be un-clustered. So I WANT them to be clustered even on the max zoom, so rewriting the algorithm cannot help, I basically only need to see how to expose the cluster click event.

But sorry for off-topic, one issue at the time, right now, the MARKER_CLICK event is more important! :)

And thanks for the code links, it will be interesting to have a look either way 👍

**Comment by wf9a5m75** [comment]
Well, I just built & run your project, I got this error.
![screen shot 2017-11-20 at 5 48 18 pm](https://user-images.githubusercontent.com/167831/33050684-01f23298-ce1b-11e7-91f0-2e49292a9e23.png)

**Comment by wf9a5m75** [comment]
Here it is.

```TypeScript
export class HomePage {
  @ViewChild('map') mapElement: ElementRef;
  private map: any;

  constructor(public platform: Platform, public navCtrl: NavController) {

  }

  public ngAfterContentInit(): void {
    this.platform.ready().then(() => {
      this.map = plugin.google.maps.Map.getMap(this.mapElement.nativeElement, {
        controls: {
          compass: false,
          myLocationButton: true
        },
        gestures: {
          scroll: true,
          tilt: true,
          rotate: true,
          zoom: true
        },
        camera : {
          target: dummyData[0].position,
          zoom: 4
        },
        preferences: {
          zoom: {
            minZoom: 2,
            maxZoom: 18
          },
          building: false
        },
      });

      this.map.addEventListener(plugin.google.maps.event.MAP_READY, this.onMapReady.bind(this));
    });
  }

  private onMapReady() {
    this.plotMapMarkers();
  }

  private plotMapMarkers() {
    const markers = [];

    dummyData.map(place => {
      const lat = place.position.lat;
      const lng = place.position.lng;
      markers.push({
        position: {
          lat,
          lng
        },
        disableAutoPan: true, // This is onfortunately ignored when adding markers to the cluster :(
      });
    });

    this.map.clear();

    this.map.addMarkerCluster({
      boundsDraw: false,
      maxZoomLevel: 18,
      markers: markers,
      icons: [
        {
          min: 2,
          url: 'assets/imgs/map-pin-zoom.png',
          anchor: { x: 24, y: 24 },
          label: {
            color: 'white',
            fontSize: 10,
            bold: true
          },
          size: {
            width: 64,
            height: 64
          }
        }
      ]
    }, (markerCluster) => {
      markerCluster.on(plugin.google.maps.event.MARKER_CLICK, (position, marker) => {
        this.onMarkerClick(position, marker);
      });
    });
  }

  private onMarkerClick(position, marker) {
    console.log('marker clicked');
    console.log(position, marker); // This only returns the locaton object
  }

}
```
![screen shot 2017-11-20 at 5 59 38 pm](https://user-images.githubusercontent.com/167831/33050976-9dd3dd64-ce1c-11e7-8919-5b7f13d4113b.png)

**Comment by wf9a5m75** [comment]
The thing that the `disableAutoPan` property does not work is a bug. I fixed it. Please reinstall the plugin from the multiple_maps branch.

**Comment by danielcrk** [comment]
@wf9a5m75 You were totally right, it worked just fine - the problem is that Xcode for some reason cannot serialize the object and it shows up empty in the console log >_<

![screen shot 2017-11-21 at 10 27 15](https://user-images.githubusercontent.com/7166101/33067909-eaf2010a-ceaf-11e7-9e84-936c79e57637.png)

Sorry to have wasted your time. If it's makes it feel any better, I've wasted probably 5-6 hours on this all together... Live and learn!

Thanks again for all your help!

**Comment by wf9a5m75** [comment]
You are welcome

**Comment by adamdupuis** [comment]
> I have data points that are on the EXACT same location, so it is impossible for them to be un-clustered. So I WANT them to be clustered even on the max zoom, so rewriting the algorithm cannot help, I basically only need to see how to expose the cluster click event.

@danielcrk Did you ever find a solution for two markers at the exact same coordinates? I also need to find a solution. Something like [OverlappingMarkerSpiderfier](https://github.com/jawj/OverlappingMarkerSpiderfier)
