### ISSUE TITLE
google maps not showing on onsenui's after myNavigator.pushPage("myPage.html");

### ISSUE THREAD

**Issue by saravanans-arch** [mapsplugin/cordova-plugin-googlemaps#1907]
I tried all the transparent css solutions from existing issues list. But the main thing is the map not showing after that pushPage.
But its working well at setMainPage on the dashboard. Any solutions?

**Comment by wf9a5m75** [comment]
Maybe this?

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md#5-using-onsenui-12

**Comment by wf9a5m75** [comment]
If you share your project files on GitHub, I will check it

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update, I close this thread. But you can reply anytime with new information.
