### ISSUE TITLE
Request: Being able to make the map static and disable DOM watching

### ISSUE THREAD

**Issue by danielcrk** [mapsplugin/cordova-plugin-googlemaps#1908]
**I'm submitting a ...** 
[ ] question
[ ] any problem or bug report
[x] feature request

Hi Mashashi, just a feature request, maybe you have already considered this.

I fully understand why the DOM watching is needed, and for most users, it's the best solution. But would you perhaps consider making it possible to make the map "static", i.e. fully disable all DOM watching and letting the user do all necessary stuff themselves?

For me, the map is always static and never moves, it only changes visibility and I can handle that manually, including making all the parent notes transparent. The DOM watching is a heavy task and noticeably slows down apps even on an iphone 8. Again, I fully understand why it is needed - but it is not needed in every case.

Perhaps something like `map.disableDOMWatching()` that can be called after the map is created, or even better, a flag that can be set during the creating of `Map.getMap(div, false);`.

I've started looking through googlemaps-cdv-plugin.js to figure out how it works and the best way to disable it but the plugin is huuuge and it feels like I can't make any changes without affecting anything else.

Do you have any thoughts on this?

**Comment by wf9a5m75** [comment]
use Google static maps api

**Comment by wf9a5m75** [comment]
Even you only one map, you probably display dialog box, button,  ... on the map.

The plugin needs to display it.

And did you try the multiple_maps branch? (I suggested you)
That's faster inspection than master version.

**Comment by danielcrk** [comment]
I haven't tried the multiple_maps branch yet, will definitely do!

But regaring the inspection, let's say I have a small dialog that opens over the map. When the dialog opens, i could call `map.disableDOMWatching()` and then when it closes, I could call for example `map.enableDOMWatching()`. That would be great.

Maybe `map.suspend()` and `map.resume()` would be better terms.

Right now, the only way to disable the inspection is to hide the map, but for cases where you need the map to remain visible, this would be a great option!

I will try to do this myself, but it will probably end up being an ugly hack compared to your solution, since I don't have overview knowlage of the plugin. Should you implement this, I promise to help out with testing :)

Iin the meantime, I will try the multiple_maps branch, thanks for the suggestion (I didn't know what was improved in it besides the bug you pointed out), not matter how much faster the inspection is, there are still cases where it would be better to turn it off fully!

**Comment by wf9a5m75** [comment]
At least, you should try the multiple_maps branch first.
Even you feel new mechanism is still heavy, you need to folk this repository, and implement it by yourself.
I won't implement the methods. Because in the v1 (past version), there were similar methods, and asked many questions. That was really stressful.

**Comment by danielcrk** [comment]
@wf9a5m75 Unfortunately, the multiple_maps causes big touch issues for me, it's like the app doesn't receive every touch. I have to tap om stuff multiple times in order to trigger the events. And this is before the map is even initiated. Just to make sure it wasn't anything else, I reverted back to the regular branch, and the issues disappear.

Do you have any idéa about this? Also, I use the Geolocation plugin (https://github.com/apache/cordova-plugin-geolocation) and after installing the multiple_maps version, the Geolocation stops working, seems like `navigator.geolocation.getCurrentPosition` is overridden somehow?

Unfortunately for me, it looks like I will have to revert back to the js-api map, because the plugin affects the DOM way to much, and out of my control. My entire app is DOM based (of course) and I can't afford to slow it down or have a plugin affect it this much.

Please don't take it as lack of appreciation, this plugin is superb for most users. What you have done here is simply amazing!

**Comment by wf9a5m75** [comment]
If you have a problem, you should share the project files on github. I will check it.

> Geolocation plugin

That's Geolocation plugin problem.
I think you need to reinstall the plugin.

**Comment by wf9a5m75** [comment]
And if you want to get the current location, this plugin also provides `map.getMyLocation()` (and `Geolocation.getMyLocation()` in the multiple_maps branch version).

I always help the people who have the problem and provide enough information.

No enough information (such as no sharing their project files even demo), I recommend to use alternatives.

**Comment by danielcrk** [comment]
If this plugin also provides the current location without initiating the map, then great, it is no issue! :)

I cannot share the project as it is a fairly large commercial application, and I fully understand that you don't have enough information to be able to help, I wasn't expecting anything really :)

If you really feel that you wont implement anything like map.suspend/resume to stop the DOM inspection stuff completely (maybe even have it undocumented, to prevent questions?) I will go back to the googlemaps-js-api.

Again Masashi, thanks for your help, your support for this **free** plugin is amazing.

**Comment by danielcrk** [comment]
@wf9a5m75 Just one more thing; would map.setClickable(false) stop all the DOM checking?

**Comment by wf9a5m75** [comment]
That's acceptable idea.

Currently no visible maps, no check. I have considered to add `map.setEnable(false)`, (not implemented yet).

**Comment by danielcrk** [comment]
@wf9a5m75 That would be awesome, I will keep my eyes open on this!

I've played around some more with the multiple-maps branch version and tested a bunch of stuff, and really, there are touch issues as soon as the app starts, even before a map is initiated.
I will try to make a demo of this and cross my fingers for `map.setEnable(false)` :)
