### ISSUE TITLE
White bar on iPhone X with WKWebView

### ISSUE THREAD

**Issue by bentomas** [mapsplugin/cordova-plugin-googlemaps#1909]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
com.napolitano.cordova.plugin.intent 0.1.3 "IntentPlugin"
com.phonegap.plugins.nativesettingsopener 1.2 "Native settings"
cordova-background-geolocation 2.8.5 "BackgroundGeolocation"
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-disable-bitcode 1.3.2 "DisableBitcode"
cordova-plugin-email 1.1.1 "EmailComposer"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-fastrde-checkgps 0.9.9 "checkGPS"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-globalization 1.0.8 "Globalization"
cordova-plugin-google-analytics 1.8.2 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 1.4.0-beta "cordova-plugin-googlemaps"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-safariviewcontroller 1.4.7 "SafariViewController"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-sqlite-ext 0.10.4 "Cordova sqlite storage plugin with extras"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
sqli-cordova-disk-space-plugin 1.0.0 "DiskSpacePlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.2 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
White, 44px bar at top of map on iPhone X.

**Expected behavior:**
No white bar.

**Screen capture or video record:**

<img width="545" alt="screen shot 2017-11-21 at 10 31 00" src="https://user-images.githubusercontent.com/49276/33090271-3c23a158-cea8-11e7-9940-1672fcc17838.png">

**Comment by bentomas** [comment]
Forgot to mention that this is with a much older version of the plugin.

**Comment by wf9a5m75** [comment]
Wow, `cordova-plugin-googlemaps 1.4.0-beta` is too old for me. No more support that version.

**Comment by wf9a5m75** [comment]
If you will update to the current version, I will help you.

**Comment by wf9a5m75** [comment]
By the way, thank you for your donation!

**Comment by wf9a5m75** [comment]
I guess the reason of staying on v1.4 is the kmlOverlay?

**Comment by bentomas** [comment]
We've made our own changes in a fork to allow encrypted polylines, so we cannot update at this time.  Any suggestions for how I can go about debugging this?

**Comment by wf9a5m75** [comment]
Could you tell me the link of the folk repo?

**Comment by wf9a5m75** [comment]
The plugin shift down 20px (or 40px... etc, I forgot) when your app has the status bar.
I removed the code from the multiple_maps branch version(next release), because the plugin tests other plugins before handing the touch event for this plugin, so (I guess) you don't face this issue anymore.

But you stay on the v1.4, you need to handle it by yourself.

I will find the code in your forked repo if you tell me the link.

**Comment by wf9a5m75** [comment]
Thanks.

**Comment by wf9a5m75** [comment]
It seems the v1.4 does not shift down.
But I found a PR to fix this issue.
Try this PR.
https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/1630/files

**Comment by wf9a5m75** [comment]
Did you solve your issue?

**Comment by bentomas** [comment]
That didn't work, I'm still looking into it.  I'll post back here if I figure something out.  Thanks for the help.

**Comment by wf9a5m75** [comment]
How about this?
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/c5b156ab00bde96d7da3a3b740fece70c91341e1/src/ios/GoogleMaps/MyPluginLayer.m#L327-L332

**Comment by bentomas** [comment]
I was wondering about that, but it seems like clicks are working fine.  

Some more information...

It isn't limited to just iPhone X.  It seems to be effecting all sizes of phones.  But the height of the white bar is maybe about the height of the status bar?

<img width="559" alt="screen shot 2017-11-21 at 13 29 53" src="https://user-images.githubusercontent.com/49276/33097800-20627bde-cec0-11e7-9dea-7474b0e76248.png">

It appears the map is just too low.  If you look at this screen shot above, you can just barely see the Google logo in the bottom left for the licensing stuff.  And then the first screenshot of the iPhone X above, you can't even see the Google logo.  So I think it is just drawing too low.  I don't know enough objective C to figure out where that happens, but I'm working through the code now.  Maybe the container view is in the wrong place or something.

**Comment by wf9a5m75** [comment]
I guess the reason is the status bar shift down the wkwebview itself.
https://github.com/apache/cordova-plugin-statusbar/blob/e41c06334e3b2fe5bd7b780f1d03a47bdd242147/src/ios/CDVStatusBar.m#L481-L498

**Comment by bentomas** [comment]
Some how the bounds for `PluginScrollView` is getting an origin of `0,20` (for most iPhones), and `0,40` (for iPhone X).  Resetting the bounds origin seems to solve the problem.  Going to test more to make sure it doesn't reset itself while using the app.  

Any idea why it might be getting set to the height of the scrollbar?

Going to close this because it doesn't apply to the current version and I found the problem.

**Comment by shrijan** [comment]
Hey Bentomas,

How do you reset the bounds origin?

[https://bitbucket.org/piyashrija/googlemapcordova](https://bitbucket.org/piyashrija/googlemapcordova)

Thanks
Shrijan
