### ISSUE TITLE
Get coordinates of current position

### ISSUE THREAD

**Issue by condacore** [mapsplugin/cordova-plugin-googlemaps#1912]
Hello,

is it possible to get the current location of the Device and use it to calculate the distance between two points **without using the cordova-plugin-geolocation**?

```javascript
var myCurrentPosition = ?
var someOtherPositon = {"lat": 32, "lng": -97};
plugin.google.maps.geometry.spherical.computeDistanceBetween(myCurrentPosition, someOtherPositon);
```

Currently using Version 2.1.1 of your Plugin with Ionic.

Best Regards
Marius

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getMyLocation/README.md
