### ISSUE TITLE
Quick question about this plugin

### ISSUE THREAD

**Issue by juancafe4** [mapsplugin/cordova-plugin-googlemaps#1913]
Hi,
I want to know if you can create a pulse animation for the marker.
And you can put event listeners like end-dragging ?
It works on iOS 11

**Comment by wf9a5m75** [comment]
Please describe more details.

What is the `pulse animation`?

And what is `end-dragging`?

**Comment by juancafe4** [comment]
this type of animation in css https://codepen.io/olam/pen/zcqea

those events https://developers.google.com/maps/documentation/javascript/events

**Comment by wf9a5m75** [comment]
Map events
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/README.md#events

**Comment by wf9a5m75** [comment]
Animation, no

**Comment by juancafe4** [comment]
Thanks for the info :)
