### ISSUE TITLE
When creating a HTMLinfowindow, no element,div, or button ( pure html speaking ) seems to recieve a click / onclick event.

### ISSUE THREAD

**Issue by tryadelion** [mapsplugin/cordova-plugin-googlemaps#1914]
I'm submitting a ... (check one with "x")
[ ] question
[ X] any problem or bug report
[ ] feature request

If you choose 'problem or bug report', please select OS: (check one with "x")
[X ] Android
[X ] iOS

Using the Multiple_Maps branch

When creating a HTMLinfowindow, no element,div, or button ( pure html speaking ) seems to recieve a click / onclick event.

@wf9a5m75  i have updated the demo repository: https://github.com/tryadelion/DemoMaps

and i owe you a beer  (or two) for both issues help.

**Comment by tryadelion** [comment]
If i modify the CSS properties while debugging and cause a "redraw", for example, moving the HTMLInfoview just one pixel, then it works! i have no idea how to correct this.

**Comment by tryadelion** [comment]
on this GIF, on the 2nd time i open a infowindow, i check and uncheck one of the infowindow content's CSS propertiesm box-sizing: border-box. after doing that,  the click works.

https://im5.ezgif.com/tmp/ezgif-5-b738e6cdf2.gif

**Comment by tryadelion** [comment]
Upon investigating, when clicking the button or the view using chrome inspection, it always works. on tapping with my finger on the screen, it never works. is there any tapping catch involved on this?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/ionic-googlemaps-quickdemo/blob/master/src/pages/html-info-window/html-info-window.ts

**Comment by tryadelion** [comment]
I'll try it as soon as i can, either at home or tomorrow ( 12-ish hours).

**Comment by wf9a5m75** [comment]
```TypeScript
let htmlInfoWindow = new HtmlInfoWindow();

      let frame: HTMLElement = document.createElement('div');
      frame.innerHTML = [
        '<h3>Hearst Castle</h3>',
        '<img src="assets/imgs/hearst_castle.jpg">'
      ].join("");
      frame.getElementsByTagName("img")[0].addEventListener("click", () => {
        htmlInfoWindow.setBackgroundColor('red');
      });
      htmlInfoWindow.setContent(frame, {
        width: "280px",
        height: "330px"
      });
```

HtmlInfoWindow is displayed on browser.

**Comment by tryadelion** [comment]
@wf9a5m75  is the commit available through the multiple maps branch already?

**Comment by tryadelion** [comment]
Tested, works perfectly. can consider it closed.

**Comment by thezakman** [comment]
@wf9a5m75 how do I pass a funcion in:
```
.addEventListener("click", () => {
                displayStores(element.id,element.numOffers);
              });
```

Do i need to construct the whole function inside it?

**Comment by pitamash** [comment]
This helps you make a custom     htmlInfoWindow ;

       this.map.addMarker({
          
          }) .then(marker => {
                marker.on(GoogleMapsEvent.MARKER_CLICK)
                  .subscribe(() => {
                     //do something on click.
                        var htmlInfoWindow = new htmlInfoWindow();
                        var html = '<h1></h1>';
                        htmlInfoWindow.setContent(html);
                        htmlInfoWindow.open(marker);
                  });
               
               });

**Comment by mntdragon** [comment]
I got the error htmlInfoWindow is not a constructor

**Comment by astronmy** [comment]
because the contructor is HtmlInfoWindow 
**change this**
 var htmlInfoWindow = new htmlInfoWindow(); 
**for** 
var htmlInfoWindow = new HtmlInfoWindow();

**Comment by pitamash** [comment]
😀😀😀 It's been 5 months. I sorted it out. Thanks anyway.
