### ISSUE TITLE
Bottom part of ionic tabs is not clickable

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1919]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**
```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.1.2-beta-20171122-2100 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
The bottom part of ionic tabs is not clickable when the map plugin is installed.
I am not sure but it may be caused by 6d4b129321ad46c10f6f434908ab364883a09c3a.

You can test with my repo: https://github.com/antoine92190/ionic-map

**Screen capture or video record:**

![map-click](https://user-images.githubusercontent.com/16256207/33230255-36849e38-d1e0-11e7-9275-9bca62d979eb.gif)

**Comment by wf9a5m75** [comment]
I just built and run your project files, but no problem.
![1919](https://user-images.githubusercontent.com/167831/33241730-2d087206-d287-11e7-81fb-935e5fe60dc1.gif)

**Comment by antoine92190** [comment]
Indeed, the issues cannot be reproduce on the iPhone X.
But it can be reproduced on the iPhone 8 (and below) simulator.
That probably confirms my guess that the issue is linked to the iPhone status bar.

**Comment by wf9a5m75** [comment]
This is the screen record of iPhone 8.

![1919](https://user-images.githubusercontent.com/167831/33253599-fc4031a0-d2f8-11e7-8299-9131429bd523.gif)

![screen shot 2017-11-26 at 10 26 01 pm](https://user-images.githubusercontent.com/167831/33253606-03322eaa-d2f9-11e7-82c4-a151a07981da.png)

**Comment by antoine92190** [comment]
Strange. Could you also send me the `ionic info` output so I can compare with mine? Maybe it is link to the Xcode version.

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.1
    npm        : 5.5.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by wf9a5m75** [comment]
```
$ ionic info

cli packages: (/Users/wf9a5m75/.nvm/versions/node/v7.10.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v7.10.0
    npm   : 4.2.0 
    OS    : macOS High Sierra
    Xcode : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```

**Comment by antoine92190** [comment]
I really don't understand why you can't reproduce the issue on your side.

However, I could isolate the commit causing this issue: 9485871be55c12ef8040a793faa27bfcc417c4fe

With this commit 89e727a5db1f595d81053c637533bc9315878425, everything works fine.

Do you have any idea what could be wrong with 9485871be55c12ef8040a793faa27bfcc417c4fe?

**Comment by wf9a5m75** [comment]
Unfortunately, without reproducing the issue on my side, I can not help you.

The commit https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/9485871be55c12ef8040a793faa27bfcc417c4fe is just passes the touch pass to other views before checking by this plugin.

If the commit has the problem, there should be an invisible view over the map.
I don't know which plugin, but it should not be the status bar plugin.
The status bar plugin just shift down the webview.

**Comment by wf9a5m75** [comment]
ping

**Comment by antoine92190** [comment]
I was not able to resolve this issue yet.
I will spend more time on it when I have time, for now i will stick to 89e727a5db1f595d81053c637533bc9315878425.
Will reopen the issue if I have more information or found a solution.

**Comment by wf9a5m75** [comment]
Did you test the multiple_maps branch after this commit https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/de44ee066046498a36e3c7ae21782d332889a820 ?

**Comment by antoine92190** [comment]
Yes, but it does not solve my issue.

**Comment by wf9a5m75** [comment]
I updated the code for another issue, but it might help your problem. Please reinstall the plugin from the multiple_maps branch.

**Comment by antoine92190** [comment]
Unfortunately, it does not fix it.

**Comment by wf9a5m75** [comment]
I've never reproduce your issue at all. So the problem is either:
- your demo is not the same as your product or
- your code of other part is wrong.

**Comment by antoine92190** [comment]
I can reproduce the issue 100% on the demo I shared with you.
I test every update you do on it, to make sure my product is not responsible for the issue.

Why I have the issue and you do not on the exact same demo, that is a mystery...

**Comment by wf9a5m75** [comment]
I tested your project with the latest multiple_maps branch, but no problem.
(no further update until new update from you)

![1919_compress](https://user-images.githubusercontent.com/167831/33790002-9b2237a0-dc31-11e7-8e9d-f9d8490466eb.gif)

**Comment by matadornetwork** [comment]
I can also confirm we are experiencing this issue. We have tried the latest version, the 89e727a commit and the multiple_maps branch but still can't click at the very bottom of the app. I remove the plugin and can click the bottom again. Note that it's only the bottom 50px or so.

**Comment by wf9a5m75** [comment]
It sounds like another plugin block the touch.

**Comment by matadornetwork** [comment]
I don't understand why it would work when we remove the maps plugin, and stop working when we install the maps plugin. We do have the statusbar plugin installed as well. Perhaps there is a conflict between the 2 plugins?

**Comment by wf9a5m75** [comment]
Did you try the `multiple_maps` branch version?

**Comment by matadornetwork** [comment]
I did try that branch as well, no change.

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by antoine92190** [comment]
@matadornetwork 
That would be really helpful if you could share your project files with @wf9a5m75.
Could you also share your `cordova plugin list` output?
Have you tried to reproduce the issue on a fresh new ionic project?

**Comment by wf9a5m75** [comment]
@antoine92190 Before asking me, you should try by your self with the latest commit. I spent many hours for this case, and never never reproduced.

**Comment by antoine92190** [comment]
@wf9a5m75 I tried with the latest commit, but the issue still exists.
Sorry for the misunderstanding, but I was asking the `cordova plugin list` and reproduction case to @matadornetwork to better understand the origin of the issue.

**Comment by wf9a5m75** [comment]
I will test if @matadornetwork share the project files on github. As you may know, @antoine92190 's demo project does not reproduce the issue at all.

**Comment by matadornetwork** [comment]
Sorry I cannot share our project, however let me see about putting together a demo. I believe the conflict is likely between the maps plugin and the statusbar plugin as removing either plugin appears to solve the problem.

**Comment by wf9a5m75** [comment]
Try this commit https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/d41f4362df341161a5119a46b6d979e9c2aa2e3b

**Comment by antoine92190** [comment]
@wf9a5m75 Fixed! Thank you!!

**Comment by gregavola** [comment]
@antoine92190 I know this like 6 months later, but are you still having this issue with the master release, or have you just used this commit?
