### ISSUE TITLE
markerCluster - removeMarkerById

### ISSUE THREAD

**Issue by Setkas** [mapsplugin/cordova-plugin-googlemaps#1921]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
com.trakm8.plugin.gps-and-annotation 0.0.1 "GpsAndAnnotation"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-crosswalk-webview 1.8.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-fastrde-checkgps 0.9.9 "checkGPS"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.1-dev "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-toast 2.5.2 "Toast"
cordova-sqlite-storage 1.4.6 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.0 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

Does not do anything

**Expected behavior:**

Should remove marker from cluster

**Related code, data or error log (please format your code or data):**
Error: undefined is not an object (evaluating 'self._isRemove') 
   - plugins/cordova-plugin-googlemaps/www/MarkerCluster.js:346:11

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub to reproduce your issue.

**Comment by wf9a5m75** [comment]
The `removeMarkerById()` is internal method. Do not use that.
