### ISSUE TITLE
Google Maps 2.1.1 freezing or blocking interaction

### ISSUE THREAD

**Issue by HartHerbert** [mapsplugin/cordova-plugin-googlemaps#1922]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS** (ONLY TESTED IN iOS by now)

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-admobpro 2.29.29 "AdMob Plugin Pro"
cordova-plugin-camera-preview 0.9.0 "cordova-plugin-camera-preview"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-extension 1.5.3 "Cordova Plugin Extension"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova.plugins.diagnostic 3.7.2 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "4.4.2",
"cordova-plugin-googlemaps": "2.1.1",
```

**Current behavior:**
Updated the plugin from version `2.0.11` to the current `2.1.1` and the map stucks now. 
I can't move, touch, zoom, pan or interact with the map at all.

**Expected behavior:**
to interact with the map

**Screen capture or video record:**
(You see the screen going up and down, thats me touching the map. so I can't do anything with the map at the moment.)
![issue-opti](https://user-images.githubusercontent.com/22191877/33285709-68d83d2a-d3b3-11e7-87c5-bff0367d06f7.gif)

**Comment by wf9a5m75** [comment]
Please share your project files on github. I will check it.

**Comment by HartHerbert** [comment]
I'm sorry but it's a private project and I don't have much time to create a demo repo.
Now I am able to touch the map again but all other pages get stuck.

But I found out what is the problem:

+ My application loads the page that contains the map first.
+ then it switches to the middle tab page

+ the thing that happens then is that the map catches all touch events while its focused once and then no other page of my app respond to touch events. Something has been changed by you since the version `2.0.11` because in that version its working fine with the tabs.

**Comment by wf9a5m75** [comment]
If you were me, what will you support without code?
You can use this plugin as free, but support is not free because you spend my private time.

So if you want to receive support from me, please save my time.
Otherwise, please debug by yourself. All source code is open

**Comment by thiphariel** [comment]
@HartHerbert Have you solve this issue by now ? It happened randomly in my app as well but I don't know why yet. Btw, I do not use tabs like you..

I have a side menu, when I open it then close it, the map is back interactive. Quite annoying :D

**Comment by HartHerbert** [comment]
no I wasn't able to solve it, I hadn't time to look into this. I just downgraded to the latest stable version `2.0.11`

**Comment by newtonmunene99** [comment]
Did anyone find a solution to this?

**Comment by b4tch** [comment]
I had a similar issue whereby an HTML overlay on the map was preventing touch events being registered on the map once they had transitioned out of view.  I'm not sure if this is related to this bug, but I fixed it with the following:

```
setTimeout( function() {
	cordova.fireDocumentEvent('plugin_touch', {force:true});
}, 300 );
```

It's on a timeout so that it fires once the overlay is out of view.
