### ISSUE TITLE
Unable to submit iOS app to Apple with cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by adamgatelogix** [mapsplugin/cordova-plugin-googlemaps#1925]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x ] **iOS**

**Current behavior:**

I make build from https://build.phonegap.com and try to upload from x-code application loader and got this error.

ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/Default.app/GoogleMaps.bundle/GMSCoreResources.bundle/Assets.car' can't be read. Try rebuilding the app with a non-beta version of Xcode and submit it again."

**cordova information:**
<gap:plugin name="cordova-plugin-geolocation" source="npm" />
<gap:plugin spec="https://github.com/mapsplugin/cordova-plugin-googlemaps.git" source="git" >
        <param name="API_KEY_FOR_ANDROID" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxx" />
        <param name="API_KEY_FOR_IOS" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxx" />
</gap:plugin>

**Comment by wf9a5m75** [comment]
Please ask to PhoneGap build team. Not plug-in's problem.
