### ISSUE TITLE
(bug) Possible memory leak in IOS

### ISSUE THREAD

**Issue by MohammadWaleed** [mapsplugin/cordova-plugin-googlemaps#1928]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com-sarriaroman-photoviewer 1.1.10 "PhotoViewer"
com.etq.reliance.plugins.CompressionPlugin 0.2.9-dev "CompressionPlugin"
com.etq.reliance.plugins.FileUtilities 0.2.9-dev "FileUtilities"
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-3dtouch 1.3.5 "3D Touch"
cordova-plugin-app-preferences 0.99.3 "AppPreferences"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-check-installed-services 0.0.2 "CheckInstalledServices"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-cookieemperor 1.0.0 "CookieEmperor"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-opener2 2.0.17 "File Opener2"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-filechooser 1.0.1 "File Chooser"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-filepicker 1.1.4 "File Picker"
cordova-plugin-googlemaps 2.1.1 "cordova-googlemaps-plugin"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-media 2.4.1 "Media"
cordova-plugin-media-capture 1.4.3 "Capture"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-video-editor 1.1.2 "VideoEditor"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-safe 2.0.1 "Safe"
cordova-sqlcipher-adapter 0.1.9 "Cordova sqlcipher adapter"
cordova.plugins.diagnostic 3.4.2 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.istablet 1.2.0 "Is Tablet"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/google-maps": "4.3.2",
"@ionic-native/core": "4.3.2",

```

**Current behavior:**

Possible memory leak..
the app becomes laggy and unresponsive
the problem happens when opening a new page the contains a map the going back

**Expected behavior:**

the shouldn't become laggy or unresponsive

**Additional Notes:**
- The issue doesn't replicate in android.
- The problem is resolved when i reverted back to 
```
cordova-plugin-googlemaps 1.4.3 "cordova-googlemaps-plugin"
"@ionic-native/google-maps": "3.12.0",
```

**Comment by wf9a5m75** [comment]
`v1.4.3` and `v2.1.1` are completely different code.

While `v1.4.3` watches only the child elements of the map div, `v2.1.1` monitors all html elements in order to detect overlays automatically.

In order to reproduce your issue, please share your project files on github.
If you don't want to share your project files, please stay on `v1.4.3` (but no longer supported)

**Comment by wf9a5m75** [comment]
ping

**Comment by MohammadWaleed** [comment]
Sorry for not responding sooner... 
unfortunately i won't be able to share with you the project code as it a project in a private company, 
and i don't have access for an IOS device right now,
i'll have access to one in Sunday, i'll create a new project and try to replicate the issue in it,
i'll post my updates then

**Comment by wf9a5m75** [comment]
Since this plugin is open source, you can use this plugin as free, but support is not free, because you spend my private time.

So, if the demo project file you will create that is not enough to detect as a bug, there is no further support. Please keep in mind.

**Comment by MohammadWaleed** [comment]
I'm not looking for a free support, i just wanted to help 
anyway i couldn't duplicate the issue,  so i'm closing the issue
