### ISSUE TITLE
Instantiate (preload) the map prior to showing it

### ISSUE THREAD

**Issue by aMUSiC** [mapsplugin/cordova-plugin-googlemaps#1929]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

I've been working a lot lately with the googlemaps plugin through ionic, and one thing I notice is that the initialization/initial rendering of the map is taking significantly much more time on iOS than on Android. I realize that on android a lot of things are shared on the os level (and hey.. it's google.. someone would suspect that a google product works better on another google product).

So my question is this. Would it be possible to initialize the map on an element that is not attached to the dom (let's say during the application loading/initialization), and when the view that would contain the map enters the screen, then attach the map element on the dom?

Would that way make the map render faster? (of course initialization would take the same time, but since it happens during loading, the perceived speed for the end user is different).

**Comment by wf9a5m75** [comment]
```TypeScript
let map : GoogleMap = GoogleMaps.create();
map.one(GoogleMapsEvent.MAP_READY).then(() => {
  map.setDiv('map_canvas');
});
```

**Comment by aMUSiC** [comment]
Ah! Excellent! thanks a lot man!

**Comment by aMUSiC** [comment]
It would also be interesting to also have an event fired after the map is rendered on the div, after setDiv is called.

**Comment by wf9a5m75** [comment]
There is no event available.

**Comment by wf9a5m75** [comment]
Possible event is the `CAMERA_MOVE_END` event

**Comment by aMUSiC** [comment]
Maybe if I attach a dom event on the div the map is drawn, it could do the trick.

**Comment by aMUSiC** [comment]
Also let map : GoogleMap = GoogleMaps.create(); does not work, as the create() function requires at least one parameter. If I pass null or {} to it, then the MAP_READY event never gets fired.

**Comment by wf9a5m75** [comment]
If you use the `@ionic-native/google-maps@4.4.2`, at least `{}` should work.
https://github.com/wf9a5m75/ionic-native/blob/17df1cd22b57e9294b0b01ca46fc3ddd934d86f4/src/%40ionic-native/plugins/google-maps/index.ts#L915-L917

**Comment by wf9a5m75** [comment]
ping

**Comment by aMUSiC** [comment]
I am using @ionic-native/google-maps@4.4.2 already. I'll test it again and come back with the results. Additionally I want to check out to see if I can use map.getMyLocation() without the map being set to a div, as multiple_maps conflicts with cordova-plugin-geolocation for some reason, so I wanted to remove the geolocation plugin entirely and rely only on your plugin to get the user's location.

**Comment by wf9a5m75** [comment]
If you use the `multiple_maps` branch, you can do like this.

```
declare var plugin: any;

export class HomePage {
  ...

  loadmap() {
    plugin.google.maps.Geolocation.getMyLocation((location) => {
         console.log(location);
    }, (error) => {
         console.log(error);
    });
  }
}
```

This is not implemented into the `@ionic-native/google-maps` plugin yet, but the original JS version already has it.

**Comment by aMUSiC** [comment]
I can confirm that it works with {} as parameter.

However, when I use getMyLocation on your example above, the error callback is triggered with the message "Invalid Action", which happens also if I use the @ionic-native/google-maps wrapper function.

It works fine however, if I remove cordova-plugin-geolocation , so there definitely is a conflict between geolocation and multiple_maps. Maybe the plugin that is installed last gets exclusive access to the geolocation capabilities of the phone?

**Comment by wf9a5m75** [comment]
> Maybe the plugin that is installed last gets exclusive access to the geolocation capabilities of the phone?

There is no such a feature in Android.

**Comment by aMUSiC** [comment]
I wouldn't know as I'm not a native android/ios developer, but it's clear that cordova-plugins-geolocation and cordova-plugin-googlemaps on multiple_maps don't play well together.

But anyway, since I can cover my location needs through multiple_maps, I'm happy.

**Comment by wf9a5m75** [comment]
I faced sometimes the same situation.
Uninstalling then reinstall the `cordova-plugins-geolocation` plugin after this plugin works fine.
So it's definitely `cordova-plugins-geolocation` plugin problem.

This plugin does not refer any feature of `cordova-plugins-geolocation` plugin.

**Comment by aMUSiC** [comment]
Not quite, here's the scenario:

If I uninstall/reinstall cordova-plugins-geolocation , then cordova-plugins-geolocation works but getMyLocation of multiple_maps does not work.

If I uninstall/reinstall multiple_maps then getMyLocation of multiple_maps works, but cordova-plugins-geolocation does not work.

**Comment by wf9a5m75** [comment]
Since I don't support the compatibility with other plugins, you need to choose one of them, or ask to fix the `cordova-plugins-geolocation` plugin developer.

I haven't update the code of accessing to the geolocation recently. I only changed the code location in files.

**Comment by aMUSiC** [comment]
Yeah, that's the way I went. I chose your plugin for both jobs :)

Thank you for the help man.
