### ISSUE TITLE
Unexpected behavior of map behid navbar tabs

### ISSUE THREAD

**Issue by gabolucuy** [mapsplugin/cordova-plugin-googlemaps#1930]
**I'm submitting a ...**  (check one with "x")
[X ] question
[ ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.2.2 "OneSignal Push Notifications"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
   @ionic-native/core": "^4.4.0"
   "@ionic-native/google-maps": "^4.4.2",
**Current behavior:**
In the app I have a fixed navbar at the bottom and on the same view I have map. When the navbar is on top of the map the links in the navbar stop working, instead when I tap a navbar link the map is triggered, so even though the map is behind the navbar for some reason its seems like the map is on top

**Expected behavior:**

I should be able to tab the navbar even thought the map is behind
**Screen capture or video record:**

<img src="https://user-images.githubusercontent.com/18706283/33503149-03a45e94-d6b9-11e7-8679-abc81d04e068.jpeg" width="250">
<img src="https://user-images.githubusercontent.com/18706283/33503150-03c4bab8-d6b9-11e7-9f35-c125cb56afa9.jpeg" width="250">

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by gabolucuy** [comment]
https://gitlab.com/franz_beltran/client_app.git

**Comment by wf9a5m75** [comment]
Thank you for sharing, but I can't see your project in my list

**Comment by wf9a5m75** [comment]
![screenshot_20171202-153806](https://user-images.githubusercontent.com/167831/33520802-e041dd0a-d776-11e7-9f2b-280d9c3dcb9f.png)

**Comment by gabolucuy** [comment]
ok sorry no i added you,thanks

**Comment by wf9a5m75** [comment]
You joined me, but you didn't share the code.

**Comment by gabolucuy** [comment]
the issue is in profile.ts and profile.html, the map is shown in the *ngSwitchCase="'location'" in the html file. Or do you want me to copy in a commet the code?

**Comment by wf9a5m75** [comment]
Yes, thank you for sharing. But it's Saturday night already. I will check it tomorrow.

**Comment by gabolucuy** [comment]
ok no problem! thank you for the help!

**Comment by gabolucuy** [comment]
@wf9a5m75 for login: testuser1@confort.com pass:foobar

**Comment by wf9a5m75** [comment]
Thank you. Confirmed. Easy solution is to set higher value for the tab bar.

```css
.tabbar {
  z-index: 99999;
}
```

But I will try to fix this problem without hack.

**Comment by wf9a5m75** [comment]
@gabolucuy Hey, you remove my account from the repo.

**Comment by wf9a5m75** [comment]
And could you tell me what is the reason of `z-index: -10` for `#mymap`?
(I thought I past the private link here, but you remove me from the project, I past this css)

```

page-profile {
    #mymap{
        display: block;
        width: 320px;
        height: 200px;
        z-index: -10;  <-- this
    }
```

**Comment by gabolucuy** [comment]
@wf9a5m75 sorry man, for work reasons I had to remove you, I will add you rigth now again, I tried your solution but now the app crashes, I tried this on an android 4.4.4 phone.

**Comment by gabolucuy** [comment]
@wf9a5m75  in the latest version theres no longer that z-index, think I put that for testing

**Comment by gabolucuy** [comment]
yes I know but I really had to remove you today, sorry

**Comment by wf9a5m75** [comment]
I fixed the bug. Please reinstall the plugin from the multiple_maps.

```
$> git clone https://github.com/mapsplugin/cordova-plugin-googlemaps

$> git checkout multiple_maps

$> git pull

$> cd (project dir)

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add (path to)/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..." 

```

<img src="https://user-images.githubusercontent.com/167831/33693874-0da697be-daaa-11e7-9fc0-204048550a03.gif" width=250">

**Comment by wf9a5m75** [comment]
ping

**Comment by gabolucuy** [comment]
excellent! i will try the solution this night or tomorrow! thanks @wf9a5m75 !

**Comment by gabolucuy** [comment]
off topic, if for example I push a new page in any of tabs, and in that new page I want to display a map, it wont work right? because the view becomes transparent I'm able to see the previous page of the navigation stack.

**Comment by wf9a5m75** [comment]
No. Ionic keeps old pages even if you open a new page when you use ionic-tab.
So there are two maps, in old page, and in new page.
But the old page is not removed, the map in the old page still remained.

So you will see two maps if you create a map in a new page.

**Comment by gabolucuy** [comment]
ok, so maybe I found another bug, because in the same app when I added a new page for example in the profile tab, and add a map in the new page, the page becomes trasparent and the previous page is visible, but in console I can check that the map was succesfully created. I can upload in a brach of the project an example in a few hours.

**Comment by wf9a5m75** [comment]
ping

**Comment by gabolucuy** [comment]
@wf9a5m75 sorry the possible bug i mentioned was a bad use of the map, so its ok, but when I download the plugin of the multiple maps brach the geolocation stops working on android devices, and on android 4.4.4 the bug is still remained.

**Comment by wf9a5m75** [comment]
I don't support the compatibility with other plugins.

**Comment by gabolucuy** [comment]
ok thanks for resolving the issue @wf9a5m75
