### ISSUE TITLE
[iOS, Question] Random "malloc: * error for object 0xXXXXX: pointer being freed was not allocated"

### ISSUE THREAD

**Issue by thiphariel** [mapsplugin/cordova-plugin-googlemaps#1931]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

I'm currently using the latest `multiple_maps` branch

My question : 
Why do you run this code in a background thread ? https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/PluginPolyline.m#L105
Is it wanted for something ?

I'm asking that because, sometimes, it makes my app crash because the `self.mapCtrl.objects` dictionary is mutated in both thread [here](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/PluginPolyline.m#L101) and [here](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/PluginPolyline.m#L131)

If I remove the code execution from the background thread, the app isn't crashing anymore randomly and it not seems to affect the speed of the Polyline drawing.

Here is some information about it : https://stackoverflow.com/questions/16974368/nsmutabledictionary-with-two-keys-pointing-to-same-object-causing-double-free#comment24521155_16974368

Again, it's just a question about your way of doing things, maybe you did this way for a good reason that I don't see because I did not build this plugin.

Thanks :)

**Comment by wf9a5m75** [comment]
Thank you for asking, but I have never seen the error (and there is no reported except you).

First of all, you may need to know that all code for Google Maps have to run on UI thread, even accessing to the property, such as `marker.getTitle()`.

But Android and iOS have only one UI thread. So the code should run in background thread as much as possible.

If you share your project files on github, I will check it.

Unfortunately, current your report is not enough to detect the issue.

**Comment by thiphariel** [comment]
I know, but why you did not put all the code related to the Polyline creation (L.74 to 102[here](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/PluginPolyline.m#L74-L102)) on the background thread too ?

I'm not opening that issue as an error reporting as I said, I wanted to know your point of view about it and why you choose this way.

I already fixed my problem by moving the dictionary mutation in the background thread too so that both mutations are in the same thread.

**Comment by wf9a5m75** [comment]
`dispatch_async(dispatch_get_main_queue(), ^` run on UI thread.

**Comment by thiphariel** [comment]
`[self.mapCtrl.executeQueue addOperationWithBlock:^{`and this one in a background thread, so they can both trying to mutate `self.mapCtrl.objects` at the same time, on different thread. 

That's why I get an error I guess ?

**Comment by wf9a5m75** [comment]
If the error occurs (I haven't never seen the error though), that might be one of the reason.

However `malloc` error usually occurs when the device is out of memory.
So there is possibility that you created lots of overlay, or your UI is heavy, etc.

**Comment by thiphariel** [comment]
Yep I know, but this one is explicit : **pointer being freed was not allocated** is not an error about memory leaking, missing or something.

With some words : The system try to free the pointer without being allocated.

If you want, I gonna try to deep in that tomorrow with some `malloc_error_break` to see if I can retrieve more info about it.

And yeah, I display "a lot" of Polyline on the screen, so the UI thread and the background thread are maybe a bit lost :)

**Comment by wf9a5m75** [comment]
Unfortunately, you don't share your code, I can not debug further more.

Although you are just asking, if you share your project files on github, I will try to reproduce your issue in order to solve the problem completely.
By the way, I'm not interested in your business at all.
So if you share your project files as private repository, I don't leak your code.

Otherwise, there is no further action at this time.
But the additional information debugging from you is appreciate.

**Comment by wf9a5m75** [comment]
Thanks. In that case, I don't change the code at this time because there is no enough information.
But I will keep this thread in mind.

**Comment by thiphariel** [comment]
Same as I am. I noticed this issue in my project and if I have something relevant to this I will reopen and give you some related code to reproduce if needed.

Thanks for arguing with me.

**Comment by wf9a5m75** [comment]
Thank you for nice arguing.
