### ISSUE TITLE
google map lose from go back index page framework7

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#1932]
hi im trying to implement this pluggin with framework7  when i have 2 pages
my index with (require.js) and contact.hml , when i click item from listen on index page for redirect to contact.html like a detail, and go back from detail to index.php i cant see the map ...

i have read many issues from here like #1541 but i havent get solution, i hope you help me

this is my repository https://github.com/dsemerida/framework7issue

**Comment by wf9a5m75** [comment]
I'm not familiar with framework7 at all.

Please share your project files on github. I will check it. Otherwise, no further action.

**Comment by dsemerida** [comment]
thanks for respond me  https://github.com/dsemerida/framework7issue

**Comment by wf9a5m75** [comment]
Oh,,, please do not archive with rar file...

**Comment by dsemerida** [comment]
how do you want?

**Comment by wf9a5m75** [comment]
Without compression, just commit all files to github.

**Comment by dsemerida** [comment]
ready i have been upload the files, check please

**Comment by wf9a5m75** [comment]
Well, I only see the `www.rar` file still now.
![screen shot 2017-12-01 at 4 27 23 pm](https://user-images.githubusercontent.com/167831/33509233-a3b61896-d6b4-11e7-82a1-c5e447b2ca14.png)

**Comment by wf9a5m75** [comment]
So what I want you do :

```
$> cd (your project folder)

$> git add .

$> git commit -m "add all files"

$> git push
```

**Comment by wf9a5m75** [comment]
And even I tried to extract the `www.rar`, the extract software says `it is not RAR archive`...

**Comment by dsemerida** [comment]
ok, sorry, its ready all files are on www

**Comment by wf9a5m75** [comment]
Thank you.
And also config.xml file please.

**Comment by dsemerida** [comment]
ready!

**Comment by wf9a5m75** [comment]
Thank you. By the way, did you test the multiple_maps branch?

There are two versions on this repo.

The master branch is stable version. The same as npm. The current version is `v2.1.1` ( you use this version)

But the multiple_maps branch is develop version. Which is next version that contains many fixes.
If you didn't know or didn't try it, please try it.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
```

**Comment by dsemerida** [comment]
this command install version 2.1.1?

**Comment by wf9a5m75** [comment]
No, currently `2.1.2-beta-20171130-1100`
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/plugin.xml#L2

**Comment by dsemerida** [comment]
i have install , do you thing if my issue is where is change of page ? or the problem is on the pluggin? how is the correct form to implement google maps multiple?

**Comment by dsemerida** [comment]
![4a9ef17e-4f81-4919-8f75-e89a2b4ffe46](https://user-images.githubusercontent.com/17621449/33509720-affffe90-d6c9-11e7-8449-c99533abb1bf.jpg)

this is the index when i go back to index

**Comment by wf9a5m75** [comment]
I just built and run your project files with the `v2.1.1`, and confirmed it.
I guess the framework7 uses `translate3d` css. That's the reason I guess.

**Comment by wf9a5m75** [comment]
Inspecting.

**Comment by dsemerida** [comment]
you have  reason but i still havent get the solution

**Comment by wf9a5m75** [comment]
Yes, that's why I wrote `inspecting`.

**Comment by wf9a5m75** [comment]
Ok, I got the reason. You need to hide this element in your code.

![screen shot 2017-12-01 at 5 23 39 pm](https://user-images.githubusercontent.com/167831/33510047-689d4a38-d6bc-11e7-8b75-e3f9d7664a25.png)

**Comment by dsemerida** [comment]
yeah i have been set translate3d 100 to the class panel left, thanks man!!

**Comment by wf9a5m75** [comment]
By the way, your app exits when I press the `backbutton` of Android.

You need to register your function like this:

```
document.addEventListener("backbutton", function() {
  backPage();
});
```

**Comment by wf9a5m75** [comment]
Did you solve your problem everything?

**Comment by dsemerida** [comment]
Yeah friend so thanks! Back button for what do i have to have?

**Comment by wf9a5m75** [comment]
```
document.addEventListener("backbutton", function() {
  backPage();
});
```
