### ISSUE TITLE
"Navigate to" and "Open in google maps" buttons on iOS

### ISSUE THREAD

**Issue by ciclick** [mapsplugin/cordova-plugin-googlemaps#1933]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

On Android when a marker is clicked two buttons are shown ("navigate to" and "open in google maps"), but on iOS that not happen. Is possible to show that buttons on iOS too?

**Comment by wf9a5m75** [comment]
No. That buttons come from the navtive api. And Google does not implement it in iOS.

**Comment by ciclick** [comment]
Ok, thank you!
