### ISSUE TITLE
Custom OverlayView

### ISSUE THREAD

**Issue by gomexa** [mapsplugin/cordova-plugin-googlemaps#1934]
**I'm submitting a ...**  (check one with "x")
[X] question
[ ] any problem or bug report
[ ] feature request

I've been trying to create a custom OverlayView to insert CSS customizable markers, using the JS API this is easy, but I can't find any way to do this with the plugin or ionic-native. So I wonder if there's something I can do to get my custom OverlayViews to work.

**Comment by wf9a5m75** [comment]
Not possible. Because this plugin does not use the Google Maps JavaScript API v3.
This plugin uses Google Maps Android API v2 and Google Maps SDK for iOS, which are drawn in OpenGL, not HTML.
