### ISSUE TITLE
Error when update this plugin (multiple_maps branch)

### ISSUE THREAD

**Issue by minhui27** [mapsplugin/cordova-plugin-googlemaps#1935]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-googlemaps 2.1.2-beta-20171130-1100 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

```
@ionic-native/google-maps  4.3.3
@ionic-native/core  4.3.3
```

**Current behavior:**
Recently I was update this plugin to the latest version using the `multiple_maps` branch. When the app is updated, the error shown as below was come out very frequently.
![error](https://user-images.githubusercontent.com/18694106/33598797-faa9d6c4-d9de-11e7-9ddf-504229dd8d8f.JPG)
Consequently, the HTML element on the map become unclickable.

The demo project files:
[https://github.com/minhui27/map-v2-testing](https://github.com/minhui27/map-v2-testing)

**Comment by wf9a5m75** [comment]
Thank you for reporting. Your preparation is perfect, but I have been working on another issue recently. Please wait your turn. I will check one by one.
Thank you for your understanding.

**Comment by minhui27** [comment]
As I add in the `cordova-plugin-crosswalk-webview` plugin, the error above was removed. However, the map become white screen at this time. I found that the `MAP_READY` event was triggered, but the map is not showing on the app.

**Comment by minhui27** [comment]
The error above had been solved as I add in the `cordova-plugin-crosswalk-webview` plugin.
However, another new bug was exist.

The behavior is:
When I click the HTML element on the map, it will navigate to a new page.
The problem is where if the page is not navigate from the root component, the new page cannot be scrolled. When I navigate back to the map, the map is being dragged as much as I scrolled in the new page.
However, this problem is not exist if the page is navigate from the root component.

**In my project, the new page must not navigating from the root component.

Ref: [Ionic NavController](https://ionicframework.com/docs/api/navigation/NavController/)

**Comment by wf9a5m75** [comment]
Try `map.setClickable(false)` when you move to the next page.

**Comment by minhui27** [comment]
The problem was solved.
Thanks.

**Comment by wf9a5m75** [comment]
Any other problems do you have?

**Comment by minhui27** [comment]
Yes. But now I test first. Later when I confirmed the problem then I will post here again.

**Comment by minhui27** [comment]
@wf9a5m75  I already solved the other problems.
Thanks for your time.

**Comment by ugirishm** [comment]
Hello,

I am facing the same issue when running the app in older phones (Android 4.4.2). The other person seems to have resolved it by installing crosswalk webview, which we dont want to use. Any other solution?

Thanks,
Girish

**Comment by ugirishm** [comment]
Hi,
Did you get a chance to look at this issue? Please let me know if you want me to open a new issue for this.

Thanks,
Girish
