### ISSUE TITLE
[Question] What happen to an object (aka TileOverlay) after calling ".remove()" ?

### ISSUE THREAD

**Issue by thiphariel** [mapsplugin/cordova-plugin-googlemaps#1936]
**I'm submitting a ...**
[x] question
[ ] any problem or bug report
[ ] feature request

Hi.

What exactly happen to an object (like a TileOverlay) when you call `remove()` on it ? The map removes it but then, is the object destroyed ? If I create another TileOverlay on the map, I should only one object on it, that's right ?

Thanks for explain to me :)

**Comment by wf9a5m75** [comment]
Well, source code is fully open, and you can read the code at least Objective-C, so I appreciate if you try to read the code at once.

The code starts from here.

**Step1:**
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/6ea3f65673bd89661f03dfc3fa594e74260a39b7/www/TileOverlay.js#L109-L125

In the step1, the code separates two path:
- `self.trigger(self.id + "_remove");` and
- `exec.call()`

`self.trigger(self.id + "_remove");`  is listened at here for memory cleanup in JS side.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/6ea3f65673bd89661f03dfc3fa594e74260a39b7/www/Map.js#L1203

`exec.call()` involves  `(void)remove:(CDVInvokedUrlCommand *)command` of `PluginTileOverlay.m`.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/6ea3f65673bd89661f03dfc3fa594e74260a39b7/src/ios/GoogleMaps/PluginTileOverlay.m#L198-L215 


**Step2:** Try it.

**Comment by thiphariel** [comment]
Thanks for explained to me. I read both Java and Obj-C code, but I'm really not familiar with Cordova plugins.
I did not get the JS side at the first time, that why I prefered to ask.

It's now clear, thanks.
