### ISSUE TITLE
Setting saturation options for POI icons makes them disappear

### ISSUE THREAD

**Issue by cburnicki** [mapsplugin/cordova-plugin-googlemaps#1939]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-appminimize 1.0 "AppMinimize"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-settings-hook 0.2.7 "Cordova Settings Hooks"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**from my package.json**
```
"@ionic-native/core": "^3.12.1",
"@ionic-native/google-maps": "^4.4.2"
```

**Current behavior:**
Changing the saturation of a POI icon in the mapStyle json makes them disappear. This seems to be the case if any saturation option is set (even the default value of 100). Although I haven't tested all options, this seems to happen for other map icons as well.

**Expected behavior:**
Map icons should be shown with modified saturation.

**Screen capture or video record:**
![screenshot_20171208-151254](https://user-images.githubusercontent.com/11300772/33769808-d833eb3a-dc2b-11e7-8179-4104fe02710d.png)
![screenshot_20171208-151518](https://user-images.githubusercontent.com/11300772/33769835-eedcb858-dc2b-11e7-9986-6c59aaab01c4.png)

**Related code, data or error log (please format your code or data):**
mapStyle.json where icons are not shown:
```
[
  {
    "featureType": "poi",
    "elementType": "labels.icon",
    "stylers": [
      {
        "saturation": 100
      }
    ]
  }
]
```
For the screenshot where map icons are shown, I used an empty array in my mapStyle.json

Thanks for your great work!

**Comment by wf9a5m75** [comment]
Ask to Google, please. This plugin just passes the styled json to the native api.
