### ISSUE TITLE
Markers events don't fire (and maybe more issues)

### ISSUE THREAD

**Issue by arimk** [mapsplugin/cordova-plugin-googlemaps#1942]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[X] **Android**
[X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.0 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

ionic-native/google-maps: "4.4.2"
ionic-native/core": "4.4.2",

**Current behavior:**
Events on Markers do not work (not sure if it is the only issue).

**Expected behavior:**
Now this should work.
I see the markers fine on the map, i can clic and i see the popup, but my events are never fired (even the console log).
And (maybe it is related or not) - an error on log (via chrome dev tools)

**Related code, data or error log (please format your code or data):**

Code is as follow

```
import {
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  GoogleMapOptions,
  CameraPosition,
  MarkerOptions,
  Marker
 } from '@ionic-native/google-maps';

[...]

map: GoogleMap;
  mapElement: HTMLElement;
  notificationsCount: number;

[...]

loadMap() {
    this.mapElement = document.getElementById('map');

    let mapOptions: GoogleMapOptions = {
      camera: {
        target: {
          lat: 46.379933,
          lng: 2.8374617
        },
        zoom: 5
      }
    };

    this.map = new GoogleMap(this.mapElement, mapOptions);

    this.map.one(GoogleMapsEvent.MAP_READY)
    .then(() => {
      console.log('Map is ready!');
      this.api.getClubs().subscribe(response =>{
        response.forEach((club) => {
          let icon = "www/assets/imgs/map_club_icon3.png";
           if  (club.total_members_count < 12) {
              icon = "www/assets/imgs/map_club_icon2.png";

           }

           if  (club.total_members_count < 6) {
            icon = "www/assets/imgs/map_club_icon1.png";

          }
          
          this.map.addMarker({
            title: club.club_name,
            icon: {
              url: icon,
            size: {
              width: 20,
              height: 24
              }
            },
            animation: 'DROP',
            position: {
              lat: club.lat,
              lng: club.lng
            },
            
          },
        
        )
          .then( (marker) => {
            //console.log(marker);
            marker.on(GoogleMapsEvent.MARKER_CLICK)
              .subscribe(() => {
                console.log("CLICK");
                this.presentClubModal();
              });

             });
          
  

        });
      
      });
      

    });
}
```

And I have an error log as follow : 
For every marker (even though they do show...) 

```
polyfills.js:3 Uncaught TypeError: Cannot set property 'marker_196468382' of undefined
    at Map.<anonymous> (vendor.js:84436)
    at Map.<anonymous> (Map.js:1010)
    at googlemaps-cdv-plugin.js:726
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask (polyfills.js:3)
    at i.isUsingGlobalCallback.invoke (polyfills.js:3)
    at n (polyfills.js:3)
```

I don't get why it happens, it is exactly following the demo.
Do you have any idea?

**Comment by wf9a5m75** [comment]
Since your code is wrong, the plugin does not work correctly.

Please share your project files on GitHub. I will check it later

**Comment by arimk** [comment]
I don't have the whole project on github (tens of pages,big app...)
Can i just give you the .ts file?
But if you know my code is wrong, what is wrong with it?

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, I need whole code. You can create a private repository at bitbucket.org as free.

**Comment by arimk** [comment]
Can't share the whole code....
I will try to get you a sample app with just this page, see if it works.
Thanks

**Comment by arimk** [comment]
Alright!
I created a small demo, just with this part --> https://github.com/arimk/TestIonicMap
I removed my credentials from

```
<plugin name="cordova-plugin-googlemaps" spec="^2.1.1">
        <variable name="API_KEY_FOR_ANDROID" value="xxxx" />
        <variable name="API_KEY_FOR_IOS" value="xxx" />
   </plugin>
```

Now with this demo,i got the same issue and result

Uncaught TypeError: Cannot set property 'marker_250022885' of undefined

I hope it's just a mistake somewhere on my side,  I don't have any idea...

**Comment by wf9a5m75** [comment]
I confirmed the reason is you write 

```
this.map = new GoogleMap(this.mapElement, mapOptions);
```

instead of 

```
this.map = GoogleMaps.create('map', mapOptions);
```

**Comment by arimk** [comment]
Yes thank you! Great!
