### ISSUE TITLE
Is it possible to handle My Location and My Location button separately?

### ISSUE THREAD

**Issue by battika** [mapsplugin/cordova-plugin-googlemaps#1948]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[x] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
"@ionic-native/core": "4.5.2",    
"@ionic-native/google-maps": "4.5.2"

**Current behavior:**
Currently, setMyLocationEnabled() both enables/disables the my location layer with the blue dot and the gray button on the map.

In PluginMap.m (IOS):
```
(void)setMyLocationEnabled:(CDVInvokedUrlCommand *)command {
[[NSOperationQueue mainQueue] addOperationWithBlock:^{
Boolean isEnabled = [[command.arguments objectAtIndex:0] boolValue];		      
self.mapCtrl.map.settings.myLocationButton = isEnabled;
self.mapCtrl.map.myLocationEnabled = isEnabled;
    }];		    }];
```

In PluginMap.java (Android)
```
  final Boolean isEnabled = args.getBoolean(0);
    this.activity.runOnUiThread(new Runnable() {
      @Override
      public void run() {
        try {
          map.setMyLocationEnabled(isEnabled);
        } catch (SecurityException e) {
          e.printStackTrace();
        }
        map.getUiSettings().setMyLocationButtonEnabled(false);
        callbackContext.success();
      }
    });	
```

I'm wondering if it was possible to support the my location layer without actually displaying the button. It is because the grey button is rather big and it does not blend into the style of most applications. Eg. I would like to put my location button in the menu bar instead.

At the moment I need to fork this repo and manually remove the button every time you have a new  release, hence the request.

Great plugin otherwise, thank you for your work.

**Comment by wf9a5m75** [comment]
Please search the past conversation.

**Comment by battika** [comment]
I found  this one the most relevant
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1612

which starts with a very "star wars"-y upbeat :-)

> Long long long time ago, I decided this plugin provides the myLocation button assigned with the blue dot.
> Because there were no way to show only the myLocation button in Android (I haven't checked this behavior recently though).
> 

I guess noone really wants to show the myLocation button only without the layer enabled. I think the real use case is remove the button so that it won't hurt screen aesthetic.

But if you don't intend to implement an optional second boolean parameter to keep/remove the my location button, please close this issue and I will keep forking the library every time there is  a new release.
Thank you.

**Comment by wf9a5m75** [comment]
I inspected, but Google does not allow to set `map.getUiSettings().setMyLocationButtonEnabled(true);` with `map.setMyLocationEnabled(false);` on Android.

In that case, the map does display the blue dot.

![](https://cloud.githubusercontent.com/assets/167831/5052171/ebe585a0-6bf2-11e4-8e6c-58ff462474af.png)

![](https://cloud.githubusercontent.com/assets/167831/5052197/1eb0b540-6bf3-11e4-890d-ee55047366e3.png)

**Comment by battika** [comment]
Thanks, I will then continue fork your code with every new release. You might want to close this request. Thanks again.

**Comment by wf9a5m75** [comment]
Thank you for understanding, and using the maps plugin.

**Comment by fablrdigital** [comment]
This is SO important for anyone who wants to brand the map differently.

The reason you've stated for you not to do this is because you can't show the button without also showing the location.

But this is _the opposite_ of what everyone wants. They want to show the location but no button, and this is possible on all devices, as you've already pointed out. It just isn't implemented on your version of the app, despite the fact it's a key part of the document for the native APIs.

Is this really something you cannot do?

**Comment by battika** [comment]
I tried to make my point regarding this request multiple times. My app also requires removing the super ugly grey my location button but show the actual location on the map. So I ended up git cloning this repo, making a new branch, removing the location button in that branch and installing the plugin from the local directory. Every time there is a new commit (like every day), I go ahead and git merge all changes from multiple branch into my development branch and reinstall the plugin from the local directory again.

**Comment by fablrdigital** [comment]
Thanks for the advice. It is a great plugin. Just minor frustrations like this. :)

**Comment by wf9a5m75** [comment]
https://developers.google.com/android/reference/com/google/android/gms/maps/UiSettings#setMyLocationButtonEnabled(boolean)

The official document (Google) says,

> Enables or disables the my-location button. The my-location button causes the camera to move such that the user's location is in the center of the map. If the button is enabled, it is only shown when the my-location layer is enabled.

It means `until you enable the my-location button, you can not display the blue dot`

**Comment by wf9a5m75** [comment]
Ok, I managed to implement the myLocation and the myLocationButton option finally.

Try like this with the multiple_maps branch version.

```
plugin.google.maps.Map.getMap(mapDiv, {
  controls: {
    myLocation: true,
    myLocationButton: false
  }
});
```

**Comment by battika** [comment]
Yeah, no more git merge! Thanks a lot.

**Comment by fablrdigital** [comment]
Thank you! :) Great work and much appreciated. It must be hard just hearing people complain all the time. ;)
