### ISSUE TITLE
Disable location

### ISSUE THREAD

**Issue by nitrique** [mapsplugin/cordova-plugin-googlemaps#1950]
Hey guys,

Did someone know how to disable location, I don't need that and the message is not user friendly.

I'm sorry but I don't find it in the doc...

Thanks a lot,
Nicolas

**Comment by wf9a5m75** [comment]
```
var div = document.getElementById("map_canvas2");
var map = plugin.google.maps.Map.getMap(div, {
  'controls': {
    'myLocationButton': false
  }
});
```

**Comment by nitrique** [comment]
I tried, but it doesn't disable the message showing "index.html would like to access your current location...", right ?

**Comment by wf9a5m75** [comment]
I guess you use other plugins, such as geolocation.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by nitrique** [comment]
Hello,
Same problem with location button disabled. Cordova geolocation disabled same error.

**Comment by wf9a5m75** [comment]
I don't support the compatibility with other plugins

**Comment by wf9a5m75** [comment]
Ok, please share your project files on github.

**Comment by nitrique** [comment]
Allright, sorry bro, it was a incompatibility between cordova-geolocation and angularjs...

I really Apologize for this.
