### ISSUE TITLE
多くのポリラインを描画しようとした際にクラッシュする

### ISSUE THREAD

**Issue by yu-nakata** [mapsplugin/cordova-plugin-googlemaps#1953]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

```

**Current behavior:**
こんにちは、初めまして。
私はプラグインを使用してMAP上に複数のマーカーとポリラインを描画するアプリを作成しています。
アプリのメイン機能となっているためかなりの数のポリラインを描画します。
（大体０〜５０００ぐらいでこれからも増えて行く見込みです）
そのポリラインを描画する際に何度かアプリがクラッシュしてしまいます。
再現率が100%でないため難しいとは思いますが解決策、回避策等はありますでしょうか？

何度かこの質問がissuesで上がっていましたが解決に至っていなかったようでしたので
半分諦めていますが・・・
お忙しいとは思いますがよろしくお願いします。

**Screen capture or video record:**
![2017-12-18 11 56 15](https://user-images.githubusercontent.com/34566488/34088086-85ec11a6-e3ea-11e7-8238-d006299f6d1d.png)

**Related code, data or error log (please format your code or data):**
https://github.com/yu-nakata/SampleMap
実アプリと実装を少しだけ近づけているためindex.htmlにmapを置いてcreateをしています。
Start demoボタンを押下でMarkerとPolyline（５０００ぐらい）を生成しています。

**Comment by wf9a5m75** [comment]
オーバーレイを描画する、ということはそれだけメモリを使います。5,000本というのは多すぎます。
UX/UIの観点から見ても、疑問です。
本当に5,000本のポリラインを描いた地図は、ユーザーとして使いやすいものでしょうか。

**Comment by yu-nakata** [comment]
返信ありがとうございます。
複数ルートを描画しているのでどうしても数が膨れ上がってしまいます。
ポリラインを引く際のポイントが500程度でもクラッシュ頻度はかなり下がりますが時々クラッシュしてしまいます。
やっぱり数を減らす以外回避策はなさそうですか・・・？

**Comment by wf9a5m75** [comment]
そうですね。それ以外は思い当たる点がないです

**Comment by wf9a5m75** [comment]
明日、時間があるときにテストしてみます

**Comment by yu-nakata** [comment]
夜遅くまでご対応頂きありがとうございます。
他の方法で解決、回避出来るとすごく助かります。

私の方でも引き続き色々と試してみます。

**Comment by wf9a5m75** [comment]
コードを変えてみましたので、試してみてください。
```
$> git clone https://github.com/mapsplugin/cordova-plugin-googlemaps

$> git checkout multiple_maps

$> git pull

$> cd (project dir)

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add (path to)/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..." 

```


-----

あと、home.tsですが、以下のようにすれば最初から地図が表示されます。

```
  loadMap() {

    // 表示したい位置にある<div>のidを指定します
    let mapElement = document.getElementById('map_canvas');
```

**Comment by yu-nakata** [comment]
早速試してみました。
サンプルアプリでも実際のアプリでも無事クラッシュしないようになりました。
本当にありがとうございました！
気持ち程度ですが、donateさせて頂きました。

本件クローズとさせて頂きます。

**Comment by wf9a5m75** [comment]
解決して良かったです。寄付していただきありがとうございます :)
