### ISSUE TITLE
Add INFO_CLICK event to markercluster

### ISSUE THREAD

**Issue by Lingomat** [mapsplugin/cordova-plugin-googlemaps#1954]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[x] feature request

Add INFO_CLICK event to markercluster. Currently it only supports MARKER_CLICK.

This can be done by simply changing line 1490 in multiple_maps branch, Map.js to:
```
if (eventName === event.MARKER_CLICK || eventName === event.INFO_CLICK) {
```
I'd PR it but that doesn't seem to be going very well...

**Comment by wf9a5m75** [comment]
Not acceptable. You have to add the evebt listetner to the clicked marker.

**Comment by Lingomat** [comment]
That works, but it's ugly. Requires more logic to address the possibility that someone would click on another marker, then reclick on that marker - thus adding two event handlers. But whatever. I get the picture.
