### ISSUE TITLE
poly.containsLocation(): not present in '@ionic-native/google-maps'

### ISSUE THREAD

**Issue by Biniot** [mapsplugin/cordova-plugin-googlemaps#1955]
**I'm submitting a ...**  (check one with "x")
[x ] question
[ ] any problem or bug report
[x ] feature request

the member Poly does not seem to be implemented in the plugin even though it is present in the ionic native documentation. How could I proceed in order to be able to make use of poly.containsLocation, without having to make my own algoythm?

thank you

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/ionic-googlemaps-demo/blob/master/src/pages/poly/contains-location/contains-location.ts
