### ISSUE TITLE
Multiple IOS rendering problems with multiple_branch in Ionic

### ISSUE THREAD

**Issue by battika** [mapsplugin/cordova-plugin-googlemaps#1957]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.1.2-beta-20171218-1109 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
    "@ionic-native/core": "4.5.2",
    "@ionic-native/google-maps": "4.5.2"
```
  
**Current behavior:**
I would like to achieve the following. I started a new Ionic project based on the sidemenu template. I added a new map and a button to the Home page. The button takes the user to the second page with push navigation that displays a second map and few lines of text. I want to preserve the home page map position so the home page remains the root page and I hide its map by calling ```this.map.setDiv(null)``` so that I can restore it when the user comes back to the home page. I also used couple of tweaks to make user experience smoother like material design for page transitions on IOS and the main menu is working in overlay mode and not the default the sliding animation that looks ugly when the maps plugin attempts to resize itself real-time while the menu is being opened.
Everything works more or less fine when the main branch (2.1.1) is being used but when I switch to multiple maps the following things will happen.
1. When I open the menu the map will catch all click events. It is only possible close the menu when I click the menu bar outside of the menu. Using version 2.1.1. the underlying map will not catch all clicks and it is possible to close the menu by clicking outside the menu area. I guess you will say I should catch menu open/close events and disable/enable map.setClickable() which I can do, but again,  it works flawlessly with the main branch.
2. When the second page is open and the second map has been rendered the original map appears in the background too. See screenshots.
Using multiple_maps branch: 
<img width="348" alt="screen shot 2017-12-19 at 14 53 01" src="https://user-images.githubusercontent.com/1209088/34160214-5a0a1320-e4cc-11e7-9a18-2abbe10f56e5.png">
Using v2.1.1.:
<img width="348" alt="screen shot 2017-12-19 at 14 37 28" src="https://user-images.githubusercontent.com/1209088/34160231-66a8c07c-e4cc-11e7-896e-a7ad22d01ff8.png">

**Related code, data or error log (please format your code or data):**

```
Sample project here:
https://github.com/battika/ionic-gmaps-test

Please switch to the multiple_maps branch version of the plugin before using it... 
```

**Comment by wf9a5m75** [comment]
You need to remove the map

**Comment by battika** [comment]
Is it a change from 2.1.1?

**Comment by battika** [comment]
Just checked the Android version of the plugin and the second issue does not occur with the multiple_maps branch there. The issue with the menu is  there though.

<img width="453" alt="screen shot 2017-12-19 at 16 45 01" src="https://user-images.githubusercontent.com/1209088/34165308-2fe9b360-e4dc-11e7-89dd-c41fcec55bb2.png">

**Comment by battika** [comment]
Hello @wf9a5m75, Do you now consider this a bug? Thanks in advance for your help.

**Comment by wf9a5m75** [comment]
Fixed. Please reinstall the plugin from the multiple_maps branch.
![1957](https://user-images.githubusercontent.com/167831/34395710-7e95fc58-eb17-11e7-94b6-fbd496bf9b3a.gif)

**Comment by battika** [comment]
Thank you Sir, it works much better now 👍
