### ISSUE TITLE
Ionic View map issue

### ISSUE THREAD

**Issue by ChelnokovaRuslana** [mapsplugin/cordova-plugin-googlemaps#1958]
When I launch App in ionic view, map doesnt work and display.
I tried to sketch up [cordova-plugin-crosswalk-webview,](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/Installation/crosswalk) but the result was the same and nothing changed.

**Comment by wf9a5m75** [comment]
Please share your project files on github. I will check it.

**Comment by ChelnokovaRuslana** [comment]
@wf9a5m75 , files shared. here is ionic-view id - 5a0577a4.

**Comment by wf9a5m75** [comment]
Thank you. Which file does contain your code? Your project files are different than generic ionic project files.

**Comment by ChelnokovaRuslana** [comment]
/src/app/core/aerial/aerial.component.ts
/src/app/core/aerial/aerial.component.html

**Comment by wf9a5m75** [comment]
Thank you. 

You need to execute `this.__mapInit(mapElement);` after the platform.ready()

And recommend way to create a map is

```
this.map = GoogleMaps.create('map');
```

**Comment by ChelnokovaRuslana** [comment]
still does not work

**Comment by wf9a5m75** [comment]
Oh, I got the reason. You use `v1.4.5` which is out-of-dated version. It is no longer supported, and `@ionic-native/google-maps` does not work with that version anymore.

**Comment by ChelnokovaRuslana** [comment]
it does not matter
plugin updated, still does not working.

**Comment by wf9a5m75** [comment]
`v2.1.1` and `v1.4.5` are completely different code.

**Comment by wf9a5m75** [comment]
`"@ionic-native/google-maps": "^3.14.0"` is too old.

Currently `"@ionic-native/google-maps": "4.5.2"

-----

You still specify `"cordova-plugin-googlemaps": "^1.4.5"` in the package.json file

**Comment by wf9a5m75** [comment]
I just add `@ionic-native/google-maps: 4.5.2` and `cordova-plugin-googlemaps: 2.1.1`.

![capture](https://user-images.githubusercontent.com/167831/34236572-0dd01d42-e5ad-11e7-8d5b-61f529264f3a.png)

**Comment by ChelnokovaRuslana** [comment]
There s no problem in launching on device or emulator.
Problem only in IonicView. Plugin updated to the last version, But on IonicView it doesnt work.
Thats App  code - 3c9ddfc5

**Comment by wf9a5m75** [comment]
Try the multiple_maps branch version.

**Comment by ChelnokovaRuslana** [comment]
still does not working.

**Comment by wf9a5m75** [comment]
Show me the screen record.

**Comment by wf9a5m75** [comment]
I'm NOT your friend, so if you don't provide proper information "how does not work", I don't support anymore.

**Comment by ChelnokovaRuslana** [comment]
https://drive.google.com/open?id=1tYfaibK_ZcPfHeSjThlW9NMAbrJlst42
The map should be displayed on "IonicView" or not?

**Comment by wf9a5m75** [comment]
Thank you for sharing the screen records.
Since the ionic view does not contain this plugin, the map is not displayed of course.

**Comment by ChelnokovaRuslana** [comment]
thank you for your message
