### ISSUE TITLE
Button Google Maps

### ISSUE THREAD

**Issue by ThalesMatoso** [mapsplugin/cordova-plugin-googlemaps#1959]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

Is it possible to remove the google maps icons that appear in the lower right corner of the map? I looked for google map options options and did not find it.

**Comment by battika** [comment]
I think your are referring the so called mapToolbar that can be disabled like this:


```
  // Change the map options
    map.setOptions({
      'mapType': plugin.google.maps.MapTypeId.HYBRID,
      'controls': {
        'compass': true,
        'myLocationButton': true,
        'indoorPicker': true,
        'zoom': true,
        'mapToolbar': true   // currently Android only
      },........
```

**Comment by thezakman** [comment]
Will be possible to disable the mapToolbar in iOS @wf9a5m75 ?

**Comment by wf9a5m75** [comment]
`'mapToolbar': true   // currently Android only`

**Comment by thezakman** [comment]
@wf9a5m75 what I mean is, if that function will ever be avaible or if there is a workaround to remove it from the plugins files, because in my app I have a fab button right over it. Where I don't want to move it away too look the same as Android version.

Thanks in advance.

**Comment by wf9a5m75** [comment]
Why don't you set `mapToolbar = false`?

**Comment by wf9a5m75** [comment]
iOS does not display the tool bar from the first.

**Comment by wf9a5m75** [comment]
The location button comes from the native sdk, not this plugin.
In order to disable it, `'myLocationButton': false`
