### ISSUE TITLE
Auto setClickable 

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1961]
how to make the map no clickable if any element go over it . and make clickabl when the element is disapear .
i made some javascript events to handle this like
$$('.panel-right').on('open', function() {
    map.setClickable(false);
});
but it is not reliable

**Comment by battika** [comment]
It should be handled automatically in 2.x, no need for calling setClickable() in theory. With 1.4 it used to be more complicated.

**Comment by wf9a5m75** [comment]
@bigbossmaher Please share your project files on github.

**Comment by bigbossmaher** [comment]
https://github.com/bigbossmaher/Parking2
 side panels event in www/js/my-app.js line 101

**Comment by bigbossmaher** [comment]
Is there any news , thanks ?

**Comment by bigbossmaher** [comment]
This is issue is solved , sorry , i deleted cordova

**Comment by wf9a5m75** [comment]
okay.
