### ISSUE TITLE
SetClickable bug after 1 min of inactivity

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1962]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ x] **Android**
[ ] **iOS**

**Current behavior:**

I mad setclickable false when the side panel is opened and false if the side panel is closed. 
But after 1 min of inactivity the setclickable is no longer working
See this short video 

https://youtu.be/AuKkrHrVmF4
.
```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by bigbossmaher** [comment]
https://github.com/bigbossmaher/Parking2
 side panels event in www/js/my-app.js line 101

**Comment by wf9a5m75** [comment]
merge to https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1961
