### ISSUE TITLE
Touch/Scroll event not handled properly when cordova-plugin-googlemaps is added to the project

### ISSUE THREAD

**Issue by stib** [mapsplugin/cordova-plugin-googlemaps#1964]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
I am using `cordova-wheel-selector-plugin` in my project and after I updated the `cordova-plugin-googlemaps` plugin I noticed that the scroll action for selector wheel is sent back to the main screen. I narrowed the problem to an **example project in github** `https://github.com/stib/wheel-select-google-maps` - this is a test project that is part of `cordova-wheel-selector-plugin`

**Expected behavior:**
The expected behavior is that the scroll action should be handled by the selector wheel.

As is, when you run the github sample project the selector wheel will work properly. But once you add the` cordova-plugin-googlemaps` plugin using this command 

```
cordova plugin add cordova-plugin-googlemaps \
    --variable API_KEY_FOR_ANDROID="..." \
    --variable API_KEY_FOR_IOS="..."
```
the scroll event is no longer handled by the selector plugin. I don't know if this is a `cordova-wheel-selector-plugin` issue or `cordova-plugin-googlemaps` and don't know enough to narrow that down further. Video capture below show the output without the `cordova-plugin-googlemaps` plugin and then with the `cordova-plugin-googlemaps` plugin

**Screen capture or video record:**

[GoogleMapsSelectorWheelIssue.mp4.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1587780/GoogleMapsSelectorWheelIssue.mp4.zip)

After adding the `cordova-plugin-googlemaps` the `cordova plugin ls` command gives the following

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```
`ionic info` output is as below
```
Cordova CLI: 7.1.0 
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS
Node Version: v6.9.1
Xcode version: Xcode 9.2 Build version 9C40b
```
and `cordova platform ls` gives the following output
```
Installed platforms:
  ios 4.5.4
```
Thank you for your help.

Sanjay.

PS: To be transparent, I have also submitted a similar question at `cordova-wheel-selector-plugin` but that is not a very active group so not sure when/if I will hear back.

**Comment by wf9a5m75** [comment]
Use the multiple_maps branch

**Comment by wf9a5m75** [comment]
```
$> git clone https://github.com/mapsplugin/cordova-plugin-googlemaps

$> git checkout multiple_maps

$> git pull

$> cd (project dir)

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add (path to)/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..." 
```

**Comment by stib** [comment]
Thank you @wf9a5m75 for the quick response. Appreciate it.

From the documentation it seems like I could also just use the command below to use the multi_map branch - will that be same or will that be any different from the instructions you have provided? 

I am curious what this multi_maps is and how this is different from the main branch and how it solves the problem I ran into - if there is any documentation I can read up on then please let me know as quick Google search for multimap didn't seem bring up anything relevant and there is not much documentation about it on the plugin page as well that I could find. Also, given that this branch seems to be in dev mode from the documentation, is this stable enough to be used in production code? Or can I go to an earlier version of released branch for stable code that will help address this issue? Is there any sense of when this branch may be released to production?

```
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps \
    --variable API_KEY_FOR_ANDROID="..." \
    --variable API_KEY_FOR_IOS="..."
```

Thanks,
Sanjay.

**Comment by wf9a5m75** [comment]
The multiple_maps branch is `development` version, not stable version.
I have been working on lots of things, the touch problem, performance, implementing new features...etc.

I can not guarantee the ETA for the next release. I just say "early next year".

Thank you for using the maps plugin.

**Comment by stib** [comment]
Thank you for your effort with this plugin @wf9a5m75
