### ISSUE TITLE
Crash with crosswalk (has code to demo)

### ISSUE THREAD

**Issue by grapemix** [mapsplugin/cordova-plugin-googlemaps#1965]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[X] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

├── @ionic-native/core@4.5.2
├── @ionic-native/google-maps@4.5.2

already tested on Samsung Note 4 and Samsung S7
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

Unable to show map, only white screen if cordova-plugin-crosswalk-webview is installed
Able to show map if cordova-plugin-crosswalk-webview is NOT installed

**Expected behavior:**

Able to show map, even if cordova-plugin-crosswalk-webview is installed

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

My sample repo can demo the white screen bug because of crash with crosswalk clearly: https://github.com/grapemix/test_googlemap

We've used this plugin since version 1.X and 2.0.0-X. After upgrading to 2.1.1, this plugin suddenly crash with crosswalk, but we don't know why. We already tried the multiple_maps branch, but still no luck. Since the version 2.0.0.X(NOT 2.0.0) of this plugin we used before is gone and we have to upgrade ionic for iOS 11, we cannot rollback to previous version of ionic + cordova-plugin-googlemaps plugin, so we cannot update our app until this problem is resolved. We tried to provide as much info as possible, we understand you are busy and hopefully our preparation can save you some time. Feel free to ask if you need any info. BTW, this plugin works perfectly in iOS. Thanks for your hard-work.

ps:  cordova-plugin-crosswalk-webview is very popular plugin in android platform. Lots of app will be incredibility slow without using it

**Comment by wf9a5m75** [comment]
Thank you for preparing.

First of all, you need to modify the `config.xml` file.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/crosswalk/README.md

then, you need to use the latest `@ionic-native/core` and `@ionic-native/google-maps`.

**package.json**
```
    "@ionic-native/core": "^4.5.2",
    "@ionic-native/google-maps": "^4.5.2",
    "@ionic-native/splash-screen": "4.5.2",
    "@ionic-native/status-bar": "4.5.2",
``

After that, you need to install the plugin from the multiple_maps branch.

```
$> git clone https://github.com/mapsplugin/cordova-plugin-googlemaps

$> git checkout multiple_maps

$> git pull

$> cd (project dir)

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add (path to)/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..." 
```

![1965](https://user-images.githubusercontent.com/167831/34404900-1623c9a4-eb65-11e7-9197-1e75dd605f76.gif)

**Comment by grapemix** [comment]
Sorry for the late reply. We were able to confirm your solution works for the sample repo last night, with and without switch to multiple_maps branch. However, we were blocked by another crosswalk + gradle bug. Now we can confirm your solution also works in our app. Thanks so much. Actually, you already show this solution a few times, sorry for missing the tips you given, but "white screen" is too generic and the "crosswalk" term does not show up. May be adding the [link](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/crosswalk/README.md) in the readme of cordova-plugin-googlemaps can save you some time? I feel sorry to see you to answer these kind of dumb question again and again.

Thanks again.

**Comment by wf9a5m75** [comment]
Well, there is already link in the v2.0 top page.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0

![screen shot 2017-12-28 at 12 33 51 pm](https://user-images.githubusercontent.com/167831/34422655-88ae3afc-ebcb-11e7-9d84-b043a325ae80.png)

**Comment by grapemix** [comment]
What I mean is put the link in the cordova-plugin-googlemaps instead of cordova-plugin-googlemaps-doc repo. We never aware there has a cordova-plugin-googlemaps-doc repo which contained valuable info. May be it is just us. And this is just a friendly suggestion.
