### ISSUE TITLE
conflict with firebase auth

### ISSUE THREAD

**Issue by mianfrigo** [mapsplugin/cordova-plugin-googlemaps#1969]
i was trying to work with native google map of ionic to add map in my porject, after install `ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"` and `npm install --save @ionic-native/google-maps` the app start with some bugs so i toke the decition of remove the plugin, after remove the plugin for some reason i get this error from firebase `auth/network-request-failed` on the emulation of the device when i try any kind of firebase auth to login the user, but when i run the project with ionic serve -l doesn´t show me any error. Any idea what could be happen.

note: if i install the ionic native plugin of google map the auht error is gone but the bug is back so i have no idea what can i do in this case.

**Comment by wf9a5m75** [comment]
Ask to the firebase plugin developer.
