### ISSUE TITLE
HTML Elements Not Clickable On Map

### ISSUE THREAD

**Issue by labhollow** [mapsplugin/cordova-plugin-googlemaps#1970]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[X ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-googlemaps 2.1.2-beta-20171227-2046 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

ionic-native/core": "^4.4.2",
ionic-native/google-maps": "^4.4.2",

**Current behavior:**
In my app, once markers are loaded, and you click on one, a html card slides up that can be expanded or closed via swipe-up or swipe-down. This works on the first marker that is clicked, but if you select a different marker, and try to swipe-up, the html is not touchable and the map moves under the html card.

Also, when navigating tabs, the map moves under the view. To fix this, I have to set map clickable to false when entering the tab view and then set map clickable to true when navigating back to the map tab.

Finally, there is an issue when navigating to a tab, then back to the map tab where the map is blank (all white background). I have a workaround that sets the div back using this.map.setDiv('map_canvas'), but it seems like a hack fix.

**To load the map points, please LONG_CLICK the map.

I have given you access to my repo here:
https://github.com/labhollow/claim-explorer

Thank you.

**Expected behavior:**

The html elements should be clickable on the map and navigation between tabs should not affect the map and other html elements.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Try the version `2.1.2-beta-20171231-1822`
![1970_uncompress](https://user-images.githubusercontent.com/167831/34465198-feb0dbf4-ee57-11e7-8d11-7525346b7078.gif)

**Comment by labhollow** [comment]
Works great. Thank you and Happy New Year!
