### ISSUE TITLE
Trigger click event on marker

### ISSUE THREAD

**Issue by piernik** [mapsplugin/cordova-plugin-googlemaps#1972]
Can I tirgger click event on marker?

I know that I can `marker.showInfoWindow();` but when clicking on marker there is also google's direction and map buttons in bottom right corner.
Those are not shown using `showInfoWindow`.

**Comment by wf9a5m75** [comment]
`marker.trigger(plugin.google.maps.event.MARKER_CLICK, marker.getPosition())`
