### ISSUE TITLE
Marker click event problem on Quick Demo example

### ISSUE THREAD

**Issue by simetin** [mapsplugin/cordova-plugin-googlemaps#1973]
[ ] question
[X] any problem or bug report
[ ] feature request

[ ] **Android**
[X] **iOS**

Hi ! For a little while now I had the problem in my app where the click event promise of the markers doesn't fire up. I downloaded the [Quick Demo](https://github.com/mapsplugin/ionic-googlemaps-quickdemo) to try it out, but the problem is present there too.

Current behavior:
On the Home Page, I can add the marker and when I click on it only the Info Window appears, not the toast. If I add the icon option to the add marker function (e.g. icon: 'blue') the click event is working.

[Here is an example](https://drive.google.com/open?id=1HOGJ6pp4ogggIhUVh4pxONiVrmzK9J2R) 

Expected behavior: 
When I click on the marker a toast should appear.

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by simetin** [comment]
The project is an exact clone of the Quick Demo provided in the official documentation. I just installed all the dependencies and compiled the project on my iPhone, but if you still want my project files I can upload them, no problem.

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by simetin** [comment]
Here is the link to my repo: [https://github.com/simetin/googlemapsquickdemo](https://github.com/simetin/googlemapsquickdemo)

**Comment by wf9a5m75** [comment]
Did you try the `multiple_maps` branch version?

**Comment by simetin** [comment]
Just tried it on the Quick Demo and it worked, however now that I've changed the plugin in my app the map freeze just after creation, but this problem is out of scope for this issue. I'll look into it.

Thanks for your time :)
