### ISSUE TITLE
remove markers from markerCluster

### ISSUE THREAD

**Issue by dimitrisTheof** [mapsplugin/cordova-plugin-googlemaps#1975]
I'm submitting a
[x] question
[ ] any problem or bug report
[ ] feature request

Happy New Year!
Is it possible to remove one or some specific markers from a marker cluster?

**Comment by wf9a5m75** [comment]
```
markerCluster.on(plugin.google.maps.event.MARKER_CLICK, function (position, marker) {
  marker.remove();
});
```

**Comment by dimitrisTheof** [comment]
Thank you!! It is clear.

Now I try to add a marker in marker cluster with the following

markerCluster.addMarker(myMarker);

but the if I don't move the map a little, the marker is not visible.
If I move the map the marker normally displayed.
Is this a bug? 

I tried the following cases but it happens the same
markerCluster.addMarker(myMarker);
--
markerCluster.addMarker(myMarker, true);
--
var markers = [myMarker];
markerCluster.addMarker(markers , true);

**Comment by wf9a5m75** [comment]
Did you see the document page?
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/MarkerCluster/addMarkerCluster/README.md

**Comment by wf9a5m75** [comment]
ping

**Comment by dimitrisTheof** [comment]
Yes, of course I saw the documentation.
But as mentioned above I have this behavior in my app when a marker is added in my cluster.
Note that I do not add the marker in MARKER_CLICK event but I add the marker by a custom trigger.

Temporary I solve the problem with the following way:
When I want to add a marker in my cluster I call the with new list of markers

var markerListNew = markerListOld+newMarker;

map.addMarkerCluster({
    **
    markers: markerListNew,
    **
  }, function (markerCluster) {


});

What is your opinion about temporary solution? Is a bad way?
Also can you understand why when I try to add a marker with custom trigger event the marker is visible only when I move the map a little first?

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by wf9a5m75** [comment]
Marker cluster has `addMarker()` method.

You probably don't understand why the marker cluster takes the locations when it is initialized.
Because the calculation takes longer time, but only once.

If you give the full location list when you create a marker cluster, the marker cluster calculates **in native side**.
However, if you add location later using `addMarker()`, the calculation is executed **in javascript side** which is slower than native side.

------

Some people do like this:


```
var  _markerCluster;

map.on(plugin.google.maps.event.CAMERA_MOVE_END, function() {
  _markerCluster.remove();

  map.addMarkerCluster({
     markers: newLocations
  }, function(markerCluster) {
    _markerCluster = markerCluster;
  });
});
```

But this is worst performance way.

**Comment by wf9a5m75** [comment]
ping

**Comment by dimitrisTheof** [comment]
Sorry for the delay
Thank you for your answer
