### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by sburnicki** [mapsplugin/cordova-plugin-googlemaps#1976]
Hey,

reading your code, I found the following typo, which tries to access `bodyRect.heihgt` instead of `bodyRect.height`, so it would add `undefined` to `bodyRect.top`.

See 

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a7cbd205473e9528fb50a84a66d6f07dde53bdf1/www/googlemaps-cdv-plugin.js#L348

**Comment by wf9a5m75** [comment]
Thanks.
