### ISSUE TITLE
remove specified marker

### ISSUE THREAD

**Issue by tuanvuf4** [mapsplugin/cordova-plugin-googlemaps#1977]
How can i remove marker that it was added ?
example: i added 10 markers, then i want to remove 1 marker after reload data
this.map.addMarker(markerOption) => this way just add marker on map.
And I try to create new marker instance but i faced a error : "_this._objectInstance.on is not a function"
let marker = new Marker(this.map, markerOption);
How can i resolve this problem ?

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub. I will check it.

**Comment by tuanvuf4** [comment]
hmm. this is outsource project so i dont have permission

**Comment by wf9a5m75** [comment]
In that case, please create a demo project that reproduce your issue 100%, then share it. Otherwise please debug by yourself.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update for a while, I close this thread.

**Comment by tuanvuf4** [comment]
I see setMap() method in google map api for web
https://developers.google.com/maps/documentation/javascript/examples/marker-remove
which method in our plugin work like that ?

**Comment by wf9a5m75** [comment]
This plugin does not use the Google Maps API v3

**Comment by wf9a5m75** [comment]
All documents are here.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

**Comment by tuanvuf4** [comment]
How can i create Marker instance ?
let marker = new Marker(this.map, {}); -> this cause an error _this._objectInstance.on is not a function

**Comment by wf9a5m75** [comment]
Could you ask after more reading documents?
https://docs.google.com/presentation/d/1zlkmoSY4AzDJc_P4IqWLnzct41IqHyzGkLeyhlAxMDE/edit#slide=id.p
