### ISSUE TITLE
Changing the marker icon works only once

### ISSUE THREAD

**Issue by MargaretaKusan** [mapsplugin/cordova-plugin-googlemaps#1978]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
```
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
    "@ionic-native/google-maps": "^4.5.0"

**Current behavior:**

Changing the icon of a marker more than once results in weird behaviour.
 I have a situation where I have multiple markers on my map. When the user clicks on one marker it changes the icon _(to indicate that marker is 'open'_) and opens the HTMLInfowindow. When the user clicks on some other marker - HTMLInfoWindow closes and I use the .setIcon again to change the icon back to 'inactive', but it stays in the previous state. 

**Expected behavior:**

**Related code, data or error log (please format your code or data):**
```
marker_inactive: MarkerIcon = { 
        url: 'assets/icon/inactive.png',
        size: {
            width: 19,
            height: 19
        }
};

marker_active: MarkerIcon = {
        url: 'assets/icons/active',
        size: {
            width: 27,
            height: 35
        }
};

private addMarkers() {
     let markerOptions: MarkerOptions = {
            title: title,
            icon: this.marker_inactive,
            position: {
                lat: latitude,
                lng: longitude
            }
      }
    
    this.map.addMarker(markerOptions).then(marker => {
           marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
                   marker.setIcon(this.marker_active);
                   this.changeIconToInactive(last_opened_index);
                   this.last_opened_index = index;
           });
           this.markers[index] = marker;
    });
}

 private changeIconToInactive(last_opened_index) {
        this.markers[last_opened_index].setIcon(this.marker_inactive);
}
```

I tried setting all markers to inactive also, not only keeping the index of last opened, but it didn't work either. It seems that I can change the marker icon only once (?)

**Comment by wf9a5m75** [comment]
Please share your project files on Github.

**Comment by wf9a5m75** [comment]
And make sure your image files are really exist on these file paths:

'assets/icon/inactive.png' and 'assets/icons/active'

**Comment by wf9a5m75** [comment]
ping

**Comment by MargaretaKusan** [comment]
Sorry, I was away over the weekend. Here is a small test project for you: https://github.com/MargaretaKusan/Google-Maps-Test

**Comment by wf9a5m75** [comment]
Thank you for sharing your repo, but why do you try to change the icon for the same marker?

https://github.com/MargaretaKusan/Google-Maps-Test/blob/5bc372f567c8b0e38a6b40148bec1293779fa54c/src/pages/maps/maps.ts#L125-L128

Did you check how this plugin handles statements?
https://docs.google.com/presentation/d/1zlkmoSY4AzDJc_P4IqWLnzct41IqHyzGkLeyhlAxMDE/edit#slide=id.g282d0a7bfd_0_576

**Comment by wf9a5m75** [comment]
Here is what happened with your code.
![screen shot 2018-01-08 at 4 49 45 pm](https://user-images.githubusercontent.com/167831/34699770-00af098e-f494-11e7-86d7-9ad254eedd7a.png)

![screen shot 2018-01-08 at 4 50 36 pm](https://user-images.githubusercontent.com/167831/34699787-14c1e4d2-f494-11e7-9dd1-96d752a15508.png)

It seems your code is problem.

**Comment by wf9a5m75** [comment]
Wow, this is very beginner mistake.
Since you don't set the initial value for `this.lastOpenMarkerIndex`,
`this.markers[this.lastOpenMarkerIndex]` is always fail.

Thus, you need to check the value.

```TypeScript
marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
  console.log("clicked on marker : ", marker);
  marker.setIcon(this.marker_active);
  if (this.lastOpenMarkerIndex !== undefined) {
    this.changeLastMarkerToInactive();
  }
  this.lastOpenMarkerIndex = index;
  console.log("--->active = " + this.lastOpenMarkerIndex);
});
```


**Please doubt your code first when you face any problem next time**.
![1978](https://user-images.githubusercontent.com/167831/34700388-c0be90f2-f497-11e7-8b56-a65e7127297b.gif)

**Comment by MargaretaKusan** [comment]
Wow, didn't expect that. I expected that first time it would be ignored since it was undefined, but later it would work since it is set after the first marker receives a click, however it seems that this is not the case. Anyways, I'm sorry to have bothered you. Thank you! Maybe the snippet helps someone who is trying to change the markers like this.
