### ISSUE TITLE
No map in the DIV

### ISSUE THREAD

**Issue by patrickboulay** [mapsplugin/cordova-plugin-googlemaps#1979]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-admob-sdklibs 2.1.6 "Google Mobile Ads SDK for Cordova"
cordova-background-geolocation 2.8.5 "BackgroundGeolocation"
cordova-plugin-admob-simple 3.3.4 "Cordova-Phonegap AdMob Plugin"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-buildinfo 2.0.1 "BuildInfo"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-globalization 1.0.8 "Globalization"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-vibration 2.1.6 "Vibration"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova-plugin-yanap 0.8.9 "Yanap"
cordova.plugins.diagnostic 3.7.2 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
es6-promise-plugin 4.1.0 "Promise"
┌──────────────────────────────────────────┐
│ Update available: 8.0.0 (current: 7.1.0) │
│ Run npm install -g cordova to update.    │
└──────────────────────────────────────────┘
```

**Current behavior:**
There is no map appearing on the screen since I update this plugin. I have a gray screen.
I also see no error in the console log.

**Expected behavior:**
See the map

**Screen capture or video record:**
![capture _2018-01-05-21-32-27](https://user-images.githubusercontent.com/26615013/34635634-4b742264-f260-11e7-87ce-78979b9ba4fd.png)

**Comment by wf9a5m75** [comment]
background must be transparent.

**Comment by wf9a5m75** [comment]
ping

**Comment by patrickboulay** [comment]
I will check tonight.. is it a difference between the v1 and v2 about the
transparent background?

Le 6 janv. 2018 5:10 PM, "Masashi Katsumata" <notifications@github.com> a
écrit :

**Comment by wf9a5m75** [comment]
v1 and v2 are completely different software.

**Comment by patrickboulay** [comment]
In my css file, I add this to the div of map-canvas and to my jquery mobile
page:
background-color:rgba(0,0,0,0.0);

Still not working..

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub. I will check it. Otherwise please debug by yourself.

**Comment by patrickboulay** [comment]
I will debug by my self.

If you tell me that only the map-canvas need to be transparent, that's
alright, I will debug my self! thanks!
