### ISSUE TITLE
The Empty Map Problem

### ISSUE THREAD

**Issue by dragonbane0** [mapsplugin/cordova-plugin-googlemaps#1981]
I'm submitting a ..
[ ] question
[x ] any problem or bug report
[ ] feature request

If you choose 'problem or bug report', please select OS: (check one with "x")
[x ] Android
[ ] iOS

I have seen countless issue reports similar to mine and tried to implement all the given solutions, but nothing is working for me. This is how the map is displaying in the Google emulator:

![Image of Yaktocat](https://image.prntscr.com/image/pf4N_cnOTYeOSHZ5H1kM6A.png)

The console has no obvious errors. The MAP_READY event fires correctly, yet no map. 
My Cordova version is 8.0.0 and im using the newest development version of the plugin (2.1.2-beta-20180103-1610). The Android API version is 27. 

I set the API Key to unrestricted in the Google Console and confirmed it several times that it is correct in the config.xml as well. The only difference is that the Google Console doesnt offer me the option of Google Maps Android API v2 but just Google Maps Android API.
  
PS: Curiously this old example apk exhibits the same problem even on a real device for me, although this might not be related and just due the Google API having changed: https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/top/phonegap-googlemaps-plugin-v1.2.5.apk

**Comment by wf9a5m75** [comment]
gray map is api key problem.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by dragonbane0** [comment]
Here are my enabled APIs:
![APIs](https://image.prntscr.com/image/X-dP9af1T1iZmVMzK-jqHA.png)

And here are the key settings:
![Key](https://image.prntscr.com/image/UBT3lXzpTuO91SVlIs8bDg.png)

I enabled the APIs first, then generated the key. I installed the plugin with the --variable API_KEY_FOR_ANDROID="myKey" parameter as well and its showing up in the config.xml correctly. I also tried re-installing the plugin with a different API key but that also didn't work. 

The Trouble Shooting Readme mentions "You need to register your SHA-1 fingerprint to Google APIs console", but is this necessary if the API key is set to unrestricted?

**Comment by wf9a5m75** [comment]
Regenerated the api key, then reinstall the plugin. Should be solved.

**Comment by dragonbane0** [comment]
Worked after I enabled the JavaScript API for some reason and generated a new Key, but I dont mind :D Thank you!
