### ISSUE TITLE
UnhandledPromiseRejectionWarning when installing

### ISSUE THREAD

**Issue by adit25** [mapsplugin/cordova-plugin-googlemaps#1982]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 5.0.1 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

![image](https://user-images.githubusercontent.com/13450677/34667317-1fc1277e-f49b-11e7-9c22-e1ba5d30c0c3.png)

node 8.9.4
cordova 8.0.0
android 7.0.0

Can u help me fix this problem?

**Comment by wf9a5m75** [comment]
```
$> cordova platform rm android

$> cordova platform add android
```

**Comment by adit25** [comment]
Thanks a lot, it works
