### ISSUE TITLE
onMapReady (map.addEventListener) is not firing

### ISSUE THREAD

**Issue by vahidvdn** [mapsplugin/cordova-plugin-googlemaps#1984]
Hi.
Unfortunately `onMapReady` does not fire in my app. I can never see the alert:

```
map.addEventListener(plugin.google.maps.event.MAP_READY, function(){
    alert('onMapReady!!!!');
});
```

The output of `alert(JSON.stringify(map));` is:
```
{"MARKERS":{}, "KML_LAYERS":{}, "OVERLAYS":{}}
```

Any idea?

Plugin list:
```
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Comment by wf9a5m75** [comment]
Please read before asking.
https://docs.google.com/presentation/d/1zlkmoSY4AzDJc_P4IqWLnzct41IqHyzGkLeyhlAxMDE/edit#slide=id.p

**Comment by vahidvdn** [comment]
I don't know what is the problem. I have already got api key from google console.

**Comment by wf9a5m75** [comment]
OK, please share your project files on github.

**Comment by vahidvdn** [comment]
@wf9a5m75 I created the project from beginning and now it works fine! Thanks for the support.

And one more question. Does it work without internet connection? I turned off the connection, and details are not appearing when I zoom the map.

**Comment by vahidvdn** [comment]
Oops, it seems working offline is not possible even in google maps main application. Btw, thanks.
