### ISSUE TITLE
Remove polylines but keep markers 

### ISSUE THREAD

**Issue by philipgriffin** [mapsplugin/cordova-plugin-googlemaps#1985]
**I'm submitting a ...**  (check one with "x")
[X] question
[ ] any problem or bug report
[ ] feature request

Hey! Still find myself coming back to this plugin a year on, it's great. 

I'm currently looking for a way to remove polylines without removing markers. I know people have asked about doing it the other way around but what I'm looking to do is remove all my polylines but keep markers. 

I will be removing them quite often so using map.clear() and re-adding my markers with dropMarker() will be a bit heavy. 

So is there a way to remove all polylines but keep the markers placed.

Thanks.

**Comment by wf9a5m75** [comment]
polyline.remove()

**Comment by philipgriffin** [comment]
Cant believe I didn't see this in the docs.. thanks.
