### ISSUE TITLE
Running enter, leave and drawell events with the plugin

### ISSUE THREAD

**Issue by renanmoraes** [mapsplugin/cordova-plugin-googlemaps#1986]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-background-geolocation-lt 2.9.1 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
I need to perform a callback function when the smartphone comes in, out and walk inside the polygon, how to do with this plugin? I noticed that it gives me the opportunity to only notice I have not seen any callback function.

**Comment by wf9a5m75** [comment]
Do you mean the geofence feature? If so, this plugin does not provide it.

**Comment by renanmoraes** [comment]
I do not really understand your question, but what I need is to identify the input, the output of a geofence (polygon), something basically like what this site does on android

https://developer.android.com/training/location/geofencing.html

**Comment by wf9a5m75** [comment]
As I said `this plugin does not provide it.`

**Comment by renanmoraes** [comment]
Are you going to support this part? Or do you know how to tell me another one that I would attend?

**Comment by wf9a5m75** [comment]
Google it!
https://www.google.com/search?q=cordova+geofence&oq=cordova+geofence&aqs=chrome..69i57.3837j0j7&sourceid=chrome&ie=UTF-8
