### ISSUE TITLE
has console.logs transitionend pgm406482972949

### ISSUE THREAD

**Issue by RanmalN** [mapsplugin/cordova-plugin-googlemaps#1988]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[X] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-open-native-settings 1.4.1 "Native settings"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-googlemaps 2.1.2-beta-20180103-1610 "cordova-plugin-googlemaps"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.1 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
The plugin seems to have console.logs
transitionend pgm406482972949
**Expected behavior:**
No prints in console

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
What are you asking?

**Comment by battika** [comment]
I guess he is asking to remove console log printouts starting with "transitionend pgm******". I can also see them when running IOS emulator and debugging using Safari. However I am not sure they are printed by this plugin.

**Comment by wf9a5m75** [comment]
@battika Thank you for following up. I understand your description, and commented out it.
