### ISSUE TITLE
Empty space left when android keyboard is closing

### ISSUE THREAD

**Issue by d4ex** [mapsplugin/cordova-plugin-googlemaps#1989]
[ ] question
[X] any problem or bug report
[ ] feature request

[X] **Android**
[ ] **iOS**

```
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.1.2-beta-20180103-1610 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

```
    "@ionic-native/core": "^4.5.2",
    "@ionic-native/google-maps": "^4.5.2",
```

I have a problem with the android keyboard... a empty white space is left after the keyboard is closed with android hardware back button or the arraow of the search field.

I'm using the multiple_maps branch. It looks like that the multiple_maps branch and master have different behaviours.

![ezgif-5-e6fd5c0c0b](https://user-images.githubusercontent.com/17742679/34869493-6101247a-f787-11e7-9feb-45525d0dd810.gif)

Some ideas to solve this problem?

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by d4ex** [comment]
I have not the time at the moment to upload a project. I try to upload a sample project on Friday.

**Comment by jsdussanc** [comment]
Use Cordova-plugin-keyboard

In the last iOS update, the title, artist, image never change, and the events are not linked to the buttons. Also create a new project with your plugin and an <audio> tag in ionic and it did not work, in cordova if it worked for me. But the advantages that cordova-ionic-webview brings are enough to leave them behind.

window.addEventListener('keyboardDidShow', function () {
    cordova.fireDocumentEvent('plugin_touch', {});            
});

window.addEventListener('keyboardWillShow', function () {
    cordova.fireDocumentEvent('plugin_touch', {});            
});

**Comment by wf9a5m75** [comment]
ping

**Comment by d4ex** [comment]
I'm closing this issue... i've no time at the moment and the issue is no show-stopper.

**Comment by StobyWan** [comment]
Seems that it is a show-stopper to me. I have been trying to resolve this for day using different variants of @jsdussanc  fix with no luck.

**Comment by dariovolaric** [comment]
I am having the same issue. The entire screen is left blank after switching to a different window in my app, typing and going back to the map.

**Comment by tolooaak** [comment]
add android:windowSoftInputMode="adjustPan" to your manifest file ;)
