### ISSUE TITLE
Problem with OnsenUI

### ISSUE THREAD

**Issue by hirbod** [mapsplugin/cordova-plugin-googlemaps#199]
Dear Masashi,
I spent the last weeks for testing and trying and did a lot of stuff with your great plugin. Now I faced a big problem when it comes up to the "real world".

I'm using OnsenUI (I guess it is familiar for you, it's at some point similar with Ionic, as they both rely on AngularJS and they use CSS transitions for animation)

I got everything up now, even complicated stuff like facebook-connect works fine with my server, but your plugin just stays black! 

I looked at Safari remote debugging and it seems like every element get's background-color: rgba(0,0,0,0) (I know, you placed the map under the webview and in that fact it is import to make everything transparent), but in my case, I don't see nothing. Initalizing at least seems to be fine.

I made a video so maybe you got an idea whats wrong here, as you've figured out what was wrong before with Ionic.

I would appreciate any help so much!

Video with the problem:
https://www.youtube.com/watch?v=5pIY38A8vCI&feature=youtu.be

As you can see at the end of the video, when I call the plugin for the second time it wouldn't even initialize again.

**Comment by JcDenton86** [comment]
Hello @Hirbod, can you provide how did you manage to make it work with Onsen UI 1.2.1, cause I always get a black screen. I am using sliding-menu and the menu page has a 'map' list item. When I tap on that I open the map page where I get the black screen.

My setup is: AngularJS 1.3, Onsen UI 1.2.1, jQuery 1.11, Android Google Play Service v22

Thank you in advance

**Comment by JcDenton86** [comment]
ok.. I am showing how am I using the plugin and I get the black screen when navigating on map page.

```
/*The View: map.html*/
<ons-page ng-controller="mapController" modifier="mappage">
        <ons-toolbar>
			<div class="left">
			  <ons-toolbar-button ng-click="menu.toggle()">
				<ons-icon icon="ion-navicon" size="28px" fixed-width="false"></ons-icon>
			  </ons-toolbar-button>
			</div>
          <div class="center">
            Map
          </div>
        </ons-toolbar>

       <div style="width:100%;height:400px" id="map_canvas" class="gmap_div"></div>

      </ons-page>
```
And in the mapController.js I do the following
```
/*The Controller: mapController.js */
module.controller('mapController',function($scope,$rootScope,$timeout){
	$rootScope.initMap = function() {
		$('.page--mappage__background').not('.page--menu-page__background').css('background-color', 'rgba(0,0,0,0)');
		if($rootScope.map) {
			$rootScope.map.clear();
			$rootScope.map.remove();
			$('.gmap_div:not(:last)').remove();
			$rootScope.map = '';
		}
		$timeout(function(){
			var div = document.getElementById("map_canvas");
            $rootScope.map = plugin.google.maps.Map.getMap(div,{
					'backgroundColor': '#f9f9f9',
					'mapType': plugin.google.maps.MapTypeId.HYBRID,
					'controls': {
					'compass': true,
					'myLocationButton': false,
					'indoorPicker': false,
					'zoom': true
				},
					'gestures': {
					'scroll': true,
					'tilt': true,
					'rotate': true
				}
			});
			$rootScope.map.setDebuggable(true);
			$rootScope.map.on(plugin.google.maps.event.MAP_READY, function(map){
				console.log('map ready!');
			});
		}, 600, false);
	} 
	ons.ready(function(){console.log('Map onsen ready');
		$rootScope.initMap();
	});
});
```
Any help is really appreciated..  The setup (google play services, libs, etc.) seems fine, because I get no errors but only successful messages for the initialization of the plugin and the map.

**Comment by Hirbod** [comment]
Hi @JcDenton86,

I guess there is still one div in the dom-tree, which isn't set to transparent.
Try using the inspector and check every single <div> / <any> (some of them are position absolute with width/height 100% and they won't get transparent cause this plugin cannot detect them als parent-node.

When you found it, make it transparent and it should work.
There could be more reasons. When you want help, let's do a teamviewer session and I will look for it right on your desktop.

**Comment by JcDenton86** [comment]
I even removed the toolbar and left only the map_canvas div on the page (updated my previous post) but still the same. Which other div you mean? On another page other than the map.html?

**Comment by Hirbod** [comment]
You need to find your div in the inspector and bubble up every single node (parent) and check the css value for background-color.

Remember: This plugin put it's content behind the regular webview, therefore, every single node in front of it has to be transparent (even html and body) in order to make the map visible.

Actually, this plugin will do it automagically, but it can only detect parent nodes, not absolute positioned elements which will make the map invisible. As said, this is a quite bit complex topic and I've invested so much time making this plugin to work perfectly with OnsenUI - but there are so many other points which will take to much time to explain. It would be the best when I checked by my own.

**Comment by JcDenton86** [comment]
Ok if you would like to check it, I am sending you a teamviewer id: 431 547 755
and the pass: 15u2fe

**Comment by Hirbod** [comment]
remove the pass

**Comment by JcDenton86** [comment]
@Hirbod , thank you for your help. I found out that adding modifier="transparent" to the <ons-page> elements, eventually showed the map on the emulator as expected. Though when I am installing the app on my device it doesn't show up. Any idea on that? Has anything to do with the signing keys?

Thanks

**Comment by Hirbod** [comment]
Seems to be a timing issue with initalizing a page and setting it to transparent. Maybe you need to delay that line

```$('.page__background').not('.page--menu-page__background').css('background-color', 'rgba(0,0,0,0)')```into a timeout. I really do not have any issues with my "hacks".. works damn fast and like native.

**Comment by JcDenton86** [comment]
Yes when the map shows up on the device it's a native performance, but the issue is that it doesn't come up every time as it does on the emulator. Wrapping up, though, the initMap function in a timeout did the trick..and now comes up every time on the device.

**Comment by Hirbod** [comment]
:+1:

**Comment by kariscomp** [comment]
I realized Onsen adds a div with a black background color just before the <ons-page> with the map div. I fixed this by writing a css selector that sets any div put above the page to have a transparent background. You could achieve the same using jquery.

**Comment by Hirbod** [comment]
Yes I've also done the same as you can see below

**Comment by sangariv** [comment]
HI,
i have used all the steps u have told above.but i am getting black background after closing sliding menu.can u pls help me to fix this.

**Comment by sangariv** [comment]
HI,
after adding this line,on  swiping  the sliding-menu, it becomes transparent immediately and I can see all the elements in the page div.can u please help me.
$('.page__background').not('.page--menu-page__background').css('background-color', 'rgba(0,0,0,0)')

**Comment by Hirbod** [comment]
sangraiv, I guess you're using "reveal" animation on the slide-menu. You need to change zu "push", otherwise, it won't work as expected.

```
<ons-sliding-menu ... ... type="reveal">
```
and change to

```
<ons-sliding-menu ... ... type="push">
```

By default, it is reveal, so if there is no type set, add ```type="push"``to your sliding menu

**Comment by sangariv** [comment]
yes it works .thanks a lot.

**Comment by ldenoue** [comment]
I had the same problem but because I forgot to include the correct CSS files in my iOS app bundle that also contained my HTML page.

onsenui.min.css
onsen-css-components.min.css
