### ISSUE TITLE
multiple_maps branch causes problem with geolocation plugin

### ISSUE THREAD

**Issue by hoermiller** [mapsplugin/cordova-plugin-googlemaps#1990]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-googlemaps 2.1.2-beta-20180111-1605 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2-dev "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
@ionic-native/core": "4.3.2
@ionic-native/google-maps": "^4.3.2
```

**Current behavior:**
After installing the newest version of the Google Maps Plugin multiple_maps branch, the Cordova Geolocation plugin does not work anymore. Xcode logs the following errors:
```
ERROR: Method 'getLocation:' not defined in Plugin 'Geolocation'
ERROR: Method 'addWatch:' not defined in Plugin 'Geolocation'
```
The Geolocation plugin is used in my project to start watching the location and calculate the distance to points on the map using the Google Maps Plugin spherical function.

**Expected behavior:**
I try to use the multiple_maps branch in order to be able to show to maps in a master-detail concept. Master View shows all points on a map and by clicking on a marker open detail view with small map, displaying small map with the selected location on a second map.
Based on the current location the distance to the selected location is supposed to be calculated.

**Comment by wf9a5m75** [comment]
Please ask to the Geolocation plugin developer
