### ISSUE TITLE
Ionic toast notification is not clickable when displayed over Google Maps plugin 

### ISSUE THREAD

**Issue by battika** [mapsplugin/cordova-plugin-googlemaps#1991]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X] **Android**
[ X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.1.2-beta-20180111-1605 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "4.5.2",
"@ionic-native/google-maps": "4.5.2",
```

**Current behavior:**
When an Ionic toast notification appears over Google Maps it is not possible to dismiss it as Google Maps catches all click events.

**Expected behavior:**
Toast notification should be clickable

**Related code, data or error log (please format your code or data):**
Demo project:
https://github.com/battika/ionic-gmaps-test

Click the Show toast button in the top right corner and try to close it using the CLOSE button.

<img width="463" alt="screen shot 2018-01-12 at 14 15 35" src="https://user-images.githubusercontent.com/1209088/34876784-68d91948-f7a3-11e7-8a18-8ccb64eada38.png">

<img width="462" alt="screen shot 2018-01-12 at 14 15 44" src="https://user-images.githubusercontent.com/1209088/34876792-7630c8b6-f7a3-11e7-9235-9f9f54ab04f0.png">

**Comment by wf9a5m75** [comment]
Before asking, please reinstall the plugin from the multiple_maps branch.

`cordova-plugin-googlemaps 2.1.2-beta-20171227-2046` is too old.

**Comment by battika** [comment]
Same thing happens with the latest one. Just updated the issue description

cordova-plugin-googlemaps 2.1.2-beta-20180111-1605 "cordova-plugin-googlemaps"

**Comment by wf9a5m75** [comment]
Fixed. Please reinstall the plugin from the multiple_maps branch.

![1991_compress](https://user-images.githubusercontent.com/167831/34893065-70fab1e4-f790-11e7-80c6-dae813efbd18.gif)

**Comment by battika** [comment]
Thanks @wf9a5m75 for providing the fix so quick. It seems to work fine now.
