### ISSUE TITLE
Google Maps Elevation API

### ISSUE THREAD

**Issue by juanmanuelariza** [mapsplugin/cordova-plugin-googlemaps#1993]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[ X ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X ] **Android**
[ ] **iOS**

Hi! Its posible use Google Maps Elevation API?

https://developers.google.com/maps/documentation/elevation/intro?hl=es-419

**Comment by wf9a5m75** [comment]
Try to implement using http request plugin.
https://github.com/wymsee/cordova-HTTP
