### ISSUE TITLE
Customizable marker infoWindow while adding multiple markers

### ISSUE THREAD

**Issue by Bengejd** [mapsplugin/cordova-plugin-googlemaps#1994]
**I'm submitting a ...**  (check one with "x")
[x ] question
[ ] any problem or bug report
[ ] feature request

I was wondering if it was possible to create custom infoWindow's for each marker added to a map. Currently, we can add multiple markers by utilizing the following:

```TypeScript
let baseArray: BaseArrayClass<any> = new BaseArrayClass<any>(markerLocations);
baseArray.mapAsync((mOption: any, callback: (marker: Marker) => void) => {
      this.map.addMarker(mOption).then(callback);
}).then((markers: Marker[]) => {
      console.log(markers);
});
```

But I was wondering how we would go about applying your method of adding custom infoWindows that are listed in the docs [here](https://github.com/mapsplugin/ionic-googlemaps-quickdemo/blob/master/src/pages/html-info-window/html-info-window.ts), so that each marker would have the customized window (having a clickable button on the infoWindow for example). 

It seems to me that because we're using the `markers: Marker[]` array, this is not possible with my current code, so I was wondering how to handle this?

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/ionic-googlemaps-demo/blob/master/src/pages/html-info-window/set-content/set-content.ts
