### ISSUE TITLE
How to calculate the zoom of two markers

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1995]
**I'm submitting a ...**  (check one with "x")
[X] question
[ ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X] **Android**
[ X] **iOS**

I have a polyline with a marker at the starting point and another marker at the point of arrival. How can I calculate the zoom to display the markers auotatically?

**Comment by wf9a5m75** [comment]
Only this.
```
map.moveCamera{
  target: [
      {lat:..., lng:...},
      {lat:..., lng:...}
  ]
})
```

**Comment by wuilmerj24** [comment]
@wf9a5m75 Yes, but try it after asking. Thank you. If not in the situation of Venezuela. I'll give you $ 10

**Comment by wuilmerj24** [comment]
@wf9a5m75 Yes, but try it after asking. Thank you. If not in the situation of Venezuela. I'll give you $ 10

**Comment by wf9a5m75** [comment]
Did you solve your question?

**Comment by wuilmerj24** [comment]
@wf9a5m75 Yes. Thank you
