### ISSUE TITLE
Fund raise: browser support

### ISSUE THREAD

**Issue by wf9a5m75** [mapsplugin/cordova-plugin-googlemaps#1998]
# Support the browser platform.

## Goal

**Implement the following features:**
- `map`
- `marker`
- `polyline`
- `polygon`
- `circle`
- `tileoverlay`
- `groundoverlay`
- `HtmlInfoWindow`
- `Geocoder`
- `poly utility`
- `encode utility`
- `spherical utility`

**Not implement for this development at this time (but in the feature)**
- `marker cluster`
- `kml overlay`

------------

Fundraise amount: $1,000 USD

Minimum donation amount: $100 USD per person (with private support)

From $50 to $100USD, I will let you know the work progress, and access to the beta test in last minutes.
(* The word `in last minutes` means pre-release version. It is not released yet, but planing very soon)

Less $50 USD, I appreciate for your donation.

------------

## Paypal
(Please write a memo **for places api** when you donate some amount)

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=cordova%2dgooglemaps%2dplugin&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted)

## Bitcoin
(Please let me know when you donate some Bitcoin. I'm not familiar with Bitcoin actually, so I don't want to miss you)

3LyVAfANZwcitEEnFbsHup3mDJfuqp8QFb

**Comment by battika** [comment]
Hello Masashi, not sure if I understand it correctly. Will you be using the Javascript GoogleMaps API v3 for browser support?

**Comment by wf9a5m75** [comment]
Yes.

**Comment by Azamorn666** [comment]
This would be really helpful, I will definitely consider donating towards this goal.

**Comment by wf9a5m75** [comment]
It looks line nobody is interested in the browser platform.

**Comment by wf9a5m75** [comment]
Since no body was interested in for adding browser support during one month, I close this fundraise, and the plan is gone.
