### ISSUE TITLE
Troubleshoting implementing on ionic cordova's project

### ISSUE THREAD

**Issue by brunovinny** [mapsplugin/cordova-plugin-googlemaps#1999]
I'm trying to configure cordova-plugin-googlemaps on my Ionic/Cordova's project, so I followed the instructions contained in [Installation on Windows](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v1.4.0/Installation/windows) 
But when I run my app none map is showed and I just receive those lines on console:

> 27010-27010/com.awesome.app I/dalvikvm: Could not find method android.content.pm.PackageManager.isInstantApp, referenced from method com.google.maps.api.android.lib6.drd.av.a
> 27010-27560/com.awesome.app I/dalvikvm: Could not find method android.os.PowerManager.isInteractive, referenced from method com.google.maps.api.android.lib6.drd.aa.a

This is my ionic info:

> cli packages: (C:\Users\MainUser\AppData\Roaming\npm\node_modules)
> 
>     @ionic/cli-utils  : 1.19.0
>     ionic (Ionic CLI) : 3.19.0
> 
> global packages:
> 
>     cordova (Cordova CLI) : 8.0.0
>     Gulp CLI              : not installed globally
> 
> local packages:
> 
>     Cordova Platforms : android 6.4.0
>     Ionic Framework   : ionic1 1.3.4
> 
> System:
> 
>     Android SDK Tools : 25.2.3
>     Node              : v6.11.2
>     npm               : 3.10.10
>     OS                : Windows 10
> 
> Environment Variables:
> 
>     ANDROID_HOME : C:\android-sdk
> 
> Misc:
> 
>     backend : pro

**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
`cordova (Cordova CLI) : 8.0.0` is not ready yet.

**Comment by brunovinny** [comment]
Thank you @wf9a5m75 , Could you tell me what is the latest version working?

**Comment by wf9a5m75** [comment]
Use cordova v6.x for the maps plugin v2.1.1.

But the next version will be released in couple of days. The next version requires the cordova v7.0.

This inconvenience is occurred because of this.
https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

**Comment by wf9a5m75** [comment]
Okay, I tested with the latest cordova version, but it has lots of problems.
So please install like this.

```
$> git clone -b multiple_maps --single-branch  https://github.com/mapsplugin/cordova-plugin-googlemaps

$> cd (your project)

$> cordova platform rm android

$> cordova platform add android@6

$> cordova plugin (path to cordova-plugin-googlemaps) --variable API_KEY_FOR_ANDROID=".."
```
```

**Comment by brunovinny** [comment]
Thank you again @wf9a5m75, I tried downgrading my Cordova CLI as you said and It works like a charm.

**Comment by wf9a5m75** [comment]
What?

**Comment by brunovinny** [comment]
@wf9a5m75 I'm sufferind another issue... I want to show maps inside Tabs but the plugin is going blank.. I'd read you comment in this publication [#1864](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1864) and tried to reinstall cordova-plugin-googlemaps  from from multiple_maps branch. But now the plugins crashes my application and doesn't  work inside or outside tabs. Besides, my splashscreen that has autohide setted false on config.xml and hide's trigger in my app.js with

```
	.run(function($ionicPlatform) {
	  //if ((device.platform == 'Android') || (device.platform == 'iOS')) {
		  $ionicPlatform.ready(function() {
			setTimeout(function() {
				navigator.splashscreen.hide();
				//ionic.Platform.isFullScreen = true;
			}, 300);
		 });
	  //}
	})
```
dd

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by wf9a5m75** [comment]
ping

**Comment by brunovinny** [comment]
@wf9a5m75 I'm dubugging my app and I discovered that cordova-plugin-googlemaps has incompatibility issue with [ionic-tabbedslidebox's library](https://github.com/bitsmuggler/ionic-tabbedslidebox). I'm still depurating my application to confirm that supposition. When I finish I'll share my project for your consideration.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update, I close this issue. But you can reply anytime.
