### ISSUE TITLE
HTML div overlay wont let me interact with the map

### ISSUE THREAD

**Issue by aj47** [mapsplugin/cordova-plugin-googlemaps#2000]
**I'm submitting a ...**  (check one with "x")
[ X] question
[ X] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.1.1 "Google Maps SDK for iOS"
com.jcjee.plugins.emailcomposer 1.4.6 "Email Composer with Attachments"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.2-dev "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.1 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
I have a html div image displaying over the map (like a circle displaying a radius) and i want to scroll the map but I can not scroll the map through the div, instead the whole container scrolls.

**Expected behavior:**
the map should be able to scroll without the whole container scrolling

**Screen capture or video record:**

![capture](https://user-images.githubusercontent.com/8023513/35036149-82100a34-fbc7-11e7-8ac4-0d62fe254410.gif)

**Related code, data or error log (please format your code or data):**

```
I can give access to the bitbucket repo if required


```
Giving much information, you are waiting time is less.
Thank you for your cooperation.

**Comment by wf9a5m75** [comment]
use the multiple_maps branch

**Comment by wf9a5m75** [comment]
```
$> git clone -b multiple_maps --single-branch  https://github.com/mapsplugin/cordova-plugin-googlemaps

$> cd (your project)

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin (path to cordova-plugin-googlemaps) --variable API_KEY_FOR_ANDROID=".."
```

**Comment by aj47** [comment]
Thank you that worked!

**Comment by aj47** [comment]
for some reason my navigator.geolocation.getCurrentPosition() is not working now
any ideas?
