### ISSUE TITLE
Build failes: Property 'BOUNCE' does not exist on type GoogleMapsAnimation.BOUNCE

### ISSUE THREAD

**Issue by gonadn** [mapsplugin/cordova-plugin-googlemaps#2002]
I'am trying to setup clean Ionic Demo/sample app, and when i try to build the project i get this error:
`Property 'BOUNCE' does not exist on type '{ [animationName: string]: string; }'.`

![gmaperror](https://user-images.githubusercontent.com/3224441/35050862-14f42386-fba4-11e7-8dfc-4900357cb225.PNG)

Here is the URL of my GIT project: [link](https://github.com/gonadn/IonicGoogleMaps)

if i comment out code line 60 and 69, i get build successfully , and the app runs....

**Comment by wf9a5m75** [comment]
Ask to ionic

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/ionic-googlemaps-demo/blob/master/src/pages/marker/set-animation/set-animation.ts

**Comment by wf9a5m75** [comment]
I tested your repo. I don't know the reason, but it certainly reproduce your issue.

In order to build, you can specify `BOUNCE` instead of `GoogleMapsAnimation.BOUNCE`.

```
marker.setAnimation('BOUNCE');
```

**Comment by gonadn** [comment]
thanks for the reply, i changed the code from "GoogleMapsAnimation.BOUNCE" to 'BOUNCE' as you explained...and it worked fine....

But can i ask why this happens, or is it a bug?
And why did you put label to "wontfix"?

**Comment by wf9a5m75** [comment]
The `@ionic-native/google-maps` is not my plugin.
