### ISSUE TITLE
Application freezing after resume 

### ISSUE THREAD

**Issue by AMerkuri** [mapsplugin/cordova-plugin-googlemaps#2004]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-appcenter-analytics 0.1.3 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.3 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

After putting application to background and bringing back to foreground about in 15 minutes application becomes fully unresponsive. App will lock itself for couple minutes, it might recover or might crash. Android will prompt with Not Responding dialog.

**Expected behavior:**

Shouldn't freeze i guess?

**Screen capture or video record:**

![screenshot_20180118-105229](https://user-images.githubusercontent.com/969989/35088968-2d3ad3be-fc3e-11e7-938e-1cd0c98cc416.jpg)

**Related code, data or error log (please format your code or data):**

Captured logs and trace with Android Device Monitor before crash.
[log.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1642087/log.txt)
[ddms951474389123393026.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1642090/ddms951474389123393026.zip)
![trace](https://user-images.githubusercontent.com/969989/35087924-824f183c-fc3a-11e7-82fe-2d210918b902.PNG)

**Comment by battika** [comment]
I had the same problem and I think you should try the multiple_maps branch. There was a fix regarding app resume and I have not got any report since then. It would be good to have it confirmed by you too.

**Comment by AMerkuri** [comment]
I have tried multiple_maps branch and for some reason it was running very poorly for me comparing to stable 2.1.1. Performance issues, lagging.

**Comment by wf9a5m75** [comment]
If you have a problem, please share your project files on github.

**Comment by battika** [comment]
@AMerkuri that is very interesting. I have never seen such issues with it and we are running it in production.

**Comment by AMerkuri** [comment]
@wf9a5m75 It is a private project, I can archive project, send privately to you and give information how to set it up.

**Comment by wf9a5m75** [comment]
I haven't recieved any invitation yet

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping
