### ISSUE TITLE
Is it possible to specify timeout for getMyLocation()?

### ISSUE THREAD

**Issue by battika** [mapsplugin/cordova-plugin-googlemaps#2005]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[x] feature request

**Current behavior:**
When the getMyLocation() method is called and the location is enabled the device might not respond for a very long time (or never) with valid GPS coordinates depending on coverage, etc. It can also happen that the user decides to disable location globally while running the app. When such thing happens getMyLocation()'s promise will never resolve and the application might get stalled because of this. It would be good to be able to specify a timeout after which the promise returns with a reject error. Eg. cordova-plugin-geolocation is using the same approach.
 
**Expected behavior:**
Should be able to specify a timeout.

Thank you for your consideration.

**Comment by wf9a5m75** [comment]
I will check this later.

**Comment by battika** [comment]
Thank you 👍

**Comment by wf9a5m75** [comment]
Try like this after reinstalling the plugin from the multiple_maps branch.

```js
var mapDiv = document.getElementById("map_canvas");
plugin.google.maps.Geolocation.getMyLocation(function(result) {

  var map = plugin.google.maps.Map.getMap(mapDiv, {
    'mapType': plugin.google.maps.MapTypeId.HYBRID,
    'camera': {
      target: result.latLng,
      zoom: 16
    }
  });

  map.addEventListener(plugin.google.maps.event.MAP_READY, function() {

    var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();
    htmlInfoWindow.setContent(JSON.stringify(result, null, 2));

    map.addMarker({
      position: result.latLng
    }, function(marker) {
      marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
        htmlInfoWindow.open(marker);
      });
    });

  });
});
```

**Comment by battika** [comment]
Thanks Masashi, I will give it a go soon

**Comment by battika** [comment]
It seems the latest version will not compile for Android with the following error:

```
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
PluginMap.java:82: error: cannot find symbol
    GoogleMap.OnInfoWindowLongClickListener, GoogleMap.OnInfoWindowCloseListener, GoogleMap.OnMyLocationClickListener, GoogleMap.OnPoiClickListener {
                                                                                           ^
  symbol:   class OnMyLocationClickListener
  location: class GoogleMap
PluginMap.java:301: error: cannot find symbol

              map.setOnMyLocationClickListener(PluginMap.this);
                 ^
  symbol:   method setOnMyLocationClickListener(PluginMap)
  location: variable map of type GoogleMap
/Users/battika/projects/greengo_mobile/3Development/greengo_v3/platforms/android/src/plugin/google/maps/PluginMap.java:731: error: cannot find symbol

                  map.setOnMyLocationClickListener(null);
                     ^
  symbol:   method setOnMyLocationClickListener(<null>)
  location: variable map of type GoogleMap
PluginMap.java:2431: error: method does not override or implement a method from a supertype

  @Override
  ^
Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

```

**Comment by wf9a5m75** [comment]
ping

**Comment by battika** [comment]
Hello, I still can't get this work. Here is how my sdkmanager --list command looks like. I believe everything should be up-to-date:
```

  Path                                                | Version | Description                                     | Location
  -------                                             | ------- | -------                                         | -------
  build-tools;26.0.3                                  | 26.0.3  | Android SDK Build-Tools 26.0.3                  | build-tools/26.0.3/
  emulator                                            | 27.0.5  | Android Emulator                                | emulator/
  extras;android;m2repository                         | 47.0.0  | Android Support Repository                      | extras/android/m2repository/
  extras;intel;Hardware_Accelerated_Execution_Manager | 6.2.1   | Intel x86 Emulator Accelerator (HAXM installer) | extras/intel/Hardware_Accelerated_Execution_Manager/
  patcher;v4                                          | 1       | SDK Patch Applier v4                            | patcher/v4/
  platform-tools                                      | 27.0.1  | Android SDK Platform-Tools                      | platform-tools/
  platforms;android-26                                | 2       | Android SDK Platform 26                         | platforms/android-26/
  tools                                               | 26.1.1  | Android SDK Tools                               | tools/
```

But I am still getting the same compile errors. Can you show me your output for reference please?

**Comment by wf9a5m75** [comment]
You need to install the google play services sdk v11.8.0

**Comment by battika** [comment]
Hello Masashi, I'm still working on testing this, actually rebuilding my entire dev environment. Please give me two additional days. In the meantime I saw you committed additional changes so I guess I'd better pull the latest changes.

**Comment by battika** [comment]
Hello Masashi, I am facing multiple issues with the implementation.
It turned out my compilation problem is caused by the onesignal cordova plugin that specifies Google Play Services 11.2+ as requirement.
```
 // ### Google Play Services library
    'com.google.android.gms': [
        'version': '11.2.+'
    ]
```

In this case the GoogleMaps plugin should indicate it requires GMS 11.8+. I saw that you specify

```
<variable name="PLAY_SERVICES_VERSION" value="11.8.+" />
```

but for some reason it is not taken into consideration. Can you please check if you can force this plugin to require GMS 11.8+?

As for the original request I am still not getting the timeout message after 6 seconds but I'm still testing it.

**Comment by wf9a5m75** [comment]
The reason of `11.8.+` means it indicates `11.8.0 or over`.

In the past, I specified particular version, then many people claims about that.
Recently I specified just `+`, then many people claims about that. 
Wow, they are craizy... I'm really really stressful.

Specifiying particular version, I need to update the plguin.xml every time, but I don't want to do that.

That's why `11.8.+`

----

Anyway, it it not related with the original issue. The plugin does not return "timeout message", but the plugin returns location in 6sec.

If you don't prefer it, why don't you other plugin?

**Comment by battika** [comment]
I understand you supplied 11.8+ but it is not followed by the compiler for some reason. Anyway I will try to fix this myself somehow.

Back to the original question. It does not return anything after 6 seconds. I am uploading a test app for you to check in a sec.

**Comment by battika** [comment]
Hello,
With the latest version I experience the following issue on Genymotion emulator with not providing GPS.
1. Navigate to the home page where I have a map displayed. Works OK.
2. Navigate to the 2nd page, hide map on the 1st page where there is another map displayed. Works OK.
3. Go back to the 1st page, destroy map on the 2nd page. Works OK.
4. Press the Get User Location button that calls getMyLocation(). It should give me the coordinates, an error or an extension. But the promise does not return anything. I can see `GCoreFlp: No location to return for getLastLocation()` message in logcat every now and then.
5. If I go back to the 2nd page now the map will not display on the second page saying map is not ready.

I am wondering do you handle that case a valid location has never been received before?

Git Repo:
https://github.com/battika/ionic-gmaps-test

YouTube video:
https://youtu.be/ZP7qB1E6zyc

**Comment by wf9a5m75** [comment]
Ask to Genymotion developer.

**Comment by wf9a5m75** [comment]
I don't support behaviors of emulators.

**Comment by battika** [comment]
OK, please close the issue. I open a new one for an iPhone issue.
