### ISSUE TITLE
Maps doesn't show up when div is removed and recreated.

### ISSUE THREAD

**Issue by danieleLewis** [mapsplugin/cordova-plugin-googlemaps#2006]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
If I set the map on a div, I delete the div and recreate it, the map doesn't show up.
I used to do that on the old version (1.4) and it worked but now with 2.1.1 the map doesn't show up.
I must recreate the map for make it working but I don't want to lose position and markers.

**Expected behavior:**
The map should appear in the div when created again.
I tried with setDiv again from console and setVisible(true) but nothing changed

**Screen capture or video record:**
https://www.youtube.com/watch?v=S79HGEoycb4

**Related code, data or error log (please format your code or data):**
```
https://github.com/danieleLewis/cordova-googlemaps-bug-recreate-div
```

**Comment by wf9a5m75** [comment]
Map is automatically removed when the map div is removed.

**Comment by wf9a5m75** [comment]
You need to recreate a map. This is not a bug.

**Comment by danieleLewis** [comment]
Is this a new think on v2? I was using v1.4 in another project and I don't remember this behaviour.
