### ISSUE TITLE
First app start after download from Store - map sometimes not loading properly

### ISSUE THREAD

**Issue by JaneDawson** [mapsplugin/cordova-plugin-googlemaps#2008]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appminimize 1.0 "AppMinimize"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-email-composer 0.8.12 "EmailComposer"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-firebase-analytics 0.12.1 "FirebaseAnalyticsPlugin"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 2.0.1 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-native-spinner 1.1.3 "Native Spinner"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-support-google-services 1.0.0 "cordova-support-google-services"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.2 "PushPlugin"


┌──────────────────────────────────────────┐
│ Update available: 8.0.0 (current: 7.1.0) │
│ Run npm install -g cordova to update.    │
└──────────────────────────────────────────┘
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^4.3.1",
"@ionic-native/google-maps": "^4.4.2",
```

**Current behavior:**
Is there anything different or special about the first start of an  Ionic / Cordova app after installing it from App- / Play Store compared to later app starts? I have issues with my app sometimes not loading the map properly on the first app start ever on a device (immediately after downloading the app from the store). The app just hangs when loading the map. When the app is forced to close and restarted, everything works like a charm…

Do you have any idea what this could be about? Thank you for this great plugin!!

**Comment by battika** [comment]
Maybe you have the same issue as this one?

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2009

We really need to wait until platform is ready before we start displaying the page that contains GoogleMaps and actually start initializing the map itself.

**Comment by JaneDawson** [comment]
hi @battika: Thanks for your response. Unfortunately, that's not what this is about. The map is not loaded before the user presses a button.
Hence, platform is ready --> user presses a button to navigate to the map --> map is loaded (and sometimes hangs for infinity while loading when it's the first app start after downloading from store.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub. No contribution, no help

**Comment by wf9a5m75** [comment]
I think using the multiple_maps branch version should get rid the problem. Please try it at once.

**Comment by JaneDawson** [comment]
Thank you @wf9a5m75. Since my app is in production, already, is somewhere documented, what the differences of the multiple_maps branch are? As far as I understand, this is a development branch, hence it may not be recommended to use it for production apps?
Did you update the multiple maps branch in some way that lets you think it may solve the problem? What do you think can be the issue?

**Comment by wf9a5m75** [comment]
@JaneDawson
 The multiple_maps branch is development version.
 This is open source. Nobody guarantee. Please decide which branch version is best for you if you don't share your project files.

**Comment by wf9a5m75** [comment]
ping

**Comment by JaneDawson** [comment]
Ok, thank you.

**Comment by Textras** [comment]
Are you giving the plugin ample time once initialized for the setInterval handler (I think line 118 or around). Basically finding its position on the device. Does it go all white and remain, after the occurrence on initial map load? @JaneDawson
