### ISSUE TITLE
Map not loading on iOS with no errors but working on Android

### ISSUE THREAD

**Issue by Baadier-Sydow** [mapsplugin/cordova-plugin-googlemaps#2009]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**Current behavior:**

Loading a page with the map on iOS only shows the page background ie white. The dom node to accept the map is empty. I'm testing on an iOS simulator and using Ionic Framework.

**Expected behavior:**

I'm expecting the map to load after the page is loaded as it does on Android.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

You can view the repo at https://github.com/Baadier-Sydow/ionic-google-maps

**Comment by battika** [comment]
Hello,

I think you should only set your root page to HomePage once platform is ready so that Google Maps can load. 

Check out the official example app:
https://github.com/mapsplugin/ionic-googlemaps-quickdemo

which does

```
 this.platform.ready().then(() => {
      this.rootPage = HomePage;
    });
```

**Comment by Baadier-Sydow** [comment]
@battika I'm going to give this a shot later this evening and report back.

Thanks for the help 👍

**Comment by wf9a5m75** [comment]
Thanks, @battika
Your point is correct.

@Baadier-Sydow 
You need to change the app.components.ts

Check out more details.
https://docs.google.com/presentation/d/1zlkmoSY4AzDJc_P4IqWLnzct41IqHyzGkLeyhlAxMDE/edit?usp=drivesdk

**Comment by Baadier-Sydow** [comment]
Thanks for the help. I just tried out @battika recommendation and it fixed it 🥇

**Comment by battika** [comment]
Cool, thanks for the confirmation 👍
