### ISSUE TITLE
Can't use same map in multiple pages

### ISSUE THREAD

**Issue by simetin** [mapsplugin/cordova-plugin-googlemaps#2012]
I'm submitting a 
- [X] any problem or bug report

For: 
- [X] Android
- [X] iOS

```
@ionic-native/google-maps: 4.5.2
@ionic-native/core: 4.4.0
```

Current behavior:
I want to use the same map on another page, my map instance lives in a provider. When I `ionViewDidEnter`, run the function `this.mapCtrl.map.setDiv(document.getElementById('map'))` and the map appear on the new page, but I can't interact with it. I tried to run the `this.mapCtrl.map.setAllGesturesEnabled(true)` function but it didn't work.

Expected behavior:
The map should appear and I should be able to interact with it. I've used this technique a lot with the V1, because it was the best way I found for reusing the same map instance, but if someone has a better way of doing it I'm open !

Here is the link to the code example: [https://github.com/simetin/reusable-map](https://github.com/simetin/reusable-map)

**Comment by wf9a5m75** [comment]
When you leave the map page, the map is removed automatically because the map div is removed.

**Comment by wf9a5m75** [comment]
You need to `map.setDiv(undefined)` when you leave the page.

**Comment by paulsynth** [comment]
I've just entered this repo to create the same issue! +1 for @simetin . It only works on iOS, but not on Android. Both platforms do the stuff with setDiv(), but in Android, you cannot interact with the maps because it gets frozen. In iOS you can interact with the maps the same way when it was created for the first time.

**Comment by goinnn** [comment]
I had the same problem with multiple_maps branch. With v2.1.0 works right with map.setDiv(undefined) or map.setDiv(), it is the same and more nice.

**Comment by paulsynth** [comment]
It also worked for me with 2.1.0! I was also using the multiple_branch and could not make it work. Thanks.

**Comment by simetin** [comment]
Good to know, but with the 2.1.0 version, I can't click on a marker on iOS with the Ionic Wrapper. Do you guys know a workaround ?

**Comment by wf9a5m75** [comment]
Fixed. Please resintall the plugin from the multiple_maps branch.
![2012](https://user-images.githubusercontent.com/167831/35243914-5181300a-ff73-11e7-8b5d-c2885bb434ce.gif)
