### ISSUE TITLE
Ionic: MarkerCluster not working, does not render any of the markers....

### ISSUE THREAD

**Issue by gonadn** [mapsplugin/cordova-plugin-googlemaps#2013]
Hi 

Iam having hard time to find out why markers are not getting redered on map, and iam not getting any error message. I had to create this repo/project to re-create the same senario as i have in my production app. App works fine with getting f.eks data from GooglePlaces, and render markers on map. 

But i have integrated an "3 Part" API giving med all Electric Charging stations in Norway, code works fine. I get the data and push it into an array and send it over to markecluster functon,. For some reason MarkeCluster dosent add any of the markers on the map.

Se pic from Chrome console:
![elerror](https://user-images.githubusercontent.com/3224441/35216711-d03bf174-ff68-11e7-8fe6-8a1bcaf61529.PNG)

Here is my repo for debuging:
[REPO](https://github.com/gonadn/IonicGoogleMaps)

You need to put ApiKey to the .ts class in: src/app/Services/GMapsServices.ts
 private nobilApiKey = '';

This is a PRIVATE Key, and i can not Share it over here, i need to send it over by email to you @wf9a5m75 

I will donate some amount for helping me with this issue, as long as we can fix it... :)

Reg
gonadn

**Comment by wf9a5m75** [comment]
I can not install the plugin because I got this error.
```
Error: Cannot find plugin.xml for plugin "jquery". Please try adding it again.
```

**Comment by gonadn** [comment]
can you please check if all plugins are included:
`"cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard",
    "cordova-plugin-geolocation",
    "cordova-plugin-googlemaps"
  ]`

**Comment by wf9a5m75** [comment]
could you specify everything in the config.xml? I'm so busy.

**Comment by gonadn** [comment]
i just updated my config.xml file, get the latest of file....

**Comment by gonadn** [comment]
iam not able to reproduce the error you got, i deleted the project from my repo, and downloaded it again from github...it works fine here...

**Comment by wf9a5m75** [comment]
Thank you for updating. That error is solved. However I can not install node_modules.

```
$ npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cordova-plugin-console@~
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'io.cordova.myapp7875ab'
npm ERR! notarget


npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/masashi/.npm/_logs/2018-01-22T23_22_00_515Z-debug.log
```

**Comment by gonadn** [comment]
i got this one to, i solved it by running command: "npm init" and then npm i
i dont no why this happen...

**Comment by wf9a5m75** [comment]
Ok, the reason of error is you specify `~` for `cordova-plugin-console`.
If you modify the config.xml file and the package.json file, you can build it.
However even I can not see the map.
Please (x 300) confirm everything before asking me. I'm terribly busy.
![capture](https://user-images.githubusercontent.com/167831/35257675-941ea2e4-ffaf-11e7-8a91-96597d4a724c.png)

**Comment by gonadn** [comment]
Oki thanks for your time, i appriciated. I have now fixed config.xml and package.json file with `"cordova-plugin-console": "^1.1.0"`  

i commited all changes, can you please download the latest one for testing.
And as i mentioned before, i will donate for any help i get to fix this....

**Comment by wf9a5m75** [comment]
Finally I found your problem that why **the marker cluster can not draw clusters**.

Because you pass the location `lat` and `lng` as **string**.

![screen shot 2018-01-23 at 5 41 58 pm](https://user-images.githubusercontent.com/167831/35310366-e41d23d6-0065-11e8-82e4-23afcd700841.png)

The `lat/lng` **MUST be float values**.

So in your code, you need to change your code like this:
```
// home.ts line 97-98
          var latMrk = parseFloat(arr[0]);
          var longMrk = parseFloat(arr[1]);
``` 

This is not bug.

**Comment by wf9a5m75** [comment]
![2013](https://user-images.githubusercontent.com/167831/35310486-870a8d5e-0066-11e8-9fb6-76f1fcbcfba4.gif)

**Comment by gonadn** [comment]
thanks alot, :)

**Comment by wf9a5m75** [comment]
It means there is JS error in your code, around `on(MARKER_CLICK)`.
Please doubt your code first.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response, and the error log is not plugin's problem (because `SafeSubsriber.next` means the error occurs inside the event listener), I close this issue, but you can still reply this thread.

----

By the way, I appreciate if you support for this project. 
This is not mandatory asking, but I appreciate if you donate some tip because I spend my private time for you (and it was not plugin's problem).

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
