### ISSUE TITLE
Can't get marker image assets within WKWebView

### ISSUE THREAD

**Issue by paulsynth** [mapsplugin/cordova-plugin-googlemaps#2014]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behaviour:**
X-Code stops in an exception throwing the following message:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSCache setObject:forKey:cost:]: attempt to insert nil value (key: http:/localhost:8080/var/containers/Bundle/Application/XXXX-XXXXXX/AppName.app/www/index.html#/./assets/icon.png)'

This happens if we specify paths like: icon: 'assets/icon.png', icon: './assets/icon.png', icon: '/assets/icon.png', icon: file:///assets/icon.png, etc etc.

**Expected behavior:**

Assets should be loaded the same way that every other element does, e.g. <img href="xxxx"/>

**Related code, data or error log (please format your code or data):**

```
let markerConfig = {
   icon: "assets/icon.png"
};

this.map.addMarker({
   title: 'xxxx',
   icon: markerConfig.icon,
   position: {...}
};
```

**Comment by wf9a5m75** [comment]
Try the multiple_maps branch version.

**Comment by wf9a5m75** [comment]
And please share your project files on github.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no reply at all, I close this thread.

**Comment by paulsynth** [comment]
Apologize for the delay. I'll try it in our next version, the current one is in production (using the UIWebView and the project is private, I would wish you to see the code and behaviour. I will keep in touch and answer you. Thanks!

**Comment by MaximeLassalleHub** [comment]
Hi there,

This is my solution to get WkWebView (plugin v2) to work with custom marker images :

The path for iOS & Android is a bit different, as it has to include 'www' for iOS and starts with './' in both cases.
 
> get rootAssetPath() {
>     if (this.platformServ.android()) {
>       return './assets'
>     }
>     else if (this.platformServ.ios()) {
>       return './www/assets'
>     } else {
>       return './assets'
>     }
>   }
> 

Hope it'd be useful.
