### ISSUE TITLE
Map doesn't load on Ionic

### ISSUE THREAD

**Issue by gersonmontenegro** [mapsplugin/cordova-plugin-googlemaps#2016]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
import { ErrorHandler, NgModule } from '@angular/core';
import { GoogleMaps } from '@ionic-native/google-maps'

**Current behavior:**
When I load the basic example for show a map, it doesn't load the map graphics.

**Expected behavior:**
Show the map

**Screen capture or video record:**
![image](https://user-images.githubusercontent.com/3643808/35259260-d4ab93b2-ffd2-11e7-8db4-ce65aca1e7e4.png)
**Related code, data or error log (please format your code or data):**

I can't see any log advice about it

**Comment by gersonmontenegro** [comment]
Thanks for any clue about my issue.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by gersonmontenegro** [comment]
thanks wf9a5m75, was my bad, obviously, the API wasn't enabled in the console:
[console.cloud.google.com/apis/library/maps-android-backend.googleapis.com/](url)

**Comment by wf9a5m75** [comment]
ok
