### ISSUE TITLE
Cannot add markers on MAP_CLICK event (Ionic Native GoogleMaps)

### ISSUE THREAD

**Issue by luisliev** [mapsplugin/cordova-plugin-googlemaps#2021]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Package.json**

    "@ionic-native/core": "4.4.0",
    "@ionic-native/google-maps": "^4.5.2",

**Current behavior:**
In a simple map (like the one in the official documents), when trying to add a marker with the latitude and longitude from a MAP_CLICK event data, I receive the info from the click but can't add a marker afterwards with those lat and lng variables.

**Expected behavior:**
Click the map in any place and a marker should be added wherever you clicked.

**Screen capture or video record:**
First event: Loaded map correctly. Click anywhere in the map.
![mapdemo1](https://user-images.githubusercontent.com/28770769/35369627-7618b9ba-014e-11e8-8dec-74fd9932ad73.png)

Second event: Alert shows the data received from clicking the map.
![mapdemo2](https://user-images.githubusercontent.com/28770769/35369628-7645c91e-014e-11e8-96f6-df367f64f4b6.png)

Third event: No marker is added even though the info was received correctly.
![mapdemo3](https://user-images.githubusercontent.com/28770769/35369629-765c5cb0-014e-11e8-8e24-06b7ef8ce4da.png)

**Related code, data or error log (please format your code or data):**

**LINK TO DEMO**
https://github.com/luisliev/demo-map

**home.ts**
import { Component, ViewChild, ElementRef } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import { GoogleMaps, GoogleMap, GoogleMapsEvent } from '@ionic-native/google-maps';

declare var plugin: any;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  @ViewChild('map') mapElement: ElementRef;
  map: GoogleMap;

  constructor(public navCtrl: NavController, private platform: Platform) {

  }

  ngAfterViewInit() {
    this.platform.ready().then(() => {
      this.initMap();
    });
  }

  initMap(){

    this.map = GoogleMaps.create('map');

    this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
      this.map.addEventListener(plugin.google.maps.event.MAP_CLICK).subscribe((data) => {
        alert('DATA -> ' + data);
        
        this.map.addMarker({
          position: data, 
          animation: 'DROP',
          draggable: true
        }).then(() =>{
          alert('Succesfully added a marker!');
        });
      });
    }).catch( error => {
      alert('ERROR -> ' + error);
    });
  }

}

**Other Information**
Been looking everywhere for any kind of related example about my issue, but no one seems to add this feature on MAP_CLICK event, at least in Ionic because I've done the same thing with Android Studio and it worked fine by overwriting the method MAP_CLICK_EVENT.

Tried different approaches but none seems to work, the best I could do is add a marker in the middle of the map (literally in the middle of the ocean) but that's because the position that I passed to the marker is "undefined".

**Comment by wf9a5m75** [comment]
You need to use both the same version
```
"@ionic-native/core": "4.5.2",
"@ionic-native/google-maps": "^4.5.2",
```

**Comment by wf9a5m75** [comment]
And try `console.log(data)` instead of `alert()`. You will notice the `data` variable is `array` not `object`.

So, you need to change the code like this:

```TypeScript
initMap(){

  this.map = GoogleMaps.create('map');

  this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
    this.map.addEventListener(GoogleMapsEvent.MAP_CLICK).subscribe((data) => {
      //alert('DATA -> ' + data);
      console.log(data);

      this.map.addMarker({
        position: data[0],
        animation: 'DROP',
        draggable: true
      }).then(() =>{
        alert('Succesfully added a marker!');
      });
    });
  }).catch( error => {
    alert('ERROR -> ' + error);
  });
}
```

![2021](https://user-images.githubusercontent.com/167831/35371815-3dbd8abc-014b-11e8-933e-56a94a798737.gif)

**Comment by luisliev** [comment]
Just did that and now it's finally working! 

Would you mind if I add this example to the documentation? I had this problem for weeks and maybe it could help others with the same issue. Specifically the part of the data array that  I haven't seen many people use.

I'll be closing the issue now.
