### ISSUE TITLE
Map does not scroll with ionic1

### ISSUE THREAD

**Issue by nrikiji** [mapsplugin/cordova-plugin-googlemaps#2022]
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/cb87a7a08cd29aa38b06e73e10252e85abc98d82
From this commit the map no longer scrolls.

No1. Map Scrolls
```
<ion-pane> 
    <ion-header-bar class="bar-stable">
      <h1>Title</h1>
    </ion-header-bar>
    <ion-content scroll="false">
      <div class="map" id="map_canvas" style="width:100%; height:100%;">
      </div>
    </ion-content>
  </ion-pane>
```

No2. Map does not scroll
```
<ion-pane> 
    <!--
    <ion-header-bar class="bar-stable">
      <h1>Title</h1>
    </ion-header-bar>
    -->
    <ion-content scroll="false">
      <div class="map" id="map_canvas" style="width:100%; height:100%;">
      </div>
    </ion-content>
  </ion-pane>
```
No2 How can I scroll it?
Is this a bug?

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by nrikiji** [comment]
https://github.com/nrikiji/ionic1_map/blob/master/www/index.html
https://github.com/nrikiji/ionic1_map/blob/master/www/js/app.js

Thanks. Please look. I tried it only with ios.

Version Info
```
$ ionic plugin ls
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
・・・

$ ionic platform ls
Installed platforms:
ios 4.5.4
・・・

```

but It worked in plugin version 2.0.8

**Comment by wf9a5m75** [comment]
Thank you for sharing, but how to build this? I'm not familiar with ionic1.

**Comment by wf9a5m75** [comment]
Regarding of your comment, https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/cb87a7a08cd29aa38b06e73e10252e85abc98d82 is too old.
Wow, `2.1.0-beta-20171027-0054`? That's 4 months ago....
I don't support back number version.

Building with the latest version (use the multiple_maps branch), I don't have any problem.

![2022](https://user-images.githubusercontent.com/167831/35426608-24cdaa36-0219-11e8-90b2-c2a4cdf88259.gif)

**Comment by nrikiji** [comment]
Thanks. I used the master branch.
I tried it with multiple_maps branch and it worked.

https://www.npmjs.com/package/cordova-plugin-googlemaps
I used a stable version, should I use a developed version?

**Comment by wf9a5m75** [comment]
Please detect which version is the best for you, because open source.

**Comment by nrikiji** [comment]
OK. Thank you very much.

**Comment by wf9a5m75** [comment]
By the way, I appreciate if you support for this project. 
This is not mandatory asking, but I appreciate if you donate some tip because I spend my private time.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
