### ISSUE TITLE
Remove location icon?

### ISSUE THREAD

**Issue by dayaki** [mapsplugin/cordova-plugin-googlemaps#2023]
Is it possible to remove the location icon being displayed on the map? see attached image below: 

![screenshot_20180125-152643](https://user-images.githubusercontent.com/815619/35393669-ed964542-01e5-11e8-8dd5-c96e450bc1b6.png)

**Comment by wf9a5m75** [comment]
Did you check the official documents?

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getMap/README.md#create-a-map-with-initialize-options

```
var map = plugin.google.maps.Map.getMap(div, {
  'mapType': plugin.google.maps.MapTypeId.ROADMAP,
  'controls': {
    'compass': true,   <----
    'myLocationButton': false,
    'indoorPicker': true,
    'zoom': true
  },
```

**Comment by dayaki** [comment]
Thanks, I missed that section.
