### ISSUE TITLE
Map Loads with all Layers and Markers But Is Not Zooming or Panning

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/cordova-plugin-googlemaps#2024]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

Kimberlees-MacBook-Pro:dvLinemanAppSDK kimberleearmstrong$ cordova plugin ls
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.9.1 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-camera 4.0.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-spatialite-storage 1.2.0 "Cordova sqlite/spatialite storage plugin"
phonegap-plugin-barcodescanner 7.0.0 "BarcodeScanner"
phonegap-plugin-contentsync 1.4.2 "content-sync"
phonegap-plugin-push 1.8.0 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.1.2 "Launch Navigator"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
When the map loads after animation to location the map 

**Expected behavior:**
Map Loads with all Layers and Markers But Is Not Zooming or Panning

**Screen capture or video record:**

Xcode logs show this:
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/A196813A-F820-4154-9B43-05860D68B8B1/Lineman-App.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/A196813A-F820-4154-9B43-05860D68B8B1/Lineman-App.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/A196813A-F820-4154-9B43-05860D68B8B1/Lineman-App.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
2018-01-25 16:04:54.737179-0600 Lineman-App[4596:4027485] panning google map with zoom:12 and center of 26.24 / -97.8231195190038 Google={"lat":26.24,"lng":-97.8231195190038}
2018-01-25 16:04:54.737416-0600 Lineman-App[4596:4027485] --->animateCamera
2018-01-25 16:04:54.737641-0600 Lineman-App[4596:4027485] refreshGoogleMap()

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Did you try the multiple_maps branch version?

**Comment by KimberleeDArmstrong** [comment]
I did just try it and I am having the same error. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by wf9a5m75** [comment]
Please share your project files.

**Comment by KimberleeDArmstrong** [comment]
I am working on building the project for you.  There are more Xcode errors with multiple_maps...
2018-01-25 17:21:54.333939-0600 Lineman-App[4636:4057155] creating google map with zoom:12 and center of 26.24 / -97.8231195190038 Google={"lat":26.24,"lng":-97.8231195190038}
2018-01-25 17:21:54.334189-0600 Lineman-App[4636:4057155] ERROR: Method 'resumeResizeTimer:' not defined in Plugin 'CordovaGoogleMaps'
2018-01-25 17:21:54.334337-0600 Lineman-App[4636:4057155] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","CordovaGoogleMaps","resumeResizeTimer",[]]
2018-01-25 17:21:54.336248-0600 Lineman-App[4636:4057155] ERROR: Method 'resumeResizeTimer:' not defined in Plugin 'CordovaGoogleMaps'
2018-01-25 17:21:54.336419-0600 Lineman-App[4636:4057155] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","CordovaGoogleMaps","resumeResizeTimer",[]]
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/F63A1BE6-0EAA-4484-8C96-A6BB1A0046CC/Lineman-App.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/F63A1BE6-0EAA-4484-8C96-A6BB1A0046CC/Lineman-App.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/F63A1BE6-0EAA-4484-8C96-A6BB1A0046CC/Lineman-App.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
2018-01-25 17:21:55.300600-0600 Lineman-App[4636:4057155] ERROR: Method 'resumeResizeTimer:' not defined in Plugin 'CordovaGoogleMaps'
2018-01-25 17:21:55.300873-0600 Lineman-App[4636:4057155] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","CordovaGoogleMaps","resumeResizeTimer",[]]
2018-01-25 17:21:55.476906-0600 Lineman-App[4636:4057155] ERROR: Method 'pauseResizeTimer:' not defined in Plugin 'CordovaGoogleMaps'
2018-01-25 17:21:55.477100-0600 Lineman-App[4636:4057155] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","CordovaGoogleMaps","pauseResizeTimer",[]]
2018-01-25 17:21:55.517438-0600 Lineman-App[4636:4057155] panning google map with zoom:12 and center of 26.24 / -97.8231195190038 Google={"lat":26.24,"lng":-97.8231195190038}
2018-01-25 17:21:55.517981-0600 Lineman-App[4636:4057155] refreshGoogleMap()

**Comment by wf9a5m75** [comment]
There is no longer exist `resumeResizeTimer` method.
It seems your project uses old JS

**Comment by KimberleeDArmstrong** [comment]
I grepped my entire source code for "resumeResizeTimer"  and it wasn't found.  I am not sure what happened.  I reinstalled #multiple_maps again for the 3rd time and this time I am not getting it.  :-S Thanks!

**Comment by wf9a5m75** [comment]
Good. I'm planing to release the next version soon (hopefully in this week). The next version is really stable than ever.

**Comment by KimberleeDArmstrong** [comment]
Let me know when you release it.

**Comment by wf9a5m75** [comment]
Don't you subscribe the official community? It's already released and announced.

https://plus.google.com/communities/117427728522929652853

https://www.npmjs.com/package/cordova-plugin-googlemaps

**Comment by KimberleeDArmstrong** [comment]
I thought I was.  I will see if I am following the right one.  Thanks! :-D

**Comment by KimberleeDArmstrong** [comment]
Running 2.2.2 I get the Google Maps SDK for iOS creashes with app name 'Lineman-App' . I checked out the comments and changed my config.xml from this...
<widget id="com.datavoiceint.dvLinemanApp" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Lineman-App</name>

to this...
<widget id="com.datavoiceint.dvLinemanApp" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name short="LinemanApp">Lineman-App</name>

What am I doing wrong?

**Comment by wf9a5m75** [comment]
`<name short="LinemanApp">Lineman-App</name>` is for the apps that use non-English characters to the app name. Your's are not related.

Please share your project files.

**Comment by KimberleeDArmstrong** [comment]
I changed the name to LinemanApp in config.xml and dropped the ios platform and readded it and the problem went away.
