### ISSUE TITLE
Datepicker plugin conflict with googlemaps plugin

### ISSUE THREAD

**Issue by elberthbracho** [mapsplugin/cordova-plugin-googlemaps#2026]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-email-composer 0.8.10 "EmailComposer"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-mfp 8.0.2017082909 "IBM MobileFirst Platform Foundation"
cordova-plugin-network-information 1.3.5-dev "Network Information"
cordova-plugin-okhttp 2.0.0 "OkHttp"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.1.0 "Launch Navigator"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

"@ionic-native/core": "^3.12.1",

Current behavior:
First of all, thanks for this great plugin. The map is working fine, the problem comes when I use the stable version with cordova-plugin-datepicker, because the window(datapicker) doesn't works and it’s no possible to close it. Before I fixed it installing develop version (current multiple_maps branch) but this didn't work yesterday. For the moment I fixed the problem installing a commit:

cordova plugin add  https://github.com/mapsplugin/cordova-plugin-googlemaps#1a19104e1dbf1d9408b4ff811f4e9b9dc605785a \
    --variable API_KEY_FOR_ANDROID="********" \
    --variable API_KEY_FOR_IOS="**********" \
    --no-fetch

Expected behavior:
Both plugins should work well as before.(commit “prevent error stop”) 

Screen capture:

![image1](https://user-images.githubusercontent.com/35746135/35461631-a54892b4-02b6-11e8-9258-88d76eaa2804.PNG)

[iOS]

**My Environment:**
Ionic 3.19.1
Cordova 6.5.0
Platform ios 4.3.1

Steps to reproduce:
 
Install the plugin:
 
cordova plugin add cordova-plugin-googlemaps \
    --variable API_KEY_FOR_ANDROID="****" \
    --variable API_KEY_FOR_IOS="*****" \
    --no-fetch
 
Select some input using datapicker plugin

```

**Comment by wf9a5m75** [comment]
Please use the multiple_maps branch version. This is already fixed problem.
