### ISSUE TITLE
Are the Marker css classes accessable?

### ISSUE THREAD

**Issue by Bengejd** [mapsplugin/cordova-plugin-googlemaps#2027]
I am looking to change the marker image on my map from a square image, to a circular image, and I figured the best way to do this would be to use border-radius, but I realized that I don't know what the Marker class names are, and I can't inspect it on my iPhone device (unfortunately). Are they accessible classes that I can do this with?

**Comment by wf9a5m75** [comment]
First of all, you need to recognize the map is not HTML element. So, it means marker is drawn on the native map, not html. Thus, there is no CSS class.

**Comment by Bengejd** [comment]
That's what I figured, but I was hopeful that I was wrong in some case. Okay, I'll go back to my changing the icon instead, thank you.
