### ISSUE TITLE
framework 7, not an issue excactly

### ISSUE THREAD

**Issue by alextapia007** [mapsplugin/cordova-plugin-googlemaps#2028]
hi.
i have a question.
do you know a css property to make imposible to use the map?
im using framework 7, in v1.6.5 works perfect, but now in v2... i can see the map, but cant use it... removing the framework7.css the map work.

**Comment by wf9a5m75** [comment]
I'm not familiar with framework7.  But please try the multiple_maps branch version

**Comment by alextapia007** [comment]
working on it...

**Comment by alextapia007** [comment]
i find a way.
just comment a css property.

.views,
.view {
  position: relative;
  height: 100%;
  /*z-index: 5000;*//*map works*/
  overflow: hidden;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

**Comment by wf9a5m75** [comment]
ok
