### ISSUE TITLE
Geocoder.geocode returns empty results for any valid address

### ISSUE THREAD

**Issue by bhavyalatha26** [mapsplugin/cordova-plugin-googlemaps#2029]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/geolocation": "^4.5.2",
"@ionic-native/google-maps": "^4.5.2",
"cordova-plugin-geolocation": "^4.0.1",
"cordova-plugin-googlemaps": "^2.1.1",
```
**Current behavior:**
Geocoder.geocode always returns empty results for any valid address string.
Testing Device : Redmi 4A
android version : 6.0.1

```
let request : GeocoderRequest = {address : data.description}
Geocoder.geocode(request).then(results => {
  console.log("results is ** : " + JSON.stringify(results))
  var geoCodeResult = results[0] as GeocoderResult
  console.log("geoCodeResult is : " + JSON.stringify(geoCodeResult))
  if(geoCodeResult)
     this.googleMap.setCameraTarget(geoCodeResult.position)
})       
```
**Related code, data or error log (please format your code or data):**

![image](https://user-images.githubusercontent.com/13586777/35485343-4d2a4f80-0484-11e8-9ca1-68a4743d5dce.png)

**Comment by wf9a5m75** [comment]
Unfortunately the plugin just passes the results of the geocoder. I can not guarantee the results.

**Comment by bhavyalatha26** [comment]
Thank you for the quick response @wf9a5m75 .
Just as reference for any one running into the same issue , rebooting my device solved it for me  .
Read  the accepted answer in this [question](https://stackoverflow.com/questions/15110528/service-not-available-while-calling-geocoder-getfromlocation) to learn more.

**Comment by nicmwenda** [comment]
Thank you for the tip @bhavyalatha26 this 'bug' was driving me nuts any resolution yet?
