### ISSUE TITLE
only load until 85 marker cluster.

### ISSUE THREAD

**Issue by kevinrodbemx** [mapsplugin/cordova-plugin-googlemaps#2032]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core": "4.4.0",
@ionic-native/google-maps": "^4.5.3",
```

**Current behavior:**
when the botton "144" is clicked, the markers dont load; but if the bottom "80" is clicked; then, all 85 markers are loading.

**Expected behavior:**
Should load all markers, but only load until 85 markers (is weird)

**Screen capture or video record:**
![image](https://user-images.githubusercontent.com/34073340/35527402-a0a9fff6-04f8-11e8-9f32-83fd5f1fea09.png)

**Related code, data or error log (please format your code or data):**
my example code: https://github.com/kevinrodbemx/maps-ionic
Map run in home page.

Thanks for your project

**Comment by wf9a5m75** [comment]
Please try the `multiple_maps` branch version at first

**Comment by wf9a5m75** [comment]
And you should use both the same version.

```
@ionic-native/core": "4.5.3",
@ionic-native/google-maps": "^4.5.3",
```

**Comment by wf9a5m75** [comment]
ping

**Comment by kevinrodbemx** [comment]
I've tested with the same version of the ionic-native's dependencies: and the result was the same.

After, i tried with multiple_maps branch, and tried to launch again, the terminal throw this message:  
![image](https://user-images.githubusercontent.com/34073340/35533560-ebf86354-050b-11e8-825f-94017b704498.png)

I've updated the repository's code.

thanks

**Comment by wf9a5m75** [comment]
```
$> cordova platform rm android
$> cordova platform add android@6
```

**Comment by kevinrodbemx** [comment]
Thanks, now i can run again the project, but just show 85 markers.
I-ve update the repository with last change the "add platform android@6" and calling to function to load 144 markers (dont show the markers :/ )

**Comment by wf9a5m75** [comment]
Please doubt your code first.
![screen shot 2018-01-29 at 2 03 14 pm](https://user-images.githubusercontent.com/167831/35536968-656c908e-04fd-11e8-8659-02d52d525674.png)

**Comment by wf9a5m75** [comment]
By the way, I appreciate if you support for this project. 
This is not mandatory asking, but I appreciate if you donate some tip because I spent my private time for your issue.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by kevinrodbemx** [comment]
thanks, it's a fool mistake. thanks for your time (I've sent a donate, for your project and support)

I have one question, how i can debug the java side of the plugin (like a debugger or breakpoint in js)

**Comment by wf9a5m75** [comment]
I use Android Studio.
