### ISSUE TITLE
Marker-Event INFO_CLOSE fired wrong

### ISSUE THREAD

**Issue by GitToTheHub** [mapsplugin/cordova-plugin-googlemaps#2033]
**I'm submitting a ...**  (check one with "x")
- [  ] question
- [X] any problem or bug report
- [  ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [  ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-calendar 5.0.0 "Calendar"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-vibration 2.1.6 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"

I'm using Phonegap

**Current behavior:**
The Event INFO_CLOSE is fired wrong for a marker. If click on the map, and a InfoWindow is closed, the event will not be fired. If i close the map with setVisible(false) and remove(), the event will be fired for every marker on the map.

**Expected behavior:**
Event should be fired, when the info window will be closed.

**Related code, data or error log (please format your code or data):**
```
baseArrayClass.map(function(markerData, iterateMarkerCallback) {
      
        // The variable "markerData" contains each element of the markersData.
        map.addMarker(markerData, function(marker) {
          
          marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
            alert("Marker clicked");
          });
          
          marker.on(plugin.google.maps.event.INFO_CLOSE, function() {
            alert("Info closed");
          });
          
          iterateMarkerCallback(marker);
        });
      }
  ..
  function destroyMap() {
    if (map) {
      map.setVisible(false);
      map.remove();
      map = null;
    }
  }
```

**Comment by wf9a5m75** [comment]
First of all, please share your project files on github.

The second, `cordova-plugin-googlemaps 2.0.11` is too old.
Please try the `multiple_maps` branch version.

**Comment by GitToTheHub** [comment]
I don't know why
  phonegap plugin list
says 2.0.11.
I'm using PhoneGapBuild, there i'm using 2.1.1. Here's the log:

> Fetching plugin "cordova-plugin-googlemaps@~2.1.1" via npm
Installing "cordova-plugin-googlemaps" at "2.1.1" for android

I thought the master branch is the newest code?

**Comment by wf9a5m75** [comment]
>I thought the master branch is the newest code?

No. It is stable code, but not the latest code.

**Comment by GitToTheHub** [comment]
I've tried multiple_maps, the bug occures here too. Here the Phonegap Build log for Android:

> Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps" via git clone
> Using shallow clone
> Repository "https://github.com/mapsplugin/cordova-plugin-googlemaps" checked out to git ref "multiple_maps" at "b216fdf".
> Installing "cordova-plugin-googlemaps" at "2.2.0-beta-20180129-1132" for android

**Comment by wf9a5m75** [comment]
Ok, please share your project files in order to reproduce your issue.

**Comment by GitToTheHub** [comment]
You can use your sample code from
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Marker/addMarker/README.md
and add the following code, when adding marker:
```
marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
  alert("Marker clicked");
});
          
marker.on(plugin.google.maps.event.INFO_CLOSE, function() {
  alert("Info closed");
});
```

**Comment by wf9a5m75** [comment]
As I said, ** in order to reproduce your issue please share your project files**.

**Comment by GitToTheHub** [comment]
ok sorry, i cannot share them, its a big app. i must build a sample app, but have no time. It's only basic functionality. If the event INFO_CLOSE is fired in your normal code, than it's my mistake.
You can close this issue, if you won't test the event.

**Comment by GitToTheHub** [comment]
Please Reopen. Hier is an example Code for the issue:
[index.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1793789/index.zip)

**Comment by GitToTheHub** [comment]
- If i click on the map, "INFO_CLOSE" will fired twice
- if i remove the map, "INFO_CLOSE" will fired for each marker

**Comment by GitToTheHub** [comment]
Ignore my comments. I recreated an issue under #2129
