### ISSUE TITLE
About display control of my location button.

### ISSUE THREAD

**Issue by nrikiji** [mapsplugin/cordova-plugin-googlemaps#2036]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/setMyLocationEnabled/README.md

Please tell me about this demonstration.
Is it possible to hide the move button to the current position on the upper right of the map?
However, while leaving the marker, it is hope.
I would like you to tell me the means if possible.

**Comment by battika** [comment]
Yes and yes.
```

       this.map = GoogleMaps.create(this.mapElement, {
          controls : {
            compass : false,
            myLocationButton : false,
            myLocation: true,
....
```

**Comment by nrikiji** [comment]
Thank you!!
