### ISSUE TITLE
Snippet not showing with Clusters

### ISSUE THREAD

**Issue by danieleLewis** [mapsplugin/cordova-plugin-googlemaps#2037]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"

**Current behavior:**
In the InfoWindow, the snippet donesn't show up. Only the title appears.
The marker object has the "snippet" property and it works if I add it in the normal way. This happens only if I render the markers with addMarkerCluster.
I know you suggest to use HtmlInfoWindow but at the moment I have not the time to change it and I'm still using the old InfoWindow.

**Expected behavior:**
I'm expecting to see the snippet under the title.

Here is the code for addMarkerCluster:

```
map.addMarkerCluster({
  markers: markerData,
  icons: [
    {min: 5, max: 100, url: "./img/cluster/CLUSTERING-01.png", anchor: {x: 16, y: 16}},
    {min: 100, max: 1000, url: "./img/cluster/CLUSTERING-02.png", anchor: {x: 16, y: 16}},
    {min: 1000, max: 2000, url: "./img/cluster/CLUSTERING-03.png", anchor: {x: 24, y: 24}},
    {min: 2000, url: "./img/cluster/CLUSTERING-04.png", anchor: {x: 32, y: 32}},
  ]
}, function (markerCluster) 
{
  markerCluster.on(plugin.google.maps.event.MARKER_CLICK, function (position, marker) {
    marker.on(plugin.google.maps.event.INFO_CLICK, function () {
      markerClick(marker.get("codice"));
    });
  });
});
```

**Comment by wf9a5m75** [comment]
Fisrt of all, please try the v2.2.2. The v2.1.1 is old.

Second, your code does not include the markerData. How did you write?

If the problem is occurred after upgrading the maps plugin to v2.2.2, please share your project files on github. I will check it.

**Comment by danieleLewis** [comment]
Updating to v2.2.2 solved the problem. Thank you.
