### ISSUE TITLE
How can I prevent the Clusters from overlapping?

### ISSUE THREAD

**Issue by danieleLewis** [mapsplugin/cordova-plugin-googlemaps#2038]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.2.2 "cordova-plugin-googlemaps"
```

**Current behavior:**
I'm trying to implement Clustering and it works fine when the zoom is high. But when I zoom out (in my case to entire Italy) I have too many clusters that overlaps each other.
The documentation doesn't tell enough about the MarkerCluster class. I saw the anchor property change something but I have no idea what it does.
Is there a way to prevent Cluster from overlapping? I'd like to remove the smaller ones and insert them in a bigger one but probably the area dimensions for the clusters is not big enough I think.
Can I change some properties that are not listed in the documentation? Thanks.

**Screen capture or video record:**
![clusteroverlap](https://user-images.githubusercontent.com/18093207/35638766-524518f2-06b8-11e8-9b56-0eeca34885ea.png)

**Related code, data or error log (please format your code or data):**
This is the code I'm using for creating the clusters.

```
map.addMarkerCluster({
                //debug: true,
                //maxZoomLevel: 5,
                markers: markerData,
                icons: [
                    {min: 5, max: 30, url: "./img/cluster/CLUSTERING-01.png", anchor: {x: 16, y: 16}, label: {
                        color: "white",
                        bold: true,
                        italic: false,
                        fontSize: 14
                      },},
                    {min: 30, max: 100, url: "./img/cluster/CLUSTERING-02.png", anchor: {x: 16, y: 16},label: {
                        color: "white",
                        bold: true,
                        italic: false,
                        fontSize: 14
                      },},
                    {min: 100, max: 500, url: "./img/cluster/CLUSTERING-03.png", anchor: {x: 32, y: 32},label: {
                        color: "white",
                        bold: true,
                        italic: false,
                        fontSize: 14
                      },},
                    {min: 500, url: "./img/cluster/CLUSTERING-04.png", anchor: {x: 64, y: 64},label: {
                        color: "white",
                        bold: true,
                        italic: false,
                        fontSize: 14
                      },},
                ]
            }, function (markerCluster)
            {
                markerCluster.on(plugin.google.maps.event.MARKER_CLICK, function (position, marker) {
                    // marker.setSnippet(marker.get("snippet"));
                    // marker.showInfoWindow();
                    marker.on(plugin.google.maps.event.INFO_CLICK, function () {
                        markerClick(marker.get("codice"));
                    });
                });
                
            });
```

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, please share your project files on github.

**Comment by danieleLewis** [comment]
My mistake, I was fetching the markers partially from an API call and rendering new markers in different moments. Now, clearing and re-fetching everything on movement solved the problem.
