### ISSUE TITLE
Androidで地図を表示したまま放置後に再操作するとANRが頻発する

### ISSUE THREAD

**Issue by tossy-yossy** [mapsplugin/cordova-plugin-googlemaps#2041]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-android-play-services-gradle-release 1.2.0 "cordova-android-play-services-gradle-release"
cordova-plugin-googlemaps 2.2.2 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
Androidで地図を表示したまま放置し、30分〜1時間後に地図以外のUI（cordovaやionicのボタン、画面スクロール等）を操作すると、ANRが頻発します。
地図を表示した状態で、アプリをバックグラウンド状態、もしくは端末スリープさせて30分〜1時間後に再度操作を開始した時も同様、地図部分以外のUIの反応が悪く、ANRが頻発します。

現状、ionic V1でアプリを開発しており、地図画面を実装後に上記挙動となったため、プラグインの使い方が悪いのかと思いましたが、配布されている「v2.0-demo」を最新バージョンのプラグインでビルドしたもので検証しても同様となりました。
検証機はSONY XPERIA SO-01Jになります。

**Screen capture or video record:**
![screenshot_20180201-201304](https://user-images.githubusercontent.com/19369133/35676823-a52f8ee8-0790-11e8-87b1-54bad3c76b57.png)

**Comment by tossy-yossy** [comment]
参考になるか分かりませんが、端末内の/data/anr/traces.txtを添付します。
[traces.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1685445/traces.txt)

**Comment by wf9a5m75** [comment]
traces.txt ファイルを添付していただいてありがとうございます。
ログを元にコードを少し変更しました。こちらでテストした限りでは問題なさそうです。

multiple_mapsブランチからプラグインをインストールしてください。

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="...."
```

**Comment by tossy-yossy** [comment]
ご対応ありがとうございます。しかしながら、
cordova-plugin-googlemaps 2.2.3-beta-20180201-1421 "cordova-plugin-googlemaps"
に差替えて同様の操作を行ったところ、同じくANRが出ました。
対象アプリも同じくv2.0-demoになります。
traces.txtも添付します。
[traces.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1688049/traces.txt)

**Comment by wf9a5m75** [comment]
となると、こちらでは再現しないので、対応が難しいですね。Javaの知識があればデバッグしていただきたいです。そうでなければ、諦めてもらうしかないかもしれません

**Comment by wf9a5m75** [comment]
Nexus 5  2012年版(Android 5.1)でテストしていますが、全く再現しません。残念ながらこれ以上のサポートは現時点でありません

**Comment by tossy-yossy** [comment]
承知いたしました。
機種依存なのか、何か対策できることがあるか、もう少し調査・検討してみます。
ご検証ありがとうございました。
