### ISSUE TITLE
ERROR :  Installing "cordova-plugin-googlemaps" for ios

### ISSUE THREAD

**Issue by bhandaribhumin** [mapsplugin/cordova-plugin-googlemaps#2042]
Failed to install 'cordova-plugin-googlemaps': CordovaError: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone -q https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git /Users/bhuminb/.npm/_cacache/tmp/git-clone-2202a37c
npm ERR! /Users/bhuminb/.npm/_cacache/tmp/git-clone-2202a37c/.git: Permission denied

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2034#issuecomment-361666238

**Comment by wf9a5m75** [comment]
`npm ERR! /Users/bhuminb/.npm/_cacache/tmp/git-clone-2202a37c/.git: Permission denied`

This is everything.

**Comment by bhandaribhumin** [comment]
already give full permission(Read&Write) to .npm directory, still getting same issue. ;(

**Comment by ZackRadnedge** [comment]
I had the same issue and installed git via pkg from their website and an earlier version of npm as this is an open issue with newer versions from what I've seen. I think the earlier npm release fixed it.

I used npm 5.3, available from https://nodejs.org/download/release/v5.3.0/
and cordova-plugin-googlemaps installed fine.
