### ISSUE TITLE
New markers added with MarkerCluster.addMarkers don't show until the map is moved

### ISSUE THREAD

**Issue by danieleLewis** [mapsplugin/cordova-plugin-googlemaps#2053]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.2.2 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
When I add markers inside a markerCluster with his method "addMarkers", I can't see the new markers until I move the map.

**Expected behavior:**
I should see the new markers when added, without moving the map.

**Screen capture or video record:**
[mapsTest.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1700287/mapsTest.zip)

**Related code, data or error log (please format your code or data):**
https://github.com/danieleLewis/cordova-map-test-cluster

**Comment by wf9a5m75** [comment]
Not bug. The marker cluster redraws when the map is moved.

**Comment by danieleLewis** [comment]
So, if I add a marker to the map it displays, if I add a marker inside a cluster I need to to move the map to see it. How can this be normal? 
On iOS I don't need to move anything for displaying the new markers.
Is there a way to trigger the redraw of MarkerCluster from js?

**Comment by wf9a5m75** [comment]
If you see the source code, you will notice the answer (that's why open source)
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/MarkerCluster.js

**Comment by danieleLewis** [comment]
Can you just tell me how to trigger the redraw? I have not the time to read a 1200 line js.
I tried with map.panBy(1,1) but it doesn't always work.

**Comment by wf9a5m75** [comment]
Try `cordova-plugin-googlemaps@2.2.3`

**Comment by danieleLewis** [comment]
The 2.2.3 update fixed this. Now it redraws on map move, thank you!

**Comment by wf9a5m75** [comment]
You are welcome.
