### ISSUE TITLE
HTML DIV not clickable if the screen rotate

### ISSUE THREAD

**Issue by Leogio360** [mapsplugin/cordova-plugin-googlemaps#2054]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-battery-status 1.2.5 "Battery"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-googlemaps 2.2.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-media-capture 1.4.3 "Capture"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-vibration 2.1.6 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Problem description:**
Hi,
in my app there are two clickable DIV over the map (MATERIALIZE CSS FIXED ACTION BUTTON), I can successfully click them in every situation if I open the app on browser (so without map), but when i open the app on Android, i can successfully click them, only on portrait (if the app started on portrait) or on landscape (if the app started on landscape). 
So if the screen rotate the Divs cannot be clicked.
I noticed that i can reproduce this problem  with every div with position:fixed or absolute, but no problem with position:relative.
Am I doing wrong something, or is there a bug in the plugin?

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, please share your project files (everything) on github.

**Comment by Leogio360** [comment]
My repo https://github.com/Leogio360/geopostWEBAPP

**Comment by wf9a5m75** [comment]
No. Please include all files of the project, such as `config.xml` like this project.

You can hide your api keys.

**Comment by Leogio360** [comment]
added config.xml and some other files in the project files directory

**Comment by wf9a5m75** [comment]
I just built and run your app.
![2054](https://user-images.githubusercontent.com/167831/35895475-74368294-0b6c-11e8-8b0b-4aede4dfefc4.gif)

**Comment by Leogio360** [comment]
No, the problem is that I can't click on the two white buttons that are over the map. If I click on them after the screen rotate, the click is transferred on the map. If I double click on the button, the map zoom

**Comment by wf9a5m75** [comment]
Oh, sorry. I will check it later again.

**Comment by Leogio360** [comment]
Ok thanks for your time.

**Comment by wf9a5m75** [comment]
Thank you for reporting the issue, I fixed the problem.
Please reinstall the maps plugin from the multiple_maps branch.
I will release the next miner version up if no one reports new issue in couple of days.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="..."

```

![2054](https://user-images.githubusercontent.com/167831/35944594-d38590b4-0c11-11e8-8476-6bf72043f32f.gif)

**Comment by Leogio360** [comment]
Thank you for the super-fast fix
