### ISSUE TITLE
touch problem with cordova-plugin-statusbar

### ISSUE THREAD

**Issue by shrijan** [mapsplugin/cordova-plugin-googlemaps#2055]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-badge 0.8.5 "Badge"
cordova-plugin-calendar 4.6.0 "Calendar"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-cocoapod-support 1.3.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.2.3 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-local-notification 0.9.0-beta.1 "LocalNotification"
cordova-plugin-nativeclicksound 0.0.3 "Native Click Sound"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
cordova.plugins.diagnostic 3.6.7 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.1.0 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

iPhone x touch at back button or top nav bar not working
**Expected behavior:**

When google maps plugin remove touch event works fine. It might me issue with cordova-plugin-statusbar. 
Navbar works fine in other iphone
**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, please share your project files (everything) on github.

**Comment by shrijan** [comment]
https://piyashrija@bitbucket.org/piyashrija/iphonexgooglemap.git
For some reason, the map is greyed out but the issue is reproduced when you click "about" link and load about page with the map. When trying to hit back button there is no response in iphonex. but its fine with other iPhones.

**Comment by wf9a5m75** [comment]
Thank you for sharing the project. I will check it tomorrow.

By the way, gray map is api key problem.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by shrijan** [comment]
Thanks Masashi

**Comment by shrijan** [comment]
Touch event is a bit slow with other iPhones as well. You have to tap multiple time to go back. Thanks

**Comment by wf9a5m75** [comment]
Could you take a screen record? I haven't tried your app yet.

**Comment by wf9a5m75** [comment]
Regarding of the `touch is slow`, if you use the iPhoneX simulator, it is always slow.
Even if the touch is slow on real iPhoneX device, please take a video.
I have not iPhone X. (I have no plan to buy it also)

**Comment by shrijan** [comment]
Its not with simulator tap is not working at all in iphonex. with other iphone its you have to tap multiple time

**Comment by shrijan** [comment]
https://www.youtube.com/watch?v=J96I_hVYr-E
not able to click back button

**Comment by shrijan** [comment]
Next video with iPhone 6. I mentioned this issue earlier and was fixed at the time but I am having issue again 
https://www.youtube.com/watch?v=FMbmGeR5xM0

when hitting back button it zooms map instead of going back. Thanks

**Comment by wf9a5m75** [comment]
Well, there is no pointer, I can not detect where did you tap on...

**Comment by shrijan** [comment]
https://www.youtube.com/watch?v=XPuqOtZWWJo
This is bit clear Thanks

**Comment by wf9a5m75** [comment]
Please try the https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/39131e5e5f4e4fe7a642fe512435a5ccd3c7aef6

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#39131e5 --variable ...
```

**Comment by shrijan** [comment]
Thanks for the update.
Now back button is responsive to all iPhone except in iphonex. I have updated github to reflect the issue.

**Comment by wf9a5m75** [comment]
What is the reflect issue? Touch slow?

**Comment by shrijan** [comment]
No, back button not working. I will post the video.

**Comment by shrijan** [comment]
https://www.youtube.com/watch?v=BtYtNoD7GoU
Thanks

**Comment by wf9a5m75** [comment]
That's strange. I tested on simulator, and it worked.

**Comment by shrijan** [comment]
did you test with iphonex simulator

**Comment by wf9a5m75** [comment]
of course

**Comment by shrijan** [comment]
is it updated code from github account

**Comment by shrijan** [comment]
i remove title from about page.

**Comment by shrijan** [comment]
if you have the title than load map after that then back button works fine.

**Comment by wf9a5m75** [comment]
I'm busy tonight. I will test your repo tomorrow.

**Comment by shrijan** [comment]
No worries, Thanks  for your help.

**Comment by shrijan** [comment]
Any update on this. With new #39131e5 i have scrolling problem with other page after opening map.

**Comment by shrijan** [comment]
I got this error in console module 
cordova-plugin-googlemaps.CordovaGoogleMaps already defined.

**Comment by wf9a5m75** [comment]
Please reinstall from the multiple_maps branch.
The error is no affect to work.

**Comment by shrijan** [comment]
Thanks for the update.
Back button still not working.

**Comment by wf9a5m75** [comment]
I know. I'm so busy today.

**Comment by shrijan** [comment]
All good no hurry

On Fri, Feb 9, 2018 at 11:49 AM, Masashi Katsumata <notifications@github.com

**Comment by wf9a5m75** [comment]
Fix: Please reinstall the plugin from the multiple_maps branch.
For this time, please reinstall the maps iOS SDK plugin also.

```
$> cordova plugin rm cordova-plugin-googlemaps
$> cordova plugin rm com.googlemaps.ios
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```

**Comment by wf9a5m75** [comment]
![2055](https://user-images.githubusercontent.com/167831/36010147-cbc7d1e0-0d04-11e8-8b75-8e25b6e2f157.gif)

**Comment by shrijan** [comment]
Thanks. Now button overlay on the map is zooming map instead of button action on click

**Comment by shrijan** [comment]
I just pushed the issue to the github.

**Comment by wf9a5m75** [comment]
What?

**Comment by shrijan** [comment]
https://www.youtube.com/watch?v=BgwTj9kUICg
please check video

**Comment by wf9a5m75** [comment]
Umm...

**Comment by wf9a5m75** [comment]
I inspected the problem, I didn't have enough time to fix it. I will check it again tomorrow

**Comment by wf9a5m75** [comment]
Fixed
![2055_compress](https://user-images.githubusercontent.com/167831/36048297-98ebe826-0d93-11e8-8f75-df88e56f6fda.gif)

**Comment by shrijan** [comment]
Thank you.

**Comment by iChuaNz** [comment]
hi im having almost the same issues as this but above does not help, my nav bar 1st item cannot click.
not just that is like the whole area of the top cannot be click. as highlighted in red in image[
![screen shot 2019-01-22 at 6 30 48 pm](https://user-images.githubusercontent.com/33714941/51529711-38d47c80-1e74-11e9-8cf9-f1e601ded12b.png)
](url)

**Comment by iChuaNz** [comment]
is weird that after install this plugin only causes this problem. is like that area being block from touching

**Comment by iChuaNz** [comment]
and is every screen of the app, that hightlight red area is not allow to click, if any of my button or clickable div is at that red region.

**Comment by shrijan** [comment]
Hey,

I just signed the petition "parliament : कुलमान बिरुद्द लाग्ने संसद सदस्य
अमनलाल मोदिलाइ संसदबाट फिर्ता ल्याउन दवाव दिउ" and wanted to see if you
could help by adding your name.

Our goal is to reach 5,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/F4HkDZwYtB

Thanks!
shrijan
