### ISSUE TITLE
plugin is not defined

### ISSUE THREAD

**Issue by JakeCube** [mapsplugin/cordova-plugin-googlemaps#2058]
Cordova version:- 8.0.0
Phonegap version :- 7.1.1
---------------------------------
Cordova plugin list : - 
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-crypt-file 1.3.3 "CordovaCrypt"
cordova-plugin-googlemaps 2.2.3 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"

Error Message from console:
Uncaught ReferenceError: plugin is not defined

I'm referring to [THIS](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/Installation/phonegap/README.md) to make installation

**Comment by wf9a5m75** [comment]
That tutorial is for v1.x, not for v2.x.

This plugin does not support for browser. Only works on android or ios devices.

If you need more information, please share your project files(everything) on GitHub.

**Comment by JakeCube** [comment]
Do this plugin supporting for android 4.0 and below?

**Comment by wf9a5m75** [comment]
ping

**Comment by JakeCube** [comment]
Thanks for prompt reply, i'm very new to Phonegap with plugins. 
Previously i been using Google Maps Javascript API 3, but it seems keep crashing & freeze the app,
also i've created a repo on GitHub. [LINK](https://github.com/JakeCube/GMapsPhoneGap)

**Comment by wf9a5m75** [comment]
Thank you for sharing your repo. Please try like this:

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="..."
```

By the way, the map_canvas div is too small.
![screenshot_20180207-192352](https://user-images.githubusercontent.com/167831/35954194-2920efd4-0c3d-11e8-8aac-d5ded0ff0c33.png)

**Comment by JakeCube** [comment]
I've change the style to width: 300px & height: 300px, but it still notable to display the map.
Also i've tried to remove previous plugin and use the multi-map version plugin provided by you 

![image](https://user-images.githubusercontent.com/20925630/35954456-b551e5ee-0cc4-11e8-9210-1a9510b142d3.png)

**Comment by wf9a5m75** [comment]
gray map is api key problem.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
@JakeCube Did you solve your problem?

**Comment by wf9a5m75** [comment]
Since there is no update, I close this issue

**Comment by JakeCube** [comment]
Sorry, lately due health issue was stopped to develop on my prototype.
I've tested on method 3 on :  
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

Since i'm using phonegap/cordova to build android i still getting empty map.
May i know how should i access & active for method 2 and 4.

**Comment by JakeCube** [comment]
Somehow by adding android key and remove to none I've solved the issue...
It shows the maps but not displaying any marker etc...

**Comment by JakeCube** [comment]
Solved... Somehow by adding android key and change back to none key it works.

**Comment by kalaiprakash93** [comment]
I have same issue..what is the solution?
