### ISSUE TITLE
API key problems

### ISSUE THREAD

**Issue by Bravcoveoko21** [mapsplugin/cordova-plugin-googlemaps#2059]
**I'm submitting a ...**  (check one with "x")
- [] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

Hey, 

First of all I am beginner with cordova and all that stuff around this. My issue is that when I type your console code : cordova plugin add cordova-plugin-googlemaps I get message which says: Error: Variable(s) missing: API_KEY_FOR_ANDROID. I have already got api key for android and ios as well but do know where to put them :( , some sources say that AndroidManifest.xml has to be changed. I am completely lost so. Big thanks for all advices.

**Comment by wf9a5m75** [comment]
```
$> cordova platform rm android

$> cordova platform add android
```

**Comment by Bravcoveoko21** [comment]
When I wrote platform add it showed same error with missing API_KEY_FOR_ANDROID.

**Comment by wf9a5m75** [comment]
It means you failed to install the plugin.

```
$> cordova platform rm android ios

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova platform add android

$> cordova plugin add cordova-plugin-googlemaps --variable ...
```

Please do your best as much as possible

**Comment by wf9a5m75** [comment]
@Bravcoveoko21 Did you solve your problem?

**Comment by Bravcoveoko21** [comment]
@wf9a5m75 plugin is succesfuly installed :) sorry for late answer ..thanks :)

**Comment by kapilSoni101** [comment]
Above is resolve but after add ios platform got another error 

Failed to install 'cordova-plugin-googlemaps': undefined
Error: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Users/kapil/Desktop/project/AMS/node_modules/.bin in PATH, mode 040777
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)
