### ISSUE TITLE
Class KmlOverlay not found

### ISSUE THREAD

**Issue by pescador07** [mapsplugin/cordova-plugin-googlemaps#2060]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

com-sarriaroman-photoviewer 1.1.11 "PhotoViewer"
cordova-plugin-calendar 4.6.0 "Calendar"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.2.3 "cordova-plugin-googlemaps"
cordova-plugin-nativegeocoder 1.0.2 "NativeGeocoder"
cordova-plugin-network-information 2.0.2-dev "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
cordova-sqlite-storage 2.2.0 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

    "@ionic-native/core": "^4.5.3",
    "@ionic-native/google-maps": "^4.5.3",

**Current behavior:**
Google Maps works correctly but I can't use KmlOverlay because the class is not defined in ionic-native/google-maps

I have searched in "node_modules/ionic-native/google-maps/index.d.ts" and  no KML appears anywhere, but I have the latest version installed. I do not understand anything.

Thanks

**Comment by wf9a5m75** [comment]
ionic-native/google-maps is not implement yet

**Comment by wf9a5m75** [comment]
All source code is open, and it is managed by ionic-team.
Why don't you implement the method and send it as PR?
That's open source community ;)

https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/google-maps/index.ts
