### ISSUE TITLE
Location disabled callback

### ISSUE THREAD

**Issue by jonatarussi** [mapsplugin/cordova-plugin-googlemaps#2063]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
com.phonegap.plugins.nativesettingsopener 1.2 "Native settings"
cordova-android-play-services-gradle-release 1.2.0 "cordova-android-play-services-gradle-release"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-apprate 1.2 "AppRate"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-certificates 0.6.4 "Certificate Plugin"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-googlemaps 2.2.4-beta-20180207-1925 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-nativestorage 2.0.1 "NativeStorage"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
phonegap-plugin-push 1.8.1 "PushPlugin"
russi-device-accounts 1.0.0 "Device Accounts"
russi-plugin-dialogs 1.2.7 "Notification"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"

```

**Current behavior:**
When the location is globaly disabled by the user, the plugin do not call the error callbak

**Expected behavior:**
Plugin should call error callback when location services are disabled

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/5868f2fef9cd7ba45d9b93fbf5b14e1cbbd9eccd/src/android/plugin/google/maps/PluginLocationService.java#L118-L135

**Comment by jonatarussi** [comment]
Yes, I saw this..

If only permissions are denied, it works.

But if the user disable location services, the app never gets the error callback

**Comment by wf9a5m75** [comment]
> the user disable location services

The plugin should ask the location permission.

**Comment by jonatarussi** [comment]
Is not asking

I do not know what is happening.

What can I send to you see the error?

**Comment by wf9a5m75** [comment]
Please take a screen record (video), and upload it to youtube, including how to disable the location service.

**Comment by jonatarussi** [comment]
https://youtu.be/_dvU7ciIhU4

**Comment by jonatarussi** [comment]
I solved this by creating a plugin to check if GPS is enabled using location manager..

Now I have another problem.

The "myLocationButton" do not works and map do no shows the blue dot of my location

Any ideia what is happening?

**Comment by wf9a5m75** [comment]
As I explained here, if you set `mylocation: false, mylocationbutton: true`, the mylocation button does not work anything. It just fires the `MY_LOCATION_BUTTON_CLICK` event.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.2.0/README.md#the-mylocation-property-has-changed

**Comment by jonatarussi** [comment]
Oh sorry. I was using only the `myLocationButton: true`. I will test with both set to true

**Comment by jonatarussi** [comment]
Ok now it is working.

But if the app does not have permission to geolocation, the plugin do not ask for permission. I do not know why, but this function `cordova.hasPermission("android.permission.ACCESS_COARSE_LOCATION")`  return true even if I denied the permission

**Comment by wf9a5m75** [comment]
![2063_compress](https://user-images.githubusercontent.com/167831/35991262-7d5f2e5c-0cbb-11e8-990c-eedb8c31cd82.gif)

**Comment by jonatarussi** [comment]
![sem titulo](https://user-images.githubusercontent.com/20585280/35991938-ec20dfc8-0cef-11e8-959c-70eac1d1a05a.gif)

**Comment by wf9a5m75** [comment]
If you have problem with `cordova.hasPermission("android.permission.ACCESS_COARSE_LOCATION")`, please ask to apache cordova team.

**Comment by jonatarussi** [comment]
Yes... I have implemented this method to my plugin too, and even in my plugin the method returns true. I know that problem is not in your plugin.

**Comment by wf9a5m75** [comment]
I can not reproduce your issue.
![2063_compress](https://user-images.githubusercontent.com/167831/35992281-b4ab234a-0cbe-11e8-9933-e3ceeea47e3f.gif)

**Comment by jonatarussi** [comment]
Yes, I know. Probably is a bug from cordova/android. Thanks for your support

**Comment by jonatarussi** [comment]
Hi.. Using `PermissionChecker.checkSelfPermission(cordova.getActivity().getApplicationContext(), Manifest.permission.ACCESS_COARSE_LOCATION)` instead `cordova.hasPermission("android.permission.ACCESS_COARSE_LOCATION")` the permission status works fine.

**Comment by wf9a5m75** [comment]
Um, PermissionChecker is part of `android.support.v4` library. It means the plugin depends on additional the library.

**Comment by jonatarussi** [comment]
I implemented in one of my plugins, and I will check the permission before call the getMyLocation method. I have tested only in Android 6. Needs to test in other api levels

**Comment by wf9a5m75** [comment]
Thank you for additional information. I'm testing.

**Comment by wf9a5m75** [comment]
Thank you for your investigation. I appreciate for your help. I implemented the code of `PermissionChecker`, and `return error callback if no provider is available`.

Please reinstall the plugin from the multiple_maps branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="..."
```

![2063](https://user-images.githubusercontent.com/167831/36003615-b358eec6-0ce3-11e8-9ad9-3cfcd26a5aec.gif)

**Comment by jonatarussi** [comment]
Thank you

**Comment by matheusdavidson** [comment]
Hi there, the multiple-maps branch does not have mylocation in the interface, only mylocationbutton option.

**Comment by wf9a5m75** [comment]
This?
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Map.js#L158-L161
