### ISSUE TITLE
Can't render the map at the bottom outside screen

### ISSUE THREAD

**Issue by kryptonn** [mapsplugin/cordova-plugin-googlemaps#2064]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-customurlscheme 4.2.0 "Custom URL scheme"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-dialogs 1.3.0 "Notification"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-globalization 1.0.4 "Globalization"
cordova-plugin-googlemaps 2.2.3 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-whitelist 1.3.0 "Whitelist"

**Current behavior:**

I have a list of products, the map is displayed at the end of the list.
Ii have to scroll down to the map div.
But the div map is blank.
And when i jump to the div before the map start to render it renders properly.
I test with a button under the map that do 
                    map.setDiv();
                    map.setDiv(mapDiv);
And the map renders properly (i guess because the div is visible on the screen)

**Expected behavior:**

Rendering the map in the div outside the screen so that i can have the map when i scroll down the product list.

**Comment by wf9a5m75** [comment]
Map requires a div.

**Comment by wf9a5m75** [comment]
I think you probably set `HYBRID` or `SATELLITE` for the map type id.
Those mapType requires to display in screen.

Anyway, this plugin is heavy to use in list.
I **strongly** recommend to use Google Maps Static API, which returns a map as image(png)
https://developers.google.com/maps/documentation/static-maps/?hl=en

**Comment by kryptonn** [comment]
i undersdand your point about memory.
But my list is very small and is not spending large amount of memory.
It's only "one or 2 screens" of height.

And when i put the map at the top of the list it works perfectly.

I can't use the google map static api because i still need a bit of interaction on the marker to set a link to the store.
I succeed by putting a trigger on the underlying map div so that i can display the marker info on a simple click anyway on the map (because i disable all intercations so that the map can scroll in the list)

You said you stop the map until the map is in screen.
Is there a way to wake up the map as the div appears in screen ?

**Comment by wf9a5m75** [comment]
> Is there a way to wake up the map as the div appears in screen ?

Not available. I focus on the plugin stability. I tested so many cases, and at end up, creating maps outside of screen causes out-of-memory easily.

**Comment by kryptonn** [comment]
ok, thanks for your quick replies !
