### ISSUE TITLE
Add marker to cluster

### ISSUE THREAD

**Issue by mapnia** [mapsplugin/cordova-plugin-googlemaps#2065]
Hi, do you have any sample of how to add a marker to a cluster? I tried with map.addMarker, the marker is added to the map but the cluster is not working.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/MarkerCluster/addMarkerCluster/README.md

**Comment by mapnia** [comment]
Thanks, but how can I add a new marker after I loaded the array? For example when I move the camera. Thanks for your help.

Enviado desde mi iPhone

**Comment by wf9a5m75** [comment]
```
markerCluster.addMarkers([
{
      "position": {
        "lat": 19.698399,
        "lng": -155.064864
      },
      "name": "Starbucks - HI - Hilo  03647",
      "address": "Prince Kuhio Plaza_111 East Puainako Street_Hilo, Hawaii 96720",
      "phone": "808-959-0000",
      "icon": "./img/starbucks.png"
    },
    {
      "position": {
        "lat": 19.722763,
        "lng": -155.085598
      },
      "name": "Starbucks - HI - Hilo [D]  03648",
      "address": "Hilo_438 Kilauea Ave_Hilo, Hawaii 96720",
      "phone": "808-933-0000",
      "icon": "./img/starbucks.png"
    }
]);

**Comment by wf9a5m75** [comment]
Did you solve your question?

**Comment by mapnia** [comment]
I am feeling really stupid.. but I don't know where I have to define markerCluster outside the code that I use to generate it and to reload the markers when I move the camera. 

Can't find variable: markerCluster



Un saludo,

J. Carlos Fernández
jcarlos@mapnia.com

Mapnia Smart Communication S.L.
Calle Fuente, 27 - 28864 Ajalvir (Madrid)
244 Madison Avenue - 10016-2817 New York City (NY, USA)

**Comment by wf9a5m75** [comment]
Please study `event-driven` programming.
```
  map.addMarkerCluster({
    //maxZoomLevel: 5,
    boundsDraw: true,
    markers: dummyData(),
    icons: [
        {min: 2, max: 100, url: "./img/blue.png", anchor: {x: 16, y: 16}},
        {min: 100, max: 1000, url: "./img/yellow.png", anchor: {x: 16, y: 16}},
        {min: 1000, max: 2000, url: "./img/purple.png", anchor: {x: 24, y: 24}},
        {min: 2000, url: "./img/red.png",anchor: {x: 32,y: 32}}
    ]
  }, function (markerCluster) {

     map.on("add_more_markers", function(locations) {
       markerCluster.addMarkers(locations);
     });

  });


  var button = document.getElementById("button");
  button.addEventListener("click", function() {

     map.trigger("add_more_markers", [ { newLocation1 }, ... { newLocationN }]);
  });
```

**Comment by mapnia** [comment]
Thanks for all your help and your work!

Un saludo,

J. Carlos Fernández
jcarlos@mapnia.com

Mapnia Smart Communication S.L.
Calle Fuente, 27 - 28864 Ajalvir (Madrid)
244 Madison Avenue - 10016-2817 New York City (NY, USA)
