### ISSUE TITLE
MAP_CLICK triggering when drag

### ISSUE THREAD

**Issue by jonatarussi** [mapsplugin/cordova-plugin-googlemaps#2066]
@**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
com.phonegap.plugins.nativesettingsopener 1.2 "Native settings"
cordova-android-play-services-gradle-release 1.2.0 "cordova-android-play-services-gradle-release"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-apprate 1.2 "AppRate"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-certificates 0.6.4 "Certificate Plugin"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-googlemaps 2.2.4-beta-20180207-1925 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-nativestorage 2.0.1 "NativeStorage"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
phonegap-plugin-push 1.8.1 "PushPlugin"
russi-device-accounts 1.0.27 "Device Accounts"
russi-plugin-dialogs 1.2.7 "Notification"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"

```

**Current behavior:**
When I try to drag map to navigate in map, the MAP_CLICK is triggered

**Expected behavior:**
The map should to be dragged

<img src="https://user-images.githubusercontent.com/20585280/36005267-f85a4bde-0d1d-11e8-9444-c08d307ed071.gif" width="250">

**Comment by wf9a5m75** [comment]
Fix: Please reinstall the plugin from the multiple_maps branch.
For this time, please reinstall the maps iOS SDK plugin also.

```
$> cordova plugin rm cordova-plugin-googlemaps
$> cordova plugin rm com.googlemaps.ios
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```

**Comment by shrijan** [comment]
I am having this issue back again with the new update from multiple_maps branch. Thanks

**Comment by wf9a5m75** [comment]
@shrijan Please make an example, because the current multiple_maps branch does not use the same implementation as the master branch. So it should be impossible to reproduce the issue with the multiple_maps branch.

**Comment by shrijan** [comment]
Sorry my mistake i was using wrong version of file.  Thanks
