### ISSUE TITLE
ios build failed with cordova googlemap plugin

### ISSUE THREAD

**Issue by pratikTH** [mapsplugin/cordova-plugin-googlemaps#2067]
>>getting this error with cordova build ios command

../../Plugins/cordova-plugin-googlemaps/PluginLocationService.m:109:20: error: no known class method for selector
      'scheduledTimerWithTimeInterval:repeats:block:'
          [NSTimer scheduledTimerWithTimeInterval:6000 repeats:NO block:^(NSTimer *timer) {
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

this is my config.xml
<plugin name="cordova-plugin-googlemaps" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps">
        <variable name="API_KEY_FOR_ANDROID" value="apikey"/>
        <variable name="API_KEY_FOR_IOS" value="apikey" />
        <variable name="PLAY_SERVICES_VERSION" value="11.8.0" />
    </plugin>

>>ionic info

Cordova CLI: 6.4.0 
Ionic Framework Version: 3.9.2
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 3.1.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS
Node Version: v7.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by wf9a5m75** [comment]
Duplicated with https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2061
