### ISSUE TITLE
Marker icon stretched on toggle

### ISSUE THREAD

**Issue by shrijan** [mapsplugin/cordova-plugin-googlemaps#2068]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-googlemaps 2.2.4-beta-20180209-1158 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

https://youtu.be/rPXZWAe-YiE
**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.



```
https://piyashrija@bitbucket.org/piyashrija/iphonexgooglemap.git

Sorry to trouble you again. :)

**Comment by wf9a5m75** [comment]
I couldn't understand what the problem is.

**Comment by wf9a5m75** [comment]
By the way, this is not good way.
```
marker[Symbol.for("vars")].position.lng
```

```
marker.getPostion()
```

is correct way

**Comment by wf9a5m75** [comment]
I see, but it is a problem of Google Maps SDK for iOS itself, not this plugin.

**Comment by wf9a5m75** [comment]
You need to specify the `size` property.

```
      'icon': {
        'url' : "www/img/park.png",
        'size': {
             width: 32,
              height: 38
         }
      },
```

**Comment by wf9a5m75** [comment]
I will inspect the details if I have enough time during this weekend.

**Comment by shrijan** [comment]
I defined size as mentioned but issue still persists Thanks

**Comment by shrijan** [comment]
Defining size fixed the issue Thanks
