### ISSUE TITLE
Onsen go back issue

### ISSUE THREAD

**Issue by mapnia** [mapsplugin/cordova-plugin-googlemaps#2069]
Hi, I am usin Onsen 2.9.1 with AngularJS 1, when I use the navigation and go to a page from the map, when I go back, the map is blank. Do you know what is the problem or how can I refresh it?

Regards, 

J. Carlos

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by mapnia** [comment]
I can’t upload it, so you can close this question and I will investigate, thank you.

Enviado desde mi iPhone
