### ISSUE TITLE
Select event not trigger on map

### ISSUE THREAD

**Issue by shrijan** [mapsplugin/cordova-plugin-googlemaps#2070]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-googlemaps 2.2.4-beta-20180209-1158 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

On select changed event text should be alerted. if map is removed then select changed event is triggered
**Screen capture or video record:**
https://youtu.be/h63VEYMLdz4

**Related code, data or error log (please format your code or data):**
https://piyashrija@bitbucket.org/piyashrija/iphonexgooglemap.git
```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
This is not a bug of this plugin.
https://stackoverflow.com/a/31961619/697856

The [DONE] button is not displayed by `cordova-plugin-ionic-keyboard`.
You need to change the settings `Keyboard.hideFormAccessoryBar(false);`

**Comment by wf9a5m75** [comment]
![2070](https://user-images.githubusercontent.com/167831/36116649-d5418b00-0feb-11e8-9a8e-97968bde62ea.gif)

**Comment by shrijan** [comment]
Thank you so much. Yeah was the issue with keyboard plugin.
