### ISSUE TITLE
Change size of myLocation marker

### ISSUE THREAD

**Issue by caleb87** [mapsplugin/cordova-plugin-googlemaps#2074]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

cordova-plugin-googlemaps v2.2.4
phonegap 7.1.1

I added the myLocation marker by adding controls.myLocation = true. The dot is pretty small on my Pixel 2. Is it possible to scale the size of this?

The Google Maps app has a location marker that is probably double the size. Obviously, I could just use a regular marker, but then I lose the accuracy radius.

**Comment by wf9a5m75** [comment]
That blue dot comes from the native APIs, not from this plugin. Thus we can not change the size or design.
