### ISSUE TITLE
google's direction and map buttons in bottom right corner.

### ISSUE THREAD

**Issue by alextapia007** [mapsplugin/cordova-plugin-googlemaps#2075]
**I'm submitting a ...**  (check one with "x")
- [x ] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ x] **Android**
- [ x] **iOS**

some way to show google's direction and map buttons in bottom right corner without marker click?

**Comment by wf9a5m75** [comment]
No. That toolbar comes from the google maps Android API when you click on a marker.

So, my recommendation is 
- disable the map tool bar with `mapToolbar: false`, and
- create your tool bar with html
