### ISSUE TITLE
Android: setMyLocationEnabed(true) hide MyLocationButton

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#2076]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
branch-cordova-sdk 2.6.17 "branch-cordova-sdk"
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-open-native-settings 1.4.1 "Native settings"
cordova-plugin-ble-central 1.1.4 "BLE"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.2.4 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-qrscanner 2.5.0 "QRScanner"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-swift-support 3.1.1 "SwiftSupport"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
map.setMyLocationEnabled(true) disabled the MyLocation button event in the map options is myLocationEnabled: true

The problem may ocurred since version 2.2.4.

**Comment by wf9a5m75** [comment]
```
{
  controls: {
     myLocation: true,
     myLocationButton: false
  }
}
```

**Comment by wf9a5m75** [comment]
Fixed. Please reinstall the plugin from the multiple_maps branch.

![2076](https://user-images.githubusercontent.com/167831/36231229-2d3581e8-1192-11e8-99fc-b47e6c125d6c.gif)

**Comment by vosecek** [comment]
Works, thanks.
