### ISSUE TITLE
getMyLocation not working on android 4.4

### ISSUE THREAD

**Issue by jonatarussi** [mapsplugin/cordova-plugin-googlemaps#2077]
*I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
com.phonegap.plugins.nativesettingsopener 1.2 "Native settings"
cordova-android-play-services-gradle-release 1.2.0 "cordova-android-play-services-gradle-release"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-apprate 1.2 "AppRate"
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-certificates 0.6.4 "Certificate Plugin"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-googlemaps 2.2.4 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-nativestorage 2.0.1 "NativeStorage"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
phonegap-plugin-push 1.8.1 "PushPlugin"
russi-device-accounts 1.0.27 "Device Accounts"
russi-plugin-dialogs 1.2.7 "Notification"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
Plugin do not retrieve the location on Android 4.4 when call the method getMyLocation

**Expected behavior:**
Plugin should to retrieve the location when I call the method getMyLocation

**Comment by wf9a5m75** [comment]
This is screen record on Android 4.4
![2077](https://user-images.githubusercontent.com/167831/36221369-ba4cc674-1172-11e8-81ee-03c1278a0f65.gif)

**Comment by jonatarussi** [comment]
This is virtual device? I had tried in AVD and in a tablet motorola xoom

**Comment by wf9a5m75** [comment]
This is actual device, Moto G, Android 4.4.4

**Comment by jonatarussi** [comment]
Huuuum, I tried in AVD version 4.4.2 and in Motorola Xoom version 4.4.4

Both do not work

**Comment by wf9a5m75** [comment]
Do you have any other devices, not AVD?

**Comment by jonatarussi** [comment]
At this time only the motorola xoom. I think at home I have a moto E, but i don't know which version it is. I will check and test today

**Comment by jonatarussi** [comment]
Ok. I have tested in my moto E in 4.4.4 android version. Works fine. But in previous version do not work

**Comment by wf9a5m75** [comment]
What is `previous version`?

**Comment by jonatarussi** [comment]
Android 4.4.2

**Comment by wf9a5m75** [comment]
I see. But I don't have it, and no body use Android 4.4.2 anymore.

**Comment by jonatarussi** [comment]
Of course. I will set my `android-minSdkVersion` to 19. But API 19 is to 4.4 Android version. The people with 4.4.2 version will be able to download. I have to check in my code if version is < 4.4.4.

Thank you for your quick responde. Great plugin, congrats
