### ISSUE TITLE
poly.containsLocation() question

### ISSUE THREAD

**Issue by alextapia007** [mapsplugin/cordova-plugin-googlemaps#2078]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

hello.
I try to use poly.containsLocation().

    map.getMyLocation(function(location) {
            var position={lat: location.latLng.lat, lng: location.latLng.lng};
            console.log('position')
            console.log(position)
            console.log('puntos')
            console.log(puntos)
            var contain = plugin.google.maps.geometry.poly.containsLocation(position, puntos);
            console.log(contain)
    });
   
<img width="1263" alt="captura de pantalla 2018-02-14 a la s 12 33 28" src="https://user-images.githubusercontent.com/15269078/36221330-61de7a4e-1183-11e8-870b-0623ba23e5f9.png">

what have I done wrong?

**Comment by wf9a5m75** [comment]
Please create an example application that includes from `Map.getMap()`, `map.animateCamera()`, then `containsLocation()`.
Then please share it on github.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there was no enough information, I close this thread
