### ISSUE TITLE
Can't get the demo code to load 

### ISSUE THREAD

**Issue by sean-hill** [mapsplugin/cordova-plugin-googlemaps#2079]
**I'm submitting a ...** 
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**
- [ ] **Android**
- [x] **iOS**

**cordova information:**

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.2.4 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.5 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^3.12.1"
"@ionic-native/google-maps": "^4.5.3"
```

**Current behavior:**
The demo code does not load the google maps plugin.

**Expected behavior:**
For the map to load like the demo does.

**Screen capture or video record:**

<img width="369" alt="screen shot 2018-02-14 at 10 02 56 pm" src="https://user-images.githubusercontent.com/1205866/36241325-d731c20c-11d2-11e8-8bc2-b7f7d08145ba.png">

**Comment by sean-hill** [comment]
I face the same issue using the [example app](https://github.com/mapsplugin/ionic-googlemaps-starter-tab).

<img width="395" alt="screen shot 2018-02-14 at 10 14 48 pm" src="https://user-images.githubusercontent.com/1205866/36241605-9dd907b6-11d4-11e8-8c3f-c404581f72db.png">

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by sean-hill** [comment]
That was it. Toggling on the SDK's, thank you, I'm an idiot 😆
