### ISSUE TITLE
App says cant connect to index.html when start

### ISSUE THREAD

**Issue by KproApps2** [mapsplugin/cordova-plugin-googlemaps#2080]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-whitelist 1.3.2 "Whitelist"
pushwoosh-cordova-plugin 7.0.8 "Pushwoosh"
and then your plugin
```
When I install this plugin , my app goes white and then an error saying unsuccessful 
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please share your project files (everything) on GitHub.

**Comment by wf9a5m75** [comment]
ping

**Comment by KproApps2** [comment]
Do you have a bitbucket account and if yes can you give me username please

**Comment by wf9a5m75** [comment]
wf9a5m75

**Comment by KproApps2** [comment]
Sent invite, wow this error is killing me, it works find on ios but on android it just goes white and then says connection unsuccessful after I install the plugin. Would appreciate help and will donate

**Comment by wf9a5m75** [comment]
Could you tell me what the repo name is?

**Comment by KproApps2** [comment]
Yes , ssd

**Comment by KproApps2** [comment]
Any thoughts so far?

**Comment by wf9a5m75** [comment]
Ok, I don't know why but even I don't install the maps plugin, your app does not start on Android.

**Comment by wf9a5m75** [comment]
I spent two hours to debug your app, but I could not figure out the reason that your app does not run with this maps plugin.

So my recommendation is please use another maps plugin, such as 
https://github.com/Telerik-Verified-Plugins/Mapbox

**Comment by KproApps2** [comment]
Yeah, how weird. I spent like 4 hours at least. I changed the app from ionic to Cordova, so maybe it is having problems understanding this change

**Comment by KproApps2** [comment]
I really like your plugin but can't understand why . It just does not start

**Comment by wf9a5m75** [comment]
If you want to use this maps plugin anyway, please create an empty project with latest cordova (currently cordova@8.0.0), and try with very simple code.

**Comment by wf9a5m75** [comment]
I have to leave my company office now anyway, I will check this tomorrow.

**Comment by KproApps2** [comment]
Okay sure, thank you for your efforts so far. In a way it is reassuring it is not only me that is having this problem. I made a new app with your plugin and worked fine. Something within the www folder doing this. Not sure what

**Comment by wf9a5m75** [comment]
Please port your code from old project to new project step by step.
You will figure out the reason probably.
I appreciate if you figure out the reason.

**Comment by KproApps2** [comment]
In my other cordova created project works fine,

**Comment by wf9a5m75** [comment]
Please past the all error logs

**Comment by KproApps2** [comment]
Okay, I think I am fixing this one. Will do

**Comment by wf9a5m75** [comment]
I close this thread at once, but I appreciate the update what the reason was.
