### ISSUE TITLE
Marker rendering issue

### ISSUE THREAD

**Issue by InfernoTheDev** [mapsplugin/cordova-plugin-googlemaps#2081]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
com.testfairy.cordova-plugin 2.1.8 "TestFairy Plugin"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-badge 0.7.3 "Badges"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-geolocation 2.3.0 "Geolocation"
cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin"
cordova-plugin-splashscreen 2.0.0 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-sqlite-storage 2.0.0 "Cordova sqlite storage plugin"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

It juts suddently happen yesterday, Also i try to update plugin's version already it still happen

![screenshot_20180215-125424](https://user-images.githubusercontent.com/23213788/36242807-91d17a8a-1250-11e8-957e-29b20b3e38f0.png)

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, please share your project files (everything) on GitHub.

**Comment by InfernoTheDev** [comment]
@wf9a5m75  It work fine before and yesterday I open the app then it just happen. sorry about share project file it is a company.

**Comment by wf9a5m75** [comment]
Ok, please debug it by yourself.
