### ISSUE TITLE
relative path for markers does not work on Android 8.0

### ISSUE THREAD

**Issue by caleb87** [mapsplugin/cordova-plugin-googlemaps#2082]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-battery-status 1.2.4 "Battery"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-googlemaps 2.2.4 "cordova-plugin-googlemaps"
cordova-plugin-hidden-statusbar-overlay 2.0.1 "HiddenStatusbarOverlay"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
Markers cannot use relative path on Android 8.0. I have to use the absolute path to show markers. This was not the case previously around version 2.0. 
Works on iOS:  img/marker.png

**Expected behavior:**
img/marker.png works for both iOS and Android.

**Comment by wf9a5m75** [comment]
Please share your project files on github.
By the way, I mainly develop the maps plugin on Android 8.1 (Google Pixel 2)

**Comment by caleb87** [comment]
I will try to put together a bare bones demo on GitHub soon, as it should still provide the same result.

Android
**Works**: file:///android_asset/www/img/highResolutionDotBlue.png
**Fails**: www/img/highResolutionDotBlue.png or img/highResolutionDotBlue.png

iOS
**Fails**: file:///var/containers/Bundle/Application/B1DXXXXXXXX/AppName/www/img/highResolutionDotBlue.png
**Works**: img/highResolutionDotBlue.png

I got the absolute paths by using $('#highResolutionDotBlue').prop('src'); on an <img>.

**Comment by wf9a5m75** [comment]
do not add `www/`

**Comment by wf9a5m75** [comment]
As I said if you share your project files on github, I will check it. Otherwise, please debug it by yourself.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Marker/setIcon.html

**Comment by caleb87** [comment]
On a side note, is there any chance the error in attached screenshot could be associated to the plugin? For some reason, some errors including GPS errors are in japanese. 

![error](https://user-images.githubusercontent.com/6970514/36289992-71b6fea2-1280-11e8-8f5e-71c2a1511c13.jpg)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps#quick-install

```
$> cordova plugin add cordova-plugin-googlemaps \
    --variable API_KEY_FOR_ANDROID="..." \
    --variable API_KEY_FOR_IOS="..." \
    --variable LOCATION_WHEN_IN_USE_DESCRIPTION="このデバイスの位置を表示するために権限が必要です"
    --variable  LOCATION_ALWAYS_USAGE_DESCRIPTION="このアプリが起動していないときも位置情報を取得します"
```

**Comment by caleb87** [comment]
That's what I used, except I use phonegap: phonegap plugin add cordova-plugin-googlemaps ....

The variables are even in the config.xml.

I tried version 2.2.3 and the Japanese reverted to English.

I see now it says "Would like to use your current location", and "Dont allow"/"OK". I am using xcode 9.2 to do the build, because I could never get phonegap to build and sign it properly. I've never had an issue with it before, and I've been using this plugin since v1.

In xcode under Info, the Usage Description for both show the variables I entered when installing the app.

**Comment by caleb87** [comment]
How do we set the language to English/Japanese for 2.2.4? I'm trying to get English, but it's showing Japanese.

**Comment by wf9a5m75** [comment]
Could you show me the iphone settings `settings > general > language & region`

**Comment by caleb87** [comment]
I fixed it by going to the plist within xcode. The localization was set to Japanese, and I just changed it to English.

BTW the settings are English & United States.

**Comment by wf9a5m75** [comment]
Did you do like this?
![screen shot 2018-02-16 at 11 13 47 am](https://user-images.githubusercontent.com/167831/36324817-828f515e-130a-11e8-9106-27778a69d371.png)

**Comment by caleb87** [comment]
Yes, though mine only had "Item 0", so I just changed it to English.

**Comment by wf9a5m75** [comment]
Ok, thank you ;)
