### ISSUE TITLE
Can not click on button outside the map div

### ISSUE THREAD

**Issue by stalniy** [mapsplugin/cordova-plugin-googlemaps#2083]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-safariviewcontroller 1.5.2 "SafariViewController"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
phonegap-plugin-push 2.1.3 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
When you put a map and `ion-fab` elements, it's not possible to click on fab elements. All clicks are redirected to map

**Expected behavior:**
Clicks on `ion-fab` should be handled by application logic, not plugin

**Screen capture or video record:**

<img src="https://user-images.githubusercontent.com/1159966/36298719-23d22838-1302-11e8-9b26-e3edfc86eb55.gif" width="250">

**Related code, data or error log (please format your code or data):**
I checked the elements tab in devtools, that elements doesn't have `__pluginDomId` attribute and `.fixed-content` element has `zIndex = 0` in `domPositions` object. Map on the other hand have `zIndex = 100`.

It worked as expected with 2.1.x, before `MutationObserver` was integrated

**Comment by wf9a5m75** [comment]
please share your project files on GitHub

**Comment by wf9a5m75** [comment]
It seems I have no problem.

```html
  <div id="map_canvas">
    <button ion-button (click)="onButtonClick($event)">Demo</button>

    <ion-fab right top small>
        <button  (click)="switch_click()" ion-fab color="light"><ion-icon name="switch"></ion-icon></button>
    </ion-fab>
    <ion-fab left top small>
        <button (click)="exit_click()" ion-fab color="light"><ion-icon name="exit"></ion-icon></button>
    </ion-fab>

  </div>
```
![2083](https://user-images.githubusercontent.com/167831/36329945-aa4078ec-131c-11e8-9bb7-7cc5d7acbdae.gif)

![2083_compress](https://user-images.githubusercontent.com/167831/36329831-3da0b42c-131c-11e8-9ae5-20c6749b73db.gif)

**Comment by stalniy** [comment]
here is my example: https://github.com/stalniy/googlemaps-ionic-fab-issue

**Comment by stalniy** [comment]
looks like that plugin can't detect content projection in `ion-content`

**Comment by wf9a5m75** [comment]
Temporally solution is 

```
<ion-content padding>
  <div #map style="position: absolute; top: 0; left:0;right:0;bottom:0;height: 100%">
    <ion-fab top right >
      <button ion-fab (tap)="callMe()">+</button>
    </ion-fab>
  </div>

</ion-content>
```

**Comment by wf9a5m75** [comment]
Ok, this is a bug, but I won't fix this.
If I change the plugin code for this fix, the performance is slowdown significantly.

I will explain the reason how omit this plugin omit the DOM tree parse tomorrow.

**Comment by wf9a5m75** [comment]
I got a new idea to fix this problem. I will test it tomorrow.

**Comment by wf9a5m75** [comment]
![2083_compress](https://user-images.githubusercontent.com/167831/36357855-e1bba024-14b8-11e8-8ae6-65734af5c9d5.gif)

![2803](https://user-images.githubusercontent.com/167831/36357875-473b651a-14b9-11e8-81e1-e5480a279753.gif)

**Comment by wf9a5m75** [comment]
Please reinstall the maps plugin from the multiple_maps branch.

**Comment by stalniy** [comment]
works as expected! Thanks!

**Comment by NicolasBehra** [comment]
I still have the problem with `ion-fab-list`

**Comment by NicolasBehra** [comment]
Ok, my mistake, I had to put all the `ion-fab` part inside the `div` of the map.
Sorry
