### ISSUE TITLE
MarkerCluster cannot use HtmlInfoWindow

### ISSUE THREAD

**Issue by srawit** [mapsplugin/cordova-plugin-googlemaps#2084]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.2.4 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
phonegap-plugin-push 2.1.3 "PushPlugin"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
"@ionic-native/core": "^4.4.0","@ionic-native/google-maps": "^4.5.3",

**Current behavior:**
when i use fixed data i can show info of marker, but i can not show info of marker  other if marker data come from api.

**Related code, data or error log (please format your code or data):**
```
this.sub = this.service.getdata().subscribe((res) => {
      Promise.all([res]).then(([data]) => {

        let marker_temp = [];
        Object.keys(data).forEach(i => {
          let myLatlng = { lat: data[i].point.lat, lng: data[i].point.lng };
          let icon = {
            url: `assets/imgs/marker/marker_landmark.png`
          };
          marker_temp.push({ "id": data[i].id, "position": myLatlng, "icon": icon });
        });
        this.map.addMarkerCluster({
          boundsDraw: false,
          markers: marker_temp,
          icons: [
            { min: 2, max: 100, url: "assets/markercluster/img/mm5.png", anchor: { x: 16, y: 16 } },
            { min: 100, max: 1000, url: "assets/markercluster/img/mm5.png", anchor: { x: 16, y: 16 } },
            { min: 1000, max: 2000, url: "assets/markercluster/img/mm5.png", anchor: { x: 24, y: 24 } },
            { min: 2000, url: "assets/markercluster/img/mm5.png", anchor: { x: 32, y: 32 } }
          ]
        }).then((markerCluster) => {
      markerCluster.on(GoogleMapsEvent.MARKER_CLICK).subscribe((position) => {
        let marker = position[1];
        var html = [ "<div style='display: inline-block; padding: 10px 10px 20px; width: auto; min-width: 110px; max-width: 200px; height: 50px; '>" ];
        html.push("<div style='font-size:0.8em;'>" + marker.get("name") + "</div>");
        this.sub = this.service.datadetail(marker.get("id")).subscribe((res) => {
          Object.keys(res.data).forEach(e => {
            if (e == 'name') {
              html.push("<div style='display: inline-block; font-family: 'ThaiSans Neue'; font-size: 19px; font-weight: bold; margin: 0; white-space: nowrap; width: 100%; overflow: hidden; text-overflow: ellipsis;'>" + res.data[e] ? res.data[e] : '-' + "</div>");
            };
          });
        });
        html.push("</div>");
        htmlInfoWnd.setContent(html.join(""));
        htmlInfoWnd.open(marker);
      });

        });

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, please share your project files on GitHub

**Comment by srawit** [comment]
So sorry,
Now I'm starting to program and I do not really understand how to build a project in github, but I'll try it do.
The problem is when I use fixed data to create MarkerCluster It works fine for "GoogleMapsEvent.MARKER_CLICK", but I do not understand why I can not use "GoogleMapsEvent.MARKER_CLICK" when linked to a database.

fixed data 
```
dummyData() {
    return [
      {
        "position": {
          "lat": 13.621277232059,
          "lng": 100.7368967756
        },
        "name": "Starbucks - HI - Aiea  03641",
        "address": "Aiea Shopping Center_99-115 Aiea Heights Drive #125_Aiea, Hawaii 96701",
        "phone": "808-484-0000",
        "icon": "./img/starbucks.png"
      },
      {
        "position": {
          "lat": 13.622801638952,
          "lng": 100.73315820544
        },
        "name": "Starbucks - HI - Aiea  03642",
        "address": "Pearlridge Center_98-125 Kaonohi Street_Aiea, Hawaii 96701",
        "phone": "808-484-0000",
        "icon": "./img/starbucks.png"
      },
      {
        "position": {
          "lat": 13.505050784104,
          "lng": 100.99657802988
        },
        "name": "Starbucks - HI - Aiea  03643",
        "address": "Stadium Marketplace_4561 Salt Lake Boulevard_Aiea, Hawaii 96818",
        "phone": "808-488-0000",
        "icon": "./img/starbucks.png"
      },
      {
        "position": {
          "lat": 13.516355421746,
          "lng": 100.97923351745
        },
        "name": "Starbucks - HI - Aiea  03644",
        "address": "Pearlridge Mall_98-1005 Moanalua Road_Aiea, Hawaii 96701",
        "phone": "808-484-0000",
        "icon": "./img/starbucks.png"
      },
      {
        "position": {
          "lat": 21.6507,
          "lng": -158.0652
        },
        "name": "Starbucks - HI - Haleiwa  03645",
        "address": "Pupukea_59-720 Kamehameha Highway_Haleiwa, Hawaii 96712",
        "phone": "808-638-0000",
        "icon": "./img/starbucks.png"
      },
      {
        "position": {
          "lat": 19.699335,
          "lng": -155.06566
        },
        "name": "Starbucks - HI - Hilo  03646",
        "address": "Border Waiakea Center_315-325 Makaala Street_Hilo, Hawaii 96720",
        "icon": "./img/starbucks.png"
      }
    ]
  }

**Comment by wf9a5m75** [comment]
> I do not really understand how to build a project in github

Github is just a repository that keeps your code with version management.
Benefit of Github is you can put your code on it as free (public plan), and share it.
As version control system, you can roll back or compare your code anytime any of your code.

Since I support you in my private time, so I don't spend much time as much as possible.
If you put your code everything on github, I just clone your repository, then I can build it soon. No stressful.

Some people past their short code at here, but it requires I have to create an app within limited time.  It's really stressful.

That's why I ask to put your code on github.

-----

This is Github tutorial for beginner.
https://www.youtube.com/watch?v=0fKg7e37bQE

**Comment by srawit** [comment]
Hi **wf9a5m75**
Sorry, and I know how to solve it.
When I replace the parameter

`` let marker = position[1]; `` it's not work

**Comment by wf9a5m75** [comment]
try `console.log()`

And check out the demo page

https://github.com/wf9a5m75/ionic-googlemaps-demo/blob/master/src/pages/marker-cluster/add-marker-cluster/add-marker-cluster.ts

**Comment by srawit** [comment]
![img_1364](https://user-images.githubusercontent.com/31229422/36338798-e47a403c-13ea-11e8-8e13-625d543ff1a0.PNG)

when can create markerCluster but MARKER:{}
