### ISSUE TITLE
Add: localization for Brazilian Portuguese

### ISSUE THREAD

**Issue by jonatarussi** [mapsplugin/cordova-plugin-googlemaps#2085]
**I'm submitting a ...**  (check one with "x")
- [X] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
com.phonegap.plugins.nativesettingsopener 1.2 "Native settings"
cordova-android-play-services-gradle-release 1.2.0 "cordova-android-play-services-gradle-release"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-apprate 1.2 "AppRate"
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-certificates 0.6.4 "Certificate Plugin"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-googlemaps 2.2.4 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-nativestorage 2.0.1 "NativeStorage"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
phonegap-plugin-push 1.8.1 "PushPlugin"
russi-device-accounts 1.0.27 "Device Accounts"
russi-plugin-dialogs 1.2.7 "Notification"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"

```

**Current behavior:**
Do you know why the plugin puts this in the info.plist?

`<key>CFBundleDevelopmentRegion</key>
    <array>
      <string>Japanese</string>
    </array>`

**Comment by wf9a5m75** [comment]
I announced at https://plus.google.com/+MasashiKatsumata/posts/RC1wbZMR7FD

**Comment by jonatarussi** [comment]
![simulator screen shot - iphone 6s - 2018-02-16 at 14 22 50](https://user-images.githubusercontent.com/20585280/36319009-ba7aa9ce-1328-11e8-99c6-84defee22891.png)

Ok but look this, all the app now have the messages in japanese

**Comment by jonatarussi** [comment]
I can add Brazilian Portuguese to your plugin, where is the messages?

**Comment by wf9a5m75** [comment]
Thank you for offering your help. Could you translate these strings, then past them to here again?

**Android**
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/res/values/pgm_strings.xml


**iOS**
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/strings/Base.lproj/pgm_Localizable.strings

**Comment by jonatarussi** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="pgm_google_close_button">Fechar</string>
  <string name="pgm_api_key_error">Por favor substitua \'API_KEY_FOR_ANDROID\' em platforms/android/app/src/AndroidManifest.xml com sua chave de API!</string>
  <string name="pgm_google_play_error">Google Maps Android API v2 não está disponível nesse dispositivo por alguma razão.</string>
  <string name="pgm_google_play_developer_error">O aplicativo está mal configurado. Este erro não é recuperável e será tratado como fatal. O desenvolvedor deve analisar os logs para determinar o que pode ser feito</string>
  <string name="pgm_google_play_internal_error">Ocorreu um erro interno no Google Play Services. Por favor tente novamente e o erro deverá estar resolvido.</string>
  <string name="pgm_google_play_invalid_account">Você tentou se conectar ao serviço com um nome de conta inválido.</string>
  <string name="pgm_google_play_lincense_check_failed">O aplicativo não está licenciado para o usuário. Esse erro não é recuperável e será tratado como fatal.</string>
  <string name="pgm_google_play_network_error">Ocorreu um erro de rede. Por favor tente novamente e o erro deverá estar resolvido.</string>
  <string name="pgm_google_play_service_disabled">A versão instalada do Google Play Services foi desativada nesse dispositivo. Por favor ative o Google Play Services.</string>
  <string name="pgm_google_play_service_invalid">A versão do Google Play Services instalada nesse dispositivo não é autêntica. Atualize o Google Play Services na Google Play Store.</string>
  <string name="pgm_google_play_service_missing">O Google Play services não existe nesse dispositivo. Por favor instale o Google Play Services.</string>
  <string name="pgm_google_play_service_update_required">A versão do Google Play Services instalada está desatualizada. Por favor atualize o Google Play Services na Google Play Store.</string>
  <string name="pgm_google_play_sign_in_required">Você tentou se conectar ao serviço mas você não está logado. Por favor cheque a configuração do Google Play Services.</string>
  <string name="pgm_no_location_providers">Esse dispositivo não tem nenhum provedor de localização, logo, este aplicativo não pode detectar sua localização.</string>
  <string name="pgm_no_location_service_is_disabled">O serviço de Localização está desativado.</string>
  <string name="pgm_location_rejected_by_user">O serviço de Localização foi rejeitado pelo usuário.</string>
  <string name="pgm_can_not_get_location">Não foi possível detectar sua localização. Tente novamente.</string>
</resources>`

**Comment by jonatarussi** [comment]
`/*
 * Generic
 */
"CLOSE_BUTTON" = "FECHAR";

/*
 * CordovaGoogleMaps.m
 */
"APIKEY_IS_UNDEFINED_TITLE" = "Erro de chave de API";
"APIKEY_IS_UNDEFINED_MESSAGE" = "A variável 'API_KEY_FOR_IOS' não foi registrada.";

"APP_NAME_ERROR_TITLE" = "Você precisa alterar o arquivo config.xml";
"APP_NAME_ERROR_MESSAGE" = "O Google Maps SDK para iOS falha se o campo CFBundleExecutable conter caracteres não-inglês.\nPara maiores detalhes, cheque o comentário no arquivo CordovaGoogleMaps.m";

/*
 * PluginLocationService.m
 */
"LOCAITON_IS_UNAVAILABLE_ERROR_TITLE" = "O serviço de localização não esta disponível";
"LOCAITON_IS_UNAVAILABLE_ERROR_MESSAGE" = "Esse aplicativo precisa acessar sua localização. Por favor ative em 'Ajustes > Privacidade > Serviços de Localização'";

"LOCAITON_IS_DENIED_MESSAGE" = "O aplicativo foi rejeitado para usar os Serviços de Localização.";
"CAN_NOT_GET_LOCATION_MESSAGE" = "Não foi possível obter sua localização.";
"LOCATION_REJECTED_BY_USER_MESSAGE" = "O serviço de localização foi rejeitado pelo usuário.";`

**Comment by wf9a5m75** [comment]
Thank you for your help, @jonatarussi 

I added files to the repo. Could you try the maps plugin from the multiple_maps branch?

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="..."  --variable API_KEY_FOR_IOS="..." 
```

**Comment by jonatarussi** [comment]
`CopyStringsFile /Users/jonata/Library/Developer/Xcode/DerivedData/Utilcar-dbhrzjodzwjtztbrkydcieneiwlk/Build/Products/Debug-iphonesimulator/Utilcar.app/pgm_Localizable.strings Utilcar/Resources/ja.lproj/pgm_Localizable.strings
    cd "/Users/jonata/DevProjects/Projetos DS Develop/infocar/Infocar/platforms/ios"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/jonata/Library/Developer/Xcode/DerivedData/Utilcar-dbhrzjodzwjtztbrkydcieneiwlk/Build/Products/Debug-iphonesimulator/Utilcar.app -- Utilcar/Resources/ja.lproj/pgm_Localizable.strings

error: failed to remove /Users/jonata/Library/Developer/Xcode/DerivedData/Utilcar-dbhrzjodzwjtztbrkydcieneiwlk/Build/Products/Debug-iphonesimulator/Utilcar.app/pgm_Localizable.strings: “pgm_Localizable.strings” couldn’t be removed.`

**Comment by wf9a5m75** [comment]
Maybe 

```
$> cordova platform rm android ios

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="..."  --variable API_KEY_FOR_IOS="..." 

$> cordova platform add android ios
```

**Comment by jonatarussi** [comment]
Ok.

But in the app still showing in Japanese

![simulator screen shot - iphone 6s - 2018-02-16 at 14 22 50](https://user-images.githubusercontent.com/20585280/36323121-fbbcafd2-1336-11e8-8fa0-2db20c0b986c.png)

**Comment by wf9a5m75** [comment]
I think rebooting the device should be solve the problem.

**Comment by jonatarussi** [comment]
No...

Still in japanese

**Comment by wf9a5m75** [comment]
Let's see..

**Comment by jonatarussi** [comment]
Look this 2 properties in .plist

![captura de tela 2018-02-16 as 16 39 02](https://user-images.githubusercontent.com/20585280/36323396-f50bd4dc-1337-11e8-8216-4638229da197.png)
![captura de tela 2018-02-16 as 16 38 56](https://user-images.githubusercontent.com/20585280/36323400-f52d43b0-1337-11e8-8ad9-2a7f5abfebf8.png)

**Comment by wf9a5m75** [comment]
`[完了]` (means `Done` in Japanese) is not defined in the localized messages of this plugin.
It means the word comes from system.

**Comment by jonatarussi** [comment]
Probably the system is choosing the Japanese language because it is in first place in .plist..

I ordered manually the languages in plist and works fine
![captura de tela 2018-02-16 as 16 50 15](https://user-images.githubusercontent.com/20585280/36323848-7c140872-1339-11e8-82f0-292afc74c1af.png)

**Comment by wf9a5m75** [comment]
I see. Then did you solve the problem for the button`[完了]`?

I will search additional information.

**Comment by jonatarussi** [comment]
Yes, after manually sorting languages, the buttons works

**Comment by wf9a5m75** [comment]
Okay..

**Comment by wf9a5m75** [comment]
It seems adding `English` to the top is the answer.
![screen shot 2018-02-16 at 11 13 47 am](https://user-images.githubusercontent.com/167831/36325746-aadb8288-130d-11e8-964d-cb16c6262782.png)


![2085_compress](https://user-images.githubusercontent.com/167831/36325696-7d3b66cc-130d-11e8-80a7-5cfd365f24a5.gif)

**Comment by jonatarussi** [comment]
Note that in Brazil is not Portuguese, but Brazilian Portuguese or pt-br

**Comment by wf9a5m75** [comment]
okay...

**Comment by wf9a5m75** [comment]
Could you reinstall the plugin from the multiple_maps branch, and test it. I specified the language as `Brazilian Portuguese`. Should be fine.

**Comment by jonatarussi** [comment]
Ok. Now I am out of office and get back only in monday.

If you want, close the issue. On monday I will test.

Thank you very much

**Comment by wf9a5m75** [comment]
Okay. I close this issue at once, but you can reply anytime. Have a great weekend!

**Comment by mariohmol** [comment]
Hi.. thanks for the awesome work! I've been passing the `“pgm_Localizable.strings” couldn’t be removed.` 

Tested the new branch, deleted and recreated many times.. and giving same issue.. any ideas?
