### ISSUE TITLE
 The map is not displayed

### ISSUE THREAD

**Issue by gustavao** [mapsplugin/cordova-plugin-googlemaps#2087]
**I'm submitting a ...  (check one with "x")**
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:  (check one with "x")**
- [x] **Android**
- [x] **iOS**

**cordova information:  (run `$> cordova plugin list`) **

call-number 0.0.2 "Cordova Call Number Plugin"
card.io.cordova.mobilesdk 2.1.0 "CardIO"
com.paypal.cordova.mobilesdk 3.5.0 "PayPalMobile"
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-vibration 3.0.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"

**ionic information:**
```
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:
    cordova (Cordova CLI) : 8.0.0 

local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : Linux 4.13

Environment Variables:
    ANDROID_HOME : /home/avao/Android/Sdk

Misc:
    backend : pro
```

**please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
@ionic-native/core": "4.4.0" 
@ionic-native/google-maps": "^4.5.3"
```

**Current behavior:**

the map is not displayed, googleMaps.create is used to create the map.
if necessary, access to the repository can be granted

**Screen capture or video record:**

<img src="https://user-images.githubusercontent.com/36246104/36337972-cca94386-1368-11e8-9c2e-e8668966d17e.png" width="250">

```

**Comment by wf9a5m75** [comment]
You need to remove the background color.

The map is displayed **under the browser**.
![](https://raw.githubusercontent.com/mapsplugin/cordova-plugin-googlemaps-doc/master/v1.4.0/class/Map/mechanism.png)

**Comment by wf9a5m75** [comment]
> if necessary, access to the repository can be granted

If you can not resolve the issue by yourself, please share your project files on git repo.

**Comment by itzamnamx** [comment]
@wf9a5m75 we will do a project cleaup and share the repository, becase the maps version 2.1.1 don't show anything and the maps version 2.2.1 don't let us load the application (gives timeout). give us some minutes.

**Comment by itzamnamx** [comment]
@wf9a5m75 it was our fault, we have created a Key for Javascript instead of Android, we have created the right one using https://developers.google.com/maps/documentation/android-api/signup?hl=es-419

**Comment by wf9a5m75** [comment]
ok. congrats!
