### ISSUE TITLE
Marker Cluster addMarker issue

### ISSUE THREAD

**Issue by HarveyD** [mapsplugin/cordova-plugin-googlemaps#2089]
**I'm submitting a ...**  (check one with "x")
- [X] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

Hello I'm trying to utilise the Marker Clustering feature as documented here: https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/MarkerCluster/addMarkerCluster/README.md

The cluster works fine if I provide the array of markers on it's initialisation. However, if I attempt to use the "addMarker()" method, it will not update the cluster with the new marker. This is what I have now:

```
  private initMarkerCluster(): void {
    this.map.addMarkerCluster({
      //maxZoomLevel: 5,
      boundsDraw: true,
      markers: [this.dummyData[0]],
      icons: [
          { min: 2, max: 20, url: "./assets/img/blue-cluster.png", anchor: { x: 16, y: 16 } },
          { min: 20, max: 50, url: "./assets/img/yellow-cluster.png", anchor: { x: 16, y: 16 } },
          { min: 50, max: 100, url: "./assets/img/red-cluster.png", anchor: { x: 24, y: 24 } },
          { min: 100, url: "./assets/img/purple-cluster.png", anchor: { x: 32, y: 32 } }
      ]
    }, function (markerCluster) {
      markerCluster.addMarker(this.dummyData[1]);
    });
  }
```

The first marker will be added fine, but the second one won't exist. Any assistance with this would be greatly appreciated!

**Comment by wf9a5m75** [comment]
If you use ionic-native/google-map, `addMarkerCluster().then()`

**Comment by HarveyD** [comment]
Not using ionic-native/google-map. Using the Cordova plugin itself.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
@HarveyD any update?

**Comment by wf9a5m75** [comment]
Since there is no enough information was provided, I close this thread.
