### ISSUE TITLE
Last translations breaks build

### ISSUE THREAD

**Issue by sam2x** [mapsplugin/cordova-plugin-googlemaps#2091]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

```
$ cordova run
/project/trunk/platforms/android/build/intermediates/res/merged/debug/values-uk/values-uk.xml:46: 
AAPT: Apostrophe not preceded by \ (in Ви спробували підключитися до сервісу з недійсним ім'ям облікового запису.)
```
The file values-uk.xml (line 46), translation contains an Apostrophe that needs to be escaped.

**Comment by wf9a5m75** [comment]
Please send a pull request to fix the problem. I just uploaded the translated files.

**Comment by wf9a5m75** [comment]
Well, I tested but I can not reproduce this.
