### ISSUE TITLE
MarkerCluster.remove() not working as intended

### ISSUE THREAD

**Issue by chris-doco** [mapsplugin/cordova-plugin-googlemaps#2093]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
Hi, on Android when I execute the MarkerCluster.remove() function it spits out this error: 
```
plugins/cordova-plugin-googlemaps/www/BaseClass.js:127 Cannot access to the 'remove' method.
```
If there are markers or marker clusters in your map camera view, then it won't remove them. The old clusters and markers are still visible but not clickable anymore.

If you look away to place with no markers and marker clusters it removes them properly.
And on iOS, it sometimes crashes when I call that function. Maybe from the above error.

**Expected behavior:**
It should remove all the markers and clusters associated with that MarkerCluster object.

**Screen capture or video record:**
![markerclusterremove](https://user-images.githubusercontent.com/36622268/36414054-337d7732-1664-11e8-89eb-d11ed0006e4c.gif)

This was also tested on your marker cluster demo project (as seen in the above gif).

Thanks!

**Comment by wf9a5m75** [comment]
Please share the reproduce project

**Comment by chris-doco** [comment]
We used the marker cluster demo.
https://github.com/mapsplugin/marker_cluster_demo

And used the 2.2.5 version of the google maps plugin for the above video.

Thanks!

**Comment by wf9a5m75** [comment]
The `markerCluster.remove()` itself works fine for me.

![2093](https://user-images.githubusercontent.com/167831/36501359-c3d8a67a-16fb-11e8-850e-63f75fd0d050.gif)

**Comment by wf9a5m75** [comment]
The HTMLInfoWindow is appeared far position from marker is a bug.

**Comment by chris-doco** [comment]
Hmm... Hang on, I'll upload a project with this bug.

**Comment by chris-doco** [comment]
Here is the project.
https://github.com/tararat-doco/marker_cluster

**Comment by redundans** [comment]
I have the same problem on Android but not in iOS with the 2.2.5 when using MarkerCluster.remove() and Map.clear();

`Cannot access to the 'remove' method.`

**Comment by wf9a5m75** [comment]
It seems the java version problem in your computer.
https://stackoverflow.com/a/32955708/697856

```
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err: java.lang.reflect.InvocationTargetException
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err:     at plugin.google.maps.MyPlugin$2.run(MyPlugin.java:117)
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err:     at java.lang.Thread.run(Thread.java:764)
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err: Caused by: java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-oj.jar)
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err:     at plugin.google.maps.PluginMarkerCluster.remove(PluginMarkerCluster.java:158)
02-26 15:27:41.368 5082-5464/plugin.google.maps W/System.err: 	... 7 more
```

**Comment by wf9a5m75** [comment]
Ok, I updated the code. Please reinstall the plugin from the multiple_maps branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="..."
```

**Comment by redundans** [comment]
I can confirm that the change from ConcurrentHashMap to Map works in my project when clearing a map that has MarkerCluster. Thanks!

**Comment by fssrepository** [comment]
Which release will contain this fix (or when it will be released), as i don't want to rely on source at the moment. Somehow i have an additional problem, my cluster icons haven't been picked up,but i'm using the same style of urls, than in other icons.
