### ISSUE TITLE
The map doesn't re-render correctly (sometimes) after a ionic side-menu is toggled.

### ISSUE THREAD

**Issue by tryadelion** [mapsplugin/cordova-plugin-googlemaps#2095]
The map doesn't re-render correctly (sometimes) after a ionic side-menu is toggled.

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-app-preferences 0.99.3 "AppPreferences"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-keyboard 1.1.5 "Keyboard"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.2-dev "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

"ionic-native/core": "4.5.2"

"ionic-native/google-maps": "^4.5.3"

"cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git",

"cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.6.0"

**Current behavior:**

when using this plugin inside ionic alongside one or more sidemenus ( lateral navigation), sometimes after toggling the menu back to the map screen the space that the menu used to fill stays white until some more "toggles".
happens both on emulators and physical devices, running on prod and dev.

**Expected behavior:**

map to be redrawn correctly.

**Screen capture or video record:**

https://youtu.be/4JcKZuUUrQw

**Comment by fablrdigital** [comment]
I am also having this issue when I'm leaving the screen and returning to it. The map takes a few moments to re-shape to fill the screen.

FYI, you can set the ion-menu to use "overlay" rather than shifting the map as described in https://ionicframework.com/docs/api/components/menu/Menu/. This should be a work-around for your specific issue, though it would be nice to know why the map is struggling to render again.

**Comment by tryadelion** [comment]
trying the overlay right now. sounds like a good patch-up for now.

**Comment by tryadelion** [comment]
worked. it might happen because of the z-index of the ios style menu vs the zindex of the map layer.

**Comment by fablrdigital** [comment]
I doesn't appear to be a z-index issue. It appears to be when the map is shifted out of frame and then pulled back in. It doesn't update the height and width quickly enough.

Now you CAN run ```cordova.fireDocumentEvent('plugin_touch', {});``` which fixes it, but it's useless if you've got a transition animation.

**Comment by wf9a5m75** [comment]
This is not a bug. Because ionic iOS version uses `translate` css, but the browser does not fire for the event. If you need repositioning the map view, use `cordova.fireDocumentEvent('plugin_touch', {});`

**Comment by fablrdigital** [comment]
I literally just said this and pointed out why it was still an issue. The only way to resolve this is to actually disable transitions entirely?

**Comment by cnmoro** [comment]
This bug still occurs for me to this day, and I can`t solve it.
The issue should not be closed

**Comment by cnmoro** [comment]
Thanks for posting some info.
Do you happen to have some tutorial or guide on how to implement the open
street maps / mapbox api on ionic ?

C. Moro

**Comment by fablrdigital** [comment]
I ended up cheating and just going down the JS route because I couldn't get the Cordova Plugin to do _everything_ I wanted. You can find the plugin at https://github.com/Telerik-Verified-Plugins/Mapbox though and they do have documentation on there.
