### ISSUE TITLE
Click on marker when using markerCluster is firing 'cluster_click', not 'marker_click'

### ISSUE THREAD

**Issue by BigFoppa** [mapsplugin/cordova-plugin-googlemaps#2099]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-facebook-audnet-sdk 4.26.2 "Facebook AudienceNetwork SDK for Cordova"
cordova-plugin-admob-facebook 4.23.0 "AdMob Mediation Adapter for Facebook Audience Network"
cordova-plugin-admobpro 2.29.29 "AdMob Plugin Pro"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-extension 1.5.3 "Cordova Plugin Extension"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-facebookads 4.23.2 "FacebookAds"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-globalization 1.0.8 "Globalization"
cordova-plugin-googlemaps 2.2.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
Click on marker when using markerCluster is not working because it is firing 'cluster_click', not 'marker_click'. See my changes below to `Map.prototype._onClusterEvent` in Map.js that makes it work.

On a sidenote: markers are not recognized if id without prefix "marker_" is given in addMarkerCluster. Not a bug but should be documented.

Keep up the good work!
/Big

**Expected behavior:**
Click on marker when using markerCluster should fire 'marker_click', or 'cluster_click' should be recognized.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```javascript
Map.prototype._onClusterEvent = function(eventName, markerClusterId, clusterId, position) {
  var self = this;
  var markerCluster = self.OVERLAYS[markerClusterId] || null;
  if (markerCluster) {

    // markers not recognized if id without prefix 'marker_' is given in addMarkerCluster 
    var markerx = markerCluster.getMarkerById(clusterId);  

    if (markerx || /^marker_/i.test(clusterId)) {
      // regular marker
      var marker = markerCluster.getMarkerById(clusterId);

      // click on marker when using markerCluster is firing 'cluster_click', not 'marker_click'
      if (eventName === 'cluster_click') {
        console.log("!!!! CLUSTER_CLICK !!!!")
        eventName = event.MARKER_CLICK;
      }

      if (eventName === event.MARKER_CLICK) {
        markerCluster.trigger(eventName, position, marker);
      } else {
        if (eventName === event.INFO_OPEN) {
          marker.set("isInfoWindowVisible", true);
        }
        if (eventName === event.INFO_CLOSE) {
          marker.set("isInfoWindowVisible", false);
        }
      }
      marker.trigger(eventName, position, marker);
    } else {
      // cluster marker
      var cluster = markerCluster.getClusterByClusterId(clusterId);
      if (cluster) {
        markerCluster.trigger(eventName, cluster);
      } else {
        console.log("-----> This is remained cluster icon : " + clusterId);
      }
    }
  }
};
```

**Comment by wf9a5m75** [comment]
cluster_click is for internal use event. Not for developers.

**Comment by BigFoppa** [comment]
Hmm ??

I am in `map.addMarkerCluster using this to capture click on markers:

          markerCluster.on(plugin.google.maps.event.MARKER_CLICK, function (position, marker) {
            // my code
          });

But as I show in `Map.prototype._onClusterEvent 'cluster_click' is getting fired.

What is it I am missing here?

/Big

**Comment by wf9a5m75** [comment]
`Map.prototype._onClusterEvent` is internal code. Not for you.

**Comment by BigFoppa** [comment]
I know, but there is where the bug is. If I understand it correctly.

/Big

**Comment by wf9a5m75** [comment]
marker_click event is fired when you click on a regular marker.

**Comment by wf9a5m75** [comment]
This plugin don't allow to control something when you click on the cluster icon in developer side. This is not a bug.

**Comment by BigFoppa** [comment]
Well, that is my point, 'marker_click' is *not* fired when you click a regular marker, 'cluster_click' is getting fired. If I change your code as shown earlier, then it works.
Please try it.

/Big

**Comment by wf9a5m75** [comment]
If you have a problem, please share your project files on github. I will check it. Otherwise, please debug  by yourself.

**Comment by BigFoppa** [comment]
Sorry, don't have time to do that. Going away on a trip for 2 weeks in a couple of hours.

But, if I am correct in my debugging of your code then you could check if your cluster demo works for click on regular markers:
[https://github.com/mapsplugin/marker_cluster_demo](https://github.com/mapsplugin/marker_cluster_demo)

I am not using the HtmlInfoWindow as in the demo, but I am setting the *title* of the marker which gives a normal infowindow. But only if I change your code as shown.

/Big
