### ISSUE TITLE
Feature request: panBy()

### ISSUE THREAD

**Issue by hirbod** [mapsplugin/cordova-plugin-googlemaps#210]
Hi Masashi,

since we're now able to place content on top of the map it would be nice to recenter our markers sometimes. Instead of providing a difficult way of recalculating world's card it would be very nice to have the "panBy" function.

You can pass a X and Y value in pixels to pan the map. In my case I like to move the pan -100px by top.
In JS, this could be done with:

``` javascript
map.panBy(0,-100);
```

Here is an example:
http://jsfiddle.net/doktormolle/JsBEx/

Google:
https://developers.google.com/maps/documentation/javascript/reference

I'm don't know if this is supported by Google SDK for iOS and Android. I hope so!

Edit:
http://stackoverflow.com/questions/15625970/offseting-the-center-of-the-mapfragment-for-an-animation-moving-both-the-target

https://gist.github.com/codebutler/6925097

(but maybe old and outdated. I hope panBy is implemented in SDK)

**Comment by ma-pe** [comment]
Thanks a lot for the panBy-feature. 

Is there any possibility to move the camera to Coordinates with offset in one move?

My Challenge is to focus a Marker after click - but the marker shall not be in the middle of the screen, but near the bottom. Currently I am moving the Camera to the Marker and after that I am panning the map up. The result is right, but of course not the animation before. First it moves to center the marker, afterwards it pans animated up. Looks a little weird.

Thanks for replies :)
