### ISSUE TITLE
Marker navigation in iOS

### ISSUE THREAD

**Issue by g4b0** [mapsplugin/cordova-plugin-googlemaps#2100]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
$ cordova plugin list
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.2.3 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

Is it possible to enable navigation when tapping a marker in iOS like in Android? In documentation [1] 'mapToolbar' is marked as android only.

[1] https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/setOptions/README.md 

Thanks a lot

**Comment by wf9a5m75** [comment]
That tool bar comes from the Google Maps Android API v2. But the Google Maps SDK for iOS does not have it.

**Comment by g4b0** [comment]
Thans
