### ISSUE TITLE
Custom marker

### ISSUE THREAD

**Issue by rudda** [mapsplugin/cordova-plugin-googlemaps#2102]
it's possivel add custom marker ? like https://raw.githubusercontent.com/warent/markerwithlabel/master/examples/markerwithlabel-screen.png

**Comment by wf9a5m75** [comment]
Only static images or base64 encoded strings are available.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Marker/setIcon.html

**Comment by wf9a5m75** [comment]
```js
var canvas = document.createElement('canvas');
canvas.width = 120;
canvas.height = 40;
var context = canvas.getContext('2d');

// draw a marker you want to use.

// export as base64 strings
var base64Strings = canvas.toDataURL();

map.addMarker({
   ...
   icon: base64Strings
}, function(marker) {

});
```
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md#base64-encoded-icon

**Comment by wf9a5m75** [comment]
Do you understand?

**Comment by rudda** [comment]
Hmmm ..  okay.
My problem is .... How to add different labels content for each marker?  For example. One marker represents one car and one label is one identify of car always showed below the marker

**Comment by wf9a5m75** [comment]
As I answered above, the only possible way is `canvas`.
You need to draw marker image on canvas, and draw your label on it.
Then export it.
