### ISSUE TITLE
Display map in child element on Ionic 2 page

### ISSUE THREAD

**Issue by mxsxs2** [mapsplugin/cordova-plugin-googlemaps#2103]
**I'm submitting a ...**  (check one with "x")
- [ x ] question
- [ ] any problem or bug report
- [ x ] feature request

**Expected behavior:**
Is it possible to embed the map into a child element of ```<ion-content>``` in ionic 2?
What i mean is:
```
<ion-content padding>
  <ion-grid>
    <ion-row>
      <ion-col>
        Name:
      </ion-col>
      <ion-col col-8>
       Some name
      </ion-col>
    </ion-row>
    <ion-row>
      <ion-col style="height:50%">
             <div #map id="map" style="height:100%"></div>
      </ion-col>
    </ion-row>
  </ion-grid>
</ion-content>
```
If i have it simply in ```<ion-content>``` it works perfect but I cannot display any other data on the page.
What I am trying to achieve is to show details of the current polygon displayed on the map and show the actual map underneath this description.

**Comment by wf9a5m75** [comment]
Try this:
https://github.com/battika/ionic-gmaps-test

![2020](https://user-images.githubusercontent.com/167831/35356274-c85bf16e-0104-11e8-9667-cfe3053f3b60.gif)

**Comment by wf9a5m75** [comment]
ping
