### ISSUE TITLE
google maps apis cannot access in China

### ISSUE THREAD

**Issue by lemonwong** [mapsplugin/cordova-plugin-googlemaps#2105]
**I'm submitting a ...**  (check one with "x")
- [ x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
7.1.0

**Current behavior:**

i cannot load the google map in China,but i can load if i use a proxy server
**Expected behavior:**

I cannot access the googleapi.com address in China ,but I can access the maps.google.cn/maps/api/js in China,which i think is a mirror in China,can i modify the api url myself and how?

**Comment by wf9a5m75** [comment]
Unfortunately, China blocks the internet access to all Google Services (such as Gmail).
I'm not sure the Google Maps SDK for iOS is available or not in China (I guess not available), thus you can not use this plugin in China.

> Why can't I access Google Maps APIs from China?
https://developers.google.com/maps/faq#china_ws_access

Regarding of the Google FAQ, only available option is 
```
<script src="http://maps.google.cn/maps/api/js?key=YOUR_API_KEY"
type="text/javascript">
</script>
```

**Comment by lemonwong** [comment]
such a pity thanks anyway.
