### ISSUE TITLE
geojson data?

### ISSUE THREAD

**Issue by rcowling** [mapsplugin/cordova-plugin-googlemaps#2106]
is it possible to load and use external geojson data with this plugin?

**Comment by wf9a5m75** [comment]
not supported.

**Comment by rcowling** [comment]
there is no way to use it?

**Comment by wf9a5m75** [comment]
no

**Comment by rcowling** [comment]
thank you

**Comment by wf9a5m75** [comment]
You need to parse the geojson, then add the overlays by yourself.
