### ISSUE TITLE
Not Understanding Map Events  And Docs Didn't Clarify

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/cordova-plugin-googlemaps#2112]
**I'm submitting a ...**  (check one with "x")
- [x ] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
Kimberlees-MacBook-Pro:dvLinemanAppSDK kimberleearmstrong$ cordova plugin ls
com.collectme.zbarScanner 0.0.1 "ZBarScanner"
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.10.1 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.2.2 "ActionSheet"
cordova-plugin-background-fetch 5.2.1 "CDVBackgroundFetch"
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-googlemaps 2.2.6-beta-20180226-1541 "cordova-plugin-googlemaps"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-urlhandler 0.7.0 "URLHandler"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-spatialite-storage 1.1.0 "Cordova sqlite/spatialite storage plugin"
phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"
phonegap-plugin-contentsync 1.3.5 "content-sync"
phonegap-plugin-push 1.8.1 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

The MAP_CLICK is firing instead of CAMERA_MOVE_END and marker clicks are firing a MAP_CLICK event also.
**Expected behavior:**

I would expect pan and zoom to fire CAMERA_MOVE_END and no MAP_CLICK.  I would expect MARKER_CLICK to not fire MAP_CLICK
**Screen capture or video record:**

http://www.youtube.com/watch?v=cq_vB79x_ZQ

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Could you make a video with `mouse cursor`?

**Comment by wf9a5m75** [comment]
This plugin just passes native events to JS side.

**Comment by KimberleeDArmstrong** [comment]
What tools do you use?

**Comment by wf9a5m75** [comment]
Try `QuickTime Player`. You can take screen record with mouse cursor.

**Comment by KimberleeDArmstrong** [comment]
https://youtu.be/WsbGm9y6iWo  I can't do a zoom on the simulator but it has the same behavior for pan and zoom on the iPad

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, please share your project files.

**Comment by KimberleeDArmstrong** [comment]
ok.  I did notice if I remove the breakpoint from the click function the camera end does fire.  Its weird.
https://youtu.be/fB-SUppGjwE

**Comment by wf9a5m75** [comment]
I think it's bug of Google Maps SDK for iOS itself.
As I replied above, this plugin just passes the events to JS side.

**Comment by KimberleeDArmstrong** [comment]
I shared it with you.

**Comment by wf9a5m75** [comment]
Ah, you use `v2.2.2`, it's too old.
https://bitbucket.org/KimberleeArmstrong/lineman-app/src/3389bfb0c3049598fa6a60ed139ef781dfc95a85/node_modules/cordova-plugin-googlemaps/plugin.xml?at=master&fileviewer=file-view-default

```xml
<?xml version='1.0' encoding='utf-8'?>
<plugin id="cordova-plugin-googlemaps" version="2.2.2" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android">
    <name>cordova-plugin-googlemaps</name>
```

**Comment by KimberleeDArmstrong** [comment]
Weird.  I just downloaded it 2 days ago using just the #multiplemaps and thats all.  I will try to download it again and see.

**Comment by KimberleeDArmstrong** [comment]
I uploaded my latest project.  using the latest version of the plugin (2.2.6-beta-20180303-0948) getting this....

2018-03-02 10:32:38.009800-0600 LinemanApp[4771:3379757] creating google map with zoom:12 and center of 26.24 / -97.8231195190038 Google={"lat":26.24,"lng":-97.8231195190038}
2018-03-02 10:32:38.013827-0600 LinemanApp[4771:3379757] Motion Change: false
2018-03-02 10:32:38.013949-0600 LinemanApp[4771:3379757] got coords: 33.16990064578233/-96.64607753481961 : 65m. at Fri Mar 02 2018 10:32:38 GMT-0600 (CST)
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/0B7AC6A2-F431-44F1-AC34-3BD2CCA88505/LinemanApp.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/0B7AC6A2-F431-44F1-AC34-3BD2CCA88505/LinemanApp.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/0B7AC6A2-F431-44F1-AC34-3BD2CCA88505/LinemanApp.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
2018-03-02 10:32:38.850462-0600 LinemanApp[4771:3379757] GLRenderTarget::CreateFramebuffer() failed.
2018-03-02 10:32:39.560722-0600 LinemanApp[4771:3379757] panning google map with zoom:12 and center of 26.24 / -97.8231195190038 Google={"lat":26.24,"lng":-97.8231195190038}
2018-03-02 10:32:39.561049-0600 LinemanApp[4771:3379757] refreshGoogleMap()
2018-03-02 10:32:39.561671-0600 LinemanApp[4771:3379757] camera idle event fired
2018-03-02 10:32:41.736643-0600 LinemanApp[4771:3379757] camera idle event fired
2018-03-02 10:33:23.660692-0600 LinemanApp[4771:3379757] -[__NSCFNumber objectForKey:]: unrecognized selector sent to instance 0xb000000000000003
2018-03-02 10:33:23.665428-0600 LinemanApp[4771:3379757] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber objectForKey:]: unrecognized selector sent to instance 0xb000000000000003'
*** First throw call stack:
(0x18319a364 0x1823e0528 0x1831a7828 0x18319fd10 0x183084ecc 0x1011ea8b8 0x1011e9b18 0x18c956878 0x18c6b5144 0x18307390c 0x18c6b4c80 0x18c956878 0x18c6b5144 0x18307390c 0x18c6b4c80 0x18c956878 0x18c93b6e4 0x18c93b438 0x18c68044c 0x18c93b330 0x18c93b85c 0x18cfcd97c 0x18cfcd61c 0x18cd293c8 0x18cfccc88 0x18cfd0d04 0x18cfd38a8 0x18cfcc7c0 0x18314297c 0x1831428fc 0x183142184 0x18313fd5c 0x18305fe58 0x184f0cf84 0x18c6df67c 0x1010dad2c 0x182b7c56c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by wf9a5m75** [comment]
Did you update the repo?

**Comment by wf9a5m75** [comment]
The bigbucket.org is currently unavailable....
https://status.bitbucket.org/incidents/hbpb9tlzvq4r

So I will check this later.

**Comment by wf9a5m75** [comment]
Okay, the bitbucket.org is now available. I checked your app, but the original issue is not reproduced.

**Comment by wf9a5m75** [comment]
And the last one `'-[__NSCFNumber objectForKey:]: unrecognized selector`, I think this is not this plugin's error, because I don't use `__NSCFNumber objectForKey` in the maps plugin.

Please provide the video how to reproduce the issue.

**Comment by KimberleeDArmstrong** [comment]
The app was crashing on map launch during the animate to center.  I did a fresh install of all plugins and it seems to be working great now.  Sorry for wasting your time.  Thanks

**Comment by wf9a5m75** [comment]
ok
