### ISSUE TITLE
Is it possible to set maps default locale?

### ISSUE THREAD

**Issue by khoshrou** [mapsplugin/cordova-plugin-googlemaps#2113]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"
cordova-plugin-nativegeocoder 3.1.0 "NativeGeocoder"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-vibration 3.0.1 "Vibration"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

    "@ionic-native/core": "^4.3.1",
    "@ionic-native/google-maps": "^4.5.3",

**Current behavior:**

right now map uses devices default language, if I change devices language, maps texts like name of streets are translated to new language , even geocoder outputs are translated

**Expected behavior:**

lets with an option set the maps locale like 'fa-IR' or 'en-US' it should set the maps locale without considering devices locale.

'Native Geocoder' plugin recently added this option and it works nice, hope you can add this. (works with ios 11+)
https://github.com/sebastianbaar/cordova-plugin-nativegeocoder

**Comment by wf9a5m75** [comment]
No option.
