### ISSUE TITLE
Map does not load after reopening app

### ISSUE THREAD

**Issue by devdaddy** [mapsplugin/cordova-plugin-googlemaps#2114]
Hello, I have an app that is ready to go to the appropriate stores. I built the app with 
```bash
ionic cordova build --release --prod
```
Signed it with my release key via jarsigner.  Ran zipalign.  Install the app via adb to make sure all is well.

Then I run the app for the first time, the map shows and works fine.  If I close the app via task manager (swipe left) and then reopen the app, it does not show the map.  It just shows a white page.  I have set all of the parent pages to have a transparent background

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com-sarriaroman-photoviewer 1.1.15 "PhotoViewer"
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic 4.0.0 "IonicCordova"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.3.1 "OneSignal Push Notifications"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^4.5.3",
"@ionic-native/google-maps": "^4.5.3",
"cordova-plugin-googlemaps": "^2.1.1",
"cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.6.0"
```

**Current behavior:**
I run the app for the first time, the map shows and works fine.  If I close the app via task manager (swipe left) and then reopen the app, it does not show the map.  It just shows a white page.  

**Expected behavior:**
show the map

**Screen capture or video record:**
unable to provide

**Related code, data or error log (please format your code or data):**
no errors
```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
If you can't resolve the issue by yourself, please share your project files on github. I will help you.
If you decline to provide your project files, please create a demo project that reproduce your issue 100%.
Even if you don't want to do it, please simply close the thread, and please debug the issue by yourself.

**Comment by devdaddy** [comment]
I don't have time to reproduce the work I have been working on for several weeks now and I am unable to share my project files due to proprietary data.  So you are telling me that you are unwilling to help?  I understand that you need more information, but I don't have the time to reproduce the entire project.

**Comment by wf9a5m75** [comment]
In that case, I can't help you unfortunately.
