### ISSUE TITLE
When I add more than 100 markers the map closes

### ISSUE THREAD

**Issue by renzvnci** [mapsplugin/cordova-plugin-googlemaps#2115]
Hello
I have an array with 449 markers and I'm going through it one by one and adding but in a moment the map closes.

If I reduce the amount, I have no problem.

I really do not know what can be

**Comment by wf9a5m75** [comment]
Out of memory.

**Comment by renzvnci** [comment]
Any suggestions to add so many markers to the map
?

**Comment by wf9a5m75** [comment]
Reduce your number of markers, or use marker cluster.

**Comment by thezakman** [comment]
how many unclustered markers does the plugin accepts before run out of memory and crash?

**Comment by wf9a5m75** [comment]
Depends on device.

**Comment by thezakman** [comment]
Thank you.
