### ISSUE TITLE
Disable Background Color

### ISSUE THREAD

**Issue by JakeCube** [mapsplugin/cordova-plugin-googlemaps#2123]
When the map was successful loaded, somehow the maps is forced to change back ground color.
I'm using Framework 7 as part of my interface design, and the theme is black color.

Is there any way to preset this background to transparent / Disable the background color? 

Before load:
 
![screenshot_2018-03-07-22-27-20 1](https://user-images.githubusercontent.com/20925630/37098512-f9534c34-2258-11e8-9ca2-8f094b0a397b.png)

After Map load:
![screenshot_2018-03-07-22-41-18 1](https://user-images.githubusercontent.com/20925630/37098530-070a580e-2259-11e8-8d4e-13b9d39fbba4.png)

**Comment by wf9a5m75** [comment]
![](https://raw.githubusercontent.com/mapsplugin/cordova-plugin-googlemaps-doc/master/v1.4.0/class/Map/mechanism.png)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Environment/setBackgroundColor/README.md
