### ISSUE TITLE
exception with Markerclusterer on IOS

### ISSUE THREAD

**Issue by tryadelion** [mapsplugin/cordova-plugin-googlemaps#2126]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [X ] **iOS**

Some users started reporting that since an ios update, sometimes the map hanged up. we requested a nearby user to come by to debug onto his phone, and found out this exception breaking the plugin's code:

![captura de pantalla 2018-03-08 a las 15 56 47](https://user-images.githubusercontent.com/3778474/37157752-e4e69d0a-22e9-11e8-94b1-0e815ec6227f.png)

happens randomly when loading the map, quite inconsistent error.
a quick fix could be a null check on the from and to.

**Comment by wf9a5m75** [comment]
>a quick fix could be a null check on the from and to.

Do not give null parameters.

**Comment by tryadelion** [comment]
the problem is i'm not the one calling that method,  i don't know where from comes in  computeanglebetween, or what to check.

**Comment by wf9a5m75** [comment]
Okay, please share your project files that reproduce your issue. Without sharing anything, what can I do?

I tested bunch of projects. The most case of unexpected errors come from invalid data. Check your data at once. Some people give string lat/lng instead float for example.

**Comment by wf9a5m75** [comment]
This plugin code is full open. At least you can trace the code flow.

---

#Trace the code flow step by step

Regarding of the error capture (thank you for providing), the error occurs at `line 200 in MarkerCluster.js`.
However JS trace log always display +1 step, so `line 199`.

![screen shot 2018-03-08 at 9 22 00 am](https://user-images.githubusercontent.com/167831/37166211-544f19d8-22b3-11e8-9f26-65e2dff7b135.png)

Okay, it seems the markerCluster executes `self.redraw` in **the constructor of MarkerCluster**.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b3fa8e7fcea26cca66116673669712e71037b802/www/MarkerCluster.js#L199-L201

It means the error occurred when markerCluster tried to draw the clusters for first time.

---

Then let's move to `the line 459 in MarkerCluster.js`.

![screen shot 2018-03-08 at 9 22 00 am](https://user-images.githubusercontent.com/167831/37166245-6f3212a0-22b3-11e8-8fe7-174282fb4366.png)

It seems the marker cluster needs to know the visible region of map.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b3fa8e7fcea26cca66116673669712e71037b802/www/MarkerCluster.js#L458-L462

-----

After that,  let's move to `the line 501 in MarkerCluster.js`.
![screen shot 2018-03-08 at 9 22 00 am](https://user-images.githubusercontent.com/167831/37166404-cb005ac4-22b3-11e8-9333-70d4cbcb4b2a.png)

Oh, the marker cluster calculates distance from A to B.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b3fa8e7fcea26cca66116673669712e71037b802/www/MarkerCluster.js#L501

----

Okay, next. Lets' move to `line 73 in spherical.js`

![screen shot 2018-03-08 at 9 22 00 am](https://user-images.githubusercontent.com/167831/37166550-35b623a8-22b4-11e8-85df-59a2d3c3849d.png)

Wow, the computeDistanceBetween is very thin wrapper.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b3fa8e7fcea26cca66116673669712e71037b802/www/spherical.js#L72-L74

----

In the end, let's move to `line 65 spherical.js`.
![screen shot 2018-03-08 at 9 22 00 am](https://user-images.githubusercontent.com/167831/37166675-83aa5fe8-22b4-11e8-90e7-f0c0a1f8f9eb.png)

Um, it seems the plugin calculates something.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b3fa8e7fcea26cca66116673669712e71037b802/www/spherical.js#L64-L67

----

The error says `undefined is not an object (evaluating 'from.lat')`. Ah I see, the variable `from` is undefined for some reason.

You can understand at least here.

-------


#Why the variable `from` is undefined?

Okay, where does the variable `from` come from?

The variable `from` comes from `params.visibleRegion.farRight`.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b3fa8e7fcea26cca66116673669712e71037b802/www/MarkerCluster.js#L501

Um, it seems `params.visibleRegion.farRight` is undefined.

Let's confirm the code of `map.getVisibleRegion()`.

-------

#map.getVisibleRegion()

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b3fa8e7fcea26cca66116673669712e71037b802/www/Map.js#L792-L813

Oh, it looks very simple code.

This function just returns camera positions.

----

If you come up here, you might guess the reason of the error.

**You tried to use a marker cluster before the `camera positions` are not filled yet.**
It means you tried to use a marker cluster **before the MAP_READY event**.

**Comment by wf9a5m75** [comment]
ping

**Comment by tryadelion** [comment]
sorry, you pinged me at 3AM here.  the marker cluster is never used before the map_ready event as per code:

```
this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => { all_the_code_that_loads_markers_and_adds_them_to_clusters }

```

my code order:
1- map ready
2 - add click listener
3 - create cluster.
![captura de pantalla 2018-03-12 a las 9 04 45](https://user-images.githubusercontent.com/3778474/37271743-7f05a93e-25d4-11e8-84f6-98e5444bb9a6.png)
4- (then), add click to cluster
![captura de pantalla 2018-03-12 a las 9 05 01](https://user-images.githubusercontent.com/3778474/37271742-7ee6186c-25d4-11e8-91f2-1cb9429af4fd.png)
5 - load markers from API/DB
6 - add markers to cluster

it's a very linear process.

**Comment by wf9a5m75** [comment]
Only accept the provided project.

**Comment by tryadelion** [comment]
i added a try catch around the markercluster constructor and it "fixed" this edge cases where map is ready but camera is not filled, as after some time i noticed  the "map ready!" console.log always prints, wether the map crashes or not, but you should check why a camera could not be set and the map could be ready.

**Comment by wf9a5m75** [comment]
If you find out the reason, please feed back ;)

**Comment by tryadelion** [comment]
@wf9a5m75  i've noticed the crash happens after map_ready is sent but before the camera variables are set. shouldn't they be set before the map ready? maybe an  observable/promise  or an async await that makes sure both are set and never returns map_Ready unless it's really ready?

**Comment by wf9a5m75** [comment]
Try the multiple_maps branch. Should be fine.

**Comment by tryadelion** [comment]
will try this afternoon,  thanks!
