### ISSUE TITLE
Typo in Docu map.addMarker - Adding multiple markers

### ISSUE THREAD

**Issue by GitToTheHub** [mapsplugin/cordova-plugin-googlemaps#2127]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Marker/addMarker/README.md

Typo in Sample-Code for "Adding multiple markers".

```
 baseArrayClass.map(function(options, cb) {
    // The variable "options" contains each element of the data.
    //
    // The variable "cb" is a callback function of interation.
    map.addMarker(option, cb);

  }, function(markers) {
```

It should be `options`, not `option` 

`map.addMarker(options, cb);`

**Comment by wf9a5m75** [comment]
Thank you.
When you find a typo, please send a pull request next time.

**Comment by GitToTheHub** [comment]
Ok, i have never done this before (make a pull request). I will try it next time.
