### ISSUE TITLE
The `INFO_CLOSE` event is triggered twice

### ISSUE THREAD

**Issue by GitToTheHub** [mapsplugin/cordova-plugin-googlemaps#2129]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
Using Phonegap Build. Hier the Output for the maps Plugin:

> Fetching plugin "cordova-plugin-googlemaps@2.2.5" via npm
> Installing "cordova-plugin-googlemaps" at "2.2.5" for android

**Current behavior:**
- INFO_CLOSE fired twice, if i click on map and a info window was opened before
- INFO_CLOSE fired for all added markers, if i remove the map. It doesn't matter, if a info window was opened or not

**Expected behavior:**
- INFO_CLOSE should only fired one time, if i click on the map, and a info window was opened
- INFO_CLOSE should not be fired for all markers, if i remove the map

**Related code, data or error log (please format your code or data):**
[maps-marker-event-test-index-html.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1793846/maps-marker-event-test-index-html.zip)

**Comment by GitToTheHub** [comment]
Tested with multiple_maps too. The issues did here still occure too.

Phonegap Build output:
>  Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps.git" via git clone
Using shallow clone
> Repository "https://github.com/mapsplugin/cordova-plugin-googlemaps.git" checked out to git ref "multiple_maps" at "6c8fa63".
> Installing "cordova-plugin-googlemaps" at "2.2.6" for android

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub, not zip file

**Comment by GitToTheHub** [comment]
Really hard for you to open a zip file, uh?

Here the git repo: https://github.com/GitToTheHub/cordova-maps-marker-test

**Comment by wf9a5m75** [comment]
Fixed. Please reinstall the plugin from the multiple_maps branch.
![2129](https://user-images.githubusercontent.com/167831/37186400-2b1f16f2-22fa-11e8-9cd3-af4da612b6fa.gif)

**Comment by GitToTheHub** [comment]
Thanks for fixing this. INFO_CLOSE is now only fired one time, if i click on the map. But if i click on "Close Map" in the top left corner, than INFO_CLOSE will be fired for every marker. This seems wrong too.

**Comment by wf9a5m75** [comment]
No, it's correct. When you remove a map, the plugin removes all overlays, marker, infoWindow, everything.
In order to remove completely, the plugin triggers `INFO_WINDOW` close when a marker is removed.

**Comment by GitToTheHub** [comment]
I don't understand, why `INFO_CLOSE` is fired, when a marker is removed an no Info-Window was opened. I thought `INFO_CLOSE` will only be fired, when a Info-Window was opened and then closed, as the event name `INFO_CLOSE` implies.

**Comment by GitToTheHub** [comment]
If you have 6 Markers on the map, no info window is shown and you remove the map, then `INFO_CLOSE` will be fired 6 times. That should be correct behaviour?

**Comment by wf9a5m75** [comment]
Because HtmlInfoWindow needs it.

**Comment by wf9a5m75** [comment]
>If you have 6 Markers on the map, no info window is shown and you remove the map, then INFO_CLOSE will be fired 6 times. That should be correct behaviour?

Yes, correct for this plugin.

**Comment by wf9a5m75** [comment]
So, remove the event lister before removing the map if annoying

**Comment by wf9a5m75** [comment]
All documents are here.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

You should read all pages before asking.

**Comment by GitToTheHub** [comment]
Read all pages is a little bit to much, to only know, how i can remove the event listener. But you helped me with
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseClass/README.md
Marker & BaseClass has confused me.
Thanks for your big support!

**Comment by wf9a5m75** [comment]
Marker class extends BaseClass.

**Comment by GitToTheHub** [comment]
Ok thank you, now i know that :)
