### ISSUE TITLE
Marker - On-Method not documented

### ISSUE THREAD

**Issue by GitToTheHub** [mapsplugin/cordova-plugin-googlemaps#2130]
Documentation for Marker:
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Marker/README.md

I couldn't find a docu for the on-method respectively the on-method is not listed in the method-list.

The trigger-method isn't documented too.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseClass/README.md

**Comment by GitToTheHub** [comment]
Ah ok, sorry, didn't know the methods belong to BaseClass, I was confused a little bit. Does the Marker class inherit from BaseClass?

So map.addMarker:
```
  map.addMarker(options, function(marker) {
   });
```
returns in the callback a BaseClass-Object?

Sorry again, for my confusion.

**Comment by wf9a5m75** [comment]
Marker and other overlay classes extend BaseClass.

**Comment by GitToTheHub** [comment]
Ok, and the Map Class extends BaseClass too?
But this should be documentend. On the docu page for Marker i couldn't find any relation to BaseClass.

**Comment by wf9a5m75** [comment]
I didn't ask you to use this maps plugin. If you don't like this plugin, you just use other plugin.

**Comment by GitToTheHub** [comment]
Sorry, your plugin is great. I like it really much. But i only want to make software better, so i wrote you, what confused me. You can ignore, what i wrote. I only wanted to help.
Keep up the good work, maybe i will help you with a little money later ;)
Thanks for developing this plugin, you make a great support :)

**Comment by wf9a5m75** [comment]
https://docs.google.com/presentation/d/1zlkmoSY4AzDJc_P4IqWLnzct41IqHyzGkLeyhlAxMDE/edit#slide=id.g291e604610_1_46

**Comment by GitToTheHub** [comment]
Wow, what a big documentation. Thank you :) There is documented what i missed :D
Sorry for reporting this "issue", i didn't wanted to bother you :)
