### ISSUE TITLE
Hi i having an issue with ionic native that the page with the map will show for 2 seconds and then its the page close itself. Thanks and sorry for any inconvenience caused

### ISSUE THREAD

**Issue by FarhanJohari** [mapsplugin/cordova-plugin-googlemaps#2132]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com-sarriaroman-photoviewer 1.1.16 "PhotoViewer"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativegeocoder 3.1.1 "NativeGeocoder"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
If you can't solve your problem by yourself, please share your project files on github.

**Comment by wf9a5m75** [comment]
ping

**Comment by FarhanJohari** [comment]
okay2.. 1 moment im pushing my code

**Comment by FarhanJohari** [comment]
hi @wf9a5m75  i did invite you in my repo. the maps is on pages/map. Sorry for the troubled

**Comment by wf9a5m75** [comment]
I can't move ahead.

![capture](https://user-images.githubusercontent.com/167831/37302521-01c30f06-25e9-11e8-91bd-8162b69143b9.png)

**Comment by wf9a5m75** [comment]
ping

**Comment by FarhanJohari** [comment]
Just login no username or password required

**Comment by wf9a5m75** [comment]
Okay, then how can I reach to the map page?

**Comment by wf9a5m75** [comment]
Well, since you don't reply, I change the code like this.

```
export class LoginPage {

    constructor(public navCtrl: NavController, public navParams: NavParams) {
    }

    ionViewDidLoad() {
        console.log('ionViewDidLoad LoginPage');
    }

    actionLogin(){
        this.navCtrl.setRoot('MapPage', {}, {animate: true, direction: 'forward'})  <-- here
    }

}
```

And run it.
![2132](https://user-images.githubusercontent.com/167831/37317215-ccf3a30c-2620-11e8-94bc-8891d5babca6.gif)

**Comment by FarhanJohari** [comment]
actually i did like you and it works.. but when open a modal to go to next page with map then map appear 2 seconds and the apps freeze.. 
 

![giphy](https://user-images.githubusercontent.com/11806226/37319033-5b5b0cac-26a8-11e8-9285-be8c527874b8.gif)

**Comment by FarhanJohari** [comment]
hi @wf9a5m75 i solved it by close the modal first then redirect to the page with map.. thanks a lot for your help earlier

**Comment by wf9a5m75** [comment]
Sounds good
