### ISSUE TITLE
White map after scrolling in pushed view

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#2135]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

I made a small git repository here: https://github.com/vosecek/whitemap

**cordova information:**
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-googlemaps 2.2.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Current behavior:**
Open sidemenu and push "Other page", close sidemenu - map is white in Android, map is OK in iOS.
Slide down or up in Other page in the list and pop go back to main page, map is white in both.
The problem occurs in iOS only after sliding up or down. In Android white map problem occurs in almost every case.

**Expected behavior:**
Map should not turned into white

**Screen capture or video record:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3978659/37335755-a528f2fc-26af-11e8-80a6-60ccb715bf26.gif)

**Comment by fbzz** [comment]
Are you using the same map id on the newpage ?  try with a different id.

**Comment by vosecek** [comment]
There is only one page with map, the main (home) page.

**Comment by fbzz** [comment]
Can i see your code to create ? Here is working after a push, but i'm using:
    "cordova-plugin-googlemaps": "2.2.5"

**Comment by vosecek** [comment]
Check the repository linked in top.

**Comment by wf9a5m75** [comment]
@vosecek Your code is not good way. Check out the document first.
Presentation at @ionic Los Angeles meetup

**Comment by wf9a5m75** [comment]
https://docs.google.com/presentation/d/1zlkmoSY4AzDJc_P4IqWLnzct41IqHyzGkLeyhlAxMDE/edit#slide=id.p

**Comment by wf9a5m75** [comment]
When you move to other page, due to the map div is invisible, the plugin removes the map automatically. You need to detach the map from webview if you want to keep the map.

This is good example.

https://github.com/battika/ionic-gmaps-test

**Comment by vosecek** [comment]
My fault, map.setDiv(null) on ionViewWillLeave() fixed the problem.
