### ISSUE TITLE
3 layers approach separation - suggestion

### ISSUE THREAD

**Issue by fssrepository** [mapsplugin/cordova-plugin-googlemaps#2137]
There are three layers, two of them are native frames and one is webview.
To handle touch events you need to combine them, but as it's a common approach for every cordova plugin which needs to use native frame, it can be a common base project, separated from the map solution.

**Comment by wf9a5m75** [comment]
What are you talking about?

**Comment by wf9a5m75** [comment]
This plugin does not use camera.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by fssrepository** [comment]
i have updated the task.

**Comment by wf9a5m75** [comment]
What do you mean `i have updated the task.`? Please explain your comment.
