### ISSUE TITLE
Exception on open HtmlInfoWindow when triggering

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/cordova-plugin-googlemaps#2139]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [X ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

insert the output from the command here

C02VX1GWG8WN:dvLinemanAppSDKBtBkt ka87029$ cordova plugin ls
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.9.1 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-camera 4.0.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-googlemaps 2.2.6 "cordova-plugin-googlemaps"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-spatialite-storage 1.2.0 "Cordova sqlite/spatialite storage plugin"
phonegap-plugin-barcodescanner 7.0.0 "BarcodeScanner"
phonegap-plugin-contentsync 1.3.1 "content-sync"
phonegap-plugin-push 1.8.0 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.1.2 "Launch Navigator"
C02VX1GWG8WN:dvLinemanAppSDKBtBkt ka87029$ 
**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
triggering a marker click event sometime gets "unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'marker.getMap')" on line 202 of HtmlInfoWindow.js

**Expected behavior:**
event would trigger the event and open the HtmlInfoWindow.js
![screen shot 2018-03-13 at 11 19 55 am](https://user-images.githubusercontent.com/9216004/37354823-859dab2a-26b0-11e8-991c-520c663f4498.png)

I shared my project on Bit Bucket.  Not sure if its my code is wrong or a bug.  The InfoWindow is opened in common_map_funcs.js in the findEquipment() .  Trigger of the marker click event is in the same file showSearchResultDetails().

Video of error:
(uploading... send link when it uploads) 

**Screen capture or video record:**
https://youtu.be/Y9XFMXyMd00

**Related code, data or error log (please format your code or data):**
I shared my project on Bit Bucket.  Not sure if its my code is wrong or a bug.  The InfoWindow is opened in common_map_funcs.js in the findEquipment() .  Trigger of the marker click event is in the same file showSearchResultDetails().

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

https://bitbucket.org/KimberleeArmstrong/lineman-app

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by KimberleeDArmstrong** [comment]
Sorry thought I had.  I just pushed them.  It should be a standalone project with no downloaded files needed.  There are some missing but enough files to see the error now.

**Comment by wf9a5m75** [comment]
Thank you for uploading.

Umm. I can't login to the app.
![screen shot 2018-03-13 at 11 43 35 am](https://user-images.githubusercontent.com/167831/37362905-cbe5aca6-26b3-11e8-8be4-cea82104b366.png)

**Comment by KimberleeDArmstrong** [comment]
When it asks for the IMS Url at the very first please enter "https://www.datavoiceint.com:57573"

**Comment by wf9a5m75** [comment]
![2139_compress](https://user-images.githubusercontent.com/167831/37364604-372dbf18-26b8-11e8-85ac-7d305c8fd0a0.gif)

**Comment by wf9a5m75** [comment]
![2139_compress](https://user-images.githubusercontent.com/167831/37365215-17824eac-26ba-11e8-8550-d6427ca75dc6.gif)

**Comment by KimberleeDArmstrong** [comment]
Sorry.  I ran the project straight from the folder and it worked.  Let me see if I can reproduce it.

**Comment by KimberleeDArmstrong** [comment]
I added some code to hard code the ins url.  Can you delete the app and reinstall it from the latest bit bucket?

**Comment by wf9a5m75** [comment]
Ok, I confirmed the error though, I guess it's timing because your code controls the code flow based on timing in many places.

**before**
https://youtu.be/LuUtosNSqJY

Although I updated the code a little to prevent the error. Please reinstall the plugin from the multiple_maps branch. It seems the error is gone. However I get JS another error that is definitely in your side problem.


**after code updated**
https://youtu.be/LuUtosNSqJY

**Comment by KimberleeDArmstrong** [comment]
ok.  Thanks!

**Comment by KimberleeDArmstrong** [comment]
I confirm it the new plugin works with no errors on my original project.  Sometimes the infowindow opens and then closes again, but there is not exception and its not as often.  Thanks.
