### ISSUE TITLE
CSS Animation Issue - Ionic

### ISSUE THREAD

**Issue by tmyers97** [mapsplugin/cordova-plugin-googlemaps#2140]
I have a navigation bar at the bottom of the map that I made with a div and a [ngClass] tied to it that controls an animation. Right now, if I use a button outside of the map to trigger the animation it works perfectly. However, I would like to trigger the animation to hide/show the bar when I click the map. 

The function is getting called on the map click but the animation does not take place. If I minimize the app to the background and come back the div shows in the position it should be.

.scss
```
.showBarHome
{
  bottom: 1.5%;
 -webkit-transition: ease-out 1s;
 -moz-transition: ease-out 1s;
 -o-transition: ease-out 1s;
  transition: ease-out 1s;
} 

```
.html
`<div id="bottomBarHome" [ngClass]="showBar ? 'showBarHome':'hideBarHome'"></div>`

.ts
```
 this.map.on(GoogleMapsEvent.MAP_CLICK)
        .subscribe(() => {
        this.showBar = this.showBar ? false : true;
        });
```

I got this to work when using PhoneGap but Ionic seems to be nothing but issues. If anyone could help it would be greatly appreciated.

Thanks!

**Comment by wf9a5m75** [comment]
Please share your project files on github. I will check it.

**Comment by tmyers97** [comment]
https://github.com/tmyers97/maprepo

**Comment by tmyers97** [comment]
Thanks for the help, I found a solution by forcing an update of the view via ChangeDetectorRef.

**Comment by wf9a5m75** [comment]
```
<div id="map_canvas" (click)="toggleShow()"></div>    
```

You can not receive the click event on the map div. All touches for this div passes to the map view.

**Comment by wf9a5m75** [comment]
Anyway, this is not plugin's issue, ionic coding problem.
