### ISSUE TITLE
iOS - Localization still use wrong translation

### ISSUE THREAD

**Issue by Michazzz** [mapsplugin/cordova-plugin-googlemaps#2143]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.2.7 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.2.1 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "3.13.1",
"@ionic-native/google-maps": "^4.5.3",
```

**Current behavior:**
Phone language is english, warning popup is in NL (see screen below)

**Expected behavior:**
Popup should be in Enghlish as well.

**Screen capture or video record:**
![img_0489](https://user-images.githubusercontent.com/1652051/37397525-235d7da6-277c-11e8-893c-3baebaa19345.jpg)

**Related code, data or error log (please format your code or data):**
Not needed.

**Comment by Michazzz** [comment]
After fix for Dutch translation, the problem still occurres

**Comment by wf9a5m75** [comment]
Please share the project files that reproduce your issue 100% onto GitHub.

**Comment by Michazzz** [comment]
@wf9a5m75 It is not possible to share the project files. I'm watching similar issues, as you know. I removed plugin as you suggested on other similar issues. On 2.2.5 I had Japanese, then in 2.2.6 I had Hindi or Arabic language and at 2.2.7 I have Dutch language.

To make sure it is not issue on my side, before every build, I'm cleaning /node_modules /platform /plugins /www and package-lock.json

**Comment by wf9a5m75** [comment]
No contribution, no help.

**Comment by Michazzz** [comment]
Sorry, it is not possible to share code using this plugin. I can make some changes in plugin and check if it helps, but it is not possible to share code.

**Comment by wf9a5m75** [comment]
I didn't ask you to share your project files.
I asked the project files that reproduce your issue 100%

**Comment by Michazzz** [comment]
@wf9a5m75 Here you can find uploaded yours GoogleMaps project files: 
[https://github.com/Michazzz/cordova-plugin-googlemaps](url)

**Comment by Skydragonsz** [comment]
Be sure to change the native development region if you are using XCode.

![image](https://user-images.githubusercontent.com/1357800/37410990-05c90b68-27a2-11e8-9bca-7e522cd8c48a.png)

**Comment by Michazzz** [comment]
@Skydragonsz Yes, I have configured it to United Kingdom, but still without success.

**Comment by wf9a5m75** [comment]
Okay, it seems Cordova lib has a bug.

**Comment by Michazzz** [comment]
@wf9a5m75 By the way I could help with PL translations

**Comment by wf9a5m75** [comment]
@Michazzz Could you translate these files, and send them to my e-mail address? (Check out my profile page https://github.com/wf9a5m75)

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/res/values/pgm_strings.xml

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/strings/Base.lproj/pgm_Localizable.strings

**Comment by wf9a5m75** [comment]
Fixed.
https://youtu.be/MOC1h7M8y7Q

**Comment by Michazzz** [comment]
I can confirm, the issue has been fixed.
