### ISSUE TITLE
  markerCluster.on(GoogleMapsEvent.MARKER_CLICK) doesnt trigger

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#2145]
```
 this.map.addMarkerCluster({
                markers: data,
                icons: [
                    { min: 2, max: 100, url: "assets/clusters/m1.png", anchor: { x: 16, y: 16 } },
                    { min: 100, max: 1000, url: "assets/clusters/m2.png", anchor: { x: 16, y: 16 } },
                    { min: 1000, max: 2000, url: "assets/clusters/m3.png", anchor: { x: 24, y: 24 } },
                    { min: 2000, url: "assets/clusters/m4.png", anchor: { x: 32, y: 32 } },
                ]
            }).then((markerCluster: MarkerCluster) => {
                
                markerCluster.on(GoogleMapsEvent.MARKER_CLICK).subscribe((params) => {
                  console.log(1)
                 })
            })
```

The problem is that doesnt do the console.log(1) instead shows this console.log: 
-----> This is remained cluster icon : 209105

**Comment by wf9a5m75** [comment]
Please share the project files that reproduce your issue 100% onto GitHub.

**Comment by francoro** [comment]
I sent you the invite to the bitbucket repo. The file is under /pages/map

**Comment by francoro** [comment]
I have this versions :

"@ionic-native/core": "^4.5.3",
   "@ionic-native/google-maps": "^4.5.3"
cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"

**Comment by wf9a5m75** [comment]
At least, please try `cordova-plugin-googlemaps 2.2.7`

**Comment by fssrepository** [comment]
I have used addEventListener and it was working on 2.2.5 just a day ago.

**Comment by francoro** [comment]
@fssrepository Did you use this code?: 
```
 this.map.addMarkerCluster({
                markers: data,
                icons: [
                    { min: 2, max: 100, url: "assets/clusters/m1.png", anchor: { x: 16, y: 16 } },
                    { min: 100, max: 1000, url: "assets/clusters/m2.png", anchor: { x: 16, y: 16 } },
                    { min: 1000, max: 2000, url: "assets/clusters/m3.png", anchor: { x: 24, y: 24 } },
                    { min: 2000, url: "assets/clusters/m4.png", anchor: { x: 32, y: 32 } },
                ]
            }).then((markerCluster: MarkerCluster) => {
               // console.log("markerCluster", markerCluster)
                
     
                markerCluster.addEventListener(GoogleMapsEvent.MARKER_CLICK).subscribe((params) => {
                    console.log("ENTER MARKER CLICK")
                    
                }); 

             })
```

**Comment by francoro** [comment]
@wf9a5m75 Could you find something wrong in the code? . The weird thing is also that when i click a marker it shows me a infowindow with a title of the marker and i remember do that the first time but now i delete that code and stills shows me the infowindow with the title is like if there is in localstorage or cache of the plugin i dont know and also shows me this console log: -----> This is remained cluster icon . Do you have any idea what can be the error?

**Comment by wf9a5m75** [comment]
I have been working on another issue currently.

**Comment by francoro** [comment]
Oh okay, well when you have time check it i will be waiting the notification. its a shame because the clusters work and are so fast but i need the clicking in the marker otherwise i will have to change to google map api js :(

**Comment by francoro** [comment]
I solve it. The problem was that i has a id property in the data that i pass to the clusters and i check that you put an id when you create them so that was interferring

**Comment by wf9a5m75** [comment]
I see. I will change the plugin's code later to prevent conflict. Anyway, congrats.

**Comment by gregavola** [comment]
@francoro Can you share your code - the following code just does this:

-----> This is remained cluster icon : 116340

```
   markerCluster
      .addEventListener(GoogleMapsEvent.MARKER_CLICK)
      .subscribe(params => {
        console.log('ENTER MARKER CLICK');
      });
```

**Comment by francoro** [comment]
@gregavola This is my code:

```
this.map.addMarkerCluster({
      markers: newArray,
      boundsDraw: false,
      maxZoomLevel: 18,
      icons: [
        { min: 2, max: 100, url: "assets/clusters/m1.png", anchor: { x: 16, y: 16 } },
        { min: 100, max: 1000, url: "assets/clusters/m2.png", anchor: { x: 16, y: 16 } },
        { min: 1000, max: 2000, url: "assets/clusters/m3.png", anchor: { x: 24, y: 24 } },
        { min: 2000, url: "assets/clusters/m4.png", anchor: { x: 32, y: 32 } },
      ]
    }).then((markerCluster: MarkerCluster) => {
      //console.log("markerCluster", markerCluster)

      markerCluster.on(GoogleMapsEvent.MARKER_CLICK).subscribe((params) => {
     })
   })
```
