### ISSUE TITLE
Cannot read property 'style' of null 

### ISSUE THREAD

**Issue by dpa99c** [mapsplugin/cordova-plugin-googlemaps#2146]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cc.fovea.cordova.purchase 6.0.0 "Purchase"
cordova-android-support-gradle-release 1.1.5 "cordova-android-support-gradle-release"
cordova-background-geolocation 2.9.1 "BackgroundGeolocation"
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-fabric-plugin 1.1.9 "cordova-fabric-plugin"
cordova-launch-review 2.0.2 "Launch Review"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-battery-status 1.2.5 "Battery"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-dialogs 1.3.2-dev "Notification"
cordova-plugin-email-composer 0.8.11 "EmailComposer"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-google-analytics 1.7.4 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.2.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2-dev "InAppBrowser"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-vibration 2.1.6 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.1.1 "Cordova sqlite storage plugin"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
cordova.plugins.diagnostic 3.9.1 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
es6-promise-plugin 4.1.0 "Promise"
jp.wizcorp.phonegap.plugin.wizUtilsPlugin 2.0.0 "Wizard Utils Plugin"
phonegap-plugin-barcodescanner 7.0.0 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"
```

**Current behavior:**
A Javascript error occurs on cold-starting the app on Android. This causes the `deviceready` error not to fire and the app to hang.

If I reload the Webview content by connecting Chrome Dev Tools, then sometimes the error does not occur and sometimes it does.

So I'm presuming this is a startup race condition because I have lots of other plugins loading in parallel to yours, and sometimes `document.body` is defined and sometimes it's not.

This appears related to #1583, but in this case the offending line is [here](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/pluginInit.js#L105).

Would it be possible to do some defensive coding here? For example:

    if(document.body){
        document.body.style.backgroundColor = "rgba(0,0,0,0)";
    }

**Expected behavior:**
The Android app starts every time without hanging due to a JS error.

**Screen capture or video record:**
![image](https://user-images.githubusercontent.com/2345062/37410548-c47058b4-2798-11e8-98dd-5aa52f700e25.png)
![image](https://user-images.githubusercontent.com/2345062/37410571-d2438416-2798-11e8-9fdd-358d4f689754.png)

**Related code, data or error log (please format your code or data):**

```
cordova@8
cordova-android@6.4.0
Test Device: Google Nexus 6P running Android 8.1.0
```

**Comment by wf9a5m75** [comment]
I see. Thank you for sending a pull request.
