### ISSUE TITLE
remove marker

### ISSUE THREAD

**Issue by matishw** [mapsplugin/cordova-plugin-googlemaps#2147]
hi, i dont know if it's a issue.
how i remove marker from the map?

**Comment by dpa99c** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md#remove-the-marker

**Comment by fssrepository** [comment]
marker object remove, for cluster marker is the same but there is a problem in the java side which has been reported. You need to store the marker objects in a separate list also.

**Comment by matishw** [comment]
hi, thanks, i'm new on ionic and native google maps.
the example of dpa99 is ok but it's just when i click on the marker.
i want to remove it from another place.
do u have any example?
