### ISSUE TITLE
turn on gps of the device

### ISSUE THREAD

**Issue by elchory96** [mapsplugin/cordova-plugin-googlemaps#2149]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```
Hello

I have been using this excellent plugin in phonegap / cordova and I just realized that before I was using the map.getMyLocation (onSuccess, onError) function; and it works perfect, the question is that before, If I had the gps deactivated I got a message that if I wanted to activate it, in which I accepted and automatically the gps.

but right now using the updated version of the plugin, and it no longer asks me to turn on the gps and the map.getMyLocation (onSuccess, onError) function; just enter the onError function

I also saw that there was a new function that is:

```
var option = {
     enableHighAccuracy: true // use GPS as much as possible
};
plugin.google.maps.LocationService.getMyLocation (option, function (location)
```

but the message does not come out either, is there a way to turn on the gps of the device with this plugin or would it be looking for a third party?

Thank you

**Comment by wf9a5m75** [comment]
Please take a screen record(video) how to reproduce the problem.

**Comment by makers-mark** [comment]
@elchory96 Is this truly an android and ios issue like you checked in the boxes?

**Comment by elchory96** [comment]
I do not have how to make it work as before, but the question is that if the gps is deactivated it always sends an error in the function map.getMyLocation (onSuccess, onError) I add image of the message it throws.

the question is, the plugin can still turn on the gps automatically or I have to use a third party for example: https://github.com/dpa99c/cordova-plugin-request-location-accuracy

**Comment by elchory96** [comment]
![screenshot_20180315-090810](https://user-images.githubusercontent.com/18226156/37468691-acdc867a-2831-11e8-87f4-f7b33cf05c9b.png)

**Comment by wf9a5m75** [comment]
Well, if you prefer alternative choice, please use it.

**Comment by elchory96** [comment]
but that's why I'm asking you, how can I use this plugin if it's still integrated, because getMyLocation (onSuccess, onError) does not ask me to activate the gps

**Comment by wf9a5m75** [comment]
Can you understand what the error message say?

**Comment by elchory96** [comment]
and you are understanding my request? I know that the message says that the gps is not activated, can I activate it with the cordova-plugin-googlemaps plugin yes or no?

**Comment by wf9a5m75** [comment]
No. That's why the plugin returns the error message. The plugin don't know the device has a GPS or not. The plugin only can know the location is on or off.

**Comment by BrianMoreno1994** [comment]
@elchory96 No, this plugin no longer supports the permission dialog box. I had a similar issue and ended up using a third-party plugin to show the permission dialog. It would be great if this plugin supported the permission dialog natively without a third-party plugin like it used to, but hey, we've got to play the cards we're dealt with. :)

[https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2119](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2119)
