### ISSUE TITLE
Found cordova plugin add workaround / bugfix

### ISSUE THREAD

**Issue by hirbod** [mapsplugin/cordova-plugin-googlemaps#215]
Hey everybody,
I'm sure the most of you probably know the annoying cordova bug after adding / deleting a plugin. You get something like

```
ERROR: Plugin 'GoogleMaps' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2014-09-26 22:10:26.461 Nachbarschaft[1171:60b] -[CDVCommandQueue executePending] [Line 158] FAILED pluginJSON = [
```

Masashis workaround was to start a new project and recopy everything. Thats quite difficult. Another fix is to type "cordova platform rm ios" (bug seems only to be on iOS) and readd the platform with "cordova platform add ios"

But there is a much better way without the hastle.
Just open your project in Xcode after you've installed the plugin.

On the left side, Click on folder "classes" to open ->  Open Plugins -> Right click on Plugins -> Select sort by type
Now mark all the files with .m (NOT .h)

And on the right side, toggle the checkbox active (Target Membership). Et voila, your plugins will work again. In my Case, all new installed Plugins (google classes, circle.m, maps.m....) we're unchecked. (this is caused trough a Cordova bug. With my workaround, it will take some seconds to get everything work again!

![bildschirmfoto 2014-09-26 um 22 20 25](https://cloud.githubusercontent.com/assets/504909/4427039/d62be97e-45ba-11e4-87df-262acf4cccd1.png)

@wf9a5m75 
This is something for your docs ;)
Saves so much time!

**Comment by Hirbod** [comment]
https://www.youtube.com/watch?v=gr0QrEShPbQ&feature=youtu.be
