### ISSUE TITLE
Add support for browser platform

### ISSUE THREAD

**Issue by JaviRpo** [mapsplugin/cordova-plugin-googlemaps#2150]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [x] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

cordova.js is not present in browser platform, only in android/ios platform.

**Expected behavior:**

cordova.js present in browser platform.

**Screen capture or video record:**

![image](https://user-images.githubusercontent.com/8562436/37441944-cd868f70-27d1-11e8-8f10-1114c40a4a05.png)

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
So far, Android and iOS only

**Comment by vwasteels** [comment]
if I detect platform and instanciate map with javascript API for browser only, will all the map method remains compatible between ios / android and browser ?

thank you
