### ISSUE TITLE
Unable to Install cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by tonyawad88** [mapsplugin/cordova-plugin-googlemaps#2151]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
Error: Failed to fetch plugin cordova-plugin-googlemaps@^2.2.8 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cordova-plugin-googlemaps@^2.2.8
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
I am unable to install the plugin. Can you please help me out?

**Expected behavior:**

**Comment by wf9a5m75** [comment]
```
$> cordova platform rm android ios

$> cordova plugin rm cordova-plugin-googlemaps
```

**Comment by wf9a5m75** [comment]
version2.2.8 is not released to npm yet.

**Comment by makers-mark** [comment]
Probably this is either a connection problem, or plugin spec is incorrect.

**Comment by Michazzz** [comment]
@tonyawad88 For now you can use multiple_maps branch to use latest version of the plugin.

**Comment by tonyawad88** [comment]
When I execute the following:
```
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
```
I get an error to retrieve it, I tried multiple times and I still get it (thoughts?):
```
Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**Comment by Michazzz** [comment]
Did you first removed plugin then install it again? 

```
$> cordova plugin rm cordova-plugin-googlemaps

$> rm -rf node_modules/cordova-plugin-googlemaps

$> rm -rf plugins/cordova-plugin-googlemaps

$> cordova plugin add cordova-plugin-googlemaps#multiple_maps  --variable API_KEY_FOR_ANDROID="your_android_api_key" --variable API_KEY_FOR_IOS="your_ios_api_key"
```

**Comment by tonyawad88** [comment]
That helped the local builds, thank you. 
Any idea why potentially the Ionic Pro Cloud builds fails with the following error? 
```
Discovered plugin "cordova-plugin-googlemaps" in config.xml. Adding it to the project
Fetching plugin "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git" via git clone
Failed to restore plugin "cordova-plugin-googlemaps" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 128 Error output:
Cloning into '/var/folders/0p/nr4nqjrd0mv015fp5tn3pb8w0000gn/T/git/1521113130652'...
fatal: Unable to find remote helper for 'git+https'
```

**Comment by Michazzz** [comment]
@tonyawad88 
Check your package.json for googlemaps. Should be exactly like this, if you using multiple_maps: 
```
"cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
```

**Comment by tonyawad88** [comment]
My package.json has these entries:
```
"cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
"cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.6.0",
```

**Comment by Michazzz** [comment]
So it could the problem with git on the cluod. Check this issue, looks like related to yours: 
[https://github.com/ionic-team/ionic-cli/issues/2716](https://github.com/ionic-team/ionic-cli/issues/2716)

**Comment by tonyawad88** [comment]
Thanks for digging up that ticket. I will follow it.

One of the suggestions they have is to replace config.xml and package.json spec with the following:
**package.json:**
```
"cordova-plugin-googlemaps": "git+ssh://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
"cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.6.0",
```
**config.xml:**
```
<plugin name="cordova-plugin-googlemaps" spec="ssh://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps">
```

I get a similar error as well when trying it locally. Mind you if we try adding this plugin using the standard way "cordova-plugin-googlemaps", on previous versions the Ionic Pro Cloud was able to build it.

**Error:**
```
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/mapsplugin/cordova-plugin-googlemaps.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
```

**Comment by Michazzz** [comment]
@tonyawad88 So Maybe it will be good idea wait few hours for update a master to 2.2.8 and then back to the standard build way?

**Comment by wf9a5m75** [comment]
v2.2.8 is now available on npm.

**Comment by tonyawad88** [comment]
I can confirm the following worked great.

**package.json:**
```
"cordova-plugin-googlemaps": "^2.2.8",
"cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.6.0",
```

**Comment by kodeine** [comment]
i keep getting this,

```
Error: Failed to fetch plugin git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

I'm trying to install `multiple_maps` branch

**Comment by battika** [comment]
I have the same issue all the time but when I re-run the install command
again it will get installed.

**Comment by leo4444** [comment]
I had the same problem ...
I already had a project on Android developed on Windows 10 and I was now working on Mac for iOS. When I wanted to add the platform (sudo ionic cordova platform add ios) I had this problem ... I tried many things but the problem was that I added "sudo" in the command line. Removing "sudo" gave me permission errors in the platforms / ios directory, so I gave it read / write permissions and ran the command again ...
This was what worked for me, I hope it serves the one who has this problem
