### ISSUE TITLE
Double infowindow

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#2153]
![screenshot_2018-03-15-10-36-52](https://user-images.githubusercontent.com/19310384/37466688-2b5e3984-283d-11e8-91be-3e805e81da9f.png)

The problem is the first infowindow that says "Casa de 2 ambientes" it should not appear because is not in the code, it was before but now i deleted. This is my code:

`
 markerCluster.on(GoogleMapsEvent.MARKER_CLICK).subscribe((params) => {
                    
                    let marker: Marker = params[1];
                   
                    let frame: HTMLElement = document.createElement('div');
                    frame.innerHTML = [
                        '<div class="card-map">',
                            '<img class="card-image" src="'+ marker.get("image") +'">',
                            '<div class="info-container">',
                                '<div class="property-transaction">' + marker.get("property_type") + " en " + marker.get("transaction_type"),
                                '</div>',
                                '<div class="title">' + marker.get("title"),
                                '</div>',
                                '<div class="address">' + marker.get("address"),
                                '</div>',
                                '<div class="price">' + marker.get("price"),
                                '</div>',
                                '<div class="caracteristicas">' + marker.get("caracteristicas"),
                                '</div>',
                            '</div>',
                        '</div>'
                    ].join("");
                    
                     // trying if this close the old infowindow but no
                    htmlInfoWindow.close();
                    
                    htmlInfoWindow.setContent(frame, { width: "150px", height: "100" });
                    
                    htmlInfoWindow.open(marker);
                    
                }); `
i dont know if the plugin is using cache and  there is way to delete this but otherwhise i dont know what can be.

**Comment by francoro** [comment]
But if i put this in my code it only shows me that hello world so it works okay i dont know what is wrong when you put in the frame innerHtml what i put above. its weird

```
frame.innerHTML = [
                        '<h3>Hello world </h3>',
                        '<h2>hOla </h2>'
                    ].join("");
```

**Comment by wf9a5m75** [comment]
Don't set the title proper.

**Comment by francoro** [comment]
Great, it works now. Thanks!
