### ISSUE TITLE
compatibility phonegap-plugin-push

### ISSUE THREAD

**Issue by tmwebs** [mapsplugin/cordova-plugin-googlemaps#2159]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.1 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-push 2.1.3 "PushPlugin"
```

**Related code, data or error log (please format your code or data):**

```
When I use the plugin phonegap-plugin-push with the plugin cordova-plugin-googlemaps I receive the following error when building on Android:

A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

But if you unite cordova-plugin-googlemaps, the notifications work correctly. Any idea why it is incompatible?

Thank you very much
```

**Comment by wf9a5m75** [comment]
`cordova-plugin-googlemaps 2.1.1` is too old. I don't support older versions.

**Comment by rafaelblink** [comment]
Why are you using 2.1.1 version? The plugin is in 2.2.8 version.

**Comment by tmwebs** [comment]
ok, the problem has been fixed updating to version 2.2.8, thanks, but when I updated the blue point of geolocation has disappeared and the geolocation button does not work

**Comment by makers-mark** [comment]
Since 2.2.0 you have the option or declaration to display the blue dot and/or the button.
On your map object you have to set it correctly, it has been documented [here.](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.2.0/README.md#the-mylocation-property-has-changed)
It is a very easy fix.

**Comment by makers-mark** [comment]
```
var onSuccess = function(location) {
      map.setOptions({
        camera: {
          'latLng': {
            "lat": location.latLng.lat, 
            "lng": location.latLng.lng 
          },
       controls : {
             myLocation = true 
             myLocationButton = true
         },
          'zoom': 15
        }
      });
 };//onSuccess
```

**Comment by tmwebs** [comment]
thank you very much, everything perfect
