### ISSUE TITLE
Cluster positioning based on the average number of markers instead of center of the area

### ISSUE THREAD

**Issue by danieleLewis** [mapsplugin/cordova-plugin-googlemaps#2160]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [x] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.2.8 "cordova-plugin-googlemaps"
```

**Current behavior:**
When I add different markers in a cluster, the cluster circle is positioned in the center of the area it represents even if I have 100 markers on the left and 1 marker on the right.

**Expected behavior:**
I want to position the cluster closer to the biggest number of markers.
For example looking at your demo repo for clustering:
In this image, the 15 circle is positioned in the center of the area
![schermata da 2018-03-19 14-22-22](https://user-images.githubusercontent.com/18093207/37598224-f80aa7fa-2b81-11e8-8a7d-dd14a18a2d9e.png)
But I'd like to have it more on the left because there are more markers in that direction:
![schermata da 2018-03-19 14-22-11](https://user-images.githubusercontent.com/18093207/37598312-254ab9bc-2b82-11e8-9083-8bdf433bebfe.png)
It should be cool to have an option to choose if the position must be at the center of the area or based on the average number of markers.
Is there an option for that?
I hope I explained it well.

Thanks

**Comment by wf9a5m75** [comment]
If you donate $1000 usd, I will implement another algorithm.

**Comment by wf9a5m75** [comment]
ping

**Comment by danieleLewis** [comment]
I can't pay for this type of work sorry.
