### ISSUE TITLE
[announce] Suspend the supporting for ionic projects

### ISSUE THREAD

**Issue by wf9a5m75** [mapsplugin/cordova-plugin-googlemaps#2162]
Thank you for using `cordova-plugin-googlemaps` through `@ionic-native/google-maps`.

As far as this plugin's author, I fixed and updated `@ionic-native/google-maps` which is **NOT** my plugin.
But I faced couple of unreliable things from the ionic-team.

Therefore, I decided to stop supporting the `@ionic-native/google-maps` plugin, including the person who use it.

From this ticket number #2162, I simply close your ticket no matter what if I decide you use `@ionic-native/google-maps` plugin.

Thank you.

**Comment by battika** [comment]
Hello @wf9a5m75 , I can see the Ionic team is naming you as official maintainer of the `@ionic/native-google-maps` plugin which is a very good news. Do you continue supporting developers using Ionic with the Google Maps plugin? Thank you for your continued work on this fantastic plugin.

**Comment by wf9a5m75** [comment]
Um, I haven't received any invitation.

**Comment by labhollow** [comment]
@wf9a5m75 That's very disappointing to say the least. I'm surprised you couldn't work out the differences and come to some type of resolution with the Ionic team. Now, those that have been using Ionic and your plugin will have to decide what direction to take next. I appreciate all that you have contributed to this plugin to this point. Thank you.

**Comment by wf9a5m75** [comment]
`Suspend` means `stop for a while` at least.

As I described at https://github.com/ionic-team/ionic-native/issues/2410, the biggest problem is the schema.

For example, I sent a pull request (code update) for the maps plugin v2.2.0 to the `@ionic-native/google-maps` repo one month ago.
After two weeks, they finally merged the code. I understand the in-charge person was busy. 
After more two weeks, they ignored my contacts, even the CEO of ionic.
As the result, the `@ionic-native/google-maps` was terribly delayed.

I can understand they have their own reason (maybe). That's why I waited long days.
But they should reply to my contacts at least.
So, until the ionic team and I solve this problem, I don't contribute the `@ionic-native/google-maps` plugin because it's not my plugin.

**Time is money.**
I spent lots of my private time to fix the bugs of `@ionic-native/google-maps`. Because even the `@ionic-native/google-maps` is open source, nobody did  not (or could not) fix it.
But there is no reason to spend further my private time if the ionic team is rude to me.

However I understand many funs of this plugin prefer ionic framework.
That's why I offered three choices:

![screen shot 2018-03-21 at 10 19 25 am](https://user-images.githubusercontent.com/167831/37725940-6224b494-2cf1-11e8-96aa-ae739d6a27a7.png)

Then, the ceo of ionic says:

![screen shot 2018-03-21 at 10 18 09 am](https://user-images.githubusercontent.com/167831/37725870-305a23ea-2cf1-11e8-9ebf-1a18b7cc3df2.png)

Well, what would be occurred. I have been waiting their action.

----

By the way, you can use this plugin without `@ionic-native/google-maps`. Some people do it.

**Comment by labhollow** [comment]
@wf9a5m75 I hope my comment didn't come off as anything negative towards you and all the hard work you have put in on this plugin. My frustration was directed at the Ionic team and their lack of communication. Sounds like they finally listened to you. Thank you!

**Comment by wf9a5m75** [comment]
Thank you for your paitient. The ionic team understood the problem, and they agreed with alternative offer.
So, the ionic-native/google-maps is now on separated repository officially.
https://github.com/ionic-team/ionic-native-google-maps

I resume the suppoting for ionic projects.
