### ISSUE TITLE
Map does not resize when containing div style is changed

### ISSUE THREAD

**Issue by AppwareDev** [mapsplugin/cordova-plugin-googlemaps#2163]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.2.8 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```
**Current behavior:**

The map does not resize to the height of the containing div when I change it. It only resizes if I transition to another page or open the side menu (I'm using Ionic).

**Expected behavior:**

The map should resize to the height of the containing div when the CSS height is changed. I have tried the suggested fix ```cordova.fireDocumentEvent('plugin_touch', {});``` but it doesn't have any effect, even when wrapped in a timeout. 

**Screen capture or video record:**
![map-resize-issue](https://user-images.githubusercontent.com/20772892/37658086-9abd792e-2c44-11e8-959e-e886fe5d18c1.gif)

**Related code, data or error log (please format your code or data):**
```
// Toggles Map on click and applies style using ng-style
$scope.toggleMap = function() {
        if ($scope.mapExpanded) {
            $scope.mapExpanded = false;
            $scope.mapHeight = {
                "height" : "35%"
            }
        }
        else {
            $scope.mapExpanded = true;
            $scope.mapHeight = {
                "height" : "100%"
            }
        }
    }
```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response, I close this thread.
