### ISSUE TITLE
getLocation() not working v2.2.7

### ISSUE THREAD

**Issue by innoflash** [mapsplugin/cordova-plugin-googlemaps#2165]
Hi fellaz,

I just upgraded to v2.2.7 and the **map.getMyLocation()** is no more working
My code goes as follows:

Init Map:
```javascript
var mapDiv = document.getElementById("routeMaps");
        map = plugin.google.maps.Map.getMap(mapDiv, {
            controls: {
                myLocationButton: true
            },
            gestures: {
                'scroll': true,
                'tilt': true,
                'rotate': true,
                'zoom': true
            }
        });
        map.one(plugin.google.maps.event.MAP_READY, onMapReady);
```

Get location:
```javascript
function onMapReady() {
        map.animateCamera({
            target: {lat: -26.129903, lng: 28.105539},
            zoom: 10,
            tilt: 20,
            bearing: 140,
            duration: 1000
        }, function () {
            var option = {
                enableHighAccuracy: true, // use GPS as much as possible
                timeout: 3000
            };
            try {
                map.getMyLocation(option, locationSuccess, positionError);
            } catch (e) {
                plugin.google.maps.LocationService.getMyLocation(option, locationSuccess, positionError);
            }
        });

    }
```

the map is successfully animating in but its not calling the try catch block, Even if i place them out of that camera callback function.

But one thing for certain its prompting that the app needs to use location services, any idea what could be happening,

The **getMyLocation** method is neither calling the **success or failure callback**

The last time i was using v2.0.0 getMyLocation was working

Thanks in advance

**Comment by battika** [comment]
What devices are you testing this on? Genymotion?

**Comment by innoflash** [comment]
No i am using a real device, v2.0.0 used to work now with v2.2.7 its another case

**Comment by wf9a5m75** [comment]
What device?

**Comment by wf9a5m75** [comment]
Internal code of `map.getMyLocation` and `plugin.google.maps.LocationService.getMyLocation` are the same, and no JS error occurs. So, you just needs only one method `plugin.google.maps.LocationService.getMyLocation()`

**Comment by wf9a5m75** [comment]
Please show me the screen captures of your device for these pages:

- system settings > location
- system settings > about your device
- The app info page of your app

**Comment by wf9a5m75** [comment]
For examples:

![screenshot_20180321-074517](https://user-images.githubusercontent.com/167831/37716584-144b90a4-2cdc-11e8-833f-d592f4d4566d.png)
![screenshot_20180321-074745](https://user-images.githubusercontent.com/167831/37716616-29918b26-2cdc-11e8-8b12-211b9a6be494.png)
![screenshot_20180321-074828](https://user-images.githubusercontent.com/167831/37716661-44a3c460-2cdc-11e8-8e53-598f45170c65.png)

**Comment by innoflash** [comment]
system settings > location
![whatsapp image 2018-03-21 at 16 47 40](https://user-images.githubusercontent.com/12772919/37716729-dcb176da-2d27-11e8-8126-b25f83b3b49f.jpeg)

system settings > about your device
![whatsapp image 2018-03-21 at 16 47 40 1](https://user-images.githubusercontent.com/12772919/37716761-f0ee68f6-2d27-11e8-9f30-bb8fc5a9d01f.jpeg)

The app info page of your app
![whatsapp image 2018-03-21 at 16 47 41](https://user-images.githubusercontent.com/12772919/37716812-10484a14-2d28-11e8-8994-df1530c8645e.jpeg)

![whatsapp image 2018-03-21 at 16 51 26](https://user-images.githubusercontent.com/12772919/37716852-2721262a-2d28-11e8-847f-d519de166d49.jpeg)

**Comment by innoflash** [comment]
**v2.0.0 useed to work on the same device**

**Comment by wf9a5m75** [comment]
Umm, looks like the code should work without problem. I will check the snippet code later.

**Comment by innoflash** [comment]
Yah i expected it to work too, and i am getting ideas of going to earlier versions if this cant be solved now

**Comment by makers-mark** [comment]
Try:
`controls: {
      myLocationButton: true, 
      myLocation: true
}`

**Comment by wf9a5m75** [comment]
@innoflash Could you try this?

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="./cordova.js"></script>

    <style type="text/css">
    #map_canvas {
      position: fixed;
      left: 0;
      top: 0;
      right: 0;
      bottom: 0;
    }
    </style>
    <script >
    document.addEventListener("deviceready", function() {
      var map = plugin.google.maps.Map.getMap(document.getElementById("map_canvas"));
      map.one(plugin.google.maps.event.MAP_READY, onMapReady);
    });
    function onMapReady() {
      var map = this;
      map.animateCamera({
          target: {lat: 33.836075, lng: -118.352823},
          zoom: 10,
          tilt: 20,
          bearing: 140,
          duration: 1000
      }, function () {
        var option = {
            enableHighAccuracy: true, // use GPS as much as possible
            timeout: 3000
        };
        map.getMyLocation(option, locationSuccess.bind(map), positionError.bind(map));
      });
    }
    function locationSuccess(location) {
      var map = this;
      map.addMarker({
        position: location.latLng,
        title: location.latLng.toUrlValue()
      }, function(marker) {
        marker.showInfoWindow();
      });
    }
    function positionError(error) {
      alert(JSON.stringify(error, null, 2));
    }
    </script>
</head>

<body>
  <div id="map_canvas"></div>
</body>

</html>
```

```
$ cordova plugin list
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.2.7 "cordova-plugin-googlemaps"
```

![2165](https://user-images.githubusercontent.com/167831/37729706-f9e56c52-2cfa-11e8-95a4-06149b9e8c8a.gif)

**Comment by innoflash** [comment]
sure thing, will implement this first thing tomorrow morning, will certainly give you feedback

**Comment by innoflash** [comment]
This really worked, thanks dude, thanks a lot
