### ISSUE TITLE
same package name conflict

### ISSUE THREAD

**Issue by innoflash** [mapsplugin/cordova-plugin-googlemaps#2168]
Now that i have installed the googlemaps plugin to my project for [phonegap build](https://build.phonegap.com)

There is now a conflict of package names, let me show you the error:
![1](https://user-images.githubusercontent.com/12772919/37757847-f51aaf86-2db6-11e8-952c-9473f9de0cab.PNG)

This is because i have 
```xml
    <plugin name="cordova-plugin-googleplus" spec="^5.2.1">
        <variable name="REVERSED_CLIENT_ID" value="my_id" />
    </plugin>
```
for google plus login

and also i have 
```xml
    <plugin name="cordova-plugin-googlemaps" spec="^2.2.8">
        <variable name="API_KEY_FOR_ANDROID" value="my-key" />
        <variable name="API_KEY_FOR_IOS" value="my_key" />
        <variable name="PLAY_SERVICES_VERSION" value="11.8.0" />
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.0" />
        <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="Maps in use" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="maps always used" />
    </plugin>
```
for maps

Any idea on how i can make the two work together

**Comment by wf9a5m75** [comment]
Sorry for late reply. I tried your repo, but I can not reproduce the problem.

**Comment by wf9a5m75** [comment]
Try `<variable name="PLAY_SERVICES_VERSION" value="12.0.0" />` instead of `11.8.0`. This might be helpful.

**Comment by innoflash** [comment]
thanks @wf9a5m75 , but it still didnt build

**Comment by innoflash** [comment]
yah so far thats the only available option, i am killing googleplus and use facebook login instead
