### ISSUE TITLE
LocationService.getMyLocation crash app on ios 9

### ISSUE THREAD

**Issue by danieleLewis** [mapsplugin/cordova-plugin-googlemaps#2169]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.2.8 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
When I try to use LocationService.getMyLocation on ios9, the app crashes.
It works with latest ios versions.

**Expected behavior:**
I should get my position.

**Related code, data or error log (please format your code or data):**

```
https://github.com/danieleLewis/cordova-googlemaps-bug-geolocate-ios9
```

**Comment by wf9a5m75** [comment]
No longer support nfor ios9. It's too old.

**Comment by danieleLewis** [comment]
Ok, didn't know. Thanks.
