### ISSUE TITLE
Can't make markers invisible for ios

### ISSUE THREAD

**Issue by AnTiDoTe153** [mapsplugin/cordova-plugin-googlemaps#2170]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelis
```

```
@ionic-native/core: 4.3.2
@ionic-native/fcm: ^4.5.2
@ionic-native/geolocation: ^4.5.3
@ionic-native/google-maps: ^4.5.2
```

**Current behavior:**

I am trying to add a marker and make it invisible. The android build is working as expected. For ios instead, the markers remain visible.

**Expected behavior:**

I am expecting the markers to be invisible.

**Screen capture or video record:**

**IOS**
![simulator screen shot - iphone 5s - 2018-03-22 at 15 18 21](https://user-images.githubusercontent.com/26393860/37772768-55a71eac-2de4-11e8-9281-72a6a3c2f7ef.png)

**ANDROID**
![29197119_1888090317891348_7484097920506003456_o](https://user-images.githubusercontent.com/26393860/37772932-e41ea812-2de4-11e8-98dd-296bfb3d0b54.png)

**Related code, data or error log (please format your code or data):**

      this.map.addMarker({
        position: {lat: svLat + Math.abs(neLat - svLat) / 2, lng: svLong + Math.abs(neLong - svLong) / 2},
        visible: false,
        infoWindowAnchor: [-150, 50]
      })

**Comment by wf9a5m75** [comment]
`cordova-plugin-googlemaps 2.1.1` is too old. Please try the 2.2.8 at least.
