### ISSUE TITLE
[question] Is map.remove() the way to clear everything related to the map including event listeners?

### ISSUE THREAD

**Issue by chrillewoodz** [mapsplugin/cordova-plugin-googlemaps#2171]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

Sorry for bothering with such a simple question but I couldn't find the exact answer I'm looking for when going through all the issues.

Basically I've been noticing that the app lags like mad when using the map along with markers and polygons, especially when switching from the map view to another view and then going back. So I figured that I was not clearing all the event listeners properly. 

I found `map.remove()` and `map.clear()`, but my question is if `map.remove()` also calls the `clear` method and if the correct way of clearing all listeners related to the map is to simply call `map.remove()` instead of doing it per marker/polygon where you actually add the listeners.

**Comment by wf9a5m75** [comment]
>Is map.remove() the way to clear everything related to the map including event listeners?

yes.
