### ISSUE TITLE
when install native-google-map application crash instance

### ISSUE THREAD

**Issue by athlona64** [mapsplugin/cordova-plugin-googlemaps#2172]
when i install with 
$ ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
$ npm install --save @ionic-native/google-maps

 application crash instance

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2162

**Comment by athlona64** [comment]
😂

**Comment by wf9a5m75** [comment]
I think this https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2167

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by athlona64** [comment]
OK guy it's now resolve thank #2167
