### ISSUE TITLE
it is possible to apply CSS to htmlInfowindow?

### ISSUE THREAD

**Issue by javi124** [mapsplugin/cordova-plugin-googlemaps#2177]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by makers-mark** [comment]
Yes it is. I use the following to apply transparency to the htmlInfoWindow and round the corners (as well as make the little triangle tail less visible):
```
.pgm-html-info-content-frame{
    border-radius: 10px 25px 25px 30px;
    opacity: 0.85;
}

.pgm-html-info-tail-frame{
    opacity: 0.45;
}
```
I can't attest to all css properties or transitions, but I do not see why anything would not work because the htmlInfoWindow is an HTML element. Just try it!

**Comment by javi124** [comment]
I refer to the content, I have a checkbox into htmlInfowindow in ionic  ,Can I call a stylesheet to modify it?
Thanks

**Comment by makers-mark** [comment]
Try:
```
.pgm-html-info-content-frame, input[type=checkbox]{
  /*css properties here*/
}
```

**Comment by javi124** [comment]
Thanks!!!

**Comment by wf9a5m75** [comment]
@javi124 Congrats!

@makers-mark Thank you for supporting othet people.
