### ISSUE TITLE
Unable to remove any other plugin when this one is installed

### ISSUE THREAD

**Issue by amirhammad** [mapsplugin/cordova-plugin-googlemaps#2179]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [X] **iOS**

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
When I enter
`cordova plugin rm cordova-plugin-googlemaps` or `cordova plugin rm cordova-plugin-is-debug`
It fails
(node:3275) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../node_modules/xml2js'

**Expected behavior:**
It should just work. I want to be able to remove any plugin without hassling with this...

**Related code, data or error log (please format your code or data):**

This patch is working for me because i have the xml2js installed on my system globally
```
 src/before_plugin_rm.js | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/before_plugin_rm.js b/src/before_plugin_rm.js
index e183d95b..e449f40d 100644
--- a/src/before_plugin_rm.js
+++ b/src/before_plugin_rm.js
@@ -4,7 +4,7 @@ module.exports = function(ctx) {
       path = ctx.requireCordovaModule('path'),
       Q = ctx.requireCordovaModule('q');

-  var xml2js = require('../node_modules/xml2js');
+  var xml2js = require('xml2js');

   var projectRoot = ctx.opts.projectRoot,
     configXmlPath = path.join(projectRoot, "config.xml");
```
I'm not sure this patch is a good idea because it depends on user to have xml2js installed. However, for now it is my workaround. I'm not a packaging expert, please help me fixing this the "clean" way.
Another workaround is to run `npm i` in the plugin directory.

Thank you for maintaining this plugin. It works well :)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2158

**Comment by amirhammad** [comment]
I'm sorry, I somehow missed that issue. If this is a duplicate, feel free to close it. However, I am encountering this issue always on this setup. 
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v6.11.5
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 
```
Why is that issue closed if the possible fix(https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/fb7dea2628bcc2793ebde3b8c42e644eeac4e6a6) is not merged into master yet? :-o

**Comment by wf9a5m75** [comment]
Historical reason, I use the `multiple_maps` branch for development, and the master is for the same as `npm`. When I release the new version to npm, the multiple_maps branch is merged to the master branch.
