### ISSUE TITLE
Android Background is set automatically without initalizing map

### ISSUE THREAD

**Issue by Emadello** [mapsplugin/cordova-plugin-googlemaps#2180]
Why do I get a blank white page even if I didn't initialize the map? I have a page with a background: url('bg1.png') but it totally ignores this and display a while background

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#how-does-this-plugin-work

**Comment by Emadello** [comment]
Hello,

I understand that the plugin sets the background as transparent, but shouldn't it does that only if I load a map?

Version 1.4 didnt have this issue, but it gives an error now on android, tried 1.4.1 up till 1.4.6  but each version gives a different error.

**Comment by Emadello** [comment]
Is there a way i override the transparent background that this plugin sets? Or disable changing background to transparent if i didnt initiate the plugin?

Or i can revert back to v1.4 but please let me know which version is stable with cordova android 7.0.0

**Comment by wf9a5m75** [comment]
The maps plugin changes the background if you execute 'map.getMap()'

**Comment by wf9a5m75** [comment]
Here is evidence. This plugin changes the background color of only necessary elements.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/4bc39caafe52815148892956197500bb44238ce0/www/Map.js#L209-L221

**Comment by Emadello** [comment]
Actually it changes the background even if map.getMap() is not called

**Comment by Emadello** [comment]
Im not calling map.getMap() and the background of all pages are changed, just installing the plugin does that, if i uninstall the plugin all backgrounds work normally again

**Comment by wf9a5m75** [comment]
Can you read the above code?

**Comment by wf9a5m75** [comment]
This plugin is fully open source code.
Please find which code is the problem.
https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/master/www

**Comment by Emadello** [comment]
I figured out what's the problem, the plugin conflicts with another plugin which is NativePageTransitions (widely used plugin) https://github.com/Telerik-Verified-Plugins/NativePageTransitions

When i install nativepagetransitions I get a blank screen as if I called map.getMap(), can you take a look? I'm currently looking at why it conflicts and will update you

**Comment by Emadello** [comment]
And by the way it happens on iOS and Android

**Comment by wf9a5m75** [comment]
Conflicting with other plugins are not my cover area.

**Comment by Bhavana-S** [comment]
Adding cordova google maps plugin is affecting all the html background color and background images, without using or calling the map.getMap(). It has been quite a long time this issue is raised by others but still could not find solution. 

Please help me out if any one have solved this problem. Or is there any other way to handle this problem.

Thanks in advance.

**Comment by suneetjain** [comment]
> 
> 
> Adding cordova google maps plugin is affecting all the html background color and background images, without using or calling the map.getMap(). It has been quite a long time this issue is raised by others but still could not find solution.
> 
> Please help me out if any one have solved this problem. Or is there any other way to handle this problem.
> 
> Thanks in advance.

Have you got any solution for this. I am still struggling with the same issue with latest stable version as well.

**Comment by Bhavana-S** [comment]
Could not stick on cordova plugin for this issue. So as an alternative used Google javascript api which is really good to work on - https://developers.google.com/maps/documentation/javascript/tutorial

**Comment by ZumelzuR** [comment]
This plugin not take the parent html object ( the container object) at all, just used the body element of the index.html. This is mark "not a bug" but is a bug and big one, so I recommend to first change the label of this issue and then change the description on the readme bellow "how-does-this-plugin-work" section and remove or put that "The benefit of this plugin is the ability to automatically detect which HTML elements are over the map or not." is not working at all. 

Owners should mark this as a bug and then we can do a proper fix. 

(Also this is a cordova plugin that mainly apps in ionic will use, and this is not working as expected in ionic)

I think that this issue if not happen always, just happen when you use the plugin inside a angular component like <app-my-map></app-my-map> for example. Anyways this is something common and sshould be cover by the plugin so we can do a fix for these cases.

**Comment by wf9a5m75** [comment]
You don't need to use this plugin mandatory.
Since this plugin uses a native Google Maps view, which is NOT HTML element, we can not put a map view over the body. If put it, you can not put any HTML elements on the map, even a dialog box.

If you say "this is a big", ok, please fix it. All source code is open.
If you can't do that, please don't use this plugin.

**Comment by ZumelzuR** [comment]
> You don't need to use this plugin mandatory.
> Since this plugin uses a native Google Maps view, which is NOT HTML element, we can not put a map view over the body. If put it, you can not put any HTML elements on the map, even a dialog box.
> 
> If you say "this is a big", ok, please fix it. All source code is open.
> If you can't do that, please don't use this plugin.

I think that nobody will fix an issue if you tagged as "not bug".

**Comment by wf9a5m75** [comment]
You can do that. You can send a pull request anytime

**Comment by wf9a5m75** [comment]
Again, this is open source. If you don't like this plugin code behavior, please send a pull request. Handing the background is in JS code. You only need to know JavaScript

**Comment by ZumelzuR** [comment]
Yes thank you I will check. Anyway you should remove the not bug tag if this is a bug. If something is expected and not happen is not about "I like", is about what is expected, so again maybe you **should** remove the not a bug in this thread, maybe you have more luck in get fixes on this plugin :)

**Comment by wf9a5m75** [comment]
No. This is **not a bug**. Because I designed originally. Don't expect **other developers**. Please do your best.

**Comment by GuerreiroLeonardo** [comment]
> https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#how-does-this-plugin-work

Rude
