### ISSUE TITLE
CAMERA_MOVE_END event not firing correctly

### ISSUE THREAD

**Issue by b4tch** [mapsplugin/cordova-plugin-googlemaps#2181]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-custom-config 2.0.3 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-admobpro-firebase 2.30.1 "AdMob Plugin Pro"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.0 "InAppBrowser"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.7 "SocialSharing"
cordova-sqlite-ext 0.10.1 "Cordova sqlite storage plugin with extras (xx dev version branch)"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.1 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
I am trying to upgrade my code from 1.4 to 2.2.9 but the CAMERA_MOVE_END event is only firing sporadically (sorry, it really does seem to be random).  If I leave my app and then go back into it, I get a number of CAMERA_MOVE_END events firing, as if it is catching up with itself.

**Expected behavior:**
The CAMERA_MOVE_END event should fire when my gesture has stopped.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
The `CAMERA_MOVE_END` event occurs when the map camera is moved including `map.animateCamera()` and `map.moveCamera()` so on.

If you want to know the event on gesture dragging, please use `map_drag_end`.
(Ah, I noticed one thing, I haven't documented this event yet.)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/MAP_DRAG_EVENTS/README.md

**Comment by b4tch** [comment]
Thanks for the speedy reply. That certainly looks like the event that I'd need, but I'm currently trying to work out some other issues caused by the upgrade. I'll close this issue as I'm sure what you suggested will work.

Thanks again for your work on this plugin, it's very much appreciated!
