### ISSUE TITLE
getMyLocation don´t work v 2.2.9

### ISSUE THREAD

**Issue by javi124** [mapsplugin/cordova-plugin-googlemaps#2183]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.2.1 "Cordova sqlite storage plugin"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
@ionic-native/core": "^4.6.0"
@ionic-native/google-maps"
```

**Current behavior:**

I have update the latest version, and location don´t work.

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
{"line":298,"column":103,"sourceURL":"http://localhost:8080/Users/javi/Library/Developer/CoreSimulator/Devices/AF1E8EF9-D2FA-4138-9B36-4CE5FFD74861/data/Containers/Bundle/Application/DAC023AF-D2B9-4B82-A908-3CA764F62A7A/xxxxxx.app/www/plugins/cordova-plugin-googlemaps/www/Map.js","__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}
```

**Comment by wf9a5m75** [comment]
Please share the project files that reproduce your issue 100%.

**Comment by wf9a5m75** [comment]
ping

**Comment by naren-edpuganti** [comment]
get my location not working

**Comment by wf9a5m75** [comment]
As I said, `Please share the project files that reproduce your issue 100%`.

**Comment by wf9a5m75** [comment]
No contribution, no help.

**Comment by javi124** [comment]
Sorry, now I can’t. Tomorrow I will do a new project to see if the problem persist.
I can’t shared muy proyect.


Enviado desde mi iPhone

**Comment by wf9a5m75** [comment]
Okay, I found the problem. Please reinstall the plugin from the multiple_maps branch.

```
$ cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
```

or use `plugin.google.maps.LocationService.getMyLocation()` instead.

**Comment by javi124** [comment]
Thanks  : )

**Comment by AntDelCas** [comment]
How i can import and use
plugin.google.maps.LocationService.getMyLocation()?

I use 
 LocationService.getMyLocation().then(( myLocation: MyLocation) => { ...
and it no works good in iOs.
The first time, ok, but second and next times has error ...

> ERROR Error: "Uncaught (in promise): TypeError: _this.myLocation is undefined...

Part of my code:
```

import {LocationService, GoogleMaps, GoogleMapsEvent, LatLng, MarkerOptions, Marker, MyLocation} from "@ionic-native/google-maps";

...
(export class)
public myLocation: any;

...

ngOnInit() {
        LocationService.getMyLocation().then((myLocation: MyLocation) => {
            console.log(myLocation.latLng);
            this.posicion = myLocation.latLng;
...
```



Thanks.
