### ISSUE TITLE
htmlinfowindow width control

### ISSUE THREAD

**Issue by ccastroelo** [mapsplugin/cordova-plugin-googlemaps#2190]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**

**Current behavior:**
I'm using htmlinfowindow with two buttons inside it that call some procedure. But it's opening almost the full size of the map and I can not control the width of it. (at some point in some other version this did not happen, but I could not reproduce)

What I've already tried:
Assign a div with a class to the htmlinfowindow content (and a simple word inside)
I changed in css the height and width of the class (both with !important)
The height of the htmlinfowindow has been affected by css, but the width does not.

I tried to change the .pgm-html-info-content-frame width via css, the htmlinfowindow is affected, but it does not get centered on the anchor.

I tried using the multiple_map version, but there was no difference.

I would then like to know if there is a way to control the width of the htmlinfowindow.

This is the git of the test project (in case I'm using multiple_map):
https://github.com/ccastroelo/gmteste

thanks in advance

**Comment by wf9a5m75** [comment]
The HtmlInfoWindow is designed that display itself 80% of the map width.
There is no way to control it.

**Comment by ccastroelo** [comment]
For some reason in the past I have been able to reshape. These are images from my app compiled in January and the same code compiled now.

![image-1](https://user-images.githubusercontent.com/2914324/38178170-5e198d5c-35e3-11e8-8732-eee1ad0a1564.jpg)

![image-1-2](https://user-images.githubusercontent.com/2914324/38178172-63df8c00-35e3-11e8-9943-fab602879d64.jpg)


Anyway thanks for the reply. I'll change the layout.

Thx again and thank you for your work.

**Comment by wf9a5m75** [comment]
In the past, I didn't specify 80% of the map div, but it causes lots of troubles.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/88ecd52b0a324c63f699942921a76590c3032a94/www/HtmlInfoWindow.js#L209
