### ISSUE TITLE
There is a way to get the api key used by plugin?

### ISSUE THREAD

**Issue by caiotarifa** [mapsplugin/cordova-plugin-googlemaps#2192]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [x] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

(Sorry for my lack of knowledge and practice.)

Is there a way to get the `API_KEY` being used by the plugin?

**Comment by wf9a5m75** [comment]
For what?

**Comment by caiotarifa** [comment]
There are some reasons for that.

- Debug purposes.
- Use with another component.

**Comment by wf9a5m75** [comment]
API key is random strings. You can't use it for anything.
Using the same api key is for another component is you just specified the same api key when you installing other plugins.

I don't think this feature is helpful for other people.

**Comment by caiotarifa** [comment]
I had a problem where the key was set but the map would not open.

I reinstalled the plugin and it worked, but it would be great have this feature for debug purposes.

So... I agree it isn't helpful for other people.

**Comment by wf9a5m75** [comment]
I think your first api key was generated before enabling the Google Maps APIs.
