### ISSUE TITLE
Typo in MarkerCluster.js?

### ISSUE THREAD

**Issue by chris-doco** [mapsplugin/cordova-plugin-googlemaps#2198]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/0b8306d5e8b008c6cd811d86c9b03d373f6308f2/www/MarkerCluster.js#L157

**Comment by wf9a5m75** [comment]
oh

**Comment by wf9a5m75** [comment]
Fixed: thank you for letting me know.
