### ISSUE TITLE
setDiv won't render map after multiple page navigation

### ISSUE THREAD

**Issue by matheusdavidson** [mapsplugin/cordova-plugin-googlemaps#2201]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.3.2 "SocialSharing"
cordova-sqlite-storage 2.3.0 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "4.6.0",
"@ionic-native/google-maps": "^4.6.3"
```

**Current behavior:**
I'm using multiple maps branch in my app, which purpose is to show churches and events nearby, i have the map in 4 different pages.

The map will render just fine(using ```setDiv```) when i open the app and transition/navigate to other pages, but, at a certain time, if the map crash in any of these transitions then it does not render anywhere anymore. 

**Expected behavior:**
Transition multiple times between pages and ```setDiv``` work as expected rendering the map.

**Screen capture or video record:**
I've made a video capture showing you how i use maps inside my app but this video won't show the problem as i could make it better by changing my code, will explain further.

[ScreenRecording_04-06-2018 15-14-34.MP4.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1885154/ScreenRecording_04-06-2018.15-14-34.MP4.zip)

**Related code, data or error log (please format your code or data):**

It was crashing after 3 or 4 transitions without showing any error, after the first crash ```setDiv``` will just not render the map inside specified div.

I'll show you a brief of how i start and reload the map:
I have a provider called map.ts, i keep here the map instance and methods to create, reload, attach events, add/clear markers.

In the home page i create the map instance and then in every page i use the map i just reload it using ```setDiv```, heres my code:

**map.provider.ts:**
```map.provider.ts
import { Injectable } from '@angular/core';
import { GoogleMaps, GoogleMap, GoogleMapsEvent, LatLng, Marker, GoogleMapOptions, GoogleMapsAnimation } from '@ionic-native/google-maps';
import { LocationProvider } from '../location/location';

@Injectable()
export class MapProvider {
    public map: any;
    public mapReady = false;
    public markersObject: any = {};
    public markersArray: any[] = [];
    public cameraMoveEvent: any = false;
    public disableNavigation: any = false;
    public disableNavigationTimeout: any = false;

    constructor(
        public googleMaps: GoogleMaps,
        public location: LocationProvider
    ) { }

    loadMap(div: string) {
        return new Promise(async (resolve, reject) => {

            if (this.mapReady) return resolve();

            //
            // Load current location
            await this.getCurrentPosition();

            //
            // Set map options
            let mapOptions: GoogleMapOptions = {
                camera: {
                    target: {
                        lat: this.location.lat,
                        lng: this.location.lng
                    },
                    zoom: 14,
                    tilt: 30
                },
                controls: {
                    compass: true,
                    // myLocation: true,
                    // myLocationButton: true,
                    mapToolbar: true
                }
            };

            //
            // Create map
            this.map = GoogleMaps.create(div, mapOptions);

            //
            // Wait for map to be ready
            this.map.one(GoogleMapsEvent.MAP_READY).then(() => {

                //
                // Mark as ready
                this.mapReady = true;

                //
                // Add event listener
                this.map.on(GoogleMapsEvent.CAMERA_MOVE_END).subscribe((data) => {
                    this.onCameraMoveEnd(data);
                });

                return resolve();
            });
        });
    }

    /**
     * Reload map
     * @param div
     * @param cameraMoveEvent
     */
    reloadMap(div, cameraMoveEvent, coords: any = {}) {

        //
        // Validate map ready
        if (!this.mapReady) return;

        //
        // Disable navigation
        this.disableNavigation = true;

        //
        // Set camera move event
        this.cameraMoveEvent = cameraMoveEvent;

        //
        // Remove markers
        this.map.clear();
        this.markersObject = {};
        this.markersArray = [];

        this.map.setCameraTarget({
            lat: coords.lat ? coords.lat : this.location.lat,
            lng: coords.lng ? coords.lng : this.location.lng
        });

        //
        // Set map
        this.map.setDiv(div);
        this.map.setAllGesturesEnabled(true);

        //
        // Get markers for current position
        if (cameraMoveEvent) cameraMoveEvent([{
            target: {
                lat: this.location.lat,
                lng: this.location.lng
            }
        }], this.map);

        //
        // Enable back button
        clearTimeout(this.disableNavigationTimeout);
        setTimeout(() => {
            this.disableNavigation = false;
        }, 2000);
    }

    /**
     * Add marker to map
     * @param id
     * @param title
     * @param lat
     * @param lng
     * @param icon
     * @param clickEvent
     */
    addMarkerToMap(id, title, lat, lng, icon, clickEvent) {

        //
        // Validate map
        if (!this.map) return;

        //
        // Check if marker is already in the map
        if (this.markersObject[id]) return;

        //
        // Add to markers object
        this.markersObject[id] = true;

        //
        // Add marker
        this.map.addMarker({
            title: title,
            icon: icon,
            animation: 'DROP',
            position: {
                lat: lat,
                lng: lng
            }
        }).then(marker => {

            //
            // Push to marker array
            this.markersArray.push(marker);

            //
            // Set marker click event
            marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe((marker) => {
                clickEvent();
            });
        });
    }

    /**
     * On camera move end
     * @param data
     */
    onCameraMoveEnd(data) {
        if (this.cameraMoveEvent) this.cameraMoveEvent(data, this.map);
    }

    /**
     * Get current position
     */
    getCurrentPosition() {
        return new Promise(async (resolve, reject) => {

            //
            // Get and set geolocation
            await this.location.getGeolocation(false);
            return resolve();
        });
    }
}
```

**home.page.ts:**
```home.page.ts
...
ionViewWillEnter() {
        this.platform.ready().then(() => {

            //
            // Set map instance(only first time i go to home page)
            this.map.cameraMoveEvent = this.mapCameraMoveEvent.bind(this);
            this.map.loadMap(this.mapId);
        });
}
ionViewDidEnter() {

        //
        // Reload map
        this.map.reloadMap(document.getElementById(this.mapId), this.mapCameraMoveEvent.bind(this));
}
...
```

**other-page-with-map.page.ts:**
```other-page-with-map.page.ts
ionViewDidEnter() {

        //
        // Reload map
        this.map.reloadMap(document.getElementById(this.mapId), this.mapCameraMoveEvent.bind(this));
}
```

**Comment by matheusdavidson** [comment]
It was very bad before, crashing after 3 or 4 page transitions, now its a little better after i replaced ```animateCamera``` to ```setCameraTarget``` to set a new center and blocking page transition for 2 seconds after any reload map is done. 

But still, sometimes, if anything goes bad and ```setDiv``` doesn't render the map properly then any other map will not load until i restart the app.

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/ionic-googlemaps-demo/blob/master/src/pages/map/set-div/set-div.ts

**Comment by matheusdavidson** [comment]
@wf9a5m75 you example works, but when you change page its a little different, somewhere the map stops working.

Also, i've tried to put empty ```setDiv``` when leaving the page but it gets worse if i do that, the map crashes in the first transition.

**Comment by wf9a5m75** [comment]
https://github.com/battika/ionic-gmaps-test/blob/master/src/pages/home/home.ts

**Comment by matheusdavidson** [comment]
Yes, but saying empty div i mean ```this.setDiv()```

**Comment by matheusdavidson** [comment]
without any param*

**Comment by wf9a5m75** [comment]
Please share your project files on github, not zip file.
I don't open zip file (or any kind of archived files).

What I will test is 
```
$> git clone http://(git repo)
$> ionic cordova run android
```

In order to save my time, please prepare the project files.

**Comment by matheusdavidson** [comment]
can i give you access to the repo in bitbucket? i have no problems sharing it with you but i don't want to leave it public over here.

**Comment by wf9a5m75** [comment]
Please invite me (my e-mail address is written in my profile page)

**Comment by wf9a5m75** [comment]
Thank you for sharing your repo. Is the name "agr-hibrido"?

**Comment by matheusdavidson** [comment]
yes, thats the one.

The files you want to look are:
```src/providers/map.ts // where the map logic is```
```src/pages/home.ts // where i start the map and reload it(ionViewWillEnter && ionViewDidEnter)```
```src/pages/churches.ts // where i reload the map(ionViewDidEnter)```
```src/pages/movements.ts  // where i reload the map(ionViewDidEnter)```
```src/pages/events.ts  // where i reload the map(ionViewDidEnter)```

**Comment by matheusdavidson** [comment]
You will notice i've placed a delay to page navigation when the map is reloaded(```mapProvider.reloadMap```), ```mapProvider.disableNavigation``` will tell if the page can leave in ```ìonViewWillLeave``` hook

**Comment by wf9a5m75** [comment]
Okay, I created an example the usage of this plugin with ionic provider.
Check out here please.
https://github.com/mapsplugin/ionic-map-provider-example

**Comment by matheusdavidson** [comment]
Looks good, i will try that and get back to you, thank you

**Comment by wf9a5m75** [comment]
ping

**Comment by matheusdavidson** [comment]
Hi, just tested on an Samsung S6 Edge Plus and i confirm the issue still happens.

The map is there when i open the app, if i go to contact page the map is there as well, here is where the problem starts, if i wait a few seconds until the map finish do load and animate in contact page and then go back to home, everything works, but if i don't wait the map finish to render and animate and go back straight to home the map will not render anymore.

**Comment by matheusdavidson** [comment]
try yourself to navigate fast between home and contact page

**Comment by wf9a5m75** [comment]
This plugin does not support such a game playing.

**Comment by wf9a5m75** [comment]
Do you want to still open this issue, or not?

**Comment by matheusdavidson** [comment]
Okay, thank you or your time.

**Comment by nosTa1337** [comment]
@matheusdavidson did you fix this problem? I got a view where I can switch between Listview and Mapview. When switchting a few times the map doesn't load anymore.
