### ISSUE TITLE
pluginInit.js Object prototype change breaks other code that enumerate objects in Android (5.0.1)

### ISSUE THREAD

**Issue by b4tch** [mapsplugin/cordova-plugin-googlemaps#2202]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-custom-config 2.0.3 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-admobpro-firebase 2.31.4 "AdMob Plugin Pro"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-googlemaps 2.3.0-beta-20180406-1845 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.7 "SocialSharing"
cordova-sqlite-ext 2.2.0 "Cordova sqlite storage plugin with extra features"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.1 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
When enumerating/iterating objects, it seems the ```Object.prototype.assign = function() {``` declaration in pluginInit.js is causing issues whereby the function being called on the object does not exist.  For example, I have the InAppBrowser plugin installed.  In Android, whenever a link is clicked in my app, the following code gets run:

```
addEventListener: function (eventname, f) {
            if (eventname in this.channels) {
                this.channels[eventname].subscribe(f);
            }
        }
```

...where this.channels are defined as follows:

```
this.channels = {
            'loadstart': channel.create('loadstart'),
            'loadstop': channel.create('loadstop'),
            'loaderror': channel.create('loaderror'),
            'exit': channel.create('exit')
        };
```

The error received is ```Uncaught TypeError: this.channels[eventname].subscribe is not a function``` where ```eventname``` is "assign".

This particular example can be workedaround by changing the if statement to ```if ( (eventname in this.channels) && ( typeof this.channels[eventname].subscribe == 'function' ) ) {``` but I have also come across a related issue in the jQuery library (error ```Uncaught TypeError: (gb.tweeners[b] || []).concat is not a function``` where ```b``` is "assign".

**Expected behavior:**
Iterating/evaluating objects without issue.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Android 5.0.1 has original Object.assign().

Thus, this code does not run.

`if (typeof Object.prototype.assign !== "function") {`

**Comment by wf9a5m75** [comment]
If you still doubt, please share the reproduce project files on GitHub.

**Comment by b4tch** [comment]
I commented your code out and the problem was solved so I'm pretty certain it's causing an issue. I have worked around it though so I will close this if you don't think it's a problem.

**Comment by wf9a5m75** [comment]
I said `If you still doubt, please share the reproduce project files on GitHub.`
