### ISSUE TITLE
App closes when marker updates in specific zoom and tilt levels

### ISSUE THREAD

**Issue by Gabplay** [mapsplugin/cordova-plugin-googlemaps#2206]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.2.9
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
java.lang.NullPointerException: 
  at plugin.google.maps.PluginMarker$7$1.run (PluginMarker.java:542)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:867)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)

It seems that this only happens when zoom level is higher than 18 or 19 and tilt level is higher than 0.
Look at this gif, first when tilt is 0 it normally updates the marker, then when is higher it crashes.

<img src="https://user-images.githubusercontent.com/12158575/38512018-5bc13e56-3c00-11e8-9cbe-8f162f588917.gif" width="250">

I've published on play store as Alpha, I can add your email if you want to test it.

**Comment by Gabplay** [comment]
Yes, you're already invited in this project because I sent one issue in ionic-native/google-maps.
https://bitbucket.org/Gabcoder/tcctestes/commits/branch/nativemap

If you want to test it, I added your email in alpha testers list.
https://play.google.com/apps/testing/br.edu.ifpr.londrinabus

**Comment by wf9a5m75** [comment]
Well, apk file is not enough. Because I can not debug it.
Please double check the project files that you really specified all necessary packages.

**Comment by wf9a5m75** [comment]
Ah, I might got the reason. I didn't notice you commit to the `nativemap` branch.

**Comment by wf9a5m75** [comment]
Your app can't start at all even the nativemap branch code.
Please double check your code.
![screen shot 2018-04-09 at 11 20 30 am](https://user-images.githubusercontent.com/167831/38525510-7fe190c2-3c07-11e8-86e4-c2d627334258.png)

**Comment by wf9a5m75** [comment]
ping

**Comment by Gabplay** [comment]
Sorry I'm not sure how to fix this error because here it's working fine... I'm using this plugins:

cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.0 "Cordova sqlite storage plugin"

I've just disabled tilt gesture for now, as it's not mandatory for my project, but this issue can help others.

**Comment by Gabplay** [comment]
That's weird, I just tried in a simple project and it didn't crash the app. The marker just glitches a little bit during the bounce animation but is working normally after .remove() and addMarker again... Maybe you can close this issue, I think it just happens in too specific ocasions. Thanks anyway!

**Comment by wf9a5m75** [comment]
okay
