### ISSUE TITLE
Nothing but a blank page

### ISSUE THREAD

**Issue by toto33331** [mapsplugin/cordova-plugin-googlemaps#2207]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.hutchind.cordova.plugins.streamingmedia 0.1.4 "StreamingMedia"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-youtube-video-player 1.0.6 "CordovaYoutubeVideoPlayer"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "4.6.0",
"@ionic-native/google-maps": "^4.6.3",

```
**Current behavior:**
My page is blank, not even the Google logo.
(I've tried to use the streaming video player, wich didn't worked neither, so it may be a native problem.)
I have seen that, since this morning, GoogleMaps component isn't on the ionic doc anymore...

**Expected behavior:**
I'd like to see a map...

**Screen capture or video record:**

I'm not on a mac right now so I can't take a screenshot. But I guess you can imagine a blank page.

**Related code, data or error log (please format your code or data):**

```
https://github.com/toto33331/app5D
```

**Comment by toto33331** [comment]
I'll try these tomorow. But I've tried width IonicView and IonicDevApp on my iPhone. IonicDavApp says

```
Native: tried accessing the GoogleMaps plugin but it's not installed.
```

I've tried that solution, widthout any difference.
```
ngAfterViewInit() {
  this.platform.ready().then(() => {
    this.loadMap();
  });
}
```

It says the same thing went I tried to stream a video
` console.warn: Install the StreamingMedia plugin: 'ionic cordova plugin add cordova-plugin-streaming-media'`

I've tried to download several ionic projects and serve them and that's the same not-installed error.

I also tried to reinstall the plugins and update the native core

**Comment by wf9a5m75** [comment]
`ionic serve` is not supported.

**Comment by toto33331** [comment]
What should I do then ?

Width IonicView I don't serve, it's directly from GitHub, and I have a blank page without information (actually it's my full-height div that is blank and it's really blank, no zoom controll, no gray background, no google logo)

**Comment by wf9a5m75** [comment]
The ionic-native/google-maps supports only actual devices or emulators.

**Comment by wf9a5m75** [comment]
Please use `ionic cordova run ios`

**Comment by toto33331** [comment]
I've tried a ` ionic cordova run android` instead (I don't have a 99$ apple dev account).
I've acivate the debug usb on an android phone and pluggled in. And nothing (I have a cheap usb cable, it may be that).

I've did a ` ionic cordova platform` to check my platforms and a `ionic cordova build ios && android`. Here nothing happened too.

I did a `ionic cordova run android --list` and no devices are detected.

I installed Android Studio and two Virtual devices. Still no device detected.

I opened the platforms/android folder in Android Studio and after 1.5hours on install, the project doesn't want to launch.

I am installing Xcode on a Macbook to try ` ionic cordova run ios`  but I don't think that will work...

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by makers-mark** [comment]
@toto33331 
The USB cable is definitely a culpable component. If replacing that and you cannot communicate with your Android device from your computer, you can not do anything as far as installing anything on it. The communication bridge (for Android) is ADB, published by Google. ADB is included in Visual Studio, but the most common problem in the Android space is improper or incompatible ADB drivers on your computer. I do not know if this is your problem, but you should Google it. It almost seems like you are biting off more than you can chew in the first place. You should look up ADB troubleshooting with your OS specifics.

**Comment by wf9a5m75** [comment]
@toto33331 Did you enable the adb debugging?
https://www.xda-developers.com/install-adb-windows-macos-linux/

**Comment by toto33331** [comment]
Here is my ionic info (just in case)
```
cli packages: (C:\Users\5Dstagiaire\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.8.0
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```

**Comment by makers-mark** [comment]
@toto33331 
Hey tony, your lack of information is troublesome. When you say that you issue the comman `adb devices` and it "confirms" that your device is listed, what does it say beside that? It is only truly connected if it displays a serial number from the device. If it says "pending" or pretty much anything else, other than the random alphanumeric sequence (serial), you cannot communicate with your device. That is unless you are getting TCP for wireless connection.

ADB and Android can be really quirky as far as recognizing devices, and it has been for a really long time. Sometimes I will have to unplug the USB cable and then plug it back in (I've had to do it five times at most with some devices). Some people have had more success plugging in to a different USB ports on the computer.

Do you know what "enable USB debugging" means, like @wf9a5m75 mentioned? You said this:

"For the adb debuging, I downloaded and extraced the folder but when I do adb devices in a command prompt in the folder where adb.exe is, I have an error"

What I think that you meant by saying "that", has nothing to do with enabling ADB debugging on your device. This is a device side instance and has nothing to do with your connection via USB to your PC. If this is the case, the ADB results of `adb devices` will say "pending" or something like I mentioned up above, but it may be some other synonym for "pending" (I do not remember).

You should probably close this issue because your problem started at IOS, and then transcended into a communication issue with Android. 

Just for future reference, you could of used ADB locally within your project folder. ADB requires two dll files as well. They are AdbWinApi.dll & AdbWinUsbApi.dll, which were included in your download.

**Comment by toto33331** [comment]
Yeah sorry for that I'm not very comfortable width all this yet (and english isn't my native language).
When I say it "confirms" it means that my device's serial number (or wathever number it is) displays.
It displays when I hit `adb devices` or `ionic cordova run -list`.

I enabled USB debuging on my android device, and now I have the dev menu with "usb debuging" checked. And the data protocol is MTP.

Now whan I hit `ionic cordova run android --livereload --target=W3D7N16729008184` (my device appears as W3D7N16729008184) here is what I see 


```
$ ionic cordova run android --livereload --target=W3D7N16729008184
Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser --iscordovaserve --platform android --target cordova - Ctrl+C to cancel
[12:39:45]  watch started ...
[12:39:45]  build dev started ...
[12:39:45]  clean started ...
[12:39:45]  clean finished in 185 ms
[12:39:45]  copy started ...
[12:39:45]  deeplinks started ...
[12:39:46]  deeplinks finished in 103 ms
[12:39:46]  transpile started ...
[12:39:54]  transpile finished in 8.04 s
[12:39:54]  preprocess started ...
[12:39:54]  preprocess finished in less than 1 ms
[12:39:54]  webpack started ...
[12:39:54]  copy finished in 8.50 s
[12:40:02]  webpack finished in 8.22 s
[12:40:02]  sass started ...
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[12:40:03]  sass finished in 1.62 s
[12:40:03]  postprocess started ...
[12:40:03]  postprocess finished in 15 ms
[12:40:03]  lint started ...
[12:40:04]  build dev finished in 18.55 s
[12:40:04]  watch ready in 18.89 s
[12:40:04]  dev server running: http://localhost:8100/

[OK] Development server running!
     Local: http://localhost:8100
     External: http://192.168.1.165:8100


> cordova run android --target W3D7N16729008184
Error: ENOENT: no such file or directory, open 'C:\Users\5Dstagiaire\Desktop\app5D\platforms\android\res\values\strings.xml'

[ERROR] An error occurred while running cordova run android --target W3D7N16729008184 (exit code 1).

[12:40:10]  lint finished in 6.03 s

```

I tried to downgrade cordova from 8.0 to 7.1.0 and still this error. I have seen that even when I try to `ionic cordova build android` the folloing error appears

> Error: ENOENT: no such file or directory, open 'C:\Users\5Dstagiaire\Desktop\app5D\platforms\android\res\values\strings.xml'.

**Comment by wf9a5m75** [comment]
`platforms\android\res\values\strings.xml` is not this plugin.
