### ISSUE TITLE
Using multiple map pages, the map drag becomes slow when deny location premission

### ISSUE THREAD

**Issue by kengchih** [mapsplugin/cordova-plugin-googlemaps#2208]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-ble-central 1.1.4 "BLE"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-device-motion 2.0.0 "Device Motion"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-flashlight 3.2.0 "Flashlight"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-mauron85-background-geolocation 2.3.5 "CDVBackgroundGeolocation"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-pedometer 0.4.1 "Core Motion Pedometer"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-shake 0.6.0 "Shake Gesture Detection"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2-dev "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.0 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^4.6.0",
"@ionic-native/google-maps": "^4.6.1",
```
**Current behavior:**
```
After launching the app, it is forbidden to request access to location coordinates.
At the beginning, the map drag is very smooth.When you after navigation the second map page, 
return to the first map page.
The drag of the map has become unusually slow.
```

**Expected behavior:**
```
Drag maps are smooth
```

**Screen capture or video record:**

[Android]
[video_2018-04-10_22-07-50.mp4.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1894956/video_2018-04-10_22-07-50.mp4.zip)

**Related code, data or error log (please format your code or data):**

```
no any error 
```

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by kengchih** [comment]
Sorry, I've uploaded the video to youtube.

https://youtu.be/8Jfx0s0VMSA

Because of security concerns, I will rewrite the sample code as soon as possible.

**Comment by kengchih** [comment]
I have uploaded the example code to github 
https://github.com/kengchih/GoogleMapLab

The map drag is smooth and normal when the coordinates permission are allowed to access.
disabled access coordinates permissions and the map becomes slow

**Comment by wf9a5m75** [comment]
Thank you for sharing the project and the video. It seems it is strange.

However, this plugin does not touch the map rendering feature at all. It is the problem of the Google Maps Android API v2 itself.

**Comment by wf9a5m75** [comment]
I just built and run your app.
![2208](https://user-images.githubusercontent.com/167831/38844001-75f15b16-41a6-11e8-87ed-40f7809e1ccd.gif)

**Comment by wf9a5m75** [comment]
I think just your device network problem.

**Comment by makers-mark** [comment]
Hi @kengchih, you have an extensive list of plugins for your app. Have you thought about, or have you tested what would happen if you alter or remove this plugin?:
`cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"`
