### ISSUE TITLE
Is there a way to get the markers inside the circle draw?

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#2211]
I know you can draw a circle and change its dimensions i see it in the documentation (https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Circle/setRadius/README.md)

But is there a way to get the markers that are inside the circle, i want it for filtering basing me if the marker is inside the circle and get its data.

**Comment by wf9a5m75** [comment]
This is just mathematic in junior high school.
![circle](https://user-images.githubusercontent.com/167831/38635124-3f31427a-3d79-11e8-934a-dac79d151e96.png)

You know the value of `R` (circle radius).

Calculating distance between A and B is 
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/utilities/geometry/spherical/computeDistanceBetween/README.md

**Comment by wf9a5m75** [comment]
If you have bunch of markers, you can also do pre-filtering with `circle.getBounds()`.

The `circle.getBounds()` returns `LatLngBounds`. The `LatLngBounds` class has `contains(LatLng)` method.
After this pre-filtering, then calculates distance between the `circle.getCenter()` and `marker.getPosition()`.

**Comment by francoro** [comment]
Thanks for the reply, i will give it a try
