### ISSUE TITLE
addTileOverlay Zoom Level

### ISSUE THREAD

**Issue by MikeWoots** [mapsplugin/cordova-plugin-googlemaps#2213]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:** 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.0 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

```
```
"ionic-native/google-maps": "^4.7.0"
"ionic-native/core": "^4.7.0",
```
**Current behavior:**
There seems to be a discrepancy between the map zoom level and the zoom level that is passed to addTileOverlay(). The addTileOverlay() zoom level that is used is consistently higher than what is return by getCameraZoom(). For example, if the camera zoom is level 19 the argument that is passed to addTileOverlay will be level 20.

The tiles that are getting pulled from the server are therefore incorrect for the zoom level.

**Expected behavior:**
The x, y, zoom level arguments passed to addTileOverlay should reflect the actual map zoom level.

**Device**
iPad

**Comment by wf9a5m75** [comment]
The x, y, and zoom values are just passes from the native api to js code.
I guess you use 256px for tile size.
Use 512px.
This is not a bug.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/TileOverlay/addTileOverlay/README.md
