### ISSUE TITLE
Is watchPosition() planned for any future release?

### ISSUE THREAD

**Issue by battika** [mapsplugin/cordova-plugin-googlemaps#2214]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [X] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [X] **iOS**

Most of us are using the Google Maps plugin in conjunction with the Geolocation plugin as we need to be notified when the user's location changes (watchPosition). I saw some early comments in one of the project files that gave me the impression you were planning to support watchPosition() in the future. It makes me wonder if it is still being planned for the foreseeable future or it will probably not happen. I would love to drop the Geolocation plugin, hence the question.

As always, thank you for your excellent plugin.

**Comment by wf9a5m75** [comment]
Yes, this is in the feature plan, but not soon.

**Comment by battika** [comment]
Yes, it would be good to have it :)

**Comment by wf9a5m75** [comment]
What is the best way to contact to you?

**Comment by wf9a5m75** [comment]
Or please contact to me by email. I just want to try the beta version before releasing the next one.

**Comment by wf9a5m75** [comment]
(But it's time to bed for me. I will reply to you tomorrow)

**Comment by cyrilxx** [comment]
Hi mate do you have date when will the watch position be release ?
