### ISSUE TITLE
Unwanted permissions are being added by tbxml framework

### ISSUE THREAD

**Issue by amirhammad** [mapsplugin/cordova-plugin-googlemaps#2215]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

In short "android.permission.READ_PHONE_STATE" permission is being requested.
It is a permission marked as "dangerous". 
I believe this googlemaps plugin does not use this permission. 
This permission is requested implicitly - it is not present in the project manifest. 
It is because minSdkVersion declared in manifest of tbxml-android.aar archive is less than 4. 
Please see my comment in
https://github.com/arnesson/cordova-plugin-firebase/issues/619#issuecomment-381178381

This is an issue marked as solved. Is it? 
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2176

**Comment by wf9a5m75** [comment]
The READ_PHONE_STATE permission comes from the Google Play Services SDK 12.0.0.
https://issuetracker.google.com/issues/76024034

Did you read the thread #2176 well?

**Comment by wf9a5m75** [comment]
tbxml is a just XML parser.

**Comment by amirhammad** [comment]
i am using 11.4.2 version of google play services. and the permission is caused by this xml parser indirectly. The hack I did was the only solution I've found effective. Somehow minSdkVersion=1 coming from tbxml is affecting the presence of READ_PHONE_STATE.

**Comment by wf9a5m75** [comment]
This plugin requires the sdk v11.8.0 or higher version. v11.4.2 is no longer supported.

**Comment by wf9a5m75** [comment]
> Somehow minSdkVersion=1 coming from tbxml is affecting the presence of READ_PHONE_STATE.
Please show me the evidence.

**Comment by amirhammad** [comment]
Is there some reasoning for support 11.8.0 and not supporting 11.4.2? Maybe it would be good to have some file regarding updating some sdk to greater one. 

evidence: https://github.com/amirhammad/maps-fun

**Comment by amirhammad** [comment]
It also happens with 11.8.0.... and applying the patch helps.

**Comment by wf9a5m75** [comment]
Can you find which `code` request the permission in this plugin?

https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=READ_PHONE_STATE&type=Code

https://github.com/wf9a5m75/tbxml-android/search?q=READ_PHONE_STATE&type=Code

**Comment by amirhammad** [comment]
I did a little bit of investigation.
After reading this:
https://developer.android.com/reference/android/Manifest.permission.html#READ_PHONE_STATE

> READ_PHONE_STATE
added in API level 1
String READ_PHONE_STATE
Allows read only access to phone state, including the phone number of the device, current cellular network information, the status of any ongoing calls, and a list of any PhoneAccounts registered on the device.
Note: If both your minSdkVersion and targetSdkVersion values are set to 3 or lower, the system implicitly grants your app this permission. If you don't need this permission, be sure your targetSdkVersion is 4 or higher.
Protection level: dangerous
Constant Value: "android.permission.READ_PHONE_STATE"

and comparing with AndroidManifest that is present in this googlemaps plugin, which contains this:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="za.co.twyst"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk android:minSdkVersion="1" />

</manifest>
```
Note the difference with the latest
https://github.com/wf9a5m75/tbxml-android/blob/master/tbxml/AndroidManifest.xml
```
<?xml version="1.0" encoding="utf-8"?>

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="za.co.twyst.tbxml"
          android:versionCode="1"
          android:versionName="1.00.0" >

 <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="19" />

</manifest>
```
The latter one contains targetSdkVersion. The prior one contains only minSdkVersion, that is equal to 1. If targetSdkVersion is ommited, the minSdkVersion is used instead([source](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html)) -> then if targetSdkVersion<4 or "3 or lower), the system implicitly grants your app this permission - READ_PHONE_STATE.
We just need to add the new tbxml build into this repository IMO, or just update the manifest.

**Comment by wf9a5m75** [comment]
As you describe, you just add `targetSdkVersion`, don't you?

**Comment by wf9a5m75** [comment]
This plugin requests `<preference name="android-minSdkVersion" value="19" />`
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/3cbfd711862ac03fa2dcab71cd1de865a17be0f2/plugin.xml#L142

**Comment by wf9a5m75** [comment]
One update: this plugin uses this tbxml on this url, not my account repo.
https://github.com/mapsplugin/tbxml-android

As you can see, the tbxml requests `android:targetSdkVersion="17"`
https://github.com/mapsplugin/tbxml-android/blob/master/tbxml/src/main/AndroidManifest.xml#L5

**Comment by wf9a5m75** [comment]
Even the native code has been compiled with `android-17`
https://github.com/mapsplugin/tbxml-android/blob/master/tbxml/src/main/jni/Application.mk#L3

**Comment by wf9a5m75** [comment]
Please let me know if there is any other doubt point.

**Comment by wf9a5m75** [comment]
I think you just need to 
```
$> cordova clean
$> cordova run android
```

**Comment by amirhammad** [comment]
> One update: this plugin uses this tbxml on this url, not my account repo.
https://github.com/mapsplugin/tbxml-android
>
> As you can see, the tbxml requests android:targetSdkVersion="17"
https://github.com/mapsplugin/tbxml-android/blob/master/tbxml/src/main/AndroidManifest.xml#L5

The first statement is not true.
Another is irrelevant because the first one is not true.

In this repository there is tbxml-android.aar that contains AndroidManifest.xml with the following contents:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="za.co.twyst"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk android:minSdkVersion="1" />

</manifest>
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/frameworks/tbxml-android.aar
fc68489dceddecaef551c427bca7145fe94d2f85
Am I wrong? 


> As you describe, you just add targetSdkVersion, don't you?

Yes because it is enough. But the place I add it is in the manifest contained in tbxml-android.aar

>  \<preference name="android-minSdkVersion" value="19" /> 

What does this mean? That it just adds minSdkVersion to the project manifest? It is not enough. My manifest had 21 all the time before installing cordova-plugin-googlemaps. This is what I am trying to say all the time. That small library that is missing targetSdkVersion >= 4 is making the build process request READ_PHONE_STATE. In case there is something more to understand, please enlighten me.

Have you seen my repository I prepared? It is a simple project. Use the README file to reproduce the issue. The test case always fails.

**Comment by wf9a5m75** [comment]
I updated the tbxml-android.aar.

**Comment by wf9a5m75** [comment]
Yes, thisp plguin minimum require is 19.

**Comment by tryadelion** [comment]
what i'm saying is that tbxml, the dependency, is now targeting 16 instead of 19,making it crash again on merge dex resources gradle build process.

**Comment by wf9a5m75** [comment]
Insert `<preference name="android-minSdkVersion" value="19" />` into config.xml

**Comment by tryadelion** [comment]
it's being ignored.

**Comment by tryadelion** [comment]
<img width="702" alt="captura de pantalla 2018-06-06 a las 16 31 29" src="https://user-images.githubusercontent.com/3778474/41044706-21d6ade6-69a7-11e8-9040-2c622a202ef3.png">

proof that it is completely ignored.

**Comment by tryadelion** [comment]
wrong screenshot on previous comment. proof here:


<img width="503" alt="captura de pantalla 2018-06-06 a las 16 33 01" src="https://user-images.githubusercontent.com/3778474/41044796-54895ed2-69a7-11e8-9e0b-11a56289da5b.png">

**Comment by wf9a5m75** [comment]
I have no problrm about building.

Try like this:

```
// upgrade cordova
$> npm -g install cordova

$> cordova platform rm android

$> cordova platform add android

$> ionic cordova run android
```

**Comment by tryadelion** [comment]
it seemed to work after some cleanup of node modules, cordova platform rm, etc...
It's silly how much "corrupted" installations on cordova can get.
