### ISSUE TITLE
Issue compiling Ionic Android App PolylineOptions error

### ISSUE THREAD

**Issue by guillermo-medina** [mapsplugin/cordova-plugin-googlemaps#2216]
Hi, I'm facing this issue from yesterday and I can't resolve it:

/platforms/android/gradlew: Command failed with exit code 1 Error output:
/platforms/android/src/plugin/google/maps/PluginPolyline.java:39: error: cannot access zzbgl
        polylineOptions.add(path.get(i));
                       ^
  class file for com.google.android.gms.internal.zzbgl not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

Anyone know what could be the problem? I uninstall the cordova component, removed android plaform, added again and the error still happen.

Please help!!

**Comment by wf9a5m75** [comment]
Duplicate https://github.com/ionic-team/ionic-native-google-maps/issues/8
