### ISSUE TITLE
error show htmlinfowindow

### ISSUE THREAD

**Issue by elchory96** [mapsplugin/cordova-plugin-googlemaps#2217]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```
Hello,

Whenever I show several times and hide an infowindow there comes a point that fails.

**Comment by elchory96** [comment]
Sorry for the delay, I could not upload the gif, what happens is that when I click on a map marker the htmlinfowindow appears well, when I move to another marker everything normal, but if I hide it by clicking on the map and then I want to return to open an infowindow, it does not open it and it seems that it is visible because if I drag the map below the marker works fine, but if I do it over the marker I open the sidebar, I leave an example gif.

![20180416_081804](https://user-images.githubusercontent.com/18226156/38811784-23512b3a-4150-11e8-8d11-da0149d06630.gif)

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by elchory96** [comment]
I already added you to the github repository

**Comment by wf9a5m75** [comment]
Umm, the framework7 is always challengeable.

**Comment by wf9a5m75** [comment]
Ok, I finally figured out the problem, and fix it.
I didn't noticed your app generate dynamic image with canvas.

In order to fix the problem, please reinstall the plugin from the `multiple_maps` branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps \
 --variable API_KEY_FOR_ANDROID="..." \
 --variable API_KEY_FOR_IOS="..." \
 --variable PLAY_SERVICES_VERSION ="11.8.0"  <--please adjust the version by yourself.
```

One default behavior has been changed.
The `HtmlInfoWindow` does not apply the `white-space:pre` css property to the contents anymore.
In order to keep the design, please modify your CSS like this.

```css
.infowindow{
  width: 100%;
  line-height: 2px;
  white-space: pre;   /* <-- Add this line */
}
```
![2217](https://user-images.githubusercontent.com/167831/38842800-c1e1ff04-41a0-11e8-8d89-624da2bb87b4.gif)

**Comment by wf9a5m75** [comment]
ping

**Comment by elchory96** [comment]
Ohh! Thank you very much, working correctly, you are a crack friend (Y), I had some problems compiling with the multiple_maps branch in phonegap build, but the rest worked very well.

PD: If I have to make images with canvas to add the label to the marker, sorry for not mentioning the data.
