### ISSUE TITLE
Locally stored tiles on iOS not loading

### ISSUE THREAD

**Issue by MikeWoots** [mapsplugin/cordova-plugin-googlemaps#2219]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:** 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.0 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```
```
"ionic-native/google-maps": "^4.7.0"
"ionic-native/core": "^4.7.0",
```

**Current behavior:**
The addTileOverlay breaks when trying to load tiles stored locally. Tiles are not displayed and the addTileOverlay stops working.

It works fine if pulling tiles from server. The functionality also works perfectly on Android.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by wf9a5m75** [comment]
ping

**Comment by MikeWoots** [comment]
Our main app is not open source so busy putting together small demo app which replicates the issue. Will share with you when done. Let me know if there is any other info that might help you in the meantime. Thanks

**Comment by wf9a5m75** [comment]
Why don't you share your project files on private repository?

**Comment by MikeWoots** [comment]
My company won't allow me to do that but should have the dummy app running in next day or so

**Comment by MikeWoots** [comment]
So writing the dummy app is taking a bit longer than I thought. In the meantime here is the tile overlay function I use.

```
  overlayTiles(){
    // Store a temporary object of the constructor
    let tempObj = this;
    this.gMap.addTileOverlay({
      debug: true,
      // Load image files from the local file path
      getTile: function(x, y, zoom) {
        // scale tile
        let ymax = 1 << zoom;
        let yNew = ymax - y - 1;
        // Get the client and boundary ids required
        let boundaryId = tempObj.currentBoundary.id;
        const offlineKey = boundaryId + '/visible/' + zoom + "/" + x + "/" + yNew + ".png";
        if (typeof tempObj.offlineTiles[boundaryId] !== 'undefined') {
          // Check first if the boundary key exists
          if (offlineKey in tempObj.offlineTiles[boundaryId]) {
            return(tempObj.file.dataDirectory + (boundaryId + '/visible/' + zoom + "/" + x + "/" + yNew + ".png"));
          }
        }
        return null;
      }
    }).then(tileOverlay => {
        this.currentTileOverlayObject = tileOverlay;
      }
    )
  }
```

Basically I download and save the tiles to the path
```
this.file.dataDirectory + (boundaryId + '/visible/' + zoom + "/" + x + "/" + yNew + ".png"
```
using Cordova fileTransfer.

In overlayTiles, if the tile exists it returns a path to that file. I have checked that the download does work and the files are there. 

On the map, the red debug squares are missing from where the tiles should be. So it almost seems like getTile is either breaking silently or not returning for some reason when trying to access the file.

**Comment by MikeWoots** [comment]
Sorry not yet, I have been quite busy the last few days. Out of interest are you able to replicate this issue on your side or is it working as expected? 

Will try get the demo app working as soon as possible.

**Comment by wf9a5m75** [comment]
Since I have piles of tasks, I don't try to reproduce userside code. Git clone is the shortest path to solution.

By the way, I released v2.3.0-rc1 to npm yesterday.
Please try it.

**Comment by MikeWoots** [comment]
https://github.com/MikeWoots/aeromobile_dev

Here's the link. Thanks

**Comment by wf9a5m75** [comment]
Well, how can I confirm the problem?
(This is `v2.3.0-rc1`, and I completed tile downloading)


![2219](https://user-images.githubusercontent.com/167831/39072900-dd905d6a-44a0-11e8-9262-d78ec9e032a0.gif)

**Comment by MikeWoots** [comment]
Hi 

Sorry I was pointing to the wrong file path. I have pushed an update to the repo.

After you click download tiles you see messages like this
```
Tile download success https://s3.amazonaws.com/aero-test-data/1/visible/19/307260/223853.png
```
being printed to the console. It could take a couple of minutes to download all the tiles because I am downloading them in series. When the download finished you should see COMPLETE printed to console.

Now when you click on a polygon you see something like this

![img_0072](https://user-images.githubusercontent.com/19834780/39082463-cfdc30d2-4553-11e8-8104-dd7c66b52e0d.PNG)

you can see where the tile should be overlayed it is just blank.

Again sorry for the initial bug

**Comment by wf9a5m75** [comment]
Unfortunately I have been on a business trip one week fromt today, and so busy.

Did you try the v2.3.0-rc1?

**Comment by MikeWoots** [comment]
Yes I tried it but same issue. Obviously would be great if you could look at it soon because a lot of our users are using the app offline so loading local tiles is quite crucial functionality.

**Comment by wf9a5m75** [comment]
Okay, I figured out the reason. Android accepts `file://` protocol, but iOS does not accept it.

So, easiest solution is 
```
return (tempObj.file.dataDirectory + (boundaryId + '/visible/' + zoom + "/" + x + "/" + yNew + ".png")).replace("file://", "");
```

**Comment by wf9a5m75** [comment]
![screen shot 2018-04-30 at 5 09 38 pm](https://user-images.githubusercontent.com/167831/39456144-49ae6c3a-4c99-11e8-8d45-2e1e70529bbd.png)

**Comment by wf9a5m75** [comment]
In order to fix the problem, modify your code, or reinstall the plugin from the multiple_maps branch please.

**Comment by MikeWoots** [comment]
Amazing, thanks so much for the help Masashi :)
