### ISSUE TITLE
Are circular markers possible?

### ISSUE THREAD

**Issue by Bengejd** [mapsplugin/cordova-plugin-googlemaps#2221]
**I'm submitting a ...**  (check one with "x")
- [X] question
- [ ] any problem or bug report
- [ ] feature request

Is there any way to create a marker that is just a circle with an image as the marker src? So that the marker would ultimately end up looking like this:

<img width="240" alt="title783581518" src="https://user-images.githubusercontent.com/11723093/38842228-d734382a-41b6-11e8-9543-f0833e8ea228.png">

**Comment by wf9a5m75** [comment]
You just need to set a circle image as a marker icon.

**Comment by Bengejd** [comment]
Is there any way to do that via the plugin? I've been looking for solutions on my own to do this on the backend, but I haven't found anything that actually works well at this point.

**Comment by wf9a5m75** [comment]
This plugin does not have such a feature.
However, this plugin accepts `base64 encoded strings` as icon image.

You can generate images with `<canvas>` tag, and export it.

**Comment by Bengejd** [comment]
I have tried adding the markers using canvas like you recommended, but I cannot for the life of me figure out how to input an image into the canvas properly. I got it to display a round circle, but the image is not displaying within the circle. Would you mind taking a look for me?

This is what I'm currently getting:

![download 1](https://user-images.githubusercontent.com/11723093/38963736-676e69b6-4341-11e8-842c-ae82f8215704.png)

Here is my canvas HTML:

`<canvas id="leaf" width="60" height="60" style="border:1px solid #d3d3d3;"></canvas>`

Below is the relevant JS:

```let canvas = <HTMLCanvasElement>document.getElementById('leaf');
let context = canvas.getContext('2d');

let imageObj = new Image();
imageObj.onload = function()
{
  context.save();
  context.beginPath();
  context.arc(30, 30, 28, 0, 2 * Math.PI);
  context.clip();
  context.drawImage(imageObj, 0, 0);
};

imageObj.src = 'http://www.html5canvastutorials.com/demos/assets/darth-vader.jpg';

context.restore();
context.beginPath();
context.arc(30, 30, 28, 0, 2 * Math.PI);
context.drawImage(imageObj, 0, 0);
context.strokeStyle = 'red';
context.stroke();

console.log(canvas.toDataURL());

return canvas.toDataURL();```

**Comment by wf9a5m75** [comment]
It is not related with this plugin. Please ask at the StackOverflow for general programming.
https://stackoverflow.com/questions/15283698/image-not-loading-on-canvas?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by wf9a5m75** [comment]
Probably this one.
https://stackoverflow.com/a/34755162/697856
