### ISSUE TITLE
Phonegap Build error compile only android - v2.2.9 - PluginCircle.java:29: error: cannot access zzbgl

### ISSUE THREAD

**Issue by andresfmg** [mapsplugin/cordova-plugin-googlemaps#2222]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/src/plugin/google/maps/PluginCircle.java:29: error: cannot access zzbgl
      circleOptions.center(new LatLng(center.getDouble("lat"), center.getDouble("lng")));
                   ^
  class file for com.google.android.gms.internal.zzbgl not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.751 secs
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/src/plugin/google/maps/PluginCircle.java:29: error: cannot access zzbgl
      circleOptions.center(new LatLng(center.getDouble("lat"), center.getDouble("lng")));
                   ^
  class file for com.google.android.gms.internal.zzbgl not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

```

**Comment by wf9a5m75** [comment]
The error means the versions of Google Play Services SDK which is requested from this plugin and other plugins are conflicted.
You need to adjust them by yourself.

**Comment by aMUSiC** [comment]
@andresfmg I suggest you use the cordova-android-play-services-gradle-release plugin which keeps the Google Play Services SDK version aligned between all your plugins. Set everything to version 15.+

**Comment by wf9a5m75** [comment]
`cordova-android-play-services-gradle-release` does not work on PhoneGap Build.

PhoneGap Build does not allow any hook scripts.

**Comment by aMUSiC** [comment]
@wf9a5m75 You are right. I didn't notice it was on PhoneGap Build.

Manually it is then for @andresfmg

**Comment by danieleLewis** [comment]
Same here with zzbfm instead if zzbgl.
I added a new plugin and it stopped working, but even if I removed it, I stil cannot build.

**Comment by wf9a5m75** [comment]
As we described above, you need to adjust **the versions of all plugins that use Google Play Services**.

In this plugin, you can specify with `PLAY_SERVICES_VERSION` variable.
https://github.com/mapsplugin/cordova-plugin-googlemaps#phonegap-build-settings

**Comment by wf9a5m75** [comment]
ping

**Comment by danieleLewis** [comment]
I'm not using PhoneGap Build, just normal Cordova.
I tried with the mentioned plugin cordova-android-play-services-gradle-release but with it, it doesn't build because it can't recognize play service 15+

**Comment by andresfmg** [comment]
The issue was a conficth between plugins "google play services",  had to fork gitbub project "cordova-background-geolocation-services.git" and change manually the google play service to 11.8.0 and set manually on  "cordova-plugin-googlemaps" too.  like this:

<variable name="PLAY_SERVICES_VERSION" value="11.8.0" />

thanks :)

**Comment by danieleLewis** [comment]
I did as told here: https://github.com/ionic-team/ionic-native-google-maps/issues/5#issuecomment-380693358
But it didn't solve my problem.
Here is my project.properties:
`target=android-26
cordova.system.library.1=com.google.android.gms:play-services:12.0.1
cordova.system.library.3=com.google.android.gms:play-services-analytics:+
cordova.system.library.4=com.android.support:support-v4:24.1.1+
cordova.system.library.5=com.google.android.gms:play-services-maps:12.0.1
cordova.system.library.6=com.google.android.gms:play-services-location:12.0.1
cordova.system.library.7=com.android.support:multidex:1.0.1
android.library.reference.1=CordovaLib
cordova.system.library.8=com.android.support:appcompat-v7:26.+
cordova.system.library.9=com.facebook.android:facebook-android-sdk:4.+
cordova.system.library.12=com.android.support:support-core-utils:24.1.0
cordova.system.library.16=io.sentry:sentry-android:1+`

**Comment by wf9a5m75** [comment]
`com.google.android.gms:play-services-analytics:+ ` to `com.google.android.gms:play-services-analytics:12.0.1`

**Comment by GonzaloDutra** [comment]
Hola usa 
```
dependencies { 
compile 'com.google.firebase:firebase-messaging:17.0.0'
```
