### ISSUE TITLE
My map disappears when I change my tab

### ISSUE THREAD

**Issue by tmwebs** [mapsplugin/cordova-plugin-googlemaps#2223]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.8 "cordova-plugin-googlemaps"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.1 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
My map disappears when I change my tab

**Expected behavior:**
The map should not disappear

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
I'm trying to uninstall version 2.2.8 and install version 2.2.9, since I've read that the problem is solved, but when I uninstall the plugin it gives me the following error:

(node: 43694) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Can not find module '../node_modules/xml2js'
(node: 43694) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that will not be handled will end the Node.js process with a non-zero exit code.

and I can not uninstall it.
```

**Comment by battika** [comment]
Hello, why don't you remove the plugin from the plugins folder, or the entire plugins folder and reinstall everything using the cordova prepare command? You should change the Google Maps plugin version in the config.xml file so version 2.2.9 will be automatically deployed.

**Comment by wf9a5m75** [comment]
In the v2.2.8, you need to detach the map view from the web view using `map.setDiv()`, then attach it with `map.setDiv('map_canvas')` again if you want to keep the map instance.

The next version takes care of this process automatically, but v2.2.8(v2.2.9) has to do this manually.

----

If you wan to uninstall the maps plugin mandatory,
you can do this with below steps:

```
$> cordova platform rm android ios

$> cordova plugin rm cordova-plugin-googlrmaps -f
(try couple of times)

$> cordova plugin add cordova-plugin-googlemaps --variable ...

$> cordova platform add android ios
```

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response, I close this thread.
