### ISSUE TITLE
map.getMyLocation() has wrong number of arguments

### ISSUE THREAD

**Issue by kozuch** [mapsplugin/cordova-plugin-googlemaps#2224]
using plugin version 2.2.9

I am migrating my code from plugin v1 to current version (v2.2.9)

The example at
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getMyLocation/README.md
uses two parameters

however production version 2.2.9 (master) and even multiple_maps branch expects three parameters (+"params") and throws this:

Uncaught (in promise) TypeError: Cannot read property 'bind' of undefined
    at Map.getMyLocation (Map.js:298)
    at Map.googleMapsPluginReady (functions.js:1160)
    at Map.trigger (BaseClass.js:67)
    at waitCameraSync (Map.js:244)
    at <anonymous>

Map.getMyLocation (Map.js:298): (line 288 in multiple_maps branch):
Map.prototype.getMyLocation = function(params, success_callback, error_callback) {
...

Latest development code does not correspond to the DOCs. It is not even mentioned in v1-to-v2 migration guide.

**Comment by kozuch** [comment]
This problem was mentioned at #2218 too.

**Comment by wf9a5m75** [comment]
The `map.getMyLocation()` takes `three arguments`, but the most case `two arguments` are enough.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/LocationService.js#L9-L17

**Comment by wf9a5m75** [comment]
The issue #2218 says `Cannot read property 'bind' of undefined`. That is not the same with this.

**Comment by wf9a5m75** [comment]
I updated the document page.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getMyLocation/README.md

**Comment by kozuch** [comment]
I think #2218 is the same problem. It expects three parameters, when I only pass two, there is no ErrorCallback and it can not bind the errorcallback.

**Comment by kozuch** [comment]
Will you also update migration guide?

**Comment by wf9a5m75** [comment]
The multiple_maps branch version is different.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Map.js#L288-L290

**Comment by wf9a5m75** [comment]
>I updated the document page.
>https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getMyLocation/README.md

Did you read my comment above?

**Comment by wf9a5m75** [comment]
Do you mean this one?
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/migrate-from-v1/README.md

**Comment by kozuch** [comment]
yes

**Comment by wf9a5m75** [comment]
The v1 also accepts the same rule.

**Comment by KiengKnot** [comment]
Well, 
`getMyLocation(options?: MyLocationOptions): Promise<MyLocation>;`
I pass a param into the function, then error is gone 
But then another problem still exists, the map is not rendered TT_TT. <br>
```
this.map.getMyLocation({
      enableHighAccuracy: true
})
```
   ```
 <plugin name="cordova-plugin-googlemaps" spec="git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git">
        <variable name="API_KEY_FOR_ANDROID" value="KEY_HERE" />
        <variable name="API_KEY_FOR_IOS" value="YOUR_IOS_API_KEY_IS_HERE" />
        <variable name="PLAY_SERVICES_VERSION" value="12.0.0" />
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.0" />
    </plugin>
```
