### ISSUE TITLE
cordova Maps and cordova FCM conflict 

### ISSUE THREAD

**Issue by FarhanJohari** [mapsplugin/cordova-plugin-googlemaps#2226]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by Textras** [comment]
Pls try just a short title and putting URL in the issue comment itself. Just friendly tip.

**Comment by FarhanJohari** [comment]
Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

**Comment by wf9a5m75** [comment]
This plugin does not use `com.google.android.gms`.

Actually FCM specifies old version.

Version conflicting has to adjust by app developer. This is not a bug.

You can specify the version with `PLAY_SERVICES_VERSION` variable.
