### ISSUE TITLE
IOS - crash on marker click

### ISSUE THREAD

**Issue by tryadelion** [mapsplugin/cordova-plugin-googlemaps#2227]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [X ] **iOS**

after installing the latest version of the plugin, when i try to set the icon on marker click, this piece of code crashes with "unrecognized selector sent to instance":
FILE: Pluginmarker.m
```
  // The `anchor` property for the icon
                if ([iconProperty valueForKey:@"anchor"]) {
                  NSArray *points = [iconProperty valueForKey:@"anchor"];
                  CGFloat anchorX = [[points objectAtIndex:0] floatValue] / image.size.width;
                  CGFloat anchorY = [[points objectAtIndex:1] floatValue] / image.size.height;
                  marker.groundAnchor = CGPointMake(anchorX, anchorY);
                }
```

this is my code:

```
marker.setIcon({ url: "assets/img/selectedIcon.png", size: { width: 22, height: 32 }, origin: { x: 0, y: 0 }, anchor: { x: 11, y: 32 }});
```

i found that the root cause is that anchor is meant to be an integer array, and not an  object with XY positon like origin  on the maps native API.  this should be  standarized or better explained in the docs.

**Comment by wf9a5m75** [comment]
You need to specify correct property type as designed.

**Comment by tryadelion** [comment]
it should be added to the documentation of Marker, currently Anchor is not defined on it's docs, only size.

**Comment by wf9a5m75** [comment]
If you find something is missing in document, please send a pull request.
