### ISSUE TITLE
Error when you use bindTo method in marker

### ISSUE THREAD

**Issue by sergiomedinavalentin** [mapsplugin/cordova-plugin-googlemaps#2229]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-plugin-add-swift-support 1.7.0 "AddSwiftSupport"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-fingerprint-aio 1.3.3 "FingerprintAllInOne"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-globalization 1.0.8 "Globalization"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-qrscanner 2.5.0 "QRScanner"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.1-dev "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.1.2 "Cordova sqlite storage plugin"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
When I try to add a circle to the marker using bindto, following the example of the [documentation](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Circle/README.md#bindto-method), I get this error:
```
ReferenceError: value is not defined
    at Marker.bindTo (BaseClass.js:46)
    at callInstance (plugin.js:212)
    at Marker.<anonymous> (plugin.js:288)
    at Marker.value [as bindTo] (decorators.js:152)
    at MapComponent.<anonymous> (map.ts:473)
    at step (main.js:9575)
    at Object.next (main.js:9556)
    at fulfilled (main.js:9547)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4753)
```

**My code is this:**
```
const marker = await this.map.addMarker({
    position: { lat: position.lat, lng: position.lng },
    disableAutoPan: false,
    zIndex: 100,
    icon: {
        url: value.realTime ? 'assets/img/marker-red.png': 'assets/img/marker.png',
        size: {
            width: 32,
            height: 42
        }
    },
});

const circle = await this.map.addCircle({
    center: marker.getPosition(),
    radius: 10,
    fillColor: "rgba(0, 0, 255, 0.5)",
    strokeColor: "rgba(0, 0, 255, 0.75)",
    strokeWidth: 1
});

marker.bindTo('position', circle, 'center');
```

**Expected behavior:**
```A circle should appear along with the marker and keep the same position ```
#

**Comment by wf9a5m75** [comment]
Make sure the variable `marker` is not `undefined`

**Comment by sergiomedinavalentin** [comment]
It is not ```undefined```.

The error is in the `bindto` method of the `BaseClass` class:

`
bindTo: function(key, target, targetKey, noNotify) {
    targetKey = targetKey || key;

    // If `noNotify` is true, prevent `(targetKey)_changed` event occurrs,
    // when bind the value for the first time only.
    // (Same behaviour as Google Maps JavaScript v3)
    target.set(targetKey, value, noNotify);   <---- Value is not defined

    this.on(key + '_changed', function(oldValue, value) {
      target.set(targetKey, value);
    });
  },

`

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by wf9a5m75** [comment]
ping

**Comment by sergiomedinavalentin** [comment]
Hi, here is a repo with that problem. I hope you can reproduce it. Thank you.

[https://github.com/sergiomedinavalentin/demoApp](https://github.com/sergiomedinavalentin/demoApp)

**Comment by sergiomedinavalentin** [comment]
Ok, don´t worry

**Comment by wf9a5m75** [comment]
Ok, what's the problem?
![2229](https://user-images.githubusercontent.com/167831/39456942-efb7590c-4c9e-11e8-885f-373262b71487.gif)

**Comment by wf9a5m75** [comment]
ping

**Comment by sergiomedinavalentin** [comment]
In my case, when I run the application I get this error
![captura de pantalla 2018-05-03 09 41 27](https://user-images.githubusercontent.com/4301699/39564971-7f62bf74-4eb6-11e8-8f3d-381d6b0ff8c9.png)

![screenshot_2018-05-03-09-41-48](https://user-images.githubusercontent.com/4301699/39564976-855b9798-4eb6-11e8-8ae3-fcdd8cdf07af.png)

**Comment by wf9a5m75** [comment]
Unfortunately I can't reproduce your issue.

**Comment by wf9a5m75** [comment]
I think you use old version of `@ionic-native/core` and `@ionic-native/google-maps`.
Please reinstall the latest versions.

Since this is not this plugin's bug, no further support is available.

**Comment by sergiomedinavalentin** [comment]
That's not the problem...

`"dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/compiler-cli": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@ionic-native/core": "^4.7.0",
    "@ionic-native/google-maps": "^4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/storage": "2.1.3",
    "cordova-android": "6.4.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-googlemaps": "^2.2.9",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.2.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.10",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  }`

I have installed the latest version and the error continues

**Comment by wf9a5m75** [comment]
Um, try the multiple_maps branch version.


```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...

```

**Comment by sergiomedinavalentin** [comment]
It does not work, it does not even add the marker. I get the error `map_0_322601553499` No value for url`

**Comment by wf9a5m75** [comment]
Please share your actual project files on GitHub. Otherwise, no further help you.

**Comment by wf9a5m75** [comment]
I said `Please share your **actual project files** on GitHub.`, not demo app. Because you hide your information to me, I can not reproduce your issue.

**Time is money.** I don't waste my private time for you. You should contribute me as much as possible.

You don't agree? Please debug the issue by yourself.

**Comment by sergiomedinavalentin** [comment]
In the repo demoApp the same error occurs as in my private project, I do not hide information. I do not pretend that you spend your time on me, just that you help me solve an error that other users may have...

**Comment by wf9a5m75** [comment]
```
$ cordova plugin list
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.0-beta-201800508-1411 "cordova-plugin-googlemaps"   <-- need to update
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
![2229](https://user-images.githubusercontent.com/167831/39783565-5e0cea80-52ca-11e8-9187-0e328d94877e.gif)

**Comment by sergiomedinavalentin** [comment]
`cordova plugin list
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.0-beta-201800507-1814 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"`

![ezgif-4-0212aa0b9b](https://user-images.githubusercontent.com/4301699/39804916-adb82328-5375-11e8-87ce-67115b869513.gif)

Sony Xperia Z3 with Android 6.0.1 and Nexus 4 with Android 5.1.1. The same with Android Emulator.
As you can see, the bookmark does not appear. You get the error that I told you, `map_0_875287964653 No value for url`

**Comment by wf9a5m75** [comment]
Read my response!


```
cordova-plugin-googlemaps 2.3.0-beta-201800508-1411 "cordova-plugin-googlemaps"   <-- need to update
```
