### ISSUE TITLE
Cannot access to the 'setCameraTarget' method.

### ISSUE THREAD

**Issue by ehorodyski** [mapsplugin/cordova-plugin-googlemaps#2233]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^4.7.0",
"@ionic-native/google-maps": "^4.7.0",
```

**Current behavior:**
`setCameraTarget` throws an error. I'm trying to set the camera with multiple `ILatLng` objects, to bound the map to their locations. 

**Expected behavior:**
Should work.

**Screen capture or video record:**
![4-21-2018 1-37-43 pm](https://user-images.githubusercontent.com/6395078/39087107-f19665e2-4569-11e8-90d4-86bef0f4f6de.png)

**Related code, data or error log (please format your code or data):**

```
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { GoogleMap, GoogleMaps, GoogleMapsEvent } from "@ionic-native/google-maps";
import { IonicPage } from 'ionic-angular';
import { Store } from '../../models/store.model';
import { LocationsConstants } from './locations.constants';
import { Observable } from 'rxjs/Observable';

@IonicPage()
@Component({
  selector: 'page-locations',
  templateUrl: 'locations.html',
})
export class LocationsPage {

  public map: GoogleMap;
  public stores: Observable<Store[]>;

  constructor(
    private _http: HttpClient
  ) { }

  public ionViewDidLoad() {
    this.stores = this._http.get<Store[]>('./assets/data/stores.json');
    this.map = GoogleMaps.create('map', LocationsConstants.MapOptions);
    this.map.one(GoogleMapsEvent.MAP_READY).then(() => this.loadMap());
  }

  public loadMap() {
    this.stores.subscribe(stores => this.placeMarkers(stores));
  }

  public placeMarkers(stores: Store[]) {
    console.log((stores.map(d => d.latlng)));
    this.map.setCameraTarget(stores.map(d => d.latlng));
    for (let store of stores)
      this.map.addMarker({ position: store.latlng, ...LocationsConstants.MarkerOptions });
  }

}

```

```
[
	{
		"name": "",
		"location": "",
		"latlng": {
			"lat": 40.334564,
			"lng": -74.487639
		}
	},
	{
		"name": "",
		"location": "",
		"latlng": {
			"lat": 40.8518239,
			"lng": -74.44092739999996
		}
	}
]
```

**Comment by wf9a5m75** [comment]
```
this.placeMarkers(stores).bind(this);
```

**Comment by ehorodyski** [comment]
@wf9a5m75 placing the markers isn't the issue, it's trying to set the camera to all the points where I am placing markers. 

The idea is that I want to display the bounds of the map in accordance to where markers are placed

**Comment by ehorodyski** [comment]
@wf9a5m75 - Thanks, that's the method I am using. However, it's throwing the error I attached above.

**Comment by wf9a5m75** [comment]
How about the `map.moveCamera()`?

**Comment by ehorodyski** [comment]
I'll give it a shot when I'm back at a computer where I can debug. Thanks for the help!

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response, I close this thread.

**Comment by manuelstiven** [comment]
this error continues... anybody can help me?
