### ISSUE TITLE
HTML Info Window position incorrect when a Base64 Encoded Icon is used

### ISSUE THREAD

**Issue by chris-doco** [mapsplugin/cordova-plugin-googlemaps#2236]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
The position that the HTML info window shows when a marker is clicked is incorrect when a base64 encoded icon is used for the markers. If I use the same image, but the icon is in a folder it works fine.

By the way, this bug doesn't occur when marker clustering is used.

**Expected behavior:**
HTML Info window should show up in the correct position (right above the marker).

**Screen capture or video record:**
Using icon from folder: (no bug)
<img src="https://user-images.githubusercontent.com/36622268/39197254-0348d06a-481f-11e8-8876-0bd4c35e1a52.png" width="250">

Using base64 encoded icon: (on first click)
<img src="https://user-images.githubusercontent.com/36622268/39197284-14b51390-481f-11e8-93a7-f9f0b2e7d55e.png" width="250">

Using base64 encoded icon: (on second and subsequent clicks)
<img src="https://user-images.githubusercontent.com/36622268/39197309-2542e35e-481f-11e8-96fa-61f7ce8c48fa.png" width="250">

**Related code, data or error log (please format your code or data):**
Here is my example project showing this bug:
```
https://github.com/chris-doco/base64InfoWindow
```

**Comment by wf9a5m75** [comment]
It seems this is already fixed problem in the multiple_maps branch version.

![2236](https://user-images.githubusercontent.com/167831/39457312-e08c987c-4ca1-11e8-9a0a-7a382d614ea9.gif)

**Comment by wf9a5m75** [comment]
I confirmed this is already fixed in iOS as well.

**Comment by molinet88** [comment]
This is still an issue in v2.6.2

```
npm@6.8.0
node@10.7.0
ionic@3.20.1
cordova@9.0.0
```
