### ISSUE TITLE
addMapMarker() fails on _this.get('_overlays')

### ISSUE THREAD

**Issue by coreymcmahon** [mapsplugin/cordova-plugin-googlemaps#2240]
Hi,

Thanks for the plugin. It's worked very well for a legacy project up until recently when we needed to make some changes and upgraded Ionic/Angular and associated dependencies during the process.

After some minor fixes to the API calls to bring everything up to date with the 2.x.x version of `cordova-plugin-googlemaps` (e.g: renaming things like CAMERA_CHANGE -> CAMERA_MOVE), most of the functionality was working as expected. The one _key_ part of the plugin that is currently broken for us is _adding map markers_.

I have a suspicion there is some conflict in the dependency chain between `ionic-native/google-maps`, `cordova-plugin-googlemaps`, `cordova-plugin-googlemaps-sdk` and the underlying Cocoapods/iOS libraries, but I can't pinpoint where this is happening. After 2 days of banging my head against this I'm hoping one of the maintainers (or another library user) may be able to point me in the right direction.

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 1.10.1 "Facebook Connect"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.2 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.11.1 "PushPlugin"
```

**package.json:**

```
  "dependencies": {
    "@angular/animations": "5.2.9",
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@ionic-native/core": "4.6.0",
    "@ionic-native/date-picker": "^4.7.0",
    "@ionic-native/dialogs": "^4.7.0",
    "@ionic-native/facebook": "^4.7.0",
    "@ionic-native/geolocation": "^4.7.0",
    "@ionic-native/google-maps": "^4.6.3",
    "@ionic-native/google-plus": "^4.7.0",
    "@ionic-native/keyboard": "^4.7.0",
    "@ionic-native/native-storage": "^4.7.0",
    "@ionic-native/network": "^4.7.0",
    "@ionic-native/push": "^4.7.0",
    "@ionic-native/splash-screen": "4.6.0",
    "@ionic-native/status-bar": "4.6.0",
    "@ionic/storage": "^2.1.3",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^3.0.1",
    "cordova-android": "^6.2.3",
    "cordova-ios": "~4.5.4",
    "cordova-plugin-datepicker": "^0.9.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-facebook4": "^1.10.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-googlemaps": "^2.2.9",
    "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.6.0",
    "cordova-plugin-googleplus": "^5.3.0",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-keyboard": "^1.2.0",
    "cordova-plugin-nativestorage": "^2.3.1",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-toast": "^2.6.2",
    "ionic-angular": "^3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "^3.0.0",
    "jstz": "^2.0.0",
    "mixpanel-browser": "^2.20.0",
    "moment": "^2.22.1",
    "moment-timezone": "^0.5.16",
    "ng-elastic": "^1.0.0-beta.5",
    "phonegap-plugin-push": "^1.11.1",
    "raven-js": "^3.24.2",
    "rxjs": "5.5.8",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  }
```

**Current behavior:**

Calling `map.addMarker(options)` results in: 

```
Unhandled Promise rejection: – "undefined is not an object (evaluating '_this.get('_overlays')[overlayId_1] = overlay_1')" – "; Zone:" – "<root>" – "; Task:" – "Promise.then" – "; Value:"
```

![image](https://user-images.githubusercontent.com/700486/39245526-3ea504fe-48be-11e8-943b-b36837a32cb4.png)

The promise is not resolved and an exception is thrown deep within the bowels of the cordova plugin. Here is the failing line (1928):

![image](https://user-images.githubusercontent.com/700486/39245843-0d64e836-48bf-11e8-863c-93e2960a3bad.png)

**Expected behavior:**

The expected behaviour is that the marker is added to the map (this is working) and the promise resolves with a reference to the added marker (this is _not_ working).

**Screen capture or video record:**

http://g.recordit.co/Ge3WMwT5JS.gif

**Related code, data or error log (please format your code or data):**

![image](https://user-images.githubusercontent.com/700486/39245779-db07de5c-48be-11e8-8123-d2aadf41f714.png)

** Ionic info**

```
ionic info

cli packages: (/Users/coreymcmahon/Sites/foodkit/consumer-app/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v6.11.2
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/coreymcmahon/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by coreymcmahon** [comment]
Also noticed these:

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1852
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1853

Unfortunately downgrading to @ionic-native/google-maps @ 4.2.1 (as suggested in the tickets above) causes the map to fail to load:

![image](https://user-images.githubusercontent.com/700486/39248793-3826a034-48c7-11e8-9976-0a2e61fba10f.png)

![image](https://user-images.githubusercontent.com/700486/39248808-45876c22-48c7-11e8-920c-493f8b3fa008.png)

**Comment by wf9a5m75** [comment]
I guess you create the map instance with `new GoogleMap()`.
You need to use `GoogleMaps.create('map_canvas')`

**Comment by coreymcmahon** [comment]
Thanks for the feedback @wf9a5m75 

This seems to have fixed the issue.

`new GoogleMap()` was previously working but I guess there's been some change in the API. After changing it to `GoogleMaps.create('map_canvas')` we no longer get the error message.

Thanks again for your help

**Comment by kunalgrover05** [comment]
Faced the same issue and this resolution worked. Adding the exact error message for someone who might stumble upon this issue:
```
TypeError: Cannot set property 'marker_XXXXXXXXXXX' of undefined
```
