### ISSUE TITLE
App crashes when LastLocation is not known on Android

### ISSUE THREAD

**Issue by TheDuc** [mapsplugin/cordova-plugin-googlemaps#2242]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 3.1.1 "NativeGeocoder"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

```
Attempt to invoke virtual method 'long android.location.Location.getTime()' on a null object reference
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
ionic-native/core 4.7.0
ionic-native/google-maps 4.7.0

**Current behavior:**
when using LocationService.getMyLocation(), the app crashes when getLastLocation returns null

**Expected behavior:**
To not crash

See also https://stackoverflow.com/questions/32290045/error-invoke-virtual-method-double-android-location-location-getlatitude-on/32291415

**Comment by wf9a5m75** [comment]
Did you test the `2.3.0-rc1`?

**Comment by TheDuc** [comment]
I have created a pull request that implements this check #2245

**Comment by wf9a5m75** [comment]
Thank you for your contribution.
