### ISSUE TITLE
Unable to move around the map and screen tearing

### ISSUE THREAD

**Issue by dfibuch** [mapsplugin/cordova-plugin-googlemaps#2243]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
branch-cordova-sdk 2.6.24 "branch-cordova-sdk"
cordova-background-geolocation 2.9.1 "BackgroundGeolocation"
cordova-plugin-android-permissions 0.8.0 "Permissions"
cordova-plugin-apprate 1.3.0 "AppRate"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-hockeyapp 2.2.4 "HockeyApp"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-inapppurchase 1.0.0 "In App Purchase"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.2.0 "Whitelist"
cordova-plugin-x-toast 2.6.2 "Toast"
cordova-sqlite-storage 0.8.2 "Cordova sqlite storage plugin (core version)"
cordova-uxcam 2.3.7 "UXCam"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.3.3 "OneSignal Push Notifications"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

Have `@ionic-native/core` installed, version 4.7.0

**Current behavior:**

Context: 

We've been using this plugin since before v2 on the multiple_maps branch, so all the migration stuff is already done and we are using the new methods. There aren't any JS errors in console. I have upgraded to the `master` branch so that we can benefit from a load of fixes that have been done since instead of trying to cherry pick them.

So the code that creates the map, etc is still the same as it was originally and working with `multiple_maps` branch.

I am still trying to get this setup on iOS so I can check if its a problem on there too and I will update this bug report once I can get it all running.

Problem: 

Not able to move the map by touching the screen and moving my finger.
The map moves with `map.moveCamera` but when it does there is a weird "screen tearing" where it squishes the whole map for a second and then refits it to the screen.

**Expected behavior:**

Should be able to move the map and should not see the weird screen tearing

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by dfibuch** [comment]
Thanks for your response. Unfortunately I can't do that, its a company product and the repo is private. I can share bits of code that initialise the map, etc if that helps. 

I know this is a weird one, I might try updating to the the `multiple_maps` branch but not sure if that will help.

I'm assuming nothing has changed how the `html` is structured, as we do have elements over the map like buttons, etc.

**Comment by dfibuch** [comment]
Further to my initial report, I can confirm this works without problems on iOS. I can move the map, no screen tearing and it actually fixes the issue I was hoping it would fix, which is quite an old one where the plugin would make the bottom tabs not clickable in certain parts of the buttons.

So its just a case of figuring out why Android is having this issue.

**Comment by dfibuch** [comment]
Don't think it works like that, especially as I am giving you my latest findings on the issue. I'm not going to hand over our company's IP to fix a bug. If you don't have any idea of what the problem might be then no worries, I'll figure it out myself. If you have a thought as to what it could be then please share so I can figure out the problem.

**Comment by wf9a5m75** [comment]
Please let me know if you figure out anything. Until you share the project files that reproduce your issue 100%, I can't help anything.

**Comment by dfibuch** [comment]
Right, I did some more testing today using a new basic test app (that I can share the project with you if you want) and it looks like its only an issue on the LG Nexus 5 running Android 6.0.1. Tried on a Samsung and a Nexus 6 and its working fine.

So dont know if its related specifically to the device (like actually my phone) or all Nexus 5s or the web view that phone is running.

Do you have a Nexus 5 you can try this on? I'm happy to leave this seeing as its not reproducible across all devices but if you want to try figure it out I can assist.
