### ISSUE TITLE
Dont load maps on Lenovo using 3g

### ISSUE THREAD

**Issue by tuliogoiania** [mapsplugin/cordova-plugin-googlemaps#2244]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

Good afternoon,

Something very strange, occurs in the "Android 7" Manufacturer "Lenovo" model: Lenovo vibe K6.

When we first started using the internet for 3g, it did not load the map. He blinks but does not open.

Then if we start it using Wifi, it loads, and the next time it already runs the map by 3g normally.

All permissions / accesses are released, would you have any suggestions?

https://streamable.com/8ukjv (link video) 

Thank you very much.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md

**Comment by tuliogoiania** [comment]
Thanks for the answer,

I read the document you sent, but my map works normally, it just does not work in that case (3G (Only the first time) and this model of cell phone).

Have you seen anything like this happen?

**Comment by wf9a5m75** [comment]
Which device is work, or which device does not work is not plugin support cover area. Because it is the problem of the device and Google Maps Android API.
If it does not work on your device, just give it up.
