### ISSUE TITLE
Colored markers are not working in 2.3 rc

### ISSUE THREAD

**Issue by piernik** [mapsplugin/cordova-plugin-googlemaps#2246]
I'm using `2.3`.  Setting marker's icon to ex. `blue` (https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Marker/README.md#color-icon) is not working.I always get red.

**Comment by makers-mark** [comment]
Hi @piernik , I noticed the same thing a couple weeks ago. I have tried to understand what has happened to cause this, but I cannot. @wf9a5m75 I can confirm that [this commit](https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/3a3e207b097fd5a3ba26ed9d6058e22e1becc9ba) is when the icon color stopped working. I have tried to figure it out, but quite a lot changed in this commit. And I have no where near the skills that you have.

**Comment by wf9a5m75** [comment]
<img src=https://user-images.githubusercontent.com/167831/39457999-6083ad32-4ca6-11e8-94cd-71342c8f32bd.png" width="250">

**Comment by wf9a5m75** [comment]
Please reinstall the maps plugin from the multiple_maps branch.

**Comment by makers-mark** [comment]
Thank you @wf9a5m75, confirmed.

**Comment by piernik** [comment]
How to install from specific branch?
Tried:
`ionic cordova plugin add cordova-plugin-googlemaps@multiple_maps --variable API_KEY_FOR_ANDROID=""`
`ionic cordova plugin add cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID=""`

I'm on windows.
