### ISSUE TITLE
geocoder 

### ISSUE THREAD

**Issue by ameniGa** [mapsplugin/cordova-plugin-googlemaps#2247]
When i use Geocoder with BaseArrayClass i get this error "utils is not defined" at Object.geocode (file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/Geocoder.js:75:27)
can you help me

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Geocoder/geocoding/README.md#multiple-locations

**Comment by wf9a5m75** [comment]
This is already fixed issue in the multiple_maps branch.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Geocoder.js#L6

Please reinstall the maps plugin from the multiple_maps branch.

**Comment by ameniGa** [comment]
hey,
Sorry but i can't reinstall the plugin from  multiple_maps branch , i get
this error "Error: Registry returned 404 for GET on
https://registry.npmjs.org/"


2018-05-01 2:45 GMT+01:00 Masashi Katsumata <notifications@github.com>:
