### ISSUE TITLE
Help understanding fix to a bug

### ISSUE THREAD

**Issue by dfibuch** [mapsplugin/cordova-plugin-googlemaps#2248]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

This isn't a bug report, as the bug has already been fixed in the newer version of the plugin, but I do have a question regarding the fix for #1919 as to what the actual problem was. I am trying to fix this "bottom menu bar" clicking issue in our fork.

I did try to upgrade to the latest version, as you will recall I had the issue where I couldn't move the map on Android and it turned out to be a problem with a single device. After I got it running, the huge jump from version 2 to 2.2.9 has created a lot of problems with actually using the plugin, so for now we just want to try fix this "bottom menu bar".

I understand if you don't have time or don't want to help with this, seeing as it is fixed in the current code. I looked the patch that was applied for #1919 but the code it's replacing doesn't even exist in my version of the file so I've tried going through the changes through the commits but still can't fix it, so am turning here for help.

**Comment by wf9a5m75** [comment]
I don't remember the details. It seems touch positioning problem.

Since the `cordova-plugin-statusbar` inserts their own view above the uiwebview, the webview is shifted down 20px or 40px.
In this commit https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/d41f4362df341161a5119a46b6d979e9c2aa2e3b, the plugin calculates the touch position based on the top (y) position of the uiwebview.

**Comment by dfibuch** [comment]
Ah yes, I'm on the right path then. I thought that's what it did. My version of the file is currently on this commit https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/96dae7f5de778ea0b33f0acbb46debf6a1268f61 which is really old compared to the commit you posted above and I tried to replace the `hitTest` code and added `findClickedDom` method but I think it's still missing something.

I don't expect you to know but do you think that what I did should have worked? Or maybe the code that calls `hitTest` needs updating also but has been done previously and is not in this commit?

**Comment by dfibuch** [comment]
When I debug the code and see what is going on with `hitTest` it keeps hitting the `break` in this `if` statement, even if I do it on the map and it doesn't let me scroll (because it keeps hitting the `break`) https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/d41f4362df341161a5119a46b6d979e9c2aa2e3b/src/ios/GoogleMaps/MyPluginLayer.m#L345-L350

So I'm thinking the `subviews` array is not getting the right data, but I don't know where that's populated.

**Comment by dfibuch** [comment]
I managed to get it to work! :D I'll check the code into my fork and show you if you're interested and maybe you can tell me if it's a stupid way of doing it.

**Comment by wf9a5m75** [comment]
Congrats. Well, I think my code and your forked code have many different.

Regarding of this code, this code is for detecting touches for other plugins that are insert own views.
Without using those plugin, always hit `break`.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/d41f4362df341161a5119a46b6d979e9c2aa2e3b/src/ios/GoogleMaps/MyPluginLayer.m#L332-L351

I focus on next things, this is already fixed issue in this repo.
So I'm not interested in so much.
But congratulation anyway, and thank you for keeping interested in this plugin.

**Comment by dfibuch** [comment]
Thank you for your help in this, I'm happy to close and move on. It was indeed this code that fixed the problem but I had to adjust it slightly to detect when the user is actually on the map and then hit `break`, otherwise if not on the map `return hit`

**Comment by gregavola** [comment]
@dfibuch We are experiencing the same issue here - how can we resolve it? Has this fix been merged with master?

**Comment by dfibuch** [comment]
@gregavola It depends if you are version locked or not because the issue is fixed in both `multiple_maps` and `master`. I believe #1919 is what fixes it so if its in your branch then it will be.

We have been modifying some code in our fork so couldn't update to it and I fixed it manually. I can share the fix with you if you need it but its best to take it from the owner of the repo (mine is a hack really).
