### ISSUE TITLE
Map not load, white-screen only

### ISSUE THREAD

**Issue by naitikpatel1990** [mapsplugin/cordova-plugin-googlemaps#2250]
**I'm submitting a ...**  
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:** 
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
```

**Current behavior:**
Plugin version 2.2.9 has not allow me to load map in HTML DOM. Initially it throwing error "Uncaught (in promise) TypeError: Cannot read property 'size' of undefined" Please see attached file for it
<img width="1095" alt="screen shot 2018-05-03 at 12 58 08 am" src="https://user-images.githubusercontent.com/4089997/39544971-58d3cb9e-4e6d-11e8-89e3-08ad53060685.png">

I did simple following in code:

HTML:  
```
<div id="googlemap">
```

JS:
```
var div = document.getElementById("googlemap");
 map = plugin.google.maps.Map.getMap(div);
```

**Comment by wf9a5m75** [comment]
`console.log(div) == null`

**Comment by naitikpatel1990** [comment]
And where should I add it?

**Comment by wf9a5m75** [comment]
Wow, unexpected question.

Insert `console.log(div)` after the `var div= document.getElementById("googlemap");`, then confirm the div is `null` or `not null`.
(I guess `null`)

**Comment by wf9a5m75** [comment]
If you can't solve the problem by yourself, please share your project files on github.

**Comment by naitikpatel1990** [comment]
Hi, Thanks for your reply.

But i did debugg and checked that "DIV" should be not null or undefined or empty. But still getting error in "CordovaGoogleMaps.js" file. Please check my attached screenshot for all info and console for check value.

<img width="1230" alt="screen shot 2018-05-03 at 10 21 38 am" src="https://user-images.githubusercontent.com/4089997/39560505-229ba8a4-4ebc-11e8-88c2-0569c6194b62.png">


One more thing i noticed my elemid is not showing in ``` self.domPositions[elemId]; ``` so it throwing undefined.

**Comment by wf9a5m75** [comment]
As I said, if you can't solve the problem by yourself, please share your project files on github.

**Comment by naitikpatel1990** [comment]
Hi,

Sharing you github link: https://github.com/naitikpatel1990/GoogleMapTest/tree/master

Which have whitescreen issue on map. Thanks for your help in advance.

**Comment by wf9a5m75** [comment]
Thanks, I briefly checked your code, but wherr do you define the size (demention) of the map div? There is no definition in index.css and style.css files.

**Comment by wf9a5m75** [comment]
Since the map div does not css size specification, the map div is `100% x 0px`.

The maps plugin doea not generate a map such a case.

**Comment by naitikpatel1990** [comment]
I did size for map div like:

```
<div id="googlemap" style="height:500px;width:500px"></div>
```

Still giving me white screen. Can you tell me what i need to set in style so at least map can be visible ?

**Comment by wf9a5m75** [comment]
I'm extremely busy these days.

**Comment by naitikpatel1990** [comment]
Ok, I am waiting here. Whenever you have time please revert back. Of course other plugin user also faced same issue. So it's good to solve it. Thank you.

Meanwhile I will also try to solve it.

Please keep this thread open.

**Comment by wf9a5m75** [comment]
Did you try very simple example code?
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#quick-demo

When you face any problem, you should solve the issue by your self as much as possible.
At this time, you should start with very simple code, then inspect your code one by one.

Please do your best before asking.

**Comment by naitikpatel1990** [comment]
I did mke it work with map version 2.2.8 so I ask this question because I thought I miss something in 2.2.9 version to be configured.

Anyways will try simple example which you suggest and revert you.

**Comment by naitikpatel1990** [comment]
Yes. Map is loading after add some CSS in map container. 

Thank you man for your valuable input.

**Comment by mmzc1011** [comment]
i got the same issue, 
i had been tried the code from :
[https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/hello-world/README.md](url)
on browser is ok, but i got only logo google without map
