### ISSUE TITLE
Plugin behaviour related questions

### ISSUE THREAD

**Issue by rosbal** [mapsplugin/cordova-plugin-googlemaps#2251]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
Ionic information provided - Includes cordova plugin info
```
"dependencies": {
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/device": "^4.5.3",
    "@ionic-native/diagnostic": "^4.5.3",
    "@ionic-native/file": "^4.5.3",
    "@ionic-native/geolocation": "^4.5.3",
    "@ionic-native/google-maps": "^4.5.3",
    "@ionic-native/in-app-browser": "^4.5.3",
    "@ionic-native/intel-security": "^4.5.3",
    "@ionic-native/location-accuracy": "^4.5.3",
    "@ionic-native/network": "^4.5.3",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/sqlite": "^4.5.3",
    "@ionic-native/status-bar": "^4.4.0",
    "@ionic/storage": "2.1.3",
    "com-intel-security-cordova-plugin": "^2.0.3",
    "copyfiles": "^2.0.0",
    "cordova-android": "^6.4.0",
    "cordova-plugin-device": "^2.0.1",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-googlemaps": "^2.1.1",
    "cordova-plugin-inappbrowser": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-request-location-accuracy": "^2.2.2",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlcipher-adapter": "^0.1.12-rc2",
    "cordova.plugins.diagnostic": "^3.9.2",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.8",
    "typescript": "2.4.2"
  }
```

**Current behaviour:**
I have a couple of questions related to the maps plugin:
1. In case a pause event is received during the app launch (for instance a phone call was received), will the plugin continue to load after receiving the resume event. What will happen if pause is received at the time the plugin is trying to fetch the google maps library? Is there a way to recover from this?

2. In poor data connections (GPRS, EDGE), if the plugin cannot load the Google maps library is there a way to reload the plugin when better network is available without having to load the page?

**Comment by wf9a5m75** [comment]
1. If the maps plugin receives the pause event, the maps plugin pauses the native maps views. If the maps plugin receives th resume event, the maps plugin resumes thr native map views.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/CordovaGoogleMaps.java#L490:L512


2. Behavior of the maps views behavior in poor connection is not the maps plugin control. This plugin is just a wrapper, it means bridge between JS and native code. The maps plugin does not control the maps view behavior.

**Comment by rosbal** [comment]
Thank you for your response.
