### ISSUE TITLE
Error loading plugin on some devices (Huawei P8 for example), Symbol.for undefined

### ISSUE THREAD

**Issue by gvillafanetapia** [mapsplugin/cordova-plugin-googlemaps#2254]
**I'm submitting a ...**  
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:** 
- [x] **Android**
- [ ] **iOS**

**cordova information:** 

```
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 4.0.1-dev "Splashscreen"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-sqlite-storage 1.5.0 "Cordova sqlite storage plugin"
```

**Current behavior:**
When cordova is loading plugins it fails with message: 
```
TypeError: undefined is not a function
```
Therefore device ready never fires.

**Expected behavior:**
Cordova loads plugins and fires device ready,

**Related code, data or error log (please format your code or data):**

Managed to narrow down the exception to line 1 and 2 of www/BaseClass.js and line 4 of www/BaseArrayClass.js
```
var VARS_FIELD = typeof Symbol === 'undefined' ? '__vars' + Date.now() : Symbol.for('vars');
```
Seems that although Symbol is defined, Symbol.for is not.
Replacing - typeof Symbol === 'undefined' - for - typeof Symbol === 'undefined' || typeof Symbol.for === 'undefined' - fixes the problem.

In www/BaseClass.js line 1 and 2:
```
var VARS_FIELD = typeof Symbol === 'undefined' || typeof Symbol.for === 'undefined' ? '__vars' + Date.now() : Symbol.for('vars');
var SUBSCRIPTIONS_FIELD = typeof Symbol === 'undefined' || typeof Symbol.for === 'undefined' ? '__subs' + Date.now() : Symbol.for('subscriptions');
```

In www/BaseArrayClass.js line 5:
```
var ARRAY_FIELD = typeof Symbol === 'undefined' || typeof Symbol.for === 'undefined' ? '__array' + Date.now() : Symbol.for('array');
```

**Comment by wf9a5m75** [comment]
The next version use `Symbol` instead of `Symbol.for`.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/BaseClass.js

Please reinstall the plugin from the multiple_maps branch.

**Comment by gvillafanetapia** [comment]
Hello again. I noticed that in the last version the error is still present in BaseArrayClass.
Not sure if its blocking like it was when the bug was present in BaseClass but it would be good to fix it also.

Thank you!
