### ISSUE TITLE
Cannot access to the 'setPosition' method.

### ISSUE THREAD

**Issue by pablogarciamiranda** [mapsplugin/cordova-plugin-googlemaps#2256]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-firebase 0.1.24 "Google Firebase Plugin"
cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.3.3 "OneSignal Push Notifications"
phonegap-nfc 0.7.1 "NFC"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

"ionic-native/core": "4.5.3",
"ionic-native/google-maps": "4.6.1",

**Current behavior:**
I am trying to update a marker when a Subscription fires and gets the new position of the marker, but the method setPosition says that it cannot be accessed.

**Expected behavior:**
I would like to update the marker as the Subscription fires.

I have another project where the marker position updates correctly and I can't see any relevant differences.

 I have pasted that code from the other project in this one and the marker neither does not update its position.

I also have checked the versions of the plugins and they are the same. I really don't know what's happening.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
This code would be enough to reproduce it.

@Component({
  selector: 'page-trip',
  templateUrl: 'trip.html'
})
export class TripPage implements OnInit, OnDestroy {
  map: GoogleMap;
  trip: Trip;
  markerBus: any;

loadMap() {
    let markers = this.createStopMarkers(this.trip.route.stops.slice(1, this.trip.route.stops.length));
    let busMarker = this.createBusMarker(this.trip.coordinates);
    let polyline = this.createPolyLineCoordinates(this.trip.route.encodedPath);
    let bounds = this.createBoundsFromStops(markers);
    let mapOptions: GoogleMapOptions = {
      camera: {
        target: bounds,
        zoom: 18,
        tilt: 30
      },
      styles: this.mapStyles
    };
    this.map = GoogleMaps.create('map_canvas', mapOptions);

    // Wait the MAP_READY before using any methods.
    this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => {
        this.addMarkersToMap(markers);
        this.addBusMarkerToMaps(busMarker);
        this.addPolylineToMap(polyline);
        this.fitMapToBounds(bounds);
        this.map.setCompassEnabled(false);
        this.onUpdateTrip();
      });
  }

 addBusMarkerToMaps(marker) {
    this.map.addMarker({
      position: marker.position,
      icon: marker.icon
    })
      .then((marker: Marker) => {
        this.markerBus = marker
        this.onUpdateMapView();
        marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe((params) => {
          let marker: Marker = params[1];
          marker.setTitle(marker.get("name"));
          marker.setSnippet(marker.get("address"));
          marker.showInfoWindow();
        });
      });
  }

onUpdateMapView() {
    this.tripsService.updatedBounds().subscribe(newPositionBounds => {
      this.markerBus.setPosition(newPositionBounds);
    })
  }
}
```

**Comment by wf9a5m75** [comment]
You should update these plugins to latest versions.
```
"ionic-native/core": "4.5.3",
"ionic-native/google-maps": "4.6.1",
```

**Comment by pablogarciamiranda** [comment]
I have updated to:

ionic-native/core: "^4.7.0",
ionic-native/google-maps: "^4.7.0"

And still does not work

**Comment by pablogarciamiranda** [comment]
Ok, I solved it. 
I was not passing a LatLng object to the position of the bus. So doing it in the following way solved my issue:

```
let position = new LatLng(newPositionBounds.latitude, newPositionBounds.longitude);
this.markerBus.setPosition(position);
```
