### ISSUE TITLE
"Map Ready" event is not firing if the height of the div wrapper is minor or equal then 200px

### ISSUE THREAD

**Issue by LabDeve** [mapsplugin/cordova-plugin-googlemaps#2259]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.2.7 "cordova-plugin-googlemaps"
cordova-plugin-mauron85-background-geolocation 2.3.2 "CDVBackgroundGeolocation"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
`"@ionic-native/core": "4.6.0",`
`"@ionic-native/google-maps": "4.6.0"`

**Current behavior:**
Using a div with height minor or equal then 200px

**Expected behavior:**
"Map Ready" event should fire

**Comment by wf9a5m75** [comment]
Create large map than 200px.

**Comment by wf9a5m75** [comment]
I believe smaller dimension map is necessary with this plugin. Use Google Maps JavaScript v3.

**Comment by LabDeve** [comment]
Kk. Can you add this information in the docs of this plugin?
