### ISSUE TITLE
Error compiling on Android

### ISSUE THREAD

**Issue by albertleao** [mapsplugin/cordova-plugin-googlemaps#2261]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
Error: /Users/myuser/Documents/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/myuser/Documents/app/platforms/android/src/plugin/google/maps/PluginPolyline.java:39: error: cannot access zzbgl
        polylineOptions.add(path.get(i));
                       ^
  class file for com.google.android.gms.internal.zzbgl not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

**Current behavior:**
Can't build on android

**Comment by wf9a5m75** [comment]
The Google Play Services you installed is too old.

**Comment by wf9a5m75** [comment]
I can't understand what you are talking about.
If you specify latest version, Gradle downloads it automatically.

Anyway, this plugin does not work with 49 anymore.

**Comment by wf9a5m75** [comment]
https://github.com/ionic-team/ionic-native-google-maps/issues/5#issuecomment-380693358

**Comment by wf9a5m75** [comment]
Please (x1000) search past issues. I answered similar question, but I replied the same answers many times in the past.

**Comment by albertleao** [comment]
Alright sounds good
