### ISSUE TITLE
High cpu usage when scrolling elements with touch events

### ISSUE THREAD

**Issue by aMUSiC** [mapsplugin/cordova-plugin-googlemaps#2264]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [X] **iOS**

**Current behavior:**

The issue is introduced with commit https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/2202439e1495c9811d5f6aca8529853202ab6de9 (probably the removal of "if (evt && evt.type === "scroll") {" in googlemaps-cdv-plugin.js but I could be wrong)

I am using a slide carousel which is rendered over the map (swiper http://idangero.us/swiper/ ). Before that commit swiping between slides was smooth and immediately responsive, but after that commit, swiping between slides can take up to 10 seconds (!) indicating very high cpu usage during the touch events. While the transition is trying to complete, all other HTML/JS is unresponsive on the page, however the map continues to be responsive.

**Expected behavior:**

Touch event sliding should be smooth

I haven't provided a project demonstrating this as it would take me some time to build, but I will provide one if needed.

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by wf9a5m75** [comment]
If you aren't satisfied with this plugin, your choices are : 
- 1. create a pull request with enough data
- 2. stay on the old commit
- 3. give up to display DOM on map, 
- 4. or stop using this plugin, and use other map library.

**Comment by aMUSiC** [comment]
Ok I will, but please be patient as it will require some time. Thank you

**Comment by aMUSiC** [comment]
I updated the gmapbugs project

https://github.com/aMUSiC/gmapbugs

I added an ion-slider at the bottom of the map with 3 slides. Each slide has a background image, and 100 small rectangular divs with 0.5 opacity in it ( in order to exaggerate the issue).

The commit of the plugin used is this: https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/2202439e1495c9811d5f6aca8529853202ab6de9 in which the problem has started.

If you try to swipe between the slides, you'll notice that when the transition is about to start the html layout will freeze. In my device (Samsung J5) the freeze takes about 2.5 to 3 seconds, and after that the transition to the next slide will complete normally. If I remove the 100 divs in the slides, then the freeze takes about 0.5 to 1 second.

With the immediately previous commit https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/76cfaee30f37f1f9ffc56d8dd91510083ef80c74 it will still freeze, but only for 0.5 seconds in my device.  If I remove the 100 divs in the slides, there is no freeze.

During the freeze, the map is still responsive. It's just the html layout that freezes.

In my production project, I have a similar setup to this project where the slides have text, and nested virtual swipers and the freeze is much more prominent (up to 10 seconds or more) on the J5. On the iPhoneX the freeze last much less, but it's still very noticeable.

**Comment by wf9a5m75** [comment]
Why don't you create another page and display the slides inside it?

I don't recommend display a lot of elements over the map.

**Comment by aMUSiC** [comment]
Because that is what the project I'm working on requires, so I have to display these over the map.

However, as I stated, the freeze was minimal before the https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/2202439e1495c9811d5f6aca8529853202ab6de9 and as I'm demonstrating in the project, the freeze happens even if I just draw the three slides with nothing but a background image in them.

I suspect that this happens due to the plugin's scan of the dom during transitions to update the touchable/visible areas of the map.

Which leads to a question: Will the map scan elements that are displayed in the same page as the map, but outside the map?

**Comment by wf9a5m75** [comment]
During `transition`,the plugin checks only map position.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/googlemaps-cdv-plugin.js#L54-L89

It doesn't matter your requirement or not, this plugin uses native map view, it is not HTML DOM element.
You need to choose which one is high priority, `design` or `map functionality`.

**Comment by aMUSiC** [comment]
In src/pages/home/home.ts line 43, change 100 to 0, so that there are no dom elements inside the slides at all, and run it again. You'll see that there's again a freeze on transition start (though it freezes only for about 500ms instead of 2500ms).

**Comment by wf9a5m75** [comment]
I think this is normal.
![2264](https://user-images.githubusercontent.com/167831/40073125-d61c27ba-582a-11e8-929f-8a6f04fcf51c.gif)

**Comment by aMUSiC** [comment]
What device is this on?

**Comment by wf9a5m75** [comment]
Nexus 5x

**Comment by aMUSiC** [comment]
This is on the Samsung J5

![ezgif-4-0fa34f4a24](https://user-images.githubusercontent.com/5752982/40074098-6a79ab66-5881-11e8-82c8-309063f77c25.gif)

**Comment by aMUSiC** [comment]
Resize it into what? If you mean the height so that the ion-slider is not rendered on top of the map, there's no difference in performance. I tried that already. It still freezes.

**Comment by wf9a5m75** [comment]
I mean resize the map div.

**Comment by aMUSiC** [comment]
that's what I tried. I resized the map div to 50% height. No difference

**Comment by wf9a5m75** [comment]
Ok, try this commit https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/d783ff0d95b802250ac57c5c86cc09a0447bc706

**Comment by wf9a5m75** [comment]
Regarding of `LocationService.getMyLocation()` has been already fixed after this patch. Please reinstall the plugin from the multiple_maps branch.

**Comment by aMUSiC** [comment]
I have updated the sample project here https://github.com/aMUSiC/gmapbugs to also include the overlay demonstrating the regression issue.

As much as I would like to share my real project files, I'm afraid it's not possible as they are not on github (it is being privately maintained on bitbucket), and I do not have a github subscription, so I cannot host private repositories.

**Comment by wf9a5m75** [comment]
Well, bitbucket is fine. I don't mind which one.

**Comment by wf9a5m75** [comment]
Try the latest commit of the multiple_maps branch.
![2264_compress](https://user-images.githubusercontent.com/167831/40148218-c84d1f48-5921-11e8-9cdf-4f942ab2fd6d.gif)

**Comment by aMUSiC** [comment]
I can confirm that the touch bleed is now fixed again, and the performance is still fast. Both on the sample project and on my production project. Thank you very much Masahi.

**Comment by wf9a5m75** [comment]
I'm really stressful you do one by one. You should reproduce the same as your actual project. You waste my private time. And **Time is money**.

**Comment by wf9a5m75** [comment]
Fixed. 
![2264_compress](https://user-images.githubusercontent.com/167831/40192793-3f136978-59ba-11e8-8bcb-4a0ad37c63cf.gif)
