### ISSUE TITLE
Cordova FCM and Google Maps conflict 

### ISSUE THREAD

**Issue by smxdevst** [mapsplugin/cordova-plugin-googlemaps#2265]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
com.synconset.imagepicker 2.1.10 "ImagePicker"
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.0 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.6 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"
```
package.json
```
"@ionic-native/core": "^4.7.0",
"cordova-plugin-googlemaps": "^2.3.0"
```

There is a conflict between cordova-plugin-fcm 2.1.2. It requires google-services 11.4.2 and minimum of this version is 12.0.1. How can I resolve it? 

I have tried to use lower version of google maps but it doesn't support cordova-android@7.0.0

**Comment by wf9a5m75** [comment]
> There is a conflict between cordova-plugin-fcm 2.1.2. It requires google-services 11.4.2 and minimum of this version is 12.0.1. How can I resolve it?

You need to specify all the same versions.

**Comment by wf9a5m75** [comment]
https://github.com/ionic-team/ionic-native-google-maps/issues/5#issuecomment-380693358

**Comment by wf9a5m75** [comment]
By the way, please use `v2.3.1` instead of `v2.3.0`

**Comment by smxdevst** [comment]
I can't specify all to 12.0.1 because cordova-plugin-fcm supports only up to 11.4.2 an no one maintaining this plugin. Is there any way for this plugin support this version by disabling some of 12.0.1 and up functionality?

**Comment by wf9a5m75** [comment]
nop.
