### ISSUE TITLE
Cordova push plugin & Google maps plugin conflict

### ISSUE THREAD

**Issue by balaji503** [mapsplugin/cordova-plugin-googlemaps#2266]
cordova plugin push 2.1.2 and firebase version 11.4.2 conflicts with cordova-plugin-googlemaps@2.1.1

cordova 8.0
cordova ios 4.5.4 
cocoapods 1.1.1
xcode 8.3

is this a bug ?

**Comment by wf9a5m75** [comment]
Conflicting is your mistake.

And I don't support for old version `cordova-plugin-googlemaps@2.1.1`

You need to install the latest version with latest Xcode.
