### ISSUE TITLE
Version 2.1.1 worked fine on Xcode 8 but now fails!

### ISSUE THREAD

**Issue by prasad83** [mapsplugin/cordova-plugin-googlemaps#2267]
My production build was working perfect with version 2.1.1 and Xcode 8 but 
it started to throw up build error all of a sudden.

Digging deeper found the root-cause due to the plugin.xml of 2.1.1 
points to https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git 
which demands Xcode 9 (see [changenote](https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk/commit/961fe9a6a1caaf116bc3e8fbc36e12094b9ae21c))

This dependency should have been:
dependency id="com.googlemaps.ios" url="https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.6.0"

It seem to be taken care in 2.3.1 - is it possible to update other releases as well.

**Comment by wf9a5m75** [comment]
You need to update Xcode 10. No longer support xcode8
