### ISSUE TITLE
How can I know if a marker is contained within a circle?

### ISSUE THREAD

**Issue by YeisonVelez11** [mapsplugin/cordova-plugin-googlemaps#2268]

**Comment by wf9a5m75** [comment]
This is just mathematic in junior high school.

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2211#issuecomment-380546469

**Comment by YeisonVelez11** [comment]
Excuse my ignorance, but it has not been clear to me. could you help me please? How should that piece of code be?

` 
var circleArea=circle.getBounds();
circleArea.contains({lat:xxx, lng:xxx})  //coordinates to evaluate if is inside of the circle..
//circle.getCenter() and marker.getPosition(). ???
`

**Comment by YeisonVelez11** [comment]
@wf9a5m75  I think it's a disrespectful comment. I'm asking you with much respect. We do not all understand and we have the same knowledge as you. and I bet you that if I had your knowledge I would not be arrogant. for your information I am new to this topic of google maps, I have little experience programming and I do not understand very well what I should do. If it makes you feel good, I am what you want to believe it to be, but it is not my fault that I do not understand you. and yes, I read your answer but I'm not sure what I should do.

**Comment by wf9a5m75** [comment]
Did you resolve your question?

**Comment by YeisonVelez11** [comment]
Thanks, I think I have it.

**Comment by YeisonVelez11** [comment]
I apologize for the problems, and misunderstandings. I am very bad with maths I must admit it.

**Comment by wf9a5m75** [comment]
Enjoy the maps plugin.
