### ISSUE TITLE
Minimum container dimention is 100x100 in pixels.

### ISSUE THREAD

**Issue by nilsk123** [mapsplugin/cordova-plugin-googlemaps#2269]
This constraint wasn't there before (right?) and stops us from using this plugin. What was the latest version without this constraint? don't see it in the changelog.

**Comment by wf9a5m75** [comment]
Minimum dimension is 100x100. That's all.

**Comment by tennist** [comment]
I am also getting this same error even though my container is much larger than 100x100.  Everything was working fine in previous versions.

**Comment by tusharnetset** [comment]
I am also getting this same error [GoogleMaps] Minimum container dimention is 100x100 in pixels.

**Comment by tennist** [comment]
@tusharnetset I found out that my div for the map wasn't completely loaded yet when I was trying to initialize my map.  I placed a 250ms delay around my map initialization code and everything works OK now.

**Comment by mariocalin** [comment]
I am getting the error too. My container is 360x512 though.

**Comment by tennist** [comment]
try placing a short delay around your map initialization code like I did.
