### ISSUE TITLE
Map freeze after pushing view, since certain commit

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#2270]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
branch-cordova-sdk 2.6.17 "branch-cordova-sdk"
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-open-native-settings 1.4.1 "Native settings"
cordova-plugin-advanced-http 1.11.0 "Advanced HTTP plugin"
cordova-plugin-ble-central 1.1.4 "BLE"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.2-beta-20180515-1309 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-qrscanner 2.5.0 "QRScanner"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-swift-support 3.1.1 "SwiftSupport"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

"@ionic-native/core": "4.7.0",
"@ionic-native/google-maps": "^4.8.2",
```

**Current behavior:**
Since commit https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/0dbe65d6a92fcbf1bca9793d7238b507dc802729 the map is frozen after new view is pushed into NavController (map.setDiv(null) is called in ionViewWillLeave and map.setDiv(mapDiv) is called on onViewWillEnter) and pushed view is dismissed.

On Android - map is frozen on new view closed
On iOS - map is blank on new view closed

No error in console is provided.

With previous commint https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/d783ff0d95b802250ac57c5c86cc09a0447bc706 is no problem.

**Comment by cedrickbae** [comment]
I also experience this issue. What I did temporarily is use modal instead of push.

**Comment by vosecek** [comment]
It is the same repository as I shared to you in https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2252

**Comment by wf9a5m75** [comment]
Try the multiple_maps branch code

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...

$> cordova plugin list
cordova-plugin-googlemaps 2.3.4-beta-20180517-1004 "cordova-plugin-googlemaps"

```

**Comment by vosecek** [comment]
The patch is applied to master, not multiple_branch.

Anyway,
iOS: map is not blank after returning to map, but is frozen
Android: map is blank after returning to map, not frozen

So: the behaviour is swapped.

**Comment by vosecek** [comment]
No, my repository is https://github.com/homeportcz/freebike

**Comment by wf9a5m75** [comment]
Oh, I didn't notice your invitation.

**Comment by wf9a5m75** [comment]
Ok, is there any problem?

![2270](https://user-images.githubusercontent.com/167831/40249913-6e370cbc-5a89-11e8-9d24-942e424f02f1.gif)

**Comment by vosecek** [comment]
My fault, setClickable has been called on ionViewWillEnter() not ionViewDidEnter().

I can confirm the bug is fixed. Thanks.
