### ISSUE TITLE
disable camara bearing?

### ISSUE THREAD

**Issue by YeisonVelez11** [mapsplugin/cordova-plugin-googlemaps#2275]
thaks for the plugin, how can disabled the effect bearing to move the map? 

thanks

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Map/getMap/README.md#create-a-map-with-initialize-options

```
var map = plugin.google.maps.Map.getMap(div, {
  'gestures': {
    'scroll': true,
    'tilt': true,
    'rotate': true,
    'zoom': true
  }
});

```

**Comment by wf9a5m75** [comment]
Please try it by yourself before asking.
