### ISSUE TITLE
Blank map with 2.3.3

### ISSUE THREAD

**Issue by piernik** [mapsplugin/cordova-plugin-googlemaps#2276]
I'm using:
```
"cordova-plugin-googlemaps": "^2.3.3",
"@ionic-native/google-maps": "^4.8.2",
"@ionic-native/core": "^4.7.0",
"cordova-android": "7.0.0",
```
I tried Your `2.2.9` and had issue with markers. Now I deleted old version `ionic cordova plugin remove cordova-plugin-googlemaps` and installed new with `ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="THE_SAME_KEY"`.
Also deleted and add android platform.

I don't have any restrictions on key:
![google-maps-api](https://user-images.githubusercontent.com/420691/40301257-dbfd45cc-5ceb-11e8-8e9e-f1975cef550a.png)

Map is gray. Markers are working. In debug console I have no error.
What can be wrong? Do I need to add something else?

![google-maps-api2](https://user-images.githubusercontent.com/420691/40301321-0cc7324e-5cec-11e8-8c12-0d734d253e24.png)

**Comment by StobyWan** [comment]
[map-test.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2022708/map-test.zip)

I am having same problem. My occurrences of MAP_READY are not firing on android 4.4.4 and 4.4.2 that I have found. There was another issue that was closed but I had followed the steps to update your google services to 15.0.1  but this had no effect for me.
<variable name="PLAY_SERVICES_VERSION" value="15.0.1" />
I have this in place with no avail. Please reconsider this issue as I have not found a resolution. 
I have an example app up here that need your own keys but should demonstrate the bug.

**Comment by wf9a5m75** [comment]
I don't spam zip file. Please share your project files on GitHub.

**Comment by wf9a5m75** [comment]
@StobyWan I just built your project files, and run it on Android 4.4.4.
![2276](https://user-images.githubusercontent.com/167831/40321001-7bf3b2fa-5ce2-11e8-8bfe-826efaac6c43.gif)

**Comment by wf9a5m75** [comment]
@piernik >Map is gray.
This mean your api key is not allow to use Google Maps Android API v2. Regenerate your api key.

**Comment by piernik** [comment]
I did generated new API key - the same result.
You're saying `Google Maps Android API v2`. I can't see it. I'm using `Maps SDK for Android`. I think it's the same think, right?
Tommorow I'll try clean install with new key.

**Comment by StobyWan** [comment]
My api 19 has android 4.4.2 as well were you able to run on this version?

**Comment by wf9a5m75** [comment]
I don't have Android 4.4.2 device, but should work.
By the way, nobody use such an old device except developers anymore.

**Comment by wf9a5m75** [comment]
Yes, but you have to enable it BEFORE generate your api key.

**Comment by piernik** [comment]
I figured it out. Key was correct.
I did a clean install and I noticed that it didn't have `"PLAY_SERVICES_VERSION": "15.0.1", "ANDROID_SUPPORT_V4_VERSION": "26.1.0"` lines in `package.json`. So I first deleted platform folder, added Your plugin and added android platform. 
New commands disapeared from `package.json` and now it's working as it should.

Thank for help.
