### ISSUE TITLE
Minimum container dimension is 100x100 in pixels error

### ISSUE THREAD

**Issue by tennist** [mapsplugin/cordova-plugin-googlemaps#2277]
After upgrading to the latest version of this plugin, I am getting an error of minimum container dimension is 100x100 in pixels and the map does not render.  I know that the div I have for the map is much larger than 100x100 pixels.  If I print div.style.height and div.style.width to the console prior to my plugin.google.maps.Map.getMap(div, mapOptions) function, I get a height of 358px and a width of 358px.  However, when I print div.offsetWidth and div.offsetHeight to the console I get a height of 0 and a width of 0.  There is clearly a 358px x 358px open space on my page that the map gets rendered on.

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by tennist** [comment]
Here is a link to the project files

https://github.com/tennist/drupalgap-test-map

**Comment by tennist** [comment]
I forgot to mention that you will need to add the android platform to the project before building it out.

**Comment by wf9a5m75** [comment]
Did you say `358px`?

If I insert code like this,
![screen shot 2018-05-21 at 12 26 12 pm](https://user-images.githubusercontent.com/167831/40325883-2d062546-5cf2-11e8-877d-1efd399d35d5.png)

it seems 0 x 0 pixels.
![screen shot 2018-05-21 at 12 25 17 pm](https://user-images.githubusercontent.com/167831/40325868-1f9295ac-5cf2-11e8-8807-a70120e2072d.png)

**Comment by wf9a5m75** [comment]
>However, when I print div.offsetWidth and div.offsetHeight to the console I get a height of 0 and a width of 0. There is clearly a 358px x 358px open space on my page that the map gets rendered on.

It's your programing problem, not this plugin.
You must specify a div which is larger than 100x100 pixels BEFORE `map.getDiv()`.

**Comment by tennist** [comment]
I generate the div in my page call back, then I initialize the map in the pageshow event.  The div is already specified and should be loaded prior to initializing the map.

**Comment by wf9a5m75** [comment]
I don't know DrupalGap lifecycle, and I'm not interested in.
Important thing is the `<div>` must be larger than 100x100px **BEFORE** executing `Map.getMap()`. That's all.

**Comment by YeisonVelez11** [comment]
@tennist  @wf9a5m75 Hi. Can someone give me some light? I'm running a timeout of 5 seconds and I keep getting this error.

Minimum container dimension is 100x100 in pixels error 
<div id="map_canvas" style="width:500px; height:500px; z-index: 1 !important; overflow: auto !important;"></div>


this is my code:

`  document.addEventListener("deviceready", onDeviceReady, false);

  function onDeviceReady(){
  $timeout(function(){
      map= plugin.google.maps.Map.getMap(mapDiv);
    },5000)
  }

  <div id="map_canvas" style="width:500px; height:500px; z-index: 1 !important; overflow: auto !important;"></div>
`

**Comment by tennist** [comment]
That is as far as my experience goes on this.  You usually get this error if the container has not been created yet. 

Device ready doesn't necessarily mean the page is loaded, but I imagine it should be after a 5sec timeout.  I would suggest placing your code in a pageshow event. 

Also for a timeout I would suggest the following:
`setTimeout(function() {
   map= plugin.google.maps.Map.getMap(mapDiv);
}, 5000`

**Comment by tennist** [comment]
my app uses the jQuery Mobile pageshow event.  This triggers code once the page is shown.

**Comment by YeisonVelez11** [comment]
in my case with timeout should be works... I use setTimeout and not works :( same problem

**Comment by tennist** [comment]
It sounds to me that your getMap is being called before the page is shown.  Do you have JQM loaded into your app?  If so, use the pageshow event.  If not, I would suggest loading it just to test and see if the pageshow works for you.

**Comment by YeisonVelez11** [comment]
excuse me my ignorance what is JQM

**Comment by tennist** [comment]
jQuery Mobile as described a few comments up the page.  I also provided a link to the pageshow event documentation in that comment.

**Comment by setu1421** [comment]
I am facing the same problem today. Is there any solution?
