### ISSUE TITLE
BUG: no map on back in ionic app

### ISSUE THREAD

**Issue by piernik** [mapsplugin/cordova-plugin-googlemaps#2279]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
When I open map and go to new page and then return with back button (at the top) there is no map anymore

**Expected behavior:**
There should be map present.

**Related code, data or error log (please format your code or data):**

https://github.com/piernik/ionic-map

**Comment by battika** [comment]
On `ionViewDidEnter` event run `this.map.show();` when you return to the map.

**Comment by piernik** [comment]
I'll try - in previous version it wasn't necessary.

**Comment by battika** [comment]
I meant setDiv(), sorry

**Comment by piernik** [comment]
It's working - thanks.
But I still cosider it as a bug.

**Comment by battika** [comment]
Sorry to hear that. I guess we need to wait until Masashi (@wf9a5m75 ) looks into it

**Comment by wf9a5m75** [comment]
This is already fixed on the multiple_maps branch version.

**Comment by piernik** [comment]
I cannot fetch it :/ When will You publish it?

**Comment by wf9a5m75** [comment]
```
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```

**Comment by piernik** [comment]
@wf9a5m75 thanks. It works but I noticed other bug.
Sadly I cannot reproduce it. I'll try to describe it.

I have app with polish touristic attractions: https://play.google.com/store/apps/details?id=pl.polskieszlaki.PolskieSzlaki&hl=pl

When open map for the first time app loads markers and pins them on map. 
If marker is tapped overlay (not info windows) shows it's details:
```
<div style="position: relative;width:100%; height:100%;">
        <div id="map_canvas" #map_canvas style="width:100%; height:100%;"></div>
        <app-mapa-chmurka-atrakcja *ngIf="atrakcja" [atrakcja]="atrakcja"
                                   style="position: absolute; top: 0; display:block;"></app-mapa-chmurka-atrakcja>
    </div>
```
In that overlay/component there is a button. And that button does not recieve `click` event :/

But when I open detail attraction (not from map) and then open map with that attraction marked, overlay works correct - recieves click event.

Map always works on the same code:
```
loadMap() {
    let mapOptions: any | GoogleMapOptions = {
      camera: {
        target: this.srodek,
        zoom: this.zoom,
        tilt: 0
      },
      controls: {
        myLocation: true,
        myLocationButton: true,
        compass: true
      }
    };
    this.map = GoogleMaps.create('map_canvas', mapOptions);
    this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => {
        this.mapaService.map = this.map;

        this.map.on(GoogleMapsEvent.MAP_CLICK)
          .subscribe(() => {
            this.atrakcja = null;
            this.ref.detectChanges();
          });

///....
      });
  }

...
//adding markers
private dodajMarkerAtrakcji(item: Atrakcja) {
    const pipe = new KolorWagiPipe();
    this.map.addMarker({
      title: item.tytul,
      icon: pipe.transform(item.waga),
      animation: 'DROP',
      position: {
        lat: item.szer_geogr,
        lng: item.dl_geogr,
      }
    })
      .then((marker: MarkerAtrakcji) => {
        marker.id_miejsca = item.id_miejsca;
        this.markery.push(marker);
        marker.on(GoogleMapsEvent.MARKER_CLICK)
          .subscribe(() => {
            this.atrakcja = item;
            this.ref.detectChanges();
          });

//if going from attraction details tirgger marker click event to show overlay

        if (this.idMiejscaWybranego !== null && this.idMiejscaWybranego == item.id_miejsca) {
          marker.trigger(GoogleMapsEvent.MARKER_CLICK, marker.getPosition());
          this.idMiejscaWybranego = null;
        }
      });
  }
```


It all worked great in `2.2.8`.

**Comment by piernik** [comment]
I managed to isolate bug. I've updated repository - https://github.com/piernik/ionic-map.
In `home` folder are those files: https://github.com/piernik/ionic-map/tree/master/src/pages/home

What is the problem? Overlay is not visible at beggining. It shows when You tab marker:
```
                // alert('marker clicked');
                this.show = true;
                this.ref.detectChanges();
```
To inform angular that overlay is not hidden I tigger `this.ref.detectChanges();`. But Your plugin is not reflecting those changes.

If You toggle overlay using standard button it works.

Hope You'll manage to fix the problem soon.

**Comment by wf9a5m75** [comment]
Add `cordova.fireDocumentEvent('plugin_touch', {});` after `this.show = true`

**Comment by piernik** [comment]
Is `cordova` globally accessable? 
I'm using typescript so I added `declare let cordova:any;` or should it be imported from some library?

```
marker.on(GoogleMapsEvent.MARKER_CLICK)
              .subscribe(() => {
                this.show = true;
                cordova.fireDocumentEvent('plugin_touch', {});
                this.ref.detectChanges();
              });
```
It doesn't work. The same behaviour.
Do You plan to fix it in next release? Or that will be permanent solution?

**Comment by wf9a5m75** [comment]
This is not a bug. You must tell to the plugin when you display with just changing css visibility. I won't fix this.

**Comment by wf9a5m75** [comment]
Please search some keywords on Google. I can find answers easily.

`declare var cordova;`
https://forum.ionicframework.com/t/how-to-use-non-native-plugins-on-ionic/63936

**Comment by piernik** [comment]
@wf9a5m75 that's exactly what I did and it does not work:/
I updated github repo so You can try Yourself.
https://github.com/piernik/ionic-map

In previuos version I did not have to use `cordova` hack.
Please look at this.

**Comment by vosecek** [comment]
Steps are simple:
once you return to map from wherever, you have to map.setDiv('your_div'); and make sure the map is clickable by map.setClickable(true).

btw, switching the map on and off by overlaying too fast (on and off in 500 ms) can cause problem.

**Comment by piernik** [comment]
@vosecek it's not the case - did You see the code?

**Comment by wf9a5m75** [comment]
>In previous version I did not have to use `cordova` hack.

Program is not the same forever. You have to change your code if new version doesn't work.

`cordova.fireDocumentEvent('plugin_touch', {});` is not a hack.
I describe here.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/whats-new-v2/README.md#change-4-save-battery-life

--------

If you prefer previous version, why do you upgrade the plugin? Choosing which version is under your risk control.

**Comment by wf9a5m75** [comment]
Try again using the latest multiple_maps branch version code without `plugin_touch` event firering.
![2279](https://user-images.githubusercontent.com/167831/40559017-2fcf73e8-600a-11e8-922c-3d3f3fc3a576.gif)

**Comment by piernik** [comment]
@wf9a5m75 `cordova.fireDocumentEvent('plugin_touch', {});` is not working. Check it Yourself.
I can use it - no problem. **But it is not working.**
Here is code: https://github.com/piernik/ionic-map

I upgraded not to bother users with unnecesary permision from play service.

**Comment by wf9a5m75** [comment]
Adjustment for your case.

**Comment by piernik** [comment]
I can confirm that it is working :) I can publish app. Great job - thanks.
