### ISSUE TITLE
plugin does not recognize HTML elements correctly after moving HTML elements with animations

### ISSUE THREAD

**Issue by tmyers97** [mapsplugin/cordova-plugin-googlemaps#2280]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ X ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ X ] **Android**
- [ X ] **iOS**

**Current behavior:**
I am currently experiencing two problems as of yesterday. 

I installed the branch #multiple_maps to fix issue #2279

However, I am still experiencing the problem of clicking through html divs that are on top of the map. It seems that the first click goes through the div and hits the map then the second click registers onto the div. Exactly like #2255 and #1291

I tried calling: 

`declare let cordova: any;`

`cordova.fireDocumentEvent('plugin_touch', {});`

after calling my animations and there does not seem to be any change.

Everything worked perfectly 100% yesterday but I will continue to toy around with the issues, any help is much appreciated!

Thanks,
Troy

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by tmyers97** [comment]
https://github.com/tmyers97/googlemapsproblem

Sorry, I was in the process of testing a new project to add to a repo.

**Comment by tmyers97** [comment]
The issue appears to only happen after animation, if that helps.

**Comment by wf9a5m75** [comment]
Ok, I confirmed your point. Simple solution is to give up to hiding/showing tool bars.

**Comment by tmyers97** [comment]
Haha yea that might be the way to go. What would be the non-simple solution? What would cause this to happen all of a sudden?

**Comment by wf9a5m75** [comment]
I don't know what you mean `as of yesterday` (because I don't change anything yesterday),  but I guess you reinstalled plugin yesterday.

As you may know, the map view is **NOT HTML element**.
The maps plugin just tracks position and dimension of (almost) all HTML elements when the plugin is necessary.
But it seems this does not work well when your app do hiding/showing.

**Comment by tmyers97** [comment]
Yea, that makes sense because I did add a new plugin yesterday so when I repackaged it would have put me on 2.3.3.

May I ask what the difference between #multiple_maps and the regular branch is to fix the map not resetting?

I will try downgrading to 2.2.9 and let you know what happens.

**Comment by wf9a5m75** [comment]
I give you some advices.

- `this.map.one(GoogleMapsEvent.MAP_READY).then(() => {})` is no longer necessary except you use `map.getVisibleRegion()`.

- Use `LocationService.getMyLocation()` instead of `Geolocation`. One less plugin.

**Comment by tmyers97** [comment]
Brilliant, thank you so much!!!
