### ISSUE TITLE
ionic map provider example showing only white blank map

### ISSUE THREAD

**Issue by DBuzzer8** [mapsplugin/cordova-plugin-googlemaps#2281]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
I am using the ionic map provider example's package.json
**Current behavior:**

I am trying to run the ionic map provider example, but it ran with a white blank map.
All the tabs are shown and navigating correctly.
I have checked that my API keys are correct, as i am using those same keys in other apps and they work.
My android device is on android version 5.0.2, and i am using it to test other google map apps too ie it should be working.  
**Expected behavior:**

Expected a properly rendered map from the ionic map provider example.

**Comment by wf9a5m75** [comment]
Did you replace API keys in `config.xml` and `package.json` files before `cordova prepare`?

**Comment by DBuzzer8** [comment]
I have change the  API keys in config.xml and package.json to my own keys. But what do i need to do with "corodva prepare"? thanks for the quick response!!

**Comment by wf9a5m75** [comment]
Okay, I tried, and it seems `cordova-plugin-device.device` is the problem.

![screen shot 2018-05-22 at 7 00 24 pm](https://user-images.githubusercontent.com/167831/40399465-670fac0c-5df2-11e8-9eee-236c45ffa429.png)

**Comment by wf9a5m75** [comment]
But anyway, it's not so important.
You just create a blank project, and replace the `src` folder to https://github.com/mapsplugin/ionic-map-provider-example/tree/master/src

**Comment by DBuzzer8** [comment]
did you just make changes to the SRC? I cloned from it about 10 hours ago and build the example from there. And that's how i came to the issue.
BTW, I did a chrome inspect of my android deployment, but did not see the same device plugin issue as your screen shot.

**Comment by wf9a5m75** [comment]
If so, please debug by yourself.

**Comment by DBuzzer8** [comment]
I am trying to debug it myself too.
But please confirm that the src code will work for you and not broken somewhere? ie its not a bug in the plugin. 
I did not change the src code at all, but am seeing the issue. Just want to know if you are also reproducing it?  just want to be sure that the issue happens only in my environment Thanks.

**Comment by wf9a5m75** [comment]
Please do not try to steal my private time. You should do your best.
