### ISSUE TITLE
Suggestion: Follow location

### ISSUE THREAD

**Issue by piernik** [mapsplugin/cordova-plugin-googlemaps#2283]
In other topic You suggested to use `LocationService.getMyLocation()` and skip `Geolocation` plugin.
I think that this method returns only one value.
Could You introduce tracing localization? as `Observable` for example?

**Comment by wf9a5m75** [comment]
Time is money. If you donate enough amount, I will create it. Otherwise, you have to create it, and send a pull request or just wait until someone implement it.
