### ISSUE TITLE
street view causing build errors in android

### ISSUE THREAD

**Issue by n7229** [mapsplugin/cordova-plugin-googlemaps#2285]
BUILD FAILED in 16s
(node:11693) UnhandledPromiseRejectionWarning: Error: 
platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
platforms/android/app/src/main/java/plugin/google/maps/PluginStreetViewPanorama.java:17: error: cannot find symbol
import com.google.android.gms.maps.model.StreetViewSource;
                                        ^
  symbol:   class StreetViewSource
  location: package com.google.android.gms.maps.model
platforms/android/app/src/main/java/plugin/google/maps/PluginStreetViewPanorama.java:87: error: cannot find symbol
          StreetViewSource source = "OUTDOOR".equals(cameraOpts.getString("source")) ?
          ^
  symbol:   class StreetViewSource
  location: class PluginStreetViewPanorama
platforms/android/app/src/main/java/plugin/google/maps/PluginStreetViewPanorama.java:88: error: cannot find symbol
              StreetViewSource.OUTDOOR : StreetViewSource.DEFAULT;
              ^
  symbol:   variable StreetViewSource
  location: class PluginStreetViewPanorama
platforms/android/app/src/main/java/plugin/google/maps/PluginStreetViewPanorama.java:88: error: cannot find symbol
              StreetViewSource.OUTDOOR : StreetViewSource.DEFAULT;
                                         ^
  symbol:   variable StreetViewSource
  location: class PluginStreetViewPanorama
platforms/android/app/src/main/java/plugin/google/maps/PluginStreetViewPanorama.java:280: error: cannot find symbol
              StreetViewSource source = "OUTDOOR".equals(cameraOpts.getString("source")) ?
              ^
  symbol: class StreetViewSource
platforms/android/app/src/main/java/plugin/google/maps/PluginStreetViewPanorama.java:281: error: cannot find symbol
                  StreetViewSource.OUTDOOR : StreetViewSource.DEFAULT;
                  ^
  symbol: variable StreetViewSource
platforms/android/app/src/main/java/plugin/google/maps/PluginStreetViewPanorama.java:281: error: cannot find symbol
                  StreetViewSource.OUTDOOR : StreetViewSource.DEFAULT;

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
```
insert the output from the command here
```
branch-cordova-sdk 3.0.0 "branch-cordova-sdk"
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.12.1 "BackgroundGeolocation"
cordova-clipboard 1.2.1 "Clipboard"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-open-native-settings 1.5.1 "Native settings"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.3.0 "AppRate"
cordova-plugin-background-fetch 5.4.0 "CDVBackgroundFetch"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-facebook4 2.1.0 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.3.4-beta-20180522-1712 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.0 "OneSignal Push Notifications"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.0 "Launch Navigator"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
"@ionic-native/google-maps": "^4.8.2",

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please search past issues before asking.

**Comment by n7229** [comment]
yes exactly I have read that

my 
**project.properties**
target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/mobile-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:11.6.0
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.2=cordova-background-geolocation-lt/mobile-build.gradle
cordova.system.library.3=com.android.support:support-v4:24.1.1+
cordova.system.library.4=com.android.support:support-v4:24.1.1+
cordova.system.library.5=com.facebook.android:facebook-android-sdk:4.+
cordova.system.library.6=com.google.android.gms:play-services-analytics:+
cordova.gradle.include.3=cordova-plugin-googlemaps/mobile-tbxml-android.gradle
cordova.system.library.7=com.google.android.gms:play-services-maps:15.0.1
cordova.system.library.8=com.google.android.gms:play-services-location:15.0.1
cordova.system.library.9=com.android.support:support-core-utils:27.1.1
cordova.system.library.10=com.google.android.gms:play-services-auth:11.8.0
cordova.system.library.11=com.google.android.gms:play-services-identity:11.8.0
cordova.system.library.12=com.android.support:support-v4:24.1.1+
cordova.system.library.13=com.android.support:support-v4:26.+
cordova.system.library.14=com.android.support:appcompat-v7:26.+
cordova.system.library.15=com.onesignal:OneSignal:3.9.0
cordova.gradle.include.4=onesignal-cordova-plugin/mobile-build-extras-onesignal.gradle
cordova.system.library.16=com.squareup.okhttp3:okhttp:3+


**build.gradle**

buildscript {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
    dependencies {

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.android.tools.build:gradle:3.0.0'
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
    //This replaces project.properties w.r.t. build settings
    project.ext {
      defaultBuildToolsVersion="25.0.2" //String
      defaultMinSdkVersion=19 //Integer - Minimum requirement is Android 4.4
      defaultTargetSdkVersion=26 //Integer - We ALWAYS target the latest by default
      defaultCompileSdkVersion=26 //Integer - We ALWAYS compile with the latest by default
    }
}

**Comment by wf9a5m75** [comment]
```
cordova.system.library.1=com.google.android.gms:play-services-location:11.6.0
cordova.system.library.10=com.google.android.gms:play-services-auth:11.8.0
cordova.system.library.11=com.google.android.gms:play-services-identity:11.8.0
```

**Comment by n7229** [comment]
changed it but still same

```
target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.android.support:support-v4:24.1.1+
cordova.system.library.2=com.android.support:support-v4:24.1.1+
cordova.gradle.include.1=cordova-plugin-googlemaps/mobile-tbxml-android.gradle
cordova.system.library.3=com.google.android.gms:play-services-maps:12.0.1
cordova.system.library.4=com.google.android.gms:play-services-location:12.0.1
cordova.system.library.5=com.android.support:support-core-utils:24.1.1
cordova.system.library.6=com.squareup.okhttp3:okhttp:3+
cordova.system.library.7=com.android.support:support-v4:24.1.1+
cordova.system.library.8=com.google.android.gms:play-services-auth:12.0.1
cordova.system.library.9=com.google.android.gms:play-services-identity:12.0.1
cordova.system.library.10=com.android.support:support-v4:26.+
cordova.system.library.11=com.android.support:appcompat-v7:26.+
cordova.gradle.include.2=cordova-plugin-background-fetch/mobile-build.gradle
cordova.system.library.12=com.google.android.gms:play-services-location:12.0.1
cordova.system.library.13=com.android.support:appcompat-v7:27.1.1
cordova.gradle.include.3=cordova-background-geolocation-lt/mobile-build.gradle
cordova.system.library.14=com.google.android.gms:play-services-analytics:+
cordova.system.library.15=com.onesignal:OneSignal:3.9.0
cordova.gradle.include.4=onesignal-cordova-plugin/mobile-build-extras-onesignal.gradle
cordova.system.library.16=com.facebook.android:facebook-android-sdk:4.+
```

```
<plugin name="cordova-plugin-googlemaps" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps">
        <variable name="API_KEY_FOR_ANDROID" value="" />
        <variable name="API_KEY_FOR_IOS" value="" />
        <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="Show your location on the map" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Trace your location on the map" />
        <variable name="PLAY_SERVICES_VERSION" value="12.0.1" />
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.1" />
    </plugin>
```

**Comment by wf9a5m75** [comment]
![screen shot 2018-05-23 at 12 52 01 pm](https://user-images.githubusercontent.com/167831/40447636-1dab39d2-5e88-11e8-9be8-797f14f4333e.png)

**Comment by wf9a5m75** [comment]
>        <variable name="PLAY_SERVICES_VERSION" value="12.0.1" />

You need to use `15.0.1`

**Comment by wf9a5m75** [comment]
Also `onesignal-cordova-plugin/mobile-build-extras-onesignal.gradle` contains Google Play Services version. Check out the file.

**Comment by n7229** [comment]
one signal updated its plugin that solved the issue tq

**Comment by AdrienV** [comment]
> PLAY_SERVICES_VERSION

Or the last one here : https://developers.google.com/android/guides/setup

**Comment by kapilSoni101** [comment]
@wf9a5m75 i tried each and every thing but noting is worked for me what i do for fix above error?

**Comment by kapilSoni101** [comment]
@enkc06: sir are u fixed above issue?
