### ISSUE TITLE
Android: ANR caused by MyPluginLayout$ResizeTask.run in Android 7.0

### ISSUE THREAD

**Issue by GitToTheHub** [mapsplugin/cordova-plugin-googlemaps#2286]
**I'm submitting a ...**  (check one with "x")
- [X] any problem or bug report

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**

**cordova information:**  (run `$> cordova plugin list`) 
Using cordova-plugin-googlemaps in Version 2.2.8 (with Phonegap Build and CLI 7.1.0)

**Current behavior:**
I got 3 ANR Reports for my running app on the google play store. It only occures on Android 7.0 with the following error message:

> Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 45. Wait queue head age: 20528.7ms.)

This is the stack trace (the second trace contains MyPluginLayout$ResizeTask.run):

```
"main" tid=1 Blocked
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x76b1dc98 self=0x7970ac7a00
  | sysTid=30091 nice=-4 cgrp=default sched=0/0 handle=0x79754b8a98
  | state=S schedstat=( 0 0 0 ) utm=6706 stm=2614 core=2 HZ=100
  | stack=0x7fc3f7d000-0x7fc3f7f000 stackSize=8MB
  | held mutexes=
 
  at android.os.MessageQueue.next (MessageQueue.java:325)
  : waiting to lock <0x0fb030d4> (a android.os.MessageQueue) held by thread 11
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke! (Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)

"Timer-61" tid=11 Runnable
"Timer-61" prio=5 tid=11 Runnable
  | group="main" sCount=0 dsCount=0 obj=0x32c05ee0 self=0x79257f6000
  | sysTid=30497 nice=0 cgrp=default sched=0/0 handle=0x794a6c3450
  | state=R schedstat=( 0 0 0 ) utm=18424 stm=3887 core=7 HZ=100
  | stack=0x794a5c1000-0x794a5c3000 stackSize=1037KB
  | held mutexes= "mutator lock"(shared held)
 
  at android.os.MessageQueue.enqueueMessage (MessageQueue.java:566)
  : locked <0x0fb030d4> (a android.os.MessageQueue)
  at android.os.Handler.enqueueMessage (Handler.java:643)
  at android.os.Handler.sendMessageAtTime (Handler.java:612)
  at android.os.Handler.sendMessageDelayed (Handler.java:582)
  at android.os.Handler.post (Handler.java:338)
  at android.app.Activity.runOnUiThread (Activity.java:6043)
  at plugin.google.maps.MyPluginLayout$ResizeTask.run (MyPluginLayout.java:94)
  at java.util.TimerThread.mainLoop (Timer.java:555)
  at java.util.TimerThread.run (Timer.java:505)
```

In 1 ANR there are 3 Tasks with MyPluginLayout$ResizeTask.run. One is runnable, and two are blocked.
In 1 other ANR there are 2 Tasks with MyPluginLayout$ResizeTask.run. One is runnable, and one is blocked.

The ANR only occures on Android 7.0.

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by wf9a5m75** [comment]
ping

**Comment by GitToTheHub** [comment]
Ok i will share a sample project, but can do it tomorrow, or Friday. Hope thats ok.

**Comment by wf9a5m75** [comment]
ok

**Comment by wf9a5m75** [comment]
ping

**Comment by GitToTheHub** [comment]
You are right, i wrote that i share a sample project at the latest today. Sorry, but something has cropped up. I will share code at the latest monday. Hope thats ok too.

**Comment by GitToTheHub** [comment]
Hey you asked for source code, here is a sample project of my app:
https://github.com/GitToTheHub/maps_anr_sample
It's a Phonegap Project. The ANR occured under Android 7.

**Comment by wf9a5m75** [comment]
Thank you for sharing the project.
Please instruct me how to reproduce the issue 100%.
I will check it out when I have a time later.

**Comment by wf9a5m75** [comment]
I noticed that you use `v2.2.8` which is already old version.
https://github.com/GitToTheHub/maps_anr_sample/blob/90e0d49f260b420829c79d03235dd262e058a663/config.xml#L103

Please reinstall `v2.3.4` then test your code. After that if the problem is still occurred, please let me know.

**Comment by GitToTheHub** [comment]
Ok, the last update i tried was 2.2.9 and i got build errors, as such:
> Error: more than one library with package name 'com.google.android.gms.license'
and i thought i cannot update the plugin any longer, because there is an incompatible or so.
Now i tried the version 2.3.4 and the build was successful.. But i got now a new problem. I extended my sample with a list page, to demonstrate this. If you switch twice to the map page from the list page, than i cannot longer move the map. With Version 2.2.8 i can always move the map, no matter how often i switch to the map page.

Another Issue:
If i start my project the first time with the Phonegap Developer App, then my custom marker icons are not shown. After start twice the Phonegap Developer App, my custom marker icons will appear.

**Comment by wf9a5m75** [comment]
I don't support "Phonegap Developer App". Ask to the developer

**Comment by GitToTheHub** [comment]
You didn't read my comment complete..
I'm using 2.3.4 now, but there is a bug, where i can't interact with the map view. Try my sample, which is using v2.3.4, and go two times to the map view. After the second time, you can't any longer interact with the map: https://github.com/GitToTheHub/maps_anr_sample

**Comment by GitToTheHub** [comment]
Independent of Phonegap Developer App, i often saw in my production App that sometimes the custom marker icons are gone. There is an issue too with the custom marker icons.

**Comment by wf9a5m75** [comment]
Did you check logcat when the app in error?

**Comment by GitToTheHub** [comment]
Which error do you mean? The issue with the custom marker icons, or that i cannot interact any longer with the map?
I cannot read the logcat, cause i debug via phonegap cli.
With Version 2.2.8 i can interact with the map, with version 2.3.4 not.

**Comment by wf9a5m75** [comment]
Do you use `PhoneGap Build` or `PhoneGap CLI`?

**Comment by GitToTheHub** [comment]
Both :)
For making my APK i use Phonegap Build. For debugging my App, i'm using Phonegap CLI (using "phonegap serve" here).

**Comment by wf9a5m75** [comment]
ok, this plugin does not support `phonegap serve`.

**Comment by wf9a5m75** [comment]
`logcat` is a system tool which is included in Android SDK.
When something occurs, Android outputs system log, and the `logcat` is able to read the log.

**Comment by GitToTheHub** [comment]
I know logcat, but it's very confusing to use. Which error i should analyse in logcat? That i cannot move the map any longer? I thought, you would look into it. If there is an error in logcat, i can't do anything here, cause it's a nativ problem and i'm only using JavaScript.

**Comment by wf9a5m75** [comment]
I just built your program. Is there any problem?
![compress](https://user-images.githubusercontent.com/167831/40692002-19cc36b4-6364-11e8-9f7c-28e7da88f1f6.gif)

**Comment by GitToTheHub** [comment]
If you open the map view the first time, there is no issue. You must go back again (to the list view) and then open the map view again. You can then no longer move on the map.

**Comment by GitToTheHub** [comment]
Thanks for testing the issue :)

**Comment by GitToTheHub** [comment]
Sorry, i didn't saw you opened the map view a second time.
Incredible, you can move on the map O_O
Maybe it's an Android 5.0.1 Problem. I tested the app on a device with that version. On which version did you test?

**Comment by GitToTheHub** [comment]
I just rebuild the apk from my repo with Phonegap Build, and the error is still occuring on my Android 5.0.1 Device. Its an Android Version problem i think.

**Comment by wf9a5m75** [comment]
You said `Android 7.0` in this thread subject. That's why I tested it.

**Comment by wf9a5m75** [comment]
Anyway, I will test your project on Android 4.4. Hold on.

**Comment by GitToTheHub** [comment]
Right, the ANR has occured on Android 7, but you told me to upgrade the plugin. The "i cannot move the map any longer" Problem has nothing to do with the ANR Problem. Its a new bug, caused by the plugin upgrade.

**Comment by wf9a5m75** [comment]
On Android 7, there is no ANR problem.

**Comment by GitToTheHub** [comment]
Maybe better test this on Android 5?

**Comment by wf9a5m75** [comment]
If you pay me, I will buy Android 5 device.

**Comment by GitToTheHub** [comment]
The ANR Problem could maybe a problem brought by the 2.2.8 Version i last uses. Maybe its resolved with Version 2.3.4. Didn't know.
What does "MyPluginLayout$ResizeTask" do?

**Comment by wf9a5m75** [comment]
ResizeTask manages map view positioning.
I can not reproduce the issue though.

**Comment by GitToTheHub** [comment]
:)
Don't you have a Android 5 Emulator installed on you machine? Didn't must buy a device for testing this :)
Ok then test it on Android 4.4 if you haven't an emulatir there.

**Comment by wf9a5m75** [comment]
I tested on emulator, I can not confirm it.

--------------

I fixed another problems in another threads.
Might be covered in them.
Try like this.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```

**Comment by GitToTheHub** [comment]
Ok maybe the ANR is fixed with version 2.3.4. Can you still test the "cannot move the map" bug on Android 4.4 (or Android 5 Emulator)?

**Comment by wf9a5m75** [comment]
Here is Android 4.4 screen record with `multiple_maps` branch version.

![2286](https://user-images.githubusercontent.com/167831/40692816-be41c5c0-6368-11e8-8e69-e79f78ae4e8a.gif)

**Comment by GitToTheHub** [comment]
Im using phonegap build for making my apk. I think it handles the right plugin install behavior.
Maybe its a Bug with Android 5.
I will test tomorrow on Android 4.4, if there's the bug, or not.

**Comment by GitToTheHub** [comment]
Can't believe it's functionig on your system.
Big thanks for your Big support!!
I will test it tomorrow on an Android 4.4 Emulator, if it's the same behaviour. If not, it's a Problem with Phonegap Build.

**Comment by wf9a5m75** [comment]
ping

**Comment by jld3103** [comment]
I have the same bug with the not interacting map in Android 6.1 and plugin version 2.3.5. In version 2.3.4 it worked.
I'll check if there are some changes in the code related to this bug.

**Comment by wf9a5m75** [comment]
If you have a problem, please share your project files on github.

**Comment by GitToTheHub** [comment]
Hey, i tested the bug with an Android 7.1.1 Emulator, and i couldn't move the map, as i said!
Could you please test my phonegap build?
https://build.phonegap.com/apps/3181374/share
Did you used my config, when you build the app?

**Comment by jld3103** [comment]
The bug seems like a css bug.
These are the styles for

v2.3.4
```css
element.style {
    height: 510px;
    position: relative;
    overflow: hidden;
}

#map {
    height: 50%;
    width: 100%;
}
html, body, ._gmaps_cdv_ {
    background-image: url() !important;
    background: rgba(0,0,0,0) url() !important;
    background-color: rgba(0,0,0,0) !important;
}
div {
    display: block;
}
```

v2.3.5
```
element.style {
    height: 510px;
    position: relative;
    overflow: hidden;
}

html, body, ._gmaps_cdv_ {
    background-image: url() !important;
    background: rgba(0,0,0,0) url() !important;
    background-color: rgba(0,0,0,0) !important;
}
div {
    display: block;
}
```

I don't known if this is right, but I think these changes matter.

**Comment by wf9a5m75** [comment]
@GitToTheHub Could you share your **REAL** project with me?

**Comment by GitToTheHub** [comment]
What's the difference? I can't move the map with my sample project. I'm using for testing the same git repo i gave you: https://github.com/GitToTheHub/maps_anr_sample
So we should test both the same code. You don't need my full project for this.

**Comment by wf9a5m75** [comment]
I gave proof the plugin works perfectly. So there is only one possibility your mistake.

If you don't share your project, no further support is available.

**Comment by GitToTheHub** [comment]
No the difference will be the build mechanismen we both use. I give you proof too, that i had reproduce the bug with the "maps_anr_sample". I didn''t test the bug with my real app. Please test my APK from Phonegap Build; https://build.phonegap.com/apps/3181374/share and tell me if there is no issue.

**Comment by wf9a5m75** [comment]
This `<div>` blocks touch event.
![screen shot 2018-05-30 at 3 45 07 pm](https://user-images.githubusercontent.com/167831/40751531-757a02d6-6420-11e8-8de2-499f63678bba.png)

**Comment by wf9a5m75** [comment]
I will continue tomorrow.

**Comment by GitToTheHub** [comment]
Ok, i think, you already had detected, that the div is not the problem (in v2.2.8 there was no problem with the div). Anyway, i had removed the div and updated my [repo](https://github.com/GitToTheHub/maps_anr_sample) and my [phonegap build](https://build.phonegap.com/apps/3181374/share).
The error still occures, without the div.

**Comment by wf9a5m75** [comment]
In order to confirm one thing, could you build your project in your local at once?
Follow the below steps everything.

```
$> node -v
v9.3.0

$> cordova -v
8.0.0

$> adb version
Android Debug Bridge version 1.0.39
Version 0.0.1-4500957
Installed as /android-sdk/platform-tools/adb

$> cordova plugin rm cordova-plugin-googlemaps

Uninstalling cordova-plugin-googlemaps from android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Removing "cordova-plugin-googlemaps"
Removing plugin cordova-plugin-googlemaps from config.xml file...
Removing cordova-plugin-googlemaps from package.json

$> rm -rf node_modules/cordova-plugin-googlemaps

$> cordova plugin list
(confirm there is no cordova-plugin-googlemaps)

$> cordova plugin add cordova-plugin-googlemaps@2.3.5 --variable API_KEY_FOR_ANDROID="(API_KEY)" --variable API_KEY_FOR_IOS="(API_KEY)"

$> cordova run android

```

[sample.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2059364/sample.zip)

**Comment by wf9a5m75** [comment]
I have no problem.
![2286](https://user-images.githubusercontent.com/167831/40797944-9f9e573a-64be-11e8-91a1-43f0ac063a7d.gif)

**Comment by GitToTheHub** [comment]
Hey, your sample worked here on my device, but why? Does v2.3.5 fix the issue? Does it maybe help, if i give you the phonegap build log? I never build my app locally, why should that fix that issue, if i do? I would continue to build with phonegap build.

**Comment by wf9a5m75** [comment]
I don't know the reason. But the plugin works correctly at least.

**Comment by GitToTheHub** [comment]
You are a strange developer. How do you test the code, which other developers give you? I thought, you test the app with my config.xml i gave you. It seems, you tested my code with your latest release of your code. With v2.3.4, the bug does appear, with v2.3.5 the bug is gone. It seems, you tested all the time my code with your latest release and i tested my code mit v2.3.4. That's not so nice.

I'm glad, that the bug does not appear any longer. I always have the luck, that i test my code with an plugin version which give me errors, and next week the error is gone ..

Regards

**Comment by wf9a5m75** [comment]
If you feel this plugin is buggy or I am a strange developer, please use Google Maps JavaScript v3.

**Comment by GitToTheHub** [comment]
No i don't feel this plugin is buggy, it's only strange, how you test the code of other people. We have lot write about this bug, and you told me, that this must be my mistake, that i have the bug on my side. But finally it was your mistake, that you test my code with your latest code, and i tested it with version v2.3.4.
Please communicate next time better, what you test on your side ..
