### ISSUE TITLE
Why limit markercluster on zoom 18 ?

### ISSUE THREAD

**Issue by jrsanchezalcala** [mapsplugin/cordova-plugin-googlemaps#2287]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ x] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**Current behavior:**
Actually i have a map with where sometimes there are several markers on same point or very near . When i zoom more than 18 the markercluster disapears.

**Expected behavior:**
 i would like to show the markercluster even if the zoom is more than 18 . So when user click cluster i,ll show the info markers in that cluster. 

Could i get markercluster visible on more than 18 zoom? In markercluster docs it says that the maximum zoom is 18 . Why this limitation?

Thanks

**Comment by wf9a5m75** [comment]
Because too much closer.

**Comment by jrsanchezalcala** [comment]
I think its a mistake nota giving the choice yo Usera un JavaScript Google
Maps its posible to do this
