### ISSUE TITLE
Reopen #1919: Bottom part of ionic tabs is not clickable

### ISSUE THREAD

**Issue by gorriens** [mapsplugin/cordova-plugin-googlemaps#2291]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.4 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
es6-promise-plugin 4.2.2 "Promise"
info.protonet.imageresizer 0.1.1 "Image Resizer"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
- ionic-native/core: 4.7.0
- ionic-native/google-maps: 4.7.0

**Current behavior:**
Same issue as this one described by antoine92190 https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1919

**Screen capture or video record:** ( Merci @antoine92190 )
![myThornyIssue](https://user-images.githubusercontent.com/16256207/33230255-36849e38-d1e0-11e7-9275-9bca62d979eb.gif)

**Related code, data or error log (please format your code or data):**
The workaround I use for the moment is to set android mode;
<ion-tabs #myTabs icon-bottom title-hide **mode="md"**>

Strangely, It works perfectly on iPhone X with 'viewport-fit=cover', but not on others iPhone/iPad...

**Comment by wf9a5m75** [comment]
please share your project files on GitHub.

**Comment by gorriens** [comment]
Exactly the same one, juste emulate it with an other device that iPhone X... :)

**Comment by wf9a5m75** [comment]
In order to reproduce your issue perfectly, I asked. Otherwise please debug by yourself. I'm super busy.

**Comment by gorriens** [comment]
I understand... I will do my best to share a simple piece of code to reproduce it on gitHub... 
debug by myself ... i'm afraid to not be able to ...
Thanks :)

**Comment by gregavola** [comment]
@gorriens Are you still seeing this issue we are seeing it iOS..

**Comment by gregavola** [comment]
@wf9a5m75 This ticket (https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/d41f4362df341161a5119a46b6d979e9c2aa2e3b) has a resolution but the correct  commit as not been rolled in 3.2.5 - is this a mistake, or am i missing something?

**Comment by wf9a5m75** [comment]
If you have a problem, please create a new issue thread, and share your project files on GitHub.

**Comment by gregavola** [comment]
@wf9a5m75 I don't have a problem, I'm just trying to get more information if this was fixed not. Based on the current version of 2.3.5 - it is not, so I will open up a issue as you suggested. Thanks!
