### ISSUE TITLE
Uncaught TypeError: evt.target.hasAttribute is not a function

### ISSUE THREAD

**Issue by caleb87** [mapsplugin/cordova-plugin-googlemaps#2293]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
cordova-plugin-battery-status 1.2.4 "Battery"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-googlemaps 2.3.4 "cordova-plugin-googlemaps"
cordova-plugin-hidden-statusbar-overlay 2.0.1 "HiddenStatusbarOverlay"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
When rotating the screen, the following error is thrown:
```
Uncaught TypeError: evt.target.hasAttribute is not a function
at Object.onTransitionEnd (googlemaps-cdv-plugin.js:81)
onTransitionEnd @ googlemaps-cdv-plugin.js:81
setTimeout (async)
followMaps @ googlemaps-cdv-plugin.js:74
```

Line 81 of googlemaps.cdv-plugin.js:
```
function onTransitionEnd(evt) {
        if (!evt || !evt.target ||!evt.target.hasAttribute("__pluginDomId")) {
          return;
        }
        var elemId = evt.target.getAttribute("__pluginDomId");
        transformTargets[elemId] = {left: -1, top: -1, right: -1, bottom: -1, finish: false, target: evt.target};
        if (!transitionEndTimer) {
          transitionEndTimer = setTimeout(detectTransitionFinish, 100);
        }
      }
```

**Expected behavior:**
No errors thrown

**Comment by wf9a5m75** [comment]
Thank you for letting me know. I fixed the bug. Please reinstall the maps plugin from the multiple_maps branch.

```
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps \
    --variable API_KEY_FOR_ANDROID="..." \
    --variable API_KEY_FOR_IOS="..."
```

**Comment by caleb87** [comment]
I've tested it and it's working good using: https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps

It also fixed other issues I was going to bring up, one being some html elements weren't clickable and were just going through to the map. Everything works good now though.

Thanks! 👍
