### ISSUE TITLE
marker.setDisableAutoPan() does not work on iOS

### ISSUE THREAD

**Issue by dennis-wedevise** [mapsplugin/cordova-plugin-googlemaps#2294]
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/39722594/40642741-4c412226-631e-11e8-9c76-fd24949a36d8.jpg" width="250">
</td>
<td>
<img src="https://user-images.githubusercontent.com/39722594/40642749-4fda2e0a-631e-11e8-9976-9a795d0b2715.jpg" width="250">
</td>
</tr>
</table>

**I'm submitting a ...** 
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:** 
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-statusbar 2.1.3
cordova-plugin-device 1.1.6
cordova-plugin-googlemaps 2.3.4
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
When creating a marker there is a option setDisableAutoPan. Is there also a option for disabling map rotation when i click on a marker?

**Expected behavior:**
What i would like is to disable automatic bearing when clicking on a marker.

**Screen capture or video record:**
Screen rotate_1 is how i see the map, with custom bearing.
Screen rotate_2 is how i see the map after clicking a marker. 

**Related code, data or error log (please format your code or data):**

```
map = plugin.google.maps.Map.getMap(div, {
	'mapType': plugin.google.maps.MapTypeId.ROADMAP,
	'controls': {
		'compass': true,
		'myLocationButton': true,
		'myLocation': true,
		'indoorPicker': false,
		'zoom': true
	},
	'gestures': {
		'scroll': true,
		'tilt': false,
		'rotate': false,
		'zoom': true
	},
	camera: {
		target: {
			lat: holeLat, //51.2243265,
			lng: holeLng //5.64024165
		},
		'tilt': 0,
		'zoom': zoom,
		'bearing': bearing
	},
	'preferences': {
		'zoom': {
			'minZoom': 16,
			'maxZoom': 20
		},
		'padding': {
			'left': 9,
			'top': 9,
			'bottom': 9,
			'right': 9
		}
	}
});

map.addMarker({
   title: "  " + distance.toFixed(0) + " m",
  position: uLocation, //live
  draggable: false,
}, 
function(marker) {

  marker.setDisableAutoPan(true);
			
});
```

**Comment by wf9a5m75** [comment]
The maps plugin does not do anything when you tap on disabled auto pan marker.
I think your code of `animateCamera()` has problem.

If you can't solve the issue by yourself, please share your project files on GitHub (or other git repo services).

**Comment by dennis-wedevise** [comment]
I have created a test project on Github with similar settings as in my app. 
https://github.com/dennis-wedevise/googlemaps

If you click on the maker, the map will automatically turn. I want to avoid this.
As you can see, setDisableAutoPan is set to true.

**Comment by wf9a5m75** [comment]
Remove the plugins folder.

**Comment by wf9a5m75** [comment]
When cordova project folder  contains `plugins` directory, cordova use the installed plugin of the directory instead of downloading from npm.

So, even if you specify `2.3.4`, you still use `2.2.8-beta-20180315-1233`, which is very old version.

**Comment by wf9a5m75** [comment]
I can not reproduce your issue at all.
![compress](https://user-images.githubusercontent.com/167831/40674712-75c23840-632a-11e8-97b6-f35d4c698d31.gif)

**Comment by wf9a5m75** [comment]
Tentatively, the below code works as you expect.
```js
map.addMarker({
   title: "  " + distance.toFixed(0) + " m",
  position: uLocation, //live
  draggable: false,
  disableAutoPan: true
});
```

**Comment by wf9a5m75** [comment]
Fixed.
![compress](https://user-images.githubusercontent.com/167831/40681384-cf704be4-633d-11e8-9b98-b1f73c9c7962.gif)

**Comment by dennis-wedevise** [comment]
@wf9a5m75 thanks for your quick response. It works now!
