### ISSUE TITLE
Uncaught ReferenceError: plugin is not defined    

### ISSUE THREAD

**Issue by wesleyasmo** [mapsplugin/cordova-plugin-googlemaps#2295]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
C:\Users\wesley\Desktop\buyplus>cordova plugin ls
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-googlemaps 2.3.4 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

the map does not load and displays the error when I test in the browser "
Uncaught ReferenceError: plugin is not defined
    at Object.loadMap (index.js: 42)
    at Object.onDeviceReady (index.js: 13)
    at Channel.fire (cordova.js: 797)
    at cordova.js: 229 "

**Expected behavior:**

I wanted the map to load in the pageMap div

**Screen capture or video record:**

![screenshot_2](https://user-images.githubusercontent.com/30452028/40666308-c1d6cab0-6335-11e8-8136-cf96d9d7b107.png)

**Related code, data or error log (please format your code or data):**

```
https://github.com/wesleyasmo/buyplus
this is the project.
```

**Comment by wf9a5m75** [comment]
This plugin does not support browser platform

**Comment by wesleyasmo** [comment]
sorry, I forgot to mention that when I run the application it goes blank like this:
![96de1067-7409-4d9d-aed7-655c119c8e21](https://user-images.githubusercontent.com/30452028/40667615-f82dd31c-6338-11e8-921b-c980ec8707ee.jpg),
I put the access keys, one for the android as for the ios and remains blank.

**Comment by wesleyasmo** [comment]
I found the error, it was in the map settings, I put it as if it were from the browser.
Sorry for taking up your time.
