### ISSUE TITLE
Unable to add polyline on Maps(Cordova phone gap)

### ISSUE THREAD

**Issue by NaveenGB** [mapsplugin/cordova-plugin-googlemaps#2297]
I am using maps plugin for maps integration.
Map, marker working fine but adding polyline not working, see the below function which I am using it in .js file

    var mapDiv = document.getElementById('map-canvas');
    var map = plugin.google.maps.Map.getMap(mapDiv);
    map.addEventListener(plugin.google.maps.event.MAP_READY, function() {

      const HND_AIR_PORT = {"lat": , "lng":};
      const SFO_AIR_PORT = {"lat": , "lng": };
      map.addPolyline({
        points: [
          HND_AIR_PORT,
          SFO_AIR_PORT
        ],
        'color' : '#AA00FF',
        'width': 10,
        'geodesic': true
      });

    });

After following this solution https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2058 I am error find the below image 

![screen shot 2018-05-30 at 2 58 51 pm](https://user-images.githubusercontent.com/16935381/40711613-4a9ff63a-6419-11e8-9a15-06e6f5314df3.png)

Project
https://github.com/NaveenGB/Maps/tree/master/Android_Maps

**Comment by wf9a5m75** [comment]
```
$> cordova platform rm android

$> cordova platform add android
```

**Comment by NaveenGB** [comment]
I am unable to add polyline,  please check the project and let me know where I am going wrong

**Comment by wf9a5m75** [comment]
Regarding of the log, your installation has problem.
In order to resolve the issue, do it.
Other debug by yourself.

**Comment by NaveenGB** [comment]
please let me know how can I debug, I am new to phone gap

**Comment by wf9a5m75** [comment]
Just type I suggested.

**Comment by wf9a5m75** [comment]
I checked your project, and you don't use this plugin at all.

You use Google Maps JavaScript v3. 

Since you don't use this plugin, I close this thread.
Please ask at StackOverflow.com.
