### ISSUE TITLE
Can't find variable: element (v2.3.5)

### ISSUE THREAD

**Issue by LabDeve** [mapsplugin/cordova-plugin-googlemaps#2301]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.3.5 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "4.6.0",
 "@ionic-native/google-maps": "^4.8.2",
```

**Current behavior:**
ReferenceError: Can't find variable: element

![image](https://user-images.githubusercontent.com/17450809/40827481-f3dc1e76-657d-11e8-8498-4e7fe3217866.png)

**Comment by battika** [comment]
Hello,

Can you try the following Ionic native versions first?

"@ionic-native/core": "4.7.0",
"@ionic-native/google-maps": "4.8.2"

Also, I believe you need to use com.googlemaps.ios version 2.7.0 as opposed
to 2.6.0.

**Comment by battika** [comment]
OK, I can see you tested the latest Ionic native version in the meantime...

**Comment by metz0r** [comment]
Same issue here. Happens frequently but not every time.

"@ionic-native/core": "4.7.0",
"@ionic-native/google-maps": "4.8.2",
"cordova-plugin-googlemaps": "2.3.5",

**Comment by LabDeve** [comment]
I think the problem lies in the CordovaGoogleMaps.js file. In line ~854, the "element" variable does not seem to exist.
I do not know if it is a global variable or in any case where it is declared ...

**Comment by wf9a5m75** [comment]
Thank you. Please reinstall the plguin from the multiple_maps branch.

```
cordova plugin rm cordova-plugin-googlemaps

cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps

```
