### ISSUE TITLE
ionic google map is showing white screen

### ISSUE THREAD

**Issue by aqibrana** [mapsplugin/cordova-plugin-googlemaps#2302]
**ionic google map is showing white screen ...**  
- [ ] do i upload the code
- [ ] i already install typings install googlemaps --global --save
- [ ] and added a plugin 

**i am facing this problem in ionic frame work

**homt.html is :** 

```
<ion-header>
  <ion-navbar>
 <ion-title> Pick Me Up</ion-title>
  </ion-navbar>
</ion-header>

<ion-content class="home">
 <div class="map-wrapper">
 
 <map></map>
 
 </div>
 <div class="bottom request">
  <ion-row>
   <ion-col width-50>
   
   <button block light>
    
    <ion-icon name="card">
    
    </ion-icon>
    Visa **34
    </button>
   
   </ion-col>
   
   <ion-col width-50>
   <button block light>
    <ion-icon name="cash">
    cash
    </ion-icon>
    
    </button>
   
   </ion-col>
  
  
  </ion-row>
 
 </div>



</ion-content>

```

**home.ts**
```
.home {
        position: relative;
          
    
         .map-wrapper{
            width: 100%;
            height: 100%;
        }
        .bottom{
                position: absolute;
                bottom: 0;
                width: 100%;
        }

}


```

**map.html**

```
<div class="wrapper">
  <div id="map"></div>
</div>

```

**map.ts**

```
import { Component, OnInit } from '@angular/core';


@Component({
  selector: 'map',
  templateUrl: 'map.html'
})
export class MapDirective implements OnInit {


public map;

  constructor() {
    }
  
  ngOnInit(){
  this.map = this.createMap();
  }
   

  
  createMap(location = new google.maps.LatLng(40.712784, -74.005941)) {
  let mapOption = {
  
  center: location,
  zoom:15,
  mapTypeId: google.maps.MapTypeID.ROADMAP,
  disableDefaultUI: true
  }
  
  let mapEl = document.getElementById('map');
  let map = new google.maps.Map (mapEl, mapOptions);
  
  return map;
  }

}

```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub. Do not paste your code here

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response, I close this thread.

**Comment by aqibrana** [comment]
where should i upload my files

**Comment by aqibrana** [comment]
i uploaded my 6 files please check home.html home.scss home.ts map.html map.scss map.ts
[](https://github.com/aqibrana/cordova-plugin-googlemaps/tree/patch-1)

**Comment by aqibrana** [comment]
i uploaded all the fils

**Comment by aqibrana** [comment]
is there any way i can email you my **src** zip folder

**Comment by wf9a5m75** [comment]
No. I decline any souce code by email.
If you want to receive private support, please donate $100 USD.
https://raw.githubusercontent.com/mapsplugin/cordova-plugin-googlemaps/master/.github/ISSUE_TEMPLATE.md

**Comment by wf9a5m75** [comment]
@aqibrana I saw your code, and it is not this plugin code. That is Google Maps JavaScript API v3, not this plugin.
https://github.com/aqibrana/cordova-plugin-googlemaps/commit/4bcc221d04961339347be2702ecf438b3830c4d6

**Comment by aqibrana** [comment]
i added Google API key

**Comment by wf9a5m75** [comment]
I said you don't use this plugin.

**Comment by wf9a5m75** [comment]
`new google.maps.Map (mapEl, mapOptions);` is not this plugin code.

**Comment by aqibrana** [comment]
please read the last section index.html in that file i use --google Api key--
is there is an diff b/w plugin and api key please let me know
