### ISSUE TITLE
Map Options cause blank screen for initial loads

### ISSUE THREAD

**Issue by kunalgrover05** [mapsplugin/cordova-plugin-googlemaps#2303]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
```
    Cordova Platforms  : android 7.0.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2
    cordova-plugin-googlemaps 2.3.5 "cordova-plugin-googlemaps"
    @ionic-native/google-maps: 4.8.2
    @ionic-native/core: 4.4.0
```

**Current behavior:**
First of all, really appreciate the amazing plugin and the support provided by you. I am currently building an app using Ionic native Google maps. The first 2-3 loads only are problematic. When I load the map, a blank white screen is shown and MAP_READY never fires. I have confirmed that the div is 100% of the page size and rendered. 
The bug only happens on first 1-2 loads. We do a location.reload() after each load, and the 3rd load, the map loads correctly and MAP_READY is fired. 
I was able to reproduce the issue both by:
- Using Ionic wrapper of cordova-plugin-googlemaps 
- Without the Ionic wrapper using cordova-plugin directly in my Ionic code.

Some things tried by me:
- Tried out firing `touch_start` manually as suggested in some earlier issue.
- Tried out adding delays before loading the map

**Workaround**
Set map options only when map is ready(using ```map.setOptions```) rather than using the ```.create(element, options``` constructor. 

**Related code, data or error log (please format your code or data):**
I didn't see any errors either in ADB or console. 
I am sorry I haven't gotten to sharing a repository with the repro happening yet, but till then anyone facing the problem can use the workaround.

**Comment by metz0r** [comment]
@kunalgrover05 have you looked at the stack trace? The problem you're describing sounds like this issue: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2301

**Comment by kunalgrover05** [comment]
I don't see any error stack trace most of the times either using Ionic or
Cordova plugin.

**Comment by wf9a5m75** [comment]
@kunalgrover05 Please share your project files on GitHub.

**Comment by kunalgrover05** [comment]
@watacoz3 I can get you access to my project files privately, but it's a fairly big and complex app, which would mean you'd have to spend some time on it. 

I think I would first try to repro it on a simpler app and share here, and if that doesn't work, I will share my project with you.

**Comment by wf9a5m75** [comment]
I recommend you use this plugin in very simple project for first time.

**Comment by wf9a5m75** [comment]
ping

**Comment by kunalgrover05** [comment]
Haven't been able to reproduce the issue on a simple Ionic example. Using https://github.com/mapsplugin/ionic-googlemaps-quickdemo with same versions of Ionic and Cordova as my project but to no success.

One thing that I think might be causing the issue is the Access location permission dialog at the start of the app. In my app, I was adding the Location permission dialog using a different plugin at the same time (before loading map). Have you seen any previous issues like this? 

Next steps would be
1- trying to remove the location permissions dialog
2- modifying the ionic google maps example to match my app flow and trying to reproduce the bug.

I think you can mark it as a corner case bug for now and just leave the issue open for allowing anyone facing the same to get a workaround.

**Comment by wf9a5m75** [comment]
I think problem is in your code.

Since there is no enough information, I close this thread. Please let me know if you find anything.
