### ISSUE TITLE
how to auto open all infowindow of my markers using cluster markers?

### ISSUE THREAD

**Issue by YeisonVelez11** [mapsplugin/cordova-plugin-googlemaps#2305]
I know how to show the infowindow of a marker, but in this case I do not know how to do it for the topic of the cluster. How can I do to auto open all the infowindow of my markers?

    [
      {
        "position": {
          "lat": myLocation.lat- 0.0000001,
          "lng": myLocation.lng- 0.0000001
        },
        "name": "uno",
        "address": "Aiea Shopping Center_99-115 Aiea Heights Drive #125_Aiea, Hawaii 96701",
        "phone": "808-484-0000",
        title: "1Welcome to \n" +
             "Cordova GoogleMaps plugin for iOS and Android",
        snippet: "This plugin is awesome!",
      },
      {
        "position": {
          "lat":  myLocation.lat- 0.0001000,
          "lng": myLocation.lng- 0.0001000
        },
        "name": "dos",
        "address": "Pearlridge Center_98-125 Kaonohi Street_Aiea, Hawaii 96701",
        "phone": "808-484-0000",
        title: "1Welcome to \n" +
             "Cordova GoogleMaps plugin for iOS and Android",
        snippet: "This plugin is awesome!",
      },
      {
        "position": {
          "lat":  myLocation.lat- 0.0090000,
          "lng": myLocation.lng- 0.0090000
        },
        "name": "lejos",
        "address": "Pearlridge Center_98-125 Kaonohi Street_Aiea, Hawaii 96701",
        "phone": "808-484-0000",
        title: "1Welcome to \n" +
             "Cordova GoogleMaps plugin for iOS and Android",
        snippet: "This plugin is awesome!",
      }
    ];

     markerCluster= map.addMarkerCluster({
          boundsDraw: false,
          markers:markers ,
          icons: [
              {min: 2, max: 100, url: "./img/i1.png", anchor: {x: 16, y: 16}},
              {min: 100, max: 1000, url: "./img/i2.png", anchor: {x: 16, y: 16}},
              {min: 1000, max: 2000, url: "./img/i3.png", anchor: {x: 24, y: 24}},
              {min: 2000, url: "./img/i4.png",anchor: {x: 32,y: 32}}
          ]
        });
        markerCluster.on(plugin.google.maps.event.MARKER_CLICK, function (position, marker) {

         //marker.get("name")

        });

**Comment by wf9a5m75** [comment]
Not available. Only clicked marker is available for marker cluster.

**Comment by YeisonVelez11** [comment]
:( thanks...

**Comment by wf9a5m75** [comment]
There is nothing you can do more than in the document page.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/MarkerCluster/README.md
