### ISSUE TITLE
Iphone X Fullscreen Map

### ISSUE THREAD

**Issue by cedrickbae** [mapsplugin/cordova-plugin-googlemaps#2306]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
Cordova Platforms  : android 7.0.0 ios 4.5.4
Ionic Framework    : ionic-angular 3.9.2
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS
cordova-plugin-googlemaps 2.3.5 "cordova-plugin-googlemaps
@ionic-native/google-maps: ^4.8.2
@ionic-native/core: 4.7.0
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
I'm trying to achieve a full screen map. I was able to do it on my test devices but not on iPhone X as there's a white space above the map in the notch area. Is this normal, my div is set to width 100% and height 100%.

**Screen capture or video record:**
![screen shot 2018-06-03 at 12 46 54 am](https://user-images.githubusercontent.com/30261394/40878801-d8710aec-66c8-11e8-8131-6e132f21123c.png)

**Related code**

HTML Template 

```
<ion-content>
    <div #map id="map"></div>
  </ion-content>
```

Thank you very much

**Comment by wf9a5m75** [comment]
Maybe `<meta name='viewport' content='initial-scale=1, viewport-fit=cover'>`?
https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by cedrickbae** [comment]
Here is my meta from index.html

<meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

**Comment by wf9a5m75** [comment]
The maps plugin displays native map view to the position where the map div is located.

**Comment by wf9a5m75** [comment]
Positioning is your under control, not this plugin. At least you should check Safari Inspector or something.

**Comment by GitToTheHub** [comment]
Maybe this helps you: https://blog.phonegap.com/displaying-a-phonegap-app-correctly-on-the-iphone-x-c4a85664c493
(It's phonegap independent)

**Comment by wf9a5m75** [comment]
If you can't solve the problem by yourself, please share your project files on GitHub. Otherwise please debug by yourself.

**Comment by cedrickbae** [comment]
Thanks for the ideas, I check safari inspector and the css 
```
.scroll-content {
padding-top : env(safe-area-inset-top);
}
``` 
in ionic is causing the white space above. It pushes the map div to the safe area causing white space.

Thanks again!
