### ISSUE TITLE
can not interact with map on tutorial code

### ISSUE THREAD

**Issue by salalex** [mapsplugin/cordova-plugin-googlemaps#2307]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.3.5 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
I followed the Hello World tutorial and the map is displayed and the animation works, but the map doesn't seem to receive touch/drag events: cannot drag and zoom the map and the whole view scrolls instead.
I tried both with Android Studio emulator (Nougat 7.1.1) and with a real device (Sony Xperia X Compact, Oreo 8.0.0).

**Expected behavior:**
I was expecting to be able to drag and zoom the map (some time ago I tried version 2.2.9 and it worked flawlessly). 

**Screen capture or video record:**
<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/7436475/40890864-efe5197a-677c-11e8-839e-cf7b31499367.jpg" width="250">
</td><td>
<img src="https://user-images.githubusercontent.com/7436475/40890865-f007a6fc-677c-11e8-915e-73049f37bb0e.jpg" width="250">
</td>
</tr>

<tr>
<td>
<img src="https://user-images.githubusercontent.com/7436475/40890866-f02d0cc6-677c-11e8-82c1-692c32e14c63.jpg" width="250">
</td><td>
<img src="https://user-images.githubusercontent.com/7436475/40890867-f0501a9a-677c-11e8-818a-060796696a0a.jpg" width="250">

</td>
</tr>
</table>

**Comment by wf9a5m75** [comment]
please share your project files on GitHub

**Comment by salalex** [comment]
I installed version 2.3.6 and now it works! Thank you very much for your super fast reply.
