### ISSUE TITLE
Error: "undefined is not an object (evaluating 'self.domPositions[elemId].isMap = true')" v2.3.6

### ISSUE THREAD

**Issue by LabDeve** [mapsplugin/cordova-plugin-googlemaps#2310]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "4.6.0",
"cordova-plugin-googlemaps": "^2.3.6",
```

When it's called "GoogleMaps.create" it throw this error
```
this.map = GoogleMaps.create(this.mapsWrapper.nativeElement);
```
![image](https://user-images.githubusercontent.com/17450809/41094177-a8906a2e-6a4d-11e8-81cf-b9d45cbfa438.png)

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by LabDeve** [comment]
Ok I found the problem. Before the "map_ready" event, I set `visibility: hidden;` to the "div" element. This triggered the error ...

**Comment by wf9a5m75** [comment]
Congrats to resolve the problem.
