### ISSUE TITLE
npm version 2.3.0

### ISSUE THREAD

**Issue by macklus** [mapsplugin/cordova-plugin-googlemaps#2311]
Hi:
I wish to use cordova-plugin-googlemaps from capacitor (https://capacitor.ionicframework.com/), but i need to install it from npm and current npm version (https://www.npmjs.com/package/cordova-plugin-googlemaps-master) seems to be 1.3.9

can you update npm references to use v2.3.0 ?
thanks in advance

**Comment by wf9a5m75** [comment]
This plugin does not support the capacitor.


And you know what https://www.npmjs.com/package/cordova-plugin-googlemaps-master is not mine. Some one forked and released without asking.

https://www.npmjs.com/package/cordova-plugin-googlemaps is correct npm package.

**Comment by macklus** [comment]
You are right. Sorry, i dont see that this is not correct repo.

Also, i can confirm that your plugin works on capacitor (IOs still testing) on their basic functions. It you want, i can write you config steps

thanks

**Comment by homeportcz** [comment]
Any change to support Capacitor? Rewrite some core classes? Could you estimate price for this enhancement?
