### ISSUE TITLE
[Question] Why minSdk 19?

### ISSUE THREAD

**Issue by zwacky** [mapsplugin/cordova-plugin-googlemaps#2312]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
```

**Question**:
Is there a reason why the plugin got bumped with a minSdk to 19 as I can see here: https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/ac560cd38f2de7d7f87ae5a5aa8f5889e2ee98d0?

I know all developers would love to kill off up until 18, but there must be still—me included—lots of developers who target API 16.

In the logs I can see it's due to *tbxml-android*
```
:processDebugManifest
/Users/zwacky/data/jw-webapp/mobile/platforms/android/AndroidManifest.xml:54:5-74 Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:tbxml-android:] /Users/zwacky/.gradle/caches/transforms-1/files-1.1/tbxml-android.aar/f92a5cd3a87984a02718493e09d79e9b/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="za.co.twyst" to force usage (may lead to runtime failures)
```

**Comment by wf9a5m75** [comment]
You just need to upgrade cordova itself.

```
$> npm install -g cordova

$> cordova -v
8.0.0

$> cordova platform rm android

$> cordova platform add android
```

`MutationObserver` works on Android 4.4 or higher version. It doesn't work on Android 4.3.

And I don't want to pay my time for older Android devices (or will you pay lots of money?)

**Comment by zwacky** [comment]
I will not "pay lots of money" rather work on it and improve the software together, as it is common practice in open source software. That's also why I was asking why there was a bump in `minSdk` which wasn't there before. This way we could figure out if we could easily support the version back.

As it seems *to me* it's caused by the library `tbxml-android`, which—correct me if I'm wrong—is an XML parser that requires minSdk 19.

**Comment by macklus** [comment]
which should be desired version ? 21 ?

**Comment by wf9a5m75** [comment]
Minimum requirement is android-19

**Comment by zwacky** [comment]
My answer has been answered, I'll close this then. Thank you!

**Comment by Doberjohn** [comment]
I still have an error on this one, developing with Ionic 3. I updated the minimum version to SDK 19 but I can still get the same error and I can't build for Android. What should I do?
