### ISSUE TITLE
MarkerCluster.js:809: Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jasus** [mapsplugin/cordova-plugin-googlemaps#2313]
**I'm submitting a ...** 
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**
- [x] **Android**
- [ ] **iOS**

**cordova information:**

```
cordova-plugin-googlemaps 2.3.5 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^4.7.0",
"@ionic-native/google-maps": "^4.8.2"
```

**Current behavior:**
Sometimes maybe one out of every twenty or thirty times when the marker cluster is added to the map it throw this error.

So, I add markers to the marker cluster dynamically and apparently marker cluster was created and the markers are added but the map doesn't show any marker cluster.

**Screen capture or video record:**
![image](https://user-images.githubusercontent.com/3764822/41097863-c0a717be-6a59-11e8-9e71-9ecb4104b265.png)

**Comment by wf9a5m75** [comment]
Make sure following things:

- you certainly pass the position list at least two locations.

- your location list contains string lat/lng values. This is really common mistake.

If you can't solve the problem by yourself, please share your project files on GitHub.

**Comment by jasus** [comment]
Hi again, okay I'm going to test it these days and I will let you know when I solve the problem.

Thank you so much.

**Comment by jasus** [comment]
@wf9a5m75 I could resolve the problem. You can already close the issue.

Thank you ; )

**Comment by FWink** [comment]
I was facing the same issue and I think this is a race condition occuring when the MarkerCluster is created.

The callback in Map.addMarkerCluster line 1325 can be executed after the onCameraMoved event that we see in the stack trace is triggered. That causes the MarkerCluster._markerMap to be undefined.
I fixed it by changing MarkerCluster.js line 206:
`if (self._isRemoved || self._stopRequest) {
    return null;
  }`
to this
`if (self._isRemoved || self._stopRequest || !self._markerMap) {
    return null;
  }`


No idea if that has any side effects, seems to work fine though.

**Comment by Hanzofm** [comment]
@jasus wich was the problem? I having the same problem.

@wf9a5m75 Did you checked the @FWink  message?
