### ISSUE TITLE
Rendering large number of markers causing the second time map load too slow.

### ISSUE THREAD

**Issue by sabanad** [mapsplugin/cordova-plugin-googlemaps#2314]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

I'm using this plugins version 2.2.9. Overall the plugin works great. There is one problem that I have been facing and unable to identify the issue. 
If I load a large number of markers e.g above 1000 then the second time map load takes alot of time. In that time only a grey screen appears. And sometimes the map doesn't even load. 
Sometimes I get this error in console log
"commandQueueExecutor.js:40 [ignore]CordovaGoogleMaps.removeMap, because it's not ready."
"[ignore]map_1_1259337741613.resizeMap, because removed."

**Comment by wf9a5m75** [comment]
Adding bunch of marker uses lots of memory. It's easy mechanism.

You need to reduce the number of markers, or use market cluster.

**Comment by Textras** [comment]
@wf9a5m75 I know it's subjective, but in your experience what would you deem as being 'a bunch' of markers?
