### ISSUE TITLE
NullPointerException on Android by findClickedDom

### ISSUE THREAD

**Issue by aMUSiC** [mapsplugin/cordova-plugin-googlemaps#2315]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.3.6-beta-20180601-0722 "cordova-plugin-googlemaps"
```

**Current behavior:**

Using 2.3.6-beta-20180601-0722 I have been getting quite a few crash reports through crashalytics (over 40 within the weekend) that seem to be caused by findClickedDom.

**Related code, data or error log (please format your code or data):**

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.containsKey(java.lang.String)' on a null object reference

plugin.google.maps.MyPluginLayout$FrontLayerLayout.findClickedDom (MyPluginLayout.java:418)
plugin.google.maps.MyPluginLayout$FrontLayerLayout.onInterceptTouchEvent (MyPluginLayout.java:569)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2366)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2839)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2456)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2839)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2456)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2839)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2456)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2839)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2456)
com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent (PhoneWindow.java:2831)
com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1863)
android.app.Activity.dispatchTouchEvent (Activity.java:3046)
com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent (PhoneWindow.java:2792)
android.view.View.dispatchPointerEvent (View.java:10228)
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:5344)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:5180)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4620)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4673)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4639)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4781)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4647)
android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4838)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4620)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4673)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4639)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4647)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4620)
android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:7306)
android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:7184)
android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:7145)
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:7416)
android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:185)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:323)
android.os.Looper.loop (Looper.java:143)
android.app.ActivityThread.main (ActivityThread.java:7225)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

**Comment by wf9a5m75** [comment]
Please share the project files that reproduce your issue 100% on GitHub

**Comment by aMUSiC** [comment]
I cannot reproduce the crash on my phone, so I don't know what to look for. I'm just getting many reports from crashalytics with this particular stacktrace, so I thought I should share the stacktrace with you and maybe you could have an idea what might be causing it.

There are no crashes at all on iOS.

I can share my project files with you, but last time I did you said that the project failed to build on your setup.

**Comment by wf9a5m75** [comment]
Without reproducable project, I can not do anything. Thus, I just say thank you for reporting.

**Comment by jtheiss** [comment]
Hi, 
i faced the same error serveral times with 2.3.6:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.containsKey(java.lang.String)' on a null object reference
at plugin.google.maps.MyPluginLayout$FrontLayerLayout.findClickedDom(MyPluginLayout.java:418)
at plugin.google.maps.MyPluginLayout$FrontLayerLayout.onInterceptTouchEvent(MyPluginLayout.java:569)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2511)
```

This is only meant as report/information. 
I am not allowed to share the project so of course i can not expect it to be fixed. 
I am staying with an older version which works good for me.

Thanks and keep up the good work!

**Comment by federicoboschini** [comment]
Hi,
I faced the same crash on Android Pie only (no issue found on API <= 27). I don't know if this information can be somehow useful for you.
I can't share my project so I will temporary downgrade the dependency.

**Comment by Santosh128** [comment]
`java.lang.NullPointerException: 
  at plugin.google.maps.MyPluginLayout$FrontLayerLayout.findClickedDom (MyPluginLayout.java:437)
  at plugin.google.maps.MyPluginLayout$FrontLayerLayout.onInterceptTouchEvent (MyPluginLayout.java:632)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2379)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2842)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2469)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2842)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2469)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2842)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2469)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2842)`


Got the above issue with cordova-plugin-googlemaps 2.5.3 "cordova-plugin-googlemaps"
It not reproduced on our end but many crashes reported in playstore with above log.
Little help will be appreciated.
Thanks
