### ISSUE TITLE
MAP_READY event not getting fired, when getMyLocation does not work

### ISSUE THREAD

**Issue by prabas08** [mapsplugin/cordova-plugin-googlemaps#2316]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-geolocation-android-activator 1.1.2 "Location Activator Cordova P
lugin"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

Sometimes when getMyLocation could not get device location, it is not returning back after timeout (10 seconds). In such situation if I try creating map with following code
"
service.googleMapService.map = plugin.google.maps.Map.getMap(mapDivElem);
var map = service.googleMapService.map;
    map.addEventListener(plugin.google.maps.event.MAP_READY, function()
    {
      alert("Map ready!");
      callback();
    });
"
MAP_READY event is not getting fired.

So the main issue is that, the function plugin.google.maps.LocationService.getMyLocation() is not returning back after timeout ({timeout:5000, enableHighAccuracy:true}), when it can not find the location.

Also not sure, why sometimes, getMyLocation() is failing to get the device's current location.

Am I the only one, who faces this issue with this plugin?

[geoLocComplaint.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2110963/geoLocComplaint.txt)

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please share the project files that reproduce your issue 100% onto GitHub.

**Comment by wf9a5m75** [comment]
ping

**Comment by prabas08** [comment]
Hi this issue is not reproducible everytime. I noticed that getMyLocation is not getting current location only when I am inside my office workarea. When I go out it is working. Also just I noticed that no other apps such as google map, uber could find the current location in my mobile.

I checked google map app on the other phone, it is showing the exact place. The problem happens with Redmi mobile only.

And my worry is that, why the the error function is not getting called after timeout, This makes the plugin not to work, when I try to show the map, thus not displaying map at all.

I have shared the file yesterday with two functions in it (which I use).

Were you able to test whether the timeout behaviour of the app actually work?

I do not think I can provide you the source that reproduce the issue 100%, as I face this issue only on Redmi mobile.

If you need, I will try to create a sample project and provide you.

All I would like to know is, has anybody checked if timeout actually works when app is unable to find current position. because when timeout is not working, it makes whole plugin's functions not to work.

**Comment by wf9a5m75** [comment]
If you don't satisfy this plugin behavior, please use othet plugins, such as cordova-geolocation-plugin.
