### ISSUE TITLE
MarkerCluster.js:809: Uncaught TypeError: Cannot convert undefined or null to object #2313

### ISSUE THREAD

**Issue by jasus** [mapsplugin/cordova-plugin-googlemaps#2318]
**I'm submitting a ...** 
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**
- [x] **Android**
- [ ] **iOS**

**cordova information:**

```
cordova-plugin-googlemaps 2.3.5 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^4.7.0",
"@ionic-native/google-maps": "^4.8.2"
```

**Current behavior:**
I would like to reopen this issue because I think that we should fix it in all cases.
This is the previous issue:
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2313

@wf9a5m75 I saw the comments of @FWink and @Hanzofm. The problem happens when the camera is moving at the same time that you create the marker cluster, then this error occurs.

As @FWink commented he fix it with that:

> I was facing the same issue and I think this is a race condition occuring when the MarkerCluster is created.
> The callback in Map.addMarkerCluster line 1325 can be executed after the onCameraMoved event that we see in the stack trace is triggered. That causes the MarkerCluster._markerMap to be undefined.
> I fixed it by changing MarkerCluster.js line 206:
> `if (self._isRemoved || self._stopRequest) { return null; }`
> to this
> `if (self._isRemoved || self._stopRequest || !self._markerMap) { return null; }`
> No idea if that has any side effects, seems to work fine though.

@wf9a5m75, could you fix it in other way?

Thank you so much.

**Screen capture or video record:**
![image](https://user-images.githubusercontent.com/3764822/41097863-c0a717be-6a59-11e8-9e71-9ecb4104b265.png)

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by jasus** [comment]
I can not share my project files because it's of my company.

But the idea is that I create the marker cluster and at same time I get my current position and move camera to this point, then this error happen.

I don't know if with the @FWink code you can know more about its solution.

Thank you.

**Comment by wf9a5m75** [comment]
No contribution, no help. Make sure your data is correct. MANY beginner people includes string lat/lng pairs.

**Comment by flyonthenet** [comment]
Same issue here:

![image](https://user-images.githubusercontent.com/6421576/41928775-9f6b4d14-7976-11e8-90aa-8aba8a3ec647.png)

**The same code works with version 2.2**

This is the piece of code where I get the error:

```
console.log(history_markers);
map.addMarkerCluster({
	boundsDraw: false,
	markers: history_markers,
	icons: [{ url: 'img/cluster1.png'}]
}, function( markerCluster ) {
	history_cluster = markerCluster;
});

```

history_markers contains position.lat and position.lng as you can see on the screenshot above

Thanks
D.

**Comment by jasus** [comment]
@flyonthenet I suggest that reopen the issue doing reference to this one.
