### ISSUE TITLE
Overwrite MARKER_CLICK animation event to another position

### ISSUE THREAD

**Issue by jasus** [mapsplugin/cordova-plugin-googlemaps#2319]
**I'm submitting a ...** 
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**
- [x] **Android**
- [x] **iOS**

**cordova information:**

```
cordova-plugin-googlemaps 2.3.5 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^4.7.0",
"@ionic-native/google-maps": "^4.8.2"
```

**Current behavior:**
I'm showing a map card when you click on a marker and the map view is centered in the middle of the screen. Is there any chance to change this behavior and move the screen to another position? 

Like a little higher and that the marker is not exactly in the center.

I tried to do that:
```
markerCluster.on(GoogleMapsEvent.MARKER_CLICK).subscribe( (params) => {
        map.animateCamera(...);
});
```
But it doesn't behaves as expected, because the camera do an strange movement.

If you have any doubt, let me know.

Thank you.

**Screen capture or video record:**
![image](https://user-images.githubusercontent.com/3764822/41593286-da848670-73bf-11e8-8720-f8b809b105e1.png)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Marker/README.md#disable-auto-pan

**Comment by jasus** [comment]
Thank you it's perfect for me. You can close the issue.
