### ISSUE TITLE
Method: getMyLocation() not receiving new lat/lng

### ISSUE THREAD

**Issue by dennis-wedevise** [mapsplugin/cordova-plugin-googlemaps#2320]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.3.6
```

**Current behavior:**
I created a simple map with the [My location button]. When I press the button, my current location is retrieved. But as soon as I move and press the button again, the lat / lng is not updated (does not give my current location).

**Expected behavior:**
By pressing the My location button getting the new lat / lng when I move.

**Screen capture or video record:**
Start location shows the correct lat / lng
![img_1753](https://user-images.githubusercontent.com/39722594/41712702-7c5dde38-754b-11e8-9f48-806013189d3e.png)

I am moving and press the My location button again. But i do not receive a new lat / lng.
![img_1754](https://user-images.githubusercontent.com/39722594/41712703-7c766cb4-754b-11e8-8f87-6a7badba77d3.png)

**Related code, data or error log (please format your code or data):**
I have made a test project on Github (Github: https://github.com/dennis-wedevise/googlemaps
) to simulate the problem.

```
var onSuccess = function(location) {
  console.log("onSuccess");
	
  uLocation = location.latLng;
  console.log(uLocation);
	
  map.moveCamera({ target: location.latLng });
	
  var labelLat	= document.getElementById("latlong");
  labelLat.innerText = location.latLng.lat + ' | ' + location.latLng.lng;
};

map.on(plugin.google.maps.event.MY_LOCATION_BUTTON_CLICK, function() {
  console.log("MY_LOCATION_BUTTON_CLICK");
  map.getMyLocation(gmOptions, onSuccess, onError);		
});

```

**Comment by wf9a5m75** [comment]
GPS behavior is depends on devices. Not bug. If you don't satisfy the behavior, please use another location plugin.

**Comment by dennis-wedevise** [comment]
I am very satisfied with the operation of the plugin.

Maybe I do not understand the function: map.getMyLocation() ?

If I look at the documentation: https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Map/getMyLocation/README.md

I see the onSuccess callback that the lat / lng is returned. As you can see in my example, I move myself and then press the Location button again. The onSuccess callback is called every time but without changing the lat / lng

Can you possibly explain what I'm doing wrong? or how I can achieve this?

**Comment by dennis-wedevise** [comment]
@wf9a5m75 is private support possible?
