### ISSUE TITLE
Clustered marker icons with specified dimensions reverting to default ones when redrawn [iOS]

### ISSUE THREAD

**Issue by iz-podpolja** [mapsplugin/cordova-plugin-googlemaps#2321]
**I'm submitting a ...**
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**
- [ ] **Android**
- [x] **iOS**

**cordova information:** 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
Whenever marker icon with specified dimensions within a cluster is redrawn it reverts to what seems to be a set default dimensions (40x24); First rendering is correct, problem only occurs on iOS on subsequent renders.

**Expected behavior:**
Icon should be redrawn correctly, using provided data;

**Screen capture or video record:**
[ios-icons-redrawn-incorrectly.mov.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2125787/ios-icons-redrawn-incorrectly.mov.zip)

**Related code, data or error log:**
xcode console shows the likes of
```
CordovaGoogleMaps[62860:3055070] --->allResults = {
    "marker_19" =     {
        height = 40;
        width = 24;
    };
    "marker_23" =     {
        height = 40;
        width = 24;
    };
}
```

Example marker options used (the only change made is icon is an object instead of url): 
```
{  
    "position":{  
       "lat":21.382314,
       "lng":-157.933097
    },
    "name":"Starbucks - HI - Aiea  03641",
    "address":"Aiea Shopping Center_99-115 Aiea Heights Drive #125_Aiea, Hawaii 96701",
    "phone":"808-484-1488",
    "icon":{  
       "url":"img/marker_asym.png",
       "width":94,
       "height":52,
       "anchor":[  
          58,
          49
       ]
    }
}
```

Any attempt to add markers with following options **while camera movement is in progress** will fail with ``Object.keys(self._markerMap) is undefined``. **This also happens on Android**; Because of this there is an added delay of 500 ms to offset the initial camera zoom. This & the icon object in marker options are the only changes to the example repo.
<img width="851" alt="screen shot 2018-06-22 at 02 56 38" src="https://user-images.githubusercontent.com/17312670/41752695-5d576b7a-75c9-11e8-9f45-e0131492f098.png">

**Issue reproduction repo**
[ios-cluster-marker-icons](https://github.com/iz-podpolja/ios-cluster-marker-icons)

**Comment by wf9a5m75** [comment]
> Any attempt to add markers with following options while camera movement is in progress will fail with Object.keys(self._markerMap) is undefined.

Do not do that.

**Comment by iz-podpolja** [comment]
@wf9a5m75 I know, I only provided the info, so that you know, what are the changes compared to the original. Send you 10$ as thanks for your hard work with the plugin.

**Comment by wf9a5m75** [comment]
Thank you for your donation and information.

**Comment by iz-podpolja** [comment]
Well, but what with the issue itself?

**Comment by iz-podpolja** [comment]
Should I treat this as "won't do"?
