### ISSUE TITLE
Zoom gesture not working after click on marker

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#2323]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.3.2 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.0 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^4.5.3"
"@ionic-native/google-maps": "^4.5.3"
```

**Current behavior:**

The gesture of the zoom works well before i click a marker and i cannot zoom in or out with the zoom gesture.

**Expected behavior:**

The expected behavior will be the zoom gesture working well all the time.

**Extra info**
The map is located in the post.ts file. And to go to the map in the app you have to click in the tab "Propiedades".

I already sent you the invite to the bitbucket repo.

**Comment by wf9a5m75** [comment]
At least these plugins are too old.
```
"@ionic-native/core": "^4.5.3"
"@ionic-native/google-maps": "^4.5.3"
```

You have to reinstall the latest versions.

**Comment by francoro** [comment]
Okay, i will try updating to the lastest versions

**Comment by francoro** [comment]
I find that it throws me an error: markercluster_1027170945544-marker_321 marker is removed
did you know what can be the cause of this error? it can be a marker.remove() ?

**Comment by wf9a5m75** [comment]
You tried to something for removed marker.

**Comment by francoro** [comment]
i fixed the error of the marker removed but it keeps happening. i made a commit with that you can check the project if you want. Meanwhile i will keep trying to find the issue but now its not a console error

**Comment by wf9a5m75** [comment]
```
$> ionic cordova preprare
...
...

[11:29:23]  typescript: src/pages/map/map.ts, line: 19 
            Cannot find module 'driver.js'. 

      L18:  import { Geolocation } from '@ionic-native/geolocation';
      L19:  import * as Driver from 'driver.js';
      L20:  import { LaunchNavigator, LaunchNavigatorOptions } from '@ionic-native/launch-navigator';

[11:29:23]  typescript: src/pages/posts/posts.ts, line: 20 
            Cannot find module 'driver.js'. 

      L19:  import { LaunchNavigator } from '@ionic-native/launch-navigator';
      L20:  import * as Driver from 'driver.js';
      L21:  import { ModalTags } from '../modal-tags/modal-tags';

[11:29:23]  copy finished in 5.82 s 
```

**Comment by francoro** [comment]
i fix it, it was that i have an html element inside the div map i put outside and now it works.Thanks for your support

**Comment by wf9a5m75** [comment]
Congrats :)
