### ISSUE TITLE
MAP_READY event not getting fired and problems on android 4.4

### ISSUE THREAD

**Issue by YeisonVelez11** [mapsplugin/cordova-plugin-googlemaps#2326]
I'm submitting a ... (check one with "x")

    question
    [x ] any problem or bug report
    feature request

If you choose 'problem or bug report', please select OS: (check one with "x")

    [x ] Android
    iOS

cordova information: (run $> cordova plugin list)

cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 2.1.0 "Facebook Connect"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"

**Current behavior:**

      map.on(plugin.google.maps.event.MAP_READY, function() {
              alert("pleasee")
      });

I am using IONIC1,In recent cell phones the map works great, but tested on an Android phone 4.4 the map remains with a white screen and is never displayed. never execute the "MAP_READY" function. I also get this error:

![captura](https://user-images.githubusercontent.com/1949889/41816547-b090d1ca-774d-11e8-8725-6ca4898c4e43.PNG)

what I managed to solve with the implementation of these libraries. (I'm not sure, but at least this problem does not occur)
`
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
`

How can I solve this problem?, thanks

**Comment by wf9a5m75** [comment]
I don't support such a older phone which does not support `Promise` function.

**Comment by YeisonVelez11** [comment]
Thanks...currently with the inclusion of these libraries I no longer have that problem. my problem is that the READY function is not activated. If you could help me, I would be very grateful.

**Comment by wf9a5m75** [comment]
I also don't support older versions. `cordova-plugin-googlemaps 2.3.2 ` is too old. You have to reinstall the plugin.

**Comment by YeisonVelez11** [comment]
thanks for answering. I updated to version 2.3.6 and the problem persists. I also managed to solve the problem of the "promise" error. I do not know why the trigger of the "ready" function does not work. I hope you can help me please. I'm not presenting erors in console. only white screen is showed (withouth logo of google)

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by YeisonVelez11** [comment]
ok I'll do it. You are very kind, besides being intelligent. wait please include only what is necessary.

**Comment by YeisonVelez11** [comment]
https://github.com/YeisonVelez11/errormaps  

fix to promise on the index.html

    <script src="lib/es6-promise.min.js"></script>
    <script src="lib/es6-promise.auto.min.js"></script>

Look file "errormaps\www\js\controllers\ubicaciones.js". this file load the map. to reproduce the error, must be tested on an android 4.4 

thanks. I will be careful

**Comment by wf9a5m75** [comment]
I have no problem on Android 4.4.2.

![capture](https://user-images.githubusercontent.com/167831/41867019-bef74aea-7866-11e8-9b80-c6b84c25bf5e.png)

**Comment by YeisonVelez11** [comment]
do you use these librarys?
<script src="lib/es6-promise.min.js"></script>
<script src="lib/es6-promise.auto.min.js"></script>

**Comment by YeisonVelez11** [comment]
on  a virtual device, not works for me :(   I do not know if it's happened because of the things I removed from my original code. I put you exclusively what is necessary. But when I get home, I'll try again. thank you!

**Comment by wf9a5m75** [comment]
I recommend you throw away Android 4.4 from your target. It's too old device, and no general users use such an old phone. It's waste your time.

**Comment by YeisonVelez11** [comment]
In Colombia, the majority of users do not have such recent phones, so I must guarantee that it works. Do you use these librarys that I put?

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response, I close this thread.
