### ISSUE TITLE
[Question] Reference to marker object in MarkerCluster

### ISSUE THREAD

**Issue by aMUSiC** [mapsplugin/cordova-plugin-googlemaps#2329]
**I'm submitting a ...**  (check one with "x")
- [X] question
- [ ] any problem or bug report
- [ ] feature request

In MarkerCluster, the addMarker member function takes MarkerOptions as a parameter, but the function returns void.

```
    /**
     * Add one marker location
     * @param marker {MarkerOptions} one location
     * @param skipRedraw? {boolean} marker cluster does not redraw the marker cluster if true.
     */
    addMarker(marker: MarkerOptions, skipRedraw?: boolean): void;
```

Is there any way to get a reference to the Marker object that was just added to the cluster?

The reason I am asking for this is that I want to store the marker reference so I can manipulate it later on from other parts of my app (like changing its icon).

I tried to look at the api reference but the link to the MarkerCluster addMarker() method documentation leads to a 404:
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/MarkerCluster/Marker/addMarker/README.md

**Comment by wf9a5m75** [comment]
>Is there any way to get a reference to the Marker object that was just added to the cluster?

No. Because generated marker is removed when it is clustered.

**Comment by wf9a5m75** [comment]
However, you can modify property values in your array. MarkerCluster creates markers with updated values.

**Comment by aMUSiC** [comment]
Does the MarkerCluster subscribe to changes made to the marker array ? Or do I have to remove and recreate the cluster?

For instance if I am at a zoom level when a marker is visible (outside the cluster) and I change the icon value of the marker in the array, will the marker change the icon automatically (assuming that I have used a reference of the array in the cluster)

**Comment by wf9a5m75** [comment]
```
var places = [
  { position: {lat: ..., lng: ..."}, icon : "iconA.png"},
  { position: {lat: ..., lng: ..."}, icon : "iconB.png"},
  { position: {lat: ..., lng: ..."}, icon : "iconC.png"}
];

var markerCluster = map.addMarkerCluster({
  markers: places,
  ...
});

function changeIcon() {
  places[0].icon = "icon_a.png";  // <---  value is affected when marker is regenerated.
}

```

**Comment by aMUSiC** [comment]
So I'll have to redraw the cluster then.

Also, isn't addMarkerCluster() a promise?

**Comment by wf9a5m75** [comment]
Why do you need promise?

**Comment by aMUSiC** [comment]
I don't need a promise, but addMarkerCluster() acts as a promise:

for instance:

```
let ccc = map.addMarkerCluster({...});
console.log('ccc:', ccc);

map.addMarkerCluster({...})
   .then( c => {
       console.log('c:', c);
   });

This is the result:

![image](https://user-images.githubusercontent.com/5752982/41868133-d6b0a92c-78bd-11e8-8b31-4c2abde8ca06.png)

**Comment by aMUSiC** [comment]
Perhaps this is rewritten as a promise by the ionic native library ?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/ReleaseNotes/v2.3.0/README.md#a-callback-is-no-longer-required-for-the-most-part

**Comment by aMUSiC** [comment]
So if I try to do this:

```
let cluster = map.addMarkerCluster({...});
cluster.on(plugin.google.maps.event.MARKER_CLICK, function(position, marker) {
  console.log('position:', position);
  console.log('marker:', marker);
});
```

I get that "on() is not a function"

if I do this:

```
map.addMarkerCluster({...})
  .then( c => {
    c.on(plugin.google.maps.event.MARKER_CLICK, function(position, marker) {
      console.log('position:', position);
      console.log('marker:', marker);
    })
  });
```

I get no errors, but tapping on a marker doesn't do anything (in this case, no console.log)

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by aMUSiC** [comment]
After lots of trial and error I discovered that in order to set an event listener on the cluster you need to subscribe to it.

The code below works as intended:

```
map.addMarkerCluster({...})
  .then( c => {
    c.on(plugin.google.maps.event.MARKER_CLICK)
    .subscribe((data) => {
      console.log('position:', data[0]);
      console.log('marker:', data[1]);
    });
  });
```

I probably need to mention that this is on an ionic project.

Worth noting here that the documentation and the examples for the MarkerCluster are currently innacurate (for ionic builds anyway):

```
      let cluster = map.addMarkerCluster({
        markers: data,
        icons: icons
      });

      cluster.on(plugin.google.maps.event.MARKER_CLICK)
        .subscribe((data) => {
            console.log('position:', data[0]);
            console.log('marker:', data[1]);
        });
```

This will not work with a compilation error:
Property 'on' does not exist on type 'Promise<MarkerCluster>'.

Anyway, I figured it out. Thank you for your help. In the end it would have been so much easier if the references to the markers were always there, and the markers would hide/show based on whether they're in a cluster or not. I'm not sure though if that would be supported by the map sdk.

**Comment by aMUSiC** [comment]
Also, is there any way to change the calculation formula that decides at what distance markers should be clustered together?

**Comment by wf9a5m75** [comment]
If you use `@ionic-native/google-maps`, you have to use `map.addMarkerClusterSync()`
https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/googlemap/README.md#addmarkerclustersyncoptions-orange_book

**Comment by aMUSiC** [comment]
Alright, everything works now. I have one last question. Is there any way to programmatically trigger a click event for a marker that is part of a MarkerCluster (assuming that it's visible)?

**Comment by wf9a5m75** [comment]
There is no way to trigger a marker programmatically so far.

**Comment by aMUSiC** [comment]
How about a way to get an array of all the visible marker instances of the cluster?

**Comment by wf9a5m75** [comment]
All available methods are described in document page.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/MarkerCluster/README.md#api-reference

**Comment by aMUSiC** [comment]
I would like to suggest a feature for the MarkerCluster in a future version:

Expose a redraw function for the cluster, which would remove and redraw all visible markers (not hidden in the cluster) by consulting the markers array. 

Right now if I want to change the icon of a marker (without tapping on the marker) and show it instantly, the only way to do so is to programmatically zoom the camera out, and back in, which is inneficient and looks ugly.

**Comment by wf9a5m75** [comment]
Full source code is open source. If you want to improve the feature, please fork, modify, and send a pull request with test code. That's open source project.

**Comment by benjamin-luescher** [comment]
@aMUSiC I'v got my reference object by searching for a place in my places array which has the same coordinates (with a precision). Maybe you can adjust the precision a little more precisely. I use a precision of "0.000001" which is about 0.1m:

```
public static findPlacesByPosition(places: PlaceModel[], lat: number, lng: number, precision: number = 0.000001): PlaceModel|undefined {
  return places.find(p => {
    return Math.abs(p.lat - lat) < precision && Math.abs(p.lng - lng) < precision;
  });
  }
```
You can then use the above method for your cluster's marker-click listener:
```
cluster.on(GoogleMapsEvent.MARKER_CLICK).subscribe((data) => {
  if (data && data.length !== 0) {
    const placeModel = PlaceModel.findPoiModelByPosition(this.places, data[0].lat, data[0].lng);
    console.log('Clicked Place Model', placeModel);
  }
});
```
