### ISSUE TITLE
Can't interact if some element overlays map div

### ISSUE THREAD

**Issue by girtsuzans** [mapsplugin/cordova-plugin-googlemaps#2331]
Having weird issue, if I put map div in relative position and nothing over it it's loads fine can interact with map.

But if I have absolute positioned div over map and then on click i hide it I can't interact with map.

[cesis_812.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2136846/cesis_812.zip)

**Comment by girtsuzans** [comment]
https://github.com/girtsuzans/cesis_812

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#how-does-this-plugin-work
