### ISSUE TITLE
MarkerCluster.js:809: Uncaught TypeError: Cannot convert undefined or null to object #2313 #2318

### ISSUE THREAD

**Issue by flyonthenet** [mapsplugin/cordova-plugin-googlemaps#2332]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
```

**Current behavior:**
When creating a MarkerCluster,
no markers/cluster of markers are drawn in the map
Error MarkerCluster.js:809: Uncaught TypeError: Cannot convert undefined or null to object
is reported on console

**Expected behavior:**
Markers or cluster of markers should appear according to current zoom level

**Screen capture or video record:**

![image](https://user-images.githubusercontent.com/6421576/41930423-4b92f8b8-797b-11e8-8672-42b3c224b428.png)

**Related code, data or error log (please format your code or data):**

```
console.log(history_markers);
map.addMarkerCluster({
	boundsDraw: false,
	markers: history_markers,
	icons: [{ url: 'img/cluster1.png'}]
}, function( markerCluster ) {
	history_cluster = markerCluster;
});

```
**This code works with version 2.2**

history_markers is array of marker options that contains position.lat and position.lng, as you can see on the screenshot above

Previous issues #2313 #2318

Thanks
D.

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by flyonthenet** [comment]
@wf9a5m75 i see your comment on #2318 
I moved the moveCamera( ) call *after* AddMarkerCluster( )
Some marker are rendered (5 of 9):
No errors in console

![screenshot_20180626-204425](https://user-images.githubusercontent.com/6421576/41933007-f30112ea-7982-11e8-94cf-373ab4ed305c.png)

If a manually pinch to zoom the map, they are rendered:

![screenshot_20180626-204609](https://user-images.githubusercontent.com/6421576/41933182-6bcbe7b8-7983-11e8-9e1c-bed12fed6a60.png)

So i switched to animateCamera( ) and moved the AddMarkerCluster( ) code to the callback
Nope. After animation completes, same error is thrown and no markers on map.

Tomorrow I will share the project files on GitHub - I need to clean up.

Thanks
D.

**Comment by wf9a5m75** [comment]
No sharing code, no help.

**Comment by flyonthenet** [comment]
Actually fixed adding 500ms timeout between moveCamera( ) and AddMarkerCluster( )
By the way, it's only a workaround. Issue remains.

As soon as possible I will post the relevant code in Github
(the entire project is too big to share)

Thanks
D.

**Comment by wf9a5m75** [comment]
Good. Regarding of share your code, please share the code as project structure, because I develop and manage this plugin project in my private time, I don't have enough time for building a new project for testing.

I only test with `git clone`, `npm i`, then `cordova run android / ios`.
If I found a problem, I debug it.

**Comment by wf9a5m75** [comment]
ping

**Comment by vosecek** [comment]
This is same problem which I mentioned months ago: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2252. Adding timeouts helps.

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread.

**Comment by mbunge** [comment]
Animate / MoveCamera returns a promise, execute your cluster builder within Promis.then().
