### ISSUE TITLE
Blank map 5% of time on iOS

### ISSUE THREAD

**Issue by caleb87** [mapsplugin/cordova-plugin-googlemaps#2333]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-battery-status 1.2.4 "Battery"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-hidden-statusbar-overlay 2.0.1 "HiddenStatusbarOverlay"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
About 5% of the time, the map is blank even though MAP_READY has been successfully called. No errors are thrown at all. 

I found that if the page is simply reloaded from the web console, then the map loads every time. So this only happens on a fresh app start, and it only happens roughly 5% of the time.

**Is there a way to test if the map has loaded properly (with tiles)?** 

**What would be the most likely reason for this to happen?**

**Comment by wf9a5m75** [comment]
Please share the project files that reproduce your issue 100% onto Github.

**Comment by wf9a5m75** [comment]
ping

**Comment by caleb87** [comment]
I can't share the code unfortunately :(

I downgraded the plugin version to 2.1.1 and the issue appears to have gone away.

On a side note, I put getMap() on a 5 second timeout so I could watch it start. The few times it went blank, it actually showed the map for a split second, and then it went blank. 

I also tried putting the MAP_READY function on a timeout, thinking that perhaps calling map functions was causing it to die, but it was blank before MAP_READY callback was fired. The app only calls map functions once MAP_READY is called.

Also, the logs in xcode were identical when the map went blank vs when it worked normally.

**Comment by spacesuitdiver** [comment]
@caleb87 @wf9a5m75 having similar issue here. Not sure where to report.

**Comment by caleb87** [comment]
In my case, the map did load, but 1/20 times, it would go blank. I resolved by using an old version. It's probable that my own code caused it to go blank, though it's odd that an old version fixed it.

**Comment by spacesuitdiver** [comment]
@caleb87 @wf9a5m75 so far commenting out this line seems to alleviate the issue and on the JS side we can hide the map until read is fired. https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/CordovaGoogleMaps.m#L227 Thoughts?

**Comment by spacesuitdiver** [comment]
Nevermind, spoke too soon :(
