### ISSUE TITLE
HtmlWindowInfo incorrect anchor position when maker rotate

### ISSUE THREAD

**Issue by anhnhoktvn** [mapsplugin/cordova-plugin-googlemaps#2334]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**

HtmlInfoWindow anchor is in incorrect position when marker rotated.

**Expected behavior:**

HtmlInfoWindow should follow correct position when marker rotated. 

**Screen capture or video record:**
![screencap](https://user-images.githubusercontent.com/2435820/42121455-b704c3a2-7c59-11e8-8509-0c8a1fa76351.png)
![screencap3](https://user-images.githubusercontent.com/2435820/42121457-bc59ae6c-7c59-11e8-8a0f-d6b60ba9f1ab.png)
![screencap4](https://user-images.githubusercontent.com/2435820/42121459-bfedaca4-7c59-11e8-8eba-fa85dd7f55c5.png)

**Related code, data or error log (please format your code or data):**
Based on [Demo Repo](https://github.com/mapsplugin/HelloGoogleMap/blob/master/www/index.html)
```
      var marker = map.addMarker({
        position: pos,
        draggable: true,
        title: 'zz'
      })

        let html = `
<div class="flex flex-column">
  <div class="flex outline">
    <div class="w-50 outline">Bs:</div> 
    <div class="w-50 outline">${11}</div>
  </div>
  <div class="flex outline">
    <div class="w-50 outline">Bs:</div> 
    <div class="w-50 outline">${11}</div>
  </div>
</div>
`
        let htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow()
        htmlInfoWindow.setContent(html)
        htmlInfoWindow.open(marker)

        let rots = [0, 90, 180, 270]
        let index = Math.round(Math.random() * 3)
        marker.setRotation(rots[index])
```

**Comment by wf9a5m75** [comment]
HTMLInfoWindow does not support rotated marker.

**Comment by anhnhoktvn** [comment]
Could we add a feature to manually set position for HtmlInfoWindow ?

**Comment by wf9a5m75** [comment]
nop

**Comment by wf9a5m75** [comment]
I don't mind if you folk this repo, and modify the code for you.
