### ISSUE TITLE
MAP not responsive (i.e cannot click anywhere) in Android 7.0 and App crashing in Android 4.4.2 after upgrading plugin to 2.3.6

### ISSUE THREAD

**Issue by sabanad** [mapsplugin/cordova-plugin-googlemaps#2335]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
com.darktalker.cordova.screenshot 0.1.5 "Screenshot"
cordova-android-support-gradle-release 1.3.0 "cordova-android-support-gradle-rel
ease"
cordova-pdf-generator 2.0.1 "PDFGenerator"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-network-information 1.3.2 "Network Information"
cordova-plugin-networkinterface 1.2.0 "NetworkInterface"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
cordova-sqlite-storage 2.1.4 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"

**Current behavior:**
MAP not responsive (i.e cannot click anywhere) in Android 7.0 and App crashing in Android 4.4.2 after upgrading plugin to 2.3.6. It used to work fine with version 2.1.1. But since I upgraded to 2.2.9 Map become unresponsive in android 7.0. Now I upgraded to version 2.3.6, expecting it will get resolved but now app is totally not working in android 4.4.2 just a white screen (and the only issue in console.log is Uncaught ReferenceError: Promise is not defined in file googlemaps-cdv-plugin.js:40". Please help.

**Related code, data or error log (please format your code or data):**
There is no error log.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by sabanad** [comment]
Sure I'm just creating a test project using almost the same code. Will share in few hours.
Thanks for the quick response.

**Comment by wf9a5m75** [comment]
Thanks. Please make sure the sample project is able to reproduce your issue 100%.

**Comment by sabanad** [comment]
I have shared the GitHub repository with you. Please check have send you an invitation.
The issues are:
Android 4.4 and Android 4.4.2
1- Just a white screen. Some issue related to promise (with version 2.3.6) - tested using emulator and device
2- Map not responsive. Clicking, dragging doesn't work in android 4.4.2 (with version 2.2.9) tested using device.
Android 7.0
2- Map not responsive. Clicking, dragging doesn't work (with version 2.2.9 and 2.3.6) - tested using emulator and device.

**Comment by wf9a5m75** [comment]
I haven't received any invitation.

**Comment by sabanad** [comment]
That's strange, I gave your "wf9a5m75" account write access to bitbucket repository. Going to make it public, so you can access it.
Here's the link,
https://bitbucket.org/Sabanad/googlemapsampleapp/

**Comment by sabanad** [comment]
Hi, we're you able to reproduce the issue?

**Comment by wf9a5m75** [comment]
Fixed. Please reinstall the plugin from the multiple_maps branch.
![2335](https://user-images.githubusercontent.com/167831/42190743-aa6f3184-7e13-11e8-92e5-24f296e60ac5.gif)

**Comment by sabanad** [comment]
Great, thanks. Map being unresponsive in android 7.0 issue has been resolved.  :) 
But now I'm unable to click on the actions links inside htmlinfowindow. Whenever I click inside htmlinfowindow icons located at the bottom, htmlinfowindow closes. I have pushed the latest code please if you can check that would be a great help. Also the app is showing a white screen whenever I start it in android 4.4.2 the issue as shown in the screenshot below
![image](https://user-images.githubusercontent.com/32160960/42212602-00e11728-7ed0-11e8-801f-a83b7cd2fd92.png)

**Comment by sabanad** [comment]
ok so you can ignore the promise issue in android 4.4.2 which is causing the app not to start. I was able to fix it using crosswalk plugin. I hope that's ok, I mean using this plugin won't affect in performance with your plugin?  Following are the plugin configuration.
<plugin name="cordova-plugin-crosswalk-webview" spec="^2.4.0">
        <variable name="XWALK_VERSION" value="23+" />
        <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
        <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
        <variable name="XWALK_MODE" value="embedded" />
        <variable name="XWALK_MULTIPLEAPK" value="false" />
    </plugin>
Please let me know if anything needs to be removed/change due to the googlemaps plugin
But please if you could fix the htmlinfowindow issue that would be really great. 
Thanks

**Comment by wf9a5m75** [comment]
Before asking me to do something, please make sure your code at first.
No marker is appeared on the map when run your app on Android 4.4.2.
![2335](https://user-images.githubusercontent.com/167831/42231714-22a580ee-7ea1-11e8-93e8-1819b3918927.gif)

**Comment by wf9a5m75** [comment]
Since XWalk is already deprecated, I don't support it anymore.
However here is description.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/crosswalk/README.md

I will drop support Android 4.4.x on the next version, because it is too old, and there is no one use such an old device anymore.

**Comment by sabanad** [comment]
Oh that's strange. Sorry about it but the marker appears in all my devices, I have just verified using devices that run android 4.4.2, 7.0 and 7.1
If possible can you check it on any other device than android 4.4.2. Please directly download the apk located in this folder, I have just generated it 
googlemapsampleapp\TW_App\platforms\android\build\outputs\apk\android-debug.apk
Also pushing the latest code again.
If you generate a new build using the code rerun the app second time. The first time the map doesn't load. Completely my fault sorry about that.


![screenshot_20180703-223118 1](https://user-images.githubusercontent.com/32160960/42235515-6bfb6eaa-7f11-11e8-8b59-0aa7c08a4705.png)

**Comment by sabanad** [comment]
Hi, were you able to reproduce the issue?

**Comment by sabanad** [comment]
Hi @wf9a5m75 any update on the issue please. If you could please help me with "htmlinfowindow links not working" issue, I'll be really grateful to you.

**Comment by wf9a5m75** [comment]
Free support is only available when I have free time. I don't have enough time to tackle with this so far. Please wait until I'm ready.

**Comment by sabanad** [comment]
Sure no problem, I understand. Thank you.

**Comment by sabanad** [comment]
Hi, i understand you must be busy these days, but I was just wondering if
you’ve had time to look into the issue.
Thanks

**Comment by wf9a5m75** [comment]
Sorry for late, I have been really busy these days. I fixed the problem. Try it.

**Comment by sabanad** [comment]
No problem, I understand. Thank you so much. Just verified everything is working perfectly. Thanks again.
