### ISSUE TITLE
maker follow the smartphone position

### ISSUE THREAD

**Issue by raphaelluiz128** [mapsplugin/cordova-plugin-googlemaps#2336]
, would you know if I can use this plugin to follow the current position of the cell phone? for example go changing the position of the "maker" after a few steps?
#--------------------
# private support
#--------------------
Even if you don't want to discover anything including screen captures or screen records,
please ask me to private support.
I ask you to donate $100 USD to the maps plugin project,
then I make a private space, then support it.

--->

**I'm submitting a ...**  (check one with "x")
- [x ] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
This plugin just returns the value of GPS. Hoe accurate is depends on device.

**Comment by wf9a5m75** [comment]
If you want to follow user long time, I recommend you use other plugins, such as https://github.com/pmwisdom/cordova-background-geolocation-services
