### ISSUE TITLE
Maps flashing

### ISSUE THREAD

**Issue by raphaelluiz128** [mapsplugin/cordova-plugin-googlemaps#2337]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

insert the output from the command here
```


C:\Users\AdmLocal\Desktop\mot2 ruan rap>cordova plugin list
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-android-play-services-gradle-release 1.4.3 "cordova-android-play-services-gradle-release"
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-open-native-settings 1.5.1 "Native settings"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zeep 0.0.4 "Zeep"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

the map flashes, as if it were updating every 10 seconds

**Expected behavior:**

just do the 'maker' wandering around on the map and do not keep updating the map all the time, I believe that the map blink should have relation to the constant updates.

**Screen capture or video record:**
<!--

[Android]

[map flashing.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2167605/map.flashing.zip)

**Related code, data or error log (please format your code or data):**
No error in the debug is show.
```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by raphaelluiz128** [comment]
this happens when I use "watch position" and the position is changed. Is there any way to just update the 'maker' position instead of loading the map again?

**Comment by raphaelluiz128** [comment]
DisplayMap() {
    
    // carrega a psiçao atual do dispositivo
   // this.geolocation.getCurrentPosition().then(position => {
    this.geolocation.getCurrentPosition().then(position => {  
   let latLng = new google.maps.LatLng(
        position.coords.latitude,
        position.coords.longitude
      )
      let mapOptions = {
        center: latLng,
        zoom: 16,
        disableDefaultUI: true,
      }
      this.map = new google.maps.Map(this.mapElement.nativeElement, mapOptions)
      let icon = './assets/image/TELA_31-09copiar2.png'
      //add marcador no mapa
      var myLocationMarker = new google.maps.Marker({
        map: this.map,
        position: latLng,
        icon: icon,
      })
    })

  }

**Comment by wf9a5m75** [comment]
`google.maps.Map` is [Google Maps JavaScript API v3](https://developers.google.com/maps/documentation/javascript/tutorial), which is not this plugin.
