### ISSUE TITLE
with Ionic when executing a callback that interacts with map from a child page results in blank map?

### ISSUE THREAD

**Issue by omicr0n** [mapsplugin/cordova-plugin-googlemaps#2339]
Trying to track down this problem.  I'm fairly new to angular and ionic so could behalf the problem but I'm using the nav control to push() (display) a new page passing a callback function from the current page through the push.  On the pushed page I'm then doing some processing and then say want to add a new marker to the map on the previous/parent page I execute the callback function that was passed through which does whatever interactions with the map then use the nav control pop() function to return back to the map which is then blank, doesn't seen to matter what kind of map interaction is done in the callback function results in map being blank when coming back to the page.

Originally I was trying to add a new marker in the callback but changed it to just call animatecamera() to move the map to another position, now I understand that the map is technically not visible or the active page on the screen so don't know if that has anything to do with it and just have to change the logic of my code.  I added plugin.google.maps.environment.setBackgroundColor('green'); to the maps page ionviewdidenter function() which when it comes back to the map page from the pop() it just shows a green background so don't know if that means anything...

I don't know if its because I'm doing camera manipulations that its causing this.  I guess I should try to just add a new marker and see what happens without any camera manipulations or probably the more proper way would be the pass the info back the parent/pop page to process on it.

**Comment by wf9a5m75** [comment]
Too long description. Please write your question more simply.

**Comment by omicr0n** [comment]
Main page (with map)  button pressed to show another page passing a callback function from current page.

```
let params = {
   callback: this.someMapInteractionCallback
};

this.navCtrl.push(SomeOtherPage, params);

someMapInteractionCallback() {
   this.map.animateCamera({
      target: {latitude: 39.8283, longitude: -98.5795},
      zoom: 4
   });
}
```

SomeOtherPage, execute the callback that was passed through then pop() back to the map page results in map not showing now.

```
   this.callback().then(() => {
      this.navCtrl.pop();
   });
```

**Comment by wf9a5m75** [comment]
Use `map.setDiv()` for detach the map from webview, then `map.setDiv(div)` for attaching thr map again

**Comment by omicr0n** [comment]
I actually do have that, I have this on my main page.

```
ionViewDidLeave() {
    plugin.google.maps.environment.setBackgroundColor('red');
    this.mapsProvider.map.map.setVisible(false);
    this.mapsProvider.map.map.setDiv(null);
    plugin.google.maps.environment.setBackgroundColor('red');
}

ionViewDidEnter() {
    plugin.google.maps.environment.setBackgroundColor('green');
    this.mapsProvider.map.map.setDiv(this.mapsProvider.map.mapElement.nativeElement);
    this.mapsProvider.map.map.setVisible(true);
    plugin.google.maps.environment.setBackgroundColor('green');
}
```

Which just results in when I ```this.navCtrl.pop();``` from ```SomeOtherPage``` a screen with a green background IF I call any camera manipulation functions in the callback function.

**Comment by omicr0n** [comment]
Indeed as I have found that is so; I don't know if that is clearly marked somewhere or just considered common sense :).  I naturally kind of expected it to fail or not work; just silently.  But it just completely breaks if you try too.  

Though the word manipulate can be taken multiple ways as you can add markers to a map that is detached which you'd kind of think would be manipulating the map as it adds a marker on the map and what not...  but apparently that's fine and its just when you manipulate the camera position (and who knows what else) that it breaks completely.

**Comment by omicr0n** [comment]
Another quick question I have while I'm here... is there a function or something to like refresh/redraw the map?  

TL;TR details...
What I mean by that is sometimes in my app when interacting around with things, it's like the screen on the device freezes and looks like it didn't do what you wanted it to do its not until I touch the screen and like move around on the map that things 'kick in' and it shows the page.

I have two main instances where that happens, one is a side menu with buttons that when clicked loads a bunch of markers on the map then uses the bounds of the markers to animate camera to those bounds.  90% of the time it works as should and loads up the markers and goes to the bounds of them all, the other 10% after clicking the buttons you can see in the console log that its processing the action and adding the markers and doing everything as it should accept your screen is still just a blank map still like nothing happened.  It's not until I touch the screen and drag my finger to move around the map that all of a sudden the page/device/map wakes up shows the map all of a sudden with the markers and camera already at the bounds.

Another instance it happens on is related to the same area in my original question here where sometimes when `.pop()` back to the main/map page again you'll see in the console it did navigate back and its running and processing everything for that page correctly but your device screen is like frozen and still showing the previous page UI you were at and once again touching the screen and dragging finger to interact causes things to kick in and redraw and show the map page.

**Comment by wf9a5m75** [comment]
>is there a function or something to like refresh/redraw the map

All functions are documented. If there is no function, answer is no.
