### ISSUE TITLE
please implement fitBounds()

### ISSUE THREAD

**Issue by hirbod** [mapsplugin/cordova-plugin-googlemaps#234]
Dear Masashi,

sorry for asking another feature, but I'm missing one of the most important functions: fitBounds(latLngBounds)

I know I can set the target with latLngBounds but I need a way to have a proper zoom level set automatically. If you can't provide fitBounds, maybe you have another idea?

**Comment by sam-lex** [comment]
Hi, is it possible to "fitBounds" with custom margins? for example, an 80 pixels margin from the bottom (some floatings controls over here).

At first I thought of just adding another point like 100m or 200m to the south, but this work-around has some flaws with zooming levels which will depend highly on where the other points are located, sometimes 200m is not enough to make the space. Any ideas? Thanks;

**Comment by Hirbod** [comment]
You could use panBy(). Please have a look at the documentation

**Comment by sam-lex** [comment]
oh hey, thanks for the suggestion. But I'll keep looking for another solution, with panBy(), I'd run into the problem of having a point right at the top going out of the screen if I "panned" it up to show the bottom points...
