### ISSUE TITLE
undefined is not an object (evaluating 'map.getDiv')

### ISSUE THREAD

**Issue by giladrom** [mapsplugin/cordova-plugin-googlemaps#2340]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
com.unarin.cordova.beacon 3.6.1 "Proximity Beacon Plugin"
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-ble-central 1.2.2 "BLE"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-facebook4 1.10.1 "Facebook Connect"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-hockeyapp 5.1.2 "HockeyApp"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-ionic 4.1.7 "IonicCordova"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.17dev "cordova-plugin-ionic-webview"
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-nativegeocoder 3.1.1 "NativeGeocoder"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.2 "Toast"
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
phonegap-plugin-barcodescanner 7.0.2 "BarcodeScanner"

package.json:
"cordova-plugin-googlemaps": "^2.3.6",
"cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.7.0",

"@ionic-native/core": "^4.7.0",
"@ionic-native/google-maps": "^4.8.2",
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

The app is an Ionic/Cordova Multiple Tab app. The map is only used in a single tab.

The app loads fine and the map behaves as expected at all times. This issue only happens if I run the app and then leave the phone alone for several hours (overnight). When I pick up my phone in the morning, the app itself still runs but the map is not displayed (blank div element) and I get the following error in my Ionic dashboard:

```
TypeError: undefined is not an object (evaluating 'map.getDiv')
at _remove (CordovaGoogleMaps.js:714:16)
at ? ([native%20code]::)
at callback (BaseClass.js:113:21)
at trigger (BaseClass.js:68:25)
at remove (Map.js:655:15)
at ? (vendor.js:70879:57)
at onInvokeTask (vendor.js:4971:43)
at runTask (polyfills.js:3:10844)
at invokeTask (polyfills.js:3:16801)
at n (polyfills.js:3:66)
```

I am not calling remove()/destroy() at any point. I have also added exception handling to report any error
with map creation or modification but nothing ever gets reported other than this specific exception. 

I have tried to recreate it manually by repeatedly closing and relaunching the app and by simulating iOS background app termination (memory clearing trick using home button) but I can not do it. It only happens after several hours of being left alone.

**Expected behavior:**

Map should load normally if app is relaunched after a few hours. 

**Screen capture or video record:**

I'll add a screen capture if you think it will help.

**Related code, data or error log (please format your code or data):**

Since this is a big project, I can not share it on GitHub at the moment, and the issue is difficult and time consuming to recreate. I realize this is very little information, but since the error message is always identical, it would be helpful if you could point me in the direction of where I need to look and I can attempt to debug this myself.

Thank you!

**Comment by wf9a5m75** [comment]
No sharing project, no help. Please learn this plugin with new project.
