### ISSUE TITLE
HtmlInfo window content not clickable if HTML structure is very simple

### ISSUE THREAD

**Issue by chernobil** [mapsplugin/cordova-plugin-googlemaps#2342]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
When you have a HtmlInfoWindow for a marker, with a button or link in it (for example) and you try to click the button, the click goes below the info window and on the map.

**Expected behavior:**
Html elements in the info window to be above the map and to be clickable

**Screen capture or video record:**
![device-2018-06-29-173717](https://user-images.githubusercontent.com/1734334/42530226-4b3df138-8489-11e8-82a7-ed065846d83a.gif)

**Related code, data or error log (please format your code or data):**
Here is a fresh new codrova project only with the plugin, one marker and one info window
[DemoRepo](https://github.com/chernobil/GoogleMapsPluginHtmlInfoWindow)

**Comment by wf9a5m75** [comment]
Please reinstall from the multiple_maps branch.

**Comment by chernobil** [comment]
Still doesn't work. I think that the bug is introduced with version 2.3.X. I'm using now 2.2.9 and it is all good

**Comment by wf9a5m75** [comment]
I figure out the reason. It seems if html structure is simple, `window.onload` works before attaching the event listener of this plugin.

So I fixed the plugin code. Please reinstall the plugin.

```
$>rm -rf plugins/cordova-plugin-googlemaps

$> cordova platform rm android

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...

$> cordova platform add android
```
