### ISSUE TITLE
Polyline with arrow

### ISSUE THREAD

**Issue by Hanzofm** [mapsplugin/cordova-plugin-googlemaps#2343]
Hi,

Is possible to add icons with this plugin to the polylines like in native way?

var line = new google.maps.Polyline({
    path: lineCoordinates,
    strokeOpacity: 0,
    **icons: [{
      icon: lineSymbol,
      offset: '0',
      repeat: '20px'**
    }]

Thanks a lot

**Comment by wf9a5m75** [comment]
nop.

**Comment by wf9a5m75** [comment]
Although there is no `arrow` function, you can still calculate the position of percentage of a path.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/utilities/geometry/spherical/interpolate/README.md
