### ISSUE TITLE
Can not load image file for marker if app runs on WKWebView but url is local path

### ISSUE THREAD

**Issue by eskhool** [mapsplugin/cordova-plugin-googlemaps#2344]
the default google icons show up on the map in iOS...not the marker icons specified using the relative file path. Same path and file works fine on Android. 

maps.map.addMarker({
    icon: 'img/marker.png',
    position: getPos(location)
  });

everything else seems to work okay.

Versions:
Cordova: 8.0.0
Cordova-ios:4.5.4
Cordova-plugin-googlemaps: latest from multiple maps branch

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by eskhool** [comment]
@wf9a5m75, will the project files matter? If the android side works perfectly with the above code and the marker is not showing up in iOS only?

Since other things are working, this seems like a bug in the iOS implementation.

can you let me know specifically which files/settings you want to see please?

**Comment by wf9a5m75** [comment]
>the project files matter

Yes, it's matter. It's really depends on your code.
If the plugin bug, I should receive more many reports, but so far only you.

Please share your project files everything in order to reproduce your issue certainly.
I will do following commands:

```
$> git clone (your git repo)

$> cd (your project)

$> npm i

$> cordova prepare

$> cordova run ios
```

So please share your project files
I don't ask your real code. You just create a new project that reproduce your issue 100%.
Or you just share your private repo to me.

**Comment by wf9a5m75** [comment]
ping

**Comment by eskhool** [comment]
@wf9a5m75, unable to reproduce in a simple demo app....now trying to isolate the code in my app which can reproduce this issue. Another day or so and will revert.

**Comment by eskhool** [comment]
it seems to be a conflict with another plugin. trying to isolate in a new project. will get back with the same

**Comment by eskhool** [comment]
So finally was able to see this error show up

`map_0_74007158782 – "Can not load image from 'file://var/containers/Bundle/Application/C30EBE76-00DA-4CB4-BF6B-7862173A1B04/Demo.app/www/./images/marker.png
`
I am using the following code to create the marker. For some reason the relative path www/./images is not working
```
        local_map.addMarker({
          icon: 'static/img/transport/bus.png',
          position: {
              lat: 28,
              lng: 77
          }
      });

```

**Comment by eskhool** [comment]
Also I can confirm that using the remote debugger attached via Safari, I can create the icon with the marker as long as I give the full path but that should not be needed. Any ideas as to why the full path may be required

**Comment by eskhool** [comment]
@wf9a5m75, finally I was able to isolate the problem down to the wkwebview plugin. 
As the UIWebView is deprecated, wkwebview should definitely be supported. 

I setup a very very simple demo to confirm it. If you need it will send it over but it confirm the marker problem with wkwebview without any other dependencies

**Comment by wf9a5m75** [comment]
Please share your project files that reproduce your issue 100% onto GitHub

**Comment by wf9a5m75** [comment]
Thank you for sharing demo repo. The problem is fixed. Please reinstall the plugin from the multiple_maps branch.

**Comment by eskhool** [comment]
Seems to be fixed. Thanks for the emergency 2.3.8 emergency
