### ISSUE TITLE
Migrating from version 1.4.5 to 2.3.6 maps does not show and app is broken. (Sample project provided)

### ISSUE THREAD

**Issue by Xpedigo** [mapsplugin/cordova-plugin-googlemaps#2345]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**
- [ x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

If we migrate in config.xml from version 1.4.5 to 2.3.6, buttons in html pages are not clickable anymore and map is white. Reverting back to 1.4.5 and everything works just fine.

**Expected behavior:**

Same as the version 1.4.5, the map should have shown and the button is clickable.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

### I created specially for your a whole sample project, with a readme.md file where you will find everything. ###
I invited you, this is a private repo call "cordova-gmap-sample-error". 

Thank you for your help. If we have to pay for your support, please send an estimate and invoice

Regards.

**Comment by wf9a5m75** [comment]
I recommend you to recreate bland new project

**Comment by Xpedigo** [comment]
**This is a brand new project,** let's take a look to the private repository I gave it to you. 

Please have a look to the repo I share with you, I take the time to prepare that for you. I need an answer please. If you want money we can pay, we are a delivery company in Canada using your plugin into our app we need this to work with our platform. 

It seems there is a problem with the transition management with the last version of your plugin.

Thank you.

**Comment by wf9a5m75** [comment]
This thread moved to private repository. I close this thread.
