### ISSUE TITLE
Does map creation always ask for user location?

### ISSUE THREAD

**Issue by aMUSiC** [mapsplugin/cordova-plugin-googlemaps#2348]
**I'm submitting a ...**  (check one with "x")
- [X] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

When I create a new map (through the ionic wrapper GoogleMaps.create ) I always get a prompt on android to access my location, even if in the map options I set controls.myLocation, controls.myLocationButton and controls.compass to false. Does the map always ask for the user's location upon creation no matter what?

**Comment by wf9a5m75** [comment]
This plugin only asks when you execute `map.getMyLocation()/LocationService.getMyLocation()` or `controls.myLocation = true` if your app does not have the geolocation permission.
(`controls.myLocation = true` causes Google Maps API asks the permission)

Check your code, I guess other plugins request the permission.

If you doubt me, check the all source code. Every source code are open ;)
