### ISSUE TITLE
Can the "Location Services not Available" prompt be disabled for ios?

### ISSUE THREAD

**Issue by aMUSiC** [mapsplugin/cordova-plugin-googlemaps#2350]
**I'm submitting a ...**  (check one with "x")
- [X] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**

Whenever I call map.getMyLocation() on ios (and I have location services turned off) a popup window comes up telling me to go to settings and enable them. As I would like to control what happens in the flow of my app if location services are not enabled, is there a way to disable that popup?

**Comment by wf9a5m75** [comment]
This plugin does not show up any popup.

`Map.getMyLocation()` is an alias of `LocationService.getMyLocation()`.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/LocationService.js
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/PluginLocationService.m

Can you find any `alert()` dialog, or any popup command in the source code?

**Comment by aMUSiC** [comment]
The message in the dialog is the one found here:

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/strings/pgm_Localizable_en.json

```
"LOCATION_IS_UNAVAILABLE_ERROR_TITLE" : "Location Service is not available",
  "LOCATION_IS_UNAVAILABLE_ERROR_MESSAGE" : "This app needs to access your location. Please turn on \"Settings > Privacy > Location Services\"",
```

And yes I can find the the alert in PluginLocationService.m

```
NSString *LOCATION_IS_UNAVAILABLE_ERROR_MESSAGE = [PluginUtil PGM_LOCALIZATION:@"LOCATION_IS_UNAVAILABLE_ERROR_MESSAGE"];
        UIAlertController* alert = [UIAlertController alertControllerWithTitle:LOCATION_IS_UNAVAILABLE_ERROR_TITLE
                                                                       message:LOCATION_IS_UNAVAILABLE_ERROR_MESSAGE
                                                                preferredStyle:UIAlertControllerStyleAlert];
```

**Comment by wf9a5m75** [comment]
Ah, I see. I forgot it.
However, the alert dialog is useful for most people.

Well, please use other geolocation plugin, such as `cordova-geolocation-plugin`

**Comment by wf9a5m75** [comment]
How about creating a new method, such as `LocationService.hasPermission()`?

**Comment by aMUSiC** [comment]
That would be even better. Can this work both for ios and android?

**Comment by wf9a5m75** [comment]
Done

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/v2.0-demo/blob/master/www/LocationService/hasPermission.html

**Comment by aMUSiC** [comment]
Wow that was fast!!!!
