### ISSUE TITLE
Map does not resize when containing div style is changed

### ISSUE THREAD

**Issue by AppwareDev** [mapsplugin/cordova-plugin-googlemaps#2351]
**I'm submitting a ...** 
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**
- [ ] **Android**
- [x] **iOS**

**cordova information:** 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
In an Ionic v1 project (not using ionic native) the map does not resize to the adjustable height of the containing div when the "Resize" button is tapped. I've identified a reproducible method of getting the map to behave as expected but it is far from ideal behaviour:

1. Run the App on an iOS device
2. Open the side menu by tapping the hamburger icon
3. You should notice that you cannot tap the menu items that are inline with the map i.e. "Home, Item 2, item 3, item 4". Tap a menu item lower down i.e. "Item 10". The map will now shift right, as it should have done when the side menu opens.
4. Now tap "Item 2"
5. Open the side menu by tapping the hamburger icon
6. Tap "Home"
7. Tap the button labelled "Resize Map" at the top left of the map
8. Open the side menu by tapping the hamburger icon
9. Tap "Home". 

The Map will now expand as it should have done when the "Resize Map" button was tapped. Close the menu and tap the "Resize Map" button again and you'll see the map doesn't shrink again until you repeat steps 8 & 9 (note the 'Google' logo at the bottom left of the map doesn't shift up until these steps are repeated).

Note that I've applied [this CSS fix](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/867#issuecomment-209188623) for a semi-related issue with the map. Remove the CSS from line 37 onwards in www/css/style.css to see the issue this fixes.

I have also tried the [suggested fix here](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1802#issuecomment-335202309).

**Expected behavior:**
The Map should resize to the height of the containing div when the "Resize Map" button is tapped and sidemenu buttons should work when tapped.

**Screen capture or video record:**

[2018-07-17 17.36.54.mp4.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2202566/2018-07-17.17.36.54.mp4.zip)

**Related code, data or error log (please format your code or data):**
[Demo App repository here](https://github.com/AppwareDev/Google-Maps-Plugin-Bug-Demo)

Add your API keys in config.xml

**Comment by wf9a5m75** [comment]
`cordova.fireDocumentEvent('plugin_touch')`
