### ISSUE TITLE
Change menssage location allow user

### ISSUE THREAD

**Issue by olmosleo** [mapsplugin/cordova-plugin-googlemaps#2354]
Hi Masashi,

First of all thank you for making this wonderful plugin, I am writing to you about the fact that I am in the process of publishing my apps in the apple store. These guys checked for the first time the apps where they tell me the following:

￼We noticed that your app requests the user's permission to access their location￼ but does not clarify the use of this feature in the permission modal alert.

Next Steps

To solve this issue, please review the permission modality alert to specify why the app is requesting access to the user's location.

Is it possible to modify the "Allow" apps "to access your location while you are using the apps?" - Show your location on the map.

This this the menssage

https://drive.google.com/file/d/16i-lJ7AvMWd4x5VEwEhIw1MgtXJmBExk/view?usp=sharing

Thanks for all..

Leo

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps#install-optional-variables

`LOCATION_WHEN_IN_USE_DESCRIPTION` and `LOCATION_ALWAYS_USAGE_DESCRIPTION`

**Comment by olmosleo** [comment]
Thank Masashi,

I start again with both variables when install the google-maps plugin and i see message is change! thanks alot for you help.. right now we still waiting again to apple proved the apps!.

- https://drive.google.com/file/d/1sLwfRHoUTXPKl5oVAqRxK3lIx0mxEHV1/view?usp=sharing

Leo.

**Comment by wf9a5m75** [comment]
Good luck!
