### ISSUE TITLE
Error getting my location using the request-location-accuracy plugin

### ISSUE THREAD

**Issue by elchory96** [mapsplugin/cordova-plugin-googlemaps#2356]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.

```
![screenshot_20180722-101424](https://user-images.githubusercontent.com/18226156/43047130-94ba4f24-8d98-11e8-91f6-45514127ab9a.png)

![screenshot_20180722-101432](https://user-images.githubusercontent.com/18226156/43047132-99f63318-8d98-11e8-9aac-ee899b5fcd87.png)

Hello, good day, what happens is that I need to activate the gps as long as I do not have it activated, and for that I am using the Location Accuracy plugin, what happens is that when it asks to activate the gps it enters the function of obtaining my position but does not execute it, does not add the marker to the map.

Please help, I'm desperate with this.

Thank you.

**Comment by wf9a5m75** [comment]
Ask to the Location Accuracy plugin author. This plugin is not related.

**Comment by elchory96** [comment]
Is that the plugin correctly activates the gps but when you get the current location with this.map.getMyLocation () does not execute it, it does not enter the .then () nor the .catch ().

Can I share my repository?

**Comment by elchory96** [comment]
I realized, that when the gps is inactive and that it calls the map, and when the GPS status changes to active, the function this.map.getMyLocation () does not run, but when it exits and reopens the application already with the active GPS already recognizes it.

In itself, the this.map.getMyLocation () function obtains the state of the gps that it has at the beginning, it does not hear the event from inactive to active.

**Comment by elchory96** [comment]
Pity, The Location Accuracy plugin was working correctly before having to update the google maps plugin, now for some reason the map.getMyLocation() does not work anymore when the status of the GPS changes from inactive to active, likewise the google maps plugin It is very good and even so I need it 100%, I have to use a third plugin "Geolocation".

I would recommend reviewing this issue of changing the status of the GPS and the getMyLocation function in ionic because the truth was working correctly before the update to 2.3.8
