### ISSUE TITLE
sdkVersion

### ISSUE THREAD

**Issue by sepullupes** [mapsplugin/cordova-plugin-googlemaps#2358]
i already set min sdk to 20 but still got same error

Error		 uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:tbxml-android:] C:\tmp\android\android\intermediates\exploded-aar\tbxml-android\AndroidManifest.xml	iJaperunC

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/tbxml-android/blob/master/tbxml/src/main/AndroidManifest.xml#L5
