### ISSUE TITLE
New mark don't show in map

### ISSUE THREAD

**Issue by dekonunes** [mapsplugin/cordova-plugin-googlemaps#2361]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.9-beta-20180718-1052 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

insert the command here
```
this.map.on(GoogleMapsEvent.MAP_LONG_CLICK).subscribe((mark) => {
      this.displayErrorAlert(mark); // in this log show {"lat": -27.54, "lng": -48.96}
      this.map.addMarkerSync({
        title: '@ionic-native/google-maps',
        icon: 'blue',
        animation: 'DROP',
        position: mark // if create a static {"lat": -27.54, "lng": -48.96} work
      });
    })
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "^4.10.0"
@ionic-native/google-maps : "^4.9.1"
```

**Current behavior:**
*I trunc numbers of position in this issue
Tried create a new marker by hold a click in map, but don't showing, just show te location of click in alert, when change position to a static position work (hold click and down a new marker).

inside displayErrorAlert() the object is ```{"lat": -27.54, "lng": -48.96}``` but if a console just lat or lng show undefined, found a issue very similar, but worked after update to new version, I tried this but same error. 

**Expected behavior:**
Show a new marker in map and calculate the distance (this not implemented eat, but if have a easy way)

**Comment by wf9a5m75** [comment]
```
this.map.on(GoogleMapsEvent.MAP_LONG_CLICK).subscribe((params: any[]) => {

let latLng: any = params[0];
```

**Comment by dekonunes** [comment]
OMG,

Worked, tnks so so much.
