### ISSUE TITLE
Cordova google maps geocoder doesnt work

### ISSUE THREAD

**Issue by stefanwilliam96** [mapsplugin/cordova-plugin-googlemaps#2364]
hi, can you tell me is that any wrong code in my coding? 
i try to call search() function but... nothing happen after i call search() function

    document.addEventListener("deviceready", function() {
        var div = document.getElementById("map_canvas");

        // Create a Google Maps native view under the map_canvas div.
        var map = plugin.google.maps.Map.getMap(div);

        // If you click the button, do something...
        var button = document.getElementById("button");
        button.addEventListener("click", function() {

            // Move to the position with animation
            map.animateCamera({
                target: {lat: 37.422359, lng: -122.084344},
                zoom: 17,
                tilt: 60,
                bearing: 140,
                duration: 5000
            });

            // Add a maker
            var marker = map.addMarker({
                position: {lat: 37.422359, lng: -122.084344},
                title: "Welecome to \n" +
                "Cordova GoogleMaps plugin for iOS and Android",
                snippet: "This plugin is awesome!",
                animation: plugin.google.maps.Animation.BOUNCE
            });

            // Show the info window
            marker.showInfoWindow();
        });
    }, false);

    function search(){
        var mapDiv = document.getElementById("map_canvas");
        var map = plugin.google.maps.Map.getMap(mapDiv);

        var isRunning = false;
        var inputField = $("#city").val();
        
        if (isRunning) {
            return;
        }
        isRunning = true;

        var dialogDiv = showVirtualDialog(mapDiv, "Just a moment, please ...");
            setTimeout(function() {
            mapDiv.removeChild(dialogDiv);
        }, 3000);

        // Address -> latitude,longitude
        plugin.google.maps.Geocoder.geocode({
            "address": inputField
        }, function(results) {
            if (results.length) {
                // Add a marker
                var marker = map.addMarker({
                    'position': results[0].position,
                    'title':  JSON.stringify(results[0].position)
                });

                // Move to the position
                map.animateCamera({
                    'target': results[0].position,
                    'zoom': 17
                }, function() {
                    marker.showInfoWindow();
                    isRunning = false;
                });
            } else {
                isRunning = false;
                alert("tidak ditemukan");
            }
        });  
    }
    <h1>Hello, World!</h1>
    <div id="map_canvas" class="map">
        <span class="smallPanel"><input type="text" id="city" value="Kyoto, Japan">
            <button onclick="search()">Search</button>
        </span>
    </div>

**Comment by wf9a5m75** [comment]
Thank you, but is it possible to create like this?
https://github.com/mapsplugin/HelloGoogleMap

```
.
├── config.xml
├── hooks
│   └── README.md
├── package.json
└── www
    └── index.html, home.html ...
```

Please include everything.

In order to reproduce your issue, I will do following commands:

```
$> git clone (your repo)
$> cd (project dir)
$> cordova prepare
$> cordova run android
```

So, I need all `www` files and `config.xml` file at least.

**Comment by wf9a5m75** [comment]
ping

**Comment by stefanwilliam96** [comment]
okay wait

**Comment by wf9a5m75** [comment]
Sorry, I can't open zip file on mobile phone.

Learning git improves your skill level, and saves your time a lot. 

Please study how to use GitHub.
https://guides.github.com/activities/hello-world/

**Comment by stefanwilliam96** [comment]
https://github.com/stefanwilliam96/cordova-google-mapss

**Comment by wf9a5m75** [comment]
If you don't use jQuery, you can replace the code `var inputField = $("#city").val();` with `var inputField = document.getElementById("city").value;`

And remove these lines:
```
var dialogDiv = showVirtualDialog(mapDiv, "Just a moment, please ...");
            setTimeout(function() {
            mapDiv.removeChild(dialogDiv);
        }, 3000);
```

**Comment by wf9a5m75** [comment]
ping

**Comment by stefanwilliam96** [comment]
YEAH that's work, i didnt notice that jquery xD.. thanks a lot
