### ISSUE TITLE
The function addMaker killed the app

### ISSUE THREAD

**Issue by ducnoivu** [mapsplugin/cordova-plugin-googlemaps#2365]
**I'm submitting a ...**  (check one with "x")
- [x ] question
- [x ] any problem or bug report

**OS:**  (check one with "x")
- [ x] **Android**
- [x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "^4.7.0"
@ionic-native/google-maps : "^4.9.1",
```

**Current behavior:**
the function addMaker kill the app without throw any errors when I used the MakerIcon. when I used the default maker, it worked perfectly 

**Expected behavior:**
 can add maker to  the map without kill the app

**Related code, data or error log (please format your code or data):**

```
 setMarker() {
    this.markersInit = false;
    this.markers = [];
    this.selectedMarker = '';
    this.map.addMarkerSync({position: this.points[0].position, icon: {
      url: 'assets/imgs/G-icon-grey.png',
      size: { width: 32, height: 45 }
  }})

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub, like this repository?
https://github.com/mapsplugin/HelloGoogleMap

In order to reproduce your issue, please include everything.

```
.
├── config.xml
├── hooks
│   └── README.md
├── package.json
└── www
    └── index.html, home.html ...
```

Please include everything.

In order to reproduce your issue, I will do following commands:

```
$> git clone (your repo)
$> cd (project dir)
$> cordova prepare
$> cordova run android
```

So, I need all `www` files and `config.xml` file at least.

**Comment by wf9a5m75** [comment]
ping

**Comment by ducnoivu** [comment]
https://github.com/tretrau1014/map-issue
@wf9a5m75 here is www folder, config.xml and package .json 
because our project is private so I can not share to you guys.
thank you

**Comment by wf9a5m75** [comment]
Thank you for sharing your project.
I think the reason is out of memory, because your icon images are large size.

In order to confirm that, please make small size images and specify it.

**Comment by ducnoivu** [comment]
I don't think the reason is out of memory. Because of the previous version (^2.3.6) can works.

**Comment by ducnoivu** [comment]
here is adb log
`07-30 09:05:24.475 25128 25317 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:760)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replaceAll(java.lang.String, java.lang.String)' on a null object reference
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:201)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:27)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-30 09:05:24.475 25128 25317 E AndroidRuntime: 	... 4 more
07-30 09:05:24.528   370  2450 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
07-30 09:05:24.649 25328 25328 E subsystem_ramdump: Directory /sdcard/ramdump does not exist
07-30 09:05:24.649 25328 25328 E subsystem_ramdump: Unable to create /sdcard/ramdump
07-30 09:05:24.649 25328 25328 E subsystem_ramdump: Unable to create /sdcard/ramdump
07-30 09:05:24.649 25328 25328 E subsystem_ramdump: Failed to initialize ramdump
07-30 09:05:24.947  1438  1585 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=681, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
07-30 09:05:24.949  1438  1585 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=680, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
07-30 09:05:25.012  1438  1837 E LocSvc_eng: W/AgpsReleasedState: unrecognized event 3
07-30 09:05:25.032  1658  1658 E Icon    : Unable to load resource 0x00000000 from pkg=com.android.systemui
07-30 09:05:25.032  1658  1658 E Icon    : android.content.res.Resources$NotFoundException: Resource ID #0x0
07-30 09:05:25.032  1658  1658 E Icon    : 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:201)
07-30 09:05:25.032  1658  1658 E Icon    : 	at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:94)
07-30 09:05:25.032  1658  1658 E Icon    : 	at android.content.res.Resources.getDrawable(Resources.java:788)
07-30 09:05:25.032  1658  1658 E Icon    : 	at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:316)
07-30 09:05:25.032  1658  1658 E Icon    : 	at android.graphics.drawable.Icon.loadDrawable(Icon.java:272)
07-30 09:05:25.032  1658  1658 E Icon    : 	at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:380)
07-30 09:05:25.032  1658  1658 E Icon    : 	at com.android.systemui.statusbar.ExpandedIcon.getDrawable(ExpandedIcon.java:59)
07-30 09:05:25.032  1658  1658 E Icon    : 	at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:184)
07-30 09:05:25.032  1658  1658 E Icon    : 	at com.android.systemui.statusbar.StatusBarIconView.setIcon(StatusBarIconView.java:137)
07-30 09:05:25.032  1658  1658 E Icon    : 	at com.android.systemui.statusbar.StatusBarIconView.set(StatusBarIconView.java:104)
07-30 09:05:25.032  1658  1658 E Icon    : 	at com.android.systemui.statusbar.phone.SimpleStatusBar.updateIcon(SimpleStatusBar.java:227)
07-30 09:05:25.032  1658  1658 E Icon    : 	at com.android.systemui.statusbar.phone.PhoneStatusBar.updateIcon(PhoneStatusBar.java:2130)
07-30 09:05:25.032  1658  1658 E Icon    : 	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:471)
07-30 09:05:25.032  1658  1658 E Icon    : 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-30 09:05:25.032  1658  1658 E Icon    : 	at android.os.Looper.loop(Looper.java:163)
07-30 09:05:25.032  1658  1658 E Icon    : 	at android.app.ActivityThread.main(ActivityThread.java:6221)
07-30 09:05:25.032  1658  1658 E Icon    : 	at java.lang.reflect.Method.invoke(Native Method)
07-30 09:05:25.032  1658  1658 E Icon    : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
07-30 09:05:25.032  1658  1658 E Icon    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
07-30 09:05:25.034  1658  1658 E Icon    : Unable to load resource 0x00000000 from pkg=com.android.systemui
07-30 09:05:25.034  1658  1658 E Icon    : android.content.res.Resources$NotFoundException: Resource ID #0x0
07-30 09:05:25.034  1658  1658 E Icon    : 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:201)
07-30 09:05:25.034  1658  1658 E Icon    : 	at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:94)
07-30 09:05:25.034  1658  1658 E Icon    : 	at android.content.res.Resources.getDrawable(Resources.java:788)
07-30 09:05:25.034  1658  1658 E Icon    : 	at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:316)
07-30 09:05:25.034  1658  1658 E Icon    : 	at android.graphics.drawable.Icon.loadDrawable(Icon.java:272)
07-30 09:05:25.034  1658  1658 E Icon    : 	at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:380)
07-30 09:05:25.034  1658  1658 E Icon    : 	at com.android.systemui.statusbar.ExpandedIcon.getDrawable(ExpandedIcon.java:59)
07-30 09:05:25.034  1658  1658 E Icon    : 	at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:184)
07-30 09:05:25.034  1658  1658 E Icon    : 	at com.android.systemui.statusbar.StatusBarIconView.setIcon(StatusBarIconView.java:137)
07-30 09:05:25.034  1658  1658 E Icon    : 	at com.android.systemui.statusbar.StatusBarIconView.set(StatusBarIconView.java:104)
07-30 09:05:25.034  1658  1658 E Icon    : 	at com.android.systemui.statusbar.phone.SimpleStatusBar.updateIcon(SimpleStatusBar.java:227)
07-30 09:05:25.034  1658  1658 E Icon    : 	at com.android.systemui.statusbar.phone.PhoneStatusBar.updateIcon(PhoneStatusBar.java:2130)
07-30 09:05:25.034  1658  1658 E Icon    : 	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:471)
07-30 09:05:25.034  1658  1658 E Icon    : 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-30 09:05:25.034  1658  1658 E Icon    : 	at android.os.Looper.loop(Looper.java:163)
07-30 09:05:25.034  1658  1658 E Icon    : 	at android.app.ActivityThread.main(ActivityThread.java:6221)
07-30 09:05:25.034  1658  1658 E Icon    : 	at java.lang.reflect.Method.invoke(Native Method)
07-30 09:05:25.034  1658  1658 E Icon    : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
07-30 09:05:25.034  1658  1658 E Icon    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
`

**Comment by wf9a5m75** [comment]
I tried to build your app, but I couldn't.

```
Plugin "call-number" already installed on browser.
Plugin "call-number" already installed on ios.
[xmldom warning]	attribute "here" missed value!! "here" instead!! 
@#[line:1,col:16]
[xmldom warning]	unclosed xml attribute 
@#[line:1,col:16]
Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes
(node:6057) UnhandledPromiseRejectionWarning: Error: Source path does not exist: google-services.json
    at updatePathInternal (/Users/masashi/Documents/workspace2/test/map-issue/platforms/android/cordova/node_modules/cordova-common/src/FileUpdater.js:145:19)
    at /Users/masashi/Documents/workspace2/test/map-issue/platforms/android/cordova/node_modules/cordova-common/src/FileUpdater.js:223:19
    at Array.forEach (<anonymous>)
    at Object.updatePaths (/Users/masashi/Documents/workspace2/test/map-issue/platforms/android/cordova/node_modules/cordova-common/src/FileUpdater.js:221:33)
    at updateFileResources (/Users/masashi/Documents/workspace2/test/map-issue/platforms/android/cordova/lib/prepare.js:432:17)
    at /Users/masashi/Documents/workspace2/test/map-issue/platforms/android/cordova/lib/prepare.js:51:9
    at _fulfilled (/Users/masashi/Documents/workspace2/test/map-issue/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/masashi/Documents/workspace2/test/map-issue/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/masashi/Documents/workspace2/test/map-issue/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/masashi/Documents/workspace2/test/map-issue/platforms/android/cordova/node_modules/q/q.js:624:44
(node:6057) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6057) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If you want me to check your program deeply, please prepare a project that I can build it (and reproduce your issue).
Otherwise, I can't help further because less information.

**Comment by wf9a5m75** [comment]
ping

(I just need to inspect only map part. You can remove other part code)

**Comment by wf9a5m75** [comment]
ping

**Comment by ducnoivu** [comment]
https://github.com/ducnoivu/map-issue-clone
@wf9a5m75  sorry for delaying, above is our project with map page only

**Comment by wf9a5m75** [comment]
Sorry for delay, it was busy.
I probably found the problem. But I haven't fixed it perfectly yet.

Sorry for your inconvenience.

**Comment by wf9a5m75** [comment]
Thank you for long waiting.
I deeply inspected, and I found one reason.

The ionic local http server `WebViewLocalServer` refuse http connection if the request is not through web browser for some reason.
I can't figure out the obvious reason, but this occurs. (I only checked with ionic v4, but this might be happened ionic v3)

The (temporally) solution is to replace `http://localhost/marker.png` to `file://android_assets/www/marker.png`.
(This is talking about internal code, so you don't need to do this).

I will change the code for ios tomorrow, but you can try new code for Android today.

``` 
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```

**Comment by ducnoivu** [comment]
many thanks, @wf9a5m75
