### ISSUE TITLE
android 4.4

### ISSUE THREAD

**Issue by apps-albertozoccheddu** [mapsplugin/cordova-plugin-googlemaps#2366]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**Message**
build works correctly and no problem with android sdk 22 and 23
it's possible to use this plugin with android 4.4 sdk 19 without crosswalk?

**Comment by apps-albertozoccheddu** [comment]
hello, i tried...
with the same apk, this is android 5
![screenshot_1532893769](https://user-images.githubusercontent.com/8273847/43370125-c0a3ec44-9379-11e8-8d9c-828385ba0343.png)
and this is android 4.4
![screenshot_1532893863](https://user-images.githubusercontent.com/8273847/43370128-d9ecdd5a-9379-11e8-935f-7ff42a5de10d.png)
these are virtual devices with Android Studio on Mac, but i tried in real devices (samsung note 10.1)
best regards

**Comment by wf9a5m75** [comment]
Then did you confirm android native log (logcat)?

**Comment by apps-albertozoccheddu** [comment]
logcat for android 4.4.2:
[logcat-android4-4-2.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2239861/logcat-android4-4-2.txt)
issue to row 329 ?

logcat for android 5.1 (all ok):
[logcat-android5-1.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2239871/logcat-android5-1.txt)

**Comment by wf9a5m75** [comment]
Ok, please share your project files on GitHub.

**Comment by wf9a5m75** [comment]
I read the logcat. I think Google Play Services library in the Android 4.4.2 device is too old, or not installed.

**Comment by wf9a5m75** [comment]
I found the reason.

```
07-30 08:07:07.542 3119-3119/com.phonegap.helloworld I/chromium: [INFO:CONSOLE(40)] "Uncaught ReferenceError: Promise is not defined", source: file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/googlemaps-cdv-plugin.js (40)
```

**Comment by wf9a5m75** [comment]
The browser in your Android 4.4.2 doesn't support Promise. That's all.

**Comment by apps-albertozoccheddu** [comment]
hello, i found a partial solution:
i downloaded the file "polyfill.min.js" from here https://github.com/taylorhakes/promise-polyfill
and then added to the app in index.html file.
Now map works in real device, but not works in virtual device.
Logcat says: 
"W/DynamiteModule: Local module descriptor class for com.google.android.gms.maps_dynamite not found.
I/DynamiteModule: Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:0
E/zzbz: Failed to load maps module, use legacy
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0."

Any idea?

thank you so much

**Comment by wf9a5m75** [comment]
There is no Google APIs in virtual machine.
