### ISSUE TITLE
touch is incorrect if another div size is changed

### ISSUE THREAD

**Issue by simetin** [mapsplugin/cordova-plugin-googlemaps#2367]
[ X ] any problem or bug report

[ X ] **Android**
[ X  ] **iOS**

**cordova information:** 
```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-cocoapod-support 1.3.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 4.11.0
@ionic-native/google-maps : 4.9.1
```

Current behavior:
After the first click on the arrow, the buttons are not responding. It's like the map is capturing the touch events. The problem appeared around v2.3.4 or v2.3.5.

Expected behavior:
The user should be able to click on the buttons.

Screen capture or video record:
[https://drive.google.com/open?id=1L2QkdMkUeR0ggyodBN-LYKI0vKFkmj_Z](https://drive.google.com/open?id=1L2QkdMkUeR0ggyodBN-LYKI0vKFkmj_Z
)

Git repo: [https://github.com/simetin/toggles](https://github.com/simetin/toggles
)

**Comment by wf9a5m75** [comment]
>The problem appeared around v2.3.4 or v2.3.5.

Already v2.3.8. I don't support backward versions.

**Comment by wf9a5m75** [comment]
I fixed the problem. Please reinstall the plugin from the multiple_maps branch.

![2367](https://user-images.githubusercontent.com/167831/43491549-d96eaed8-94d9-11e8-869e-ed0f7430c263.gif)

**Comment by simetin** [comment]
Thanks mate ! It works, I really appreciate your support. You can expect a little donation :)

**Comment by wf9a5m75** [comment]
Yap. I received it. Thank you for your donation :)
