### ISSUE TITLE
Cannot interact with Google Maps immediately after building Ionic 3 app

### ISSUE THREAD

**Issue by laoshelly** [mapsplugin/cordova-plugin-googlemaps#2368]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dreamover-uid 1.3.0 "UID"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.9-beta-20180718-1052 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
    "@ionic-native/core": "^4.11.0",
    "@ionic-native/google-maps": "^4.9.1",

**Current behavior:**

After running ionic cordova run android, I first login in the app and then display the map. The map loads, displays the marker correctly, and also fires the MAP_READY event. However I cannot interact with the map, be it zooming or simple clicking. However, by refreshing the app using Chrome Devtools, I can interact with the map properly.

**Expected behavior:**

I should be able to interact with the map on the first try.

**Related code, data or error log (please format your code or data):**

.ts file
```
ionViewDidLoad() {
    this.platform.ready().then(() => {
      this.getCurrentLocation();
    });
  }

  loadMap() {
    let coords: LatLng = new LatLng(this.lat, this.lng);
    let mapOptions: GoogleMapOptions = {
      camera: {
        target: coords,
        zoom: 18,
      },
      gestures: {
        zoom: true,
        rotate: true,
        scroll: true
      },
      controls: {
        zoom: true
      },
      zoomControl: true
    }
    
    this.map = GoogleMaps.create('map_canvas', mapOptions);
    this.map.setClickable(true);
    this.map.addMarker({
      position: coords
    }).then((marker: Marker) => {
      marker.showInfoWindow();
    });

    this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
      console.log('map is ready');

      this.map.on(GoogleMapsEvent.MAP_CLICK).subscribe(
          (data) => {
              alert("Click MAP");
          }
      );
    })
  }

  getCurrentLocation() {
    this.geolocation.getCurrentPosition().then((resp) => {
      this.lat = resp.coords.latitude;
      this.lng = resp.coords.longitude;
      setTimeout(() => {
        this.loadMap();
      }, 1000);
    }).catch((error) => {
      console.log('Error getting location', error);
    });
  }
```

.html file
```
<ion-header>

  <ion-navbar>
    <ion-title>survey-map</ion-title>
  </ion-navbar>

</ion-header>


<ion-content>
  <div id="map_canvas" data-tap-disabled="true">
  </div>
</ion-content>
```

**Comment by makers-mark** [comment]
However, by refreshing the app using Chrome Devtools, I can interact with the map properly.

I use Chrome's development 'console', but I am interested in the refreshing aspect? Thank you in advance, and are you using breakpoints in the debugger?

**Comment by wf9a5m75** [comment]
nop

**Comment by laoshelly** [comment]
@wf9a5m75 Is it okay if I just upload the code that leads up to the particular page? I'm afraid the other parts of the code are confidential.

**Comment by laoshelly** [comment]
@makers-mark Here's the screenshot. And I don't use breakpoints in the debugger. 
![image](https://user-images.githubusercontent.com/2346587/43440121-b0aefee6-94c8-11e8-9fbc-844898102e27.png)

**Comment by laoshelly** [comment]
Thank you!!
