### ISSUE TITLE
App crashes on iOS if icon url is redirected to another url

### ISSUE THREAD

**Issue by YeisonVelez11** [mapsplugin/cordova-plugin-googlemaps#2369]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [x ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ x] **iOS**

**cordova information:**  
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-android-play-services-gradle-release 1.4.2 "cordova-android-play-services-gradle-release"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 2.1.0 "Facebook Connect"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"

**Current behavior:**
I am using  IONIC V1.
I initially use a web service to obtain some locations, and this same web service returns me some routes with my icons. When the web service has been received, I use the markercluster and the icons of my bookmarks will be the icons that I receive from my web service.
I am trying to add to the makrers images that is hosted on my server. I'm using markercluster. Initially everything is going well, and the number 3 appears, since there are 3 nearby places. but when zooming, the application stops.

![captura](https://user-images.githubusercontent.com/1949889/43436843-cdedacd2-944b-11e8-9592-e6c18197e1f8.PNG)

**Expected behavior:**
when doing the respective zoom, it should show the images that I am loading from my server, without any problem. this does not happen on android

![problem](https://user-images.githubusercontent.com/1949889/43437289-df3b00fa-944d-11e8-9b73-1102987acff8.gif)

```          
            //I build this variable with the result of the web service
             $scope.aCoordenasSW=[

              {
                "position":{
                  "lng":lng,
                  "lat":lat
                },
                "icon":"http:\/\/tin.domovida.com\/Tin-Developer\/Images\/Tiendas\/Icon-TiendaVilladelRio2018-07-13.png",
                "distancia":distancia,//custom field
                "nit":data[i].nit,//custom field
                "nombre":data[i].name//custom field
              },
              {
                "position":{
                  "lng":lng,
                  "lat":lat
                },
                "icon":"http:\/\/tin.domovida.com\/Tin-Developer\/Images\/Tiendas\/Icon-Tiendalosyarumos2018-07-23.jpg",
                "distancia":distancia,//custom field
                "nit":data[i].nit,//custom field
                "nombre":data[i].name//custom field
              },
              {
                "position":{
                  "lng":lng,
                  "lat":lat
                },
                "icon":"http:\/\/tin.domovida.com\/Tin-Developer\/Images\/Tiendas\/Icon-TiendaManizales2018-07-14.png",
                "distancia":distancia,//custom field
                "nit":data[i].nit,//custom field
                "nombre":data[i].name//custom field
              }            
          ]


            markerCluster= map.addMarkerCluster({
            boundsDraw: false,
            zoomOnClick: false,
            markers:$scope.aCoordenasSW,
            icons: [
                {min: 2, max: 100, url: "./img/i1.png", anchor: {x: 16, y: 16}},
                {min: 100, max: 1000, url: "./img/i2.png", anchor: {x: 16, y: 16}},
                {min: 1000, max: 2000, url: "./img/i3.png", anchor: {x: 24, y: 24}},
                {min: 2000, url: "./img/i4.png",anchor: {x: 32,y: 32}}
            ]
            },function(){
            });
```
I would really appreciate it if you can help me please.

**Comment by YeisonVelez11** [comment]
Thank you very much for wanting to help me. It is difficult for me to modify my code since it works with geolocation, but I will try to have something to try. thank you very much.

**Comment by YeisonVelez11** [comment]
@wf9a5m75  While I try to adapt my code, do you know what it can be? I suspect that the problem is the images.

**Comment by sbatezat** [comment]
@YeisonVelez11 how many markers have you added?
Performances are very poor with the plugin implementation of cluster when you got a lot of markers.
I recommend using https://github.com/mapbox/supercluster instead. I'm using it and is so much more efficient!

**Comment by wf9a5m75** [comment]
@YeisonVelez11 Thank you for sharing your project files.

Well, v2.3.2 is old.
https://github.com/YeisonVelez11/errormaps/blob/5c5f197e3e1d25e8ac31d4e990d6f33c0ada7c17/config.xml#L105

Using v2.3.8, I can't confirm your issue.
![2369](https://user-images.githubusercontent.com/167831/43477416-ff7418e0-94af-11e8-9da0-49801c4b7271.gif)

**Comment by wf9a5m75** [comment]
I recommend you use put icon files in your app or, put them on faster static serve servers, such as CDN or github pages. It seems your http server is bit slow.

**Comment by YeisonVelez11** [comment]
@wf9a5m75  Within 4 hours I will be at my house. and I will try again.

**Comment by YeisonVelez11** [comment]
now, I am using the latest version 2.3.8 and I am getting this error:

2018-07-31 01:02:01.004625-0500 TIN[8908:170493] [fail] url = http://tin.domovida.com/Tin-Developer/Images/Tiendas/Icon-TiendaVilladelRio2018-07-13.png
2018-07-31 01:02:01.006368-0500 TIN[8908:170617] Task <63CC78D5-5FF1-4904-AF81-AC09ED6682E1>.<1> HTTP load failed (error code: -999 [1:89])
2018-07-31 01:02:01.069009-0500 TIN[8908:170493] *** Terminating app due to uncaught exception 'GMSThreadException', reason: 'The API method must be called from the main thread'

**Comment by wf9a5m75** [comment]
ok, please update the repository.
You must commit the same code as you tested.

**Comment by YeisonVelez11** [comment]
@wf9a5m75 Thanks. This problem only occurs on ios. your screenshot is taken by a phone with android( I believe) and I could try to share the code but it would have to be private, because for legal reasons I could go to jail. I would also need you to tell me your location when you use it to generate locations near you. But for now see if this error occurs in ios, maybe this is a clue to the problem.

**Comment by wf9a5m75** [comment]
Oh, I didn't notice you specify ios. I see, let me check out tomorrow.

If you need private support, please read here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/.github/ISSUE_TEMPLATE/private-support.md

**Comment by YeisonVelez11** [comment]
@wf9a5m75 for now maybe if you try it on an ios device, you can reproduce the error. in my past comments the problem appears for an image.

**Comment by wf9a5m75** [comment]
I got the reason.
You specify `http://tin.domovida.com/.../Icon-TiendaVilladelRio2018-07-13.png`, but the server replies `301 Moved Permanently`.
Then, redirected to `https://tin.domovida.com/.../Icon-TiendaVilladelRio2018-07-13.png`.

![screen shot 2018-08-01 at 10 17 09 am](https://user-images.githubusercontent.com/167831/43537411-14580900-9574-11e8-9320-dac98e658b1f.png)

Because of this, cache mechanism does not work as intended.
That's why the app crashes.

-----------

I fixed the plugin, please reinstall from the multiple_maps branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...

```

And you also need to modify your code `https://tin.domovida.com` instead of `http://tin.domovida.com`

**Comment by YeisonVelez11** [comment]
@wf9a5m75  thanks, it solve my problem! you are the best
