### ISSUE TITLE
detect collision Circle and polyline

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#2374]
**I'm submitting a ...**  (check one with "x")
- [X] question
- [ ] any problem or bug report

Hello how are you friend.
I have a map with a polyline and a circle and I would like to know if it is possible to detect a unioin between the circle or the polyline?

**Comment by wuilmerj24** [comment]
@wf9a5m75  Not actually. But I explain to you while I create the example project.
I have an apolline which is updated with the results of google maps directions, but I have a marker_events ("position_changed") to update the polyline. You want to add a circle with a radius of 300 meters, and if the radius does not touch the polyline, you can update the polyline.

**Comment by wf9a5m75** [comment]
So, do you want to detect the draggable marker is in circle or not?

**Comment by wuilmerj24** [comment]
@wf9a5m75  
do not. I have the circle and a polyline. I would like to know if the circle and the polyline are touching

**Comment by wuilmerj24** [comment]
@wf9a5m75 if you can understand me?

**Comment by wf9a5m75** [comment]
Ah, I see. here.
http://ericleong.me/research/circle-line/

**Comment by wf9a5m75** [comment]
There are many examples.

https://www.google.com/search?q=line+circle+collision+detect

**Comment by wuilmerj24** [comment]
@wf9a5m75 Thansk man.
