### ISSUE TITLE
(bug)Can't find variable: onTransitionFinish

### ISSUE THREAD

**Issue by fxckdead** [mapsplugin/cordova-plugin-googlemaps#2375]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-flashlight 3.2.0 "Flashlight"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.9 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-qrscanner 2.6.0 "QRScanner"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "^4.11.0"
@ionic-native/google-maps :  "^4.9.1"
```

**Current behavior:**

After a POP/Push Page on Ionic 3 (3.9.2) the console shows:

`ReferenceError: Can't find variable: onTransitionFinish`

And sometimes it doesn't  position correctly the Map.

**Expected behavior:**

It should position the map correctly in the widht and i think don't throw the error

**Screen capture or video record:**
![captura de pantalla 2018-08-03 a la s 23 52 38](https://user-images.githubusercontent.com/116668/43672448-1fc683de-977c-11e8-85d6-d4008e9c52eb.png)

![img_0303-2](https://user-images.githubusercontent.com/116668/43672473-8d2af9aa-977c-11e8-9ece-f8e1bf46a539.jpg)

**Related code, data or error log (please format your code or data):**
I installed the "Multiple_maps" branch 
```
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
```

** EDIT **

I'm trying the solution you said at #2351 and now i'm not getting the issue. I was doing 
`window.dispatchEvent(new Event("resize"));` 
Maybe that was causing the error in console.

**Comment by wf9a5m75** [comment]
Oh, it's my mistake... Sorry about that. I released v2.3.10. Please reinstall it.

**Comment by fxckdead** [comment]
@wf9a5m75  Just updated, but the issue of the map doesn't position correctly still :( 

I'm doing:

```
ionViewDidEnter() {
    console.debug("ionViewDidEnter cordova");;
    cordova.fireDocumentEvent("plugin_touch");
  }
```

It doesn't happens always, and if i change the page and come back to "home" it position the map ok, but, like i said, its a random event

**Comment by wf9a5m75** [comment]
Could you share your project files on GitHub? (example project is fine)

**Comment by fxckdead** [comment]
@wf9a5m75 I will try to replicate it in a new project and upload to github.

In the meanwhile, i

**Comment by wf9a5m75** [comment]
Since map view is not a HTML element, it is very difficult to catch up the same position as map div.
I recommend you use `overlay` menu instead of `push` menu.

But thank you for creating an example project. I will check it on Monday.

**Comment by fxckdead** [comment]
@wf9a5m75 in fact, i'm using the overlay menu, and if i check where the "#map" div is located, its in all the space, only the map is in the wrong position :/

**Comment by wf9a5m75** [comment]
Did I miss something?

I can't see any `type="overlay"` in this file.
https://github.com/fxckdead/ionic-gmaps-tests/blob/6406d070a5ca65895aa5bf4b35f5fc3c1097386f/src/app/app.html

Also, I can't see any map code in this file.
https://github.com/fxckdead/ionic-gmaps-tests/blob/6406d070a5ca65895aa5bf4b35f5fc3c1097386f/src/pages/home/home.ts

**Comment by fxckdead** [comment]
Oh, it seems that I didn’t commit my code, just the demo app -.-‘ I will update it in a few hours

Enviado desde mi iPhone

**Comment by fxckdead** [comment]
@wf9a5m75 Now you can see the changes :D 

ps: i just made a push of the original code, i didn't commit the new changes lol
