### ISSUE TITLE
can't load local image for marker if wkwebview hosts the index.html on file:// protocol

### ISSUE THREAD

**Issue by eskhool** [mapsplugin/cordova-plugin-googlemaps#2376]
The commit for Cordova fix for wkwebview for showing icon in markers that was done in the #multiplemaps branch works only at that commit. 

Refer issue #2344 which was closed after testing the [fix](
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/2e92852c63db640f8a77a2ea78a3d34a5a5e1a6a)

A subsequent change has regressed this fix and it not longer works with Cordova (maybe its the ionic fix).

**Comment by wf9a5m75** [comment]
Please share the reproduce project on GitHub

**Comment by eskhool** [comment]
Please refer to @2344. The same project is able to reproduce the issue with the latest #multiplemaps branch.

**Comment by wf9a5m75** [comment]
Thank you for reporting.
This causes because wkwebview behavior is changed.

One thing before reporting your issue next time, please fix your example project.
https://github.com/eskhool/cordovaDemo/blob/master/www/js/index.js#L81-L90
