### ISSUE TITLE
compilation error in PluginMarker

### ISSUE THREAD

**Issue by csabbey** [mapsplugin/cordova-plugin-googlemaps#2377]
**I'm submitting a ...**  (check one with "x")
- [ x ] question
- [ x ] any problem or bug report
(either? both?)

**OS:**  (check one with "x")
- [ x ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

com.rsginc.exceptionthrower 1.0.0 "Exception Thrower"
com.rsginc.heartbeat 1.0.0 "Heartbeat"
com.rsginc.loaner 1.0.0 "Loaner"
com.rsginc.mobilesurvey 1.0.0 "Trip Recorder guts"
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"
cordova-plugin-app-preferences 0.99.3 "AppPreferences"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.3.10 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"

**Current behavior:**
Can't compile:
/Users/craig.sabbey/code/mobile-survey/ms-client-dugong/platforms/android/src/plugin/google/maps/PluginMarker.java:1149: error: local variable onComplete is accessed from within inner class; needs to be declared final
        AsyncLoadImage task = new AsyncLoadImage(cordova, webView, options, onComplete);

**Expected behavior:**
Can compile.

This was compiling for me recently, and I'm not sure why it stopped. I've looked back at recent versions of this class, and code around this hasn't changed. Any idea why it wouldn't compile for me?

**Comment by wf9a5m75** [comment]
Um, I wonder. I can compile without `final`. I guess your Java version is old.

**Comment by wf9a5m75** [comment]
But I merged your PR. Thank you for your help.

**Comment by lucawen** [comment]
I have see the fix on master, but can create a new version on NPM? Thanks!! (Sorry for the rush)

**Comment by wf9a5m75** [comment]
Reinstall from the multiple_maps branch, please.
