### ISSUE TITLE
Trying to add custom icon to marker 

### ISSUE THREAD

**Issue by razvang10** [mapsplugin/cordova-plugin-googlemaps#2380]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.10 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Current behavior:**
marker is still default (red one)
**Expected behavior:**

marker should be my image 
**Related code, data or error log (please format your code or data):**

```
    let icon:MarkerIcon={
      url: "assets/imgs/markers/client.png",
      size: {
          width: 30,
          height: 30,
      }
    }

    let options:MarkerOptions={
      position: this.location.getLastRecord(),
      disableAutoPan: true,
      icon: icon 
    }
    this.map.addMarker(options).then((marker)=>{
      this.me = marker;
      this.events.subscribe('location:update',(location:Point )=>{
        let prevLocation=<Point>marker.getPosition();
        marker.setPosition(location);
      });
    });

```

**Comment by wf9a5m75** [comment]
Duplicated.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2365
