### ISSUE TITLE
Ionic - Java compiler error

### ISSUE THREAD

**Issue by Sideral-Inc** [mapsplugin/cordova-plugin-googlemaps#2382]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-background-geolocation 2.10.1 "BackgroundGeolocation"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-open-native-settings 1.5.1 "Native settings"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-fetch 5.2.1 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-estimote 0.8.2 "EstimoteBeacons"
cordova-plugin-google-analytics 1.0.0 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.3.10 "cordova-plugin-googlemaps"
cordova-plugin-hockeyapp 5.1.2 "HockeyApp"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
```

**Current behavior:**
When trying to generate an app with Android Studio. I got the following error message:

error: local variable imageOptions is accessed from within inner class; needs to be declared final

in file PluginGroundOverlay.java line 438. This currently blocks me from building my app.

**Expected behavior:**
This would not blocks me to build my app.

**Screen capture or video record:**

![screen shot 2018-08-07 at 8 35 44 pm](https://user-images.githubusercontent.com/24905059/43809652-731c2fe0-9a81-11e8-86c3-991b54ce3fba.png)

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
What version of jdk do you use?

**Comment by Sideral-Inc** [comment]
In Android Studio, it point to jdk 1.8.0_172

**Comment by wf9a5m75** [comment]
Thank you for your information. I have no problem for compiling, but I adjusted the code.

Please reinstall the plugin from the multiple_maps branch.

**Comment by Sideral-Inc** [comment]
Thanks for your quick reply.

Unfortunately, now I have an issue with the "onComplete" variable, right after the imageOptions you fixed.

`error: local variable onComplete is accessed from within inner class; needs to be declared final`

Any way to fix that as well?

Thanks

**Comment by wf9a5m75** [comment]
Try again

**Comment by spacesuitdiver** [comment]
@wf9a5m75 it looks like your commit targeted the new multi_maps branch, can you merge the same fix into master?

**Comment by Sideral-Inc** [comment]
@wf9a5m75 Awesome, it's all good now. Thanks so much for your quick replies.
