### ISSUE TITLE
Positioning delay on popping back 

### ISSUE THREAD

**Issue by jasvindersingh-evon** [mapsplugin/cordova-plugin-googlemaps#2387]
**I'm submitting a ...**  (check one with "x")
- [] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 3.1.2 "NativeGeocoder"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 4.11.0
@ionic-native/google-maps : 4.9.1
```

**Current behavior:**
The home page is a map and when i navigate to next screen. After popping back to the home page, the map is not rendered properly. I guess its the same issue that you have mentioned here, but this happens only on iOS.
 
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Map/README.md#positioning-is-delay-a-little

**Expected behavior:**
It should not delay the position. Its kind a little weird. 

**Screen capture or video record:**
Recording - https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2274312/recordingTwo.mov.zip)

**Comment by wf9a5m75** [comment]
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g3e207b82bf_886_16

**Comment by jasvindersingh-evon** [comment]
Okay, Can you please guide in right direction. I know you have written that there is another alternative of using Javascript. Please help you know that client don't accept such reasons as they are not technical.

**Comment by wf9a5m75** [comment]
It's easy. You just stop to use side page.

**Comment by wf9a5m75** [comment]
You can use Google Maps Java Script v3 or other plugins alternatively if you don't satisfy for this plugin.

**Comment by wf9a5m75** [comment]
@jasvindersingh-evon One possible way is to use `map.setDiv(null)` and `map.setDiv('map_canvas)`.

https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/googlemap/setDiv/README.md
