### ISSUE TITLE
Marker and infoWindow stays in a wrong position if clicked during "bounce" animation

### ISSUE THREAD

**Issue by Gabplay** [mapsplugin/cordova-plugin-googlemaps#2389]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  

```
cordova-plugin-googlemaps 2.3.8 
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "4.4.0"
@ionic-native/google-maps : "^4.8.2"
```

**Current behavior:**
This happens everytime that I click on any marker during its bouncing animation. I think it's related to infoWindow anchor coordinates... Is there a way to prevent this kind of glitch?

Using cordova-google-maps 2.3.8 and ionic-native/google-maps@4.8.2
But I think this issue happens in all versions.

**Screen capture or video record:** https://imgur.com/Y2RZz7n

![20180810_131411_edited](https://user-images.githubusercontent.com/12158575/43970037-877ea53a-9ca2-11e8-9d1a-b5e8f1765710.gif)

**Comment by wf9a5m75** [comment]
Don't do any action during animation.

**Comment by Gabplay** [comment]
Okay, but isn't there a way to prevent a click during animations? Or maybe infoWindow should get the same place of marker final position. Users do not understand this kind of behavior, they think the marker is just wrong...

**Comment by wf9a5m75** [comment]
Don't open the infoWindow during the animation, that's all.

InfoWindow position is controlled by native API, not this plugin.
