### ISSUE TITLE
Smooth movement of marker from one position to other like a vehicle tracking on map

### ISSUE THREAD

**Issue by techno2mahi** [mapsplugin/cordova-plugin-googlemaps#2391]
We were using the Google maps JavaScript API quite for some time. Now that we are creating a hybrid mobile app. In order to implement a vehicle online tracking we need to act on the constantly received target vehicle position. For that we used to animate the marker setPosition like the logic below.

https://github.com/combatwombat/marker-animate

Can we expect something like this so that we can use the plugin effectively in a Realtime vehicle tracking system. Or can u through some pointers how to achieve this effect in this great plugin.

**Comment by wf9a5m75** [comment]
Before implement this plugin into your product, please create a test app, and evacuate this plugin deeply. I can't guarantee your request.

**Comment by techno2mahi** [comment]
I have done the same and I have facing problem in moving the marker smoothly in order to achieve the effect as a moving vehicle. Can you please provide some instance where this plugin is used for live vehicle tracking scenario. Also the plugin is having a tons of functionalities which is appreciated a lot. But for creating a tracking application the main functionality will be the animating the marker movement. 

If I am trying to animate the movement as mentioned in the  url below, its a hack and not the native way of doing so. 
https://github.com/combatwombat/marker-animate

Please let me know how can i achieve the same in a more native way.

**Comment by wf9a5m75** [comment]
This plugin *DOES NOT** have any animation feature.
(Google Maps JS API v3 as well)

However there is a feature to **calculate the interpolate location** between A and B.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/utilities/geometry/spherical/interpolate/README.md

You need to implement animation feature by yourself.

**Comment by techno2mahi** [comment]
@wf9a5m75 Can you please let me know what will be the ideal way to implement for a vehicle moving. is it the SetPosition if the marker with proper animation or something else.

**Comment by wf9a5m75** [comment]
Did you see this demo?
<img src="https://raw.githubusercontent.com/mapsplugin/cordova-plugin-googlemaps-doc/master/v2.3.0/class/utilities/geometry/spherical/interpolate/image.gif" width="250">

**Comment by techno2mahi** [comment]
Yes, But the marker movement need to be done within 10-100 meters of distances. Like you see in Uber or Lyft that their vehicle is moving smoothly in the map.

**Comment by wf9a5m75** [comment]
I don't support your code programming.
Thinking how to write the code is your role.

**Comment by kovaneth** [comment]
Hello any update of the request ?

**Comment by lkonzen-garupa** [comment]
You can use a ```map.animateCamera``` to move the map smoothly and set the marker position as documented [here](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/utilities/geometry/spherical/interpolate/README.md)
You can even calculate the marker rotation before each loop of animation an set using ```marker.setRotation```
