### ISSUE TITLE
Search within radius

### ISSUE THREAD

**Issue by stefanwilliam96** [mapsplugin/cordova-plugin-googlemaps#2392]
How to make search nearby / search within radius with google maps plugin ? thanks

**Comment by wf9a5m75** [comment]
This plugin does not provide any DB search engine. You need to implement it by yourself.

**Comment by stefanwilliam96** [comment]
i already get latitude and longitude from DB, but the problem is that any API which can help me to know where's the nearest place from my location with latitude and longitude ?
