### ISSUE TITLE
Trace Route

### ISSUE THREAD

**Issue by luisfernando-rf** [mapsplugin/cordova-plugin-googlemaps#2395]
Good afternoon, how do I trace vehicle routes from one marker to another? Is there a method available from the plugin?

I've been looking at the computeSignedArea () method, but it traces a straight, "let's say from an airplane" route. Please help me?

**Comment by wf9a5m75** [comment]
This plugin does not provide any direction feature. You need to make requests to [Google Directions API](https://developers.google.com/maps/documentation/directions/intro), then get the results, and draw the route by yourself.

**Comment by wf9a5m75** [comment]
You need to parse the `routes[0].legs` property, then draw the line with `map.addPolyline()`.

**Comment by luisfernando-rf** [comment]
It will only work if I pass the points with this syntax in an array: {lat: 51.511077, lng: -0.119245}?

Because the api returns me to different latitude and longitude, like a google.maps.LatLng, would it have to convert back to string?

**Comment by wf9a5m75** [comment]
yes
