### ISSUE TITLE
map.addKmlOverlay() does not work if page url contains '#hash'

### ISSUE THREAD

**Issue by Gabplay** [mapsplugin/cordova-plugin-googlemaps#2396]
`this.map.addKmlOverlay({ 'url': "assets/overlay.kml" });`

This works in 2.3.9 normally, but stopped working when I updated to 2.3.11
I'm working with 'file://' not localhost webviews.

**Comment by wf9a5m75** [comment]
In order to reproduce your issue 100%, please share your project giles on GitHub.

**Comment by wf9a5m75** [comment]
ping

**Comment by Gabplay** [comment]
I made another test using [this quickdemo](https://github.com/mapsplugin/ionic-googlemaps-quickdemo) and it happens exactly the same. My project is too big now, I think it's better to test in this demo just change the plugin version and try KML page.

In 2.3.9 it works if using 'file://' but not with localhost
In 2.3.11 it works in localhost but not with 'file://'

**Comment by wf9a5m75** [comment]
I think ionic serves the index.html file on `http://` always.

**Comment by Gabplay** [comment]
I forgot to say that I'm not using 'cordova-plugin-ionic-webview' because of CORS issues, so it shows 'file://' on Origin requests

**Comment by wf9a5m75** [comment]
Thank you for waiting.

I tested the `kmlOverlay` on `file://` with the quick demo, but I have no problem.

**Comment by wf9a5m75** [comment]
Thank you for waiting, I can not confirm your issue.

The KmlOverlay demo of [ionic-googlemaps-quickdemo](https://github.com/mapsplugin/ionic-googlemaps-quickdemo) works perfectly even `file://` protocol.

![screen shot 2018-08-21 at 9 59 15 am](https://user-images.githubusercontent.com/167831/44416839-e7bd0700-a528-11e8-9697-21548c233cc3.png)
![capture](https://user-images.githubusercontent.com/167831/44416896-0de2a700-a529-11e8-8162-0f3191bd452f.png)

**Comment by Gabplay** [comment]
I found the problem, I'm using lazy loading so Ionic route works differently. Look at the screenshot:

![capturar](https://user-images.githubusercontent.com/12158575/44428913-3f309680-a56c-11e8-806c-3c4ba4deff91.jpg)

**Comment by Gabplay** [comment]
If you remove all pages from app.module except HomePage and change page title to string in app.components you will see it wont load.

**Comment by wf9a5m75** [comment]
Please create the reproduce demo project, then share it on Github.

**Comment by Gabplay** [comment]
I made a fork and this commit: https://github.com/Gabplay/ionic-googlemaps-quickdemo/commit/f111fdc26f30f3d17ab86418eb3c4a43d9a2107b

**Comment by wf9a5m75** [comment]
Thank you for creating the demo project, it's perfect for the inspection.
I fixed the bug. Please reinstall the plugin from the multiple_maps branch.
