### ISSUE TITLE
Map not interactive with Polymer Webcomponents

### ISSUE THREAD

**Issue by ddbb1977** [mapsplugin/cordova-plugin-googlemaps#2399]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.3.11 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**

Using a map inside a custom web component (Polymer Element) the map shows but it is not interactive. Trying to move, pinch to zoom or other gestures will not work.

**Expected behavior:**

To be able to interact with it normally.

**More info**
I've tried the same project with only the map and it loads and becomes interactive. It only happens if the map DIV is defined inside the shadow DOM, inside a WebComponent.

**Comment by wf9a5m75** [comment]
Not supported, and no plan to support it.

**Comment by ddbb1977** [comment]
Any pointers on why it fails or on how to start debugging the issue?
