### ISSUE TITLE
HTML Info Window?

### ISSUE THREAD

**Issue by paishin** [mapsplugin/cordova-plugin-googlemaps#240]
Now with v.1.2 is it possible to have html in the infoWindow?

If yes, then how?

**Comment by joewoodhouse** [comment]
Anyone have a working link for that customInfWindow page?

**Comment by quiuquio** [comment]
Up. Sorry to bring back something so old but I'd be seriously curious about that!

**Comment by sressi** [comment]
@wf9a5m75 is there a working link for that customInfoWindow example? Thank you!
