### ISSUE TITLE
the application uses ionic v1 can't interactive with map view on only iPhone5 because of resetCSS

### ISSUE THREAD

**Issue by lynavis** [mapsplugin/cordova-plugin-googlemaps#2402]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ X] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [X ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
call-number 0.0.2 "Cordova Call Number Plugin"
com-sarriaroman-photoviewer 1.1.16 "PhotoViewer"
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http2 1.6.1 "Cordova HTTP plugin"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.1-dev "Console"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.3.11 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-sms 1.0.5 "SMS"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.2 "Toast"
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.0 "Launch Navigator"

```

```
Cordova CLI : 7.1.0
Ionic Framework : 1.3.1
Cordova Platforms : ios 4.5.0
```

**Current behavior:**
I was in version 2.1.1 but i had a problem with method "setIcon" on markers so i updated the plugin to the last version and all work fine instead on iphone 5 (v10.3.3). I have this comportement : 

![](https://user-images.githubusercontent.com/3638322/33795572-0b4228b2-dcb2-11e7-98b5-238bdafc5766.gif)

It's not my projet, it's from this [issue](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1941) but the fix don't work for me. 
I tried many version of the plugin and all version above 2.2.0 don't work on this iphone.

HTML :

```
<ion-view>
    <ion-nav-title class="bg-grey-link">
        <span class="nav-bar-title-text">MAP</span>
    </ion-nav-title>

    <ion-content class="full-height">
        <div id="map_canvas"></div>
    </ion-content>
</ion-view>
```
JS :

```
$scope.$on('$ionicView.afterEnter', function() {
    var div = document.getElementById("map_canvas");
    $rootScope.map = plugin.google.maps.Map.getMap(div, {
        'gestures': {
            'scroll': true,
            'tilt': true,
            'rotate': true,
            'zoom': true
        }
    });

});

```

Do you see why it doesn't work on this iphone with other version than 2.1.1 ?

Thank you for your help!

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by wf9a5m75** [comment]
Without reproduce projet, I won't check it. So I can't help you

**Comment by lynavis** [comment]
I can't share because it's a professional project.

Here a demo projet where the issue is reproduced : [Demo](https://github.com/lynavis/googlemapdemo)
It's a default ionic project where i added my basic code for display the map.

Iphone 5
iOs : 103.3
cordova-ios : 4.5.0

**Comment by wf9a5m75** [comment]
Thank you for creating a demo project.
But I don't support older version, so I will check it with the latest version.

**Comment by wf9a5m75** [comment]
I tried to inspect your project, but because of your ionic is too old, I couldn't run your code.

Please upgrade your ionic framework

**Comment by lynavis** [comment]
I can't upgrade to an other version of the ionic framework. Like i said before it's a professional project and we don't have time to allocate to version migration.

**Comment by wf9a5m75** [comment]
Well, unfortunately please give up to use this plugjn. I don't have also enough time to spend much time for ancient ionic framework.

You need to choose one of them:
- creare a very simple demo that reproduce your issue
- or give up to use this plugin.

**Comment by lynavis** [comment]
I can't create more simple demo than the one i gave you. I created the project with the command "ionic start googleMaps" blank --type=ionic1". Then, install your plugin and ios platform and run the project.

What did you change in your code beetween 2.1.1 and  2.2.0 that can produce this issue? It's like an invisible div above the map

**Comment by wf9a5m75** [comment]
Please check commit logs. All code is open.

**Comment by lynavis** [comment]
I already cheked what change but i don't know where to search in all files

**Comment by wf9a5m75** [comment]
https://blog.github.com/2010-03-01-introducing-github-compare-view/

**Comment by wf9a5m75** [comment]
Here you are, I tried with another PC, and reinstall ancient ionic. Then run it. I have no problem.
![2402](https://user-images.githubusercontent.com/167831/44670659-21ce5300-a9d8-11e8-8c63-e4413e2dc9af.gif)

**Comment by lynavis** [comment]
It work fine With recent iPhone but dont on iphone 5

**Comment by lynavis** [comment]
Can you give me a line search ? In witch file i have to look ?

**Comment by wf9a5m75** [comment]
Any comments?
![2402](https://user-images.githubusercontent.com/167831/44672534-9952b100-a9dd-11e8-9536-770a30a41a97.gif)

**Comment by lynavis** [comment]
OK i tried with the iphone 5s simultor and it work but when i run on my iphone 5 it dosen't

**Comment by wf9a5m75** [comment]
You should check it with safari inspector

**Comment by wf9a5m75** [comment]
Unfortunately I can't do anything. The problem is your iPhone.

**Comment by lynavis** [comment]
I inspect with safari and all parents élément have the class for the transparence. I think first the problem come from by the div «scroll » add by ionic but with scroll to false the issue is still present

**Comment by wf9a5m75** [comment]
I have been entered into a strike. All questions & issues about ionic are refused.
Ionic member @perrygovier will help you.

**Comment by wf9a5m75** [comment]
Ok, I figured out the reason finally. The reason is `resetCSS`. This breaks the touch calculation of this plugin.
I fixed the problem. Please reinstall the plugin from the multiple_maps branch.

![2402](https://user-images.githubusercontent.com/167831/44745488-b5794f80-aabc-11e8-9d69-b3847b777774.gif)

**Comment by lynavis** [comment]
It work perfect !!!!! Thank a lot for you time !!!

**Comment by wf9a5m75** [comment]
You are welcome
