### ISSUE TITLE
Grey map on iOS

### ISSUE THREAD

**Issue by davayd** [mapsplugin/cordova-plugin-googlemaps#2403]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.3.11 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
Hello , i downloaded your example ionic project from https://github.com/mapsplugin/ionic-googlemaps-quickdemo and run it by command "ionic cordova run ios". Application was started fine, but i have a grey screen. I've read this (https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/TroubleShooting/Blank-Map/README.md) help, but no one method not helps me. The same problem in device (iPhone 6)
**Expected behavior:**
Expected to see the map in application
**Screen capture or video record:**

![googlemapsproblem](https://user-images.githubusercontent.com/17270614/44525781-bb50e880-a6ea-11e8-9ab6-4f8746b601fd.gif)

**Related code, data or error log (please format your code or data):**
https://github.com/davayd/googlemapsiosproblem

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/graymap/README.md

**Comment by wf9a5m75** [comment]
Your key is valid for JS API and geocoding API, but your key is NOT valid for iOS SDK.

**Comment by davayd** [comment]
how can I make it valid?

**Comment by wf9a5m75** [comment]
Regenerate api key for ios.

**Comment by davayd** [comment]
1) I've generate new api and past in config.xml
![aa](https://user-images.githubusercontent.com/17270614/44590401-b9a72380-a7c3-11e8-8308-1b52be2d2d42.png)
2) In Xcode searching this API on whole project
![ss](https://user-images.githubusercontent.com/17270614/44590429-d2173e00-a7c3-11e8-8c92-64de39b81212.png)
-- no one find
3) same behavior
![dd](https://user-images.githubusercontent.com/17270614/44590454-e22f1d80-a7c3-11e8-8cb3-3a98d15bbef0.png)

**Comment by davayd** [comment]
Xcode console 
![ewe](https://user-images.githubusercontent.com/17270614/44590770-9f217a00-a7c4-11e8-86fe-187c50b2b3a1.png)

**Comment by wf9a5m75** [comment]
`White page` and `gray map` is completely different meaning and behavior.

`Gray map` means `your api key is invalid`.

`White page` means `you execute code before platform.ready()`.
As the evidence, `Ionic Native tried accessing the GoogleMaps plugin but it's not installed.` warning.

**Comment by wf9a5m75** [comment]
Here
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g292c767148_0_24


And here
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g292c767148_0_24

**Comment by wf9a5m75** [comment]
ping

**Comment by davayd** [comment]
Issue was solved with help gmap docs (https://developers.google.com/maps/documentation/ios-sdk/start#step_3_get_an_api_key). I'm just generate new API key and set the Credentials. Anyway, thx for help!
