### ISSUE TITLE
Plugin Crashes Build

### ISSUE THREAD

**Issue by rlaurente** [mapsplugin/cordova-plugin-googlemaps#2404]
Got random crash in android and saw this error in ionic 3

plugin.google.maps.PluginLocationService$7.onSuccess
PluginLocationService.java - line 454
java.lang.NullPointerException: Attempt to invoke virtual method 'long android.location.Location.getTime()' on a null object reference
plugin.google.maps.PluginLocationService$7.onSuccess PluginLocationService.java:454
plugin.google.maps.PluginLocationService$7.onSuccess PluginLocationService.java:450

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by rlaurente** [comment]
Please refer the call below, my goal there is simply showing the current user pin in the loaded map.
It works normally but there are times that it crashes. and I got the message above in my crash reporting tool.

this.map.getMyLocation().then(data => {
// loading current pin
            }).catch(err => {
                console.log("can't access location", err);
            });

**Comment by wf9a5m75** [comment]
If you just showing the user location only, I recommend you use [Google maps Embed API](https://developers.google.com/maps/documentation/embed/guide) or [Google Maps Static Maps API](https://developers.google.com/maps/documentation/maps-static/intro), because this plugin is too rich for your purpose.

[cordova-plugin-geolocation](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-geolocation/) is able to obtain the user location.

**Comment by rlaurente** [comment]
actually I'm testing it separately to have a very simple map plugin integration to track the cause of crash.

In the whole app I'm building I'm using it to show multiple pins for nearby resto, etc. I'm also using the plugin to calculate distances, etc :)

**Comment by ccastroelo** [comment]
I have a similar type of app here and I have also identified the same problem.

**Comment by wf9a5m75** [comment]
@ccastroelo If you can not the issue by yourself, please share your project files on github.

**Comment by wf9a5m75** [comment]
ping

**Comment by ccastroelo** [comment]
I will work in this, give me one day.

**Comment by wf9a5m75** [comment]
ping

**Comment by ccastroelo** [comment]
https://github.com/ccastroelo/ionicGoogleMapsPluginTest

Sorry for the delay, okay, I tested it in a simple code to make sure the problem is not in my project, which is more complex and full of other plugins.
It never returns from getMyLocation.
I suspect it might have something with some new google policy.

I've removed my googlemaps keys from the code.

**Comment by wf9a5m75** [comment]
Are you asking about build problem, or others?

**Comment by ccastroelo** [comment]
I did not understand your question.
I have an ionic / angular app that uses cordova-plugin-googlemaps that works normally. (Complete! For iOS and Android)

I recently made a small adjustment that did not involve the map, but in the tests after compiling for android, I noticed that getMyLocation was not bringing the coordinates. As my plugin was outdated, I upgraded to the latest version, from there I noticed that it does not return from getMyLocation (the callback is never executed).

In all cases the app asks the user for permission to use your location.

To discard any problem of my design and interference from plugin versions, etc, I created this simple project, where getMyLocation is also not returning the coordinates.

I'm sorry if I'm talking any bullshit.

I'll do some more tests.

**Comment by wf9a5m75** [comment]
I see.

The original questioner asked a question about build error, not it's the same error with you.
Your question is `getMyLocation()` does not return.
It's completely different topics.
You should not jump in to other people's thread.

**Comment by wf9a5m75** [comment]
Please create another issue from here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/new?template=question-or-bug-report.md

You just create a new issue thread with subject 'getMyLocation() does not return`.

**Comment by ccastroelo** [comment]
ok, it's because at first my app was crashing for lack of values in getMyLocation and it seemed to be the same problem reported. I'm sorry for this.

**Comment by wf9a5m75** [comment]
It's ok, I don't argue it anymore. But I can't split thread to different thread (there is no feature on Github).
In order to make communication with you better, please create new issue thread.

**Comment by wf9a5m75** [comment]
Since @ccastroelo's topic is not the same as @rlaurente's one, I moved to @ccastroelo's comment into https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2405

**Comment by wf9a5m75** [comment]
@rlaurente Did you solve your problem?

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread. But you can still reply anytime.
