### ISSUE TITLE
getMyLocation() does not return (@ccastroelo)

### ISSUE THREAD

**Issue by wf9a5m75** [mapsplugin/cordova-plugin-googlemaps#2405]
![screen shot 2018-08-28 at 5 27 26 pm](https://user-images.githubusercontent.com/167831/44758162-a8be2100-aae7-11e8-9b6d-7cf21ed975b3.png)

**Comment by wf9a5m75** [comment]
@ccastroelo ping

**Comment by wf9a5m75** [comment]
![screen shot 2018-08-28 at 5 28 22 pm](https://user-images.githubusercontent.com/167831/44758178-c9867680-aae7-11e8-867c-a1d67b56af9e.png)

https://github.com/ccastroelo/ionicGoogleMapsPluginTest

**Comment by wf9a5m75** [comment]
I have no problem, @ccastroelo
![2405](https://user-images.githubusercontent.com/167831/44758412-1b7bcc00-aae9-11e8-9d89-59bd43a7d468.gif)

**Comment by ccastroelo** [comment]
thx for the test. Pls, Could you list your node / npm / ionic version?

**Comment by ccastroelo** [comment]
NM, it's strange, but after I manually enter coordinates in the simulator, I got the getMyLocation return. Before it was not working nor in the device.

**Comment by ccastroelo** [comment]
I may be talking nonsense, but it seems to me that before the location.latLng had the lat and lng in lowercase, now the properties are with the first letter in capital letters.

**Comment by makers-mark** [comment]
I haven't looked at at your repo, but are using strings as opposed to
latlng plugin objects?
