### ISSUE TITLE
Map layer is not completely drawn

### ISSUE THREAD

**Issue by davayd** [mapsplugin/cordova-plugin-googlemaps#2406]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
call-number 0.0.2 "Cordova Call Number Plugin"
card.io.cordova.mobilesdk 2.1.0 "CardIO"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-fingerprint-aio 1.3.8 "FingerprintAllInOne"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.4.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-mauron85-background-geolocation 3.0.0-alpha.38 "CDVBackgroundGeolocation"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-okhttp 2.0.0-dev "OkHttp"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.2.2 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.1 "Launch Navigator"
```
@ionic-native/core : 4.12.0
@ionic-native/google-maps : 4.9.1

**Current behavior:**

1) When i click on INFO block, the app navigate (push) to a detail information page, after I click on BACK button and i see white block on the right side of the map, which doesn't catches clicks. After clicking and dragging an item on the map (e.g. the zoom button on the right), the map is redrawn to the correct view. The most interesting is that this does not always happen (you can see on gif).
2) When i clicking and dragging an element on map  (e.g. the zoom button on the right), the map ALSO dragging in the UP/DOWN.

**Expected behavior:**
1) See the whole map after returning to it.
2) Not dragging map up/down

**Screen capture or video record:**

1)
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/17270614/44781236-816d5f80-ab8c-11e8-8dbd-90b57fcd1d22.gif)

2)
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/17270614/44780956-d6f53c80-ab8b-11e8-9420-91cffb52d79a.gif)

***Related code***
```
<ion-content scroll="false">
  <div #googleMap id="map_canvas">
    <ion-fab left middle>
      <ion-col col-12>
        <button ion-fab color="orange" class="control" (click)="showActiveSession()" [@flyInOut]="hasActiveSession">
          <ion-icon name="ios-alert-outline"></ion-icon>
        </button>
      </ion-col>
      <ion-col col-12>
        <button ion-fab color="light" class="control" (click)="locateMe()" [disabled]="myLocationLoader">
          <ion-icon *ngIf="!myLocationLoader" name="locate"></ion-icon>
          <ion-spinner *ngIf="myLocationLoader"></ion-spinner>
        </button>
      </ion-col>
    </ion-fab>
    <ion-fab right middle>
      <ion-col no-padding>
        <button ion-fab color="light" class="control" (click)="zoomIn()">
          <ion-icon name="add"></ion-icon>
        </button>
      </ion-col>
      <ion-col col-12>
        <button ion-fab color="light" class="control" (click)="zoomOut()">
          <ion-icon name="remove"></ion-icon>
        </button>
      </ion-col>
    </ion-fab>
    <div class="bottom-panel" [@showPanel]="panelIsShown">
      <button ion-button clear color="dark" (click)="openSearch()">
        <ion-icon name="search"></ion-icon>
      </button>
      <button ion-button clear color="dark" (click)="openFilters()">
        <ion-icon name="funnel"></ion-icon>
      </button>
      <button ion-button clear color="dark" (click)="openFavorites()">
        <ion-icon name="bookmarks"></ion-icon>
      </button>
    </div>
  </div>
</ion-content>
```

**Comment by wf9a5m75** [comment]
It's easy. Don't open side panel. The map view is not html Dom element. Thus, don't manipulate, such as  move, resize, or etc.., as much as possible.

**Comment by davayd** [comment]
i've just push another page by NavController and don't manipulate with map

**Comment by wf9a5m75** [comment]
`push and back page by NavController ` moves map view position

**Comment by davayd** [comment]
okay, I get it. how can i resolve this?

**Comment by wf9a5m75** [comment]
Use overlay or open another page.
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g3e207b82bf_886_16

**Comment by davayd** [comment]
okay, i resolve my first question, thanks!
but, what you say about question 2?

**Comment by wf9a5m75** [comment]
Please share your project files on Github.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close thos thread. But you can still reply anytime
