### ISSUE TITLE
The map isn't loading in quickdemo app for Ionic  V4

### ISSUE THREAD

**Issue by rmachado33** [mapsplugin/cordova-plugin-googlemaps#2407]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [X] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.4.2-beta-20180828-1152 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "^5.0.0-beta.14"
@ionic-native/google-maps :  "^5.0.0-beta.20"
```

**Current behavior:**

After following the README instructions (using a different version of the plugin since 5.0.0-beta.15 version isn't available) I got these errors in the console

![image](https://user-images.githubusercontent.com/4340433/44856981-251a4680-ac45-11e8-92e4-76d07259403c.png)

**Expected behavior:**

The map should load like in the browser demo

![image](https://user-images.githubusercontent.com/4340433/44857061-5b57c600-ac45-11e8-9700-76c729720163.png)

Did I miss anything?

**Comment by wf9a5m75** [comment]
Yes, you miss `platform.ready()` I guess.

https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4/blob/4859f0be73a00a85be1654465b6e8cfeca6d5f4a/src/app/home/home.page.ts#L31-L36

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close thos thread. But you can still reply anytime

**Comment by rmachado33** [comment]
I did not forget to include this line `await this.platform.ready ();` I cloned the repository, installed the plug-ins and ran `npm install`.
The code is exactly the same as that of the main branch.

**Comment by wf9a5m75** [comment]
If you can't solve the problem by yourself, please share your project files on GitHub
