### ISSUE TITLE
KMLファイルが読み込めない（then catch どちらも通過しない）

### ISSUE THREAD

**Issue by chankane** [mapsplugin/cordova-plugin-googlemaps#2410]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^4.12.1",
"@ionic-native/google-maps": "^4.12.0",
```

**Current behavior:**

![fail](https://user-images.githubusercontent.com/28649434/44944206-b4725600-ae0d-11e8-8b34-ff7107da156a.png)

**Expected behavior:**

![success](https://user-images.githubusercontent.com/28649434/44944214-da97f600-ae0d-11e8-88b0-b2e8f04cd764.png)
--->

**Related code, data or error log (please format your code or data):**

```TypeScript:home.ts
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import {
  GoogleMaps,
  GoogleMap,
  Marker,
  LatLng,
  GoogleMapsMapTypeId,
  KmlOverlay,
} from '@ionic-native/google-maps';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  // readonly is const(final)
  readonly CENTER: LatLng = new LatLng( 35.549415, 139.779842 );
  map: GoogleMap;
  myMarker: Marker;
  osaka: Marker;

  constructor( public navCtrl: NavController ) {
   this.createMap();
   this.readKml();
  }

  createMap(){
    // create a map
    this.map = GoogleMaps.create('map_canvas', {
      mapType: GoogleMapsMapTypeId.SATELLITE,
      camera: {
        target: this.CENTER,
        zoom: 5
      }
    });

    // create a marker
    this.myMarker = this.map.addMarkerSync({
      title: 'Haneda Airport',
      animation: 'BOUNCE',
      position: this.CENTER
    });
  }

  readKml() {
    //alert('before');
    alert('success');
    this.map.addKmlOverlay( {
      url: 'assets/kml/test.kml'
    } ).then( ( kmlOverlay :KmlOverlay ) => {
      alert('success');
    } ).catch( (err: any) => alert('Error :_(') );
    //alert('after');

    // create a marker (Osaka Airport)
    /*this.myMarker = this.map.addMarkerSync({
      title: 'Haneda Airport',
      animation: 'BOUNCE',
      position: new LatLng( 34.789580, 135.438089 ),
      icon: 'skyblue'
    });*/
  }
}
```
アラートが表示されないのはなぜでしょうか？
ちなみに `@ionic-native/core` と `@ionic-native/google-maps`  をベータ版にアップグレードした場合はそもそも地図が表示されませんでした．（タイトルすら）
今回のケースの git を公開いたします．
[ionic-googlemaps-test.git](https://github.com/chankane/ionic-googlemaps-test)

**Comment by wf9a5m75** [comment]
ionic4と書かれていたのですが、ionic3のファイル構造ですね。

ionic3の場合、`@ionic-native/core`と`@ionic-native/google-maps`は通常版を使います。

あといろいろ事前準備が出来てないですね。

まず[app/src/app.module.ts](https://github.com/chankane/ionic-googlemaps-test/blob/master/src/app/app.module.ts)にGoogleMapsモジュールを追加する必要があります
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g282d0a7bfd_0_115

[app/src/app.component.ts](https://github.com/chankane/ionic-googlemaps-test/blob/master/src/app/app.component.ts)ファイルも変更する必要があります。
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g292c767148_0_0


[page/home/home.ts](https://github.com/chankane/ionic-googlemaps-test/blob/master/src/pages/home/home.scss)に`<div id='map_canvas'>`に対するcssの設定も足りないですね。
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g282d0a7bfd_0_140

コード以外の部分をちゃんと設定してあげれば動くと思います。

**Comment by chankane** [comment]
スライドの通りに修正しましたが、'Please wait...' と出たままです(;.;)
v4の動作も確認するために新しくプロジェクトを作って確認してみましたが、動作に変わりはありませんでした(´･ω･`) 
マップも表示できますし、マーカーも表示できますし（アイコン画像の変更も可能）、位置情報も取得できますが、なぜかKMLだけが読み込めないのです...
git を更新しました（v3）

**Comment by wf9a5m75** [comment]
2つ原因があります。

1つは、どうもKMLファイルが悪いみたいです。
このようにすると`Browser`プラットホームでは表示されます。
（もともとのKMLファイルはGoogle MyMapでも読み込めないです)

```xml
<?xml version="1.0" encoding="utf-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <Placemark>
      <name>Osaka Airport</name>
      <description>description</description>
      <Point>
        <coordinates>135.438089,34.78958,0</coordinates>
      </Point>
    </Placemark>
  </Document>
</kml>
```

もう一つは、ionic3のバグです。
Mapsプラグインとしては `http://localhost:8080/assets/kml/test.kml` にHTTPリクエストをしているのですが、ionicの内部サーバがレスポンスを返さないのでエラーになっていたため、Javaコードが途中で止まったため、`then()` にも `catch()`にもコードが到達しませんでした。

すでに対応するコードに変更したので、multiple_mapsブランチから再インストールしてください。

```
$> ionic cordova plugin rm cordova-plugin-googlemaps

$> ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps  --variable ...
```

![screen shot 2018-09-01 at 11 42 24 pm](https://user-images.githubusercontent.com/167831/44952960-d5a06a00-ae40-11e8-8509-fac7a07f6576.png)

**Comment by chankane** [comment]
うまくいきました。大変お世話になりました。
ありがとうございます。
バグ情報が提供できて何よりですヾ(＾v＾)k
