### ISSUE TITLE
50% of the time the Map is never ready (_isReady stays false)

### ISSUE THREAD

**Issue by mhaddon** [mapsplugin/cordova-plugin-googlemaps#2412]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x ] any problem or bug report

**OS:**  (check one with "x")
- [ x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.2-beta-20180901-2335 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-spotify-oauth 0.1.10 "cordova-spotify-oauth"
es6-promise-plugin 4.2.2 "Promise"
```

**Current behavior:**
When I load the application on the latest release or multi-map, at least 50% of the time the map will never load. I do not mean like: https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/troubleshootings/graymap, or a blankmap. I mean that the Map object gets created with getMap, and an id is assigned to the div, but the map object always has ._isReady equal to false and never triggers the Ready Event. The div itself looks unchanged.
No errors are printed to the console and no errors are printed on build.
This affects the emulator and real phone on Android 8.1.
Is there a way to troubleshoot the creation of a map?

**Expected behavior:**
Map successfully loads on every time getMap is ran.

**Related code, data or error log (please format your code or data):**

I am creating a demo project shortly.

**Comment by wf9a5m75** [comment]
Please share the demo project files on GitHub

**Comment by mhaddon** [comment]
@wf9a5m75 
https://github.com/mhaddon/demo_phonegap

You will need to define the API key.

and in src/js/tiwio/core/GlobalJS
make a file called
GoogleMaps.js
with the contents:

```
window.plugin.google.maps.environment.setEnv({
    'API_KEY_FOR_BROWSER_RELEASE': 'x',
    'API_KEY_FOR_BROWSER_DEBUG': 'x'
});
window.plugin.google.maps.environment.setBackgroundColor("#f3f3f3");
```

You will then need to build the project

go to src folder and do `npm install` and `sudo npm install gulp -g`

Then (cd src && ./build.sh) from the root directory

That will build the Javascript.

then you can just do cordova emulate android

**Comment by wf9a5m75** [comment]
```
masashis-Mac-mini:src masashi$ ./build.sh 
[20:48:30] Using gulpfile ~/Documents/workspace/test/demo_phonegap/src/gulpfile.js
[20:48:30] Starting 'scripts'...

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./js/tiwio/core/GlobalJS/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./GoogleMaps in /Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS
resolve file
  /Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps.webpack.js doesn't exist
  /Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps.web.js doesn't exist
  /Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps doesn't exist
  /Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps.js doesn't exist
  /Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps.json doesn't exist
resolve directory
  /Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps doesn't exist (directory default file)
  /Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps/package.json doesn't exist (directory description file)
[/Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps.webpack.js]
[/Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps.web.js]
[/Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps]
[/Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps.js]
[/Users/masashi/Documents/workspace/test/demo_phonegap/src/js/tiwio/core/GlobalJS/GoogleMaps.json]
 @ ./js/tiwio/core/GlobalJS/index.js 3:0-23

```

**Comment by mhaddon** [comment]
@wf9a5m75 

Yeah you need to make the file mentioned in my other post. I redacted it because of credentials

**Comment by wf9a5m75** [comment]
Please prepare everything before asking me. I'm super busy. Otherwise please debug by yourself.

**Comment by wf9a5m75** [comment]
Okay, I figured out the reason.

```
export default class App {
    static session;

    static load() {
        if (typeof App.session === `undefined`) {
            App.session = new App();
        }
        return App.session;
    }

    constructor() {
        //CoordWatcher.watch();   <-- comment out here
    }
}
```

**Comment by wf9a5m75** [comment]
`cordova-plugin-geolocation` blocks other plugin execution for some reason.
I don't know why, and I don't support the conflict with other plugins.
Please ask to them if you want to know more deeply.

**Comment by mhaddon** [comment]
@wf9a5m75 I believe the reason is that sometimes the geolocation would return null for the heading and when the heading is null it breaks your plugin. That makes sense and is understandable but maybe there could be a way to handle null pointer exceptions.
I need to do more testing but I believe my API stuff has just expired because of my debit card expiring. So I need to wait 3 days before I can do more tests.

**Comment by wf9a5m75** [comment]
Giving what values in proper is responsibility of application developer.

**Comment by wf9a5m75** [comment]
ping

**Comment by mhaddon** [comment]
That fixed ~95% of the time when it failed to load, it still happens 5% or so of the time, but I assume it is another null pointer exception floating around. 

Even though giving the correct values is the responsibility of the developer, it would be nice to have some error messages in the console which explain which value is incorrect, or even a simple general error like "invalid configuration settings". To point developers to the right area of the fault.

Since I am confident that null pointers are the problem, I will close this ticket.

**Comment by tryhardest** [comment]
How did you resolve your null pointer exception @mhaddon?
