### ISSUE TITLE
Styling markerCluster and label of marker cluster

### ISSUE THREAD

**Issue by jrsanchezalcala** [mapsplugin/cordova-plugin-googlemaps#2414]
Hi everyone,
i would like to apply some styles to the label of markercluster and icon . In the example you can set some labelOptions for the label like color and fontSize but , what are not enougth. I would like for example tu put the label in the right side of the cluster , becouse de icon shows "+" simbol and if the label appears in right side it seems better.

Could this be posible?

Thank you in advance.

**Comment by wf9a5m75** [comment]
Nop.
