### ISSUE TITLE
(Browser) Fix: map.setCameraTarget() implementation is wrong

### ISSUE THREAD

**Issue by alex-polosky** [mapsplugin/cordova-plugin-googlemaps#2416]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android** ( Could be an issue, haven't yet tested )
- [ ] **iOS** ( Could be an issue, haven't yet tested )
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-camera-preview 0.9.0 "cordova-plugin-camera-preview"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-geolocation 4.0.2-dev "Geolocation"
cordova-plugin-googlemaps 2.4.2 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.2.0 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.2 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "4.4.0",
"@ionic-native/google-maps": "^4.12.0",
```

**Current behavior:**

Calling GoogleMaps.create('map_canvas', {}).setCameraTarget(LatLng) where LatLng is an implementation of ILatLng fails with an error of "InvalidValueError: setCenter: not a LatLng or LatLngLiteral: not an Object". I dug into the internals to see where exactly the issue is coming from, and it looks like the issue is in src/browser/PluginMap:PluginMap.prototype.setCameraTarget, line 333. Instead of passing in the args as the object, it's passing in args[0], which only references the latitude.
I suppose I might be able to get around this by telling my linter to ignore the line, and then passing in [LatLng]. although I have yet to test it.

**Expected behavior:**

The call to setCameraTarget should work as expected. 

**Screen capture or video record:**

No screen capture as it's not a visual bug

**Related code, data or error log (please format your code or data):**

```
class LatLng implements ILatLng {
    public lat: number;
    public lng: number;
    constructor(lat: number, lng: number) {
        this.lat = lat;
        this.lng = lng;
    }
}

@IonicPage()
@Component({
    selector: 'test',
    template: '<div id="map_canvas"></div>'
})
export class TestComponent {
    constructor() {}
    public ionViewDidLoad() {
        let map = GoogleMaps.create('map_canvas', {});
        map.setCameraTarget(new LatLng(20, -60));
    }
}
```

**Comment by alex-polosky** [comment]
Please disregard, I just realized that the call signature for setCameraTarget is an array. -_-

**Comment by alex-polosky** [comment]
Yeah, so I think I fixed it? I changed the exec.call in setCameraTarget in Map from `this.exec.call(this, null, this.errorHandler, this.id, 'setCameraTarget', [latLng.lat, latLng.lng]);` to `this.exec.call(this, null, this.errorHandler, this.id, 'setCameraTarget', [latLng]);` and everything loads properly. I just need to figure out how to change it so it's not overwritten everytime I build. I'll probably just make a branch and install the plugin from there.

**Comment by alex-polosky** [comment]
Branch has been made with the fix (unfortunately I accidentally left the commented code in there, but as I assume that it's something that I'm doing this doesn't actually fix whatever I was doing wrong):

https://github.com/alex-polosky/cordova-plugin-googlemaps/tree/setCameraTarget_fix

**Comment by wf9a5m75** [comment]
```
map.setCameraTarget({
  lat: ...
  lng: ...
})
```

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/setCameraTarget.html

**Comment by wf9a5m75** [comment]
```

class LatLng implements ILatLng {
    public lat: number;
    public lng: number;
    constructor(lat: number, lng: number) {
        this.lat = lat;
        this.lng = lng;
    }
}

```

Why are you creating own class?

**Comment by wf9a5m75** [comment]
You should read documents before using this plugin

```
    let mapOptions: GoogleMapOptions = {
      camera: {
         target: {
           lat: 43.0741904,
           lng: -89.3809802
         },
         zoom: 18,
         tilt: 30
       }
    };

    this.map = GoogleMaps.create('map_canvas', mapOptions
```
https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/README.md

https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000

**Comment by wf9a5m75** [comment]
If you drive a car with wrong way, the car doesn't work correctly.

As the same, if you use this plugin without reading documents, the plugin does not work correctly.

**Comment by alex-polosky** [comment]
Yeah, doing this:
```
map.setCameraTarget({
  lat: ...
  lng: ...
})
```
Results in that error that I posted above.

I do not want to destroy the map and recreate it every time the user's position changes.

I'm creating my own class because there are additional properties that need to be added to what I am using, I gave a minimal example which causes the issue. I then saw that there is already an implementation for LatLng, but that still throws the error. Regardless, if the function only expects a signature of ILatLng, it should work.

Either way, I've found the root of the issue, and I fixed it in the branch that I linked above.

**Comment by wf9a5m75** [comment]
Can you read Java a little?
Well even if you are not familiar with Java, you can understand those three code lines.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/f84c3cf388792784050f2a2f485ce621a01d770a/src/android/plugin/google/maps/PluginMap.java#L1395-L1398

So the native code expects `args[0] = lat; args[1] = lng`

----

In JS side, can you read JavaScript?
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/f84c3cf388792784050f2a2f485ce621a01d770a/www/Map.js#L291-L295

**Comment by wf9a5m75** [comment]
Ah, ok. I got it.
Browser code is wrong.

Code of platforms must be all the same behaviors.

In Android, and iOS, native code expects `array`.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/c4b3c117ebbc8cac6d552f2d1909451d78244a06/src/android/plugin/google/maps/PluginMap.java#L1395-L1397

But browser code is wrong.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/c4b3c117ebbc8cac6d552f2d1909451d78244a06/src/browser/PluginMap.js#L330-L333

Thus, browser code implementation is wrong.

-----

I already fixed the problem.
Please reinstall the plugin from the multiple_maps branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable...
```

**Comment by alex-polosky** [comment]
Didn't realize that about the plugins, actually. That is good information for when I finally get around to trying out writing my own in the future. So I had just solved it in the wrong area then lol.

Thanks for looking into it and fixing it mate! Cheers.
