### ISSUE TITLE
map.getMyLocation() doesn't run any callbacks

### ISSUE THREAD

**Issue by sonlexuan** [mapsplugin/cordova-plugin-googlemaps#2419]
I'm using Ionic1/AngularJS on my App. The issue is:
When I open my App with GPS is off, I did using "map.getMyLocation(options, successCallback, errorCallback)" after MAP_READY and it did run the "errorCallback" as I expected. But after that, I enable GPS and call getMyLocation() again, it's never been running into any callback, either successCallback or errorCallback. 
I did using `plugin.google.maps.LocationService.getMyLocation()` instead of  `map.getMyLocation()` but it still happens. Beside, I also try: `navigator.geolocation.getCurrentPosition(geolocationSuccess,geolocationError,
                                         {
            enableHighAccuracy: true, // Force GPS
            timeout: 10000
        });`
But it always error with time_out code
Thank u!!
Here is my code:

`
var map;
vm.initNativeMap = function () {
        var mapOption = {
            'backgroundColor': '#ffc20e',
            'controls': {
                'compass': true,
                'myLocationButton': false
            },
            'gestures': {
                'scroll': true,
                'tilt': true,
                'rotate': true,
                'zoom': true
            }
        }
        var div = document.getElementById("map_canvas");
        map = plugin.google.maps.Map.getMap(div, mapOption);
        map.one(plugin.google.maps.event.MAP_READY, onMapReady);
    }

    function onMapReady() {
        console.log("map ready >> find current location");
        map.moveCamera({
            'target': SAUDI_ARABIA_LOCATION,
            'zoom': 5
        });
       vm.getLocation(true);
    }

    vm.getLocation = function () {
        map.getMyLocation({
            enableHighAccuracy: true, // Force GPS
            timeout: 10000
        },onGetLocationSuccess, onGetLocationError);
    }
`
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

com.microsoft.azure-mobile-services 1.2.9 "Windows Azure Mobile Services"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.3 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-sms 1.0.5 "SMS"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
cordova-sqlite-storage 2.2.0 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
phonegap-plugin-push 2.1.2 "PushPlugin"

**Comment by wf9a5m75** [comment]
Reboot your device. It is depends on your device.

**Comment by wf9a5m75** [comment]
ping

**Comment by sonlexuan** [comment]
Hi @wf9a5m75 , I tested on so many different Android devices but it still happens!!

**Comment by sonlexuan** [comment]
@wf9a5m75 please take a look at this video record [https://youtu.be/CRfKdiwuH9U](url)
I add a loading icon when click the button and also call:
`map.getMyLocation({
        enableHighAccuracy: true, // Force GPS
        timeout: 10000
    },onGetLocationSuccess, onGetLocationError);`
The function to hide loading icon I set on both `onGetLocationSuccess` and `onGetLocationError`

**Comment by wf9a5m75** [comment]
There is no timeout option.


Ok, please share your project files on GitHub.

**Comment by wf9a5m75** [comment]
Try the multiple_maps branch code.

**Comment by wf9a5m75** [comment]
ping

**Comment by sonlexuan** [comment]
Thank @wf9a5m75 , I'm using multiple_maps branch and it works well until now with all the devices used to happen this issue!!
On my HTC One M7, the issue still happens but nevermind. I just want to add an options timeout when call map.getMyLocation().
Thank u so much!!
