### ISSUE TITLE
App won't build when GoogleMaps and PushPlugin are installed even when google-play-services versions are the same

### ISSUE THREAD

**Issue by esol1** [mapsplugin/cordova-plugin-googlemaps#2420]
**I'm submitting a ...**  (check one with "x")
- [] question
- [X ] any problem or bug report

**OS:**  (check one with "x")
- [X ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-support-google-services 1.2.1 "cordova-support-google-services"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "~4.12.0"
@ionic-native/google-maps :  "^2.4.2"
```

**Current behavior:**
When creating a new Ionic app and adding the GoogleMaps and Push plugins, the app doesn't build for android:

 1. Create new project
 2. cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable FCM_VERSION=15.0.2
 3. cordova plugin add cordova-plugin-googlemaps --variable
    API_KEY_FOR_ANDROID="123"  --variable API_KEY_FOR_IOS="ABC" --variable PLAY_SERVICES_VERSION=15.0.2
 4. cordova platform add android@latest
 5. cordova build android - Fails

It seems that google-play-maps and google-play-location are not found and the build is failing.

Error Output
Could not find com.google.android.gms:play-services-maps:15.0.2.
  Searched in the following locations:
> https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-maps/15.0.2/play-services-maps-15.0.2.jar
 > https://maven.google.com/com/google/android/gms/play-services-maps/15.0.2/play-services-maps-15.0.2.pom
...and many more similar locations.
...and...

Could not find com.google.android.gms:play-services-location:15.0.2.
  Searched in the following locations:
> https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/15.0.2/play-services-location-15.0.2.jar
> https://maven.google.com/com/google/android/gms/play-services-location/15.0.2/play-services-location-15.0.2.pom
...and many more similar locations.

Android Studio and all build tools are fully updated.

if either plugin is removed then the build succeeds.

**Expected behavior:**
App should simply build.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
> Could not find com.google.android.gms:play-services-maps:15.0.2.

As the error log says, there is no `com.google.android.gms:play-services-maps:15.0.2.`

**Comment by wf9a5m75** [comment]
Check out here for what version is the latest.
https://developers.google.com/android/guides/setup

![screen shot 2018-09-13 at 4 50 37 pm](https://user-images.githubusercontent.com/167831/45521950-2d11d480-b775-11e8-8dab-d19b60c44477.png)
