### ISSUE TITLE
Touch map problem

### ISSUE THREAD

**Issue by luisfernando-rf** [mapsplugin/cordova-plugin-googlemaps#2421]
Good afternoon, every time I start my job application and I make my first login, my map is being loaded and it locks its touch. Do not just enter, enter and re-enter the map button normally.

I have already tried to force with "map.setClickable (true)" however, to no avail. What could be the problem?

**Comment by wf9a5m75** [comment]
Please share your project files on Github.

**Comment by luisfernando-rf** [comment]
Follow the link below:

https://github.com/luisfernando-rf/photoSellingMobileUI

**Comment by wf9a5m75** [comment]
Thank you for sharing the project files, but do you have test account?

![capture](https://user-images.githubusercontent.com/167831/45577036-f4cecc80-b82e-11e8-9598-ebbee1ce79ad.png)

**Comment by luisfernando-rf** [comment]
Sorry, yes 

Login: teste@rf.com.br
Password: 111

**Comment by wf9a5m75** [comment]
Thank you, but the authentication has never ended up.

**Comment by wf9a5m75** [comment]
ping

**Comment by luisfernando-rf** [comment]
Try changing the login code only to move to the next page and loading the map that will work.

**Comment by luisfernando-rf** [comment]
Attached is apk. So you can do the simulation.

[app-debug.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2389422/app-debug.zip)

**Comment by wf9a5m75** [comment]
I don't accept any zip file, it's kind of spam. Please change your code on Github.

**Comment by luisfernando-rf** [comment]
The code is the same, I added app-debug-update.apk to the next GitHub path, to perform the simulation.

photoSellingMobileUI / platforms / android / app / build / outputs / apk / debug / app-debug-update.apk

https://github.com/luisfernando-rf/photoSellingMobileUI/tree/master/platforms/android/app/build/outputs/apk/debug

**Comment by luisfernando-rf** [comment]
Use the login and password that I mentioned above. However, the problem is on the map, it's already stuck. The error can be a network that uses that is different, because I am from Brazil.

**Comment by wf9a5m75** [comment]
If I decline the geolocation permission, map is interactive.

**Comment by luisfernando-rf** [comment]
Sorry, but a question does not have access with a geographic location, I just want to know why it's not the first Login and then it's normal.

**Comment by wf9a5m75** [comment]
Inspecting. Please wait.

**Comment by wf9a5m75** [comment]
Ok, the reason is `navigator.geolocation.getCurrentPosition` blocks this plugin preparation for some reason.

**Comment by wf9a5m75** [comment]
If you use `plugin.google.maps.LocationService.getMyLocation(config, onSuccess, onError);`, the code works as you expected.

```
    var config = {
        enableHighAccuracy: true
    }
    plugin.google.maps.LocationService.getMyLocation(config, onSuccess, onError);
}

function onSuccess(position) {
    map.clear()
    rotas = []
    routesOrder = []
    origem = null

    var localizacaoVend = {
        lat: location.latLng.lat,
        lng: location.latLng.lng,
        distance: (location.latLng.lat + location.latLng.lng)
    }

```

**Comment by wf9a5m75** [comment]
Um, it seems it is not caused by `navigator.geolocation.getCurrentPosition`, but keyboard causes this problem.

When I login to your app without entering `email` and `password` (I set default values for these fields), the application works perfectly.

**Comment by luisfernando-rf** [comment]
hmm, may be, have any solutions to this problem?

**Comment by wf9a5m75** [comment]
I have no solution at this time.

**Comment by luisfernando-rf** [comment]
Should I wait? What should I do?

**Comment by wf9a5m75** [comment]
Hey, why didn't you try the latest version before asking me :angry: ?
You use `v2.3.6` which is too old.

This problem has been already fixed in the past.
Using the `v2.4.3`, there is no problem at all.

**Comment by wf9a5m75** [comment]
Do not waste my time.

**Comment by luisfernando-rf** [comment]
I can not update the plugin, every time I upgrade it brings me to version v2.3.6.

How should I do?

**Comment by wf9a5m75** [comment]
You specified `v2.3.6` at here.
https://github.com/luisfernando-rf/photoSellingMobileUI/blob/master/package.json#L15

In order to upgrade the plugin, you just need to uninstall, then reinstall the plugin.

```
$> cordova plugin rm cordova-plugin-googlemaps

// for just in case
$> rm -rf plugins/cordova-plugin-googlemaps

$> cordova plugin add cordova-plugin-googlemaps --variable ....

// confirm
$> cordova plugin list
```

**Comment by wf9a5m75** [comment]
Installation is your problem, not plugin's bug.

 Simply try to remove thr Android platform

**Comment by luisfernando-rf** [comment]
Solved, thanks for the support and sorry for the unforeseen.
