### ISSUE TITLE
Map on ionic 3 modal nor showing

### ISSUE THREAD

**Issue by francoro** [mapsplugin/cordova-plugin-googlemaps#2423]
I know it works if i do it in a page, but the problem is when i try in a modal, it only shows me the header of the page that has the map and where the content of the map should be it shows me a transparent layer so i can see my previous page , my questions is: I have to put some css to make it work on a modalpage?

**Comment by wf9a5m75** [comment]
Map view is displayed under the browser, not in HTML modal page.
https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios

**Comment by francoro** [comment]
Okay, it has to be from a page to page with map.Because from a modal to a page it doesnt work either

**Comment by wf9a5m75** [comment]
If you don't want to do that, you can't use this plugin.

**Comment by francoro** [comment]
I will do it in a page, thanks for your answers.
