### ISSUE TITLE
map.setOptions on browser throws error

### ISSUE THREAD

**Issue by jonathan-chin** [mapsplugin/cordova-plugin-googlemaps#2426]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [X] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 6.0.9
@ionic-native/google-maps : 5.0.0-beta.20
```

**Current behavior:**
I can't set the map options after it is initialized. My calling code is simple:

```
setOptions(){
        this.map.setOptions({draggable: false});
    }
```
but I get this error:
```
Exception calling native with command :: map_0_683723465206 :: setOptions ::exception=ReferenceError: options is not defined
```
I think it relates back to this:

```
cordova-plugin-googlemaps/src/browser/PluginMap.js
starting on line 251

PluginMap.prototype.setOptions = function(onSuccess, onError, args) {
  var self = this;
  var map = self.get("map");

  var mapInitOptions = {};

  if (options) {
```

options is not in the function signature

**Expected behavior:**

**Related code, data or error log (please format your code or data):**

<img width="1184" alt="screen shot 2018-09-19 at 7 44 56 pm" src="https://user-images.githubusercontent.com/7519412/45787713-a3ff0f80-bc44-11e8-8ea7-ff450a2d9bc1.png">

I made minimal adjustments to the example app. I added a button on the home page that tries to run setOptions

https://github.com/jonathan-chin/cordova-google-maps-setoptions

**Comment by wf9a5m75** [comment]
Try `cordova-plugin-googlemaps 2.4.4`

**Comment by jonathan-chin** [comment]
Thanks. that fixed it.

**Comment by jonathan-chin** [comment]
sorry, it no longer throws the error. however, the options don't seem to change
```
this.map.setOptions({draggable: false});
```
the map gets pointed at 0 latitude, 0 longitude and is still draggable.

**Comment by jonathan-chin** [comment]
Thanks. It seems like what I need is the gesture options.
