### ISSUE TITLE
Center mapa

### ISSUE THREAD

**Issue by luisfernando-rf** [mapsplugin/cordova-plugin-googlemaps#2428]
Is there a function that centralizes the map according to the origin and destination marker?

For example, on a route you would like to center the map in the center between the origin and the destination to appear the entire route of the map.

**Comment by wf9a5m75** [comment]
You need to calculate the center using LatLngBounds everytime.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/LatLngBounds/README.md

**Comment by wf9a5m75** [comment]
`latLngBounds.getCenter()`

**Comment by luisfernando-rf** [comment]
Error

![image](https://user-images.githubusercontent.com/41697952/45832906-90ea4f00-bcd9-11e8-8d1c-123ee397089c.png)

**Comment by wf9a5m75** [comment]
Ok, please share your project files on Github.

**Comment by luisfernando-rf** [comment]
Follow:

https://github.com/luisfernando-rf/photoSellingMobileUI/blob/master/www/js/map.js

**Comment by wf9a5m75** [comment]
You must pass `LatLng` class of this plugin, not `Google Maps JavaScript API v3`'s one.

**Comment by luisfernando-rf** [comment]
Ignore me, I'm going through the var "waypts". And yet the error is occurring.

**Comment by wf9a5m75** [comment]
Can you understand what I say?

**Comment by luisfernando-rf** [comment]
Yes, check again for kindness, I'm passing the waypts array which is a LatLng and even then the error mentioned above occurs.

https://github.com/luisfernando-rf/photoSellingMobileUI/blob/master/www/js/map.js

**Comment by wf9a5m75** [comment]
Can you read English?

>You must pass {lat: ..., lng: ...}, not {latitude: ..., longitude: ...}

https://github.com/luisfernando-rf/photoSellingMobileUI/blob/019629f/www/js/map.js#L166-L172

**Comment by luisfernando-rf** [comment]
Yes, I'm passing lat and lng.

![image](https://user-images.githubusercontent.com/41697952/45835370-4ae4b980-bce0-11e8-9181-2c50126db35f.png)

**Comment by wf9a5m75** [comment]
Haaaaa......:weary:

```js
var locRoutes = new google.maps.LatLng(r.latitude, r.longitude)

waypts.push({
   location: locRoutes
})
```
https://github.com/luisfernando-rf/photoSellingMobileUI/blob/019629f/www/js/map.js#L164-L168

Change here to 

```
waypts.push({
  lat: r.latitude,
  lng: r.longitude
});
```

**Comment by wf9a5m75** [comment]
@luisfernando-rf ping

**Comment by luisfernando-rf** [comment]
Gracias

**Comment by luisfernando-rf** [comment]
Do you have something like getCenter to manipulate the map zoom?

**Comment by wf9a5m75** [comment]
I'm not your Q&A machine.
Please read documents a lot.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Map/getCameraPosition/README.md

**Comment by luisfernando-rf** [comment]
Answering so you will lose the morale you have in this plugin. And the forums are for questions, if you do not want to answer close them. thanks bro

**Comment by luisfernando-rf** [comment]
You think I did not read the documentation? Just wondering if some function to manipulate the zoom and not get the value of zoom .........

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.3.0/class/Map#get-the-camera-position
