### ISSUE TITLE
Release >3.11 will result in unclickable area

### ISSUE THREAD

**Issue by madoBaker** [mapsplugin/cordova-plugin-googlemaps#2429]
Noticed this bug once i updated the plugin to latest, i was using 3.10 before updating and all was fine..

once the map has been added as a plugin and used, it seems like the top section, where the toolbar would be, becomes unclickable.. 

In other words, throughout the app (doesnt have to be on same page as map) if you dont have a toolbar set, and you try clicking on where the toolbar would be (close button, maybe even a search input field) no clicks are register, but as soon as you click right under the spot where the toolbar would occupy, it registers the click...

Fixed the issue by removing plugin and adding v3.11

if my horrible explanation isn't descriptive enough, i can provide photos

**Comment by wf9a5m75** [comment]
This plugin latest version is `version 2.4.4`. I have never released `v3.10`

**Comment by wf9a5m75** [comment]
ping @madoBaker

**Comment by madoBaker** [comment]
Sorry i meant 2.3.11(and 2.3.10) vs 2.4.4

**Comment by wf9a5m75** [comment]
Could you rewrite your description? And please share your project files on Github.

**Comment by makers-mark** [comment]
Wow, a screenshot would be great be great too (you offered).

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by madoBaker** [comment]
I can't do that. It's a completed app and too much confidential info.

Are there specific files you'd like to see? Maybe the google maps TS code? or the `explore` tab (where the map is) html?

I'm sure it has something to do with this package as if I rebuild the app without changing anything, except for updating the google maps package to latest release, I get this issue.

**Comment by wf9a5m75** [comment]
If you can't share your project, how can I test the problem?

I that case, please debug by yourself
