### ISSUE TITLE
Is there a way I could use heatmap with your plugin?

### ISSUE THREAD

**Issue by AlbertSanIza** [mapsplugin/cordova-plugin-googlemaps#2430]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [x] **Browser**

I mostly want to use it with ionic on mobile devices.

Something like this:
https://developers.google.com/maps/documentation/javascript/examples/layer-heatmap
https://developers.google.com/maps/documentation/ios-sdk/utility/heatmap

**Comment by wf9a5m75** [comment]
not implement it
