### ISSUE TITLE
File promise-7.0.4.min.js.map is missing

### ISSUE THREAD

**Issue by livedota** [mapsplugin/cordova-plugin-googlemaps#2436]
- [ ] question
- [X ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ X] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

cordova-plugin-googlemaps 2.4.6
cordova-plugin-whitelist 1.3.3

**Current behavior:**
Map not showing 

**Expected behavior:**
Map should show

**Screen capture or video record:**
![cattura](https://user-images.githubusercontent.com/15877216/46155093-d62cf480-c276-11e8-90d7-8ff83154afe8.PNG)
![map](https://user-images.githubusercontent.com/15877216/46155095-d6c58b00-c276-11e8-8d76-a00a2211b8c1.PNG)

Additional Information:
I can add marker and use location button
In brower work

**Comment by wf9a5m75** [comment]
Gray map means your api key does not allow to use the Google Maps SDK for iOS.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/graymap/README.md

The js error is not related and affect it.

**Comment by livedota** [comment]
What about the console error?

**Comment by wf9a5m75** [comment]
That's just there is no file error, that file is not necessary to use this plugin.

**Comment by livedota** [comment]
The problem was i didn't enabled the api for ios. Tanhks and sorry if have bother you.

**Comment by tim-coin** [comment]
I am again facing this issue in Ionic Cordova with High Sierra Xcode 10.

cordova-android-support-gradle-release 1.4.7 "cordova-android-support-gradle-release"
cordova-plugin-accountkit 1.4.0 "Cordova AccountKit"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-buildinfo 1.1.0 "BuildInfo"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"

`
```
Ionic:

   ionic (Ionic CLI)  : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.6.0
   @ionic/app-scripts : 2.1.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0, ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 17 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/meenuaggarwal/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v8.12.0 (/usr/local/Cellar/node/11.1.0/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```
`

**Comment by makers-mark** [comment]
Yeah, I can help. Read the posts in the link that you Googled.
