### ISSUE TITLE
Can not load icon image file for Marker after external link opened

### ISSUE THREAD

**Issue by chadevans** [mapsplugin/cordova-plugin-googlemaps#2438]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x ] any problem or bug report

**OS:**  (check one with "x")
- [ x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "4.14.0" (also tested on 4.8.0)
@ionic-native/google-maps : "4.14.0" (also tested on 4.8.2)
```

**Current behavior:**
On Android, clicking a simple "a" link which takes the user out the of the app and into a web browser removes custom marker icons on the map. Marker images from a URL and Base64 marker images are not affected, only marker images from the local file path.

**Expected behavior:**
Clicking an "a" link anywhere in the app should not prevent the maps plugin from being able to use custom marker icons from a local filepath.

**Screen capture or video record:**

[markerfilebug.m4v.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2425387/markerfilebug.m4v.zip)

I made a modification of the ionic-googlemaps-quickdemo repo for testing:
https://github.com/chadevans/ionic-googlemaps-quickdemo/tree/android-link-bug-example

If you build from this repo/branch, you will need to add keys.

All I did was add an "a" link to the home page and a filepath icon to the marker on the HtmlInfoWindow page. Feel free to use this or just test in any app using this plugin.

**Comment by wf9a5m75** [comment]
Thank you for preparing, but attaching zip file is kind of spam.
Because I can't see it on mobile.
Please upload it to youtube.

**Comment by chadevans** [comment]
[YouTube video link](https://youtu.be/Qda_WgwBOcw)

**Comment by wf9a5m75** [comment]
Thank you for uploading the video. Umm, that's curiosity.

**Comment by chadevans** [comment]
Agreed. It doesn’t happen on iOS.

**Comment by PatrickMello** [comment]
Hi!
I have the same problem, I caught the log entries:

```shell
$ adb -d logcat | grep png
09-27 21:31:43.516 15742 21408 W System.err: java.io.FileNotFoundException: www/img/icon/img/location-large.png
09-27 21:36:01.180 22851 25779 W System.err: java.io.FileNotFoundException: www/img/icon/img/woman-large.png
09-27 21:36:03.225 22851 25811 W System.err: java.io.FileNotFoundException: www/img/icon/img/ios-circle-filled-large.png
```
In all icons URLs I passed the path `img/file_path_sample.png` which is relative to my `www` folder. When the map is rendered and `map.addMarker(options)` is called, the path is changed on plugin. But if I restart the app, the same map is rendered as expected.

Thanks for your time!

**Comment by wf9a5m75** [comment]
Confirmed.

Enable this line, then output are changed.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/293815d811f3bfe8febd95287cf1a6d23b665846/src/android/plugin/google/maps/AsyncLoadImage.java#L131

**first time (just open the HtmlInfoWindowPage)**
```
 -->currentPageUrl = file:///android_asset/www/index.html
```

**second time (open the external url, then open the HtmlInfoWindowPage)**
```
-->currentPageUrl = http://www.apple.com/
```

Um, this is curiosity.

**Comment by wf9a5m75** [comment]
Ok, I got the reason, this is a bug.

**Comment by wf9a5m75** [comment]
Fixed. Please reinstall the plugin from the multiple_maps branch.
Thank you for reporting such a rare bug.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ....
```

**Comment by PatrickMello** [comment]
@wf9a5m75 Thanks a lot, man!

**Comment by wf9a5m75** [comment]
Thank you for using this plugin.

**Comment by RaphyLi** [comment]
Hi,

I have the same issue on iOS.

`    const markerOptions = {
      icon: {
        url: '../../assets/imgs/numeroquestion_3x.png',
        size: {
          width: 32,
          height: 32
        }
      },
      animation: 'BOUNCE',
      position: {
        lat: latitude,
        lng: longitude
      }
    };

    const marker = this.googleMap.addMarkerSync(markerOptions);`

This is my code when a set my custom pointer.

I also tried to wrote `assets/imgs/numeroquestion_3x.png` but same problem.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2438#issuecomment-425340080

**Comment by RaphyLi** [comment]
@wf9a5m75 I tried this but the fix is for Android and on iOS the problem still here.
