### ISSUE TITLE
"Failed to load optimized model at path" with XCode 10

### ISSUE THREAD

**Issue by collindutter** [mapsplugin/cordova-plugin-googlemaps#2440]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
phonegap-plugin-push 2.2.3 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^5.0.0-beta.21",
"@ionic-native/google-maps": "^5.0.0-beta.23"
```

**Current behavior:**
Map fails to load and the console prints `Failed to load optimized model at path '/var/containers/Bundle/Application/DCF4B796-3AE6-4E1A-B083-CD5AED06223A/ridetrackr-ionic.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'`

This issue is documented here: https://issuetracker.google.com/issues/64504919 and several people claim to have gotten it working (issues with UI constraints). Not sure if anything can be done in the scope of this project, just figured I would see if there are any workarounds.
**Expected behavior:**
Map should load and this error should not print.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Tell me if you find the solution.

**Comment by wf9a5m75** [comment]
As far as I read the issue thread, there is no solution, and the error is not related with the map currently.

**Comment by collindutter** [comment]
It seems like most people in the thread are still able to get the map loading, but the error just displays in the background. Any idea why it might not be loading at all in this case?

**Comment by wf9a5m75** [comment]
Do you mean you see the grey map? 
If so, it means your api key does not allow to use your application id.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/graymap/README.md

**Comment by collindutter** [comment]
Actually after further investigation, my issue was with @ionic/angular beta 12. The map was actually loading, but appeared to be behind the ion-content so I just saw a white screen. Downgrading to beta 11 fixed this.

**Comment by wf9a5m75** [comment]
Congrats!

**Comment by collindutter** [comment]
Thanks! I would eventually like to upgrade to beta 12 though. Any idea why the map might be getting put behind the content? Anything from these? https://github.com/ionic-team/ionic/commit/9badb08 https://github.com/ionic-team/ionic/commit/f68c457 https://github.com/ionic-team/ionic/commit/5f5ba66

**Comment by wf9a5m75** [comment]
Check out here please.
https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios
![](https://raw.githubusercontent.com/mapsplugin/cordova-plugin-googlemaps-doc/master/v1.4.0/class/Map/mechanism.png)

**Comment by collindutter** [comment]
Ah looks like the content transparency was the issue, thanks! One last note, now page transitions appear a bit strange because the background is transparent so it looks like the individual elements on the page are transitioning in, rather than the entire page. This might be a bit out of the scope for this library, but do you have a recommended method of making the page transparent only once it is fully loaded in?

**Comment by zaarheed** [comment]
> Ah looks like the content transparency was the issue

@collindutter did you find a workaround for this in beta.11 or later?
