### ISSUE TITLE
Plugin Crash

### ISSUE THREAD

**Issue by kodeine** [mapsplugin/cordova-plugin-googlemaps#2441]
<img width="962" alt="screen shot 2018-09-28 at 7 04 23 pm" src="https://user-images.githubusercontent.com/8620059/46238406-65a6d600-c351-11e8-86a0-c5082234c4c1.png">

**Comment by wf9a5m75** [comment]
What version do you use?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a248a1366d1d80873cccdd4a2203a7275a6f98cc/src/android/plugin/google/maps/PluginLocationService.java#L454

**Comment by wf9a5m75** [comment]
Please test the latest version before asking. Just posting error log is rude.

**Comment by kodeine** [comment]
@wf9a5m75 it was `"cordova-plugin-googlemaps": "^2.3.6",` and its weird that line 454 ends up with `Log.d(TAG, "---->The last location is obtained in 2 sec.");`

**Comment by wf9a5m75** [comment]
You use `v2.4.3`
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v2.4.3/src/android/plugin/google/maps/PluginLocationService.java#L454

**Comment by wf9a5m75** [comment]
Do you know what version is the latest?

**Comment by kodeine** [comment]
@wf9a5m75 i am aware of the latest version and your sarcastic comments doesn't help anyone. I wanted to bring the error to your attention because you've coded this plugin and you know what your code does exactly. I don't follow your plugins change log to see if that error was fixed or not. If it was fixed, please point me to that change log. Thank you for your time. closing this issue.

**Comment by wf9a5m75** [comment]
You don't following updates is your freedom, but you should confirm the latest version before asking.
Please don't steal my time.
