### ISSUE TITLE
Using different maps than Google maps

### ISSUE THREAD

**Issue by kozuch** [mapsplugin/cordova-plugin-googlemaps#2447]
I have a question - is it possible to use different maps than Google maps (normal/satellite) but still use the features of the plugin (markers etc.). Or maybe at least hide the map - I mean background only and leave markers etc. visible. I would like to use different map source (OSM etc.). Thanks.

**Comment by wf9a5m75** [comment]
> You can change map type using map.setMapTypeId(). Available map types are ROADMAP, SATELLITE, HYBRID, TERRAIN and NONE.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Map/setMapTypeId/README.md

**Comment by kozuch** [comment]
Thanks. do you have any hints on how to deal with a 3rd party map when using NONE map type for googlemaps? I mean to integrate some other solution like leaflet etc. but where the map touch gestures (move, rotate, zoom) still work? Is it possible to catch these touch events from your plugin so that they can me "forwarded" to other mapping framework?

**Comment by wf9a5m75** [comment]
I recommend you see document overview what this plugin can do before asking.


https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/TileOverlay/README.md

**Comment by kozuch** [comment]
thanks, i was looking for the page you posted :)
