### ISSUE TITLE
The map is not displayed correctly

### ISSUE THREAD

**Issue by gillouxxx** [mapsplugin/cordova-plugin-googlemaps#2448]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

Packages used :
"@ionic-native/core": "^4.12.0"
"@ionic-native/google-maps": "^4.12.0",
"cordova-plugin-googlemaps": "^2.4.1",
"cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.7.0",

Current behavior:
When I go back to my page (button back) which contains the map, sometimes, the map is not displayed correctly on the width.

Expected behavior:
When I go back to my page (button back) which contains the map, the map is displayed with 100% width.

Related code, data or error log (please format your code or data):
In my CSS I have :

.scroll-content {
width: 100%;
overflow: hidden;
}
#map_canvas, #pano_canvas {
display: block;
height: 100%;
width: 100%;
}

![map](https://user-images.githubusercontent.com/29124818/46425392-d710cb00-c73b-11e8-9aca-3c1662f28c23.png)

**Comment by wf9a5m75** [comment]
Duplicated https://github.com/ionic-team/ionic-native-google-maps/issues/87
