### ISSUE TITLE
How does the map markers work when creating a new map?

### ISSUE THREAD

**Issue by github-jorgem** [mapsplugin/cordova-plugin-googlemaps#2449]
**I'm submitting a ...**  (check one with "x")
- [X] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [X] **iOS**
- [X] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
```
cordova-plugin-browsersync 0.1.7 "cordova-plugin-browsersync"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.4 "cordova-plugin-googlemaps"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-plugin-x-toast 2.7.0 "Toast"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
Using cordovoa.
```

**Current behavior:**
When clicking on the map markers, they do not open.

**Expected behavior:**
When clicking on the map makers, they should open.

## My Question
When clicking on the map markers, they do not open. I suspect this is because the old map was destroyed and the map markers were created using the old map, not the new one. If this is the case, how can I update the markers to use the new map instead?

**Comment by wf9a5m75** [comment]
I can't understand what are you taking about.
One hint. Do not keep the map instance in old page if you use multiple page.

**Comment by github-jorgem** [comment]
Thank for your help. I figured it out. I was targeting the wrong marker. Closing this.
