### ISSUE TITLE
iOS installation error

### ISSUE THREAD

**Issue by ArrowsOff** [mapsplugin/cordova-plugin-googlemaps#2451]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
It's quite a long list but should really matter in this example

```
om-sarriaroman-photoviewer 1.1.18 "PhotoViewer"
cordova-clipboard 1.2.1 "Clipboard"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-admobpro 2.31.6 "AdMob Plugin Pro"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-facebook4 2.5.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-localization-strings 2.0.0 "Localization"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-sqlite-storage 2.4.0 "Cordova sqlite storage plugin"
cordova-support-google-services 1.2.1 "cordova-support-google-services"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
```

ionic info:
```
Ionic:

   ionic (Ionic CLI)  : 4.2.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 25 other plugins)

System:

   Android SDK Tools : 26.0.2 (/Users/veiligebuurt/Library/Android/sdk/)
   ios-deploy        : 1.9.2
   NodeJS            : v8.9.4 (/usr/local/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

Okay right now I'm working on updating my iOS app but ran into a problem when updating this app. I removed my platform `ionic cordova platform rm ios` and added it back again when I updated some versions. `ionic cordova platform add ios`. 

Now everytime I try to add platform or build the app I am getting this error: 
```
Discovered plugin "cordova-plugin-googlemaps" in config.xml. Adding it to the project
Installing "cordova-plugin-googlemaps" for ios
--[cordova-plugin-googlemaps]------------------------
From version 2.4.5, the cordova-plugin-googlemaps uses CocoaPod.
No longer necessary com.googlemaps.ios plugin.
Automatic uninstalling com.googlemaps.ios plugin...
-----------------------------------------------------
Failed to install 'cordova-plugin-googlemaps': undefined
Failed to restore plugin "cordova-plugin-googlemaps" from config.xml. You might need to try adding it again. Error: Version should contain only numbers and dots
```

I've checked if there were any issues with the version but everywhere I go I specified 2.4.6, which is the latest version I believe. I don't know what is going wrong and from what version this is happening but It's very consistent. Even when completely removing the plugins from node_modules and plugins folder, then redownloading it again does not change the behaviour here. 

**Expected behavior:**

Well pretty much just installing the plugin as it should. 

**Related code, data or error log (please format your code or data):**
Just a basic plugin install, nothing special
`ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID=HiddenKeyForReasons --variable API_KEY_FOR_IOS=HiddenKeyForReasons --variable LOCATION_WHEN_IN_USE_DESCRIPTION="Show your location on the map" --variable LOCATION_ALWAYS_USAGE_DESCRIPTION="Trace your location on the map" --variable PLAY_SERVICES_VERSION=11.8.0 --variable ANDROID_SUPPORT_V4_VERSION=24.1.0`

I hope you can do something with this information, I'm really not sure where this problem comes from but it only happens with the googlemaps plugin. I'm going to test further with some older versions to check from what version on it is happening.

**Comment by ArrowsOff** [comment]
I've tried that multiple times without any results. I have been check changing the versions for the last few minutes and found that version 2.4.4 does not have this issue. 

I've tried 2.4.6 over 10 times 
Tried 2.4.5 a few times but got a different installation error
Now on 2.4.4 everything is working as expected

**Comment by wf9a5m75** [comment]
I think your `cocoapod` is out-of-dated in this case.
Check here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2434

**Comment by wf9a5m75** [comment]
If you can't solve this problem by yourself, please share your project files, including `platforms` directory, onto github.

**Comment by ArrowsOff** [comment]
Another run at it here, I've updated my cocoapods and I've even checked that I could install the plugin through running `pod install` in the platforms/ios folder. That works fine, but when recreating the project it won't install it. Not sure if cocoapods is the problem right now.

looking at `'cordova-plugin-googlemaps': undefined` seems to be the issue, not being able to find a version for the plugin I suppose. 

```
--[cordova-plugin-googlemaps]------------------------
From version 2.4.5, the cordova-plugin-googlemaps uses CocoaPod.
No longer necessary com.googlemaps.ios plugin.
Automatic uninstalling com.googlemaps.ios plugin...
-----------------------------------------------------
Install start for "cordova-plugin-googlemaps" on ios.
Beginning processing of action stack for ios project...
Action stack processing complete.
Adding pods since the plugin contained <framework>(s) with type="podspec"
pods.json: The file at /someDirectory/platforms/ios/pods.json does not exist.
Creating new pods.json in platforms/ios
Wrote to pods.json.
Podfile: The file at /someDirectory/platforms/ios/Podfile does not exist.
Creating new Podfile in platforms/ios
Wrote to Podfile.
Set pods.json for `GoogleMaps`
Added pod line for `GoogleMaps`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
Failed to install 'cordova-plugin-googlemaps': undefined
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

When running pod install in the platforms/ios folder this is the result:
```
pod install
Analyzing dependencies
Downloading dependencies
Installing GoogleMaps (2.7.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```
It still doesn't work though when running the app though

But, I do feel like it has something to do with cocoapods, so I'll be checking that out right now.

**Comment by wf9a5m75** [comment]
>platforms/ios/pods.json does not exist

https://stackoverflow.com/questions/41069416/cordova-ios-plugin-install-pod-install-silently-exits

https://issues.apache.org/jira/browse/CB-12272

**Comment by wf9a5m75** [comment]
I guess your cordova version is old.

**Comment by ArrowsOff** [comment]
I've tried running this with cordova 7.1.0 and 8.1.0. I feel like that shouldn't be the issue.
I've also tried npm versions 5.4.0(with node 8.9) and 6.4.0 (node 10.11) both without success. 

Also the pods.json file does exist, it's not missing from the project structure and looks also fine to me when running the proces. Not really sure what is going on but I guess it is something in my project not liking the way cocoapods work. Very strange since my custom plugins with cocoapods work fine. (Yes I've also tried running this with my custom plugins if that would make a difference)

**Comment by wf9a5m75** [comment]
Should be like this:

```
$> find . -name "pods.json"
./platforms/ios/pods.json

$> cat platforms/ios/pods.json 
{
    "GoogleMaps": {
        "name": "GoogleMaps",
        "type": "podspec",
        "spec": "~> 2.7.0",
        "count": 1
    }
}
```

**Comment by wf9a5m75** [comment]
If you can't find it, just create an empty file.

**Comment by makers-mark** [comment]
Error: Version should contain only numbers and dots

Try removing ~ and ^'s from the json file and use explicit versions?

**Comment by wf9a5m75** [comment]
Regarding of this thread, I guess @ArrowsOff 's cocoapod version is old.
https://github.com/phonegap/phonegap-plugin-push/issues/1465

**Comment by wf9a5m75** [comment]
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/186#issuecomment-347623033
![screen shot 2018-10-04 at 2 08 15 pm](https://user-images.githubusercontent.com/167831/46503182-f6acff80-c7de-11e8-834a-15790cbc713e.png)

**Comment by ArrowsOff** [comment]
The file is present and that's indeed what I found aswell. I ran the gem install and reinstalled cocoapods and I ran the update command. unfortunately that also didn't work. 

Once I find whats actually wrong on my setup i'll post for it for people actually running into this problem aswell.

**Comment by wf9a5m75** [comment]
ping

**Comment by CoachMorta** [comment]
@ArrowsOff ' did you find any solution for this issue ??? i have the same one , i tried everything

**Comment by ArrowsOff** [comment]
@CoachMorta I basically reverted to version 2.4.4 which is working fine. 

It's likely that the problem is revolving around cocoapods but I can't seem to figure out why. If you find any other solutions, it would be very welcome.

**Comment by UlisesCeca** [comment]
If I try to install version 2.4.4 it gets stuck when installing the plugin. Why?

**Comment by kapilSoni101** [comment]
@ArrowsOff ur are using 2.4.4 version used for google maps?

**Comment by ArrowsOff** [comment]
What I did was completely removing everything of CocoaPods and then reinstall it. Quite the hassle to do but after you did this you can install the latest version correctly.

I do not have any links for this right now but the older version of cocoapods is the problem here.

**Comment by kapilSoni101** [comment]
what i do sir actually i have tried everything that is mentioned above ?
