### ISSUE TITLE
Uncaught TypeError: Cannot read property 'insertAdjacentHTML' of null at plugin Init

### ISSUE THREAD

**Issue by CoachMorta** [mapsplugin/cordova-plugin-googlemaps#2452]
Uncaught TypeError: Cannot read property 'insertAdjacentHTML' of null at plugin Init (plugins/cordova-plugin-googlemaps/www/pluginInit.js:72)

at latest version of plugin i got this error in android devices 

my ionic info 

   ionic (Ionic CLI)  : 4.1.2 (/Users/alkhateeb/.npm-packages/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, (and 14 other plugins)

System:

   Android SDK Tools : 25.2.5 (/Users/alkhateeb/Downloads/android-sdk-macosx)
   ios-deploy        : 1.9.2
   ios-sim           : 5.0.11
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.3 Build version 9E145

- i did remove platform
- remove plugin 
- reinstall platform
- reinstall plugin 

**Please tell us your new feature idea**

**Why do you need it?**

**How helps other people?**

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2445

**Comment by wf9a5m75** [comment]
ping

**Comment by PrahladNarayan** [comment]
I do get the same error after update to version 2.4.6
Uncaught TypeError: Cannot read property 'insertAdjacentHTML' of null at plugin Init

> document.body.insertAdjacentHTML('afterbegin', envTestDiv);

I had to switch back to 2.4.4 to keep the project running.

**Comment by CoachMorta** [comment]
i still have the same issue

**Comment by wf9a5m75** [comment]
If you can't solve the problem by yourself, please share your project files (including platforms directly) onto GitHub.

**Comment by cpamp** [comment]
Upgrading to 2.4.6 causes issues. I had to recreate my project from scratch to fix this error. Luckily, for ionic, recreating the project and moving the source was simple.

Also, be sure `cordova-plugin-googlemaps` is the last plugin you install after adding all of your platforms.

Good luck...

**Comment by wf9a5m75** [comment]
As I said, 

>If you can't solve the problem by yourself, please share your project files (including platforms directly) onto GitHub.

**Comment by FLATT-Dev** [comment]
Which version does not have the error ?

**Comment by wf9a5m75** [comment]
As I said,

>If you can't solve the problem by yourself, please share your project files (including platforms directly) onto GitHub.

**Comment by wf9a5m75** [comment]
ping

**Comment by FLATT-Dev** [comment]
I cannot share my project publicly
V 2.4.4  works and that will do for the moment.
I have a more pressing issure to resolve :
The map does not show at all in my app.
It uses angular js and  onsen-ui framework.
My guess is that something in the framework prevents the app background
from becoming transparent still looking into that.any ideas are appreciated.
Ps.my keys work, verified by building a hello world app   which works fine
Thanks
Andy

**Comment by wf9a5m75** [comment]
> I cannot share my project publicly

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/.github/ISSUE_TEMPLATE/private-support.md

**Comment by wf9a5m75** [comment]
Nobody contribution, no help (then will close this thread)

**Comment by wf9a5m75** [comment]
Since nobody provided enough information, I close this thread.

**Comment by spinninghamster** [comment]
Just found this on Google search (it's the only result that matches). I'm experiencing the same problem. Unfortunately I also cannot share the project files but I get the exact same error on 2.4.6:

2019-02-19 11:02:06.479 2576-2576/com.domain.app I/chromium: [INFO:CONSOLE(1224)] "deviceready has not fired after 5 seconds.", source: file:///android_asset/www/cordova.js (1224)
2019-02-19 11:02:06.479 2576-2576/com.domain.app I/chromium: [INFO:CONSOLE(1217)] "Channel not fired: onCordovaReady", source: file:///android_asset/www/cordova.js (1217)
2019-02-19 11:02:06.479 2576-2576/com.domain.app I/chromium: [INFO:CONSOLE(1217)] "Channel not fired: onCordovaInfoReady", source: file:///android_asset/www/cordova.js (1217)
2019-02-19 11:02:06.480 2576-2576/com.domain.app I/chromium: [INFO:CONSOLE(1217)] "Channel not fired: onCordovaConnectionReady", source: file:///android_asset/www/cordova.js (1217)

**Comment by wf9a5m75** [comment]
No longer support for v2.4.6.

**Comment by spinninghamster** [comment]
Sorry, I don't understand. 2.4.6 is the latest version, no?

**Comment by wf9a5m75** [comment]
![screenshot_20190220-071412](https://user-images.githubusercontent.com/167831/53101731-3307a080-34df-11e9-94c3-29b14abdf512.png)

What number do you see?

**Comment by wf9a5m75** [comment]
And don't jumping in to closed issue thread.
