### ISSUE TITLE
how can i pick location with callback long and lat 

### ISSUE THREAD

**Issue by dizzlr** [mapsplugin/cordova-plugin-googlemaps#2453]
how can i pick location with callback  long and lat ?

**Comment by wf9a5m75** [comment]
I can't understand what you are asking. Please describe more details.

**Comment by dizzlr** [comment]
okay i want to pick location from map on click on any point and this click give me call back with long and lat

**Comment by wf9a5m75** [comment]
Please read `MAP_CLICK` event.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Map/README.md#events

**Comment by dizzlr** [comment]
or you can say i want to select location from map and return location long and lat

**Comment by dizzlr** [comment]
> Please read `MAP_CLICK` event.
> https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Map/README.md#events

thanks :)

**Comment by wf9a5m75** [comment]
You are welcome. Please read documents a lot.

**Comment by dizzlr** [comment]
> You are welcome. Please read documents a lot.

ok thanks 👍
