### ISSUE TITLE
subdomains for addTileOverlay

### ISSUE THREAD

**Issue by caleb87** [mapsplugin/cordova-plugin-googlemaps#2454]
**Please tell us your new feature idea**
Would be great to implement subdomains for tile servers, such as: http://[abc].tile.openstreetmap.org/zoom/x/y.png

Where a, b, and c are tile server subdomains. 
https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames

**Why do you need it?**
To fetch 3rd party tiles faster

**How helps other people?**
Anyone using 3rd party tiles can load tiles quickly

**Comment by wf9a5m75** [comment]
Please read more documents before using this plugin.

**Comment by caleb87** [comment]
I read the TileOverlay docs, but I did not see anything that mentioned the subdomains: https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/TileOverlay/README.md


I haven't tested "http://[abc].tile.openstreetmap.org/zoom/x/y.png" yet, but it doesn't look like it would work. The return for getTile should be the complete URL which could be navigated to with a browser. 

Your example: 
"http://[abc].tile.openstreetmap.org/zoom/x/y.png", which you must have shorthanded for:
"http://[abc].tile.openstreetmap.org/" + zoom + "/" + x + "/" + y + ".png";

But the [abc] is still just a string, and it will likely throw a 404. I was going to test it before responding, but I got sidetracked with other stuff.

I could put a, b, or c in the URL at random, but it would be preferable to evenly distribute them based on the number of tiles being fetched.

**Comment by wf9a5m75** [comment]
I believe the most JS developer understand the below example is enough.

```
  getTile: function(x, y, zoom) {
    return "http://tile.openstreetmap.org/" + zoom + "/" + x + "/" + y + ".png"; // sting
  }
```

**Comment by caleb87** [comment]
I do understand that.

But how does one get:
return "http://tileA.openstreetmap.org/" + zoom + "/" + x + "/" + y + ".png";
return "http://tileB.openstreetmap.org/" + zoom + "/" + x + "/" + y + ".png";
return "http://tileC.openstreetmap.org/" + zoom + "/" + x + "/" + y + ".png";

And evenly distribute the subdomains based on tile fetch count.


I could program it based on screen info and pan amount, but since subdomains are a fundamental to loading raster maps, it makes sense to have it built in. 

For sake of time, I'm just going to use a random subdomain for each request. It works, but it could be more efficient.
