### ISSUE TITLE
CordovaGoogleMaps :: getMap ::exception=TypeError: Cannot read property 'onThrottled' of undefined

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#2455]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-browsersync 0.1.7 "cordova-plugin-browsersync"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.5.0-beta-20181003-1630 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^5.0.0-beta.21",
"@ionic-native/google-maps": "^5.0.0-beta.21",
```

**Current behavior:**
Console error:
Exception calling native with command :: CordovaGoogleMaps :: getMap ::exception=TypeError: Cannot read property 'onThrottled' of undefined

This error is since mapsplugin/cordova-plugin-googlemaps@964a9d3, previous commit works well.

If you need github repository, you can use the same freebikev2 as used for https://github.com/ionic-team/ionic-native-google-maps/issues/85

**Comment by wf9a5m75** [comment]
Please report including error log screenshot.

**Comment by vosecek** [comment]
<img width="865" alt="screenshot 2018-10-09 18 47 52" src="https://user-images.githubusercontent.com/13045589/46684690-e12b4180-cbf3-11e8-8c62-5cf7bd15bbe5.png">

**Comment by wf9a5m75** [comment]
Please share your project files.

**Comment by homeportcz** [comment]
You have been invited a few minutes ago.

**Comment by wf9a5m75** [comment]
```
$> freebikev2 masashi$ npm i
npm ERR! code E404
npm ERR! 404 Not Found: ansi-styles@2.2.0
```

**Comment by wf9a5m75** [comment]
Ok, I found the problem point. It seems I mixed another project code into the file. Please try again.

**Comment by homeportcz** [comment]
Great. It is working now. Thanks.
