### ISSUE TITLE
Allow installation without API keys

### ISSUE THREAD

**Issue by cpamp** [mapsplugin/cordova-plugin-googlemaps#2457]
**Please tell us your new feature idea**
Allow plugin installation without API keys, currently if no API is provided the installation fails with an error.

**Why do you need it?**
Not all installation is manual. For example, when adding cordova platform this plugin fails to install and prevents all other plugins in the project from installing as well.

**How helps other people?**
Allows plugin installation to be automated by cordova and prevents hard to track errors when automated installation fails.

**Comment by wf9a5m75** [comment]
nop.

**Comment by cpamp** [comment]
Why? The current behavior is poor and does not work with cordova.

**Comment by wf9a5m75** [comment]
Cordova provides only one way to define a node in `AndroidManifest.xml` is to define `plugin.xml`.
There is no other solution.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v2.4.6/plugin.xml#L236-L240

If you find alternative way (but not using `cordova hook script`, because cloud builds do not support it), please send a pull request.

**Comment by cpamp** [comment]
It is possible. The same `edit-config` and `config-file` nodes available in `plugin.xml` also work in `config.xml`

**Comment by cpamp** [comment]
👍
