### ISSUE TITLE
Set visible to false when adding kml Overlay

### ISSUE THREAD

**Issue by livedota** [mapsplugin/cordova-plugin-googlemaps#2458]
**Please tell us your new feature idea**
Set visible to false when add kml  
**Why do you need it?**
Because after i have added kml i have to set visible to false programmatically and that cause an ugly show/hide effect.

Thank for plugin and thanks for response.

**Comment by wf9a5m75** [comment]
```
kmlOverlay.setVisible(false);
```

**Comment by livedota** [comment]
As i have already explain if i do this Just After add It Will cause an ugly effect, i would like set it in options

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/KmlOverlay.js#L278

**Comment by livedota** [comment]
Maybe i am explaining bad, i would like do
` map.addKmlOverlay({
        'url': "mykml.kml",
        "visible": false,
      }`
instead of 
` map.addKmlOverlay({
        'url': "mykml.kml"
      }, function (kmlOverlay) {
       //add kmlOverlay.setVisible(false);`
Beucause in 2 case the overlay first appear and then disappear

**Comment by wf9a5m75** [comment]
I don't think that option is it is helpful for other people.

**Comment by wf9a5m75** [comment]
Adding a kml layer, it is that actually adding multiple overlays on the map.

```
map.addKmlOverlay({ 'url': "mykml.kml", "visible": false, }
```

Adding invisible overlays a lot spends lots of memory ( = spends lots of battery usage ).

Thus, you should not add kml overlay if you don't want to show it.

**Comment by wf9a5m75** [comment]
In order to hide overlays temporally, I created "kmlOverlay.setVisible(false)".

There is a description about the  accept tags.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/KmlOverlay/README.md#overview

**Comment by livedota** [comment]
You are just quoting the doc without giving real explanation but it's your plugin so you decode how should be, if you just can give me a hint i would make the function myself

**Comment by wf9a5m75** [comment]
Well, it seems I implemented `<visibility>` tag parser.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v2.4.6/www/KmlLoader.js#L860-L862

If it does not work as you expected, please send a pull request.

**Comment by livedota** [comment]
I have put a breakpoint at https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v2.4.6/www/KmlLoader.js#L858 and and never reach this point, as result of puttin the `<visibility>` tag inside kml file i get a object like this 
`{
	"value":0,
	"tagName":"visibility",
	"styleIDs":["#mystyle"],
	"id":"myid",
	"xmlns":"http://www.opengis.net/kml/2.2",
	"xmlns:gx":"http://www.google.com/kml/ext/2.2",
	"xmlns:xsi":"http://www.w3.org/2001/XMLSchema-instance",
	"xsi:schemaLocation":"http://www.opengis.net/kml/2.2 http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd http://www.google.com/kml/ext/2.2 http://code.google.com/apis/kml/schema/kml22gx.xsd"
}`
and if have understand correctly the parser it's called under ` <NetworkLink>` tag
