### ISSUE TITLE
iOS 11.1 has white bar after map plugin upgrade to 2.4.6

### ISSUE THREAD

**Issue by spacesuitdiver** [mapsplugin/cordova-plugin-googlemaps#2459]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

Before (2.4.0):
```
branch-cordova-sdk 3.0.0 "branch-cordova-sdk"
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
com.mbppower.camerapreview 0.0.8 "cordova-plugin-camera-preview"
com.phonegap.plugins.facebookconnect 1.7.1.3 "Facebook"
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-ios-plugin-no-export-compliance 0.0.5 "iOS No Export Compliance"
cordova-launch-review 3.1.0 "Launch Review"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-appavailability 0.4.1 "AppAvailability"
cordova-plugin-backbutton 0.3.0 "Backbutton"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-cszbar 1.3.2 "ZBar barcode scanner"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-disable-bitcode 1.3.2 "DisableBitcode"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.3.11-beta-20180806-1918 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-intercom 4.1.2 "Intercom"
cordova-plugin-localization-strings 1.1.1 "Localization"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-okhttp 2.0.0 "OkHttp"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3-dev "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.0.12 "SocialSharing"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.3 "PushPlugin"
```

After (2.4.6):
```
branch-cordova-sdk 3.0.0 "branch-cordova-sdk"
com.mbppower.camerapreview 0.0.8 "cordova-plugin-camera-preview"
com.phonegap.plugins.facebookconnect 1.7.1.3 "Facebook"
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-ios-plugin-no-export-compliance 0.0.5 "iOS No Export Compliance"
cordova-launch-review 3.1.0 "Launch Review"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-appavailability 0.4.1 "AppAvailability"
cordova-plugin-backbutton 0.3.0 "Backbutton"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-cszbar 1.3.2 "ZBar barcode scanner"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-disable-bitcode 1.3.2 "DisableBitcode"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-intercom 4.1.2 "Intercom"
cordova-plugin-localization-strings 1.1.1 "Localization"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-okhttp 2.0.0 "OkHttp"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3-dev "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.0.12 "SocialSharing"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.3 "PushPlugin"
```

**Current behavior:**
It seems the Webview and any other native plugin is shifted up on iOS 11.1.

**Expected behavior:**
Webview should span the proper device height.

**Screen capture or video record:**
Before (2.4.0):
<img width="384" alt="screen shot 2018-10-10 at 11 39 22 am" src="https://user-images.githubusercontent.com/2807897/46752169-24cc8c80-cc82-11e8-8dea-500da5ef3bfb.png">

After (2.4.6):
<img width="384" alt="screen shot 2018-10-10 at 11 39 22 am" src="https://user-images.githubusercontent.com/2807897/46751965-a839ae00-cc81-11e8-9e8f-b8333e1bf4e7.png">

**Comment by wf9a5m75** [comment]
Please share the reproduce project files on github.

**Comment by spacesuitdiver** [comment]
@wf9a5m75 it doesn't happen on 2.4.4 plugin version so using that for now. I have no shareable source code pieced together. I'm assuming it's related to your viewport cover detection. Let me know what you think.

This is what's in our `index.html`.
```
    <meta charset="utf-8">
    <meta http-equiv="Content-Security-Policy" content="
        default-src * 'self' gap://ready cdvfile://* data: filesystem: blob:;
        style-src 'unsafe-inline' 'self' cdvfile://* filesystem: blob:;
        script-src 'self' 'unsafe-inline' 'unsafe-eval' cdvfile://* filesystem: https://fast.wistia.com https://src.litix.io"
    >
    <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
```

**Comment by wf9a5m75** [comment]
@chadevans ping

**Comment by wf9a5m75** [comment]
Please create a simple project that reproduce your issue 100%, then share it on github.

**Comment by chadevans** [comment]
Happy to help if there is a sample project.

**Comment by chadevans** [comment]
If not that, at least the css and a screenshot of the DOM viewport meta tag.

**Comment by wf9a5m75** [comment]
@chadevans thanks for jumping on.

**Comment by spacesuitdiver** [comment]
@chadevans above is the meta tag for the project. I'll see about bootstrapping a new project, I haven't in so long though.

**Comment by chadevans** [comment]
Meta tags in chrome devtools DOM, this plugin modifies the viewport meta tag.

**Comment by chadevans** [comment]
Nevermind you are talking iOS.. try Safari Inspector.

**Comment by spacesuitdiver** [comment]
@chadevans okay.

> Please share the reproduce project files on github.

We're also working on sandboxing a version for additional help because we have been trying to release our app with v2 maps coming from v1 and about 10% of the time the map just renders white with no error and map ready fired just fine.

**Comment by chadevans** [comment]
@spacesuitdiver 

Thanks for the update - I've tested an app using the latest cordova-plugin-googlemaps 2.4.6.

I'm getting `viewport-fit=cover` in my DOM and no issues with map. This is on iPhone 8+ w/ iOS 12, I'm downloading 11.1 and iPhone SE to more closely match your testing.

I'm using an Ionic app so there may be some differences there in how the DOM is loaded.. look forward to being able to test on your Cordova sandbox.

**Comment by spacesuitdiver** [comment]
@chadevans this issue is for certain not an issue on 12 only < 11.2.

**Comment by wf9a5m75** [comment]
@spacesuitdiver We are still waiting the project that is reproduce your issue.

**Comment by chadevans** [comment]
@spacesuitdiver ah, this piece of info helps me understand. iOS 11.1 or less.

Now I remember, 11.0 and 11.1 called what is now `env()`, it was called `constant()`. Working to reproduce issue on 11.1 and should be able to fix.

**Comment by spacesuitdiver** [comment]
> @spacesuitdiver We are still waiting the project that is reproduce your issue.

Me too ;)

**Comment by chadevans** [comment]
@spacesuitdiver try changing line 69 in pluginInit.js to this:

`var envTestDiv = '<div id="envTest" style="margin-top:-99px;margin-top:constant(safe-area-inset-top);margin-top:env(safe-area-inset-top);position:absolute;z-index:-1;"></div>';`

(run a console log or alert to make sure your change isn't overwritten on build)

**Comment by wf9a5m75** [comment]
@spacesuitdiver ping

**Comment by wf9a5m75** [comment]
@spacesuitdiver ping

**Comment by spacesuitdiver** [comment]
> @spacesuitdiver try changing line 69 in pluginInit.js to this:
> 
> `var envTestDiv = '<div id="envTest" style="margin-top:-99px;margin-top:constant(safe-area-inset-top);margin-top:env(safe-area-inset-top);position:absolute;z-index:-1;"></div>';`
> 
> (run a console log or alert to make sure your change isn't overwritten on build)

This change didn't seem to help. `viewport-fit=cover` is not applied to 11.1 devices.

**Comment by chadevans** [comment]
> try changing line 69 in pluginInit.js to this:
> 
> `var envTestDiv = '<div id="envTest" style="margin-top:-99px;margin-top:constant(safe-area-inset-top);margin-top:env(safe-area-inset-top);position:absolute;z-index:-1;"></div>';`

@wf9a5m75 tested and confirmed this works. In iOS 11.1, returns `0px` instead of `-99px` with the addition of `margin-top:constant(safe-area-inset-top);` to the test, which is what we want. As a reminder, any value other than `-99px` in this test will add `viewport-fit=cover` to the `viewport` meta tag.

With this fix, iOS 11 early versions work.

**Comment by wf9a5m75** [comment]
@chadevans Thank you for your work.
@spacesuitdiver Please make sure @chadevans 's advise works for you

**Comment by spacesuitdiver** [comment]
@chadevans @wf9a5m75  testing this again right now in my actual project, I tried testing it yesterday but wasn't sure if it was working because the default cordova project doesn't actually go the edges of the screen.

**Comment by wf9a5m75** [comment]
@spacesuitdiver You should share the project files on github if you ask to do something, at least reproducible project.

**Comment by spacesuitdiver** [comment]
@wf9a5m75 yep.

**Comment by spacesuitdiver** [comment]
@chadevans fix seems good over here, thanks!

**Comment by wf9a5m75** [comment]
@spacesuitdiver Thank you for working a lot.

**Comment by chadevans** [comment]
My pleasure, thank you for the excellent plugin.

**Comment by bb128b** [comment]
Hi all, this is actually happening across the board on iOS 12 too... I found this issue from the Ionic repo if anybody is having an issue of no clickable back buttons in the top area of the device. I believe the status bar is covering the header buttons in an Ionic app... https://github.com/ionic-team/ionic/issues/15960

Attached is a poorly drawn picture of mine when I was explaining it to a colleague.

![img_20181023_164800](https://user-images.githubusercontent.com/2276905/47373407-af31d900-d6e3-11e8-8707-32ddb58e717d.jpg)

**Comment by chadevans** [comment]
@bb28b

Please try to reproduce using the multiple_maps branch.
