### ISSUE TITLE
IOS: message pops up everytime app starts

### ISSUE THREAD

**Issue by JonathanKanContracting** [mapsplugin/cordova-plugin-googlemaps#2462]
Although the plugin works for ios, everytime the app starts, a dialog box pops up saying:

Google Maps SDK for iOS crashes if CFBundleExecutable contains non-English characters. More details, Check put the comment in the CordovaGoogleMaps.m file.

How do i get rid of this prompt? My app is in english.

Any help much appreciated.

Thanks

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2017#issuecomment-379001012

**Comment by JonathanKanContracting** [comment]
Checking the file in this project i see that the message is from the string APP_NAME_ERROR_MESSAGE

and theres a regex compare against the cfbundleexecutable.
 NSRegularExpression *regex = [NSRegularExpression regularExpressionWithPattern:@"^[a-zA-Z0-9$@$!%*?&#^\\-_.\\s+]+$" options:NSRegularExpressionCaseInsensitive error:nil];

        if ([regex numberOfMatchesInString:CFBundleExecutable options:0 range:NSMakeRange(0, CFBundleExecutable.length)] == 0) {

          errorMsg = [PluginUtil PGM_LOCALIZATION:@"APP_NAME_ERROR_MESSAGE"];

        }

Im guessing with phonegap build, the cfbundleexecutable name is the app's name and looking at the regex it doesnt account for the square brackets as being "english allowed". My app name has [ and ] in it to denote the environment, i.e. [DEV] or [QA]. I'll remove these and try again...

**Comment by wf9a5m75** [comment]
ping

**Comment by JonathanKanContracting** [comment]
Anyways, i have removed the [ ] and ( ) in the name of the app and now it is working. issue can be closed. the name of the app can only contain characters that are specified within the regex string: a-zA-Z0-9$@$!%*?&#^\\-_.\\s+
