### ISSUE TITLE
Proguard - Reverse Geocoder is not working

### ISSUE THREAD

**Issue by pallikondan** [mapsplugin/cordova-plugin-googlemaps#2463]
**I'm submitting a ...**  (check one with "x")
- [ x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

cordova-plugin-googlemaps 1.3.9 "phonegap-googlemaps-plugin"
phonegap-plugin-barcodescanner 5.0.0 "BarcodeScanner"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-file 4.2.0 "File"

**Current behavior:**
After I'm enabled the proguard in my project,  I'm Getting Lattitude Longitude only instead of getting Address when i try to reverse geocode the lat, lng  

**Expected behavior:**
I want proguard rules for this plugin and also need reverse geocoder to work after enable the proguard

**Comment by wf9a5m75** [comment]
cordova-plugin-googlemaps 1.3.9 "phonegap-googlemaps-plugin"


Too much older
