### ISSUE TITLE
Back button causing app to close 

### ISSUE THREAD

**Issue by leftdead7** [mapsplugin/cordova-plugin-googlemaps#2464]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
Cordova version : 8.1.2
cordova android version : 8.1.2
```
com-moduscreate-plugins-echo 0.0.1 "ModusEcho"
cordova-plugin-android-permissions 0.11.0 "Permissions"
cordova-plugin-appinfo 2.1.2 "AppInfo Plugin"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-contacts 2.3.1 "Contacts"
cordova-plugin-crypt-file 1.3.2 "CordovaCrypt"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-proguard 1.0.0 "Cordova plugin ProGuard"
cordova-plugin-qrscanner 2.5.0 "QRScanner"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-sms-receiver 0.1.6 "Cordova SMS Receiver Plugin"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

I have registered a handler for the back button. As long as the plugin is not installed, it's working as intended. After adding the plugin, on click of back its performing the action I have registered for, at the same time it's exiting the app.
**Expected behavior:**

The app should not exit
**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by vosecek** [comment]
Share your project to github. First rule for this plugin :)

**Comment by wf9a5m75** [comment]
Too less information. Please share your project files on GitHub in order to reproduce your issue.

**Comment by leftdead7** [comment]
I cannot share my actual project on github

However, will create a sample version where the error can be replicated

**Comment by wf9a5m75** [comment]
ping

**Comment by leftdead7** [comment]
Was not able to reproduce the issue in a new project.  Also, the issue is fixed in my project. So closing the issue here
