### ISSUE TITLE
MarkerClustering support for `set` method and other references

### ISSUE THREAD

**Issue by sean-hill** [mapsplugin/cordova-plugin-googlemaps#2465]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.2.3 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.5 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : ^3.12.1
@ionic-native/google-maps : ^4.5.3
```

**Current behavior:**
I'm building an app with a similar idea to AirBnB, using only markers like this:

```js
const marker = await this.map.addMarker({
  icon: this.getIcon(this.markerIcons.listing, 34),
  position: geo,
  listing: listing._id,
  disableAutoPan: true
})

marker.set(listing, listing._id)

const click = marker
  .on(GoogleMapsEvent.MARKER_CLICK)
  .subscribe(() => {
    if (!marker) return
    marker.setIcon(this.getIcon(this.markerIcons.listingActive, 44))
    this.showListing(listing)
  })

marker.set('click', click)
```

I would like to start clustering my markers using the `MarkerCluster` class. I'm unsure how to keep my marker `set` functions and clicks, when using the `MarkerCluster` class since `cluster.addMarker` returns `void` and not a reference to a `marker`.

Thanks.

**Comment by wf9a5m75** [comment]
```

var markerCluster = map.addMarkerCluster({
  markers: dummyData(),
  icons: [
      ...
  ]
});

markerCluster.on(plugin.google.maps.event.MARKER_CLICK, function(latLng, marker) {
  // marker clicked
});
```

By the way, `cordova-plugin-googlemaps 2.2.3 "cordova-plugin-googlemaps"` and `@ionic-native/google-maps : ^4.5.3` are too much old. I only support the latest versions.

**Comment by sean-hill** [comment]
@wf9a5m75 thank you! Yeah, I'm in the process of updating my depedencies. 

So with the `MarkerCluster`, we don't use the `map.addMarker` functionality anymore, we could simply do this?

```js
const marker = new plugin.google.maps.Marker({
  icon: listingIcon,
  position: geo
})

marker.set('data', { example: 'data' })

this.clusterer.addMarker(marker)
```

**Comment by sean-hill** [comment]
Nevermind, it does not appear I can do `new plugin.google.maps.Marker`

**Comment by wf9a5m75** [comment]
For ionic usage:

https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.gefe7d3b89a139c8_119

**Comment by sean-hill** [comment]
Yeah I've removed that `ionic-native` dependency and I'm using this plugin directly. Is it possible to create a marker without adding it to the map, so that I could set some preliminary meta data, and then add it to my `MarkerCluster`?

**Comment by sean-hill** [comment]
I only see:

![image](https://user-images.githubusercontent.com/1205866/46965581-173b4c00-d060-11e8-843e-1b43e8bc537f.png)

As a way to retrieve a marker reference.

**Comment by sean-hill** [comment]
My use case is when a marker is clicked, I change the icon so that it becomes the "active" and focused one. When the user swipes and moves the map, I'd like the switch that "active" marker back to an "inactive" state. I used to be doing this by keeping track of marker references inside of an object and calling the `setIcon` method to switch it back to an "inactive" state.

However with the `MarkerCluster`, I don't see how to get access to those marker references.

**Comment by wf9a5m75** [comment]
`MarkerCluster` does not provide any marker reference, because the actual marker is added/removed automatically.

The `MarkerCluster` purpose is to reduce the number of markers on the map.
Creating a marker spends some memory. 100,000 markers, for example, spends tons of memory, then your app crashes, especially native running (Android, iOS).
That's why the markers outside of screen are removed.

If you want to keep marker instance, you should not use marker cluster, or you need to create it by yourself.

--------------

If you want to do switching `Active/inactive` marker, I do like this:

```
// plugin v2.4.6 style
var markerSet = [
  {
    position: {lat: xxx, lng: xxx},
    myId: "marker1"
  },
  {
    position: {lat: xxx, lng: xxx},
    myId: "marker2"
  },
  {
    position: {lat: xxx, lng: xxx},
    myId: "marker3"
  }
];

var markers = markerSet.map(function(markerOpts) {
  var marker = map.addMarker(markerOpts);
  map.on('activeId_changed', onActiveChanged.bind(marker);
  return marker;
});

map.set('activeId', 'marker1');


function onActiveChanged(prevValue, newValue) {
  var icon = newValue === this.get('myId') ? "imgs/active.png" : "imgs/inactive.png";
  this.setIcon(icon);
}
```
