### ISSUE TITLE
Bounds issues with marker cluster

### ISSUE THREAD

**Issue by sean-hill** [mapsplugin/cordova-plugin-googlemaps#2467]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.5 "Launch Navigator"
```

**Current behavior:**
When I click a marker cluster, the bounds it's zooming into places the markers on the very edge of the screen. Also, sometimes when I click a cluster, it doesn't actually zoom in.

**Expected behavior:**
For there to be some padding around the edges so it's easier to click one of the markers.

**Screen capture or video record:**
https://www.icloud.com/iclouddrive/0s0NpTqTT4BIHEsHnmVG-6-Fg#map
https://www.icloud.com/iclouddrive/0sgNvVEHM0WphUOlvo9Rf4ezg#map2

**Comment by wf9a5m75** [comment]
There is no option available.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v2.4.6/www/MarkerCluster.js#L194
