### ISSUE TITLE
Marker Cluster: updating individual markers

### ISSUE THREAD

**Issue by thoessl** [mapsplugin/cordova-plugin-googlemaps#2470]
**Please tell us your new feature idea**

It should be possible to update the marker properties - especially the icon - of markers after adding them to the cluster. The previous icon should be replaced with the new one if the marker is visible at the current zoom level. If it's clustered at the moment, then obviously nothing changes immediately, only when zooming in far enough.
Also, it would be good to be able to delete a marker afterwards again.
Both could be done either by using a reference to the marker, or an ID.

**Why do you need it?**

I want to cluster places whose state changes over the time, with the state being indicated by icons. Currently, I see no way to do that with the MarkerClustering.
Also, I want to have the marker have an active and an inactive state. Currently, I only see a way to change the icon in answer to an click event. However I would want this state to be activated programmatically (optionally combined with zooming in to the place of that marker to it's visible on an individual basis).

**How helps other people?**

It would help other people having the same requirement. Maybe the intention of #2465 goes into the same direction as well.

I formulate this feature in full awareness of the donation policy :-)

**Comment by wf9a5m75** [comment]
```js
var positionList = [
  {
     position: {lat: ..., lng: ...},
     icon: { ... }
  },
  {
     position: {lat: ..., lng: ...},
     icon: { ... }
  },
  {
     position: {lat: ..., lng: ...},
     icon: { ... }
  }
]

var markerCluster = map.addMarkerCluster({
  markers: positionList,
  icons: [ ... ]
});

button.addEventListener('click', function() {

  positionList[0].icon = { ... }; // set new icon. This affects when marker is added next time.

});
```

**Comment by CatoTH** [comment]
Thanks a lot for your reply. I didn't think about that, indeed. However, it's still not possible to update the icon of a marker that's currently visible?

**Comment by thoessl** [comment]
Just a small update: i kind of managed to get the behavior I expect, by adding a `updateIcon`-method that sets the icon-property and, if the marker is visible, forces a `redrawClusters`-call, that then also updates icons. My (rather rough) take on this would be at https://github.com/CatoTH/cordova-plugin-googlemaps, with implementations for browsers and android for now.
I'm not sure if this is in any way interesting for the main project; if so, I could at least try to get this to a state where it's suitable for a pull request. If this is too specific for my use case, it's fine to just close this issue.

Thanks a lot for your help!
