### ISSUE TITLE
Layer detection doesn't seem to work with nested absolutely positioned elements

### ISSUE THREAD

**Issue by spacesuitdiver** [mapsplugin/cordova-plugin-googlemaps#2472]
After about 2.3.0 the layer detection seems off for absolutely positioned items.

**Sample Project:**
https://github.com/spacesuitdiver/cordova-googlemaps-sandbox

**Code in question:**

```html
            <div style="height: 40px; position: relative; z-index: 10; background-color: red; width: 100%;">
                <div style="position: absolute; bottom: 0; right: 0; height: 100px; width: 100px; background-color: white; top: 40px; border: 1px solid blue; z-index: 1">
                    <div>Ye</div>
                    <div>Yo</div>
                    <div>Yo</div>
                    <div>Yo</div>
                </div>
            </div>
```

**I'm submitting a ...**  (check one with "x")
- [x] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

![2018-10-16 13-35-47 2018-10-16 13_38_12](https://user-images.githubusercontent.com/2807897/47039134-cc493380-d148-11e8-90a8-d1bbce8dfe30.gif)

**Comment by spacesuitdiver** [comment]
I'd added some more test cases in the sandbox. One thing I am finding is that the positioning in the markup seems to matter, positioning the item below the map canvas seems to help.

**Comment by wf9a5m75** [comment]
If you change to this, it works.

```

            <div style="height: 40px; position: absolute; background-color: red; width: 100%;z-index:0">
                <div style="position: absolute; top: 40px; right: 0; height: 100px; width: 100px; background-color: white;border: 1px solid blue;">
                    BROKE - Menu with nav bar on top of map markup (relative)
                </div>
            </div>
```

**Comment by spacesuitdiver** [comment]
@wf9a5m75  Ah you found the root cause, setting `z-index: 0` in this scenario works on Android but not iOS.

**Comment by wf9a5m75** [comment]
How about changing `z-index: 2` for the element, and set `z-index:1` for map div?

**Comment by spacesuitdiver** [comment]
Sorry I reported back incorrectly, I am not experiencing the same thing when settings `z-index: 0` on either platform now.

**Comment by wf9a5m75** [comment]
Don't forget to change to `position: absolute` from `position: relative`.

**Comment by spacesuitdiver** [comment]
Ah yes, that kind of defeats the purpose though.

**Comment by wf9a5m75** [comment]
Or change to like this:

```

            <div id="map" style="width: 100%; height: calc(100vh - 80px);">
              <div style="height: 40px; position: relative; background-color: red; width: 100%;">
                  <div style="position: absolute; top: 40px; right: 0; height: 100px; width: 100px; background-color: white;border: 1px solid blue;">
                      BROKE - Menu with nav bar on top of map markup (relative)
                  </div>
              </div>
            </div>
```

**Comment by spacesuitdiver** [comment]
Let me try nesting it, any reason why the relative positioned solution doesn't work?

**Comment by spacesuitdiver** [comment]
Ah I can't nest it in my project I realize because the map is in a scrollview and the nav (red/blue bar) isn't.

**Comment by spacesuitdiver** [comment]
@wf9a5m75 I think it's important to know when the plugin decides to skip elements in it's hit detection if we are going to make make the hit detection work differently than what is normally expected with standard HTML/CSS rules. This ticket can sort of serve as that I suppose.

**Comment by spacesuitdiver** [comment]
@wf9a5m75 can you show me where in the so

**Comment by wf9a5m75** [comment]
If you want to fix the problem, read & understand this code, then send a PR please.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v2.4.6/src/android/plugin/google/maps/MyPluginLayout.java#L414-L599

**Comment by spacesuitdiver** [comment]
> If you want to fix the problem, read & understand this code, then send a PR please.
> https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v2.4.6/src/android/plugin/google/maps/MyPluginLayout.java#L414-L599

Thanks!

**Comment by cpamp** [comment]
I have used `position: absolute` and `position: fixed` successfully over the map, with scrollviews.

I think your strategy for positioning the top right box is not typical. Your absolutely positioned div renders outside of the relatively positioned parent.

**Comment by alexbonhomme** [comment]
@spacesuitdiver did you find a solution ? I'm in the same situation, update from 2.3 to 2.4 brokes the touch detection on Android 6 (seems to work on Android 8)
