### ISSUE TITLE
Continuous execution using getMyLocation without stopping

### ISSUE THREAD

**Issue by ichenghau** [mapsplugin/cordova-plugin-googlemaps#2474]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-flashlight 3.2.0 "Flashlight"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.2.3 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.1 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

In places where the indoor signal is not good, use GoogleMap.getMyLocation({enableHighAccuracy:true}), wait for and no error and no response. After that, as long as the method of calling getMyLocation is called, the positioning cannot be successfully obtained, and the APP needs to be restarted to be successfully obtained.

**Expected behavior:**

I expect that if the timeout shows an exception for a while, and the positioning is still successful after the second execution.

**Comment by wf9a5m75** [comment]
Please find another plugin for the purpose.

**Comment by ichenghau** [comment]
Is there any other plugin recommended?

**Comment by wf9a5m75** [comment]
I have no idea.

This plugin's `getMyLocation()` implementation is just a regular code of Android programming, it's not suite for indoor positioning.

**Comment by ichenghau** [comment]
The previous version 2.3.8 will not have this problem. I feel that the gps connection seems to be occupied. I have been waiting, can you make corrections, thank you

**Comment by ichenghau** [comment]
In addition, this problem will not occur as long as the high-definition WIFI is turned off.

**Comment by wf9a5m75** [comment]
As I said, 

> Please find another plugin for the purpose.
