### ISSUE TITLE
(Android) Using setOptions() prompts for user location.

### ISSUE THREAD

**Issue by spacesuitdiver** [mapsplugin/cordova-plugin-googlemaps#2475]
After initializing the map, if we supply any controls object `setOptions({ controls: { compass: false } })` on the JavaScript side it evaluates key items `myLocation` and `myLocationButton` to `true` even though they are `false` (or undefined really) as we are simply checking for their existence using `.has()` and on the .js side we seem to always set them.

These lines:
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/Map.js#L266
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/Map.js#L267

Cause this to always evaluate true:
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/PluginMap.java#L1376

**Comment by wf9a5m75** [comment]
Could you provide test code?

**Comment by spacesuitdiver** [comment]
You can try it simply with calling `setOptions({ controls: { compass: false } })` after initializing a map.

**Comment by wf9a5m75** [comment]
Ok, I remember that. Actually I intended to include `myLocation` and `myLocationButton` always for another issue (I can't remember which issue case).

But I understand your point. Stay tune.

**Comment by spacesuitdiver** [comment]
This is still an issue with getMap() as well, something initializes myLocation as false.
![image](https://user-images.githubusercontent.com/2807897/47818334-dc0a6f80-dd25-11e8-937d-1264c5efe225.png)

**Comment by wf9a5m75** [comment]
`mylocation: false, myLocationButton: false`.

https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/ec67cdc8b403ae8bdcbe6b54ccc57f760d51a5ad#diff-0aa8d1843181c94cf122e0f77be3c2f5R1820

**Comment by spacesuitdiver** [comment]
But that shouldn't be passed as args to Java, still trying to step through this and find out where this is happening ATM.

**Comment by wf9a5m75** [comment]
Passing `myLocation` and `myLocationButton` are intended as I explained.

**Comment by spacesuitdiver** [comment]
Explained? You are checking for the existence of a key instead of a false value so this is still broke.

**Comment by wf9a5m75** [comment]
If you don't satisfy this plugin, you don't need to use this plugin mandatory, or folk the repository then modify the code as you like.

**Comment by spacesuitdiver** [comment]
I don't understand what you are hinting at. If I pass options `{ controls: { myLocation: false, myLocationButton: false } }` what's the purpose of it checking location services?

**Comment by spacesuitdiver** [comment]
That being said I'm not even doing that... simply `getMap()` prompts for location services.
