### ISSUE TITLE
Disable iOS SDK - use JS SDK instead

### ISSUE THREAD

**Issue by riyuk** [mapsplugin/cordova-plugin-googlemaps#2476]
**I'm submitting a ...**  (check one with "x")
- [X] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.2 "cordova-plugin-googlemaps"
cordova-plugin-googleplaces 0.0.5 "Google Places"
cordova-plugin-qrscanner 2.6.0 "QRScanner"
cordova-plugin-taptic-engine 2.1.0 "Taptic Engine"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
Is there a way to set the Maps Framework fixed to Google Maps JavaScript API - even on iOS?
Since we currently have everything done with your framework it would be nice to just enable JS Framework instead of the Native one.

The Reason:
The Lag/Delay is not acceptable.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Map/README.md#positioning-is-delay-a-little

We need to find a way/ rework the layout which disables scrolling on iOS.
Until then it would be nice to simply tell the Framework it should use the JS SKD.

**Related code, data or error log (please format your code or data):**

We've tried to "trick" the Framework by simply adding the env
```
plugin.google.maps.environment.setEnv({
    'API_KEY_FOR_BROWSER_RELEASE': 'xyz',
    'API_KEY_FOR_BROWSER_DEBUG': 'xyz'
});
```

But it seems to load the ios sdk anyway.

**Comment by wf9a5m75** [comment]
Please use Google Maps JavaScript v3 directly instead of using this plugin.
