### ISSUE TITLE
Error Installing Plugin invalid variable format: app

### ISSUE THREAD

**Issue by MichaelSamteladze** [mapsplugin/cordova-plugin-googlemaps#2479]
I'm trying to install this plugin and I receive this error: 

Installing plugin 'https://github.com/mapsplugin/cordova-plugin-googlemaps'
Error: invalid variable format: app

Visual Studio 2017
Cordova V7.1.0

Any ideas?

![error](https://user-images.githubusercontent.com/1502280/47417180-7ac42880-d788-11e8-9058-b5afb6734617.jpg)

**Comment by wf9a5m75** [comment]
I have no idea. I've never used cordova with Visual Studio. Please ask at StackOverflow.
Sorry about that.

**Comment by wf9a5m75** [comment]
ping
