### ISSUE TITLE
Cordova google maps tracker

### ISSUE THREAD

**Issue by you-coin** [mapsplugin/cordova-plugin-googlemaps#2480]
Hello,
Can we use this plugin to track position  and drow route from a point A to point B?

Thanks

**Comment by wf9a5m75** [comment]
This plugin doesn't provide direction feature at this time.

**Comment by you-coin** [comment]
And real live tracker ?

**Comment by wf9a5m75** [comment]
No plan to implement the feature at this time.

**Comment by you-coin** [comment]
thanks
