### ISSUE TITLE
Ground Overlay not overlapping the satellite view

### ISSUE THREAD

**Issue by pawangjain** [mapsplugin/cordova-plugin-googlemaps#2482]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.2.2 "Whitelist"
```

**Current behavior:**
The Ground Overlay DOESNOT exactly overlap the satellite view.

**Expected behavior:**
When accurate bounds are specified, the Ground Overlay should exactly overlap the satellite view.

We want to add a GroundOverlay of an illustration of the ThemePark on the actual satellite view as shown in the attached "appScreenshot.png"

![appscreenshot](https://user-images.githubusercontent.com/1822882/47454744-96ade580-d7ed-11e8-9416-c8483dc23e0b.png)

The set of bounds (Lat,Long of the 4 Corners of Overlay Image) passed to the map.addGroundOverlay() method is as below:
```
//LatLong of 4 corners of the overlay image
var bounds = [
            {"lat": 23.180857, "lng": 72.564129},//Rw
            {"lat": 23.182776, "lng": 72.576878},//Garden
            {"lat": 23.187722, "lng": 72.569211},//Rail
            {"lat": 23.176023, "lng": 72.571833},//Parking
        ];
```

But the problem we are facing is - No matter in what order we specify the lat long of the corners, the overlay image DOES NOT EXACTLY overlap the satellite view. Please see attached image.

In what order should the lat long of the bounds be specified?

Can you please specify how we can exactly overlap the ground overlay on the satellite view?

Also what is the maximum size of the image we can use for GroundOverlay?

**Comment by wf9a5m75** [comment]
You mis-understand one important thing.
`LatLngBounds` means `Rectangle bounds`, not `polygon bounds`.

For ground overlay adjustment, you can specify `bearing` property (`0-359`).

**Comment by pawangjain** [comment]
Thank you Masashi for pointing out in the right direction.

I now understand that LatLngBounds means Rectangle bounds (just 2 coordinates) and not polygon bounds.

I was able to set the bounds for the overlay image using the **"groundOverlay.setBounds"** example of the plugin wherein the markers were adjusted to overlay the image exactly on the satellite view as shown in the screenshot.

![mapgroundlayoutmarkersetting](https://user-images.githubusercontent.com/1822882/47555502-974b9680-d929-11e8-9d7b-601421499232.jpg)

I also used the bearing property to rotate the overlay image.

It basically worked.

But is it possible to compute the bounds directly based on the image beforehand?
Which SouthWest and NorthWest coordinates are represented by the bounds?

**Comment by wf9a5m75** [comment]
> But is it possible to compute the bounds directly based on the image beforehand?

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/utilities/geometry/spherical/computeHeading/README.md

>Which SouthWest and NorthEast coordinates are represented by the bounds?

Try like this:

```js

var bounds = new plugin.google.maps.LatLngBounds();
bounds.extends({"lat": 23.180857, "lng": 72.564129});
bounds.extends({"lat": 23.182776, "lng": 72.576878});
bounds.extends({"lat": 23.187722, "lng": 72.569211});
bounds.extends({"lat": 23.176023, "lng": 72.571833});

var polyline = map.addPolyline({
  points: [
     bounds.northeast,
     {lat: bounds.northeast.lat, lng: bounds.southwest.lng},
     bounds.southwest,
     {lat: bounds.southwest.lat, lng: bounds.northeast.lng},
     bounds.northeast
  ]
});
```

**Comment by wf9a5m75** [comment]
ping
