### ISSUE TITLE
npm ERR! 404 Not Found: com.googlemaps.ios@~2.7.0

### ISSUE THREAD

**Issue by MichaelSamteladze** [mapsplugin/cordova-plugin-googlemaps#2484]
I can't build android apk file. Every time I try to build it gives an error 

npm ERR! 404 Not Found: com.googlemaps.ios@~2.7.0

![screenshot_1](https://user-images.githubusercontent.com/1502280/47525648-d983c200-d8ae-11e8-8a96-f4a0ccad6d0d.jpg)

**Comment by wf9a5m75** [comment]
That's ios module.

**Comment by MichaelSamteladze** [comment]
I know it's iOS module, All I do is, I install this plugin and trying to build my apk, I don't have any other google plugins installed.

**Comment by wf9a5m75** [comment]
Make sure in your `package.json`. `com.googlemaps.ios` is not on npm, because too huge, and this plugin does not use it anymore.

**Comment by wf9a5m75** [comment]
If you can't solve the problem by yourself, please share your project files on github.
