### ISSUE TITLE
App Crash due to high resolution Ground Overlay image

### ISSUE THREAD

**Issue by pawangjain** [mapsplugin/cordova-plugin-googlemaps#2485]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.2.2 "Whitelist"
```

**Current behavior:**
Ground Overlay image with resolution 1920x1690 and size 887KB causes the app to crash on Moto-E (1GB RAM Android 5.1) and Mi Redmi 4A (2GB RAM Android 7.1)

Hello

Is there a limitation to the maximum size and resolution of the Ground Overlay image we can use in the plugin?

Using a Ground Overlay image with resolution 1920x1690 and size 887KB causes the app to crash on Moto-E (1GB RAM Android 5.1) and Mi Redmi 4A (2GB RAM Android 7.1)

What is the best possible image size and resolution we should use?

Thanks and Regards.

**Comment by wf9a5m75** [comment]
Out of memory. Reduce image size.

**Comment by wf9a5m75** [comment]
> 1920x1690

1920 x 1690 x 4 (rgba) = 12,979,200 (12.3MB)

In order to resize the image, the plugin needs to almost the same memory.

12.3 * 2 = 24.6MB.

And then, native Google Maps API display it as texture.
That spends many memory.
Android does not allow to use such a much memory space.

**Comment by wf9a5m75** [comment]
ping
