### ISSUE TITLE
Offline Tile Path computation issue on an Ionic App

### ISSUE THREAD

**Issue by pawangjain** [mapsplugin/cordova-plugin-googlemaps#2486]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.2.2 "Whitelist"
```

Hello

We are trying to use local tiles (bundled in the www folder) for TileOverlay in an ionic app.

There could be an issue in the path computation of the local tiles, specially for an ionic app in which the page URL contains **"#"**

**In the file PluginTileProvider.java line no. 318**

```
//---------------------------------
// load image from the local path
 //---------------------------------


File relativePath = new File(urlStr);
 urlStr = relativePath.getCanonicalPath();

```

In your demo app with the **webPageUrl**
`file:///android_asset/www/TileOverlay/index.html`
the method **getCanonicalPath** computes the tile image path to 
`www\images\map-for-free\0_0-0.gif`
which is a vallid file path.

But in an ionic app
the webPageUrl includes a **#** as shown below
`file:///android_asset/www/index.html#/Els/LocationMap//`

And therefore the method "getCanonicalPath" does not return a valid tile image path.The url computed is
`/www/index.html#/Els/images/ELS/map/tiles/16/45978/28428.png`
which is **invalid**.

If you can handle and fix the computation of the tile image path with **webPageUrl** having a **#** for ionic apps on both android and iOS, it will be great.

Thanks.

**Comment by wf9a5m75** [comment]
`cordova-plugin-googlemaps 2.3.8 `

Please upgrade the plugin before reporting problem at least.

**Comment by pawangjain** [comment]
Hello Masashi

I tried updating to the latest version.
This issue seems to be there in the latest version - 2.4.6.

Please check from your side if possible to handle a urlStr as shown below
`
www/index.html#/Els/LocationMap///../images/ELS/map/tiles/16/45978/28428.png.
`
in the statement

`File relativePath = new File(urlStr);
`
so that it gets converted into a valid image URL as below

`www/images/ELS/map/tiles/16/45978/28428.png`

Thanks.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by wf9a5m75** [comment]
ping
