### ISSUE TITLE
fromPointToLatLng on android 5

### ISSUE THREAD

**Issue by fareshan** [mapsplugin/cordova-plugin-googlemaps#2488]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 3.1.0 "Facebook Connect"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
```

```
@ionic-native/core : 4.12.2
@ionic-native/google-maps : 4.12.0
```

**Current behavior:**
this.map.fromPointToLatLng does not work on android 5 but works on android 6

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Ping

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread.

**Comment by fareshan** [comment]
I fixed the issue by upgrading to multiple_maps branch.
It seems to be the same kind of issue than this one [https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2419](url)
