### ISSUE TITLE
ERROR: Plugin 'map_0_104192685002' not found, or is not a CDVPlugin [Ionic v4]

### ISSUE THREAD

**Issue by zaarheed** [mapsplugin/cordova-plugin-googlemaps#2489]
**I'm submitting a ...** 
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:** 

```
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.5.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : ^5.0.0-beta.21
@ionic-native/google-maps : ^5.0.0-beta.25
```

**Current behavior:**
App builds and compiles fine. During runtime, the Output Console in XCode 10 shows the error message: 

```
ERROR: Plugin 'map_0_104192685002' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
```

Followed by:
```
FAILED pluginJSON = ["INVALID","map_0_104192685002","detachFromWebView",[]]
```

And finally:
```
CoreData: annotation:  Failed to load optimized model at path 'PATH_TO_SIMULATOR/MyAppName.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
```

My `config.xml` contains the follow:
```
<feature name="CordovaGoogleMaps">
    <param name="ios-package" value="CordovaGoogleMaps" />
    <param name="onload" value="true" />
    <param name="onreset" value="true" />
</feature>
```

So I cannot figure out where `map_0_104192685002` in the error message is originating from. Does anyone have any suggestions on how I can debug. I have gone through all related issues in this repo with no luck. I have installed and re-installed `cocoapods`, used `ionic cordova plugin remove` and add. I am using the flag `--buildFlag="-UseModernBuildSystem=0"` during builds.

The component containing the app does load, but displays a white screen.

**Expected behavior:**
Error message to not be displayed, or for the error message to be `Plugin 'CordovaGoogleMaps' not found, or is not a CDVPlugin`. Map to be displayed in component.

**Related code, data or error log (please format your code or data):**

I don't have any project files to share (yet). I'd like some advice on how to debug, or where the error is originating from.

**Comment by wf9a5m75** [comment]
I can't debug your issue without your project. If you decline share your project, please simply close this thread. If you will create a project that reproduce your issue 100%, please let me know.

**Comment by zaarheed** [comment]
@wf9a5m75 The doctor can ask about symptoms and make some initial guesses before the patient strips off their clothes, no? 

I tried to re-create a new, simpler project to upload but ran in to new issues which is why I didn't provide any code. It seems, as a separate issue that `ionic cordova plugin add cordova-plugin-googlemaps` doesn't complete the process of adding cocoapods dependencies.

I am now stuck with only a blank screen and the error:

```
CoreData: annotation:  Failed to load optimized model at path 'PATH_TO_SIMULATOR/MyAppName.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
```

Which means the original error I opened this bug for:

```
ERROR: Plugin 'map_0_104192685002' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
```

Is related to my project only and not the plugin. However, I notice that if I run the project in a browser it logs that a proxy is created for `map_0_104192685002`. I still haven't found where the reference to `map_0_104192685002` is generated :(

**Comment by wf9a5m75** [comment]
>The doctor can ask about symptoms and make some initial guesses before the patient strips off their clothes, no?

Yes, I guess it's depends on your program. That's why I asked. 

Based on my experience, I know I have to waste tons of time to inspect just guessing without checking your project.

But you refused. In that case, please inspect by yourself.

Since open source code, you can use this plugin as free, but spending my private time is not free.
You haven't contributed to this plugin anything, such as donation, or sending pull request.
I also provide private support issue chance, but you even didn't choose it.

Then there is no reason to support on your way.

I haven't asked to use this plugin mandatory. If you don't satisfy this plugin, please choose another plugin, such as open street map.

**Comment by Dasone** [comment]
I also have the exact same problem with my project on ios. Where Cordova-plugin-googlemaps is my only plugin. Would be glad if this issue would be taken seriously.

**Comment by zaarheed** [comment]
I resolved the error message by cloning [this demo](
https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4) and copying my `src` folder over. Not ideal, but for whatever reason it fixed the issue.

I have found that the white screen is caused by a [change in Ionic `v4.0.0-beta.12`](https://github.com/ionic-team/ionic/issues/16284). You can resolve the white screen by reverting to Ionic `v4.0.0-beta.11`
