### ISSUE TITLE
Crash when targeting Android 9 (API Level 28)

### ISSUE THREAD

**Issue by csabbey** [mapsplugin/cordova-plugin-googlemaps#2490]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x ] any problem or bug report

**OS:**  (check one with "x")
- [ x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

When targeting Android Pie with:
```
<preference name="android-targetSdkVersion" value="28" />
```

I get this stack trace when trying to pull up a map:

```
> Caused by java.lang.ClassNotFoundExceptionDidn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000009c/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000009c/MapsDynamite.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]] Raw Text
> --
>   | dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:134)
>   | java.lang.ClassLoader.loadClass (ClassLoader.java:379)
>   | ac.loadClass (:com.google.android.gms.dynamite_dynamiteloader@14367081@14.3.67 (100400-216465562):4)
>   | java.lang.ClassLoader.loadClass (ClassLoader.java:312)
>   | ew.b (:com.google.android.gms.dynamite_mapsdynamite@14367081@14.3.67 (100400-216465562):3)
>   | ev.a (:com.google.android.gms.dynamite_mapsdynamite@14367081@14.3.67 (100400-216465562):3)
>   | ex.a (:com.google.android.gms.dynamite_mapsdynamite@14367081@14.3.67 (100400-216465562):14)
>   | com.google.maps.api.android.lib6.drd.al.a (:com.google.android.gms.dynamite_mapsdynamite@14367081@14.3.67 (100400-216465562):6)
>   | dz.a (:com.google.android.gms.dynamite_mapsdynamite@14367081@14.3.67 (100400-216465562):21)
>   | dz.run (:com.google.android.gms.dynamite_mapsdynamite@14367081@14.3.67 (100400-216465562):8)
> 
> 
```

### The solution is to put
```
<uses-library android:name="org.apache.http.legacy" android:required="false"/>`
```
inside the application tag of the AndroidManifest.xml file.

References:
https://stackoverflow.com/a/50794266/2199492
https://issuetracker.google.com/issues/79478779
https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

**Comment by wf9a5m75** [comment]
This plugin does not use it.

**Comment by wf9a5m75** [comment]
As Google says
> If your app is targeting API level 28 (Android 9.0) or above, you must include the following declaration within the <application> element of AndroidManifest.xml.

This plugin specifies only `min-sdk`.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L156

If you choose `target-sdk` as `v28`, you need to include it by yourself, such as using `<edit-config>`. That's your role.

**Comment by wf9a5m75** [comment]
I believe this is role of App developer, but I inserted code to prevent further same question.
