### ISSUE TITLE
HTML Info Window no background and border

### ISSUE THREAD

**Issue by cedrickbae** [mapsplugin/cordova-plugin-googlemaps#2494]
**I'm submitting a ...**  (check one with "x")
- [X ] question
- [ ] any problem or bug report
- [X ] feature request

Hi, is there a way to remove the default background and pointer when creating htmlinfo windows?
I've search the docs for HTML Info window but apparently the only option available is setBackgroundColor. I would like to remove the background and stick to my div and css. Thanks!

**Comment by wf9a5m75** [comment]
Code is here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/HtmlInfoWindow.js

**Comment by cedrickbae** [comment]
Thanks! I just use the css to meet my needs.
