### ISSUE TITLE
Dynamically creating map instances

### ISSUE THREAD

**Issue by DonnyVerduijn** [mapsplugin/cordova-plugin-googlemaps#2495]
I am using this plugin in conjunction with React. I know about the issue that has recently been closed. I do not agree that it is impossible to integrate. It is possible to control the rendering behavior of React to prevent the map from re-rendering on state updates.

However, i would like to know if it is possible to create and destroy map instances dynamically or if i should use a static instance and provide access to the map using context?

**Comment by wf9a5m75** [comment]
I have no knowledge about react.

**Comment by DonnyVerduijn** [comment]
It doesn't really matter. Basically i just want to know if i can remove the map and later create a new one. Is that possible or should i use the same instance over the lifetime of the app?

**Comment by wf9a5m75** [comment]
I appreciate you quickly look over the document pages before asking.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Map/README.md

**Comment by DonnyVerduijn** [comment]
Sorry, i missed the reference of the map object. I will try to integrate it soon. For now i am using a static intance. Thanks for your response.
