### ISSUE TITLE
map on popup framework7 v1 not working

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#2496]
Im develop a app but i use framework7 v1 but i use a popup when i need to load a map inside but its not working my code of popup es  
`<div class='popup ppRegLc6 regloc'>
      <div class='view view-popup '>
        <div class='mapLocalw page-content mapclient'>
          </div>
      </div>
    </div>`

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios

**Comment by dsemerida** [comment]
thanks, i have changed the logic on my project i steel framework7 v1 but now i cant see any map

`  <div data-page="ppreglc6" class="page pull-page">
        

  
       <div class="navbar greenbase " >
           <div class="navbar-inner">
           <div style="width:84%;padding-left: 15px">
                       <a class="mylocation color-white">
                          <h4>Cuenta</h4>
                       </a> 
               </div>
               <div>
                   <a href="pages/clientside.html">
                    <i class="fas fa-times  color-white"></i>
                 </a>
               </div>
            </div>
        </div>
         <div class="page-content " style="background: #f9f9f9;">  
            <div  class="contentdetaillocal"   style="overflow: auto; height:93%;">
              <div id="mapi" style="height: 180px;width:180px;z-index:9999">
              </div>
            </div>
        </div>
        <div class="toolbar toolback " style="padding:14px 7px 0px 7px;">
               <div class="width50" style="float: left;">
                 <a style="color:#b3b3b3">
                    <i class="fas fa-sign-out-alt fa-2x color-gray"></i>
                    Cerrar sesión
                 </a>
               </div>       
        </div>
    </div>`

error on logcat
 DexFile_isDexOptNeeded failed to open oat file '/data/dalvik-cache/arm/data@data@com.google.android.gms@app_chimera@m@00000052@GoogleCertificates.apk@classes.dex'

**Comment by wf9a5m75** [comment]
That error does not comes from this plugin, or your authentication is failed.

If you ask me further question, please share your project files on github.

**Comment by dsemerida** [comment]
ok wait me some minutes

**Comment by dsemerida** [comment]
this is my project 
[rt2.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2559059/rt2.zip)

**Comment by wf9a5m75** [comment]
Please create a git repository, and put files on it.

**Comment by dsemerida** [comment]
https://github.com/dsemerida/mapframework7v1

**Comment by wf9a5m75** [comment]
:flushed: Are you kidding me, or you are git beginner(I don't think so)?

**Comment by wf9a5m75** [comment]
And did you read & understand the url I shared? (I don't think so)

This plugin displays the **native map view UNDER browser view**.

It means **(1) map is not HTML DOM element**, and **(2) you can not set background color for any HTML elements that are displayed over the map**.

```
<div class="page-content " style="background: #f9f9f9;">  <--- here!
        <div  class="contentdetaillocal"   style="overflow: auto; height:93%;">
          <div id="mapi" style="height: 180px;width:180px;z-index:9999">
          </div>
        </div>
    </div>
```

**Comment by dsemerida** [comment]
sorry

**Comment by wf9a5m75** [comment]
Then did you solve your problem?

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread.
