### ISSUE TITLE
When clicking on some POI's an exception is thrown: Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by yosigolan** [mapsplugin/cordova-plugin-googlemaps#2498]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x] any problem or bug report

**OS:**  (check one with "x")
- [x ] **Android**
- [x ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
call-number 0.0.2 "Cordova Call Number Plugin"
cc.fovea.cordova.purchase 7.2.4 "Purchase"
cordova-clipboard 1.2.1 "Clipboard"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 2.5.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.2.1 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 4.1.7 "IonicCordova"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-photo-library 2.1.1 "Photo Library"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.5.1 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 4.11.0
@ionic-native/google-maps : 4.9.1
```

**Current behavior:**
When clicking on some POI's an exception is thrown: Uncaught SyntaxError: Unexpected identifier.
for example, click on the McDonald poi at this coordinates: 48.875568, 2.296035

**Expected behavior:**
fire the poi event

**Screen capture or video record:**
![image](https://user-images.githubusercontent.com/18391088/48198700-565c7480-e362-11e8-97de-cd7e6faf8e5f.png)

![image](https://user-images.githubusercontent.com/18391088/48198718-65432700-e362-11e8-8fe7-2819ba6c4bbf.png)

**Comment by wf9a5m75** [comment]
> cordova-plugin-googlemaps 2.3.8

Please upgrade to the latest version at least.


Someone sent PRs recently.
Even if v2.4.6 doesn't work, please try the `multiple_maps` branch version.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ....
```

**Comment by wf9a5m75** [comment]
Ping

**Comment by yosigolan** [comment]
Thanks @wf9a5m75 
i am using ionic 3 and having problems with the upgrade due versions matching issues. once i will update my entire ionic project (should be soon) i will update the maps plugin as well and update you.

Thanks

**Comment by wf9a5m75** [comment]
ping

**Comment by yosigolan** [comment]
it wont be soon. if its problematic you can close the issue until i will make the upgrade.
Thanks
