### ISSUE TITLE
Option Map

### ISSUE THREAD

**Issue by luisfernando-rf** [mapsplugin/cordova-plugin-googlemaps#2503]
Good afternoon, I have a problem in the google maps plugin, where it happens only in IOS. In android when clicking on a marker it appeared the options in the bottom corner of the device. See below.

ANDROID: 
![android](https://user-images.githubusercontent.com/41697952/48506546-ccfce480-e830-11e8-9102-2cdaad74f363.png)

IOS: 
![ios](https://user-images.githubusercontent.com/41697952/48506317-47793480-e830-11e8-9e5d-1b2228024024.jpg)

And in the same app for IOS the same options do not appear. What's the problem?

My repository (this repository is not the ios platform):
https://github.com/luisfernando-rf/photoSellingMobileUI

**Comment by wf9a5m75** [comment]
Please ask to Google.

**Comment by luisfernando-rf** [comment]
Sorry, did you understand that I need it for IOS? In android it works.

Even marking true for mapToolbar for IOS does not display the options.
`map.setOptions({
       'controls': {
           'mapToolbar': true
        }
    })`

The documentation says the following:
`var button = div.getElementsByTagName('button')[0];
button.addEventListener('click', function() {

  // Change the map options
  map.setOptions({
    'mapType': plugin.google.maps.MapTypeId.HYBRID,
    'controls': {
      'compass': true,
      'myLocationButton': true,
      'indoorPicker': true,
      'zoom': true,
      'mapToolbar': true   // currently Android only
    },`

**Comment by wf9a5m75** [comment]
The toolbar is coming from the native API. Not this plugin.
That's why I said `Please ask to Google`.
