### ISSUE TITLE
Is it possible to specify Android minsdkversion="16"?

### ISSUE THREAD

**Issue by PurpleEdge2214** [mapsplugin/cordova-plugin-googlemaps#2506]
**I'm submitting a ...**  (check one with "x")
- [x ] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [ x] **Android**
- [ ] **iOS**
- [ ] **Browser**

name="cordova-plugin-googlemaps" spec="^2.4.6"

   Android SDK Tools : 26.1.1 (C:\Users\User\AppData\Local\Android\android-sdk)
   NodeJS            : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

Hello, I know that Android 4.1 is long gone, however some of my clients are using Android barcode scanners that still use this OS, and are very expensive to replace, so would like to continue using them.

Is it possible for me to somehow override the minsdkversion that is specified by this plugin so I can compile the app and install it on these devices?

**Comment by PurpleEdge2214** [comment]
Thanks, what do I need to change in order to get it to compile with minsdkversion="16"

**Comment by wf9a5m75** [comment]
Including the method, please search on google. It's not unsupported thing.

**Comment by PurpleEdge2214** [comment]
Thanks?
