### ISSUE TITLE
Maximum number of markers inside the marker cluster

### ISSUE THREAD

**Issue by elchory96** [mapsplugin/cordova-plugin-googlemaps#2508]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**
I am adding 196 markers to the MarkerCluster, but do not paint them on the map, if I make a limit of 100 there if it works

**Expected behavior:**
Let me draw all the 196 markers in the MarkerCluster

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by elchory96** [comment]
I already shared the project by bitbucket, in the folder 

`src / providers / mapa-inmuebles / mapa-inmuebles.ts`

 `on line 216` 

is where the counter of the maximum number of markers that lets me enter, is currently at 104 but if I increase a 105 shows nothing on the map.

**Comment by wf9a5m75** [comment]
Sorry for late response, I was really busy.
Number of cluster is updated when marker cluster redraw, such as zoom level is changed. This is not a bug.
