### ISSUE TITLE
is there a way to remove marker by a custom event (I'm using react and cordova)

### ISSUE THREAD

**Issue by ChEmunah** [mapsplugin/cordova-plugin-googlemaps#2512]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

**Comment by wf9a5m75** [comment]
I can't understand what you ask. Please describe more details. I have no knowledge about react.

**Comment by ChEmunah** [comment]
solved  by something else..
thank you anyway

**Comment by LiamKarlMitchell** [comment]
@ChEmunah How did you solve it?

I want to update markers when changed this may add or remove additional markers.

**Comment by ChEmunah** [comment]
I didn't try it but is [this](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/Marker/remove/README.md) what you're looking for?

**Comment by ChEmunah** [comment]
is [this](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/Marker/remove/README.md) helpfull?
