### ISSUE TITLE
![screenshot_2018-12-01-12-43-10-940_io ionic starter](https://user-images.githubusercontent.com/38494425/49325402-bad8b100-f567-11e8-8f25-c3a65461ae28.png)

### ISSUE THREAD

**Issue by Deliph13** [mapsplugin/cordova-plugin-googlemaps#2515]
![screenshot_2018-12-01-12-43-10-940_io ionic starter](https://user-images.githubusercontent.com/38494425/49325733-66383480-f56d-11e8-8e6e-9e7d67d02e7f.png)

not working in device ..
![screenshot-192 168 1 16-8100-2018 12 01-12-46-56](https://user-images.githubusercontent.com/38494425/49325407-d6dc5280-f567-11e8-94a6-0626dcaf1925.png)

_Originally posted by @Deliph13 in https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2514#issuecomment-443406439_

**Comment by wf9a5m75** [comment]
Don't spamming

**Comment by Deliph13** [comment]
cleared issue,, type script must be Version 2.7.2 ...
