### ISSUE TITLE
Move user's marker smoothly as the user moves

### ISSUE THREAD

**Issue by UlisesCeca** [mapsplugin/cordova-plugin-googlemaps#2516]
Hello, I've been finding through the issues in this repo but I havent found anything useful.

Is there any way such as a method to smootly move the marker as the user walks?

If not, what would be the best way?

Thanks!

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/utilities/geometry/spherical/interpolate/README.md

**Comment by UlisesCeca** [comment]
How could I know if I must increase or decrease fraction? I only wanna go 1 way as in a GPS

**Comment by wf9a5m75** [comment]
You have two points, current marker position and GPS position.

**Comment by UlisesCeca** [comment]
Doing an interval in such sort period of timee is causinbg the app to stop working...

**Comment by wf9a5m75** [comment]
Then please give up.

**Comment by wf9a5m75** [comment]
Google Maps native API doesn't have such a functionality.
