### ISSUE TITLE
Problem with v.1.2 and chromium webview

### ISSUE THREAD

**Issue by paishin** [mapsplugin/cordova-plugin-googlemaps#252]
When packaging an app with webview everything works fine and I can see though to the map but when packaged with chromium webview 38.0.2069.0 (I am using CocoonJS) then I only see the map and the app does not show through. 

If I inspect the code with chrome debugging tools then I can see that the app still runs fine but its under the map.

**Comment by besa23** [comment]
@paishin did you find out why those errors are thrown at the comment you wrote on  Nov 11, 2014 ???

**Comment by paishin** [comment]
Unfortunately no, I had to remove the plugin, abandon phonegap-googlemaps-plugin and re-write everything in angular-google-maps in order to have a chromium view. JS maps are slower and user experience not that great but I had to chose between an app that is generally slow but has responsive maps or a fast app that has a slow map. I went with the later.

As far as I know until today no solution has been found to use both.

**Comment by wf9a5m75** [comment]
Sorry @paishin , but it's chromium issue. I can't solve it by myself.

**Comment by paishin** [comment]
No worries Masashi, I already know this and I have stated numerous times in other posts that your work is nothing short of amazing. If at some point it does get resolved I will definitely come back to this plugin.

**Comment by jianbo** [comment]
Same here :(

**Comment by Hirbod** [comment]
I guess this bug will be fixed in the next weeks as crosswalk is also working on it to fix this problem.
