### ISSUE TITLE
Problem with myLocation

### ISSUE THREAD

**Issue by yusufs3435** [mapsplugin/cordova-plugin-googlemaps#2521]
Hi. Thank you for  this great plugin.

I have a problem with myLocation property. When I set myLocation:true,  location service of phone starts blinking on the top bar, the blue dot appears in the map.  If I leave the page that contains map or close the app, blinking stops. But if  the page that contains map is active (even if the app is in the background) the blinking keep its active state. So the battery quickly discharge.

I want to stop the service's active state after find location. How can I do it?

**Comment by wf9a5m75** [comment]
Try `map.setOptions()`

**Comment by yusufs3435** [comment]
Thanks. It solved my problem.  I use setOptions in Cordova's pause event to suspend location service.
