### ISSUE TITLE
button

### ISSUE THREAD

**Issue by yusufs3435** [mapsplugin/cordova-plugin-googlemaps#2522]
I want to create a button on the map. But the click event of the button never fire. What is the problem?

html file:
&lt;div id="map"&gt;
          &lt;button id="btn"&gt;click me&lt;/button&gt;;
&lt;/div&gt;

js file:
`$('#btn').on('click',function(){
    alert("ok");
});`

**Comment by battika** [comment]
Does it work if you move your button outside the map div? This is what I do in my project.

**Comment by yusufs3435** [comment]
I tried like this but nothing changed

<div id="wrapperMap">
                <button>click me</button>
                <div id="map"></div>
</div>

**Comment by battika** [comment]
I guess you should share your project for further investigation

**Comment by wf9a5m75** [comment]
@yusufs3435 In order to confirm your situation, please share your project files on git repository.

**Comment by yusufs3435** [comment]
It's my bad. There was a "pointer-events: none;" line for the button in css file. I'm sory to waste your time.
