### ISSUE TITLE
App crash when add cordova-plugin-googlemaps 

### ISSUE THREAD

**Issue by mehdio-namiki** [mapsplugin/cordova-plugin-googlemaps#2523]
when i install accountkit plugin app work fine but when i added cordova-plugin-googlemaps build sucess but the app has stopped ( crash ) !

**Comment by wf9a5m75** [comment]
Ping

**Comment by mehdio-namiki** [comment]
![bloggif_5c0bbe041e737](https://user-images.githubusercontent.com/11910154/49834670-e728d480-fd94-11e8-9f7f-cc9aa23db060.gif)
i dont know why really !!

**Comment by mehdio-namiki** [comment]
https://github.com/mehdio-namiki/accountkit-googlemaps

**Comment by wf9a5m75** [comment]
At least you need to set `19` instead `16`.
https://github.com/mehdio-namiki/accountkit-googlemaps/blob/f6f0dbd2fe83a0a293c16b79fd99265310d3aa76/accountkit_googlemaps/config.xml#L15

**Comment by wf9a5m75** [comment]
When I build your app, the app did not crash at least.
You can see Google Maps logo.
![capture](https://user-images.githubusercontent.com/167831/50269190-68f6ae80-03e2-11e9-8df4-6c84b1a712d4.png)

**Comment by wf9a5m75** [comment]
Ping

**Comment by wf9a5m75** [comment]
Ping

**Comment by jerryaner** [comment]
Dear friends,
i have the same issue,when i set the android-minSdkVersion to 16,it can not build success,when i set it to 19,it can build success,but when i open the app,it crashed,when remove this plugin,it work well,i have follow the [TIP](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/unknown_properties/README.mdl) to set it,it also have this issue
can you help me about this?

**Comment by jerryaner** [comment]
> please provide your repository before asking any question

Sorry,i don't have repository,i can provider the envirment version:
android:6.4.0
cordova:8.1.2 (before is 8.0.0 save issue)
node:10.8.0

**Comment by wf9a5m75** [comment]
You can create a repository on GitHub as free.

**Comment by hiepxanh** [comment]
let do it, declare this function:
```
.ts
detectWebGL() {
    // Check for the WebGL rendering context
    if ( !! (window as any).WebGLRenderingContext) {
        var canvas = document.createElement("canvas"),
            names = ["webgl", "experimental-webgl", "moz-webgl", "webkit-3d"],
            context;

        for (var i in names) {
            try {
                context = canvas.getContext(names[i]);
                if (context && typeof context.getParameter === "function") {
                    // WebGL is enabled.
                    return 1;
                }
            } catch (e) {}
        }

        // WebGL is supported, but disabled.
        return 0;
    }

    // WebGL not supported.
    return -1;
  }
```

then check it: 
``` .ts
let canOpenWebGL = this.detectWebGL();
console.log(`canOpenWebGL: ${canOpenWebGL}`);
```
```
-1 for not Supported,
 *                    0 for disabled
 *                    1 for enabled
```
if result is -1 or 0. Your app is sure will be crash. unless you add an small check to html, for my example: 
``` .html
    <!-- map -->
    <div *ngIf="canLoadMap else noMap" class="spa-maps">
        <button *ngIf="touchMaps" class="btnEnable" (click)="touchMaps = !touchMaps;">
            <ion-img src="../../../../../assets/imgs/icon-map/drag-icon.png"></ion-img>
        </button>
        <div id="bookableMaps" [ngStyle]="{'pointer-events': touchMaps ? 'none' : 'all' }">
        </div>
    </div>
    <ng-template #noMap>
        <p style="margin:25px">Map is not available on your device!</p>
    </ng-template>
```

**Comment by wf9a5m75** [comment]
This plugin does not use webGL at all.

**Comment by wf9a5m75** [comment]
Since there is no response from @mehdio-namiki for a while, I close this thread.
