### ISSUE TITLE
fillOpacity  property not working

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [mapsplugin/cordova-plugin-googlemaps#2524]
circleOptions: CircleOptions = {
        center: { lat: 0, lng: 0 },
        radius: 20,
        strokeColor: "rgba(0, 0, 255, 0.5)",
        strokeOpacity: 0.8,
        strokeWidth: 1,
        fillOpacity: 0,
        fillColor: "rgba(0, 0, 255, 0.5)",
    };

In ionic I am using this plugin 
the property fillOpacity value is not reflacting
But in jquery plugin by google, the property is working fine.

**Comment by Gurjit-ONEBCG** [comment]
> Please share your project files on git repository.

Please check there is no option for fillOpacity
https://github.com/ionic-team/ionic-native-google-maps/tree/master/documents/circleoptions

So my question is how can is use fillOpacity param as there is no such option in given plugin

**Comment by wf9a5m75** [comment]
There is no fillOpacity property. You need to specify alpha using ethier #rrggbbaa or rgba()

**Comment by wf9a5m75** [comment]
>But in jquery plugin by google, the property is working fine.

Other plugin is other plugin, not this plugin. It's not related at all.

**Comment by Gurjit-ONEBCG** [comment]
> > But in jquery plugin by google, the property is working fine.
> 
> Other plugin is other plugin, not this plugin. It's not related at all.

Ok Thanks
