### ISSUE TITLE
Marker Cluster: new marker under cluster

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#2530]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-ios-plugin-no-export-compliance 0.0.5 "iOS No Export Compliance"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-advanced-http 2.0.1 "Advanced HTTP plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-browsersync 0.1.7 "cordova-plugin-browsersync"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.5.0-beta-20181030-1133 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-qrscanner 2.6.0 "QRScanner"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^5.0.0-beta.22",
"@ionic-native/google-maps": "^5.0.0-beta.22",
```

**Current behavior:**
New marker created as single marker with method map.addMarker() is under Marker cluster icon.

Use case:
I have Marker Cluster, zoomed to high zoom level to see single markers. On tap of some marker I need change its icon to mark as active.
- There is one option: change marker cluster source and let it assemble again by cluster.remove() and addMarkerCluster() (bad option, too high cpu system resources usage).
- My approach: create new marker using addMarker() method with same coords as clicked marker. Marker is placed under clicked marker almost everytime. Zoom out to recalculate cluster and zoom in helps, new added marker is above original marker cluster single icon.

New created marker has big zIndex (99999), it has no effect.

Calling cluster['_objectInstance']._triggerRedraw({force:true}) after marker created does not help - this will let avoid using addMarker() method for changing icon of clicked marker.

Works correct on iOS, new marker is always above single marker of Marker Cluster.

**Expected behavior:**
- Place new markers always above marker cluster single marker.
- Working redraw method to update Marker cluster from source icons to avoid using addMarker(). This is preferred solution, if it is possible. Adding new marker is redundant.

**Related code, data or error log (please format your code or data):**
Will create small git repository if needed.

**Comment by wf9a5m75** [comment]
>Will create small git repository if needed.

Yes please

**Comment by wf9a5m75** [comment]
Ping

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread.
