### ISSUE TITLE
problem with getPosition() marker.getPosition is not a function

### ISSUE THREAD

**Issue by rizpardazan** [mapsplugin/cordova-plugin-googlemaps#2532]
hello all
i was used v1.4.0 in my phonegap app and now i want to change to v2.3.7 
i do everything except this code :

`marker.addEventListener(plugin.google.maps.event.MARKER_DRAG_END, function(marker) {
							marker.getPosition(function(latLng) {								 
								temp_result=explode(",", latLng.toUrlValue() );
								
								drag_marker=marker;
								callAjax("dragMarker","lat=" + temp_result[0] + "&lng="+ temp_result[1] );	 
							});
						});`

please help me to convert this to v2.3.7

**Comment by wf9a5m75** [comment]
Please read documents before asking.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md
