### ISSUE TITLE
isit possible to pass key at run time

### ISSUE THREAD

**Issue by aks257** [mapsplugin/cordova-plugin-googlemaps#2533]
For my project i will get api _key from server, so is it possible to pass api key at run time instead of at the time of plugin addition?

**Comment by makers-mark** [comment]
Unfortunately No. Quite honestly you would of heard about people doing this for a long time as it is a "ideal" way for everybody. But, for the sanctity of being able to scrutinize api keys for what they are, you do not have that option. 12.25.18

**Comment by wf9a5m75** [comment]
@aks257 Since Google Maps SDK for Android requires API key at the build time, you (we) can not set API key at run time.
