### ISSUE TITLE
Slow performance on Android/IOS adding polygons

### ISSUE THREAD

**Issue by holsteinkaa** [mapsplugin/cordova-plugin-googlemaps#2534]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
es6-promise-plugin 4.2.2 "Promise"
```

**Current behavior:**
Adding around 500 polygons stored in JS array, takes around 2-5s for Android and IOS, with SDK. Under 1s in desktop browser and mobile browser, and even faster with Google Maps v3 GeoJSON data layer. 

The app feels more responsive in browser but the native SDK apps loads map tiles faster. 

Any idea to make it faster on Android/IOS? 

My idea is to only show the polygons within the bounding box or go back to GM V3 Javascript API.

**Comment by wf9a5m75** [comment]
Please use Google Maps JavaScript v3.
