### ISSUE TITLE
Issue with ionic header

### ISSUE THREAD

**Issue by int128fly** [mapsplugin/cordova-plugin-googlemaps#2536]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : ~4.18.0
@ionic-native/google-maps : ^4.15.1
```

ionic info
```
Ionic:

   ionic (Ionic CLI)  : 4.5.0 (/xxx/.nvm/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 6 other plugins)

System:

   NodeJS : v8.11.3 (/xxx/.nvm/versions/node/v8.11.3/bin/node)
   npm    : 5.6.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61
```

**Current behavior:**
The issue only happen on iOS where ionic menu buttons in headers are really hard to click on ( you have to click above or under it to trigger the buttons) and this only happen when I add  the google maps cordova plugin. We had a older version of our app with google map and it was working back then but since we updated the google map plugin we had that issue.

**Expected behavior:**
When I remove the plugin everything works properly as expected.

**Comment by int128fly** [comment]
I don't have time to setup a project right now since I am at work and we are on a deadline for multiple project but I just want throw you an update, I've installed version 2.3.6 and everything works flawlessly (at least for our uses)

I will post an example to reproduce that error on my free time later tonight.

**Comment by wf9a5m75** [comment]
Duplicated issue.
