### ISSUE TITLE
How to use in android application 

### ISSUE THREAD

**Issue by haghighi251** [mapsplugin/cordova-plugin-googlemaps#2537]
Hi ...
I want to use this plugin in android application.I made android apps api key in google console and verify it .But don't know how can I use that ?!
I need example.I searched at google and I just found some example in javascript api 3 .

**Comment by haghighi251** [comment]
I'm using framework7.

**Comment by wf9a5m75** [comment]
Then please ask the another community

**Comment by haghighi251** [comment]
I just need the code of how can I use Google Maps Android API in my cordova application .You  just think I'm using cordova with out f7 .So All thing that I need is a sample code for using Cordova GoogleMaps plugin for Android .If you get me that code ,I can edit it for f7 .
