### ISSUE TITLE
GroundOverlayOptions docs

### ISSUE THREAD

**Issue by UlisesCeca** [mapsplugin/cordova-plugin-googlemaps#2538]
I can't seem to find the docs for this class, what attribute do I have to use to add an image? Until now I was using url but now I have a base64

Thanks

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/GroundOverlay/README.md

**Comment by UlisesCeca** [comment]
Thanks but that's GroundOverlay not GroundOverlayOptions. I'd like to know which properties I can set.

**Comment by wf9a5m75** [comment]
Why don't you search by yourself.
https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/groundoverlayoptions/README.md
