### ISSUE TITLE
MARKER_CLICK event not working

### ISSUE THREAD

**Issue by UlisesCeca** [mapsplugin/cordova-plugin-googlemaps#2539]
Hi, I am trying to use this event as follows:

`this.map.addEventListener(GoogleMapsEvent.MARKER_CLICK).subscribe(() => console.log("Tocado"))

However, it doesn't get fired. I'm creating the markers with "addMarker" method.

What's wrong?
    `

**Comment by wf9a5m75** [comment]
Wrong target.

https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000
