### ISSUE TITLE
MarkerCluster will not load after Click on Marker

### ISSUE THREAD

**Issue by webnologie** [mapsplugin/cordova-plugin-googlemaps#2541]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```

```

**Current behavior:**

this problem only exists on a huawei 5.0.1 phone with your current version 2.4.6. i use also markercluster. if i scroll into one "cluster" and than i klick one one marker, after that i zoom out and klick on another marker i have the problem that the other marker will not shown - like the whole map will not react... 

**Expected behavior:**

**Screen capture or video record:**
1st Screen after loading, 2 Screen i clicked one one Marker and zoomed automated in, 2 Screen i zoomed manually out but the other marker will not shown. 
![1](https://user-images.githubusercontent.com/21243083/50887285-19107380-13f3-11e9-8c83-bfc82d80597a.png)
![2](https://user-images.githubusercontent.com/21243083/50887294-1f9eeb00-13f3-11e9-94ea-8bf3b165adb0.png)
![3](https://user-images.githubusercontent.com/21243083/50887300-23327200-13f3-11e9-8749-0e3ec8438143.png)

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Try `v2.5.0`. Should be fine.

**Comment by webnologie** [comment]
@wf9a5m75 thank you very much, but when i test it on android 5.0 it will be load very slow. about 5-7 minutes for about 2000 markers in markerclusterer. in your previous version the performance was better, but if i open some markercluserer, it will not display the others when i zoom out. and its not a huawei problem, android 5.0 is the problem in this case.

**Comment by wf9a5m75** [comment]
Please share your project files on github if you want to help.

**Comment by webnologie** [comment]
@wf9a5m75 i just checked your version 2.4.6. yes there is no performance problem with android 5.0. i do nothing special following a snipped to add my marker. about 3000... 


`    allMarkers.forEach(function(data) {
      var tm=map.addMarker({
        position: data.position,
        markerid: data.markerid,
        icon: data.icon
  
      }, function(){});
      tm.on(plugin.google.maps.event.MARKER_CLICK, function() {
          showInfowindow(tm.get("markerid"));
      });
    });`

and there is no different if i use markerclusterer or not. in your old version this problem will not happen.

best regards, emanuel

**Comment by wf9a5m75** [comment]
Okay, please stay on 2.4.6 in your case.

**Comment by webnologie** [comment]
no problem, if you need somebody for testing, let me know. br, emanuel

**Comment by wf9a5m75** [comment]
Without providing entire project files, I do not do nothing for free support.

**Comment by webnologie** [comment]
in my case its ok with 2.4.6. and i mean it positive that i can test it for you because other people may also the same problem with android 5.0... you can also tell me your fee, i can transfer it via paypal - thats no problem if you want, i can send you the files private..

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/.github/ISSUE_TEMPLATE/private-support.md

**Comment by webnologie** [comment]
> https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/.github/ISSUE_TEMPLATE/private-support.md

just send you again... thanks...

**Comment by wf9a5m75** [comment]
This issue moves to private support room.

**Comment by webnologie** [comment]
ok great, thank you for your assistance. im not a professional user on git-hub so the best think is that i explan or send you some code snippets to the project... best way - i think - please tell me what you need?

**Comment by wf9a5m75** [comment]
You can reply at here.

![screen shot 2019-01-25 at 11 59 10 am](https://user-images.githubusercontent.com/167831/51769755-a6f98900-2098-11e9-98a7-475401803db5.png)

**Comment by wf9a5m75** [comment]
@webnologie Can you open this URL?
https://github.com/orgs/mapsplugin/teams/cordova-plugin-googlemaps-2541/discussions
