### ISSUE TITLE
map.addKmlOverlay throw "self.map.addMarker(...).then is not a function"

### ISSUE THREAD

**Issue by rodneicouto** [mapsplugin/cordova-plugin-googlemaps#2544]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android** (it just tested here)
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
```
cordova-plugin-googlemaps 2.5.0-beta-20190102-1842 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**

With some KML file, the following code launch a exception
```JAVASCRIPT
 map.addKmlOverlay({
       url: 'example.kml'
 }, function(kmlOverlay) {
     this.map.moveCamera(kmlOverlay.camera);
 })
```

The Exception
```
Uncaught (in promise) TypeError: self.map.addMarker(...).then is not a function
    at KmlLoader.js:615
    at new Promise (<anonymous>)
    at KmlLoader.parsePointTag (KmlLoader.js:591)
    at KmlLoader.parseKmlTag (KmlLoader.js:287)
    at BaseArrayClass.<anonymous> (KmlLoader.js:136)
    at BaseArrayClass.js:148
````

The KML was generated by Google MyMaps. [https://raw.githubusercontent.com/rodneicouto/cordova-googlemaps-test/master/www/example.kml](https://raw.githubusercontent.com/rodneicouto/cordova-googlemaps-test/master/www/example.kml)

**To Reproduce**
* Download repo: [https://github.com/rodneicouto/cordova-googlemaps-test](https://github.com/rodneicouto/cordova-googlemaps-test)
* Change API_KEY in both _config.xml_ and _package.json_. Look for 'CHANGE_HERE'
* run `npm install`
* run `cordova platform add android`
* run `cordova run android`

**Comment by rodneicouto** [comment]
I think get the problem. In _KmlLoader.js_, line 614, is expected to _addMarker_ returns _Promise_ but the _Map.addMarker()_ returns an object of type _Marker_, not a _Promise_. 

This change solved the problem for me. [https://github.com/rodneicouto/cordova-plugin-googlemaps/commit/ef0e3807e1335d667fce95b4fce1a3fbe6b5b921#diff-0ff499d7893eab07be44dc981d0e6f50](https://github.com/rodneicouto/cordova-plugin-googlemaps/commit/ef0e3807e1335d667fce95b4fce1a3fbe6b5b921#diff-0ff499d7893eab07be44dc981d0e6f50).

**Comment by wf9a5m75** [comment]
Fixed. thank you.
