### ISSUE TITLE
HtmlInfoWindow is not always reading marker's image size, when it was set as data url

### ISSUE THREAD

**Issue by marcinn** [mapsplugin/cordova-plugin-googlemaps#2550]
In `HtmlInfoWindow`'s `calculate` fn there is code like this: 
```
        var img = document.createElement("img");
        img.src = icon;
        iconSize.width = img.width;
        iconSize.height = img.height;
```
If `icon` is set to `data:` string, there is probably some kind of race condition and `img.width`, `img.height` are set to `0`. Probably reading image's size should be placed within `img.onload` callback. 

But maybe better solution is to set `marker.icon` property to an object containing `url` with data string, where icon's image size would be stored while calling `marker.setIcon()`.  This would also improve consistency and will not require re-reading icon's size in HTMLInfoWindow.

**Comment by wf9a5m75** [comment]
If you want to desire something, please send a pull request.

**Comment by marcinn** [comment]
This bug should not be closed, because still exists.
