### ISSUE TITLE
Error adding overlay with image from assets or large base64

### ISSUE THREAD

**Issue by UlisesCeca** [mapsplugin/cordova-plugin-googlemaps#2552]
Hello, again...

I am trying to add an overlay to my map. This image is a bit "big" (6mb) If I add it from an url it works but I don't wanna use user's network data so I wanna either use its base64 or get it from the assets. However, if I use its base64 or y to get the image from `assets`, the App crashes. The code is:

```
let groundOptions: GroundOverlayOptions = {
        bounds: bounds,
        url: "assets/img/planta_0.png",
        bearing: this.building.rotation * 180 / Math.PI
};
```

Could it be because the image's size is too big or it has too many pixels? Because if I try with a smaller image, it works...

The image is the following: https://i.imgur.com/w4GwxEj.jpg

**Comment by wf9a5m75** [comment]
Out of memory. Not bug.

**Comment by wf9a5m75** [comment]
Use TileOverlay

**Comment by UlisesCeca** [comment]
> Use TileOverlay

Doesn't work too with large image in assets or base64, just from URL, there is nothing that can be done?

**Comment by wf9a5m75** [comment]
You must need to split image into 512x512 pixels.
