### ISSUE TITLE
MarkerCluster: -----> This is remained cluster icon (markers are too close each other)

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#2553]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.5.0 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.2 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^5.0.0",
"@ionic-native/google-maps": "^5.0.0-beta.26",
```

**Current behavior:**
Markers placed to marker cluster too close each other resolves in error after click to marker detail -----> This is remained cluster icon: markercluster_519581655346. 

Attached github repository contains randomly generated markers between [0,0] to [0.02,0.02].
Try to change ```Math.random() / 50``` to ```Math.random() / 40``` and almost every marker detail works (shown in console).

**Expected behavior:**
Fire marker tap for every marker.

**Related code, data or error log (please format your code or data):**

Working error sample:
```
https://github.com/vosecek/map_test
```

**Comment by wf9a5m75** [comment]
Thank you for reporting. I fixed the problem.
Please reinstall the plugin from the multiple_maps branch (https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/5a6d2870dba24ff74bcbfa0b016fbf7c7dfbf231)

**Comment by wf9a5m75** [comment]
Please reinstall 
- `cordova-plugin-googlemaps` v2.5.1
- `@ionic-native/google-maps` v5.0.0-beta.27
