### ISSUE TITLE
Map not shown on iOS 12.2

### ISSUE THREAD

**Issue by giladrom** [mapsplugin/cordova-plugin-googlemaps#2555]
This is just a report, not sure where the bug is, but it confused me initially since I thought
there was something wrong with Google's servers, and only then I realized that my
phone had auto-upgraded overnight. 

Posting in case anyone else has an issue and wondering why the map stopped showing up
in their app all of the sudden :)

**Comment by wf9a5m75** [comment]
Please create a simple app with this plugin and test it on your phone before asking.

**Comment by wf9a5m75** [comment]
Native Google Maps app is not related with this plugin at all.

**Comment by giladrom** [comment]
That is correct. However, they are both having issues on iOS 12.2 and the common denominator is that they both use the Google Maps SDK.

**Comment by wf9a5m75** [comment]
That's not this plugin's problem. Ask Google or Apple.

**Comment by giladrom** [comment]
This is not a bug report. This is reported for visibility to assist other developers (and you).

**Comment by wf9a5m75** [comment]
I think problem is only occurred on you, otherwise, I should receive the more reports.

**Comment by giladrom** [comment]
I hope so.

**Comment by battika** [comment]
Not really, It affects my IOS 12.2 beta users too. Creating a sample app and looking into the issue soon...

**Comment by giladrom** [comment]
There are other issues with 12.2 - the first beta also had Firestore connection errors for me. They never happen on 12.1, but semi-consistently on 12.2, so at first I thought this was causing the map to not initialize. However, now with the second beta Firestore is working fine bu the map is still misbehaving.

**Comment by seriyvolk83** [comment]
I have iOS 12.1 and map is empty in my case too. No error in console. It Just shows blank rect with Google logo.

**Comment by seriyvolk83** [comment]
cc @wf9a5m75

**Comment by seriyvolk83** [comment]
>That's not this plugin's problem. Ask Google or Apple.
🤣

 You just closed the issue without trying to reproduce it? Wow! That's a level!

**Comment by wf9a5m75** [comment]
>  It Just shows blank rect with Google logo.

It's your API key problem.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/graymap/README.md

**Comment by seriyvolk83** [comment]
@wf9a5m75 I have a valid key with unlimited access and the map is empty.
