### ISSUE TITLE
Map view getting destroyed when turning off Wi-Fi

### ISSUE THREAD

**Issue by UlisesCeca** [mapsplugin/cordova-plugin-googlemaps#2556]
Hello, when my map is loaded and I turn off my Wi-Fi the map view gets destroyed. Here is a video to show it: https://youtu.be/FyRZGDnglzc

My code is pretty simple:

HTML: 

`<div #map id="map" [class.oculto]="loading && allPreconditionsSet()"></div>`

CSS: 

```
  .oculto {
    position: absolute;
    left: -100%;
  }
```

**Comment by wf9a5m75** [comment]
If you want me to check your code, please share your project files on GitHub repository. Otherwise how can I advise you without any hints?

**Comment by wf9a5m75** [comment]
ping
