### ISSUE TITLE
Rotate map with Google Maps API V3

### ISSUE THREAD

**Issue by UlisesCeca** [mapsplugin/cordova-plugin-googlemaps#2559]
Hello, I know this is not the right section, but I am truly desperate and I thought you may know if this is possible.

I am trying to rotate Google's Map and I'm using their JS API. I am trying to use `setHeading()` method but it's not working since as I've read it'll only work if the map type is hybrid or satellite and if there's a certain tilt.

I've seen in your browser code -> https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/browser/PluginMap.js that you have this method too in your `setCameraBearing()` method. 

My question is, is there a way to rotate the map using Google's Map JS API v3 as I can see this plugin does it in its code? I am willing to request private support if you can help me rotate Google's Map but using their JS API not this plugin, but I need to know if this is possible first in order to pay.

Thanks.

**Comment by wf9a5m75** [comment]
Technically not possible, because Google Maps JavaScript API v3 does not have the function.

`setHeading()` method works only satellite tile panel at particular locations (such as US big cities)

**Comment by UlisesCeca** [comment]
How comes it works with this plugin then? Don't you use Google JS API under it?

**Comment by wf9a5m75** [comment]
This plugin uses three APIs (everything describes in [README.md](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md)).

Android - Google Maps SDK for Android
iOS - Google Maps SDK for iOS
browser - Google Maps JavaScript API v3.

**Comment by UlisesCeca** [comment]
And in the browser version of this plugin, does setCameraBearing(bearing) work? I only tried the Android version and it worked perfectly there without satellite or tilt mode

**Comment by wf9a5m75** [comment]
>does setCameraBearing(bearing) work without satellite and tilt?

As I said above, no.

**Comment by UlisesCeca** [comment]
It worked on Android tho

**Comment by wf9a5m75** [comment]
APsI are different.
