### ISSUE TITLE
[ionic] The map disappears when changing tabs

### ISSUE THREAD

**Issue by ramirogm** [mapsplugin/cordova-plugin-googlemaps#256]
Hi, I'm trying to integrate the plugin with ionic. 
If I switch from the tab showing the map to another one and back again, the map is missing.
I think it's because ionic resets all the tab content. See: http://ionicframework.com/docs/api/directive/ionTab/ it says "The content only exists while the given tab is selected.".
How to reproduce: the example project initially shows the map in the dashboard, but the tabs are not working because the plugin steals the clicks. 
If I change the map div height to 200px, the tabs work again, but if I go back to the "Dashboard" tab, the map is missing.

I'm trying to undertand if the map is removed or just hidden somewhere.

**Comment by VGerris** [comment]
I am unable to implement whatever was posted.
Is someone able to post the code to fix it in this:
http://www.instructables.com/id/Creating-an-Android-app-using-Ionic/?ALLSTEPS
with the difference of this V2 plugin being used for the map?
I keep having the map being half visible after an open-close of the tabs.
Any help is appreciated :)

**Comment by jujubha** [comment]
Here is another way to fix it.

Have different canvas id per navigation to the same view,

Like 

<div id="map_canvas_{{some_id}}"></div>

This keeps the data pertaining to particular the visit to the view private, having one map per view, not per visit. That way the map state is retained and will be displayed properly.

This works for my quite well without a single glitch.

**Comment by jujubha** [comment]
&lt;div id="map_canvas_{{some_id}}"&gt;&lt;/div&gt;

**Comment by rolinger** [comment]
@ramirogm - I am having the same problem, and I understand the concept of the ionic dumping the DOM per tab just don't know how to go about fixing it though. 

I just tried your implementation above and laced it with console messages all throughout to see what/where things are triggering.  However, the `<ion-tab on-select="refreshMap()" ...>` isn't firing at all.  The view goes back to the map tab...it is still blank.  Best I can tell refreshMap simply doesn't fire.  I then tried ng-click='refreshMap' and nothing happened at all...the tab button hightlighted for a moment but the view stayed on the current tab versus going back to the map tab.  

Any thoughts?  I can post more code/details later.

**Comment by rolinger** [comment]
Ok, so I saw my app do something else.  While the phone was upright in portrait mode, the map disappeared (more like greyed out and I can still see some of the map along the edge - so def not a "white" screen), but when I flip the phone to landscape mode, the map screen redraws itself.  And the opposite is true too.  If in landscape mode, go to another tab, come back its greyed out, move the phone to portrait and it redraws itself.

I am thinking my issue is different though I do like your solution above - it guarantees the map all the way around.   I think (rather hope) your solution would also fix my issue.

**Comment by rolinger** [comment]
Then I found this:  http://stackoverflow.com/questions/3838580/google-map-comes-partially-grey-area-comes-instead-of-images-from-google-server

Seems based on my apps symptoms that this is very much my ongoing issue.  Going to give this a shot and post results.

**Comment by rolinger** [comment]
Well, discovered my issue, related to AdMob persistent ads (which are sub-views) interfering with the proper rendering of google maps.

Mine is further documented here:  http://stackoverflow.com/questions/38511771/cordova-admob-causing-google-map-rendering-grey-screen-in-ionic-tabs

**Comment by melkir** [comment]
This is what I am currently doing with 3 tab, the first one is the map : 
`
  ionViewWillEnter() {
    let divScan = document.getElementById("tabpanel-0-1");
    let divParam = document.getElementById("tabpanel-0-2");
    divScan.style.visibility = 'hidden';
    divParam.style.visibility = 'hidden';
    this.mapComponent.enableMap() // setVisibility and clickable true
  }

  ionViewWillLeave() {
    let divScan = document.getElementById("tabpanel-0-1");
    let divParam = document.getElementById("tabpanel-0-2");
    divScan.removeAttribute("style")
    divParam.removeAttribute("style")
    this.mapComponent.disableMap()  // setVisibility and clickable false
  }
`

**Comment by srishiva89** [comment]
Hi,
I'm too facing same issue. In my app, I have two tabs. One tab is showing list and another one is showing Map. Also I have a search page too.
I can see the map whenever I'm visiting the map tab at first time. But I'm navigate to search page and come back to Map tab. I'm unable to see the Map in map tab. Function is working fine. But map is appending in html again. 

Please help me on this.

**Comment by SKempin** [comment]
@srishiva89 I am experiencing an identical issue, did you find a solution for this?

**Comment by rajatsawant** [comment]
In Ionic 1 instead of using $ionicPlatform.ready() use: 
angular.element(document).ready(function(){
   //your code
});
Worked for me!

**Comment by SKempin** [comment]
@rajatsawant I'm using Ionic 2 unfortunately.

**Comment by frystpingvin** [comment]
@srishiva89 @SKempin I experience a similiar issue using Ionic 2 and Typescript as well. Did you solve the problem?

**Comment by SKempin** [comment]
@frystpingvin No I haven't solved this. Are you using the new version 2 plugin?

**Comment by frystpingvin** [comment]
@SKempin No, I decided to try out v1 first as there doesn't seem to be much documentation for Ionic and v2 of this plugin. Have you tried v2?

The solution from @buithaibinh worked for me, but it isn't the most beautiful solution as the map flashes when entering the view.
```javascript
ionViewDidLoad(): void {
    setTimeout(()=>{
      this.loadMap();
    }, 100);
  }
```

**Comment by SKempin** [comment]
I am attempting to try version 2, but have not got this working as of yet. It supports multiple maps, and apparently will work.

**Comment by rolinger** [comment]
@Skempin @frystpingvin  - hey guys, check out my comments above from July 21 2016.  There are two solutions I found, the 2nd one kind of just ensures there aren't anymore issues from other plugins causing blank maps, greyed out maps etc.  Both are relatively easy to implement.

**Comment by mbenvenuto** [comment]
Thanks guys for the solution, this one works for ionic 2/3:

   ionViewDidLoad() {
    setTimeout(() => {
      this.initMap();
    }, 100);
  }

**Comment by SKempin** [comment]
@mbenvenuto Thanks! Your fix has solved it - it seems that having crosswalk previously installed prevented this fix from working the first time I tried it. I have now removed crosswalk and that works. 

However I also link to the map from sub-pages, and for some reason I can only see a small portion of the view when I navigate to it from these (rather than from the tab).

**Comment by Idrimi** [comment]
I have the following specs:
"@angular/core": "^5.2.6",
 "@ionic-native/core": "^4.5.3",
 "@ionic-native/geolocation": "^4.5.3",
 "@ionic-native/google-maps": "^4.5.3",


Fixed it using CSS. In the page you're displaying a map (eg. map.html) add the followin css to (eg. map.css):

ion-app._gmaps_cdv_ .nav-decor{
  background-color: transparent !important;
}
