### ISSUE TITLE
Error loading KML if polygon has 'tessellate' node 

### ISSUE THREAD

**Issue by ggiordan** [mapsplugin/cordova-plugin-googlemaps#2560]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ X] any problem or bug report

**OS:**  (check one with "x")
- [ X] **Android**
- [ X] **iOS**
- [ x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
D:\rovermobileandroid>cordova plugin list
com.borismus.webintent 1.0.0 "WebIntent"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"
```

**Current behavior:**

The KML loader is not finding the coordinates if there is a tesselate node in the linearring, like this:
![image](https://user-images.githubusercontent.com/3812056/52893671-006f4800-316d-11e9-9d8b-8027b61564a5.png)

**Expected behavior:**
Load the KML file

**Related code, data or error log (please format your code or data):**
The problem is caused by these lines of code in KmlLoader.js (around line 608)
```
    switch (element.tagName) {
      case "outerboundaryis":
        if (element.children.length === 1) {
          switch(element.children[0].tagName) {
            case "linearring":
              coordinates = element.children[0].children[0].coordinates;
              break;
```
in the case above, the coordinates are not children of the 0th element.  They are the children of the 1st element.

I _THINK_ the answer is to use findTag(), but, I'm not 100% sure.

I've worked around my immediate problem by removing the node, so that the coordinates are at the 0th element.
But in the long run this is not workable as I don't control all the supplied KML.

**Comment by wf9a5m75** [comment]
`<tessellate>1</tessellate>` is difficult for this plugin. Thus, ignore the tag. Please send a pull request, or give up it.

**Comment by wf9a5m75** [comment]
Update: `<tessellate>1</tessellate>` is technically not available. Because Google does not provide any altitude information from SDKs/API.

If you don't believe me, please try by yourself, and send a pull request.

**Comment by ggiordan** [comment]
I have no issue ignoring that tag, or any other unused tag for that matter.  I am not suggesting that support for altitude is needed in this case, sorry if for not being clear on that point.

The real point is that if the kml contains a polygon with something other than the <coordinates> as index zero, it throws an exception... the the coordinates variable is undefined and the foreach a few lines down barfs.

I'm simply suggesting that the code should be a little more robust and not make an assumption where the element is.  We know there is at least one KML file in the wild where this is true.  I think it was exported from an ARCSYS system, so I expect that there are plenty more too.
