### ISSUE TITLE
Crashes with black screen

### ISSUE THREAD

**Issue by thomashrabe** [mapsplugin/cordova-plugin-googlemaps#2561]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android** (not tried)
- [x] **iOS**
- [ ] **Browser**

```
cordova-plugin-googlemaps 2.5.0 "cordova-plugin-googlemaps"
```

```
@ionic-native/core : "^4.20.0"
@ionic-native/google-maps : "^4.20.0"
```

**Current behavior:**
When map loads, it kills the whole app.

**Expected behavior:**
Map shows as with previous `2.3.8` installation

**Screen capture or video record:**

Blank, black screen in the simulator after the main view loads, crash, default iOS window.

**Related code, data or error log (please format your code or data):**

 ```
         const mapOptions: GoogleMapOptions = {
          //   controls: {
          //     compass: false,
          //     myLocation: true,
          //     myLocationButton: false,
          //     mapToolbar: false,
          //   },
            // mapType: GoogleMapsMapTypeId.HYBRID
          };
          this.map = GoogleMaps.create('map_canvas', mapOptions);
```

The app crashes completely without any logs or prints when the above code is enabled, when it's disabled it works.
I have a old installation with `cordova-plugin-googlemaps 2.3.8` running on another computer with as I see `com.googlemaps.ios 2.7.0` still installed. The above code works there. This is a fresh installation and I believe I must be missing an installation step somewhere. Do I need to download 
`com.googlemaps.ios` somehow? I thought `pod` would take care of that?

**Comment by wf9a5m75** [comment]
```
cd platforms/ios
pod install
```

**Comment by thomashrabe** [comment]
And then? I did pod install in the ionic project folder. Can this info be added to the install instructions?

**Comment by wf9a5m75** [comment]
Cordova command should take care of cocoapod installation. If does not work, ask to them.

**Comment by thomashrabe** [comment]
Thank you, that worked!
