### ISSUE TITLE
Marker image does not show on device but on shows in simulator

### ISSUE THREAD

**Issue by thomashrabe** [mapsplugin/cordova-plugin-googlemaps#2562]
- [x] question
- [x] any problem or bug report

- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

```
cordova-plugin-googlemaps 2.5.0 "cordova-plugin-googlemaps"
```

```
@ionic-native/core : "^4.20.0"
@ionic-native/google-maps : "^4.20.0"
```

**Current behavior:**
Device does not show custom marker as with 2.3.8, but simulator still does

**Expected behavior:**
Markers are same on device as in simulator

Here is the marker generator

```
    static stationMarkerGenerator(station){
        return {
            title: station['name'],
            icon: './assets/imgs/buoySymbolSatelit26_31.png',
            position: {
              lat: parseFloat(station.lat),
              lng: parseFloat(station.lng)
            } 
        }
    }
```

**Screen capture or video record:**
**Device - bad** 

![untitled](https://user-images.githubusercontent.com/3632672/52931852-cc2d9000-3302-11e9-892f-55d3a472437d.png)

**Simulator - good**
<img width="507" alt="screen shot 2019-02-17 at 10 14 35 pm" src="https://user-images.githubusercontent.com/3632672/52931862-d485cb00-3302-11e9-8989-9e1cda431137.png">

**Comment by wf9a5m75** [comment]
Use the multiple_maps branch version.

**Comment by thomashrabe** [comment]
How do I check out the branch? As described here?

**Comment by wf9a5m75** [comment]
Use 2.5.1 or the multiple_maps branch

**Comment by thomashrabe** [comment]
Yes, but how do I specify a specific branch?

**Comment by wf9a5m75** [comment]
The stackoverflow page explains exactly.
