### ISSUE TITLE
Ground overlay not working properly @2.3.6

### ISSUE THREAD

**Issue by UlisesCeca** [mapsplugin/cordova-plugin-googlemaps#2563]
Hello,

I am making an App using cordova 7.1.0 (I can't use other cordova version). So I am using the version 2.3.6 of this plugin because with it won't compile with newer versions.

The thing is that when I add a GroundOverlay it's not adding as it's supposed to.

With Cordova 7.1.0 and version 2.3.6 (these are the versions I need) it looks like this:

![1](https://user-images.githubusercontent.com/23300072/53285154-bc2c0b00-375d-11e9-833c-05961f062e3b.jpg)

But in Cordova 8.1.2 and version 2.4.6 it looks like this (this is how it's supposed to look like):

![2](https://user-images.githubusercontent.com/23300072/53285170-ebdb1300-375d-11e9-9d86-848377a631bc.jpg)

The error that I get when buildingif I install version 2.4.6 of plugin is:

`Execution failed for task ':transformClassesWithDexForDebug'. > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v13/view/DragAndDropPermissionsCompat;`

Any ideas on what's going on?

Thanks.

**Comment by wf9a5m75** [comment]
Please search the error message on Google before asking me. I'm not your free help service.

https://forum.ionicframework.com/t/help-with-build-failed-android-ionic/94396/22


I don't support old versions. Current latest version is v2.5.1
