### ISSUE TITLE
setLatLngBoundsForCameraTarget

### ISSUE THREAD

**Issue by litasales02** [mapsplugin/cordova-plugin-googlemaps#2564]
how can i use setLatLngBoundsForCameraTarget
@description
Embed native Google Maps views into your app. This version is aimed for ionic v4/beta. You need to use [cordova-plugin-googlemaps

@
2.4.1](https://www.npmjs.com/package/cordova-plugin-googlemaps) with this plugin.

**Comment by wf9a5m75** [comment]
Array of lat,lng.

By the way, I support only the latest version. Not for older versions.
