### ISSUE TITLE
Hi, Please help! I've been struggling with this for a while now, I've tried everything to fix this

### ISSUE THREAD

**Issue by Hlaphoneo** [mapsplugin/cordova-plugin-googlemaps#2566]
-     "@ionic-native/google-maps": "^4.20.0",
    "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",

The map loads for the first time navigating to this component, on when I pop back and navigate to the same page the map does not load.

`import { Component, ViewChild, NgZone  } from '@angular/core';
import { IonicPage, NavController, NavParams, PopoverController } from 'ionic-angular';
import { SocketService } from '../../../services/socket.service';

import { Platform } from "ionic-angular";

import * as moment from 'moment';
import { PermitBuyPage } from '../permit-buy/permit-buy';
import { GoogleMapPage } from '../../google-map/google-map';
import { NavigatorService } from '../../../services/navigation.service';
import { AdventurePage } from '../adventure/adventure';
import { LaunchNavigator } from '@ionic-native/launch-navigator';

import {
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  GoogleMapOptions,
  CameraPosition,
  MarkerOptions,
  Marker,
  Environment
} from '@ionic-native/google-maps';

@Component({
  selector: 'page-site',
  templateUrl: 'site.html',
})
export class SitePage {

  @ViewChild('forecastroller') scroll: any;
  @ViewChild('content') content: any;

 
  constructor(
    public navParams    : NavParams,
    private nav         : NavigatorService,
    private websocket   : SocketService,
    private launchNavigator : LaunchNavigator,
    public zone         : NgZone,
    private platform    : Platform,
    public popoverCtrl  : PopoverController
  ) {
    this.init()
  }

  private async init() : Promise<void> {
    try {
      this.pageLoading = true;
      this.siteDetails = await this.websocket.getSiteDetails(this.site.id);
      
      this.siteActivities = await this.websocket.getSiteActivities(this.site.id);

      this.pageLoading = false;
    } catch (error) {
      console.log(error);
      
      error.message  == null ? this.errorMessage = "Sorry! something went wrong!" : this.errorMessage = "Mm! there seems to a problem connecting to our server."
      this.pageLoading = false;
    }
  }

  mapElement;
  map: GoogleMap;

  ionViewDidEnter() { 
    this.loadMap();
  }

  ionViewWillLeave() { 
    console.log("removvvvviiinnng map");
    console.log(this.map);
    
    this.map.remove();
    this.map.destroy
    
  }

  async loadMap() {
    this.platform.ready().then(async () => {

    if(Environment) {
      try {
        Environment.setEnv({
          'API_KEY_FOR_BROWSER_RELEASE': 'xxxxxxx',
          'API_KEY_FOR_BROWSER_DEBUG': 'xxxxxxxxx'
        });
      } catch (error) {
        
      }

    }

    let mapOptions: GoogleMapOptions = {
      camera: {
         target: {
          lat: 12.2255,
          lng: 36.366
         },
         zoom: 14,
         tilt: 30
       },
       gestures: {
        scroll: true,
        tilt: true,
        rotate: false,
        zoom: true
    }
    };

        this.mapElement = document.getElementById('test');

        console.log(this.mapElement);
        

        try {
       
          this.map = await GoogleMaps.create(this.mapElement, mapOptions);   

          if(this.map) {
            this.map.addKmlOverlay({
              url : "https://doc-10-ak-docs.googleusercontent.com/docs/securesc/noa72o067k58v6m4h2l88p412rn0cd4m/07djh8l0lnsr17epj9furq1v2ue9n0sv/1551103200000/18322926786011980654/18322926786011980654/1LcmbHTZUVzxaKf2_Niwnpyo3qjVbdv_Z?e=download"
            }).then(()=>{

            }).catch((error)=>{
              console.log(error);
            })
          }
        } catch (error) {
          console.log(error); 
        }
    })
  }`

**Comment by hobbydevs** [comment]
how did you solve your issue?

**Comment by Hlaphoneo** [comment]
Hobbydevs yes I did manage to fix it. Are you having the same issue ?
