### ISSUE TITLE
setMyLocationEnabled(false) does not disable blue dot

### ISSUE THREAD

**Issue by diegomendespt** [mapsplugin/cordova-plugin-googlemaps#2567]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

```
cordova-plugin-googlemaps: 2.5.0

@ionic-native/core : 4.3.2
@ionic-native/google-maps : ^4.20.0
```

I start the map with
`controls: {
        compass: false,
        myLocationButton: false,
        indoorPicker: false,
        zoom: false
      }`

then later on I turn my location with `setMyLocationEnabled(true)`
everything works as expected (if it has location permission places the blue dot on the map)

but then I want to turn it off (remove the bue dot), and from what I understood it would be a simple `setMyLocationEnabled(false)` but it does not seem to work

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by diegomendespt** [comment]
Here it is:
https://github.com/diegomendespt/testGoogleMapsMyLocation

**Comment by wf9a5m75** [comment]
Thanks. I had no time to check it. I will check it tomorrow.

**Comment by wf9a5m75** [comment]
Please reinstall v2.5.2

**Comment by diegomendespt** [comment]
With v2.5.2 `setMyLocationEnabled(false)` is working correctly.
Thanks.
