### ISSUE TITLE
Conflict with cordova-plugin-statusbar (iOS)

### ISSUE THREAD

**Issue by ataylor32** [mapsplugin/cordova-plugin-googlemaps#2568]
When using both cordova-plugin-statusbar and cordova-plugin-googlemaps, part of the screen can't be tapped. Here is a demo:

![demo](https://user-images.githubusercontent.com/1054222/53527167-747dea00-3aa3-11e9-8037-6a77b642f166.gif)

I recorded the above demo with the stable version of cordova-plugin-googlemaps. With the development version, the same problem occurs, but the part of the screen that can't be tapped is higher up.

To reproduce this, you just need to create two files (config.xml and www/index.html) and run some commands. Here are the instructions:

Create the config.xml file with this content (same as Cordova's default, but added the three `preference` tags):

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <preference name="DisallowOverscroll" value="true" />
    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="StatusBarBackgroundColor" value="#000000" />
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>
```

Create the www/index.html file with this content:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Demo</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" rel="stylesheet">
    <style>
      html,
      body {
        overflow: hidden;
        position: relative;
        height: 100%;
      }

      html {
        touch-action: manipulation;
      }

      body {
        display: grid;
        grid-template-columns: repeat(auto-fill, 2.5vw);
      }

      div {
        width: 2.5vw;
        height: 2.5vw;
        background-color: #0d47a1;
        border: 1px solid #000;
        box-sizing: border-box;
      }

      .active {
        background-color: #ef9a9a;
      }
    </style>
  </head>
  <body>
    <script src="cordova.js"></script>
    <script>
      function toggleColor(e) {
        e.target.classList.toggle('active');
      }

      for (let i = 1; i <= 3000; i++) {
        let div = document.createElement('div');
        div.onclick = toggleColor;
        document.body.appendChild(div);
      }
    </script>
  </body>
</html>
```

Run the following commands in the same directory as config.xml:

```
cordova platform add ios
cordova plugin add cordova-plugin-statusbar
cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_IOS="..."
cordova emulate ios --target="iPhone-8-Plus, 12.1" --buildFlag="-UseModernBuildSystem=0"
```

**Comment by wf9a5m75** [comment]
I only support of this plugin. Conflicting with other plugins are not supported. Please choose one plugin.

**Comment by ataylor32** [comment]
I understand where you're coming from. I would appreciate it if you would consider it anyway, though, since cordova-plugin-statusbar is a plugin that is both official and widely used. I know I'm not the only one who cares about this since this has been reported before (see #2409 and #2055). But if you still decide to not support it, I would suggest adding something to your documentation letting people know about this issue. I would try to fix this myself and submit a pull request, but I think this is written in Objective-C, which I don't know. Thanks for your time!

**Comment by wf9a5m75** [comment]
Please try v2.5.2

**Comment by ataylor32** [comment]
In 2.5.2, the same problem occurs, but the part of the screen that can't be tapped is higher up.

**Comment by wf9a5m75** [comment]
Ok, please send a pull request. Otherwise remove the `cordova-plugin-statusbar`.

**Comment by ataylor32** [comment]
Like I said before, I would try to fix this myself and submit a pull request, but I think this is written in Objective-C, which I don't know. Thanks for trying!

**Comment by wf9a5m75** [comment]
That's why I wrote "Otherwise remove the `cordova-plugin-statusbar`."

**Comment by ppetree** [comment]
Just my 2 cents worth... I'm using the status bar plugin and on iOS 9-11 this isn't an issue.  I've not tried it on 12 yet.

**Comment by hrhosni** [comment]
If I'm not mistaken you don't necessarily have to remove `cordova-plugin-statusbar`. You can keep it but set `StatusBarOverlaysWebView` to `true` in your config.xml.
Obviously that can mean the status bar overlaying some critical UI. If that's the case for you, perhaps you can consider shifting your whole UI down by 20px (height of the status bar) on iOS?

Another option would be to hide the statusbar completely with StatusBar.hide(). 

I realize that both of the above options are suboptimal. But I only suggest them as a quick workaround until the issue is fully resolved.

Note: Not only is the upper part of the screen rendered unclickable because of this bug (the one shown in the gif), but any native UI also gets shifted. 
e.g. I use a native datetime picker in my app and its "Cancel" and "Done" buttons become unclickable in their shown position. You have to click about 20px below them.

**Comment by ppetree** [comment]
I believe the iOS guidelines say to not show the status bar on phones but do show it on tablets.

But that still doesn’t address the 20px problem.  If my hunch is correct, I don’t believe the offset problem arises until after the map is shown the first time. I’ll know more this weekend (off today).

**Comment by ggiordan** [comment]
@wf9a5m75  First, I really appreciate your work on this plugin, it is awesome!
I think ended up tripping on what @ppetree  is talking about. 
I _THINK_ (you are the expert here) that the solution may be as simple as always adding in the inset.top when dealing with iOS 11 and up?
I _THINK_ this accounts for notches (and other safe areas) of arbitrary sizes.

**Comment by ppetree** [comment]
I just did a bunch of reading and I think @ggiordan may be on to something... least wise this seems pretty logical.

**Comment by ggiordan** [comment]
I just submitted a PR on this.  I tried it with a variety of devices, seems to be ok.

**Comment by wf9a5m75** [comment]
@ggiordan I tested your PR with @ataylor32 's code, but there are top two lines are not clickable.

**Comment by wf9a5m75** [comment]
Fixed at least ios8 plus 
<img width="526" alt="screen shot 2019-03-05 at 12 34 24 am" src="https://user-images.githubusercontent.com/167831/53791500-764e1000-3ede-11e9-98de-58a3d724357b.png">

**Comment by ggiordan** [comment]
@wf9a5m75 good input, which device still couldn't click?

I was using my app to do the testing, which does seem pretty happy.  But, I agree, @ataylor32 app is better, it's much less subjective.  I'll use his app to redo my testing before resubmitting the PR.

Also, after sleeping on this I realized 2 things
1) My PR leaks
2) I think we should always use the inset value, not just when it's > 20

I'll report back in a bit.

**Comment by ggiordan** [comment]
@ataylor32 , When I test with your code on the X, I'm getting alot of space between the top row of blocks and the notch... I messed with it some, but could not get it to go any higher, can you try?
I did try changing the meta tag to this:
`<meta name="viewport" content="initial-scale=1,width=device-width,height=device-height,viewport-fit=cover">
`![image](https://user-images.githubusercontent.com/3812056/53805567-7a971f00-3f18-11e9-9b87-d70eee61a953.png)

I did try my updated PR using both my app and @ataylor32 's and don't see any issues, I tested with the X, 6s, 8Plus and XE

**Comment by wf9a5m75** [comment]
@ggiordan Yes, your code works if the app has `viewport-fit=cover`, and the app does not have `cordova-plugin-statusbar` on above iOS11.

However if the device is iOS10, no `viewport-fit=cover` and the app has `cordova-plugin-statusbar`, you can not click top 2 lines.

![screen shot 2019-03-05 at 10 39 36 am](https://user-images.githubusercontent.com/167831/53828611-fef69b80-3f32-11e9-8300-95ef372542dd.png)

Because the `cordova-plugin-statusbar` inserts small window above the browser.

![screen shot 2019-03-05 at 10 40 42 am](https://user-images.githubusercontent.com/167831/53828660-251c3b80-3f33-11e9-8c55-29a2ebbfcc32.png)

```
  CGPoint subviewPoint;
  if (@available(iOS 11.0, *)) {
    UIEdgeInsets inset = [[UIApplication sharedApplication] delegate].window.safeAreaInsets;
    // Fix touch issue for iPhone X and above devices
    subviewPoint = CGPointMake(browserClickPoint.x, browserClickPoint.y + inset.top);
  } else {
    subviewPoint = CGPointMake(browserClickPoint.x, browserClickPoint.y );
  }
```

The height of the status bar window is the same as `inset.top`.
That's why inaccurate.

**Comment by wf9a5m75** [comment]
```
CGPoint subviewPoint = CGPointMake(browserClickPoint.x, browserClickPoint.y + self.webView.frame.origin.y);
  
```

It seems this code works perfectly. 
![screen shot 2019-03-05 at 10 45 43 am](https://user-images.githubusercontent.com/167831/53829333-c2c43a80-3f34-11e9-8afa-68ccd9e55aed.png)

**with cordova-plugin-statusbar**
![screen shot 2019-03-05 at 10 48 24 am](https://user-images.githubusercontent.com/167831/53829339-c657c180-3f34-11e9-88c5-286fd4bfe4e1.png)


**without cordova-plugin-statusbar**
![screen shot 2019-03-05 at 10 49 45 am](https://user-images.githubusercontent.com/167831/53829340-c6f05800-3f34-11e9-821e-a02746b0bc51.png)

**Comment by ggiordan** [comment]
Nicely done @wf9a5m75 !
Seems to work perfectly on my app and in the test app.
Do I need to do anything w/my PR?  or will it just die off?

Thanks so much for your time and help!
