### ISSUE TITLE
Cannot run Google Map in iOS

### ISSUE THREAD

**Issue by minimedj** [mapsplugin/cordova-plugin-googlemaps#2575]
Hi, I cannot make it working on iOS.
I did `cd platforms/ios && pod install`
I see grey map with Google logo on it. Keys are OK.
In log I see the following messages:

```
2019-03-11 18:22:10.028331+0100 Elis[1273:466060] ERROR: Plugin 'map_0_74670188322' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2019-03-11 18:22:10.028458+0100 Elis[1273:466060] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","map_0_74670188322","detachFromWebView",[]]
2019-03-11 18:22:10.204654+0100 Elis[1273:466060] ERROR: Plugin 'map_0_74670188322' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2019-03-11 18:22:10.204789+0100 Elis[1273:466060] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","map_0_74670188322","attachToWebView",[]]
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/77AFC220-9D79-42EF-89ED-5D2F50A456F6/Elis.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/77AFC220-9D79-42EF-89ED-5D2F50A456F6/Elis.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/77AFC220-9D79-42EF-89ED-5D2F50A456F6/Elis.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
```

Any idea?

**Comment by wf9a5m75** [comment]
Please share your project files on github repository.

**Comment by minimedj** [comment]
@wf9a5m75 Would you like to see just Xcode files?

**Comment by wf9a5m75** [comment]
No. You need to share your project files everything on to github repository, `src (if ionic), www, res, config.xml, package.json`.

Otherwise, please debug by yourself.

**Comment by minimedj** [comment]
@wf9a5m75 So, I figured out that `cordova-plugin-googlemaps` doesn't work well with React. More about this problem here #2487.

It the problem exists, please consider to include such information to README. It could save somebody's time in the future.

**Comment by wf9a5m75** [comment]
If you share your project files on GitHub repository, I answered this plugin does not work with React.js so far.

**Comment by minimedj** [comment]
> If you share your project files on GitHub repository, I answered this plugin does not work with React.js so far.

@wf9a5m75 It works fine with React for me so far. If there are known issues with React, please let me know so I will check it for you.

**Comment by minimedj** [comment]
@wf9a5m75 So, now it works with React for me. It was my lack of experience with `pod` software and API keys proper configurations.

Please tell me what is the problem with react, so I can test it for you.

**Comment by wf9a5m75** [comment]
Congrats. I don't know the reason of the problem with React.js. Because I don't have experienced React.js well, and nobody share the project with me.

Please check https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2487 for the details of previous inspection.
