### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by kodeine** [mapsplugin/cordova-plugin-googlemaps#2576]
Hello, 
i'm on the latest versions and received this error report from play store.

![image](https://user-images.githubusercontent.com/8620059/54247944-4079de80-4511-11e9-9881-6be82f801363.png)
![image](https://user-images.githubusercontent.com/8620059/54247949-45d72900-4511-11e9-803c-83aeb5aea580.png)

**Comment by wf9a5m75** [comment]
Upgrade the maps plugin, please. I don't support old versions.
