### ISSUE TITLE
Issue on ionic header iPhone X

### ISSUE THREAD

**Issue by LuisValle** [mapsplugin/cordova-plugin-googlemaps#2578]
After update 2.5.2 click not works on iPhone X, iPhone XR and iPhone XR 
<img width="373" alt="Screen Shot 2019-03-18 at 10 29 43 AM" src="https://user-images.githubusercontent.com/19562044/54546173-c7dbad80-4968-11e9-8449-344b8dca93ea.png">
Before, I´was using 2.3.6 and it was working , if i downgrade it, icon click works again

**Comment by wf9a5m75** [comment]
Use the multiple_maps branch.

**Comment by wf9a5m75** [comment]
As I said, "Use the multiple_maps branch."
