### ISSUE TITLE
Camera going crazy when setting a displacement offset

### ISSUE THREAD

**Issue by UlisesCeca** [mapsplugin/cordova-plugin-googlemaps#2580]
Hello,

as you can see in the video I'm linking next, I am trying to set an offset displacement to my marker to put it in a more down place: https://youtu.be/ctz6on25Byk

As you can see, the camera is going crazy when I do this. Also I am calling the function that does this every half a second so this is a potential cause but I am not sure.

My code is the following:

```
private async calculateCenterOffset(latlng: ILatLng, offsetyIn: number): Promise<any> {
    return new Promise(async (resolve, reject) => {
      this.map.setCameraZoom(100);
      return this.map.fromLatLngToPoint(latlng).then(res => {
        let offsety = (window.screen.availHeight * offsetyIn * -1);
        return this.map.fromPointToLatLng([res[0], res[1] + offsety]).then(res => {
          resolve(res);
        })
      })
    });
  }

```

And I call it like this:

`this.map.setCameraTarget(await this.calculateCenterOffset(googlePosition, NAVIGATING_POSITION_OFFSET));`

Is there anything I'm doing wrong which causes this effect? I am testing it on iOS, on Android it happens too but it doesn't look so awkward, it just shakes a very bit (which would be good to fix too)

Is it because it's an async function or because I'm calling it a lot of times and very fast?

Thanks.

**Comment by wf9a5m75** [comment]
> Is it because it's an async function or because I'm calling it a lot of times and very fast?

Yes.

All source code is open. I received you check the internal code at least JS part.

**Comment by wf9a5m75** [comment]
Also `this.map.setCameraZoom(100);` is storage.

**Comment by UlisesCeca** [comment]
Sorry I don't know what you mean in your two posts 😔
