### ISSUE TITLE
Error: Can't resolve all parameters for GoogleMap: (?, ?, ?) ionic 4

### ISSUE THREAD

**Issue by Timn97** [mapsplugin/cordova-plugin-googlemaps#2582]
I used your plugin like home page in repository (https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4) , when i delete GoogleMap in app.module.ts, browser send error NullInjectorError: No provider for GoogleMap!

So I add it agian in app.module.ts, browser send me error Can't resolve all parameters for GoogleMap: (?, ?, ?). 

How to fix it ?

**Comment by wf9a5m75** [comment]
I can't understand your situation. Please share your project files (all files) on GitHub repository.

**Comment by Timn97** [comment]
@wf9a5m75 
in this case, my project is in https://github.com/hieunguyenvanLC/FacingCapstone/tree/thangdp/FPS_Mobile_App/FPS

my problem in scr/app/screens/order/order.page.ts + order.html.ts

my ionic version: 4.10.3
cordova version : 8.1.2

**Comment by UlisesCeca** [comment]
This error is usually because you have a circular dependency.

This means that you're importing a 2 providers into the same page and both of those providers are using another provider which is the same.

For example you import provider A and B to a page and then both providers A and B and using the same dependency C.

**Comment by Timn97** [comment]
oh, I will check base on your advice, I will reply soon.

Thank you very much !

**Comment by Timn97** [comment]
Tks so much, it worked ! But now I have a new problem with the real device. Should I create a new issue ?

**Comment by UlisesCeca** [comment]
I guess you should close this issue and open another one
