### ISSUE TITLE
Warning after upgrade to cordova-ios@5.0.0

### ISSUE THREAD

**Issue by Mathieu-Castets** [mapsplugin/cordova-plugin-googlemaps#2583]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ X ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ X ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-googlemaps 2.5.4-beta-20190320-1419 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 4.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.1.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**
I am using multiple_maps branch.

After upgrading `cordova-ios` to `5.0.0` and when running `cordova prepare`, I get the following warning:

```
Installing "cordova-plugin-googlemaps" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
```

**Comment by wf9a5m75** [comment]
Thank you for sharing the information, but "Warning" is just a warning. Not error.

In order to keep backward compatibility, I will left it for a while.
