### ISSUE TITLE
Ability to switch between Native & Javascript modes

### ISSUE THREAD

**Issue by NicksonYap** [mapsplugin/cordova-plugin-googlemaps#2584]
**Please tell us your new feature idea**

Switch between Native SDK & Javascript SDK

**Why do you need it?**

In some situations, Javscript SDK is better (no scroll jerk, minor differences)
Although Native supports offline and performs better

**How helps other people?**

This way, we get to choose the mode optimal mode to use in certain pages, depending on situations

**Comment by wf9a5m75** [comment]
No plan to implement.

**Comment by adamduren** [comment]
Not sure how hard it would be to implement but would be great in some cases to choose the JS vs Native SDK. I have a couple of pages that are full map views. In this the Native SDK makes the most sense. However I have a location preview on a services page similar to what you would find on Airbnb, when scrolling there is a noticeable delay from the Native SDK tracking the JS webview. Ideally here I could use the JS SDK. Not a big deal but it's definitely noticeable and get worse the quicker the scroll action occurs.

**Comment by adamduren** [comment]
@wf9a5m75 where can we find the view syncing code? I'm impressed overall with what the library accomplishes but would also be interested to see if there is room for improvement in this area.

**Comment by NicksonYap** [comment]
Yes, I decided to just switch to JS map due to scrolling issue

I've created my own component, and wrote duplicate code (one for JS one for this plugin) or each feature

And then a boolean to switch between the two libraries

It's more work, but more reliable than depending on this repo
