### ISSUE TITLE
iOS - Geocoder null result

### ISSUE THREAD

**Issue by themrzmaster** [mapsplugin/cordova-plugin-googlemaps#2588]
When i try to use reverse Geocoder.geocode on iOS i get no result. ( result.length == 0 )
on Android it works great.
ive already checked the latitude and longitude and they look good.

iOS: 12
Cordova version: 8.1.1
cordova-plugin-googlemap : 2.5.2

my XCode console gives this output when i call the function Geocoder.geocode:

 

>  [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C16.1:2][0x153e66460] get output frames failed, state 8196

is it some kind of request permission? should i allow googlemaps domain?

**Comment by wf9a5m75** [comment]
Result of reverse geocoding is depends on Google, not this plugin. Please ask to Google.

**Comment by themrzmaster** [comment]
> Result of reverse geocoding is depends on Google, not this plugin. Please ask to Google.

but as i mentioned the results are different on iOS/Android. It doesnt make sense to be googles issue if the same query on android works as expected

**Comment by wf9a5m75** [comment]
If you doubt, please debug the code by yourself using xcode. All source code is fully open.
