### ISSUE TITLE
Map div becomes white after some navigation to another pages

### ISSUE THREAD

**Issue by tatsumibruno** [mapsplugin/cordova-plugin-googlemaps#2593]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.5.3 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "^4.13.0"
@ionic-native/google-maps : "^4.13.0"
```

**Current behavior:**
Sometimes, after some navigation between pages, the map div becomes blank. Then, if i go to any page (that uses gmaps), it also still blank. I try use setDiv() and then setDiv(this.mapElement). But accours an error when call setDiv without passing argument.

**Expected behavior:**
If called create from GoogleMaps in any page, the lib must inits correctly.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
N/A
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
It depends on your code. Please share your project files on GitHub repository.

**Comment by tatsumibruno** [comment]
Here's the code that i call every time i navigate to any page that use maps (executed in ionViewDidLoad):

```
private _map: GoogleMap;
create(mapOptions?: MapOptions): MapEvents {
        if (this._map)
            this._map.remove();

        let options: GoogleMapOptions = this.getDefaultMapOptions();

        if (mapOptions) {
            if (mapOptions.disable) {
                options.gestures = { rotate: false, zoom: false, scroll: false, tilt: false };
                options.controls = { compass: false, myLocationButton: false, myLocation: false };
            }
        }

        this._map = GoogleMaps.create(this.mapElement.nativeElement, options);
}
```

**Comment by wf9a5m75** [comment]
I said  "Please share your project files on GitHub repository."

**Comment by tatsumibruno** [comment]
Sorry, i cant share the project files. Its a private project. I will write some sample project and simulate the error, then i share it. Ok?

**Comment by battika** [comment]
That is the right thing to do

**Comment by tatsumibruno** [comment]
@wf9a5m75 
Here's the project that contains the mentioned situation. If you navigate between some page and back to first one, the map div becomes blank. If you call setDiv() and setDiv([ELEMENT]), throws an error: "vendor.js:1823 ERROR Error: DIV is too small. Must be bigger than 100x100.".

Thanks for helping.

**Comment by wf9a5m75** [comment]
Ionic-native/google-maps plugin manages attaching/detaching map view automatically. Don't do yourself except you are an expert.

**Comment by tatsumibruno** [comment]
The setDiv() that i said before, is not the original code. If you remove this code, the map will become blank when use bavk buttob

**Comment by wf9a5m75** [comment]
If you want to control the timing by yourself, check the code of ionic-native/google-maps how to control.

"ERROR Error: DIV is too small. Must be bigger than 100x100." is not a bug , it's a message that you tried to attach in wrong timing.

**Comment by tatsumibruno** [comment]
The code "setDiv()" was just a try to make map appears again. I want to remove this line. The problem is, when i came back, the map is blank.

**Comment by tatsumibruno** [comment]
I just made a change, removing the setDiv(). Now you can see the blank map when navigate to some page and go back to first one.

**Comment by wf9a5m75** [comment]
As I said, you need to read the code of ionic-native/google-maps.

**Comment by tatsumibruno** [comment]
Like i said before. The setDiv() is not a problem. My intention isnt control the render timing, that was just a try to resolve the real problem (Blank Map when navigate back).

**Comment by wf9a5m75** [comment]
Since you use this plug-in in provider, you must control the timing by yourself.
