### ISSUE TITLE
Polygon is visible on Android

### ISSUE THREAD

**Issue by TdoubleG** [mapsplugin/cordova-plugin-googlemaps#2595]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-admob-sdk 0.22.0 "AdMob SDK"
cordova-plugin-admob-free 0.25.0 "Cordova AdMob Plugin"
cordova-plugin-appcenter-crashes 0.2.2 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.2.2 "App Center shared code for Cordova"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-mauron85-background-geolocation 3.0.0-alpha.50 "CDVBackgroundGeolocation"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 5.2.11
@ionic-native/google-maps : 4.21.0
```

**Current behavior:**

The polygon is still visible on android, despite I set the polygon visibility to false. Even when I hardcode the visibility in Java it doesn't work.
This works on iOS

**Expected behavior:**

The polygon shouldn't be visible even in Android.

**Screen capture or video record:**

![Screenshot_2019-04-09-09-12-39](https://user-images.githubusercontent.com/20188615/55780225-c6089400-5aa7-11e9-9885-69eb74500a88.png)

**Related code, data or error log (please format your code or data):**

```
 if (!this.polygon) {
          this.map.addPolygon({
            'points': polyPoints,
            'strokeColor': '#0083ff',
            'strokeWidth': 5,
            'fillColor': '#3794e0',
            'visible': false
          }).then((polygon: Polygon) => {
            this.polygon = polygon;
            this.polygon.setVisible(false);
          });
        }
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Please send a pull request

**Comment by adappter** [comment]
there is no PR. I was asking for help, because even changing the native code, didn't hide the polygon

**Comment by adappter** [comment]
Found the place of the Code. Created a PR #2600

**Comment by wf9a5m75** [comment]
(log) PR #2600 has merged to the multiple_maps branch.
