### ISSUE TITLE
Disable camera movement when clicking a marker

### ISSUE THREAD

**Issue by UlisesCeca** [mapsplugin/cordova-plugin-googlemaps#2597]
Hello, currently when I click on a marker, the camera is automatically animated to go to that marker.

I wanna disable that the camera moves automatically and move it myself since I wanna add an offset to the movement.

Is this possible?

Thanks.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Marker/README.md#disable-auto-pan
