### ISSUE TITLE
`fromLatLngToPoint` is not executing in background

### ISSUE THREAD

**Issue by adappter** [mapsplugin/cordova-plugin-googlemaps#2601]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-admob-sdk 0.22.0 "AdMob SDK"
cordova-plugin-admob-free 0.25.0 "Cordova AdMob Plugin"
cordova-plugin-appcenter-crashes 0.2.2 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.2.2 "App Center shared code for Cordova"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-mauron85-background-geolocation 3.0.0-alpha.50 "CDVBackgroundGeolocation"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 5.2.11
@ionic-native/google-maps : 4.21.0
```

**Current behavior:**

`fromLatLngToPoint` is not executing in background.
I need this when the app is in background to rotate the polygon. It works all fine when the app is in foreground.

I also checked the `MyPlugin.java` file with the debugger, but it's not stopping there. Only after putting the app in the foreground again, the debugger stops with the correct action.

Even `Map.js` is not stopping.

**Expected behavior:**

`fromLatLngToPoint` should executing in background

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
 private rotatePolygon(polygon: Polygon, latLngArray: ILatLng[], angle: number) {
    const pointsPromise = [];

    latLngArray.forEach((latLng: ILatLng) => {
      const point = this.map.fromLatLngToPoint(latLng);
      pointsPromise.push(point);
    });

    const coordsPromise = [];
    Promise.all(pointsPromise).then((results: any[]) => {
      this.map.fromLatLngToPoint(latLngArray[0]).then((originResult: any[]) => {
        const originPoint = {x: originResult[0], y: originResult[1]};
        results.forEach((points: number[]) => {
          const point = {x: points[0], y: points[1]};
          const rotatePoints = this.rotatePoint(point, originPoint, angle);
          const rotatedLatLng = this.map.fromPointToLatLng([rotatePoints.x, rotatePoints.y]);
          coordsPromise.push(rotatedLatLng);
        });

        Promise.all(coordsPromise).then((result: ILatLng[]) => {
          console.log("result:", result);
          polygon.setPoints(result);
        });
      });
    });
  }
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
All Google Maps code runs on UI thread, thus the code does not work in background. It's specification of Google. Not bug
