### ISSUE TITLE
conflict with OneSignal-Cordova-SDK

### ISSUE THREAD

**Issue by doonfrs** [mapsplugin/cordova-plugin-googlemaps#2604]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
[root@code mobile-user]# cordova plugin list
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.6.0 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core": "^4.4.0"
"@ionic-native/google-maps": "^4.15.1" : 
```

**Current behavior:**
Can not build for android (tried with cordova android 7 and 8)
I am getting GOOGLE_MAPS_ANDROID_API_KEY not provided, while I added preferences values to config.xml
    <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="***" />
    <preference name="GOOGLE_MAPS_IOS_API_KEY" value="***" />
 
**Expected behavior:**
To build android apk successfully

**Related code, data or error log (please format your code or data):**
BUILD FAILED in 10s
/root/projects/busvibe/mobile-user/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: /root/projects/busvibe/mobile-user/platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/root/projects/busvibe/mobile-user/platforms/android/app/src/main/AndroidManifest.xml:12:66-112 Error:
        Attribute meta-data#com.google.android.geo.API_KEY@value at AndroidManifest.xml:12:66-112 requires a placeholder substitution but no value for <GOOGLE_MAPS_ANDROID_API_KEY> is provided.
/root/projects/busvibe/mobile-user/platforms/android/app/src/main/AndroidManifest.xml Error:
        Validation failed, exiting

FAILURE: Build failed with an exception.

```

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#api-key-android-and-ios-platforms

**Comment by wf9a5m75** [comment]
please share your project files on github.

**Comment by doonfrs** [comment]
I can find now the problem happens with onesignal cordova plugin, problem solved after removing this plugin.

**Comment by doonfrs** [comment]
I filed the issue on onesignal plugin https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/503

**Comment by wf9a5m75** [comment]
It seems the problems occurs because of `OneSignal-Cordova-SDK` throws all `manifestPlaceholders` values.
I changed approaching way in this plugin. As far as I test, this way should be fine.

**Comment by battika** [comment]
Thanks, it seems to be working now at least on my own system using 
   
"cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#a5155cd",

**Comment by wf9a5m75** [comment]
>by the way I am using cordova-ios@5.0.0 but it seems IOS SDK v2.7 is being installed for me for some reason

@battika Because your `cordova-ios` is old. You have to upgrade to `cordova-ios@5.0.1`, and reinstall the maps plugin.

**Comment by battika** [comment]
Trying it now Sir, thanks for the hint

**Comment by battika** [comment]
Hello, I removed the entire platform folder and added only the following plugins: 
"git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#a5155cd" and the OneSignal plugin.
After building for Cordova-IOS@5.0.1 my PodFile looks like this:
```
# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '9.0'

target 'GreenGo' do
        project 'GreenGo.xcodeproj'
        pod 'GoogleMaps', '~> 2.7.0'
        pod 'OneSignal', '2.9.4'
end
```

The command `ionic info `reports the following
```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 5.0.1
   Cordova Plugins       : no whitelisted plugins (2 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/battika/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v8.12.0 (/usr/local/Cellar/node@8/8.12.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by wf9a5m75** [comment]
`cordova (Cordova CLI) : 8.1.2 ` should be `cordova (Cordova CLI) : 9.0.0 `

**Comment by wf9a5m75** [comment]
Since installation is the role of cordova system, please don't clam to me.
Cordova has only poor installation system.
You can update CocoaPod by command line.

**Comment by battika** [comment]
Sure, thank you I am just trying to find a combination where OneSignal and GoogleMaps plugins will work for both IOS and Android for **production** builds. Once I find the combination I should let everyone know.

**Comment by battika** [comment]
Masashi, when I use cordova-cli@9.0.0, cordova-ios@5.0.1 with the platform directory removed (clean run) I get the following message upon running 

`$ ionic "cordova" "build" "--release" "--device" "ios" "--" "--buildFlag=-UseModernBuildSystem=0"
`

 ```
Installing "cordova-plugin-googlemaps" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
cordova-plugin-googlemaps depends on GoogleMaps@~> 2.7.0, which conflicts with another plugin. GoogleMaps@~> 3.1.0 is already installed and was not overwritten.
Running command: pod install --verbose
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    23 54.7M   23 13.0M    0     0  24.8M      0  0:00:02 --:--:--  0:00:02 24.8M
    77 54.7M   77 42.3M    0     0  27.7M      0  0:00:01  0:00:01 --:--:-- 27.7M
   100 54.7M  100 54.7M    0     0  27.9M      0  0:00:01  0:00:01 --:--:-- 27.9M
```

**Comment by wf9a5m75** [comment]
Yes, no problem.

**Comment by wf9a5m75** [comment]
Since `cordova-ios@4.4` or below specifies `platform :ios, '8.0'` in `platforms/ios/Podfile`, you can not use `GoogleMaps@3.x` Pod. Because Google drops supports.

However `cordova-ios@4.4` or below versions are still active in many projects. That's why I specified two ways.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a5155cd34f0ea02b2ee4d37177504a4bdb5d5cca/plugin.xml#L474-L482

```xml
 <framework src="GoogleMaps" type="podspec" spec="~> 2.7.0" />
```

works for `cordova-ios@4.4` or below versions.

```xml
    <podspec>
      <config>
        <source url="https://github.com/CocoaPods/Specs.git"/>
      </config>
      <pods>
        <pod name="GoogleMaps" spec="~> 3.1.0"/>
      </pods>
    </podspec>
```

works for `cordova-ios@5.x` with `cordova-cli@9`.

--------

>cordova-plugin-googlemaps depends on GoogleMaps@~> 2.7.0, which conflicts with another plugin. GoogleMaps@~> 3.1.0 is already installed and was not overwritten.

As the message, `GoogleMaps@~> 3.1.0 is already`.

**Comment by wf9a5m75** [comment]
v2.6.1 has been released.

**Comment by pcsantana** [comment]
Just for info if anyone need, I was having the same issue even following the instructions here. 

```
Installing "cordova-plugin-googlemaps" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
cordova-plugin-googlemaps depends on GoogleMaps@~> 2.7.0, which conflicts with another plugin. GoogleMaps@~> 3.1.0 is already installed and was not overwritten.
Running command: pod install --verbose
Failed to install 'cordova-plugin-googlemaps': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Projetos/appautonomo/src/node_modules/cordova-common/src/superspawn.js:125:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
pod: Command failed with exit code 31
```
Then I tried to run `pod install --verbose` and the console log:
```
$ pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Parana Servicos`: (``)

Finding Podfile changes
  A GoogleMaps
  - AeroGear-Push

Resolving dependencies of `Podfile`
[!] CocoaPods could not find compatible versions for pod "GoogleMaps":
  In Podfile:
    GoogleMaps (~> 3.1.0)

None of your spec sources contain a spec satisfying the dependency: `GoogleMaps (~> 3.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

So, following the instruction I updated with `pod repo update` and it worked!
To ensure, I removed the plugin and added again:
```
Installing "cordova-plugin-googlemaps" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
cordova-plugin-googlemaps depends on GoogleMaps@~> 2.7.0, which conflicts with another plugin. GoogleMaps@~> 3.1.0 is already installed and was not overwritten.
Running command: pod install --verbose
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                    Dload  Upload   Total   Spent    Left  Speed

     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     0 54.7M    0  104k    0     0   371k      0  0:02:30 --:--:--  0:02:30  370k
     9 54.7M    9 5151k    0     0  4031k      0  0:00:13  0:00:01  0:00:12 4031k
    17 54.7M   17 9663k    0     0  4243k      0  0:00:13  0:00:02  0:00:11 4242k
    22 54.7M   22 12.2M    0     0  3832k      0  0:00:14  0:00:03  0:00:11 3831k
    26 54.7M   26 14.3M    0     0  3288k      0  0:00:17  0:00:04  0:00:13 3288k
    27 54.7M   27 14.8M    0     0  2839k      0  0:00:19  0:00:05  0:00:14 2976k
    28 54.7M   28 15.4M    0     0  2511k      0  0:00:22  0:00:06  0:00:16 2124k
    29 54.7M   29 16.2M    0     0  2291k      0  0:00:24  0:00:07  0:00:17 1403k
    31 54.7M   31 17.1M    0     0  2119k      0  0:00:26  0:00:08  0:00:18  996k
    33 54.7M   33 18.4M    0     0  2030k      0  0:00:27  0:00:09  0:00:18  856k
    36 54.7M   36 20.0M    0     0  2001k      0  0:00:27  0:00:10  0:00:17 1091k
    43 54.7M   43 24.0M    0     0  2184k      0  0:00:25  0:00:11  0:00:14 1771k
    51 54.7M   51 28.2M    0     0  2358k      0  0:00:23  0:00:12  0:00:11 2456k
    57 54.7M   57 31.7M    0     0  2446k      0  0:00:22  0:00:13  0:00:09 2986k
    61 54.7M   61 33.8M    0     0  2423k      0  0:00:23  0:00:14  0:00:09 3149k
    70 54.7M   70 38.8M    0     0  2601k      0  0:00:21  0:00:15  0:00:06 3833k
    76 54.7M   76 42.0M    0     0  2641k      0  0:00:21  0:00:16  0:00:05 3670k
    81 54.7M   81 44.7M    0     0  2653k      0  0:00:21  0:00:17  0:00:04 3379k
    87 54.7M   87 47.8M    0     0  2679k      0  0:00:20  0:00:18  0:00:02 3296k
    92 54.7M   92 50.8M    0     0  2700k      0  0:00:20  0:00:19  0:00:01 3495k
   100 54.7M  100 54.7M    0     0  2773k      0  0:00:20  0:00:20 --:--:-- 3307k


      Official document https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/README.md Please consider to buy a beer for us 🍺 https://github.com/mapsplugin/cordova-plugin-googlemaps#buy-us-a-beer

Adding cordova-plugin-googlemaps to package.json
```

Thanks!

**Comment by kapilSoni101** [comment]
@wf9a5m75: Sir why you have closed above issue this issue is still here.in my case i am not using any onesingnal plugin i  have use firebase plugin as well as cordova-plugin-googlemaps 2.6.2 also used 2.4.4 but i got another multiple errors.

@doonfrs: sir but i  my case  i am not using any onesingnal plugin are u fixed above issue ?

**Comment by wf9a5m75** [comment]
Original issue has been solved.

**Comment by kapilSoni101** [comment]
@wf9a5m75  but sir in my case issue is not resolve.sir i don't need oneSignal plugin please provide me any hint sir how to fix and check our ionic info sir:

> 
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 23 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v11.10.1 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

**Comment by wf9a5m75** [comment]
I already answered about your issue.
