### ISSUE TITLE
how to handle the location permission denied?

### ISSUE THREAD

**Issue by kalaiprakash93** [mapsplugin/cordova-plugin-googlemaps#2606]
I am using error callback for getMyLocation(). but it is not triggered when user denied the permission in v2.6.0

**Comment by wf9a5m75** [comment]
Since all source code is open, please check the code before asking.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/d30c6c44b29e69c11e1ad7ca124db089b1cd801a/www/LocationService.js#L38

**Comment by kalaiprakash93** [comment]
var option = {
					enableHighAccuracy: true // use GPS as much as possible
				};
plugin.google.maps.LocationService.getMyLocation(option, function(location) {
    alert(JSON.stringify(location));
},function(){
alert("denied";)});

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/d30c6c44b29e69c11e1ad7ca124db089b1cd801a/src/android/plugin/google/maps/PluginLocationService.java

**Comment by kalaiprakash93** [comment]
Thanks.can u tell me how to use this one for checking user denied/allowed?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/d30c6c44b29e69c11e1ad7ca124db089b1cd801a/www/LocationService.js#L11

**Comment by kalaiprakash93** [comment]
ok.Thank you so much.I will check this now.

**Comment by kalaiprakash93** [comment]
`plugin.google.maps.LocationService.hasPermission(function(){
							  deviceLocation.lat = location.latLng.lat.toFixed(5);
                              deviceLocation.lng = location.latLng.lng.toFixed(5);
						 }, function() { 
							alert("errorallbacl");
						 });`

**Comment by kalaiprakash93** [comment]
is this correct?

**Comment by wf9a5m75** [comment]
Should be.

**Comment by kalaiprakash93** [comment]
I can get  boolean values from checking thank u
