### ISSUE TITLE
Failed to install plugin, pod command failed

### ISSUE THREAD

**Issue by fatalcaron** [mapsplugin/cordova-plugin-googlemaps#2607]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.6.1-beta-20190423-1048 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sms-plugin 1.0.0 "Cordova SMS Plugin"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 5.5.0
@ionic-native/google-maps : 5.5.0
```

**Current behavior:**
When I add the ios platform, i got this error:
My pod version is 1.6.1
```
Installing "cordova-plugin-googlemaps" for ios
cordova-ios version check failed ("/Users/user917328/Desktop/Gitlab/boly-mobile/platforms/ios/cordova/version"), continuing anyways.
apple-xcode version check failed ("/Users/user917328/Desktop/Gitlab/boly-mobile/platforms/ios/cordova/apple_xcode_version"), continuing anyways.
apple-ios version check failed ("/Users/user917328/Desktop/Gitlab/boly-mobile/platforms/ios/cordova/apple_ios_version"), continuing anyways.
Failed to install 'cordova-plugin-googlemaps': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/user917328/Desktop/Gitlab/boly-mobile/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
pod: Command failed with exit code 1

```

**Comment by wf9a5m75** [comment]
`2.6.1-beta-20190423-1219` is already available.

**Comment by wf9a5m75** [comment]
And the reason of the error is `cordova-ios` is too old. I recommend you upgrade to `cordova-ios@5.0.1`.

**Comment by fatalcaron** [comment]
Same error with cordova-ios@5.0.1

I do not found you package: 
npm i cordova-plugin-googlemaps@2.6.1-beta-20190423-1219

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/a5155cd34f0ea02b2ee4d37177504a4bdb5d5cca/plugin.xml

**Comment by fatalcaron** [comment]
After removing the package and reinstall everything seem to work by magic.

**Comment by fatalcaron** [comment]
Now i got this error inside XCODE

‌`
‌‌‌Ld /Users/user917328/Library/Developer/Xcode/DerivedData/Boly_Camera-dedafovrcpwccphctqyqrgxvizfa/Build/Intermediates.noindex/ArchiveIntermediates/Boly_Camera/InstallationBuildProductsLocation/Applications/Boly_Camera.app/Boly_Camera normal arm64 (in target: Boly_Camera)    cd /Users/user917328/Desktop/Gitlab/boly-mobile/platforms/ios    export IPHONEOS_DEPLOYMENT_TARGET=11.0    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -L/Users/user917328/Library/Developer/Xcode/DerivedData/Boly_Camera-dedafovrcpwccphctqyqrgxvizfa/Build/Intermediates.noindex/ArchiveIntermediates/Boly_Camera/BuildProductsPath/Release-iphoneos -F/Users/user917328/Library/Developer/Xcode/DerivedData/Boly_Camera-dedafovrcpwccphctqyqrgxvizfa/Build/Intermediates.noindex/ArchiveIntermediates/Boly_Camera/BuildProductsPath/Release-iphoneos -F/Users/user917328/Desktop/Gitlab/boly-mobile/platforms/ios/Pods/GoogleMaps/Base/Frameworks -F/Users/user917328/Desktop/Gitlab/boly-mobile/platforms/ios/Pods/GoogleMaps/Maps/Frameworks -filelist /Users/user917328/Library/Developer/Xcode/DerivedData/Boly_Camera-dedafovrcpwccphctqyqrgxvizfa/Build/Intermediates.noindex/ArchiveIntermediates/Boly_Camera/IntermediateBuildFilesPath/Boly_Camera.build/Release-iphoneos/Boly_Camera.build/Objects-normal/arm64/Boly_Camera.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=11.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/user917328/Library/Developer/Xcode/DerivedData/Boly_Camera-dedafovrcpwccphctqyqrgxvizfa/Build/Intermediates.noindex/ArchiveIntermediates/Boly_Camera/IntermediateBuildFilesPath/Boly_Camera.build/Release-iphoneos/Boly_Camera.build/Objects-normal/arm64/Boly_Camera_lto.o -Xlinker -final_output -Xlinker /Applications/Boly_Camera.app/Boly_Camera -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lc++ -lz -framework Accelerate -framework CoreData -framework CoreGraphics -framework CoreImage -framework CoreLocation -framework CoreTelephony -framework CoreText -framework GLKit -framework GoogleMaps -framework GoogleMapsBase -framework GoogleMapsCore -framework ImageIO -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit /Users/user917328/Library/Developer/Xcode/DerivedData/Boly_Camera-dedafovrcpwccphctqyqrgxvizfa/Build/Intermediates.noindex/ArchiveIntermediates/Boly_Camera/BuildProductsPath/Release-iphoneos/libCordova.a -weak_framework SafariServices -framework CoreLocation -lPods-Boly_Camera -weak_framework WebKit -weak_framework SystemConfiguration -framework CoreTelephony -weak_framework MessageUI -framework CoreBluetooth -framework Photos -framework AVFoundation -framework UserNotifications -framework Contacts -framework AddressBook -framework EventKit -framework CoreMotion -Xlinker -dependency_info -Xlinker /Users/user917328/Library/Developer/Xcode/DerivedData/Boly_Camera-dedafovrcpwccphctqyqrgxvizfa/Build/Intermediates.noindex/ArchiveIntermediates/Boly_Camera/IntermediateBuildFilesPath/Boly_Camera.build/Release-iphoneos/Boly_Camera.build/Objects-normal/arm64/Boly_Camera_dependency_info.dat -o /Users/user917328/Library/Developer/Xcode/DerivedData/Boly_Camera-dedafovrcpwccphctqyqrgxvizfa/Build/Intermediates.noindex/ArchiveIntermediates/Boly_Camera/InstallationBuildProductsLocation/Applications/Boly_Camera.app/Boly_Camera
`
ld: library not found for -lPods-Boly_Camera

**Comment by ellecito** [comment]
I try installing:

`cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git#a5155cd34f`

but the error persist. I downgrade cordova@9.0.0 and it works

`sudo npm uninstall -g cordova && sudo npm install -g cordova@8.1.2`
