### ISSUE TITLE
Error compiling v2.6.1 on Android 

### ISSUE THREAD

**Issue by battika** [mapsplugin/cordova-plugin-googlemaps#2610]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
    "@ionic-native/core": "4.20.0",
    "@ionic-native/google-maps": "4.21.0"
```

Cordova-CLI version 9.0.0, Cordova-android version 7.1.4

**Current behavior:**
When attempting to compile getting the following error with plugin version 2.6.1.
```

/Users/vagrant/git/platforms/android/app/src/main/java/plugin/google/maps/PluginPolygon.java:143: error: incompatible types: int cannot be converted to boolean
                if (keySet.size()) {
                               ^
```
It compiled OK before.

**Expected behavior:**
Should compile with no error

**Comment by wf9a5m75** [comment]
Sorry. V2.6.2 has been released.

**Comment by battika** [comment]
Thanks

**Comment by battika** [comment]
I confirm it works OK, thank you again for the quick help.
