### ISSUE TITLE
iOS App crashed when LocationServices is off

### ISSUE THREAD

**Issue by hungca** [mapsplugin/cordova-plugin-googlemaps#2614]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.microsoft.azure-mobile-services 1.2.9 "Windows Azure Mobile Services"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-googlemaps 2.5.3 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.1.0 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.0.0 "StatusBar"
cordova-plugin-whitelist 1.2.0 "Whitelist"
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
ionic-plugin-keyboard 1.0.8 "Keyboard"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
phonegap-plugin-push 2.1.0 "PushPlugin"
```

**Current behavior:**
1. **Turn off Location Services**
2. Open app, after init map, app is crashed at getMyLocation function

**Expected behavior:**
Map shows the current location.

**Screen capture or video record:**

![image](https://user-images.githubusercontent.com/11658969/57831105-699f3f80-77de-11e9-8a9e-08e5371532a6.png)

**Related code, data or error log (please format your code or data):**
```
map.getMyLocation({
                    enableHighAccuracy: true // Force GPS
                        ,
                    timeout: 10000
                },
                function (locationResult) {
                    onGetLocationSuccess(locationResult.latLng)
                }, onGetLocationError);
```
Why is `onGetLocationError` function not fired and app crashed?
Please check and let me know if you need any additional information.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository. Otherwise please debug by yourself.

**Comment by hungca** [comment]
> Please share your project files on GitHub repository. Otherwise please debug by yourself.

You can try on a new Cordova project with `cordova create`, it also occurs. Also, I will upload my project soon, after I fixed this issue.

**Comment by wf9a5m75** [comment]
Unfortunately, I have no time to spend for creating test application from scratch.

**Comment by wf9a5m75** [comment]
ping
