### ISSUE TITLE
draw route service

### ISSUE THREAD

**Issue by marking11** [mapsplugin/cordova-plugin-googlemaps#2616]
Hello,
 Is this plugin support drawing route between location to have such a live tracker ? 

Thanks,

**Comment by wf9a5m75** [comment]
nop.

**Comment by marking11** [comment]
see this topic https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2493 , he can integrate the google maps v3 with the plugin

**Comment by marking11** [comment]
I can't understand you have implement a plugin and you don't give answer, you just answer by one word without any informations, you don't want us to use this plugin?

**Comment by wf9a5m75** [comment]
I don't know why you don't see the past issues. 
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=direction&type=Issues

I don't recommend to use this plugin for beginners. Why don't you use Google Maps JavaScript v3 directly.

**Comment by marking11** [comment]
because your plugin looks native,  did you see this topic https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2493,  what should we do to update marker position in your native map and draw the route please?
