### ISSUE TITLE
watch position

### ISSUE THREAD

**Issue by kovaneth** [mapsplugin/cordova-plugin-googlemaps#2617]
Hello everyone,
I have a (user A) that share his location with a ( user B), the (user A) is in a vehicule, so his location change frenquently, is it possible in this plugin to show the location update like in uber and draw polyline between positions ?

Thanks,

**Comment by wf9a5m75** [comment]
This plug-in does not have a such function

**Comment by kovaneth** [comment]
Can you talk on private i have  an offer for you.  hish0451@gmail.com
