### ISSUE TITLE
Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

### ISSUE THREAD

**Issue by ahmadkam72** [mapsplugin/cordova-plugin-googlemaps#2619]
I get this error when I want to add google maps plugin to my ionic 4 project
I run this command:
ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps

can anyone help me to slove this issue?

Thank you.

**Comment by wf9a5m75** [comment]
Find the past answer from the issue list, please.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2581

**Comment by adamduren** [comment]
@wf9a5m75 I see a number of these where people don't properly search for existing issues before creating a new one. I know GitHub has tried to introduce features such as a live search that suggests similar issues.

Have you considered [pinned issues](https://help.github.com/en/articles/pinning-an-issue-to-your-repository) for things that frequently pop up as repetitive? It might help cut down on the number of duplicates.
