### ISSUE TITLE
plugin.google.maps.geometry.spherical.interpolate and marker

### ISSUE THREAD

**Issue by kovaneth** [mapsplugin/cordova-plugin-googlemaps#2621]
Hello, 
I tried to use the plugin.google.maps.geometry.spherical.interpolate with a marker but the marker dont follow the route, he appears just one time and disappear.

```js
var mapcurrentLocationMarker;var map ;var polyline;var directionsService;var directionsDisplay;var HND_AIR_PORT = {lat: 31.6596826, lng:-8.0151057};var SFO_AIR_PORT = {lat: 31.6639381, lng: -8.0327653}; var button = document.getElementById("button"); button.addEventListener("click", function() { // Move to the position with animation directionsService = new google.maps.DirectionsService; directionsService.route({ origin: HND_AIR_PORT, destination: SFO_AIR_PORT, travelMode: google.maps.TravelMode['DRIVING'] }, (res, status) => { if (status == google.maps.DirectionsStatus.OK) { decodedPoints = plugin.google.maps.geometry.encoding.decodePath(res.routes[0].overview_polyline); console.log(" res 0 "+res.routes[0]); console.log("overview "+res.routes[0].overview_polyline) console.log(" decoded point "+decodedPoints); map.animateCamera({ target: HND_AIR_PORT, zoom: 17, tilt: 60, bearing: 140, duration: 5000 }); map.addPolyline({ points: decodedPoints, 'color': '#4a4a4a', width: 4, geodesic: false }); var marker = map.addMarker({ position: decodedPoints[0], draggable: true }); var circle = map.addCircle({ center: marker.getPosition(), radius: 10, fillColor: "rgba(0, 0, 255, 0.5)", strokeColor: "rgba(0, 0, 255, 0.75)", strokeWidth: 1 }); marker.bindTo("position", circle, "center"); var fraction = 0; var direction = 1; setInterval(function() { fraction += 0.01 * direction; if (fraction >= 1) { direction = -1; } else if (fraction <= 0) { direction = 1; } //console.log(decodedPoints[i]); var position = plugin.google.maps.geometry.spherical.interpolate(decodedPoints[0], decodedPoints[10], fraction); marker.setPosition(position); //Do something }, 3000); } else { console.warn(status); } }); });
```

**Comment by wf9a5m75** [comment]
That's not bug.

**Comment by kovaneth** [comment]
`var button = document.getElementById("button");
button.addEventListener("click", function() {
    directionsService = new google.maps.DirectionsService;
    directionsService.route({
        origin: HND_AIR_PORT,
        destination: SFO_AIR_PORT,
        travelMode: google.maps.TravelMode['DRIVING']
    }, (res, status) => {
        if (status == google.maps.DirectionsStatus.OK) {
            decodedPoints = plugin.google.maps.geometry.encoding.decodePath(res.routes[0].overview_polyline);
            console.log(" res 0 " + res.routes[0]);
            console.log("overview " + res.routes[0].overview_polyline)
            console.log(" decoded point " + decodedPoints);

            map.animateCamera({
                target: HND_AIR_PORT,
                zoom: 17,
                tilt: 60,
                bearing: 140,
                duration: 5000
            });

            map.addPolyline({
                points: decodedPoints,
                'color': '#4a4a4a',
                width: 4,
                geodesic: false
            });

            var marker = map.addMarker({
                position: HND_AIR_PORT,
                draggable: true
            });
            var circle = map.addCircle({
                center: marker.getPosition(),
                radius: 10,
                fillColor: "rgba(0, 0, 255, 0.5)",
                strokeColor: "rgba(0, 0, 255, 0.75)",
                strokeWidth: 1
            });
            marker.bindTo("position", circle, "center");
            var fraction = 0;
            var direction = 1;

            var counter = 0;
            var i = setInterval(function() {
                fraction += 0.01 * direction;
                if (fraction >= 1) {
                    direction = -1;
                } else if (fraction <= 0) {
                    direction = 1;
                }

                counter++;
                if (counter === 10) {
                    clearInterval(i);
                }
                console.log(decodedPoints[i]);
                var position = plugin.google.maps.geometry.spherical.interpolate(decodedPoints[i], decodedPoints[i] + 1, fraction);
                marker.setPosition(position);
                //Do something



            }, 3000);


        } else {
            console.warn(status);
        }

    });


});`

**Comment by wf9a5m75** [comment]
Interpolate function calculates meddle points of geometric straight line. It doesn't consider route.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/spherical.js

**Comment by kovaneth** [comment]
But mathematically, between two point theres is always a straight line, so we give the function two parameter spherical.interpolate(decodedPoints[i], decodedPoints[i] + 1, fraction);

**Comment by kovaneth** [comment]
Is there any solution?

**Comment by wf9a5m75** [comment]
Google Directions API returns the detail steps of the route. You should try to see the results of the API using `console.log` before asking, or please read the Google Maps API documents more

**Comment by kovaneth** [comment]
I already do that, the returned result from google directions apis is an array of points.
{"lat": 31.65957, "lng": -8.014859999999999},{"lat": 31.65967, "lng": -8.014769999999999},{"lat": 31.65966, "lng": -8.014679999999998},{"lat": 31.659549999999996, "lng": -8.014429999999999},{"lat": 31.659369999999996, "lng": -8.014569999999999},{"lat": 31.658899999999996, "lng": -8.01498},{"lat": 31.657679999999996, "lng": -8.01602},{"lat": 31.657839999999997, "lng": -8.01638},{"lat": 31.658099999999997, "lng": -8.01689},{"lat": 31.65825, "lng": -8.017119999999998},{"lat": 31.658289999999997, "lng": -8.01724},{"lat": 31.658429999999996, "lng": -8.01756},{"lat": 31.658429999999996, "lng": -8.017809999999999},{"lat": 31.658479999999997, "lng": -8.018089999999999},{"lat": 31.65854, "lng": -8.01877},{"lat": 31.65853, "lng": -8.01921},{"lat": 31.658479999999997, "lng": -8.01989},{"lat": 31.658419999999996, "lng": -8.020259999999999},{"lat": 31.658299999999997, "lng": -8.020669999999999},{"lat": 31.658109999999997, "lng": -8.02121},{"lat": 31.657899999999998, "lng": -8.02163},{"lat": 31.657349999999997, "lng": -8.022559999999999},{"lat": 31.658019999999997, "lng": -8.023299999999999},{"lat": 31.658409999999996, "lng": -8.02375},{"lat": 31.65938, "lng": -8.02512},{"lat": 31.660019999999996, "lng": -8.026119999999999},{"lat": 31.660929999999997, "lng": -8.02751},{"lat": 31.661989999999996, "lng": -8.029129999999999},{"lat": 31.662229999999997, "lng": -8.029459999999998},{"lat": 31.6623, "lng": -8.02957},{"lat": 31.662049999999997, "lng": -8.02985},{"lat": 31.66144, "lng": -8.03051},{"lat": 31.660659999999996, "lng": -8.031189999999999},{"lat": 31.661059999999996, "lng": -8.031889999999999},{"lat": 31.661309999999997, "lng": -8.03233},{"lat": 31.661609999999996, "lng": -8.032869999999999},{"lat": 31.662249999999997, "lng": -8.03408},{"lat": 31.662519999999997, "lng": -8.03455},{"lat": 31.663269999999997, "lng": -8.03431},{"lat": 31.663659999999997, "lng": -8.034229999999999},{"lat": 31.663779999999996, "lng": -8.034189999999999},{"lat": 31.66388, "lng": -8.034089999999999},{"lat": 31.663939999999997, "lng": -8.03397},{"lat": 31.664039999999996, "lng": -8.033809999999999},{"lat": 31.664389999999997, "lng": -8.03333},{"lat": 31.664499999999997, "lng": -8.03314},{"lat": 31.664499999999997, "lng": -8.03299},{"lat": 31.664469999999998, "lng": -8.032919999999999},{"lat": 31.664239999999996, "lng": -8.03256}
i loop on the table to draw line between  point[i] and point[i]+1

**Comment by wf9a5m75** [comment]
routes.legs.steps

**Comment by kovaneth** [comment]
Sorry can you explain?

**Comment by wf9a5m75** [comment]
See the reference of DirectionsRoute
https://developers.google.com/maps/documentation/javascript/reference/directions#DirectionsResult

**Comment by kovaneth** [comment]
So is there any solution ?

**Comment by wf9a5m75** [comment]
Did you see the steps :angry: ? The steps contains details position of the routes. It means the steps contain the interpolate positions of routes.

I'm not your teacher. Please do your best as much as possible, then even though you don't understand, you can ask.

**Comment by kovaneth** [comment]
lol thank you i really want to use your plugin because he looks native, i don t want to draw route, just to track a position sent from my server to the mobile application.
And because your plugin doesnt support map api v3.  i had the reflex to create a web service that sent the latest position to my application, save the position in array and like this draw the polyline between position 0 and position 1.

**Comment by wf9a5m75** [comment]
There is no function to calculate the intermediate route position between A and B, because only Google has route data.
Google returns detailed steps (turn-by-turn positions) in DirectionsRoute. Even you use Google Directions API, it contains them.

Technically, I can implement directions API into this plugin, but nobody wants to pay for my worktime of this plugin, I don't implement it.

**Comment by kovaneth** [comment]
Can we talk on private i can pay you for such mission

**Comment by kovaneth** [comment]
ok i undestand, so you think the actual version of the plugin can not do what i want even if i use Google Directions API.
i start to implement something like this to use the step, but you are the owner of the plugin if you confirm me the plugin will not do such feature, i will stop and waste time.

`var bounds  = new plugin.google.maps.LatLngBounds();
         var legs = response.routes[0].legs;
         for (i = 0; i < legs.length; i++) {
        var steps = legs[i].steps;
        for (j = 0; j < steps.length; j++) {
          var nextSegment = steps[j].path;
          for (k = 0; k < nextSegment.length; k++) {
            polyline.getPoints().push(nextSegment[k]);
            bounds.extend(nextSegment[k]);
          }
        }
      }`

**Comment by wf9a5m75** [comment]
I always request $1,000 USD for one feature implement.
There are some reasons.
- I have to work for three platforms.
- I typically face unexpected some problems.
- Even after releasing the function, I have to maintenance of the function forever (until I close this project)

If I receive the amount, I implement it in three months.
If I fail (such as I can not finish the work in three months), I fully refund the amount.

---------

`HTMLInfoWindow` and `MarkerCluster` are implemented this way.
If we agree this causes, I can work for it.

If you are still interested in, please let me know to my email. My email is shown at my profile page.

**Comment by kovaneth** [comment]
thank you for your offer, i have a project to deliver in two weeks ... i think i will use the google maps v3
