### ISSUE TITLE
MyLocation zIndex with marker not consistent between Android and IOS leading to marker click issue

### ISSUE THREAD

**Issue by nroulon** [mapsplugin/cordova-plugin-googlemaps#2622]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.1.0-dev "InAppBrowser"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
ionic-plugin-deeplinks 1.0.19 "Ionic Deeplink Plugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```

**`@ionic-native/google-maps`, package.json**
```
@ionic-native/core : 5.5.1
@ionic-native/google-maps : 5.5.0
```

**Current behavior:**
Hello, I have a problem with the MyLocation blue dot and the marker on Android.

The blue dot is behind the marker on iOS but not on Android. On the original Goole Maps Android app, when you click on the map to create a marker, the marker is displayed behind the blue dot. This is not consistent, is it possible to have a parameter like the zIndex on the blue dot (I tried the zIndex on markers but it does not seem to work) ? I would like to set the marker over the blue dot on Android.

If it is not possible, I have a related issue on Android. As my marker is behind the blue dot, it is difficult to click on the marker.

Maybe, the MY_LOCATION_CLICK event capture the click but I haven't found a way to propage the event (in order to let MARKER_CLICK capture the event). This is really problematic for me because most of my users will be located on the marker they want to click.

I link an updated demo repository of the problem: https://github.com/nroulon/ionic-googlemaps-quickdemo-v4. I modify the home page to display MyLocation and I set the marker a little below (I modify the latitude) when you click on "Demo".

This is what happen on iOS : 
<img width="200" alt="demo on ios" src="https://user-images.githubusercontent.com/15632435/58265117-62000d80-7d7f-11e9-96fc-ab05c2acdd4e.png">

And this is a video on Android, we can see I clicked on the marker many times but it did not work : [demo on android.mp4.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/3212985/demo.on.android.mp4.zip)

Thanks.

**Comment by wf9a5m75** [comment]
Blue dot displays by native SDKs, not this plugin. Thus, there is no way.

**Comment by Mathieu-Castets** [comment]
Hi, I experience the same issue and I understand this is a native behaviour.

But, what about **not** listening to/bypassing the MY_LOCATION_EVENT? Thus, MAP_MARKER_CLICK should be called. No?

**Comment by wf9a5m75** [comment]
Even under the blue dot, you can click the marker.
![capture](https://user-images.githubusercontent.com/167831/58270417-a0c1a380-7d3e-11e9-9fcf-b1928f17cacd.gif)

**Comment by Mathieu-Castets** [comment]
The marker is not right under the blue dot on your screencast but slightly beside it.

Look at this demo, the blue dot is over the marker and only a fex pixels at the top of the marker receives the marker click event:
![demo on android](https://user-images.githubusercontent.com/4427447/58285233-a5bd3c00-7dac-11e9-931c-8cf54e9a9d05.gif)

I'm looking for any workaround.

Thank you for your quick reply anyway.

**Comment by wf9a5m75** [comment]
This is Google's problem. Please ask to Google.

**Comment by nroulon** [comment]
Hi,
I forked the plugin and my supposition was right. The MY_LOCATION_CLICK event is always listening in PluginMap.java, I just comment the line :

`map.setOnMyLocationClickListener(PluginMap.this);`

And it work, I can click on a marker behind the blue dot. So the thing is that, the plugin listen all map's events, even if my app don't listen it and that stop the event propagation to element behind the first one.

From what I understand the plugin, it is not easy to listen and remove the listener on the fly : like my app listen the MY_LOCATION_CLICK so the Android part do a : `map.setOnMyLocationClickListener(PluginMap.this);` and a `map.setOnMyLocationClickListener(null);` when the app does not do it anymore. But maybe I am wrong. (And I do not take a look to the iOS/browser part)

If it is not possible, is it ok to add boolean options in GoogleMapsOptions that specify for each event if the native part must set a listener of not ?
