### ISSUE TITLE
Plugin removes my background image

### ISSUE THREAD

**Issue by GitToTheHub** [mapsplugin/cordova-plugin-googlemaps#2623]
**I'm submitting a ...**  (check one with "x")
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**

Using latest Plugin Version 2.6.2

**Current behavior:**
When i set a background image and using the plugin, my background image isn't anymore after destroying the map. Only a white background appears.

**Expected behavior:**
It would be nice, when my background image would be restored after using the plugin.

**Related code, data or error log (please format your code or data):**
- ComputedStyle for "background" before showing the map: rgb(233, 233, 233) url("file:///data/data/com.adobe.phonegap.app/files/phonegapdevapp/www/img/bg_start_unten.png") no-repeat scroll
- ComputedStyle after using the map: rgba(0, 0, 0, 0) url("file:///data/data/com.adobe.phonegap.app/files/phonegapdevapp/www/index.html") repeat scroll 0% 0% / auto padding-box border-box

Or is there already a way to restore the background image?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#how-does-this-plugin-work-android-ios

**Comment by GitToTheHub** [comment]
Thank you, i see it's common, that the plugin changes the background to transparent. But when I'm closing the map, it should be possible to set a background again, because I'm not using anymore the map overlay. Is there no way?

**Comment by GitToTheHub** [comment]
I see you put following CSS in the head:

```
html, body, ._gmaps_cdv_ {
  background-image: url() !important;
  background: rgba(0,0,0,0) url() !important;
  background-color: rgba(0,0,0,0) !important;
}

._gmaps_cdv_ .nav-decor {
  background-color: rgba(0,0,0,0) !important;
  background: rgba(0,0,0,0) !important;
  display:none !important;
}

.framework7-root .page-previous {
  display:none !important;
}
```

Maybe it should be dynamically added and removed, when you init or destroy a map?

**Comment by leo4444** [comment]
@GitToTheHub I could solve it in Angular, I don't know how it is in 7Framework, but you should put on your exit hook, the event that fires before leaving your map screen the following javaScript code:

 async ngOnDestroy() {
    const elements = document.getElementsByClassName('_gmaps_cdv_');
    for (let i = 0; i < elements.length; i++) {
      elements[i].classList.remove('_gmaps_cdv_');
    }
    const a = elements.length;  
  }

**Comment by GitToTheHub** [comment]
@leo4444 Thank you, but i found another solution. When i'm not on the map page, i forcing my background image with !important. When i'm visiting the map page, i remove the !important before showing the map. After closing the map i re-add the !important.

Because !important is not add-/removable with jQuery, i did it with a css class. I set the css class with the background and !important to my page-div and removing it, before visiting the map page, and re-adding the class after visiting the map page.

**Comment by leo4444** [comment]
@GitToTheHub It is a possible solution but you should keep in mind that when loading a map and leaving it, the plugin leaves a class with the name 'gmaps_cdv' injected into all layers of your app which can interfere with the proper functioning of your front

**Comment by GitToTheHub** [comment]
This is right, but it should be the job of this plugin to remove the class, when closing the map.

@wf9a5m75 Could you remove your injected css, when your map is desroyed?

```
html, body, ._gmaps_cdv_ {
  background-image: url() !important;
  background: rgba(0,0,0,0) url() !important;
  background-color: rgba(0,0,0,0) !important;
}

._gmaps_cdv_ .nav-decor {
  background-color: rgba(0,0,0,0) !important;
  background: rgba(0,0,0,0) !important;
  display:none !important;
}

.framework7-root .page-previous {
  display:none !important;
}
```

Thank you.
