### ISSUE TITLE
KmlLoader unable to load KML with <color>00000000</color>

### ISSUE THREAD

**Issue by carlchan1994** [mapsplugin/cordova-plugin-googlemaps#2627]
Some KML file have a # before the color, and some do not:

`<color>#00000000</color>`
`<color>00000000</color>`

The colorStr(00000000)  seems to be read as a number instead of string and an error of "colorStr.replace is not a function" happens when loading KML.

=======================================================

> //-------------------------------
> // KML color (AABBGGRR) to RGBA
> //-------------------------------
> function kmlColorToRGBA(colorStr) {
>   var rgba = [];
>   colorStr = colorStr.replace('#', '');
>   for (var i = 6; i >= 0; i -= 2) {
>     rgba.push(parseInt(colorStr.substring(i, i + 2), 16));
>   }
>   return rgba;
> }

========================================================

> ERROR Error: Uncaught (in promise): TypeError: colorStr.replace is not a function
> TypeError: colorStr.replace is not a function
>     at kmlColorToRGBA (KmlLoader.js:1066)
>     at KmlLoader.js:743
>     at Array.forEach (<anonymous>)
>     at KmlLoader.js:740
>     at Array.forEach (<anonymous>)
>     at KmlLoader.parseLineStringTag (KmlLoader.js:736)
>     at KmlLoader.parseKmlTag (KmlLoader.js:302)
>     at BaseArrayClass.<anonymous> (KmlLoader.js:135)
>     at BaseArrayClass.js:147
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
>     at resolvePromise (zone.js:831)
>     at zone.js:896
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
>     at Object.onInvokeTask (core.js:17290)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
>     at drainMicroTaskQueue (zone.js:601)
>     at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
>     at invokeTask (zone.js:1744)
>     at Worker.globalZoneAwareCallback (zone.js:1770)
> defaultErrorLogger @ core.js:15724

**Comment by makers-mark** [comment]
Make a pull request.

**Comment by wf9a5m75** [comment]
Please provide evidence KML file link.

**Comment by carlchan1994** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
  <Folder>
	<Placemark>
        <LineString>
          <coordinates>114.1688205610001,22.29385387500003,0 114.1712166780001,22.29456057500005,0</coordinates>
        </LineString>
		 <Style> 
			<LineStyle>  
				<color>00000000</color>
		   </LineStyle> 
		</Style>
    </Placemark>
  </Folder>
</Document>
</kml>

```

**Comment by wf9a5m75** [comment]
`00000000` should be transparent black because aarrggbb.

**Comment by carlchan1994** [comment]
> `00000000` should be transparent black because aarrggbb.

I have changed the color to 99999999 instead, same error should occur.

**Comment by wf9a5m75** [comment]
I confirmed the latest version works correctly.
![capture](https://user-images.githubusercontent.com/167831/62741641-7d7acc00-b9f0-11e9-88d2-858bc053f195.png)
![Screen Shot 2019-08-08 at 3 17 16 PM](https://user-images.githubusercontent.com/167831/62741649-88356100-b9f0-11e9-9b36-dc34bb733f95.png)
![Screen Shot 2019-08-08 at 3 17 52 PM](https://user-images.githubusercontent.com/167831/62741650-88356100-b9f0-11e9-91f4-3bf7efa5cc33.png)
