### ISSUE TITLE
Google Maps SDK for iOS crashes if CFBundleExecutable contains non-English characters

### ISSUE THREAD

**Issue by alexmeseguer** [mapsplugin/cordova-plugin-googlemaps#2629]
Hi, when I try run my with Simultator of Xcode, the device simulator runs but when my app starts show this error:

"Google Maps SDK for iOS crashes if CFBundleExecutable contains non-English characters. More details, Check out the comment in the CordovaGoogleMaps.m file."

Would you know what may be happening? If you need more information, tell me it.

Thanks!

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2017


That's Google's bug.

**Comment by sametocak** [comment]
aynı hatayı bende alıyorum
