### ISSUE TITLE
undefined is not an object (evaluating 'prevRect.left')

### ISSUE THREAD

**Issue by adamduren** [mapsplugin/cordova-plugin-googlemaps#2631]
**I'm submitting a ...**
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
> cordova plugin ls
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-firebase-analytics 2.0.3 "FirebaseAnalyticsPlugin"
cordova-plugin-firebase-config 2.0.3 "cordova-plugin-firebase-config"
cordova-plugin-firebase-dynamiclinks 2.0.3 "FirebaseDynamicLinksPlugin"
cordova-plugin-firebase-messaging 2.1.5 "FirebaseMessagingPlugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.2.1 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 5.7.0
@ionic-native/google-maps : 5.5.0
```

**Current behavior:**

Occasionally a runtime error occurs.

**Expected behavior:**

For the conditions that result in the undefined variable to not arise or for it to be handled in a way that does not cause a runtime error.

**Screen capture or video record:**

This happened with a device in production. I have yet to been able to reproduce this.

**Related code, data or error log (please format your code or data):**
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/3f6ce0f97b1ac2aafcb35c389a9dec7031b7054b/www/js_CordovaGoogleMaps-for-android_ios.js#L436-L442

**Comment by adamduren** [comment]
@wf9a5m75 I got this error from our error reporting service (Sentry). It happened to a user in production. It seems like a race condition. I'm not sure if an appropriate fix would be to check for `prevRect` to be undefined or if there may be a better fix.

**Comment by adamduren** [comment]
Happy to hear your thoughts.

**Comment by wf9a5m75** [comment]
Please prove the HTML where is the error occurred.

**Comment by adamduren** [comment]
@wf9a5m75 I am not even sure which map caused the issue. I have attached the information I have regarding the issue. If you look at the pages the user visited, at least for the history captured in the breadcrumbs, you'll see navigation events. None of those pages contain a map so it would have been in the breadcrumb history that was truncated. In other words, we have no way of knowing which map caused it.

I'm guessing some cleanup code is trying to run after the map is gone. We should be able to detect when `prevRect` is null and sensibly handle it, correct?

![sentry io_organizations_truzen_issues_1057397166__project=1461556 query=is%3Aunresolved (2)](https://user-images.githubusercontent.com/581097/58998434-9c24d280-87b5-11e9-8f1c-8fc7a7812b0f.png)

**Comment by wf9a5m75** [comment]
The purpose of `detectTransitionFinish` is to detect the timing of `transition` of CSS.
Since this plugin watches all `transition` events everywhere, the page where error occurred is not related with maps page.

Please create a simple project that has two views, that reproduce this part.
![Screen Shot 2019-06-06 at 10 05 57 AM](https://user-images.githubusercontent.com/167831/59051879-b8bb1c00-8842-11e9-8ed9-ffb5ab50d551.png)

I guess this error occurred when the `manage-business` view disappeared unexpectedly.

**Comment by adamduren** [comment]
I have yet to have been able to reproduce this so I am currently unable to provide a code sample to do so. Since it happened once, it can obviously happen again. It would seem wise to protect against this case just as you would expect to guard against known things like dividing by 0. 

Would this be a sane fix or does it have issues?
```javascript
    // Added !prevRect
    if (!prevRect || divRect.left === prevRect.left &&
        divRect.top === prevRect.top &&
        divRect.right === prevRect.right &&
        divRect.bottom === prevRect.bottom) {
      self.transformTargets[elemId].finish = true;
    }
```

**Comment by wf9a5m75** [comment]
I can't agree without enough test.

**Comment by wf9a5m75** [comment]
Although there is no enough information, but the code is updated to prevent the error.
