### ISSUE TITLE
not show map on framework7 mvc for see second view

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#2633]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.0 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-whitelist 1.3.3 "Whitelist"
org.pbernasconi.progressindicator 1.1.0 "Progress Indicator"
phonegap-plugin-push 1.11.1 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

Hi, im create a  project with framework7 for build app on ios , but im using a mvc structure with require.js and handlebars, but when i try load my map on the second view i dont see nothing, the problem that if i load the map on the first view the map load very well , while i load on the second view not show, i have seen that the map load, but for show i have to go background and resume app again for show ( this on my project master), i uploaded a some files for reproduce the problem.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

[mvc_cordova.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/3262560/mvc_cordova.zip)

**Comment by wf9a5m75** [comment]
Please share your project files on github repository instead of zip file. I don't open zip file.

**Comment by dsemerida** [comment]
please wait me for upload you, thanks

**Comment by dsemerida** [comment]
https://github.com/dsemerida/framework7mvcmaps here my repo

**Comment by wf9a5m75** [comment]
![Screen Shot 2019-06-06 at 10 32 12 AM](https://user-images.githubusercontent.com/167831/59053480-65e36380-8846-11e9-99a1-8578c4fe41ef.png)

I can't see the google maps. Please include the simple code which reproduces your problem.

**Comment by dsemerida** [comment]
my map load on harmap.hmtl with controller hadmapController.js

**Comment by dsemerida** [comment]
i try to upload my master project, wait me so minutes for share it

**Comment by wf9a5m75** [comment]
I'm sorry, but I'm not expert of Framework7. Could you create simple code at least display a map?

**Comment by dsemerida** [comment]
yeah man , i have upload the files true of my master project, you can update for download and see, in this example i reproduce my problem.

**Comment by wf9a5m75** [comment]
![Screen Shot 2019-06-06 at 11 46 35 AM](https://user-images.githubusercontent.com/167831/59058109-c24b8080-8850-11e9-911f-2c193858c732.png)

**Comment by wf9a5m75** [comment]
Try to reinstall the plugin.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add cordova-plugin-googlemaps@2.6.2
```

**Comment by dsemerida** [comment]
the map load on the first call?

**Comment by dsemerida** [comment]
i have been upload to `$> cordova plugin add cordova-plugin-googlemaps@2.6.2` but now dont see the map, my error with version 2.1 are when call second view, for see map , after loaded 2 view i have to onpause and onresume agan for see the map

**Comment by wf9a5m75** [comment]
I don't support old versions.

**Comment by dsemerida** [comment]
` <plugin name="cordova-plugin-googlemaps" spec="^2.6.2" />
    <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="" />
    <preference name="GOOGLE_MAPS_IOS_API_KEY" value="" />`

this is my config.xml cordova

**Comment by wf9a5m75** [comment]
Show me the `cordova plugin list` and `cordova platform list`

**Comment by dsemerida** [comment]
plugin list
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-progress 0.3.0 "Progress"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-push 1.11.1 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"

platform list
Installed platforms:
  ios 4.5.5
Available platforms: 
  android ~7.0.0
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

**Comment by wf9a5m75** [comment]
`ios 4.5.5` too old.

**Comment by wf9a5m75** [comment]
You installed old cordova google maps plugin, because you have `com.googlemaps.ios 2.7.0`.

**Comment by wf9a5m75** [comment]
```
$> cordova plugin list
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"

$> cordova platform list
Installed platforms:
  android 8.0.0
  ios 5.0.1
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0
```

**Comment by dsemerida** [comment]
ok, ill reinstall ios platform and reinstall the  new version

**Comment by dsemerida** [comment]
hi, i have been updated my ios platform for your version and reinstall the map plugin to 2.6 but i still get my error, how i can upload video for see it?

**Comment by wf9a5m75** [comment]
youtube

**Comment by dsemerida** [comment]
https://youtu.be/A1MFEIX6XlY this video for see

**Comment by wf9a5m75** [comment]
You checked iOS.

**Comment by dsemerida** [comment]
yeah only in ios i have the problem on android works fine

**Comment by dsemerida** [comment]
good morning, excuseme , you have been able to solve the problem?

**Comment by wf9a5m75** [comment]
As I posted above, I have no problem with your code.

**Comment by dsemerida** [comment]
hi, i found that remove my meta tag the map work right
`<meta http-equiv="Content-Security-Policy" content="img-src * data: 'unsafe-inline';default-src *; style-src 'self' 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval';connect-src *">`, but i dont know wich atribute is wrong

**Comment by wf9a5m75** [comment]
I think you don't need the meta tag, because all code is managed by only you.

**Comment by dsemerida** [comment]
i know but this only way for can use,  i have to see how config meta tag, because other plugins that i use depending for load some actions like camera
