### ISSUE TITLE
marker pass parameter

### ISSUE THREAD

**Issue by wearta** [mapsplugin/cordova-plugin-googlemaps#2636]
i am using the plugin in ionic 3 app
and addmarker ( for multi marker ) for places 
i need to make id to callback when click the marker 

how can i do this , is this plugin do this 

please help

**Comment by wearta** [comment]
it just give 
position 
icon 
title 

need to put my data

**Comment by wf9a5m75** [comment]
Just add your data, then use `get()` method to obtain it.

**Comment by wearta** [comment]
can u give me example please

**Comment by wf9a5m75** [comment]
Duplicated.

**Comment by wf9a5m75** [comment]
```
marker = this.map.addMarkerSync({
  position: ....,
  title: ....,
  myData: "hello world"
});

console.log(marker.get("myData"));
```

**Comment by wearta** [comment]
i did that but not work for my 

marker = this.map.addMarker({
position : ...,
icon : .....,
placeid : ...
}):

marker.on(GoogleMapsEvent.MARKER_CLICK,).subscribe(()=>{
var theplaceid = marker.get('placeid'):
alert(thepaceid):
}); 



this is my code put not working and not get the alert 
i use ( cordova-plugin-googlemaps  2.6.2 )

please help

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository.

**Comment by wearta** [comment]
@wf9a5m75 did u see my code 

what is wrong in it

**Comment by wf9a5m75** [comment]
I'm not your teacher or friend. Please do not still my private time. Please share your project files to reproduce your issue, otherwise close the issue

**Comment by phiasco12** [comment]
@wearta 

This is how you should be passing parameters and getting the parameters back when the marker is tapped on:


```
marker = map.addMarker({
          position: {lat: XXXXXXX, lng: XXXXXXXX},
          title: "Some title goes here",
          snippet: "This plugin is awesome!",
          _id: locations[i][4],
          animation: plugin.google.maps.Animation.BOUNCE	  
        });


  marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
    alert(marker.get("_id"));
  });
```

**Comment by phiasco12** [comment]
@wearta 

Done.

here is what you need to do:


```
marker = map.addMarker({
          position: {lat: XXXXX, lng: XXXXXX},
          title: "Some title goes here",
          snippet: "This plugin is awesome!",
		  icon: 'marker.png',
		   _id: 'myID',
          animation: plugin.google.maps.Animation.BOUNCE
}, function(marker) {
   marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
      alert(marker.get("_id")); 
   });
		
});
```

This works with multiple Markers too.

Happy coding. :)

**Comment by wf9a5m75** [comment]
`IMPORTANT: The word 'id' is reserved by this plugin` is old.

In the latest version, '_id' is reserved word. 'id' is not reserved word.

**Comment by phiasco12** [comment]
@wf9a5m75 thank you for the update. I take a note of that as i will be updating to the latest version soon.
