### ISSUE TITLE
Phonegap cli-8.1.1 build problem

### ISSUE THREAD

**Issue by uroskivi** [mapsplugin/cordova-plugin-googlemaps#2638]
I have a problem including the plugin for iOS on the Phonegap build.
I'm using the latest phonegap version cli-8.1.1 (4.5.5 / 7.1.2 / 6.0.1).

The app builds, but the map won't load, it says "cordova-plugin-googlemaps is not installed or not ready yet".

In the phonegap build log it says: 
"Installing "cordova-plugin-googlemaps" at "2.6.2" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.5.5, failed version requirement: >=5.0.0".

Is there anyway to include the plugin for the 4.5.5 version? As I see there is no phonegap version that supports the 5.0.0 yet?

Thank you.

**Comment by phiasco12** [comment]
can you please provide your javascript and your config.xml file?

**Comment by uroskivi** [comment]
On Android the javascript works fine. The problem is with including/installing the plugin on iOS.

```
ionViewDidLoad()
  {
/*...*/
    this.platform.ready().then(() => {
      if(this.isPrivate)
      {
        this.getBoxInfo();
      }
    });
/*...*/
  }

getBoxInfo()
  {
  /*....*/
                  this.createMap();
/*...*/
  }

 createMap()
 {
/*..*/
    let mapOptions: GoogleMapOptions = {
      camera: {
        target: {
          lat: this.geoLat,
          lng: this.geoLong
        },
        zoom: 16,
        tilt: 30
      }
    };
    this.map = GoogleMaps.create('map_canvas', mapOptions);
/*..*/
}
```
Thats in my config.xml file (for phonegap build):

<gap:plugin name="cordova-plugin-googlemaps" source="npm">
    <variable name="API_KEY_FOR_ANDROID" value="***" />
    <variable name="API_KEY_FOR_IOS" value="***" />
</gap:plugin>

And thats in the log file:

> Fetching plugin "cordova-plugin-googlemaps" via npm
> Installing "cordova-plugin-googlemaps" at "2.6.2" for ios
> Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.5.5, failed version requirement: >=5.0.0
> Skipping 'cordova-plugin-googlemaps' for ios

**Comment by RonaldPK** [comment]
Not sure about Phonegap, but using Cordova I could work around the issue by installing 5.0.1. Works fine.

`cordova platform remove ios`
`cordova platform add ios@5.0.1`

**Comment by uroskivi** [comment]
Yeah, the problem is building it on Phonegap, as I see there is no support for >=5.0.0 yet.

**Comment by phiasco12** [comment]
have you tried to install the plugin this way?

```
    <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="(API KEY)" />
    <preference name="GOOGLE_MAPS_IOS_API_KEY" value="(API KEY)" />
    <plugin name="cordova-plugin-googlemaps" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps" />
    <engine name="ios" spec="^5.0.1" />
```

**Comment by phiasco12** [comment]
This is the example:

https://github.com/mapsplugin/HelloGoogleMap/blob/master/config.xml

**Comment by uroskivi** [comment]
Yeah that worked! Thank you very much!
