### ISSUE TITLE
Ionic 3 demo broken due to version 2.4.6 -> 2.6.2 incompatibility in cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by y-a-n-n** [mapsplugin/cordova-plugin-googlemaps#2639]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "4.14.0",
    "@ionic-native/google-maps": "4.14.0",
```

**Current behavior:**
Steps to reproduce:
1. Clone https://github.com/mapsplugin/ionic-googlemaps-quickdemo.git
2. Run `npm install`
3. Run `ionic cordova prepare`
4. Run `ionic cordova build android`

Result:
```
FAILURE: Build failed with an exception.

* Where:
Script '<redacted>\ionic-googlemaps-quickdemo\platforms\android\cordova-plugin-googlemaps\quickdemo-apikey.gradle' line: 54


* What went wrong:
A problem occurred evaluating script.
> Please add '<preference name="GOOGLE_MAPS_ANDROID_API_KEY" />' to the config.xml file.
```

**Expected behavior:**
Project in demo repository should build successfully without any manual configuration changes

**Additional information**
It seems that somewhere between version 2.4.6 and 2.6.2 of the plugin, the requirement was added for `<preference name="GOOGLE_MAPS_ANDROID_API_KEY" />` in the config.xml file. Because the demo has a dependency on `"cordova-plugin-googlemaps": "^2.4.6",` it resolves to version 2.6.2, but doesn't have the required preference in config.xml

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#api-key-android-and-ios-platforms

**Comment by y-a-n-n** [comment]
Hi, thanks for the reply. I understand what configuration is needed. This ticket is to point out that the ionic 3 demo at https://github.com/mapsplugin/ionic-googlemaps-quickdemo is broken in its current form. Anyway, if that doesn't matter, feel free to close this ticket.

**Comment by wf9a5m75** [comment]
Thank you. I updated the repo.
