### ISSUE TITLE
Bug in RGBA color conversion in Common.js

### ISSUE THREAD

**Issue by calrsom** [mapsplugin/cordova-plugin-googlemaps#2640]
The CSS RGBA alpha value should be multiplied by *255* not 256, so the range [0, 1] maps to [0, 255].  On Android the color values are not checked and it appears the low 8 bits are taken, so a CSS alpha of 1 -> 256 -> 0 becomes transparent.

 * https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/64fff8a30a13b026526d927fb7511c76dbea64a6/www/Common.js#L92
 * https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/64fff8a30a13b026526d927fb7511c76dbea64a6/www/Common.js#L92

Should be:
```
alpha = matches.length == 4 ? Math.floor(parseFloat(matches[3]) * 255) : alpha;
```

**Comment by wf9a5m75** [comment]
Ah, please send me a pull request.

**Comment by wf9a5m75** [comment]
Fixed. Thanks.
