### ISSUE TITLE
Remove some point of polyline

### ISSUE THREAD

**Issue by kovaneth** [mapsplugin/cordova-plugin-googlemaps#2641]
Hello,

Can we remove a part of polyline ?

Thanks

**Comment by wf9a5m75** [comment]
```js
var HND_AIR_PORT = {lat: 35.548852, lng: 139.784086};
var SFO_AIR_PORT = {lat: 37.615223, lng: -122.389979};
var HNL_AIR_PORT = {lat: 21.324513, lng: -157.925074};
var AIR_PORTS = new plugin.google.maps.BaseArray([
  HND_AIR_PORT,
  HNL_AIR_PORT,
  SFO_AIR_PORT
]);

var polyline = map.addPolyline({
  'points': AIR_PORTS,
  'color' : '#AA00FF',
  'width': 10,
  'geodesic': true
});

polyline.on(plugin.google.maps.event.POLYLINE_CLICK, function(latLng) {
  AIR_PORTS.removeAt(1);
});
```

**Comment by kovaneth** [comment]
plugin.google.maps.BaseArray is not a constructor

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/class/BaseArrayClass

**Comment by kovaneth** [comment]
So i didnt understand the error come from what?

**Comment by wf9a5m75** [comment]
Please make a question with proper information.

**OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Comment by kovaneth** [comment]
OS: (check one with "Huawei mate 10")
cordova plugin list 
cordova plugin list
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.0-dev "Camera"
cordova-plugin-device 2.0.3-dev "Device"
cordova-plugin-dialogs 2.0.2-dev "Notification"
cordova-plugin-file 6.0.2-dev "File"
cordova-plugin-file-transfer 1.7.2-dev "File Transfer"
cordova-plugin-geolocation 4.0.2-dev "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.1.0-dev "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-splashscreen 5.0.4-dev "Splashscreen"
cordova-plugin-statusbar 2.4.3-dev "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"

**Comment by wf9a5m75** [comment]
Do you use ionic or not?

**Comment by kovaneth** [comment]
no i dont use ionic

**Comment by wf9a5m75** [comment]
```
var mvcArray = new plugin.google.maps.BaseArrayClass();

// Catch the insert_at event when you insert new value to the mvcArray each time.
mvcArray.on("insert_at", function(index) {
  console.log("---> [insert_at] position : " + index + ", value : " + this.getAt(index));
});

// Catch the set_at event when you change an element with new value.
mvcArray.on("set_at", function(index, oldValue) {
  console.log("---> [set_at] position : " + index + ", value : " + this.getAt(index));
});

// Catch the remove_at event when you delete an element from the mvcArray each time.
mvcArray.on("remove_at", function(index, oldValue) {
  console.log("---> [remove_at] position : " + index + ", value : " + oldValue);
});

mvcArray.push("A");       // ---> [insert_at] position : 0, value : "A"
mvcArray.push("B");       // ---> [insert_at] position : 1, value : "B"
mvcArray.push("C");       // ---> [insert_at] position : 2, value : "C"

mvcArray.pop()            // ---> [remove_at] position : 2, value : "C"

mvcArray.setAt(2, "D");   // ---> [set_at] position : 1, value : "B"

console.log(mvcArray.getArray());  // "A", "D"
```

**Comment by kovaneth** [comment]
Thanks the array work, but the 
`polyline.on(plugin.google.maps.event.POLYLINE_CLICK, function(latLng) {
  AIR_PORTS.removeAt(1);
});`

is not firing.

**Comment by wf9a5m75** [comment]
Please share your project files on github repository.

**Comment by kovaneth** [comment]
i need to add 'clickable': true to the polyline thanks

**Comment by wf9a5m75** [comment]
There are many documents. Please read, try and error, by yourself before asking.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc
