### ISSUE TITLE
Cannot see map when --background is set in Ionic 4

### ISSUE THREAD

**Issue by kelvindart** [mapsplugin/cordova-plugin-googlemaps#2643]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase-analytics 2.0.4 "FirebaseAnalyticsPlugin"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-transport-security 0.1.2 "App Transport Security"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 5.5.1
@ionic-native/google-maps : 5.5.0
```

**Current behavior:**
Whenever I attempt to use the plugin in an Ionic 4 project with `--background` set, I cannot see the Google Map displayed.

If I remove the `--background` property, the map renders fine. Even setting the property to something very simple like just a colour seems to cause the bug to occur, i.e. `--background: white;`. I therefore do not know if this issue is Ionic's problem, or the plugin maintainer here...

I have take some screenshots to further illustrate my problem. I also receive the following line in the Xcode console. But I doubt this is related.

```
2019-06-14 13:29:09.181929+0100 MyMapps[24530:1452077] ERROR: Plugin 'map_2_34074899756' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2019-06-14 13:29:59.613137+0100 MyMapps[24530:1452077] FAILED pluginJSON = ["INVALID","map_2_34074899756","detachFromWebView",[]]
```

If I remove the background property, the map works as expected. If you'd like me to isolate a project with the issue, I can do. Just let me know.

**Expected behavior:**
For the Google Map area to display when `--background` has been set.

**Screen capture or video record:**
*Issue:*
![working](https://i.ibb.co/FXNM63n/Screen-Shot-2019-06-14-at-14-02-52.png)

*Working:*
![background set](https://i.ibb.co/RBjhyGD/Screen-Shot-2019-06-14-at-14-02-54.png)

**Related code, data or error log (please format your code or data):**
Happy to create an isolated incident upon request 🙂

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#how-does-this-plugin-work-android-ios

**Comment by kelvindart** [comment]
Ohhh makes sense! Thanks so much 🙂 I'll have to turn off the background for this page then.
