### ISSUE TITLE
Ionic 5 googlemaps on iOS now crashes at changeCameraPosition

### ISSUE THREAD

**Issue by aircable** [mapsplugin/cordova-plugin-googlemaps#2644]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android** works just fine
- [x] **iOS** crashes
- [ ] **Browser** works just fine

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-orientation 2.0.1 "Device Orientation"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^5.8.0",
"@ionic-native/google-maps": "^5.5.0",
"cordova-plugin-googlemaps": "^2.6.2",
```

**Current behavior:**
Every call to any of the maps API with location information (marker, camera etc.) crashes on iOS only.
It happened after upgrade to Ionic 5 and the latest plugin googlemaps, my app crashes on iOS 12. Android and Browser are working just fine. Whenever I pass position information (lat, lng) into a maps call, I get this error. Only on iOS.

**Related code, data or error log (please format your code or data):**

```
this.map = GoogleMaps.create(this.mapElement.nativeElement, mapOptions);
    console.log("create maps");
this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => {
        console.log("ready")
        // Get the location of you
        return this.map.getMyLocation()
      })
.then((location: MyLocation) => {
        // Move the map camera to the current location with animation
        console.log(`move camera to ${location.latLng}`)
        this.map.animateCamera({
          target: location.latLng,
        });
      })
```
I get this error on Xcode 10.
```
2019-06-13 17:36:28.977662-0700 EnsurityAL[818:342922] move camera to {"lat": 36.99274272626102, "lng": -121.97547187118792} 
2019-06-13 17:36:28.979604-0700 EnsurityAL[818:342922] -[NSNull doubleValue]: unrecognized selector sent to instance 0x1be0b17e0
2019-06-13 17:36:28.994666-0700 EnsurityAL[818:342922] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull doubleValue]: unrecognized selector sent to instance 0x1be0b17e0'
```

Please let me know if I can get better information from Xcode where it actually happens. Seems to me a conversion problem between code and native. I have seen old references to this problem before maps@5 but not lately. version >5, like this one:
[#1478](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1478)
But I don't pass any more parameter in that the on in the source. Even using a fixed string leads to the same error.

![Screen Shot 2019-06-14 at 10 56 24 AM](https://user-images.githubusercontent.com/831110/59528508-517d1780-8e93-11e9-8ac4-774e7cda73e4.png)

**Comment by wf9a5m75** [comment]
![2644](https://user-images.githubusercontent.com/167831/59545327-a8a1dd00-8ed1-11e9-8295-40ae5316c7e9.gif)

**Comment by wf9a5m75** [comment]
I exactly tested with the same environment and code, I can't reproduce your issue.

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, please share your project files on github repository.

**Comment by aircable** [comment]
Just invited you to the private repo.
Once you did get the app working on iOS you need this code in the project
ID. *MTkwNzE0*
Then switch to the first tab (maps page) and you'll get the error.

Again, Android and Browser all work fine. Just iOS crashes

**Comment by wf9a5m75** [comment]
```

ERROR in src/app/app.module.ts(20,25): error TS2307: Cannot find module '../../3rdparty/Ionic4ibeacon/ngx'.
src/app/assets/assets.page.ts(17,50): error TS2307: Cannot find module '../../../3rdparty/Ionic4ibeacon/ngx'.
```

**Comment by wf9a5m75** [comment]
It seems you need to give me permission to above repositories.

**Comment by aircable** [comment]
>>> NOT WORKING: npm install @ionic-native/ibeacon
// need to patch iBeacon for Ionic4
mkdir 3rdparty; cd 3rdparty
git clone https://github.com/IT-Dan/Ionic4ibeacon.git
// instead of @ionic-native/ibeacon/ngx
import { IBeacon, IBeaconDelegate } from
'../../../3rdparty/Ionic4ibeacon/ngx';

**Comment by wf9a5m75** [comment]
Please reinstall the maps plugin from the multiple_maps of this repository.

**Comment by aircable** [comment]
Thank you, that did it. 
For IONIC developers on iOS native, branch multiple_maps is required
```
ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
```
Angular:
```
npm --save install git://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps
```
