### ISSUE TITLE
Keep full changelog

### ISSUE THREAD

**Issue by ziyaddin** [mapsplugin/cordova-plugin-googlemaps#2645]
**Please tell us your new feature idea**

Keeping full changelog instead of changelog just for current minor version.

**Why do you need it?**

It is more convenient to look up full changelog to see the "big picture" of changes.

**How helps other people?**

It is more convenient to look up full changelog to see the "big picture" of changes.

**Comment by wf9a5m75** [comment]
Please look git commit log.
