### ISSUE TITLE
bring back default launchNavigation 

### ISSUE THREAD

**Issue by irreprehensible** [mapsplugin/cordova-plugin-googlemaps#2647]
Earlier the launchNavigation was used as
plugin.google.maps.external.launchNavigation({
      "from": frmlatlng,
      "to": toLatlng,
      "travelMode": "driving"
    });
now we need to use the phonegap-launch-navigator pluin that launches the apps fine, but we need to share the API KEY for google maps plugin AND phonegap-launch-navigator, if the plugin.google.maps.external.launchNavigation({ ... is brought back, it would be helpful, as for those who just want to enable navigation of any kind, and no need to have the API key mention twice in config (using phongap BUILD here)

**Why do you need it?** **How helps other people?**

* it removes the need to use the api keys twice
* You do not need to use two plugins (coz youré already using cordova-google-maps)
* Default navigation is made simple
If there is a dire need to select the application for navigation, then the  launch-navigator plugin might be useful, but for those of us (maybe just me) who simple need the default nevigation the external.launchNavigation method was fine.

**Comment by wf9a5m75** [comment]
No plan to bring back it.  phonegap-launch-navigator plugin covers not only Google maps but also other map apps. I don't want to catch up them.

All source code of this plug-in is open even v1.x.
Please check out the code.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v.1.4.5/www/googlemaps-cdv-plugin.js#L2444-L2458
