### ISSUE TITLE
Add and remove maps div issues - stress testing

### ISSUE THREAD

**Issue by alex116** [mapsplugin/cordova-plugin-googlemaps#2650]
**I'm submitting a ...**
- [X ] any problem or bug report

**OS:**  (check one with "x")
- [X ] **Android** 

**cordova information:**
testproject> cordova plugin list
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"

testproject> cordova --version
8.0.0

Android OS 9
OnePlus 6

**Current behavior:**
 This project creates a map
zooms to germany,poland,finland,sweden
creates lots of random mapmarkers
deletes the map
Loops <<<<

I am trying to get it to safely create and delete maps.

I edited the config.xml to point to my computer's http://192.168.10.45:8000/index.html. 
On my PC I cd to the testproject/www folder and run a python webserver:
> python -m http.server 8000

That way I can edit my files in chrome and just reload the page to get the updated version. 
You can change the config.xml back so the index points to "index.html" and run it.

At some point it crashes on my phone. Attached is a logfile
[hellocordova.crash.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/3370103/hellocordova.crash.txt)

**Expected behavior:**
I expect it to keep running. I hope I am doing something wrong and you can tell me how to do it correctly.

My project is here: 
https://github.com/alex116/cordova-maps-issue.git

I have deleted my API key that is present in the config.xml, from my google console.

**Comment by wf9a5m75** [comment]
It seems you run the plugin in-proper way. Regarding of the crash log, your app does not load necessary JS files properly.

If you want to use `live-reload`, I recommend you use `cordova-plugin-browsersync` or `ionic`.
https://github.com/mapsplugin/cordova-plugin-googlemaps#browser-platform

**Comment by alex116** [comment]
Thank you for your quick reply,
 
I changed the config.xml to load from local resources. 
The `Unexpected response code 400`  error does not appear in the logs any more. 

The `java.util.ConcurrentModificationException` still appears after about 5-10 iterations. 
I committed and pushed my change. 

My Project: 
https://github.com/alex116/cordova-maps-issue.git

My new crash log: 
[hellocordova.crash.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/3374246/hellocordova.crash.txt)

Would you be so kind and please have another look? 
Thank you for your help.

**Comment by wf9a5m75** [comment]
Please use this plugin in normal way.

**Comment by alex116** [comment]
I am confused. 
I followed the instructions to create this example. 
It is a valid use case because I have many markers on my map, my device gets overloaded and users are unpredictable. 
I would like to load and remove the map without the app crashing. 
I am simulating an impatient user that opens and closes a map with many points before all points have loaded. 
What do you mean when you say to use it in a normal way?

**Comment by wf9a5m75** [comment]
You write "run a python webserver". This is not normal way.

**Comment by alex116** [comment]
Ah now I understand. I already fixed that in this comment: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2650#issuecomment-509747003
That is why I was still confused. I guess that means it is running normally now. 
It does not use the python web server any more. 
> I changed the config.xml to load from local resources.

**Comment by JordyLangen** [comment]
We are experiencing similar issues with our app in production.
There is no proper way to reproduce it (other then performing stress tests), but we see this every once in a few days:

```
Fatal Exception: java.lang.RuntimeException
Caused by java.util.ConcurrentModificationException
plugin.google.maps.CordovaGoogleMaps.onDestroy

java.util.LinkedHashMap$LinkedHashIterator.nextEntry (LinkedHashMap.java:346)
java.util.LinkedHashMap$ValueIterator.next (LinkedHashMap.java:370)
**plugin.google.maps.CordovaGoogleMaps.onDestroy (CordovaGoogleMaps.java:540)**
org.apache.cordova.PluginManager.onDestroy (PluginManager.java:297)
org.apache.cordova.CordovaWebViewImpl.handleDestroy (CordovaWebViewImpl.java:484)
org.apache.cordova.CordovaActivity.onDestroy (CordovaActivity.java:315)
android.app.Activity.performDestroy (Activity.java:6442)
android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1143)
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:3877)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:3908)
android.app.ActivityThread.access$1500 (ActivityThread.java:157)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1410)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5551)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:734)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:624)
```

It seems to be related to this following setup of code:

```
Collection<PluginEntry>pluginEntries = pluginManager.getPluginEntries();
for (PluginEntry pluginEntry: pluginEntries) {
  // logic
}
```

We've also seen crashes in the other Adroid lifecycle method (`onPause` for example) that had the same exception.

Would it make sense to handle the entries from `getPluginEntries` so the `ConcurrentModificationException` no longer occurs?

**Comment by wf9a5m75** [comment]
Please send a pull request.

**Comment by JordyLangen** [comment]
@wf9a5m75 that would result in an hotfix/workaround, not a root cause fix.

Why is the `getPluginEntries()` result throwing `ConcurrentModificationException`?

**Comment by wf9a5m75** [comment]
> Why is the getPluginEntries() result throwing ConcurrentModificationException?

I don't know.
