### ISSUE TITLE
Map is draggable from the HTML elements below the map canvas

### ISSUE THREAD

**Issue by ppetree** [mapsplugin/cordova-plugin-googlemaps#2653]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android** 6.0, 7.0
- [x] **iOS** 10.x, 11.x 12.x
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps   	npm	2.5.3 	android,ios,
cordova-plugin-statusbar   	npm	2.4.3	 	android,ios,
cordova-plugin-whitelist   	npm	1.3.4	 	android,ios,
```

**Platform**
Phonegap Build 8.1.1

**Plugin Version**
2.5.3 (the last version that will build on PGB)

**Current behavior:**
**When it the plugin works correctly:**
Page is loaded, becomes static, press a button to draw the map and the map gets drawn and all touch events are handled as expected.

**When the bug rears its nasty head:**
Load the page, trigger some code (ajax works) that will retrieve some information, populate some fields above the map, draw the map using coordinates from the ajax call. Once the page is fully drawn and depending on the device and/or os version you can sometimes move the map from the map div but you can always move the map by moving your finger on the elements below the map_canvas div. 

**Expected behavior:**
Moving your finger on the mobile device outside of the map_canvas should NOT move the map!

**Screen capture or video record:**
[YouTube Video](https://www.youtube.com/watch?v=3m3FimlmRwI)

**Related code, data or error log (please format your code or data):**

```
https://github.com/ppetree/plugin-googlemaps-bug
```

**Comment by wf9a5m75** [comment]
Since I don't support old versions, please use v2.6.2 at least.

**Comment by ppetree** [comment]
So you're no longer supporting Phonegap Build?  v2.6.x will not build on PGB as you started requiring cli 9.0 and PGB is topped out at 8.1.1.

**Comment by ppetree** [comment]
This issue exists on 2.6.x as well.  The problem is when the page is scrolled, you're not adjusting your touch event handlers to the new screen coordinates of the map_canvas. smh
