### ISSUE TITLE
HTMLInfoWindow odd padding

### ISSUE THREAD

**Issue by adamduren** [mapsplugin/cordova-plugin-googlemaps#2654]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-applepay 5.0.0 "Apple Pay"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-firebase-analytics 2.0.3 "FirebaseAnalyticsPlugin"
cordova-plugin-firebase-config 2.0.3 "cordova-plugin-firebase-config"
cordova-plugin-firebase-dynamiclinks 2.0.3 "FirebaseDynamicLinksPlugin"
cordova-plugin-firebase-messaging 2.1.5 "FirebaseMessagingPlugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.2.1 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 5.7.0
@ionic-native/google-maps : 5.5.0
```

**Current behavior:**
`contentBox.style.padding = '5px 17px 17px 5px';`
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/HtmlInfoWindow.js#L252

**Expected behavior:**
Padding is symmetrical or configurable
`contentBox.style.padding = '5px 17px';`

**Screen capture or video record:**

![image](https://user-images.githubusercontent.com/581097/61254659-1aac5280-a71a-11e9-9720-28e9cf56bfbe.png)

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by adamduren** [comment]
Hello @wf9a5m75, just looking for information around why the padding is set the way it is. Is it intentional to have left not equal to right as well as top not equal to bottom or a mistake in order?

**Comment by wf9a5m75** [comment]
HTMLInfoWindow class sets padding by default in order to display text.
However, you can control css ether using `cssOptions` or `.pgm-html-info-frame` class.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/HtmlInfoWindow.js

**Comment by adamduren** [comment]
Thanks for the info. I was unaware of `cssOptions` must have missed it in the docs. I still don't understand why the padding is as such.
![image](https://user-images.githubusercontent.com/581097/61255052-dcb02e00-a71b-11e9-83b9-790915bd3df4.png)

However having a way to override it is sufficient.

**Comment by adamduren** [comment]
If it is intentional to be those values I will close this.

**Comment by wf9a5m75** [comment]
`cssOptions`
https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/htmlinfowindow/README.md#setcontentstring--htmlelement-cssoptions

and 

you can override css properties

```css
. pgm-html-info-content-box {
  padding: 0px !important;
}
```
