### ISSUE TITLE
Is it possible to open htmlInfoWindow as soon as adding marker?

### ISSUE THREAD

**Issue by JeongJun-Lee** [mapsplugin/cordova-plugin-googlemaps#2657]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

It is not possible to open htmlInfoWindow  as soon as adding marker.

**Expected behavior:**

As soon as adding marker, htmlInfoWindow is shown at the same time without clicking icon once more.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```
`
let htmlInfoWindow = new HtmlInfoWindow();

      let frame: HTMLElement = document.createElement('div');
      frame.innerHTML = [
        '<h3>Hearst Castle</h3>',
        '<img src="assets/hearst_castle.jpg">'
      ].join("");
      frame.getElementsByTagName("img")[0].addEventListener("click", () => {
        htmlInfoWindow.setBackgroundColor('red');
      });
      htmlInfoWindow.setContent(frame, {
        width: "280px",
        height: "330px"
      });

      this.map.addMarker({
        position: {lat: 35.685208, lng: -121.168225},
        draggable: true,
        disableAutoPan: true
      }).then((marker: Marker) => {

        // Without clicking icon additionally
        //marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
          htmlInfoWindow.open(marker);
        //});

      });
`

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by adamduren** [comment]
@JeongJun-Lee I adjusted your code to programmatically open the InfoWindow on Marker creation. Is this what you're looking for? (see last line)
```typescript
  const htmlInfoWindow = new HtmlInfoWindow();
  const frame: HTMLElement = document.createElement('div');
  frame.innerHTML = [
    '<h3>Hearst Castle</h3>',
    '<img src="assets/hearst_castle.jpg">'
  ].join("");

  frame.getElementsByTagName("img")[0].addEventListener("click", () => {
    htmlInfoWindow.setBackgroundColor('red');
  });

  htmlInfoWindow.setContent(frame, {
    width: "280px",
    height: "330px"
  });

  const marker = await this.map.addMarker({
    position: {lat: 35.685208, lng: -121.168225},
    draggable: true,
    disableAutoPan: true
  })

  // Without clicking icon additionally
  marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
    htmlInfoWindow.open(marker);
  });

  // Trigger marker click programmatically
  marker.trigger(GoogleMapsEvent.MARKER_CLICK, undefined, marker);
```

**Comment by JeongJun-Lee** [comment]
Thank you for your quick answer. but the last code doesn't work.
I am using "cordova-plugin-googlemaps": "2.6.2". Is there any clue?

**Comment by adamduren** [comment]
@JeongJun-Lee I'm not sure. I am doing something similar and it works. If you can share a repo I can take a look.

**Comment by JeongJun-Lee** [comment]
I am using this plugin at Ionic 4. When the last code is applied, the result is like below.
Only arrow without content.

![image](https://user-images.githubusercontent.com/11474775/61517338-74fe2980-aa20-11e9-920b-4c035d2d6399.png)

**Comment by wf9a5m75** [comment]
Check your car with chrome inspector or safari web debugger

**Comment by JeongJun-Lee** [comment]
Right. MARKER_CLICK works. It's another issue. So I create new issue.
