### ISSUE TITLE
Is this will work on capacitor?

### ISSUE THREAD

**Issue by rosnaib11** [mapsplugin/cordova-plugin-googlemaps#2658]
Is this supported by capacitor? I mean that when I run it using `ionic capacitor run android`  will it works on native device/emulator?

**Comment by wf9a5m75** [comment]
No

**Comment by Mapiac** [comment]
It will work on Android apparently not iOS

**Comment by dupiesdupreez** [comment]
Whoopty whooopty dooo, just running around chasing your tail, Install a plugin here, remove a plugin there, conflicts, errors, not supported, un supported, no documentation.

Open source Is the worst decision of my life

**Comment by dupiesdupreez** [comment]
For any one wanting to use google maps with Capacitor, you can follow this tutorial. 
It works for both android and IOS, tested it myself.

You have to create a component in the way the tutorial shows you.

[Using Google Maps and Geolocation in Ionic with Capacitor
](https://www.joshmorony.com/using-google-maps-and-geolocation-in-ionic-with-capacitor/)

**Comment by wf9a5m75** [comment]
I made a fundraising to implement the code for supporting Capacitor iOS.
Please join and support the project!

[Fundraising: Support for Capacitor iOS platform](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781)
