### ISSUE TITLE
Polygon fill becoming transparent at low zoom level.

### ISSUE THREAD

**Issue by guillerial** [mapsplugin/cordova-plugin-googlemaps#2659]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**Current behavior:**
Polygon fill becoming transparent at low zoom level.

**Expected behavior:**
Polygon fill **not** becoming transparent at low zoom level.

**Notes:**
Hi, this is a known bug from google maps SDK: https://issuetracker.google.com/issues/35822872

They said that it's solved in google maps sdk v3.0.0 beta, where they solved a lot of issues, but without changing the API surface: https://developers.google.com/maps/documentation/android-sdk/v3-client-migration

**Finally, the question:**
Will you make any update or branch for cordova library pointing to that v3.0.0 beta? or will you wait until they release that beta?

Thank you! I really appreciate your work.

**Comment by wf9a5m75** [comment]
Your Cordova and cordova-ios are old.

This plugin uses 3.1 sdk
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L479

**Comment by wf9a5m75** [comment]
```
$> cordova platform rm ios

$> npm uninstall -g cordova

$> npm -g install cordova@latest

$> cordova platform add ios@latest
```

**Comment by guillerial** [comment]
This happens to me in android, not ios...

**Comment by wf9a5m75** [comment]
Umm, beta version sdk.

**Comment by guillerial** [comment]
Yep :S

**Comment by guillerial** [comment]
Is it very hard to implement?

**Comment by wf9a5m75** [comment]
Please reinstall the maps plugin from the `2659test` branch.
And you need to add following nodes in `config.xml`.

```xml
<!-- required -->
<preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="(YOUR API KEY)" />

<!-- optional -->
<preference name="GOOGLE_MAPS_ANDROID_SDK" value="maps-sdk-3.0.0-beta" />

<!-- optional -->
<preference name="ANDROID_SUPPORT_V4_VERSION" value="27.1.1" />

<!-- optional -->
<preference name="GOOGLE_MAPS_PLAY_SERVICES_VERSION" value="16.0.0" />
```

**Comment by wf9a5m75** [comment]
Now on multiple_maps branch is available.
