### ISSUE TITLE
Feature request: mylocation without button

### ISSUE THREAD

**Issue by carsten19** [mapsplugin/cordova-plugin-googlemaps#266]
The SDK supports a separate toggle of the user location and the mylocation button:
mapView_.myLocationEnabled = YES;
vs
mapView_.settings.myLocationButton = YES;

It would be great if you could add this to your API as I would like to show the user location and the map but I don't want the button.

**Comment by lakano** [comment]
Hello,

This feature will be really usefull ( I only need MyLocation, not the button ).
May be the last version of the SDK have fixed the bug, now ?

Thanks :)

**Comment by dafi87** [comment]
I'd highly appreciate this feature. Only need the location showing but not the button.

**Comment by lakano** [comment]
Yep, but I'm not sure @wf9a5m75 is notified on closed ticket ( already tried 1 month ago .. ).

This could be really usefull !

**Comment by githubkyo** [comment]
who fix this problem?

**Comment by dafi87** [comment]
I'm just using my own location service and updating a dedicated map marker (blue dot) on location changes. Not ideal, though.

**Comment by iBasit** [comment]
+1

**Comment by wf9a5m75** [comment]
**update**
The v2.2.0 allows you to control the myLocationButton and the myLocation (blue dot) separately.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.2.0/README.md#the-mylocation-property-is-changed
