### ISSUE TITLE
crash on android

### ISSUE THREAD

**Issue by rall** [mapsplugin/cordova-plugin-googlemaps#2662]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:** 

cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-customconfigparameters 3.0.0 "Custom Config Parameters"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

```
07-29 18:29:07.488  6774  6774 E AndroidRuntime: FATAL EXCEPTION: main
07-29 18:29:07.488  6774  6774 E AndroidRuntime: Process: io.ionic.starter, PID: 6774
07-29 18:29:07.488  6774  6774 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference
07-29 18:29:07.488  6774  6774 E AndroidRuntime: 	at plugin.google.maps.MyPluginLayout$1.run(MyPluginLayout.java:122)
07-29 18:29:07.488  6774  6774 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-29 18:29:07.488  6774  6774 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-29 18:29:07.488  6774  6774 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-29 18:29:07.488  6774  6774 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-29 18:29:07.488  6774  6774 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 18:29:07.488  6774  6774 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-29 18:29:07.488  6774  6774 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-29 18:29:07.491  1159  2049 W ActivityManager:   Force finishing activity io.ionic.starter/.MainActivity
```

```
    "@ionic-native/core": "^5.8.0",
    "@ionic-native/google-maps": "^5.5.0",
```

**Current behavior:**

The app crashed when I navigate to the map page

**Expected behavior:**

No crash

```
https://github.com/rall/yelper
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
The error means you tried to create a map before native side has been ready.

**Comment by rall** [comment]
thanks! I wonder why that would be on an android device but not an iOS simulator? I will investigate.

**Comment by wf9a5m75** [comment]
This plugin uses `native google maps` not `JavaScript google maps` on Android and iOS.
https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios

It means the implementations in Android and iOS are different.
iOS works fine, but why not Android are nonsense question (not blaming you, but many people asked), because code is different (= different software).

**Comment by rall** [comment]
I'm not so much asking why it's different internally, more what I have to change in my code to make android work properly. I'm waiting for `platform.ready()` which I understood to be sufficient (and certainly seemed to be for android on the Ionic 3 app I worked on recently.)

But thanks for your swift reply and the good direction. I have something to work on now to attempt to resolve. I'll report back in this issue if I make any discovery

Also, thank you for your great work on this plugin. It must be an enormous undertaking and it's really genuinely appreciated. The performance improvement of this plugin over a javascript rendered alternative is quite significant.

**Comment by wf9a5m75** [comment]
Did you solve your problem?

**Comment by rall** [comment]
I still get the occasional crash calling `setDiv` on Android, but I had some success with this RxJS stream:


`showMap$:Observable<GoogleMap>` emits when map should render, ie. after `platform.ready()`
```
scheduled(showMap$, animationFrameScheduler).pipe(
    filter(([_, visible]) => Boolean(visible)),
    take(1),
).subscribe(([mapObject]) => mapObject.setDiv(this.domId));
```

Which can also be expressed using a callback:

```
const googleMap = GoogleMaps.create({});
requestAnimationFrame(() => googleMap.setDiv("map-canvas"));
```

Maybe this is useful to someone in the future. I'll close this ticket issue for now
