### ISSUE TITLE
Inconsistent htmlInfowindow height and width

### ISSUE THREAD

**Issue by rcpinheiro** [mapsplugin/cordova-plugin-googlemaps#2668]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-buildinfo 2.0.2 "BuildInfo"
cordova-plugin-camera 4.0.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"
cordova-plugin-device 2.0.3-dev "Device"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-geolocation 4.0.2-dev "Geolocation"
cordova-plugin-googlemaps 2.6.3-20190808-1526 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.1.0-dev "InAppBrowser"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
```

**Current behavior:**

For exactly the same htmlInfoWindow content, the height and width varies. Opening the same htmlInfoWindow in the same place and with the same content returns different results.
Example (htmlInfoWindow is &lt;div id="hook"&gt;&lt;h1&gt;Title&lt;/h1&gt;&lt;p&gt;Some description, size varies&lt;/p&gt;&lt;p&gt;Coordinates: 38.821069,-9.16273&lt;/p&gt;&lt;/div&gt;):

![1](https://user-images.githubusercontent.com/3802348/62820418-e92d7800-bb5b-11e9-9a22-b39b3ba4314d.png)
![2](https://user-images.githubusercontent.com/3802348/62820419-ea5ea500-bb5b-11e9-8d43-b3bc6f8478f1.png)

**Expected behavior:**

Consistent width and height.

**What I've tried:**
Tried changing CSS (a lot). The only thing that worked was to make all .pgm-info-* classes transparent and do all the formatting in the htmlInfoWindow CSS. It's an ugly solution and has problems on it's own.

**Comment by wf9a5m75** [comment]
You can use ` .pgm-info-* classes`,  it's not an ugly solution.

**Comment by rcpinheiro** [comment]
> You can use ` .pgm-info-* classes`, it's not an ugly solution.

I beg to differ. It doesn't make a lot to "delete" (make transparent) CSS classes and try to emulate their behaviour in a new class just because there's a bug in the javascript. And there's additional work to align the tail.

**Comment by rcpinheiro** [comment]
Another workaround is to have a fixed width. That way the bug in the calculations in htmlInfoWindow.js can be circumvented. It's not ideal but it works:

```
.myDiv {
    width: 210px !important;
}

.pgm-html-info-frame {
    width: 224px !important; // Bug fix
}
```
In .js:
```
            var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();
            htmlInfoWindow.setContent('<div class="myDiv"><p>Your content here</p>');
```

**Comment by wf9a5m75** [comment]
If you have an idea, please send a pull request.

**Comment by adamduren** [comment]
This inconsistency seems pretty minor. @rcpinheiro Can you provide a screenshot of the box model in different states? Looking for something like what is pictured [here](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2654#issuecomment-511604069)

**Comment by rcpinheiro** [comment]
The example I gave is not the best, but imagine having a button at the bottom of the InfoWindow that sometimes has some weird white space below. 
Here are two model boxes for exactly the same content taken one right after another:

![1](https://user-images.githubusercontent.com/3802348/62838965-276d8900-bc7b-11e9-93d0-5efdf72ff6ba.png)
![2](https://user-images.githubusercontent.com/3802348/62838967-29cfe300-bc7b-11e9-95a4-907e07ba1fc6.png)

**Comment by adamduren** [comment]
As a workaround in my project I have explicitly set the size of my content and it appears to give consistent results.

```typescript
class MyComponent {
  // ...other code
  private createAndPresentInfoWindow(
    marker: Marker,
    appointmentSummary: fromSearch.IAppointmentSummary,
    appointmentSummaryComp,
  ) {
    const clonedSummaryItem = appointmentSummaryComp.cloneNode(
      true,
    ) as HTMLElement;
    clonedSummaryItem.style.width = '300px';
    clonedSummaryItem.style.height = '219px';
    clonedSummaryItem.style.margin = '0 auto';
    clonedSummaryItem.setAttribute('no-border', '');
    clonedSummaryItem.style.cursor = 'pointer';

    this.currentPresentedInfoWindow = new HtmlInfoWindow();
    this.currentPresentedInfoWindow.setContent(clonedSummaryItem);
    this.currentPresentedInfoWindow.open(marker);

    clonedSummaryItem.addEventListener('click', () => {
      this.viewServiceProvider(appointmentSummary);
    });
}
```

**Comment by rcpinheiro** [comment]
Created a pull request that solves this bug.
