### ISSUE TITLE
cordova-ios 4.5.5 compatibility

### ISSUE THREAD

**Issue by UlisesCeca** [mapsplugin/cordova-plugin-googlemaps#2669]
Hello,

I need to install the plugin in a project which uses Cordova 9 and cordova-ios 4.5.5. Changing this is not an option.

I've seen the following in the releases notes from version 2.6.0:

`Update: (iOS) Specify the Google Maps SDK version as => 3.1.0. Please use cordova-ios@5.0.0 or above, otherwise modify platform/ios/Podfile`

What do I exactly need to fix to make the plugin work?

Thanks!

**Comment by wf9a5m75** [comment]
Since cordova-ios@4.5.5 requests min version ios7.0, you can't install Google Maps SDK for ios@3.1.0

**Comment by UlisesCeca** [comment]
> Since cordova-ios@4.5.5 requests min version ios7.0, you can't install Google Maps SDK for ios@3.1.0

so I'd just have to use the 2.7.0 version of the sdk? 

I'd have to modify some code on this plugin too I assume?

**Comment by UlisesCeca** [comment]
if we make a donation could you edit this for us in a new branch or something?

**Comment by wf9a5m75** [comment]
It's the problem of  Cordova and Google Maps SDK. Not code's problem.
