### ISSUE TITLE
Technical question: Drawable rect of the map

### ISSUE THREAD

**Issue by dorianrod** [mapsplugin/cordova-plugin-googlemaps#2670]
Hi,

Does someone known where I can find in the the part of code where the map is drawn, and more precisely when we decide the RECT position/size we use to not draw the webview? I looked in MyPluginLayout.java and tested few things without success.

Side note: sorry if it's obvisous but I'm not used to develop in java... still learning it :)

Thank you!

Have a good day

DR

-------------------

Details: 

WHAT I'D LIKE TO DO
I'd like to customize this plugin to my project because I get some issues related to map positioning VS dom: 

Use case:
- Screen divided in two parts vertically, up one is the map the other one is a scrollable content, and when

Problem:
- When I scroll down, map disappears because the plugin thinks the visible content is the big list in the scrollable content.

SOLUTION I FOUND
- shouldWatchByNative: I can just change it to return true only for my scrollable content
=> that works, now I can swipe my map even if I scroll down
- Problem is the map is still invisible when I scroll down (I can see that it's behind if I set body opacity to 0). => this is what I need to do

**Comment by wf9a5m75** [comment]
Could you tell me more about ` I get some issues related to map positioning VS dom`?

**Comment by dorianrod** [comment]
My page structure:

1) Top: the map
2) A scrollable content: the scrollable wrapper contains a long DIV

For instance for a 800px height viewport:
1) Top wrapper (map): 300px
2) Bottom wrapper (scrollable): 500px. Inside the wrapper, a long list (10000px). The set is a virtual list: the long list contains abolutely positioned elements.

When I wrap the bottom content, the plugin detects the click on the long list or elements inside the long list (findClickedDom function in Android). This is because effectively, the long list is covering all the screen when you scroll. But in reality it's hidden by the scrollable wrapper and the map should intercept the click.
I found a simple solution to prevent that: I just ignore tell the native scrollview to ignore every items inside a scrollable content. (cf. my fork). I used a specific class name for scrollable wrapper. Then every items inside the scrollable wrapper are ignore by the plugin (not id is set). Then when I scroll the content, the plugin just try to discriminate between the top wrapper and the bottom wrapper. Not more problem. Concerning my first question, this solution is enough. The map was white when I was scrolling for another reason not linked to the plugin.

Let me know if you need more information or if I'm not clear enough

Have a good day

DR

**Comment by wf9a5m75** [comment]
Please use Google maps JavaScript v3 API, or other ones.

**Comment by dorianrod** [comment]
Yes there are a bunch of div inside scroll. The plugin suits in that case with few adaptation. The solution I found works very fine with this plugin. 

https://github.com/dorianrod/cordova-plugin-googlemaps/commit/6fdbe4f8beed7f5768d8aface06a2bba5d7ebd26
> for people with the same use case

The main principle is just to help the plugin to know which elements to check. Sometimes you know exactly which elements will never be over the map, thus you can exclude some elements.

**Comment by wf9a5m75** [comment]
After considering during on my commute, I come up a good idea. 
Use shadow DOM.

Since shadow DOM is able to block inspection from outside, this plugin omits checking.
Create a shadow DOM, and put your bunch of DIV into it.

**Comment by dorianrod** [comment]
I didn't know about shadow DOM, but from what I understand that should work as well! Good idea

**Comment by dorianrod** [comment]
There may be some side effects: shadow DOM seems designed to isolate a subtree. A not negligible consequence is that global style seems to not apply to that shadow DOM.

**Comment by wf9a5m75** [comment]
https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/

**Comment by wf9a5m75** [comment]
For other people who are the similar case, I provide more detailed information.

Since this plugin needs to check all the position, size and hierarchy (z-index, etc), large number of elements cause bad performance problem.

The below code generates bunch of `div` under `div#scroll`.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript">
    document.addEventListener("deviceready", function() {
      var mapDiv = document.getElementById("map_canvas");
      var map = plugin.google.maps.Map.getMap(mapDiv);

      var scrollDiv = document.getElementById("scroll");

      var row = document.createElement("div");
      row.style.height="40px";
      row.style.borderBottom = "1px solid #ccc";
      row.style.textAlign = "center";
      row.style.lineHeight = "40px";
      for (var i = 0; i < 10000; i++) {
        var cloneDiv = row.cloneNode();
        cloneDiv.innerText = i;
        scrollDiv.appendChild(cloneDiv);
      }
    }, false);

    </script>
    <style type="text/css">
    html, body {
      height: 100%;
    }
    #map_canvas { /* Must bigger size than 100x100 pixels */
      width: 100%;
      height: 50%;
    }
    #scroll {
      width:100%;
      height: 50%;
      position: fixed;
      bottom: 0;
      overflow: scroll;
    }
    </style>
  </head>
  <body>
    <div id="map_canvas"></div>
    <div id="scroll"></div>
  </body>
</html>
```
![Screen Shot 2019-08-23 at 9 21 44 AM](https://user-images.githubusercontent.com/167831/63608243-59d78a00-c589-11e9-9b99-ca12329ae572.png)

In that case, please use `Shadow DOM`. Shadow DOM creates a web component, which is isolated component from host page.
This plugin omits checking Shadow DOMs. Just count as 1 element instead of 100000.

![Screen Shot 2019-08-23 at 9 22 13 AM](https://user-images.githubusercontent.com/167831/63608445-e71ade80-c589-11e9-9a5e-4166f060cc58.png)
