### ISSUE TITLE
Multiple markers plotting take huge time

### ISSUE THREAD

**Issue by walioul** [mapsplugin/cordova-plugin-googlemaps#2673]
Hello,

I am using your library in my Cordova apps ( Target : Android ). I am plotting about 300 markers and polyline among them using a for loop. 

Plotting 300 markers takes 1500 seconds maybe. But I don't need any animation.

How can I play with you nice library in efficient way for multiple markers ? 

Thanks in advance.

Regards,
Walioul Jewel

**Comment by battika** [comment]
I am also drawing 250-300 markers on a map without using marker cluster and I find the performance OK'ish on real devices. On emulators it is really slow but that should be OK.
Just wondering are you using addMarkerSync() in your loop or you wait for each marker to be created with a Promise? I am using addMarkerSync() and it works well so far.

**Comment by battika** [comment]
@walioul just read your original report again, are you sure about the 1500 seconds? That means 25 minutes. Did you mean 1500ms?

**Comment by walioul** [comment]
Yes I meant 25 minutes if I place 300 markers and animate that locations one after another.

Again thank you for your nice cooperation.

**Comment by walioul** [comment]
@battika & @wf9a5m75 Does this plugin have any way to place arrow symbols like have in Javascript API. ( I am using it for android / iOS )

https://developers.google.com/maps/documentation/javascript/examples/overlay-symbol-arrow
