### ISSUE TITLE
app crash on android 9 and above

### ISSUE THREAD

**Issue by Bhagirath123** [mapsplugin/cordova-plugin-googlemaps#2675]
Hi

i am using google-maps plugin in ionic 3 project
in my cash map working in android 8.1.0
but when i am open map in my android 9 and above version device my app close 

plz help

**Comment by wf9a5m75** [comment]
Please share the logcat output at least...

**Comment by Bhagirath123** [comment]
Thank you for your reply
but when i am inspect my app on map open time i am not getting any type of error in my console

**Comment by wf9a5m75** [comment]
`logcat`, not `console`

**Comment by Bhagirath123** [comment]
logcat i am not understand

**Comment by wf9a5m75** [comment]
Please search the word "logcat" on Google, or Youtube.

**Comment by Bhagirath123** [comment]
sorry for i am not found my logcat

**Comment by wf9a5m75** [comment]
Please share your project files on github repository.

**Comment by Bhagirath123** [comment]
ok

**Comment by Bhagirath123** [comment]
thanks for you support 
problem is resolved for update plugin version
