### ISSUE TITLE
Cordova wheel selector buttons not clickable when google maps installed(iPhone XR/XS)

### ISSUE THREAD

**Issue by ratheeshkumarnv** [mapsplugin/cordova-plugin-googlemaps#2676]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
In iPhone XR/XS simulator or devices when map plugin is installed, the buttons on the Cordova wheel selector plugin (Done/Cancel) is not clickable. But if you click slightly above the buttons it works. This works fine when map plugin is uninstalled but we need this plugin for map features. Found similar issue logged already with date picker plugin https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2497. But that didn't solve my issue.

**Expected behavior:**
The buttons on the Cordova wheel selector plugin (Done/Cancel) should be clickable with map plugin installed

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

Have created a demo project. Please check here https://github.com/ratheeshkumarnv/Cordova-map-issue
```

```

**Comment by ratheeshkumarnv** [comment]
Do we have any solution or work around for this since this is critical for us. Right now we removed the maps plugin because of this issue. But we need maps plugin back with all those features. Can anyone suggest any solution or workaround for this please?

**Comment by wf9a5m75** [comment]
Sorry for late response. I'm super busy right now. Install `cordova-plugin-statusbar` and adjust the height of status bar if necessary.

**Comment by ratheeshkumarnv** [comment]
@wf9a5m75 Thanks for your reply. I installed statusbar plugin in my demo project but still same issue. Also tried adding StatusBarOverlaysWebView to true in config for notch support. Still same issue.

**Comment by wf9a5m75** [comment]
Then use another plugin or create a selector by HTML, please. I have no enough time to work.

**Comment by wf9a5m75** [comment]
Fixed.
