### ISSUE TITLE
 Error opening maps for the first time

### ISSUE THREAD

**Issue by EglisonHenrique** [mapsplugin/cordova-plugin-googlemaps#2678]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report

**OS:**  (check one with "x")
- [ x] **Android**
- [ x] **iOS**
- [ ] **Browser**

**cordova information:** 
```
call-number 0.0.2 "Cordova Call Number Plugin"
card.io.cordova.mobilesdk 2.1.0 "CardIO"
com-badrit-base64 0.2.0 "Base64"
cordova-base64-to-gallery 4.1.3 "base64ToGallery"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appminimize 1.0.1 "AppMinimize"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-daniel-readcalls 0.0.1 "ReadCalls"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.6 "cordova-plugin-filepath"
cordova-plugin-fingerprint-aio 1.7.0 "FingerprintAllInOne"
cordova-plugin-firebasex 5.0.0 "Google Firebase Plugin"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-local-notification 0.8.4 "LocalNotification"
cordova-plugin-mauron85-background-geolocation 3.0.1 "CDVBackgroundGeolocation"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sms-plugin 1.0.0 "Cordova SMS Plugin"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.5.0 "OneSignal Push Notifications"

```

```
@ionic-native/core : 4.3.3
@ionic-native/google-maps : 4.20.0
```

Hello,

When installing the application, and opening maps for the first time, the application crashes, doing the process by android studio, it brings the following log:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
     at plugin.google.maps.PluginMarker._create(PluginMarker.java:250)
     at plugin.google.maps.PluginMarkerCluster$3.run(PluginMarkerCluster.java:395)
     at android.os.Handler.handleCallback(Handler.java:873)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:193)
     at android.app.ActivityThread.main(ActivityThread.java:6923)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

However, when you open the application a second time, the error does not occur.

I would like to know the cause of the problem.

**Comment by EglisonHenrique** [comment]
Hi, follow the repository https://github.com/EglisonHenrique/erro-maps

The error occurs when you install the app and open the map for the first time, from the moment you close the app and reopen, the map works normally.

**Comment by wf9a5m75** [comment]
Thank you for preparing.

I wonder why you specify `"-24.728839", "-53.737562"` as `String` instead of number.

**Comment by EglisonHenrique** [comment]
I put to do the test, now changed to number, but got the same result. Would it have any impact on using String or Number?

**Comment by wf9a5m75** [comment]
lat/lng should be number not string.

And try to fix the height of map div for test.

```css
#map {
        height: 500px;
}
```

**Comment by EglisonHenrique** [comment]
lat / lng changed to number.
Map height to 500px, but error persists

**Comment by wf9a5m75** [comment]
Okay, I got the reasons.
There are two reasons.

## 1) your JSON data is too large. This causes memory overflow.

This plugin keeps the data in both side, JS and native.
Since you pass whole JSON data to the native side, this causes memory overflow.
I increase the number of cache size, but you also should slim down your data.

For example, keeps only the minimum necessary data

```
markers.push({
  position: { lat: element.geoLatitude, lng: element.geoLongitude },
  codProspect: element.codProspect   // <--keep only marker id
});
```

instead of keeping whole data.

```
markers.push({
  position: { lat: element.geoLatitude, lng: element.geoLongitude },
  prospect: JSON.stringify(element)
});
```

-----------

## 2) map visible region

The reason of the error occurs only the first time is that map tile is loaded after second time.

Even `MAP_READY` is fired, the camera information is not synchronized with JS and native side when the first time, because the native map is still loading.
That's why the marker cluster try to pass the whole location data to the native side.

Then memory overflow is occurred.

**Comment by wf9a5m75** [comment]
I increased cache memory size up to 10MB. Please reinstall the plugin from the multiple_maps branch.
