### ISSUE TITLE
can't remove map while map.animateCamera() is running

### ISSUE THREAD

**Issue by 8bhsolutions** [mapsplugin/cordova-plugin-googlemaps#2682]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X ] any problem or bug report

**OS:**  (check one with "x")
- [ X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core :  4.20.0
@ionic-native/google-maps :  4.21.0
```

**Steps**

1. Compile demo/test project (link provided below)
1. In root page, click "Animate Camera".
1. While camera is animating to target, before animation finishes, click "Root Page #2".

**Current behavior:**
_App setup_
Root page has a map. Pushing a child view also have a map.
_Scenario_
Root view map is animating camera. During camera animating to target, pushing new view. The new view will result in blank page

**Expected behavior:**
The child view should show map.

**Screen capture or video record:**
[capture.mp4.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/3619596/capture.mp4.zip)

**Related code, data or error log (please format your code or data):**

```
https://github.com/8bhsolutions/gmap-test

No errors or anything notable in logcat
```

**Context**
My app has a function to keep the centre of the map on the current user location.
This is implemented using GPS plugin, watchposition(). Every second, animate camera is called to centre the camera on the current GPS location.

The user can also push another map view from the root page.
If the user pushes the child view while the camera is still animating the child map is not shown.
Also, in the child page, if the user was to pop to get back to root page while the child map is animating, both maps will be blank. User will need to restart app to restore map views.

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
This plugin can't stop the camera animation. Thus, your app should wait until camera is done when user clicked on the button.

**Comment by wf9a5m75** [comment]
One of the possible solutions is to detach the map view using `map.setDiv(null)` when the button is clicked and before opening a new child view.

**Comment by battika** [comment]
This is exactly how I am using it. It is also good for "saving" the map state when you come back to the page and restore the map using map.setDiv(_divName_) function.

**Comment by 8bhsolutions** [comment]
Thanks guys for your input.

The demo project executes map.setDiv() to detach map before leaving the page and before opening the new child view. I do this in my actual app to speed up page transitions.

Because there are no errors in logcat, I'm not sure where to even start debugging.

@battika 
My demo project is actually forked from your project. 
I changed 

- setRoot to push 
- added camera animation button

**Comment by FerhatMotiv** [comment]
I also ran into this problem, which is a rather blocking issue regarding loading a map into certain Ionic pages, as its own 'map component'.

@wf9a5m75 Your solution regarding map.setDiv(null) doesn't make a difference in my case. 
When the google maps plugin is either animating with an animateCamera zoom-in, or when it's drawing polylines with map.addPolyline the issue persists. 

In both scenarios if a user navigates to another page while the map is drawing/animating it will load as a blank map afterwards, every single time. 

What I noticed while debugging however, is that when you leave the page during an animation/drawing event the ngOnDestroy will never be called in my map component, which seems to be resulting in the map plugin not being able to destroy itself properly. Therefore the map can't load itself properly anymore. If you wait for everything to animate/draw etc, the ngOnDestroy will be called, which results in being able to properly call the map.remove() function.

**Comment by wf9a5m75** [comment]
The map is not a HTML element. Throw away HTML knowledge. You need to implement your code for native map.

If the map causes unexpected behavior, you should implement your code to prevent that.

**Comment by FerhatMotiv** [comment]
Well, while debugging it seems that whenever the map manages to destroy itself when navigating away from the page, everything goes fine. 

However, if you navigate away during an animation or drawing of polylines and such, the map doesn't trigger the destroy lifecycle hook(s) (Both Angular/Ionic hooks) and therefore gets bugged.

**Comment by FerhatMotiv** [comment]
I added you as collaborator to a test project.
It has a home page with a button that redirects to a map-details page where a map component will load & use the ```animateCamera```.

If you press the home button on the tab bar during this animation, you'll end up at the initial home page again. This will trigger the IonViewDidLeave from the map-details page, and calls the ```remove``` function from the map plugin. 

The issue with this setup is that the home page will freeze once you go back, until the map animation is completed somewhere in the background. It seems like the home page is waiting for the map-details native map to finish its animateCamera event, even though the map should have been removed. Once the animate event is done in the background, the home page responds again. Same thing happens with drawing a lot of polylines in order to show a route over 200km for example.

What I expect to happen is, I call the map remove, and the map gets removed + any pending animations/drawing code execution is stopped with the map remove.

**Comment by wf9a5m75** [comment]
Thank you for sharing the repo. I added "map.stopAnimation()" method, and it is involved before `map.remove()` automatically.

Please reinstall the maps plugin from the multiple_maps branch.

![capture](https://user-images.githubusercontent.com/167831/65908179-c27d0800-e37a-11e9-9f85-59082fe33d96.gif)

**Comment by 8bhsolutions** [comment]
@wf9a5m75 - Thanks mate.
Is the multiple-maps branch a "development" branch?

**Comment by FerhatMotiv** [comment]
@wf9a5m75 - Works like a charm, thanks for the quick fix :)
