### ISSUE TITLE
Can't get controls display on IOS

### ISSUE THREAD

**Issue by Steco17** [mapsplugin/cordova-plugin-googlemaps#2683]
Hello guys am working the the latest version of this plug but i can't display the map controls on IOS. The same google map  controls works on Android (6.4>) but not IOS . 
Any solution to this?

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository

**Comment by wf9a5m75** [comment]
Do you mean `mapToolbar`?

**Comment by JZubero** [comment]
Same problem here.

```javascript
let mapOptions: GoogleMapOptions = {
      controls: {
        compass: true,
        myLocation: await this.geoService.hasPermission(),
        myLocationButton: await this.geoService.hasPermission(),
        mapToolbar: true,
        zoom: true
      }
    };
```

Works just fine under Android. On iOS no controls at all.

**Comment by wf9a5m75** [comment]
```
 // Change the map options
  map.setOptions({
    'mapType': plugin.google.maps.MapTypeId.HYBRID,
    'controls': {
      'compass': true,
      'myLocationButton': true,
      'indoorPicker': true,
      'zoom': true,
      'mapToolbar': true   // currently Android only
    },
```

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/Map/setOptions/README.md

**Comment by Steco17** [comment]
thanks @wf9a5m75 will try that

**Comment by JZubero** [comment]
Thanks for clarification, @wf9a5m75. Works for us.
