### ISSUE TITLE
Css animation interference when call setDiv and there is a push/pop page

### ISSUE THREAD

**Issue by zarelint** [mapsplugin/cordova-plugin-googlemaps#2685]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [X] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-android-firebase-gradle-release 3.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 3.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-core-android-extensions 2.0.0 "CoreAndroidExtensions"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-emma-sdk 1.0.1 "EMMA"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filepath 1.5.5 "cordova-plugin-filepath"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-localization-strings 3.1.0 "Localization"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 2.0.3-dev "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-transparent-status-bar 1.0.1 "Transparent status bar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 4.4.0
@ionic-native/google-maps : 4.4.2
```

**Current behavior:**
As it's explained on docs we call setDiv() to get out of the page, for detaching map, in this way when you come back to the page you can reattach it again. 

From a commit post below, it can not be seen anymore the **out of page animations**.  that means the page doesn't slide to left/right (see video)

**Expected behavior:**
After call a setDiv(), we expect the plugin don't do a **hard DOM refresh** and let run the animations transitions again as before the commit happens.

https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/4ef4e5ce68716f1a916f5138ff745d7ed9523f76

We try 2 things i write you the results

1. A more conservative approach removing these lines from **refreshLayout(),**  to avoid a hard DOM refresh:

```
    div.style.display = 'none';
    div.offsetHeight;
    div.style.display = '';
```

Put inside the refreshLayout() these one:

`document.body.style.transform = 'rotateZ(0deg)';`

Result: the transition is fix but the map is not seen:

2-Second try 
We remove the lines from **refreshLayout(),**
```
    div.style.display = 'none';
    div.offsetHeight;
    div.style.display = '';
```
And  after call **setDiv()**  we call from our app code:

`document.body.style.transform = 'rotateZ(0deg)';`

That works transition is seen and map is seen on IOS

We wonder if you could get a fix to have all working !!! 

**Screen capture or video record:**

1 - First video shows slides animations working getting out of the page
https://youtu.be/U5dPZqZ2mxA
2- Second video shows getting out page 3 times and the animation can hardly seen it get out of the page abruptly without sliding out left as usual.
https://youtu.be/3Y7MqZMtPvE

Note: On Ios the transition are showed but in Android not. i post the videos on android case.
**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Video must upload to YouTube or server please. I don't open zip file.

**Comment by zarelint** [comment]
> Video must upload to YouTube or server please. I don't open zip file.

ok i've upload now to youtube

**Comment by zarelint** [comment]
update videos screens to improve explanation any else say me  please

**Comment by wf9a5m75** [comment]
If you don't help me, I don't help you.

**Comment by zarelint** [comment]
say what you need please

**Comment by wf9a5m75** [comment]
I can't open zip file on mobile phone.

**Comment by zarelint** [comment]
i update the ticket with youtube linnks look
1 - First video shows slides animations working getting out of the page
https://youtu.be/U5dPZqZ2mxA
2- Second video shows getting out page 3 times and the animation can hardly seen it get out of the page abruptly without sliding out left as usual.
https://youtu.be/3Y7MqZMtPvE

**Comment by wf9a5m75** [comment]
Did you read this section?
https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios

**Comment by wf9a5m75** [comment]
Map is a not HTML element. Thus, map can't follow css animation (transition).

**Comment by zarelint** [comment]
Thanks for reopening the ticket very much, sorry for the mess before I will try to explain it better.
yes, I've read the documentation that you refer, Let me put in context, we have an app publish already using the plugin  from version 2.1.1 forked:

https://github.com/goinnn/cordova-plugin-googlemaps/tree/v2.1.1%23custom

This is the link app in case you want have a look:
https://play.google.com/store/apps/details?id=com.joinuptaxi.passenger&hl=en

Now we are updating to the last version and work much better but the only thing we see is the issue comment before.

Yes, as you say the map is not an HTML element and the map, so the maps redraw o refreshes must no be a problem with other CSS animation on HTML page... but I see the next things until now:

We test the app before the commit and was working, I think that the change on commit adding the lines refreshLayout function() force a "Webkit redraw"  as you explain in the code, and that could be the cause to interference with other animations running in the same moment...  

I did some trials that point in that direction ...

1- I removed from refreshLayout() the lines that do "Webkit redraw". This done the CSS animation appears again.  Here is my fork (https://github.com/zarelint/cordova-plugin-googlemaps.git)
that I did where I' removed that lines basically in the state before the commit.

The issue from removing that lines as you know broke the map in IOS leaving the screen map in black as you explain in the commit. 
I've tried 2 things, Sure, may here you have better ideas...
	
1. I try replacing the redraw lines inside the function refreshLayout()  by forcing a rotation to refresh the map doing this:
document.body.style.transform = 'rotateZ(0deg)';

2. With no success on point 1, in this second this time  after calling the setDiv() I force that refresh with  'rotateZ(0deg)' but this time from the app itself that fix the issue map but this is bad deal because  I have to use the fork I paste before.

[Current official plugin: no animation] (https://youtu.be/3Y7MqZMtPvE)
[Our solution fork URL FORK + after setDiv for iOS document.body.style.transform = rotateZ(0deg)]  (https://youtu.be/U5dPZqZ2mxA)

The difference could be hard to see on both videos because the animation goes faster, I words would be getting out page the page slide left instead show the other page directly that is the animation that is lost. Any test or clarification say us.

Maybe you can have another approach to avoid "Webkit redraw" and at the same the get the maps working IOS. that would be great

We appreciate your work,  we will send you a donation as soon as possible, Thanks very much for your time.

**Comment by zarelint** [comment]
> Thank you for the further update. The code of `refreshLayout()` is very old. It might not be necessary for the recent iOS. I will test it more details.

ok, it would be great could be removed it,  if you need any else, tell me. Regards.

**Comment by wf9a5m75** [comment]
This is already fixed.
