### ISSUE TITLE
Touch events not working within maps dimensions

### ISSUE THREAD

**Issue by fjckls** [mapsplugin/cordova-plugin-googlemaps#2686]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**cordova version**

```
9.0.0 (cordova-lib@9.0.1)
```

**Current behavior:**
Touch events not responding within maps dimensions.When I scroll down and then try to engage inside upper part of the screen, touch events are not responding.

**Expected behavior:**
Touch events working as normal

**Screen capture:**

![googleMaps-1](https://user-images.githubusercontent.com/2750675/65601361-a0663d00-dfaa-11e9-8ac1-f83fdc4c17f5.jpg)

**Can't scroll here inside red area**

![googleMaps-2](https://user-images.githubusercontent.com/2750675/65601409-b70c9400-dfaa-11e9-84cc-3d9d95541f62.jpg)

**Can't tap on anchor link inside red area**

![google-maps-3](https://user-images.githubusercontent.com/2750675/65601426-bd027500-dfaa-11e9-851b-532b845de911.jpg)

**Git repo with the issue**
https://github.com/fjckls/cordova-native-google-maps-issue

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository

**Comment by fjckls** [comment]
> Please share your project files on GitHub repository

Here, please have a look:  https://github.com/fjckls/cordova-native-google-maps-issue
Thanks!

**Comment by wf9a5m75** [comment]
Oh, sorry.

You need to change the HTML hierarchy a little.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript">
      ...
    </script>
    <style type="text/css">
      #map_canvas { ... }
      button { ... }
      .body { ... }
      body {
        width: 0px;
        height: 0px;
      }
      #container {
        position: fixed;
        width: 100%;
        height: 100%;
        overflow: scroll;
        left: 0px;
        top: 0px;
        padding: 0px;
        margin: 0px;
      }
    </style>
  </head>
  <body>
    <div id="container">
      <div id="map_canvas">
        <button id="button">Click me!</button>
        <button id="button-resize">Resize!</button>
      </div>

      <div class="body">
        <h1>...</h1>
        <h1>...</h1>
        <h1>...</h1>
        <h1>...</h1>
        <h1>...</h1>
        <h1>...</h1>
        <h1>...</h1>
        <h1>...</h1>
        <h1>...</h1>
        <h1>...</h1>
        <h1>...</h1>
        <h1>...</h1>
      </div>
    </div>

    <script>
      ...
    </script>
  </body>
</html>

```

**Comment by fjckls** [comment]
Thanks, now it works! So to be able to scroll content and the map window itself you need to have an extra wrapper with `position:fixed`?

**Comment by wf9a5m75** [comment]
Please try other cases.

**Comment by fjckls** [comment]
Cool, thanks!
