### ISSUE TITLE
runing marker.setPosition() in the background mode

### ISSUE THREAD

**Issue by abdullah1225** [mapsplugin/cordova-plugin-googlemaps#2688]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [*] any problem or bug report

**OS:**  (check one with "x")
- [* ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.5.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sms-plugin 1.0.0 "Cordova SMS Plugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**
when switching to the background mode while updating the marker position using marker,setPosition() during a long drive and then switch to foreground after the ride finishes app tends to start showing the marker from the last state and position and repeat the setting position for the whole ride using the full time of the journey in the map as if you are watching a video record of the ride. also it creates multiple markers of the marker instead of updating the one marker position 

**Expected behavior:**
app opens using the final marker.setPosition() location having one marker in the screen

**Screen capture or video record:**
[video+image.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/3674097/video%2Bimage.zip)
<!--
Please take a screen capture or a screen record. You can upload your files with drag & drop up to 10M bytes. If your video file is bigger than 10MB, please upload to your youtube channel, or your Google drive.

**Comment by wf9a5m75** [comment]
This plugin does not work in background mode

**Comment by abdullah1225** [comment]
ok !
so what about the recorded positions. may it be from the background-geolocation plugin ??

**Comment by wf9a5m75** [comment]
I don't know other plugin.
