### ISSUE TITLE
Android - NullPointerException on AsyncLoadImage

### ISSUE THREAD

**Issue by Mathieu-Castets** [mapsplugin/cordova-plugin-googlemaps#2689]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-cookie-manager 1.0.0 "CookieManagementPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-googlemaps 2.6.3-20190930-1257 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.1.0-dev "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-localization-strings 3.1.0 "Localization"
cordova-plugin-network-information 2.0.2-dev "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-inject-cookie 1.0.2 "WKWebViewInjectCookie"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"

```

**Current behavior:**
We are seeing crash reports on Google Play Console:
```
java.lang.NullPointerException: 
 
  at plugin.google.maps.AsyncLoadImage.onPreExecute (AsyncLoadImage.java:128)
 
  at android.os.AsyncTask.executeOnExecutor (AsyncTask.java:648)
 
  at android.os.AsyncTask.execute (AsyncTask.java:595)
 
  at plugin.google.maps.PluginMarker$16.run (PluginMarker.java:1156)
 
  at android.os.Handler.handleCallback (Handler.java:873)
 
  at android.os.Handler.dispatchMessage (Handler.java:99)
 
  at android.os.Looper.loop (Looper.java:214)
 
  at android.app.ActivityThread.main (ActivityThread.java:7045)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```

It seems like `webView.getUrl()` returns `null`:
![Capture d’écran 2019-10-02 à 08 35 20](https://user-images.githubusercontent.com/4427447/66023163-a00cfb00-e4f0-11e9-968d-e1c19f4abbf0.png)

**Expected behavior:**
I would add a null statement to `currentPage` and also to `this.currentPageUrl` wherever they are used.
It would be also interesting to understand how or why `webView.getUrl()` is returning a `null` value.

**Comment by wf9a5m75** [comment]
I also don't know `how` and `why`.
Please share your project files on GitHub repository. I think the hint is in your code.

**Comment by Mathieu-Castets** [comment]
I cannot share the whole project files but I could create a sample repo with the relevant files (but which ones?). Do you think upgrading `cordova-android` version from `7.1.4` to `8.0` could fix the problem?

**Comment by wf9a5m75** [comment]
The important thing is to figure out `how` and `why`.
Just inserting `if` statement cause memory leaking.

**Comment by wf9a5m75** [comment]
ping

**Comment by Mathieu-Castets** [comment]
As I said, I cannot share the whole project files but I could create a sample repo with the relevant files (but which ones are you interested with?).

**Comment by wf9a5m75** [comment]
Please create a project which is able to reproduce your issue 100%.

**Comment by Mathieu-Castets** [comment]
I cannot reproduce the issue 100%. I have, myself, never encountered this exception. It happens for some user for some devices.

**Comment by wf9a5m75** [comment]
No cooperation, no help. Lots of contributions, lot of help.

**Comment by drawcard** [comment]
@Mathieu-Castets create a private repo in Github and assign @wf9a5m75 as a collaborator
