### ISSUE TITLE
Changing the height of the map container results in "jelly like animation"

### ISSUE THREAD

**Issue by fjckls** [mapsplugin/cordova-plugin-googlemaps#2690]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**Current behavior:**
Change the height of the map container - the map is being redrawn to fit new dimensions and it results in jerky, jelly like animation when map is being redrawn 

**Expected behavior:**
Smooth map redraw.

**Screen capture or video record:**

[video capture here](https://wetransfer.com/downloads/579dc39378a40891f21b9df9c9ab35ad20191002141422/bd6b1f1f2e24e27eecc1cf22d70af9ed20191002141422/5b1dd2?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email)

**Related code, data or error log (please format your code or data):**

```
repo - https://github.com/fjckls/cordova-google-maps-issues
```

**Comment by wf9a5m75** [comment]
I don't recommend that. Because the map is NOT a HTML element

**Comment by wf9a5m75** [comment]
Please use as is.
