### ISSUE TITLE
Grey map loading on Android & iOS (after creating new project)

### ISSUE THREAD

**Issue by drawcard** [mapsplugin/cordova-plugin-googlemaps#2696]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**
I have created a brand new test project and am getting a grey rectangle instead of the expected Google Map in Android, however it partially works in iOS. I first noticed this problem in a seperate Ionic 4 project (with ionic-native/google-maps) so I decided to try out a test repo to troubleshoot, and ran into the problems here as well.

Please clone my rest repo below to test.

I followed these instructions exactly, with no other plugins added: https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/hello-world/README.md

I also noted this guide: https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/graymap/README.md:

> Your API key does not allow to use Google Maps Android API or Google Maps SDK for iOS. 
Since the cordova-plugin-googlemaps uses Google Maps Android API and Google Maps SDK for iOS, you need to generate API keys for Android application and iOS application.

> **Common mistakes**
> You only enable Google Maps JavaScript API v3.
> You don't enable Google Maps Android API or Google Maps SDK for iOS.

All APIs are enabled for test keys. The keys are completely unrestricted.

> You contains unnecessary string, such as space.

The API keys were copied directly from Google Dev Console and pasted into config.xml where needed.

> You generated API keys before enabling API keys.

Test keys was generated after the Maps SDK for Android was enabled.

**Expected behavior:**
The maps should load.

**Screen capture or video record:**

Android (clicking "Click me" loads nothing):
![image](https://user-images.githubusercontent.com/1435638/67560907-5d42e980-f763-11e9-933d-133631954451.png)

iOS (clicking "Click me" loads the marker and infowindow only):
![image](https://user-images.githubusercontent.com/1435638/67562240-de02e500-f765-11e9-9fa8-fb9d8c917eb2.png)

Unrestricted keys - note that these keys work fine with other API services:
![image](https://user-images.githubusercontent.com/1435638/67562700-c9731c80-f766-11e9-9f19-2de6fed8ead8.png)

![image](https://user-images.githubusercontent.com/1435638/67562758-e3146400-f766-11e9-90c0-369475b9d3bd.png)

**Related code, data or error log (please format your code or data):**

https://github.com/drawcard/cpgm-test/ to see the setup. This repo is private (since it contains API keys) so I will grant access to @wf9a5m75 as a collaborator. 

**Thank you for any assistance you can provide.**

**Comment by drawcard** [comment]
@wf9a5m75 I have invited you to my repo for testing: https://github.com/drawcard/cpgm-test/invitations

**Comment by drawcard** [comment]
Update: iOS seems to be working, Android is still displaying nothing. I also noticed this behaviour originally in my other Ionic 4 application, this test repo seems to validate the bug.

![image](https://user-images.githubusercontent.com/1435638/67564434-78fdbe00-f76a-11e9-8636-714f9057a181.png)

**Comment by wf9a5m75** [comment]
Gray map means API key problem. Since you were already able to display the Google Maps, you can use the same key for Android.

**Comment by drawcard** [comment]
Thanks @wf9a5m75 for your quick response. That is what I figured, so I tried the same key that was generated for iOS, and it didn't work. I have pushed a new commit to my repo to demonstrate.

![image](https://user-images.githubusercontent.com/1435638/67616650-ed943380-f822-11e9-84fd-102aec25850f.png)

![image](https://user-images.githubusercontent.com/1435638/67616701-60051380-f823-11e9-84cc-2d2a35cd9aac.png)

The strange thing is that everything was working fine for Android after many months of testing our production app, and our app even passed approval on Google Play Store a few days ago (the map functionality is a pretty significant feature of our app). It has only been in the past 48 hrs that this error has occurred. We have checked our production keys closely and they are all correctly set up, nothing seems out of place or changed there. 

Did you manage to get access to our test repo to confirm the problem on your side?

Thank you

**Comment by drawcard** [comment]
Also to confirm there are no restrictions at all on the test keys:

![image](https://user-images.githubusercontent.com/1435638/67616757-38627b00-f824-11e9-897b-fc7af89d7595.png)

In particular the key used for iOS:

![image](https://user-images.githubusercontent.com/1435638/67616777-6cd63700-f824-11e9-80e3-f8a9619c5f9d.png)

**Comment by drawcard** [comment]
After trying out @imanzal 's suggestion [here](https://github.com/ionic-team/ionic-native-google-maps/issues/242#issuecomment-521197846), to downgrade the ionic-native components to earlier versions, the Android map started working again on my production app. Here's what I ran:

(note this solution is adapted for @ionic-native/google-maps)

```
ionic platform remove android
npm uninstall @ionic-native/core @ionic-native/google-maps
npm install @ionic-native/core@5.0.0 @ionic-native/google-maps@5.0.0-beta.27
ionic cordova emulate ios --livereload
```

Here's the API key setup for my production app:

![image](https://user-images.githubusercontent.com/1435638/67634156-48ec2180-f908-11e9-8f3d-894fe593fa8a.png)

![image](https://user-images.githubusercontent.com/1435638/67634282-b5b3eb80-f909-11e9-9766-2110fbdba1d3.png)

Tomorrow I will build the production version of the app, sign it and re-release onto the Google Play store, and will update you with the results.

**Comment by drawcard** [comment]
Production app went live without a hitch.

**Comment by wf9a5m75** [comment]
Did you solve your problem?

**Comment by drawcard** [comment]
I did, I rolled back to earlier versions of the plugin as mentioned above. All working now. Thank you for following up :)

**Comment by tryhardest** [comment]
@drawcard what version of the plugin are you using then? Did you determine issue?

**Comment by drawcard** [comment]
@tryhardest if you go through my notes above you'll see all the details & descriptions of the issue as I encountered it.
