### ISSUE TITLE
package za.co.twyst.tbxml does not exist 

### ISSUE THREAD

**Issue by delfimvenceslau** [mapsplugin/cordova-plugin-googlemaps#2698]
`C:\Users\DelfimVenceslau\Documents\Foodfixe! Novas Versoes do App\Foodfixe Lite\
platforms\android\gradlew: Command failed with exit code 1 Error output:
C:\Users\DelfimVenceslau\Documents\Foodfixe! Novas Versoes do App\Foodfixe Lite\
platforms\android\app\src\main\java\plugin\google\maps\PluginKmlOverlay.java:20:
 error: package za.co.twyst.tbxml does not exist
import za.co.twyst.tbxml.TBXML;
                        ^
C:\Users\DelfimVenceslau\Documents\Foodfixe! Novas Versoes do App\Foodfixe Lite\
platforms\android\app\src\main\java\plugin\google\maps\PluginKmlOverlay.java:181
: error: cannot find symbol
    private Bundle parseXml(TBXML tbxml, long rootElement) {
                            ^
  symbol:   class TBXML
  location: class PluginKmlOverlay.KmlParserClass
C:\Users\DelfimVenceslau\Documents\Foodfixe! Novas Versoes do App\Foodfixe Lite\
platforms\android\app\src\main\java\plugin\google\maps\PluginKmlOverlay.java:154
: error: cannot find symbol
      TBXML tbxml = new TBXML();
      ^
  symbol:   class TBXML
  location: class PluginKmlOverlay
C:\Users\DelfimVenceslau\Documents\Foodfixe! Novas Versoes do App\Foodfixe Lite\
platforms\android\app\src\main\java\plugin\google\maps\PluginKmlOverlay.java:154
: error: cannot find symbol
      TBXML tbxml = new TBXML();
                        ^
  symbol:   class TBXML
  location: class PluginKmlOverlay
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 4s`

**Comment by wf9a5m75** [comment]
I think your Gradle is old.

By the way, please read this page https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2661

**Comment by delfimvenceslau** [comment]
When I take your plugin Build works normally, before the Plugin update Build worked normally but now nothing works, and keeps giving this error.

**Comment by delfimvenceslau** [comment]
My gradle version is 5.4.1

**Comment by wf9a5m75** [comment]
Then I don't know why. Please try to reinstall the plugin

**Comment by wf9a5m75** [comment]
ping
