### ISSUE TITLE
DistanceMatrixService

### ISSUE THREAD

**Issue by jzlinn** [mapsplugin/cordova-plugin-googlemaps#2699]
Hi,
I'm new to github Question or bug report support.
I need to implement `DistanceMatrixService` and `DirectionsService` for my `cordova` project. Is there any other plugins have these supports ??

or is there any way to bridge java code to this functionality

**Comment by wf9a5m75** [comment]
Direction APIs are accessable using HTTP/Get directly. Please implement using HTTP plugin.
