### ISSUE TITLE
Using like DirectionsService

### ISSUE THREAD

**Issue by Tong2203** [mapsplugin/cordova-plugin-googlemaps#270]
In google map api, Route can be generated by DirectionsService.
Could you tell how to do that in this plugin?
thanks.

**Comment by sangariv** [comment]
HI @aguilacontrol 
can u please tell explain this line
     var route = new Array(my_position);

**Comment by wf9a5m75** [comment]
Before ask to someone, I recommend you search over the internet.
http://www.w3schools.com/js/js_arrays.asp

**Comment by sangariv** [comment]
hi ,
i didnt ask about the array creation.
i need to know what implies "my_position ".

**Comment by wf9a5m75** [comment]
I think the value is just LatLng.
You can get your position using map.getMyLocation()

**Comment by sangariv** [comment]
i got working..

**Comment by iBasit** [comment]
above one was not working for me, following will work fine. 

```
var gRoute = response.routes[0]['overview_path'];
for (var s = 0; s < gRoute.length; s++) {
         route.push(new plugin.google.maps.LatLng(gRoute[s].lat(), gRoute[s].lng()));
 }

map.addPolyline({
                        points: route,
                        color : '#0088FF',
                        width: 6
                    });
```
