### ISSUE TITLE
Android - Issue with back button and e.preventDefault()

### ISSUE THREAD

**Issue by AsixMaster** [mapsplugin/cordova-plugin-googlemaps#2701]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**Cordova information:**

$> cordova -version
```
9.0.0 (cordova-lib@9.0.1)
```
$> gradle -version
```
Gradle 5.6.3
```
$> cordova plugin list
```
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-call-number 1.0.1 "Cordova Call Number Plugin"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-fileopener 1.0.5 "FileOpener"
cordova-plugin-filepath 1.5.6 "cordova-plugin-filepath"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-listpicker 2.2.2 "ListPicker"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

Hi everyone,
I recently updated my Cordova project, updating my version of Cordova and **cordova-plugin-googlemaps 2.6.2**.
I have problems with the back button on Android. The problem is solved when I delete this plugin, so the focus of the problem has to be here.
I'm testing with an **Android 9.0.**

The problem occurs even if I don't initialize any map.
The rest of the code works correctly except for the **e.preventDefault ();** which prevents the application from navigate back.
Although the code of the back button is quite extensive, testing only with a simple code does not work either.

The simple code I am using is:

         document.addEventListener ("backbutton", function (e) {
             e.preventDefault ();
         }, false);

This works without the plugin.

I have no idea why this happens (I would appreciate some help that can serve as a guide). 
I do not know if it is a problem with the project or plugin.

Thank you

**Comment by AsixMaster** [comment]
You're right. It has been very easy.
Thanks :)

**Comment by CodeWithOz** [comment]
@wf9a5m75 I'm just encoutering this and I think the handling can be improved to allow devs to set multiple listeners for the backbutton event. Right now the plugin saves a reference only for the first listener, so if a dev sets more than one then only the first is executed and the rest are simply ignored. Maybe maintain an array of handlers and execute each item in the queue when the event fires?
