### ISSUE TITLE
iOS: Scroll broken if map is moved up

### ISSUE THREAD

**Issue by fsvilas** [mapsplugin/cordova-plugin-googlemaps#2702]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.4 "Whitelist"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

There is a scroll problem when the app doesn't fit in one page. For instance if you add text below the map.
If you scroll down hidding part of the map. The map continues detecting touches on the text that occupies the position where the map was before. Broking this way the scroll

In the following video, after scrolling up I am touching in the text not in the map:

[Video with Problem](https://vimeo.com/371462655)

**Expected behavior:**

When the map dissapears from screen, if you touch in the position were the map was,  the map shouldn't respond to this touches
**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

You only need to follow the installation guide and replace index.html by this one https://github.com/fsvilas/html-bug-cordova-google-maps/blob/master/index.html

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
I don't open any zip file. Please upload video to YouTube (unlisted)

**Comment by fsvilas** [comment]
Video: https://vimeo.com/371462655

**Comment by wf9a5m75** [comment]
Thanks, but I couldn't understand where you touch on.
But this plugin displays a map under HTML &lt;body&gt;

<img src="https://raw.githubusercontent.com/mapsplugin/cordova-plugin-googlemaps-doc/master/v1.4.0/class/Map/mechanism.png">

**Comment by fsvilas** [comment]
Before scrolling the area that occupies the map and that receives the events is:

<img src="https://user-images.githubusercontent.com/420097/68385417-fc031900-0159-11ea-99fd-5af0982c2da3.jpg" width="50%" height="50%">

After scrolling, the map's position is properly updated but the touch events over the red area are being received by the map, so if you try to scroll in the "Lorem ipsum..." text part, instead of scrolling the webview, you move the map:

<img src="https://user-images.githubusercontent.com/420097/68385465-189f5100-015a-11ea-97f6-7911f9b0a40e.jpg" width="50%" height="50%">

Could be a problem due to the transparency area are not being properly updated?

You can reproduce the problem simple by following the installation guide and replace index.html by this one https://github.com/fsvilas/html-bug-cordova-google-maps/blob/master/index.html. In it I added some text after the map

Thanks

**Comment by wf9a5m75** [comment]
Please try to wrap with a &lt;div&gt; for a map_canvas and text.

**Comment by wf9a5m75** [comment]
```html
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript">
    document.addEventListener("deviceready", function() {
      var div = document.getElementById("map_canvas");

      // Create a Google Maps native view under the map_canvas div.
      var map = plugin.google.maps.Map.getMap(div);

      // If you click the button, do something...
      var button = document.getElementById("button");
      button.addEventListener("click", function() {

        // Move to the position with animation
        map.animateCamera({
          target: {lat: 37.422359, lng: -122.084344},
          zoom: 17,
          tilt: 60,
          bearing: 140,
          duration: 5000
        });

        // Add a maker
        var marker = map.addMarker({
          position: {lat: 37.422359, lng: -122.084344},
          title: "Welecome to \n" +
                 "Cordova GoogleMaps plugin for iOS and Android",
          snippet: "This plugin is awesome!",
          animation: plugin.google.maps.Animation.BOUNCE
        });

        // Show the info window
        marker.showInfoWindow();

      });

    }, false);

    </script>
    <style type="text/css">
    #map_canvas { /* Must bigger size than 100x100 pixels */
      width: 100%;
      height: 500px;
    }
    button {
      padding: .5em;
      margin: .5em;
    }
    #container {
      position: fixed;
      left: 0;
      top: 0;
      right: 0;
      bottom: 0;
      width: 100%;
      height: 100%;
      overflow: scroll;
    }
    </style>
  </head>
  <body>
    <div id="container">
      <h1>Hello, World!</h1>
      <div id="map_canvas">
      </div>
       <div id="text_canvas">
          Lor... tortor.
      </div>
    </div>
  </body>
</html>

```

**Comment by fsvilas** [comment]
Yes, this way it works properly, if you surround both divs with 
`<div id="container"></div>`
If the id is different to  container it seems that it doesn't work
Thank you very much
