### ISSUE TITLE
Bottom sheet like Google Places

### ISSUE THREAD

**Issue by tryhardest** [mapsplugin/cordova-plugin-googlemaps#2704]
Carousel and bottom sheet 'pull-up' functionality are both hugely popular methods of displaying map data, which most of us are in some fashion using this map for...to display data.

I am proposing we can build, or contribute too, 2 extensible features. Maybe we raise $150 for (A) and $250 for (B)?

A) integrate a popular carousel like iDangerous swiper for horizontal scrolling of data associated with plotted markers.

B) a 'bottom sheet' like Google Places that can be pulled up from map bottom. There are a few native plugins doing similar for both iOS and Android but would require some tuning to work with WebView. 

The latter is more important to us and the former is possible without question. The bottom sheet has more complexity. 

Anyone want to chip in on these to get a bounty going? We'll put in $50 on each

**Comment by wf9a5m75** [comment]
You can communicate with the Google Places API without this plugin.
And your requested feature is kind of large.
So, I recommend you create another plugin for your purpose instead of implement the feature to this plugin directly.

**Comment by tryhardest** [comment]
I don't refer to actually using places or even place info. I am refer to a pull-up Drawer with data over map with UX of drawer (bottom sheet) similar to places bottom sheet over map.

Anyway anyone want to pitch in post and let's do it else we'll be creating our own plugin for. The second is most important to us the sheet. Carousel already works. Let's call it 300 to make a pull-up and swipe away crossplatform sheet from bottom for this plugin that can callback some data associated with map marker.
