### ISSUE TITLE
Framework7 Vue.js and history back

### ISSUE THREAD

**Issue by babonka** [mapsplugin/cordova-plugin-googlemaps#2708]
The problem is on real devices (not in browser)
When I use framework7 router to go from view with map, and use history back action (like system back button), the framework7 doesn't create new vue component instance in DOM, it uses the previous DIVs and swap its visibility. And native map layer sometimes not reinitialized (and isn't shown). All HTML layers have transparent background (I added in chrome inspeciton mode * {background: transparent} for testing). So map should work, but it looks like native map layer is absent at this situation. Is any way to reinit native map to show it in previous state?

And sometimes (very rare) native map layer is shown, but gestures not working. I know that f7 makes this, but maybe this plugin has a method to solve this situations?

**Comment by wf9a5m75** [comment]
This plugin catches the back button event. If the framework7 or vue.js also catch the back button event, you need to add the event listener after the initialization of this plugin.

**Comment by wf9a5m75** [comment]
Ping
