### ISSUE TITLE
Compiles with errors when with adMod Free

### ISSUE THREAD

**Issue by piernik** [mapsplugin/cordova-plugin-googlemaps#2709]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
c:\strony\www\ionic\myApp>cordova plugin list
cordova-admob-sdk 0.24.1 "AdMob SDK"
cordova-plugin-admob-free 0.27.0 "Cordova AdMob Plugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : ^5.0.0
@ionic-native/google-maps : 
```

**Current behavior:**
With ionic clean `sidemenu` project I have both Your plugin and `AdMob Free` (https://github.com/ratson/cordova-plugin-admob-free).
It does not compile without errors.

Your plugin and `AdMob Free` have `PLAY_SERVICES_VERSION@15.0.1`.

Here ares install commands:
```
ionic cordova plugin add cordova-plugin-admob-free --save --variable ADMOB_APP_ID="ca-app-pub-x~x" --variable PLAY_SERVICES_VERSION="15.0.1"
ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="xxx" --variable PLAY_SERVICES_VERSION="15.0.1"
```

**Expected behavior:**
Should compile

**Screen capture or video record:**
![maps-admob](https://user-images.githubusercontent.com/420691/69790705-38f38600-11c3-11ea-9583-3255fbb5572a.png)

**Comment by wf9a5m75** [comment]
I don't support the conflict with other plugins. Please ask to the AdmobFree developer, or give up to use this plugin.

**Comment by piernik** [comment]
Maybe from error description You could give me some clues how to solve it?

**Comment by wf9a5m75** [comment]
Only readable hint from the screen capture is there was a dex merge error.

**Comment by piernik** [comment]
Issue solved: https://github.com/ratson/cordova-plugin-admob-free/issues/405
Thanks
