### ISSUE TITLE
API_KEY under platform tag

### ISSUE THREAD

**Issue by Todlesstod** [mapsplugin/cordova-plugin-googlemaps#2710]
Please support having GOOGLE_MAPS_ANDROID_API_KEY and GOOGLE_MAPS_IOS_API_KEY under platform tag.
With the current set-up, when deploying for browser also, the browser config.xml will contain both those keys, which I think is a vulnerability.

**Comment by wf9a5m75** [comment]
The API keys must be restricted with your application package names.

**Comment by wf9a5m75** [comment]
As far as I know there is no way to pass the custom value to app inside.
In iOS platform, the plugin code needs to read the API key value from somewhere.
Cordova provides only `--variable` option to write custom values to `.plist` file.
However ionic/capacitor does not support it.
Ionic/capacitor is not supported currently, but it will be supported in near feature.
In that case, the way through `config.xml` file is the only possible way for this plugin.

As I wrote above, there is a way to restrict API key for only certified app.
In that case, there is no way to use the API keys in the other apps.

**Comment by Todlesstod** [comment]
I'm new to this, so I don't really understand how all of this works. 
For Android the fix should be easy, as it seems to parse the config as an XML, so it could easily look for the key in the <platform name="android"></> block (see apikey.gradle).
I don't understand the iOS code, but is the plugin unable to read properties defined in the <platform name="ios"></> block? Must the property be in the widget block?
Sorry if my questions, are stupid. I just want to make sure what I propose can't be done.

**Comment by wf9a5m75** [comment]
I think you need to work your hand before discussing this topic. Please come back after you understand this plugin read API key from what data, and why this plugin do that.
At this time, your knowledge is not enough.

If you don't want, please use another plugins.

**Comment by Todlesstod** [comment]
This was really uncalled for.

**Comment by wf9a5m75** [comment]
As I said, "please come back". The reason I close is you don't do your best at all. You just post your idea without your inspection.

If you have improve idea, please send a pull request. At least you can remove your Android/iOS API keys from config.xml file by manual.

If you don't agree with that, please use another plugins.

**Comment by Todlesstod** [comment]
Thank you very much for your time. I still think that exposing api_keys from other platforms is a bad design, never mind the fact that you can restrict who accesses it. But, then again, I worked mostly in C/C++, so I may have different standards compared to web developers.

**Comment by wf9a5m75** [comment]
I understand your standard. I wish Cordova environment provides more enough options.
But unfortunately, there is no enough choice.
This plugin has 7 years history, then becomes the current implementation.
