### ISSUE TITLE
iOS CompileC command fails

### ISSUE THREAD

**Issue by BernhardFuchs** [mapsplugin/cordova-plugin-googlemaps#2711]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "4.7.0"
@ionic-native/google-maps : "4.8.2"
```

**Current behavior:**
Depending on the iPhone there are object files missing and the Clang compiler crashes (see code sample).
If we remove the google-maps-plugin we can build the App again.
We recently upgraded to Catalina OS and Xcode 11.2.1. With earlier versions the app compiled.

**Expected behaviour:**
App builds with google maps plugin.

**Related code, data or error log (please format your code or data):**

iPhoneX output:

```CompileC /Users/<username>/Library/Developer/Xcode/DerivedData/<appname>-fyyrheepomlxpdczvznxxsulsjnf/Build/Intermediates.noindex/ArchiveIntermediates/<appname>/IntermediateBuildFilesPath/<appname>.build/Debug-iphoneos/<appname>.build/Objects-normal/armv7/PluginCircle.o <appname>/Plugins/cordova-plugin-googlemaps/PluginCircle.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Tentatively, try to reinstall the plugin.

**Comment by BernhardFuchs** [comment]
This happens after a fresh `platform add` too which we us at our CI server.

**Comment by wf9a5m75** [comment]
Please show the full log.

**Comment by BernhardFuchs** [comment]
We use the following command:

`cordova run ios --buildFlag=-UseModernBuildSystem=0 --developmentTeam=<cert-hash>"--codeSignIdentity=iPhone Developer" "--provisioningProfile=<Profile Name>" --debug --device`

I tried it without the `buildFlag` but this gives me a certificate error, which was the reason we introduced it in the first place.

This is the full log:
[compilec-error.log](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/3926540/compilec-error.log)

**Comment by wf9a5m75** [comment]
```
/Users/bernhardfuchs/workspace/tmp-psa-app/paysafecash-app/platforms/ios/Paysafecash/Plugins/cordova-plugin-googlemaps/CordovaGoogleMaps.h:10:9: fatal error: 'GoogleMaps/GoogleMaps.h' file not found
#import <GoogleMaps/GoogleMaps.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
```

I think you don't install Google Maps SDK for iOS
