### ISSUE TITLE
Capacitor Support

### ISSUE THREAD

**Issue by tototares** [mapsplugin/cordova-plugin-googlemaps#2713]
Any chance to support Ionic Capacitor in the Future without 'ionic-native'?

**Comment by wf9a5m75** [comment]
At this time, this plugin does not work on Capacitor.

**Comment by Mapiac** [comment]
Anyone else throw in $50 on this to get help make it happen?

**Comment by tototares** [comment]
> Anyone else put in $50 on this to get help make it happen?

yes I would put in some money for that, when the plugin would work for android and ios. do you know somebody who can realise that?

**Comment by dupiesdupreez** [comment]
For any one wanting to use google maps with Capacitor, you can follow this tutorial. 
It works for both android and IOS, tested it myself.

[Using Google Maps and Geolocation in Ionic with Capacitor
](https://www.joshmorony.com/using-google-maps-and-geolocation-in-ionic-with-capacitor/)

**Comment by AEINSIT** [comment]
@dupiesdupreez this tutorial describes how to use the javascript maps API, but there are reasons why we would prefer the native way:

- out target platform is only ios and android
- better performance, also for older devices
- way more easy offline usage
- saving running costs (see [Google Maps Pricing](https://cloud.google.com/maps-platform/pricing/?hl=de&utm_source=google&utm_medium=cpc&utm_campaign=FY18-Q2-global-demandgen-paidsearchonnetworkhouseads-cs-maps_contactsal_saf&utm_content=text-ad-none-none-DEV_c-CRE_321425922652-ADGP_Hybrid+%7C+AW+SEM+%7C+BKWS+~++Google+Maps+Price+BMM-KWID_43700039888869803-kwd-313356770055-userloc_9044593&utm_term=KW_%2Bgoogle%20%2Bmaps%20%2Bpricing-ST_%2Bgoogle+%2Bmaps+%2Bpricing&gclid=EAIaIQobChMIkbTYmZKo5wIVheh3Ch0YrAK7EAAYASAAEgKWDvD_BwE))

Our company would also invest in a capacitor version of this plugin.

**Comment by HansKrywaa** [comment]
@wf9a5m75 - how much will it cost us to pay you to implement capacitor support?

**Comment by wf9a5m75** [comment]
Please contact me by email

**Comment by IngAjVillalon** [comment]
I also join to support with money so that this plugin is compatible with Capacitor.
I think it is a good idea for you to do this collection publicly so that all us interested could help.

**Comment by Radecom** [comment]
Yes, friend, your plugin is very useful. Tell us what you need to take it to the next level, and we will help you.

**Comment by wf9a5m75** [comment]
I made a fundraising of this topic.
If you really want to use this plugin on Capacitor iOS, please support my activity.

[Fundraising : support for Capacitor iOS](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781)

**Comment by tototares** [comment]
https://github.com/capacitor-community/proposals/issues/20

Please 👍 the issue if you'd like to see this plugin for Capacitor!

**Comment by tototares** [comment]
This is a very new capacitor plugin which already has a few basic functions for ios and android, looks already really good: 

https://github.com/hemangsk/capacitor-googlemaps-native

**Comment by wf9a5m75** [comment]
@tototares Thank you for the information. This is just my curiosity. Is the `capacitor-googlemaps-native` able to display a side bar over the map (like this image)?

![capture (1)](https://user-images.githubusercontent.com/167831/86501352-014a4f00-bd4d-11ea-986f-ba6f4cf0645b.png)

By the way, I have been working on [this project](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781) recently.
It means `cordova-plugin-googlemaps` will support `Capacitor iOS` officially.
