### ISSUE TITLE
[Android] myLocationButton = false or myLocation = false and the plugin ask for geolocation permission

### ISSUE THREAD

**Issue by goinnn** [mapsplugin/cordova-plugin-googlemaps#2714]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
It is not neccesary

**Current behavior:**
Creating a Map with myLocation = false or myLocationButton = false. The app ask for geolocation permission.

**Expected behavior:**
myLocation = false or myLocationButton = false are the same like if I don't pass these params

**Screen capture or video record:**
It is not neccesary

**Related code, data or error log (please format your code or data):**

	var options = {
		camera: {
		target: {lat: ..., lng: ...},
		zoom: 19
		},
		controls: {
		myLocation: false
		}
	};
	var map = plugin.google.maps.Map.getMap(mapDiv, options)

The problem is in this [line](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/PluginMap.java#L189
): 

    if (controls.has("myLocationButton") || controls.has("myLocation")) {

The problem is the plugin only ask for if in control **has** both keys, but it should ask if has and the value is true.

**Comment by goinnn** [comment]
Hi!, I am a mate of @zarelint. We had update our app 2 weeks ago. And in the way we have found several bugs or details.

We had updated our apps (Android and iOS) from version [2.1.1 forked](https://github.com/goinnn/cordova-plugin-googlemaps/tree/v2.1.1#custom) to last version forked: [2.6.2](https://github.com/we-are-Joinup/cordova-plugin-googlemaps/tree/2.6.2#custom)

Thanks a lot for this maravellous project! We can grow up thanks of you.

Links of our apps, if you want test or something (please move to Spain, France or Portugal):

1. https://play.google.com/store/apps/details?id=com.joinuptaxi.passenger&hl=es
2. https://apps.apple.com/es/app/joinup-pedir-y-reservar-taxi/id554668455

**Comment by wf9a5m75** [comment]
Google Maps SDK for iOS needs the permission when one of flags is true. This plugin designs all code are synchronized in each platforms as much as possible, in order to maintain the code.

This is not a big. Designed behavior.

**Comment by goinnn** [comment]
@wf9a5m75 I didn't explain good, with something like this:

  var options = {
    controls: {
        myLocation: false,                         <-- False
        myLocationButton: false                <-- False.
    }
  };
  var map = plugin.google.maps.Map.getMap(mapDiv, options)

In Android, the plugin ask for geolocation permission. 

With something like this, the plugin does not ask for geolocation permission:

  var options = {
    controls: {
    }
  };
  var map = plugin.google.maps.Map.getMap(mapDiv, options)


@wf9a5m75 Please, consider to reopen this issue...
