### ISSUE TITLE
[Android] Little flicker html when change app from background to foreground

### ISSUE THREAD

**Issue by goinnn** [mapsplugin/cordova-plugin-googlemaps#2715]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-android-firebase-gradle-release 3.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 3.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-core-android-extensions 2.0.0 "CoreAndroidExtensions"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filepath 1.5.5 "cordova-plugin-filepath"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-localization-strings 3.1.0 "Localization"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 2.0.3-dev "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-transparent-status-bar 1.0.1 "Transparent status bar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 3.3.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 4.4.0
@ionic-native/google-maps : 4.4.2
```

**Current behavior:**

The HTML elements fades out and very quicky fades in.

**Expected behavior:**

The HTML elements don't do anything

**Screen capture or video record:**

https://www.youtube.com/watch?v=bs_PajGI8kk

**Comment by goinnn** [comment]
Hi!, I am a mate of @zarelint. We had update our app 2 weeks ago. And in the way we have found several bugs or details.

We had updated our apps (Android and iOS) from version [2.1.1 forked](https://github.com/goinnn/cordova-plugin-googlemaps/tree/v2.1.1#custom) to last version forked: [2.6.2](https://github.com/we-are-Joinup/cordova-plugin-googlemaps/tree/2.6.2#custom)

Thanks a lot for this maravellous project! We can grow up thanks of you.

Links of our apps, if you want test or something (please move to Spain, France or Portugal):

1. https://play.google.com/store/apps/details?id=com.joinuptaxi.passenger&hl=es
2. https://apps.apple.com/es/app/joinup-pedir-y-reservar-taxi/id554668455

**Comment by wf9a5m75** [comment]
Please share the project files that is able to reproduce your problem on to GitHub.
Without it, I cannot help you.

**Comment by goinnn** [comment]
Is this problem not common? We had the same problem with version 2.1.1.

We can not share the project files easily, but we can talk about another way... or we can try to create a little project with this problem and share it.

**Comment by wf9a5m75** [comment]
>  we can try to create a little project with this problem and share it.

Yes, that's fine. I don't want to debug inside your app too.

**Comment by wf9a5m75** [comment]
By the way, I don't support for older versions.

**Comment by goinnn** [comment]
> By the way, I don't support for older versions.

We are using latest version 2.6.2

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/multiple_maps

`2.7.0-20191107-1035`

**Comment by goinnn** [comment]
We have the same problem with the last version 2.7.0-X
