### ISSUE TITLE
[Android] Clear map block map

### ISSUE THREAD

**Issue by goinnn** [mapsplugin/cordova-plugin-googlemaps#2717]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-android-firebase-gradle-release 3.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 3.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-core-android-extensions 2.0.0 "CoreAndroidExtensions"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filepath 1.5.5 "cordova-plugin-filepath"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-localization-strings 3.1.0 "Localization"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 2.0.3-dev "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-transparent-status-bar 1.0.1 "Transparent status bar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 3.3.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 4.4.0
@ionic-native/google-maps : 4.4.2
```

**Current behavior:**
Currently when change between pages the app call to clear map. Then the map is blocked 1 second and there is a ugly effect.

https://www.youtube.com/watch?v=nTzeFPnUvJQ

**Expected behavior:**
A behaviour more fluid.

https://www.youtube.com/watch?v=UsfPwrUrStg

**Screen capture or video record:**

With version 3.6.2: https://www.youtube.com/watch?v=nTzeFPnUvJQ
With our fork: https://www.youtube.com/watch?v=UsfPwrUrStg

**Related code, data or error log (please format your code or data):**

Commit that fix this error: https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/b130a755a15a3fbc582c35d9a0e5ac5aef2bf773

With official version if keySet.size() is 0, the plugin wait a second... it is no sense. I think it is only a indent error.

Another related commit: https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/98af0f0465aadc0edccc9b5363977186a5174d68

**Comment by goinnn** [comment]
Hi!, I am a mate of @zarelint. We had update our app 2 weeks ago. And in the way we have found several bugs or details.

We had updated our apps (Android and iOS) from version [2.1.1 forked](https://github.com/goinnn/cordova-plugin-googlemaps/tree/v2.1.1#custom) to last version forked: [2.6.2](https://github.com/we-are-Joinup/cordova-plugin-googlemaps/tree/2.6.2#custom)

Thanks a lot for this maravellous project! We can grow up thanks of you.

Links of our apps, if you want test or something (please move to Spain, France or Portugal):

1. https://play.google.com/store/apps/details?id=com.joinuptaxi.passenger&hl=es
2. https://apps.apple.com/es/app/joinup-pedir-y-reservar-taxi/id554668455

**Comment by wf9a5m75** [comment]
This is already fixed in the multiple_maps branch version.

**Comment by goinnn** [comment]
@wf9a5m75 I think this bug is in multiple_maps branch too. I will confirm it.

Do you want the pull request from my fork to multiple_maps branch or master branch?

**Comment by JordyLangen** [comment]
This as fixed in https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/2694 and should be merged into `multiple_maps` right now 👍

**Comment by goinnn** [comment]
Thanks @JordyLangen
