### ISSUE TITLE
Java error when I change quickly beetween pages

### ISSUE THREAD

**Issue by goinnn** [mapsplugin/cordova-plugin-googlemaps#2720]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [?] **iOS**
- [?] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
```
cordova-android-firebase-gradle-release 3.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 3.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-core-android-extensions 2.0.0 "CoreAndroidExtensions"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filepath 1.5.5 "cordova-plugin-filepath"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-localization-strings 3.1.0 "Localization"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 2.0.3-dev "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-transparent-status-bar 1.0.1 "Transparent status bar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 3.3.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 4.4.0
@ionic-native/google-maps : 4.4.2
```

**Current behavior:**
Similar to #2718. When I change quickly beetween pages with map I get a java error.

1. To do something like this video: https://www.youtube.com/watch?v=DQQu8gksaww
2. Get next java error

**Expected behavior:**
No java error

**Related code, data or error log (please format your code or data):**

Fixing error:

https://github.com/we-are-Joinup/cordova-plugin-googlemaps/commit/d7b78e2d2f534fa4607afb3d4430083226437856

I think would be a good idea to have a test app with a transition from a page with a map to another page with a map. We had a lot of problems for this use case.

**Comment by goinnn** [comment]
Hi!, I am a mate of @zarelint. We had update our app 2 weeks ago. And in the way we have found several bugs or details.

We had updated our apps (Android and iOS) from version [2.1.1 forked](https://github.com/goinnn/cordova-plugin-googlemaps/tree/v2.1.1#custom) to last version forked: [2.6.2](https://github.com/we-are-Joinup/cordova-plugin-googlemaps/tree/2.6.2#custom)

Thanks a lot for this maravellous project! We can grow up thanks of you.

Links of our apps, if you want test or something (please move to Spain, France or Portugal):

1. https://play.google.com/store/apps/details?id=com.joinuptaxi.passenger&hl=es
2. https://apps.apple.com/es/app/joinup-pedir-y-reservar-taxi/id554668455

**Comment by wf9a5m75** [comment]
Please send a pull request.

**Comment by goinnn** [comment]
@wf9a5m75 do you like the solution?

**Comment by wf9a5m75** [comment]
If you send a pull request, I can test it easily later. If I this your debugging is true, then I can merge it.

At this time, I reply your comments on my smartphone (and I just walked up from my bed).

**Comment by goinnn** [comment]
Ok! Good day!

I will try to do it tomorrow or next week

**Comment by goinnn** [comment]
It was fixed in multiple_maps_branch. Commit: ab684afb6c459c91dd9bf6bea2a7fda2ceb6e62f
