### ISSUE TITLE
Crash in iOS

### ISSUE THREAD

**Issue by goinnn** [mapsplugin/cordova-plugin-googlemaps#2721]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-android-firebase-gradle-release 3.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 3.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-core-android-extensions 2.0.0 "CoreAndroidExtensions"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filepath 1.5.5 "cordova-plugin-filepath"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-localization-strings 3.1.0 "Localization"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 2.0.3-dev "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-transparent-status-bar 1.0.1 "Transparent status bar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 3.3.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 4.4.0
@ionic-native/google-maps : 4.4.2
```

**Current behavior:**
Sometimes only in one of our apps in iOS the app is crashed. And we get next error:

    2019-11-13 11:45:50.662662 Joinup driver[297:8978] -[UIView mapType]: unrecognized selector sent to instance 0x102559780
    2019-11-13 11:45:50.667154 Joinup driver[297:8978] Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView mapType]: unrecognized selector sent to instance 0x102559780' First throw call stack:
    
    ([pluginViewCtrl.overlayId hasPrefix:@"panorama"] ||
    ([pluginViewCtrl.overlayId hasPrefix:@"map"] &&
    ((GMSMapView *)pluginViewCtrl.view).mapType != kGMSTypeSatellite &&

**Expected behavior:**
Does not crash

**Related code, data or error log (please format your code or data):**

We have fixed it with these commit:
https://github.com/we-are-Joinup/cordova-plugin-googlemaps/commit/3aace62aa6cd389f20c74a63e16f5678145d8417
https://github.com/we-are-Joinup/cordova-plugin-googlemaps/commit/612618c0dbde6f3b8d765847502fa03ed43621e1

We know there is not a good solution, but we don't use Satellite map or Hybrid map, so for us it is a good solution. But sometimes pluginViewCtrl.view is not a GMSMapView. It is very very strange error.

**Comment by goinnn** [comment]
Hi!, I am a mate of @zarelint. We had update our app 2 weeks ago. And in the way we have found several bugs or details.

We had updated our apps (Android and iOS) from version [2.1.1 forked](https://github.com/goinnn/cordova-plugin-googlemaps/tree/v2.1.1#custom) to last version forked: [2.6.2](https://github.com/we-are-Joinup/cordova-plugin-googlemaps/tree/2.6.2#custom)

Thanks a lot for this maravellous project! We can grow up thanks of you.

Links of our apps, if you want test or something (please move to Spain, France or Portugal):

1. https://play.google.com/store/apps/details?id=com.joinuptaxi.passenger&hl=es
2. https://apps.apple.com/es/app/joinup-pedir-y-reservar-taxi/id554668455

**Comment by wf9a5m75** [comment]
Thank you for debugging.
How often does this error occurred?

**Comment by goinnn** [comment]
We have two apps, something like Uber. One for passenger and one for taxi drivers.

We get this error, only when taxi cancel a service. 1 or 2 for every 10 services the taxi driver cancel.

So, 10-20% of the cases but only in a use case

**Comment by wf9a5m75** [comment]
`We get this error, only when taxi cancel a service.`

I don't want to debug inside your app.
Please create a reproduce code, and share it on GitHub.

**Comment by goinnn** [comment]
> Please create a reproduce code, and share it on GitHub.

I understand perfectly. We can create something to reproduce them. But please, give us time... 

The most of these issues have a commit to fix them :-) So, they don't need share anything and the others... we will try to have a little public project (or projects) to detect them.

**Comment by battika** [comment]
Pablo, I also have users reporting crashes on IOS but I am struggling to reproduce it in the emulator or on my IPhone7. I have seen random crashes on IPhone 6 and IPhone XS but they were intermittent issues, I never got to reproduce them. Do you have any hint how to reproduce these IOS crashes? I am not sure if I understand the fix (or workaround) you are proposing in the pull request.

**Comment by goinnn** [comment]
Hi @battika, I'm sorry but I only get this error in a use case (one of 20-30 use cases with maps). Our use case is something like this:

1. Enter in a page with map
2. Click on a button with a pop action
3. Crash on iOS in this use case 1 or 2 times of 10

We reproduce this in real devices and emulators. But we don't understand because only 1 or 2 times of 10 and only in this use case.

We have removed a feature for Satellite map or Hybrid map. So, how we don't use this type map we have removed this comparation. And we are happy, but we understand this is not the way.

**Comment by wf9a5m75** [comment]
I'm not sure this plugin catches native crash logs also, but try this one.
https://ionicframework.com/docs/native/firebase-crashlytics

At least, original Firebase Crashlytics is able to catch crashes in native side, and report it to your dashboard.
