### ISSUE TITLE
Improve transition from page with map to another page with map

### ISSUE THREAD

**Issue by goinnn** [mapsplugin/cordova-plugin-googlemaps#2723]
Improve transition from page with map to another page with map

**Please tell us your new feature idea**

When you move from page with map to another page with map the documentation says to do something like this:

Page 1:
willLeave
map.setDiv(null);

Page 2:
didEnter
map.setDiv(myDiv);

Both map are the same instance.

These setDivs are called almost at the same time. Both fire several events and the transition is not good, this problem is bigger if you have html elements on the map.

When our app goes from the page x (with map) to page y (with map) we don't call to setDiv(null) we do something like this:

Page 1:
willLeave
setDivNullWithouEvents();

Page 2:
didEnter
map.setDiv(myDiv);

Where setDivNullWithouEvents is a function like this:

    setDivNullWithouEvents() {
      let div = this.map.get('div');
      div.removeAttribute('__pluginMapId');
      this.map.set('div', null, true);
    }

If do you like, our proposal is document it and to change setDiv to include this feature.

**Why do you need it?**

We have two pages with map, one continuation of the other  page.

**How helps other people?**

Every person that have same use case in its app

**Comment by goinnn** [comment]
Related with this: 

> I think would be a good idea to have a test app with a transition from a page with a map to another page with a map. We had a lot of problems for this use case.

**Comment by wf9a5m75** [comment]
In the latest version, the plugin destroys the map instance when the map div is destroyed automatically.

Other case, usage like your case is not a normal way. 

The goal of this plugin is to reproduce the Google Maps JavaScript API v3. Your idea is not on the path.

So your idea is good for you, but it won't in the document.

**Comment by goinnn** [comment]
latest version is 2.6.2 or multiple_maps branch or another branch?

**Comment by wf9a5m75** [comment]
Historical reason, the edge version is in the `multiple_maps` branch always. Other branch is almost my test or another dev version

**Comment by wf9a5m75** [comment]
You can follow the network.

https://github.com/mapsplugin/cordova-plugin-googlemaps/network

**Comment by battika** [comment]
@goinnn just wondering what sort of events do you avoid by using this alternate "setDiv" method?

**Comment by goinnn** [comment]
> @goinnn just wondering what sort of events do you avoid by using this alternate "setDiv" method?

1. Obviously a lot of code of setDiv mainly: https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Map.js#L861
2. div_changed: https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/js_CordovaGoogleMaps-for-android_ios.js#L707

**Comment by goinnn** [comment]
> In the latest version, the plugin destroys the map instance when the map div is destroyed automatically.

I have upgraded with the last version of multiple_maps branch. And my code works right. After it,  I have removed my solution, now I always do setDiv(null) when I will leave a page with map. And the map is not destroy never.

Case 1:

1. MapPage DidEnter: create map with map.one
2. MapPage WillLeave: setDiv(null)
3. ProfilePage DidEnter: nothing
4. ProfilePage WillLeave: nothing
5. MapPage DidEnter: setDiv(mapDiv)

Case 2:

1. MapPage DidEnter: create map with map.one
2. MapPage WillLeave: setDiv(null)
3. AnotherMapPage DidEnter: setDiv(mapDiv2)
4. AnotherMapPage WillLeave: setDiv(null)
5. MapPage DidEnter: setDiv(mapDiv)

With my solution:

Case 1 (exactly same):

1. MapPage DidEnter: create map with map.one
2. MapPage WillLeave: setDiv(null)
3. ProfilePage DidEnter: nothing
4. ProfilePage WillLeave: nothing
5. MapPage DidEnter: setDiv(mapDiv)

Case 2:

1. MapPage DidEnter: create map with map.one
2. MapPage WillLeave: setDivNullWithouEvents() <-- events run with next step
3. AnotherMapPage DidEnter: setDiv(mapDiv2)
4. AnotherMapPage WillLeave: setDivNullWithouEvents() <-- events run with next step
5. MapPage DidEnter: setDiv(mapDiv)


So, my solution is a normal way. Currently if you move between pages with maps, the plugins fires and executes events two times and you only need to run one time. It is only a detail, but with this detail you get a great improve of the  user experience.

> The goal of this plugin is to reproduce the Google Maps JavaScript API v3. Your idea is not on the path.

Yes, I gave you it 2.5 years ago (more or less) #1510

**Comment by wf9a5m75** [comment]
This plugin is not only for ionic. Specialized for ionic usage is not for good to this plugin.

**Comment by battika** [comment]
Thanks Pablo, I understand that it can only be an issue when you transition between pages with map. That is not my use case so I leave the official method in place (setDiv(null)).

**Comment by goinnn** [comment]
> This plugin is not only for ionic. Specialized for ionic usage is not for good to this plugin.

Yes, I understand. I explain my point of view with ionic because I use ionic. But it was a way to explain it.

My idea is to improve in several cases the user experience of the user (with ionic or without ionic). When I executed the events of a setDiv two times in a small period of time the app was slows down.

My idea is change setDiv for something like this:

    Map.prototype.setDiv = function(div, fireEvents) {
      if (fireEvents === undefined) {
        fireEvents = true;
      }
      ...
    }

And only to add this case use to documentation. And set fireEvents like true when the developer consider.

Do you like a little more?

Feel free if you dislike it to close the issue... it is your project and you rules... but my opinion is that this issue is necesary for a "map app", this is not necesary for a app with a map. So, if the map is the main feature, and there are several maps it is necesary. If you have only a map like a secondary feature it is not necesary.

Thanks again!

**Comment by Mapiac** [comment]
We never destroy map. We keep it persisting under webview at all time for immediate transitions.
