### ISSUE TITLE
MarkerOption.anchor property does not work

### ISSUE THREAD

**Issue by 8bhsolutions** [mapsplugin/cordova-plugin-googlemaps#2730]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core :  4.20.0
@ionic-native/google-maps :  4.21.0
```

**Current behavior:**
Setting anchor property of MarkerOption have no effect.
Require calling setIconAnchor to take effect

```
const markerOptions = {
....
anchor: [32, 32],   // Have no effect
}
const marker = this.map.addMarkerSync(markerOptions);
marker.setIconAnchor(markerOptions.anchor[0], markerOptions.anchor[1]);   // Requires this line to take effect
```

**Expected behavior:**
During the addMarkerSync function, the anchor property should be applied

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Could you show me the full code of `markerOptions`?

**Comment by services4smb** [comment]
Check out this -> https://github.com/ionic-team/ionic-native-google-maps/issues/259

**Comment by 8bhsolutions** [comment]
```
		const url = "./assets/imgs/finish.png";
		const markerPos = new LatLng(lat, lng);
		const options: MarkerOptions = {
			title: 'Marker',
			snippet: "hello",
			icon: {
				url: url,
				size: { width: 32, height: 32 },
			},
			position: markerPos,
			zIndex: 999,
			anchor: [0, 32],
		}
		const marker = this.map.addMarkerSync(options);
		marker.setIconAnchor(options.anchor[0], options.anchor[1]);

		const currLoc = await this.map.getMyLocation();
		const routePoints: ILatLng[] = [];
		routePoints.push(currLoc.latLng);
		routePoints.push(markerPos);

		const po: PolylineOptions = {
			points: routePoints,
			width: 8,
			geodesic: true
		}
		this.map.addPolylineSync(po);

```

**Comment by 8bhsolutions** [comment]
@wf9a5m75 
code snippet above.

The polyline is used to highlight the lat/lng of the markerPosition

**Comment by 8bhsolutions** [comment]
@services4smb 
I can confirm, moving anchor inside works.
