### ISSUE TITLE
Phonegap googlemaps plugin only work in build version with Phonegap Build

### ISSUE THREAD

**Issue by Micha851** [mapsplugin/cordova-plugin-googlemaps#2733]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ X] any problem or bug report

**OS:**  (check one with "x")
- [X ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**Current behavior:**

When i upload my project to Phonegap Build the googlemaps plugin work fine, but when I use the quick Live Demo with 
$> phonegap serve
the map doesn´t show.

**Comment by wf9a5m75** [comment]
Yes, because the map is native code, not JavaScript

**Comment by Micha851** [comment]
> 
> 
> Yes, because the map is native code, not JavaScript

Wow thanks for the fast reply. So there is no chance to get the plugin working while using phonegap serve?

**Comment by wf9a5m75** [comment]
No chance.

**Comment by wf9a5m75** [comment]
I'm not familiar with phonegap, but you can use this plugin instead with cordova. Please try this.
https://www.npmjs.com/package/cordova-plugin-browsersync

**Comment by Micha851** [comment]
Ok thanks
