### ISSUE TITLE
Tileserver missing class names

### ISSUE THREAD

**Issue by leabdalla** [mapsplugin/cordova-plugin-googlemaps#2734]
I'm trying to use TileServer. My 3rd-party tool exported this script:

    <html>
      <head>
        <title>MyMap</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
        <script src="https://maps.google.com/maps/api/js?sensor=false"></script>
        <script>
          function init() {
            var mapBounds = new google.maps.LatLngBounds(
                new google.maps.LatLng(-27.82676708, -50.38245456),
                new google.maps.LatLng(-27.74233264, -50.33024907));
            var mapMinZoom = 11;
            var mapMaxZoom = 21;
            var opts = {
              streetViewControl: false,
              tilt: 0,
              mapTypeId: google.maps.MapTypeId.HYBRID,
              center: new google.maps.LatLng(0,0),
              zoom: mapMinZoom
            }
            var map = new google.maps.Map(document.getElementById("map"), opts);

            // https://developers.google.com/maps/documentation/javascript/examples/maptype-image-overlay
            var imageMapType = new google.maps.ImageMapType({
                getTileUrl: function(coord, zoom) {
                  var proj = map.getProjection();
                  var z2 = Math.pow(2, zoom);
                  var tileXSize = 256 / z2;
                  var tileYSize = 256 / z2;
                  var tileBounds = new google.maps.LatLngBounds(
                    proj.fromPointToLatLng(new google.maps.Point(coord.x * tileXSize, (coord.y + 1) * tileYSize)),
                    proj.fromPointToLatLng(new google.maps.Point((coord.x + 1) * tileXSize, coord.y * tileYSize))
                  );
                  if (!mapBounds.intersects(tileBounds) || zoom < mapMinZoom || zoom > mapMaxZoom) return null;
                  return "{z}/{x}/{y}.png".replace('{z}',zoom).replace('{x}',coord.x).replace('{y}',coord.y);
                },
                tileSize: new google.maps.Size(256, 256),
                minZoom: mapMinZoom,
                maxZoom: mapMaxZoom,
                name: 'Tiles'
            });

            map.overlayMapTypes.push(imageMapType);
            map.fitBounds(mapBounds);

          }
        </script>
        <style>
          html, body, #map { width:100%; height:100%; margin:0; padding:0; }
        </style>
      </head>
      <body onload="init()">
        <div id="map"></div>
      </body>
    </html>

So I'm trying to make it run in my Ionic 4 Google Maps plugin. Here is my script:

    import {
      GoogleMaps,
      GoogleMap,
      GoogleMapsEvent,
      GoogleMapsMapTypeId,
      LatLng,
      MarkerOptions,
      Marker,
      HtmlInfoWindow,
      LatLngBounds,
      Circle,
      Poly,
      Spherical,
      GroundOverlay,
      TileOverlay,
      KmlOverlay,
    } from "@ionic-native/google-maps";

    ...
    ...

    this.tileOverlay = this.map.addTileOverlay({
      getTile: function(x, y, zoom) {
        let mapMinZoom = 11;
        let mapMaxZoom = 21;

        let proj = this.map.getProjection();
        var z2 = Math.pow(2, zoom);
        var tileXSize = 256 / z2;
        var tileYSize = 256 / z2;
        var tileBounds = new LatLngBounds(
          proj.fromPointToLatLng(new google.maps.Point(coord.x * tileXSize, (coord.y + 1) * tileYSize)),
          proj.fromPointToLatLng(new google.maps.Point((coord.x + 1) * tileXSize, coord.y * tileYSize))
        );
        if (!mapBounds.intersects(tileBounds) || zoom < mapMinZoom || zoom > mapMaxZoom) return null;
        return "http://www.mysite.com/customer/mycustomer/uploads/tileserver/"+zoom+"/"+x+"/"+y+".png";
      }
    });

So I'm getting these errors:

    [ng] src/app/tab-dashboard/tab-dashboard.page.ts(274,28): error TS2554: Expected 0-1 arguments, but got 2.
    [ng] src/app/tab-dashboard/tab-dashboard.page.ts(275,40): error TS2304: Cannot find name 'google'.
    [ng] src/app/tab-dashboard/tab-dashboard.page.ts(275,58): error TS2304: Cannot find name 'coord'.
    [ng] src/app/tab-dashboard/tab-dashboard.page.ts(275,80): error TS2304: Cannot find name 'coord'.
    [ng] src/app/tab-dashboard/tab-dashboard.page.ts(276,40): error TS2304: Cannot find name 'google'.
    [ng] src/app/tab-dashboard/tab-dashboard.page.ts(276,59): error TS2304: Cannot find name 'coord'.
    [ng] src/app/tab-dashboard/tab-dashboard.page.ts(276,85): error TS2304: Cannot find name 'coord'.
    [ng] src/app/tab-dashboard/tab-dashboard.page.ts(278,16): error TS2304: Cannot find name 'mapBounds'.

Is that the correct way to implement this? Where should I find these missing names?

**Comment by wf9a5m75** [comment]
This is strange at least.

```
var tileBounds = new LatLngBounds(
      proj.fromPointToLatLng(new google.maps.Point(coord.x * tileXSize, (coord.y + 1) * tileYSize)),
      proj.fromPointToLatLng(new google.maps.Point((coord.x + 1) * tileXSize, coord.y * tileYSize))
    );
```

**Comment by leabdalla** [comment]
I've just removed this code block and it worked.

thanks!
