### ISSUE TITLE
ionic 4 - load KML file is triggering CORS error

### ISSUE THREAD

**Issue by leabdalla** [mapsplugin/cordova-plugin-googlemaps#2735]
I'm trying to load Kml file with this code:

    let server_url = 'http://www.mysite.com/customer/uploads/googlemaps';
    let server_file = 'myfile.kml';
    this.kmlOverlay = this.map.addKmlOverlay({
      'url': server_url + '/' + server_file,
    });

This is causing CORS errors

    Access to XMLHttpRequest at 'http://www.mysite.com/customer/uploads/googlemaps/myfile.kml' from origin 'http://localhost:8100' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Checking at the plugin code, I found `loadKml()` method 

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/3f6ce0f97b1ac2aafcb35c389a9dec7031b7054b/src/browser/PluginKmlOverlay.js#L38

Looks like this method tries to load KML file by using `'Content-Type', 'application/xml; charset=UTF-8'`, and this is what causes Ionic to try the preflight OPTIONS request: https://ionicframework.com/docs/faq/cors#how-does-cors-work

As I'm not in control on the file server, is it possible to load the KML without using `'Content-Type', 'application/xml` to avoid the preflight request?

**Comment by wf9a5m75** [comment]
Do you understand what the `CORS` mean?

You must run you app on `http://www.mysite.com`

**Comment by leabdalla** [comment]
It worked, thanks
