### ISSUE TITLE
Cannot add KML file - TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by leabdalla** [mapsplugin/cordova-plugin-googlemaps#2736]
I'm trying to add this KML in Ionic 4 app: https://pastebin.com/5LHLeTKf

So I'm getting this errors:

        TypeError: Cannot read property 'children' of undefined
        at KmlParserClass._default (2dbe94fd-1b0d-4101-943b-2b6f729a03df:429)
        at KmlParserClass.parseXml (2dbe94fd-1b0d-4101-943b-2b6f729a03df:321)
        at 2dbe94fd-1b0d-4101-943b-2b6f729a03df:433
        at Array.forEach (<anonymous>)
        at KmlParserClass._default (2dbe94fd-1b0d-4101-943b-2b6f729a03df:431)
        at KmlParserClass.parseXml (2dbe94fd-1b0d-4101-943b-2b6f729a03df:321)
        at 2dbe94fd-1b0d-4101-943b-2b6f729a03df:356
        at Array.forEach (<anonymous>)
        at KmlParserClass._style (2dbe94fd-1b0d-4101-943b-2b6f729a03df:355)
        at KmlParserClass.parseXml (2dbe94fd-1b0d-4101-943b-2b6f729a03df:321)

I tried to compare tags to check compatibility problems and found two occurences:

- LinearRing
- tessellate

These tags are present in KML and not present on plugin allowed tags table. However, I've removed them and the error keeps happening.

Also, I've imported the KML in Google Earth (mac) and it worked good.

How can I find out what is the problem on the file?

**Comment by wf9a5m75** [comment]
Could you read the document first?

**Comment by leabdalla** [comment]
which one?

**Comment by leabdalla** [comment]
As I said before, I tried to compare with plugin compatible tags. According the docs:

- balloonstyle (<description> only)
- coordinates
- document
- extendeddata
- folder
- groundoverlay
- iconstyle
- kml
- linestring
- lookat
- multigeometry
- networklink (<region> is also supported)
- photooverlay
- placemark
- point
- polygon
- schema
- stylemap (normal mode only)
- styles
- styleurl

**Comment by leabdalla** [comment]
I've commented all styles that uses IconStyle tag like this one:

    <Style id="sh_ylw-pushpin12">
      <IconStyle>
        <scale>1.3</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>
        </Icon>
        <hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>
      </IconStyle>
      <LineStyle>
        <color>ff0000ff</color>
        <width>2</width>
      </LineStyle>
    </Style>

So I got it working but with a few errors (probably due to missing those styles).

What I expect (same KML being viewed in another app):

<img width="361" alt="Screen Shot 2020-01-28 at 13 05 18" src="https://user-images.githubusercontent.com/925727/73281651-0cfa7e00-41cf-11ea-88e8-61df1fb7797c.png">

What I'm seeing in Ionic:

<img width="175" alt="Screen Shot 2020-01-28 at 13 05 23" src="https://user-images.githubusercontent.com/925727/73281680-18e64000-41cf-11ea-8482-60de2e19665a.png">

Any help?
