### ISSUE TITLE
Map Dissappears after navigation and coming back

### ISSUE THREAD

**Issue by zack403** [mapsplugin/cordova-plugin-googlemaps#2737]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
If the map div is destroyed, the map is also destroyed.

**Comment by zack403** [comment]
Okay, please can you show me how i can solve this issue ? i have been battling with it for weeks now, thanks.

**Comment by wf9a5m75** [comment]
Could you share your project files on GitHub repository?

Without your code, I can't help you

**Comment by zack403** [comment]
its a company project though, not personal and the repo is private. Please if you can help, please do, thanks

**Comment by battika** [comment]
Before you leave the page call map.setDiv(null) and when you come back to the page your DOM is ready, call map.setDiv(divID). It will do the trick.

**Comment by zack403** [comment]
> Before you leave the page call map.setDiv(null) and when you come back to the page your DOM is ready, call map.setDiv(divID). It will do the trick.

I have tried this before but still did not work, thanks for ur suggestion tho

**Comment by battika** [comment]
Are you using Ionic 3 or 4?

**Comment by battika** [comment]
Sorry, silly question. I can see you are using Ionic :)
