### ISSUE TITLE
[android] Crash (NullPointerException) when clicking on Polyline

### ISSUE THREAD

**Issue by ndrake** [mapsplugin/cordova-plugin-googlemaps#2738]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.7.0-20191107-1035 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.3 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : ^5.5.0
@ionic-native/google-maps : ^5.5.0
```

**Current behavior:**

My app displays multiple Polylines on a map.  If the user clicks a Polyline, I add a marker where they clicked and display an HTMLInfoWindow.  On Browser and iOS this works fine. On Android, the click results in a NullPointerException. It sometimes takes a few clicks on the line to trigger the crash.

**Expected behavior:**

Clicking on a Polyline does not cause a crash and allows my POLYLINE_CLICK handler to run and display an HtmlInfoWindow.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

Stacktrace:

```
2020-01-30 14:36:49.865 8670-8670/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 8670
    java.lang.NullPointerException: Attempt to read from field 'double com.google.android.gms.maps.model.LatLng.latitude' on a null object reference
        at plugin.google.maps.PluginMap.onOverlayEvent(PluginMap.java:2442)
        at plugin.google.maps.PluginMap.onPolylineClick(PluginMap.java:2448)
        at plugin.google.maps.PluginMap$33$1.run(PluginMap.java:3156)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Demonstration repository available here: https://github.com/ndrake/ionic-googlemaps-quickdemo-v4/tree/polyline-bug

Steps to reproduce:

* Clone repository
* `npm install`
* Set Google Maps API keys in config.xml
* `ionic cordova platform add android`
* `ionic cordova platform build android`
* Install apk on device
* Open app
* Click on the Polylines on the map

NOTE: It can take several clicks before the crash happens

It seems like the plugin knows a Polyline was clicked, but `PluginMap.isPointOnTheLine()` returns null, which gets passed on to `onOverlayEvent()` which attempts to read lat/lon from the null `LatLng`.  

The other strange thing is that this only seems to happen when there are 3 or more polylines on the map. I'm unable to reproduce it with less than 3 Polylines.

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by makers-mark** [comment]
Try giving it a LatLng instead of a double, maybe?

[LatLng Class](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/LatLng/README.md)

**Comment by tryhardest** [comment]
@ndrake did you get this solved? We have similar issue only with null pointer error after Avatar from Lambda crashes app from bitmap.getCongif(). (Only 1 map marker, a png). Seems similar #2732 cc @makers-mark

**Comment by ndrake** [comment]
@tryhardest Haven't solved it yet

**Comment by 8bhsolutions** [comment]
Seems like the same issue I have fixed.

Might be helpful
https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/2777
