### ISSUE TITLE
Marker.setSnippet(value) does not update infoWindow text, if the window is already open

### ISSUE THREAD

**Issue by 8bhsolutions** [mapsplugin/cordova-plugin-googlemaps#2739]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 4.20.0
@ionic-native/google-maps : 4.21.0
```

**Current behavior:**

1. Create marker with info window snippet
2. Click on marker to open up the infoWindow
3. Click button to update snippet text (Invokes the code that executes setSnippet)

The infoWindow text does not change.
If you tap anywhere on the map to dismiss the window, then click on marker to open window again, the snippet is updated.

**Expected behavior:**

The infoWindow text should be updated when setSnippet is called

**Screen capture or video record:**

```
https://github.com/8bhsolutions/gmap-test
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Yes, you need to reopen it

**Comment by 8bhsolutions** [comment]
@wf9a5m75 
Thanks for the confirmation.
That's basically my current workaround

		if(marker.isInfoWindowShown()) {
			marker.hideInfoWindow();
			marker.showInfoWindow();
		}
