### ISSUE TITLE
Map is loaded but invisible

### ISSUE THREAD

**Issue by Taxi4you** [mapsplugin/cordova-plugin-googlemaps#2740]
I put this in a blank Framework7 + React page (component did mount):

```
    var mapDiv = document.getElementById("map_canvas")

    // Initialize the map plugin
    var map = plugin.google.maps.Map.getMap(mapDiv)

    // The MAP_READY event notifies the native map view is fully ready to use.
    map.one(plugin.google.maps.event.MAP_READY, onMapInit)

    function onMapInit() {
      console.log(`map inited successfully`)
    }
```

And this in the render:

`<div id="map_canvas" style={{width: "300px", height: "300px"}}></div>`

The **map inited successfully** is logged and I see a map load count in the GCP console.

How ever the screen remain blank and no map is rendered above the Framework7 page.
Now obviously you can say that the problem is with Framework7 but this is not the case, since the map is probably rendered behind the Framework7 page and probably issues like this in other frameworks, probably.

So how should it be fixed?

**Comment by wf9a5m75** [comment]
There is something on the map. The map is placed under `<body>` tag
