### ISSUE TITLE
marker icon are not display. 

### ISSUE THREAD

**Issue by monsieurPaon** [mapsplugin/cordova-plugin-googlemaps#2741]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ X ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ X ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.moust.cordova.videoplayer 1.0.1 "Video Player"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-bambuser 0.9.11 "Bambuser Mobile SDK"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-camera-preview 0.11.0 "cordova-plugin-camera-preview"
cordova-plugin-chooser 1.2.5 "Chooser"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-streaming-media 2.2.0 "StreamingMedia"
cordova-plugin-telerik-imagepicker 2.3.3 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 5.0.0 
@ionic-native/google-maps : 5.0.0-beta.27
```

**Current behavior:**
Marker icons not display in the main map or others maps.
I have try all the url variation possible, i have rm the plugin, install the develop version etc etc. 
Actually i load only 6 markers. I have try icon {url : '/path'} , icon : './assets/path' etc etc.

**Related code, data or error log (please format your code or data):**

```
addmarker(param, type) {
        if (type === 0) {
            var icon = 'assets/map_marker/map_marker_1.png';
        } else if (type === 1) {
            var icon = 'assets/map_marker/map_marker_2.png';
        }

        console.log('add mark ' + type);
        this.map.addMarker({
                title: param.name,
                icon: 'www/assets/map_marker/map_marker_1.png',
                animation: 'DROP',
                position: {
                    lat: param.latitude,
                    lng: param.longitude
                }
            }
        ).then(marker => {
            console.log(marker);
            marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
              
            });
        });

    }
```

Thanks for your support.

**Comment by battika** [comment]
What works for me for IOS is the following:
www/assets/mapicons/
where I have my icons in the mapicons directory

**Comment by monsieurPaon** [comment]
@battika i will try this, thank-you.

**Comment by monsieurPaon** [comment]
@battika no change, marker don't display.. Really weird.

**Comment by HansKrywaa** [comment]
try include a `./` to the path --> **./assets/map_marker/map_marker_1.png**

**Comment by monsieurPaon** [comment]
@HansKrywaa same issue, nothing display. On an other map in my app i have this error 

`2020-02-19 13:10:26.247624-0500 KikApp[26930:6422282] 5.7.0 - [Firebase/Performance][I-PRF300002] Invalid URL - ionic://localhost/publication-created/assets/mapicons/map_marker_1.png, returning nil.`

the addMarker for this map is the following (this map display only one marker) 
```
addmarker(param) {
        this.map.addMarker({
                title: param.name,
                icon:
                    {
                        url: './assets/mapicons/map_marker_1.png'
                    },
                // animation: 'DROP',
                position: {
                    lat: param.latitude,
                    lng: param.longitude
                }
            }
        ).then(marker => {
            marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
                // this.currentmeet = param.id;
                // this.presentMeetupModalDetails();
            });
        });
    }
```
But on my main map i haven't this error.

**Comment by monsieurPaon** [comment]
Up, any ideas ?

**Comment by HansKrywaa** [comment]
`ionic://localhost/publication-created/assets/mapicons/map_marker_1.png` this URL looks correct for me - can you verify that under exactly this path the image is available?

**Comment by monsieurPaon** [comment]
Yes it's correct ... But nothing display it's really weird.

**Comment by kuiperr005** [comment]
Having the same issue on iOS only. The markers display for a second after the map has loaded, after which they disappear and the same message displays `Invalid URL - ionic://localhost/.../.../marker.png`. If i move the map the markers show up again.

**Comment by monsieurPaon** [comment]
I haven't any error, i have try addmarkerSync, change icon test everything.. Nothing work. I will reinstall all and see.

**Comment by monsieurPaon** [comment]
After re-installation nothing change. For fun i have put a non existant path and i don't have any errors.

**Comment by monsieurPaon** [comment]
After some rm and reinstallation of the plugin i have now a good result when i launch ionic cordova run browser. If i build my app and launch it on a real device i have this error => 
'''
 [fail] url = ionic://localhost/assets/map_marker/map_marker_1.png 
'''

**Comment by kuiperr005** [comment]
@monsieurPaon I have found that there were some issues with the `ionic://` protocol being not allowed and returned 'invalid' for the first time on iOS. I ended up converting the marker images to base64.

**Comment by monsieurPaon** [comment]
Thank you @kuiperr005. I finally change the process to load marker and use  url: '/www/assets/mapicons/map_marker_1.png' and is looking good for now.. We will see in future with all my different marker icons. I close this issues, i think something is weird but i'm not sure what.
