### ISSUE TITLE
Plugin is not compatible with iOS from April 2020

### ISSUE THREAD

**Issue by chris087** [mapsplugin/cordova-plugin-googlemaps#2746]
This plugin uses the uiwebview, which is not supported by Apple from April 2020.
@see: https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/

The plugin must be updated to use WKWebView.

**Comment by wf9a5m75** [comment]
This plugin also supports WKWebView on ionic.

**Comment by Mathieu-Castets** [comment]
Yep. But action are needed by the end of 2020 for existing apps and by April 2020 for new apps using this plugin.

Every plugin should understand the new config.xml preference tag: `<preference name="WKWebViewOnly" value="true" />` introduced with `cordova-ios@5.0.1`.

**References to UIWebView must be removed from the source.**

See also other plugins such as InAppBrowser which are taking actions: https://github.com/apache/cordova-plugin-inappbrowser/pull/584

**Comment by wf9a5m75** [comment]
Ah, I see. Please send a pull request.

**Comment by HansKrywaa** [comment]
Anyone working on a PR? Otherwise i will, as the Changes seems not to be that hard?

**Comment by Mathieu-Castets** [comment]
> Anyone working on a PR? 

I don't have enough Objective-C background to do so but I could try based on what have been done on InAppBrowser plugin. The main strategy seems to add a condition on every places containing the UiWebView keyword if WkWebViewOnly preference is present.

**Comment by wf9a5m75** [comment]
The PR has been merged on the multiple_maps branch.

**Comment by wf9a5m75** [comment]
The cordova-plugin-googlemaps version 2.7.0 has been released.

**Comment by HansKrywaa** [comment]
@wf9a5m75 Is there a Changelog for 2.7.0? I like installing a stable Version more than a Branch, so is 2.7.0 the old multiple_maps?

**Comment by battika** [comment]
Thanks Masashi.

**Comment by wf9a5m75** [comment]
Sorry for late action.
