### ISSUE TITLE
Can´t add multiple markers.

### ISSUE THREAD

**Issue by Micha851** [mapsplugin/cordova-plugin-googlemaps#2747]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [X] **Browser**

**Current behavior:**

I´m trying to add multiple marker at once, but they doesn´t appear on the map. In the code section i inserted my code where i want to add the marker. The screenshot is from the "console.log(markerArr);".
**Expected behavior:**

**Screen capture or video record:**

![grafik](https://user-images.githubusercontent.com/26982627/76113952-5f586700-5fe5-11ea-85cd-b7e759316984.png)

**Related code, data or error log (please format your code or data):**
`
function successData(data){
        var events = data.val();
        var eventKeys = Object.keys(events);
        var markerArr = [];
        console.log(eventKeys);

        for(var i=0; i<eventKeys.length;i++){
            var key = eventKeys[i];
            var latData = events[key].geoLat;
            var lonData = events[key].geoLon;

            var newMarker = {
                position: {lng: lonData, lat: latData},
                title: "Test Titel"
            }

            markerArr.push(newMarker);
        }
        console.log(markerArr);

        markerArr.map(function(options) {
            return map.addMarker(options);
        });
    }

**Comment by Micha851** [comment]
sry for the half formatted code, i dont know why its happening.

**Comment by Micha851** [comment]
Oh man I misunderstood the function "map.clear". I can add multiple Marker now!
But is there a possibility to close the Info Window of a Marker without clicking on the X?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/Marker/hideInfoWindow/README.md

**Comment by Micha851** [comment]
Thank for the anwser.
For this method you need the marker object by it self. Is there a method to check if any info window is open and than close it?
