### ISSUE TITLE
bug: Nullpointer in MapView?

### ISSUE THREAD

**Issue by HansKrywaa** [mapsplugin/cordova-plugin-googlemaps#2751]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**Current behavior:**

Hey there,

i just saw a new Crash in our App. Stacktrace:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.AbstractCollection.isEmpty()' on a null object reference

com.google.android.gms.dynamic.DeferredLifecycleHelper.zal
com.google.android.gms.dynamic.DeferredLifecycleHelper.onStop
com.google.android.gms.maps.MapView.onStop
plugin.google.maps.PluginMap.onStop PluginMap.java:512
plugin.google.maps.CordovaGoogleMaps.onStop CordovaGoogleMaps.java:503
```

This seems to happen in the MapView? Can this be fixed by this Plugin or where do i have to submit that?

**Comment by HansKrywaa** [comment]
@wf9a5m75 Do you have a Idea why this is happening?

**Comment by wf9a5m75** [comment]
I have no idea. Did you update the plugin?

**Comment by HansKrywaa** [comment]
I was always on the latest multiple_maps. There are some crashes about this, thats why i'm asking.

**Comment by wf9a5m75** [comment]
I have no idea. If you provide the project files that reproduce your issue 100%, I can fix it

**Comment by HansKrywaa** [comment]
I can't 100% reproduce it. But the Error comes from the `DeferredLifecycleHelper` in the `MapView`. I think this MapView Class isn't from your Plugin right? Is is by `com.google.android.gms.maps` - do you now where i can open the Issue?

**Comment by wf9a5m75** [comment]
`com.google.android.gms.dynamic.DeferredLifecycleHelper.zal` is code of Google Maps SDK, not this plugin

**Comment by HansKrywaa** [comment]
Yeah okay, you know where to submit this Issue?

**Comment by wf9a5m75** [comment]
Google's issue tracker

**Comment by moudmagongore** [comment]
Hi are you find solution ?
