### ISSUE TITLE
As soon as I add cordova-plugin-whitelist the googlemaps plugin doenst work anymore

### ISSUE THREAD

**Issue by Micha851** [mapsplugin/cordova-plugin-googlemaps#2755]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**Current behavior:**

Im using the googlemaps plugin and trying to integrade firebase into my app. Maps plugin worked perfectly fine but i had some struggle to get the firebase working. (Btw on the browser preview with phonegap serve everything works fine. It starts after being build and installed on android.) Today I found a post on stackoverflow that I need to had these into the config.
`<gap:plugin name="cordova-plugin-whitelist" source="npm" />
<access origin="*" />
<allow-navigation href="*" />
<allow-intent href="*" />
`
I did it and the firebase connection worked but now maps doents work anymore. Im not getting a grey screen its just white.

**Comment by wf9a5m75** [comment]
On `Android` and `iOS` platforms, this plugin does not use `Google Maps JavaScript v3` at all. Thus, `cordova-plugin-whitelist` is not related at all.

I think you mis configuration `PLAY_SERVICES_VERSION` variable.

**Comment by Micha851** [comment]
Where can I set the PLAY_SERVICES_VERSION variable?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps#install-optional-variables

**Comment by Micha851** [comment]
Ok im gonna check on these, can you answer one more of my question? 
How can I set a "allow all" content security tag and where I have to put these?

**Comment by Micha851** [comment]
I debugged my app with android studio and found out that all my scripts are getting blocked cause of a content security tag
