### ISSUE TITLE
Removing references to UIwebview to comply with Apple policy

### ISSUE THREAD

**Issue by tryhardest** [mapsplugin/cordova-plugin-googlemaps#2756]
https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

As per this blog post, Apple is rejecting any plugin or SDK's with any UIwebview references, which the Branch SDK has. Just want to make aware and see if there a plan to remove references to UIwebview to comply with this Apple policy?

**Comment by battika** [comment]
There is a PR in place it has not been merged yet.
https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/2752

**Comment by wf9a5m75** [comment]
The PR is merged on the multiple_maps branch.
