### ISSUE TITLE
cordova-plugin-googlemaps depends on GoogleMaps@> 2.7.0, which conflicts with another plugin. GoogleMaps@> 3.1.0 is already installed and was not overwritten

### ISSUE THREAD

**Issue by LuoShao** [mapsplugin/cordova-plugin-googlemaps#2757]
**My ionic info
Ionic:**

ionic (Ionic CLI) : 6.1.0 (/usr/local/lib/node_modules/ionic)
Ionic Framework : @ionic/angular 4.1.0
@ionic-native/app-version :  ^5.3.0

**Cordova:**

cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : ios 5.0.0
Cordova Plugins : cordova-plugin-ionic-keyboard 2.0.5, (and 10 other plugins)

**System:** 

ios-deploy : 1.10.0
ios-sim : 9.0.0
NodeJS : v12.16.1 (/usr/local/bin/node)
npm : 6.13.4
OS : macOS Mojave
Xcode : Xcode 11.3.1

**I can see this error when I follow run command**
"ionic cordova platform add ios"

cordova-plugin-googlemaps depends on GoogleMaps@~> 2.7.0, which conflicts with another plugin. GoogleMaps@~> 3.1.0 is already installed and was not overwritten.
Running command: pod install --verbose
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/lsuo071/Documents/angular-product/CDFO_Mobile in PATH, mode 040777

Cloning into 'cocoapods'...

**package.json**
`{ 
  "version": "0.0.1",  
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.12",
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/app-version": "^5.3.0",
    "@ionic-native/barcode-scanner": "^5.21.5",
    "@ionic-native/call-number": "^5.3.0",
    "@ionic-native/camera-preview": "^5.3.0",
    "@ionic-native/core": "^5.23.0",
    "@ionic-native/date-picker": "^5.3.0",
    "@ionic-native/device": "^5.3.0",
    "@ionic-native/diagnostic": "^5.3.0",
    "@ionic-native/dialogs": "^5.3.0",
    "@ionic-native/file": "^5.3.0",
    "@ionic-native/file-opener": "^5.5.0",
    "@ionic-native/file-transfer": "^5.3.0",
    "@ionic-native/geolocation": "^5.3.0",
    "@ionic-native/google-maps": "^5.5.0",
    "@ionic-native/http": "^5.4.0",
    "@ionic-native/in-app-browser": "^5.3.0",
    "@ionic-native/local-notifications": "^5.6.1",
    "@ionic-native/network": "^5.3.0",
    "@ionic-native/screen-orientation": "^5.3.0",
    "@ionic-native/speech-recognition": "^5.4.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.1.0",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "SalesforceMobileSDK-CordovaPlugin": "file:custom_plugins_files/com.salesforce",
    "angular2-signaturepad": "^2.8.0",
    "call-number": "^1.0.1",
    "chart.js": "^2.8.0",
    "com.salesforce": "file:custom_plugins_files/com.salesforce",
    "cordova-android": "8.0.0",
    "cordova-common": "^3.2.1",
    "cordova-ios": "^5.0.0",
    "cordova-plugin-advanced-http": "2.0.7",
    "cordova-plugin-app-version": "0.1.9",
    "cordova-plugin-badge": "0.8.8",
    "cordova-plugin-camera-preview": "file:custom_plugins_files/cordova-plugin-camera-preview",
    "cordova-plugin-compat": "1.2.0",
    "cordova-plugin-datepicker": "file:custom_plugins_files/cordova-plugin-datepicker",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-dialogs": "2.0.1",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-file-opener2": "file:custom_plugins_files/cordova-plugin-file-opener2",
    "cordova-plugin-file-transfer": "1.7.1",
    "cordova-plugin-geolocation": "4.0.1",
    "cordova-plugin-googlemaps": "^2.6.2",
    "cordova-plugin-inappbrowser": "3.0.0",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-local-notification": "file:custom_plugins_files/cordova-plugin-local-notification",
    "cordova-plugin-network-information": "2.0.1",
    "cordova-plugin-screen-orientation": "3.0.1",
    "cordova-plugin-speechrecognition": "1.2.0",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-wkwebview-engine": "1.1.4",
    "cordova-plugin-wkwebview-file-xhr": "2.1.1",
    "cordova.plugins.diagnostic": "file:custom_plugins_files/cordova.plugins.diagnostic",
    "core-js": "^2.5.4",
    "es6-promise-plugin": "^4.2.2",
    "forcejs": "^2.2.1",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "ng2-charts": "^2.2.2",
    "node-sass": "^4.12.0",
    "phonegap-plugin-barcodescanner": "^8.1.0",
    "rxjs": "~6.3.3",
    "snazzy-info-window": "^1.1.1",
    "underscore": "^1.9.1",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.12.3",
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular-devkit/core": "~7.2.3",
    "@angular-devkit/schematics": "~7.2.3",
    "@angular/cli": "~7.3.1",
    "@angular/compiler": "~7.2.2",
    "@angular/compiler-cli": "~7.2.2",
    "@angular/language-service": "~7.2.2",
    "@ionic/angular-toolkit": "~1.4.0",
    "@ionic/v4-migration-tslint": "^1.7.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.14.2",
    "codelyzer": "~4.5.0",
    "ios-deploy": "^1.9.4",
    "ios-sim": "^8.0.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "shelljs": "^0.7.0",
    "ts-node": "~8.0.0",
    "tslint": "~5.12.0",
    "typescript": "~3.1.6"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-screen-orientation": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-geolocation": {},
      "cordova-plugin-wkwebview-engine": {},
      "cordova-plugin-wkwebview-file-xhr": {},
      "com.salesforce": {},
      "cordova-plugin-dialogs": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-speechrecognition": {},
      "cordova-plugin-advanced-http": {},
      "cordova-plugin-file-opener2": {},
      "cordova-plugin-camera-preview": {},
      "cordova.plugins.diagnostic": {
        "ANDROID_SUPPORT_VERSION": "27+"
      },
      "cordova-plugin-local-notification": {},
      "cordova-plugin-badge": {},
      "phonegap-plugin-barcodescanner": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-datepicker": {},
      "cordova-plugin-googlemaps": {
        "PLAY_SERVICES_VERSION": "15.0.1",
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      }
    },
    "platforms": [
      "android"
    ]
  }
}
`
Please help me

**Comment by wf9a5m75** [comment]
Your Cordova is old.

**Comment by wf9a5m75** [comment]
`3.1.0 is already installed and was not overwritten.`

No problem

**Comment by LuoShao** [comment]
@wf9a5m75 
cordova-ios 5.0.1 same error
`Using cordova-fetch for cordova-ios@5.0.1
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: com.pwcsdc.retailapp
        Name: PwCRetailExecution
iOS project created with cordova-ios@5.0.1
Installing "cordova-plugin-googlemaps" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
cordova-plugin-googlemaps depends on GoogleMaps@~> 2.7.0, which conflicts with another plugin. GoogleMaps@~> 3.1.0 is already installed and was not overwritten.
Running command: pod install --verbose
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/lsuo071/Documents/angular-product/CDFO_Mobile in PATH, mode 040777

  Cloning into 'cocoapods'...`

**Comment by wf9a5m75** [comment]
Please search the past logs

**Comment by LuoShao** [comment]
@wf9a5m75 Where can I find it?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=3.1.0+is+already&type=Issues
