### ISSUE TITLE
how to show Custom marker with user image inside the pin. In ionic 4 app. 

### ISSUE THREAD

**Issue by Anjalij80** [mapsplugin/cordova-plugin-googlemaps#2759]
I'm not getting how to show user image just as below image as a marker on native google maps. Please help me sort this issue.

![IMG_0939 (2)](https://user-images.githubusercontent.com/50195665/78243814-128f7f80-7502-11ea-8dd2-7c51f8fdb99b.jpg)

this is my package.json

{
  "name": "abc",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/android-permissions": "^5.22.0",
    "@ionic-native/camera": "^5.22.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/crop": "^5.22.0",
    "@ionic-native/file": "^5.22.0",
    "@ionic-native/file-transfer": "^5.22.0",
    "@ionic-native/geolocation": "^5.22.0",
    "@ionic-native/google-maps": "^5.0.0-beta.27",
    "@ionic-native/location-accuracy": "^5.22.0",
    "@ionic-native/native-geocoder": "^5.22.0",
    "@ionic-native/push": "^5.22.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "@ionic/storage": "^2.2.0",
    "@types/hammerjs": "^2.0.36",
    "cordova-android": "^8.0.0",
    "cordova-browser": "^5.0.4",
    "cordova-plugin-android-permissions": "^1.0.2",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-crop": "^0.4.0",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^4.0.0",
    "cordova-plugin-nativegeocoder": "^3.2.2",
    "cordova-plugin-request-location-accuracy": "^2.3.0",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "2.4.2",
    "cordova-plugin-whitelist": "1.3.3",
    "cordova-support-google-services": "^1.3.2",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "ion-bottom-drawer": "^2.0.0",
    "ionic-selectable": "^4.6.0",
    "moment": "^2.24.0",
    "phonegap-plugin-multidex": "^1.0.0",
    "phonegap-plugin-push": "^2.3.0",
    "rxjs": "~6.5.1",
    "socket.io-client": "^2.3.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-nativegeocoder": {},
      "phonegap-plugin-push": {
        "ANDROID_SUPPORT_V13_VERSION": "27.+",
        "FCM_VERSION": "17.0.+"
      },
      "cordova-plugin-crop": {},
      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-file": {},
      "cordova-plugin-android-permissions": {},
      "cordova-plugin-request-location-accuracy": {
        "PLAY_SERVICES_LOCATION_VERSION": "16.+"
      },
      "cordova-plugin-geolocation": {},
      "cordova-plugin-googlemaps": {}
    },
    "platforms": [
      "browser",
      "android"
    ]
  }
}

**Comment by wf9a5m75** [comment]
How did you write your code?

**Comment by Anjalij80** [comment]
> How did you write your code?

I’m not getting how to achieve this in ionic4

**Comment by wf9a5m75** [comment]
Check this out please.

https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.p

**Comment by Anjalij80** [comment]
> Check this out please.
> 
> https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.p

let filePath: string = './assets/Images/pin.png';
                that.base64.encodeFile(filePath).then((base64File: string) => {
                  console.log("base64File: " + base64File);
                  
                  let icon: string = base64File;
                  let canvas: any = document.createElement('canvas');
                  canvas.width = 120;
                  canvas.height = 40;
                  let context: any = canvas.getContext('2d');

                  let img: any = new Image();
                  img.src = "./assets/Images/user (1).png";
                  img.onload = () => {
                    context.drawImage(img, 0, 0);

                    context.font = '15pt Calibri';
                    context.fillStyle = 'blue';
                    context.fillText('Google', 40, 15);
                    context.fillText('Tokyo!', 60, 35);

                    let markTemp: Marker = that.map.addMarkerSync({
                      'position': { lat: that.allData[key].poly[0].lat, lng: that.allData[key].poly[0].lng },
                      'title': canvas.toDataURL(),
                      'icon': icon
                    })
                    markTemp.showInfoWindow();
                    that.allData[key].mark = markTemp;
                  };
                }, (err) => {
                  console.log(err);
                });

I have tried this but image is not loading only showing default red marker and blue text.

**Comment by Anjalij80** [comment]
> Check this out please.
> 
> https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.p

               let filePath: string = './assets/Images/pin.png';
                that.base64.encodeFile(filePath).then((base64File: string) => {
                  console.log("base64File: " + base64File);
                  let icon: string = base64File;
                  let canvas: any = document.createElement('canvas');
                  canvas.width = 120;
                  canvas.height = 40;
                  let context: any = canvas.getContext('2d');

                  let img: any = new Image();
                  img.src = "./assets/Images/user (1).png";
                  img.onload = () => {
                    context.drawImage(img, 0, 0);

                    context.font = '15pt Calibri';
                    context.fillStyle = 'blue';
                    context.fillText('Google', 40, 15);
                    context.fillText('Tokyo!', 60, 35);
                    let markTemp: Marker = that.map.addMarkerSync({
                      'position': { lat: that.allData[key].poly[0].lat, lng: that.allData[key].poly[0].lng },
                      'title': canvas.toDataURL(),
                      'icon': icon
                    })
                    markTemp.showInfoWindow();
                    that.allData[key].mark = markTemp;
                  };
                }, (err) => {
                  console.log(err);
                });

I tries to show base64 format image on map but no success. only showing default red icon and blue text with blank image.

**Comment by Anjalij80** [comment]
![Screenshot_20200403-143643_OneQlik Personal Tracker](https://user-images.githubusercontent.com/50195665/78343769-f569b800-75b8-11ea-9bde-1fe452d426d3.jpg)

im not getting how to put image inside circle of the marker image.

**Comment by Anjalij80** [comment]
![New Project](https://user-images.githubusercontent.com/50195665/78344266-c6077b00-75b9-11ea-99f6-b6e3d2040a0d.jpg)

till now i can achieve this. But not getting how to insert user image here inside the marker icon circle.

**Comment by wf9a5m75** [comment]
This plugin does not any function that merges image. You need to do that using canvas before passing image to the map.

**Comment by Anjalij80** [comment]
okay, i will try it

**Comment by boris-keep-alive** [comment]
@wf9a5m75 https://stackdev.space/questions/images-in-the-ionic-app-are-failing-to-display-certain-asset-files
