### ISSUE TITLE
[Android] - NullPointerException: Attempt to read from field 'java.lang.Object com.google.maps.api.android.lib6.gmm6.util.g.c'

### ISSUE THREAD

**Issue by 8bhsolutions** [mapsplugin/cordova-plugin-googlemaps#2760]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core :  4.20.0
@ionic-native/google-maps :  4.21.0
```

**Current behavior:**
Sometimes when entering one of my map pages. The app would crash.

`Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.Object com.google.maps.api.android.lib6.gmm6.util.g.c' on a null object reference`

I don't know the steps to reproduce it.

The page does not do anything complex. It interact with the map plugin using the following function
* creates map
* show/hide map
* animate camera (every second, based on location from Geolocation plugin)

**Expected behavior:**
Does not crash

**Screen capture or video record:**
N/A

**Related code, data or error log (please format your code or data):**

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.Object com.google.maps.api.android.lib6.gmm6.util.g.c' on a null object reference
       at com.google.maps.api.android.lib6.gmm6.util.h.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):4)
       at com.google.maps.api.android.lib6.gmm6.util.h.c(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):7)
       at com.google.maps.api.android.lib6.gmm6.vector.bx.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):18)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.q.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):6)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.s.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):81)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ae.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):53)
       at com.google.maps.api.android.lib6.gmm6.vector.bd.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):7)
       at com.google.maps.api.android.lib6.gmm6.vector.bt.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):179)
       at com.google.maps.api.android.lib6.gmm6.vector.av.run(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):60)
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Please try to upgrade to `2.7.0` at least.

**Comment by wf9a5m75** [comment]
And it's hard to detect the problem. Please provide an example project repo that reproduce this issue.

**Comment by 8bhsolutions** [comment]
@wf9a5m75 
No worries Masashi. It is happening in production, and it is compiled with the plugin version 2.6.2.

I'll update to 2.7.0 in dev, and see if I encounter the issue.

However, I can't reproduce at will. 

Because the logcat error do not provide any hints of source of bug, I created this issue to see if there are others who may be experiencing the same issue. If there are others, we maybe able to collect additional information. And hopefully it can help me deduce the cause, and debug the issue.

**Comment by wf9a5m75** [comment]
Yeah, I understand. If this error is occurred many times, please ask to Google.
At least this issue is occurred in Google Maps SDK for Android itself.
(I guess the end user's Google Play Services was old version)

https://stackoverflow.com/questions/34188394/nullpointerexception-from-google-maps

**Comment by 8bhsolutions** [comment]
Thanks mate. I saw that SO question as well. 

I will update this thread if I get any more information

**Comment by 8bhsolutions** [comment]
BTW, what is the recommended play service for this plugin?

I'm currently using 17.0.+ in my package.json setup

**Comment by battika** [comment]
I'm using
`"GOOGLE_MAPS_PLAY_SERVICES_VERSION": "17.0.0"`
also
`"ANDROID_SUPPORT_V4_VERSION": "27.1.1"`
and these settings work for me.

On an aside note, I'm also using the `cordova-android-play-services-gradle-release` plugin as I have many other cordova plugins where `"PLAY-SERVICES-MAPS": "17.0.0"` is set.

**Comment by 8bhsolutions** [comment]
Thanks mate.
I've got similar setup.
Play Service: 17.+
Support V4: 27.+
