### ISSUE TITLE
street view not rendering

### ISSUE THREAD

**Issue by ankitjainOfficial** [mapsplugin/cordova-plugin-googlemaps#2761]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
branch-cordova-sdk 3.1.5 "branch-cordova-sdk"
call-number 0.0.2 "Cordova Call Number Plugin"
com.googlemaps.ios 3.8.0 "Google Maps SDK for iOS"
cordova-clipboard 1.2.1 "Clipboard"
cordova-custom-config 5.0.3 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
**cordova-plugin-googlemaps 2.7.0 "cordova-plugin-googlemaps"**
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.8.4 "OneSignal Push Notifications"
sentry-cordova 0.17.0 "Sentry"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**
Street view does not display

**Expected behavior:**
Street view should display, without any problem

**Screen capture or video record:**
![street-view-error](https://user-images.githubusercontent.com/8897202/78672137-dee79780-78fd-11ea-8bd9-54f15df3716b.png)

**Related code, data or error log (please format your code or data):**

This is my current implementation for showing street view:

```
    this.mapInstance = GoogleMaps.createPanorama(this.elementRef.nativeElement, {
        camera: {
          target: {
            lat: this.map.lat,
            lng: this.map.lng
          },
          zoom: 0
        }
      });
```

The `panoromaReady`, is being fired. But, I'm stuck with only the "something went wrong", error.

There are no errors, and the normal maps view is working fine.

Please let me know, if you need any additional information.

**Comment by wf9a5m75** [comment]
I think your API key problem

**Comment by ankitjainOfficial** [comment]
I thought that to be a problem. But, the normal maps view (satellite and road map, loads fine). Is there some specific API, that I need to enable?

**Comment by wf9a5m75** [comment]
It works.

https://mapsplugin.github.io/ionic-googlemaps-quickdemo-v4/

**Comment by wf9a5m75** [comment]
Please try with `lat: 42.345573, lng: -71.098326`
