### ISSUE TITLE
UiWebView references present in v2.7.0

### ISSUE THREAD

**Issue by dondos** [mapsplugin/cordova-plugin-googlemaps#2762]
Related issue: #2756

Apple still complains about uiwebview references in my app, which was build using version 2.7.0 of this plugin. The only file referencing that was PluginMarker.m:
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/1e27920751a74fb015dc81618e78e369f3d5b1fa/src/ios/GoogleMaps/PluginMarker.m#L1146-L1147
Shouldn't that reference also be removed?

**Comment by wf9a5m75** [comment]
Got it. Thank you for your report.

**Comment by wf9a5m75** [comment]
Please reinstall v2.7.1
