### ISSUE TITLE
Blank page in android and ios 

### ISSUE THREAD

**Issue by CedLP** [mapsplugin/cordova-plugin-googlemaps#2765]
Hello, i try to integrate a google map in my app, in browser platform it's works fine but when i try to run it with cordova run android or ios i have a blank page and Nothing error in chrome console device.
Can you help me please? i send you an email with gitlab repo if you can look my code please :( 
```
import {AfterViewInit, Component, OnInit} from '@angular/core';
import {
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  MarkerOptions,
  Marker,
  Environment, LatLng, GoogleMapOptions
} from '@ionic-native/google-maps/ngx';
import { ActionSheetController, Platform, AlertController } from '@ionic/angular';

@Component({
  selector: 'app-favoris',
  templateUrl: './favoris.component.html',
  styleUrls: ['./favoris.component.scss'],
})
export class FavorisComponent implements OnInit, AfterViewInit {
  map: GoogleMap;
  constructor(
    public alertController: AlertController,
    public actionCtrl: ActionSheetController,
    private platform: Platform
  ) {
  }

  ngOnInit() {
    // await this.platform.ready();
    // await this.loadMap();
  }

  ngAfterViewInit() {
    this.platform.ready().then( () => {
      this.loadMap();
    });
  }


  loadMap() {

    const map = GoogleMaps.create('map');

    map.one( GoogleMapsEvent.MAP_READY ).then( ( data: any ) => {

      const coordinates: LatLng = new LatLng( 45.649864, -73.584213 );
      const position = {
        target: coordinates,
        zoom: 14
      };

      map.animateCamera( position );

      const markerOptions: MarkerOptions = {
        position: coordinates,
        // icon: "https://cdn0.iconfinder.com/data/icons/small-n-flat/24/678111-map-marker-512.png",
        title: 'Hello California',
        draggable: true
      };

      const marker = map.addMarker( markerOptions )
        .then( ( markesr: Marker ) => {
          markesr.showInfoWindow();
        });

    });
  }
}

```
in my typescript file i have this

**Comment by wf9a5m75** [comment]
Please share your project files on github page.
By the way, you **can not** put a map in a dialog.

**Comment by CedLP** [comment]
i was send you an email with my gitlab project , can you look your mail please :) 
you can clone it to in https://gitlab.com/ISD2019/animal3000-mobile

**Comment by wf9a5m75** [comment]
I don't support email private support without fee. Time is money. Sorry about that.

**Comment by wf9a5m75** [comment]
Please attach the screen shot. Also please double check the system logs in logcat.

**Comment by wf9a5m75** [comment]
Regarding of your API key, did you be enabled `Google Maps SDK for Android` and `Google Maps SDK for iOS`?

**Comment by wf9a5m75** [comment]
In order to test, please provide demo account.

**Comment by CedLP** [comment]
![Uploading Capture d’écran 2020-04-22 à 09.46.43.png…]()

**Comment by CedLP** [comment]
<img width="1440" alt="Capture d’écran 2020-04-22 à 09 46 43" src="https://user-images.githubusercontent.com/47782812/79950580-f6875a00-847f-11ea-9e97-938471d1cedd.png">
<img width="1440" alt="Capture d’écran 2020-04-22 à 09 49 19" src="https://user-images.githubusercontent.com/47782812/79950597-fd15d180-847f-11ea-9dab-2b68acaf825f.png">
<img width="1440" alt="Capture d’écran 2020-04-22 à 09 49 40" src="https://user-images.githubusercontent.com/47782812/79950602-fdae6800-847f-11ea-90ab-42373dadf651.png">
<img width="1440" alt="Capture d’écran 2020-04-22 à 09 51 00" src="https://user-images.githubusercontent.com/47782812/79950603-fe46fe80-847f-11ea-8b94-2adcc6ea6152.png">
<img width="1440" alt="Capture d’écran 2020-04-22 à 09 51 08" src="https://user-images.githubusercontent.com/47782812/79950606-fedf9500-847f-11ea-9f84-2bd8082b2a5f.png">
<img width="1440" alt="Capture d’écran 2020-04-22 à 09 51 14" src="https://user-images.githubusercontent.com/47782812/79950609-ff782b80-847f-11ea-9afb-09879e9435bb.png">
<img width="1440" alt="Capture d’écran 2020-04-22 à 09 51 21" src="https://user-images.githubusercontent.com/47782812/79950612-00a95880-8480-11ea-9242-9c1118320982.png">
<img width="1440" alt="Capture d’écran 2020-04-22 à 09 58 04" src="https://user-images.githubusercontent.com/47782812/79950620-030bb280-8480-11ea-8525-b9b770ba88b6.png">

**Comment by CedLP** [comment]
you have the all issus i use to debug that

**Comment by wf9a5m75** [comment]
In the last screenshot, the SDK says "Authorization failure"

**Comment by CedLP** [comment]
and what can i do to authorise this please?

**Comment by wf9a5m75** [comment]
Regenerate API keys for Android and iOS each other

**Comment by CedLP** [comment]
i  was try to regeneraye API keys but i have the same problem, my question is, i need to paid a google map to use that  in android and ios ?

**Comment by CedLP** [comment]
i don't understand why but i create a diffrent project it's work, but in this project that not work.
In the diffrent project i use v5.0.0-beta.20 ionic google maps.
Do you think it's not work because i use a tab of ionic or not ?

**Comment by CedLP** [comment]
Hello, finaly i solve my problem, if someone have a same problem later,
just downgrade a version ionic-google maps and ionic core like this

    "@ionic-native/core": "^5.24.0",
    "@ionic-native/google-maps": "^5.0.0-beta.20",

After that look if your div with who contains google if is have a 500px height or more if it's ok, your map workly fine and you need to paid google map too.
