### ISSUE TITLE
map in black  (Android Oreo 8.0)

### ISSUE THREAD

**Issue by jomego** [mapsplugin/cordova-plugin-googlemaps#2767]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X ] any problem or bug report

**OS:**  (check one with "x")
- [X ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

The map does not appear ... I have been able to observe that the map remains below the Div and is blocked ... in Android 9 ... It works as expected.

**Expected behavior:**

It works like Android 9
**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Please share your project files on github repository, then share it to here. Otherwise, I can not help you.

**Comment by jomego** [comment]
[Image Problem ](https://drive.google.com/file/d/1o48uLSE22NZHpQe0maY9WRQmZdSsMu7i/view?usp=sharing)

**Comment by wf9a5m75** [comment]
Sorry, I can't help you only the screen capture. If you can't help me, I can't help you.

**Comment by jomego** [comment]
The question is that in Android 9 it works perfectly, and the same code in Oreo 8.0 does not show the map ... it is as if the layer stays below ... you have tried it in Oreo 8.

**Comment by wf9a5m75** [comment]
I have no problem. Without your code, I can not help you.
I recommend you create a simple project that only contains a map then try it.
