### ISSUE TITLE
TODO'S for Google Maps Bug?

### ISSUE THREAD

**Issue by HansKrywaa** [mapsplugin/cordova-plugin-googlemaps#2768]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

**Current behavior:**

The last days, Google really fu*ked it up and cause thousands of App Crashes. The IssueTracker is here: https://issuetracker.google.com/issues/154855417

Now they came up with a "[Solution](https://issuetracker.google.com/issues/154855417#comment505)", but i don't know how this will work with this Plugin.

Android:
On Android they said that **The updates to Google Play Services to fix the crash is now available to all devices with Google Play Services version 17.4.55 and newer. End users' devices need to download and apply the updates.** They recommend if we use **Android Maps SDK v3 beta** to roll out a **Code Workaround** which they provided.

-> What about this Plugin? Which SDK is used? Which Play Version? Do we have to change something here?

iOS:
For iOS they seems to don't have a Fix, they just give a Code Workaround (really nice Google 😒). So we should add this Workaround to this Plugin?

What do you think about this whole Topic and my Questions? If you have any Plan, i will give my best to support you with PR's, etc.

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
You can specify the ` Google Play Services version 17.4.55` with `PLAY_SERVICES_VERSION `

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#install-optional-variables-configxml

**Comment by HansKrywaa** [comment]
But this set's the **play-service-maps** Version right? I don't think they mean this, because the latest Version of this seems to be **17.0.0** (See [here](https://mvnrepository.com/artifact/com.google.android.gms/play-services-maps)).

And what about iOS?

**Comment by wf9a5m75** [comment]
`play-service-map` is part of `Google Play Services`

**Comment by wf9a5m75** [comment]
Actually I have no problems on Android and iOS.
If you still have the problems, try to reinstall your apps.

**Comment by HansKrywaa** [comment]
I have no Problems either, but have seen many many Crash Reports. I manually added one Workaround in Android to stop the App crashing, which seems to work, but i want a final solution.

I cannot say 400.000 Users to reinstall their app. 🤔

I don't know if i understand the Google Play Version Thing correctly, but there is no Version `17.4.55` we can use. Is this maybe kind of a internal Version Users need to install on their device?

Still: They recommend the Workaround for iOS

**Comment by wf9a5m75** [comment]
I don't think `400.000` people face this problem.
The problem occurs only the people who launched at the day.
And reinstalling your app is the fastest way to solve the problem instead of waiting next release at this time.

**Comment by wf9a5m75** [comment]
Oh, I found one thing. You can specify `google maps SDK for Android version 3` if you want.

Define `GOOGLE_MAPS_ANDROID_SDK` in `config.xml`.

```xml
<preference name="GOOGLE_MAPS_ANDROID_SDK" value="maps-sdk-3.0.0-beta" />
```

**Comment by HansKrywaa** [comment]
Okay seems to be resolved then. One last Question: What is the default Android SDK that is used if i don't specify `GOOGLE_MAPS_ANDROID_SDK`?

**Comment by wf9a5m75** [comment]
v2
