### ISSUE TITLE
cordova-plugin-googlemaps.LocationService can not get your location 

### ISSUE THREAD

**Issue by Suryalg** [mapsplugin/cordova-plugin-googlemaps#2770]
**Expected behavior:**
The current location should be caught and maps should show

**Screen capture or video record:**
<img width="1280" alt="Screenshot 2020-05-05 at 10 51 13 AM" src="https://user-images.githubusercontent.com/37505509/81036888-6ce37d80-8ebe-11ea-8c23-97ce586521b9.png">
<img width="1280" alt="Screenshot 2020-05-05 at 10 51 25 AM" src="https://user-images.githubusercontent.com/37505509/81036897-74a32200-8ebe-11ea-83b1-346f9a826be1.png">

**Comment by wf9a5m75** [comment]
Because your browser does not allow to get the location

**Comment by wf9a5m75** [comment]
I have no problem on Android, iOS and browser

**Comment by Suryalg** [comment]
I will check on real device and post it here. Thanks for the answer bro!

**Comment by Suryalg** [comment]
I have checked on iPad . It's the same issue that "can not get your location"

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by Suryalg** [comment]
It is solved by using a real device (previously my iPad was buggy it was pending long for an update)
Or in simulator Product->Scheme->Edit Scheme-> set a default location to work

**Comment by Suryalg** [comment]
Now the issue is Map is blank in ios

**Comment by Suryalg** [comment]
![WhatsApp Image 2020-05-08 at 12 19 57 PM](https://user-images.githubusercontent.com/37505509/81379248-5dff0400-9126-11ea-835e-1039a71bd090.jpeg)
Now the issue is Map is blank in ios. I have checked the common transparency issue and thats not issue

**Comment by wf9a5m75** [comment]
Since you don't share your code files, I have no idea.

I can see the marker, Google Logo, so the maps plugin works correctly at least.
Inside the map things, such as map tile, are under the Maps SDK, not this plugin

**Comment by makers-mark** [comment]
Welcome to the googlemaps plugin. There's a lot of help for you! Fortunately the mastermind behind this debugs issues in a very intuitive way. The actual process has been documented and explained to a certain degree of understanding. Please share your project or a simple one where you can demonstrate the problem. Welcome aboard!

**Comment by sepullupes** [comment]
same with me. but i got problem in android, i just use this simple code but turn out blank.
 var option = {
                enableHighAccuracy: true // use GPS as much as possible
            };
            plugin.google.maps.LocationService.getMyLocation(option, function (location) {

                console.log('getMyLocation');
                map = plugin.google.maps.Map.getMap(div, {
                    'camera': {
                        target: location.latLng,
                        zoom: 10
                    }
                });

                var text = ["Current your location:\n",
                    "latitude:" + location.latLng.lat.toFixed(3),
                    "longitude:" + location.latLng.lng.toFixed(3),
                    "speed:" + location.speed,
                    "time:" + location.time,
                    "bearing:" + location.bearing].join("\n");

                console.log(text);
                map.one(plugin.google.maps.event.MAP_READY, onMapInit);
            });

but when i remove this code and only use
 map = plugin.google.maps.Map.getMap(div, {
                    'camera': { 
                        zoom: 10
                    }
                });
the map also gone

map only appear when i just use this code 
map = plugin.google.maps.Map.getMap(div);

**Comment by wf9a5m75** [comment]
I guess you don't wait the `deviceready` event before using this plugin
