### ISSUE TITLE
Andorid Build Gradle fail due to missing " 

### ISSUE THREAD

**Issue by ppetree** [mapsplugin/cordova-plugin-googlemaps#2773]
Plugin version 2.6.0 and 2.7.2
CLI version 9.0.0 (cordova-lib@9.0.1)

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report

**OS:**  (check one with "x")
- [ x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**Current behavior:**
```
FAILURE: Build failed with an exception. * 
Where: Script /platforms/android/cordova-plugin-googlemaps/android-pgm-custom.gradle' line: 66 * 
What went wrong: A problem occurred evaluating script. > 
Please add '' to the config.xml file. * 
Try: Run with --stacktrace option to get the stack trace. 
Run with --info or --debug option to get more log output. 
Run with --scan to get full insights. * Get more help at https://help.gradle.org 
BUILD FAILED in 1s /platforms/android/gradlew: Command failed with exit code 1 
Error output: FAILURE: Build failed with an exception. * 
Where: Script '/platforms/android/cordova-plugin-googlemaps/android-pgm-custom.gradle' line: 66 * 
What went wrong: A problem occurred evaluating script. > 
Please add '' to the config.xml file. * 
Try: Run with --stacktrace option to get the stack trace. 
Run with --info or --debug option to get more log output. 
Run with --scan to get full insights. * 
Get more help at https://help.gradle.org BUILD FAILED in 1s
```
**Expected behavior:**
The app would build

**Comment by wf9a5m75** [comment]
Please share your project files on git repository (Please don't paste your zip file).

**Comment by ppetree** [comment]
Sorry no.  I can't do that.  

This is a compiler/gradle error referencing a very specific line in pgm-custom.gradle
**Line 66:** 
```
throw new GradleException("Please add '<preference name=\"GOOGLE_MAPS_ANDROID_API_KEY\" />' to the config.xml file.")
```

Removing your plugin allows the app to build.

**Comment by wf9a5m75** [comment]
The error means there is no `<preference name="GOOGLE_MAPS_ANDROID_API_KEY" />` in the `AndroidManifest.xml` file.
If you install the maps plugin proper, `<preference name="GOOGLE_MAPS_ANDROID_API_KEY" />` is inserted by cordova automatically.

Since you don't share your code, I can't help this anymore.

**Comment by wf9a5m75** [comment]
Open the file config.xml with your text editor, and write preferences like this.

```xml
<widget ...>
  ...
  <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="(api key)" />
  <preference name="GOOGLE_MAPS_IOS_API_KEY" value="(api key)" />
  ...
</widget>
```

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/hello-world/README.md#step-3-edit-configxml

**Comment by ppetree** [comment]
1) Users of cloud build services like Phonegap don't install plugins that way. Most of us don't have cordova installed on our local machines.
2) <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="xxxxxxxxx" /> does indeed exist in my config.xml
3) the error message isn't about a missing key, the error message is a parse error in your gradle file.

**Comment by wf9a5m75** [comment]
This plugin picks up API keys from `config.xml` on Android/iOS.
This change has been introduced from `v2.6.0`.

The benefit of this change is to omit the `--variable` when you reinstall the maps plugin.
If there is no `config.xml` file, you need to create a `config.xml` file.

**Comment by ppetree** [comment]
Of course there's a config.xml file, if there wasn't this error wouldn't be happening!!!
The variable that you need is in the config.xml file. 

I have tried it three ways:
1)
```
<preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="xxxxx" />
```
2)
```
  <platform name="android">
    <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="xxxxx" />
  </platform>
 ```
3)
```
  <plugin name="cordova-plugin-googlemaps" spec="2.7.1">
  <!-- <variable value="xxxxx" name="API_KEY_FOR_ANDROID" /> -->
    <variable name="GOOGLE_MAPS_ANDROID_API_KEY" value="xxxxx" />
    <variable name="GOOGLE_MAPS_IOS_API_KEY" value="xxxxx" />
  </plugin>
```
4)
````
  <plugin name="cordova-plugin-googlemaps" spec="2.7.1">
    <variable value="xxxxx" name="API_KEY_FOR_ANDROID" /> -->
  </plugin>
```

And of course none of these work because the compiler is barfing because it detects some problem with parsing the gradle script at line 66.  That's the compiler output.  It doesn't say the key is missing, it says insert ' ' in the config.xml because it can't parse ' '

**Comment by wf9a5m75** [comment]
Example
```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.ionic.starter" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>MyApp</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework.com" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <platform name="android">
        ...
    </platform>
    <platform name="ios">
        ...
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^4.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="(YOUR API KEY)" />
    <preference name="GOOGLE_MAPS_IOS_API_KEY" value="(YOUR API KEY)" />
</widget>
```

**Comment by ppetree** [comment]
You're not even listing your own plugin in that example.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps#quick-install

**Comment by wf9a5m75** [comment]
I also provides two `HelloWorld` tutorials

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/hello-world/README.md

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/hello-world-phonegap-build/README.md

**Comment by ppetree** [comment]
I have my config.xml configured the way you want EXACTLY according to your instructions and posts and it will not build with your plugin.  I'll try to use your plugin again when you've gone up a couple of versions but for now, I can't implement this.  Thanks for your time.

**Comment by wf9a5m75** [comment]
If you share your project files on git repository, I can help more.
I didn't specify the git repository must be public. It means private repository is acceptable.

Even if you don't want to share your code, I recommend you try to create a simple project of `HelloWorld` to drill down your problem. If you can't solve the problem with `HelloWorld` project, please come back and share the project files on git repository.
