### ISSUE TITLE
[iOS only] Capacitor support

### ISSUE THREAD

**Issue by splitice** [mapsplugin/cordova-plugin-googlemaps#2775]
**Please tell us your new feature idea**

As of #2762 (v2.7.1) this project seems to be getting closer to Capacitor support. From what I can see (forgive me if I am missing large incompatibilities) there only remains a few issues (to at-least get basic support).

The next one on the chopping block appears to be usage of CDVViewController properties (e.g `pluginsMap`) that are not provided for in Capacitor.

**Why do you need it?**

Capacitor is extremely popular and support is generally wanted by the community at large. Currently marked as incompatible (https://github.com/ionic-team/capacitor/issues/215) could there be a push in this direction?

The alternative for Capacitor users is to use the limited, low performing and relatively expensive Javascript SDK.

See also #2713

**Comment by wf9a5m75** [comment]
In order to support Capacitor iOS, I need to make a big change, but I have no enough time to work for that. And no body does not pay for my work for that. Thus, no plan to support the Capacitor iOS at this time.

**Comment by phal0r** [comment]
@wf9a5m75 
Do you have an estimation of the costs to make it compatible?

**Comment by wf9a5m75** [comment]
If someone donate $3000 USD, I can focus this on one month fully.

**Comment by AE1NS** [comment]
Create a crowdfunding project and lets start collecting.

**Comment by wf9a5m75** [comment]
I made a fundraising of this topic.
If you really want to use this plugin on Capacitor iOS, please support my activity.

[Fundraising : support for Capacitor iOS](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781)
