### ISSUE TITLE
Error Google Play services library dependency

### ISSUE THREAD

**Issue by mtnskb** [mapsplugin/cordova-plugin-googlemaps#2780]
Hello,

I'm trying to install this plugin in a cordova project and I have this error. I solved this error adding googleServices.disableVersionCheck = true to the end of platforms/android/app/build.gradle. But after that, the map doesn't show and aren't any error in js console.

I don't know if because googleServices.disableVersionCheck = true is wrong or other thing (I put the google apikey in config.xml).

following I put the error on plugin installation. 

Any body fix this error?

thanks!

Android Studio project detected
ANDROID_HOME=S:\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_221
Reading build config file: C:\Users\Dev\Desktop\appConductorDev\appConductorDev\build.json
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
config.xml
../config.xml
../../config.xml
../../../config.xml
preference = 4
name = SplashScreen
name = windows-target-version
name = GOOGLE_MAPS_ANDROID_API_KEY
name = Orientation
---->PLAY_SERVICES_VERSION = 16.0.0
---->ANDROID_SUPPORT_V4_VERSION = 27.1.1
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_a1cmm370pw7nwddqzdn8wwfod.run(C:\Users\Dev\Desktop\appConductorDev\appConductorDev\platforms\android\app\build.gradle:153)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:prepareLintJar UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:platformAttrExtractor UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:javaPreCompileDebug UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild
FAILURE: Build failed with an exception.

* What went wrong:
In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[15.0.
1]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: com.google.android.gms:play-services-stats:15.0.1 -> com.google.android.gms:play-services-basement@[
15.0.1], but play-services-basement version was 16.0.1.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
ifact with the issue.
-- Project 'app' depends onto com.google.android.gms:play-services-location@16.0.0
-- Project 'app' depends onto com.google.android.gms:play-services-maps@16.0.0
-- Project 'app' depends onto com.google.firebase:firebase-messaging@17.0.+

For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by wf9a5m75** [comment]
You need to specify `PLAY_SERVICES_VERSION` in config.xml file

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#install-optional-variables-configxml

**Comment by mtnskb** [comment]
Hello, 

I tried to specify PLAY_SERVICES_VERSION from two way

<plugin name="cordova-plugin-googlemaps" spec="~2.7.1" src="https://github.com/mapsplugin/cordova-plugin-googlemaps.git">
        <variable name="PLAY_SERVICES_VERSION" value="15.0.1" />
    </plugin>

and 

<preference name="PLAY_SERVICES_VERSION" value="15.0.1" />

And I have the same error.

thanks!

**Comment by wf9a5m75** [comment]
`16.0.0` or `17.0.0`

**Comment by dallastjames** [comment]
I think there may be a regression here with the latest version. Using 2.7.1, I'm not able to change the value of the PLAY_SERVICES_VERSION preference for this plugin, but I am able to successfully change the value by rolling back to version 2.6.2 and using the values as recommended above.

**Comment by cesaresantiago** [comment]
I can confirm @dallastjames findings. Reverting to 2.6.2 and setting <preference name="PLAY_SERVICES_VERSION" value="17.0.0" /> on config.xml resolves the issue for me.

**Comment by wf9a5m75** [comment]
As of `v2.7.0`, you need to define `<preference name="PLAY_SERVICES_VERSION" value="..." />`.

Before `v2.7.0 (up to v2.6.2)`, you need to define `--variable PLAY_SERVICES_VERSION="..."`

**Comment by dallastjames** [comment]
@wf9a5m75 Thanks for you quick response. I have tried using the preference in the config.xml file but it still does not seem to make use of that value.  Image below is a quick reference:

![image](https://user-images.githubusercontent.com/16655763/82678635-2b193d80-9c07-11ea-8d44-056cc9a502c0.png)

This is the code I'm using for this test (Blank Ionic + Cordova project with only this plugin added beyond the defaults that come with an Ionic project). In this case, no matter where I place the PLAY_SERVICES preference, the plugin does not appear to use the version specified.

https://github.com/dallastjames/cordova-googlemaps-playservices

Appreciate the support. 👍

**Comment by wf9a5m75** [comment]
Thank you for sharing the test project.
I figured out the problem.
Please use `GOOGLE_MAPS_PLAY_SERVICES_VERSION` instead of `PLAY_SERVICES_VERSION`

**Comment by mjamshidy** [comment]
So I am using version `2.7.1`  and to get rid of that error, I've tried `<preference name="GOOGLE_MAPS_PLAY_SERVICES_VERSION" value="16.0.0" />`. But then, when the map loads, it only shows a `blue` page and not that `gray` page for wrong API key.

**Comment by wf9a5m75** [comment]
@mjamshidy Could you show me the screen shot?

**Comment by wf9a5m75** [comment]
Ping

**Comment by mjamshidy** [comment]
My friend used to encounter this. She couldn't reproduce it. We are migrating the project. I'll post here once we have everything in place.

**Comment by wf9a5m75** [comment]
Please try the multiple_maps branch version

**Comment by ppetree** [comment]
This is still an issue.  I'm using the new [voltbuilder](https://volt.build/) cloud build service and this error is persistent with plugin versions 2.7.0 and 2.7.1.

**Comment by wf9a5m75** [comment]
@ppetree could you show me the error log?

**Comment by ppetree** [comment]
I think first let's level set and make sure I have ALL of the config variables set correctly.  
```
  <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="A....." />
  <preference name="GOOGLE_MAPS_IOS_API_KEY" value="A....." />
  <preference name="GOOGLE_PLAY_SERVICES_VERSION" value="16.0.0" />

<plugin name="cordova-plugin-googlemaps" spec="2.7.1">
    <variable name="PLAY_SERVICES_VERSION" value="16.0.0" />
    <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.1.1" />
  </plugin>
```
With 16.0.0...
```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of input files for task ':app:preReleaseBuild' property 'compileManifests' during up-to-date check.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[15.0.
  1]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: com.google.android.gms:play-services-stats:15.0.1 -> com.google.android.gms:play-services-basement@[
  15.0.1], but play-services-basement version was 16.0.1.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the artifact with the issue.
  -- Project 'app' depends onto com.google.android.gms:play-services-tasks@16.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-location@16.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-common@16.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-iid-interop@16.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-base@16.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-maps@16.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-measurement-connector@16.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-basement@16.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-stats@15.0.1
  -- Project 'app' depends onto com.google.firebase:firebase-messaging@17.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-iid@16.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-places-placereport@16.0.0
  
  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dependency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your build.gradle file.
```

With 16.0.0...
```
  <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="A....." />
  <preference name="GOOGLE_MAPS_IOS_API_KEY" value="A....." />
  <preference name="GOOGLE_PLAY_SERVICES_VERSION" value="16.0.0" />

<plugin name="cordova-plugin-googlemaps" spec="2.7.1">
    <variable name="PLAY_SERVICES_VERSION" value="16.0.0" />
    <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.1.1" />
  </plugin>
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of input files for task ':app:preReleaseBuild' property 'compileManifests' during up-to-date check.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[15.0.
  1]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: com.google.android.gms:play-services-stats:15.0.1 -> com.google.android.gms:play-services-basement@[
  15.0.1], but play-services-basement version was 16.0.1.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the artifact with the issue.
  -- Project 'app' depends onto com.google.android.gms:play-services-tasks@16.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-location@16.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-common@16.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-iid-interop@16.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-base@16.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-maps@16.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-measurement-connector@16.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-basement@16.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-stats@15.0.1
  -- Project 'app' depends onto com.google.firebase:firebase-messaging@17.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-iid@16.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-places-placereport@16.0.0
  
  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dependency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your build.gradle file.
```

**Comment by wf9a5m75** [comment]
@ppetree Your problem is not related with the original problem. Your problem is just conflict with other plugins.

**Comment by kristianfjelde** [comment]
Though the issue is closed i resolved this issue by removing `phonegap-plugin-push` and replacing it with `@havesource/cordova-plugin-push` as phonegap has older dependencies.

Also, you must specify a `GOOGLE_MAPS_PLAY_SERVICES_VERSION` value that matches both `com.google.android.gms.play-services-maps` and `com.google.android.gms.play-services-location` versions which can be checked here: https://maven.google.com/web/index.html?q=play-services-maps

In my opinion, it should be possible to specify different play-services versions for the two artifcats.
