### ISSUE TITLE
information about BaseArrayClass

### ISSUE THREAD

**Issue by jomego** [mapsplugin/cordova-plugin-googlemaps#2784]
**I'm submitting a ...**  (check one with "x")
- [ X] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [X ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

There is no information about the BaseArrayClass function in the documentation leading to a page without content.

**Expected behavior:**

How can I know the number of elements my Basearray has and how to retrieve the last value.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseArrayClass/README.md

**Comment by wf9a5m75** [comment]
> How can I know the number of elements my Basearray has and how to retrieve the last value.

You can know `baseArray.getLength()`, and you can get the last value either:
```
baseArray.pop();

or

baseArray.get(baseArray.getLength() - 1);
```

**Comment by jomego** [comment]
in your page:
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/README.md

bindings to base and basearray do not work ...

I don't see any function that returns the length of basearray elements

**Comment by jomego** [comment]
thanks

**Comment by wf9a5m75** [comment]
BaseArray class is designed for `google.maps.MVCArray` of Google Maps JavaScript API v3.

https://developers.google.com/maps/documentation/javascript/reference/event#MVCArray

**Comment by wf9a5m75** [comment]
Slides of `BaseArray` class.
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g291e604610_1_162

**Comment by wf9a5m75** [comment]
And `BaseClass` (for your information)
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g291e604610_1_41

**Comment by wf9a5m75** [comment]
I know some links are missing. Sorry about that.
I have no enough time to fix them.

I really appreciate if you send pull requests.
