### ISSUE TITLE
Creation of Parallel Polyline at a certain distance

### ISSUE THREAD

**Issue by jomego** [mapsplugin/cordova-plugin-googlemaps#2785]
**Please tell us your new feature idea**
It would be interesting to be able to make a parallel line at a distance that we pass and that we can draw another line in reference to a polyline ... it is very interesting because it can be used for many things ... for example for agriculture ... parallel itineraries ..etc..

**Why do you need it?**

I am doing an agricultural GPS project with your library and I need to be able to draw parallel lines to mark where the tractor will go on the next line at a defined distance from the first line.

**How helps other people?**
Very useful to create parallel paths in many activities.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/utilities/geometry/spherical/README.md

**Comment by jomego** [comment]
If I know those functions exist and I have tried by:

spherical.computeOffset ()

but this function does it on the same angle ... there is no possibility to draw a parallel line because the distance is on the same line, it is on the same latitude and the displacement should be on the longitude so that the line is parallel ..

I do not see how to do it and it is very important in my project.

**Comment by wf9a5m75** [comment]
I think `spherical utility` has enough functions to draw parallel lines.
Please do your best.

**Comment by jomego** [comment]
Solution:

//On our master line we calculate the heading:

    var P_A = { lat: longuitud_AA, lng: latitud_AA, };
    var P_B = { lat: longuitud_BB, lng: latitud_BB, };

    var heading_calculado = plugin.google.maps.geometry.spherical.computeHeading(P_A, P_B);

//Calculate Lines Parallel

//Line 1
    posicion1_a = plugin.google.maps.geometry.spherical.computeOffset(punto_origen_A, ancho_trabajo, heading_calculado);
    posicion1_b = plugin.google.maps.geometry.spherical.computeOffset(punto_destino_B, ancho_trabajo, heading_calculado);
    datos_linea_1 = [posicion1_a, posicion1_b];
    linea1.setPoints(datos_linea_1);

//Line 2
 posicion1__a = plugin.google.maps.geometry.spherical.computeOffset(punto_origen_A, -ancho_trabajo, heading_calculado);
    posicion1__b = plugin.google.maps.geometry.spherical.computeOffset(punto_destino_B, -ancho_trabajo, heading_calculado);
    datos_linea__1 = [posicion1__a, posicion1__b];
    linea_1.setPoints(datos_linea__1);
