### ISSUE TITLE
Google Play Store opens automatically to update Play Services

### ISSUE THREAD

**Issue by kolbasa** [mapsplugin/cordova-plugin-googlemaps#2789]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-background-geolocation 3.6.3 "BackgroundGeolocation"
cordova-plugin-background-fetch 6.0.8 "CDVBackgroundFetch"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-google-play-services-version 1.0.0 "Google Play Services Version"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.4-dev "StatusBar"
cordova-plugin-vibration 3.1.0 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.7.2 "Toast"
```

**Current behavior:**
I need to support old devices with old versions of Google Play Services.
The app has its own mechanism to get the user to update this dependency.
With this plugin, however, the user cannot open the app if Google Play Services are outdated.
The Google Play Store will open instead. The user is effectively locked out.
I would be very grateful for a hint on how I can configure the plugin so that you can still use the app without a current version of Google Play Services.

**Expected behavior:**
The app can be opened and used as normal. The Google Play Store does not open automatically.

**Screen capture or video record:**
![PlayServices](https://user-images.githubusercontent.com/3901582/83185275-fcc9bf80-a12a-11ea-99b5-83a274a3023e.gif)

**Comment by wf9a5m75** [comment]
I understood your situation, but Google Maps SDK for Android API is included in the Google Play Services.

**Comment by kolbasa** [comment]
I understand that too. However, I also have older users who have to be guided by the hand. Throwing someone out of the app right away doesn't work. I also have another plugin that also needs Google Play Services and that doesn't have this behavior (cordova-background-geolocation).
If the user does not have the dependency, a map is simply not shown with a tutorial on how to update. I only need one way to deactivate this version check. I don't expect the plugin to work despite the lack of a proper SDK present.

**Comment by wf9a5m75** [comment]
I have no longer old phones. All source code is open. Please diddle the code on the phone

**Comment by kolbasa** [comment]
You can also reproduce this with an Android 10 emulator, just by leaving out Google APIs.

![Android 10 without Google APIs](https://user-images.githubusercontent.com/3901582/83236698-35ea4a00-a194-11ea-9820-ca274522f954.png)

![PlayServices](https://user-images.githubusercontent.com/3901582/83236726-40a4df00-a194-11ea-9a3f-4e4e36c078f9.gif)

**Comment by kolbasa** [comment]
Thanks for the help.

I have now actually found the file that controls this:
```bash
src/android/plugin/google/maps/PluginEnvironment.java
```
line 60-74
```java
    if (checkGooglePlayServices != ConnectionResult.SUCCESS) {
      String errorMsg = GoogleApiAvailability.getInstance().getErrorString(checkGooglePlayServices);
      callbackContext.error(errorMsg);

      try {
        cordova.getActivity().startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("market://details?id=com.google.android.gms")));
      } catch (android.content.ActivityNotFoundException anfe) {
        cordova.getActivity().startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("http://play.google.com/store/apps/details?id=com.google.android.gms")));
      }

      // End the app (in order to prevent lots of crashes)
      cordova.getActivity().finish();

      return;
    }
```
I can work with that. :)

And finally: Thank you for the fantastic plugin. :)
