### ISSUE TITLE
Hello World example is not working on any device

### ISSUE THREAD

**Issue by CrackerakiUA** [mapsplugin/cordova-plugin-googlemaps#2790]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 3.8.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**Current behavior:**

Map never show up, seeing an grey area.

**Expected behavior:**

Map to show up

**Screen capture or video record:**

http://prntscr.com/sq05ih

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```
Followed all steps carefully, replaced step 3 with my keys, no code has changed. Tested on cordova 9.0.0, but also on 8.1.2
**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Gray map means your API key is wrong.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/graymap/README.md
