### ISSUE TITLE
[Question] Webp for markers ?

### ISSUE THREAD

**Issue by razvang10** [mapsplugin/cordova-plugin-googlemaps#2791]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

Does this plugin support webp format for markers (icon)?

**Comment by wf9a5m75** [comment]
Did you try?

**Comment by razvang10** [comment]
not yet. I'm currently working on a backend for a application and i wanted to know before i start working on the actual app :)

**Comment by wf9a5m75** [comment]
`BitmapDescriptorFactory.fromBitmap` supports `webp`, but iOS does not support `webP`

**Comment by razvang10** [comment]
Thank you!
