### ISSUE TITLE
Problem Android - not showed map when i try getMyLocation

### ISSUE THREAD

**Issue by u01ser** [mapsplugin/cordova-plugin-googlemaps#2792]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 3.8.0 "Google Maps SDK for iOS"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : ^5.26.2
@ionic-native/google-maps : ^5.5.0
```

**Current behavior:**

I´m trying to show a map with my location with Ionic.
On Apple, it´s seems ok, but in android the map show blank when i try this:

this.map.getMyLocation().then((location: MyLocation) => {
       //...
}).catch(err => {
        this.showToast(err.error_message);
});

On Android studio the map is blank, and the Toast is not showed. I can see on logcat
D/PluginLocationService: ---->The last location is expired. Let's get the latest location...
D/PluginLocationService: ---->_requestLocationUpdate (isRetry = true)

On Android Device, the app show me the toast with the text "Since this device does not have any location provider, this app can not detect your location."

**Comment by wf9a5m75** [comment]
Please share your project files on Github repository (not zip file or Google Drive etc)

**Comment by wf9a5m75** [comment]
> Since this device does not have any location provider, this app can not detect your location

As the message says your Android device does not have GPS receiver or network is offline

**Comment by u01ser** [comment]
Oh, I´m sorry but when i activated the location on the device, everything has worked. (Thanks wf9a5m75)

But in the emulator, the location is active, the app show me: "Allow APP to access this device´s location?". Next I touch on ALLOW button, but the map dosent works

The console said: "The last location is expired. Let's get the latest location".

I can see that this message is from:
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/PluginLocationService.java#L459

If in the same emulator I open google maps app, this app has worked, but my app continue not working

**Comment by wf9a5m75** [comment]
If you find a problem, please fix the code, then send your code as pull request. That's open source contribution :)

**Comment by wf9a5m75** [comment]
Any updates?

**Comment by u01ser** [comment]
Hi again.

I just upload a clean project in https://github.com/u01ser/test-map00 (obviusly i delete API KEY)

On iOS, everything works. 

On Android, the  maps when i use:
this.map.getMyLocation()

The logcat shows: 

Android Studio said:
2020-06-18 10:12:07.440 19132-19132/io.ionic.starter D/PluginLocationService: ===> onConnected  PluginLocationService1079793405
2020-06-18 10:12:07.440 19132-19132/io.ionic.starter D/PluginLocationService: --->regularAccuracyRequestList.size = 1
2020-06-18 10:12:07.440 19132-19132/io.ionic.starter D/PluginLocationService: ---->_requestLocationUpdate (isRetry = false)
2020-06-18 10:12:07.451 19132-19132/io.ionic.starter D/PluginLocationService: --->highAccuracyRequestList.size = 0
2020-06-18 10:12:07.513 19132-19132/io.ionic.starter D/PluginLocationService: ---->The last location is expired. Let's get the latest location...
2020-06-18 10:12:07.513 19132-19132/io.ionic.starter D/PluginLocationService: ---->_requestLocationUpdate (isRetry = true)

And the map is shown blank.

If i don't use "his.map.getMyLocation()" everything is ok.

**Comment by wf9a5m75** [comment]
Please try to insert `this.platform.ready()` before `initmap()`

**Comment by u01ser** [comment]
> Please try to insert `this.platform.ready()` before `initmap()`

https://github.com/u01ser/test-map00/commit/ac2c97e705eb1b3b2fad66bb2a966eaec92e24a8

Unfortunately, it still not works. Same results

**Comment by wf9a5m75** [comment]
Ok, I'll check it later

**Comment by wf9a5m75** [comment]
Hmm, I have no problem
![ezgif-5-f96f2a8bb483](https://user-images.githubusercontent.com/167831/85048793-ac051f80-b148-11ea-98b8-9413cfaf9eb5.gif)

**Comment by u01ser** [comment]
Ok, i just install a APK in the device and all works fine. Is strange, i think is problem of my emulator, and the plugin its ok.

How do you made the gifs? I think is very util for me in next times.

**Comment by wf9a5m75** [comment]
Record from Android Studio, then save a mp4 file. After that, use online free video to gif service.
