### ISSUE TITLE
[IOS] Bottom navigation bar hide when I rotate device

### ISSUE THREAD

**Issue by dima83909** [mapsplugin/cordova-plugin-googlemaps#2796]
**I'm submitting a ...**  (check one with "x")
- [x ] any problem or bug report

**OS:**  (check one with "x")
- [x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 3.8.0 "Google Maps SDK for iOS"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-sqlite-storage 4.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
pushy-cordova 1.0.37 "PushySDK"
pushy-cordova-receiver 1.0.0 "Pushy SDK Receiver for Cordova"
```

**Current behavior:**

I have this issue after installing cordova-plugin-wkwebview-engine and cordova-plugin-googlemaps. When I rotate my device - navigation bar is falling down

**Screen capture or video record:**

before rotate:
![one](https://user-images.githubusercontent.com/41889553/84712094-73aae900-af70-11ea-9cac-4edeb4f92e9f.png)
after rotate:
![two](https://user-images.githubusercontent.com/41889553/84712095-74dc1600-af70-11ea-94e6-f3765497e78f.png)

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Please share your project files on Github repository. Or prepare an example project that reproduce your issue (only map page is enough), then share the project files on Github repository.
Please do NOT past a zip file here.

**Comment by wf9a5m75** [comment]
This plugin follows the map div size. I think your CSS or JS program has some problems. Otherwise, I should get more similar reports :)

**Comment by dima83909** [comment]
Can I use the latest version of plugin without cordova-plugin-wkwebview-engine? I think that these plugins conflict with each other.
Or maybe there is a version that supports UIWebView?

**Comment by wf9a5m75** [comment]
This plugin does not work without `wkwebview` anymore. Because Apple refuses those applications.

However, if you want to test supporting `UIWebView` version, you can reinstall `cordova-plugin-googlemaps@2.6.2`

**Comment by wf9a5m75** [comment]
Again, this plugin does not change any CSSs except `background` of the map div and parent elements.

**Comment by wf9a5m75** [comment]
Ping
