### ISSUE TITLE
Plugin with dynamic api key option

### ISSUE THREAD

**Issue by aljosalindic** [mapsplugin/cordova-plugin-googlemaps#2797]
Hello,
I'm developing an Ionic 5 app and I'm planning to incorporate this plugin. There are multiple companies that are interested in the app and they would like to distribute the app to their employees, which puts me in a bit of an odd situation. 
Each company wants to use their own google api key (beause of the billing). Is there a way, to dynamically input the API key through js code?  This would allow me to use a single publish of the app for all the clients. Otherwise I'd have to create a publish (with the specific API key) for every company that wants to use the app.

Thank you for your time and effort

**Comment by Mathieu-Castets** [comment]
Hi,

Do you know that using Google Maps native SDK is free on iOS and Android? Therefore, do you really need a different API key for each company?

**Comment by wf9a5m75** [comment]
> Is there a way, to dynamically input the API key through js code?

Unfortunately, no.
