### ISSUE TITLE
Load the map but it doesn't show

### ISSUE THREAD

**Issue by tmwebs** [mapsplugin/cordova-plugin-googlemaps#2799]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report

**OS:**  (check one with "x")
- [x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 3.8.0 "Google Maps SDK for iOS"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.3.0 "PushPlugin"

```

**Current behavior:**

**Expected behavior:**
On Android, load the map, the controls appear but you don't see the map. In the Android Studio emulator it works correctly, but when I upload the bundle, when I install it in a mobile, it doesn't show, I attach a screen of the emulator and another one of the APP installed in a mobile. In iOS it works correctly

**Screen capture or video record:**
![WhatsApp Image 2020-06-22 at 08 08 13](https://user-images.githubusercontent.com/12540076/85254600-fba55d00-b460-11ea-9592-352367c6beac.jpeg)
![Captura de pantalla 2020-06-22 a las 8 18 19](https://user-images.githubusercontent.com/12540076/85254615-0102a780-b461-11ea-8ba4-57833fac23d6.png)

**Comment by wf9a5m75** [comment]
Gray map means your API key is wrong

**Comment by tmwebs** [comment]
but on the emulator it does work

**Comment by tmwebs** [comment]
Thank you, I have reviewed my API key and it is working correctly.
