### ISSUE TITLE
This plugin uses google official api (that need key), or is something "illegal"? 

### ISSUE THREAD

**Issue by makveli** [mapsplugin/cordova-plugin-googlemaps#2801]
I need to know if this plugin support places autocomplete api (for adress search), and if for this service this plugin use the official billed api service...?
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [x] **Browser**

**Comment by makveli** [comment]
Sorry my english does not is so good....
This GeoCoder function is free? not "illegal"?
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.6.0/class/Geocoder/geocoding
And about perfomance, it's have a low latency response time?

**Comment by wf9a5m75** [comment]
This plugin uses `Android native geocoder` and `iOS native geocoder` which are not required API keys, not `Geocode API of the Google Maps`.

If this plugin has some wrong ways, I have been claimed from Google and Apple already, but no claims so far at all.

**Comment by wf9a5m75** [comment]
So, the geocoder is free.

**Comment by wf9a5m75** [comment]
> And about perfomance, it's have a low latency response time?

Please do your tests before asking.

**Comment by wf9a5m75** [comment]
>  if this plugin support places autocomplete api (for adress search)

Not supported yet

**Comment by makveli** [comment]
Another question, that i dont found in doc, what are max results of this plugin GeoCoder? I can pass a location to the function to "turn results more close to me"?

**Comment by makveli** [comment]
Thank you very u much, this is a amazing plugin, congratulations

**Comment by wf9a5m75** [comment]
This plugin involves the native geocoder API based on your request, then return the results from the native geocoder to JS side.
Thus, it's depends on the native geocoder API, not this plugin.
