### ISSUE TITLE
Nearby markers filter

### ISSUE THREAD

**Issue by kennedyngigi4** [mapsplugin/cordova-plugin-googlemaps#2802]
I want to filter the markers that have been displayed on my map ie closest markers as per the filtered category. How can this be achieved with this plugin??

**Comment by wf9a5m75** [comment]
Maybe marker cluster?

**Comment by kennedyngigi4** [comment]
Is it advisable to use cordova-google-maps in two different pages so that one can have the filtering functionality?

Tried that but it fails to show the child map

**Comment by wf9a5m75** [comment]
How did you write your code? Could you share your code files on GitHub?
