### ISSUE TITLE
[Question] How to pan map when dragging a marker to the edge of the visible map

### ISSUE THREAD

**Issue by 8bhsolutions** [mapsplugin/cordova-plugin-googlemaps#2803]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core :  4.20.0
@ionic-native/google-maps :  4.21.0
```

**Question**
When the user tap and hold a marker that is draggable, the marker can then be moved around the map.
When the marker is dragged to the edge of the map, the map does not pan.

How do I make the map pan as the marker is dragged to the the edge of the visible map?

**Comment by wf9a5m75** [comment]
There is no such a function in this plugin. You need to create it

**Comment by 8bhsolutions** [comment]
Thanks for the confirmation.
