### ISSUE TITLE
Marker with text

### ISSUE THREAD

**Issue by mtnskb** [mapsplugin/cordova-plugin-googlemaps#2805]
hello,

I need to put in each marker a label with some text, this text have to be dynamic. I read with this plugin I can't show all infoWindow at the same time. 

In Android native you have a library (Android utility library) and with that you can draw marker with text (Customize markers via bubble icons). 

![Screenshot 2020-07-03 at 15 40 37](https://user-images.githubusercontent.com/46711519/86474643-8fb9d300-bd43-11ea-9a55-d62a26568322.png)

Anyone knows some method to do with this plugin?

thanks!

**Comment by wf9a5m75** [comment]
There is no way to do that in this plugin

**Comment by marcusdiy** [comment]
You can generate the marker via canvas and then maybe pass it as base64 image...
