### ISSUE TITLE
The map is not visible

### ISSUE THREAD

**Issue by WilbertBocanegra** [mapsplugin/cordova-plugin-googlemaps#2807]
I am using the plugin but at the moment of wanting to visualize it it is not seen, I have everything as the documentation but really the map is not visualized, when I build it does not mark me error and allows me to install it perfectly, I use framework7 with svelte

![Screenshot_20200703_164801_io framework7 myapp](https://user-images.githubusercontent.com/40700680/86498796-11622e80-bd4d-11ea-8191-e470ea6ab4ac.jpg)

![Captura de pantalla de 2020-07-03 16-45-54](https://user-images.githubusercontent.com/40700680/86498820-32c31a80-bd4d-11ea-8104-c2a8b2a14799.png)

![Captura de pantalla de 2020-07-03 16-46-10](https://user-images.githubusercontent.com/40700680/86498825-3787ce80-bd4d-11ea-973d-cb0e955b073a.png)

**Comment by wf9a5m75** [comment]
I guess some element(s) covers on map with background color.

The map is not a HTML element, so the map is placed under `<html>` (outside of browser)

**Comment by WilbertBocanegra** [comment]
> Supongo que algunos elementos cubren en el mapa con color de fondo.
> 
> El mapa no es un elemento HTML, por lo que se coloca debajo `<html>`(fuera del navegador)

woow is correct, I have played something with css and the map is displayed perfectly, thank you very much seriously, then it is not an html element, now everything is clear to me

**Comment by wf9a5m75** [comment]
Congratulation!
