### ISSUE TITLE
Is it possibile to use the map without the touch overlay?

### ISSUE THREAD

**Issue by marcusdiy** [mapsplugin/cordova-plugin-googlemaps#2808]
**I'm submitting a ...**
- [x] question
- [ ] any problem or bug report

**OS:**
- [x] **Android**
- [x] **Browser**
- [x] **iOS**

**Questions**
1) Is it possible to use the plugin without the overlay? 
2) Is it possibile to trigger and control the map via js? 
3) Is it possibile to trigger click and drag events via js?

**Current behavior:**
The native layer is placed every time the plugin is used...

**Expected behavior:**
No overlay layer. All the map changes and event will triggered by js.

**Comment by wf9a5m75** [comment]
I can't understand what's your questions.
I recommend you use Google Maps JavaScript v3. It's easy to control by is everything.

**Comment by wf9a5m75** [comment]
I think you have only JS knowledge, but you need to lean more native sides knowledge of Android and iOS, in order to discuss about this plugin.

**Comment by marcusdiy** [comment]
Yes, I'm a web developer. Google Maps Javascript api has limitations. Native is way better.
My question was about the possibility to control the native map layer without the native overlay layer.

**Comment by wf9a5m75** [comment]
Use version 1 of this plugin.
