### ISSUE TITLE
Upgrading from 2.7.0 to latest from multiple_maps causes ~6mb increase in APK size

### ISSUE THREAD

**Issue by CodeWithOz** [mapsplugin/cordova-plugin-googlemaps#2810]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
branch-cordova-sdk 3.2.0 "branch-cordova-sdk"
com.googlemaps.ios 3.5.0 "Google Maps SDK for iOS"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-background-geolocation 3.6.2 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-android-notch 1.0.0 "AndroidNotch"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-background-fetch 6.0.3 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-camera 4.1.0 "Camera"                                                                                                   [0/319]
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-file 6.0.2 "File"                                             
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.5.1 "cordova-plugin-ionic-webview"  
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-media 5.0.3 "Media"                                                                                                            
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-purchase 9.0.0 "Purchase"                                                                                                      
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"                                                               
cordova-plugin-streaming-media 2.2.0 "StreamingMedia"                                                              
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-video-editor 1.1.3 "VideoEditor"
cordova-plugin-whitelist 1.3.4 "Whitelist"        
cordova-plugin-x-socialsharing 5.6.3 "SocialSharing"                                 
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 5.0.1 "Diagnostic" 
es6-promise-plugin 4.2.2 "Promise"               
pushwoosh-cordova-plugin 7.18.7 "Pushwoosh"
```

**Current behavior:**

If I upgrade from v2.7.0 of this plugin to the latest from the `multiple_maps` branch, my APK's size increases by about 6mb. If I upgrade to v2.7.1 from the `master` branch, the bundle size remains roughly the same.

**Expected behavior:**

The bundle size should not increase by as much as 6mb.

**Screen capture or video record:**

I don't yet have a reproduction of the problem in a demo app.

**Comment by wf9a5m75** [comment]
Because Google's SDK is provided as a file instead of API. Please claim to Google

**Comment by wf9a5m75** [comment]
If you set `androidx=false`, this plugin choose Google Play Services API. Then the APK file size should be reduced

**Comment by CodeWithOz** [comment]
@wf9a5m75 thanks for the quick response. Yes I now understand the notice in the changelog. Can that be made clearer? Or at least just include a statement that the change will introduce a big bump in size of the APK.

Also please can you very briefly state the major differences currently between `master` and `multiple_maps`? We are supporting androidx so turning off the flag is not ideal. `master` doesn't appear to have that change yet.

**Comment by wf9a5m75** [comment]
As you may know, I work on the multiple_maps branch (dev branch), then I merge the code to the master when I release a new version.

I've been working on new features, but these are not ready (discovered) yet.
One of big differences is `hiding __pluginDomId` property.

So, if you don't mind `__pluginDomId`, I recommend you use the v2.7.0 at this time.

**Comment by wf9a5m75** [comment]
Or if you found a bug, please report to me.
I will try to fix it on the multiple_maps branch code, then reinstall it from the branch
