### ISSUE TITLE
Map works in browser but crashes app on device (Android).

### ISSUE THREAD

**Issue by liquidcms** [mapsplugin/cordova-plugin-googlemaps#2815]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
$ cordova plugin list
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 3.4.1 "NativeGeocoder"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
    "@ionic-native/core": "^5.27.0",
    "@ionic-native/geolocation": "^5.27.0",
    "@ionic-native/google-maps": "^5.5.0",
```

**Current behavior:**
The map displays correctly in browser. When building for android and running the app, the app runs fine until going to the map page - then it crashes the app. I briefly had Chrome inspect running and there was nothing reported in the console when it crashed (but i can't repeat as my phone no longer works with Chrome inspect).

**Expected behavior:**
Display the simply map with my markers.

**Screen capture or video record:**
<!--
Please take a screen capture or a screen record. You can upload your files with drag & drop up to 10M bytes. If your video file is bigger than 10MB, please upload to your youtube channel, or your Google drive.

[Android]
$> adb shell screenrecord /sdcard/capture.mp4
$> adb pull /sdcard/capture.mp4 ./

Will need to buy a new phone to test this.

**Related code, data or error log (please format your code or data):**

```
repo: https://github.com/liquidcms/sz-app

to go to map: pick TOURS button on start page, then View Tour, then Take Tour (this is map).

```

**Support this plugin activity**

I appreciate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
I checked your code briefly, and the reason of crashing is you mix the code of `Google Maps JavaScript API v3` and this plugin.

You only need to use this plugin APIs.

**Comment by wf9a5m75** [comment]
For example, `new google.maps.LatLng()` and `new LatLng()` are different.

**Comment by liquidcms** [comment]
I know there are remnants of that in an old component; but i don't think being loaded.. but will go through and clean everything out related to old js map.

thanks,

**Comment by liquidcms** [comment]
Deleted the component that was using google maps; although the JS V3 code wasn't being pulled in anywhere. So now the only code related to maps is the code i pulled from your slides. Still crashes app on device.

**Comment by wf9a5m75** [comment]
Ok, I'll check it later.

**Comment by wf9a5m75** [comment]
By the way, thank you for your donation :)

**Comment by wf9a5m75** [comment]
By the way, could you provide me temporally login account to check your app? such as `test / test`

**Comment by liquidcms** [comment]
There is no login on the app. You have access to the github repo. What am i missing?

**Comment by wf9a5m75** [comment]
I haven't tested your app yet.

**Comment by wf9a5m75** [comment]
I just did `ionic cordova run android`, but I can see the map without any problems.

![device-2020-07-24-161847](https://user-images.githubusercontent.com/167831/88442448-68e24000-cdc9-11ea-963e-7fd3c5eaf7c7.png)

**Comment by wf9a5m75** [comment]
Ah, I found the reason.
This plugin does not support `svg`.

```
  placeMarkers() {
    var data = [];
    this.drupal.getViewData(globals.adres, this.tid).then((val) => {
      for (let a of val) {
        data.push({
            title: a['title'],
            icon: {
              'url': '../assets/icon/home-sharp-tiny.svg'  <--- 
            },
            position: {
              lat: a['latitude'],
              lng: a['longitude']
            }
          }
        );
      }
```

**Comment by wf9a5m75** [comment]
Only `gif`, `jpg`, and `png`

**Comment by wf9a5m75** [comment]
Without `icon` property, I can see like this.

![device-2020-07-24-162432](https://user-images.githubusercontent.com/167831/88442660-31c05e80-cdca-11ea-8b2d-2f7ed7bc359d.png)

**Comment by liquidcms** [comment]
Yes, works perfect now. I would have never guessed that was the issue... do you see an error in some device debugger, or just noticed SVG in my code?

Thanks again for your help.

**Comment by wf9a5m75** [comment]
I run it on my phone, and crashed at once. I checked the crash log using Android Studio, then tracked down the code.
