### ISSUE TITLE
Accuracy concerns.

### ISSUE THREAD

**Issue by liquidcms** [mapsplugin/cordova-plugin-googlemaps#2818]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
$ cordova plugin list
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 3.4.1 "NativeGeocoder"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
    "@ionic-native/core": "^5.27.0",
    "@ionic-native/geolocation": "^5.27.0",
    "@ionic-native/google-maps": "^5.5.0",
```

**Current behavior:**
This is partially a question and maybe a bug report. I am curious as to what accuracy could be expected from this plugin? Please see images for test data:

**this native plugin**
<img src="https://user-images.githubusercontent.com/355815/89066049-c717a180-d33a-11ea-9a98-06f78614f37f.png" width="300">

**Google JS API v3**
<img src="https://user-images.githubusercontent.com/355815/89066064-cd0d8280-d33a-11ea-994e-6e558a35ab50.png" width="300">
**Google Maps app**
<img src="https://user-images.githubusercontent.com/355815/89066072-d139a000-d33a-11ea-894b-9419ed297bba.png" width="300">

**Just to show distance marker**
<img src="https://user-images.githubusercontent.com/355815/89066096-d696ea80-d33a-11ea-89e0-5fc26c684efe.png" width="300">

From the following data i can see the following:
- From the 10m info on the last pic it seems like the JS API and this native plugin have an accuracy of around 20m
- Google Maps is within a couple meters - I believe GPS has an accuracy of around 3m, so this makes sense.

Also:
- with the many other tests i have done i have seen much wider spreads between the JS api and this native plugin between both the 2 methods as well as within tests with the same method. With this native plugin i have seen cases where if i read a value and then walk 30m away, it still reads the same value. Doing something like switching wifi off/on causes it to "refresh" and get a proper answer (this is likely a different bug report). Not counting that issue i have also seen a spread of over 20m between measurements when i am not moving locations.

**Expected behavior:**
Would have thought the native plugin would be closer to what the Google Maps app does as I would have thought it is also using the native GPS functions within the phone.

**Code**
let LocationOptions = {enableHighAccuracy: true};

was used for the app using this plugin for the above tests.

**Comment by wf9a5m75** [comment]
Thank you for the report.
But this plugin just return the values from the location api.

Please also try this plugin (not mine)
https://www.npmjs.com/package/cordova-plugin-geolocation

**Comment by liquidcms** [comment]
Yes, obviously not from this plugin.. i'll take a look at: cordova-plugin-geolocation but yes, I admit i am a little confused which plugins are being used when.

in my code on my map page i have 
import { GoogleMaps, GoogleMap, Environment } from "@ionic-native/google-maps/ngx";
import { GoogleMapsEvent, Marker, GoogleMapsAnimation, MyLocation} from '@ionic-native/google-maps';

which i was assuming was your plugin.

so even though i have this installed: cordova-plugin-geolocation 4.0.2 "Geolocation", i am not importing to my maps page.

so, if this is correct so far, what do you mean when you say "this plugin just returns the values from the location api", you mean the native location API?

anyway, i'll check out geolocate and see if there are other options available. I think the test app i used for JS API is using the geolocation plugin, and it isn't any more accurate.. but will check.

thanks.

**Comment by wf9a5m75** [comment]
`@ionic-native/google-maps/ngx` and `@ionic-native/google-maps` are the same.
`@ionic-native/google-maps` is a wrapper plugin of this plugin.
Ionic uses `TypeScript` but this plugin uses `JavaScript`. And `ngx` is used for `ionic 4`, but with/without `ngx` on ionic 5.

-------------

>so, if this is correct so far, what do you mean when you say "this plugin just returns the values from the location api", you mean the native location API?

Yes, this plugin just returns the values from `com.google.android.gms.location.LocationServices` class, which is provided by Android.

-------------

For ionic, `@ionic-native/geolocation` is available.

https://ionicframework.com/docs/native/geolocation
