### ISSUE TITLE
Is possible add a marker without Native INFO WINDOW?

### ISSUE THREAD

**Issue by fafvaz** [mapsplugin/cordova-plugin-googlemaps#2824]
Hello, 

Im trying to add a list of markers, but i want to hide the _INFO Window_ (onclick) i already hide using the **(marker.hideInfoWindow();)** on _MARKER_CLICK_ but the behavior is a little bit strange.

How i can add the marker and set the default value for the _INFO Window_?

Best Regards.

**Comment by wf9a5m75** [comment]
```js
let marker = map.addMarker({
     position : ...,
     myValue : "something"
});

console.log(marker.get("myValue"));
```

**Comment by fafvaz** [comment]
Hi @wf9a5m75, thanks for the fast reply.

My question is how to hide the Ballon on the marker. Like a default value (this marker is to show/hide) and only changed by the methods (marker.showInfoWindow(); and marker.hideInfoWindow();)

![image](https://user-images.githubusercontent.com/8831870/90647335-1feaa380-e230-11ea-93db-910bd8d1e45b.png)

**Comment by wf9a5m75** [comment]
Add `title` property

**Comment by wf9a5m75** [comment]
Please check the document for more information

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/README.md

**Comment by wf9a5m75** [comment]
What do you mean of `without Native INFO WINDOW`?

**Comment by fafvaz** [comment]
The infoballon with the information about the marker.

**Comment by wf9a5m75** [comment]
I asked what are you pointing "without"?

If you write like this,

```
let marker = map.addMarker({
   'title': 'something'
});
marker. showInfoWindow();
```

the `native` info window will be displayed.

-----------

But you asked `without` native infoWindow.

I'm not sure what you want to know.

**Comment by wf9a5m75** [comment]
There are two types InfoWindow in this plugin.

Using `title` and/or `snippet` properties, you can show the `native` info window, which is provided by Google, and you **can not** use HTML tags.

HTMLInfoWindow is provided by this plugin, and you **can** use HTML tags.

**Comment by fafvaz** [comment]
> I asked what are you pointing "without"?
> 
> If you write like this,
> 
> ```
> let marker = map.addMarker({
>    'title': 'something'
> });
> marker. showInfoWindow();
> ```
> 
> the `native` info window will be displayed.
> 
> But you asked `without` native infoWindow.
> 
> I'm not sure what you want to know.

If i dont fill the title and/or snippet, the native info window will not be shown?

**Comment by fafvaz** [comment]
Yes that's it 👍 thank you.

**Comment by karimBenBechir** [comment]
> Yes that's it 👍 thank you.

That's not true my dear, removing title and snippet does not remove the infowindow. 
You have to add  :
   const marker: Marker = this.map.addMarkerSync(point);
   marker.hideInfoWindow();
