### ISSUE TITLE
Support AndroidX

### ISSUE THREAD

**Issue by eviv3k** [mapsplugin/cordova-plugin-googlemaps#2826]
Are you going to update the plugin to support AndroidX?

Thanks

**Comment by wf9a5m75** [comment]
Use the multiple_maps brand version, please

**Comment by eviv3k** [comment]
use the Cordova Android X plugins that enable Android X in the project and patch plugin dependencise and code usage for the Android X equivalent.

Install `cordova-plugin-androidx` to enable Android X and then install `cordova-plugin-androidx-adapter` to patch existing plugins.
