### ISSUE TITLE
Googlemaps Cordova plugin not installing for iOS

### ISSUE THREAD

**Issue by musawershah1598** [mapsplugin/cordova-plugin-googlemaps#2831]
I have used the googlemaps in ionic v4 it works absolutely fine on android, but when I run the
`ionic cordova platform add ios` on my Mac OS, the command hangs at 
`Installing "cordova-plugin-googlemaps" for iOS`
and it goes forever I even waited for about 1 hour but it still stays over there.
If I remove the google maps plugin from my cordova project, it adds the platform.
And one thing more on Activity Manager on MacBook a service is running due to cordova which downloads something I don't know. The service is 
`git -remote-https`
and it has downloaded around 300mbs but when I cancel the plugin addition the service is also terminated.
Below is the ionic info
```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.13.10
   @angular-devkit/schematics    : 7.3.10
   @angular/cli                  : 7.3.10
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 30 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   ios-deploy : 1.11.1
   ios-sim    : 8.0.2
   NodeJS     : v12.18.3 (/usr/local/bin/node)
   npm        : 6.14.8
   OS         : macOS Catalina
   Xcode      : Xcode 11.7 Build version 11E801a


  ────────────────────────────────────────────────────────────
```

**Comment by wf9a5m75** [comment]
https://github.com/ionic-team/ionic-native-google-maps/issues/320

**Comment by wf9a5m75** [comment]
Please ask to Cordova team to improve more speed up.

**Comment by musawershah1598** [comment]
let me check. But thank you for your reply

**Comment by musawershah1598** [comment]
Thank you. The above link solved my problem.
