### ISSUE TITLE
Is there anyway to speed up the install?

### ISSUE THREAD

**Issue by nickmblain** [mapsplugin/cordova-plugin-googlemaps#2837]
I'm just wondering if there is way to improve the speed of the install? When I clear everything out and install again it gets stuck on the following command for about 10 minutes. I've tried on several different networks and computers with the same result.
`Installing "cordova-plugin-googlemaps" for ios`

**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
appd-plugin-eum-mobile 1.0.0 "ADEUMMobilePlugin"
com.googlemaps.ios 3.9.0 "Google Maps SDK for iOS"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 2.5.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-app-launcher 0.4.0 "Launcher"
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-google-analytics 1.9.0 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic 5.4.7 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
@ionic-enterprise/app-version 0.1.12 "@ionic-enterprise/app-version"
@ionic-enterprise/camera 4.1.4 "@ionic-enterprise/camera"
@ionic-enterprise/filesystem 1.1.2 "@ionic-enterprise/filesystem"
@ionic-enterprise/identity-vault 3.6.4 "@ionic-enterprise/identity-vault"
@ionic-enterprise/nativestorage 2.3.4 "@ionic-enterprise/nativestorage"
@ionic-enterprise/network-information 2.0.5 "@ionic-enterprise/network-information"
@ionic-enterprise/offline-storage 2.0.2 "@ionic-enterprise/offline-storage"
@ionic-enterprise/social-sharing 5.6.6 "@ionic-enterprise/social-sharing"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "^5.28.0"
@ionic-native/google-maps : "^5.5.0"
```

Thank you.

**Comment by wf9a5m75** [comment]
There is no way.

**Comment by nickmblain** [comment]
Thanks for the quick response.

**Comment by wf9a5m75** [comment]
Sorry about that

**Comment by mcastets** [comment]
@nickmblain There is a way. I've managed to decrease install time to 60~90 seconds.

Please look at [my answer in a previous post.](https://github.com/ionic-team/ionic-native-google-maps/issues/320#issuecomment-681722127)

It requires to copy and edit a little bit the `cordova-plugin-googlemaps-sdk` repo until @wf9a5m75 could find some time to clean the .git history (500 Mb) on that repo.
