### ISSUE TITLE
Turn by Turn Navigation

### ISSUE THREAD

**Issue by vin2890** [mapsplugin/cordova-plugin-googlemaps#2838]
Does this library support in app turn by turn navigation?

**public support**

If you have a question about this plugin, please ask here.
However this is not a good place for Q&A, please ask only things related with this plugin (such as how to use).

If you want to report your problem, please share your project files on Github in advance.
Without your project files, I can only guess your issue (except your issue is really easy case).
Sharing your project files in advance is the fastest way to resolve your issue.

**private support**

If you don't want to discover anything including code, screen captures or screen records,
please [create an private issue ticket](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/.github/ISSUE_TEMPLATE/private-support.md).
I provide a private space for chatting.

*********************************************************************

--->

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
Creating navigation system is prohibited by the Google Maps API terms
