### ISSUE TITLE
Polyline not displaying

### ISSUE THREAD

**Issue by evansbusobozi** [mapsplugin/cordova-plugin-googlemaps#2840]
**I'm submitting a ...**  (check one with "x")
- [ x ] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [ x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**Current behavior:**
I am implementing the map and it displays successfully with the marker and info window. But when I attempt to add a polyline to the map, it doesn't display anything and I don't seem to understand what the reason is. This is the code that am using below.

```
   directionsService.route({
        origin: new LatLng(this.origin.lat, this.origin.lng),
        destination: new LatLng(this.destination.lat, this.destination.lng),
        travelMode: google.maps.TravelMode['DRIVING']
    }, (res, status) => {

      if(status == google.maps.DirectionsStatus.OK){
          // decode overview_polyline from direction services.
          let decodedPoints = new google.maps.geometry.encoding.decodePath(res.routes[0].overview_polyline);

          let map = GoogleMaps.create("map", {
            camera: {
              target: decodedPoints
            }
          });

          map.addPolylineSync({
              points: decodedPoints,
              color: '#228b22',
              width: 6, 
              geodesic: true
          });

      } else {
          console.warn(status);
      }

    });
`

**Comment by wf9a5m75** [comment]
Could you past the value of `decodedPoints`?

**Comment by evansbusobozi** [comment]
This is what it returns

Array(109)
[0 … 99]
[100 … 108]
length: 109

**Comment by wf9a5m75** [comment]
Sorry, but I can't test without actual values.

**Comment by wf9a5m75** [comment]
`google.maps.geometry.encoding.decodePath` returns `Array<LatLng>`, which is an array of `google.maps.LatLng`, not `plugin.google.maps.LatLng`

`google.maps.LatLng`≠`plugin.google.maps.LatLng`

**Comment by evansbusobozi** [comment]
I do not understand exactly what am supposed to do.

**Comment by evansbusobozi** [comment]
All the contents of that returned array are of type LatLng. This is the array

0: _.I {lat: ƒ, lng: ƒ}
1: _.I {lat: ƒ, lng: ƒ}
2: _.I {lat: ƒ, lng: ƒ}
3: _.I {lat: ƒ, lng: ƒ}
4: _.I {lat: ƒ, lng: ƒ}
5: _.I {lat: ƒ, lng: ƒ}
6: _.I {lat: ƒ, lng: ƒ}
7: _.I {lat: ƒ, lng: ƒ}
8: _.I {lat: ƒ, lng: ƒ}
9: _.I {lat: ƒ, lng: ƒ}
10: _.I {lat: ƒ, lng: ƒ}
11: _.I {lat: ƒ, lng: ƒ}
12: _.I {lat: ƒ, lng: ƒ}
13: _.I {lat: ƒ, lng: ƒ}
14: _.I {lat: ƒ, lng: ƒ}
15: _.I {lat: ƒ, lng: ƒ}
16: _.I {lat: ƒ, lng: ƒ}
17: _.I {lat: ƒ, lng: ƒ}
18: _.I {lat: ƒ, lng: ƒ}
19: _.I {lat: ƒ, lng: ƒ}
20: _.I {lat: ƒ, lng: ƒ}
21: _.I {lat: ƒ, lng: ƒ}
22: _.I {lat: ƒ, lng: ƒ}
23: _.I {lat: ƒ, lng: ƒ}
24: _.I {lat: ƒ, lng: ƒ}
25: _.I {lat: ƒ, lng: ƒ}
26: _.I {lat: ƒ, lng: ƒ}
27: _.I {lat: ƒ, lng: ƒ}
28: _.I {lat: ƒ, lng: ƒ}
29: _.I {lat: ƒ, lng: ƒ}
30: _.I {lat: ƒ, lng: ƒ}
31: _.I {lat: ƒ, lng: ƒ}
32: _.I {lat: ƒ, lng: ƒ}
33: _.I {lat: ƒ, lng: ƒ}
34: _.I {lat: ƒ, lng: ƒ}
35: _.I {lat: ƒ, lng: ƒ}
36: _.I {lat: ƒ, lng: ƒ}
37: _.I {lat: ƒ, lng: ƒ}
38: _.I {lat: ƒ, lng: ƒ}
39: _.I {lat: ƒ, lng: ƒ}
40: _.I {lat: ƒ, lng: ƒ}
41: _.I {lat: ƒ, lng: ƒ}
42: _.I {lat: ƒ, lng: ƒ}
43: _.I {lat: ƒ, lng: ƒ}
44: _.I {lat: ƒ, lng: ƒ}
45: _.I {lat: ƒ, lng: ƒ}
46: _.I {lat: ƒ, lng: ƒ}
47: _.I {lat: ƒ, lng: ƒ}
48: _.I {lat: ƒ, lng: ƒ}
49: _.I {lat: ƒ, lng: ƒ}
50: _.I {lat: ƒ, lng: ƒ}
51: _.I {lat: ƒ, lng: ƒ}
52: _.I {lat: ƒ, lng: ƒ}
53: _.I {lat: ƒ, lng: ƒ}
54: _.I {lat: ƒ, lng: ƒ}
55: _.I {lat: ƒ, lng: ƒ}
56: _.I {lat: ƒ, lng: ƒ}
57: _.I {lat: ƒ, lng: ƒ}
58: _.I {lat: ƒ, lng: ƒ}
59: _.I {lat: ƒ, lng: ƒ}
60: _.I {lat: ƒ, lng: ƒ}
61: _.I {lat: ƒ, lng: ƒ}
62: _.I {lat: ƒ, lng: ƒ}
63: _.I {lat: ƒ, lng: ƒ}
64: _.I {lat: ƒ, lng: ƒ}
65: _.I {lat: ƒ, lng: ƒ}
66: _.I {lat: ƒ, lng: ƒ}
67: _.I {lat: ƒ, lng: ƒ}
68: _.I {lat: ƒ, lng: ƒ}
69: _.I {lat: ƒ, lng: ƒ}
70: _.I {lat: ƒ, lng: ƒ}
71: _.I {lat: ƒ, lng: ƒ}
72: _.I {lat: ƒ, lng: ƒ}
73: _.I {lat: ƒ, lng: ƒ}
74: _.I {lat: ƒ, lng: ƒ}
75: _.I {lat: ƒ, lng: ƒ}
76: _.I {lat: ƒ, lng: ƒ}
77: _.I {lat: ƒ, lng: ƒ}
78: _.I {lat: ƒ, lng: ƒ}
79: _.I {lat: ƒ, lng: ƒ}
80: _.I {lat: ƒ, lng: ƒ}
81: _.I {lat: ƒ, lng: ƒ}
82: _.I {lat: ƒ, lng: ƒ}
83: _.I {lat: ƒ, lng: ƒ}
84: _.I {lat: ƒ, lng: ƒ}
85: _.I {lat: ƒ, lng: ƒ}
86: _.I {lat: ƒ, lng: ƒ}
87: _.I {lat: ƒ, lng: ƒ}
88: _.I {lat: ƒ, lng: ƒ}
89: _.I {lat: ƒ, lng: ƒ}
90: _.I {lat: ƒ, lng: ƒ}
91: _.I {lat: ƒ, lng: ƒ}
92: _.I {lat: ƒ, lng: ƒ}
93: _.I {lat: ƒ, lng: ƒ}
94: _.I {lat: ƒ, lng: ƒ}
95: _.I {lat: ƒ, lng: ƒ}
96: _.I {lat: ƒ, lng: ƒ}
97: _.I {lat: ƒ, lng: ƒ}
98: _.I {lat: ƒ, lng: ƒ}
99: _.I {lat: ƒ, lng: ƒ}

**Comment by wf9a5m75** [comment]
```
const latlng1 = new google.maps.LatLng(135, 10);
console.log( latlng1 instanceof google.maps.LatLng );  // --> true
console.log( latlng1 instanceof LatLng );  // --> false

const latlng2 = new LatLng(135,10);
console.log( latlng2 instanceof google.maps.LatLng); // --> false
console.log( latlng2 instanceof LatLng );  // --> true
```

You must need pass `array of LatLng()` but you pass `array of google.maps.LatLng()`.

More clear?

**Comment by wf9a5m75** [comment]
I don't know you use this plugin in JS code or TypeScript, but to convert `array of LatLng`, you need to use `decodePath` of this plugin.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/utilities/geometry/encoding/decodePath/README.md

**Comment by evansbusobozi** [comment]
With this method as described in the docs,

`
plugin.google.maps.geometry.encoding.decodePath(encodedPath);
`

I don't understand what data type is the plugin variable at the beginning?

**Comment by wf9a5m75** [comment]
What data is included in your code?

```
let decodedPoints = new google.maps.geometry.encoding.decodePath(res.routes[0].overview_polyline);
```

**Comment by evansbusobozi** [comment]
I use the direction service with two points (origin and destination) of type LatLng, which returns data including the encoded polyline route, that's all I can tell.
```
   directionsService.route({
        origin: origin,
        destination: destination,
        travelMode: google.maps.TravelMode['DRIVING']
    }, (res, status) => {
        if(status == google.maps.DirectionsStatus.OK){
           let decodedPoints = new google.maps.geometry.encoding.decodePath(res.routes[0].overview_polyline);
        }
    });

**Comment by wf9a5m75** [comment]
I'm not a beginner. No need to explain your code. I'm waiting you figure out what the problem in your code by yourself.

**Comment by evansbusobozi** [comment]
I already understood what the problem is, I only don't know what the workaround is.

**Comment by wf9a5m75** [comment]
> to convert array of LatLng, you need to use decodePath of **this plugin**.

**Comment by evansbusobozi** [comment]
This is what is happening now.
I changed this line
`let decodedPoints = new google.maps.geometry.encoding.decodePath(res.routes[0].overview_polyline);`
to
`let decodedPoints: ILatLng[] = Encoding.decodePath(res.routes[0].overview_polyline);`

When I log the value of `res.routes[0].overview_polyline` in the console,  it displays the string below

cjbAey|eEnDbHrApCf@pA`@`A~@|Az@z@JFp@FLCRMNMRVrAxA`DjDtC|CjDbEfJ`LxAdBR\Pj@DVDn@Gp@i@~Bg@|BOrAAhAJlAZ~Ab@fAZh@\d@dC`CvBlBt@p@RJXJlBd@\@PCNCZUd@m@pBeDpFmI|FqHzAmBb@e@\Yp@c@|HkFnFuDtD_CpE_D~CuBlI_GbAu@^e@rCuDvEmGlBeC?UFQNMXGNBh@UbAm@zEgDvDqCnBsAdAw@\YRW?UBIJIJCVBLLBJ?JADH\Jb@tA|BtAlBjChD|BdC~DvD`KdJn@v@Zj@jAtBh@v@|@~@fBzAn@l@`@|@FXRtAl@xHPfDd@IbDoApHaEX^|AdB

But I get the error below in the console `Uncaught TypeError: Cannot read property 'decodePath' of undefined`

**Comment by wf9a5m75** [comment]
Did you important "Encoding" class? Also could you share your project files on GitHub?

**Comment by evansbusobozi** [comment]
Yes I imported the Encoding class.

**Comment by wf9a5m75** [comment]
> could you share your project files on GitHub?

Otherwise, there is no way to help more.

**Comment by evansbusobozi** [comment]
I have added some files here https://github.com/Evanzsnr/google-maps

**Comment by wf9a5m75** [comment]
Thank you, but please also include the package.json (and please remove credentials, such as api keys, if it included).

I need to know the plugin versions (which should be included at the first post)

I will check it tomorrow

**Comment by evansbusobozi** [comment]
Okay, thank you

**Comment by wf9a5m75** [comment]
Please try this:

```
$> ionic cordova plugin rm cordova-plugin-googlemaps

$> ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
```

**Comment by evansbusobozi** [comment]
It still returns the same error

**Comment by wf9a5m75** [comment]
Alternative solution, using `let decodedPoints = new google.maps.geometry.encoding.decodePath(res.routes[0].overview_polyline);`, 
then you need to convert from `google.maps.LatLng` to `ILatLng`

**Comment by evansbusobozi** [comment]
Could you be having any idea how I can do that?

**Comment by wf9a5m75** [comment]
**ILatLng**
```
const pos: ILatLng = {
  "lat" : 135,
  "lng" : 38
};
```

**Comment by evansbusobozi** [comment]
Does it make any difference if I attempt to use  the DirectionService for this plugin? Is it available in this version that I just installed?
https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps

**Comment by wf9a5m75** [comment]
DirectionService of this plugin is not completed yet

**Comment by Evanzsnr** [comment]
After searching online, I found this solution https://github.com/ionic-team/ionic-native-google-maps/issues/138#issuecomment-445430033 
I implemented it and the error disappeared. But still the polyline path is not showing. I displayed the decodedPoints array returned after decoding and this is how it looks like. Just some of the points.
```
0: LatLng {lat: 0.34481999999999996, lng: 32.59299}
1: LatLng {lat: 0.34393999999999997, lng: 32.59153}
2: LatLng {lat: 0.34352, lng: 32.590799999999994}
3: LatLng {lat: 0.34331999999999996, lng: 32.59039}
4: LatLng {lat: 0.34314999999999996, lng: 32.590059999999994}
5: LatLng {lat: 0.34282999999999997, lng: 32.589589999999994}
6: LatLng {lat: 0.34252999999999995, lng: 32.58929}
7: LatLng {lat: 0.34247, lng: 32.58925}
8: LatLng {lat: 0.34221999999999997, lng: 32.589209999999994}
9: LatLng {lat: 0.34214999999999995, lng: 32.58923}
10: LatLng {lat: 0.34204999999999997, lng: 32.589299999999994}
11: LatLng {lat: 0.34197, lng: 32.589369999999995}
12: LatLng {lat: 0.34186999999999995, lng: 32.58925}
13: LatLng {lat: 0.34145, lng: 32.5888}
14: LatLng {lat: 0.34063999999999994, lng: 32.587939999999996}
15: LatLng {lat: 0.33988999999999997, lng: 32.587149999999994}
16: LatLng {lat: 0.33903, lng: 32.586169999999996}
17: LatLng {lat: 0.33723, lng: 32.58408}
18: LatLng {lat: 0.33677999999999997, lng: 32.583569999999995}
19: LatLng {lat: 0.33668, lng: 32.58342}
20: LatLng {lat: 0.33658999999999994, lng: 32.5832}
21: LatLng {lat: 0.33655999999999997, lng: 32.583079999999995}
22: LatLng {lat: 0.33653, lng: 32.58284}
23: LatLng {lat: 0.33657, lng: 32.582589999999996}
24: LatLng {lat: 0.33677999999999997, lng: 32.58195}
`

**Comment by evansbusobozi** [comment]
After searching online, I finally found a solution that solved my problem here https://github.com/ionic-team/ionic-native-google-maps/issues/138#issuecomment-445430033
Thanks for your help and time. And thanks for creating the plugin, it's very awesome.

**Comment by evansbusobozi** [comment]
My problem is when I add the polyline to the map, it's displayed successfully, I later remove it using `this.path.remove()` but when I try to add the polyline again, it doesn't display.
I created the map using the code below.
```
    this.map = GoogleMaps.create('map', {
      styles: [
        {
          "featureType": "poi.business",
          "stylers": [
            { "visibility": "off" }
          ]
        },
        {
          "featureType": "transit.station.bus",
          "stylers":  [
            { "visibility": "off" }
          ]
        }
      ],
      camera: {
        target: coordinates,
        zoom: this.zoom
      },
      controls: {
        compass: false,
        myLocationButton: true,
        myLocation: true
      }
    });
`

At some other point I add the polyline to the map with the code below.
```
      this.path = this.map.addPolylineSync({
        points: decodedPoints,
        color: '#3171e0',
        width: 5, 
        geodesic: true,
        clickable: false,
        zIndex: 3
      });
`

I can only add and remove the polyline for the first time when I open the app. When I try to add it again, it fails and I have to restart the app in order for it to work.

**Comment by FretesM** [comment]
Usando api google, tengo error aqui: 
const polylinePoints = google.maps.geometry.encoding.decodePath(data.routes[0].overview_polyline);
error:   Invalid array length
