### ISSUE TITLE
Build error: Cannot find module '@ionic-native/google-maps'

### ISSUE THREAD

**Issue by evansbusobozi** [mapsplugin/cordova-plugin-googlemaps#2859]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-androidx-build 1.0.4 "cordova-androidx-build"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.8.0-20200709-2008 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
I added this plugin to my project successfully, but when I attempt to build the project, I get the error below
```
Error: src/app/home/home.page.ts:2:56 - error TS2307: Cannot find module '@ionic-native/google-maps' or its corresponding type declarations.

2 import { GoogleMaps, GoogleMap, GoogleMapsEvent } from "@ionic-native/google-maps";
```

I have attached a link to the project here https://github.com/Evanzsnr/ionic-google-maps.

**Comment by wf9a5m75** [comment]
To use with ionic, you need to install `@ionic-native/google-maps`
