### ISSUE TITLE
Grey Map but api key is set up how adviced

### ISSUE THREAD

**Issue by BTW18** [mapsplugin/cordova-plugin-googlemaps#2861]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report

**OS:**  (check one with "x")
- [ x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**Current behavior:**

First I have created a google maps api key. I didn´t restrict the key.
Then I created a completely new cordova project and exactly followed the "Hello World" guide. The only thing I did additionally was adding: <preference name="android-minSdkVersion" value="22" /> to my config file because else the project wouldn´t run. When I run the program only a grey map shows with the google logo at the bottom. In the logcat it said it was an authorization failure. I know that the problem has something to do with my api key but I can´t figure out what. The weird thing: if I generate a google maps project with android studio my key works and the map shows. But with cordova and this plugin it doesn´t work.
What I already did:
I enabled "maps sdk for android" and "maps sdk for ios"
I created the key after enabling the api and I have already regenerated my key multiple times
I tried to run it with a restricted key instead of an unrestricted one. I used the right fingerprint but it also didn´t work
I normally try to run the project on an emulator (which has google play activated) but I also tried to run it on a real device with the same result

I searched the web for hours now but I can´t find a solution. I would be very thankful if anybody could help me.

**Expected behavior:**
The plugin should work and show a map

**Screen capture or video record:**
![Screenshot 2021-04-02 115041](https://user-images.githubusercontent.com/76944561/113405693-84670700-93aa-11eb-9293-bc026ef6f546.png)
![Screenshot 2021-04-02 115142](https://user-images.githubusercontent.com/76944561/113405637-6f8a7380-93aa-11eb-907c-3d2dc4cc54bc.png)
![Screenshot 2021-04-02 115207](https://user-images.githubusercontent.com/76944561/113405661-7913db80-93aa-11eb-9710-667f810b0e97.png)
![Screenshot 2021-04-02 115246](https://user-images.githubusercontent.com/76944561/113405719-8af57e80-93aa-11eb-802c-1807d1a350c9.png)
![Screenshot 2021-04-02 115542](https://user-images.githubusercontent.com/76944561/113405728-8e890580-93aa-11eb-950b-85e73b50516e.png)

```
https://github.com/BTW18/test.git
I have never shared a project. Is this the right link?
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by spinninghamster** [comment]
```
<widget ...>
  <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="(api key)" />
  <preference name="GOOGLE_MAPS_IOS_API_KEY" value="(api key)" />
</widget>
```

Don't include the `(` and `)` with the keys.

**Comment by BTW18** [comment]
I can't believe it. I spent hours on this. I tried everything. But I always set the key within the "()". I feel so stupid right now. It works now. Thank you very much. I will give you a beer.

**Comment by spinninghamster** [comment]
> I can't believe it. I spent hours on this. I tried everything. But I always set the key within the "()". I feel so stupid right now. It works now. Thank you very much. I will give you a beer.

No worries. We all do that sometimes :)
