### ISSUE TITLE
Map marker not draggable

### ISSUE THREAD

**Issue by evansbusobozi** [mapsplugin/cordova-plugin-googlemaps#2874]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "^5.33.1"
@ionic-native/google-maps : "^5.5.0"
```

**Current behavior:**
When I add a marker to the map, I am unable to drag the marker. I created a test project to reproduce the issue [here](https://github.com/Evanzsnr/marker) and the problem still persists.

**Expected behavior:**
The marker should be draggable to any point on the map.

**Comment by wf9a5m75** [comment]
Put your finger on the marker 3 seconds

**Comment by evansbusobozi** [comment]
Thank you @wf9a5m75 , I didn't know this trick. Now it's working as expected.
