### ISSUE TITLE
Ethical Hacking: memcpy and strlen functions used on iOS platform marked as vulnerabilities

### ISSUE THREAD

**Issue by diegofdospina** [mapsplugin/cordova-plugin-googlemaps#2881]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
```

**Current behavior:**
N/A

**Expected behavior:**
N/A

**Screen capture or video record:**
N/A

**Related code, data or error log (please format your code or data):**

We got an hybrid app and we decided to use iRoot for avoiding rooted devices to run it, this was a 
requirement by Ethical hacking testers. The customer is pretty interested in checking all kinds of 
vulnerabilities in order to be mitigated. This time a report was made about your plugin because 
it uses some functions which are considered dangerous, those are memcpy and strlen, located in the 
following file:
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/TBXML.m  

We would like to know the purpose of this function's usage and if you implement some control on them.

Thank you very much for your time

**Comment by wf9a5m75** [comment]
`TBXML` is a library that parse XML string. 

https://github.com/codebots-ltd/TBXML

Inside the library itself, I don't touch it.

-------------

This plugin uses the TBXML library for parsing KML files

**Comment by diegofdospina** [comment]
Great!
I'm going to transfer my question to codebots-ltd/TBXML
Thanks @wf9a5m75

Have a great day
