### ISSUE TITLE
New Maps SDK renderer compatibility

### ISSUE THREAD

**Issue by alexp25** [mapsplugin/cordova-plugin-googlemaps#2888]
**I'm submitting a ...**  (check one with "x")
- [ x ] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [ x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

Google has issued a warning that a new renderer will start to roll out next year:

https://developers.google.com/maps/documentation/android-sdk/renderer

Here is some info received by email from Google:

"This Maps SDK update features a new map renderer, which will become the default renderer for Android devices* through a progressive rollout, starting in March 2022 at the earliest.

Update to the new SDK (version 18.0.0) now to test and deploy the new SDK and renderer with your apps before the new renderer becomes the default for Android devices*.

To anticipate and avoid issues with your apps we advise you to:

1. Use the new SDK.
2. Specify the new renderer in your code."

What is to be done? Will the new renderer break everything, or how should we proceed to ensure a smooth transition?
It looks like there are just a few updates required (see link above).

**Comment by alexp25** [comment]
I think a better question would be if it's really required to use the new renderer once it's rolled out. It says "An upgraded map renderer is available as of version 18.0.0 of the Maps SDK for Android". Does this mean that the new renderer only applies when using `com.google.android.gms:play-services-maps:18.0.0`? The plugin uses version 16.0.0 by default, which means it's not affected and should continue to work (please confirm, I am not really sure about that)

**Comment by xinfengmich** [comment]
I have the same question.  Will this plugin have a new release to use com.google.android.gms:play-services-maps:18.0.0 soon?  Or any option to set using com.google.android.gms:play-services-maps:18.0.0?

**Comment by alexp25** [comment]
There is an additional message from Google which enforces the previous concerns regarding the compatibility risk: _Once the new renderer becomes the default, your apps will use the new renderer whether or not they were built against Maps SDK for Android version 18.0.x._
At least the deadline was pushed to _starting in June 2022 at the earliest_, so there is still time to make the required changes.

**Comment by EinfachHans** [comment]
I just forked this Plugin because i guess no more work is done here...

See how easy it is to use the new renderer: https://github.com/EinfachHans/cordova-plugin-googlemaps/commit/71d8d45286a451270518847f95a25e74ee7fa382

**Comment by alexp25** [comment]
@EinfachHans great job! It works like a charm, my app seems to be using the latest renderer with no problems so far

**Comment by xinfengmich** [comment]
@alexp25 Would you please share more details about how to adopt @EinfachHans work? 
I tried to specify "PLAY_SERVICES_VERSION": "18.0.0" while I installed  "cordova-plugin-googlemaps", then manually applied  EinfachHans's change, but can't compile, not able to find the reference to 'com.google.android.gms.maps.MapsInitializer.Renderer' .  I guess I still have the old version of 'com.google.android.gms:play-services-maps' installed, but couldn't find it in my project.  Thanks for your help.

**Comment by uhmarc** [comment]
@EinfachHans Is your fork working with Android 10? Specifically this issue here:
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2892

**Comment by EinfachHans** [comment]
@uhmarc i target sdk 30 so yes

**Comment by uhmarc** [comment]
> @uhmarc i target sdk 30 so yes

Thanks, will be using it! :)
