### ISSUE TITLE
🆘  [ANDROID] Plugin doesn't work with android 10+

### ISSUE THREAD

**Issue by kaddyadriano** [mapsplugin/cordova-plugin-googlemaps#2892]
Map does not show and $maps.event.MAP_READY never fires. Please help!
Google Play now requires Target API level 30 so downgrading android version is not an option.
https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by akhilsivdn** [comment]
Same. I just updated to android 10, and all of a sudden maps showing up as blank screen!

**Comment by kaddyadriano** [comment]
I have fixed by forking and merging a couple of pending PRs together and added a minor change to the custom icons. #2871 and #2880. Both PRs are merged into master branch of my fork https://github.com/kaddyadriano/cordova-plugin-googlemaps and also to my `PR-Android10-Blank-Screen-Fix-and-Custom-Icons-Fix` branch. 
I have used the following to install the plugin for now until the PRs are merged.

`cordova plugin add https://github.com/kaddyadriano/cordova-plugin-googlemaps`

**Comment by uhmarc** [comment]
Do you know if this is fixed in multiple_maps branch? I don't have any Android 10 to test and this worries me.

**Comment by uhmarc** [comment]
Very strange. I tested this in the Emulator and it works with Android 10. Is this only a physical device problem?

**Comment by mrnebbi** [comment]
I'm also having this problem and have tried a huge number of fixes with no luck. The closest I can get to it working is the multiple_maps branch too, but then I'm left with a black empty screen on Android.

**Comment by gautamsinh** [comment]
any update on this?
