### ISSUE TITLE
Geocode multiple addresses and add Markers

### ISSUE THREAD

**Issue by adilscout** [mapsplugin/cordova-plugin-googlemaps#310]
Hi all :)

Thanks a lot for this great plugin , 

the code below can add geocode just for one adresse , what should i do if i want to geocode multiple adresses and add there markers in same time ?  :  

``` js
var request = {
  'address': "casablanca"
};
plugin.google.maps.Geocoder.geocode(request, function(results) {
  if (results.length) {
    var result = results[0];
    var position = result.position;    
    map.addMarker({
         'position':new plugin.google.maps.LatLng(33.544746,-7.638,17),
         'title':"Technopark",
         'snippet': "This plugin is awesome!"
       }, function(marker) {
             marker.showInfoWindow();
     });
    map.addMarker({
      'position': position,
      'title':  JSON.stringify(result.position)
    }, function(marker) {
      map.animateCamera({
        'target': position,
        'zoom': 17
      }, function() {
        marker.showInfoWindow();
      });
    });
  } else {
    alert("Not found");
  }
});
```

**Comment by ma-pe** [comment]
Well, I tried exactly what you said, @wf9a5m75. It seems, that only the last callback of the geocode function is called, when executing geocode multiple times (as in an forEach-method).

Example:
_.each(addresses, function(address, index){
   // call geocode here by address
});


When I instead increase waiting-time for each geocode-call - all callbacks are called.

Example:
var i = 0;
_.each(addresses, function(address, index){
   i++;
   setTimeout(function(){
      // call geocode here by address
   }, i*1000);
});

Of course, this is no solution. I could also wait for the success-callback to geocode the next address. But this would make the asynchronous calls a little more synchronous again - what can't be the intention ;-)

Any thoughts on this issue? Issue should be opened again. Thanks.

**Comment by Hirbod** [comment]
Tricky problem. I guess a js-closure could fix this problem. As @wf9a5m75 , this plugin should not be used to batch-geocode. You really should consider doing this with php or any other server-side language. I use https://github.com/geocoder-php/Geocoder
