### ISSUE TITLE
Small bug in Cordova 3.7.0

### ISSUE THREAD

**Issue by hirbod** [mapsplugin/cordova-plugin-googlemaps#312]
Hi Masashi,

just updated to Cordova 3.7.0 (careful people, some ugly bugs with console.log() and memory leaks, stay at 3.6.3 till they patch)

But there is a small problem. On init I receive more then 60 console.log messags with "NULL" and triggered red (as error)

They are invoked here:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/www/googlemaps-cdv-plugin.js#L114

The message is also NULL.

![bildschirmfoto 2014-11-20 um 01 05 28](https://cloud.githubusercontent.com/assets/504909/5117154/636b9c7e-7051-11e4-8409-2560bc3644d9.png)

**Comment by Hirbod** [comment]
so #352 was the problem and this is now fixed correctly. Maybe the patch is unessacary now?
