### ISSUE TITLE
I couldn't use device GPS to determine my location

### ISSUE THREAD

**Issue by efkan** [mapsplugin/cordova-plugin-googlemaps#325]
Hello,

I've added a screenshot the below regarding my issue. 
When my location mode is "High accuracy", my plugin works properly. However if my location mode is Device only my plugin cannot determine my location.

I've set enableHighAccuracy on my codes;

```
       map.getMyLocation(
            {
                enableHighAccuracy: true
             }, 
             success, 
             error
        );
```

I've tried to get my location using another app - that uses a native maps - it can determine my location.

What should I do?
Or can I determine my location using only device's GPS sensor (this is "Device only" mode) ?

Cordova Version: 4.0.0
Android Version: 4.4.4
Phone Model: Xperia Z

Ps: This is a useful Cordova 3rd part plugin I have ever seen! I can use almost all Google Map native (Java) function on Cordova!

![screenshot_2014-12-04-21-00-53](https://cloud.githubusercontent.com/assets/6974198/5304190/0177afb8-7bf9-11e4-893e-08b03cfd847d.png)

**Comment by oorodong** [comment]
@efkan @wf9a5m75 

hallo, sorry to bother :)

i encounter this problem too, how i fix this??

thx

**Comment by efkan** [comment]
I really don't remember. 

But most likely it was because of misunderstanding of the docs.

Good luck..
