### ISSUE TITLE
Can i draw Polylines specifically on roads, i.e. emulate directions?

### ISSUE THREAD

**Issue by mladenp** [mapsplugin/cordova-plugin-googlemaps#339]
I know i can't get road data from any Google Maps API because that's not shared with public. And i know there isn't anything in this plugin docs about roads/navigation, except for external navigation method.
But i would like to know is there any way to draw Polylines specifically on roads. I would like to "emulate" directions, add two points on map and draw polyline between them that goes by roads.

I would like to know if there is a way to do it in native java maps API, too. 

Thanks

**Comment by vinayak-kaviskar** [comment]
You may use snap to roads api of google, but then you should have lat lngs which are quite close enough
