### ISSUE TITLE
Can I set the position of "myLocationButton" in map.setOptions

### ISSUE THREAD

**Issue by avidityventures** [mapsplugin/cordova-plugin-googlemaps#379]
I would like to position the button of "myLocationButton" to the top right of the screen.  Is there any chance for me to do it ?
# ios

Thanks

**Comment by wf9a5m75** [comment]
The my location button comes from Google Maps SDK for iOS, and the sdk does not provide the way to change the button position.
Thus there is no way.

**Comment by rwh23** [comment]
http://stackoverflow.com/questions/16879694/google-maps-ios-sdk-move-my-location-button-to-bottom-left-hand-corner?answertab=active#tab-top

Please check above stackoverflow answer. I tested already. 
Looks good.

**Comment by wf9a5m75** [comment]
Thanks.
