### ISSUE TITLE
Marker or image always on center

### ISSUE THREAD

**Issue by aosmorac** [mapsplugin/cordova-plugin-googlemaps#41]
Hi, i need to put a image over the map in order to keep it always in the center at the map. Also i need to set a button over the map. How can i do that?

**Comment by gchokeen** [comment]
Is this documented, I am using plugin v1.2.5, but I unable to find how to implement this?

**Comment by rayanwipes** [comment]
Hey ! 
Is there a new way as of now to keep a marker fixed to the center of the map ? 
Thank you,

**Comment by wf9a5m75** [comment]
Using the plugin v2, you should be able to do with this:

```js
map.on(plugin.google.maps.event.CAMERA_MOVE, function(cameraPosition) {
  marker.setPosition(cameraPosition.target);
});
```

**Comment by rayanwipes** [comment]
Hey Masashi, 
Thank you for your answer. This is how I do it now; however, there's a slight delay between the map moving and the marker staying in the center. This is what I'm looking to correct...

**Comment by wf9a5m75** [comment]
Or put an image in the map div.

```html
<div id="map" style="position: relative">
    <img src="marker.img" style="position: absolute; left:50%;top:50%;" />
</div>
```

**Comment by rayanwipes** [comment]
Hello Masahi, 

I have used your fix and it has been working perfectly. However, multiple users have alerted me about a problem. When elements are overlayed on top of the map, dragging those elements causes the map to scroll. 

The detail of the bug can be found here : 
[https://forum.ionicframework.com/t/elements-on-top-of-google-map-scroll-bug/114692](url)

Would anyone know if there's a way to prevent that from happening ? 

Thank you very much.

**Comment by wf9a5m75** [comment]
How about this?

```
<div id="map" style="position: relative">
    <img id="centerMarker" src="marker.img" style="position: absolute; left:50%;top:50%;" />
</div>
```

```
var centerMarker = document.getElementById("centerMarker");
centerMarker.addEventListener("touchstart", function(e) {
  e.preventDefault();
});
```

**Comment by Muralilive** [comment]
<div id="map" style="position: relative">
    <img id="centerMarker" src="marker.img" style="position: absolute; left:50%;top:50%;" />
</div>

I need only draggable map without marker and center position
