### ISSUE TITLE
Possibility to pass custom variables to a marker

### ISSUE THREAD

**Issue by em-ka** [mapsplugin/cordova-plugin-googlemaps#54]
Hi,
I would appreciate a possibility to set custom variables to a marker. e.g. when you want to show additional information after user clicks on an info window (you need to pass some kind of an ID, to be able to show them).

**Comment by Jerome2606** [comment]
@em-ka Could you submit a pull request for this because I need it too but I don't know how to reproduce your change ?

Thanks
