### ISSUE TITLE
Setting marker icon 'anchor'

### ISSUE THREAD

**Issue by stevesims** [mapsplugin/cordova-plugin-googlemaps#55]
With the Google Maps JS API, one can set the anchor point of a marker icon to be something other than the bottom centre of the icon image.  You'd do this by doing something like:

``` javascript
        this.homePin = new google.maps.Marker({
          position: latLng,
          map: this.map,
          icon: {
            url: "images/pin-only.png",
            anchor: new google.maps.Point(8, 8),
          }
        });
```

(My pin-only.png is 16x16, so the anchor on the icon is the middle of the icon.)

This doesn't seem to be supported by the plugin.

In my app I'm drawing a circle with the radius of the accuracy of the home location at latLng, and then placing the homePin on top of that.  As I can't adjust the anchor point of the marker icon, the marker sits above the centre point of the circle, which looks slightly odd.

**Comment by neXorianus** [comment]
yes, I know... this is a really old issue, but any chance, that this property didn't make it into the documentation?
I can only find the `infoWindowAnchor` property in the [Marker Docs](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md)
