### ISSUE TITLE
MAP_CLICK not working on Android device

### ISSUE THREAD

**Issue by mosinconsrv** [mapsplugin/cordova-plugin-googlemaps#575]
Hi,

I'am trying to use this code.But console.log dosen't print any message when I click on map.

map.on(plugin.google.maps.event.MAP_CLICK , function(latLng) {
                    console.log('Map is clicked.\n' + latLng.toUrlValue());
                });

**Comment by svr93** [comment]
I have some problem too. Clicks work fine on iOS emulator but there are no anything after my click on Android device

**Comment by Hirbod** [comment]
@wolf-s could you dig into this? I really need someone whon contributes to android and it seems that you have good know how

**Comment by wolf-s** [comment]
Actually I don't, but I'll try to sort it out

**Comment by Slavrix** [comment]
On android 4.4 im using this angularjs code and it works fine.

      map.on($window.plugin.google.maps.event.MAP_CLICK, function (e) {
        $log.debug('click');
        $log.debug(e);
        $log.debug(e.lat);
        $log.debug(e.lng);
      });

**Comment by Hirbod** [comment]
Also tested today, can't reproduce any error. I'm sorry. Make sure nothing is blocking the map

**Comment by kshaaban-** [comment]
I just ran into this issue, and after some debugging I found the root cause behind it.

This occurs when you have hidden (`visible: false`) circles/polygons/polylines on the map and you tap/click where they would show had they been visible.

**Comment by wf9a5m75** [comment]
Ah, I see.

The current version does not consider the visibility of the circle (overlays).
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L1444-L1459

**Comment by wf9a5m75** [comment]
The v2-beta version considers the visibility of each overlays.
Please use it.
https://github.com/mapsplugin/v2.0-demo/
