### ISSUE TITLE
Marker drag flaw

### ISSUE THREAD

**Issue by acidmk** [mapsplugin/cordova-plugin-googlemaps#577]
![asdf](https://cloud.githubusercontent.com/assets/12675793/8937793/9a29b764-357c-11e5-828f-6981076eb0ea.gif)

I have map embedded in frame and top part of it seems to be as wide as distance from marker to mouse after drag start. Possible reason behind of it dragged in that move event is getting absolute screen coordinates. As for plugin tail ends after draggable flag is passed to android gms.

**Comment by Hirbod** [comment]
Sorry, I don't have the time to fix this currently. Will close for now

**Comment by samuelgoldenbaum** [comment]
@Hirbod, why is this being closed?

**Comment by masashiGMS** [comment]
This is not a bug of this plugin. It comes from the Android Maps API v2. So it's a spec.

Check out here:
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L1319-L1322

This plugin just passes the event to the JS, not modified at all.
