### ISSUE TITLE
Reintroduction of issue #5?

### ISSUE THREAD

**Issue by NoddyM** [mapsplugin/cordova-plugin-googlemaps#624]
Following the update of my application from Cordova 4.3.1 to 5.3.1 and Cordova Android 3.7.2 to 4.1.1, issue #5 appears to have been reintroduced between plugin.google.maps 1.2.5 and plugin.google.maps 1.3.0.

The issue is occurring when the Android back button is used after calling .showDialog().
Expected result: The dialog is closed.
Actual result: The application closes.

**Comment by RegexLLC** [comment]
Your best option is to bind to the close dialog event and also the back button event to force the back button to close the dialog if its open.

**Comment by xoxbet** [comment]
Hi, I would like to ask you how did you fix this issue? I use Cordova 6.0.0, android platform 5.1.0 and plugin version 1.3.9 (stable).
After calling showDialog() and clicking back button app closes without firing plugin.google.maps.event.MAP_CLOSE or cordova's _backbutton_ event. Without calling showDialog() I catch _backbutton_ event successfully.

**Comment by Hirbod** [comment]
@atannus could you dig into this? Can't fix this due to knowledge

**Comment by wf9a5m75** [comment]
Fixed.
