### ISSUE TITLE
geocoding with bounds

### ISSUE THREAD

**Issue by Slavrix** [mapsplugin/cordova-plugin-googlemaps#625]
Looking through the plugin code, it should support geocoding with a bounds set to the request along with the address.
I created a bounds using the plugins built in plugin.google.maps.LatLng and plugin.google.maps.LatLngBounds

when passing the bounds object in the geocodeing request

Geocode.geocode({
      'address': query,
      'bounds': theBounds
    }

I get an empty string returned.

something I noticed, is that when the latLngBounds is created
it creates an JSON 
'bounds':{
  'northeast':{
    'lat':<value>,
    'lng':<value>
  },
  'southwest':{
    'lat':<value>,
    'lng':<value>
  }
}

but the code in mygeocoder.java and mygeocoder.m are looking for  bounds.northeast.latitude, bounds.northeast.longitude, bounds.southwest.latitude, bounds.southwest.longitude,

so i assume, since it cant find anything within a bounds on undefined, its returning nothing.
or something like this.

am i looking at it wrong or doing something wrong with it ?

**Comment by Hirbod** [comment]
Did you try to change the source, maybe you were on the right path. I don't have time to dig into this currently.

**Comment by Slavrix** [comment]
ill give it a go

**Comment by Hirbod** [comment]
any progress on this?

**Comment by Slavrix** [comment]
havnt had a chance to yet, but ill check it out when i can

**Comment by Hirbod** [comment]
I'll reopen since you find a solution

**Comment by walfridosp** [comment]
+1
