### ISSUE TITLE
Install stuck with Fetching Fetching plugin "https://github.com/nightstomp/cordova-plugin-googlemaps-sdk" via git clone

### ISSUE THREAD

**Issue by ashwin19** [mapsplugin/cordova-plugin-googlemaps#679]
When i am trying to install plugin via CLI for cordova installation stuck with this message "https://github.com/nightstomp/cordova-plugin-googlemaps-sdk" via git clone. Did any one encounter such error?

**Comment by Hirbod** [comment]
You need to be patient. Can take up to 5 minutes

**Comment by ashwin19** [comment]
I have waited for more than 30 -40 min. Still the message remains the same. Any way to get the progess in terminal.

**Comment by Hirbod** [comment]
Weird. For me it works flawlessly

**Comment by Hirbod** [comment]
Managed to fix this?

**Comment by jokorivai** [comment]
This should be github or your network issue, not this plugin one. You should check with any other github repository to ensure where the problem is.
