### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lat' of undefined

### ISSUE THREAD

**Issue by githubkyo** [mapsplugin/cordova-plugin-googlemaps#681]
...
        map.getVisibleRegion(function (latLngBounds) {

            $scope.bounds = latLngBounds;            //　地図エリア矩形緯度経度をセット
            $scope.sw = $scope.bounds.southwest;      //　左下緯度経度（左下 lat 小さい　lon　大きい）
            $scope.ne = $scope.bounds.northeast;      //　右上緯度経度（右上 lat 大きい  lon　大きい）
            $scope.k = $scope.ne.lat - $scope.sw.lat; // 地図エリア上部の緯度と下部の緯度の差

        });

        if (lat > 38.0 || lat < 34.4 || lon > 141.3 || lon < 137.0) {

            $scope.$apply($scope.setMsg(true, '周辺に店舗が見つかりませんでした'));

        }

        $scope.nearTenpoSQL = "select *  from m_tenpo where lat > " +
                $scope.sw.lat +      // here is error!!
                " and lat < " +
                $scope.ne.lat +
                " and lon > " +
                $scope.sw.lng +
                " and lon < " +
                $scope.ne.lng;
...

**Comment by jokorivai** [comment]
Put the sql inside callback of getVisibleRegion, to avoid the sql being initialized before callback is called.

**Comment by Hirbod** [comment]
:+1: @jokorivai

**Comment by githubkyo** [comment]
Thank you
