### ISSUE TITLE
Delete all marker 

### ISSUE THREAD

**Issue by FaisalAriyanto** [mapsplugin/cordova-plugin-googlemaps#682]
Hello everybody,
How can i remove all marker without using map.clear()?
Thanks.

**Comment by jokorivai** [comment]
Declare markers colection, i.e
window.markers = [];
And every time a marker added, push it
wondow.markers.push(newMarker);
You can remove them later by looping through 
window.markers[i].remove();

**Comment by Hirbod** [comment]
Yes, this should be the right way. I will consider adding some more API-Methods in the future (like removeAllMarkers, removePolygon() etc)

**Comment by Hirbod** [comment]
@FaisalAriyanto I've just checked the SDKs. There is no official way for it, so I won't add it (I could do it JS-side, but when I save all Markers and Polygons by default, it would be address to much memory, so I will drop this. @jokorivai's suggestions is the right path (on angular, you could also use a $rootScope or something similar)
