### ISSUE TITLE
Error with file path ./ on icon url property

### ISSUE THREAD

**Issue by arilsonkarmo** [mapsplugin/cordova-plugin-googlemaps#690]
This error appears when we try to run map plugin with 500 pins:

10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime: Process: com.test1.testest, PID: 6499
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:300)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:  Caused by: java.lang.IllegalStateException: Not on the main thread
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at com.google.a.a.ab.b(Unknown Source)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at com.google.maps.api.android.lib6.c.c.a(Unknown Source)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at com.google.maps.api.android.lib6.d.af.b(Unknown Source)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at com.google.android.gms.maps.model.a.p.onTransact(SourceFile:169)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at android.os.Binder.transact(Binder.java:361)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at com.google.android.gms.maps.model.internal.zzf$zza$zza.setVisible(Unknown Source)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at com.google.android.gms.maps.model.Marker.setVisible(Unknown Source)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at plugin.google.maps.PluginMarker$1.onPostExecute(PluginMarker.java:164)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at plugin.google.maps.PluginMarker$7.doInBackground(PluginMarker.java:738)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at plugin.google.maps.PluginMarker$7.doInBackground(PluginMarker.java:698)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
10-23 13:52:57.810 6499-7734/com.test1.testest E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841) 
10-23 13:52:57.820 6499-7736/com.test1.testest W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:316)
10-23 13:52:57.830 6499-7736/com.test1.testest W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:290)
10-23 13:52:57.830 6499-7736/com.test1.testest W/System.err:     at plugin.google.maps.PluginMarker$7.doInBackground(PluginMarker.java:734)
10-23 13:52:57.830 6499-7736/com.test1.testest W/System.err:     at plugin.google.maps.PluginMarker$7.doInBackground(PluginMarker.java:698)
10-23 13:52:57.830 6499-7736/com.test1.testest W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
10-23 13:52:57.830 6499-7736/com.test1.testest W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-23 13:52:57.830 6499-7736/com.test1.testest W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
10-23 13:52:57.830 6499-7736/com.test1.testest W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-23 13:52:57.840 6499-7736/com.test1.testest W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-23 13:52:57.840 6499-7736/com.test1.testest W/System.err:     at java.lang.Thread.run(Thread.java:841)
10-23 13:52:57.840 6499-7736/com.test1.testest W/dalvikvm: threadid=52: thread exiting with uncaught exception (group=0x430f3140)

**Comment by arilsonkarmo** [comment]
Edit: The error on debug is : FileNotFindException 
on the String iconUrl = iconProperty.getString("url");  get the path : "images/test/pinimage.png"

in try to get asset : AssetManager assetManager = PluginMarker.this.cordova.getActivity().getAssets(); is throwing me to catch.

Android 4.4, Asus Zenphone.

**Comment by Hirbod** [comment]
So, the file could not be found. Of course it should not crash, but the error belongs to you. I have a map with far more then 2000 pins, working fine.

**Comment by arilsonkarmo** [comment]
Sorry I found the error.

map.addMarker(
        {
          'position': new plugin.google.maps.LatLng(test.location.latitude, test.location.longitude),
          'icon': {
            url:"images/test/pinImage.png",
            'size': {
              width: 25,
              height: 20
            }
          },
        }, function(marker) { 
   //do something.
});

The error is in path of image. we have to use ./ before the path. This is happening only in this version. In old versions works normally in both methods.

**Comment by Hirbod** [comment]
Yeah, we had many changes currently, maybe there is a bug. Thanks for pointing out.
Should be related to the fix made by @cosmith

**Comment by arilsonkarmo** [comment]
Cool! No Problem! 
Another think.. in iOS if you pass ./ before path image cannot be loaded, resulting in red pins.

yeah. it's a serious problem haha.

**Comment by Hirbod** [comment]
When you have Cordova's Device plugin installed, you could do a quick workaround

url: (device.platform == "iOS") ? "...ios" : "android....",

**Comment by Hirbod** [comment]
Actually, it SHOULD work https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/Marker.m#L618

need to dig into it

**Comment by arilsonkarmo** [comment]
i fix it.  range = [iconPath rangeOfString:@"/"];
                if (range.location != 0) {
                    iconPath = [NSString stringWithFormat:@"./%@", iconPath];

when you pass ./ for a path this line range = [iconPath rangeOfString:@"/"]; detect your ./ like / and run this  iconPath = [NSString stringWithFormat:@"./%@", iconPath]; (where concatenate more one ./ in your path resulting in error.

**Comment by Hirbod** [comment]
Could you provide a PR please? Please double check if ./ and / will work

**Comment by arilsonkarmo** [comment]
ok! I will make a fix for android too and I'll make a PR.

**Comment by Hirbod** [comment]
thanks!

**Comment by arilsonkarmo** [comment]
Hi my permission is denied. Can you enable my account to make a branch and a pull request?

**Comment by Hirbod** [comment]
It should be possible?

**Comment by Hirbod** [comment]
It's not blocked, just make a PR. Seems like you're not familiar with GitHub? Just go into your fork and provide a pull request

**Comment by arilsonkarmo** [comment]
haha. I'm try to make a push without use my fork... because my for is pretty old.
I'm updating my fork and I'll make a PR. thanks

**Comment by roblav96** [comment]
Any updates on this? When trying to use base64, a normal marker shows up.

Here's my code:
```javascript
	var image = new Image()
	image.src = '/img/home.png'
	image.onload = function () {
		var canvas = document.createElement( 'canvas' )
		canvas.getContext( '2d' ).drawImage( this, 0, 0 )
		var icon64 = canvas.toDataURL( 'image/png' )

		var home = new plugin.google.maps.LatLng( 47.3522713, -78.1629116 )
		_$map.map.addMarker( {
			'position': home,
			'title': 'Google Tokyo!',
			'icon': icon64 // << this doesnt work :(
			// 'icon': {
			// 	'url': image.src // << this works :D
			// }
		} )
	}
```
I'm sure it's something stupid I'm missing :X

**Comment by Hirbod** [comment]
@roblav96 

tell me if this works for you:


```js
            map.addMarker({
                position: home,
                icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACUAAABACAYAAACdp77qAAARb0lEQVR42s1ZB3hUVdqOmFVRWdQFXYFgKIKACIKCC1JUUCwUC80VERGlI4h0BFkpAlIjAdIIIXV6730m0zLJlEzKpJJeSaUqvPvd2RXkd/1tFM/zvM+de86553u/cr5TJuQPlMcI0wlHu3T5GyesRw/xI2E92CH3hB6jutmE8N8zKIDfTiT0zg7LRw0ZLF02592CQ/v2tadGHYPVaIRFr4eZJwV/VwSOHv727PrVnxU8P3SwvFPnB1YyBG8GqV5h3bof2fD52ha1UAhbUhwqM9LBlLMmLy4XVIIp7RYfWpL0QEMrKlxW2JNiEPfVJiyZO6etT99+kTRO7xtFat2kOUObM6VqtAntQNMF1JcUwcZKQKXDhZoENRrVmajxetDozcX54io0lZTBmnwCmfwUuLmJKHMY4edosGLuguYOoX9Z/UdIdQp7tBsnLv44fOVpuHy2DZWSdDS5A8g1aKA8vg9nystxrrQalxrOwZvGgTXpBLL1CrgVQjg4SXDykuFgn0IWvTf4c9CUm4PDWzegV88wHo1//28lFTbo8T4uQexR4PIVNKu8qFM5cOUCY6VSpO7ZgMRd65AuPIUY1/uIzl4A3bqFUK5fD4eUAxsnEQ5+ahBOIQvm1BMQR+6GQ5iKfJUI/GOHMHTAE06S8+ivJXVvv/CebkF0BDxyLgIWI85IHGgUWVEXCKC5vhYelRRX2i8iz2gGS7IGm839wXWvhoMrhU2QArsw7RoEqbCRG/0mLVoKS5Fj1MKvFkFKHhgycICX5HX+RVI9unc/JWWloibHg8pAHiryc9FQWIQqn4/e89FYWIw6jgl1Mhu+az9HxNVQsyORlSuDQ6tGOrnMJmJdBwsRq/b50SzPQJXHBwuXhXydBimRB9CzezfOL5FauG/nV2BKrcaJi4VVqC8vw4ldn0OZFAWLmI2yzCy0qFxot+Wg1JMFkzAFZnYqyoh4ptMCEzcJ6WL2dTDyk1HszcSlMy2o8ORAJTkCkXw3Csx6bF+/Gh06dFj1c6S6zXj7zUafSY0KZxYqo6VokNtRVVgAk5iDdBkPBkEKvQfQWHoaDSUl8FkNMFKcmJQCeGOOw/TtweBvi5R7HQzUx2czoNXgR0NmNg44JoEj/gpWsQg+kxJvT36tncllPyHVvevfDwcy/KjIy0ZDcTHOBcpxsaoRHoseeooNM5FiYCB3mEgQ8zSSFYL1Vi1Mc96DbPYsmNI1VMdl6q99Q/18djNqs3IQoPSgscSgxJsNi0IAl1YK1oljoLCJ+r+kui15+Z0259FI7F4xHVaJBDmUgzItOpiVQhhpYJOcfxXMu/HquwAG0tbwwouQPj8GBouaqbvWRrNRJ0qDnqyd5TRDkHQMbqkM3zmLUe71QSthw5uuxbz3Zp1jrHWVVI9efT/dveJjpOxdB5OaB55yH/iKvdDJODDQwEbFz0NvUMBycC/KVq1ByaKl0G7fBoNR8d92YfApTomGTpyK9txSVLmzUZrrQ6PNRzHpIVIcZJhUiIs8iAcfeHD9D6TueHPaNE0ZzS60AfmlBmw3DkesdjG0YhJKpHSMAMovBuVPoSWr5dhN8FOM5ZUUw8BnQyPn/adNzqd2Pn3Ph8/hRFtGEZrdeWgLlMFFMaancQ2MJ1TiIF4Y97yR4cOQenLrxo01lxz5OH1CgiuN7WhtaYDLZELA50VLfT0yrSYoSSO9SvwTGNUSyOVipKSmQSgSITnlFAykgIYEOm1GuF026KQSyAzRSAksR3VWBlr1Xqi4CZBTbOqUwb5B127cuK6G+DzFkPokJvLIpcv+MjTJM4LJMk+pAi4Cl8rrSLt81FNuspm1UJNWOrXkOliMKkQdPQyBWAKeQIS9e3bCZJDDTjOzJTOAVm8BHOkWpKh2IFm7Bb5MF/zujOD6WEC/9RoZQYlzFVXgf3P8+9C7794Qcn+n+6UpSSdxtrkFDafLUGa1Y9WLA5CwZx1q1XacjuDhQkk1sn1ZkJMbNBoJ1GoxtFppEGqyis6oo0Amy4mEUGhVkJIFHA4TWlx5aMrMg4Vmp1alhFGjg5Ti1E5tbUYvzrkKYXFowFNE4UJNE6T7I9C58/3ikLCwHsUJibHQkICKokJcOd1Ai2cAx75cjKhNC3GhqAo1+YVQkHC5SgitXgGDQQUlEdPoZDBadYiJOIRF/xiNj0aNxq4tX0BNwa8jmCxaODIsMNv0UGpJGZ0USo0YVnJrqd8Pv9UKjvRbsP2bUEEZf+eimXi8b7/CkN69e51OoxVdRzPAkq6nDwwoyM8BU6q9flxsakY6ETATkfrqalQWFKCtvoGsJIeKSOnsRrAjD+Gbvv3xdXgfHN+4FjqnmQjIISElsj2ZaM8uRj65Sq6RQqfTQ0bjWRxmBAwmJOxcg2aaJDVGOzIVKvTv90R7SM+eYaWJaRSc6ToyvQwiGsjhsqLJX4Dy4yK0WP0oK8qFWS3EhbIaVCaqcD6nBI21NZBTTKlICQVtWcR/+ztEHf8Kzt5d0GSYoSKLSohEPk2WdoMHtYEiyMhSLON+yCgEnC4XLmVUwCcUodrpxSV3ESmqQrce3StCunbtaomMiYSRNFYalFAQZGSBxvwitKoyiEApucAGOQV0TYYH9Sk6tLsD8GS7g/1UdgMEJ6Jgm/sB7P98D6d2bae64FjULoeerN9KM/i8vxbqrMM4aJwOrc4KoSUOhpIjOOsrQZsrH7mFOYhNjEN4eLgmpMMdd2zatX/392ZXOhQkWM7EC6G6ohwl+Xkoo12m2qwNCmltaERdQREaK6sgEqVCTHGooqDlx0ejQshHrUKKpEPfQG7RMmMFISLiAbcbFzR+BPLV4BqSiKwWB3RzEG/7HC0+yl1ZeXD73dh5YA863tPxEJOpRn269rMms9tOuYRIGdWQEUQUM2K9EiLSVkr1MkaIQQ2FSQMZPXlSDli8U5BoyVpmPeppx9DocYNHOUtC39E4QUh0CthcdvgDORCJeRCrFCgI5MHv8UFldKCmuB6BeB4yVDxs3bGjmVLUhOCm7vWpk10a0lhGAv8XxAYiR6SE9JSa1AQNFOkGyM3Uxrgoy0l5pxDNxYWQmA2QGJTUpmW+DT4lRE5I37PVInBEiWi2+vC9vRgqFw9S9z74nSq0kcWWzJjjubpNfiw8/HACP41cYYbUrL0OEhrY5ExHVdlp2N1OiBjtiYzkv+0ySpKydCNq7FbUWNMh1BNRRhmLDpL/fE918qACZeR6b4YdVfn5KKakqnAIsM/4FiwVSZS03ej3SNiRH+8Sxn62eT1M2Zk0IA1EAzIQM6BZ2UBBf07mpHRQCIFZS/XX+sjtJvA0CsgmTIT0H88jTcCFkOpF1E9gIZArk2kx1lICPe8oxnlvGdrySqAhoglKKbxEDnmNiNl/CCF33jHxx6TuHDVujFtKSU1MmovS9VfBkCgPFOJMBu00i4rAM6mvaxcTKa6J0smLEyB+ZiRYcgm4RMZEM7YyrwB6lw0Cqx5ySpTeAi3ys4U4q6XEaTNB7zShuIRmucOP18e95Gd4/JgUMwvnb96zA3p/FgSkqZAECq0ERrCN4oeZnc70a20MSAExgc1OgWrqNEjHv4jk2CikUvDn+3MAWz4ysz3gmMly5OK9xrch952E3UcK0kbygsGLi7VnsCNyP0I6hCz+X9vhu4Y/NzJHyFjLYQ5qyyGrCEgoAz6RIBARY5BMEHRKFkkFSNj1FQSDh4DTPRyxX24Gm5cGJcWfldZLVYYVfFJOQO5jW+REUI9EgwJOnxutzBnSlYGhI4YFSP49P3dweHXp+jVQUWzZsrNQUV1FrtGCy7iRyP4EmeQadjJOHYuAZMx4cPsNRDzt01kJceBn2cCmeORZf/jWBDPlq9qaapg9rqCirrJCfLXjXwyLN//fI1Z4n948m92Gi5V1QF0TGqproKT44KSTtWym6yB0kWAhB/FESjxsBLjhfRG7fy+SWckQUNsP/ThEQE4KtOUWo1VEs7SoBOIsO+LlQgwcOEj8aw6jfZZ89HHbeRWdaE4pcK6qFhpyBZtxod10HQSUcFmcFMSejIH0mefA7fU44mKPIfFkLPhEgkd9mO/SKBREGRa0FJSiVZ+JyuJSKHPdmPbuLOYU0/fXkGKy/KKo1VsBa35QKxHFDoeZ+g7zdeB7nEiOj8EpVhIkI0eB1bM34k/FIT7yMDiZVnDIbQqyWENjA4y+TMjpt8nvRnZ1Odbv3YnQ0NAVv+mCo2/fPqL8LA9w5QoUmQ6wyA1chyUIntMCtt0MFglJovNeVPRRCJ9+Bvw+/REdGQF2HG19qT2jIA/ny6pxNjMf3zU0w5zjoW+siJaJ0Kd/P/nvuXXp8drUKY1q0ozNkHGmXwWLBIqzHCg/U4+mhjo0tLegrbQE7adL0XKuHefPtaGZEDhdghaLF+URXDS4c6Eia4kp5bw8bUojjd/z995PzVn8xUaoi3KDxDhEiEEKWU3n9+CXSlExrQQVdahx+nClpR1ZVWVYuu0LRurcP3Rp1r1nWFqkmAcJY3oixKa8k0oEpV4Xrlz+Dq11tairr0NzTTXN1CpKI5Woo3WyrakJUpsFYpokMurrrTiNKKkQ3R/rybsRN3ndXpz8eqM41xuMoSAy7eCQsA3Ll2PRmLH4cOLLmP/SBMyjU/I0ei5+bhTmTHwFe1KTwPa5kEqK8HLcmPDm1GZm/b9Rd54fr/p6O+TFeUgjAWyKpxRPBmZNnYp3Bw3G+iFPY/azIzFrxEisGzocC4aPwIQnn8IWCnhhrgeyojys2beHkbbsht4OP/HUYEuCRQ8uuSKNSYwFfmzdshkznxqCGWPGYTpZbMrYcZhPJ5oZo8fglRHPYQcd3STUL5HSyaDhTzuZbHOjr6xHv79qBWQlAaQSqbSAH6zDB3GyTz9sJ1dFTnoVCcOexX4iePC115FMFjtBMaSoKsWHaz9nJL1wU+7Rw/v25R/XKMCldTE1Pxusb/aAR66KXr4MJ+fNg2jIMCTNmo3Yjz6CdPAwpHFYiLGbKSf1l93My/1n565eBWlxACl5PiTRwTORscoHHyBm1iwcW7Ec3E8+wck330ICWU5CF//ztm9jpIy7maRCBgwdojxhNYFFs5EzezYSX54ETe/+iH/1NcS+NwdJM2dBTgtz8uQpSF6yBP0nTjDe7L9BmPL2SppJwkAOTpKrjs+ciVgidGLhQhz9cguOLV2C6HfegXTZMmx+YiBCOnacdStI3Tt+1owyrlYFPgX2UYqlU5s2IpVcyaEZd4zIpdB9umD3Lkx54MFqpv+tIBXy8OAn9+3fuAHKQUMQvXQpTtLJOGHJUkjDeiFu8SKkfjAPXy9YgB4PPnTkZv+Lda106PD8x+PGgTdlGmJoBkYc3I+4FSsQQTEWv3YNkvbuwQfz5wXTwC0jRSV0YpeuBdEH9oFFwRwzfToi1q5FFF0JxQu44FPwj+3fr4T63X0rSYX06NLl4PZ/bYNs8lSwmNjavBkJM2Yi7uABxFNsDQq96yjT75aSuuvuu9/4eP6HYL8xGfFvvYNoWny/3bYVSRIhVj49jA6Wd06+5aSodHp12LC6KIqhIxRXqStXIoqeyV9+iXHDn6kPuf/eh24HKWaRTjy88lPE22njt3ULWGPHY/eazzFgwkscpv22kPpr578u2Db8WSR9sRmJCxdBT6eZjW+8gU6PPLz0tpGiMvC9mTO+SywrxsklixFP2f39V165HBIaOuR2kvrLhHlziziHDiCCFuLYw4fw0uyZp5lUcDtJhYzo1o3+vd2A2KwMHNy8CQPGjBEy9beVVOdOnTZu27YNqthY7KNtzEOPPbbxtpOi8uqyz1bBPuEVbH60B0Luu2/G7Sd1110Dlo8Z+71w/kf45/jxF0PuDH3iz0Dqvpe7Plx5ks/F7EmTyqim4+0nRWXiwEEG/rr1GDl6VDbz/qcgNWL0KO4uOpA+81AX1Z+GVLeHH17/0L33oldY2KYbQerfxcfvGvlQSLYAAAAASUVORK5CYII="
            });
```

**Comment by roblav96** [comment]
That does not work for me :/

**Comment by Hirbod** [comment]
iOS or Android?

**Comment by roblav96** [comment]
Android. NO crosswalk.

```
Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X Yosemitie
Node Version: v5.0.0
Xcode version: Xcode 7.1 Build version 7B91b 
```

**Comment by atannus** [comment]
I believe you have to specify the icon as an object with url and size, such as:

`
'icon': {
  url: 'www/images/image.png',
  size: {
    'width': 32,
    'height': 32
  }
}
`

At least what is what works for me.

I'm wondering who is the maintainer for the Android support of this plugin. I have done some extensive work on the PluginMarker class, mostly in comments and improving code quality.

The changes, like I said, are significant, but they greatly improve two areas:

1. Performance of the plugin when inserting a large number of markers simultaneously (I add several hundred markers at a time).

1. Bla.

**Comment by roblav96** [comment]
the maintainer is @Hirbod

**Comment by atannus** [comment]
Yeah, I've looked at the code for declaring the icon as a single property, like @roblav96 wanted to do, and it's really not hard to implement it correctly, but the code in the current master is waay too messy to even consider fixing this support. It seems like it grew organically and can greatly benefit from an overhaul, part of which I've already made.

I don't want to go through the huge trouble of forking, fixing, testing and sending a PR that will be rejected.

**Comment by roblav96** [comment]
Ye I mean this project is not as reliable as I had hoped it to be. I used it for a few months on a project but it was not working out. I'm currently now using mapbox-gl-js which is more consistent than this plugin.

**Comment by arilsonkarmo** [comment]
Do you tried my fix? 
https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/691

**Comment by roblav96** [comment]
Well, this icon problem is only the beginning. I've had numerous ios random crashes too. If someone started this project back up, I would certainly fund it however I can.

**Comment by Hirbod** [comment]
I will not reject good work, especially when it improves performance.

**Comment by madfauzi** [comment]
i have same proble with @roblav96 
When trying to use base64, a normal marker shows up.

var iconBase64 = 'data:image/png;base64,iVBORw0KGgoAA....';
map.addMarker({
position  : latLng,
icon        : iconBase64
}, function(marker)  { });

Any updates on this?

**Comment by Hirbod** [comment]
icon: {
   url: base64
}

**Comment by madfauzi** [comment]
great, its work
thx @Hirbod 

this plugin is awesome :D

**Comment by Hirbod** [comment]
Thx
