### ISSUE TITLE
Click events not firing in Ionic app

### ISSUE THREAD

**Issue by wbreza** [mapsplugin/cordova-plugin-googlemaps#693]
Any ideas whey I'm not getting any click events, gestures or controls working in my Ionic app?  I can draw the map perfectly, add markers, etc... just not getting ANY interactions...

**Comment by joewoodhouse** [comment]
Make sure you add data-tap-disabled="true" to the element you're initialising the map on.

**Comment by wbreza** [comment]
Unfortunately that didn't fix it.  After too long of troubleshooting I finally found it it was because I had it within a directive whose element was a custom tag.  After changing the directive to "replace" all is well in the world.
