### ISSUE TITLE
plugin not defined

### ISSUE THREAD

**Issue by deepak-nagesh** [mapsplugin/cordova-plugin-googlemaps#694]
Getting plugin not defined error.
Cordova version 5.3.3.
Below are the plugins used.

![pluginlist](https://cloud.githubusercontent.com/assets/6448891/10722572/7e1b30ce-7bd7-11e5-87b2-633411238850.png)

**Comment by Hirbod** [comment]
the plugin works perfectly, I don't know what you're doing.

**Comment by datatypevoid** [comment]
@Hirbod that is just about the worst response I have ever witnessed on GitHub lol. I stumbled in here looking for an answer to the same question. Luckily I figured it out on my own. In my case, I didn't realize that the cordova plugins wouldn't be available during development as I expected.
