### ISSUE TITLE
Plugin not working on android sdk 22

### ISSUE THREAD

**Issue by mosinconsrv** [mapsplugin/cordova-plugin-googlemaps#695]
Hi there,
I am developing an ionic app in which I am using this plugin. Its working fine on android SDK 19. But recently I updated my android SDK to android 22 as I want to integrate crosswalk in my app. 
The map is appearing blank with only google logo placed at the footer. I have verified my api key and SHA fingerprint both are correct. Its not giving any error while building apk.
I also referred the tutorial to install this plugin for crosswalk but still no luck.﻿

**Comment by Hirbod** [comment]
Grey map with Google Logo = api key problem. Recheck

**Comment by mosinconsrv** [comment]
Thanks for the reply @Hirbod. I just rechecked, the api key its correct. As I already mentioned the map was working fine when I was using android sdk 19 but as I switched to android sdk 22 it started giving me this problem.

**Comment by mosinconsrv** [comment]
@Hirbod Do we need to add google play services manually?

cordova plugin add https://github.com/wf9a5m75/google-play-services#v22

I am using android sdk 22 & cordova 5.0.0.
