### ISSUE TITLE
Crash on iOS9 when calling marker mutators / initializing them

### ISSUE THREAD

**Issue by n00dl3** [mapsplugin/cordova-plugin-googlemaps#696]
My app crashes when I initialize it on iOS9.
>Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull boolValue]: unrecognized selector sent to instance 0x19fde9ea8'

Same kind of thing as in #688 , wrong parameter type. I'm gonna use my (poor) knowledge of iOS to debug this. 
More informations coming soon. F**k, I hate Xcode and Objective-C :cry: !!!!

**Comment by n00dl3** [comment]
Ok, so the problem is that if you call any `setFoo()`method on marker object with an undefined parameter, the app crashes, it happened for me with `setRotation()`, `setVisible()` and `setFlat()`. I don't have much time to fix it by myself this week, but if it is not fix this weekend, I'll send a pull request.

**Comment by Hirbod** [comment]
So why are you calling it without parameter? :) 
I just tried it, it won't crash on setFlat, but it will on setPostion('') or setRotation('');

I will add a small check on the JS-side to return false when it's empty

**Comment by n00dl3** [comment]
>So why are you calling it without parameter? :) 
I am not, angular does it for me when the scope is digested. However, the app should not crash.

**Comment by Hirbod** [comment]
fixed in master

**Comment by n00dl3** [comment]
thanks !

**Comment by Hirbod** [comment]
> That's what I wanted to do, but I have to type a report to my boss explaining why we should avoid using third party plugins like this one :laughing: .

Maybe you just should not be unthankful and do not pass invalid values to the functions. Troll.
