### ISSUE TITLE
Marker Clustering is coming

### ISSUE THREAD

**Issue by Hirbod** [mapsplugin/cordova-plugin-googlemaps#699]
Hello everybody,

we got it! Thanks to @limeuwe and @TheMassassian we finally have clustering support.
iOS is already working.

<img width="423" alt="bildschirmfoto 2015-10-27 um 16 55 45" src="https://cloud.githubusercontent.com/assets/504909/10764817/26853306-7cd0-11e5-9d06-fd9727179aea.png">

**Comment by FaisalAriyanto** [comment]
cool bro

**Comment by Hirbod** [comment]
Yay. Android will work also now. But currently, no images will be loaded and no events will fire, still many work for android to investigate. 

<img width="601" alt="bildschirmfoto 2015-10-29 um 01 40 28" src="https://cloud.githubusercontent.com/assets/504909/10807261/0dd7152c-7dde-11e5-8b8a-b5b436ae40f4.png">

**Comment by FaisalAriyanto** [comment]
okay, i dont know how hard to make native plugin to work in hybrid but thanks hirbod. btw what framework do you use? i think kendo ui cant make big circle button in the tabstrip, its really cool

**Comment by Hirbod** [comment]
The circle is from google maps sdk, and it's quite hard. Android nearly killed me today.

**Comment by Hirbod** [comment]
Ah, sorry, I misunderstood. I'm using Onsen-UI, it's actually just made with CSS, they also don't support big circles by default. I just needed to remove the overflow hidden property of the tab-bar-element, rest ist just border-radius etc.

**Comment by Hirbod** [comment]
Before I release the clustering feature, I want to raise a funding of 800-1000$. I will donate some of the funded money to @limeuwe for donating the code and to my developer for the Android part.

[Donate on Bountysource](https://www.bountysource.com/teams/cordova-plugin-googlemaps)

[![img](https://www.paypalobjects.com/webstatic/en_US/btn/btn_donate_cc_147x47.png)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=LLCBVUA7TQ8SU)

**Comment by roblav96** [comment]
can you provide an english link please?

**Comment by Hirbod** [comment]
On Paypal?

**Comment by roblav96** [comment]
this link is broken:
```
https://www.bountysource.com/checkout/amount?team=cordova-plugin-googlemaps
```
Can you provide me an english paypal link?

**Comment by roblav96** [comment]
Any updates on this paypal donation in english? I really want to give you something for your efforts on this plugin. Thank you!

**Comment by Hirbod** [comment]
If you want, just send something to 

info "you not that special sign" hirbod.de

**Comment by roblav96** [comment]
It has been done. Thank you!

**Comment by Hirbod** [comment]
Thanks a lot, but why don't you sent it with PayPal? I don't know pop money

**Comment by Hirbod** [comment]
I can't deposite because I'm not an US citizen and Germany is not supported. Your money will be returned automatically on 7th December. You could send to me via PayPal.

**Comment by roblav96** [comment]
Dang, OK. lol I didn't know you could email money through paypal. I'll fix that.

**Comment by pke** [comment]
What is the holdup with the Android version? Aren't the google SDKs for maps identical? Clustering is available in the official Maps SDK and it seems pretty easy to implement in Android: https://developers.google.com/maps/documentation/android-api/utility/marker-clustering?hl=en

**Comment by Hirbod** [comment]
@pke Clustering is only available for Android SDK, not the iOS SDK. The implementation would differ when using the official SDK and an inofficial API for iOS. We decided to incorporate third-party code for iOS and Android - different implementations but same algorithms.

The clustering is mostly done and donated from @limeuwe's company, fixed and optimized by me and an external developer. It was/is very time consuming and tooked at least 80 hours of work from our side, no idea how much work it took from @limeuwe's side. Currently, people have donated 50$. Funding limit is 1000$. When funding limit is reached, we will officially publish it.

If it's that easy, you are free to develo clustering for both iOS and Android and submit to us.

**Comment by saad-ansari** [comment]
Download below JS file and include in your project 

    http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer.js

Add following code in your controller and replace your Map Object with '$scope.myMap' and pass your Markers Array as parameter 'markers'. 

    $scope.initializeMarkerClusterer=function (markers)
    {
            $scope.markerClusterer = new MarkerClusterer(
            $scope.myMap,
            markers,
            {
                maxZoom: 18,
                gridSize: 15
            });
    }

and now just call this function after completing all your normal functionality of showing markers on Map.
       
       $scope.initializeMarkerClusterer($scope.myMarkers);

Now you will have marker cluster on your map!! 
Cheers and happy coding..

![screen shot 2016-01-11 at 6 08 38 pm](https://cloud.githubusercontent.com/assets/2099415/12235636/673249e4-b88e-11e5-9b2b-c3b02b0da6d3.png)

**Comment by Hirbod** [comment]
😂😂 - have fun with your JS map... We have the native SDK

**Comment by arilsonkarmo** [comment]
OMG. hahaha

**Comment by dbesiryan** [comment]
any news about the release? can't wait to implement the cluster feature :)

**Comment by pke** [comment]
well you know what? Tried the Bing Maps JS SDK on Android, iOS and Windows Phone. Its reasonable fast and comes with clustering build in. So I'll go with that for now, see no need for anything 'native' if it throws rocks in my way.

**Comment by dbesiryan** [comment]
@pke i cannot find the clustering Feature for Bing Maps. I visited bingmaps dev center

**Comment by pke** [comment]
Ah sorry, its an `OpenLayers` feature. I am just using Bing Maps as one of the (base) layers for the map display. The cluster come from `ol.source.Cluster`. Pretty easy and straight forward.

**Comment by dbesiryan** [comment]
Thank you! i will give it a try👍. BTW, do you Know if there is an Option to use the cordova googlemaps Plugin with the openlayers?

**Comment by pke** [comment]
No, this plugin uses the native SDKs. OpenLayers is a JS SDK.

**Comment by dbesiryan** [comment]
damn..

**Comment by wf9a5m75** [comment]
Well, I really wonder why don't you folk the marker cluster I created before. https://github.com/wf9a5m75/markercluster

I implemented both Android and iOS version, same methods, same functions.
There is some points need to fix, but it's almost completed :(

**Comment by Hirbod** [comment]
To be honest, I thought you only finished android. We can stick to yours if you want. @wf9a5m75

**Comment by Hirbod** [comment]
There is no iOS version inside your branch @wf9a5m75 
That's why I dropped your version

**Comment by wf9a5m75** [comment]
@Hirbod I said to you in e-mail, there is the dev branch, and that has ios version.
https://github.com/wf9a5m75/markercluster/tree/dev/src

You didn't check it?

**Comment by Hirbod** [comment]
Somehow missed that
