### ISSUE TITLE
error in phonegap build

### ISSUE THREAD

**Issue by alaanasreng** [mapsplugin/cordova-plugin-googlemaps#700]
In build.phonegap.com

when i use this lines in config.xml:

< gap:plugin name="plugin.google.maps.menusito" version="1.2.5" >
	< param name="API_KEY_FOR_ANDROID" value="------" / >
</ gap:plugin >

give me this error in:

Error - The following plugin (or plugin version) is not on npm or not available for this platform: /home/ec2-user/gimlet/var/plugins/dfe3d26a-1c56-11e5-bd0a-22000ba705f9 --var API_KEY_FOR_ANDROID=": Installing "plugin.google.maps.menusito" for android Fetching plugin "plugin.http.request

and i am using 3.7.0 phonegap version

**Comment by Hirbod** [comment]
this is not our plugin

**Comment by demege** [comment]
This config worked for me:

```javascript
    <gap:plugin name="cordova-plugin-googlemaps" source="npm" >
        <param name="API_KEY_FOR_ANDROID" value="key" />
        <param name="API_KEY_FOR_IOS" value="key" />
    </gap:plugin>
```
