### ISSUE TITLE
map view and webview

### ISSUE THREAD

**Issue by alaanasreng** [mapsplugin/cordova-plugin-googlemaps#701]
when i use map plugin in my app and scroll down, the map is fixed and don't move with my app

is there any solution?

**Comment by Hirbod** [comment]
you need to change the map_canvas position with JS and call map.refreshLayout()

also have a look for watchDogTimer, to speed up the speed of position adjustment

**Comment by alaanasreng** [comment]
please @Hirbod 
can you help me how to change map_canvas with JS

**Comment by Hirbod** [comment]
No, sorry, I'm not giving support for JS-problems. Small and last hin

$('#map_canvas').css(..do...whatever...you...want);
