### ISSUE TITLE
plugin.google.maps.Map.getMap google undefined

### ISSUE THREAD

**Issue by explosoft** [mapsplugin/cordova-plugin-googlemaps#702]
May i know how to use this plugin ?

Error message :
plugin.google.maps.Map.getMap google undefined

**Comment by Hirbod** [comment]
The wiki is big enough

**Comment by explosoft** [comment]
Good Day

Thank your reply

I have download the file already , but i dont not how to call this plugin ! , may i know can step by step let me know 


![capture](https://cloud.githubusercontent.com/assets/15373050/10837351/7d83f438-7ef3-11e5-8a1a-3a18a6b6830f.PNG)

**Comment by Hirbod** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Installation
