### ISSUE TITLE
Application does not build after plugin installation

### ISSUE THREAD

**Issue by tperrelli** [mapsplugin/cordova-plugin-googlemaps#703]
Hi everyone! 

i just installed the phonegap-googlemaps-plugin following cordova steps. When i try to build for android "cordova build android", i get the error in the attached image. Do someone passed through the same issue? Thanks!﻿

![cordova-google-maps-error](https://cloud.githubusercontent.com/assets/1470890/10816993/9b1004da-7e15-11e5-8bfa-9d198a1bd2c2.png)

My installed plugins

![installed plugins](https://cloud.githubusercontent.com/assets/1470890/10817456/ac214ce0-7e18-11e5-9355-bbece6c2dea6.png)

What i'm missing? I'm new in cordova and kinda lost :(

**Comment by Hirbod** [comment]
see #686 and #689
