### ISSUE TITLE
OVERLAY_CLICK returns wrong polygon when polygons are overlapping

### ISSUE THREAD

**Issue by karlkilgi** [mapsplugin/cordova-plugin-googlemaps#708]
I have polygons overlapping each other and they have different zIndex. One polygon is inside of other.
When clicking on a polygon that has higher zIndex and it is on top of other polygon, OVERLAY_CLICK returns polygon that has lower zIndex.

**Comment by Hirbod** [comment]
its a google bug, can't fix this. Already reported.
