### ISSUE TITLE
Initiating map element causes temporary transparent background in Ionic

### ISSUE THREAD

**Issue by benallfree** [mapsplugin/cordova-plugin-googlemaps#709]
I'm using Ionic, I wonder if someone can help me track down this bug. When I load a map into its `#map` container, the initialization causes a temporary 'flicker' because the background becomes transparent. I can see the previous view underneath.

This is very noticeable during view transitions in Ionic, and definitely is related to the map initialization.

Even if I initialize the map in `$ionicView.afterEnter`, I still see a slight flicker as the underlying view temporarily appears through the transparent background before the background becomes opaque again after the map is done rendering.

Does anyone else have more info or clues?

This does not happen with the JS implementation of Google Maps.

**Comment by Hirbod** [comment]
The map need to make every parent element transparent (including body and webview) in order to make the map behind the webview visible.
