### ISSUE TITLE
Transparency Problem: XWalk14 + Android + Cordova5

### ISSUE THREAD

**Issue by ffabreti** [mapsplugin/cordova-plugin-googlemaps#711]
Testing my app on a Motorola Razr i - Android 4.1.1 (x86 CPU) I have faced a transparency issue where the plugin map let the background of the O.S. shows through.

I have followed the tutorial for using CrossWalk with this plugin. Works fine on a Galaxy S4.
Any clues ?

Screen1
https://drive.google.com/file/d/0Bz9EAjPa_w23VElBMUxZNFlTMlE/view?usp=sharing
Screen2
https://drive.google.com/file/d/0Bz9EAjPa_w23N2JwWmV3d0VJdlE/view?usp=sharing
Screen3
(https://drive.google.com/file/d/0Bz9EAjPa_w23cFY5NG96aEgwd2c/view?usp=sharing

**Comment by Hirbod** [comment]
Please file a bug report on jira-crosswalk and post them our tutorial.
