### ISSUE TITLE
Have older versions been deleted?

### ISSUE THREAD

**Issue by davidluthiers** [mapsplugin/cordova-plugin-googlemaps#713]
Since plugins.cordova.io has been deprecated (a week ago) we can't use the Google Map Plugin with ~1.2.4 version as stated in the Documentation link:
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/411#issuecomment-75452290

If I try to build with the "cordova-plugin-googlemaps" from npmjs it doesn't find this version. And the last plugin versions requires Gradle.
This forces us to move on to the last Phonegap version, which have Gradle and then we can use the last plugin version.

But this is a problem, because moving onto a new Phonegap version means a lot of things and development have to be re-done again. 
Is there any way of putting the older version (1.2.4 - 1.2.5) in the npmjs page?

Thanks.

**Comment by Hirbod** [comment]
Maybe I misunderstood, but why don't you use version 1.3.4, which I pushed to npm?

**Comment by davidluthiers** [comment]
Because 1.3.4 requires cordova > 4, and another thing that I'm using only works at cordova 3.7.0. 

Thanks for your fast answer, I'm going to do what you suggested and let you know the outcome.

**Comment by davidluthiers** [comment]
I can't make it to work :(

I had put it on github:
https://github.com/davidluthiers/cordova-plugin-googlemaps-124

And published it on npmjs:
https://www.npmjs.com/package/cordova-plugin-googlemaps-124

But Phonegap Build doesn't find it:
Error - The following plugin (or plugin version) is not on npm: cordova-plugin-googlemaps-124

**Comment by davidluthiers** [comment]
I solved the problem, I couldn't make it work in the last Phonegap version because of the required plugin "cordova-plugin-googlemaps" for internet access...Thank you for your time.

**Comment by Hirbod** [comment]
Thanks!
