### ISSUE TITLE
This plugin seems can not added to the Intel XDK cordova build.

### ISSUE THREAD

**Issue by aahedi** [mapsplugin/cordova-plugin-googlemaps#714]
Whether it can be supported in order to be used also in Intel XDK?

**Comment by Hirbod** [comment]
I don't have any knowledge with Intel XDK. I will close this for now, when you have useful informations or even a solution, please do not hesitate to post it for other users.! Thanks!

**Comment by ttarakanoff** [comment]
When you add cordova-plugin-googlemaps to Intel XDK and specify your API_KEY_FOR_* variables you will get blank screen (without Google logo).
Problem seems to be similar to this one https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map but how to fix it from the Intel XDK?

**Comment by ttarakanoff** [comment]
I examined this problem more and I can say when you actually build your app in Intel XDK, map works without any issues. 
Problem exists only when you preview your app in Intel App Preview. 
It doesn't matter what type of preview you use: USB, WiFi or Intel server.
I will try to contact XDK developers about this issue.

**Comment by ttarakanoff** [comment]
Also when you try to debug app with the plugin, you will get error while generating debug module
![screenshot](http://i.imgur.com/qdvg0ry.png)
When you debug app without this module everything fine.

**Comment by ttarakanoff** [comment]
Got an answer from Intel.
Conclusion: if you want to use the plugin with Intel XDK, you have to use remote debugger.
More info: https://software.intel.com/en-us/forums/intel-xdk/topic/605927

**Comment by jmi23** [comment]
It works with intel XDK in debug mode on connected devices - with debug modules. usage as window.plugin.googlemaps
