### ISSUE TITLE
Google map plugin is not working and installing proper giving build error

### ISSUE THREAD

**Issue by nishithrajyaguru** [mapsplugin/cordova-plugin-googlemaps#717]
Hi,

I am using this plugin in my cordova application.
When I try to install the plugin, it is installing google map plugin. previously it was adding the plugin for androidv4 and play service as well.

Due to this I am getting error while building the project. I am using the stable version of google map to install it using below command.
cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="ANDROID_KEY"

ERROR : some resource and image are not found

If  I remove google map plugin then my project is building successfully.

Kindly Provide me the stable link to download the plugin or the version 1.2.5 which was working properly in my project . OR please help if anyone have faced the same problem.

**Comment by ullasmohan** [comment]
Facing same issue !

**Comment by Hirbod** [comment]
Nobody can help without error logs, but I think you are missing Google support and android support sdk. Grab it inside your SDK Manager and recheck the new install progress, as we using framework tags and no support libs anymore

**Comment by nishithrajyaguru** [comment]
Please find the error log below.
_______________________________________________________________________



F:\CSM\06.SourceCode\02.Development-PostProd_1.0.0.10_6Aug14\HDFCERGO.CSMApp\HDF
CERGO.CSMApp\bld\Debug\platforms\android\build\intermediates\exploded-aar\com.go
ogle.android.gms\play-services-base\8.3.0\res\drawable-xhdpi\common_plus_signin_
btn_text_dark_pressed.9.png ERROR: Unable to open PNG file
F:\CSM\06.SourceCode\02.Development-PostProd_1.0.0.10_6Aug14\HDFCERGO.CSMApp\HDF
CERGO.CSMApp\bld\Debug\platforms\android\build\intermediates\exploded-aar\com.go
ogle.android.gms\play-services-base\8.3.0\res\drawable-xxhdpi\common_google_sign
in_btn_icon_dark_normal.9.png ERROR: Unable to open PNG file
Error: Failed to run command:
        C:\Users\rajyagni\AppData\Local\Android\android-sdk\build-tools\23.0.1\a
apt.exe s -i F:\CSM\06.SourceCode\02.Development-PostProd_1.0.0.10_6Aug14\HDFCER
GO.CSMApp\HDFCERGO.CSMApp\bld\Debug\platforms\android\build\intermediates\explod
ed-aar\com.google.android.gms\play-services-base\8.3.0\res\drawable-mdpi\common_
google_signin_btn_icon_dark_disabled.9.png -o F:\CSM\06.SourceCode\02.Developmen
t-PostProd_1.0.0.10_6Aug14\HDFCERGO.CSMApp\HDFCERGO.CSMApp\bld\Debug\platforms\a
ndroid\build\intermediates\res\debug\drawable-mdpi-v4\common_google_signin_btn_i
con_dark_disabled.9.png
Error Code:
        42
Output:
        F:\CSM\06.SourceCode\02.Development-PostProd_1.0.0.10_6Aug14\HDFCERGO.CS
MApp\HDFCERGO.CSMApp\bld\Debug\platforms\android\build\intermediates\exploded-aa
r\com.google.android.gms\play-services-base\8.3.0\res\drawable-mdpi\common_googl
e_signin_btn_icon_dark_disabled.9.png ERROR: Unable to open PNG file

:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeDebugResources'.
> Error: Failed to run command:
        C:\Users\rajyagni\AppData\Local\Android\android-sdk\build-tools\23.0.1\a
apt.exe s -i F:\CSM\06.SourceCode\02.Development-PostProd_1.0.0.10_6Aug14\HDFCER
GO.CSMApp\HDFCERGO.CSMApp\bld\Debug\platforms\android\build\intermediates\explod
ed-aar\com.google.android.gms\play-services-base\8.3.0\res\drawable-mdpi\common_
google_signin_btn_icon_dark_disabled.9.png -o F:\CSM\06.SourceCode\02.Developmen
t-PostProd_1.0.0.10_6Aug14\HDFCERGO.CSMApp\HDFCERGO.CSMApp\bld\Debug\platforms\a
ndroid\build\intermediates\res\debug\drawable-mdpi-v4\common_google_signin_btn_i
con_dark_disabled.9.png
Error Code:
        42
