### ISSUE TITLE
Multiple Map Markers

### ISSUE THREAD

**Issue by schurkecon** [mapsplugin/cordova-plugin-googlemaps#72]
Hi @wf9a5m75,

Thanks Masashi Katsumata for the new version of the plugin and for fixing the issues.
I just wanted to ask if the latest version supports multiple map markers. 
If this feature is not yet supported, is there any work around?

Thank you.

Edit Notes: Tested on Android Device, Multiple Markers is working, but cluster marker is not.
Issue is closed: Possible Duplicate of https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/9

**Comment by deshatom** [comment]
I created loop to add multiple markers... like this
`
var markers = ['marker1','marker2' ........... , 'marker100'];
for( var i=0; i < markers.length(); i++){
 map.addMarker({
     'position': new plugin.google.maps.LatLng(data.post_lat, data.post_long)
 }, function(themarker) {
     markers[i] = themarker;
 });
}
`
there are more than 100 of markers.. When try to click back button, it says 
Unfortunately, AppName has stopped.
