### ISSUE TITLE
Reuse Multiple Maps as a Service

### ISSUE THREAD

**Issue by rickschmidt** [mapsplugin/cordova-plugin-googlemaps#720]
I've done enough research to know the Map object is a singleton object and there are no plans to implement multiple maps. Is it possible using ionic + angular to create a service and reattach the map object to different divs when navigating from page to page? I've given it a few tries and every time I try to get a handle on the object it invalidates the first and results in no maps being displayed on any page.

**Comment by Hirbod** [comment]
This should be possible, please have a look at this example:
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/432

Reattaching the map is not a problem at all.
