### ISSUE TITLE
Geocoder include getAddressLine and getMaxAddressLineIndex

### ISSUE THREAD

**Issue by Distopico** [mapsplugin/cordova-plugin-googlemaps#721]
Hi, some address in Latin America have more complex address and current object return by geocoder in this plugin not have all necessary information for construct correct address.

please add **maxAddressLineIndex** from android API **getMaxAddressLineIndex(), getAddressLine(int index) and getSubAdminArea()**

http://developer.android.com/reference/android/location/Address.html

thanks

**Comment by Hirbod** [comment]
Is this

a) available for both iOS and Android?
b) If a = true, would you mind to provide a PR?

**Comment by Distopico** [comment]
ok, I will prepare a PR :)

**Comment by Hirbod** [comment]
Merged #800. Available in master (inside of extra object)

**Comment by Hirbod** [comment]
and now also on npm! many thanks goes out to @vxcamiloxv
