### ISSUE TITLE
More bitcode annoyance

### ISSUE THREAD

**Issue by roblav96** [mapsplugin/cordova-plugin-googlemaps#722]
I've been at this error for about 6 hours now no joke.

```
ld: 'client/Plugins/com.googlemaps.ios/GoogleMaps.framework/GoogleMaps(GMSCachedTile.o)' does not contain bitcode.
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is driving me absolutely nuts. I can't develop any further.

```
Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X Yosemite 10.10.5
Node Version: v4.2.1
Xcode version: Xcode 7.1 Build version 7B91b
iOS: 9.1
Installed platforms: android 4.1.1, ios 3.9.2
```

I tried everything I can think of. I made a fresh blank project and installed from both npm and github. nothing.

I followed this video:
https://www.youtube.com/watch?v=gr0QrEShPbQ
nothing.

I also followed everything on this post:
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/620

Is it just not possible to run this with bitcode enabled?

**Comment by Hirbod** [comment]
Yes. Build Settings -> Bitcode enabled -> No

**Comment by roblav96** [comment]
That's what I've resorted to, but how will my app get approved in the app store?

**Comment by roblav96** [comment]
how much would it cost?

**Comment by johnrobertcobbold** [comment]
@roblav96 enabling bitcode is not compulsory to get your app into the appstore (at least for now)

**Comment by roblav96** [comment]
sweet! thanks :D

**Comment by Hirbod** [comment]
Only obligatory when using tvos or watchOS, but will change soon for sure. But it's actually on google side to provide bitcode support. Nevertheless, my apps got all approved with disabled bitcode support

**Comment by Hirbod** [comment]
SDK 1.11.0 is out, with Bitcode support. I will update the SDK today.

**Comment by roblav96** [comment]
Sweet! Thanks man!

**Comment by Hirbod** [comment]
Update is out!

**Comment by roblav96** [comment]
Love it! Can we try to get base64 marker/icons working again?

Also take a look at these commits by joe.
https://github.com/joewoodhouse/phonegap-googlemaps-plugin/commits/master
Looks like he's added a few useful features.

And when installing from the master I get a white screen. I'll upload an adb logcat.
