### ISSUE TITLE
Feature request - Polygon contains location

### ISSUE THREAD

**Issue by lengoyvaerts** [mapsplugin/cordova-plugin-googlemaps#724]
Is it possible to implement the containsLocation feature? I think it's not yet imlemented because I can't seem to find it in the documentation.

Reference: https://developers.google.com/maps/documentation/javascript/examples/poly-containsLocation

**Comment by joewoodhouse** [comment]
I think you can already do this by just creating a LatLngBounds https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/LatLngBounds with the same points as the polygon, and then using it's contains() function?

**Comment by lengoyvaerts** [comment]
I already looked into this earlier. It's not really the same. This function creates bounds for a rectangle. What I actually need is the same but for other shapes (polygons)

**Comment by Hirbod** [comment]
containsLocation() isn't available for iOS or Android-SDK - it's a Javascript V3 only feature.
You can find if a point is inside a polygon by using mathematical calculations based on the algorithms suggested on http://stackoverflow.com/questions/19106556/get-location-address-w-r-t-the-polygon-i-am-in/19109375#19109375
