### ISSUE TITLE
How to show enable location dialog like Google maps?

### ISSUE THREAD

**Issue by githubkyo** [mapsplugin/cordova-plugin-googlemaps#725]
How to show enable location dialog like Google maps?

like this

http://uzzai.com/ZB46BRN5/google-play-services-locationservicesapi-new-option-%E2%80%9Cnever%E2%80%9D.html

**Comment by Richacinas** [comment]
First:

   cordova plugin add cordova-plugin-dialogs

Then:

    cordova.plugins.diagnostic.isLocationEnabledSetting(function(enabled){
                  cordova.plugins.diagnostic.switchToSettings(function(){
                      console.log("Successfully switched to Settings app");
                  }, function(error){
                      console.error("The following error occurred: "+error);
                  });
                  var cleanUpFunc = $document.$on("resume", function(){
                      cordova.plugins.diagnostic.isLocationEnabledSetting(function(enabled){
                          
                          if(enabled==1){
                              window.location.reload();
                          }else{

                              //Show layer giving information
                          }
                      })

                  }, false);
                  

              }, function(error){
                  console.log("Error: " + error);
              });

This can only be done with this plugin or something similar.

I hope it helps

**Comment by githubkyo** [comment]
Thank  you.  any other suggestions?

**Comment by Hirbod** [comment]
No, the only way.
