### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by kountouretis** [mapsplugin/cordova-plugin-googlemaps#726]
Can i use this plugin offline even that there is no wifi singnal?

**Comment by johnrobertcobbold** [comment]
yes

**Comment by polymorp** [comment]
Yes, as long as it has been used with a data connection at some point so it has some data you should see something.

**Comment by kountouretis** [comment]
Sorry about my previous question, i was not clear. My question is if i can use this plugin offline without any connection to the internet before and add points with x,y that i have also save in sqlite table

**Comment by Hirbod** [comment]
No you can't, the map would not load
