### ISSUE TITLE
How do I reuse a map in multiple map divs? 

### ISSUE THREAD

**Issue by prashantghimire** [mapsplugin/cordova-plugin-googlemaps#728]
I'm aware that the plugin throws a singleton map. But what I want to do is use the same map for two different views in my ionic project. I want to clear the map when the user switches between the views to make it appear like a new map. I tried using : var map = `plugin.google.maps.Map.getMap( )` and `map.setDiv('map_canvas1')` and `map.setDiv('map_canvas2')` but was unable to achieve the functionality. Is it something that's possible ? Any help would be appreciated.

**Comment by Hirbod** [comment]
Please check this demo-code
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/432

**Comment by prashantghimire** [comment]
Thank you @Hirbod. Just wanted to let you know that I was facing the problem because ionic uses angular  ja which doesnot refresh the page on tabs switch. This means that the controller which has the code to load the map did not execute everytime on switching the page. I created buttons like the one on #432 and it works now. Thank you again!

**Comment by Hirbod** [comment]
Hi, I understand. Had some of this persistent swtiching problems also on OnsenUI. But I'm sure that Ionic has some events (tabChanged or similar) like OnsenUI has. I'm also listening to this events to reattach my map (which I hide for memory-reasons when not visible)
