### ISSUE TITLE
Not compatible with iAds plugin

### ISSUE THREAD

**Issue by kubofonista** [mapsplugin/cordova-plugin-googlemaps#729]
Hi,

I'm going to use this plugin with cordova-iad-pro.
However, when iAds is loaded, then maps going upper than it should and left free space on bottom.
On this picture I have loaded Safari inspector and marked map canvas - it is okay but map are going before it.
RefreshLayout and even map remove and recreate didn't working.

http://qba.wtf/image/221o1V3M2y12

**Comment by Hirbod** [comment]
Sorry, I can't support every incompatibillity with other plugins, but I guess you should be able to patch this easy.

Have a look here, (initWithFrame). Patch GoogleMaps.m and append some more pixels (you need to figure out how much pixels are missing)
