### ISSUE TITLE
How i can create custom InfoWindow?

### ISSUE THREAD

**Issue by olaferlandsen** [mapsplugin/cordova-plugin-googlemaps#730]
Hi everyone, well, i try edit infoWindow with 'styles' key in "Marker" Class, but this dont work for me... only accept text styles...

So, i want create my own infoWindow like to this example:
http://gmaps-samples-v3.googlecode.com/svn/trunk/infowindow_custom/infowindow-custom.html

Have a idea to implement it?

Thanks

**Comment by Hirbod** [comment]
Not possible, sorry. Only chance is to add the window als base64 encoded canvas
