### ISSUE TITLE
Native Page Transitions plugin incompatibility in Crosswalk environment 

### ISSUE THREAD

**Issue by onnoll** [mapsplugin/cordova-plugin-googlemaps#732]
Hello there,

I've tried this plugin works with Cordova Native Page Transitions plugin using Crosswalk 14+ and Ionic as the doc says. The GoogleMaps plugin works fine but when I try to add NativePageTransitions these don't work properly.

I think the cause is the ANIMATABLE_XWALK_VIEW value of Crosswalk. The NativePageTransitions requires set this value to TRUE and GoogleMaps requires the opposite.

It would be great if these two fantastic plugins could work together. Any suggestion? Why is ANIMATABLE_XWALK_VIEW required to FALSE?

**Comment by Hirbod** [comment]
I don't know why it has to be. Did you try with TRUE? Will GMaps work? The suggestions came directly from Crosswalk, they helped us with the tutorial.

**Comment by Hirbod** [comment]
I just tried Crosswalk 15+ without the ANIMBATABLE_XWALK_VIEW at all (did not even implement the line that was suggested.) Worked perfectly for me. So I don't see any reason for it. Maybe that behaviour was madatory before, but right now (really, I just tested 2 min on my default application) it's not important anymore. Works fine!

**Comment by Hirbod** [comment]
I've just read the native transition plugins' documents, they say

```
Crosswalk
Since Crosswalk's 1.3.0 release (Aug 28, 2015) ANIMATABLE_XWALK_VIEW has been set to false.
This likely interferes with this plugin, so add this to your config.xml: 
<preference name="CrosswalkAnimatable" value="true" /> 
```

**Comment by Hirbod** [comment]
So, I've just rechecked everything. Looks like our plugin does not care about ANIMATABLE_XWALK_VIEW. No matter if true or false - it will work! So just remove the line from the tutorial, make sure 14+ is installed, activate CrosswalkAnimatiable inside of your config.xml.

But remember: our view is an own view behind the webview, it's no real html content. I'm not sure how it will look with native transitions. If it look worse, consider hiding map during animation.

**Comment by johnrobertcobbold** [comment]
@onnoll did you sort this out ? If so, how ?

@Hirbod, I just began testing on Android, currently on a Samsung Galaxy S4
Using cordova-plugin-crosswalk-webview with xwalkVersion 15+ and NativePageTransitions, this is what I get :

If ANIMATABLE_XWALK_VIEW is set to FALSE, google maps appears fine but the transitions are not working.
If ANIMATABLE_XWALK_VIEW is set to TRUE, transitions are working but the map is entirely black.

**Comment by roblav96** [comment]
Yes this issue still resides. I'm going to have to resort to removing crosswalk sadly 😢

**Comment by sam2x** [comment]
woah, i spent hours to figure out this, I also confirm there is a conflict using these two.  I'm experiencing exactly the same problem, but i'm not using *crosswalk*. I removed lot of plugin before noticing it was reworking correctly when uninstalling cordova-plugin-googlemaps v2.

I think a **recent** commit (re)introduced this bug : 

2.0.0-beta2-20170510-1500 : Was working perfectly with nativepagetransitions
2.0.0-beta2-20170625-1805 : Got a flickering page transition or transitions "stucks" in the previous displaying pages (while it should be current page displayed).

I'm trying to figureout which commit, and which parameters is behind this behaviour.

**Comment by sam2x** [comment]
maybe @wf9a5m75 can 	enlighten us about this.

**Comment by sam2x** [comment]
Solved this! To people who may have the same problem, try this : 

1- Removing google-maps plugin (and all cache files)
2- Removed "native-transitions" (and all cache files source ) : 
```
./platforms/android/build/intermediates/classes/debug/com/telerik/plugins/nativepagetransitions/
./platforms/android/build/intermediates/assets/debug/www/plugins/com.telerik.plugins.nativepagetransitions/
./platforms/android/build/intermediates/sourceFolderJavaResources/debug/com/telerik/plugins/nativepagetransitions/```
3- Reinstall google-maps plugin first
3- Reinstall "native-transitions" then

Looks like you absolutely need to build google-maps first, then nativetranstions. And if you update google-maps you may need to redo these steps.
