### ISSUE TITLE
Map content goes 100% height?

### ISSUE THREAD

**Issue by yeemun** [mapsplugin/cordova-plugin-googlemaps#733]
Hi, just a simple question from me. How to make map goes 100% in height? I know it already stated that 100% in height will not have any effects. But, is there any other way? If I set a specific number in px (e.g 500px), it works, but it might looks smaller in bigger screen? Sorry for my bad english.

**Comment by Hirbod** [comment]
Please ask on StackOverflow. Issues are for issues/bugreports, not general questions!
