### ISSUE TITLE
I cant move canvas map when i scroll(touchmove event)

### ISSUE THREAD

**Issue by olaferlandsen** [mapsplugin/cordova-plugin-googlemaps#734]
I have problems with event "touchmove".
When i scroll (touchmove event), the map not move, so i try using `$('body').bind('touchmove', function(){map.refreshLayout();});`

Example:
![Normal](http://s28.postimg.org/p824e6kz1/full.png)

My problem(when i scroll down[touchmove event]):
![Error](http://s22.postimg.org/5h8dbqjoh/error.png)

I can't resolve it...
My HTML:
```HTML
<html>
    <head>
    ...
    <script>
        var div;
        var map;
        document.addEventListener("deviceready", function(){
            $(document).ready(function(){
                div = document.getElementById("canvas");
                map = plugin.google.maps.Map.getMap(div);
                map.addEventListener(plugin.google.maps.event.MAP_READY, function(){
                    $('body').bind('touchmove', function(){
                        map.refreshLayout();
                    });
                });
            });
        });
</script>
</head>
    <body>
        <div class="container-fluid">
            <div id="canvas"></div>
            <div class="row" id="items">
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
                <div class="col-xs-12">...</div>
            </div>
        </div>
    </body>
</html>
```

So, i need:
![Error](http://s24.postimg.org/548hdaggl/i_want.png)

Thanks
Bye

**Comment by Slavrix** [comment]
<html>
    <head>
    ...
    <script>
        var div;
        var map;
        document.addEventListener("deviceready", function(){
            $(document).ready(function(){
                div = document.getElementById("canvas");
                map = plugin.google.maps.Map.getMap(div);
                map.addEventListener(plugin.google.maps.event.MAP_READY, function(){
                    $('body').bind('touchmove', function(){
                        map.refreshLayout();
                    });
                });
            });
        });
    </script>
    </head>
    <body>
        <div class="container-fluid">
            <div id="canvas">
                <div class="row" id="items">
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                    <div class="col-xs-12">...</div>
                </div>
            </div>
        </div>
    </body>
</html>

also you should make a plunkr or something, make it a bit easier for people to create a solution and test it quickly for you.

**Comment by olaferlandsen** [comment]
Well, i change this plugin for Google Maps Javascript API...

**Comment by Osukarin** [comment]
Hi olaferlandsen, can you resolve with the plugin??
