### ISSUE TITLE
Polyline with symbols on it (arrow)

### ISSUE THREAD

**Issue by Richacinas** [mapsplugin/cordova-plugin-googlemaps#735]
Hi there,

I would like to know if there is a way to attach symbols to a polyline, like in the Google Maps v3 Javascript API examples:

    // Define a symbol using a predefined path (an arrow)
      // supplied by the Google Maps JavaScript API.
      var lineSymbol = {
    path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW
      };

      // Create the polyline and add the symbol via the 'icons' property.
      var line = new google.maps.Polyline({
    path: [{lat: 22.291, lng: 153.027}, {lat: 18.291, lng: 153.027}],
    icons: [{
      icon: lineSymbol,
      offset: '100%'
    }],
    map: map
      });

Thanks a lot!

**Comment by Hirbod** [comment]
Looks like this feature is not available for the native sdk, V3 only.
