### ISSUE TITLE
the footer Shelter that only in iOS

### ISSUE THREAD

**Issue by bau720123** [mapsplugin/cordova-plugin-googlemaps#738]
hi @Hirbod 
I am using 1.3.4 version from npm
Android 4.4.2 and ipad mini iOS 9.1(13B143)

according to this，I use the fullscreen feature
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Windows#6-change-the-wwwindexhtml

in Android，no problem at all
![android](https://cloud.githubusercontent.com/assets/5110085/11205015/42ee9436-8d3f-11e5-84c7-d8477973c40f.jpg)

but in iOS，the footer seem been Shelter (I doubt if is the "statusBar" related problem)
![ios](https://cloud.githubusercontent.com/assets/5110085/11205033/5bafe7ae-8d3f-11e5-88d9-2586c3347b7c.PNG)

**Comment by Hirbod** [comment]
Yeah, for sure. I guess there is some patch required (substracting some pixels from the drawer)

**Comment by Hirbod** [comment]
@bau720123 

Open GoogleMaps.m

Inside of PluginInitilize

search for
```obj-c
self.pluginLayer = [[MyPluginLayer alloc] initWithFrame:self.webView.frame];
```
and replace with

```obj-c
CGRect viewBounds = [self.webView bounds];
viewBounds.origin.y -= 20;
viewBounds.size.height = viewBounds.size.height + 20;
self.pluginLayer = [[MyPluginLayer alloc] initWithFrame:viewBounds];
```

As the normal case is to have the StatusBar overlayed, I will only provide the method "how to patch", but I don't have any current way to detect this automatically. But this will fix the problem for you

**Comment by bau720123** [comment]
thanks @Hirbod 
I will try for this
