### ISSUE TITLE
No map under Crosswalk 15+ 

### ISSUE THREAD

**Issue by lakano** [mapsplugin/cordova-plugin-googlemaps#740]
Hello,

This works inside Crosswalk 14+ ( 14.43.343.17 ) but not with 15+ ( 15.44.384.12 current stable ).
If I don't touch the platform/android/AndroidManifest.xml, I see a black screen, and if I change as requested in Wiki to "Translucent", the black screen is replaced by a screenshot of my Android background photo & icons.

It's not a problem of keys, I can switch from 15+ to 14+ and this works correctly.

Do you have any suggestions to help please? 
Regards

**Comment by lakano** [comment]
Strange things, when the Android Keyboard is opened, the map is show, but not when I close it.

**Comment by fmendoza** [comment]
I confirm this issue

**Comment by fmendoza** [comment]
But in my case, it didn't work neither 15 nor 14

**Comment by fmendoza** [comment]
Now is working with Crosswalk 15. The only change to make this work is to add the following in XWalkWebViewEngine.java
```
webView.setZOrderOnTop(true); 
```

**Comment by vitto32** [comment]
I think it's a preference now (xwalkZOrderOnTop)

**Comment by fmendoza** [comment]
Yes it is. But not available from npm yet. You have to download from master branch

**Comment by lakano** [comment]
@fmendoza : Thanks for the solution, I'll try !
@vitto32 : Could you explain me how to set the preference exactly please ?
( and why the npm package have to be updated? I suppose @fmendoza would mean cordova package?)

**Comment by Hirbod** [comment]
Just add 

```xml
        <preference name="xwalkZOrderOnTop" value="true" />
```
to your config.xml
