### ISSUE TITLE
html content in infowindow

### ISSUE THREAD

**Issue by kamakshi417** [mapsplugin/cordova-plugin-googlemaps#741]
Hi,
Can anybody let me know how to show html content in map info-window.

**Comment by kamakshi417** [comment]
ex: i want show  like "<h1> i am infowindow</h1>"  instead of "i am infowindow" .

**Comment by celron** [comment]
I don't think you can, this plugin implements the native (ios and android) api's in a way that is callable through cordova/phonegap.  Google did not incorporate html content in the [native api's](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.InfoWindowAdapter.html#getInfoContents(com.google.android.gms.maps.model.Marker)).  

I think that the authors have implemented some basic styling for the infowindow , however it is not html based.  If you want html content, you will have to add it to this plugin.

**Comment by kamakshi417** [comment]
Thanks Mr.Lee

**Comment by kamakshi417** [comment]
Is it possible to hide infowindow permanently. when we click on marker no need to show infowindow.

**Comment by Hirbod** [comment]
Yes, just do not insert text for the marker
