### ISSUE TITLE
License

### ISSUE THREAD

**Issue by poseydonfba** [mapsplugin/cordova-plugin-googlemaps#742]
Good afternoon,
I would like some help on licenses, ...
I'm developing an app with Cordova, the app can be downloaded free of charge, only some internal features will have some cost.
I had to use this plugin to handle googlemaps, this plugin is under Apache License v2.0.
What it takes to be able to use this plugin with this license?

**Comment by Hirbod** [comment]
Will change Licencs to MIT soon. Just grab it!

**Comment by Hirbod** [comment]
changed to MIT

**Comment by Hirbod** [comment]
Sorry, changed back to APACHE LICENSE. Just use the plugin.
Apache License v2 is enough to modify and redistribute the library by another person.
