### ISSUE TITLE
Map is getting out of the wrapper div scope when scrolling the page

### ISSUE THREAD

**Issue by hazem-tamimi** [mapsplugin/cordova-plugin-googlemaps#744]
Hello,
I’m facing a problem with the maps when I scroll the page to the bottom. The map is not showing within the specified div for it. After few tests, I’ve realized that when I scroll only from inside the specified div for map (which is currently empty), the map starts coming from the bottom scrolling under HTML. When I scroll my app (the normal page), map is not moving and HTML moves above it. I’m using the maps with Cordova 5.3.3, Android platform 4.1.1, and latest maps plugin (1.3.4). Issue is showing on Android lollipop 5.1.1. I've went through the same scenario on iOS and it seems fine.
Please check the screenshots. Thanks.

![111](https://cloud.githubusercontent.com/assets/2403540/11392214/e45eabd6-9360-11e5-8a7b-feec231d9643.png)
![222](https://cloud.githubusercontent.com/assets/2403540/11392217/e77d2b62-9360-11e5-952d-042a22dee903.png)

**Comment by Hirbod** [comment]
try refreshLayout after scrolling
