### ISSUE TITLE
Map pushed to right

### ISSUE THREAD

**Issue by fmendoza** [mapsplugin/cordova-plugin-googlemaps#747]
Previously i had no problem with this plugin, but now i'm facing a very rare issue. I had debugged remotely and i don't think that any div is causing this. The map container already has width:100% and height:100%... So, any ideas?

<img width="391" alt="captura de pantalla 2015-11-27 a las 11 17 30 p m" src="https://cloud.githubusercontent.com/assets/1320696/11450282/08076154-955f-11e5-87c7-9978ef768281.png">

**Comment by Hirbod** [comment]
not enough information. I can't face any issues like that.

**Comment by fmendoza** [comment]
Well, I use Ionic, in the case of my app, you need to navigate up to three child pages until open the map (I don't know if this can cause this behavior). When the map view is open, the controller create the map, the map load (as you can see), no error is displayed in console, but the result is exactly what you see on the screenshot.

I have tested in Nexus 4, Galaxy S5, Galaxy S3 and several emulators with no luck.

**Comment by Hirbod** [comment]
2 ideas.

1) there could be some kind of translate/translate3D. Use DOM Inspector to find to debug
2) try map.refreshLayout() (just test with a timeout after 3 sec.

**Comment by fmendoza** [comment]
refreshLayout with a timeout works. I just tried in the simulator.

**Comment by Hirbod** [comment]
So just try to call refreshLayout without a timout inside of your MAP_READY function. This should work as a workaround. I guess the map dimensions or something isn't ready soon enough.
