### ISSUE TITLE
Hardware Acceleration for Crosswalk/KitKat

### ISSUE THREAD

**Issue by ballenjr** [mapsplugin/cordova-plugin-googlemaps#748]
So I was using an older version that I had re-enabled acceleration, for all cases(since I am using Crosswalk), that was working fine on KitKat.

Then I updated and it no longer worked on kitkat. As I got digging into it I figured out that it now it only gets enabled for 21 and above. This is appropriate for webview but for crosswalk it does not work on kitkat anymore.

Is there a way to test for crosswalk and the chrome version? I know that it is in the user agent if you can get to it. But honestly it shouldn't really be a concern as long as it is crosswalk. Since it is unlikely that someone would be using an old enough crosswalk to make it an issue these days...

**Comment by Hirbod** [comment]
I've fixed that locally, will push for final 1.3.6

**Comment by Hirbod** [comment]
fixed in master
