### ISSUE TITLE
marker.setInfoWindowAnchor() does nothing

### ISSUE THREAD

**Issue by roblav96** [mapsplugin/cordova-plugin-googlemaps#749]
I'm sure it's something small, but when I do:
```javascript
marker.setInfoWindowAnchor( 200, 10 )
```
Nothing happens. I'm trying to move the info window at the bottom of the marker. Those values in the code above are just random ones. I'm trying to see if I can get it to work.

**Comment by Hirbod** [comment]
I tried, it works well for me..

<img width="624" alt="bildschirmfoto 2015-12-07 um 13 13 25" src="https://cloud.githubusercontent.com/assets/504909/11626611/5d898c9c-9ce4-11e5-89c7-39a31dd90ee0.png">

**Comment by roblav96** [comment]
Hmm. I'll have to try this again. XD

Thank you!
