### ISSUE TITLE
One more workaround is required in Crosswalk tutorial

### ISSUE THREAD

**Issue by Honry** [mapsplugin/cordova-plugin-googlemaps#751]
When I follow up the [Crosswalk tutorial](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-CrossWalk-Webview-Plugin-%28Android%29) to create a simple app, I encounter one issue that the "fullscreen" button always show at the fullscreen page. See below screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/3271201/11555480/8427ad5e-99db-11e5-8991-e57006e7d50f.png)

I figure out this is an issue from Crosswalk and submit a ticket at [XWALK-5869](https://crosswalk-project.org/jira/browse/XWALK-5869), and got response from Crosswalk developer that another workaround should be added for "xwalkZOrderOnTop" preference. See the comment in this ticket.
I've verified the workaround, it works fine.
Anyone can help to add this workaround into the  [Crosswalk tutorial](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-CrossWalk-Webview-Plugin-%28Android%29)?

**Comment by Hirbod** [comment]
Well, I could place a reference for this inside of the tutorial at section "Trouble Shooting"
