### ISSUE TITLE
Blank map and inoperative fullscreen

### ISSUE THREAD

**Issue by Honry** [mapsplugin/cordova-plugin-googlemaps#752]
I follow up the guide https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Mac to create a simple android app, but only see a blank map and an inoperative "fullscreen" button.
See below screenshot:
![screenshot_2015-12-03-16-51-19](https://cloud.githubusercontent.com/assets/3271201/11556029/28060076-99df-11e5-8ced-08fac9044c40.png)

My env:
Cordova CLI 5.4.1
GoogleMap plugin: https://github.com/mapsplugin/cordova-plugin-googlemaps

It works fine with the googlemap plugin from npm.

**Comment by roblav96** [comment]
The master branch is broken :/

**Comment by Honry** [comment]
:sob: What is the main line?

**Comment by roblav96** [comment]
ionic plugin add cordova-plugin-googlemaps

**Comment by Honry** [comment]
Alright, many thanks for your response.

**Comment by Hirbod** [comment]
Master is potentially unstable, but actually should not be broken. I'll check tomorrow.
