### ISSUE TITLE
Uncaught TypeError when backgroundColor not set (setOptions() and getMap())

### ISSUE THREAD

**Issue by smcpjames** [mapsplugin/cordova-plugin-googlemaps#753]
Hirbod,

When initializing a map with options, or using setOptions(), the plugin attempts to convert backgroundColor to RGBA. Unfortunately, if backgroundColor isn't set in the options object, the script throws a TypeError, as it would be undefined.

Maybe I missed it somewhere in the documentation, but I don't recall seeing this needs to be set! I started using this plugin with 1.2.5, and came back recently to majorly overhaul an app that's using it. In any case, a simple fix would be to add:

    params.backgroundColor = params.backgroundColor || '#ffffff';

on line 282 and line 316 before:

    params.backgroundColor = HTMLColor2RGBA(params.backgroundColor);

and change line 414 from:

    options.backgroundColor = HTMLColor2RGBA(options.backgroundColor);

to:

````
if(options.hasOwnProperty('backgroundColor')) {
    options.backgroundColor = HTMLColor2RGBA(options.backgroundColor);
}
````

Someone may want to use setOptions without (re-)setting a background color.

Thanks for your hard work keeping this plugin alive!

**Comment by Hirbod** [comment]
Hi, thanks a lot. Could you send me a PR for this?

**Comment by smcpjames** [comment]
Sent PR #755.

**Comment by Hirbod** [comment]
merged. Thank you!
