### ISSUE TITLE
Installation: Asking for a password on bitbucket

### ISSUE THREAD

**Issue by pbudner** [mapsplugin/cordova-plugin-googlemaps#758]
Hello everbody,

First of all, great plugin! I just wanted to update my cordova-plugin-googlemaps version but I experienced the following issue during the installation:
`Installing "plugin.google.maps" for ios
Fetching plugin "https://hirbod@bitbucket.org/nightstomp/cordova-plugin-googlemaps-sdk.git" via git clone
Password for 'https://hirbod@bitbucket.org': ______`

Is this correct? If so, is there any password I have to enter?
I have typed the following command to install the plugin:
`cordova plugin add cordova-plugin-googlemaps --variable ...`

Thanks in advance!

**Comment by Hirbod** [comment]
Weird... I've uploaded the SDK to bitbucket because it has a size of 113MB, Githubs max. limit is 100MB.
There is no password. It's public.

Could you try 

`cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps --variable...`instead? I guess, npm is the root problem here with bitbucket..

**Comment by pbudner** [comment]
Thanks for the fast reply. But still the same issue..

`Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps" via git clone
Repository "https://github.com/mapsplugin/cordova-plugin-googlemaps" checked out to git ref "master".
Installing "plugin.google.maps" for ios
Fetching plugin "https://hirbod@bitbucket.org/nightstomp/cordova-plugin-googlemaps-sdk.git" via git clone
Password for 'https://hirbod@bitbucket.org': `

**Comment by Hirbod** [comment]
should be fixed. Both npm and github. Could you try again?

**Comment by pbudner** [comment]
Now I need to create an own Bitbucket account in order to access the repository. But even if I create a Bitbucket account and try to access the repository via a browser i get the following message:
`You do not have access to this repository.
Use the links at the top to get back.`

**Comment by Hirbod** [comment]
Ok, I will have a look whats wrong there.

**Comment by Hirbod** [comment]
Oh... it was set to "private". It should work now!

**Comment by Hirbod** [comment]
can you confirm?

**Comment by pbudner** [comment]
Yap, works like a charm. Thanks a lot!!

**Comment by Hirbod** [comment]
Super! :)
