### ISSUE TITLE
InfoWindow with 'undefined' title shows up on marker click

### ISSUE THREAD

**Issue by pbudner** [mapsplugin/cordova-plugin-googlemaps#759]
Hey,

since I've upgraded to the latest version of cordova-plugin-googlemaps, I have the following issue:
Even if I do not specify any title or text for the marker, the InfoWindow always shows up after clicking on a marker (I do not want to show the standard InfoWindow, but a custom HTML element). Am I missing something?

The content of the marker is `undefined`.

**Comment by Hirbod** [comment]
Could you show me your JS code please? Would like to see how you add the markers.

**Comment by Hirbod** [comment]
Confirmed. I will fix it today (there is already a PR for it)

**Comment by Hirbod** [comment]
Fixed in master
