### ISSUE TITLE
Custom duration for marker.setPosition()

### ISSUE THREAD

**Issue by jskidd3** [mapsplugin/cordova-plugin-googlemaps#76]
Would it be possible to set a custom duration for the `setPosition` animation?

Currently `setPosition` has a linear animation with a duration of roughly 500-1000 milliseconds. I would like it so I could do `setPosition(3000)` or `setPosition({duration: 3000})` so that my markers move to their new position slower than the current speed.

Thanks

**Comment by wf9a5m75** [comment]
@AndreVicenteW That plugin is for Google Maps JavaScript API v3, not for this plugin.
