### ISSUE TITLE
ploygon not loading in V1.3.8

### ISSUE THREAD

**Issue by bdwilton** [mapsplugin/cordova-plugin-googlemaps#763]
Hello,
I've been testing the plugin V1.3.8 under and have found that Markers and Circles work.  However when I try the documented example for Polygon I get nothing shown.

My test environment is an Ionic test application :- 
Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.8
Ionic App Lib Version: 0.6.4
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X El Capitan
Node Version: v0.12.4
Xcode version: Xcode 7.1.1 Build version 7B1005

plugin:
com.googlemaps.ios 1.11.0 "Google Map iOS SDK for Cordova"
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-whitelist 1.2.0 "Whitelist"
plugin.google.maps 1.3.8 "phonegap-googlemaps-plugin"

**Comment by bdwilton** [comment]
Monitor error log as follows :- 
12-08 16:45:16.061: I/Choreographer(14408): Skipped 31 frames!  The application may be doing too much work on its main thread.
12-08 16:45:16.326: W/System.err(14408): java.lang.reflect.InvocationTargetException
12-08 16:45:16.326: W/System.err(14408): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-08 16:45:16.326: W/System.err(14408): 	at java.lang.reflect.Method.invoke(Method.java:525)
12-08 16:45:16.326: W/System.err(14408): 	at plugin.google.maps.MyPlugin.execute(MyPlugin.java:49)
12-08 16:45:16.326: W/System.err(14408): 	at plugin.google.maps.GoogleMaps$3.run(GoogleMaps.java:262)
12-08 16:45:16.326: W/System.err(14408): 	at android.os.Handler.handleCallback(Handler.java:730)
12-08 16:45:16.326: W/System.err(14408): 	at android.os.Handler.dispatchMessage(Handler.java:92)
12-08 16:45:16.326: W/System.err(14408): 	at android.os.Looper.loop(Looper.java:176)
12-08 16:45:16.326: W/System.err(14408): 	at android.app.ActivityThread.main(ActivityThread.java:5419)
12-08 16:45:16.331: W/System.err(14408): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-08 16:45:16.331: W/System.err(14408): 	at java.lang.reflect.Method.invoke(Method.java:525)
12-08 16:45:16.331: W/System.err(14408): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
12-08 16:45:16.331: W/System.err(14408): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
12-08 16:45:16.331: W/System.err(14408): 	at dalvik.system.NativeStart.main(Native Method)
12-08 16:45:16.331: W/System.err(14408): Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
12-08 16:45:16.336: W/System.err(14408): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
12-08 16:45:16.336: W/System.err(14408): 	at java.util.ArrayList.get(ArrayList.java:308)
12-08 16:45:16.336: W/System.err(14408): 	at com.google.maps.api.android.lib6.d.au.c(Unknown Source)
12-08 16:45:16.336: W/System.err(14408): 	at com.google.maps.api.android.lib6.d.au.<init>(Unknown Source)
12-08 16:45:16.336: W/System.err(14408): 	at com.google.maps.api.android.lib6.d.eu.a(Unknown Source)
12-08 16:45:16.336: W/System.err(14408): 	at com.google.android.gms.maps.internal.j.onTransact(SourceFile:152)
12-08 16:45:16.336: W/System.err(14408): 	at android.os.Binder.transact(Binder.java:347)
12-08 16:45:16.336: W/System.err(14408): 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.addPolygon(Unknown Source)
12-08 16:45:16.336: W/System.err(14408): 	at com.google.android.gms.maps.GoogleMap.addPolygon(Unknown Source)
12-08 16:45:16.336: W/System.err(14408): 	at plugin.google.maps.PluginPolygon.createPolygon(PluginPolygon.java:65)
12-08 16:45:16.336: W/System.err(14408): 	... 13 more
12-08 16:45:16.346: W/System.err(14408): java.lang.reflect.InvocationTargetException
12-08 16:45:16.346: W/System.err(14408): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-08 16:45:16.346: W/System.err(14408): 	at java.lang.reflect.Method.invoke(Method.java:525)
12-08 16:45:16.346: W/System.err(14408): 	at plugin.google.maps.MyPlugin.execute(MyPlugin.java:49)
12-08 16:45:16.346: W/System.err(14408): 	at plugin.google.maps.GoogleMaps$3.run(GoogleMaps.java:262)
12-08 16:45:16.346: W/System.err(14408): 	at android.os.Handler.handleCallback(Handler.java:730)
12-08 16:45:16.346: W/System.err(14408): 	at android.os.Handler.dispatchMessage(Handler.java:92)
12-08 16:45:16.346: W/System.err(14408): 	at android.os.Looper.loop(Looper.java:176)
12-08 16:45:16.351: W/System.err(14408): 	at android.app.ActivityThread.main(ActivityThread.java:5419)
12-08 16:45:16.351: W/System.err(14408): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-08 16:45:16.351: W/System.err(14408): 	at java.lang.reflect.Method.invoke(Method.java:525)
12-08 16:45:16.351: W/System.err(14408): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
12-08 16:45:16.351: W/System.err(14408): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
12-08 16:45:16.351: W/System.err(14408): 	at dalvik.system.NativeStart.main(Native Method)
12-08 16:45:16.351: W/System.err(14408): Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
12-08 16:45:16.351: W/System.err(14408): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
12-08 16:45:16.351: W/System.err(14408): 	at java.util.ArrayList.get(ArrayList.java:308)
12-08 16:45:16.351: W/System.err(14408): 	at com.google.maps.api.android.lib6.d.au.c(Unknown Source)
12-08 16:45:16.351: W/System.err(14408): 	at com.google.maps.api.android.lib6.d.au.<init>(Unknown Source)
12-08 16:45:16.351: W/System.err(14408): 	at com.google.maps.api.android.lib6.d.eu.a(Unknown Source)
12-08 16:45:16.351: W/System.err(14408): 	at com.google.android.gms.maps.internal.j.onTransact(SourceFile:152)
12-08 16:45:16.356: W/System.err(14408): 	at android.os.Binder.transact(Binder.java:347)
12-08 16:45:16.356: W/System.err(14408): 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.addPolygon(Unknown Source)
12-08 16:45:16.356: W/System.err(14408): 	at com.google.android.gms.maps.GoogleMap.addPolygon(Unknown Source)
12-08 16:45:16.356: W/System.err(14408): 	at plugin.google.maps.PluginPolygon.createPolygon(PluginPolygon.java:65)
12-08 16:45:16.356: W/System.err(14408): 	... 13 more
12-08 16:45:16.366: W/PicturePileLayerContent(14408): Warning: painting PicturePile without content!
12-08 16:45:16.366: W/PicturePileLayerContent(14408): Warning: painting PicturePile without content!
12-08 16:45:16.366: W/PicturePileLayerContent(14408): Warning: painting PicturePile without content!
12-08 16:45:16.366: W/PicturePileLayerContent(14408): Warning: painting PicturePile without content!
12-08 16:45:16.366: W/PicturePileLayerContent(14408): Warning: painting PicturePile without content!
12-08 16:45:16.366: W/PicturePileLayerContent(14408): Warning: painting PicturePile without content!
12-08 16:45:16.371: D/WebView(14408): loadUrlImpl: called
12-08 16:45:16.371: D/webcore(14408):  CORE loadUrl: called

**Comment by Hirbod** [comment]
fixed in master

**Comment by bdwilton** [comment]
thanks, will give that a crack.

**Comment by Hirbod** [comment]
Just grab from master, not npm

```bash
$> cordova plugin rm plugin.google.maps
$> cordova plugin rm com.googlemaps.ios #only call this line when not on version 1.11.0
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
```
