### ISSUE TITLE
Map is not shown on clean install

### ISSUE THREAD

**Issue by Mojo90** [mapsplugin/cordova-plugin-googlemaps#765]
Unfortunately I have a new Issue since update to the latest version.

If I do a clean, new install of the App the Map is not shown. It is only shown if I close the App and reopen it again. Then it works as normal.
If I check the divs after opening the new installed App everything is fine (the divs have the Class ```_gmaps_cdv_``` etc. But nothing is shown). Also my log does not printout some error or so.

Any Ideas on this?

Here is my normal initialize Code (just almost similar as in the doc):

```
var mapDiv = document.getElementById("table-stores");
var mapStores = plugin.google.maps.Map.getMap(mapDiv);
mapStores.on(plugin.google.maps.event.MAP_READY, onMapInit);
mapStores.setClickable( true );
```

**Comment by Hirbod** [comment]
Is jQuery installed?

**Comment by Mojo90** [comment]
yes

**Comment by Hirbod** [comment]
(I just want to confirm something)

Please try following inside of your onMapInit

```js
                        setTimeout(function(){
                            $('body').css('background-color', 'rgba(255,255,255,0)');
                        },3000);
```
And if this did not work
```js
                        setTimeout(function(){
                            $('._gmaps_cdv_').css('background-color', 'rgba(255,255,255,0)');
                        },3000);
```

**Comment by Mojo90** [comment]
Sorry indeed there was a problem with overlaying. But I realized just now that it was the tutorial which was still in the back. Tried so much things but now delete tutorial correctly after finishing and now also works for first install 👌🏿

Thank you very much for the thought impulse!

**Comment by Hirbod** [comment]
:+1:
