### ISSUE TITLE
How to check connection to google maps api 

### ISSUE THREAD

**Issue by msio777** [mapsplugin/cordova-plugin-googlemaps#766]
HI,
Is there any function to check if API Key is correct and connection to google maps API can be made ?
Best Regards 
Michal

**Comment by adaniello** [comment]
+1
Also i'ld like it to debug my app: for me mac osx tutorial not works, i get the same result as in #752 and in google developer console i see 0 requests; so i'ld like to know if there's a problem with API key or with service.

**Comment by Hirbod** [comment]
Yes, there is. If you have a grey map with the Google logo visible, the plugin works but your key is wrong. No map (nor Google logo= Other problem)

**Comment by msio777** [comment]
Thanks but how can i check it programmatically ?

**Comment by Hirbod** [comment]
There is no way

**Comment by adaniello** [comment]
@Hirbod i solved my issue simply using version 1.3.4 instead the latest

**Comment by Hirbod** [comment]
Please do not mix up issues. @adaniello

**Comment by adaniello** [comment]
sorry! only to inform you

**Comment by Hirbod** [comment]
Actually in my test cases, the current master works perfectly by the way.
