### ISSUE TITLE
Prevent resizing

### ISSUE THREAD

**Issue by front-stream** [mapsplugin/cordova-plugin-googlemaps#767]
I noticed that after few ms plugin adds 20px to height of my map container. How to prevent this situation?
plugin.google.maps 1.3.8

**Comment by Hirbod** [comment]
I guess you have activated the StatusBar Plugin + overlayswebview.

Open GoogleMaps.m

Inside of 
- (void)pluginInitialize


search for
```obj-c
self.pluginLayer = [[MyPluginLayer alloc] initWithFrame:self.webView.frame];
```
and replace with

```obj-c
CGRect viewBounds = [self.webView bounds];
viewBounds.origin.y -= 20;
viewBounds.size.height = viewBounds.size.height + 20;
self.pluginLayer = [[MyPluginLayer alloc] initWithFrame:viewBounds];
```

As the normal case is to have the StatusBar overlayed, I will only provide the method "how to patch", but I don't have any current way to detect this automatically. But this will fix the problem for you

**Comment by front-stream** [comment]
It didn't fix my problem :( When I applied your patch I have something like this:
<img width="376" alt="ios" src="https://cloud.githubusercontent.com/assets/5076410/11714676/35fa319a-9f3c-11e5-8f3d-ccf1afd8b319.png">
Moreover the height of the map is changing after some time and this fact introduces a short lag...

**Comment by Hirbod** [comment]
Well so revert my patch, cause you have the default StatusBar set. Actually they should be no problems for you. More details please

**Comment by Hirbod** [comment]
The map-div height won't get manipulated trough this plugin. If you have an offset in your camera view, you can call

`map.panBy(x,y);`
eg
`map.panB(0,-20);`

**Comment by front-stream** [comment]
Please look at gif file. After some time map is moving down (20px). How to remove this effect? 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5076410/11715119/b362adb2-9f3f-11e5-9851-523fec111806.gif)

**Comment by Hirbod** [comment]
This is not related to our plugin. I guess something in your framework is wrong (like a toolbar-push in OnsenUI.) I've never faced this problem

**Comment by front-stream** [comment]
ahh, you are right. This issue was related with ionic. thank you!
