### ISSUE TITLE
Help me plz, I use cordova-plugin-googlemaps. problem side menu can't click link. (ionic)

### ISSUE THREAD

**Issue by maxasus123** [mapsplugin/cordova-plugin-googlemaps#768]
Help me plz, I use cordova-plugin-googlemaps. problem side menu can't click link. (ionic)
I upload on youtube:
https://www.youtube.com/watch?v=Hbl-8tjHx9I

cordova-plugin-googlemaps ver. 1.3.7
ionic Info
<pre>
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.11
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.2
ios-sim version: 3.1.1
OS: Mac OS X El Capitan
Node Version: v0.12.5
Xcode version: Xcode 7.2 Build version 7C68
</pre>

**Comment by kwiateusz** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map and map.setClickable()

**Comment by maxasus123** [comment]
@kwiateusz  i try already not work.

**Comment by Hirbod** [comment]
It work. map.setClickable(false) inside of your menu open callback (post open). Set to true after post close
