### ISSUE TITLE
Map takes all clicks

### ISSUE THREAD

**Issue by cvaliere** [mapsplugin/cordova-plugin-googlemaps#769]
I recently updated the plugin, and after initializing a map, it takes all clicks, even if I go to another screen.
So my entire app becomes "unclickable".
If I remove your commit 8581b9f045d2dcca25795ab34383fcba61125c0d, it works, like before.

Any idea why ? And what's the point of this commit ?

Thanks for your work anyway

**Comment by Hirbod** [comment]
Hi @cvaliere looks like this monkey patch makes more problems then it solves. It was actually a very quick and dirty patch for a splashscreen-problem - but I need to find another way. The master does not include this dirty patch anymore.
