### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by AndreyEkb** [mapsplugin/cordova-plugin-googlemaps#772]
Hello!

I try to launch on galaxy s5.
Map not showing.

![screenshot_2015-12-12-13-15-43](https://cloud.githubusercontent.com/assets/7191525/11764013/ff27f334-a141-11e5-97bc-97b5d679a18f.png)

Code: 
document.addEventListener("deviceready", function() {
    var mapDiv = document.getElementById("map_canvas");
    var map = plugin.google.maps.Map.getMap(mapDiv);
    map.on(plugin.google.maps.event.MAP_READY, onMapInit);
});

I did use chrome debugger and noticed next things:
 1. After .getMap(mapDiv) classes(_gmaps_cdv_) and styles(background: rgba(0.0.0.0)) are created, but then they erasing
 2. If I run code by manually in console, then map is shown

I'm using cordova 5.4.1

**Comment by adaniello** [comment]
I had same problem with same version of cordova. Solved using version 1.3.4 of plugin instead of the last.

**Comment by Hirbod** [comment]
I guess I know what's going on. I made a monkey patch but it looks like it makes more problems

**Comment by Hirbod** [comment]
Could you guys try the master branch and tell me, if the bug is gone?

**Comment by FmeuMan** [comment]
Tested on a Moto 4G (android 4.4.4) with cordova 5.3.3 & 5.4.1.
 * Without commit 8c948a245359d1f0e05dc9ab3b11c8dd8ad12a3a the map is blank
 * With commit 8c948a245359d1f0e05dc9ab3b11c8dd8ad12a3a the map show up normally

I ran into similar issues last day and i used this kind of workaround :
```
var _isAvailable;
function isNativaMapAvailable(callback) {
    if(_isAvailable !== undefined) {
        callback(_isAvailable);
    }
    else {
        plugin.google.maps.Map.isAvailable(function(available) {
            var map = plugin.google.maps.Map.getMap();
            map.addEventListener(plugin.google.maps.event.MAP_READY, function(map) {
                map.remove();
               _isAvailable = available;
                setTimeout(function() {
                    callback(_isAvailable);
                }, 500);
            });
        });
    }
}
```
All these brings me to think it is a timing issue. Since the isAvailable function is triggered on deviceready (cf js line 2616), trying to insert a map somewhere else while the tmpmap is being destroyed will not work. I'll have a look around that with #638.

**Comment by Hirbod** [comment]
I would be happy if you find the issue and could provide an fix for this. There are similar issues on iOS with blank maps appearing sometimes

**Comment by Andr3llo** [comment]
With commit 8c948a2 works fine

**Comment by Hirbod** [comment]
As I thought. We will investigate further

**Comment by brahmikumar** [comment]
I am also getting same problem, i commit monkey path, but no use getting same result.
But map.showDialog(), isAvailable() methods are perfectly working.
Tell me some one how to resolve this issue.

**Comment by mogiman** [comment]
Hi...PhilHannent, API key location #781, made a comment that this plugin was good a some hours ago.

**Comment by mogiman** [comment]
So I assumed that the bug had been fixed, however
i down loaded the latest zip file and installed it, I am still get a blank map screen with showDialog.
I am using and Alcatel Android smartphone with android 4.2.2.

**Comment by Hirbod** [comment]
Don't use NPM. It's broken. You need to grab the master version. They is a PR for this, as soon as I had time to evaluate, I will fix it

**Comment by mogiman** [comment]
HI Hirbod
Thanks for letting me know.
Mok 

    On Monday, 21 December 2015 3:26 AM, Hirbod <notifications@github.com> wrote:
 

 Closed #772.—

**Comment by castrojr913** [comment]
The same thing on iOS9. The API Key is well.

**Comment by wf9a5m75** [comment]
Use the master branch for Cordova-ios4

**Comment by castrojr913** [comment]
@wf9a5m75 Thank you. I updated Cordova for ios version 4.0.0 and it worked. The commands were the following:

```
sudo cordova platform update ios@4.0.0
sudo cordova plugin add https://github.com/apache/cordova-plugin-wkwebview-engine.git#1.0.0
```

For more information [here](https://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html).
