### ISSUE TITLE
New argument for addKmlOverlay: suppressInfoWindows

### ISSUE THREAD

**Issue by adaniello** [mapsplugin/cordova-plugin-googlemaps#774]
This is a little improvement, based on the corresponding argument used for Google Maps Javascript: as defined in https://developers.google.com/maps/documentation/javascript/kmllayer, i think that the argument "suppressInfoWindows" could be very useful  because actually addKmlOverlay method opens always an infoWindow on markers, but sometime developer wants no infoWindow (or wants to show data in another container, eg a modal).
What do you think about?
By seeing the code, maybe seems not very hard to do.

**Comment by Hirbod** [comment]
This is only available for the JS-SDK. I'm sorry.

**Comment by adaniello** [comment]
@Hirbod, i know it but i think that this argument could be useful.
I thinked also that perhaps something could be done about this in code where

`overlay.on(plugin.google.maps.event.MARKER_CLICK, function() {
            kmlLayer.trigger(plugin.google.maps.event.OVERLAY_CLICK, overlay, overlay.getPosition());
});`

Thanks

**Comment by Hirbod** [comment]
When you have a solution, please provide a PR. My time is absolutley limited at the moment.

**Comment by adaniello** [comment]
Ok, thanks
