### ISSUE TITLE
Added HTMLElement on top of map is always null

### ISSUE THREAD

**Issue by Mojo90** [mapsplugin/cordova-plugin-googlemaps#777]
According to this: https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#put-html-elements-on-the-map we can always add HTMLElements on top of the map. I did this by javscript, the HTMLElement is also shown and I can do with it whatever I want to but if I check if the Element exists it says always "no" --> I always checking like this:
 ```
if(document.getElementById("ID")){
    //exist
}
else{
    //doesn't exist
}
 ```

So it print out always "null" for my added Element even if it definetely added to dom and the map. The Plugin also adds a property to the Element: __plugindomid="pgm787853408411". And I am not sure if this has to to with it that it is not "in normal DOM Tree" or so...

Any help appreciated, because I sometimes need to check if it is existent or not and according to this do sth...

**Comment by Hirbod** [comment]
Could you add a class instead and check if that works for you? I'm on the phone now, could be possible that the id get's overwritten

**Comment by Mojo90** [comment]
added a class and checked with ```document.getElementsByClassName("classname").length``` and it prints out ```0``` all the time. In Web Inspector I can see the element with ID, Class etc. perfectly. But as mentioned before not sure if the plugin does sth. that the element cannnot be recognized anymore.
But the weird thing is: I can even style or remove the element with ```document.getElementById("ID").style.color = "red"```etc. But just before this styling line the console tells me that the element does not exist (```console.log(document.getElementById("ID"))```)

**Comment by Hirbod** [comment]
The only thing I could imagine right now is, that you try to look for that element before the DOM is loaded (eg. deviceready or window.onload)

**Comment by Mojo90** [comment]
mh no not really. I fixed it with a boolean value, not beautiful but it works. Better is of course checking if element is added to DOM but somehow it does not work for me with the map. Very weird though...

**Comment by Hirbod** [comment]
I tried with document.getElementByid, getElementsByClassName, querySelector and querySelectorAll + sizzle (jQuery-Engine) - it works as expected.
