### ISSUE TITLE
Difficult to follow the guide for obtain the Google Maps API Key

### ISSUE THREAD

**Issue by haoxli** [mapsplugin/cordova-plugin-googlemaps#780]
Now https://code.google.com/apis/console/ has been updated to new version. The guide for obtain the Google Maps API Key is out of date, it will be difficult to use by the user who not fimilar with google developer console.

![google developer console](https://cloud.githubusercontent.com/assets/3271257/11834501/0afcbc08-a408-11e5-9af8-524254a64de0.png)

**Comment by masashiGMS** [comment]
https://developers.google.com/maps/documentation/android-api/signup?hl=en#display_your_apps_certificate_information

**Comment by haoxli** [comment]
thanks, i will follow the google guide.
