### ISSUE TITLE
API key location

### ISSUE THREAD

**Issue by PhilHannent** [mapsplugin/cordova-plugin-googlemaps#781]
Hi,

Firstly thank you for a great plugin.

I have a bit of an issue with the configuration of the plugin. I don't have my plugins or platforms folders within version control. I like that I am only version controlling files I actually develop. This means that all the configuration data has to live within the project.json file and the config.xml files.

The problem I have is that this plugin appears to be storing the Google API key in a non-standard location of android.json, fetch.json and ios.json within the plugins folder. Rather than the expected config.xml folder.

Am I missing something, can the Google API keys be stored in the config.xml instead?

Many thanks
Phil

**Comment by Hirbod** [comment]
I'm sorry, due to lack of time, I can't provide any other way atm. If you have time to provide a clean way how to store the keys inside of config.xml, you're free to submit a PR.
