### ISSUE TITLE
Installing plugin with "cordova prepare android" after "cordova plugin save"

### ISSUE THREAD

**Issue by edolix** [mapsplugin/cordova-plugin-googlemaps#782]
Hello!

When i save all installed plugins with:
```
cordova plugin save
```
or install with ```--save``` flag in ```config.xml``` i see "plugin.google.maps" plugin instead of "cordova-plugin-googlemaps". 

When i use
```
cordova prepare
```
to re-install all plugins, cordova does not install "cordova-plugin-googlemaps" but "plugin.google.maps" from another repo.

I think the problem is derived by attribute ID of tag "plugin" in ```plugin.xml``` file.

Thanks a lot for this great gmaps plugin!

**Comment by Hirbod** [comment]
Yeah, we need to submit a PR to the redirection-repo, to prevent this.

**Comment by Hirbod** [comment]
I send a PR to https://github.com/stevengill/cordova-registry-mapper/pull/65 - as soon as they merge my PR, it will be fixed

**Comment by stevengill** [comment]
I'll merge it in, but the better solution is to have `plugin.id` in `plugin.xml` be the same as the package name in package.json. I'd change `id` to `cordova-plugin-googlemaps` in `plugin.xml`
