### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by front-stream** [mapsplugin/cordova-plugin-googlemaps#783]
Map works like a charm on development mode. When I built project (http://ionicframework.com/docs/guide/publishing.html) and uploaded to phone then I see only Google logo. How can I solve this problem? What I made wrong? 

![74099729745861 we65d3lrrjpvnxotizca_height640](https://cloud.githubusercontent.com/assets/5076410/11847015/a4babf58-a41b-11e5-8221-bde7534b5eea.png)

plugins:

cordova-plugin-crosswalk-webview 1.4.0 "Crosswalk WebView Engine"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-inappbrowser 1.1.1 "InAppBrowser"
cordova-plugin-media 1.0.1 "Media"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-whitelist 1.2.0 "Whitelist"
plugin.google.maps 1.3.7 "phonegap-googlemaps-plugin"

**Comment by Hirbod** [comment]
Set up Production/ Release hashes

**Comment by adaniello** [comment]
This issue is so well documented by author at https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map
