### ISSUE TITLE
maxWidth not respected when passing image into marker

### ISSUE THREAD

**Issue by FuzzyTree** [mapsplugin/cordova-plugin-googlemaps#785]
The maxWidth is not respected when the passed in image is wider

Changing the following in GoogleMaps.java (around line 1827)

        if (maxWidth > 0) {
          imageView.setMaxWidth(maxWidth);
        }

to

        if (maxWidth > 0) {
          imageView.setMaxWidth(maxWidth);
          imageView.setAdjustViewBounds(true);
        }

resolves the issue for me

**Comment by Hirbod** [comment]
Please provide a PR
