### ISSUE TITLE
Google Map Blank Pages

### ISSUE THREAD

**Issue by karthiki2s** [mapsplugin/cordova-plugin-googlemaps#787]
Dear All,

used the plugin as mentioned but I am getting a blank screen while loading map. Can any one suggest the solution for this issue?

This plugin has been integrated with android environment. and same time I was download the sample .apk file its working fine our device.

Version : 1.3.4

Thanks Advance

**Comment by Hirbod** [comment]
Use Master Version

**Comment by karthiki2s** [comment]
Yes we are using master version only.

**Comment by karthiki2s** [comment]
we are following this way only.

1. cordova create projectname

2 . cd <projectpath > cordova plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"

3. cordova platform add android

4. cordova build android

    var div = document.getElementById("map_canvas");  

	      // Initialize the map view
	      map = plugin.google.maps.Map.getMap(div);  // here getMap uncaught reference : plugin is not defined error
	      // Wait until the map is ready status.
	      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);

**Comment by adaniello** [comment]
Has your map the Google logo? Seems as reported at https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map

But in your steps there is something strange: you should add before platform, then plugin. Follow the well written instructions at https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Mac if you use Mac, or https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Windows if you use Windows.

**Comment by karthiki2s** [comment]
Hi,
Thanks you so much. its working for me. I want one more suggestion and help. Our application environment is ibm-worklight-mobilefirst apps how can i implement this cordova project in my environment. I tried this same cordova plugin only i move to worklight project but i can not able to run an application because i was getting error for "Conversion to Dalvik format failed issues ". Kindly advice me.
