### ISSUE TITLE
GroundOverlay Issue

### ISSUE THREAD

**Issue by maperry2009** [mapsplugin/cordova-plugin-googlemaps#788]
Hi,
  My Android app works perfectly with ground overlays, but when I port it to iOS I have to comment out some of the code in GroundOverlay.m to get it working.

  Any idea what I'm doing wrong or is this a bug?

Javascript:

					map.addGroundOverlay({
					  'url': URL,
					  'bounds': bounds,
					  'opacity': 0.5,
					  'zIndex': 99
					},function(groundOverlay) {
					});

Commented Out To Avoid Issue:

  NSURL *isUrl = [NSURL URLWithString:urlStr];
  //if (!isUrl || !isUrl.scheme || isUrl.host) {
  //  layer.icon = [UIImage imageNamed:urlStr];
  //  [self.mapCtrl.overlayManager setObject:layer.icon forKey: id];
  //  completionHandler(nil);
  //} else {
    dispatch_queue_t gueue = dispatch_queue_create("GoogleMap_createGroundOverlay", NULL);
    dispatch_sync(gueue, ^{
      NSURL *url = [NSURL URLWithString:urlStr];
      NSData *data = [NSData dataWithContentsOfURL:url];
      UIImage *layerImg = [UIImage imageWithData:data];
      layer.icon = layerImg;
      [self.mapCtrl.overlayManager setObject:layerImg forKey: id];
      completionHandler(nil);
    });

  //}

Thanks!

**Comment by Hirbod** [comment]
This is already fixed in master

**Comment by maperry2009** [comment]
Great, I see it now, thank you!!

**Comment by tankhanleng** [comment]
Comment on issue

**Comment by tankhanleng** [comment]
Comment on issue

**Comment by Hirbod** [comment]
What you want to tell us?
