### ISSUE TITLE
marker.SetVisible() app crash!!

### ISSUE THREAD

**Issue by Hoejer** [mapsplugin/cordova-plugin-googlemaps#790]
I'm having a major problem with markers and filtering them. If I add 80+ markers on a map, with a specific icon. Then I have a function that filters the markers, with the marker.SetVisible() function. But suddenly when I try filtering, the whole app crashes. The error only persist on all iPads with iOS 9.2 and iPhone 6 and 6 Plus with iOS 9.2. Anyone experiencing the same problem?  I get no error message and no warnings, and memory has no spikes, it's steady at around 80 mb.

When I add marker it looks like this:

```js
map.addMarker({
                                'position': pos,
                                'icon': icon + '.png',
                                'defaulticon': icon,
                                'size': {
                                    width: 26,
                                    height: 30
                                },
                                'disableAutoPan': true
                            });

When I loop through:
for (var i = 0; i < app.turbineMarkers.length; i++)
        {
            var turbine = app.turbineMarkers[i];
            var turbineStatus = turbine.get('turbineStatus');
            app.setTurbineVisibleState(turbine, statuses, turbineStatus);
        }

setTurbineVisibleState: function(turbine, statuses, turbineStatus)
    {
        if (statuses == undefined || statuses.length == 0) {
            turbine.setVisible(true);
        }
        else
        {
            var containsStatus = $.inArray(turbineStatus, statuses);
            turbine.setVisible(containsStatus >= 0);
        }
    }
```

**Comment by Hirbod** [comment]
Icons have to passed as object since there where some changes. Maybe this is the root of your problem.

Try 

icon: {
  url: ...
}

**Comment by Hoejer** [comment]
It didn't do the trick. The icons load perfectly, but as soon as I start looping the 214 markers, and making a SetVisible(true) or SetVisible(false) the whole app freezes.

**Comment by Hirbod** [comment]
I guess running trough a loop is to memory consuming, as you will fire 200 native calls (which aren't async iirc) - this will cause your ui to block and maybe run out of memory. Please have a look here, how Masashi did that.

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Categorize-your-markers

**Comment by Hirbod** [comment]
@Hoejer 

Please open Marker.m and try to change the setVisible function as following

```obj-c
-(void)setVisible:(CDVInvokedUrlCommand *)command
{

    dispatch_async(dispatch_get_main_queue(), ^{

        NSString *markerKey = [command.arguments objectAtIndex:1];
        GMSMarker *marker = [self.mapCtrl.overlayManager objectForKey:markerKey];
        Boolean isVisible = [[command.arguments objectAtIndex:2] boolValue];

        if (isVisible) {
            marker.map = self.mapCtrl.map;
        } else {
            marker.map = nil;
        }

        dispatch_async( dispatch_get_main_queue(), ^{
            CDVPluginResult* pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
            [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
        });
    });

}
```

or you could also try this

```obj-c
-(void)setVisible:(CDVInvokedUrlCommand *)command
{

    dispatch_async(dispatch_get_main_queue(), ^{

        NSString *markerKey = [command.arguments objectAtIndex:1];
        GMSMarker *marker = [self.mapCtrl.overlayManager objectForKey:markerKey];
        Boolean isVisible = [[command.arguments objectAtIndex:2] boolValue];

        if (isVisible) {
            marker.map = self.mapCtrl.map;
        } else {
            marker.map = nil;
        }
        CDVPluginResult* pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
        [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
       // you could also try to comment out the last 2 lines, CDVPluginResult and [self.]
    });

}
```

I'm quite sure that one of my suggestions should help you. Could you try and tell me if it worked out?

**Comment by celron** [comment]
Hello,
I have been testing with 1.3.9 on iOS and am having a problem with setVisible(false).  The app workse fine, it is not freezing, but I can't get the markers to hide.  Unlike @Hoejer I'm only using 12 markers, I'm not sure if it 's the same issue but will investigate.

setOpacity() works.

**Comment by Hoejer** [comment]
Thank you very much Hirbod, I am currently testing on different Apple devices and different versions of iOS, so I will let you know later today if it's working properly.

**Comment by Hoejer** [comment]
@Hirbod - The first function you suggested makes it better, it can withstand a little more before it freezes. The second function didn't make any difference. But the issue still persist, if the function is fired numerable times the app freezes.

**Comment by Hoejer** [comment]
@Hirbod - My boss needs to know if there will be any solution to this problem soon? Otherwise we will need to build our customers app in a different way.

**Comment by Hirbod** [comment]
You could try to find one and submit a PR. My time is very limited currently - I'm sorry

**Comment by alexislg2** [comment]
Hey. Same problem here. My iPhone6 users report crash I guess this is the reason.
@Hoejer did you succeed to reproduce the bug on emulator? I don't have actual device :(
Did you find a solution to avoid that?

**Comment by atannus** [comment]
I'm also wandering around topics with Marker issues. My use case is adding/removing a large number of markers with custom icons as the user pans the map. Every time the camera moves I need to typically add a few hundred Markers and add a few hundred more.

I have some questions regarding plugin design.

For one, why does the `Map.addMarker()` store marker instances OVERLAYS as well as in MARKERS? `Marker.remove()` removes from MARKERS but not from OVERLAYS, which could cause memory leaks.

Another, would a `Map.addMarkers()` taking an array of `Marker`s perhaps be faster?

I'm also very concerned with performance. I can add/remove hundreds of markers using the default marker, but as soon as I try a custom icon it slows down terribly. Using a remote image is the worst option because we download the image once per marker added. Performance is pathetic, icons show at a rate of a few per second at most. I switched to base64 and it got considerably faster but still much much slower then with the default marker icon.

Is this the proper place for this kind of discussion?
Can someone address these questions, please?

If I can get a primer on these matters I'll send PRs soon.

**Comment by Hoejer** [comment]
@alexislg2 - I have not solved this problem yet. I used the first proposal from Hirbod and changed the Marker.m to which made it a little bit better, but it still crashes, but not as often though.

     -(void)setVisible:(CDVInvokedUrlCommand *)command
    {

        dispatch_async(dispatch_get_main_queue(), ^{

            NSString *markerKey = [command.arguments objectAtIndex:1];
            GMSMarker *marker = [self.mapCtrl.overlayManager objectForKey:markerKey];
            Boolean isVisible = [[command.arguments objectAtIndex:2] boolValue];

            if (isVisible) {
                marker.map = self.mapCtrl.map;
            } else {
                marker.map = nil;
            }

            dispatch_async( dispatch_get_main_queue(), ^{
                CDVPluginResult* pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
                [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
            });
        });

    }

**Comment by alexislg2** [comment]
@Hirbod I think the problem is the same for cirlces.
Could you write me the same lines of code for circle.setVisible ? I'm sorry I never coded Objective C.
Thanks

**Comment by wf9a5m75** [comment]
Could you give me an example project?

**Comment by wf9a5m75** [comment]
@Hoejer Could you share your project code with me?

**Comment by Hoejer** [comment]
@wf9a5m75 - Here is my code.

```
for (var i = 0; i < sites.length; i++)
            {
                var site = sites[i];
                // Remove 0,0
                if (site.Location.Latitude === 0 && site.Location.Longitude === 0)
                {
                    continue;
                }
                var pos = new plugin.google.maps.LatLng(site.Location.Latitude, site.Location.Longitude);

                var marker = map.addMarker({
                    'position': pos,
                    'icon': 'www/img/marker.png',
                    'siteId': site.Id,
                    'size': {
                        width: 32,
                        height: 32
                    },
                    'disableAutoPan': true
                }, markerFunction);

                bounds.extend(pos);
                app.siteMarkers.push(marker);
            }
```

**Comment by Hirbod** [comment]
@Hoejer your crashes only happen, because you're calling methods before all markers are added. You should do following:

- as long as your still adding markers, dont remove, hide, manipulate them. it will lead into crash. As you're going trough a loop, you should know how many markers you have. Use the addMarker callback to save the state, when the last marker was added. (using a counter). Only when "expected markers == $i" -> do visibility stuff.

**Comment by skle** [comment]
This problem occurs with me as well, even with the latest version. After all markers are added, the user can call a filter function that will decide if a maker is visible or not. When I loop through all markers and set the visibility state, it will crash (about 500 markers on the map). My solution is to add a setTimeout when looping through the markers. When adding markers to the map, I added a reference to each marker in the __markers object. See the example code:

```
var __filter = {1:false, 2:true, 3:false};

for (i in __markers)
{
	var bIsVisible = __filter[i];

	setTimeout(function()
	{
		__markers[i].setVisible(bIsVisible);
	}, (i*3));
}
```

I used 3 miliseconds in this example, you can try to lower this in your own projects and test if it works.
