### ISSUE TITLE
Map stays in background behind the view

### ISSUE THREAD

**Issue by loulouDelPays** [mapsplugin/cordova-plugin-googlemaps#791]
Hey, 

I have been using cordova-plugin-googlemaps with ionic framework.

in the version 1.3.7, If I go to the map view, then go back to the previous view, It seems like the map is still in background. All interactions are disabled in the area where the map was displayed.

Plus, when I reload, the app, my current view disappears (that's normal), and I can see the map (it is supposed to be closed).

The probleme is not there in the previous versions (at least it works great using 1.3.4, but this version does not support crosswalk ...).

**Comment by gregavola** [comment]
Also having this problems as well.

**Comment by Hirbod** [comment]
Once the map is created it wil last there till you remove it. It's not html content, it is a native view behind the webview. If you change your view, hide the map or call .remove()  and reinit. If you just want to make it invisible, call setVisible() and setClickable(false).

**Comment by gregavola** [comment]
@Hirbod thanks for the info - however in prior versions, when the view wasn't visible (like an ionic) that had the map on it it would not impact the other views. I assume this changed in 1.3.7?

**Comment by Hirbod** [comment]
Yeah there is a bug in the npm version. You could try GitHub master. I will incorporate some new fixes in the new year which will also fix some other crosswalk / white view relates problems. But I'm pretty sure that the master should fix your problem

**Comment by gregavola** [comment]
@Hirbod sounds good - do you know if there are still issues removing plugins using ```cordova plugin rm```?

**Comment by gregavola** [comment]
@Hirbod this issue is not fixed in 1.3.9 - shall we re-open?

**Comment by Hirbod** [comment]
No, as it is not a plugin bug. You are doing something wrong

**Comment by Hirbod** [comment]
I guess something changed in ionic which will interfere here. On view change, hide map, setClickable false and on return, make it visible again and set setClickeable to true. I handle this the same way

**Comment by gregavola** [comment]
I've tried this and it doesn't appear to work correctly. Is there a way to see if the view is behind the WKWebview?

**Comment by yuripx** [comment]
I am facing the same issue.

My div map is showing behind the view and i am not sure how to fix this.

I've tried set the z-index of the div, but doesn't work, the same with the setClickable and setVisible.

Could someone help me fix this?

**Comment by wf9a5m75** [comment]
@Hirbod You should take care if you reopen this.

**Comment by fmsouza** [comment]
I am building an app with Ionic2 and managed to make the map show up. The problem was what @Hirbod explained:

`Once the map is created it wil last there till you remove it. It's not html content, it is a native view behind the webview.`

So what I did was use the framework's lifecycle to hide my webview content when I was navigation to the view with the map and then display it again when navigating back:

```
export class SearchPage {

    public ionViewWillEnter(): void {
        // Entering in SearchPage, assuring the content will show up
        document.getElementById('search-view').style.display = 'initial';
    }

    public ionViewWillLeave(): void {
        // Going to map view
        document.getElementById('search-view').style.display = 'none';
    }
}
```

`#search-view` is an `<ion-content>` in this case.

```
<ion-content class="search" id="search-view">
...
</ion-content>
```

And my map view has a fullscreen native map inside my `<ion-content>`. And it worked very well in my case. The code is in: https://github.com/fmsouza/ionic
