### ISSUE TITLE
 Failed to fetch plugin

### ISSUE THREAD

**Issue by SKOOKII** [mapsplugin/cordova-plugin-googlemaps#795]
Error: Failed to fetch plugin https://bitbucket.org/nightstomp/cordova-plugin-go
oglemaps-sdk.git via git.

**Comment by SKOOKII** [comment]
Installing "plugin.google.maps" for ios
Fetching plugin "https://bitbucket.org/nightstomp/cordova-plugin-googlemaps-sdk.
git" via git clone
Failed to install 'plugin.google.maps':CordovaError: Failed to fetch plugin http
s://bitbucket.org/nightstomp/cordova-plugin-googlemaps-sdk.git via git.
Either there is a connection problems, or plugin spec is incorrect:
        Error: "git" command line tool is not installed: make sure it is accessi
ble on your PATH.
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cord
ova-lib\src\plugman\fetch.js:88:33
    at _rejected (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_m
odules\q\q.js:797:24)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.
js:823:30
    at Promise.when (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\nod
e_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\Admin\AppData\Roaming\npm\node_
modules\cordova\node_modules\q\q.js:741:41)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.
js:557:44
    at flush (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modul
es\q\q.js:108:17)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Error: Failed to fetch plugin https://bitbucket.org/nightstomp/cordova-plugin-go
oglemaps-sdk.git via git.
Either there is a connection problems, or plugin spec is incorrect:
        Error: "git" command line tool is not installed: make sure it is accessi
ble on your PATH.

**Comment by Hirbod** [comment]
connection problem - temp problem. I can't do anything about that.

**Comment by yascasa** [comment]
hello world 
@Hirbod sorry but is not connection problem 
i get the same problem in ios even i have good internet all other plugins work fine 
except cordova-plugin-googlemaps 
i think problem was with cordova-ios4 so i changed to 3.9.2
but is always stuck in fetching.
i try the master branch but always the same problem
there are any solution please ???
==>sorry for my bad english<==

**Comment by Hirbod** [comment]
Try the Master-branch from github, it's not using bitbucket anymore. Current npm package is old
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L231

**Comment by yascasa** [comment]
Thanks a lot is work .
I use now version 1.4.0--beta with ios is amazing
Send my Thanks to all the groupe, ☺😄

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Wed, Nov 30, 2016 at 4:49 AM +0000, "Hirbod" <notifications@github.com<mailto:notifications@github.com>> wrote:


Try the Master-branch from github, it's not using bitbucket anymore. Current npm package is old
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L231

**Comment by atamjeet11** [comment]
ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE"

i am using that but still proublem
ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID=xxxxxxxxxxx
