### ISSUE TITLE
setOpacity clarification

### ISSUE THREAD

**Issue by celron** [mapsplugin/cordova-plugin-googlemaps#796]
Greetings,
I believe that a change in www/googlemaps-cdv-plugin.js to setOpacity() where you added the lines
````
1358    var m = opacity.match(/^\d{0,2}(?:\.\d{0,2}){0,1}$/);
1359	    if (!m) {
1360	        console.log('opacity value must be int or double');
1361	        return false;
1362	    }
````
in 8e477ccf5b1d7071c170550683ce1e088624f78f
which I believe requires that we use *setOpacity("1.1")* rather than *setOpacity(1.1)*.  Is this the intended change?  The documentation only states that it is alpha but doesn't say what format the value should be in, this would make it different from the javascript libraries.

**Comment by Hirbod** [comment]
you believe or did you try it?

**Comment by celron** [comment]
I actually tried it with 1.3.7 and was getting errors

**Comment by celron** [comment]
When I try with newly 1.3.9 (thanks for that), and commented out the lines regarding opacity in *googlemaps-cdv-plugin.js*, 1361-1365 the app seems to work (I'm still testing).

If I do not comment out the lines I get *opacity.match is not a function* and parts of my app does not work.

**Comment by Hirbod** [comment]
thanks. I checked and fixed this. I just added a check to proof if a value is submitted, removed the .match function.

**Comment by celron** [comment]
setOpacity(0) which works, won't be allowed with the new check.

**Comment by Hirbod** [comment]
Yeah, you're right. Will fix this later
