### ISSUE TITLE
1.3.7 initialization on android does not return

### ISSUE THREAD

**Issue by celron** [mapsplugin/cordova-plugin-googlemaps#797]
I've been doing some initial testing on android with version 1.3.7 of the plugin, which seems to be mostly iOS fixes, however on Android my 
````
  map.on(plugin.google.maps.event.MAP_READY, onMapInit);
````
does not return and when I look at the android logs, I see the following about when the map.on call is made, which I've not seen before.
````
12-24 20:01:21.789: W/System.err(30991): remove failed: ENOENT (No such file or directory) : /data/data/com.loolmaps.Loolmaps/files/event_store_v2_com.loolmaps.Loolmaps
````
Are you familiar with this file at all?  The closest changes that I could see that would affect this is

c681954c16495daa152420b5bbae1f65b0be4402

What was this needed for before?  Is there a change that I need to implement?

**Comment by Hirbod** [comment]
You should update to version 1.3.9 which mostly will fix many bugs for android and improve performance, specially when you use crosswalk (you should if not)
