### ISSUE TITLE
Does this plugin support Cordova Android platform 4.1.1?

### ISSUE THREAD

**Issue by YazeedFares** [mapsplugin/cordova-plugin-googlemaps#798]
We are having issues with cordova android 4.1.1, did anybody tasted it on that version?

The map view scrolls over the content of the HTML and doesn't stick inside the DIV element that should contain it!!

We are using:
- Android 5.1.1
- Cordova Version 5.4.1
- Cordova-Android Version 4.1.1

**Comment by celron** [comment]
Hi, I am using Cordova 5.2 with Cordova Android 4.1.1 and Android 5.1.1 and do not have any problems.  It seems to run fine on other versions of Android as well.

Are you having problems with the sample app, or is this an existing app that you upgraded?  Please provide more details.

**Comment by celron** [comment]
Greeting @YazeedFares , what version of the plugin are you using?

**Comment by YazeedFares** [comment]
Hi Celron,

I am using the latest version of the plugin 

I think there is an issue with lines from 607 to 701 in class  GoogleMaps.java

**Comment by Hirbod** [comment]
Update to 1.3.9. Fixed all problems with android and works pretty well with 4.1.1

**Comment by YazeedFares** [comment]
I am still having the same issue ! 

The map keeps scrolling over the page content and doesn't stick to its container !!
