### ISSUE TITLE
With getMap i can't center map

### ISSUE THREAD

**Issue by andreadompe** [mapsplugin/cordova-plugin-googlemaps#799]
Hello,
i'm trying to use this AMAZING plugin, i would like to center the map in a specific position,
i can see the map but it's not centered and zoommed, if i use 
    maps.LatLng(0, 0)
instead of 
     maps.LatLng(37.422476, -122.08425);
nothing change...
follow my code, what i'm doing wrong
    
            document.addEventListener("deviceready", function () {
            plugin.google.maps.Map.isAvailable(function (isAvailable, message) {

                if (isAvailable) {
                    var mapDiv = document.getElementById("map_canvas");

                    const GOOGLE = new plugin.google.maps.LatLng(37.422476, -122.08425);
                    var map = plugin.google.maps.Map.getMap(mapDiv, {
                        'camera': {
                            'latLng': GOOGLE,
                            'zoom': 17
                        }
                    });
                }
            });
        });
Please help me...

Thanks in advance

Andrea

**Comment by celron** [comment]
try map.setCenter(GOOGLE) and map.setZoom(zoom), they work for me

**Comment by andreadompe** [comment]
Thanks for the answer but nothing changes...
i tried two ways

with MAP_READY event

            var map;
        document.addEventListener("deviceready", function () {
            plugin.google.maps.Map.isAvailable(function (isAvailable, message) {

                if (isAvailable) {
                    var mapDiv = document.getElementById("map_canvas");
                    map = plugin.google.maps.Map.getMap(mapDiv);
                    map.one(plugin.google.maps.event.MAP_READY, onMapInit);
                }
            });
        });

        function onMapInit(map) {
            console.log('onMapInit');
            const GOOGLE = new plugin.google.maps.LatLng(37.422476, -122.08425);
            map.setCenter(GOOGLE);
            map.setZoom(15);
        }

And without the event

            document.addEventListener("deviceready", function () {
                plugin.google.maps.Map.isAvailable(function (isAvailable, message) {

                if (isAvailable) {
                    var mapDiv = document.getElementById("map_canvas");
                    const GOOGLE = new plugin.google.maps.LatLng(37.422476, -122.08425);
                    var map = plugin.google.maps.Map.getMap(mapDiv);
                    map.setCenter(GOOGLE);
                    map.setZoom(15);
                }
            });
        });

Any ideas?

**Comment by celron** [comment]
You have to wait for mapInit to return before you can manipulate the map.

Depending on the platform I sometimes have problems with setCenter and setZoom, you can also try

map.animateCamera({
  'target': GOOGLE,
  'zoom': 18
});

**Comment by celron** [comment]
Did the suggestion work?  What platform are you on iOS or Android?

**Comment by andreadompe** [comment]
Nothing changes...

this is what i did

    var deviceready = function () {
    console.log('deviceready');

    function onMapInit(map) {
        console.info('onMapInit', map);
        const GOOGLE = new plugin.google.maps.LatLng(37.422476, -122.08425);
        map.animateCamera({
        'target': GOOGLE,
        'zoom': 18
        });
    }

    plugin.google.maps.Map.isAvailable(function (isAvailable, message) {

        if (isAvailable) {

            var mapDiv = document.getElementById("map_canvas");
            var map = plugin.google.maps.Map.getMap(mapDiv);
            map.one(plugin.google.maps.event.MAP_READY, onMapInit);
            console.log(map);
        }
    });

    };

and this is the result...

![sh39kw905016_snapshot_2015-12-31_08-32-34](https://cloud.githubusercontent.com/assets/11677749/12062259/18be6084-af99-11e5-870c-0a24f752bd5c.png)

**Comment by andreadompe** [comment]
Ok! i found the problem! With Cordova 5.4.1 i have to use the 
_Github (current master, potentially unstable)_
instead of
_npm (current stable 1.3.7)_

Everything works well!
