### ISSUE TITLE
Black or Transparent Map

### ISSUE THREAD

**Issue by lucas-rds** [mapsplugin/cordova-plugin-googlemaps#802]
Hello,

Same error as https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/740.

I tried :
webView.setZOrderOnTop(true); 
and :
preference name="xwalkZOrderOnTop" value="true" 

Nothing happened.
didn't work neither 15 nor 14.

 Suggestions?
 Thanks.

**Comment by Hirbod** [comment]
Install new plugin on a fresh install and check the updated crosswalk install

**Comment by Hirbod** [comment]
This was def. fixed on 1.3.9
