### ISSUE TITLE
WatchDog (div monitoring) does not work after calling map remove - fix provided

### ISSUE THREAD

**Issue by iori57** [mapsplugin/cordova-plugin-googlemaps#806]
Hello,

When we call remove() of the map plugin, it disables the watchdog (which is correct) but at the same time it also removes all events, including the "keepWatching_changed" event, by calling this.off(). Since this event is only added on load, if you call remove and then later try to use the map plugin again using getmap, everything works but the watchdog is not enabled back.

To fix it, I modified the googlemaps-cdv-plugin.js file with the change below, search for the comment 'Remove all event listeners' and change that part of the code to:

    //Remove all event listeners except 'keepWatching_changed'
    var eventNames = Object.keys(_listeners);
    for (i = 0; i < eventNames.length; i++) {
        eventName = eventNames[i];
        if ( eventName !== 'keepWatching_changed' ) {
            for (var j = 0; j < _listeners[eventName].length; j++) {
                document.removeEventListener(eventName, _listeners[eventName][j].listener);
            }
            delete _listeners[eventName];
        }
    }

Not sure if this is the best way to fix this though.

Let me know if I need to create a pull request.

**Comment by Hirbod** [comment]
Thank you very much. Please provide the PR :)

**Comment by Hirbod** [comment]
I just tested your code, and it also fix some other problems I had in my App. Never thought about that eventlistener. No need to provide a PR, I will add this on my own. Thank you!

**Comment by iori57** [comment]
Cool, glad that it helps! I was scratching my head for a while too when I'm seeing weird problems in my app. Took me a while to trace it :)
