### ISSUE TITLE
Clickable issue

### ISSUE THREAD

**Issue by hripman** [mapsplugin/cordova-plugin-googlemaps#808]
Hi

I use the plugin and it works fine.
But I have one issue. I have a button inside map-canvas with absolute positioning and it's not clickable on galaxy nexus device, android  version 4.2.1

Thank you.

**Comment by Acenth** [comment]
Does it work outside of the canvas using the setClickable call? https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#mapsetclickable

**Comment by hripman** [comment]
Yes, it works using the setClickable(false), but I want use it with map inside map canvas. It works on other devices, but on galaxy nexus doesn't work.
