### ISSUE TITLE
not building with cordova-ios 4.0.1

### ISSUE THREAD

**Issue by bau720123** [mapsplugin/cordova-plugin-googlemaps#809]
all detail right here
https://github.com/dpa99c/cordova-diagnostic-plugin/issues/27
this is why "cordova-plugin-googlemaps" the error occur is

developer should be follow this in iOS@4.0.1
http://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html

and when I use
cordova plugin rm cordova-plugin-googlemaps
it will appear this error
Error: Cannot read property 'buffer' of undefined

**Comment by bau720123** [comment]
hi @Hirbod 
why this become colse ?

**Comment by Hirbod** [comment]
Because it's a known issue and we are already working on it.

**Comment by bau720123** [comment]
OK
thanks @Hirbod 
sorry to bother you
