### ISSUE TITLE
Map not showing using API v3 on iOS

### ISSUE THREAD

**Issue by gianis6** [mapsplugin/cordova-plugin-googlemaps#810]
Hi,

I am trying to use your plugin with the Google Maps API v3.
When I run plugin.google.maps.Map.getMap method the div container turns blank and nothing is showing.
I am using the Cordova-iOS 3.9.2.
Everything works fine, events are dispatched correctly (like the MAP_READY event), from my Google Developer Console I can see the requests coming from my app; however the map is not showing.

Any hints about this bug?
Thanks in advance

**Comment by Hirbod** [comment]
API V3 is JS - I dont now why this should be related to us.
