### ISSUE TITLE
$ionicPopup confirm not work

### ISSUE THREAD

**Issue by faroca** [mapsplugin/cordova-plugin-googlemaps#811]
using the ionic popup the confirm button does not work.

http://stackoverflow.com/questions/32524521/phonegap-googlemaps-plugin-ionicpopup

**Comment by Hirbod** [comment]
Set map.setClickable(false) when you open the pop up and back to true, when you closing

**Comment by faroca** [comment]
Ok, thanks

**Comment by ezabaw** [comment]
This doesn't work for me unless I reenable all control with map.setAllGesturesEnabled(true);
