### ISSUE TITLE
MAP_CLICK event does not change data value

### ISSUE THREAD

**Issue by cihankandis** [mapsplugin/cordova-plugin-googlemaps#812]
When you click/touch on map, onMapClick() function is fired. onMapClick() changes the value of $scope.state from 1 to 2. However, it does not change on UI until I click on the div which shows its value.

//js
$scope.state = 1;
function onMapClick(position)
{$scope.state = 2;}

//html
<div data-tap-disabled="false" ng-click="enableMap()" style="width:100%;height:100%" id="map_canvas">
<div>{{currentState}}</div>
</div>

**Comment by Hirbod** [comment]
$timeout(function(){
  $scope.state = 2;
}, 0);

You should read a bit about angular and how it's digest system work. The map event is fired native and won't update when it isn't invoked trough angular. Calling Angulars timeout will trigger the next digest cycle. Be sure to pass the timeout directive to your Controller. 

By the way, this is not a support forum for general JS questions
