### ISSUE TITLE
Issue #5 Back Button, and map catches touch of panel in front.

### ISSUE THREAD

**Issue by 79137913** [mapsplugin/cordova-plugin-googlemaps#814]
Hello, i have some issues with the backbutton, like mapsplugin/cordova-plugin-googlemaps#5 when i press backbutton on a mapdialog the map plugin closes the whole app. BTW i have already binded the backbutton on my app.I have another issue, when i inicialize a map div it changes the background of my whole app to white, and if i have a panel or something in front of the map when i tap the panel the map catches the tap for itself. some ideas? 

[code.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/95863/code.txt)

**Comment by hripman** [comment]
Hi. You can change map background color https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.setBackgroundColor() . Is the panel inside map div? If not, you should set map.setClickable(false) to catch the panel tap.

**Comment by Hirbod** [comment]
Please read the docs to understand, how this plugin works. I can't confirm backbutton problems. If there is a problem, you could try to find a fix and submit a PR
