### ISSUE TITLE
join("\n") - snippet not working on IOS

### ISSUE THREAD

**Issue by alexmira** [mapsplugin/cordova-plugin-googlemaps#816]
The join("\n") on snippet is not working in ios

i did the join on Title and its working, but not working on snippet

everything works on android

code
-------------
map
									.addMarker({
										'position' : GOOGLE,
										'title' : "" + paroquia + "",
										'snippet' : [ "" + igreja, "" + local,
												"" + hora, "" + obs, "",
												"Mais Informações" ].join("\n"),
										'myMsg' : ""
												+ pertoDeMimMapaMarkers[markerIndice].idlocalculto,
										'markerClick' : function(marker) {
											marker.showInfoWindow();
										},
										'infoClick' : function(marker) {
											showLocalDetails(marker
													.get("myMsg"));
										}
									});
--------------

**Comment by petertenhoor** [comment]
Why is this closed. This issue still exists..
