### ISSUE TITLE
"Displaying the certificate fingerprint" - what, and why?

### ISSUE THREAD

**Issue by toby1kenobi** [mapsplugin/cordova-plugin-googlemaps#817]
Hi there,

  I'm following the Windows tutorial, and can't do/don't understand the step [here](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Windows#user-content-3-displaying-the-certificate-fingerprint), about displaying the certificate fingerprint. It seems like something is missing, like where would debug.keystore have come from (I don't have it)?

  Sorry if this is a really basic question.

Toby

**Comment by toby1kenobi** [comment]
I'm guessing it was not a good question, but could you at least give me a clue...?

**Comment by Hirbod** [comment]
You need to obtain your hashes for Google - the app won't not work. Just do the steps as described.
