### ISSUE TITLE
Support locale language in geocoder module 

### ISSUE THREAD

**Issue by amlan-sw** [mapsplugin/cordova-plugin-googlemaps#819]
Hi Devs,

I'm new in android,java,googlemaps development,
when I use geocode module, currently this plugin 
not support change locale, for android, maybe you
can implement and optimize this patch below to
support change locale in geocoder module.
note: already tested and worked. 

thx 

- MyGeocoder.java line 19:
	
add:
	
	import java.util.Locale;

- MyGeocoder.java line 45:

```java
    Geocoder geocoder = new Geocoder(this.cordova.getActivity());
```

change/patch to:

```java
    String lang = "en_US"; //-- default language
    if(opts.has("locale")){lang = opts.getString("locale");}
    Geocoder geocoder = new Geocoder(this.cordova.getActivity(),new Locale(lang));
```

result:

in javascript code, now we can use locale:

```java
plugin.google.maps.Geocoder.geocode(
	{
		locale: "id",
		position:{lat:mylat,lng:mylng}
	},
	function(results) {
	    var res = results[0].extra.lines.join('\n');
	    //-- res with locale language if availble.

	    //-- do smoething with res
	    //--
	}
);	
```

**Comment by Hirbod** [comment]
Do you have the equivalent for iOS also?

**Comment by amlan-sw** [comment]
sorry, but currently no. my current project currently only spesific to android, and I don't have any development device  for ios

**Comment by wf9a5m75** [comment]
Since GMSGeocoder does not support `locale` feature, this plugin does not adopt your suggestion. But thank you.
