### ISSUE TITLE
color for icons does not work at all 

### ISSUE THREAD

**Issue by jrm0695** [mapsplugin/cordova-plugin-googlemaps#820]
I'm trying to modify the marker color, (if a shop saved in my app is open, it should be displayed green, otherwise, it is red, and I use plenty of other colors to recognize certain types of shops). 
But, it looks like the plugin doesnt understand proprely the colors
when I write "
window.marker = sk.pages.map.themap.addMarker({
					  icon : "rgb(255,255,255)",
					  position : currentPosition,
					  title : "test",
}); 
it display a red marker, when I try with rgb (255,255,254), just to try, it display a yellow marker.... 
Exactly the same problem with #rrggbb version. Color are taken at random?
I also tried to make 3 png images (for 3 colors) and set a custom marker but the the app crashes when I use an url for the icon value........
Anyone has the same problem ?  
thanks :)

**Comment by Hirbod** [comment]
Please set the url like that:

```js
icon: {
   url: 'path/to/file or http:'..
   size: {
     width: 20,
     height: 30
   }
}

**Comment by Hirbod** [comment]
and also:
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#color-icon
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Available-HTML-colors
