### ISSUE TITLE
Reverse Geocoding Not working

### ISSUE THREAD

**Issue by sydCPT** [mapsplugin/cordova-plugin-googlemaps#822]
Hi

I am having issues using reverse geocoding.  All I get back is the error.

I am not sure what to put into 'position', as GOOGLE does nothing and is not very descriptive of what needs to be added there.

All I want to do is enter the latitude and longitude and get back a street address.

Please any help will be appreciated.

**Comment by Hirbod** [comment]
Sorry the documentation is more then enough information basis

**Comment by sydCPT** [comment]
You took the time to comment, but couldn't even be bothered to say what GOOGLE is referring to?

Maybe if the documentation was 'enough information basis', I wouldn't have needed to ask for help?

**Comment by Hirbod** [comment]
I'm tired explaining all the stuff over and over again. GitHub is for bug reports, not a support forum. You could kindly ask on SO - where general questions belong to.

**Comment by sydCPT** [comment]
If you have to continue explaining stuff over and over again, then maybe the documentation isn't thorough enough?

It's fine, I will use another plugin

**Comment by Hirbod** [comment]
No - it's just people are lazy

**Comment by Hirbod** [comment]
Just replace GOOGLE with "my address I want to geocode"..
