### ISSUE TITLE
Google Plugins Error

### ISSUE THREAD

**Issue by explosoft** [mapsplugin/cordova-plugin-googlemaps#824]
Hi,

You really have done a great work. I am trying to implement this plugin in my project using telerik appbuilder VS Extension. You can have a look to it at- http://www.telerik.com/appbuilder/visual-studio-extension

After importing plugin in my project, no issue comes up. But when I run my app it gives me error that plugin is not defined.
Hope you can provide some good suggestion over this
![capture](https://cloud.githubusercontent.com/assets/15373050/12602407/16ff7c64-c4e4-11e5-8120-04102113432a.PNG)
.

**Comment by cvaliere** [comment]
there's a deviceready event fired by cordova when plugins are fully initialized : https://cordova.apache.org/docs/en/latest/cordova/events/events.deviceready.html

maybe try to execute your code after this event is fired ?
