### ISSUE TITLE
Move Camera Position After Geolocation is enabled

### ISSUE THREAD

**Issue by norvinjohn** [mapsplugin/cordova-plugin-googlemaps#825]
Hi,

Thanks for this great plugin!

I just want to ask how can I move the camera to my current location after I tap "Yes" when it ask me to use my location.

```
map.addEventListener(plugin.google.maps.event.MAP_READY, function() {
    map.getMyLocation(function(location) {
        // Move camera to the marker created
  	map.animateCamera({
	    'target': location.latLng,
	    'zoom': 15,
	    'bearing': 140
  	});
    });
});
```

**Comment by Hirbod** [comment]
Looks good for me. Does not work?

**Comment by norvinjohn** [comment]
Hello sir,

It works if my geolocation is already enabled before I navigate to the map.

Is it possible to trigger map.animateCamera() when I tap the "Yes" button?

![screenshot_2016-02-02-22-20-10](https://cloud.githubusercontent.com/assets/6295837/12752029/6ad2d18a-c9fb-11e5-992e-fb64e770a768.png)

Thank you again sir for this great plugin :D

**Comment by Hirbod** [comment]
No it is not. You should use Cordovas geolocation plugin and ask for permission before, if permitted, try to locate its own position. This should be done before using the map functionality. Looks like you have Marshmallow, I did not test with it currently. Maybe there are some changes to be done.

**Comment by Hirbod** [comment]
Concept: https://github.com/fastrde/cordova-plugin-fastrde-checkgps/

Use this plugin to check if GPS is enabled. Will work for iOS and Android. If yes, ask with your own pop up solution and store the result. When user say yes, start a watchLocation or a regular location request with Cordovas Geolocation plugin, which will trigger the native Permission alert. Facebook and Skype do it like that. It will force to double confirm, but will prevent that the user tab no, which would lead into never seeing this pop up again. (Need to be enabled over the settings then, at least on iOS)
