### ISSUE TITLE
cordova-ios@4.0.1 build failing

### ISSUE THREAD

**Issue by prakashsejwani** [mapsplugin/cordova-plugin-googlemaps#834]
Hello,

I'm using the cordova-plugin-googlemaps in my ionic app with cordova-ios@4.0.1
i am unable to build the app since i upgraded from cordova-ios@3.9.2 and the build error i get is as shown in the screenshot below.
the cordova platform is v5.4.1 and ionic v1.2.4.

Pls fix this issue ASAP as my release is stuck due to this issue.
Rest of all the plugins are working fine with cordova-ios@4.0.1

![screen shot 2016-02-01 at 11 39 40 am](https://cloud.githubusercontent.com/assets/31607/12710118/29172f70-c8d9-11e5-955d-a53ff606cf25.png)

**Comment by celron** [comment]
It is clearly stated in the readme

> WARNING
> 
> This plugin is not compatible with Cordova-iOS 4.0.0. WKWebView is not supported. They have been huge changes in the API, and due to lack of time, there is no ETA when this plugin will be compatible. PRs are welcome!!

**Comment by Hirbod** [comment]
Thanks @celron

**Comment by prakashsejwani** [comment]
HI @Hirbod and @celron 

i am not using the WKWebView plugin in my ionic application 
and am still using the default UIWebView with cordova-ios@4.0.1 by default.
Does that mean the cordova-plugin-googlemaps is also incompatible with
UIWebView on cordova-ios@4.0.x?

See my plugins list below
com.cordova.plugins.sms 0.1.7 "Cordova SMS Plugin"
cordova-plugin-camera 2.1.0 "Camera"
cordova-plugin-contacts 2.0.1 "Contacts"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-facebook4 1.4.1 "Facebook Connect"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.2.0 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-sms 1.0.5 "SMS"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.0.10 "SocialSharing"
cordova.plugins.diagnostic 2.3.10 "Diagnostic"
ionic-plugin-keyboard 1.0.8 "Keyboard"
phonegap-plugin-push 1.5.3 "PushPlugin"

**Comment by Hirbod** [comment]
Yes, 4.0 even on stock Webview isnt supported. Cordova iOS 4 does not have any big benefits (just WKWebView). Cordovas API has changed, we did not find time to fix this. There is a PR, but it is still buggy and thus not merged.
