### ISSUE TITLE
how to determine if div already has embedded map?

### ISSUE THREAD

**Issue by djangojack** [mapsplugin/cordova-plugin-googlemaps#838]
Is there an easy way for me to determine whether or not a div already has a map embedded in it?

I have multiple views that require maps, so I constantly re-initialize the map on different divs. Is there a simple solution for this, or do I need to keep track of the active map div it with a service?

**Comment by RegexLLC** [comment]
There is only one map, you cannot create multiple instances, it is an illusion. Checking if the map is initialized will initialize it. You could either hide it and show it, or call .remove() after each use.

' plugin.google.maps.Map.getMap(document.getElementById("map_canvas")).remove() '

**Comment by djangojack** [comment]
Yep, there is only one map, but you can move it from div to div.

My question is whether of not there is a method for determining whether or not a div has an embedded map. There is a setDiv() method. Is there something like getDiv()?

**Comment by RegexLLC** [comment]
only that .getMap method I used above, but like I said without the .remove() it's the same as initializing it originally.

**Comment by RegexLLC** [comment]
I think the best solution is to be sure to clear your map once it's out of sight.
