### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by denkomanceski** [mapsplugin/cordova-plugin-googlemaps#839]
Is there any way to navigate inside the plugin without redirecting to google maps ? Only to follow the route without any voice or other stuff

**Comment by Hirbod** [comment]
Sorry, but no.

**Comment by celron** [comment]
According to Google's [terms of service] (https://developers.google.com/maps/iphone/terms?hl=en) you are not allowed to use their maps to provide turn-by-turn navigation of any form.
However you can use their javascript libraries for [direction services](https://developers.google.com/maps/documentation/directions/) to provide a static route or routes from one point to another.  It will be a bit of a hack but it will work

**Comment by denkomanceski** [comment]
Okay thank you, how about only showing the route between point A and B ? Without navigating or anything ? Is it possible ? If its not is it hard to implement ?

Thanks

**Comment by celron** [comment]
Look at google.maps.directionsService.route()
The only drawback is that you have to have initialized a map using google javascript libraries that is passed to the function.  If you follow the link in my comment above it has demo code and examples of what to expect.
How hard will depend on your abilities

**Comment by sam-lex** [comment]
@denkomanceski sup, it is possible, for only showing the route between point A and B with this plugin, you can do it like this:
1. initialize map etc, normally (v2 - plugin);
2. load the v3 library separately, (you'll have v2 and v3 map js basically) - you'd need to get an JS API key.
3. request the route/directions using the v3 library;
4. from the response, you'll get the route, you'll get an array of points; (inspect the object and find the routes)
5. use the points and draw a polygon in your existing v2 map. (https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Polygon)

This is the only way I've found so far of doing this. I honestly don't know why Google doesn't allow us to use the map to provide turn-by-turn navigation :(, if anyone knows why, please let me know...

For the navigation itself, I'm using the "external service" for now. (https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/External-Service)

**Comment by denkomanceski** [comment]
Thanks, this was the way I thought of at the end but still havent implemented it. Does the polyline look smooth and clear ? Also, did u manage to put custom markers at point A and point B or you are using the default ones

**Comment by sam-lex** [comment]
markers? I haven't tried with custom ones yet, but it should be possible.

The polyline does looks smooth and clear, but not as good as the v3 ones. (The DirectionsRenderer).

Difference:
v3 -> line thickness is somehow "dynamic", it always has the same width as the road (about one way), when zooming, the line thickness zooms together.

v2 -> the opposite, it's fixed, so, if you set for example 2px, it might look Ok for a zoom level of .. 7? 15? (sorry, I don't have the exact values here, and sort of lazy to test and see..), and when you zoom in a lot more, the line "becomes" thin in the road, it continues as 2px.

**Comment by celron** [comment]
Sam-lex's description of using a hybrid javascript v3 and native library v2 will work, I've implemented a version of it in my project.  I don't believe you need a js api key.

Polyline works well though the line thickness does change.  I don't think you can draw a grey dotted line in the native libraries that google maps uses to display the walking portion of a route.

I have implemented custom markers for point A and point B on the map and in the **route description** which is a div that you give to google maps direction services and it populate the div with the route information.  You can also create your own description, and add your own UI elements

Using customer markers on the map is easy since you are doing all the drawing, in the description text that you get from google, you have to do some div manipulation to change them, but it's not hard.

**Comment by FmeuMan** [comment]
I used the google javascript v3 for route requesting too, this works quite well. Additionally using google loader allows to load the google map only when needed.

HTML :
```html
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
```
JS :
```js
google.load('maps', '3', {other_params:'sensor=false', callback: function() {
    new google.maps.DirectionsService().route(routeOptions, function(response, status) {
        if(status === google.maps.DirectionsStatus.OK) {
            /* build the route polyline. The is quite straightforward running through
               response.routes[0].legs[0].steps[ i ].path[ j ].lng/lat()
               see https://developers.google.com/maps/documentation/javascript/reference#DirectionsResult
               and https://developers.google.com/maps/documentation/javascript/reference#DirectionsRoute */
        }
        else {
            /* handle error
               see https://developers.google.com/maps/documentation/javascript/reference#DirectionsStatus */
        }
    });
}});
```
