### ISSUE TITLE
Uncaught TypeError: e.target.getBoundingClientRect is not a function 

### ISSUE THREAD

**Issue by koenoe** [mapsplugin/cordova-plugin-googlemaps#842]
Cordova version: 5.4.1
Ionic CLI version: 1.7.14
Ionic version: 1.2.4

Maps are working fine and both Android or iOS are not crashing, but I see these errors popping up in my log when I tap/drag/zoom the map:

```
Uncaught TypeError: e.target.getBoundingClientRect is not a function
```

Am I doing something wrong in my configuration or is this a known bug? I couldn't find something about it in the issues.

My current code:
```
var latLng = new $window.plugin.google.maps.LatLng(vm.trip.stop_lat, vm.trip.stop_lon);

var mapParams = {
  mapType: $window.plugin.google.maps.MapTypeId.ROADMAP,
  backgroundColor: '#3e3e3e',
  controls: {
    compass: false,
    myLocationButton: false,
    indoorPicker: false
  },
  gestures: {
    scroll: true,
    tilt: true,
    rotate: true,
    zoom: true
  },
  camera: {
    latLng: latLng,
    zoom: 16
  }
};

var mapDiv = document.getElementById('home-map');
var map = $window.plugin.google.maps.Map.getMap(mapDiv, mapParams);

map.on($window.plugin.google.maps.event.MAP_READY, ready);

function ready(map) {
  map.addMarker({
    animation: $window.plugin.google.maps.Animation.DROP,
    position: latLng,
    icon: {
      url: 'www/content/img/map-marker-mini.png',
      size: {
        width: 100,
        height: 40
      }
    }
  }, function(marker) {
  });
}
```

**Comment by wf9a5m75** [comment]
Well, I guess it's depends on your code, because no body people report this issue except you.
Please try to inspect in your code one more time.

**Comment by wf9a5m75** [comment]
@koenoe Since I'm not familiar with ionic, could you provide an example project?

Please create an example app that reproduce your issue, and deploy to github on your repository, then tell me the repository link.
If so, I will check your code.

**Comment by koenoe** [comment]
@wf9a5m75 Thanks for your reply, but I'll close this comment. We switched back to the Javascript SDK since we needed multiple maps anyway.
