### ISSUE TITLE
get center coordinates

### ISSUE THREAD

**Issue by denkomanceski** [mapsplugin/cordova-plugin-googlemaps#843]
Hi,

I am trying to get the coordinates that are in the current center. I tried with getVisibleRegion() but I am not getting the center coordinates, how do I calculate the current center of the map ? this getVisibleRegion() can probably help too..

Thanks

**Comment by celron** [comment]
I've used the camera coordinates with map.getCameraPosition() callback.  With getVisibleRegion, you'd have to take the corners and do some calculations to get the center, though you'd probably have to use some trigonometry functions.

**Comment by denkomanceski** [comment]
Thanks
