### ISSUE TITLE
cordova ver6.0.0 have permission error

### ISSUE THREAD

**Issue by githubkyo** [mapsplugin/cordova-plugin-googlemaps#845]
error like this!

my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION

anybody have any suggest?

![image](https://cloud.githubusercontent.com/assets/11607324/12937919/13221b66-cff1-11e5-9968-aeda802560bb.png)

**Comment by joewoodhouse** [comment]
In Android API 23 and above, it's not longer sufficient just to put the permissions in the Manifest file. You also need to specifically request the permissions from the user and wait for them to respond.

Debatebly this plugin should be updated to do all this. I started doing a PR for it, but then realised a short-cut would be to use the cordova-diagnostic-plugin plugin to requestPermissions()

https://github.com/dpa99c/cordova-diagnostic-plugin#requestruntimepermissions

I've not actually tried this yet but I'll let you know!

**Comment by joewoodhouse** [comment]
It works fine, basically:

```
document.addEventListener('deviceready', function (){
  cordova.plugins.diagnostic.requestRuntimePermissions(function(statuses) {
      var map = plugin.google.maps.Map.getMap(div);
      // ....
    }, function(err) {
      console.log('Permission rejected');
    }, [
    cordova.plugins.diagnostic.runtimePermission.ACCESS_FINE_LOCATION,
    cordova.plugins.diagnostic.runtimePermission.ACCESS_COARSE_LOCATION,
  ]);
}, false);
```

**Comment by joewoodhouse** [comment]
@Hirbod Any thoughts on whether the plugin should handle this? Currently with the plugin at the moment when I try to call map.getMyLocation() without the permissions having been already requested, the app will crash immediately. So I would suggest the plugin probably does need updating.

**Comment by Hirbod** [comment]
Hi @joe - yes, the plugin should handle this. Would you be so kind to provide a PR?

**Comment by githubkyo** [comment]
Hi, @joewoodhouse,  thank you. I will try it.
