### ISSUE TITLE
Geocoder offline

### ISSUE THREAD

**Issue by abellion** [mapsplugin/cordova-plugin-googlemaps#847]
Hey,

When my device is offline the geocoding make the app freeze for about a second, and then the geocoding method callback fire with an empty array.
I guess it's caused by the Google API call which fail.

I found in the Google Geocoding doc a "isPresent()" method which return true or false if the geocoding methods are available. I think this method could resolve this issue.

http://developer.android.com/reference/android/location/Geocoder.html#isPresent()

Thank you !

**Comment by Hirbod** [comment]
Would you like to provide a PR ?

**Comment by wf9a5m75** [comment]
@abellion Thank you for inspecting. I will check this later.

**Comment by wf9a5m75** [comment]
Um, `isPresent()` returns `true` on my device when it is in the Airplane mode.

**Comment by wf9a5m75** [comment]
This is not reproduce issue. This one close at once. If any update, please reopen this.
