### ISSUE TITLE
scrollViewDidScroll - problem

### ISSUE THREAD

**Issue by aesmon** [mapsplugin/cordova-plugin-googlemaps#848]
Cordova-plugin-googlemaps overwrites the scrollViewDidScroll event from a keyboard plugin. Is there any way to make Google Maps use its own separate scrollViewDidScroll ? I don't know Objective C and have been trying to pinpoint the problem for hours now, probably going to take me another day or so to figure out a solution as google doesn't seem to be so helpful :(. If anyone has any ideas I would appreciate it tremendously!

Thanks

**Comment by wf9a5m75** [comment]
`scrollViewDidScroll` is one of important event to control the map position. So it's not sharable with other plugins.
