### ISSUE TITLE
Put HTML elements on map with css animation

### ISSUE THREAD

**Issue by djangojack** [mapsplugin/cordova-plugin-googlemaps#849]
I am putting html elements on the bottom of the map when a user clicks on a marker. Users can then click on the html element and go to a different $state etc.

Everything worked 100% perfectly until I implemented a simple css animation. Now the html elements animate in smoothly, but they are no longer clickable. Clicking on them gets passed through to the map. Yes, I know about sidebars for example and toggling map.setClickable(), but this shouldn't be needed for elements defined in the map div, and it wont work because I want users to be able to click on the html element or another marker on the map.

How can I animate in html elements and still be able to click them?  

```
<style>
  @-webkit-keyframes slideUp {
    0% {
      -webkit-transform: translate3d(0,100%,0);
    }
    100% {
      -webkit-transform: translate3d(0,0,0);
    }
  }
  .slide-up{
     -webkit-animation: slideUp ease-in 1; 
    animation: slideUp ease-in 1;
    -webkit-animation-fill-mode: forwards;
    animation-fill-mode: forwards;
    -webkit-animation-duration: 200ms;
    animation-duration: 200ms;
  }
</style>

<div id="map_canvas">
   <div id="mapItemPreview" ng-if = "showMapBottomImage" class="slide-up" ng-click="foo">
      [images etc]
   </div>
</div>
```

**Comment by Hirbod** [comment]
You need to use ng-show instead of ng-if. Ng-if removes element from DOM and re-add when needed. Therefore, or child watcher won't work anymore

**Comment by djangojack** [comment]
Thanks for the response, but I tried ng-show, and it didn't change anything.

Everything was working 100% perfectly until the css animations were added. Any ideas?

**Comment by Hirbod** [comment]
Actually not. I also have some css animated stuff, which works well. Try WebKit back face visibility or something like that. But ng-if should not work. (But maybe the is will be restored also, that should work then).
