### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by jbmckee** [mapsplugin/cordova-plugin-googlemaps#850]
Android works fine. However, getting build failed error for ios.

The following build commands failed:
	CompileC build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/GoogleMapsViewController.o HelloCordova/Plugins/plugin.google.maps/GoogleMapsViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/GroundOverlay.o HelloCordova/Plugins/plugin.google.maps/GroundOverlay.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

**Comment by jbmckee** [comment]
SOLVED

As the warning says, "This plugin is not compatible with Cordova-iOS 4.0.0."

I downgraded from 4.0.1 to 3.9.0 and now it compiles just fine!

cordova platform rm ios
cordova platform add ios@3.9.0

Sorry, I am very new to app dev.

**Comment by Bloggerschmidt** [comment]
Still the solution. Muah!
