### ISSUE TITLE
Fixed Position HTML Element

### ISSUE THREAD

**Issue by joewoodhouse** [mapsplugin/cordova-plugin-googlemaps#852]
Quick question. I'm wondering if anyone can think of a way of "pinning" an HTML element to a particular position on the map.

So for example when the users clicks on the map, I add some element to that position (using Map. fromLatLngToPoint to get the position on the page to render it). However then when the user moves the map around, I want it to remain pinned to that position (so could potentially scroll in and out of view), rather than moving with the scroll. Basically I want it to behave like a marker, but not be a marker :)

Anyone any ideas? My only thought so far is to listen for the CAMERA_CHANGE events and move the elements position the appropriate amount. But that sounds pretty heavy-weight to me.

**Comment by joewoodhouse** [comment]
FYI I tried my idea above. It works OK on iOS, because CAMERA_CHANGE is raised as the map is dragged. But on Android, it is only fired when the dragging has stopped, meaning that the element jumps from one position to another. So back to the drawing board....

**Comment by joewoodhouse** [comment]
@Hirbod any ideas on this?

**Comment by Hirbod** [comment]
Sorry, I would have the same suggestion as you already figuered out yourself.

Looks like you need to hack around. 
http://stackoverflow.com/questions/14235686/oncamerachangelistener-is-not-responsive-enough-is-there-another-way

**Comment by Hirbod** [comment]
https://code.google.com/p/gmaps-api-issues/issues/detail?id=4636
