### ISSUE TITLE
gms.location

### ISSUE THREAD

**Issue by wolvesworld** [mapsplugin/cordova-plugin-googlemaps#855]
After Installing the Plugin and clean the project , I got the Errors in the GoogleMaps.java File 
Description	Resource	Path	Location	Type
The import com.google.android.gms.location.LocationSettingsRequest cannot be resolved	GoogleMaps.java	/QNDRIVER/src/plugin/google/maps	line 64	Java Problem

**Comment by Hirbod** [comment]
Looks like your missing the android and Google support libs. Please have a look at the documentation and grab everything that's necessary from the sdk manager

**Comment by wolvesworld** [comment]
goolge play service v23 is installed and also i am usig google push notification and other services all are working

**Comment by Hirbod** [comment]
As said, u need to install also android and Google support library

**Comment by wolvesworld** [comment]
As said , Google Play service V23 , and android Support V13 already installed.
