### ISSUE TITLE
Bad image quality with toDataURL()

### ISSUE THREAD

**Issue by troxler** [mapsplugin/cordova-plugin-googlemaps#856]
We are using `toDataURL()` when the map should move similar to #50. However, the generated image is of bad quality. For testing, we removed the following lines in the `toDataURL` method in PluginMap.java:

    float density = Resources.getSystem().getDisplayMetrics().density;
    image = PluginUtil.resizeBitmap(image,
                                    (int)(image.getWidth() / density),
                                    (int)(image.getHeight() / density));

After that change, the generated images looks exactly like it looked on the native map. Is there any way to disable or properly configure that resize without changing the plugin's code?

**Comment by Hirbod** [comment]
You could provide me a PR, I would merge it into main branch

**Comment by cvaliere** [comment]
if I get it well, you remove a resizing step
do you think it can have a positive/negative impact on performance?

**Comment by troxler** [comment]
@Hirbod PR https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/861. It would be awesome if you could make a new version including this change.

@cvaliere Yes that is the only change I did. Creating the image from the canvas will be slightly faster, however, showing the image in the UI might be slightly slower because it has more pixel. In general, its effect on performance should be negligible.

**Comment by Hirbod** [comment]
I'm thinking about a parameter. Instead of making this BC (we don't know how people currently handling the output), we should provide a new method or a parameter

**Comment by troxler** [comment]
Same thing happens on iOS. It can be fixed by replacing

    UIGraphicsBeginImageContext(self.mapCtrl.view.frame.size);

with

    UIGraphicsBeginImageContextWithOptions(self.mapCtrl.view.frame.size, NO, 0.0f);

in the method `toDataURL` in "Map.m".

**Comment by cvaliere** [comment]
hi @troxler 
interested in this feature
could you provide a PR both for iOS and Android, that works with a parameter "uncompressed" as suggested by @Hirbod ?

thanks !

**Comment by troxler** [comment]
@cvaliere Unfortunately, I do not have time for this at the moment. But I guess, this would only be a small change.

**Comment by wf9a5m75** [comment]
I have been checking all issues that are currently filed one by one. Thus, I will check this later. Hold on please.

**Comment by wf9a5m75** [comment]
Do you guys really want to `uncompress` parameter?

**Comment by cvaliere** [comment]
I just want good quality of images
If we can achieve that without downgrading performance, in simply removing the resize, it's ok for me
the "uncompressed" parameter is interesting only if we have to choose between good quality of images or good performance

**Comment by wf9a5m75** [comment]
Ok, the `uncompress` option is available.

You can pass an optional parameter like this:

```js
map.toDataURL({
  uncompress: true
}, function(image) {
   ...
});
```

If you omit the optional parameter, the plugin return **compress (resized)** image.

**Comment by samuelgoldenbaum** [comment]
Thanks guys, had issues with master so grabbed the code from the fix.
