### ISSUE TITLE
iOS setClickable delay

### ISSUE THREAD

**Issue by denkomanceski** [mapsplugin/cordova-plugin-googlemaps#858]
I am testing this plugin on real iOS device (I added platform ios@3.9.0 so the plugin will be compatible). The problem I have is that when i call setClickable(false) on the map I have to wait around 2 seconds for  my UI to become responsive (I am using a sidebar). On android on the other hand it works perfectly. 

The idea is when someone opens the sidebar I am setting the menu to setClickable false, and when they close it i set it to true so the map will be alive. How can I improve this delay so on iOS I will be able to get the same results as on Android ?

Thanks in advance,
I really need to find some solution for this

**Comment by Hirbod** [comment]
Actually there should be no delay, but you could try map.setWatchDogTimer(1) before changing the setClickable and then, map.setWatchDogTimer(false) when you're done.

**Comment by denkomanceski** [comment]
Should I set map.setWatchDogTimer(1) before I am setting setClickable to true or to false ?
and map.setWatchDogTimer(false) when I change to the opposite ? or just do this before and after I use setClickable at all ? I tried setting map.setWatchDogTimer(1) before setClickable to true, and map.setWatchDogTimer(false) before setClickable(false) but I no changes, the delay is still the same :(

**Comment by Hirbod** [comment]
> Should I set map.setWatchDogTimer(1) before I am setting setClickable to true or to false ?
yes
> and map.setWatchDogTimer(false) when I change to the opposite
no, just set it to false, after you changed setClickable() (maybe put in some small delay, like 100ms)

**Comment by Hirbod** [comment]
When you have a look here:

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/GoogleMaps.m#L726

you will see, that there is really no delay or any async task.

Same for the JS-Call
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/googlemaps-cdv-plugin.js#L598

**Comment by Hirbod** [comment]
I just checked function inside of my app and my testapp - no delay at all. It works just as soon as I trigger setClickable true/false. Without changing the watchDog

**Comment by denkomanceski** [comment]
Ye it seems that Ionic 2 has some problem on iOS devices and it delays. I removed the map completely and the delay is still there so it has nothing to do with the map sorry.
