### ISSUE TITLE
Is it possible to disable the link to the google maps app?

### ISSUE THREAD

**Issue by peterhannon** [mapsplugin/cordova-plugin-googlemaps#859]
Can anyone tell me if it is possible (and allowed) to disable the link to the google maps app that appears in the bottom left hand corner of the map please (circled in pink)?

![google-map-link](https://cloud.githubusercontent.com/assets/15670059/13249710/b8357888-da1d-11e5-9e7b-338023e30ff0.png)

We are happy to provide a link to the google maps app, but that link is too easy to click on by accident and several users have got very confused as they had no idea they were swapping to a different app.

Would we be able to put the link in a different part of the screen? And perhaps change it to say "View in google maps app" or similar?

Interestingly, it is a link on ios, but on the android devices we have tested it on, even ones that have the google maps app installed, its just a graphic. 

Thanks in advance :)

**Comment by Hirbod** [comment]
No, it can't be changed (of course you could do with some overlaying/offset hack) but it is not allowed. The difference between iOS and Android is, that Maps is there by default on an Android device, so they don't have to include a link - while on iOS, it is not anymore.
