### ISSUE TITLE
adding Custom Control

### ISSUE THREAD

**Issue by wolvesworld** [mapsplugin/cordova-plugin-googlemaps#860]
Is there any way to embed a custom control or Div inside the Map Layout ? 

I tried to apply direct html code inside the Map div and setting the style  
 #map_canvas  .mycontrols {
            position:absolute;
            bottom: 35px;
            left: 45px;
            width: 75%;
            height: 25px;
            background-color:yellowgreen;
        }

But still not getting the result as I want . 

I am trying to find how to implement the same way of coding 

map.controls[google.maps.ControlPosition.TOP_CENTER].push(mycontrolsDiv);

Any ideas ?

**Comment by masashiGMS** [comment]
Why don't you put your `mycontrolsDiv` on the mapDiv?
This plugin does not provide any way to create a native (android/ios) button into the map layer.
