### ISSUE TITLE
marker icon loaded from base64 image does not work (title using base64 works) (ionic) (discovered crash)

### ISSUE THREAD

**Issue by developez** [mapsplugin/cordova-plugin-googlemaps#863]
When I run the [marker example of the wiki ](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker)("Base64 Encoded Icon" section) the custom icon does not work. However if I use the base64 against the title property it works.

Thus, in the wiki there isn't example with icon, the code is written for 'title' though in the description talks about 'icon'.
**UPDATE:** Documentation is ok (super ok, ultra ok, I am sorry).

I saw in the [release document](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Release-Notes) that in the version 1.2.8 a bug about marker icon was fixed, is that about this? I don't know if this a bug. I am working with Ionic (more details at the bottom of the issue).

Code:

This code creates a marker with image in the title and default red marker (icon; base64image doesn't work).

                var base64image = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAlCAYAAAAjt+tHAAAEcUlEQVRYhbWXTW8bRRjHfzOza6/XTeomJU0jIVlQiaJSIag4FDimChcEypVPwDfgsyBx4cKJcEACRTmjnNoK8VaVUllFVRJK3MRer2ffZjhkN90kfllX4ZFG6/WOn/9vn3me8TzCWgvAnTt3HEACtfzqcL6WAgaIAbO1tZUCCGttIV4DvHzUcgB5TuImB4gBnY94a2srFaurq4W4D8znV4//JwIaCIFefo2Lt/Ry8aXd9bXtcxY+Ycsbm7fzjwZIy6H3d9fXttvtNr7v43neREfWWowxRFFEEARYaxFCIKWk1WrhOCcDqLUmDEM662vbyxubN8mXoZx4HlBJHDgS7vepI7gxf4lPr71JagxfP/qNWIgz80/5LPJMOhytdTEqiRtj6Pf7XJ+7yCevX+dqc44Fr8G9ZztEaQo1d+TvSr6PNYs4zZTt1lpcCx+/9gbvX32VHzp/stn5i07/AFmr0RJ+FTeyIBlrxhiyLMNaS5Zlx98nSYIDXG3O8fBgn69+vUcsBI1mE6UUcRyjlEIIgeM4iBFLUthEgCiKGPb6XPYa6CRBCHClwhdwpbWAFIKDKOZSvYHOUtw0gzTDlYrUxnTjiLnWRer1+ssBANy4vMTnb72LsRZjLTWlkELgCEnL83il4fPFex+ipMSREgHUlcPzSPPl7/fZs9lE/1MB+pFmZxBQV4ooy0jMkcPUGIy1uFLRyFMps5bMGAyW1BiiJMGq8eGfCiCl5PHBAd88+IWP2tfIrCXOc8FiEQiUFPRiebQvYPGUgxKC7x8/5Mmgz8VW6+UBarUafrNJYgy3rqwwX6uTWTPZoZSEScJ3jx7Q8H1cd3RJVgIQQqCUIoxigiRmyW9OdFbYk94hvThCNeoTKwAq1L9SisM4ZncQVBIH2BkEHCYRSqmpcysBRCabCWAvDEiMPfN/8FIAUkqMEHT1sDJAVw9ByanhrwRQ7Gb7OiQ1kxMQIMpSdgfB1B2wMgCA4zjshQEHkZ46d3845J9wUCn8MwE8C0OeV1iGrh6yr4dTy28mANd1CdKkUh48j4aEWXK+EZBSorO04hKEpJZKJVgZQCmFFYK9cDBxXmoMT4M+VopKCVgZAEA5Dk+DHjpNx84Jk4S/+4eVKwBebMUT60sIged57AwCunrIkt88U5KOlPyrQ7qRptFoVNE2BUBaGmitR54LHcfhj+4+n/347USvruuyuLg48pnWxzl0rOnwol3SAGEYAmcPp57nsbKyUuHFRltxLC9uc03jlMTD5Y3N250xjUm73WZhYaGSWLfbpdPpjHyWNyYhpb7A5De9fMJNTrZmEqCzvvYTMBWiEF/e2Pwg/6pIltOtmQZMleb0+Ay/u752d1IkSuK3OJlb45vTKe15cS23b/dHQZTE3ymH+BTA6PZ8kuVgHnAhH/7u+trPZYiS+Nu5eJAPXQiNs6kAYyAuFJEAym8eMIN4ZYAREPM5xF2gWPOAo+SqLD4TwCkIPx+1/FHMUejDWcRnBihBFElZlGpRYvEs4gD/AQLqQbBu0ZQTAAAAAElFTkSuQmCC';

                $rootScope.map.addMarker({
                    'position': pos,
                    'title': base64image,
                    'icon': base64image
                }, function(marker) {
                    marker.showInfoWindow();
                });  

This **CRASH** my application on my Android device:

               var base64image = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAlCAYAAAAjt+tHAAAEcUlEQVRYhbWXTW8bRRjHfzOza6/XTeomJU0jIVlQiaJSIag4FDimChcEypVPwDfgsyBx4cKJcEACRTmjnNoK8VaVUllFVRJK3MRer2ffZjhkN90kfllX4ZFG6/WOn/9vn3me8TzCWgvAnTt3HEACtfzqcL6WAgaIAbO1tZUCCGttIV4DvHzUcgB5TuImB4gBnY94a2srFaurq4W4D8znV4//JwIaCIFefo2Lt/Ry8aXd9bXtcxY+Ycsbm7fzjwZIy6H3d9fXttvtNr7v43neREfWWowxRFFEEARYaxFCIKWk1WrhOCcDqLUmDEM662vbyxubN8mXoZx4HlBJHDgS7vepI7gxf4lPr71JagxfP/qNWIgz80/5LPJMOhytdTEqiRtj6Pf7XJ+7yCevX+dqc44Fr8G9ZztEaQo1d+TvSr6PNYs4zZTt1lpcCx+/9gbvX32VHzp/stn5i07/AFmr0RJ+FTeyIBlrxhiyLMNaS5Zlx98nSYIDXG3O8fBgn69+vUcsBI1mE6UUcRyjlEIIgeM4iBFLUthEgCiKGPb6XPYa6CRBCHClwhdwpbWAFIKDKOZSvYHOUtw0gzTDlYrUxnTjiLnWRer1+ssBANy4vMTnb72LsRZjLTWlkELgCEnL83il4fPFex+ipMSREgHUlcPzSPPl7/fZs9lE/1MB+pFmZxBQV4ooy0jMkcPUGIy1uFLRyFMps5bMGAyW1BiiJMGq8eGfCiCl5PHBAd88+IWP2tfIrCXOc8FiEQiUFPRiebQvYPGUgxKC7x8/5Mmgz8VW6+UBarUafrNJYgy3rqwwX6uTWTPZoZSEScJ3jx7Q8H1cd3RJVgIQQqCUIoxigiRmyW9OdFbYk94hvThCNeoTKwAq1L9SisM4ZncQVBIH2BkEHCYRSqmpcysBRCabCWAvDEiMPfN/8FIAUkqMEHT1sDJAVw9ByanhrwRQ7Gb7OiQ1kxMQIMpSdgfB1B2wMgCA4zjshQEHkZ46d3845J9wUCn8MwE8C0OeV1iGrh6yr4dTy28mANd1CdKkUh48j4aEWXK+EZBSorO04hKEpJZKJVgZQCmFFYK9cDBxXmoMT4M+VopKCVgZAEA5Dk+DHjpNx84Jk4S/+4eVKwBebMUT60sIged57AwCunrIkt88U5KOlPyrQ7qRptFoVNE2BUBaGmitR54LHcfhj+4+n/347USvruuyuLg48pnWxzl0rOnwol3SAGEYAmcPp57nsbKyUuHFRltxLC9uc03jlMTD5Y3N250xjUm73WZhYaGSWLfbpdPpjHyWNyYhpb7A5De9fMJNTrZmEqCzvvYTMBWiEF/e2Pwg/6pIltOtmQZMleb0+Ay/u752d1IkSuK3OJlb45vTKe15cS23b/dHQZTE3ymH+BTA6PZ8kuVgHnAhH/7u+trPZYiS+Nu5eJAPXQiNs6kAYyAuFJEAym8eMIN4ZYAREPM5xF2gWPOAo+SqLD4TwCkIPx+1/FHMUejDWcRnBihBFElZlGpRYvEs4gD/AQLqQbBu0ZQTAAAAAElFTkSuQmCC';

                $rootScope.map.addMarker({
                    'position': pos,
                    'title': base64image,
                    'icon': {
                         url: '/img/test-marker.png'
                     }
                }, function(marker) {
                    marker.showInfoWindow();
                });  

However this `url: 'img/test-marker.png'` does not crash, simply doesn't work (red marker).

Details about installation:

cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID=$ANDROID_KEY$ --variable API_KEY_FOR_IOS=$IOS_KEY$

Version in cordova plugin list: plugin.google.maps 1.3.9 "phonegap-googlemaps-plugin"

**UPDATE:**
Info about my build:

Ionic CLI, 1.7.10
Cordova 5.4.0
plugin.google.maps 1.3.9 (cordova-plugin-googlemaps).

**Comment by Hirbod** [comment]
icon: {
   url: canvas.toDataURL()
}

i will check the wiki, maybe the doc is wrong

**Comment by Hirbod** [comment]
Well the Doc looks good to me - all the examples show cleary that you can't pass string directly to icon, but to the { url: }

**Comment by developez** [comment]
Yes the documentation is ok.

But, look on the documentation:

    var icon = "data:image/png;base64,iVBORw0KGgo...CC";
    ...
    map.addMarker({
        'position': latLng,
        'title': canvas.toDataURL(),
        'icon': icon // <== here
    }, function(marker) {
        marker.showInfoWindow();
    });

`'icon': icon` is the right way (if icon was image base64 string), no 'icon': { url: icon }.

I found a issue where this is dealed and the use is `'icon': icon`.
here: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/547

The problema is that I obtain the default red marker, I don't know why, but with 'title' the base64 Works.

**Comment by Hirbod** [comment]
did you try my suggested way?

**Comment by developez** [comment]
@hitbod no, that neither works, I tried it.

**Comment by celron** [comment]
Just to clarify, from your comment there is no problem if you include ***'title'*** the base64 image works?

In my app I use custom markers everywhere with no problems on both android and ios with 1.3.9. and have no issues with ***'icon'***, but I always have a ***'title'**** for my markers.

**Comment by developez** [comment]
@celron

Yes, my marker has got title.

            var img = new Image();
            img.src = "/img/logos/house.png";
            img.onload = function() {
            
                context.drawImage(img, 0, 0);
                $rootScope.map.addMarker({
                    'position': pos,
                    'title': 'hello5', // 'title': canvas.toDataURL("image/png") WORKS */
                    'icon': canvas.toDataURL()
                }, function(marker) {
                    marker.showInfoWindow();
                });        
            
            };

I am using this plugin with Ionic Framework, I can see the map, I can show a title with image, no problema, the only issue is here in the icon.

**Comment by developez** [comment]
I update the issue to give more details.

**Comment by developez** [comment]
I wonder how can i debug the file android/plugin/google/maps/GoogleMaps.java easily to discover what's going on.

**Comment by developez** [comment]
Ok, I am dealing with this. I am debugging PluginMarker.java, by any reason to the base64 code is added another slash.

`I/GoogleMaps(19456): Creating marker ({"position":{"lat":36.6290511,"lng":-4.5024065},"title":"HELLO7","icon":{"url":"data:image\/\/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAlCAYAAAAjt+tHAAAEcUlEQVRYhbWXTW8bRRjHfzOza6\/XTeomJU0jIVlQiaJSIag4FDimChcEypVPwDfgsyBx4cKJcEACRTmjnNoK8VaVUllFVRJK3MRer2ffZjhkN90kfllX4ZFG6\/WOn\/9vn3me8TzCWgvAnTt3HEACtfzqcL6WAgaIAbO1tZUCCGttIV4DvHzUcgB5TuImB4gBnY94a2srFaurq4W4D8znV4\/\/JwIaCIFefo2Lt\/Ry8aXd9bXtcxY+Ycsbm7fzjwZIy6H3d9fXttvtNr7v43neREfWWowxRFFEEARYaxFCIKWk1WrhOCcDqLUmDEM662vbyxubN8mXoZx4HlBJHDgS7vepI7gxf4lPr71JagxfP\/qNWIgz80\/5LPJMOhytdTEqiRtj6Pf7XJ+7yCevX+dqc44Fr8G9ZztEaQo1d+TvSr6PNYs4zZTt1lpcCx+\/9gbvX32VHzp\/stn5i07\/AFmr0RJ+FTeyIBlrxhiyLMNaS5Zlx98nSYIDXG3O8fBgn69+vUcsBI1mE6UUcRyjlEIIgeM4iBFLUthEgCiKGPb6XPYa6CRBCHClwhdwpbWAFIKDKOZSvYHOUtw0gzTDlYrUxnTjiLnWRer1+ssBANy4vMTnb72LsRZjLTWlkELgCEnL83il4fPFex+ipMSREgHUlcPzSPPl7\/fZs9lE\/1MB+pFmZxBQV4ooy0jMkcPUGIy1uFLRyFMps5bMGAyW1BiiJMGq8eGfCiCl5PHBAd88+IWP2tfIrCXOc8FiEQiUFPRiebQvYPGUgxKC7x8\/5Mmgz8VW6+UBarUafrNJYgy3rqwwX6uTWTPZoZSEScJ3jx7Q8H1cd3RJVgIQQqCUIoxigiRmyW9OdFbYk94hvThCNeoTKwAq1L9SisM4ZncQVBIH2BkEHCYRSqmpcysBRCabCWAvDEiMPfN\/8FIAUkqMEHT1sDJAVw9ByanhrwRQ7Gb7OiQ1kxMQIMpSdgfB1B2wMgCA4zjshQEHkZ46d3845J9wUCn8MwE8C0OeV1iGrh6yr4dTy28mANd1CdKkUh48j4aEWXK+EZBSorO04hKEpJZKJVgZQCmFFYK9cDBxXmoMT4M+VopKCVgZAEA5Dk+DHjpNx84Jk4S\/+4eVKwBebMUT60sIged57AwCunrIkt88U5KOlPyrQ7qRptFoVNE2BUBaGmitR54LHcfhj+4+n\/347USvruuyuLg48pnWxzl0rOnwol3SAGEYAmcPp57nsbKyUuHFRltxLC9uc03jlMTD5Y3N250xjUm73WZhYaGSWLfbpdPpjHyWNyYhpb7A5De9fMJNTrZmEqCzvvYTMBWiEF\/e2Pwg\/6pIltOtmQZMleb0+Ay\/u752d1IkSuK3OJlb45vTKe15cS23b\/dHQZTE3ymH+BTA6PZ8kuVgHnAhH\/7u+trPZYiS+Nu5eJAPXQiNs6kAYyAuFJEAym8eMIN4ZYAREPM5xF2gWPOAo+SqLD4TwCkIPx+1\/FHMUejDWcRnBihBFElZlGpRYvEs4gD\/AQLqQbBu0ZQTAAAAAElFTkSuQmCC"},"anchor":[0.5,0.5],"draggable":false,"visible":true,"flat":false,"rotation":0,"opacity":1,"disableAutoPan":false,"params":{}})

E/GoogleMaps(19456): making bitmap from http

D/skia    (19456): --- SkImageDecoder::Factory returned null

W/System.err(19456): java.lang.IllegalArgumentException: width and height must be > 0

W/System.err(19456): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:841)

W/System.err(19456): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:820)

W/System.err(19456): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:787)

W/System.err(19456): 	at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:101)

W/System.err(19456): 	at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:18)

W/System.err(19456): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)

W/System.err(19456): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

W/System.err(19456): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)

W/System.err(19456): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

W/System.err(19456): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

W/System.err(19456): 	at java.lang.Thread.run(Thread.java:818)`

**Comment by developez** [comment]
Ok, I sent a pull request with this solved (I think), with that change, the icon is shown with base64.

The key is add iconUrl.startsWith("data:image") == false to line 695.

**Comment by wf9a5m75** [comment]
I merged your pull request. Thanks for your help.

**Comment by markygab** [comment]
Hi guys, I'm having the same issue, but on iOS (can't get a base64 image to work as a marker, but it does work on the info window). Looking at the source in Marker.m in the setIcon method, It's clear that it should work with the base64 string in the  icon: {url: xxx} property. Otherwise all the code around the width/height/anchor would be pointless!

**Comment by markygab** [comment]
Hi again - I've found the issue and it was with the "Ionic emulate ios -l". These loads the html and JS from a local web server and thus was appending a "http://" at the beginning of the icon path. My work around was to make up a protocol so this it didn't do this!
e.g. **data://**data:image/png;base64,iVBORw0KGg.....
