### ISSUE TITLE
Sidemenu overlap

### ISSUE THREAD

**Issue by denkomanceski** [mapsplugin/cordova-plugin-googlemaps#867]
![image](https://cloud.githubusercontent.com/assets/10501247/13317460/8861db44-dbb5-11e5-991c-2aa30da9ef4e.jpg)
Guys do you have any idea how to solve this issue ? When I drag the sidemenu back and forth it looks like the map div including all the items wrapped inside are on top of the sidemenu and the map is behind the sidemenu and it looks weird. Even if i open/close the menu programatically it is the same effect

**Comment by Hirbod** [comment]
you can't use a revealing sidebar - only a pushing one (which really pushes the map out).
Overlaying one will not work.

If you're on OnsenUI for example, just change the sidebar from reveal to push. Ionic has something similar

**Comment by raphaeldealmeida** [comment]
How can I fix it on Ionic?

**Comment by wf9a5m75** [comment]
@raphaeldealmeida Read here https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Ionic-Side-Menu-with-the-plugin

**Comment by raphaeldealmeida** [comment]
Great! Its works. 
Please make it visible on the wiki. I couldn't find it there.

Thanks!

**Comment by samuelgoldenbaum** [comment]
But this disables the side menu for the view? Now if you click on the menu icon, the side-menu is expands but is blank?

**Comment by gboiko** [comment]
In my case I didn't do trick with hide/show side bar, instead I just slide menu of the screen.
.menu {
  transform: translateX(-275px);
  -webkit-transition: -webkit-transform 200ms ease;
  transition: transform 200ms ease;
}

.menu-open {
  .menu {
    transform: translateX(0px);
    -webkit-transition: -webkit-transform 200ms ease;
    transition: transform 200ms ease;
  }
}

**Comment by pierreNeck** [comment]
Thanks gboiko, best solucion, it's work very well !

**Comment by tperrelli** [comment]
I simply did this:
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/Ionic-Side-Menu-with-the-plugin/README.md

And added the below code to hide the header. So that i don't need to worry when de user opens the map and click side bar menu, playing around the app navigation.

`<ion-view hide-nav-bar="true">
	<ion-content has-header="false" padding="false" scroll="true">
	  	<div id="map" data-tap-disabled="true"></div>
 	</ion-content>
</ion-view>`
