### ISSUE TITLE
Add config option to disable StatusBar Plugin detection and its +-20px feature

### ISSUE THREAD

**Issue by karolszklarski** [mapsplugin/cordova-plugin-googlemaps#868]
From https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map

> Since plugin version 1.3.3, we will check if the StatusBar Plugin is installed, and substract -20px from the map-height and also move the y-offset by -20px. This will not affect you when you're using StatusBar with default settings, but it will affect you, when you set StatusBar.overlaysWebView(false)

> To fix this 20px white bottom problem, just add 20 extra pixels to your #map_canvas (with jQuery or vanilla js)

Could you add a configuration option to disable checking for StatusBar Plugin and don't activate this -20px feature? In my app I switch between overlaysWebView on and off, depending on current page. Handling this +20px / -20px margin / padding is causing much trouble. It would be nice to be able to turn off this feature.

Thanks :)

**Comment by Hirbod** [comment]
switching between overlaysWebView on and off will not work at all. With or without that config - you will have problems if you change as there is no function currently which will update properly. As far as I can see, the autodetection is not inside anymore. Its a documentation bug
