### ISSUE TITLE
Unable to add custom icon on marker

### ISSUE THREAD

**Issue by Shahroz** [mapsplugin/cordova-plugin-googlemaps#872]
Hi, I'm trying to add custom icon on marker. However I'm following up the documentation and after tried couple of hours, some times map shows it's default icon or sometimes no marker is display on map.
I tried many of these but no one is able to fix for me:
img: {'url': 'img/icon.png'}
img: {url: './img/icon.png'}
img: {url: '../../img/icon.png'}

and also tried base64 encoded image
'icon': {'url': base64Icon}
unfortunately, nothing work for me.

I have a very shot deadline.
Please help me. I'm stuck on it.

**Comment by Slavrix** [comment]
```
map.addMarker({
   icon: {
      url: 'www/img/icon.png',
      size: {
         width: 48,
         height: 48
      }
   },
   title: markerName,
   position: myLatLng,
}, function (marker) {
});
```
thats how i add them

**Comment by Shahroz** [comment]
It didn't work for me

**Comment by Shahroz** [comment]
Sorry It was my fault i didn't put url in addMarker method. It's work now. Thanks
