### ISSUE TITLE
showing route from external service

### ISSUE THREAD

**Issue by iBasit** [mapsplugin/cordova-plugin-googlemaps#873]
https://developers.google.com/maps/documentation/javascript/examples/directions-waypoints

is there a way to combine external service with this package? I'm trying to get route information from external service and display on native map, but its not working

```
var map = plugin.google.maps.Map.getMap(document.getElementById("map"));
var request = {
                origin: {
                    lat: 37.736033,
                    lng: -122.406750
                },
                destination: {
                    lat: 37.787060,
                    lng: -122.389584
                },
                travelMode: google.maps.TravelMode.WALKING
            };

            new google.maps.DirectionsService().route(request, function(response, status)
            {
                if (status == google.maps.DirectionsStatus.OK)
                {
                    alert(response);
                    var route = new google.maps.DirectionsRenderer({suppressMarkers: true});
                    route.setMap(map);
                    route.setDirections(response);
                }
            });

```

**Comment by iBasit** [comment]
solved by


```javascript
var gRoute = response.routes[0]['overview_path'];
for (var s = 0; s < gRoute.length; s++) {
         route.push(new plugin.google.maps.LatLng(gRoute[s].lat(), gRoute[s].lng()));
 }

map.addPolyline({
                        points: route,
                        color : '#0088FF',
                        width: 6
                    });
```

**Comment by luco** [comment]
@iBasit How you included the JS API? I'm getting a little conflict.

**Comment by iBasit** [comment]
JS API or native plugin, they both separate. 

But you need to provide more details, just saying I'm having problem. I won't be able to guide you right solution other then pointing on sky and say solution is there lol

**Comment by luco** [comment]
@iBasit Yep. I'm including the JS API and it's causing conflict. All I can say is this. If I remove the js, works fine.

**Comment by andichaerul** [comment]
hello, can you include a full script example,

because I don't understand

var gRoute = response.routes[0]['overview_path'];
for (var s = 0; s < gRoute.length; s++) {
         route.push(new plugin.google.maps.LatLng(gRoute[s].lat(), gRoute[s].lng()));
 }

map.addPolyline({
                        points: route,
                        color : '#0088FF',
                        width: 6
                    });
