### ISSUE TITLE
KML Overlay

### ISSUE THREAD

**Issue by quary1993** [mapsplugin/cordova-plugin-googlemaps#875]
I noticed that kmlOverlay.getOverlays() method doesn't return points with images ( i have a point with a green pin image on it, and this method only returns basic red markers from the overlay )

**Comment by wf9a5m75** [comment]
Could you see your example code, and demo kml file?

**Comment by VishnuPMali** [comment]
Hello Sir, Thank you for your gr8 plugin. I am using it with ionic framework project in which Im trying to show offline map and also two or three maps using KML file. I have done demo first and got all offline but some issues are : 
1) The KML file which I'm showing on map is came but when I click on markers(points), data is showing without image means it showing me <description><[[CDATA ......]]>n all HTML tags. I tried one KML file but no luck . (http://dominoc925.blogspot.in/2013/02/example-kml-for-displaying-photo-image.html).
2) On first time in my App I got offline map on first page well.On second page, where Im trying to show three divs with different maps of different KML files, only one map I hv got and other two divs came blank. 
Im new to ionic framework . and in phonegap also. Could you help me to show multiple maps at time. 
Thank You, sorry for this essay but facing the issues ....

**Comment by wf9a5m75** [comment]
@VishnuPMali This plugin does not support multiple maps. You can only use one map in your app.
Regarding of CDATA, KML parser does not recognise it. And you can not use <HTML> tags in infoWindow, because it's drew inside the native side (java or Objective-c) as text.

**Comment by wf9a5m75** [comment]
@quary1993 The KMLparser recognises as icon if there is `styleurl` attribute.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/AsyncKmlParser.java#L225-L242

**Comment by VishnuPMali** [comment]
Thank you Sir for reply and for such a gr8 plugin....
