### ISSUE TITLE
toDataURL creates white square with transparent circle in it on iOS

### ISSUE THREAD

**Issue by troxler** [mapsplugin/cordova-plugin-googlemaps#876]
When calling `toDataURL` on iOS, the generated image contains a white square with a transparent circle in it on the bottom right corner. The actual map does not show this square, only the generated image on iOS does. Any idea what could cause this? Is it some kind of hidden control element that is revealed when calling `toDataURL`?

![todataurl](https://cloud.githubusercontent.com/assets/2767948/13396014/8403d274-def2-11e5-8319-c47c9140c5c9.png)

**Comment by troxler** [comment]
This seems to be related to `getMyLocation()`. When setting `getMyLocation(true)`, the circle location button will be placed exactly in that transparent circle. But explicitly setting `getMyLocation(false)` still shows that white square.

**Comment by chrigi** [comment]
I found the corresponding bug report here: https://code.google.com/p/gmaps-api-issues/issues/detail?id=9173

I could fix the issue by replacing the following line in the toDataURL function in Map.m:
`[self.mapCtrl.map.layer renderInContext:UIGraphicsGetCurrentContext()];`
with:
`[self.mapCtrl.view drawViewHierarchyInRect:self.mapCtrl.map.layer.bounds afterScreenUpdates:NO];`

As this is an accepted bug I'm not sure if this workaround should be committed to the repo.

**Comment by masashiGMS** [comment]
@chrigi Could you make a pull request for us?

**Comment by wf9a5m75** [comment]
I will check this later.

**Comment by wf9a5m75** [comment]
Thanks @chrigi  !
