### ISSUE TITLE
Run as Background service

### ISSUE THREAD

**Issue by wolvesworld** [mapsplugin/cordova-plugin-googlemaps#877]
I have on Javascript Function that get a my Current Location and Check if I am near from any of the markers from my markers List , 
But I want to run this in the background even the Application is Not open  still be notified that I am near from of the markers .  

What is the Best Approach with using only Javascript side .

**Comment by woody1990** [comment]
Will this help?
[Cordova Background Geolocation Services](https://github.com/pmwisdom/cordova-background-geolocation-services)
