### ISSUE TITLE
Set camera to cover two points

### ISSUE THREAD

**Issue by denkomanceski** [mapsplugin/cordova-plugin-googlemaps#881]
I have two markers, A and B, and they are connected with polyline between. How can I animate/set the camera so I will be able to see both points A and B on the screen, and the zoom level should probably be set automatically. I saw in the .apk example app that you have, after you write the polygon, you unzoom a bit so it will be inside the current screen, but I dont know how did you do it and if that is what I need. I saw some function like `fromLatLngToPoint(LatLng, function([x, y]) {})` but I am not sure if this one can help me. Anyone has an idea ?

**Comment by denkomanceski** [comment]
Any idea for a workaround on this ?

**Comment by masashiGMS** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.moveCamera()#fit-camera-to-multiple-points

**Comment by denkomanceski** [comment]
Huh.. Thank you, I guess I am so blind
