### ISSUE TITLE
Apply a style to the map : Hue, Visibility, etc....

### ISSUE THREAD

**Issue by itAsia** [mapsplugin/cordova-plugin-googlemaps#883]
Hello

I could succeed to make the plugin work. It is a much better solution than the web version.

But there are less options, or maybe I simply don't find them. For example, how can I style the map? 

Web Version : 
var styles = [{stylers: [{"hue": "#ff0000"}, {"visibility": "simplified"}]}];
map.setOptions({styles: styles});

In your plugin, where can I do that? 

Thanks for everything !

S.L.

**Comment by masashiGMS** [comment]
Since this plugin uses Google Maps API Android v2 and Google Maps SDK for iOS, they are not implemented the styledMapTyle feature. So it's not possible technically.
