### ISSUE TITLE
limit minZoom 

### ISSUE THREAD

**Issue by itAsia** [mapsplugin/cordova-plugin-googlemaps#884]
Hi

I'm trying to dispose minZoom and maxZoom but I think the launcher doesn't take these parameters.

So I tried to patch setZoom in the PluginMap Class. But it doesn't work as this class is indicated "unused".

I tried as well to patch getTile() from the class PluginTileProvider, but it didn;t work as well.

I want to force the zoom >10 because I dont want the software to download all marker coordinates for the whole world.

What did I miss?

Thanks !

S.L.

**Comment by wf9a5m75** [comment]
Well, you are trying a hard challenge ( I think ), but check this page:
http://stackoverflow.com/questions/14977078/limit-scrolling-and-zooming-google-maps-android-api-v2

**Comment by DaDanny** [comment]
Hi @itAsia : I know its been a while, but did you ever solve this? I'm just getting started on solving the problem you described (not loading all markers across the whole world), and what I am doing is if they are at the min zoom level (seeing the entire world), I only load the most recent markers. 


Then as the camera changes, I detect if the zoom has changed. If it is still the min zoom level, I don't get any more markers. 


But as the user zooms in, I get the bounding box radius (haven't solved that one yet, but should be easy and I'll update once I do) and use that to query markers in the area. 


If the user moves around the camera, and isn't at the min zoom, I continue to get the bounding box radius, and use that to query any additional markers. 


While I haven't fully implemented this, I believe it should work and I'll let you know once I finish it (hopefully tonight).

**Comment by itAsia** [comment]
Hi Danny

We reversed to the web based version... :(

Good luck on your side !

++

Stéphane
