### ISSUE TITLE
Remove poi from map (company names etc.) 

### ISSUE THREAD

**Issue by otined** [mapsplugin/cordova-plugin-googlemaps#885]
Hi,

I tried to find a solution for this, but wasn't able to find a way to remove the company names etc. from the map. In the javascript API it can be done with:

```
var noPoi = [
    {
        featureType: "poi",
        stylers: [
            { visibility: "off" }
        ]   
    }
];
```

      map.setOptions({styles: noPoi});

Can this be done with the Cordova plugin?

Thanks in advance!

**Comment by masashiGMS** [comment]
Since this plugin uses Google Maps API Android v2 and Google Maps SDK for iOS, they are not implemented the styledMapTyle feature. So it's not possible technically.

**Comment by otined** [comment]
Ok thanks for your response!
