### ISSUE TITLE
Map zooms out to min

### ISSUE THREAD

**Issue by AndroConsis** [mapsplugin/cordova-plugin-googlemaps#886]
Sometimes in between on click on markers map zooms out to the min zoom level.
I think this is some bug. has anyone else experienced it.

**Comment by wf9a5m75** [comment]
Could you take a video (upload to youtube), and show me your example code that reproduce your issue?
As far as I know (until v1.2.5), I did not experience something like that, and I did not write code such a behavior.

**Comment by AndroConsis** [comment]
I've mailed you the video on wf9a5m75@gmail.com. Please go through it.
I'm animating the map to the location from ListView. I'm not passing any zoom level. As it is supposed to be stay on the default zoom level user is on. But still it zooms out. Please look into it.

**Comment by wf9a5m75** [comment]
> Is there any work aroud to trigger the marker info window from array of markers?

Trigger `click` event for marker is `marker.trigger(plugin.google.maps.event.MARKER_CLICK)` (should work)
