### ISSUE TITLE
App getting crashed while clicking back button when the Map is visible

### ISSUE THREAD

**Issue by Dineshrajaa** [mapsplugin/cordova-plugin-googlemaps#887]
Hello all, I am using this map plugin  and in Android while clicking "Device back button" when the Map Dialog is visible the app is getting crashed how can I close the Map Dialog alone instead of closing the app?
Kindly help me to fix it.

**Comment by wf9a5m75** [comment]
It seems this https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/624

**Comment by Dineshrajaa** [comment]
But I am not using admob plugin.. still facing this issue :(

**Comment by wf9a5m75** [comment]
@Dineshrajaa Could you give me an example project? I will inspect it.

**Comment by Dineshrajaa** [comment]
@wf9a5m75 sure, please clone my repo `https://github.com/Dineshrajaa/MapMan.git` I have made a sample app with this plugin.

**Comment by wf9a5m75** [comment]
Fixed.

**Comment by Dineshrajaa** [comment]
Thanks for fixing it :)
