### ISSUE TITLE
iOS API keys aren't working?

### ISSUE THREAD

**Issue by davidluthiers** [mapsplugin/cordova-plugin-googlemaps#888]
I generated 2 different Google Maps SDK for iOS keys and none of them work. I can see the uses each gets everytime I try to load the map, so the keys are fine, but the map doesn't load and this appears in the console:

Google Maps API warning: NoApiKeys

I googled this message and found a ton of threads opened in the last 8 days, no solution. I assume that Google maps still works on iPhones so I suppose the problem resides in the plugin, Apple probably changed something, I dont know.
I'm testing on 7.1.2 iOS.

It works perfectly on Android.

Thank you.

**Comment by wf9a5m75** [comment]
Did you specify the api key for ios when you install the maps plugin?

**Comment by davidluthiers** [comment]
Of course, I said it adds up to the number of uses on the Google developer console each time the app map tries to load. I'm putting both Android and iOS keys on the config.xml and using phonegap build.

**Comment by wf9a5m75** [comment]
Well, many people creates their app on PhoneGap build with this plugin for Android and iOS, I have been never asked this.
(I left this project for a while though)

Could you invite me to your project? If so, I will check your project.

**Comment by davidluthiers** [comment]
Yes, please, thank you.

This is my project, you don't need any invite: https://github.com/davidluthiers/MaquetaDiasporas
You can check there the config.xml and the map things are on https://github.com/davidluthiers/MaquetaDiasporas/blob/master/app/modules/custom/map_module/map_module.js

I'm building on phonegap build. I remind you this works perfectly on Android. I have commented some code trying to leave the map creation pure and isolated. The new things I have seen through debugging are: the HTML element where the map will be put is correctly created, and the map object fires the onMapInit trigger, but trying to add markers frozes the app.

**Comment by mikehebert** [comment]
I'm having the same problem with Visual Studio Tools for Cordova. Android builds and runs fine, but the remote iOS build server returns:

Error: Remote build error from the build server Build failed with error Variable(s) missing: API_KEY_FOR_IOS

**Comment by davidluthiers** [comment]
That is not my case, mike, I do have the variable API_KEY_FOR_IOS with a key value on my config.xml, as stated in this link from the plugin docs:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/411#issuecomment-75452290

**Comment by mikehebert** [comment]
That's what I mean - I have the API_KEY_FOR_IOS in the config.xml, but it somehow isn't being passed / is being ignored by the remote iOS build server.

**Comment by wf9a5m75** [comment]
@davidluthiers Sorry for late response. I see your project, and on Android was no problem (looks good your app).
I left debuggable iPhone at my house, hold on please.

**Comment by davidluthiers** [comment]
Thank you, I'm still here. While this is sorted out I'm going to put there a javascript map.

**Comment by davidluthiers** [comment]
SOLVED. It was a iOS certificate issue...no idea how or why it affected only the plugin. Probably because the iOS SDK key had a wrong app ID the first time I executed the app, and corrupted it forever or something like that till I made a new set of everything.

Thanks a lot for your help.

**Comment by wf9a5m75** [comment]
Congratulation!
