### ISSUE TITLE
Offline map using KML file in Ionic iOS app(mountain app)

### ISSUE THREAD

**Issue by VishnuPMali** [mapsplugin/cordova-plugin-googlemaps#889]
I am trying to show offline map in my app using IONIC framework for iOS. I am showing one offline map on one page and on other pages I m showing 3 maps using KML files .All these maps I'm appending to DIVs on pages. I m using  (https://github.com/wf9a5m75/ionic_test) this plugin. I got this plugin after trying many things to get offline maps n KML maps offline. This plugin is really best I have seen, supports offline map . works gr8. for map, native look. But facing some issues :not getting data with images on map of KML file when Im clicking on markers in it. It shows <description><[[!CDATA... ]]> tags. tried (http://dominoc925.blogspot.in/2013/02/example-kml-for-displaying-photo-image.html) but no luck.Also not getting multiple maps of using KML file in DIV. . Im new to IONIC . OR is there any solution without plugin . Plz share some help n links. Thank You...

**Comment by wf9a5m75** [comment]
Check this answer.
#530

**Comment by VishnuPMali** [comment]
Thank you Sir for reply...
