### ISSUE TITLE
Very poor performance with a single marker

### ISSUE THREAD

**Issue by jskidd3** [mapsplugin/cordova-plugin-googlemaps#891]
As you can see here there is very poor performance with only a single marker:

https://youtu.be/4koMLQnyGZY

Also, the marker quality is very poor and there is no transparency on the shadow (despite the PNG having transparency). Any ideas why this is happening?

I have installed Crosswalk.

```
var map = null;

document.addEventListener("deviceready", function() {
	var div = document.getElementById("map");
	map = plugin.google.maps.Map.getMap(div);
	map.addEventListener(plugin.google.maps.event.MAP_READY, initMap);
});

function initMap() {
	map = plugin.google.maps.Map.getMap(document.getElementById('map'));
	map.addMarker({
		position: new plugin.google.maps.LatLng(53.959067, -1.077215),
		title: 'York, The Stonebow',
		icon: {
			url: 'www/img/markers/destination2.png'
		}
	});
}
```

I have tested on Nexus 5X and Samsung Galaxy S3 and the problem occurs on both.

**Comment by jskidd3** [comment]
Gah sorry..... infinite loop. I'm an idiot. It's 4AM here so I need to get some sleep!!! Hope you're well Masashi.

**Comment by Assilfira** [comment]
@jskidd3 Can you tell me which version of the plugin did you use? Your video shows that the app only took about 1 second to be ready for use, and I want to know what have you done for that so.

**Comment by battika** [comment]
Pretty sure he used version 1.4 as 2.0 is not compatible with Crosswalk.

**Comment by Assilfira** [comment]
Good point. Regardless, how did he get so good performance in boot speed up?
