### ISSUE TITLE
android 6.0 permissions

### ISSUE THREAD

**Issue by DEllingsworth** [mapsplugin/cordova-plugin-googlemaps#892]
I'm having trouble using this on my Android 6,0 phone.  I'm requesting the permissions manually with https://www.npmjs.com/package/cordova.plugins.diagnostic.  But it would be nice if this plugin would prompt for permissions itself.

Currently, if the permissions are not granted, the app just crashes when it attempts to get the current location.

**Comment by wf9a5m75** [comment]
I see, I will check this later.

**Comment by wf9a5m75** [comment]
Accept. Thank you for your feed back. I have been implementing this.

**Comment by wf9a5m75** [comment]
I have been trying to implement this.
Currently the plugin can request the location permissions, but Cordova project can not receive the permissions for some reason.

Even if I use the `cordova.plugins.diagnostic` plugin, the same result.

**Comment by DEllingsworth** [comment]
Perhaps there is something in here you can look at, as it has the
permissions request built in.

https://github.com/apache/cordova-plugin-geolocation



On Fri, Mar 25, 2016 at 4:08 AM, Masashi Katsumata <notifications@github.com

**Comment by wf9a5m75** [comment]
Ok, I got the reason. I don't know why but the installed CordovaActivity.java does not have [onRequestPermissionsResult](
https://github.com/apache/cordova-android/blob/5.0.x/framework/src/org/apache/cordova/CordovaActivity.java#L493-L506) for some reason.

Without this method, callback does not work.
So I need to change the lower Cordova version at least Cordova 5.x

**Comment by wf9a5m75** [comment]
This issue is fixed. Use the master branch please.
