### ISSUE TITLE
Marker not shown

### ISSUE THREAD

**Issue by Dineshrajaa** [mapsplugin/cordova-plugin-googlemaps#893]
Hi all,
 I am just trying to Add a marker to the map with a particular LatLng but the marker icon is not visible only the info window is being shown and it is not at the correct location how can I fix this?please correct me if I am coding wrongly.

Please clone my repo https://github.com/Dineshrajaa/MapMan.git

![screenshot_2016-03-23-00-01-01](https://cloud.githubusercontent.com/assets/7291567/13963201/73b2aab8-f08a-11e5-9a2f-cb8166235c0a.png)

**Comment by wf9a5m75** [comment]
In your code, you should pass the raw div object like this: `var mapDiv = $("#mapHolder")[0];`.

If you use only with dialog, you just do `map = plugin.google.maps.Map.getMap(mapOptions);`.

At least for me, this work like this.
![screen shot 2016-03-23 at 10 31 39 pm](https://cloud.githubusercontent.com/assets/167831/14009228/1d3930c2-f147-11e5-9b54-b203d3799d1d.png)

**Comment by Dineshrajaa** [comment]
Thanks will try this.
