### ISSUE TITLE
Monaca build failed

### ISSUE THREAD

**Issue by ikooooh** [mapsplugin/cordova-plugin-googlemaps#895]
I am working on Monaca.io and try to build blank project same as tutorial from https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Monaca.

My project setting: 
cordova:5.2.0,  ios:3.9.1, android:4.1.1

I got an error as below:

> Temporary folder: /private/tmp/monaca/56f290f0fd17347b6efaf306
Downloading project
Download complete
Running for 5.2
plugin add mobi.monaca.plugins.Monaca@3.0.0
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Fetching plugin &quot;mobi.monaca.plugins.Monaca@3.0.0&quot; via npm
Installing &quot;mobi.monaca.plugins.Monaca&quot; for android
No ALTQ support in kernel
ALTQ related functions disabled
pf disabled
plugin add android.support.v4
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Installing &quot;android.support.v4&quot; for android
No ALTQ support in kernel
ALTQ related functions disabled
pf disabled
plugin add com.googlemaps.ios
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Installing &quot;com.googlemaps.ios&quot; for android
No ALTQ support in kernel
ALTQ related functions disabled
pf disabled
plugin add cordova-google-play-services
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Installing &quot;cordova-google-play-services&quot; for android
No ALTQ support in kernel
ALTQ related functions disabled
pf disabled
plugin add plugin.google.maps
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Installing &quot;plugin.google.maps&quot; for android

             In order to run this plugin, you need to obtain Google Maps API key for Android.
             Visit https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Installation

             Check our release notes.
             https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Release-Notes
        
No ALTQ support in kernel
ALTQ related functions disabled
pf disabled
plugin add plugin.http.request
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Installing &quot;plugin.http.request&quot; for android
No ALTQ support in kernel
ALTQ related functions disabled
pf disabled
plugin add cordova-plugin-whitelist@1.0.0
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Fetching plugin &quot;cordova-plugin-whitelist@1.0.0&quot; via npm
Installing &quot;cordova-plugin-whitelist&quot; for android
No ALTQ support in kernel
ALTQ related functions disabled
pf disabled
plugin add cordova-plugin-splashscreen@2.1.0
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Fetching plugin &quot;cordova-plugin-splashscreen@2.1.0&quot; via npm
Installing &quot;cordova-plugin-splashscreen&quot; for android
No ALTQ support in kernel
ALTQ related functions disabled
pf disabled
Project has 8 plugins.
8 plugins has been installed.
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Running command: /private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton/hooks/after_prepare/monaca_enterprise_android.js /private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton
No ALTQ support in kernel
ALTQ related functions disabled
pf disabled
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Running command: /private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton/platforms/android/cordova/build --release
ANDROID_HOME=/Applications/android-sdk-macosx
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
Running: /private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton/platforms/android/gradlew cdvBuildRelease -b /private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton/platforms/android/build.gradle -Dorg.gradle.daemon=true
:preBuild
:preReleaseBuild
:checkReleaseManifest
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preBuild
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:compileReleaseJava
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:cordova-google-play-services:google-play-services_lib:compileLint
:cordova-google-play-services:google-play-services_lib:copyReleaseLint UP-TO-DATE
:cordova-google-play-services:google-play-services_lib:mergeReleaseProguardFiles
:cordova-google-play-services:google-play-services_lib:preBuild
:cordova-google-play-services:google-play-services_lib:preReleaseBuild
:cordova-google-play-services:google-play-services_lib:checkReleaseManifest
:cordova-google-play-services:google-play-services_lib:prepareAndroidCordovaLibUnspecifiedReleaseLibrary
:cordova-google-play-services:google-play-services_lib:prepareReleaseDependencies
:cordova-google-play-services:google-play-services_lib:compileReleaseAidl
:cordova-google-play-services:google-play-services_lib:compileReleaseRenderscript
:cordova-google-play-services:google-play-services_lib:generateReleaseBuildConfig
:cordova-google-play-services:google-play-services_lib:generateReleaseAssets UP-TO-DATE
:cordova-google-play-services:google-play-services_lib:mergeReleaseAssets
:cordova-google-play-services:google-play-services_lib:generateReleaseResValues
:cordova-google-play-services:google-play-services_lib:generateReleaseResources
:cordova-google-play-services:google-play-services_lib:mergeReleaseResources
:cordova-google-play-services:google-play-services_lib:processReleaseManifest
:cordova-google-play-services:google-play-services_lib:processReleaseResources
:cordova-google-play-services:google-play-services_lib:generateReleaseSources
:cordova-google-play-services:google-play-services_lib:compileReleaseJava
:cordova-google-play-services:google-play-services_lib:processReleaseJavaRes UP-TO-DATE
:cordova-google-play-services:google-play-services_lib:packageReleaseJar
:cordova-google-play-services:google-play-services_lib:compileReleaseNdk
:cordova-google-play-services:google-play-services_lib:packageReleaseJniLibs UP-TO-DATE
:cordova-google-play-services:google-play-services_lib:packageReleaseLocalJar
:cordova-google-play-services:google-play-services_lib:packageReleaseRenderscript UP-TO-DATE
:cordova-google-play-services:google-play-services_lib:packageReleaseResources
:cordova-google-play-services:google-play-services_lib:bundleRelease
:prepareAndroidCordovaGooglePlayServicesGooglePlayServices_libUnspecifiedReleaseLibrary
:prepareAndroidCordovaLibUnspecifiedReleaseLibrary
:preDebugBuild
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:compileDebugJava
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:cordova-google-play-services:google-play-services_lib:copyDebugLint UP-TO-DATE
:cordova-google-play-services:google-play-services_lib:mergeDebugProguardFiles
:cordova-google-play-services:google-play-services_lib:preDebugBuild
:cordova-google-play-services:google-play-services_lib:checkDebugManifest
:cordova-google-play-services:google-play-services_lib:preDebugTestBuild
:cordova-google-play-services:google-play-services_lib:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:cordova-google-play-services:google-play-services_lib:prepareDebugDependencies
:cordova-google-play-services:google-play-services_lib:compileDebugAidl
:cordova-google-play-services:google-play-services_lib:compileDebugRenderscript
:cordova-google-play-services:google-play-services_lib:generateDebugBuildConfig
:cordova-google-play-services:google-play-services_lib:generateDebugAssets UP-TO-DATE
:cordova-google-play-services:google-play-services_lib:mergeDebugAssets
:cordova-google-play-services:google-play-services_lib:generateDebugResValues
:cordova-google-play-services:google-play-services_lib:generateDebugResources
:cordova-google-play-services:google-play-services_lib:mergeDebugResources
:cordova-google-play-services:google-play-services_lib:processDebugManifest
:cordova-google-play-services:google-play-services_lib:processDebugResources
:cordova-google-play-services:google-play-services_lib:generateDebugSources
:cordova-google-play-services:google-play-services_lib:compileDebugJava
:cordova-google-play-services:google-play-services_lib:processDebugJavaRes UP-TO-DATE
:cordova-google-play-services:google-play-services_lib:packageDebugJar
:cordova-google-play-services:google-play-services_lib:compileDebugNdk
:cordova-google-play-services:google-play-services_lib:packageDebugJniLibs UP-TO-DATE
:cordova-google-play-services:google-play-services_lib:packageDebugLocalJar
:cordova-google-play-services:google-play-services_lib:packageDebugRenderscript UP-TO-DATE
:cordova-google-play-services:google-play-services_lib:packageDebugResources
:cordova-google-play-services:google-play-services_lib:bundleDebug
:prepareComAndroidSupportSupportV42220Library
:prepareComGoogleAndroidGmsPlayServicesBase830Library
:prepareComGoogleAndroidGmsPlayServicesBasement830Library
:prepareComGoogleAndroidGmsPlayServicesLocation830Library
:prepareComGoogleAndroidGmsPlayServicesMaps830Library
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
/private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton/platforms/android/res/drawable-ldpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton/platforms/android/res/drawable-land-mdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton/platforms/android/res/drawable-port-ldpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton/platforms/android/res/drawable-port-mdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton/platforms/android/res/drawable-land-ldpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/private/tmp/monaca/56f290f0fd17347b6efaf306/android/skeleton/platforms/android/res/drawable-mdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task &apos;:processReleaseResources&apos;.
&gt; Error: more than one library with package name &apos;com.google.android.gms&apos;
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.58 secs

I'd appreciate any help.
Thanks

**Comment by wf9a5m75** [comment]
The monaca page was written when Cordova version was 3.x. It does not work now probably (I'm not sure).

**Comment by wf9a5m75** [comment]
@ikooooh Could you invite me to your project? I will check it if you invite me.

**Comment by ikooooh** [comment]
Hi @wf9a5m75,

I shared the project to your mail.. it's just blank project with Google map plugin.
If you find the way to solve this issues please help me update wiki for every one.

Big thanks for your kind!

**Comment by wf9a5m75** [comment]
Oops, I need to upgrade to the Gold plan. It is expensive for test... I will contact to Monaca by e-mail, wait couple of days please.

**Comment by ikooooh** [comment]
The project I shared is in Gold plan so you can test it. The plans lower than Gold can not share.

**Comment by wf9a5m75** [comment]
I found "free trial" button for 14 days now, I will check yours later.

**Comment by wf9a5m75** [comment]
Thank you for waiting. I figured out what is wrong.
Since this plugin was modified https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/599, you don't need to upload `google-play-services.zip`, `cordova-plugin-android-support-v4.zip`.
And also this plugin does not use `phonegap-http-request.zip` anymore.

After deleted these packages, the app was built on Monaca for Android.

**Comment by wf9a5m75** [comment]
Follow up. Since you use download the v1.3.9 of this plugin, **you can build Android app with the downloaded zip file** .

However, I changed the minimum support Android platform in order to support Android 6.0.
So the tutorial I have been writing does not work currently.

**Comment by wf9a5m75** [comment]
@ikooooh Following up.

The Monaca uses Cordova5.x, and Cordova-Android 4.1.1 internally.
Because of other issue (https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/892), this plugin needed to change the minimum support version of Cordova to v5.1.0.

Due to this, you can not use this plugin on the Monaca at this time.

I suggested to the Asial (= monaca) to upgrade their Cordova version as soon as possible,
but they said it is difficult to do that soon.

This issue is not this plugin's fail, not your fault.
Please claim to the monaca support to extend your plan by yourself if you feel this is Monaca fail.

----

However, if you want to use this plugin on the Monaca in anyway,
you can download the zip file from [here](https://github.com/mapsplugin/cordova-plugin-googlemaps/archive/master.zip),
upload it to the Monaca,
and change the minimum required version at this line.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L18

Then you can build your app.

**Comment by ikooooh** [comment]
Hi @wf9a5m75 and sorry for late reply.

Thank you for your answers and your research. It is bad news for me.

I will contact with Monaca for this problem.
