### ISSUE TITLE
Map always on top

### ISSUE THREAD

**Issue by ZiFFeL1992** [mapsplugin/cordova-plugin-googlemaps#898]
My current 'issue' is that when I push a new view at the top of the map on Ionic 2 while tapping on an info window, I keep dragging the map while watching the secondary view.
I can only scroll that view in the square of the tabs, otherwise I drag the map.

My current workaround is to move the map far from the screen size (float and add -999999px margin), this is currently working fine but might be awesome to get this working without that fix.

**Comment by masashiGMS** [comment]
Use `map.setClicable(false)`
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#mapsetclickable

**Comment by ZiFFeL1992** [comment]
Works like a charm :D
