### ISSUE TITLE
Maps blank screen

### ISSUE THREAD

**Issue by FrancescoASessa** [mapsplugin/cordova-plugin-googlemaps#901]
Hi, I tried to use your plugin but it doesn't work. I see only a white screen. I am using intel xdk with cordova and bootstrap 3

**Comment by wf9a5m75** [comment]
Please report with more detailed information, such as error message, your code, etc. 
Check the wiki pages and past posts also please.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/538

Deploy your whole project on to github is also applicate.

**Comment by FrancescoASessa** [comment]
![111](https://cloud.githubusercontent.com/assets/18053767/14024278/bb3ac79e-f1e8-11e5-9904-360c246abad8.PNG)
![222](https://cloud.githubusercontent.com/assets/18053767/14024319/db0473a4-f1e8-11e5-8ffd-ff97c90cf70d.PNG)
I use Intel XDK, I tried to use the "Add Marker" (https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker)

**Comment by wf9a5m75** [comment]
Thank you. So what is the error messages in logcat? I don't use Intel XDK, so I can not test your environment.

**Comment by wf9a5m75** [comment]
Any update?

**Comment by wf9a5m75** [comment]
I close this issue because no additional information was provided.
If you have any update, please reopen this issue.
