### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Keyboard' of undefined

### ISSUE THREAD

**Issue by Plex768** [mapsplugin/cordova-plugin-googlemaps#902]
I am getting the following message in the debug console when I try to run an ionic app using corodva-plugin-googlemaps in the visual studio code IDE:
`
Uncaught TypeError: Cannot read property 'Keyboard' of undefined`

I am assuming it is referring to the reference to the keyboard property in the .run function of the app.js code.

However, the app builds successfully and loads on my device.

I tried removing and reinstalling both the android and iOS platforms.  Still I see this error message and the map is not loading.  I only see a blank white screen.  Any help would be appreciated.  thanks.

**Comment by masashiGMS** [comment]
What plugins do you installed this plugin else?

If you share your **WHOLE** project, I can check yours.

**Comment by Plex768** [comment]
this is what i have:

cordova-plugin-console
cordova-plugin-device
cordova-plugin-keyboard
cordova-plugin-splashscreen
cordova-plugin-whitelist

I read that i need to install com.plugin.keyboard

I typed this command: `cordova plugin add com.plugin.keyboard`

Fetching plugin "com.plugin.keyboard" via npm
Error: Failed to fetch plugin com.plugin.keyboard via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.plugin.keyboard

**Comment by ZiFFeL1992** [comment]
I think you have to install `cordova-plugin-keyboard` or `ionic-plugin-keyboard`.

**Comment by Plex768** [comment]
I installed both and added a reference to the ionic-plugin-keyboard js file like so:

<script src="plugins/ionic-plugin-keyboard/www/android/keyboard.js"></script>

Now I am not getting the original error message but I am getting a new message now:

`Uncaught ReferenceError: plugin is not defined`

Any ideas why this is showing up?  thanks.

**Comment by wf9a5m75** [comment]
Could you share your **whole** project to save my time? I'm not familiar with ionic also.
Github or bitbucket.org, please.

**Comment by Plex768** [comment]
Hi. Here is a link to the project on github. Thanks.

https://github.com/Plex768/cordova-plugin-googlemap-project

**Comment by wf9a5m75** [comment]
Thanks, I will check it later.

**Comment by Plex768** [comment]
Ok. Thank you.

**Comment by wf9a5m75** [comment]
When I executed `$ ionic state restore`, I got these errors. What should I do?
```
$ ionic state restore
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add ios
cordova platform add android

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-console
cordova plugin add cordova-plugin-whitelist
cordova plugin add cordova-plugin-splashscreen
cordova plugin add com.ionic.keyboard

/Users/masashi/.nvm/v4.2.1/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add com.ionic.keyboard":
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.ionic.keyboard

```

**Comment by Plex768** [comment]
I am asking the same question. I don't know how to solve the issue associated with that error message.

**Comment by wf9a5m75** [comment]
Well, this is out-of-range of the plugin support.
Because this is related with `com.ionic.keyboard` project.

Please ask the project author [@obetomuniz](https://github.com/obetomuniz/)

**Comment by Plex768** [comment]
Ok. thanks for your time. :)

**Comment by wf9a5m75** [comment]
Sorry, I'm not familiar with ionic.
