### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by eg271** [mapsplugin/cordova-plugin-googlemaps#907]
Installing the ios platform seems to change the plugin so that it won't build.

After getting the latest version of the plugin from git, if I add the ios platform, I get "Notice: plugin.google.maps has been automatically converted to cordova-plugin-googlemaps..." but then it appears to fetch it and install ok.

Cordova build then throws multiple errors and on inspecting plugin.xm in plugins > plugin.google.maps I can see that the file has been overwritten (presumably to an old version)

Looks like this is mentioned in issue #685 - @denisbabineau 's repo works: https://github.com/denisbabineau/cordova-plugin-googlemaps

**Comment by wf9a5m75** [comment]
Please report with error logs always.

**Comment by eg271** [comment]
CompileC build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/GoogleMaps.o HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
cd /Users/edgraham/test33/platforms/ios
export LANG=en_US.US-ASCII
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=147 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/5v/ldldk84d7yg8jz71w6k51k8r0000gp/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/edgraham/test33/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/HelloCordova-generated-files.hmap -I/Users/edgraham/test33/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/HelloCordova-own-target-headers.hmap -I/Users/edgraham/test33/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/HelloCordova-all-target-headers.hmap -iquote /Users/edgraham/test33/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/HelloCordova-project-headers.hmap -I/Users/edgraham/test33/platforms/ios/build/emulator/include -I/Users/edgraham/test33/platforms/ios/build/emulator/usr/local/lib/include -I/Users/edgraham/test33/platforms/ios/build/UninstalledProducts/include -I/Users/edgraham/test33/platforms/ios/build/UninstalledProducts/iphonesimulator/include -I/Users/edgraham/test33/platforms/ios/build/emulator -I/Users/edgraham/test33/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/DerivedSources/i386 -I/Users/edgraham/test33/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/DerivedSources -F/Users/edgraham/test33/platforms/ios/build/emulator -FHelloCordova/Plugins/com.googlemaps.ios -include /Users/edgraham/test33/platforms/ios/build/sharedpch/HelloCordova-Prefix-hjxiftzxvfnteiaywgvecrhcyyxq/HelloCordova-Prefix.pch -MMD -MT dependencies -MF /Users/edgraham/test33/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/GoogleMaps.d --serialize-diagnostics /Users/edgraham/test33/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/GoogleMaps.dia -c /Users/edgraham/test33/platforms/ios/HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m -o /Users/edgraham/test33/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/GoogleMaps.o
/Users/edgraham/test33/platforms/ios/HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m:24:30: warning: incompatible pointer types assigning to
'UIWebView *' from 'UIView * _Nullable' [-Wincompatible-pointer-types]
self.pluginLayer.webView = self.webView;
^ ~~~~~~~~~~~~
/Users/edgraham/test33/platforms/ios/HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m:28:45: warning: incompatible pointer types assigning to
'UIWebView *' from 'UIView * _Nullable' [-Wincompatible-pointer-types]
self.pluginScrollView.debugView.webView = self.webView;
^ ~~~~~~~~~~~~
/Users/edgraham/test33/platforms/ios/HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m:34:30: warning: incompatible pointer types assigning to
'UIWebView *' from 'UIView * _Nullable' [-Wincompatible-pointer-types]
self.pluginLayer.webView = self.webView;
^ ~~~~~~~~~~~~
/Users/edgraham/test33/platforms/ios/HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m:167:30: warning: incompatible pointer types assigning to
'UIWebView *' from 'UIView * _Nullable' [-Wincompatible-pointer-types]
self.mapCtrl.webView = self.webView;
^ ~~~~~~~~~~~~
/Users/edgraham/test33/platforms/ios/HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m:176:59: error: no known instance method for selector
'initWithWebView:'
Map *mapClass = [[NSClassFromString(@"Map")alloc] initWithWebView:self.webView];
^~~~~~~~~~~~~~~
/Users/edgraham/test33/platforms/ios/HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m:186:38: warning: incompatible pointer types assigning to
'UIWebView *' from 'UIView * _Nullable' [-Wincompatible-pointer-types]
self.pluginLayer.webView = self.webView;
^ ~~~~~~~~~~~~
/Users/edgraham/test33/platforms/ios/HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m:245:68: error: no known instance method for selector
'initWithWebView:'
pluginClass = [[NSClassFromString(className)alloc] initWithWebView:self.webView];
^~~~~~~~~~~~~~~
/Users/edgraham/test33/platforms/ios/HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m:321:19: error: no visible @interface for 'UIView'
declares the selector 'stringByEvaluatingJavaScriptFromString:'
[self.webView stringByEvaluatingJavaScriptFromString:jsString];
~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/edgraham/test33/platforms/ios/HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m:404:34: warning: incompatible pointer types assigning to
'UIWebView *' from 'UIView * _Nullable' [-Wincompatible-pointer-types]
self.pluginLayer.webView = self.webView;
^ ~~~~~~~~~~~~
6 warnings and 3 errors generated.

** BUILD FAILED **


The following build commands failed:
CompileC build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/GoogleMaps.o HelloCordova/Plugins/plugin.google.maps/GoogleMaps.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/edgraham/test33/platforms/ios/cordova/build-debug.xcconfig,-project,HelloCordova.xcodeproj,ARCHS=i386,-target,HelloCordova,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/edgraham/test33/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/edgraham/test33/platforms/ios/build/sharedpch
You may not have the required environment or OS to build this project
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/edgraham/test33/platforms/ios/cordova/build-debug.xcconfig,-project,HelloCordova.xcodeproj,ARCHS=i386,-target,HelloCordova,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/edgraham/test33/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/edgraham/test33/platforms/ios/build/sharedpch

**Comment by eg271** [comment]
Eds-Mac:test33 edgraham$ cordova platform add ios
Adding ios project...
iOS project created with cordova-ios@4.0.1
Installing "com.googlemaps.ios" for ios

Google Maps SDK for iOS : v1.11.1

Installing "cordova-plugin-whitelist" for ios
Notice: plugin.google.maps has been automatically converted to cordova-plugin-googlemaps and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-plugin-googlemaps" via npm
Installing "plugin.google.maps" for ios
Dependent plugin "com.googlemaps.ios" already installed on ios.

In order to run this plugin, you need to obtain Google Maps API key for iOS.
Visit https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Installation

Check our release notes.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Release-Notes

**Comment by wf9a5m75** [comment]
I guess you specify `Cordova iOS 4.0`, but you use the map plugin v1.3.9.
v1.3.9 does not support Cordova iOS 4.0
https://github.com/mapsplugin/cordova-plugin-googlemaps#warning

However, the next version (v1.4.0) supports Cordova iOS 4.0.
I have already merged the pull request #807 (issue #685) into the master branch, and fixed a little.
So please **try again with the master branch instead of npm**.

In the `config.xml` file, you should specify like this:
```
<gap:plugin source="git" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps" >
  <param name="API_KEY_FOR_ANDROID" value="(YOUR KEY)" />
  <param name="API_KEY_FOR_IOS" value="(YOUR KEY)" />
</gap:plugin>
```

**Comment by wf9a5m75** [comment]
@eg271 Ping

**Comment by eg271** [comment]
I was actually specifying the git master branch like so:

<plugin name="cordova-plugin-googlemaps" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps.git">
        <variable name="API_KEY_FOR_IOS" value="(KEY)" />
    </plugin>

The plugin gets overwritten with the npm version though: "Notice: plugin.google.maps has been automatically converted to cordova-plugin-googlemaps and fetched from npm. This is due to our old plugins registry shutting down.  Fetching plugin "cordova-plugin-googlemaps" via npm".

I notice that your tags include a "gap:" prefix.  Might this be to do with the some difference between Cordova CLI and PhoneGap?

Anyway, the solution is to rename the plugin and package id to "cordova-plugin-googlemaps" as mentioned here in issue #685. @denisbabineau 's repo works using this.

I've submitted a PR: #916

**Comment by wf9a5m75** [comment]
I think you just need to remove `name="cordova-plugin-googlemaps"` in this case.
Another person who build on PhoneGap Build was no problem with old name.

**Comment by Hirbod** [comment]
any news?

**Comment by Hirbod** [comment]
will be fixed in 1.4.0

**Comment by yuripx** [comment]
My map used to work on IOS, now I have this issue.

Is there any fix or work arround for this?

**Comment by afxgroup** [comment]
I have this error too.. few days ago i was building my app without any problem. Now i'm facing this issue. I'm using cordova 5.4.1

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps#information

**Comment by kodeine** [comment]
@wf9a5m75 
i've updated plugin to use master branch, it compiles fine, no errors, but i get a black screen on maps page. no errors. It works fine on 1.3.9 (android).

**Comment by noor92** [comment]
I am facing the same problem. It works on Android but not IOS
