### ISSUE TITLE
set marker position on dragging map like uber

### ISSUE THREAD

**Issue by Shahroz** [mapsplugin/cordova-plugin-googlemaps#909]
Hi,
I'm new in phonegap and want to implement "drag the map to set your location" feature in my app just like uber, what I need:
1) When the user dragging map, get the location coordinates and set it to the marker.
3) When the user click on locate button, map should be placed on dragged place

I don't have any idea how to tackle these things.
Any help would be appreciate.

**Comment by wf9a5m75** [comment]
Please ask at the official community for general question.
https://plus.google.com/u/0/communities/117427728522929652853
