### ISSUE TITLE
Disable Auto Pan (false) not working on Android

### ISSUE THREAD

**Issue by ZiFFeL1992** [mapsplugin/cordova-plugin-googlemaps#910]
Without passing `disableAutoPan: false`, the effect is working on iOS, also if we add that attribute while creating the marker still not working on Android. So at the moment this attribute is always true on Android.

**Comment by wf9a5m75** [comment]
Um, I could not reproduce your issue.

```js
map.addMarker({
  position: {"lat": -33.867487, "lng": 151.20699},
  disableAutoPan: true,
  draggable: true,
  'title': 'infoWindow',
  'markerClick': function(marker) {
    marker.showInfoWindow();
  }
});
```
![issue_910](https://cloud.githubusercontent.com/assets/167831/14093746/175a3662-f505-11e5-91a6-bc9c39cc2c00.gif)

**Comment by ZiFFeL1992** [comment]
I can try to record the screen on iOS as well but there are no issues on that platform.

https://drive.google.com/file/d/0BzzwDw5jEO0xc211S2RKN0UwYjg/view?usp=docslist_api

I'm using cordova 6 + ionic 2. Let me know if you need something else.

BTW, can you share that apk with me?

**Comment by wf9a5m75** [comment]
Oops, I mis-read your question... :(
You asked `disableAutoPan = false` does not work.

**Comment by wf9a5m75** [comment]
Fixed: I'm sorry, long long time ago, I created a wrong patch.
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/fc88d129676397eed81853761b50853f01bead59#diff-a1ab80937241428ba084115768af12e4R1125

Please use the master branch.
![issue_910](https://cloud.githubusercontent.com/assets/167831/14094834/d9b16a42-f50e-11e5-9f05-b99f015a5ec3.gif)
