### ISSUE TITLE
Enhancement: Move the variable value for map key to config.xml

### ISSUE THREAD

**Issue by aaabidunique** [mapsplugin/cordova-plugin-googlemaps#911]
It will be easily changable and efficient if the developer moves the map key variable from cli input to just read from config.xml

**Comment by wf9a5m75** [comment]
Impossible. In Android, you **MUST** put your API_KEY in the `AndroidManifest.xml` file that is not changeable from the application code.

**Comment by aaabidunique** [comment]
Thanks for your quick reply.Actually i was talking about something like this

<platform name="android">
    <preference name="API_KEY_FOR_ANDROID" value="YOUR-ANDROID-KEY" />
</platform>
<platform name="ios">
    <preference name="API_KEY_FOR_IOS" value="YOUR-IOS-KEY" />
</platform>

and i have seen similar configuration in this #907 issue as explained by you.

**Comment by wf9a5m75** [comment]
#907 is case for PhoneGap Build. Not CLI.
