### ISSUE TITLE
rename plugin

### ISSUE THREAD

**Issue by Hirbod** [mapsplugin/cordova-plugin-googlemaps#917]
@wf9a5m75 i want to rename plugin.google.maps to cordova-plugin-googlemaps (inside of xml-file) to prevent problems with the old name convention. Any regrets about that? Do we have to think about any consequences when doing so?

**Comment by wf9a5m75** [comment]
No problem.

**Comment by Hirbod** [comment]
:+1: but we need to make it very clear inside of the docs. The people have to remove the plugin before grabbing the new version or they would have 2 versions of the plugin installed

**Comment by wf9a5m75** [comment]
Using the hook mechanism, we should check ether the old name package is existed or not.

**Comment by Hirbod** [comment]
hint to myself: also need to change package.json for npm

**Comment by Hirbod** [comment]
Changed!
