### ISSUE TITLE
cocoa pod install

### ISSUE THREAD

**Issue by wf9a5m75** [mapsplugin/cordova-plugin-googlemaps#918]
This plugin uses Google Maps SDK for iOS, but we upload to it on the bitbucket of @Hirbod 
As a temporally solution is fine, but as the result, you will miss the latest Maps SDK.

Apache Cordova does not support Cocoa Pod, but Apache Cordova allows us to execute external process using Hooks.
https://cordova.apache.org/docs/en/dev/guide/appdev/hooks/

Using this, I was able to download the maps SDK automatically when I installed the maps plugin.

---

However I did not merged the code into the master, because there was several reasons.
- I was busy.
- Code is not completed yet.
- I did not test PhoneGap Build or other Cloud building service support the hook mechanism.

---

Regarding of PhoneGap Build, it supports the hook mechanism now.
So we should complete the `automatic install` in near the feature.

**Comment by Hirbod** [comment]
I am totally fine with it, if it works without big troubles. I used bitbucket, because bitcode-support bloated SDK to 113MB, and Github only allows 100MB.

**Comment by wf9a5m75** [comment]
Memo for my self.
https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/GoogleMaps/1.13.0/GoogleMaps.podspec.json

**Comment by wf9a5m75** [comment]
@Hirbod,

I created a simple plugin, which is able to download the Google Maps SDK for iOS without CocoaPod.
I know downloading the large file with only node.js is bit slow, but the code downloads the file certainly.
I will add more code to speed up the downloading.

And in order to keep the backward compatibility, the plugin use the packagename `com.googlemaps.ios` (as well as you currently serve).
https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk

**Comment by wf9a5m75** [comment]
Unfortunately, it seems the PhoneGap Build does not allow to write file from node.js.  
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1099

We have to give up at this time.
