### ISSUE TITLE
Auto centering map on my position when changing location

### ISSUE THREAD

**Issue by lukaszrozbicki** [mapsplugin/cordova-plugin-googlemaps#921]
I have this issue: while moving (e.g. driving bus or car) and scrolling the map, when my app get location change, map is automatically centering on my new current position. 
Disabling "my location" control do nothing. Map still does auto center.
It's quite annoying :/
Is there any way to disable that behavior?

**Comment by wf9a5m75** [comment]
This plugin does not follow your location automatically. It comes from the native Map SDKs.
You need to set proper settings by yourself.
```js
var map = plugin.google.maps.Map.getMap({
  'controls': {
    'myLocationButton': true / false
  }
});
```


And also check out here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/266#issuecomment-63118586

**Comment by lukaszrozbicki** [comment]
Thanks, but as I said, setting myLocationbutton to false doesn't change anything. Map is still centering on current position while I moving.

**Comment by wf9a5m75** [comment]
As I said, this plugin does not do anything. It comes from the native SDK. So this is not related with this plugin.
And only possible way is 
```js
map.setMyLocation(false);
map.getUiSettings().setMyLocationButtonEnabled(false);
```

Please check this https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/266#issuecomment-63118586

**Comment by lukaszrozbicki** [comment]
Ok, I'll try that! Thank you very much! :)
