### ISSUE TITLE
Maps SDK 1.13.0

### ISSUE THREAD

**Issue by Hirbod** [mapsplugin/cordova-plugin-googlemaps#922]
@wf9a5m75 GMaps SDK 1.13.0 is out since today. 
Do we want to support some of the new functions?

- UIView based markers. Marker content can now show advanced animations by providing a custom view hierarchy to be displayed through the iconView property.
- Info windows can now have their custom views animated. Set tracksInfoWindowChanges on the associated marker to YES to enable real-time updates.
- Map rendering now defaults to 60fps on modern iOS devices. Set the new preferredFrameRate property on GMSMapView to revert to the old behavior (Conservative) or a new low frame rate option to save battery (PowerSave).
- Added mapViewSnapshotReady: to GMSMapViewDelegate which fires when map content, including markers and other overlays, has been fully rendered.
- Autocomplete widgets in the Places API now provide options for custom styling.

**Comment by Hirbod** [comment]
Updated bitbucket to 1.13.0

**Comment by wf9a5m75** [comment]
Thank you for checking up. How about Android api? If there are some common features or similar features, we should implement them.

**Comment by Hirbod** [comment]
What both have in common is the places picker ui. What I'm thinking about is: own plugin or shall we integrate this?

**Comment by wf9a5m75** [comment]
Sorry for late working.
I will bring the sdk v2.0.1 for the multiple_maps branch in a few days.

**Comment by wf9a5m75** [comment]
Merge #1047
