### ISSUE TITLE
Using external service causes the application to restart when going back from Google Maps

### ISSUE THREAD

**Issue by clviper** [mapsplugin/cordova-plugin-googlemaps#923]
Hi there.
I am developing an Android App. I am using cordova version 6.1.1.

When using the external service in the plugin, when I go back from the opened Google Maps, the application did not stay on the last view, and basically restarts.

I already tried to use the latest version on git by removing the plugin from the projecto and doing `cordova plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps`

Any ideas to solve this?

Thank you.

**Comment by wf9a5m75** [comment]
I could not reproduce your issue.
https://youtu.be/4WUlpeSrgfc

In the above video, there is "full screen button" in the app, but it launches the external GoogleMaps.
(I reused some other code)

**Comment by clviper** [comment]
Hi there. You have a different scenario. Basically I have an html with various divs that correspond to various pages. I have navigate from page A to page B and in page B I trigger the external service. When I press back from the Google Maps it returns to the app but to the Page A.

**Comment by wf9a5m75** [comment]
Please make an example project.

**Comment by wf9a5m75** [comment]
@clviper If you don't provide an example project, we close this issue since we don't have enough information.
Thank you for your cooperation.

**Comment by clviper** [comment]
Hi there. Sorry for not giving feedback. In a hour or two I will leave here an example project.

**Comment by clviper** [comment]
I'm sorry. I found out the problem while trying to create a new sample project to send you. Nothing related to the plugin itself.
Thanks for the patience. 
Congrats on the plugin. Really awesome. Good work.

**Comment by wf9a5m75** [comment]
Thank you for following up, and thank you for using this plugin.
