### ISSUE TITLE
getCenter of the map

### ISSUE THREAD

**Issue by clembou590** [mapsplugin/cordova-plugin-googlemaps#924]
Hello.
How do you get the center of the map?
if it's not possible can you add this method?

Another question:
can I have one view displaying one map. And another view displaying another map?
When reading the docs it seems that it's not possible. please just confirm.

**Comment by wf9a5m75** [comment]
In this plugin, you can get the center position of the map through this code:

```js
map.getCameraPosition(function(camera) {
  var center = camera.target;
});
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#get-the-camera-position

or

```js
map.addEventListener(plugin.google.maps.event.CAMERA_CHANGE, function(camera) {
  var center = camera.target;
});
```

---

> two maps?

Not possible with this plugin.
