### ISSUE TITLE
How to add a search box in Map Dialog?

### ISSUE THREAD

**Issue by Dineshrajaa** [mapsplugin/cordova-plugin-googlemaps#925]
Is it possible to add a Search box to the Map Dialog if so what is the option that I need to send?kindly shed some light on this topic..

**Comment by wf9a5m75** [comment]
Please understand how this plugin display the map.
This plugin places the native map view **UNDER** the browser, so it is displayed **UNDER** any HTMLs always.
Thus, you can not display the map on your modal dialog.

However, if you use `map.showDialog()`, the native map view places **OVER** the browser, 
so the map view displays like a dialog.

**Comment by wf9a5m75** [comment]
Opps, I mis-read your question.
Regarding of the maps dialog (I guess you already use `map.showDialog()`), it does not have a browser layer.
So it's not possible to add any additional UI. Sorry.

**Comment by Dineshrajaa** [comment]
Ok @wf9a5m75 thanks I thought there will be option for that like we have for "MyLocation" etc.. Thanks for the awesome plugin :)
