### ISSUE TITLE
Reusing map between views

### ISSUE THREAD

**Issue by samuelgoldenbaum** [mapsplugin/cordova-plugin-googlemaps#926]
As the plugin returns a singleton instance of a map, is it worth attaching/detaching the map container div when moving between views?

With the JS plugin, I would detach the map from the current view and attach it to the body when moving between views. If the next view needed the map, it would grab it off the body and start to work with it. This sped up init and rendering.

**Comment by wf9a5m75** [comment]
`map.setDiv()` should detach the map, and `map.setDiv(mapDiv)` should attach the map again.

**Comment by wf9a5m75** [comment]
@samuelgoldenbaum Did you confirm this?

**Comment by samuelgoldenbaum** [comment]
Sorry, been tied up. Will check shortly
