### ISSUE TITLE
App crashes when I swipe on the map when a camera animation is running

### ISSUE THREAD

**Issue by jabas06** [mapsplugin/cordova-plugin-googlemaps#927]
Hi,

I'm getting this error on Android when I swipe on the map when a camera animation is running.

> 04-07 01:08:00.485 18090-18090/com.gasvip.mobile E/InputEventReceiver: Exception dispatching input event.
> 04-07 01:08:00.485 18090-18090/com.gasvip.mobile D/AndroidRuntime: Shutting down VM
> 04-07 01:08:00.488 18090-18090/com.gasvip.mobile E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                    Process: com.gasvip.mobile, PID: 18090
>                                                                    java.lang.IllegalStateException: Camera moved during a cancellation

I'm using:
- cordova 6.1
- cordova-android 5.1
- master branch of the maps plugin

**Comment by wf9a5m75** [comment]
I could not reproduce your issue.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <script type="text/javascript" src="cordova.js"></script>
      <script type="text/javascript">

        var map;

        document.addEventListener("deviceready", function() {
          var div = document.getElementById("map_canvas");

          const GOOGLE = new plugin.google.maps.LatLng(37.422858, -122.085065);

          // Initialize the map view
          map = plugin.google.maps.Map.getMap(div);

          // Wait until the map is ready status.
          map.addEventListener(plugin.google.maps.event.MAP_READY, function() {
            map.animateCamera({
              target: GOOGLE,
              zoom: 17
            });
          });
        }, false);

      </script>
      </head>
  <body>
    <h3>PhoneGap-GoogleMaps-Plugin</h3>
    <div style="width:100%;height:500px" id="map_canvas"></div>
  </body>
</html>
```
![ezgif-1539640809](https://cloud.githubusercontent.com/assets/167831/14358628/a34fb3b4-fca2-11e5-8b43-16e44dd448c2.gif)

Please provide an example project.

**Comment by wf9a5m75** [comment]
I read also here, but it looks like there is some problem in your code or just an incidential error.
http://stackoverflow.com/questions/15609671/java-lang-illegalstateexception-camera-moved-during-a-cancellation-happens-durn

**Comment by jabas06** [comment]
I've an app that crashes every time I swipe on the map when the animation is running. I'm trying to make a minimal repro to not to share my whole project, but the issue it's not reproducible in the new project. I'll try to figure out what's going on in my original project. So, you may want to close this issue until I'm able to reproduce it in a new project.

**Comment by jabas06** [comment]
I finally could reproduce it. The exception its thrown when the camera's target it's and array of points or an instance of LatLngBounds. This is the code. I'm testing on android Lollipop and:

cordova 6.1
cordova-android 5.1
master branch of the maps plugin

```javascript
angular.module('starter.controllers', [])
.controller('DashCtrl', function($scope, $window, $ionicPlatform) {
  $ionicPlatform.ready(function() {
    var mapDiv = document.getElementById("map_canvas");
    var map = $window.plugin.google.maps.Map.getMap(mapDiv);

     map.on($window.plugin.google.maps.event.MAP_READY, function () {
       var points = [
         new $window.plugin.google.maps.LatLng(41.79883, 140.75675),
         new $window.plugin.google.maps.LatLng(41.799240000000005, 140.75875000000002)
       ];

        map.animateCamera({
          target: points
        });
      });
  });
});

```

**Comment by wf9a5m75** [comment]
Since you use the master branch code (next version), you can write like this:

```js
var mapDiv = document.getElementById("map_canvas");
var map = $window.plugin.google.maps.Map.getMap(mapDiv, {
  camera: {
    target: [
      {lat: 41.79883, lng: 140.75675},
      {lat: 41.799240000000005, lng: 140.75875000000002}
    ]
  }
});

map.on($window.plugin.google.maps.event.MAP_READY, function () {
  
});
```

**Comment by wf9a5m75** [comment]
Ok, your issue is reproduced with your code.

**Comment by wf9a5m75** [comment]
The bug is fixed. Thank you for your report. 
Please reinstall this plugin from the master branch again.
