### ISSUE TITLE
How to use Google maps services like DirectionService with your plugin?

### ISSUE THREAD

**Issue by syeddanishali8080** [mapsplugin/cordova-plugin-googlemaps#928]
Hey,

Thank you so much for such a great plugin. I was wondering how to integrate other google maps services like DirectionService or DitanceMatrixService with your plugin. A short guide or tutorial will be a lot helpful. 

Thank you.

**Comment by wf9a5m75** [comment]
This plugin does not implement Google Maps Web APIs at this time.
Please implement them by yourself.

For HTTP requests, you can use these plugins:
https://github.com/wf9a5m75/phonegap-http-request
https://github.com/wymsee/cordova-HTTP
