### ISSUE TITLE
markerClick function is not executed

### ISSUE THREAD

**Issue by jabas06** [mapsplugin/cordova-plugin-googlemaps#929]
Hi,

I've an issue with the marker click event. If I define de click handler using the markerClick property, the function it's never executed, but the click handler works if I explicitly add an event listener.

doesn't work
```javascript

    map.on($window.plugin.google.maps.event.MAP_READY, function () {
       map.addMarker({
          'position': new $window.plugin.google.maps.LatLng(41.79883, 120.75675),
          'markerClick': function (marker) {
            alert('clic from markerClick');
          }
        });
      });
```
works
```javascript
     map.on($window.plugin.google.maps.event.MAP_READY, function () {
       map.addMarker({
          'position': new $window.plugin.google.maps.LatLng(41.79883, 120.75675)
        }, function(marker) {
          marker.addEventListener($window.plugin.google.maps.event.MARKER_CLICK, function(marker) {
              alert('clic from addEventListener');
           });
       });
    });
```

I'm using:

cordova 6.1
cordova-android 5.1
master branch of the maps plugin

**Comment by wf9a5m75** [comment]
It's the same as you do.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/googlemaps-cdv-plugin.js#L1063-L1065

**Comment by wf9a5m75** [comment]
Oh, somebody introduced this issue... I'm checking now.

**Comment by wf9a5m75** [comment]
Thank you for the report. The bug is fixed.
