### ISSUE TITLE
elements inside ui-view are not considered as child elements?

### ISSUE THREAD

**Issue by FatalTouch** [mapsplugin/cordova-plugin-googlemaps#930]
I have the following markup.

    <div id="map-canvas" class="map">
                <div ui-view></div>
            </div>

The elements that are inside the ui-view are not treated as child elements of the map div. i.e i can click through them to the map. Are the elements only added the first time the map is initialized? Because i am initializing the map one time in the parent view controller and getting the reference in all the child controllers. Because in my project i wanted to have map as a main view and place elements on it using different states by employing angular ui-routing.

if i set the height of ui-view div to 100% then i can not select the map but can select elements in the ui-div.

**Comment by wf9a5m75** [comment]
Confirm with this: https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#mapsetdebuggable

**Comment by FatalTouch** [comment]
After some testing, i found out that it only takes the dimensions of the first hierarchy child div and ignores the width or height properties of the children of the first hierarchy child. In this case it will ignore all the dimensions of the elements inside the ui-view div and just make the clickable area depending upon what i set for the width and height of the ui-view div.

**Comment by FatalTouch** [comment]
for ex.
I changed my structure to this for testing.

    <div id="map-canvas" class="map">
     <div id="centerMarker"><button ng-click="requestRide()" ng-hide="hideSearchButton"       
    class="button button-one-ryder"><ion-spinner ng-show="searchLoading" class="btn-spinner"    
     icon="spiral"></ion-spinner><span>&nbsp; {{searchText}}</span></button></div>
       </div>

The css for the elements is 

```
#centerMarker{
  position:absolute;
  /*url of the marker*/
  background:url(../img/user.png) no-repeat;
  background-size:50px 73px;
  /*center the marker*/
  top:50%;left:50%;
  z-index:1;
  /*fix offset when needed*/
  margin-left:-25px;
  margin-top:-73px;
  /*size of the image*/
  height:73px;
  width:50px;
  cursor:pointer;
}

  #centerMarker button{
      border-radius:50px;
      width:240px;
      margin-left:-90px;
      position:absolute;
  }
```

and this is the output

[img](https://cloud.githubusercontent.com/assets/8601052/14407933/2ad3bd4e-fefb-11e5-97e8-447eb3f8d0a3.png
)

as you can see. only the marker is non-clickable area. and the dimensions of the button inside it is completely ignored.

**Comment by wf9a5m75** [comment]
Try to add `data-clickable='true'` attribution to `<div id="centerMarker">`.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/googlemaps-cdv-plugin.js#L2389-L2392

**Comment by FatalTouch** [comment]
It doesn't affect anything, i could already click the marker. But if i tried to click on the button portion that is not on top of the marker. The click is sent to the map instead.

ex. img
[screenshot_2016-04-10-09-01-57](https://cloud.githubusercontent.com/assets/8601052/14408552/c921fa72-ff16-11e5-9bf7-cdefbe5026bc.png)

**Comment by wf9a5m75** [comment]
How about this?

```html
<div style="position:relative;width:xxx;height:xxx">
  <div  id="map-canvas" style="position:absolute;width:100%;height:100%"></div>
  <div id="centerMarker" style="left:xxx; top:xxx">...</div>
</div>
```

**Comment by FatalTouch** [comment]
Well none of this was supposed  to work because the plugin doesn't search anywhere except for all the first children. 

So i modified the getAllChildren method like this.

```
 var searchChildNodes = function (nodeName, depth) {
        if (depth < 3) {
            if (nodeName.hasChildNodes) {
                for (i = 0; i < nodeName.childNodes.length; i++) {
                    if (nodeName.childNodes[i].nodeType == 1) {
                        list.push(nodeName.childNodes[i]);
                        searchChildNodes(nodeName.childNodes[i], ++depth);

                    }
                }
            }
        }
    };


    
    var search = function(node) {
        while (node != null) {

            if (node.nodeType == 1) {
                style = window.getComputedStyle(node);
                visibilityCSS = style.getPropertyValue('visibility');
                displayCSS = style.getPropertyValue('display');
                opacityCSS = style.getPropertyValue('opacity');
                if (displayCSS !== "none" && opacityCSS > 0 && visibilityCSS != "hidden") {
                    clickable = node.getAttribute("data-clickable");
                    if (clickable &&
                        clickable.toLowerCase() === "false" &&
                        node.hasChildNodes()) {
                        Array.prototype.push.apply(list, getAllChildren(node));
                    } else {
                        list.push(node);
                        searchChildNodes(node, 1);
                    }
                }
            }
            node = node.nextSibling;
        }
    };```

Haven't checked the performance impact yet!

**Comment by wf9a5m75** [comment]
Thank you for inspecting. Please send as pull request.

**Comment by Nadejde** [comment]
@FatalTouch 
Hi,

I'm having the same problem as you and was trying to implement your solution. However after I change the file and copy it inside the plugin folder the map no longer loads (could be a javascript error I guess although I can't see any problems with the code). 
I've also tried doing a different change like this:
```
var search = function(node) {
        while (node != null) {
            if (node.nodeType == 1) {
                style = window.getComputedStyle(node);
                visibilityCSS = style.getPropertyValue('visibility');
                displayCSS = style.getPropertyValue('display');
                opacityCSS = style.getPropertyValue('opacity');
                if (displayCSS !== "none" && opacityCSS > 0 && visibilityCSS != "hidden") {
                    clickable = node.getAttribute("data-clickable");
                    if (//clickable &&
                        //clickable.toLowerCase() === "false" &&
                        node.hasChildNodes()) {
                        Array.prototype.push.apply(list, getAllChildren(node));
                    } else {
                        list.push(node);
                    }
                }
            }
            node = node.nextSibling;
        }
    };
```
But this also results in the map failing to load. I'm not sure what I'm doing wrong. Would welcome some guidance please!

Thank you.

**Comment by FatalTouch** [comment]
@Nadejde 
This is the modified js i am using right now.
try to see if this works for you.

https://drive.google.com/file/d/0B8rNr_oqeCv0NU80NUN5enk5eGM/view?usp=sharing

**Comment by Nadejde** [comment]
@FatalTouch 
Thank you for your help. It's working now. Don't know what I was doing wrong.
Now if I can only get it to work with a directive :)) 

Thanks alot again!

**Comment by Nadejde** [comment]
It wasn't because of the directive. It was because the object was outside the screen when the map was loaded. Will update if I figure it out. Thank you again.
