### ISSUE TITLE
Specifying "HTML color" for marker icon

### ISSUE THREAD

**Issue by jaredgreener** [mapsplugin/cordova-plugin-googlemaps#933]
This used to work:

var latlng = {lat: 33.115, lng: -117.23424};
var latlng = new plugin.google.maps.LatLng(latlng.lat, latlng.lng);
nativeMap.addMarker({
			position: latlng,
			icon: 'green',
			draggable: true
		});

Now it shows a blank marker.

var latlng = {lat: 33.115, lng: -117.23424};
var latlng = new plugin.google.maps.LatLng(latlng.lat, latlng.lng);
nativeMap.addMarker({
			position: latlng,
			draggable: true
		});

If I remove the icon property it works again and shows a standard red icon. Seems specifying a color is no longer working.

Thanks - your plugin is awesome!

**Comment by wf9a5m75** [comment]
Any error log?

**Comment by jaredgreener** [comment]
no error -- just a blank icon

**Comment by wf9a5m75** [comment]
Sorry for late. It's my mistake. The bug is fixed on the master branch.
