### ISSUE TITLE
getMyLocation() error callback

### ISSUE THREAD

**Issue by ZiFFeL1992** [mapsplugin/cordova-plugin-googlemaps#939]
I'm actually asking for permissions before going to map view, but in case the user doesn't grant permissions I get this error:

`my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION`

Is possible to have something like:

```
getMyLocation((success) => {
	//Found you!
}, (error) => {
	//Ask for permissions but user doesn't give them
	//Timeout, etc
});
```

I know I can do it with another plugin checking if I have permissions, but this might be a good option because it will avoid just fail and display blank map.

Tested on Android 6+.

**Comment by wf9a5m75** [comment]
getMyLocation treats the last argument as error callback.
And if user denied, you should get the message "Geolocation permission request was denied".

**Comment by ZiFFeL1992** [comment]
The matter is that I use Geolocation plugin in the first view, if I denied the permissions, I spect this plugin to ask me for permissions, but it doesn't, just through the error I mention in the first comment, seems like is not forcing to ask for permissions again.

**Comment by wf9a5m75** [comment]
I confirmed this plugin check every time, and the below code appears the location request dialog two times.

https://www.youtube.com/watch?v=NFW-UPmJVVM

```js
navigator.geolocation.getCurrentPosition(function(position) {
  alert("ok:" + JSON.stringify(position));
}, function(error) {
  map.getMyLocation(function(result) {
    alert("ok2:" + JSON.stringify(result));
  }, function(error) {
    alert("error:" + error);
  });
});
```

It means the problem is in your project, not this plugin.

**Comment by ZiFFeL1992** [comment]
Is mandatory to have Location permissions in order to load the map? I have the following:

![image](https://cloud.githubusercontent.com/assets/5492960/14582169/171f6692-03fe-11e6-92c4-cfd2a4c21d32.png)

With location permissions the map load successfully, but without them I get a blank screen with the following error in console:

`my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION`

As you can see I'm not asking for permissions, but the plugin seems to be using them.

**Comment by wf9a5m75** [comment]
This plugin does not ask the geolocation permission until you use getMyLocation() or other enable mylocatiommn button.

**Comment by wf9a5m75** [comment]
Ok, I added some code in order to check location permission for `mapOptions.controls.myLocationButton`.
Retry the master branch.

Again, this plugin does not ask the geolocation permission until if you set `mapOptions.controls.myLocationButton = true` or use `map.getMyLocation()` method.
