### ISSUE TITLE
Geocoder -  different position on Android and IOS

### ISSUE THREAD

**Issue by Omnitasker** [mapsplugin/cordova-plugin-googlemaps#942]
I work with phonegap build.
When using geocoder in Android I get precise position of location in format:
` {"lng": -0.1278191, "lat": 51.5109455 }`
and in IOS I got position that is inaccurate about 50 m in format:
` {"lat":51.51080950231084, "lng": -0.128126600}
`

Is there anything I can do with this?

**Comment by wf9a5m75** [comment]
This plugin just passes the request data to Google or Apple, then receives their results.
So you can not do anything about that, and it's not related with this plugin.

**Comment by Hirbod** [comment]
Well, Android use Google and iOS use Apples Internal. I guess there is nothing we can do. The only chance for you to have same results on both systems would be to use the JS v3 API for geocoding
