### ISSUE TITLE
Question: When dragging a marker to the edge of a map, should the map pan to accommodate the marker?

### ISSUE THREAD

**Issue by samuelgoldenbaum** [mapsplugin/cordova-plugin-googlemaps#943]
Question: When dragging a marker to the edge of the map bounds, should the map pan over to accommodate the marker? Currently, you cannot drag a marker beyond the bounds of the map. The marker simply drops at the bounds of the map.

**Comment by wf9a5m75** [comment]
This plugin does not manage dragging action at all. Just passes the events: `drag_start` and `drag_end`.
So the map does not pan automatically, it's a spec.

**Comment by samuelgoldenbaum** [comment]
Thanks for the reply Masashi. 

Going to try throttle a function inside the DRAG event and simply call map.setCenter(). I'll update here with a solve that others may find useful.

**Comment by wf9a5m75** [comment]
Since I prefer the number of issues list is small (even question), I close this issue file at once.
But you can update this with new information, or sending a pull request.
