### ISSUE TITLE
Random bug on launch 

### ISSUE THREAD

**Issue by Hurinj** [mapsplugin/cordova-plugin-googlemaps#944]
Hello there,

I don't know if someone already had this kind of bug : 
- On the first launch "cordova run ios/android" my map is fully white, but if i run again "cordova run ios" the map appears and there is no problem. Same happens on my phone, it is really weird.
- Is there something that can bug the map when i initialise it ? 

Thank you.

**Comment by ZiFFeL1992** [comment]
Which version of this plugin do you have?

**Comment by Hurinj** [comment]
seems to be 1.3.9

**Comment by Hirbod** [comment]
This random bug is fixed in master and will be incorporated in the upcoming 1.4.0

**Comment by ffabreti** [comment]
@Hirbod  
Do You mind pointing to the commit that fix this issue? Thank you.
