### ISSUE TITLE
Implemente native map for different platform

### ISSUE THREAD

**Issue by Afondevi** [mapsplugin/cordova-plugin-googlemaps#946]
Hi,

I would like to know if you think update your plugin to do like this : https://www.npmjs.com/package/mapkit

And have Apple map for iOS, google map for android and bing map for windows phone ?
I hope really because your plugin work good and if you can add this speciality inside for each platform, that can be really nice for me and maybe for a lot of person :)

thanks for reading !
Alex

**Comment by wf9a5m75** [comment]
I'm not interested in at all. It might be nice for you and maybe for a lot of person, so please try the great task by yourself :)

**Comment by SeanHub** [comment]
Any reason for not supporting iOS MapKit? No restrictions on its use for iOS. Google Maps has SDK restrictions.
