### ISSUE TITLE
Provide TrafficLayer integration

### ISSUE THREAD

**Issue by fmsouza** [mapsplugin/cordova-plugin-googlemaps#950]
Google Maps SDK already provides a TrafficLayer class (at least in Android SDK) which can be set to the map to show a traffic layer over the map. It'd be nice to have this feature here.

**Comment by wf9a5m75** [comment]
This plugin is full open source. Please fork the repository, and implement by yourself at first.
Then we appreciate if you send a pull request.
Best

**Comment by fmsouza** [comment]
I was already thinking about it. But I only know how to do this for Android. Can I send a PR even without iOS implementation?

**Comment by wf9a5m75** [comment]
This plugin focus on providing the same features for both Android and iOS.
That's why you can customise the folk version, but we don't implement it.

**Comment by fmsouza** [comment]
Ok. Maybe I'll talk to a friend that develops to iOS and ask him to help me on this task.
