### ISSUE TITLE
Foreground tracking not reliable?

### ISSUE THREAD

**Issue by brudidier** [mapsplugin/cordova-plugin-googlemaps#951]
Hi there!

I am experiencing some issues with your awesome plugin (thanks again for your contribution)
FYI I edited it in order to remove the stationary filter and co, as I didn't need it.

Here is what I've noticed based on my test and other users feedback: 
Geolocation when the app is in background, both Android and iOS is working great BUT, it seems like when the app is in foreground even though I can see the **arrow** on iOS or the **Background notification** on Android, i HAVE to go to the background and then to foreground again in order for the app to send positions to the server.
If I don't toggle the background/foreground mode, it seems like it's running, but not sending any position.
Any idea of what could be happening?

Worst case, could I just start the plugin when the app goes to background and use navigator.watchPosition in foreground? How would I do this and avoid the plugin + HTML5 geoloc to run at the same time?

Thanks a lot!

**Comment by wf9a5m75** [comment]
Use this: https://github.com/transistorsoft/cordova-background-geolocation-lt

**Comment by brudidier** [comment]
Thanks for your reply...seems like I was tired and posted this message on the wrong github repo!
