### ISSUE TITLE
Privacyscreen compatibility issues on ios

### ISSUE THREAD

**Issue by Alex-Sessler** [mapsplugin/cordova-plugin-googlemaps#953]
Hi,

I'm using your gmaps plugin along with multiple other plugins. Since updating to master (i need cordova ios 4+ support), I noticed that there are compatibility issues with the privacy screen plugin (https://github.com/devgeeks/PrivacyScreenPlugin) on ios. That is, before the privacy screen plugin was creating an overlay with the splashscreen image and displaying it in the app switcher instead of the content when the app was in the background. But now, the only thing displayed is a black screen.
Any help/info on this issue?

Thanks a lot!

**Comment by wf9a5m75** [comment]
We are really busy, so we don't check the compayibility with other plugins.

**Comment by Alex-Sessler** [comment]
I managed to fix this in the privacyscreen plugin, so this is fine with me
