### ISSUE TITLE
iOS: Custom Markers not showing on Master

### ISSUE THREAD

**Issue by Alex-Sessler** [mapsplugin/cordova-plugin-googlemaps#954]
Hi,

I've been using the Plugin for a few months now and use it to display different locations through custom image markers. Since i'm working on upgrading my project to cordova ios > 4.x, i've switched to master. Unfortunately the markers are not showing any more, although the success callback is being called on the addMarker() function. Could this be a bug or did you change the API recently or something?

Fwiw, when changing back to my old cordova version (5.4.1) and cordova-ios version (3.9.1), the markers were not showing as well with the master version.

Also, do you have any idea when you'll release a stable 1.4.0 version?

Thanks a lot!

**Comment by wf9a5m75** [comment]
I think there is still remaining the old plugin.
Please remove the old version completely before install the master version.

**Comment by Alex-Sessler** [comment]
Okay, so I went ahead and compared the master version to the 1.3.9 release. I saw you changed a lot in the Marker.m class, especially concerning the visible flag.
I was able to get regular markers (not the custom images) to show by re-adding the following lines in line 29:
`if ([[json valueForKey:@"visible"] boolValue] == true) {
        marker.map = self.mapCtrl.map;
    }`

**Comment by wf9a5m75** [comment]
Please provide example js code that reproduce your issue.

**Comment by Alex-Sessler** [comment]
Btw, android is showing the markers and behaving normally.

I'm using the following code in the js side (I cannot give you a full example because i'm working on a productive app):

```
div = document.getElementById('map_canvas');

map = googleMaps.Map.getMap(div, {
          'backgroundColor': 'white',
          'mapType': googleMaps.MapTypeId.ROADMAP,
          'controls': {
            'compass': true,
            'myLocationButton': true,
            'indoorPicker': false,
            'zoom': false
          },
          'gestures': {
            'scroll': true,
            'tilt': false,
            'rotate': true,
            'zoom': true
          },
          'camera': {
            'latLng': new googleMaps.LatLng(46.801111, 8.226667),
            'zoom': 8,
          }
        });

      map.addMarker({
        position: new googleMaps.LatLng(
          46.801111,
           8.226667
        ),
        icon: {
          url: 'www/assets/images/map_marker.png',
          size: { width: 20, height: 20 },
          anchor:  [10, 10],
        },
        zIndex: 1
```

**Comment by Alex-Sessler** [comment]
I did some debugging and found out, that the custom icon is not found in the filesystem. This is probably closely related to the changes in cordova-ios4... when i remove the custom icon, it correctly displays the default icons.

**Comment by beastmike1** [comment]
Whaiting for the fix :+1:  ty man!

**Comment by Alex-Sessler** [comment]
@beastmike1 what cordova/cordova-ios/ios versions did you get this bug on?

**Comment by beastmike1** [comment]
I'm using ionic, and that are my versions:

$ ionic info
Your system information:

Cordova CLI: 6.1.1
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.3 Build version 7D175 

$ cordova platform
Installed platforms:
  ios 4.1.1

$ cordova plugin ls
(among other)
com.googlemaps.ios 1.13.0 "Google Map iOS SDK for Cordova"
cordova-plugin-googlemaps 1.3.9 "phonegap-googlemaps-plugin"

**Comment by Alex-Sessler** [comment]
thanks. I'll do the PR later today

**Comment by Alex-Sessler** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/956

**Comment by beastmike1** [comment]
I did changed the changes on the PR and it didn't worked but then I realized than there was more changes between my file Marker.m and the one from the PR and then I replaced the whole file and it worked at the first try. Thank you very much @Alex-Sessler

**Comment by diegognt** [comment]
IS this fixed? Im having the same issue using master...

**Comment by Alex-Sessler** [comment]
You can either manually apply the changes of my PR to your local repo or ask the developers to merge my PR into master

**Comment by mudolab** [comment]
=S is fixed???? XP

**Comment by alexislg2** [comment]
Same issue here. Will you merge the PR?

**Comment by blckshrk** [comment]
It looks like there is a similar bug on Android. Custom icons aren't displayed (classic red icons appear instead).

**Comment by arielgelbard** [comment]
any updates on the issue?

**Comment by arielgelbard** [comment]
???

**Comment by vosecek** [comment]
@arielgelbard Make sure you have not space in App name, this cause the same problem (file not found according to XCode console with map.setDebuggable(true).

**Comment by arielgelbard** [comment]
That worked, thanks! the next question now is how can I have custom markers for iOS with the app name having spaces? Can we tell Apple to patch this?

**Comment by arielgelbard** [comment]
That worked, thanks! Found a plugin that allows spaces for the app name visually [https://github.com/blakgeek/cordova-plugin-app-name](https://github.com/blakgeek/cordova-plugin-app-name)

**Comment by vosecek** [comment]
@arielgelbard Nice, plugin-app-name works well 🎆

**Comment by Krishna25Vrinsoft** [comment]
Can anyone please help me. i m facing the same issue. custom marker is not showing

**Comment by vosecek** [comment]
Enable debuggable mode as mentioned above and check the XCode console for errors.

**Comment by blckshrk** [comment]
@Krishna25Vrinsoft Try to check the url on your marker image file. This is stupid, but I forgot the "www/".

**Comment by wf9a5m75** [comment]
The plugin v2-beta version does not need to "www/" anymore.
And relative path is available.
The v1.x will be shutdown in the near future. Please start to use v2-beta version.

**Comment by blckshrk** [comment]
Hi, 

Have you a change log for the v2? 

Thx

**Comment by ZiFFeL1992** [comment]
Check the wiki @blckshrk :

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta
