### ISSUE TITLE
Cordova 6.1.0 version, ios build failed.

### ISSUE THREAD

**Issue by LucasNova** [mapsplugin/cordova-plugin-googlemaps#955]
Hello, google-maps-plugin on Cordova 6.1.0 with iOS platform not working, i can't build app, see errors:

.../GoogleMaps.m:176:59: error: no known instance method for selector
      'initWithWebView:'

.../GoogleMaps.m:245:68: error: no known instance method for selector
      'initWithWebView:'
                pluginClass = [[NSClassFromString(className)alloc] initWithWebView:self.webView];

.../GoogleMaps.m:321:19: error: no visible @interface for 'UIView' declares
      the selector 'stringByEvaluatingJavaScriptFromString:'
    [self.webView stringByEvaluatingJavaScriptFromString:jsString];

.../GoogleMapsViewController.m:10:9: fatal error: 'Cordova/CDVJSON.h' file
      not found

P.S Adding "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" in X-Code "Header search paths" not resolve problem.

**Comment by LucasNova** [comment]
Sorry, on the latest version of plugin, Cordova build is successful. Solution: You need use "cordova plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps" instead of "cordova plugin add cordova-plugin-googlemaps".

**Comment by duluca** [comment]
@LucasNova It'd be great if this information was available a bit more front and center in the documentation. None of the samples currently work without adding the plugin in this manner on ios.
