### ISSUE TITLE
weird vertical line

### ISSUE THREAD

**Issue by fmendoza** [mapsplugin/cordova-plugin-googlemaps#958]
See attached screenshot. It's only happening on Android. iOS is working good. I'm not sure if is related, but I'm using crosswalk.

Any ideas?

![screenshot_2016-05-04-11-22-59](https://cloud.githubusercontent.com/assets/1320696/15021378/04051380-11ec-11e6-8f1e-07d92a3ee074.png)
![screenshot_2016-05-04-11-23-24](https://cloud.githubusercontent.com/assets/1320696/15021379/056ac27e-11ec-11e6-8496-5c6616bf3d97.png)

**Comment by wf9a5m75** [comment]
Is this reproduce on another Android?

**Comment by xloading** [comment]
@wf9a5m75, yes, I see the same line on Genymotion emulator.
btw I'm using Ionic

**Comment by wf9a5m75** [comment]
I tested couple of times, but not reproduced.
As you may know, **this plugin changes the &lt;body&gt; background as transparent**,
and the ionic framework places the side menu **UNDER** the background.
So it maybe come from the ionic.

**Comment by xloading** [comment]
@wf9a5m75, Indeed that was the issue with Ionic side menu's scroll bar.
I used the following dirty hack to fix it:
```js
function($scope, $rootScope, $ionicSideMenuDelegate) {
    $rootScope.side_menu = document.getElementsByTagName("ion-side-menu")[0];
    $rootScope.ion_content = $rootScope.side_menu.getElementsByTagName("ion-content")[0];
    /*$rootScope.$on('$stateChangeSuccess', function (event, toState, toParams, fromParams, toParams) {
      if (toState.name != 'menu.home') {
        $rootScope.side_menu.style.visibility = "visible";
      }
    });*/
    $scope.$watch(function() {
      return $ionicSideMenuDelegate.isOpen();
    }, function(value) {
      if(value === true){
        $rootScope.side_menu.style.visibility="visible";
        $rootScope.ion_content.style["overflow-y"]="scroll";
      } else{
        $rootScope.side_menu.style.visibility="hidden";
        $rootScope.ion_content.style["overflow-y"]="hidden";
      }
    });
```
