### ISSUE TITLE
Map not displaying in normal view but displaying in full screen dialog

### ISSUE THREAD

**Issue by AlexandreVaudelin** [mapsplugin/cordova-plugin-googlemaps#962]
Hi there, I'm having a little problem with your plugin.

I followed all the steps to install and make the plugin works and I just copy/pasted the code I [found here](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Windows) .

So I should have the first view with a fully customizable map and a fullscreen dialog when I click the button "full screen".
When I run the application, nothing is displaying on the first map (really nothing, not even the google logo or the zoom buttons), but when I click "full screen", the map works perfectly and I can do what I want in it. 

I checked my API key, all is good, I even see the requests from the fullscreen map in Google Developper Tools.

Last thing I can precise is that I don't use emulator, I'm running it on my own smartphone.

Thanks in advance for all help you can provide.

Alex.

**Comment by wf9a5m75** [comment]
Most of this case, the problem is in your code or project. Please try again with the **master branch (not npm)**.

**Comment by jeffreyrajanofficial** [comment]
try to remove this code map.showDialog();
