### ISSUE TITLE
IOS 9.3.1 has extra space on top

### ISSUE THREAD

**Issue by Furqankhanzada** [mapsplugin/cordova-plugin-googlemaps#963]
![slack for ios upload](https://cloud.githubusercontent.com/assets/2400215/15148403/84300f50-16de-11e6-9781-47c9c770844e.jpg)

Its working fine on android. but not on IOS 9.3.1 i have checked on iphone 6s and 4s.

**Comment by roblav96** [comment]
I don't believe this has anything to do with this plugin.

Check your config.xml for statusbar plugin settings.

**Comment by Furqankhanzada** [comment]
@roblav96 what exactly i need to do on config.xml for statusbar plugin setting ?

**Comment by roblav96** [comment]
Idk, but check the docs and play around with padding

**Comment by Furqankhanzada** [comment]
@roblav96 : i am doing it form 9 days but nothing works only this solution is working https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/657#issuecomment-162517262 
but i think it's not the proper way.

**Comment by roblav96** [comment]
Play with CSS

**Comment by Furqankhanzada** [comment]
@roblav96 : it's not the css issue. i have tried but its not working.

**Comment by roblav96** [comment]
Idk what to tell ya. sorry

**Comment by wf9a5m75** [comment]
Please test this plugin **WITHOUT** other plugins (such as status bar plugin). Even if the issue is reproduced, I will inspect it.
