### ISSUE TITLE
Still getting White Screen with 1.3.9

### ISSUE THREAD

**Issue by cwoolum** [mapsplugin/cordova-plugin-googlemaps#966]
I've been following all of the issue with white screen and all of the resolutions and I'm still having the white screen issue. Here is my config.xml

```
<preference name="webviewbounce" value="false" />
  <preference name="loadUrlTimeoutValue" value="99999999" />
  <preference name="UIWebViewBounce" value="false" />
  <preference name="DisallowOverscroll" value="true" />
  <preference name="android-minSdkVersion" value="17" />
  <preference name="BackupWebStorage" value="cloud" />
  <preference name="KeepRunning" value="True" />
  <preference name="ShowTitle" value="False" />
  <preference name="InAppBrowserStorageEnabled" value="False" />
  <preference name="SuppressesIncrementalRendering" value="False" />
  <preference name="AndroidLaunchMode" value="singleTop" />
  <preference name="Fullscreen" value="True" />
  <preference name="Orientation" value="portrait" />
  <preference name="SplashScreen" value="screen" />
  <preference name="SplashScreenDelay" value="3000" />
  <preference name="xwalkVersion" value="18+" />
  <preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect" />
  <preference name="xwalkMode" value="embedded" />
  <preference name="xwalkMultipleApk" value="true" />
  <preference name="target-device" value="handset" />
  <preference name="xwalkZOrderOnTop" value="true" />
  <allow-navigation href="*" />
  <feature name="StatusBar">
    <param name="ios-package" onload="true" value="CDVStatusBar" />
  </feature> 
  <plugin name="cordova-plugin-actionsheet" version="2.2.2" />
  <plugin name="cordova-plugin-app-event" version="1.2.0" />
  <plugin name="cordova-plugin-camera" version="2.1.1" />
  <plugin name="cordova-plugin-console" version="1.0.2" />
  <plugin name="cordova-plugin-contacts" version="2.0.1" />
  <plugin name="cordova-plugin-crosswalk-webview" version="1.4.0" />
  <plugin name="cordova-plugin-device" version="1.1.1" />
  <plugin name="cordova-plugin-dialogs" version="1.2.0" />
  <plugin name="cordova-plugin-facebook4" version="1.7.0" />
  <plugin name="cordova-plugin-file" version="4.1.1" />
  <plugin name="cordova-plugin-file-transfer" version="1.5.0" />
  <plugin name="cordova-plugin-geolocation" version="2.1.0" />
  <plugin name="cordova-plugin-globalization" version="1.0.3" />
  <plugin name="cordova-plugin-inappbrowser" version="1.3.0" />
  <plugin name="cordova-plugin-splashscreen" version="3.0.0" />
  <plugin name="cordova-plugin-whitelist" version="1.2.1" />
  <plugin name="cordova-plugin-googlemaps" version="1.3.9" />
  <plugin name="de.appplant.cordova.plugin.local-notification" version="0.8.4" />
  <plugin name="ionic-plugin-keyboard" version="2.0.1" />
  <plugin name="phonegap-plugin-push" version="1.6.2" />
  <plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" version="3.0.1" />
  <plugin name="cordova-plugin-ms-azure-mobile-apps" version="2.0.0-beta4" />
  <plugin name="cordova-plugin-hockeyapp" version="2.2.2" />
  <plugin name="cordova-plugin-googleplus" version="4.0.8" />
  <plugin name="cordova-plugin-statusbar" version="2.1.3" />
  <plugin name="cordova-plugin-x-toast" version="2.5.1" />
  <plugin name="plugin.google.maps" version="1.3.9" />
```

I've reset all of my plugins and I know the api key is correct because I can see the requests in the google api dashboard. What should I be looking for in logcat?

**Comment by ZiFFeL1992** [comment]
@cwoolum have you tried master branch?

**Comment by cwoolum** [comment]
Yes, no change. Logging shows the message 'The animation is done'

**Comment by nunomsh** [comment]
I had same problem in android. It was related to the api keys. I was using the production key in debug mode, so the result was a blank map with "google" in bottom left. Although booth keys maybe correct, when using "ionic run android" -- uses development key;
If I sign the app ready for submit, uses the production key

**Comment by cwoolum** [comment]
I pretty sure the key is correct because I'm seeing the API calls getting
made in the Google Api explorer. I haven't even tried testing with a
production key yet.

I'm not even getting Google in the bottom left. It is literally just a
white screen.

**Comment by ZiFFeL1992** [comment]
@cwoolum can you see the code generated by the plugin? Or just your div? Did you set css properties?

**Comment by cwoolum** [comment]
I can only see the div I call it on. I'm setting height and width.

```
<div style="width:100vw;height:400px"></div>
```

**Comment by cwoolum** [comment]
I can only see the div I call it on. I'm setting height and width.

````
<div style="width:100vw;height:400px"></div>
````

**Comment by cwoolum** [comment]
Sorry, I was mistaken. I'm actually getting plugin specific classes.

````
<div class="_gmaps_cdv_" style="width:100vw;height:400px;background-color:rgba(0, 0, 0, 0)"></div>
````

**Comment by cwoolum** [comment]
I figured out the issue. I was calling getMap and passing in a custom directive that i had created for Ionic. The plugin needs the dom element passed in using document.getElementById. Changing it to use this fixed the problem

**Comment by miumi-u** [comment]
I had the different issue with blank view. I think this should be mentioned somewhere in docs, that devs should keep in mind that whole views hierarchy will have to become transparent in order to display the map. I had couple of screens background colour set with a flag important, which was not overridden by maps classes. After removing the important flag, I could see the map.

Hope this will help somebody in the future.

**Comment by hungca** [comment]
@cwoolum How to you fix it ?

**Comment by kanishkamehta801** [comment]
I'm still facing the same problem. Only white screen is coming, no maps are displaying, no errors are there. I am also not able to see Google written on the bottom of the page. I am having this issue on v1.4.0
