### ISSUE TITLE
map not show marker when API 23

### ISSUE THREAD

**Issue by aucifer16** [mapsplugin/cordova-plugin-googlemaps#967]
My code it work when test android 5 but not work api 23 I try use cordova.plugins.diagnostic but not work... pls help me thank....
    document.addEventListener("deviceready", function() {
cordova.plugins.diagnostic.requestRuntimePermissions(function(statuses){
			var div = document.getElementById("map_canvas");

      // Initialize the map view
      map = plugin.google.maps.Map.getMap(div);

      // Wait until the map is ready status.
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
	  	map.getMyLocation(function(location) {
		 yourLocation = location.latLng;
		 alert(yourLocation);
       map.addMarker({
    'position': location.latLng,
	'title': "Currtent your location"
  }, function(marker) {
   marker.showInfoWindow();
   map.animateCamera({
        'target': location.latLng,
        'zoom': 19
      }, function() {
       
      });
	  
  });
});

//call markers
const Google = new plugin.google.maps.LatLng(13.879386, 100.590530);
Destination=Google;
map.addMarker({
  'position': Google,
}, function(marker) {
 marker.showInfoWindow();
});		 
    for (var permission in statuses){
        switch(statuses[permission]){
            case cordova.plugins.diagnostic.runtimePermissionStatus.GRANTED:
                console.log("Permission granted to use "+permission);
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.NOT_REQUESTED:
                console.log("Permission to use "+permission+" has not been requested yet");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED:
                console.log("Permission denied to use "+permission+" - ask again?");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED_ALWAYS:
                console.log("Permission permanently denied to use "+permission+" - guess we won't be using it then!");
                break;
        }
    }
}, function(error){
    console.error("The following error occurred: "+error);
},[
    cordova.plugins.diagnostic.runtimePermission.ACCESS_FINE_LOCATION,
    cordova.plugins.diagnostic.runtimePermission.ACCESS_COARSE_LOCATION
]);
 }, false);

**Comment by wf9a5m75** [comment]
Try with the master branch.

**Comment by aucifer16** [comment]
Sorry i ask stupid questions. What master branch?

**Comment by ZiFFeL1992** [comment]
@aucifer16 
`cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git`

**Comment by aucifer16** [comment]
I try new plugin from cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git but still not work not show marker at android api 23 (it can work only android below api23)
you can test apk at https://drive.google.com/file/d/0BzWUo4PPLZu-aW9Ya3pyZ3QxbTg/view?usp=sharing

my code
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="cordova.js"></script>
	 <script type="text/javascript" src="index.js"></script>
    <script type="text/javascript">
    var map;
	var yourLocation = null;
	var Destination=null;
	var latitude =null ;
    var longitude= null ; 
    document.addEventListener("deviceready", function() {
			 cordova.plugins.diagnostic.requestRuntimePermissions(function(statuses){
			 
			       var div = document.getElementById("map_canvas");

      // Initialize the map view
      map = plugin.google.maps.Map.getMap(div);

      // Wait until the map is ready status.
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);

	  	map.getMyLocation(function(location) {
		 yourLocation = location.latLng;
		 //const ss = new plugin.google.maps.LatLng(13.879386, 100.590220);
		 //yourLocation=ss;
		   latitude =location.latLng.lat;
			longitude = location.latLng.lng;
			yourLocation =latitude+","+longitude;
	
       map.addMarker({
    'position': location.latLng,
	'title': "Currtent your location"
  }, function(marker) {
   marker.showInfoWindow();
   map.animateCamera({
        'target': location.latLng,
        'zoom': 19
      }, function() {
       
      });
	  
  });
});

//call markers

const Google = new plugin.google.maps.LatLng(13.879386, 100.590530);
Destination=Google;
map.addMarker({
  'position': Google,
}, function(marker) {
 marker.showInfoWindow();
});
			 
    for (var permission in statuses){
        switch(statuses[permission]){
            case cordova.plugins.diagnostic.runtimePermissionStatus.GRANTED:
                console.log("Permission granted to use "+permission);
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.NOT_REQUESTED:
                console.log("Permission to use "+permission+" has not been requested yet");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED:
                console.log("Permission denied to use "+permission+" - ask again?");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED_ALWAYS:
                console.log("Permission permanently denied to use "+permission+" - guess we won't be using it then!");
                break;
        }
    }
}, function(error){
    console.error("The following error occurred: "+error);
},[
    cordova.plugins.diagnostic.runtimePermission.ACCESS_FINE_LOCATION,
    cordova.plugins.diagnostic.runtimePermission.ACCESS_COARSE_LOCATION
]);


    }, false);

	function SearchMap(){
	      if (confirm("Do you want to go?")) {
        plugin.google.maps.external.launchNavigation({
          "from": yourLocation,
          "to": "13.879386, 100.590530"
        });
      }
	}
    function onMapReady() {
      var button = document.getElementById("button");
      button.addEventListener("click", onBtnClicked, false);
    }

    function onBtnClicked() {
     // map.showDialog();
	 SearchMap();
    }

    </script>
  </head>
  <body>
    <h3>GoogleMaps-Test</h3>
    <div style="width:100%;height:400px" id="map_canvas"></div>
    <button id="button">Goto</button>
  </body>
</html>

**Comment by aucifer16** [comment]
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="cordova.js"></script>
	 <script type="text/javascript" src="index.js"></script>
    <script type="text/javascript">
    var map;
	var yourLocation = null;
	var Destination=null;
	var latitude =null ;
    var longitude= null ; 
    document.addEventListener("deviceready", function() {
			 cordova.plugins.diagnostic.requestRuntimePermissions(function(statuses){
			 
			       var div = document.getElementById("map_canvas");

      // Initialize the map view
      map = plugin.google.maps.Map.getMap(div);

      // Wait until the map is ready status.
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);

	  	map.getMyLocation(function(location) {
		 yourLocation = location.latLng;
		 //const ss = new plugin.google.maps.LatLng(13.879386, 100.590220);
		 //yourLocation=ss;
		   latitude =location.latLng.lat;
			longitude = location.latLng.lng;
			yourLocation =latitude+","+longitude;
	
       map.addMarker({
    'position': location.latLng,
	'title': "Currtent your location"
  }, function(marker) {
   marker.showInfoWindow();
   map.animateCamera({
        'target': location.latLng,
        'zoom': 19
      }, function() {
       
      });
	  
  });
});

//call markers

const Google = new plugin.google.maps.LatLng(13.879386, 100.590530);
Destination=Google;
map.addMarker({
  'position': Google,
}, function(marker) {
 marker.showInfoWindow();
});
			 
    for (var permission in statuses){
        switch(statuses[permission]){
            case cordova.plugins.diagnostic.runtimePermissionStatus.GRANTED:
                console.log("Permission granted to use "+permission);
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.NOT_REQUESTED:
                console.log("Permission to use "+permission+" has not been requested yet");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED:
                console.log("Permission denied to use "+permission+" - ask again?");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED_ALWAYS:
                console.log("Permission permanently denied to use "+permission+" - guess we won't be using it then!");
                break;
        }
    }
}, function(error){
    console.error("The following error occurred: "+error);
},[
    cordova.plugins.diagnostic.runtimePermission.ACCESS_FINE_LOCATION,
    cordova.plugins.diagnostic.runtimePermission.ACCESS_COARSE_LOCATION
]);


    }, false);

	function SearchMap(){
	      if (confirm("Do you want to go?")) {
        plugin.google.maps.external.launchNavigation({
          "from": yourLocation,
          "to": "13.879386, 100.590530"
        });
      }
	}
    function onMapReady() {
      var button = document.getElementById("button");
      button.addEventListener("click", onBtnClicked, false);
    }

    function onBtnClicked() {
     // map.showDialog();
	 SearchMap();
    }

    </script>
  </head>
  <body>
    <h3>GoogleMaps-Test</h3>
    <div style="width:100%;height:400px" id="map_canvas"></div>
    <button id="button">Goto</button>
  </body>
</html>

**Comment by wf9a5m75** [comment]
I think the problem is in your project. Please test this plugin **WITHOUT** other plugins using **SIMPLE CODE**.

**Comment by chillyprig** [comment]
You need to bind your marker code inside:

`map.addEventListener(plugin.google.maps.event.MAP_READY, function () { } )`

This help me.
