### ISSUE TITLE
Integration with Admob Pro Plugin

### ISSUE THREAD

**Issue by BeDave** [mapsplugin/cordova-plugin-googlemaps#968]
Hi, i'm running into the same issue described in #938 (map disappear when showing the banner)
Sorry for the double post, I'm not sure if I have to open a new issue or just reply to the closed one.

I have some more information about that.
I'm using cordova 4.0.0, cordova android 5.1.1, latest crosswalk version.

It happens when calling showBanner function of Admob plugin which is actually resizing the webview. This is not happening when setting the banner properties to overlap the webview neither when showing another view (as an interstitial ad) which is not resizing the webview.
This should mean something is happening to the map when the view is resized.

I also set the backgrond of all android activities to Theme.Translucent.NoTitleBar, but this is not removing the issue: what i'm facing to is a transparent view where it should be the map (i can see device home throght it) as soon as i call showBanner function. This meaning it should not be a problem of transparent background.

Are you able to reproduce a situation in which the webview is resized and see what's going on?

Let me know if i can provide other info which are useful to reproduce this.

**Comment by wf9a5m75** [comment]
Since I'm too busy on working for new feature, I don't support the compatibility with another plugins.
Please inspect the plugin deeply by yourself.
