### ISSUE TITLE
Map.setTilt() on Android doesn't allow the tilt to be zero

### ISSUE THREAD

**Issue by JeffreyJamesMMM** [mapsplugin/cordova-plugin-googlemaps#970]
I need to reset tilt programmatically and the [Map.setTilt wiki page](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.setTilt()) states that tilt can be between 0 and 45 degrees.

However, with Android (I have not checked iOS) setting the tilt to 0 yields an error from native code stating "Invalid tilt angle(0.0)". I looked at PluginMap.java and the check inside of setTilt() looks like this: "tilt > 0 && tilt <= 90". It should be "tilt => 0 && tilt <= 90".

**Comment by wf9a5m75** [comment]
Got it.

**Comment by wf9a5m75** [comment]
Sorry, I forgot this issue for a while.

**Comment by wf9a5m75** [comment]
@meetshawn Why did you revert the patch?

**Comment by meetshawn** [comment]
@wf9a5m75 wrong person?

**Comment by wf9a5m75** [comment]
This is fixed perfectly in the v2-beta version.
**The plugin accepts `tilt:0`, but it's not equal with `Google Maps accepts tilt 0`.**
The plugin just passes the value to the Google Maps.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/ios/GoogleMaps/PluginMap.m#L311-L324

For the v2-beta, please read at here.
https://github.com/mapsplugin/v2.0-demo/
