### ISSUE TITLE
Extending Via LtLngBounds with animate causes strange animation

### ISSUE THREAD

**Issue by pmwisdom** [mapsplugin/cordova-plugin-googlemaps#971]
To preface this only happened when I upgraded to the latest version, this was coming from a pretty old version. 

When you use extendBounds with a array of LatLng's with animation set to true it will animate to the correct point and then "pop" back to the original position you came from. Without animation, this works correctly. I will try to find the commit that broke the animation.

**Comment by wf9a5m75** [comment]
Please provide the example code that reproduce your issue, and video capture also.

**Comment by pmwisdom** [comment]
I'll provide some example code, if it isn't apparent whats happening i'll try to get a video recording of my droid.

Tried to make this as PnP as possible.

````
var watchId = null;
var myMap = null;

const spaceNeedle = new plugin.google.maps.LatLng(47.620608, -122.349320);

//Variables to control our animation
var isAnimating = false;
var nextAnimationPoint = null;

//This is where we actually extend our camera bounds
function extendBounds(latlng) {
  const latLngBounds = [
    spaceNeedle,
    latlng
  ]

  const opts = {
    target : latLngBounds
  }

  //Set our animation control variable to true to block future animations
  isAnimating = true;

  myMap.animateCamera(opts, function() {
    //Set animating to false, since we have completed our camera animation
    isAnimating = false;

    //If we have a coordinate queued up, animate towards it.
    if(nextAnimationPoint) {
      extendBounds(nextAnimationPoint);
      nextAnimationPoint = null;
    }

  })
}

//Watch for position changes from GPS
function startWatch() {
  return navigator.geolocation.watchPosition(function(position) {
    const mLatLng = new plugin.google.maps.LatLng(position.coordinates.latitude, position.coordinates.longitude);

    //If were are already animating, don't interrupt the current animation, save it for later
    if(isAnimating) {
      nextAnimationPoint = mLatlng;
      return;
    }

    //Extend bounds
    extendBounds(mLatLng);
  });
}

function onMapReady() {
  watchId = startWatch();
}

myMap = plugin.google.maps.Map.getMap("#selector");
myMap.addEventListener(plugin.google.maps.MAP_READY, onMapReady)

````

**Comment by pmwisdom** [comment]
This commit works as expected:
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/8797668975a0676e934e69b756b3a81f291ad371

**Comment by pmwisdom** [comment]
More information, This only occurs on android.

**Comment by smcpjames** [comment]
Your device may be returning your location again before it's updated, and before the animation ends. In doing so, the next time extendBounds() runs, it'll animate you right back there. You may want to store the previous location returned, so that if the new location === previous location, it won't cue up that same location and make you jump back.

**Comment by pmwisdom** [comment]
@smcpjames  I have tried that as well as that was my thought to begin with, but to no avail. 

If I have an array of two points [[x1, y1], [x2, y2]] and set a timeout of 5 seconds in which we do latlng bounds extension it will still pop back and forth. I would expect if I extended by the same lat lng bounds x number of times, that it would only do the first animation to begin with.

This is not a problem with the code i've written, and I only say this with confidence because:

1. The problem does not occur on IOS with the same code.
2. The problem does not occur before the android lat lng bounds implementation was changed.

**Comment by pmwisdom** [comment]
I believe this is the same issue as this : https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/986

**Comment by kloppster** [comment]
Anyone have a fix for this? I am seeing this as well. Kind of ugly.

**Comment by rroque6428** [comment]
Yeah, any news about this issue? Really annoying bug.

**Comment by capitlux** [comment]
No work around for this issue ?
Thanks
