### ISSUE TITLE
How to hide directions button

### ISSUE THREAD

**Issue by R2D221** [mapsplugin/cordova-plugin-googlemaps#972]
Hi, I'm starting to use this plugin, and so far it works great. However, I've found something that apparently isn't documented anywhere.

When I tap on a marker, in the bottom right corner two buttons appear, one for opening the location in Google Maps, and the other one for getting directions (using Google Maps as well). Since I don't need these functions for the scope of my app, it would seem weird to leave them there.

Is there a way to hide them using the API, or is this function not implemented yet?

![screenshot_2016-05-18-14-07-47](https://cloud.githubusercontent.com/assets/774575/15372667/26d11b0e-1d07-11e6-8ee7-62b64861eabf.png)

**Comment by masashiGMS** [comment]
It comes from the Android API, not this plugin.

**Comment by R2D221** [comment]
I mean, yes, but I can also hide the current location using `setMyLocationEnabled(false)`, which is ultimately a function from the native plugin.

**Comment by roblav96** [comment]
This is a must, if possible please :) 

I'm going to try and switch my project from mapbox-gl-js to this plugin now that it supports ios wkwebview.

**Comment by smcpjames** [comment]
Since this function is easily enabled/disabled through the Google Maps Android API's UI settings, I went ahead and added it. Please see PR #983.

**Comment by roblav96** [comment]
@smcpjames I wub you =]

**Comment by Slavrix** [comment]
+1 for merge

**Comment by smcpjames** [comment]
@roblav96 @Slavrix If Masashi decides not to merge, you can try it from my repo: https://github.com/smcpjames/cordova-plugin-googlemaps/tree/master Just follow the install instructions under 'github' and substitute 'phonegap-googlemaps-plugin' for 'smcpjames'.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/983#issuecomment-223649572

**Comment by wf9a5m75** [comment]
Please use the v2-beta version.
In the v2-beta version, many bugs are fixed and some new options are implemented.
This request is also implemented.

https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/setOptions.html#L51

Read the description for the v2-beta.
https://github.com/mapsplugin/v2.0-demo/
