### ISSUE TITLE
map.setClickable(true) also disable touch/click on the element inside of the map_canvas

### ISSUE THREAD

**Issue by shahbazkhan054** [mapsplugin/cordova-plugin-googlemaps#974]
I am having one circle inside map_canvas div. I can fire click and pan event(pan using hammer.js) when map.setClickable(false). But when I set map.setClickable(true) the circle becomes non-clickable.
As per the documentation, the setClickable(ftrue) property only applies to the div present outside of map_canvas. How can I pan/drag the html element above the map. I think issue is before the pan event on html element, the camera_change event by native app is getting triggered. Please let me know of there is any workaround for both iOS and Android to pan/drag the html element above map.

**Comment by denkomanceski** [comment]
I think the thing is that this map calculates the clickable space dynamically, so after every move of your circle you need to call map.refreshLayout which I dont think is very light (performance wise) function. Also to check what is exactly happening you should use map.setDebuggable(true)

**Comment by wf9a5m75** [comment]
I'm not familiar with hammer.js, but it seems the hammer.js moves the dom position.
In that case, you need to call `map.refreshLayout()` everytime as @denkomanceski describes.

**Comment by amirul1000** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/class/Map/setClickable
