### ISSUE TITLE
is this the correct response from getLicenseInfo() ? Android 6.0.1 + Crosswalk

### ISSUE THREAD

**Issue by kshaaban-** [mapsplugin/cordova-plugin-googlemaps#975]
~~`getLicenseInfo()` is returning null / undefined to the callback params '(txt,txt2)' similar to the [documented example](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.getLicenseInfo()) for Android (6.0.1) on a Nexus 5.~~

~~Worth mentioning that I get correct license info when running on iOS.~~

Since that is no longer an issue, and I'm actually receiving test instead of null/defined. The returned text (6624 lines!) made me wonder of that's what I should be expecting:

[Gist of License info text](https://gist.github.com/kshaaban-/c1e02fe04f46393149ed79d828b150a0)

It lagged my android device when opened, especially when opened in a AlertDialog over the full screen map.

**Comment by kshaaban-** [comment]
Well , scratch that; it decided to work without me changing anything 🤔🤔🤔

**Comment by smcpjames** [comment]
That is the text you should expect. Your best bet will be to stick it somewhere other than a dialog - that control was never designed to handle this much text. Try overlaying a div with it, or something cleaner depending on your choice of UI toolkit.

**Comment by wf9a5m75** [comment]
It seems this is a bug of Google Play Services.
http://stackoverflow.com/questions/37273810/getopensourcesoftwarelicenseinfo-is-returning-null-now
