### ISSUE TITLE
Android 6.0 permission 

### ISSUE THREAD

**Issue by pmella16** [mapsplugin/cordova-plugin-googlemaps#981]
hi, i have this error in android 6.0 - unfortunately app has stoped. 
   java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.

i have this permission in manifest

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

outside of  < application> </ application>
any help ?﻿

**Comment by wf9a5m75** [comment]
Use the master branch.
