### ISSUE TITLE
plugin.google.maps.Geocoder - Completely Freezes JS/DOM Rendering

### ISSUE THREAD

**Issue by roblav96** [mapsplugin/cordova-plugin-googlemaps#982]
Example:
```javascript
	plugin.google.maps.Geocoder.geocode( {
		position: new plugin.google.maps.LatLng( cont.pos[ 1 ], cont.pos[ 0 ] )
	}, function ( response ) {
		if ( response[ 0 ] ) {
			let result = response[ 0 ]
			let address
			if ( _hasIn( result, 'extra.lines' ) ) {
				address = result.extra.lines.join( ", " )
			} else {
				address = [
					result.subThoroughfare || "",
					result.thoroughfare || "",
					result.locality || "",
					result.adminArea || "",
					result.postalCode || "",
					result.country || ""
				].join( ", " )
			}
			console.log( 'address >', address )
		}
	} )
```

From the time the function is called to the callback (~1500ms) the entire DOM tree is completely frozen and all client JS execution is halted.

Maybe this command should be using a background thread?

**Comment by Hirbod** [comment]
I guess your hint, using a background thread, should fix that. I will be back in about 10 days and help again on development. Had a lot private stuff to fix

**Comment by roblav96** [comment]
@Hirbod No worries man! Thanks so much =]

**Comment by wf9a5m75** [comment]
I added some code for the geocoding class of the Android.
Please reinstall the new master branch code.
