### ISSUE TITLE
[Android] Map.animateCamera Glitches At The End

### ISSUE THREAD

**Issue by roblav96** [mapsplugin/cordova-plugin-googlemaps#986]
[Map.animateCamera Example](https://vid.me/iYzd)

You can see at the very end the camera glitches inwards.

```javascript
let bounds = new plugin.google.maps.LatLngBounds( markers )
$map_map.animateCamera( {
	'target': bounds,
	'duration': 1000,
} )
```

**Comment by wf9a5m75** [comment]
Please check the code around here by yourself.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/PluginMap.java#L235-L311

**Comment by roblav96** [comment]
OK... It was just a bug report; How am I supposed to know you intended it to be this way.

If I were to take a guess as to why this is happening, I'd say `this.density` here:
```java
cameraUpdate = CameraUpdateFactory.newLatLngBounds(cameraBounds, (int)(20 * this.density));
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/PluginMap.java#L263

**Comment by roblav96** [comment]
Changing `(20 * this.density)` to `(1 * this.density)` removes the glitch at the end of the animation.

Can you please elaborate on why we do `(20 * this.density)`? Just for knowledge.

**Comment by masashiGMS** [comment]
The value `20` means the margin value.
But I got that why the camera bounds after the camera animation is finished.

The `finalCameraBounds` is the same as `cameraBounds`.
But in the code, I updated the camera target (cameraUpdate) after calculating the cameraBounds.

**Comment by roblav96** [comment]
Ah, that makes much more sense now. Thank you for the input!
