### ISSUE TITLE
[Android] Blank maps on release build, Fine on debug build

### ISSUE THREAD

**Issue by adyhp** [mapsplugin/cordova-plugin-googlemaps#987]
Hi guys, i have problem with blank maps when compiling in release build apk, it was fine when compiled in debug build, i have re-check everything, including the api key and registered apps name on dev console and nothing seems wrong, any ideas what i missed?﻿

**Comment by adyhp** [comment]
My bad, im signin my released apk with difference keystore, problem solved

**Comment by jlopez90** [comment]
Hi @adyhp I'm generating my private key like this: keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000 and then signing the apk(registered OK on dev console). I still have blank map. Any ideas?
