### ISSUE TITLE
Set html inside the map to not block touch 

### ISSUE THREAD

**Issue by Slavrix** [mapsplugin/cordova-plugin-googlemaps#989]
Getting HTML to display inside the map is easily done.
Is there a way currently to prevent the html added from blocking touch events to the map though?

I have a few buttons that Are fine to absorb the events, but i have a region which is an image overlay that I want users to be able to touch the map through.

It's a SVG (if that makes a difference)

**Comment by denkomanceski** [comment]
You should put that image (or whatever content it is that you want to work over the map) outside of the map tag and use absolute positioning to cover it over the map. I have a "marker" in the middle which is .png image and its put like this 

```
  <googlemap (draggf)="dragStart()"></googlemap>
  <div [ngStyle]="{'bottom': middleMarkerBottom}" *ngIf="clientService.appState.setPickupLocationPanel" class="sameAsRequest">
    <center>
      <img  *ngIf="!clientService.appState.pickupLocationChoosen" src="greenflag.png"/>
      <img  *ngIf="clientService.appState.pickupLocationChoosen" src="flag2.5.png"/>
    </center>
  </div>
```

what I am doing with ngStyle is calculating the bottom % based on the screen size so i will have the marker's bottom at the center of the map

You shouldnt have problems like this, I am able to touch over the marker (the image) and move the map
