### ISSUE TITLE
Move camera between targets 

### ISSUE THREAD

**Issue by denkomanceski** [mapsplugin/cordova-plugin-googlemaps#990]
Hi, I have quick question regarding moving the camera between two targets (in my case 2 markers). I have location A and location B. Everything works fine but the problem that I have couple of elements over the map which are around 35% from the screen (from the bottom to the top) and when I move between two markers, sometimes (depends on the location) the marker is hidden behind this content. Is there any workaround how can I force the camera use the space that is not covered. 

I know this is not easy but maybe I can add some more targets (which are not markers but just coordinates) to compensate for the space?

Here is a screenshot of what I exactly mean (http://prntscr.com/bctz2p). That marker that has blue square around is covered by the content. How do I make a padding or some idea that could solve this?

Thanks

**Comment by wf9a5m75** [comment]
For the purpose, you can use map.setPadding().

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.setPadding()

**Comment by denkomanceski** [comment]
Thanks. I solved it by doing this: I called map.setPadding with some parameters and than setTimeout to reset the paddings to 0 so image in the middle will actually be in the middle of the map. The timeout I added was 100ms in case someone helps this

**Comment by arielgelbard** [comment]
@denkomanceski can you please elaborate? I don't see any adjustment to the map when I go map.setPadding( 0,0,200,0 );

where does your setTimeout come in? example code?

**Comment by denkomanceski** [comment]
setPadding adds like virtual padding on the map, so the center will not really be in the center of the map but in the square that is set by the padding (If the padding is 0,0,0,0 that means that the padding is same as the map so the center is really in the center), but if you add padding, the map is still the same but the center is in the center of the virtual square formed by the padding, and the google maps logo also is positioned in the bottom of this virtual square (I think this picture that I made explains it better http://prntscr.com/clhryp)

**Comment by arielgelbard** [comment]
thanks @denkomanceski for the additional info, unfortunately the setPadding is still not working for me
