### ISSUE TITLE
Disable Scroll Gestures on Zoom

### ISSUE THREAD

**Issue by chadwhitaker** [mapsplugin/cordova-plugin-googlemaps#993]
It would be nice to discuss the need to implement the `allowScrollGesturesDuringRotateOrZoom` option for this library.

It appears this was [recently brought up](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/940), but I think this feature is highly desired by many in the community, especially for all the "on-demand, uber-like" applications being developed recently. It is important to lock the map center when zooming to prevent pin selection from moving several hundred meters.

Here is a quick example of the issue:
[![](https://cloud.githubusercontent.com/assets/433078/15937720/a64d910c-2e35-11e6-80d7-cdcd6101d052.jpg)](http://www.youtube.com/watch?v=U0J39ps_-bQ)

> In iOS, it's easy. You can just pass the boolean value to allowScrollGesturesDuringRotateOrZoom.
> https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/GoogleMapsViewController.m#L177-L200
> 
> In Android, it seems you can do with this:
> http://stackoverflow.com/a/32734436/697856
> 
> into here.
> https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L320

**Comment by morfeus929** [comment]
Any progress in this features?

**Comment by chadwhitaker** [comment]
@morfeus929 I was able to get everything working for iOS. I'm finishing up the Android implementation now. I'll post a link to the forked plugin after I'm finished.

**Comment by chadwhitaker** [comment]
@morfeus929 I created a forked version here: https://github.com/chadwhitaker/cordova-plugin-googlemaps

Please review the commits to see how to set the proper options. I'll admit that the Android version still requires a bit of polish, and I'm open to pull requests.
