### ISSUE TITLE
addMarker with visible false not working in iOS

### ISSUE THREAD

**Issue by Hyperonic** [mapsplugin/cordova-plugin-googlemaps#994]
```
map.addMarker({
                'position': position,
                'visible': false,
              });
```

this doesn't work in iOS. works in Android

**Comment by wf9a5m75** [comment]
I guess you use the npm version which is released 6 month ago.
Please use the master branch version instead.
(Next version is still under construction, sorry)

**Comment by Hyperonic** [comment]
using master branch

**Comment by thelightbird** [comment]
+1
Using master branch, i got the same issue (only in iOS)
It was working with the npm version

**Comment by wf9a5m75** [comment]
Use the plugin v2-beta version, plrase.

**Comment by pke** [comment]
@wf9a5m75 which branch world that be?  Can't see no v2-beta
