### ISSUE TITLE
Android: App Crashes immediately 

### ISSUE THREAD

**Issue by dbesiryan** [mapsplugin/cordova-plugin-googlemaps#995]
Hello dear developers and users. 
I am using this great plugin for about half a year to develop the IOS version of my ionic/Cordova App. But I tried really everything to let this plugin work for android. I followed the step-by-step guide several times -  	unfortunately without success.

The Android app crashes immediately as it starts.

No failure messages appear in my CLI.

Any ideas? maybe i forgot something? I also added any necessary settings in the google developer console.

I would be really thankful if anybody could help me to let my app work on android.

**Comment by jlopez90** [comment]
Try to update cordova platfom for android, it work for me. Btw I have iOS version working OK but on Android I have a Blank Screen-controls and Google logo appears-test it with&without crosswalk (all APIs enabled with the correct keys...)

**Comment by dbesiryan** [comment]
@jlopez90 thx for your help and information. I've considered your advice to update the cordova android version (current version: 5.1.1). Also I installed all mentioned SDKs and Tools. But when I try to build the android version it fails and I get the following message:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:23.0.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.0/support-v4-23.0.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.0/support-v4-23.0.0.aar
         file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/google/m2repository/com/android/support/support-v4/23.0.0/support-v4-23.0.0.pom
         file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/google/m2repository/com/android/support/support-v4/23.0.0/support-v4-23.0.0.aar
     Required by:
         :android:unspecified > com.google.android.gms:play-services-maps:9.0.2 > com.google.android.gms:play-services-basement:9.0.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I attached a screenshot of all installs from my SDK Manager. Any further ideas?
![screenshot sdk manager](https://cloud.githubusercontent.com/assets/12836628/16178532/4139aa44-364b-11e6-831b-ab4c311ef8b2.png)

**Comment by dbesiryan** [comment]
Updating Cordova Android to Version 5.1.1 AND Re-Install Android Support Repository by starting Android SDK Manager with sudo fixed my issue. The Plugin is now working well!! 
Thx again to @jlopez90 !

**Comment by jlopez90** [comment]
Nice! If you can make it work on Android real devices please let me know!

**Comment by dbesiryan** [comment]
I will try testing the plugin on a real android device in the next days and let you know if it works. Good luck in your own project @jlopez90

**Comment by dbesiryan** [comment]
ok, now i have tested the app on android device but i am facing a blank map (only google maps logo and controls visible). i checked my api keys again but it doesnt seem to work. do you have any idea @jlopez90?

**Comment by jlopez90** [comment]
I have the same problem on Android devices but its working ok on iOS

**Comment by wf9a5m75** [comment]
>only google maps logo and controls visible
This case is 99% your key is wrong.
The common reasons are
- you don't set be enabled to Google Maps API,
- you don't register your signature, or
- you register wrong signature or package.

At least you see the google maps logo, the plugin works correctly.

**Comment by dbesiryan** [comment]
it works now!! @jlopez90 I just deleted the app from my device, rebuild and installed it again- everything is fine and workin now :) 
give it a try by DELETING your app from the device FIRST (got this hint from another issue-discussion) 
Good luck and let me know if you can solve the problem.

**Comment by dbesiryan** [comment]
@jlopez90 okay, I realized that the map does not work if I close the app on device (close from app switcher) and restart it again. cleaning the cache when firing deviceready method completely solved my issue.
maybe you should give this plugin a chance, too:
https://www.npmjs.com/package/cordova-plugin-cache

**Comment by jlopez90** [comment]
thanks @dbesiryan I'll give a chance to this plugin. I'll let you know if this fixes the issue.

**Comment by dbesiryan** [comment]
@jlopez90 cleaning the cache did NOT fix them issue with blank screen. I found out, that setting a Timeout of 1000 milliseconds and create the map (with all your settings) AFTER is resolving all issues. You should try a setTimeout-Method! In my case, I always see the map can use it (even after relaunching the app) Good luck :)

**Comment by jlopez90** [comment]
thanks for your help @dbesiryan. I tried setting a timeout and nothing happens. Should be something related to the API key config. Are you using Ionic?

**Comment by dbesiryan** [comment]
yes, I am using Ionic with the newest version. you only need to get your android fingerprint (check the official tutorial for configuring android cordova google maps on the plugin github page) and set the required key in your google developer console. 
You should also check if your package name (look at the config.xml) is the same as in your developer console.

**Comment by dbesiryan** [comment]
Also, In my case I am using the google places JS library, too. That's why I also embedded the script src for google maps js api with places in my index.html.

**Comment by jlopez90** [comment]
I checked it several times haha.. the problem is that when I want to display the SHA1 fingerprint with keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android (because I'm Mac user) this debug.keystore doesn't exists. Do you know why?

Also I'm using this command to get my keystore to release Android app to the store:

keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000 as it is said in http://ionicframework.com/docs/guide/publishing.html

Thanks for your help @dbesiryan

**Comment by dbesiryan** [comment]
I am using the exact command as you posted to reveal my key. But I am able to get my SHA1 key after running the command in terminal - on OSX, too. I think this is your problem why your app does not run as expected... I would try to install the Android SDK and development environment once again

**Comment by jlopez90** [comment]
I've reinstalled Android Studio and the SDK via SDK Manager. What else I should do to set up the development environment?

**Comment by dbesiryan** [comment]
@jlopez90 did you set your JAVA HOME and Android Home Directory correctly in your bash_profile file?

**Comment by jlopez90** [comment]
@dbesiryan this is my bash_profile file:

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
export ANDROID_HOME=~/Library/Android/sdk
export PATH=${JAVA_HOME}/bin:$PATH
export PATH=${PATH}:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools

There is something wrong? SDK manager up to date and ant is installed also.
