### ISSUE TITLE
Show map zoomed in in existing pins

### ISSUE THREAD

**Issue by brisa-pedronetto** [mapsplugin/cordova-plugin-googlemaps#998]
Say I have 5 pins, all in Iceland. I'd like to open my map centered and zoomed in the region the pins are located. Does anyone have an idea how to implement this? 

Thank you!

**Comment by wf9a5m75** [comment]
You can pass an array of LatLng to the camera target property (with the master branch version).
For example, you can do this.

```js
var map = plugin.google.maps.getMap(div, {
  camera : {
    target: [
      {lat: ..., lng: ...},
      {lat: ..., lng: ...},
      {lat: ..., lng: ...},
      {lat: ..., lng: ...},
      {lat: ..., lng: ...}
    ]
  }
});
```

If you pass an array of LatLng to the target property, the zoom parameter is ignored, and zoom level will be set as automatically.

**Comment by brisa-pedronetto** [comment]
That's perfect, thank you so much!
