### ISSUE TITLE
[iOS] Polygon Click Event latLng returns undefined

### ISSUE THREAD

**Issue by roblav96** [mapsplugin/cordova-plugin-googlemaps#999]
Following the example provided in the documentation,
```javascript
map.addPolygon( {
	'points': [
		new plugin.google.maps.LatLng( 41.79883, 140.75675 ),
		new plugin.google.maps.LatLng( 41.79567, 140.75845 ),
		new plugin.google.maps.LatLng( 41.79576, 140.75475 ),
		new plugin.google.maps.LatLng( 41.79883, 140.75673 )
	],
	'strokeColor': '#AA00FF',
	'strokeWidth': 5,
	'fillColor': '#880000'
}, function ( polygon ) {
	polygon.on( plugin.google.maps.event.OVERLAY_CLICK, function ( overlay, latLng ) {
		console.log( 'latLng >', latLng ) // returns undefined :(
	} );
} );
```
On iOS `latLng` returns undefined 😢 

Plugin version installed from master branch.

Everything works properly on Android.

**Comment by wf9a5m75** [comment]
Is there any error log in native side?

**Comment by roblav96** [comment]
If by native logs you mean Xcode debugger, no there were not any errors.
![Xcode](https://s32.postimg.org/sx2nuvqw5/Screen_Shot_2016_06_15_at_1_30_55_PM.png)

**Comment by wf9a5m75** [comment]
Thank you for long-long-time waiting.
The current version does not implement this feature in the iOS code.
(Since I was tired at the time)

However the next version resolve this issue.
(I have been implementing this feature).

**Comment by wf9a5m75** [comment]
This is solved in the plugin v2 beta.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#version-2x-events
